### ISSUE TITLE
Maybe have a option to rename /TELEMETRY? Or option to rebroadcast /POWER during TELEPERIOD

### ISSUE THREAD

**Issue by Hogesyx** [arendst/Sonoff-Tasmota#10]
Currently I had TELEMETRY topic rename to RESULT, reason being is that my current program are coded in such a way that I use the same topic name for both feedback and periodically cross checking the status.

We could do that previously with Legacy Mode MessageFormat as the topic are rebroadcasted as /POWER. Would be nice if we have some options available so that people who uses the TELEMETRY the same way as me can have a easier time porting from MQTT-Arduino to Tasmota.

Alternatively, we can just abuse the single level wildcard of MQTT on the application side, but it might not be ideal for busy environment with many devices pumping to the same topic.

**Comment by arendst** [comment]
See #15
