### ISSUE TITLE
Feature Request: Advanced LED API

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#1000]
Thanks for the great work!

It would be really great if we could have an advanced LED API like the Yeelight for example:
http://led/cm?cmnd=Color%20FF0000&effect=smooth&duration=1000
http://led/cm?cmnd=Color%2000FF00&effect=sudden

This would bring the Sonoff Tasmota for LEDs on a whole other level since many effects and atmospheres can be implemented.

I know there are options to turn fading on/off and speed setting but it is not utilizable if you want to create a lightning experience.

This can be further improved with transitions and patterns.

I am issue #1000 yay

**Comment by stefanbode** [comment]
Have you checked the new option (5.3.0) to send: "Backlog". This allows putting several commands in row (max 16) and executes them with a predefined delay. This should allow the same as you have in ONE of the http requests above. https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by ageorgios** [comment]
I didn't know of this thanks!
