### ISSUE TITLE
Feature request: RF Bridge - unlimited (?) codes and possibility for full code manual input

### ISSUE THREAD

**Issue by sgofferj** [arendst/Sonoff-Tasmota#1001]
Similar to ESPurna, it would be nice if Tasmota would support an unlimited - or limited by available memory - amount of codes for sending and transmitting.

It would also be nice if it was possible to not only learn a code but also enter one manually. The latter would be useful for easy addition of code-learning devices which don't come with its own transmitter, such as RF alarm strobes, sirens, etc. One could simply make up a code oneself and let the device learn that. The input field should support the input of the full code - including the "house code" prefix where applicable.

A `cmnd/sendKey <full key data>` MQTT option would be the caking on the ice :)

**Comment by MatzeJoerling** [comment]
+1 
i would appreciate such a feature!

**Comment by arendst** [comment]
Implemented in master release v5.9.0

**Comment by Tresett** [comment]
Sorry for dummy question
Can I send this command from Domoticz via MQQT?
