### ISSUE TITLE
Sonoff dual, does not upgrade fw via web

### ISSUE THREAD

**Issue by Tresett** [arendst/Sonoff-Tasmota#1007]
Can't upgrade firmware on Sonoff Dual via web.

1. Working on ESPEasy. Download from github (Tasmota) already compiled sonoff.bin and try to update via webform. Failed and not back to ESPEasy firmware.
2. Ok. Compile Tasmota project in Arduino IDE, load firmware to device via serial port. All working.
3. Add few changes in Tasmota project (little changes un user_config.h), compile in Arduino IDE. Try to update fw via web. Failed and not back to working mode. Button not working too.
4. Today i'm try to upload fw via serial.

Do I smth wrong?

**Comment by Tresett** [comment]
TH16 has same problem
May be firmware is too big, for upload via web?
I'm purchase new chips for upgrare memory 1M->4M

Link to describe few hacks: https://www.jackenhack.com/sonoff-switch-i2c/

**Comment by davidelang** [comment]
did you try uploading the minimal version? it has most features disabled, but 
exists so that you can load it, and then load a larger image.

**Comment by Tresett** [comment]
Compile and upload minimum version. Suscesseful.
But in minimum version Web Management is off. 9-(
How to upload new firmware? OTA? I have not expireience to configure and start update OTA via MQQT =)

I'm disable all unneeded options, recompile it, new firmware is -20kb.
Upload successeful, I'm happy =)

P.S. But chips already purchased.

**Comment by Tresett** [comment]
Closed
