### ISSUE TITLE
Multiple DS18B20 extract data Hassio

### ISSUE THREAD

**Issue by vicok** [arendst/Sonoff-Tasmota#1009]
Hi...need some help. Installed an mqtt sensor Tasmota on D1 mini. Seems to transmit the status into Hassio. State shows {"Time":"2017-09-28T18:15:50", "DS18x20":{"DS1":{"Type":"DS18B20", "Address":"28FFDAE770170468", "Temperature":26.7}, "DS2":{"Type":"DS18B20", "Address":"28FFCEBA7017044E", "Temperature":27.9}}, "TempUnit":"C"}. What should I put into config.yaml to extract the temp values?
Can't get it working

**Comment by mkh595** [comment]
value_template: "{{ value_json.DS18x20.DS1.Temperature }}"

**Comment by vicok** [comment]
thx Piotr

2018-04-26 20:58 GMT+02:00 Piotr Oleszczyk <notifications@github.com>:

**Comment by ppnacho** [comment]
> Just in case you're like me and want to extract value by sensor address, e.g.:
> 
> `value_template: "{% for key, value in value_json.DS18x20.items() if value.Address == "28FFDAE770170468" %} {{ value.Temperature }} {% endfor %}"`

Hi, I have an error when I use your code, my config,

sensor hexid4:
  platform: mqtt
  name: "00000B10C80F Temperature"
  state_topic: "tele/pbaja1/SENSOR"
  unit_of_measurement: "°C"
  value_template: "{% for key, value in value_json.DS18B20.items() if value.Address == "00000B10C80F" %} {{ value.Temperature }} {% endfor %}"
  payload_available: "Online"
  payload_not_available: "Offline"

and the error,

can not read a block mapping entry; a multiline key may not be an implicit key 

Please, could you help me. Thanks
