### ISSUE TITLE
Sonoff POW MQTT interval

### ISSUE THREAD

**Issue by simonszu** [arendst/Sonoff-Tasmota#1010]
I have noticed that a Sonoff POW displays quite real-time measurements on its web frontend, but only sends the measurements to the MQTT in 5-minute-intervals. Is it possible to configure this interval to a shorter period?

**Comment by FitzJac** [comment]
With TelePeriod <sec> in the console, see [url]github.com/arendst/Sonoff-Tasmota/wiki/Commands#management[/url]

**Comment by simonszu** [comment]
Okay, thanks.
