### ISSUE TITLE
Sonoff Dual custom button - custom relay control?

### ISSUE THREAD

**Issue by mczac** [arendst/Sonoff-Tasmota#1011]
Hello, thanks for the great FW.

Where can I configure what relay external button control on Sonoff Dual? by default it's relay 1
Also is it possible to activate 2 relays from one external button in settings or I need to handle it with button topic and have the client activate both relays?

**Comment by ionciubotaru** [comment]
Define switch 1 - to toggle relay 1 and switch 2 - to toggle relay 2
By default swithc(x) tpggle relay(x) where x is between 1 to 4
