### ISSUE TITLE
Is it possible to add a ButtonMode command, same as SwitchMode?

### ISSUE THREAD

**Issue by calcipher49** [arendst/Sonoff-Tasmota#1017]
For now, it is possible to "disconnect" buttons from relays by defining a specific topic with ButtonTopic command.
However, the only message send to MQTT is 'TOGGLE' when button is pressed or released, similar to SwitchMode=0 for switches.
But for switches, we can change SwitchMode to 1 or 2, and then MQTT messages distinguish states ON and OFF.
It would be interesting to be able to do the same with the buttons, differentiate between states push and released.

Thanks for your great job...

**Comment by davidelang** [comment]
switchtopic is what makes switches send messages instead of changing relays

buttontopic does the same thing for buttons.

switchmode changes what messages are generated when the switch opens and closes, 
there is no equivalent for buttons.

**Comment by calcipher49** [comment]
You're right,
My question is precisely if it is possible to add the equivalent of switchMode for buttons.

**Comment by ionciubotaru** [comment]
Define a switch on the button pin and enjoy switchtopic

**Comment by calcipher49** [comment]
> Define a switch on the button pin and enjoy switchtopic
Sorry, do you explain how this can be done?

**Comment by ionciubotaru** [comment]
Read this: https://github.com/arendst/Sonoff-Tasmota/wiki/Adding-new-Module-types

**Comment by calcipher49** [comment]
Ok, thanks very much.
Replace GPIO_KEYx by GPIO_SWTx or GPIO_USER in sonoff_template.h should do the trick...

**Comment by sfanicola** [comment]
Sorry for asking on a closed issue, but could you explain me how to do the modification?
I'd like to set the GPIO0 button acting like a switch.
I tried to replace GPIO_KEY1 with GPIO_SWT1 but it doesn't work
