### ISSUE TITLE
Flash the sonoff switch with sonogf-tasmota, but it did not work after a 100 percent flash comoletion.

### ISSUE THREAD

**Issue by sumitrajancse** [arendst/Sonoff-Tasmota#1018]
The sonoff switch never turn back on. I tried two times with two different switch and both are now useless. 
Can you please suggest or advise what should be done to make switch work ?

**Comment by ionciubotaru** [comment]
read https://github.com/arendst/Sonoff-Tasmota/wiki/Upload
and take care of `Flash Mode: DOUT`

**Comment by sumitrajancse** [comment]
I did again... now it flashed.
When i connect to the power supply , led blinks and then stay constant then
after few seconds start blinking again
