### ISSUE TITLE
Patch for WPA2 vulnerability (Krack Attack)

### ISSUE THREAD

**Issue by mzealey** [arendst/Sonoff-Tasmota#1024]
As described in the [Krack attack website](https://www.krackattacks.com/) there has been a serious problem identified in WPA2 protocol on most all devices. I'm assuming ESP8266 wifi implementation is affected. There are some suggested [mitigations in the paper](https://papers.mathyvanhoef.com/ccs2017.pdf)

**Comment by g1r1** [comment]
+1. This is an issue, which needs to be handled.

**Comment by thayoz** [comment]
+1

**Comment by arendst** [comment]
See https://github.com/esp8266/Arduino/issues/3725
