### ISSUE TITLE
Sonfoff basic can't connect to MQTT broker as configured.

### ISSUE THREAD

**Issue by internetcontact** [arendst/Sonoff-Tasmota#1026]
I have MQTT broker running on Raspberry pi(static ip) and sonoff is configured to use this. All was working fine till I got new Roomba vacuum and setup on same wifi. Now sonoff is trying to connect to roomba instead of my broker on raspberry.

Sono
![capture3](https://user-images.githubusercontent.com/32808793/31629185-e574543a-b280-11e7-934a-36f7e5485008.PNG)
![capture1](https://user-images.githubusercontent.com/32808793/31629186-e58693d4-b280-11e7-866a-a98d74b84b44.PNG)
![capture2](https://user-images.githubusercontent.com/32808793/31629187-e5955a04-b280-11e7-8431-3e12afec6a5d.PNG)

**Comment by ionciubotaru** [comment]
on serial interface send this command `MqttHost 192.168.1.100`

**Comment by internetcontact** [comment]
I have already tried that. Also tried to flash a new sonoff, but same result. The things I don't understand is 
1. "MQTT service found on Roomba-3144460062428500, IP Address 192.168.1.11, Port 1883" - Rommba's ip address is not configured anywhere in sonoff still it finds that service and trying to connect to it.
2. even if I change the config for Mqtt host it don't use it and revert it back to roomba.

Thanks for helping.

**Comment by ionciubotaru** [comment]
add this line to user_config_override.h

`#undef USE_DISCOVERY                        // Disable Discovery services for both MQTT and web server`

**Comment by ionciubotaru** [comment]
and also send `reset 1` via serial or mqtt

**Comment by internetcontact** [comment]
Great advice. This is exactly what I was looking for. Thanks for quick response, saved me lot of time and headache.

I just disabled the MQTT_HOST_DISCOVERY.

**Comment by ionciubotaru** [comment]
@arendst please consider that MQTT DISCOVER should work only when MQTT HOST is empty

**Comment by arendst** [comment]
@ionciubotaru will be in next (pre)release

**Comment by Bedzaa** [comment]
> add this line to user_config_override.h
> 
> `#undef USE_DISCOVERY // Disable Discovery services for both MQTT and web server`

Hi, this is link to the same problem I have with Roomba. Could You explain a bit more "how to do that"? I am not that professional and I have no idea where can I find that file. Thanks a lot, Bedza
