### ISSUE TITLE
LED1 and LED1_INV missing

### ISSUE THREAD

**Issue by KPK75** [arendst/Sonoff-Tasmota#1029]
In the last "L" version you can't configure any GPIO as LED1 or LED1I if this LED is used in template.h
The same is for BUTTON1 and RELAY1.
Yes, I know "I can use WEMOS module and define GPIOs like ie. sonoff basic".
Is this by design ?

**Comment by arendst** [comment]
As the led has already been used in the template there is no physical way to connect it to another GPIO and therefore as designed.
