### ISSUE TITLE
wifi setting

### ISSUE THREAD

**Issue by marcgrc** [arendst/Sonoff-Tasmota#1038]
why after uploading the frimware the wifi settings remain the same ??
I tried many times but did not take the new wifi settings
Thanks for your help

**Comment by davidelang** [comment]
see the troubleshooting page on the wiki, in the section on configs

**Comment by ionciubotaru** [comment]
Change the value of 

`#define CFG_HOLDER             0x20170615`

and all saved setting will be reset to default

**Comment by marcgrc** [comment]
Thank you

Inviato da iPhone

Il giorno 21 ott 2017, alle ore 09:36, Ion <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Change the value of

#define CFG_HOLDER 0x20170615

and all saved setting will be reset to default

**Comment by pcopa** [comment]
Thanks @ionciubotaru , this solved my issue too
