### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ro-76** [arendst/Sonoff-Tasmota#1040]
Please be patient with a python newbie. I followed all the steps and installed the dependencies and requirements, but when I run the script I get this error:

File "./sonota.py", line 499
    print(".", end="", flush=True)
                  ^
SyntaxError: invalid syntax

Please help!

**Comment by ionciubotaru** [comment]
For sonota problems please post your issue [here](https://github.com/mirko/SonOTA/issues)
