### ISSUE TITLE
Feature Request: New SwitchTopic - Fallback from SwitchTopic 2 to SwitchTopic 0 when MQTT down

### ISSUE THREAD

**Issue by ajaypala** [arendst/Sonoff-Tasmota#1041]
I use SwitchTopic 2 to trigger various lights in the room which may or may not include the local relay. However if the MQTT or Wifi is down for whatever reason, all the switches stop working, hence I thought it would be a good idea for it to temporarily revert to SwitchTopic 0 while MQTT is down.

**Comment by ionciubotaru** [comment]
It is very dangerous to change the way a device act. Wifi and mqtt can disconnect for a short period (less than 1 second) if the user press the button lots of unexpected actions can happened.

Better try to have a good wifi coverage and a reliable mqtt server
