### ISSUE TITLE
Add VEML6070 support

### ISSUE THREAD

**Issue by pascalsaul** [arendst/Sonoff-Tasmota#1053]
See: https://learn.adafruit.com/adafruit-veml6070-uv-light-sensor-breakout/wiring-and-test

stat/th_mv/RESULT {"I2CScan":"Device(s) found at 0x38 0x39"}

**Comment by arendst** [comment]
In next (pre)release as an option in user_config.h (adds 0.5k code).

**Comment by pascalsaul** [comment]
Quick! Looking forward to it :)

**Comment by arendst** [comment]
Implemented in master release v5.9.0
