### ISSUE TITLE
PL-PL result toogle ON/OFF adding to pl-PL.h where ?

### ISSUE THREAD

**Issue by roblad** [arendst/Sonoff-Tasmota#1057]
Hi,

I have one problem with translation, toogle switch on web main page shows ON/OFF, is it possible to add to translate file that result for future update i.e. ON=WL  OFF=WYL

Regards,
RL

**Comment by arendst** [comment]
See the header ATTENTION notes in the language file. 

You will need to use online command ``StateText`` to translate ON, OFF, HOLD and TOGGLE

**Comment by roblad** [comment]
Hi,

Haw to do it ?
