### ISSUE TITLE
Pulsetime

### ISSUE THREAD

**Issue by aferraz** [arendst/Sonoff-Tasmota#106]
Hi @arendst,
 it's possile to add Pulsetime for relay2 ?

Thank you and Best Regards
Alessandro

**Comment by aferraz** [comment]
Hi @arendst,
 any news on this ? are you going to implement it ?

Thanks
 Alessandro

**Comment by rayzor666** [comment]
I to would find this useful.. I'm currently using a sonoff to activate a timed relay to control a motor that opens and closes my blinds...

**Comment by aferraz** [comment]
Thank @arendst you are great

**Comment by off14** [comment]
how pulsetime works, if configured?

**Comment by davidelang** [comment]
when you turn a relay on, it will turn off pulsetime seconds later.
kk

**Comment by off14** [comment]
Thanks! so , no need for openhab/3rdparty system to trigger and controll OFF after ON.
great thing to manage "stupid" blind controller.
