### ISSUE TITLE
v.5.8.0.n Problem with compilation

### ISSUE THREAD

**Issue by Greg2002** [arendst/Sonoff-Tasmota#1062]
v.5.8.0.n Problem with compilation - Error in xdrv_ir_send.ino
(possible a new version of lib IRremote8266)
You have to replace <ir_Mitsubishi.h> // <IRMitsubishiAC.h>
and declare 
#include <IRsend.h>
#include <IRrecv.h>

**Comment by arendst** [comment]
Only the provided libraries are supported as the newer ones are just taking up precious code space without additional, by tasmota supported functionality.
