### ISSUE TITLE
Calendar for relay control - scheduler ON/OFF

### ISSUE THREAD

**Issue by roblad** [arendst/Sonoff-Tasmota#1063]
Hi,

What do you think about implementation of scheduler and calendar to tasmota ?
And ON/OFF when some sensor wil got a value thereshold ?
Rds,
RL

**Comment by davidelang** [comment]
I think that's overreach, Tasmota is about giving you control of relays/sensors 
not being an automation in itself

**Comment by ionciubotaru** [comment]
do it from your HA software
