### ISSUE TITLE
GPIO14-Switch

### ISSUE THREAD

**Issue by mittelfeldmotor** [arendst/Sonoff-Tasmota#1068]
I configured a sonoff basic with gpio14 as switch01. It works, but wenn i turn the switch off for longer time, the sonoff needs few seconds to toggle. Is this normal?

**Comment by Gompka** [comment]
I have experienced the same issue, it seems like the sonoff takes a moment to wake up and actually turn on my light.

**Comment by jetema** [comment]
Have a look at "PulseTime" command, see if its value is zero or not

**Comment by mittelfeldmotor** [comment]
where?

**Comment by mittelfeldmotor** [comment]
can I find it

**Comment by mittelfeldmotor** [comment]
found it. It´s zero

**Comment by Gompka** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands    

You can enter the commands in the console on the webpage of your sonoff. 

Jesus, mine is set to 0, i am using the switch as a wall switch not a momentary.

**Comment by mittelfeldmotor** [comment]
Same here

**Comment by jetema** [comment]
Have you Tasmota 5.8.0 or older versions ?

**Comment by mittelfeldmotor** [comment]
5.4.0

**Comment by jetema** [comment]
If so try a older one, you have all versions available on 
https://github.com/arendst/Sonoff-Tasmota/releases

**Comment by Gompka** [comment]
I am on version 4.0.5

**Comment by jetema** [comment]
Try to update to 5.8.0 via OTA, is quick and easy

**Comment by Gompka** [comment]
I tried updating, but it doesn't want to take, even with use_minimal uncommitted. I will try to do it one more time and if not ota will flash manually and report the results.

**Comment by jetema** [comment]
There are two methods to update, the easiest one is updating by file upload, select  sonoff.bin  ( NOT minimal )

**Comment by mittelfeldmotor** [comment]
Update minimal finished, nut now sonoff is not reachable in wlan

**Comment by mittelfeldmotor** [comment]
I tried https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage to config the wlan, but no chance, I think I should reflash

**Comment by Gompka** [comment]
I upgraded to the latest version of tasmota and so far i have not experienced any delays with the external switch. I will check again today after work to make sure, but i think that was my issue.

**Comment by mittelfeldmotor** [comment]
Upgrade to latest Version solved the problem for me

**Comment by joaohess** [comment]
I'm up-to-date and I still get the problem. Using Sonoff basic to control the lights of my home using a wall switch on GPIO14/Ground. Sometimes it takes up to 10 seconds to turn on/off the lights. Anyone knows what can it be?

**Comment by davidelang** [comment]
probably because you are having network connectivity issues.

There is a bug in the arduino network library that means that while the device 
is attempting to connect to a mqtt server, nothing at all can happen.
