### ISSUE TITLE
SwitchMode question

### ISSUE THREAD

**Issue by roblad** [arendst/Sonoff-Tasmota#1069]
Hi,

Is it possible to change SwitchMode from 1 that is default to SwitchMode to value 2 somewhere in config or source code ? I need SwitchMode 2 by default.

Thanks
RL

**Comment by davidelang** [comment]
see user_config.h

**Comment by roblad** [comment]
ok,

what is a parameter ?

**Comment by jhlweb** [comment]
around line 154
`#define SWITCH_MODE            TOGGLE            // [SwitchMode] TOGGLE, FOLLOW, FOLLOW_INV, 
PUSHBUTTON, PUSHBUTTON_INV, PUSHBUTTONHOLD or PUSHBUTTONHOLD_INV (the wall switch state)`

**Comment by roblad** [comment]
Hi

Smitchmoe1 2
Switchmode2 2

through conslole MQTT solved that, but haw to do it in config, there is a question ?

Regards,
RL

**Comment by roblad** [comment]
SWITCH_MODE1 TOGGLE
SWITCH_MODE2 TOGGLE

???

**Comment by jhlweb** [comment]
@roblad, maybe your should type a bit more text with your comments to make clear what you want.
