### ISSUE TITLE
identify which gpio is default for sensors on th

### ISSUE THREAD

**Issue by davidelang** [arendst/Sonoff-Tasmota#107]
using the th series deivces, the built-in sensor port is gpio14, but once you select the th series, you are presented with three gpios to configure, without any indication as to which is which.

It would be very useful to be able to identify which one is the default sensor port on the th series when it's selected.

**Comment by arendst** [comment]
As you know, gpio14 is the default port.

As some want to add extra hardware for gpio04 it is also available for use.  Gpio03 is always available on the serial port.

As I get requests from those only wanting to see easily available gpios while others want to see all gpios I have to make decisions about useability and code size.

Explaining gpios hs no priority for me. You can always edit sonoff_template.h and remove the ones you do not want to see.

**Comment by davidelang** [comment]
I found that it was port 14 by looking at the prior repo. I couldn't find the 
info anywhere in the wiki (I may have missed it)

I agree that they should all be shown (in fact, I think there should probably be 
more GPIO_USER entries)

I'm just thinking that there should be an ability to add a comment to a template 
to be displayed on the configuration page.

is it reasonable to add this to the datastructure holding the GPIO defs? or 
would it need to be a separate array like you have for user defined functions 
and their descriptions?

**Comment by arendst** [comment]
I'm running out of memory and have to choose between features or descriptions. Currently there is just 4k left...

**Comment by davidelang** [comment]
would you accept a patch that was protected by ifdefs?

**Comment by arendst** [comment]
give it a try

**Comment by arendst** [comment]
Will implement some text to well known GPIOS like **GPIO14** = TH Default in next version.
