### ISSUE TITLE
Wifi settings not saved

### ISSUE THREAD

**Issue by mittelfeldmotor** [arendst/Sonoff-Tasmota#1075]
I udated a sonoff with newest minimal.bin
I Start the wifi accesspoint and scan wifi. After set password the sonoff restarts, but doesnt connect to wifi. Any auggestions?

**Comment by davidelang** [comment]
flash the device with a full version, minimal only exists to let you flash a 
larger image, that's why it doesn't let you save any settings.

**Comment by mittelfeldmotor** [comment]
That was it
Thanks
