### ISSUE TITLE
How to see all possible networks with RSSI information?

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#1080]
I have some Fritz Repeater in my home repeating the SAME WLAN SSID. would be great to have a "scan" function with SSID and MAC-Adress and RSSI to see which repeaters are nearby and how clear is the signal. I assume that on connection the internal procedures will always use the strongest network on reboot/reconnect when finding more than one network with the same name. 

Thanks for sharing more information.

**Comment by jetema** [comment]
There's a scan function via web, hope it helps 
![image](https://user-images.githubusercontent.com/30664452/32111892-23da33e8-bb3c-11e7-88bb-55aaec3665f6.png)

**Comment by stefanbode** [comment]
No, this neither show the MAC-Address, nor does it show SSID that where broadcasted by more than one repeater. In this case the Ssid is the same and the MaC is different.

**Comment by stefanbode** [comment]
There is a hard-coded option to enable/disable this in webserver.ino

`boolean remove_duplicate_access_points = false;`

Good to know.
