### ISSUE TITLE
Restet on Power Toggle on 1 Channel Inching /self-locking Switch

### ISSUE THREAD

**Issue by jchmielniak** [arendst/Sonoff-Tasmota#1086]
After sending Power On or Power Toggle to 1 Channel Inching / Self-locking Switch in Inching Mode, the switch goes to WiFi Config Mode. In Self-Locking Mode all works correctly.
Version 5.8.0p.
Log from MQTT:

stat/sonoff05/RESULT {"POWER":"ON"}
stat/sonoff05/POWER ON
stat/sonoff05/RESULT {"POWER":"OFF"}
stat/sonoff05/POWER OFF
stat/sonoff05/RESULT {"WifiConfig":"SmartConfig selected"}
tele/sonoff05/LWT Online
cmnd/sonoff05/POWER (null)
tele/sonoff05/INFO1 {"Module":"1 Channel", "Version":"5.8.0p", "FallbackTopic":"DVES_84F420", "GroupTopic":"sonoffs"}
tele/sonoff05/INFO2 {"WebServerMode":"Admin", "Hostname":"sonoff05", "IPAddress":"192.168.X.X"}
tele/sonoff05/INFO3 {"RestartReason":"Software/System restart"}
stat/sonoff05/RESULT {"POWER":"OFF"}

**Comment by armdan** [comment]
I see this is an old post but what is the solution for this problem
