### ISSUE TITLE
Disconnect wifi connection, the relay gpio0 automatically open!

### ISSUE THREAD

**Issue by 1043717432** [arendst/Sonoff-Tasmota#1094]
hi, the use of firmware set switch, when wifi power, call again connected wifi, relay gpio0 location automatically turn on the lights, any firmware test will have such a problem, how to solve it?

**Comment by davidelang** [comment]
turn on logging to more detail and see what is actually happening. I wouldn't be 
surprised if you have some messae retain problems (see the poweronstate page on 
the wiki)
