### ISSUE TITLE
BMP_ADDR hardwired to 0x77

### ISSUE THREAD

**Issue by mihalski** [arendst/Sonoff-Tasmota#11]
Many of the modules available from eBay and AliExpress (and elsewhere) use 0x76 instead. If Tasmota could recognise the BMP280 with either of these 2 addresses that would be ideal.

Thank you for an INCREDIBLE piece of software that just keeps getting better and better :)

Regards,
Michal

**Comment by arendst** [comment]
Give it a try and see what happens...

**Comment by mihalski** [comment]
Doh!

Totally missed the bmpaddr--

Works perfectly. Thank you :)
