### ISSUE TITLE
Sonoff Pow don't remember „Today” kWh after power loss

### ISSUE THREAD

**Issue by MacWyznawca** [arendst/Sonoff-Tasmota#110]
After turning off the power to the module and then power on the data of „today's” power consumption are reset, data „yesterday” are ok.

Version 3.9.19, 3.9.17

**Comment by jaysuk** [comment]
That's normal. If Theo kept saving the results to flash, it would kill your
ESP fairly quickly.
You need to use an external system to save your power usage.

**Comment by MacWyznawca** [comment]
OK! Perhaps UPS will be a good solution :-)
