### ISSUE TITLE
Sonoff 4ch controlled by wall switch

### ISSUE THREAD

**Issue by firefighter0112** [arendst/Sonoff-Tasmota#1100]
Hello,

i have a little problem. Is installed a Sonoff 4ch flashed with Tasmota FW. Everything work fine. Now I want to control the sonoff with the wall switches. I have 3 lights and every light controlled by 2 wall switches. I use GPIO01, GPIO02 and GPIO03 to connect the switches to sonoff. First I connected the first 2 switches and everything worked fine! Connect the next 2 switches also everything worked fine. After I connected the last 2 switches all worked. But than son off turns off and now its dead.. Whats the problem? There is no voltage at the switch cables. Its only open or close..

**Comment by ionciubotaru** [comment]
First- disable serial log because you use gpio1 and 3 as input pins
Second GPIO2 si as important as GPIO0 for boot process - better use other pin
