### ISSUE TITLE
Shrink code

### ISSUE THREAD

**Issue by ionciubotaru** [arendst/Sonoff-Tasmota#1104]
Replace

`void MqttPublishPrefixTopic_P(uint8_t prefix, const char* subtopic, boolean retained)`

with 

`void MqttPublishPrefixTopic_P(uint8_t prefix, const char* subtopic, boolean retained=false)`

then delete

```
void MqttPublishPrefixTopic_P(uint8_t prefix, const char* subtopic)
{
  MqttPublishPrefixTopic_P(prefix, subtopic, false);
}
```

you will save 48 bytes

**Comment by arendst** [comment]
Just for fun I tried it and came up with different results.

Arduino IDE 1.8.1 and esp core 2.3.0 +32 bytes more (!?!)
(VisualStudioCode)PlatformIo and esp core 2.3.0 +48 bytes more (!?!)

So please tell me what great compiler you used to get 48 bytes less

**Comment by ionciubotaru** [comment]
That's true, sorry, my mistake.
