### ISSUE TITLE
GHBO1/SHBO1 temperature and level sensor for solar water heaters

### ISSUE THREAD

**Issue by gelitoam** [arendst/Sonoff-Tasmota#1113]
Hello.

After installing Tasmota/Sonoff in lights and humidity control (works fine, thank you), I'm trying to integrate my solar water heater into Domoticz connecting its level/temp sensor (GHBO1/SHBO1) to a Sonoff switch (which would turn on the auxiliary electric heater when needed).

The sensor's protocol was analyzed yet by someone here: http://hack4life.pbworks.com/w/page/75653090/Arduino%20Solar%20Water%20Heater%20Sensor

There is also some code there to read the sensor with Arduino, but I don't know how to use all that info to make Sonoff read the sensor and send the values to Domoticz.

Would you kindly help a domotic newbie with this? It would be quite useful having temperature data and  graphics for dynamic fine-tuning of the solar heater.

Best regards.

**Comment by aamxxx** [comment]
Any idea? I can understand how the Arduino code from the link works, but don't know how to insert it in the firmware to work with Sonoff.

Sorry for the insistence, I'm very interested in getting heater's data to adjust it before Winter comes.

**Comment by aamxxx** [comment]
Got an Arduino and managed to read temperature and level values from sensor via serial port, but I don't know how to make Sonoff to do the same.

Anybody can give me an idea about how to do it, please? Maybe modifying the existing temperature/humidity sensor? What files do I have to modify?

Best regards.
