### ISSUE TITLE
Any update on Sonoff SC support?

### ISSUE THREAD

**Issue by KonstantinMastak** [arendst/Sonoff-Tasmota#112]
Do you have plans to add Sonoff SC support, and how fast can this happen? Thank you!

**Comment by jaysuk** [comment]
Try this in the interim.

https://github.com/xoseperez/sonoffsc

**Comment by KonstantinMastak** [comment]
I know about this projects, thank you! Just wanted to have something like "All Sonoff in one firmware", e.i. was looking for a merge between these two projects, to leverage all avaliable features of both.

**Comment by arendst** [comment]
It'll take at least a month as I still haven't received my SC

**Comment by KonstantinMastak** [comment]
Thank you! It's great that you have it in short plans. Hope you'll receive your SC soon.

**Comment by khcnz** [comment]
@arendst have you received your SC? I have one and happy to start looking at it to give you a headstart. There is some good starting information here as well http://tinkerman.cat/sonoff-sc-with-mqtt-and-domoticz-support/

**Comment by arendst** [comment]
Nope, still waiting for it to be send so add another month...

**Comment by arendst** [comment]
Initial support in next release
