### ISSUE TITLE
Sonoff Phantom switch Relay is active without use?

### ISSUE THREAD

**Issue by freaktech** [arendst/Sonoff-Tasmota#1120]
hi

sorry for the silly question but my english is not the best and i am not sure how secure this system is.

i want to switch a door.

So is it possible that the Relay switch  if you have not pressed a key ?
sometimes? after some days, after a reboot when there was a blackout.

this is not so important when you switch a lamp but when you switch a door it could be big problem.

anyone have made a bad  experience with this?

 thank you

tom

**Comment by ionciubotaru** [comment]
If your relay is ON and ESP restarts it is a short OFF / ON toggle
Here is a similar problem https://github.com/arendst/Sonoff-Tasmota/issues/1097
