### ISSUE TITLE
Not Responding to Alexa

### ISSUE THREAD

**Issue by mB-PiBox** [arendst/Sonoff-Tasmota#1122]
Alexa/Echo is able to Discover the sonoff, but it doesn't respond.

If I ask Alexa to turn ON or OFF the device, I get the response back "Sonoff Isn't Responding"

**Comment by zerog2k** [comment]
Do you have it set to wemo or hue emulation?

I am not able to get my echo pro to discover my tasmota device in wemo emulation, but works with hue emulation with a caveat: turning on device from echo results in the device turning on but alexa saying something about not responding. When I turn off the device through echo this works as expected with Alexa responding with OK.

**Comment by mB-PiBox** [comment]
1. There is no "Echo Pro."
2. I have them all set to WeMo

**Comment by zerog2k** [comment]
Sorry it was late when posting. It’s echo plus.

**Comment by Alveran81** [comment]
I have a Echo Plus and Echo Dot. My Echo Plus can not find or switch wemo device. When I switch Echo Plus off my echo dot can find and switch wemo devices.

**Comment by zerog2k** [comment]
Not sure at what point this was fixed, but it seems to be reliably working for me for past few months... Something may have been fixed at some point
