### ISSUE TITLE
Having difficulty installing/configuring Arduino IDE

### ISSUE THREAD

**Issue by mamvcivm** [arendst/Sonoff-Tasmota#1127]
Hi, I'm using Windows 10 64 bit. I'm finding the Github instructions unclear (https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE) - or maybe I'm being pedantic - wouldn't be the first time!

Under the section **Install Arduino IDE** it says create a _known folder_ (I've called it Arduino) and unzip the Arduino zip to it, this creates a folder called _C:\Arduino\Arduino-1.8.5_. It then says create a folder called _portable_ in the known folder (_C:\Arduino_), but I believe this should actually be under _C:\Arduino\Arduino-1.8.5_. Only when Arduino is then run for the first time does the _portable_ folder get populated. However, the next step is to copy an ld file to _portable\packages\esp8266\hardware\esp8266\2.3.0\tools\sdk\ld_, but this folder doesn't exist - should I create that whole tree?

The only subfolder that exists at this point is _C:\Arduino\arduino-1.8.5\portable\sketchbook\libraries_

In the **Configure Arduino IDE** section, it says 

Replace in Arduino IDE folder _portable\packages\esp8266\hardware\esp8266\2.3.0 file boards.txt ...._

But again, that folder tree doesn't yet exist

Can you please advise where I'm going wrong here?

Thanks,

Andrew

**Comment by arendst** [comment]
Continuewith the ide parameters first which will install the directory tree you need.
