### ISSUE TITLE
Feature: Xenon 3 gang US Light Switch

### ISSUE THREAD

**Issue by kierenblack** [arendst/Sonoff-Tasmota#1128]
I have finally got the Xenon 3CH WIFI US switch working on Tasmota. If someone can add it to the code that would be awesome. They are the US size, not the UK which is why I wanted it to work. 

`{ "Xenon 3CH",      // Xenon 3CH (ESP8266)
    0,0,0,
    GPIO_KEY2,        // GPIO03 Serial TXD and Optional sensor
    GPIO_REL2,        // GPIO04 Relay 2
    GPIO_KEY3,        // GPIO05 Input 2
    0, 0, 0,          // Flash connection
    0,
    0,
    0,
    GPIO_KEY1,        // GPIO12 Key input
    GPIO_REL1,        // GPIO13 Relay 1
    0,
    GPIO_REL3,        // GPIO14 Relay 3
    0, 0
  }`

I also had to add XENON3 after WITTY to make it work.

**Comment by davidelang** [comment]
Is there a reason you can't just use the generic wemo and  define the 
appropriate GPIOs?

**Comment by kezzab25** [comment]
I could but would it not be good to have there so that others can use it
without having to try and work out the GPIO's?

**Comment by davidelang** [comment]
only if it's common enough, we are short of space and so having definitions for 
every device out there is unaffordable.

document what's needed on the wiki, complete with pictures so that other people 
can use it easily

**Comment by CZ1979** [comment]
@kezzab25 : Im really interested in how you flashed your Xenon switch! Which pins did you used? Which tool and which configuration? Maybe you have a picture of your device?

**Comment by webtop** [comment]
@kezzab25 I also would be interested in seeing a Wiki page on how you did this.

**Comment by kezzab25** [comment]
I will post some images and how I did everything this weekend.
Unfortunately I am busy at work during the week.

**Comment by hahmann** [comment]
I'm curious as well on how you did it @kezzab25 . Havent tried to remove the ESP12F module though, it seems the easiest option to me now. Will be really awesome if you can post some pictures on how you manage to wire it and upload the code. Thanks.

**Comment by kezzab25** [comment]
I would have to dismantle it which is a bit more difficult now. I soldered
wires directly onto the esp module and did it that way. I noticed sonoff
have just released a 3 gang light switch for the US so that might be a
better option

**Comment by hahmann** [comment]
Having wires soldered into the board directly is not working, some of the pins fluctuate and the espcomm_sync/open/upload failed, maybe due to the other components on the board. Serial is working as in normal operation I see messages coming on it. Did you had the same issue?

**Comment by kezzab25** [comment]
Did you remember to hold GPIO0 low on power up?
