### ISSUE TITLE
Want to use GPIO 3 (RXD) on Sonoff Dual

### ISSUE THREAD

**Issue by WollZender** [arendst/Sonoff-Tasmota#1129]
Hello,

I hope somebody can help me.

I try to use GPIO3 (RXD) and GPIO13 (blue LED) as Input for two wall Switches. I don't want using GPIO 4/14, because it is difficult to connect a switch there. I removed the blue LED an connect a Switch to GPIO13. This works properly, but with a switch at GPIO3 nothing happens when I toggle the switch. I already disabled serial logging.

I know that the relays will toggled by the TXD (GPIO1) pin.

Somebody knows what I'm doing wrong?

many thanks

WollZender

**Comment by davidelang** [comment]
you cannot use GPIO3 on the dual because that is how the dual controls the 
relays, it's not just the tx pin.

**Comment by WollZender** [comment]
I also disconnected the RX between its pin and resistor R10 and it still works. The RX pin now is only connected to GPIO3. Is it possible to use only GPIO1 for sending?

**Comment by davidelang** [comment]
not with the stock serial library, it claims both GPIOs

**Comment by WollZender** [comment]
Is it possible to tell the library e.g. GPIO4 as serial Input?

Thanks for your reply.

**Comment by davidelang** [comment]
no, the hardware has a single serial port, you can't use any other ports for the 
serial port.

**Comment by WollZender** [comment]
Thank you for pointing me in the right direction.

I now just open the serial port to send the relay command. After that I close the port to use GPIO3 as Input.

This works properly.
