### ISSUE TITLE
SR04 Ultrasonic sensor support?

### ISSUE THREAD

**Issue by Killobite** [arendst/Sonoff-Tasmota#113]
First off, fantastic firmware!  I have installed this firmware on more than 20 Sonoffs and am really appreciating the capabilities and attention to detail!

I do find that I would really like to add the use of a SR04 distance sensor for one of my implementation and am wondering if there may be any plan or ideas on how to do so?

Thanks!

**Comment by arendst** [comment]
The SR04 needs 5V. Sonoff can only supply 3V3. Do you expect the SR04 to work reliably on 3V3?

**Comment by AlexTransit** [comment]
Sonoff basic - use 2 power
5v - via trancformater (power relay)
3.3v - afrer stabiliser

**Comment by Killobite** [comment]
I will actually be using it with a Wemos D Mini and can take the 5V right off the VCC pin.  I have a mock up working with 3.9.21 and just threw the sonar code in the void loop and sent the output to serial.  I started to dig into an "easy" way to publish the distance into MQTT but that's when I thought I would reach out and see if anybody has any plan/code on it. I had to put a little millis delay in to get it to read correctly and only report out if the distant changes by more than 10 inches but it works reliably, I just have to figure out hot to make it pretty for the web interface and MQTT output.

My use case is a garage door control with open/closed (distance) indicator and a sump pump monitor/override with water level (distance) logging.

Here is my simple loop code in case you are interested:
if (millis() >= lMillis + 250) {

      lMillis = millis();
      sDistNew = Ultrasonic.distanceRead(INC);
    
      if (sDistNew > sDist + 10 ){
        sDist = sDistNew;
        Serial.print("Distance in Inches: ");
        // Pass INC as a parameter to get the distance in inches
        Serial.println(sDist);
        //delay(1000);
      }
      else{
          if (sDistNew < sDist - 10 ){
          sDist = sDistNew;
          Serial.print("Distance in Inches: ");
          // Pass INC as a parameter to get the distance in inches
          Serial.println(sDist);
          //delay(1000);
      }
     }
}

**Comment by f0m3** [comment]
Thats a cool idea. Id like to use the sonoff dual for my garage door control but id like to know if it is open or closed too...

**Comment by hamwong** [comment]
Wish SR04/05 will support in sonoff, power should not be the reason make SR04 not add as SR501 also use 5V

**Comment by quadflight** [comment]
Great idea. Did you get it to work?

**Comment by BernardLaurenzo** [comment]
The sonoff dev board has 5v 
Im currently running my SR04 and sonoff dev with ESP easy firmware

**Comment by jetema** [comment]
![3inferior](https://user-images.githubusercontent.com/30664452/32017768-11c9c9fe-b9c8-11e7-96e6-e8e1225702da.jpg)

Yes, 5 volts are available on D5 ( zenner diode ) terminals, you can get a few extra mA from this point to supply SR04

**Comment by Gompka** [comment]
You can also use this sensor [https://www.bananarobotics.com/shop/US-100-Ultrasonic-Distance-Sensor-Module](url) as it runs on 3.3v

**Comment by nosaj66au** [comment]
Hi Guys,
  has this gone any further I required it for rain water tank level

Jason

**Comment by fragolinux** [comment]
HC-SR04P can can work at 3.3V, you can recognize it because usually is blue as the other model, but has NO crystal oscillator on the front panel, look at image
![s-l300](https://user-images.githubusercontent.com/21192010/39438356-3088987e-4ca4-11e8-851a-6c861a313ab0.jpg)

**Comment by scottchristian** [comment]
I'm going to throw my request for this as well.
Would be very nifty

**Comment by Frogmore42** [comment]
Well you are in luck.
https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-HC-SR04-Ultrasonic-Sensor

**Comment by ascillato** [comment]
Now it is implemented. Closing.

**Comment by Gompka** [comment]
C.f. gtcy

**Comment by ascillato** [comment]
?

**Comment by Gompka** [comment]
Yea it does, I have been using it for over a year.

**Comment by rajil** [comment]
@Gompka I tried to use PingSerial library with US-100 but that did not [work](https://github.com/stoduk/PingSerial/issues/6). Do you have any example code which works on nodemcu?

**Comment by Gompka** [comment]
@rajil, did you make sure the jumper on the back of the us-100 is in the correct position?

**Comment by rajil** [comment]
@Gompka I was able to get it working after taking off the jumper. Is it possible to hook two ultrasonic sensors on the same ESP8266. In Tasmota 'configure module' 73/74 device type is Trigger/Echo. I assigned these to two devices, but only one device showed up.

**Comment by nikito7** [comment]
Can we change trigger time?
