### ISSUE TITLE
Unauthenticated wireless password disclosure

### ISSUE THREAD

**Issue by strasharo** [arendst/Sonoff-Tasmota#1131]
Hello. I'm running version 5.9.0 on a Sonoff S20 relay and have configured a password for the web interface. If for some reason it loses connectivity to the wireless access point (either due to the AP not being present or if I forcefully de-authenticate it from the AP using packet injection) the relay reboots and starts broadcasting an unencrypted wireless network with the relay name as a SSID. When I connect to that wireless network and open http://192.168.4.1/ I'm presented with the Wifi configuration screen without being asked for any authentication even though I've set a password for the web interface. From there I can just use "Inspect element" and reveal the configured wireless password in clear text. This way anyone within the wireless range of the relay can force de-authenticate it from the network and connect to it and retrieve the wireless password. It would be good if the specific screen requires authentication if it was configured for the web interface.

**Comment by davidelang** [comment]
change the wifi config, it has the ability to do multiple thingsat startup, and 
if the first connection fails.

**Comment by strasharo** [comment]
Thanks a lot, set WifiConfig to 5 and now I does what I want. :)

**Comment by chaoranxie** [comment]
@strasharo i am having the exact same issue and i am not sure "WifiConfig 5" solves the issue. so if your house lost power, or you unplug the S20, the setting goes back to "WifiConfig 2".

Can you check if this is the case for you? it is the case for me

**Comment by strasharo** [comment]
@chaoranxie just retested with the latest firmware, it's persistent for me. Unplugged it for 10 minutes and plugged it back it and it was still there.

**Comment by meingraham** [comment]
Where (which header file) does one set WifConfig?

**Comment by strasharo** [comment]
I'm setting it through the web console once and it persists on the device. Regarding the header file, it's set here:
https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/user_config.h#L66
Values are documented here in the wifi section:
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by meingraham** [comment]
@strasharo I suspected that was it, but the slight name difference and the fact that it was being referred to as a value rather than a symbol... I just wanted to ensure that this wasn't something altogether different. Thanks.
