### ISSUE TITLE
Sonoff S20 Smart Socket won't work, flashes OK

### ISSUE THREAD

**Issue by MatsKarlsson** [arendst/Sonoff-Tasmota#1139]
I Successfully flash the S20 Smart Socket. ...100%
But when it won't log anything in arduino serial log after.

Putting it in a socket doesn't send any mqtt messages. pressing button does not switch it on or off.

It's a ESP8266 chip on it, board rev is: S20_EU_V1.3, with a date of 2017-2-16

Have flashed a ton of various Sonoff devices but can't seem to find whats the problem with this. (have tried 2 different S20 Smart sockets, same with both)

**Comment by MatsKarlsson** [comment]
Sorry, my bad :-( 

Flashed with DIO instead of DOUT, reflashed with correct flash mode, now it works like a charm.

**Comment by MatsKarlsson** [comment]
Sorry, my bad :-(

Flashed with DIO instead of DOUT, reflashed with correct flash mode, now it works like a charm.

**Comment by RoeBus** [comment]
Hello Mats,
Hopefully this works (after closing topic).. I have been digging around the internet for days and came across your issue. I have the same issue, two units wont be flashed, no matter what. Can you share the command that worked for you? What image did you flash?

Thanks,
Roel

**Comment by strasharo** [comment]
Did you try with https://github.com/mirko/SonOTA ? I already flashed four S20s without any issues.

**Comment by MatsKarlsson** [comment]
Hello @RoeBus ,
Now it works for me, I just downloaded the latest code from this repository.

In Arduino IDE you can set "flash mode", I think it's `DIO` by default, change that so it is: `DOUT`

When using wrong flash mode I could flash the devices, but they didn't work after I flashed them.

it even says so on the front page of Tasmota:

----------

ATTENTION All versions

**Only Flash Mode DOUT is supported**. Do not use Flash Mode DIO / QIO / QOUT as it might seem to brick your device.

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Theo's-Tasmota-Tips) for background information.

**Comment by davidelang** [comment]
On Fri, 10 Nov 2017, MatsKarlsson wrote:

> **Only Flash Mode DOUT is supported**. Do not use Flash Mode DIO / QIO / QOUT as it might seem to brick your device.

it's a soft brick, you can fix it with a flash over serial. nothing you can do 
in software will prevent that from working.

David Lang
