### ISSUE TITLE
Change Pulstime via webinterface?

### ISSUE THREAD

**Issue by freaktech** [arendst/Sonoff-Tasmota#1145]
hi

i Programmed a sonoff Touch pulstime = 15      so its 1.5 sec.

is there a way to change this value to 10   without flashing the device again?

thanks
tom

**Comment by arendst** [comment]
How about opening the web console and execute command ``pulsetime 10``. Just a thought...

**Comment by freaktech** [comment]
great, will try it

just

 pulsetime 10 

and enter 


will try this

**Comment by freaktech** [comment]
thank you works perfect now
