### ISSUE TITLE
Release number confusion

### ISSUE THREAD

**Issue by smadds** [arendst/Sonoff-Tasmota#1147]
Hi Theo. My upgrade logic is getting confused!
Looks like you've released 5.9.1, but the code is still reporting 5.9.0b. Can you fix this please?

**Comment by arendst** [comment]
I took a Snicker and it's better now.

Had the wrong repository... Too many handjobs...

**Comment by smadds** [comment]
lol. Suggest Google that last word..

**Comment by arendst** [comment]
When I wrote it down I though that's not right but on the other hand...
