### ISSUE TITLE
Sonoff Touch as MQTT Button

### ISSUE THREAD

**Issue by TH3M45K** [arendst/Sonoff-Tasmota#1152]
Hey,
I am using limitless LED Bulbs with Home Assistantant and want to use the Sonoff Touch as a MQTT button.

I would like to send something like "Button_Pressed" via MQTT  to my Home Assistant after a short press. Home Assistant is than managing the rest, so the ralay does not need to switch.

Thanks for your help

TH3M45K

**Comment by gajotnt** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Understanding-SwitchMode-and-SwitchTopic

**Comment by davidelang** [comment]
once you set switchtopic (correctly, to something different than the device id), 
no local switching will take place, it will only send a mqtt message
