### ISSUE TITLE
Error: Upload failed, File upload buffer miscompare

### ISSUE THREAD

**Issue by derm23** [arendst/Sonoff-Tasmota#1157]
Trying to upgrade a whole bunch of remote devices via their webpages from 5.0.1 to 5.9.1.a and get this error. Searched for the issue and it suggests a two step process first with; 
#define USE_MINIMAL enabled
then #define USE_MINIMAL disabled.
Can't figure out where in the code this line goes. I am using Arduino 1.8.5. Please help.

**Comment by derm23** [comment]
Got it to work by using the minimal firmware but still don't see where #define USE_MINIMAL should be placed.

**Comment by davidelang** [comment]
US_MINIMAL is in user_config.h normally.

David Lang

**Comment by shayshtern** [comment]
I also go fail when try to upload the sonoff.bin file. ...
