### ISSUE TITLE
No .bin file encryption

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#1159]
Hello,

I saw that the .bin file isn't encrypted. It's easy to find the wifi and mqtt password in this file. A bit dangerous if this file is uploaded to a server (for upgrades).

Greetings
Fabi

![bildschirmfoto vom 2017-11-09 13-40-00](https://user-images.githubusercontent.com/6533600/32606004-e4f48314-c553-11e7-93fd-c4a9376e6f39.png)

**Comment by arendst** [comment]
These parameters are stored in flash memory. People are overrating the possibility of editing the user_config.h file. No need to do this. 

Not editting the user_config.h file but using the appropriate commands the setting you see won't be the real values as long as you do not change the CFG_HOLDER define the flash settings are not overwritten.

**Comment by 0n3-70uch** [comment]
Ok so its better to upload a stock file and than change everything via mqtt or webinterface. I put some settings into the user_config_override.h because sometime I use the command "Reset 2". After a reset the sonoff need a working wifi configuration from the "user_config.h" file. Is there any other solution?

**Comment by davidelang** [comment]
If you can compile your own .bin file and make it available on a webserver, you 
should also be able to add restrictions so that it can only be accessed by the 
things that you want to use it, and who need the passwords

**Comment by 0n3-70uch** [comment]
That's a good idea but therefore I need a password protection at the server side. How I can add the password string to the Sonoffs?
