### ISSUE TITLE
Can't update sonoff via web access, why?

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#1163]
Im getting fail. Why? 
Upload the sonoff.bin from releases. 
Any help?
Thanks,
Shay Shtern.

**Comment by davidelang** [comment]
there's no way to know what is happening from what you are describing. you give 
no details.

**Comment by shayshtern** [comment]
4 Sonoff -
2 Basic : v5.6.1 both. 
1 POW : v5.6.1h
1 Touch : v5.6.1h

**Comment by shayshtern** [comment]
![Image](https://i.imgur.com/QoMfNyV.jpg)

After uploading presentags get 100% it's automatically get this message ⏫
In the pic :

**Comment by Tresett** [comment]
Check fw size and free space on device.

**Comment by jetema** [comment]
Read this #1081
