### ISSUE TITLE
Add sonoff to HomeAssistant project.

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#1164]
Can someone explain me exactly how to add sonoff that formated with Tasmota project and have web access to HomeAssistant project ?
( http://hassio.local:8123 ). 
I really can't get it. Thank you! 
Thanks !

**Comment by ionciubotaru** [comment]
Read https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant

**Comment by shayshtern** [comment]
Yea I read it. But can't really understant the code. 
Any other maybe more explaining tutorial ?

**Comment by gajotnt** [comment]
Use domoticz :P

**Comment by shayshtern** [comment]
What do you mean?

**Comment by gajotnt** [comment]
Use domoticz instead of Home Assistant, way simpler to configure and use.

**Comment by shayshtern** [comment]
Supported homekit and Google home?!

**Comment by gajotnt** [comment]
HomeKit yes
https://www.domoticz.com/wiki/Homekit_Siri

Google Home I dont think its quite implemented yet, and i find that wierd

**Comment by shayshtern** [comment]
Homekit for iPhone and some : hi Google turn on lights" on Android. How do I do that? Is there "Home" app for Android?
