### ISSUE TITLE
Removed C15 from sonoff-basic

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#1167]
I accidentally removed C15 from sonoff basic while flashing
here is the schematic
https://www.itead.cc/wiki/images/f/ff/Sonoff-Schematic.pdf
can somebody tell me if it is safe to continue to use the device?
what is the capacitor used for?

Thank you.

**Comment by ionciubotaru** [comment]
It stabilize the 3V3 output, without it you may experience unexpected resets.

**Comment by ageorgios** [comment]
Thank you!
