### ISSUE TITLE
not working when network down

### ISSUE THREAD

**Issue by kezzab25** [arendst/Sonoff-Tasmota#1169]
I am not sure if my config is wrong but how do I get a sonoff basic to work when the network goes down? Unfortunately that happens a lot here as our router is in the main house and the owner likes to disconnect me from the network often.

**Comment by freaktech** [comment]
hi

i have the TOUCH and tested NOW

it is working the most times but def. sometimes not

sometimes the LED for WIFI starts flashing, then it will be ON   (also when there is no WIFI)


so its not working 100% when WIFI is off   in 5,9

tom

**Comment by davidelang** [comment]
When the network is down, the device will attempt to reconnect to the network 
and to the mqtt server. While it is attempting to connect to the mqtt server, 
the library prevents anything else from happening (including responding to local 
buttons), so you will see 3-5 second delays on a regular basis.

run your own router and Pi with your mqtt server and home automation server. 
Then have your router connect to the main house's router for connections out. 
When the Internet connection goes down, all your local stuff will keep working.
k

**Comment by freaktech** [comment]
i don't use MQTT so its only a problem if the router would be down

**Comment by davidelang** [comment]
disable mqtt if you aren't using it and you will not run into the delays of the 
device attempting to connect to the mqtt server.

David Lang

**Comment by stefanbode** [comment]
Is there a config option or compiler option to influence the timeout for the MQTT server connection. Normally the server answers quite fast. Therefore a hardcoded change of the timeout can be something we can take into consideration.

**Comment by davidelang** [comment]
This is a bug somewhere in the arduino network library, we havent' gone digging 
to find out exactly where and what it would take to override it

> Is there a config option or compiler option to influence the timeout for the MQTT server connection. Normally the server answers quite fast. Therefore a hardcoded change of the timeout can be something we can take into consideration.
>
>
