### ISSUE TITLE
Sonoff T1 with new 5.9.1c - not booting

### ISSUE THREAD

**Issue by Wieg** [arendst/Sonoff-Tasmota#1170]
Hi Guys,

Just flashed a T1 UK and the flash went ok but the device doesn't startup.

It is an esp8285 i only changed the default wifi SSID and password and flashed it with DOUT.
So i am a bit stuck, what to do now ? any thoughts are very appreciated.

**Comment by jeylites** [comment]
Have you check the flash size? Did you flag using SonOTA or manually with GPIO 0 to Ground?

**Comment by Wieg** [comment]
flash size was OK flash was SUCCES i did it manually GPIO 0 to ground. 
I don't get .....

**Comment by jeylites** [comment]
Don't know if would it make any difference, have you tried V.5.8 also what are you getting on serial terminal, any messages?

**Comment by Wieg** [comment]
got one working with 5.8p, the first one i couldn't even get in flashmode anymore.
Hope i didn't brick it ........ :(

**Comment by jeylites** [comment]
The one you can't get into flash mode, was it flashed with 5.9 before?


*Jey Kasi*

**Comment by Wieg** [comment]
no fresh out the box ........ i tried it for 30 minutes now ..... can't get it to go in flash anymore .... but it seems not to be a brick i think / hope

**Comment by jeylites** [comment]
Don't know if it's a related problem but I will share my past experinece. My very first attempt to flash the T1 was through SonOTA and it failed so manual upload was next. Even then doing it manually, I couldn't get it into flash mode.  By accident, I discovered the Atmel (Marked in Yellow) somehow was interfering with the ESP so I removed it and was able to flash the ESP without any problem.

![29631413-dc3c8b64-883f-11e7-9ec0-cd9f9c340697](https://user-images.githubusercontent.com/9190080/32692303-a005f572-c750-11e7-9dd8-d5f1b891a4de.jpg)

**Comment by Wieg** [comment]
the second it did out off the box with the 5.8p not the 5.9.1c (thats all i can think off for now) .... but .... my package arrived today .... just did 2 sonoff pow's out off the box with the 5.9.1c and they work like a charm ........

**Comment by Wieg** [comment]
Just could not leave it alone .... i just flashed my "bricked" T1 UK .... and bam in one time it worked .... just call me a noob .... did the same as always ... now it works.

Now the lights and devices in my house are allmost all sonoff based :) 29 devices and counting :)
big thanks to @arendst :)
