### ISSUE TITLE
Voltage missing in Domoticz config page

### ISSUE THREAD

**Issue by SimoneBnc** [arendst/Sonoff-Tasmota#1177]
I was previously running version 5.5.2b on a POW then upgraded to latest stable version and I noticed I no longer have the voltage field in Domoticz page that I had before and it was sending voltage data and it stopped sending voltage readings right after I did the update. Now it will not let me upload OTA a recompiled version of the 5.5.2b. Is there a fix to have the voltage back?

**Comment by arendst** [comment]
Mine still works as expected.

Enable weblog 3 to see if pow still sends data to domoticz.

**Comment by SimoneBnc** [comment]
It only sends data for IDX of the POWER sensor; in domoticz page I only see up to IDX 6 and I remember I had 2 more if I am not mistaken

**Comment by arendst** [comment]
So to solve just enable the idexes again on the Domoticz configuration page

**Comment by SimoneBnc** [comment]
![image](https://user-images.githubusercontent.com/24373370/32727306-6651a18c-c87c-11e7-8f0b-c552b2020cb9.png)
let's hope this makes it more clear

**Comment by arendst** [comment]
So you are using a version which does NOT support voltage and current. 

Domoticz Voltage and Current was introduced in development release version 5.8.0b and official release version 5.9.0. See file _releasenotes.ino

![image](https://user-images.githubusercontent.com/11044339/32727588-51a5403a-c87d-11e7-8908-abc071c4909e.png)

**Comment by SimoneBnc** [comment]
I have this
 #define VERSION                0x05090101   // 5.9.1a
Could it be something corrupted on the internal flash?

**Comment by arendst** [comment]
What is the result of command status 2?

**Comment by SimoneBnc** [comment]
After some tinkering I figured it had an old version on it, don't understand why since I was compiling the 5.9.1. Thanks for your help.
