### ISSUE TITLE
tasmota mqtt + PWA

### ISSUE THREAD

**Issue by MariusGrey** [arendst/Sonoff-Tasmota#1178]
Hi,
I installed tasmota on a sonoff 4ch pro. It works via HTTP requests, but I cant control it from mqtt (mqttlens + cloudmqtt.com)... do you know why?
I have a website (wordpress) and I use ita from smartphone (mobile theme + progressive web app tool), now I'd like to use this PWA to controll my sonoff 4ch pro. I cant use HTTP requests because PWA need an SSL connection, so I think to use MQTT via PHP... is it possible? Do you know how? Can you help me?
THX

**Comment by davidelang** [comment]
you need to start out by figuring out if you are connecting to your mqtt server 
and passing messages (you should be able to see this in the logs)

from there, you need to figure out how to send the appropriate messages from 
whatever you connect to your mqtt server.

you haven't given us any detail about what fails in your message, so I can't 
give you any details of how to solve it, just where to start looking.

**Comment by MariusGrey** [comment]
Hi davidelang,
thanks for your reply.
I just put the sonoff online.
Here some SS:
![screenshot_20171113-223222](https://user-images.githubusercontent.com/33056755/32750597-68695ebe-c8c3-11e7-9d6d-4cd3aeedcfb3.png)
![screenshot_20171113-223429](https://user-images.githubusercontent.com/33056755/32750598-688be61e-c8c3-11e7-8429-a0c4bc0d2a1a.png)
![screenshot_20171113-223445](https://user-images.githubusercontent.com/33056755/32750599-68a76a88-c8c3-11e7-9ed4-079baefbd629.png)
![screenshot_20171113-223456](https://user-images.githubusercontent.com/33056755/32750600-68bfe676-c8c3-11e7-9b6c-31fc55e42d9f.png)

Can you send command to it?
Can you check it?

THX

**Comment by MariusGrey** [comment]
Is still online. Do you need more info?

**Comment by MariusGrey** [comment]
help me, please. 
Do you need more details?
