### ISSUE TITLE
v5.9.1c not working with ALEXA, why ?

### ISSUE THREAD

**Issue by Olli80** [arendst/Sonoff-Tasmota#1184]
I have tried so many times to connect my sonoff with ALEXA after flashing v5.9.1c ,
but ALEXA didn't find the device !?

**Comment by Olli80** [comment]
I have tried WeMo and HUE emulation and ALEXA didn't find anything....

**Comment by Alveran81** [comment]
Which Alexa? Echo Plus or Dot?

**Comment by Olli80** [comment]
Do I need a Echo or Dot to work with the sonoff ?
At the moment ALEXA is used by FireHD10 Tablet !?

**Comment by Alveran81** [comment]
The new Echo with Integrated Hub doesn't work. My old echo dot works.

**Comment by Olli80** [comment]
Do I need minimum one Echo at my network,
or did it work with the ALEXA on the FireTablet?

**Comment by Alveran81** [comment]
I don't know

**Comment by AcHoBi** [comment]
You must have one physical hardware Echo in your local network as a "communication server"!
For sending commands you can use also software Echos like REVERB or the actual Alexa app itself.

**Comment by Olli80** [comment]
Thank you, that are good news 👍
