### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by flexiti** [arendst/Sonoff-Tasmota#1186]
Backup restore IP adres, but this can not be changed from the website (only form MQTT)
eg. if you have another device with a different address and you want to copy the same settings.

I suggest either bypassing the settings of IP in backup or by adding IP settings from the web page.

**Comment by arendst** [comment]
Use web console and IPADDRESS commands to change.

**Comment by flexiti** [comment]
Yes, I know ;) but in my opinion  backup will be more useful when the IP address is not saved - it can be used as a backup and as a "start" setting for new sonoff.
