### ISSUE TITLE
Encode/decode log data

### ISSUE THREAD

**Issue by decologne** [arendst/Sonoff-Tasmota#1187]
In case of viewing log data in Console mode this will fail if the log data contains the characters < or > .
 Is it possible to encode the log data in function HandleAjaxConsoleRefresh() in webserver.ino and
decode this in javascript function l(p)
  ...
  z=d.getElementsByTagName('l')[0].childNodes;
  if(z.length>0)
  {
    t.value+=z[0].nodeValue;
  }
Thanks.

**Comment by arendst** [comment]
Solved in next (pre) release.
