### ISSUE TITLE
Direct control buttons with IR receiver

### ISSUE THREAD

**Issue by spe6** [arendst/Sonoff-Tasmota#1191]
Please help me to implement direct control buttons with IR receiver, or tell me what variable to manipulate, thanks in advance.

**Comment by ionciubotaru** [comment]
You cannot do it in Tasmota, you must configure your HA to send proper commands to relays when a certain IR code was received

**Comment by spe6** [comment]
This option is understandable, but you need to pull the pins directly, upgrade the firmware.
