### ISSUE TITLE
5.9.1d Compile problem

### ISSUE THREAD

**Issue by decologne** [arendst/Sonoff-Tasmota#1193]
Theo, if I compile the last distribution there are some errors about new declaration and old declaration.
xsns_bh1750:44: error: new declaration 'boolean Bh1750Detect()'
 boolean Bh1750Detect()
                      ^
xsns_10_bh1750:48: error: ambiguates old declaration 'void Bh1750Detect()'
 void Bh1750Detect()
etc.

**Comment by arendst** [comment]
Correct. You will have to remove the old file xns_bh1740. In fact I suggest to remove all files from sonoff folder and install new files from repository as many file names have changed ;-)
