### ISSUE TITLE
Rssi 100

### ISSUE THREAD

**Issue by flexiti** [arendst/Sonoff-Tasmota#1195]
If anybody have RSSI show at 100 ? after uploading the program.
 I have not found the rule yet, eg. now I have still RSSI 100, upgrade was 2 hours ago

**Comment by ionciubotaru** [comment]
RSSI means the wifi signal strength - you get 100 because your sonoff is close to te AP.
Maybe you are looking for uptime.

**Comment by flexiti** [comment]
no, this is not that problem, and I know what it is RSSI  ;)

**Comment by swampdogmash** [comment]
I have a similar display with some of my units.. one which is next to another which reports only 83 rssi. Not sure what causes it but keen to have a look later this long weekend in the UK. I thought it was a version 5.11 thing but one of these is an S20 I just bought and installed 5.12 on and one is a sonoff basic running 5.11, right next to a sonoff basic running 5.12...

Need to grab some logs and configs and will post back later.
