### ISSUE TITLE
Hue Emulation as LIGHT, not as BRIDGE

### ISSUE THREAD

**Issue by symboter** [arendst/Sonoff-Tasmota#1197]
Hi,
is there any possibility to emulate a sonoff S20 Power Socket as HUE LIGHT?
If emulated as Hue Bridge, it cannot be used in a physical Hue Bridge because it only shows up as Bridge with no memory available.

The reason is, that Echo Plus with integrated Hub finds the Hue Bridge emulated Sonoff S20, but does not allow any IFTTT with them because the internal Hub of Echo Plus can not be exported to any application.
This means NO device which is connected directly to the Echo Plus can be used by an external routine.

This is why I want to use the external physical Hue Bridge which can be exported to IFTTT through the Hue app.

Thanks

**Comment by zerog2k** [comment]
Maybe I understand this wrong, but hue devices, e.g. lights, are zigbee protocol, not wifi. The hue bridge is a bridge between wifi and zigbee. So the Sonoffs being wifi-only devices only make sense with bridge emulation.
