### ISSUE TITLE
Can you add more switches? For example, 8?

### ISSUE THREAD

**Issue by lovinggrey** [arendst/Sonoff-Tasmota#1198]
Hello arendst, can you add 8 switches to go in? I want to make D1 Mini a remote controller. I want to add 8 swtich or 8 button

**Comment by ionciubotaru** [comment]
download the latest version and you can enjoy 8 switches

**Comment by lovinggrey** [comment]
![image](https://user-images.githubusercontent.com/28864318/32935169-dee3e4ea-cba9-11e7-8915-667a2856a08b.png)
I only found 4 switches, and I didn't find 8

**Comment by ionciubotaru** [comment]
try 4 switches and 4 buttons

**Comment by jchmielniak** [comment]
Can I assign/use separate MQTT Topics to Switches and Buttons to receive the info which one was pressed?
