### ISSUE TITLE
Wifi Client and AP

### ISSUE THREAD

**Issue by Joeyhza** [arendst/Sonoff-Tasmota#1200]
Hi,

Not really an issue at all - but I was wondering :

Because I have a Sonoff SV connected to my main gate motor quite a distance away from my Router which intermittently loses wireless signal, is it all possible to have a nearer Sonoff device function as both a a client and an AP set as a wireless extender/repeater?

Thanks in advance

**Comment by davidelang** [comment]
no, the tasmota firmware cannot act as a client and AP at the same time
k

**Comment by Joeyhza** [comment]
Yes....okay

I'm quite aware of what the firmware does and does not offer - I was merely wondering about the possibilities 

k

**Comment by davidelang** [comment]
well, it's software, so you can do just about anything if you try hard enough 
:-)

but it's unlikely that this will be added to tasmota as we are very tight for 
space. It's better to setup a new AP to cover the area than to try to have the 
sonoff devices relay the messages.

David Lang

**Comment by Joeyhza** [comment]
Cool - Thanks again David

**Comment by ionciubotaru** [comment]
Here is example of wifi repeater.
https://github.com/martin-ger/esp_wifi_repeater
Is it possible to add this extension to Tasmota Lite ?
