### ISSUE TITLE
MQTT broker field max.number of chars

### ISSUE THREAD

**Issue by etpedro** [arendst/Sonoff-Tasmota#1205]
Hi,

I have an MQTT broker hosted on an EC2 server and the hostname for the connection is quite big (49 chars) and it's not accepted on the MQTT broker filed configuration page due to the size limit.

Is it possible to increase the max. number of chars?

Regards,
Pedro Ferreira

**Comment by Joeyhza** [comment]
use use the public IP address of the instance

49 Character long hostnames in a log ill probably make you go blind in the long run :)

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html
