### ISSUE TITLE
SDA / SCL pins for I2C communication

### ISSUE THREAD

**Issue by yaydogan** [arendst/Sonoff-Tasmota#1208]
Hi,

I have a Sonoff and looking at the ESP8266 pinout  diagram, I see GPIO4 is SDA and GPIO5 is SCL. I want to use these I/O pins for an I2C OLED and soldered wires on the chip. However these bits are defined as:
I2C_SCL - 5
I2C_SDA - 6 in Tasmota software. Has anyone used I2C interface with an OLED and did it work? Or do I need to change the values of SCL, SDA pins to use with OLED display?

Thanks.

**Comment by arendst** [comment]
Tasmota does as yet not support OLED or any display.

**Comment by webtop** [comment]
I'm going to be working on some I2C code this weekend. If I come across anything that I think will help you, I'll let you know, but no guarantees,
