### ISSUE TITLE
Update DateTime using MQTT?

### ISSUE THREAD

**Issue by TommySharpNZ** [arendst/Sonoff-Tasmota#1210]
My OpenHAB server always has the correct date and time. Is it possible to push this out to a tasmota flashed device using MQTT?

**Comment by ionciubotaru** [comment]
NU, it's not possible to set time via mqtt. You can install a NTP server on your openHAB server.

**Comment by zerog2k** [comment]
they set time from NTP server on the net, which will work for 99.9% of people out there.
https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/user_config.h#L133-L136

But maybe you have them on a restricted network, in which case ionciubotaru mentioned is a great alternative, point them at a local NTP server on your LAN.
