### ISSUE TITLE
BME680

### ISSUE THREAD

**Issue by ionciubotaru** [arendst/Sonoff-Tasmota#1212]
Tasmota supports BMP180, BMP280, BME280
Please add support for BME680 - it's a new great sensor (4 in one - Temperature, Humidity, Pressure and Gas Sensor)
https://www.adafruit.com/product/3660
https://eu.mouser.com/ProductDetail/Bosch/BME680/?qs=v271MhAjFHjo0yA%2fC4OnDQ==

**Comment by dingausmwald** [comment]
Does it show the passive co2 values? Have red that this should be possible through Algorythms with the 680
