### ISSUE TITLE
Sonoff 4Ch

### ISSUE THREAD

**Issue by Wojcioo** [arendst/Sonoff-Tasmota#1213]
Hello

I've created in Domoticz a schedule which turns off all for relays at 22 PM, and it turns it off.
But after few second this 4 relay are again on.
I don't know how to resolve this trouble.....

**Comment by ionciubotaru** [comment]
Subscribe to '#' topic of your mqtt server and check which messages turn your device on.

**Comment by kenmcc** [comment]
i think you need to change the switch settings from factory default, I think they are set to 'inching' mode.
 (disclaimer, i've not got a 4ch yet, it's in the post, but that sounds like the behaviour i've seen demonstrated in youtube etc)
