### ISSUE TITLE
Sonoff POW - HlwIcal <> HlwPcal.

### ISSUE THREAD

**Issue by twikedk** [arendst/Sonoff-Tasmota#1214]
Running FW 5.9.1

If I send a 'HlwIset' command through my web browser
`http://sonoff-POW-IP/cm?cmnd=HlwIset 4200`

the console returns
`12:53:06 MQT: stat/sonoff-92D56B/RESULT = {"HlwPcal":3454}`

which I guess should be HlwIcal instead of HlwPcal.

**Comment by arendst** [comment]
Thnx to putting it to my attention!

Small error... The name is wrong, the value is OK.

Fixed in next (pre)release.
