### ISSUE TITLE
Force OTA upload

### ISSUE THREAD

**Issue by trikon** [arendst/Sonoff-Tasmota#1218]
Hi!
Is it possible to force upload firmware via OTA ?
I need to upload 1Mb file.

**Comment by HellGL** [comment]
Usually there is only 1MB of memory available at all. Half (a little bit less) of it is occupied by the firmware itself and the other half is available for an OTA update before flashing it over the running firmware. So without SPI upgrade (see here https://hackaday.com/2016/07/16/your-esp8266-needs-more-memory/) there is no way to flash a 1Mb file over the air.

**Comment by trikon** [comment]
oh, thanks for details. now is all clear :)
