### ISSUE TITLE
FTDI from Ebay is not working with Sonoff Basic

### ISSUE THREAD

**Issue by eimix** [arendst/Sonoff-Tasmota#1219]
I suggest to update Wiki page for hardware:
https://github.com/arendst/Sonoff-Tasmota/wiki/Hardware-Preparation

It states that "3.3V FTDI USB-to-Serial Converter/Programmer" is required, but any like CP2102, CH340, PL2303 works. 
Please remove "FTDI" as any UART TTL 3.3V programer works.

As FTDI has many fake chips on EBay, i got one of them and was unable to upload until tried with CP2102.

**Comment by arendst** [comment]
You may update the wiki yourself ;-)

**Comment by eimix** [comment]
OK
