### ISSUE TITLE
Multiple DS18B20

### ISSUE THREAD

**Issue by Amadeus71rus** [arendst/Sonoff-Tasmota#1222]
Hello. How i can set resolution ds18b20 to 11bit? TempRes not working.

**Comment by ionciubotaru** [comment]
you can't, it's a digital sensor, not an analog one.

**Comment by Amadeus71rus** [comment]
This is not true. The DS18B20 has a resolution of 9.10 and 11 and 12 bit. In normal arduino set by the command setResolution.

**Comment by arendst** [comment]
According to the datasheet:

> The resolution of the temperature sensor is user-configurable to 9, 10, 11, or 12 bits, corresponding to increments of 0.5°C, 0.25°C, 0.125°C, and 0.0625°C, respectively. The default resolution at power-up is 12-bit.


So what more do you want?

**Comment by Amadeus71rus** [comment]
When using TempRes 3, I only add zeros. The temperature continues to be measured to within 0.5 degrees. As if the accuracy of 9 bits is set.

**Comment by arendst** [comment]
It also depends on your DS18x20 sensor. The S version does not have that many resolution.

**Comment by Amadeus71rus** [comment]
The sensors are defined as DS18B20. On firmware EspEasy all works correctly.

**Comment by arendst** [comment]
Then I suggest you set the DS18B20 resolution in ESPEasy to 12 bits and then move it over to Tasmota. Here is my result:
![image](https://user-images.githubusercontent.com/11044339/33073536-7bec7cf4-cec3-11e7-948e-a00345ca0f3b.png)

**Comment by Amadeus71rus** [comment]
![screenshot-192 168 1 162-2017-11-21-15-55-38](https://user-images.githubusercontent.com/32751768/33073633-8bb6b9b8-ced4-11e7-9e33-a0eec55a7638.png)

**Comment by Amadeus71rus** [comment]
I'll try it.

**Comment by arendst** [comment]
Next (pre)release will set resolution to 12-bit if not yet set.

**Comment by mkh595** [comment]
_you can't, it's a digital sensor, not an analog one._
@ionciubotaru : You very often write nonsense

**Comment by ionciubotaru** [comment]
@mkh595 - thank you for sharing your opinion. I try to answer as many issues as I can, of course sometimes I make mistakes. Please try to answer as many issues as you can - this is a better way to help the community.
