### ISSUE TITLE
4ChPro: Wifi Led behaviour

### ISSUE THREAD

**Issue by kenmcc** [arendst/Sonoff-Tasmota#1227]
Hi,
I received my 4Ch PRO yesterday and flashed latest Tasmota to it. It's all working fine, except that the blue wifi led seems to operate on the logic:

WIFI_LED_STATE = (LED1_ON|LED2_ON|LED3_ON|LED4_ON)

i.e. if at least one of the relays are ON, then the blue LED is on also. Is this normal behaviour? If so is there anyway to change it, since the RED leds also indicate if any of the leds are on.

Thanks
Ken

**Comment by arendst** [comment]
See #1225
