### ISSUE TITLE
sending topic/cmnd/power 1 returns {"Command":"Unknown"}

### ISSUE THREAD

**Issue by daygoor** [arendst/Sonoff-Tasmota#1234]
Hi,
I am new in this project.
When I send: topic/cmnd/power
I receive: OFF
but when I send: topic/cmnd/power 1
I receive: {"Command":"Unknown"}

What am I doing wrong here?

I tried debugging the code, but were not able to figure out what is going wrong!

p.s. I am using mosquitto as my broker .. and I use MQTT.fx to send the above commands.

**Comment by arendst** [comment]
See wiki https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Overview

**Comment by daygoor** [comment]
My problem was that I was using MQTT.fx wrongly! The payload was empty.

I figured that out after comparing the command I send using in terminal: 
mosquitto_pub -h broker -t cmnd/sonoff/power -m 1
and the command I send using MQTT.fx
