### ISSUE TITLE
The IRremote coding of sharp TV is not recognized, and also can not be sent

### ISSUE THREAD

**Issue by plutosherry** [arendst/Sonoff-Tasmota#1238]
Learning and sending infrared remote control code for request adaptation sharp TV
It looks like the irsend code part is not yet finished?

**Comment by arendst** [comment]
Correct.It is not implemented. If you want it you will have to add some code to the xdrv_light.ino file and re-enable both sending and receiving in the irremoteesp8266.h library file.

To save code space I have to make choices and this is one of them.

**Comment by plutosherry** [comment]
Thank you very much. I'll try that next

**Comment by Nixsm** [comment]
![noice](https://media.giphy.com/media/l3q2slcE8854Yqqg8/giphy.gif)
