### ISSUE TITLE
Support for Electrodragon ESP LED Strip Board

### ISSUE THREAD

**Issue by canis-ferrin** [arendst/Sonoff-Tasmota#1241]
I am looking for a 5050 LED Stripe driver board and found Electrodragon ESP LED Strip Board as described here: 
http://www.electrodragon.com/product/esp-led-strip-board/
Is this compatible with Tasmota?

**Comment by arendst** [comment]
Select the wemos d1 mini and the correct pwm channels as documented on their site and you should be  good to go.

Alternatives H801, Arilux and MagicHome are already supported.

**Comment by empenoso** [comment]
> Select the wemos d1 mini and the correct pwm channels as documented on their site and you should be good to go.
> 
> Alternatives H801, Arilux and MagicHome are already supported.

I bought ESP LED Strip Board, Mosfet Drive https://www.electrodragon.com/product/esp-led-strip-board/. Board works with Sonoff-Tasmota. RGB LED Strip also works.
But do not work together.

I can't send "+12V" to exit "V". https://www.electrodragon.com/w/ESP_Light

Please tell me. Thank!
