### ISSUE TITLE
Swap relay output signals

### ISSUE THREAD

**Issue by zarss** [arendst/Sonoff-Tasmota#1244]
Hi. Was trying to find a way, how can i swap relay output from HIGH to LOW? I have this relay board, where realys are powered while OFF.  Thank you.

**Comment by arendst** [comment]
Select Relay1i instead of Relay1. The i inverts the relay signal.

**Comment by zarss** [comment]
Thank you so much.

**Comment by jeylites** [comment]
How do you invert Switches?

**Comment by phedders** [comment]
Sweet! :)
