### ISSUE TITLE
Two BME280 sensors with different addresses doesn't work.

### ISSUE THREAD

**Issue by ChukXP** [arendst/Sonoff-Tasmota#1251]
Hello!
I've tried to use 2 BME280 sensors which connected to the same I2C bus. Sensors have different addresses 0x77 and 0x76. i2cscan command give result that both sensors was found. But unfortunately I can receive data only from one sensor. 
Is any way exists to solve this issue?
Thanks in advance.

**Comment by arendst** [comment]
As designed only lne sensor supported.

**Comment by ChukXP** [comment]
Is it possible to release this feature in new versions? I've tried to use BME280 and SI7021 together and got big difference in humidity values.
