### ISSUE TITLE
Switch is not reported via mqtt

### ISSUE THREAD

**Issue by boaschti** [arendst/Sonoff-Tasmota#1253]
Ist it a normal behavior that tasmota don't report a Switch immideatelly if it is pressed?

Client mosqsub/32281-raspberry received PUBLISH (d0, q0, r0, m0, 'stat/sonoff/RESULT', ... (15 bytes))
{"POWER2":"ON"}
Client mosqsub/32281-raspberry received PUBLISH (d0, q0, r0, m0, 'stat/sonoff/POWER2', ... (2 bytes))
ON
Client mosqsub/32281-raspberry sending PINGREQ
Client mosqsub/32281-raspberry received PINGRESP
Client mosqsub/32281-raspberry received PUBLISH (d0, q0, r0, m0, 'stat/sonoff/RESULT', ... (16 bytes))
{"POWER2":"OFF"}
Client mosqsub/32281-raspberry received PUBLISH (d0, q0, r0, m0, 'stat/sonoff/POWER2', ... (3 bytes))
OFF

The switch is reported periodically but not immediatelly.

Client mosqsub/32281-raspberry received PUBLISH (d0, q0, r0, m0, 'tele/sonoff/SENSOR', ... (63 bytes))
{"Time":"2017-11-26T17:44:32", "Switch1":"OFF", "Switch2":"ON"}

Parameters:
:02:29 MQT: stat/sonoff/RESULT = {"SwitchTopic":"0"}
21:03:51 CMD: SwitchMode
21:03:51 MQT: stat/sonoff/RESULT = {"SwitchMode1":0}
 
I think it would be nice to get the switch state immediatelly because switch and power can be different.
SwitchTopic = 1 is a alternative but relais is not working if server is offline.

**Comment by ionciubotaru** [comment]
set `switchtopic` and try different `switchmodes` - Tasmota reports switch changes via mqtt instantly.

**Comment by boaschti** [comment]
I tried it. 
The problem is: 
If pysical switch ==Off and homeassistant sends to cmnd/sonoff/Power On then the switch (which is read from hass) is set to on. 
Perhaps  is another way to configure that.

**Comment by smulle48** [comment]
mine is publishing the same time I press the button in the web interface / firming mqtt command. Try to subscribe to # (all) to see all messages.

When I used HASS, I used this code to control my sonoff:

switch:
  - platform: mqtt
    name: "Lampe Stue"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

Now I have abandoned HASS in favor of node-red :-)

**Comment by boaschti** [comment]
Yes that`s the config to controll relay but if you want to know the real switch state (in hass binary_sensor) sonoff don't tells it immidiatelly. You can only see the "output" on topic stat/sonoff/POWER. And if you set the switchtopic = sonoff you get same msg on cmnd/sonoff/POWER.

**Comment by boaschti** [comment]
In my case i have a pir sensor which is connected to port configured as switch1 the relay1 switches the lamp switchmode1 = follow. Additionally i have a switch in hass. If i switch the lamp on with hass i also want to know if pir is on or off because it controlls other lamps too.

**Comment by stefanbode** [comment]
I double checked on my devices. You need to define a RELAY1 to get immediate feedback through MQTT. The switch itself is not reported through the RESULT event. You just get it indirect through the POWER result or by waiting for the STATUS

**Comment by boaschti** [comment]
Hm. Ok then aktual there is no way to get the real switch state immeditelly. Just indirekt (Power) but it can be inverted... Is it possible to implement it in the next fw version?

**Comment by davidelang** [comment]
if you set switchtopic, then changing a switch doesn't change the relay, it only 
sends a mqtt message. Set switchmode to define how to respond to the switch

**Comment by boaschti** [comment]
Ok. But i think the relay don't switch when any switch topic is set. So in this case i have to link switch and relay in hass. Right? I'll try again. Switchmode have to be 1 (follow).

**Comment by davidelang** [comment]
On Wed, 29 Nov 2017, boaschti wrote:

> Ok. But i think the relay don't switch when any switch topic is set. So in this case i have to link switch and relay in hass. Right? I'll try again. Switchmode have to be 1 (follow).

well, when it switches the relay, you should get an immediate stat/ message that 
the relay has changed.

But I thought the problem was you didn't have a relay defined for that switch?

In any case, your home automation software can get the message and instruct 
anything to happen when it gets the message

**Comment by boaschti** [comment]
Yes thats right i get the stat of relay if it changes. But if not like in the upper explained case the Relay doesn't change and i cannot see the switch state. switchmode1 = 1
pir Sensor = off -> switch lamp on with hass (cmnd/sonoff/power1 ON) -> i get the state via mqtt (stat/sonoff/power1 ON)

pir changes to on -> i get no msg no relay change because it is already on but i want to know that pir is changed to on

pir changes to off -> relay turns off -> (stat/sonoff/power1 OFF)

> In my case i have a pir sensor which is connected to port configured as switch1 the relay1 switches the lamp switchmode1 = follow. Additionally i have a switch in hass. If i switch the lamp on with hass i also want to know if pir is on or off because it controlls other lamps too.

**Comment by smulle48** [comment]
Why not configure the pir as switch 2 with switchtopic pir and let Hass do the switching with the relay?

**Comment by mkh595** [comment]
In Hass I have switch and PIR and both are reported via mqtt immediately.

![basic4](https://user-images.githubusercontent.com/30566575/33439239-38e85f50-d5ed-11e7-8f92-c28d57bdba62.PNG)


PIR on GPIO1, external button on GPIO3 (standard GPIO0)

![basic1](https://user-images.githubusercontent.com/30566575/33438923-73013924-d5ec-11e7-9ae8-311b3eee33d1.PNG)

SwitchTopic: "home208pir"
ButtonTopic: ""
SwitchMode1: 1

```
binary_sensor:
# 208 - PIR
- platform: mqtt
  name: home208_move
  state_topic: "cmnd/home208pir/POWER1"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion


switch:
# 208 - Light
- platform: mqtt
  name: "home208"
  state_topic: "stat/home208/POWER"
  command_topic: "cmnd/home208/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: false

**Comment by davidelang** [comment]
I believe that switchmode 7 (just added) will signal any state change of the 
switch.

But in your case, you need to have the pir set to something other than switch1, 
or you need to set switchtopic to decouple it from the relay

What you are seeing is what is intended, if you have the relay connected to the 
switch and you manually turn on the relay, the swtich being turned on isn't 
supposed to do anything.

it's doing what you've asked it to.

If you want it to do something different, then you need to change how it's 
configured (switchtopic) so that the switch isn't directly tied to the relay.

**Comment by smulle48** [comment]
I have made a garage door opener with a reed switch. Finally I got it working as it's supposed to.

The reed sensor is set as a switch2, with switchmode2 7 and switchtopic garagealarm.

every time the reed switch is changing, it's publishing the message: cmnd/garagealarm/POWER2 ON or cmnd/garagealarm/POWER2 OFF depending on the current reed switch state.

This should also be possible to do with your PIR sensor :-)

**Comment by boaschti** [comment]
@smulle48 yes it works but there is no funktionality without server

@mkh595 right but the Problem is explained upper you read your relay state and it can be differ to switch

@davidelang switchmode has to be 1 because relay have to follow the switch

So i think i'll decouple relay from switch in tasmota an couple it in hass. Not the best solution but it works.
I'll add a immediatelly switch update to the firmware. Who can commit it for me?

**Comment by boaschti** [comment]
Adding 
`        if (MqttShowSensor()) {
          MqttPublishPrefixTopic_P(2, PSTR(D_RSLT_SENSOR), Settings.flag.mqtt_sensor_retain);
        } `

in sonoff.ino Line 2110 will fix that. 
can anybody commit it?
