### ISSUE TITLE
Sonoff Basic GPIO4 restart problem

### ISSUE THREAD

**Issue by jannnfe** [arendst/Sonoff-Tasmota#1255]
Hello,
i want to use two Reed Sensors on one Sonoff Basic. So I found out, that I can connect second Reed Sensor to GPIO4. The first ist connected at GPIO14.
The Problem is, that every time i trigger the second Reed Sensor on GPIO4 the Sonoff reboots and reboots and reboots on his own.
Maybe I have a soldering issue? Please have a look at this picture:
![img_0302](https://user-images.githubusercontent.com/30130742/33243079-435d3df4-d2df-11e7-92fc-fa4b631c1af3.JPG)

Thanks for your help :)

**Comment by gajotnt** [comment]
Well it looks like really bad soldering.
You joined several pins on the chip...

**Comment by ionciubotaru** [comment]
try gpio 1 or 3 (tx/rx) instead of gpio14 - is easier to solder

**Comment by jannnfe** [comment]
I thought it was my soldering. but that was really hard to get such a small pin ran. I will try to completely remove the solder joint.
Thanks for the information with RX and TX. I did not know that this is possible. Of course that is much easier.
Thanks everyone!

**Comment by gajotnt** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/GPIO-Locations
