### ISSUE TITLE
Sonoff Brdige with Sonoff DW1

### ISSUE THREAD

**Issue by Odianosen25** [arendst/Sonoff-Tasmota#1261]
Hello @arendst ,

Please this is not an issue, but more like questions.

- I have just ordered a Sonoff bridge with a few DW1 Door/window sensors. I wish to confirm if after loading your firmware, I will be able to use the door sensors? 

- Are there extra settings I will need to do, that you recommend that I do before it works? 

- How many of such sensors can I have on a single bridge?

- What security should I put in place to ensure it all works fine.

Kind regards

**Comment by ChukXP** [comment]
I've tested few days ago this firmware on Sonoff RF bridge. So I can confirm that when device send RF code, You've got mqtt message with this code from RF Bridge. So, I suppose that You can have any quantity of sensors.

**Comment by Odianosen25** [comment]
Hello @ChukXP,

Oh thanks for the response, very much appreciated.

Kind regards

**Comment by oriolism** [comment]
@ChukXP Do you receive an rf code when the sensor opens and another when the sensor is close or just one?

**Comment by maartenpaauw** [comment]
@oriolism I connected my DW1 sensor to the Sonoff RF Bridge. I only receive a RF code when the sensor opens. Not when it close.

Anyone knows how to fix this?

**Comment by Daemonentreiber** [comment]
@maartenpaauw This sensor doesnt send a signal when its closed.

**Comment by charinduedirisuriya** [comment]
Is it possible to identify which sensor got triggered. Assume i attach one sensor to my front door and save it at key 1, and another sensor to my back door and save that as key2. Will tasmota be able to differentiate which door sensor sent the code, becouse both the sensors might send the same code. Does the sensors send same code or how exactly does the rf in the sensor work?

**Comment by ascillato** [comment]
Hi @roger443 

How do you modify the DW to be normally closed?

**Comment by xFvPx** [comment]
@roger443 how to reverse the operation ?

**Comment by pedrosimao** [comment]
I bought six DW1 sensors thinking it also signal when the window / door is closed, and I am quite disappointed. For me this is necessary because I want to know the current state of the window. As I live on the ground floor it would be easier for me than checking each individual window before leaving home.
Do you know another good alternative to Sonoff DW1 (maybe working with Sonoff bridge) that has both close and open signal?

**Comment by ascillato** [comment]
Hi, keep searching in issues. This issue is super old. In another issue of DW1 there is a link to an alternative sensor.

**Comment by daueee** [comment]
Do you now the alternative sensor?

**Comment by ascillato** [comment]
Search for KERUI D026 window sensors

**Comment by barriethesen** [comment]
On eWeLink the DW1 does not send out a notification until the sensor opens and then closes.  This is problematic because if an intruder just opens the door but does not close it there is no notification.  If the RF Bridge was Tasmotized I would think the same behaviour would repeat.
