### ISSUE TITLE
DS18B20 new JSON format is pain on parsing because of "-" in identifier

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#1268]
Hi,

I may not know, but parsing a "-" in an identifier does not work really well. It will be recognized as an operator.
This is not working:
`JSON.parse(input).DS18B20-3.Temperature;`

if we can replace with a _ everything would be fine:
`JSON.parse(input).DS18B20_3.Temperature;`

**Comment by davidelang** [comment]
you need something to tell your code that DS18B20-3 is one entity. I don't know 
what language you are using, but putting {} around them or using quotes is a 
common method

**Comment by arendst** [comment]
From www.json.org:

![image](https://user-images.githubusercontent.com/11044339/33340713-2efff67c-d47d-11e7-95a1-f8be2a8b6d44.png)

Problem regarding the dash have been solved by people using more DHT's or AM2301's like:
```
"AM2301-12":{"Temperature":22.3,"Humidity":48.0},"AM2301-14":{"Temperature":21.8,"Humidity":47.5}
```
Search around here for a solution.

**Comment by stefanbode** [comment]
As you can see Ivuse plain Javascript. This does not like the -   Also putting “ around did not help. Will try with { but assume this is also a problem. Also tried \ to mask the -. Also no success. Any idea, how the JavaScript should look like.

**Comment by arendst** [comment]
Google is your friend https://stackoverflow.com/questions/13869627/unable-to-access-json-property-with-dash

**Comment by AlexSwensen** [comment]
This is not an issue with the firmware, but an issue with understanding its api.

This issue should be closed.
