### ISSUE TITLE
Webfrontend: Add footer with the usual info

### ISSUE THREAD

**Issue by ThomDietrich** [arendst/Sonoff-Tasmota#1275]
I just realized that the webfrontend doesn't actually contain any product information. No GitHub link, no author details, the page doesn't even mention "Tasmota" once. Is that intentional? 

I propose to add a static footer with "Sonoff-Tasmota", the installed firmware version and the GitHub Repo Link.

The same goes for the page title. Currently it states "Main Menu" or similar. Pretty useless with multiple tabs open. Consider "Main Menu - ${Friendly Name} - Sonoff Tasmota Module".

**Comment by arendst** [comment]
Great idea at the cost of about 250 bytes:

![image](https://user-images.githubusercontent.com/11044339/33385585-3e146e3e-d529-11e7-9866-65c53e245fe4.png)

**Comment by lgnd33** [comment]
or additional 41 for "<a href="http://bit.ly/2ndbFAt">GitHub</a>"

you should probably register the shortURL, to make it permanent.

**Comment by arendst** [comment]
As always there is more going on beneath the waves ;-)
```
<div style='text-align:right;font-size:11px;'><hr/><a href='https://github.com/arendst/Sonoff-Tasmota' target='_blank' style='color:#aaa;'>Sonoff-Tasmota {a} by Theo Arends</a></div>
 ```
Where {a} is being replaced by the version number.

I think I have to settle with that...

**Comment by lgnd33** [comment]
Do a URL shortener - that should save few bytes here and there.

**Comment by ThomDietrich** [comment]
LGTM. Thanks!
