### ISSUE TITLE
Sonoff Dual occasional switching issue channel 1 when both channels are switched simultaneously

### ISSUE THREAD

**Issue by mogwai2** [arendst/Sonoff-Tasmota#1278]
Hi,

I use several Sonoff Dual's to switch my outdoor lighting. Multiple channels are switched in one "group" in domotics. Now I notice that occasionally "Channel 1" doesn't switch off, while the tasmota GUI reports OFF. Apparently the serial commands from the ESP to the SIL F330 can get messed up when you switch 2 channels simultaneously via MQTT. I saw the problem with both version 5.8.0 and 5.9.1 and also on 2 different modules. It always happens to channel 1, not 2. I'm sure all serial logging is off, so that cannot be the problem.

Kind regards and thanks for creating this great firmware 👍

**Comment by janmashat** [comment]
> the problem is caused by the Energy Saving

https://github.com/arendst/Sonoff-Tasmota/issues/1459#issuecomment-361692501
