### ISSUE TITLE
sonoff RF bridge IDX MQTT domoticz

### ISSUE THREAD

**Issue by skorc99** [arendst/Sonoff-Tasmota#1281]
Hello,
i managed to learn codes- now i would like to use it with domoticz.
I am using IDx on basic module and it is working with no problem.

How to use RF bridge with MQTT domoticz.
My setup is 
RFkey1 - sensor i recieve mqtt message in console -alert
RFkey2- ON- outlet 
RFkey3-OFF-outlet
.
.
If i use web outlet on/off is working.

Thanks for help..

U

**Comment by tukestolo** [comment]
Hello do you figure how resolve this? I have the same problem :(
