### ISSUE TITLE
Dash button like device?

### ISSUE THREAD

**Issue by lobradov** [arendst/Sonoff-Tasmota#1284]
I recently found out about this device: 
https://www.aliexpress.com/item/RAK413AS-UART-serial-port-AT-commands-low-power-consumption-WiFi-module/32814812323.html

It's a nicely packaged device with 4 buttons and it's own battery, that can act as Amazon Dash replacement. Unfortunately for us, it's running RTL8711 instead of ESP8266, which makes it incompatible with Tasmota.

Anyone knows any alternative or similar button-device that uses Espressif chips, so that we can make Tasmota work with it?
I can build similar thing with Wemos, but this one really looks nice and has battery already packaged. I can't ever build such a nice housing on my own.

**Comment by ionciubotaru** [comment]
https://www.aliexpress.com/item/30-energy-saving-CC2541-ibeacon-module-Bluetooth-4-0-module-BLE-ibeacon-for-indoor-navigation/32753259856.html?spm=2114.10010108.1000014.5.5c280227DIJH8P&traffic_analysisId=recommend_3035_3_83054_iswinstore&scm=1007.13338.83054.0&pvid=694f0f78-9366-4aa6-bbc3-5b11feeb9dfd&tpp=1
