### ISSUE TITLE
Sonoff POW Domoticz

### ISSUE THREAD

**Issue by tobang** [arendst/Sonoff-Tasmota#1285]
I am no able to retrieve the power usage in Domoticz. I am using Electric (Instant + Counter), but no data is sent to Domoticz.

Current, Voltage and Power are working fine.

On the Sonoff i set the idx on Sensor idx 6 Count

Torben

**Comment by arendst** [comment]
Tasmota sends this to Domoticz:
```
      DomoticzSensorPowerEnergy((uint16_t)watts, stotal_energy);  // PowerUsage, EnergyToday
      DomoticzSensor(DZ_VOLTAGE, svoltage);  // Voltage
      DomoticzSensor(DZ_CURRENT, scurrent);  // Current
```
and my Domoticz config looks like:

![image](https://user-images.githubusercontent.com/11044339/33445040-23e85934-d5fc-11e7-85e3-3457f4404840.png)

Resulting in this:

![image](https://user-images.githubusercontent.com/11044339/33445077-45bb2a78-d5fc-11e7-85d2-3789f109a225.png)

**Comment by tobang** [comment]
Thank you, got it working looking at your screen dumps. 

Thank you,
Torben
