### ISSUE TITLE
DST for Israel

### ISSUE THREAD

**Issue by issacg** [arendst/Sonoff-Tasmota#1286]
Hi,

I'm trying to figure out how to set TIME_DST for Israel.

Israel has very odd timing for DST.  [According to Wikipedia](https://en.wikipedia.org/wiki/Israel_Summer_Time#2013.E2.80.93Present), the current definition is the Friday before the last Sunday in March at 02:00

Any pointers as how to set that in TIME_DST?

**Comment by arendst** [comment]
You must be able to make the change in user_config.h and re-compile.

**Comment by issacg** [comment]
Yes, I already understood that.  I'm having trouble finding what powers the DSL for the summer-time rules.  I can make it the last sunday in march at 02:00 really easily, but my question is how would I make it the *Friday before* the last Sunday in March?

**Comment by arendst** [comment]
Ah. You can't. Time to move ;-)

**Comment by arendst** [comment]
I understand the problem and for now the only solution I see is to configure either the last friday OR the last sunday in March. During these few days your time will be off but after a week it should be fine again as it must be DST time then.

I expect major coding additions to tackle this anomaly (as I see it). Sorry.

**Comment by arendst** [comment]
From this table

![image](https://user-images.githubusercontent.com/11044339/33517673-9d840864-d788-11e7-86db-ef0d228c5e9a.png)

You could choose to set DST for the next year:
```
#define TIME_DST               North, Fourth, Fri, Mar, 2, +180 
```
and after that for the next 5 year set it to:
```
#define TIME_DST               North, Last, Fri, Mar, 2, +180 
```

**Comment by issacg** [comment]
Thanks.  Just wanted to make sure I wasn't just unaware of some cool macros.

You're right that it's anomoly - summer time rules have always been messed up here ;)
