### ISSUE TITLE
ADS1115: Current limit is only +- 2V. "Dangerous" and should change

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#1289]
In the function `Ads1115StartComparator `there is a default used for the voltage range that can be measured. Because most devices run with 3.3 or even 5V the current default:
**ADS1115_REG_CONFIG_PGA_2_048V** = +-2V
is not a good idea. The used default in the i2cdev library is **ADS1115_REG_CONFIG_PGA_6_144V**. I would suggest using this also in the xns_12_ads1115.ini as default. 
In this case, 3.3V and 5V is no problem. The resolution is 0.1875mV, which should be ok for most cases

**Comment by arendst** [comment]
Thnx. I will change in nxt (pre)release.

**Comment by stefanbode** [comment]
Works!
