### ISSUE TITLE
LED Configuration

### ISSUE THREAD

**Issue by snagytx** [arendst/Sonoff-Tasmota#1293]
Hello,

I have Sonoff Basic. Is it possible to have the LED On file the switch is off and Off when the switch is On? This way I can see where the switch is in the dark.

I checked https://github.com/arendst/Sonoff-Tasmota/wiki/Commands but I can't find anything that would make it reverse to what it currently is.

Thank you

**Comment by arendst** [comment]
It's currently the default for touch devices only and cannot be chhanged by the user.

As a workaround you could select the wemos module and choose the inverted led option from what is used for a Sonoff basic. See file sonoff_template.h what gpio functions to choose.

**Comment by carloszacu** [comment]
any solution fot this yet?, I have a sonoff T1 3CH that I need to invert the led state (like a normal wall switch)
