### ISSUE TITLE
4ch pro, one channel self activates constantly 

### ISSUE THREAD

**Issue by doppiaemme** [arendst/Sonoff-Tasmota#1299]
Hi, 

the first channel on a 4ch pro constantly turns on by itself.
the selected mode is inching with 0.5s timer.

I've tried flashing the board several times but it's still the same.
Can it be an hw issue? 

thanks

**Comment by ottoplanet** [comment]
Hi,

I have somthing similar on my 4ch pro. Channel 4 is toggeling every 15 min in minute 27, 42,57 and 12. Even if I remove the power, self switching chennel 4 at minute 27, 42,57 and 12.
What can it be?

Thanks

**Comment by ottoplanet** [comment]
My problem was solved. It seems, that I had activated the 433MHz remote command and my 4ch received an signal from my home automation system

Thanks

**Comment by doppiaemme** [comment]
Ok this is interesting, 
how was the 433MHz channel activated? was it enabled by default after reflashing? and how did you disable it?
Still I wonder even of it was activated how it could pick up some signals that triggered it
