### ISSUE TITLE
Which MQTT Broker?

### ISSUE THREAD

**Issue by timhng** [arendst/Sonoff-Tasmota#1301]
The Wiki states: _To use HomeBridge with Sonoff-Tasmota you need to have installed the broker MQTT._ Is this something that I need to install on my Raspberry Pi? Which plugin do you recommend? There appears to be a number of MQTT plugins to choose from!

**Comment by sreichholf** [comment]
mosquitto is probably the most famous mqtt broker :)

**Comment by stefanbode** [comment]
Yes and all help also here on the WIKI is describing the solution with mosquitto commands. As a convenient client, I suggest MQTT-SPY. All opensource you can get from google.
