### ISSUE TITLE
sonoff Bridge rfcode Hex and Dec

### ISSUE THREAD

**Issue by sammy2360** [arendst/Sonoff-Tasmota#1303]
hi, is there a way to change the format of the data returned on mqtt when an rf code is received?`tele/sonoffBridge/RESULT = {"RfReceived":{"Sync":9580,"Low":310,"High":870,"Data":"83008F","RfKey":"None"}}` 
for example above the Data is in HEX format 83008F but if i want to send an rf code in HEX `cmnd/sonoffBridge/RfCode` the data needs prefixing with #  so a payload would be `#83008F` this is difficult to use in home assistant as the state and command payloads are required to be identical. it makes more sense to me to keep the data formats the same weather hex or dec or be able to choose. thanks in advance for any respose.

**Comment by arendst** [comment]
#1290
