### ISSUE TITLE
{"RestartReason":"External System"}-Sonoff T1 2CH Module

### ISSUE THREAD

**Issue by mushudog** [arendst/Sonoff-Tasmota#1306]
Hi,
I have several Sonoff modules, running Sonoff-Tasmota 5.10.0a by Theo Arends.

On the 2CH Touch modules they restart randomly when an mqtt request is triggered. 
Wifi is available, MQTT server is running. Any idea what would be the cause?

17:53:35 MQT: tele/baiedormitor/INFO3 = {"RestartReason":"External System"}

**Comment by davidelang** [comment]
it's probably a hardware problem on the modules.

just to be sure, set logging to the highest detail level and watch what gets 
logged as it hits whatever is causing it to restart (watching the logs via the 
serial port would be the best)
