### ISSUE TITLE
What does sonoff C2K and C2D do?

### ISSUE THREAD

**Issue by hamwong** [arendst/Sonoff-Tasmota#131]
on some of the sonoff product, PCB also have VCC C2K C2D GNC, may I know what does it do?
I can't found any information regarding this, please share if you know.

**Comment by Chinchilla** [comment]
Those are the reprogramming pins for the [C8051F330](https://www.silabs.com/documents/public/data-sheets/C8051F33x.pdf) which is used as a secondary processor on some of the modules.

**Comment by hamwong** [comment]
thanks for your information, so does these pin only for reprogram F330 and it's not for general usange?

**Comment by Chinchilla** [comment]
No, not really for general use. You can see where they're connected on this [schematic](https://www.itead.cc/wiki/images/1/1d/Sonoff_Dual_View.pdf).

**Comment by hamwong** [comment]
Thank you.
