### ISSUE TITLE
Support for TSL2561

### ISSUE THREAD

**Issue by dawsmac** [arendst/Sonoff-Tasmota#1311]
Hi Guys

I might have this wrong, I noticed that the TSL2561 module is supported, so I followed what I thought was correct but this has not enabled the sensor. 

Downloaded the TSL2561 library and copied to this location ~\Work Folders\Documents\Arduino\libraries\TSL2561

Did not changes to the code and just recompiled I as was of the understanding this would get included.

I and trying this on my MakerHawk D1 Mini NodeMcu. any help would be amazing thanks!.

**Comment by arendst** [comment]
Give the latest version a try and feedback the results please.
