### ISSUE TITLE
webserver access.

### ISSUE THREAD

**Issue by sam9s** [arendst/Sonoff-Tasmota#1312]
is there a way to edit the webserver properties, like what button to show, change button type, color, basically customize the webpage for tasmota. where is the webserver hosted?

**Comment by arendst** [comment]
Just take a fork and edit the webserver.ino file to your likings.

**Comment by sam9s** [comment]
ok cool , so that would be from within the Arduino sketch tool from where we upload the firmware in to sonoff right?

**Comment by arendst** [comment]
Correct

**Comment by sam9s** [comment]
Cool thanks  ... and BTW ultimate firmware .... :)

**Comment by sam9s** [comment]
issue resolved
