### ISSUE TITLE
sleep mode switches sporadically

### ISSUE THREAD

**Issue by thrusty66** [arendst/Sonoff-Tasmota#1319]
Hello, first of all, thank you very much for this project. Even someone without programming knowledge can build his Smart Home with it.
But now to my problem, I have two sonoff pow in the basement. Both versions run with version 5.8. 
Recently I set both to 50ms with the sleep command. Unfortunately I found out that both sonoff's turned on sporadically. After I had removed the sleep again, there was no more soradic power on.

**Comment by ionciubotaru** [comment]
Sleep mode is recomanded on battery operated devices. You have no reason to activate it on POW
