### ISSUE TITLE
Delay when using a switch on GPIO14

### ISSUE THREAD

**Issue by joaohess** [arendst/Sonoff-Tasmota#1322]
Issue #1068 is closed but I'm having the same trouble.

I'm using Sonoff basic to control the lights of my house and I connected my wall switch to GPIO14/Ground. Whenever I toggle the switch it takes up to 10 seconds for my lights to turn on/off. I'm running version 5.10.0 already.

What can it be?

**Comment by joaohess** [comment]
I'm still configuring my RaspberryPi with all my accessories, so there's no MQTT broker for now. They are working alone, only through the switch.

**Comment by davidelang** [comment]
You are probably running into the bug in the arduino network library that 
prevent anything else from happening while it is attempting to connect to the 
mqtt server.

**Comment by davidelang** [comment]
Then you need to disable the network, or disable mqtt so that the device isn't 
trying to connect to the MQTT server.

or just get the mqtt server online :-)

**Comment by joaohess** [comment]
@davidelang that's it. I've disabled the MQTT on the sonoff and now it works instantly. Thank you!
