### ISSUE TITLE
Broke the button, there's a way to switch to GPIO14

### ISSUE THREAD

**Issue by dboa** [arendst/Sonoff-Tasmota#1324]
I kinda broke the button and I wish to know how to overwrite from GPIO00 to GPIO14 on arduino IDE.

Is there a way?

**Comment by davidelang** [comment]
you would need to change the module type to wemos, then you can define any GPIO 
as any function.

**Comment by dboa** [comment]
@davidelang You're awesome.
It's doing exactly what I need.
Thank you so much

**Comment by morres83** [comment]
I have a question related to this topic:
Is the special button functionality (1-7 press for WIFI modes, reboot etc.) not statically mapped to GPIO0? Did it work with GPIO14?

Can the functionality be mapped to another switch (GPIO_SWT1)?
In my case the internal switch is not easy to access (physically), but I have an external switch (defined by GPIO_SWT1), which should trigger these events if necessary.
