### ISSUE TITLE
Console <RRGGBBWW>

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#1332]
Hello 
I have a flashed H801, but I can only change the colors from console like "color #ff0000"

how can I use RGBW?

What does < RRGGBBWW > payload mean?
I try "color < RRGGBBWW >" but:
RESULT = {"Color":"00FF00"}
I try "color < RGBW >" but:
RESULT = {"POWER":"OFF","Dimmer":0,"Color":"000000"}

Thank you.

5.10

**Comment by arendst** [comment]
The H801 module is default configured for RGB. You need to add one PWM channel in the module configuration page to get RGBW. I don't know which gpio to use but someone does...

**Comment by ageorgios** [comment]
It worked by setting
![screen shot 2017-12-10 at 9 15 22](https://user-images.githubusercontent.com/3126351/33802881-ac0c0b9a-dd8a-11e7-92c8-7e3b2af9a768.png)
using output W2

Thank you very much!
