### ISSUE TITLE
Sonoff POW improvement

### ISSUE THREAD

**Issue by ionciubotaru** [arendst/Sonoff-Tasmota#134]
I like to set a maximum power limit. For example:
I use a Sonoff POW to control a circuit. The user put more and more consumers on that circuit. When the power limit is reached for more than T seconds, Sonoff must open the relay and stop the circuit until user manual intervention (T seconds is important to avoid activation on spikes - engine start).
It will be useful to avoid dangerous situation, Sonoff will act as a smart fuse.

**Comment by arendst** [comment]
There is some functionality already available. Have a look at undocumented commands ``SafePower, SafePowerHold, SafePowerWindow, MaxPower, MaxPowerHold, MaxPowerWindow, MaxEnergy, MaxEnergyStart``
