### ISSUE TITLE
RFE: New device support

### ISSUE THREAD

**Issue by macemoneta** [arendst/Sonoff-Tasmota#1349]
There are in-wall switches which are marketed under several names: GRESATEK Smart WiFi Light, Laduo, Joso, Lyasi, DLX Control Solutions, DLX-KS602. Uses esp8285.

- The blue WIFI led is controlled by GPIO 13. The LED is on when the IO is LOW.
- The relay and the bulb LED are controlled by GPIO 12 – they are on when IO is HIGH.
- The capacitive touch switch is connected to GPIO 0 and the IO goes low when touched.

They currently support eWeLink.  Details from:
https://makingsomestuff.wordpress.com/2017/11/07/flashing-a-gresatek-smart-wifi-light-switch-with-an-esp8285-chip-or-joso-or-lyasi-or-dlx-control-solutions-dlx-ks602/

**Comment by arendst** [comment]
So using the Sonoff Touch module selection should satisfy your request as it is the perfect match.

**Comment by macemoneta** [comment]
Excellent, thanks!
