### ISSUE TITLE
Sonoff Basic GPIO14 not toggling

### ISSUE THREAD

**Issue by gid204** [arendst/Sonoff-Tasmota#135]
I'm having an issue with my SONOFF basic. 

Switch mode in user_config.h is set to toggle. I have it set to the sonoff basic module and gpio14 set to switch 1 in the web console configuration.

However, when I ground gpio 14 it acts as a pushbutton. i.e it'll change state for as long as I hold it but as soon as I let go it switches back.

Any help is greatly appreciated!

**Comment by hamwong** [comment]
use switchmode command

**Comment by gid204** [comment]
Hey thanks for your reply!
Sorry if this is a stupid question but what do you mean use the switch mode command?
I've got switch mode set to toggle in user_config.h ....

thanks!

**Comment by hamwong** [comment]
You may goto web-ui and type switchtopic command
Further detail may look here/wiki/commands

**Comment by hamwong** [comment]
I am not very good in English as its not my mother language, I don't know do you understand what I said or not?

**Comment by gid204** [comment]
I think I do understand, I will try again. Thank you!

**Comment by gid204** [comment]
I did as you said but it still does not work :(
I went to web UI > console and use switchmode<0>
but it still does not work :(
any other suggestions?

**Comment by hamwong** [comment]
no.... you miss something,
<0> means switch no. as you can max assign 4 switch,
you should first just type swichmode and see what it come out, 
it will tell you your current switch mode
than you should try with difference no. see which one is your want

**Comment by hamwong** [comment]
So You should do it as switchmode first, than it will tell you that your current mode like switchmode 0
Than you may try switchmode 1 to 4
