### ISSUE TITLE
PulseTime Help

### ISSUE THREAD

**Issue by aferraz** [arendst/Sonoff-Tasmota#1352]
Hi @arendst,
 in the wiki I can see:
PulseTime<x> | 1..111 | Set PulseTime for relay<x> with 0.1 seconds increment
-- | -- | --
PulseTime<x> | 112..64900 | Set PulseTime for relay<x> with 1 seconds increment starting with 12 seconds (113 = 13 seconds etc.)

so, from what I understand, a PulseTime of 123 should be 23 seconds.
Is this correct ?

I use Electrodragons for covers, I timed 23 seconds to have cover open/close.
However if I set pulsetime to 123 the relay stay open longer, I need to set pulsetime to 43 for a correct opening/closing.
 
Thanks
 Alessandro

**Comment by davidelang** [comment]
On Tue, 12 Dec 2017, Alessandro wrote:

> Hi @arendst,
> in the wiki I can see:
> PulseTime<x> | 1..111 | Set PulseTime for relay<x> with 0.1 seconds increment
> -- | -- | --
> PulseTime<x> | 112..64900 | Set PulseTime for relay<x> with 1 seconds increment starting with 12 seconds (113 = 13 seconds etc.)
>
> so, from what I understand, a PulseTime of 123 should be 23 seconds.
> Is this correct ?

yes

> I use Electrodragons for covers, I timed 23 seconds to have cover open/close.
> However if I set pulsetime to 123 the relay stay open longer, I need to set pulsetime to 43 for a correct opening/closing.

what shows up in the logs? do you have any communications problems with the mqtt 
server during this time? that can cause all processing to pause

**Comment by aferraz** [comment]
@davidelang I've done the tests by web interface because at first I thought about a mqtt problem.
Before using the pulsetime I used nodered giving the off command to the relay after n seconds, never had these problems.

Thanks

**Comment by davidelang** [comment]
if the device is trying to reconnect to the mqtt server, everything else pauses 
while it is trying. it doesn't matter if you are sending a command via serial, 
web, mqtt, or anything else, _everything_ stops

This is why I asked about the logs during this time.

**Comment by aferraz** [comment]
Thanks @davidelang, I checked the logs in console and did not disconnect from mqtt.
However, in the past I had tried the pulsetime and it worked as written in the wiki, but I did not use it because there was not yet the interlock function. 
I do not remember what version I tried but it worked on the same devices I use now.

**Comment by davidelang** [comment]
are there any logs of anything happening during the timeframe? a pulsetime of 43 
should only be a delays of 4.3 seconds, if it's delaying for 23 seconds 
something is going wrong, please set debugging to 'more detail' and see if there 
is anything showing up.

**Comment by aferraz** [comment]
@davidelang I think I understand where the problem is. I have set sleep to 250ms.
So, with a sleep 250 a pulsetime of 43 become about 20 seconds

**Comment by stefanbode** [comment]
Why did you use a sleep? I Do Not See any benefit from using this. And yes, this is likely to cause the issue.

**Comment by aferraz** [comment]
to reduce electricity consumption
