### ISSUE TITLE
A more accurate reporting of energy consumed for Sonoff Pow

### ISSUE THREAD

**Issue by MacWyznawca** [arendst/Sonoff-Tasmota#136]
Can you add more decimal places when reporting today and yesterday kilowatts?
Saving data in the file and more accuracy would need to setting the hourly electricity consumption by "eco" devices.

Lines: 531 and 532 in sonoff/xsns_hlw8012.ino

void hlw_mqttStat(byte option, char* svalue, uint16_t ssvalue)
{
  char stemp0[10], stemp1[10], stemp2[10], stemp3[10], speriod[20];
  float ped, pi, pc;
  uint16_t pe, pw, pu;

  hlw_readEnergy(option, ped, pe, pw, pu, pi, pc);
  dtostrf((float)sysCfg.hlw_kWhyesterday / 100000000, 1, 5, stemp0); // more precision
  dtostrf(ped, 1, 5, stemp1); // more precision
  dtostrf(pc, 1, 2, stemp2);
  dtostrf(pi, 1, 3, stemp3);
  snprintf_P(speriod, sizeof(speriod), PSTR(", \"Period\":%d"), pe);
  snprintf_P(svalue, ssvalue, PSTR("%s\"Yesterday\":%s, \"Today\":%s%s, \"Power\":%d, \"Factor\":%s, \"Voltage\":%d, \"Current\":%s}"),
    svalue, stemp0, stemp1, (option) ? speriod : "", pw, stemp2, pu, stemp3);
#ifdef USE_DOMOTICZ
  dtostrf(ped * 1000, 1, 1, stemp1);
  domoticz_sensor4(pw, stemp1);
#endif  // USE_DOMOTICZ
}

**Comment by arendst** [comment]
Implemented as a define in user_config.h in version 4.0.0 just released
