### ISSUE TITLE
MagicHome OTA?

### ISSUE THREAD

**Issue by edit21** [arendst/Sonoff-Tasmota#1375]
Hi All, My MAgicHome device came with no rx/tx pads :( just wondering if anyone knows if this can be flashed OTA?
Kinda stuck otherwise!

Thanks for the epic code!

James

**Comment by edit21** [comment]
Found the new pinout - will add to the Magic Home page :)

**Comment by ageorgios** [comment]
Is any OTA method available?
The pins on the chips are too risky for me to solder.

**Comment by lobradov** [comment]
Nope, soldering only :/

**Comment by davidelang** [comment]
well, wired anyway (you can use pogopins or just hold the wires in place while 
flashing, you don't _have_ to solder them.

Once Tasmota is installed, you will be able to upgrade over the network, it's 
the transition from the stock firmware to tasmota that will require wires
