### ISSUE TITLE
Support for LED State "mirroring"

### ISSUE THREAD

**Issue by dieterrosch** [arendst/Sonoff-Tasmota#1381]
Hi Theo,

Firstly, thank you for this incredibly useful firmware.

On to my question:

I see a number of questions where people are asking how to send the current LED1 state to an external LED, for example:

https://github.com/arendst/Sonoff-Tasmota/issues/716
https://github.com/arendst/Sonoff-Tasmota/issues/977
https://github.com/arendst/Sonoff-Tasmota/issues/1374

There are other tickets with relatively similar requirements.

I've been thinking about this, and the way I currently do this in my Sonoff Basic is by changing the SetLedPower() function as follows:

````
void SetLedPower(uint8_t state)
{
  if (state) {
    state = 1;
  }
  digitalWrite(pin[GPIO_LED1], (bitRead(led_inverted, 0)) ? !state : state);

 // ****************************** ADDITIONAL CODE ******************************
  //If this is a Sonoff basic, put LED2-4 in "follow" mode, i.e. follow the state of LED1.
  //On the Sonoff basic, only one power LED is available, so LED2-4 doesn't get used anyway,
  //and it is often useful to mirror or invert the state of LED1 to an external LED or set of LED's.
  //This change also honours the INVERTED option of LED2
  if (SONOFF_BASIC == Settings.module) {
    for (byte i = 1; i < MAX_LEDS; i++) {
      if (pin[GPIO_LED1 + i] < 99) {
        digitalWrite(pin[GPIO_LED1 + i], (bitRead(led_inverted, i)) ? !state : state);
      }
    }
  }
 // ****************************** END ADDITIONAL CODE ******************************  

}
````

While this works for me for now, ovbiously it is less than ideal, since this means one cannot set the state of LED2-4 via MQTT. 

The cleanest way I can figure out to do this, would be to add a uint8_t  ledmode (or a uint8_t       ledmode[MAX_LEDS]; ) to settings.h, and allow the bits to be set via a command, similar to switchmode etc.

That would then change  the code above to something like below (assuming ledmode is defined as uint8_t       ledmode[MAX_LEDS]).

````
void SetLedPower(uint8_t state)
{
  if (state) {
    state = 1;
  }
  digitalWrite(pin[GPIO_LED1], (bitRead(led_inverted, 0)) ? !state : state);

 // ****************************** ADDITIONAL CODE ******************************
  //If this is a Sonoff basic, put LED2-4 in "follow" mode, i.e. follow the state of LED1.
  //On the Sonoff basic, only one power LED is available, so LED2-4 doesn't get used anyway,
  //and it is often useful to mirror or invert the state of LED1 to an external LED or set of LED's.
  //This change also honours the INVERTED option of LED2
    for (byte i = 1; i < MAX_LEDS; i++) {
      if (pin[GPIO_LED1 + i] < 99 && Settings.ledmode[i-1] == MIRROR_LED1 ) {
        digitalWrite(pin[GPIO_LED1 + i], (bitRead(led_inverted, i)) ? !state : state);
      }
  }
 // ****************************** END ADDITIONAL CODE ******************************  

}
````

The important change is:

 if (pin[GPIO_LED1 + i] < 99 **&& Settings.ledmode[i-1] == MIRROR_LED1** ) { 

I am happy to make the above changes, test and submit a pull request, if this is something you are willing to consider?

**Comment by xeroiv** [comment]
It would be useful to control both the brightness and trigger of the external LED (always on or some defined brightness level when the relay was on and a different brightness when the relay was off).
