### ISSUE TITLE
Switchmode and gpio config to user_config.h

### ISSUE THREAD

**Issue by mtfurlan** [arendst/Sonoff-Tasmota#1388]
I'm working with a large number of tasmota devices, and one thing I've been having an issue with is devices that require commands sent to them after they are programmed, like for setting gpio mode.

I have a script that sets a lot of other things on a per-device basis, but I haven't made the script do anything more than just upload the new binary, so I end up forgetting to set switchmode or gpio mode.

Could those get moved into `user_config.h`?
Also `MODULE` and `WIFI_HOSTNAME` would be nice, but `sed` is working fine for that.

For reference, this is how I'm currently programming my tasmota devices: https://github.com/i3detroit/Automatic-IoT-module-programming/blob/master/tasmota.pl
And this is my list of devices: https://github.com/i3detroit/Automatic-IoT-module-programming/blob/master/tas.tsv

**Comment by mscreations** [comment]
I too am interested in having WIFI_HOSTNAME in user_config.h. I can never remember the end of the MAC address when I'm trying to type in the hostname, so I prefer it to be set to %s. It'd be nice if this didn't require me to change any other files than user_config.h
