### ISSUE TITLE
Mesh

### ISSUE THREAD

**Issue by kiralikbeyin** [arendst/Sonoff-Tasmota#139]
@arendst Do you have any plan about Mesh network?

**Comment by davidelang** [comment]
On Thu, 2 Mar 2017, kiralikbeyin wrote:

> @arendst Do you have any plan about Mesh network?

I'm not him, but I would not expect it. Mesh networking requires a lot of 
resources, and the ESP8266 is very limited. We are already not getting features 
added to this beacuse they would eat up too many resources.

David Lang

**Comment by arendst** [comment]
As David noted correctly I do not plan changes regarding Mesh network as resources are scarce.

Keeping the thing up and running is becoming challenging already with just a simple webserver active...
