### ISSUE TITLE
Sensor polling time

### ISSUE THREAD

**Issue by Joeyhza** [arendst/Sonoff-Tasmota#1392]
Hello Again

perhaps I'm missing the obvious - if so please forgive me .

I've notices on my sensors that they are only updating every so often on my Domoticz interface. Usually the sensor reading timestamps are hours behind. Is there any way to check/ change the polling frequency on the console? I've gone through the Tasmota commands and can't find any reference to it.

**Comment by davidelang** [comment]
the sensor data is reported every 'teleperiod', by default every 300 seconds. 
This can be set to anything down to 10 seconds.

**Comment by gajotnt** [comment]
TelePeriod |   | Show current telemetry period in seconds
-- | -- | --
TelePeriod | 0 / off | Disable telemetry messages
TelePeriod | 1 | Reset telemetry period to user_config.h (TELE_PERIOD)
TelePeriod | <secs> | Set telemetry period between 10 and 3600 seconds

**Comment by Joeyhza** [comment]
Thank you very much
