### ISSUE TITLE
Support of PZEM-004 modyficatino possibility

### ISSUE THREAD

**Issue by roblad** [arendst/Sonoff-Tasmota#1393]
Hi,

Could you add possibility to add 3 virtual TX/RX for PZEM-004 for usage it as 3 phase measure ? See the project where 4 GPIO can be used for measure 3 phases based on 3 PZEM-004.

https://github.com/apreb/eNode

and that:

https://github.com/olehs/pzem004t

https://www.letscontrolit.com/forum/viewtopic.php?t=2595&start=20

**Comment by arendst** [comment]
Nope. This is it.

**Comment by gajotnt** [comment]
Use 3 sonoffs :P they are dirt cheap

**Comment by roblad** [comment]
Hi,

There is last option :-), but if there is possibility to clone ino file and assignment some GPIO as soft serial it could be nice, because it could be very helpfully for 3 phases energy measure as emon :-)

**Comment by roblad** [comment]
Hi,

There is last option :-), but if there is possibility to clone ino file and assignment some GPIO as soft serial it could be nice, because it could be very helpfully for 3 phases energy measure as emon :-)
