### ISSUE TITLE
Interlock command

### ISSUE THREAD

**Issue by calcipher49** [arendst/Sonoff-Tasmota#1403]
Would it be possible to have a command 'Interlock'
Same as SetOption14, but more explicit

Also (much more complicated request), on 4CH/4CH Pro, it should be nice to have separate interlock commands for the 2 pairs of relays, ie interlock relay1 and 2, and separately interlock relay 3 and 4.

Thanks.

**Comment by alakdae** [comment]
Would this be the same behavior as in my issue?
https://github.com/arendst/Sonoff-Tasmota/issues/1423

**Comment by junior013** [comment]
@alakdae I think, that's not the same.

I prefer too the 2 pairs of interlock. I want to control 2 independent shutters motors with a 4ch
