### ISSUE TITLE
Sonoff basic with  DS18B20 , temperature adjust

### ISSUE THREAD

**Issue by sp2003** [arendst/Sonoff-Tasmota#1432]
it's possible to adjust temperature?
I need to add 2°C to detected temperature

**Comment by ionciubotaru** [comment]
Do this in you HA, there is no reason to "adjust" temperature in Tasmota

**Comment by sp2003** [comment]
merry xmas!

not exactly, because i use sonoff's temperature in domoticz and other system. if sensor is modifiable, all systems is ok

**Comment by l1q1d** [comment]
I agree with sp2003, an additional command to adjust the temperature offset could be really useful.
I see that different sensor even in the same room show different temperature.

**Comment by fennec622** [comment]
Yes please possible adjust temperature
domoticz adjust value don't work with mqtt domoticz/in

**Comment by ascillato2** [comment]
Hi,

You can use rules for adjusting temperature and then publishing to a topic.

See https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#8-arithmetic-commands-to-be-used-with-vars

Thanks

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please reopen if needed. Thanks.
