### ISSUE TITLE
Hue emulation works with Alexa but she says, "device is not responding"

### ISSUE THREAD

**Issue by halpz** [arendst/Sonoff-Tasmota#1434]
the sonoff works as expected, for example when I say, "Alexa, lights on" the lights turn on, but Alexa goes on to say "Lights isn't responding" - I think this is because it takes a while for the 'ON' status to be delivered to the echo and alexa thinks there is a problem?

anyone else had / solved this issue?

Thanks

**Comment by Frogmore42** [comment]
I use ha-bridge and have it configured to send mqtt commands to turn on/off things.  I did this because I had a light that was not hue capable but did support mqtt (with another gateway).  I have not tried the emulation with Tasmota.

**Comment by Frogmore42** [comment]
Looks like issue 1429 is similar and there is a fix there.  Or, you can use ha-bridge like I do.

**Comment by chunter1** [comment]
Got the exact same issue with version 5.10.0c

**Comment by arendst** [comment]
Pls try again with 5.10.0d and report progress.

**Comment by halpz** [comment]
issue remains on 5.10.0f

**Comment by KoLSMS** [comment]
Hello, same problem Here... :(

**Comment by geekypenguin** [comment]
Same issue on 5.11.1, the devices add no problem and Alexa app shows the status but when sending a command it says not responding

**Comment by KennethLavrsen** [comment]
I have same issue. 5.11.1b. Alexa can discover and show the device in Alexa app but it cannot control it. Alexa says that the device does not respond and nothing happens when to try and turn on or off. The app shows the correct on or off state of the device so it seems that Tasmota ignores the commands from Alexa

**Comment by TekMason** [comment]
Using Hue Bridge emulation on 5.11.1 the sonoff basic works as it should for me with one exception:
When I say, "Alexa, light on" the light turns on but Alexa replies with "light isn't responding".

**Comment by KennethLavrsen** [comment]
See my comment on what I think is a duplicate of this  https://github.com/arendst/Sonoff-Tasmota/issues/1639

**Comment by OFreddy** [comment]
See my last comment in #1639, this might also fix this issue.

**Comment by reloxx13** [comment]
Heya @arendst ,

it seems like alex ais not sending args to the webserver anymore when changing the state.

i made some debug outputs in the code and received this:

21:33:37 HTP: Hue API (/api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1)   
21:33:37 HTP: Hue POST args (NO ARGS)   
21:33:37 HTP: Hue API (/api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state)   
21:33:37 HTP: Hue POST args (NO ARGS)   
21:33:37 HTP: Hue API **E2** ()   
21:33:39 HTP: Hue API (/api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state)   
21:33:39 HTP: Hue POST args (NO ARGS)   
21:33:39 HTP: Hue API **E2** ()   
21:33:43 HTP: Hue API (/api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1)   
21:33:43 HTP: Hue POST args (NO ARGS)   
   
this is state switch on/off from alexa app
/api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1/state
   
this is request state of device (repeated while device open in alexa app)
/api/dIUhc67uzIHamo5mYqfQVjkjgRMsvkXeZo4u4Fg/lights/1
  
   
   
![grafik](https://user-images.githubusercontent.com/14855001/35355786-b4b17a36-014e-11e8-9df0-8999860e7bd1.png)
![grafik](https://user-images.githubusercontent.com/14855001/35355809-cfb791d0-014e-11e8-811b-e022f5913c18.png)

E2
![grafik](https://user-images.githubusercontent.com/14855001/35355878-0285d720-014f-11e8-9d23-340bf648b156.png)


i could not find out why the args are missing.

**Comment by koraysels** [comment]
issue is still here v5.12.0

**Comment by reloxx13** [comment]
we are on 6.3.0.x

**Comment by koraysels** [comment]
ha wow the OTA didn;t work then ... lets try that again !
