### ISSUE TITLE
Nothing happening after flashing Sonoff to MagicHome LED Controller - Only Blue Light

### ISSUE THREAD

**Issue by AzonInc** [arendst/Sonoff-Tasmota#1445]
After flashing Sonoff to the LED Controller, the blue LED lights up permanently. No blinking or something, just lighting up. There is also no Wifi Network created. Does someone has an answer for me?
![435e4644-95bf-48b1-9e4e-00d85af3feea](https://user-images.githubusercontent.com/11911587/34388104-1cc45d1a-eb32-11e7-9d06-61daf6ed2f97.jpg)

**Comment by timyboyb** [comment]
Hello, what was the solution? I have the same with the bigger version
