### ISSUE TITLE
Magic Home Module isn't found by Alexa

### ISSUE THREAD

**Issue by MischaTyde** [arendst/Sonoff-Tasmota#1447]
I flashed my Magic Home Controller with the latest version 5.10d and set emulation to Hue Bridge.
I'm not able to find the device in my Alexa app. If I configure the device to Sonoff Basic it will be found as a Switch. (If the switch is off the LEDs are red, if the switch is off the lights are green). Same for Emulation Belkin WeMo.

Is there actual no support for using Hue Bridge with Magic Home? If not, is it planned?

**Comment by AzonInc** [comment]
@MischaTyde How did you get that actually working? Have you changed the wifi settings before flashing?

**Comment by MischaTyde** [comment]
@AzonInc its not really working ;-) 
I set my wifi settings in user_config.h before flashing.

**Comment by AzonInc** [comment]
Thanks man - I got it setup for now - now theres only a problem with the gpio - magic home has only the option for 2 gpios

**Comment by AzonInc** [comment]
have you got the basic configuration for a magic home led controller?

**Comment by MischaTyde** [comment]
My one seems to be from Zengge:
![image](https://user-images.githubusercontent.com/32143692/34393934-67c968d6-eb56-11e7-8a18-0bd0044f5215.png)

**Comment by MischaTyde** [comment]
After flashing the latest version 5.10.0g my echo was able to find the controller, but it still not works.
Alexa shows the name "LED Controller 1CFA7" instead off my frindly name. And I'm still not able to switch the light on.
I faced an other issue. If I try to set some commands in the console from the Command table or via MQTT (e.g. Color, CT, Dimmer or Fade) I always get the error Unknown Command

**Comment by AzonInc** [comment]
try "setoption15 on" - this will enable the commands for you
