### ISSUE TITLE
Default relay power-on state

### ISSUE THREAD

**Issue by joshuagti** [arendst/Sonoff-Tasmota#145]
How is it possible to have the default state when the sonoff is powered up to be on? Example being that the sonoff is wired in after the light switch and sonoff currently remembers previous state which is no good when it is turned off at wall and off in my app. Is there a setting or some code I can add to have the default on?

Regards, Josh

**Comment by davidelang** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

look at the POWERONSTATE command

David Lang
