### ISSUE TITLE
Change connectivity settings without instant reboot

### ISSUE THREAD

**Issue by terba** [arendst/Sonoff-Tasmota#1453]
Hello,

I would like to change SSID and Password on all my installed sonoffs which have only MQTT support compiled in (no webserver). My idea was to issue `SaveData 0` on them to prevent instant reboot when changing SSID or Password (or MQTT settings). But doesn't worked, it rebooted instantly at the first command, so I was not able to change the password to pass the new SSID.

It would be great if I could change connectivity settings without connecting them one by one over serial. Any tips for this?

Thanks is advance!

P.S. I will now try to have the same wifi password on the two APs, change the SSID, reboot, change the password on AP2 to a new one, change the passwords on the sonoffs. But it is a bit complicated and even gets worse if you want to change MQTT settings also.

**Comment by arendst** [comment]
Look for the Backlog command which is very handy in this case...

**Comment by terba** [comment]
That's what i'm looking for! Thanks!

**Comment by avrhack** [comment]
@terba will you mark this as closed please if you've found your solution - helps keep focus on the real issues that are still needing attention......

**Comment by terba** [comment]
I wrote a short section about this [in the wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Features#send-multiple-mqtt-commands-at-once)
