### ISSUE TITLE
Setup password for WebAdmin, cant login

### ISSUE THREAD

**Issue by marcinbauer85** [arendst/Sonoff-Tasmota#1454]
I just setup a password for my first Sonoff Tasmota, but when I enter the credentials it doesn't work. Apart from my password, what should be the login? The device name, or what?

Thanks!

**Comment by marcinbauer85** [comment]
Pardon. Used the +4s reset method to reset to defaults. All working now :)

**Comment by JostAusSoest** [comment]
Same problem here...
What "name" is the login mask asking for?
I've only defined a web admin password.

**Comment by JostAusSoest** [comment]
OK, got it.
The username is predefined as "admin".
