### ISSUE TITLE
Feature request - integration with Telegram bots

### ISSUE THREAD

**Issue by ilya-fedin** [arendst/Sonoff-Tasmota#1456]
Hello! I think, would be the fine idea to add in a firmware a feature for device management of Sonoff through Telegram bots. It will give the chance to control from any point of the world to people with a private IP address, without rent of VPN or use of a cloud (eWeLink, etc.).

**Comment by gajotnt** [comment]
Use a program like Domoticz or HomeAssistant...

**Comment by cobra85ec** [comment]
You can also use node-red .. its great

**Comment by ilya-fedin** [comment]
No, I ask to make it without additional devices, such as Raspberry Pi or 24/7 running PC.

**Comment by cobra85ec** [comment]
Do u have a alexa.

**Comment by ilya-fedin** [comment]
@cobra85ec No, of course

**Comment by ilya-fedin** [comment]
Any progress?

**Comment by ascillato** [comment]
Do you have any explanation, code for esp8266, any example, link?

**Comment by ilya-fedin** [comment]
https://github.com/Gianbacchio/ESP8266-TelegramBot
https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot
https://create.arduino.cc/projecthub/JohnWick/telegram-bot-with-esp8266-dbada8
And more on Google

**Comment by ascillato** [comment]
Ok,

So, you want to use the instant messaging application for IOS and Android called Telegram with a chat bot inside Tasmota, right?

What do you want the bot to do? write directly to the Tasmota console?

**Comment by rustymh** [comment]
May I add to this topic. Telegram will be a great add-on. I'm hoping to add option myself. 

The idea will be to have a separate section for bot token and Webhook link for user input via Web-manager. 
In the code similar MQTT functions can be implemented for Telegram, commands like /on, /off and /toggle. 

This will enable the option to send basic function commands via telegram to the sonoff for switching when not close to the divice.

**Comment by ascillato2** [comment]
Hi,

This is a very nice idea but it is out of the actual scope of Tasmota (from [readme](https://github.com/arendst/Sonoff-Tasmota/blob/development/README.md)):

> Alternative firmware for ESP8266 based devices like iTead Sonoff with web, timers, 'Over The Air' (OTA) firmware updates and sensors support, allowing control under Serial, HTTP, MQTT and KNX, so as **to be used on Smart Home Systems.**

So, the label _requested feature (hold over)_ has been added in order to be taken into account.

Thanks for sharing your ideas.
