### ISSUE TITLE
timing between backlog command

### ISSUE THREAD

**Issue by shmrymbd** [arendst/Sonoff-Tasmota#1468]
1. hi i am sending this command - backlog power1 on;power1 off
what is the time delay in ms between these two command

2. if used pulsetime1=1 when send power1 on .. the delay is 100ms it is true?

Thanks

**Comment by arendst** [comment]
1. backlog delays always 100 ms between commands. You can use command delay within backlog to extent the time between two commands.

2. See wiki about pulsetime parameters and timing.
