### ISSUE TITLE
DHT11 Sensor

### ISSUE THREAD

**Issue by profesionalTI** [arendst/Sonoff-Tasmota#1475]
Hi, I have Tasmota 5.10.0f on my Sonoff Basic. I plug a DHT11 Sensor, I config it on GPIO14 but when the Sonoff Restart, I can't see Tº and H on the main home page of my sonoff, some can help me please?

**Comment by webtop** [comment]
Have you tried on another GPIO? That would give a good indication where the issue might lie. I have a DHT22 on a GPIO4, and the T & H come up immediately, so it should in your case.

**Comment by profesionalTI** [comment]
Thanks, I test, regards.

**Comment by profesionalTI** [comment]
The DHT22 si connect to the sonoff basic?

I can’t find DHT22 sensor on GPIO 14 in the new firmware 


Coordialmente,
Best Regards,

Marcelo A. Anuch Medina
Consultor de Empresas Público/Privadas
Ingeniero Comercial, MBA UDD
Business Management


🔒   La información contenida en esta transmisión es confidencial y está dirigida exclusivamente a el o los destinatarios indicados. Cualquier uso por otras personas que no sean sus destinatarios está sancionado por la ley chilena. Si ha recibido esta transmisión por error, por favor destrúyala y notifique al remitente si corresponde. Las opiniones expresadas en este correo son las de su autor y pueden no ser compartidas por la compañía. Marcelo A. Anuch Medina,  no asume obligaciones ni responsabilidades por el contenido de este correo. Tampoco garantiza que la transmisión de este correo sea segura o libre de errores, y en consecuencia, no responde por virus, pérdidas, destrucción, recepción tardía o incompleta.

🍀  Antes de imprimir este correo electrónico asegúrese que sea realmente necesario: Cuidemos el medio ambiente! Todos vivimos en un solo planeta.

**Comment by arendst** [comment]
@profesionalTI Try AM2301 option as it uses the same handler as the DHT22

**Comment by profesionalTI** [comment]
Thanks Theo, I try, regards


Coordialmente,
Best Regards,

Marcelo A. Anuch Medina
Consultor de Empresas Público/Privadas
Ingeniero Comercial, MBA UDD
Business Management


🔒   La información contenida en esta transmisión es confidencial y está dirigida exclusivamente a el o los destinatarios indicados. Cualquier uso por otras personas que no sean sus destinatarios está sancionado por la ley chilena. Si ha recibido esta transmisión por error, por favor destrúyala y notifique al remitente si corresponde. Las opiniones expresadas en este correo son las de su autor y pueden no ser compartidas por la compañía. Marcelo A. Anuch Medina,  no asume obligaciones ni responsabilidades por el contenido de este correo. Tampoco garantiza que la transmisión de este correo sea segura o libre de errores, y en consecuencia, no responde por virus, pérdidas, destrucción, recepción tardía o incompleta.

🍀  Antes de imprimir este correo electrónico asegúrese que sea realmente necesario: Cuidemos el medio ambiente! Todos vivimos en un solo planeta.

**Comment by Jabo889** [comment]
Hi, I have the same issue with DHT11  sensor on Wemos D1 Mini. Tried a few GPIO's with no luck. Therefore relay working fine. Do the Wemos D1 needs to be conected to MQTT?

Any help will be appreciated.

The below is attached screen shot. 

![a1](https://user-images.githubusercontent.com/35012992/34471397-7856b6a2-ef40-11e7-9a18-39b40b9cc37d.jpg)
![a2](https://user-images.githubusercontent.com/35012992/34471398-78703f78-ef40-11e7-9ef4-c2c04deafe7b.png)

**Comment by phdemartin** [comment]
Same isue witha sheild DHT11 or DHT22 on my Wemos D1 Mini.
