### ISSUE TITLE
RF Bridge Homebridge Scene

### ISSUE THREAD

**Issue by jannnfe** [arendst/Sonoff-Tasmota#1477]
Hello,
I have flashed my Sonoff RF Bridge and learned some old radio sockets. I can switch them all individually, but if I create a scene in Homebridge, which is to turn off all radio sockets, only one of the sockets of the RF Bridge is turned off. Is there any way that you can successfully create a scene that turns all outlets on and off?
Thanks

**Comment by MatzeJoerling** [comment]
You cannot start n RF signals at the same time, only one. So you need to delay the off / on commands for at least 0.5 to 0.7 sec per device. I have 1sec delay between the commands, to be save and that setup is working.

regards

**Comment by jannnfe** [comment]
Can you tell me how i can set this delay in Tasmota firmware?
What commands i have to use?
Thanks! :)

**Comment by MatzeJoerling** [comment]
nope, you have to do that in your home automation.
My node red looks like:
![screenshot 2017-12-31 13 04 51](https://user-images.githubusercontent.com/25864208/34461472-57f9ea7a-ee2b-11e7-8283-bdcc9c7c43a0.png)

Dash01 switches all on/off, Dash02 only Video Light.
