### ISSUE TITLE
Add a timer...

### ISSUE THREAD

**Issue by gemitro** [arendst/Sonoff-Tasmota#148]
It would be nice to add a timer to the configuration menu.

**Comment by arendst** [comment]
And what kind of timer do you want? Once a day at a certain time? Once after a certain time has elapsed?
What do want the timer to do? Switch one relay? Switch all relays? Just send a MQTT message?

Having answered these questions think about the code needed to implement and do not forget the user input validation...

Feel free to supply a pull request ;-)

**Comment by gemitro** [comment]
Personally i use the sonoff basic as a light switch. So a timer that switch on & off the light at certain times every day would be nice. At the moment i use crontab & mosquitto to a raspberry pi3.

Thanks for the response.

**Comment by arendst** [comment]
That's the correct way to go using an external manager like you do. I guess I leave it that way.

**Comment by Greg2002** [comment]
Now we already have I2C with a number of sensors. We can connect to I2C RTC (DS3231) and have very good RTC, timer, alarms, real EEPROM for config and so on. And it will work when you loose or have not at all internet connection. Let it be!?

**Comment by Greg2002** [comment]
It's realized in Russian project. Code: https://drive.google.com/open?id=0B7YhCK2ZNsYYcjg4VHhsTlNJODQ
and video (in Russian) https://www.youtube.com/watch?v=0gjqXPSK4yE

**Comment by davidelang** [comment]
I was actually about to start to look for timer functionality to turn something 
on for X amount of time and then turn it off.

I'm happy to do this with an external manager (I'm using openhab), but haven't 
yet done much looking to see the easiest way to do this.

**Comment by ChienTing** [comment]
If you can join the timing it is more perfect
Stand-alone device can be set when the time off
Do not add the host to do control

**Comment by redviper2100** [comment]
Are there any updates regarding this timer? Thanks.

**Comment by lobocobra** [comment]
ESPeasy has this in the code. You can program a little sketch there.
=> pro.... your device becomes more independent and even if your server is offline, it works
=> contra.... how are you go to keep this updated, with 40 devices all around?

**Comment by hsmptg** [comment]
Hi
I think a timer in the sonoff could be helpfull.
I use a sonoff to control a valve of an irrigation system of my garden.
Since it is in the limit of the wifi range I am always afraid of it do not receive the turn off command after being received sucessfully the turn on command.
With a timer I could send a command like: turn on and after nn seconds turn it off.
This way even in the case of losing the wifi connection after turn on the valve I would have certain that the valve would turn off!
Gotcha?
Regards,
Hélio

**Comment by davidelang** [comment]
already there, see the pulsetime command

**Comment by flexiti** [comment]
I see a lot of resistance  ;) before implementing a timer like
![timer](https://user-images.githubusercontent.com/11538048/31936380-b97692a8-b8b1-11e7-9173-e898ca429aec.jpg)

Since we have time from internet, **the feature can work locally, on the device,** and can be programmed with MQTT
eq,
`AllTimer on/off  (default off) `
and eg.
`Timer1:{Time:12:00, OnOff:(on/off/nop), Relay: 1, Replay:(on/off)}`
Timer2:.....  etc. 
There could be eg. 8 timers
If `Replay:off`, this would be a one time action
If someone wants to splash you can add days of the week ;)

ps. As we have access to the internet we have set the time correctly ... and if there is no internet .... nothing can be controlled, Sonoff-tasmota is useless   ;)

By the way, Sonoff-Tasmota is a great, good job 👍  :)

**Comment by davidelang** [comment]
network access != Internet access

**Comment by flexiti** [comment]
I feel sorry for everyone who has a network without internet access 😉

**Comment by davidelang** [comment]
most of the time it's deliberate. It narrows the attack range.

**Comment by flaotte** [comment]
I have timer request also. But it is a bit different timer I need. I want to have "maximum working time" timer. E.g. 4 hours. Just to have limit for devices that are not meant to be on 24/7.

**Requirements**:

- setup time in minutes;
- relay will be turned off after working for given time;
- if you will send on command during device is working, timer counter resets;
- drifting from exact timing is ok (+/-20%). It is not chronometer.

**optional**:
 - provide duration within on command. "switch on for 15 minutes";

I like to use default-on mode. It works fine with old light switches. You keep them on, and control light with sonoff, but you can always use hardware switch to control light or remove sonoff.
But... If something fails (power outage + server fails) when I on vacation etc I don't want my lights to be on for weeks.

Is it possible to get timer for maximum time on? You can use it for other purpose also.

**Comment by flexiti** [comment]
#1091  meets your expectations

**Comment by on-off-on** [comment]
Is there relly no way to implement in the "original" repository a simple timer function based on a electronic timer? :-// It would be a great feature for users like me to have "one" firmware to switch with commands from a controller e.g. FHEM and a simple timer function within the unit for areas without WLAN or LAN-access. I would like to have a timer for security reason during my holiday.... without connection to FHEM-controller... 
The forked timer doesn´t work and I´m unable to find the issue :-/

**Comment by ascillato** [comment]
Sam9s

Please read the wiki. Timers are implemented. This is a very old and close  thread.

Thanks

**Comment by sam9s** [comment]
ascillato, I dont need timer ... I know timer is there called pulstime, I need scheduling ... like the device should start on at certain time certain date and switch off certain time and date , with repeat schedule ..... I was able to find a fork of tasmota with schedule BUT looks like it works with MQTT. I dont want to run anything extra, just a scheduling feature with standalone tasmota on sonoff.

**Comment by ascillato** [comment]
Hi

For timing in tasmota you have already implemented in the actual version:

- Pulsetime (time to turn off relays after they are turn on)
- Timing variables for rules:
1 - uptime
2 - time in seconds from midnight
3 - sunset
4 - sunrise
- Ruletimer (countdown timers for being used inside rules)
- And weekly Timers:
![image](https://user-images.githubusercontent.com/35405447/42014207-758304cc-7a77-11e8-9b68-cae0f2039740.png)

**Comment by JeffJefferson** [comment]
It would be really great if you could add a duration parameter for automatically turn off the specified power output. Otherwise you always need a power on timer and a second timer for powering off.
