### ISSUE TITLE
How to see the http hostname isolated 

### ISSUE THREAD

**Issue by JoergZ2** [arendst/Sonoff-Tasmota#1480]
I'm looking for a command, that gives me the http name from sonoff basic. When I send the command status 5 I got this answer:
`stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-7497",...`
When I send the command hostname I got this answer:
`{"Hostname":"%s-%04d"}`
What is the command to get the Hostname sonoff-7497 isolated from the rest or do I have to filter the status 5 answer?

**Comment by arendst** [comment]
Yes...

or just change hostname to anything meaninful (as I always do) and it will return anything meaningful
