### ISSUE TITLE
Flicking Light

### ISSUE THREAD

**Issue by merlin051** [arendst/Sonoff-Tasmota#1492]
Hi,

I'm using pin14 and switch mode 9 to work with a rocker switch which is fine, but depending on other noise on the circuit the light flickers on/off regardless of the current state.

Is there any option that can introduce a 250ms delay to verify its actually changed state instead of the false readings from the circuit noise?

My log looks like this:

22:31:19 MQT: stat/sonoff1/RESULT = {"POWER":"ON"}
22:31:19 MQT: stat/sonoff1/POWER = ON
22:31:19 MQT: stat/sonoff1/RESULT = {"POWER":"OFF"}
22:31:19 MQT: stat/sonoff1/POWER = OFF
22:31:21 MQT: stat/sonoff1/RESULT = {"POWER":"ON"}
22:31:21 MQT: stat/sonoff1/POWER = ON
22:31:21 MQT: stat/sonoff1/RESULT = {"POWER":"OFF"}
22:31:21 MQT: stat/sonoff1/POWER = OFF
22:31:31 MQT: stat/sonoff1/RESULT = {"POWER":"ON"}
22:31:31 MQT: stat/sonoff1/POWER = ON
22:31:31 MQT: stat/sonoff1/RESULT = {"POWER":"OFF"}
22:31:31 MQT: stat/sonoff1/POWER = OFF
22:31:59 MQT: stat/sonoff1/RESULT = {"POWER":"ON"}
22:31:59 MQT: stat/sonoff1/POWER = ON
22:31:59 MQT: stat/sonoff1/RESULT = {"POWER":"OFF"}
22:31:59 MQT: stat/sonoff1/POWER = OFF

**Comment by merlin051** [comment]
Forgot to mention this is a sonoff basic using the latest firmware.

My switch is wired to gnd and gpio14,  GPIO Sensor is configured to 09 Switch1.


I've read about adding a resister on the gnd pin but I'm not sure where to start with that.

**Comment by merlin051** [comment]
anyone?

**Comment by lobradov** [comment]
This has been already addressed number of times - for example, check #850.

//_ on phone
