### ISSUE TITLE
Status every X period like the domoticz option

### ISSUE THREAD

**Issue by neographikal** [arendst/Sonoff-Tasmota#1497]
The docs say there is the following option for domoticz:

DomoticzUpdateTimer | 1..3600 | Send status to Domoticz between every 1 and 3600 seconds
-- | -- | --

I would like to push the stat/ messages every x seconds to mqtt just like the teleperiod. This way pimatic/homeassistant are always synced with the latest state despite being offline during the last toggle.

**Comment by pascalsaul** [comment]
This is a nice feature when you don't want to use retained messages :)
