### ISSUE TITLE
arendst/Sonoff-Tasmota Help please cant open "clone or download"

### ISSUE THREAD

**Issue by ukpaulthm** [arendst/Sonoff-Tasmota#1507]
hi all
every time I click on "clone or download" on this page https://github.com/arendst/Sonoff-Tasmota
the box wont open for me to download the zip can anyone please help me on this
many thanks
paul

**Comment by FitzJac** [comment]
[url]
https://github.com/arendst/Sonoff-Tasmota/archive/development.zip
[/url]

**Comment by ukpaulthm** [comment]
thank you
