### ISSUE TITLE
Wifi network only works when both SSIDs set in user_config.h

### ISSUE THREAD

**Issue by Brasletti** [arendst/Sonoff-Tasmota#1508]
Hello,
today i tryed to setup some sonoff basics. I figured out that the wifi network only get connected when both SSIDs and Passwords are set. (Tasmota 5.10.0)
Regards
Brasletti

**Comment by avrhack** [comment]
Yes I have had to set them both to the same one as well; thought it was just me so didn't raise a ticket!
