### ISSUE TITLE
Scroll back buffer request

### ISSUE THREAD

**Issue by kskenyon** [arendst/Sonoff-Tasmota#1512]
If there is room, a scroll back buffer for the command line in the web interface console page would be nice.  That is the easiest way to play around with cmnd without using an MQTT publishing app.  I wouldn't be retyping a command each time since I usually don't think to copy it into the clipboard each time.

Tasmota is terrific!

**Comment by arendst** [comment]
No room. Every line takes that many bytes of ram.

You might want to keep the web console open and the browser will log older messages.

**Comment by arendst** [comment]
Will look into it.Should be browser feature...
