### ISSUE TITLE
Sonoff T1 UK  RF Pairing

### ISSUE THREAD

**Issue by juan11perez** [arendst/Sonoff-Tasmota#1513]
NOT AN ISSUE, but wanted to share to save others some time. This is the way to pair the T1 with an RF remote. http://ewelink.coolkit.cc/?p=698.

Problem is that once you've loaded Tasmota, pressing the button long, resets tasmotta and I was unable to link with the switch tirelessly again. Tried the default SSID (indebuurt1) with no luck; so I had to pull the switch and reflash it.

So the advise is simple. Pair the RF before flashing tasmota. Once flashed it will ratain the RF code.

**Comment by arendst** [comment]
Or use ``SetOption13 1`` to disable long press

**Comment by juan11perez** [comment]
thank you. where do i do that? and how would I pair the RF?

**Comment by arendst** [comment]
Pairing will be the same as with the original software as it is not serviced by tasmota but by the "other" microcontroller.

All commands can be given by either MQTT, Serial or web console. See wiki for more commands.

**Comment by juan11perez** [comment]
Thank you very much. so for my benefit. I can SetOption13 1 throught the console, but I can still do the RF pairing afterwards without resetting tasmotta?

**Comment by arendst** [comment]
Correct

**Comment by juan11perez** [comment]
Once again, thank you. and thank you for sharing this fantastic software.
