### ISSUE TITLE
Voltage value

### ISSUE THREAD

**Issue by lovinggrey** [arendst/Sonoff-Tasmota#1515]
hi，when I used ina219, I found that the voltage value of the display was not accurate enough to display the numbers behind the decimal point.
![qq 20180105224036](https://user-images.githubusercontent.com/28864318/34613718-b97ed566-f269-11e7-9ecb-d554691416d9.png)

**Comment by arendst** [comment]
How about command ``VoltRes``

**Comment by lovinggrey** [comment]
Thank you. It's done.
