### ISSUE TITLE
Change port 80

### ISSUE THREAD

**Issue by jkiape** [arendst/Sonoff-Tasmota#152]
Is it possible change the web server port from 80 to ...any ???

**Comment by davidelang** [comment]
in webserver.ino is the line:

       webServer = new ESP8266WebServer(80);

change the 80 to your desired port and I'll bet that it works.

David Lang

**Comment by jkiape** [comment]
David thnx for your respond but unforchantly does not work.

**Comment by davidelang** [comment]
well, if that doesn't work, you'll have to change the library

on my system it's:
/home/dlang/.arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/ESP8266WebServer/src/ESP8266WebServer.h

change port=80 to whatever you want it to be.

but reading the header, the change to webserver.ino really should work.

David Lang

**Comment by jkiape** [comment]
Something strange happens. The server listens to the port (81) I gave (telnet 192.168.1.127 81) but it does not open by the web browser (http://192.168.1.127:81)

**Comment by davidelang** [comment]
It's possible that your system has a firewall in place that prevents the browser 
from going to odd ports (it's a valid security concern)

why are you needing to run the webserver on a different port anyway? it's not 
like there is anything else on that IP address to compete with it.

David Lang

**Comment by jkiape** [comment]
εxperimenting and ... playing.
Thank's any way,

**Comment by davidelang** [comment]
see PR #232 

it turns out is was just the line in webserver.ino

**Comment by godlich** [comment]
Honeslty, I am a beginner especially with tasmota. Do I have to change the file, recompile everything and upload the new code to my sonoff? Or can I do the changes online by connecting with tasmota via telnet?
