### ISSUE TITLE
Feature request: Shutter mode for Sonoff 4ch and Sonoff Dual via Buttons and MQTT

### ISSUE THREAD

**Issue by HGBAXXTER** [arendst/Sonoff-Tasmota#1521]
Although this topic has been excessively discussed, I have not yet found a satisfactory way to utilize the Sonoff 4ch and Sonoff Dual to control rollershutters and comparable devices. I am aware of potential risks (i.e. simultaneous activation of both channels), however, several devices exist that are not sensitive against those effects. 

My proposed implementation would have the following functionality: 

- In the configuration, the up/down channels can be selected, and the opening/closing times for each channel could be specified
- Via button press or hold, the shutters can be commanded up/down. Based on the accumuated run time, the percentage of the opening level is calculated in the Sonoff
- Alternatively, a target level in percent or a run up/down time can be commanded via MQTT
- The opening level in percent is communicated back via MQTT

This type of implementation would really boost my home automation (and maybe others).

**Comment by Courty40** [comment]
This is classic Sonoff + Node-Red automation, bit more work but you can add a heap more intelligence to the setup.
