### ISSUE TITLE
How to add adafruit mqtt broker?

### ISSUE THREAD

**Issue by yashildoongoor** [arendst/Sonoff-Tasmota#1526]
I have just flash my sonoff and connected to adafruit mqqt broker. But am having issue with how to send payload to switch on and off light.

**Comment by gtortone** [comment]
if you did not touch the default configuration for full topic you can use this (Linux) command

mosquitto_pub -h **_mqtt_hostname_** -t  **_device_**/cmnd/POWER -m ON

replace **mqtt_hostname** with Adafruit MQTT server hostname and **device** with name of your
sonoff configured in user_config.h
