### ISSUE TITLE
Error upgrading to 5.11 a

### ISSUE THREAD

**Issue by rlust** [arendst/Sonoff-Tasmota#1539]
I am getting the following error on upgrade of 2 Sonoff basics running 5.10j

Upload Failed

Upload buffer miscompare

**Comment by arendst** [comment]
Expected. See https://github.com/arendst/Sonoff-Tasmota/wiki/Theo's-Tasmota-Tips.

Look for sonoff-minimal usage

**Comment by rlust** [comment]
Thanks! Loading the minimal first fixed all issues. Works great now!
