### ISSUE TITLE
Plans to integrate dual original and dual R2 code?

### ISSUE THREAD

**Issue by taitrt** [arendst/Sonoff-Tasmota#1540]
When selecting "Sonoff Dual", MQTT and web toggles work perfectly but button1 and button2 pins do not function properly.

When selecting "Sonoff Dual R2", button1 and button2 pins function perfectly but MQTT and web toggles do not switch the relays.

It seems like these two builds could be combined to have full functionality on non R2 duals, any plans to do this in the future?

**Comment by arendst** [comment]
Nope as they are mutually exclusive
