### ISSUE TITLE
Problems setting Sonoff Pow Calibration

### ISSUE THREAD

**Issue by altelch** [arendst/Sonoff-Tasmota#1542]
Trying to get/change calibration on 5.11 (didn't test lower versions) fails:

Tried via webconsole, direct http-request and MQTT. All tries result in Command Unknown.
On the other hand using "AmpRes" works.

20:41:38 CMD: cmnd/haus/abstellkammer/pow/AmpRes
20:41:38 MQT: stat/haus/abstellkammer/pow/RESULT = {"AmpRes":3}
20:42:10 CMD: cmnd/haus/abstellkammer/pow/HlwUcal
20:42:10 MQT: stat/haus/abstellkammer/pow/RESULT = {"Command":"Unknown"}

Greetings,

     Heiko.

**Comment by arendst** [comment]
Fixed in 5.11.1 just released.

**Comment by danphamus304** [comment]
https://github.com/joecotton/Sonoff-Tasmota/commit/437dae5147140a01ea51979bc3c7ac446a2e2364

**Comment by mipxx** [comment]
It seems to be still not working with version 5.12.0a
