### ISSUE TITLE
Cant update firmware 5.11 on B1 bulb

### ISSUE THREAD

**Issue by rajil** [arendst/Sonoff-Tasmota#1544]
Hello,
I have a B1 bulb running 5.10. I tried upgrade to 5.11, but the upload of the firmware never finishes (using google chrome). It the first instance the upload was stuck at 46%, second time it got stuck at 62%.

With the same firmware file i was able to upgrade Sonoff POW.
Thanks

**Comment by profesionalTI** [comment]
Dos loas full project and compile

**Comment by arendst** [comment]
Check your wifi signal strength

**Comment by MatzeJoerling** [comment]
what is needed for online update? 
What is the minimal RSSI?
