### ISSUE TITLE
v2.40 max() Function Compiling Error

### ISSUE THREAD

**Issue by reloxx13** [arendst/Sonoff-Tasmota#1549]
Heya aren,

got this for you:
(Ah, i suggested the user to update the packages with Atom, did not response now, ill give feedback if this solves it.)

> Archiving .pioenvs\sonoff\lib741\libNeoPixelBus_by_Makuna.a
> lib\IRremoteESP8266\IRKelvinator.cpp: In member function 'void IRKelvinatorAC::setTemp(uint8_t)':
> lib\IRremoteESP8266\IRKelvinator.cpp:96:41: error: **no matching function for call to 'max(unsigned int, uint8_t&)'**
> temp = max(KELVINATOR_MIN_TEMP, temp);
> ^
> lib\IRremoteESP8266\IRKelvinator.cpp:96:41: note: candidates are:
> In file included from c:\users\hw_note006\.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include

> 
> c:\users\hw_note006\.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include\c++\4.8.2\bits\stl_algo.h:4236:5: note: template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>,
> _Compare)
> **max**(initializer_list<_Tp> __l, _Compare __comp)
> ^
> 

> Thanks for the heads up that v2.4.0 has finally been released. Dang, I was hoping this would be fixed before it was officially released.
> 
> The problem stems from the way the arithmetic min() and max() functions are implemented. Before v2.4.0 they were implemented as macros and the macro parameters could be of different data types (byte, int, long or whatever). With v2.4.0 min() and max() are now implemented using the std::min and std::max library and both function parameters have to be the same data type, the compiler won't do implicit type conversion. :(
> 
> So probably the easiest solution is to explicitly cast one of the two parameters when they are different data types. The WS2812FX library needs to be tweaked in two places.

https://github.com/kitesurfer1404/WS2812FX/issues/58#issuecomment-355793296

FullLog:
[log.txt](https://github.com/arendst/Sonoff-Tasmota/files/1612162/log.txt)

**Comment by arendst** [comment]
You seem to use the old libraries. Pls update with the latest libraries as provided with release 5.11.1
