### ISSUE TITLE
OTA update aborts if upload takes longer than 30s (OSWATCH_RESET_TIME)

### ISSUE THREAD

**Issue by HellGL** [arendst/Sonoff-Tasmota#1556]
Hi,
on my desk OTA was never working because it aborted after approx. 30s. After reboot the reason stated was "Blocked Loop". With chrome (it shows a percentage during upload) I figured out that the Wifi connection was just not fast enough. After connecting to my mobile hotspot upload went fine and OTA update was no problem. Would it be a good idea to disable or at least extend OSWATCH_RESET_TIME during OTA?

**Comment by MatzeJoerling** [comment]
I have had a bunch of problems updating my esp devices. I hace cisco wlan, 80211n and a band, working good for all devices, except esp. i only get every 100th update done. Always blocked loop.

did run wireshark on my webserver that sends out the bin file, esp is downloading with 32kBytes/s!!! and less. so no chance to get the update in 30 sec, even with 80% Signal and "empty" wlan. anyways, my other devices easily get 10Mbit/s and more in 2.4GHz band...

**i have set OSWATCH_RESET_TIME  to 180 sec, no problem anymore.** 

Dont know why my download speed is that BAD, also upload when i use a browser, same behavior.
