### ISSUE TITLE
Sonoff RF Bridge not joining MQTT (rc-2) - TAS menu only accessible via WiFi 

### ISSUE THREAD

**Issue by RKF-FKR** [arendst/Sonoff-Tasmota#1565]
Well this one has me completely stumped. 

I have a number of Tasmota devices working beautifully with my Pi MQTT server.

My router has assigned the RF Bridge an IP address of 192.168.1.106 / 255.255.255.0.  I've bound that IP address to the Bridge.

But this little fella will not connect to the server.  
Same user and pass.
Same MQTT server:port
Different topic / group / 
Different Friendly name

The weird thing is that the IP address of the Bridge / menus can only be accessed my my wifi devices.  If I try to open the sonoff menu from a computer that has hard wired ethernet connections, the Tasmota page won't load.
My iPhone and a wifi only PC are able to access the device menu.

I'm assuming the -rc-2 error for the MQTT and the fact that I can't access the device menu via Ethernet are related.

Am I missing something ultra basic here?

Any help would be greatly appreciated.
Rod

**Comment by RKF-FKR** [comment]
All sorted - please close this issue - Sorry to bother

**Comment by WagnerBeccard** [comment]
Jea.. But now i got this problem.. How you fixed it?
(but I cant even connect to the webserver)

**Comment by RKF-FKR** [comment]
I bought a new sonoff bridge and everything flashed as expected. I discarded the other bridge. 
But I have had this problem on other wemos D1 mini also. In this case just choosing the exact settings in Arduino fixed the problem.
