### ISSUE TITLE
New Sonoff TH10 does not show up in network list. How to SonOTA then?

### ISSUE THREAD

**Issue by eirikgund** [arendst/Sonoff-Tasmota#1569]
As the title says. I connected the TH10 to the wall, but it does not show in my AP list. This worked fine on the Basic modules. I used SonOTA on the previous ones, but this will not be possible now. Is this a new firmware thing?

**Comment by bensuffolk** [comment]
The new firmware on all the so off devices is not compatible with SonOTA, you have to flash them with a programmer now.

**Comment by eirikgund** [comment]
Stupid. OTA was so simple😂 Now I have to buy connectors to solder in and that will take days in shipping. Any tricks I should know of to speed things up? 🤔
