### ISSUE TITLE
hostname change

### ISSUE THREAD

**Issue by acejacek** [arendst/Sonoff-Tasmota#157]
I can't change hostname via "Configure WiFi". Always fall back to %s-%04d. Also, hostname includes MQTT topic, which is not perfect.

I'm using 4.0.0.

**Comment by arendst** [comment]
You can only change the hostname to a text string without a % sign OR use the suggested default of %s-%04d.

So changing it to ``acejack-123`` is no problem

**Comment by acejacek** [comment]
Leave a comment

**Comment by ornago** [comment]
thanks, helped me too
