### ISSUE TITLE
Wrong response for DomoticzSwitchIdx

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#1571]
Hello,

If I set DomoticzSwitchIdx to a random number for example:
`DomoticzSwitchIdx1 33`

I will always receive the number 0:
`21:50:11 MQT: stat/Sonoff/RESULT = {"DomoticzSwitchIdx1":0}`

But the IDx is correct (33) only the response (0) is wrong.

Greetings Fabi

**Comment by arendst** [comment]
Fixed two issues (Truncated command and wrong variable addressed) in next pre-release

**Comment by 0n3-70uch** [comment]
Hi Theo, thank you :-)

**Comment by 0n3-70uch** [comment]
Version 5.11.1b tested and everything works great now.
