### ISSUE TITLE
Can't connect to WiFi with ! in the password

### ISSUE THREAD

**Issue by Fridleif** [arendst/Sonoff-Tasmota#1575]
Hi, I can't connect to a WiFi with a ! in the password. Is there a trick? With only numbers and letters are no problems.

Thanks

**Comment by GrandadEvans** [comment]
I sometimes have this issue as my passwords often contain these characters. I often have to escape them, so
"Password123!"
Becomes
"Password123\!"
Sorry if this is something you are already aware of but it's worth a shot.

**Comment by Fridleif** [comment]
@GrandadEvans 
Thanks for you suggestion. But it doesn't work :(

I found a solution using the WPS-button and the 5 Click option from https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage

It's more a workarround then a solution but it work for now.
