### ISSUE TITLE
Sonoff Dual - Echo Plus with Built-in Hub

### ISSUE THREAD

**Issue by zibous** [arendst/Sonoff-Tasmota#1578]
I can not manage Sonoff Dual with Alex (Echo Plus with Built-in Hub). It works with the WeMo emulation, but then I can only control one relay. Echo does not recognize a device with Hue Bridge (multi device).

![bildschirmfoto 2018-01-12 um 17 15 59](https://user-images.githubusercontent.com/30198737/34885391-2002aa00-f7c0-11e7-9d7b-4be390ddc66c.jpg)

Is there a workaround or a tip on how I could control the shutters with Sonoff Dual via Amazon Echo?

**Comment by cyclemat** [comment]
Ich würde es über open hab steuern problem ist du müsstest so ein deinem Relais einstellen können das immer nur eins an ist das kann die Tasmota Firmware Bisher nicht da du ja scheinbar über relais 1 Rauf und Relais 2 Runter Fährst. Ich würde das ganze einfach als 2 Devices in Openhab anlegen und per MQTT Steuern Openhab hat auch Hue emulation eingebaut von daher super sache und du kannst auch Setze auf 50% usw nutzen.
Zweite idee die ich hätte alles über ein Relais Steuern also über NC und NO so kannst du aber nur komplett rauf oder komplett runter fahren.

**Comment by zibous** [comment]
Via a web interface, this is easy with the home assistant application. There I can use "UP, STOP, CLOSE". Interesting would be a controller with Amazon Echo / Dot devices.

![bildschirmfoto 2018-01-16 um 10 18 50](https://user-images.githubusercontent.com/30198737/34981089-bcb1f782-faa6-11e7-90d7-010423488177.png)

I am looking for a general skill with which I can pass any voice commands to the MQTT Brocker and then control the Sonoff devices with NODE-RED. But so far have found no approach / solution.

![bildschirmfoto 2018-01-16 um 10 17 37](https://user-images.githubusercontent.com/30198737/34981102-ca0e15b4-faa6-11e7-8001-a88bbe52cdff.png)

**Comment by thomasnordquist** [comment]
I use https://www.npmjs.com/package/node-red-contrib-alexa-local, but it is very limited in functionality.

It basically emulates a philips hue bridge.
Commands are something like:
 - Turn {DeviceName} on
 - Change the temeprature of {DeviceName} to 21 ~degrees~ 
 *(no unit allowed here, actually changing the brightness)*

It does not yet support change the light color, I'm trying to change that with a pull request within in the next weeks.

To control things like AVRs, thermostats etc you'll have to use a "cloud" solution, the solution for node-red is hosted by some random dude.
https://www.npmjs.com/package/node-red-contrib-alexa-home-skill
Sadly the server side is not open source as far as I can tell, but it shouldn't be to hard to write your own backend if you are familiar with javascript, amazon has some very nice boilerplate code.

Worth mentioning:
https://flows.nodered.org/node/node-red-contrib-alexa

**Comment by zibous** [comment]
@thomasnordquist, thanks for this information.

**node-red-contrib-alexa-local** can not do much more than the tasmota WeMo or philips hue bridge emulation and with this i can not control shutters because they have 3 states (ON, STOP, OFF).

- Alexa open kitchen shutter
- Alexa stop kitchen shutter
- Alexa close kitchen shutter
- Alexa close kitchen shutter 50%
.....

Yes, **node-red-contrib-alexa** is promising, but I have to create a skill and I have not done that yet (just try to learn how i can build a skill).

Nice would be a "MQTT generic Skill" that passes the voice commands to a MQTT Brocker, then they could be queried and processed with Node-RED conditions.

Am still testing and looking for ...
