### ISSUE TITLE
no % sign on dht sensor after atom upgrade

### ISSUE THREAD

**Issue by roblad** [arendst/Sonoff-Tasmota#1579]
Hi,

I discovered that no % sin exist after humidity on dht sensor

const char HTTP_SNS_HUM[] PROGMEM = "%s{s}%s " D_HUMIDITY "{m}%s%{e}";  

I sugest to change each % sign in html to &#37;

**Comment by arendst** [comment]
Observed randomly too. Will investigate.

**Comment by roblad** [comment]
Hi

Does not show % sign I sugest to use "&#37;"

**Comment by arendst** [comment]
Clear your brower cache and try again. All my browsers work fine now.

What browser do you use?

**Comment by roblad** [comment]
Hi,


Firefox

**Comment by arendst** [comment]
So I guess all's well now? If so pls close issue.
