### ISSUE TITLE
#Include <TasmotaSerial.h>

### ISSUE THREAD

**Issue by dinger69** [arendst/Sonoff-Tasmota#1584]
I downloaded the latest from the lib repository and replaced the original's but it still will not compile with the same error:

C:\Sonoff-Tasmota-5.11.0\sonoff\xsns_03_energy.ino:252:27: fatal error: TasmotaSerial.h: No such file or directory

#include <TasmotaSerial.h>

                       ^
compilation terminated.

exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by arendst** [comment]
Duplicate. See #1522.
