### ISSUE TITLE
Nodemcu outputs

### ISSUE THREAD

**Issue by ramsaymike** [arendst/Sonoff-Tasmota#159]
I was very happy to see the addition of nodemcu/wemos to the supported hardware list but I can not figure out how to add outputs to these.  There are lots of options in the in the GPIO definition but nothing like a  relay.  Can this be done somehow?  Thanks.

**Comment by arendst** [comment]
If you want relays you'll have to edit file sonoff_template.h and add them to your NodeMCU config. I won't support easy web based relay config as the interface will get to clumsy and this is about sonoff not espeasy.

**Comment by ramsaymike** [comment]
Thanks for the tip - seems to work just fine....
