### ISSUE TITLE
MQTT with TLS disable Domoticz

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#1591]
Hello,

I enabled `USE_MQTT_TLS` and disabled `USE_WEBSERVER`.

When I set `cmnd/Sonoff_E71F69/DomoticzIdx1 -m "4"` then I get this error:
`{"Command":"Unknown"}`

Greetings Fabi

**Comment by arendst** [comment]
What version of tasmota? It might have been solved in the latest pre-release.

**Comment by 0n3-70uch** [comment]
Ah yeah I tested 5.11.1b a fex seconds ago. Everything running nice now. Thanks, my mistake :-).

Fix: https://github.com/arendst/Sonoff-Tasmota/commit/4fba6f2758265e39d6cea0de8d00efc2812f8060
