### ISSUE TITLE
DHT22 sensor v5.11.1

### ISSUE THREAD

**Issue by dragouf** [arendst/Sonoff-Tasmota#1602]
it seems DHT22 disappeared from GPIOS list in 5.11.1 version. Is it normal ?

**Comment by curzon01** [comment]
5.11.1 same configuration as for my previous 5.10.0 displays now my DHT22 sensor as a "SI7021" and works well.

**Comment by rene9900** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/1552#issuecomment-358014964

**Comment by MimbaMonkeyHouse** [comment]
Yes, this happened when compatibility with Sonoff SI7021 single wire sensor was added.
