### ISSUE TITLE
Sonoff th16 temperature decimals 

### ISSUE THREAD

**Issue by andyd999** [arendst/Sonoff-Tasmota#1606]
Hi

I just got my sonoff th16 today and currently has stock firmware. Temperature works but only reported to whole numbers. Will adding Tasmota add the functionality to have decimals to 0.5degrees?

**Comment by issacg** [comment]
I can't speak for the accuracy of whatever temperature unit you connected to your TH16, but it will be reported in decimals, if supported by the hardware. (I use the DHT22 and get decimals - I'm happy enough with the accuracy for climate control)

**Comment by arendst** [comment]
See Wiki command tempres
