### ISSUE TITLE
Wifimanager 3minutes timeout use WIFI_CONFIG_SEC instead of WIFI_MANAGER_SEC

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#1615]
#Default both variables are 180. Therefore the error does not show up. But when changing the MANAGER you can see, that still uses the 180 from the WIFI_CONFIG_SEC.

I found this during changing the MANAGER to 255 and still see it counting up from 180.

**Comment by arendst** [comment]
Thnx. Will consolidate both in WIFI_CONFIG_SEC
