### ISSUE TITLE
DHT11 does not work - 5.11.1 

### ISSUE THREAD

**Issue by chorus12** [arendst/Sonoff-Tasmota#1617]
Sonoff TH16 with DHT11 sensor
![screenshot from 2018-01-16 18-15-42](https://user-images.githubusercontent.com/10760182/34996145-c8104a3c-fae9-11e7-8ccc-cef54569c04b.png)
Tasmota version  5.11.1
Core/SDK Version 2_4_0/2.1.0(deb1901)

Does not report a temperature and humidity.

**Comment by ngalfas** [comment]
try to reselect the GPIO selection for SI7021, press OK to the selection and make it restart.
You should know that the DHTxx selections have changed now (because of a library merge) and it will have the SI7021 as sensor selection instead of DHT
