### ISSUE TITLE
error: 'class TasmotaSerial' has no member named 'flush'

### ISSUE THREAD

**Issue by darfi** [arendst/Sonoff-Tasmota#1618]
Hello all,

please don't kill me if I ask for maybe trivial issue. I'm starting with Tasmota firmware for sonoff products, but during verification I got below errors. Could you please help what to check, why getting this error?

Thanks

C:\Users\Jaro\Documents\Arduino\Sonoff-Tasmota-development\sonoff\xdrv_03_energy.ino: In function 'void PzemSend(uint8_t)':

xdrv_03_energy:307: error: 'class TasmotaSerial' has no member named 'flush'

   PzemSerial->flush();

               ^

C:\Users\Jaro\Documents\Arduino\Sonoff-Tasmota-development\sonoff\xsns_15_mhz19.ino: In function 'void Mhz50ms()':

xsns_15_mhz19:137: error: 'class TasmotaSerial' has no member named 'flush'

       MhzSerial->flush();

                  ^

C:\Users\Jaro\Documents\Arduino\Sonoff-Tasmota-development\sonoff\xsns_17_senseair.ino: In function 'void ModbusSend(uint8_t, uint16_t, uint16_t)':

xsns_17_senseair:77: error: 'class TasmotaSerial' has no member named 'flush'

   SensairSerial->flush();

                  ^

**Comment by arendst** [comment]
You need TasmotaSerial-1.0.1 from de development lib.
