### ISSUE TITLE
Domoticz options doubt

### ISSUE THREAD

**Issue by gajotnt** [arendst/Sonoff-Tasmota#1619]
Hello, sorry for my ignorance, but are the "**Key idx**" in the domoticz page used for?

https://github.com/arendst/arendst.github.io/raw/master/media/domoticz3.jpg

**Comment by webtop** [comment]
It’s a link to a device in Domoticz. In Domoticz, you creat a device, get its key idx, enter that into the module, and you’ll get data in Domoticz without anything else needing to be done. When I was using Domoticz it worked perfectly.

**Comment by webtop** [comment]
The wiki page gives a walkthrough

**Comment by gajotnt** [comment]
I know that, but I usually put the IDX where it shows in the image above. The "Key IDX" is the thing I don't know what's for.

**Comment by gajotnt** [comment]
![screenshot_20180116-200433](https://user-images.githubusercontent.com/25504364/35012218-9693fba2-faf8-11e7-848e-a6bb1e91a697.png)

**Comment by arendst** [comment]
I have sensor in my letterbox down the road. It switches three sonoff like devices to signal the postman rang once.

The letterbox domoticz index is filled in in all three sonoff like domoticz key idx to switch their lights on.

**Comment by gajotnt** [comment]
I know you can have several devices with the same IDX.
What i dont get is the why theres a "**Idx 1**" and a "**Key Idx 1**". I usualy set my domoticz idx in the **Idx1** field, never used the "**Key Idx 1**" and dont understand for what it is used for, that is my doubt.

**Comment by arendst** [comment]
I've tried to explain the use of Key Idx in my last answer. For some reason I failed...

**Comment by gajotnt** [comment]
:( yeah i didnt get the logic of the Key Idx field.
I get it that the idx of the mailbox sonoff is the same as the other 3 sonoffs in the house, so when the postman rings some lights turn on in the house, and if you turn off the lights the signal should be reset then, this would be the way i would make this automation, maybe your using a better way and im not understanding the logic of the key idx.
The Wiki of domoticz doesent have anything about keys (only API Keys), Tasmota Wiki, only mentions this in the Known Commands but doesnt explain what it is.

**Comment by arendst** [comment]
Actually another sensor connected to the backdoor is resetting the signal but that is out of scope here.

The main issue is that using the button on any of the three sonoffs will reset the signals on all three sonoffs. This could also be used in a long aile or staircase with different switches controlling a single light.

Once you get it you might want to update the Domoticz wiki page ;-)

**Comment by gajotnt** [comment]
When i have some spare time ill try out to mess with the key idx and understand better its use and then for sure i will update the wiki :)
