### ISSUE TITLE
BME680 found at 0x77 , but not recognized and not reporting 

### ISSUE THREAD

**Issue by anpj123** [arendst/Sonoff-Tasmota#1620]
Hi, I connected BME680 to Sonoff Basic with Tasmota 5.11.1 . After MQTT command I2Cscan I get response {"I2CScan":"Device(s) found at 0x77"} , but the sensor is still not reporting. I tested also BMP180 and that one works perfect , but BME680 don't . I also tried 5.11.0 firmware with the same results .

**Comment by arendst** [comment]
You'll need to enable bme680 support in user_config.h first. Then recompile and upload.

**Comment by anpj123** [comment]
Perfect ! It works excellent now. Thank you very much. Your work on this firmware is remarkable.

**Comment by renne** [comment]
Hi, I connected the BME680 with SDA to GPIO2 and SCL to GPIO14 and selected "18 generic" for the ESP8266-12F, SDA for GPIO2 and SCL for GPIO 14. CS is connected to 3.3V and SDO to GND. Tasmota is compiled with `#define USE_BME680` uncommented in user_config.h.

I2CScan lists `00:51:18 MQT: stat/sonoff/RESULT = {"I2CScan":"Device(s) found at 0x76"}` but I can't find anything else about the BME680.

How can I debug this?

**Comment by renne** [comment]
After switching the BME680 to address 0x77 by connecting SDO to 3.3V instead of GND the BME680 is detected. All sensor values are zero. Is there anything else to configure?

**Comment by renne** [comment]
The BME680 works fine with the Pimoroni library on a Raspberry Pi with address 0x76.

**Comment by renne** [comment]
Good news, The BME680 works. :-)
It was just a broken ground lane on the breadboard. :-(
