### ISSUE TITLE
Persistence of Backlog command ??

### ISSUE THREAD

**Issue by SGF-Lon** [arendst/Sonoff-Tasmota#1631]
If I send a backlog command with 3 commands in it - but the first command requires a restart (say for example "Module 8" - do the remaining commands persist & continue to be executed after the restart or are they 'forgotten' ?

**Comment by arendst** [comment]
If backlog encounter a restart request it processes the rest of the backlog first before the restart is executed. This allows for multiple changes in one command line.

**Comment by SGF-Lon** [comment]
Excellent - that's what I had hoped for.  I will build my functionality accordingly.
