### ISSUE TITLE
MQTT_MAX_PACKET_SIZE error when compiling

### ISSUE THREAD

**Issue by ascillato** [arendst/Sonoff-Tasmota#1634]
What about to modify _sonoff.ino_ with the following code so as there is no need to go and modify other libraries?

**sonoff.ino, Line 41:**
```
// Max message size calculated by PubSubClient is (MQTT_MAX_PACKET_SIZE < 5 + 2 + strlen(topic) + plength)
#if (MQTT_MAX_PACKET_SIZE -TOPSZ -7) < MIN_MESSZ  // If the max message size is too small, throw an error at compile time. See PubSubClient.cpp line 359
  #error "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increase it to at least 1000"
#endif
```
change to:
```
// Max message size calculated by PubSubClient is (MQTT_MAX_PACKET_SIZE < 5 + 2 + strlen(topic) + plength)
#if (MQTT_MAX_PACKET_SIZE -TOPSZ -7) < MIN_MESSZ  // If the max message size is too small, throw a warning at compile time. See PubSubClient.cpp line 359
  #warning "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increasing it to 1000"
  #undef MQTT_MAX_PACKET_SIZE
  #define MQTT_MAX_PACKET_SIZE 1000
#endif
```

@arendst Testing Tasmota v5.11.1c. It is working very good!!!!

**Comment by arendst** [comment]
Did you test it with Arduino Ide too? I did a year ago and didn't work. Pls try too.

**Comment by ascillato** [comment]
Yes, in Arduino IDE works:

![image](https://user-images.githubusercontent.com/35405447/35120006-802fa3c4-fc75-11e7-8cfe-b79e85a20b00.png)

It works just fine.

**Comment by arendst** [comment]
Pls provide the output of command status 6

**Comment by ascillato** [comment]
@arendst Where I can find the output of command status 6 ?

**Comment by davidelang** [comment]
you can send the command via mqtt, serial, or the web console

**Comment by ascillato** [comment]
Thanks @davidelang 

The output of Status 6 on the Console is:

![image](https://user-images.githubusercontent.com/35405447/35196553-5893a6be-feb2-11e7-8b06-c96dc9028138.png)

![image](https://user-images.githubusercontent.com/35405447/35196554-5dac63ca-feb2-11e7-957a-4721b39bfbff.png)

So, it means that the proposed modification to _sonoff.ino_ works

I tested on Arduino IDE 1.8.2

**Comment by Sergey-SRG** [comment]
![21-01-2018 21-38-00](https://user-images.githubusercontent.com/3891900/35197732-f0d9829e-fef4-11e7-9c95-51890548af68.png)
![21-01-2018 21-38-23](https://user-images.githubusercontent.com/3891900/35197733-f0f53a20-fef4-11e7-9ed2-a200d0af0222.png)

**Comment by Sergey-SRG** [comment]
Works in Arduino IDE and PlatformIO.

**Comment by ascillato** [comment]
Closing #1634 as there is the PR #1657.

@Sergey-SRG, your PR is good enough for solving the issue, but if you like we can add the warning for the user.

Thanks! :+1:

**Comment by ascillato** [comment]
Hi @arendst ,

As this warning works on Arduino IDE and also on Platform.io, can be added to Tasmota?

Thanks
