### ISSUE TITLE
SendIR Problem

### ISSUE THREAD

**Issue by cinehorse** [arendst/Sonoff-Tasmota#1636]
I have a problem with IRsend and Tasmota/Mqtt (5.11.1)  on a sonoff basic (Sorry for my bad english)

- IR Diode is installed on GPIO14
- Select 08 IRSend
- Mqtt works Topic: tasmota/irsend/
- Language: DE

Testing Szenario in the console : 
`irsend {"PROTOCOL":"SONY","BITS":20,"DATA":"691015"}`

so i get the follwing message:
`22:14:18 CMD: irsend {"PROTOCOL":"SONY","BITS":20,"DATA":"691015"}
22:14:18 MQT: tasmota/irsend/stat/RESULT = {"IRSend":"No PROTOKOLL, BITS or DATEN"}`

the same result  when i send from broker directly this teststring:
`mosquitto_pub -q 2 -t tasmota/irsend/cmnd/irsend  -m '{"protocol": "SAMSUNG","bits": 32, "data": 3772793023}'
`

Where is the problem?  
can you help me?

**Comment by arendst** [comment]
Took a while before I got it but the problem is with the language. It should have been in English but apparently the German translation is used. So for now you should be able to execute the Sony command as
```
irsend {"PROTOKOLL":"SONY","BITS":20,"DATEN:"691015"}
```
I will change it in the next (pre)release to English as it should be.

**Comment by cinehorse** [comment]
Yes, thats the solution , a simple translation bug 

So i change the json string  in the command  and get 
`{"IRSend":"Done"}` 

Thanks
