### ISSUE TITLE
MQTT HSB color command

### ISSUE THREAD

**Issue by DerEnderKeks** [arendst/Sonoff-Tasmota#1642]
Do understand that right that there is no support to set a HSB color via MQTT right now? I found some code related to HSB but no way to use that with MQTT commands.

If so, it would be really nice to have this possibility as I'm using OpenHAB which can't natively send RGB values, but only HSB values. It would also have to include the HSB color in the response.
(The format should be like it's for RGB right now; "h,s,b")

**Comment by ThomDietrich** [comment]
One can always build an openHAB rule to translate back and forth between HSB and RGBW. See: https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/types/HSBType.java#L81

Still I agree, it would be amazing if Tasmota also supported HSB natively.

**Comment by DerEnderKeks** [comment]
I thought about doing that but it wouldn't feel very native to do it like that and that's why I dislike that way.

**Comment by ThomDietrich** [comment]
Not sure what you mean. To expect everything always served in just the right bits is also a bit too much to ask. If you are still interested, I build working rules yesterday evening:

* From RGBW to HSB+W: https://community.openhab.org/t/sonoff-b1-rgbcw-wifi-bulb-w-sonoff-tasmota/34202/15
* From HSB+W to RGBW: https://community.openhab.org/t/sonoff-b1-rgbcw-wifi-bulb-w-sonoff-tasmota/34202/18

**Comment by DerEnderKeks** [comment]
I will probably use the rules for now but having a native integration of HSB in Tasmota would still be nice to have. :D

**Comment by ThomDietrich** [comment]
Yes indeed, I don't argue with that 😉 

Actually I'd also like the implementation of an `RGBType` in openHAB. It's surprising that none exists...

**Comment by Cypris2010** [comment]
I also would really appreceate this.

**Comment by ThomDietrich** [comment]
The working openHAB solution can be found here: https://community.openhab.org/t/light-color-rgb-rgbw-rgbcw-to-and-from-hsb-dimmer-conversion/39132
