### ISSUE TITLE
Calibration parameter for the temperature, the humidity and the air pressure

### ISSUE THREAD

**Issue by micropet** [arendst/Sonoff-Tasmota#1643]
First of all thank you for the great software, Theo.
I use it mostly on NodeMCU or Wemos D1 Boards.

I have a 2 feature requests:

1.
The measured values from the BME280 are therefore inaccurate.
I would like a calibration parameter for the temperature, the humidity and the air pressure.

2.
The Automatic Baseline Correction for the MH-Z19 also does not work well.

I would like to do a zeropoint calibration by command.

I do that with my own programs and it works perfectly.
I have 5 Co2 meters here and all show the same results.

This is the Sequenz:  byte zeropoint[]= {0xff,0x01,0x87,0x00,0x00,0x00,0x00,0x00,0x78};

Greetings Peter

**Comment by arendst** [comment]
How often is that zero point calibration needed? Could I decide to do it once a day (too often perhaps) or once a week. Or is it only needed after some minutes after power on. 

I don't want to have another command so making this automatic would make me very happy.

**Comment by micropet** [comment]
Hi Theo,

I only ever did the zero point calibration once.
For this, the sensor must be in free air for 20 minutes, ie outside.

After a few years you should calibrate again. The MH-Z19 uses a normal lamp as the light source. This does not shine so bright after years.

abs outputs different values every day. It depends on how much CO in the room is when abs is executed.

Greetings Peter

**Comment by Frogmore42** [comment]
Here is an article on calibrating CO2 sensors.  https://www.co2meter.com/blogs/news/7512282-co2-sensor-calibration-what-you-need-to-know
Sounds like once a year would be okay for many uses.

**Comment by micropet** [comment]
Yes, that will be enough in any case.
I think only abs bad. It depends on the ventilation behavior.
I have wrong values over and over again.

This is not the case with manual calibration.

**Comment by chriskmn** [comment]
I would also love to have calibration value for temp, humidity etc. as my humidity values of the DHT22 are way too high.

**Comment by tiberiuana** [comment]
👍 for the calibration parameter. 
The Wemos SHT30 shields also seem to measure way to high.

**Comment by tiberiuana** [comment]
👍 for the calibration parameter. 
The Wemos SHT30 shields also seem to measure way to high.

**Comment by micropet** [comment]
Thank you for MH-Z19 manual calibration.
Now we need calibration value for temp, humidity, press etc. 
Then it would be perfect.

**Comment by DonStefano** [comment]
I would like to see calibration for all sensors.

**Comment by Frogmore42** [comment]
See https://github.com/arendst/Sonoff-Tasmota/issues/2966
For a way to do it.

**Comment by ascillato** [comment]
Hi,

If your issue is solved, please close it. Thanks :+1:

**Comment by ThinkPadNL** [comment]
I see it has been implemented in the code  (mhz_cmnd_zeropoint) but how do i trigger this from Tasmota?
