### ISSUE TITLE
Sonoff POW does not show energy data after restart

### ISSUE THREAD

**Issue by pjanco** [arendst/Sonoff-Tasmota#1648]
Hi,
if **no load is connected** after restart, only "Energy Yesterday" contain correct saved data.
"Energy Today" and also "Energy Total" are zero even if they should not to be zero. These two values are actualized just after some load is connected.

Problem is in file "xsns_03_energy.ino" in function "void HlwInit()".

just change line: **`hlw_energy_period_counter = 0;`**

to this: **`hlw_energy_period_counter = 1;`**

**Comment by MimbaMonkeyHouse** [comment]
I had a similar issue with firmware 5.11.1. Reversed to 5.10 and my POWs work!
