### ISSUE TITLE
Help! Get Analog0 value via http returns "WARNING":"Enable weblog 2 if response expected"

### ISSUE THREAD

**Issue by kevinshane** [arendst/Sonoff-Tasmota#1658]
Hey guys, very noob question, I setup a wemos d1mini and a MQ5 sensor reading value from `Analog0`
I would like to get direct realtime value from http request, so I try this:
`http://192.168.0.5/cm?user=admin&password=admin&tele=Analog0`
or this:
`http://192.168.0.5/cm?user=admin&password=admin&tele=status`
I got `{"WARNING":"Enable weblog 2 if response expected"}`, but I've alrady set all log level to debug, still I can't get an Analog0 value

What exact address I should type in order to get an Analog0 realtime value? Please help, thanks!!

**Comment by reloxx13** [comment]
their is no tele command
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

Your url is wrong, too.
