### ISSUE TITLE
Using Sonoff Basic for controll a lamp manually

### ISSUE THREAD

**Issue by goncalvesdiogo** [arendst/Sonoff-Tasmota#166]
Hi all,
I'd like to apologise by my bad english in advance.

What I need to do is to put a sonoff basic module inside the switch box in the walls of my home.
I did test and the sizes fits perfectly but I was wondering how can I hit the switch button once it is inside the wall?? The answer I found is to use a momentary switch(that is like a bell switch) to trigger the relay by soldering 2 wires on the sonoff button and so create a second way to control.

My question is,  If I decide to use the GPIO14 instead to solder the 2 wires, where else I need to plug the other wire? I mean should be 1 wire coming out the 3.3vcc and going to the momentary switch and another one from momentary switch to the GPIO14. Does not need to put some resistors?

Another question, the switch mode I need to use, may I keep it as TOGGLE?

I hope you guys understand what I am trying to do. I understand that the issues here should be about the TASMOTA firmware but I don't know where else I could get help.
Tks in advance.

**Comment by arendst** [comment]
One wire to GPIO14 the other to Gnd

**Comment by goncalvesdiogo** [comment]
Thank you so much Theo. Regards.

**Comment by davidelang** [comment]
did your question get fully answered? if so, can this issue be closed?

**Comment by goncalvesdiogo** [comment]
Yes the issue can be closed please. I'm newbie here. How can I do that?
