### ISSUE TITLE
RF Bridge 2 codes for one button

### ISSUE THREAD

**Issue by mpuff** [arendst/Sonoff-Tasmota#1660]
Hello,

is it possible to add a feature to learn 2 codes to one button, like up and down?
i want to intigrate a rollershutter (433mhz module) to openhab2, the samples are using commands up and down ore 1 and 0
Maybe someone can help me?

Thank you

**Comment by Jason2866** [comment]
I have some 433 Mhz poweroutlet switches, which needs some commands send from my Sonoff RfBridge to switch On and Off. In the UI is it a normal Switch.
The items definition is:
Switch WohnFluter   "WZFluter"          <light> (LR,gLight) [ "Lighting" ] 
		{ mqtt=">[broker:cmnd/sonoff-8E8329/Backlog:command:ON:RfSync 11320; RfLow 360; RfHigh 1090; RfCode #150551],
                >[broker:cmnd/sonoff-8E8329/Backlog:command:OFF:RfSync 11320; RfLow 360; RfHigh 1090; RfCode #150554]" }
Myhome.sitemap:
Switch item=WohnFluter label="Wz. Fluter"
