### ISSUE TITLE
Button Names for Web interface

### ISSUE THREAD

**Issue by stoehrmark** [arendst/Sonoff-Tasmota#1667]
Can the "Friendly Name" be used in the web interface instead of "Toggle".

I have and Electrodragon and would like to see the 2 switches as my "Friendly Names" or just under the button put the friendly names. 

eg

⌈‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾⌉    ⌈‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾⌉
|&nbsp;&nbsp;&nbsp;&nbsp;TOGGLE 1&nbsp;&nbsp;&nbsp;&nbsp; |    | &nbsp;&nbsp;TOGGLE 2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
⌊_______________⌋    ⌊_______________⌋

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TO

⌈‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾⌉    ⌈‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾⌉
| Kids Bathroom|    |&nbsp;&nbsp;&nbsp;Kids Shower &nbsp; |
⌊_______________⌋    ⌊_______________⌋
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OR
⌈‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾⌉    ⌈‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾⌉
|&nbsp;&nbsp;&nbsp;&nbsp;TOGGLE 1&nbsp;&nbsp;&nbsp;&nbsp; |    | &nbsp;&nbsp;TOGGLE 2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
⌊_______________⌋    ⌊_______________⌋
&nbsp;&nbsp;  Kids Bathroom&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kids Shower

As always thank you for all the hard work on this project.

**Comment by davidelang** [comment]
this is unlikely to happen due to the added ram/code space needed. Tasmota is 
primarily a mqtt based firmware, the web interface is for setup and 
debugging. So things that make it take more resources face an uphill battle.

**Comment by Chelovekmolekula** [comment]
Implement Please

**Comment by meingraham** [comment]
Try `WebButton<x> Desc` where `<x>` is the number of the button corresponding to the relay number. `Desc` is any text... but don't carried with long button descriptions.

**Comment by Chelovekmolekula** [comment]
> Попробуйте, `WebButton<x> Desc`где `<x>`находится номер кнопки, соответствующий номеру реле. `Desc`это любой текст ... но не переносится с длинными описаниями кнопок.

It worked, thank you so much!
Tasmota 8.1.0.3

**Comment by Chelovekmolekula** [comment]
> Try `WebButton<x> Desc` where `<x>` is the number of the button corresponding to the relay number. `Desc` is any text... but don't carried with long button descriptions.

It worked, thank you so much!
Tasmota 8.1.0.3

**Comment by lksmj** [comment]
이 게시물 덕분에 스위치 토글 이름을 설정할수 있어 큰 도움이 됐습니다.
감사합니다.~!

**Comment by ascillato** [comment]
> 이 게시물 덕분에 스위치 토글 이름을 설정할수 있어 큰 도움이 됐습니다.
> 감사합니다.~!

Using Google translate:

> Thanks to this post, it was very helpful to be able to set the switch toggle name.
> Thank you~!

**Comment by stiw47** [comment]
> Try `WebButton<x> Desc` where `<x>` is the number of the button corresponding to the relay number. `Desc` is any text... but don't carried away with long button descriptions.

Thank youuuuuuuuu!!!!

**Comment by telece2** [comment]
Is there any way to enter multiline messages in a long button description text, so that the tasmota home page keeps a reasonable width?
I tried without success the following: %n, \n, ~0D

Thanks

**Comment by sfromis** [comment]
Try with html, like `<br>`

**Comment by telece2** [comment]
Yes, that worked! Thanks a lot @sfromis!
