### ISSUE TITLE
Keeping track of all of the devices, how do you do it?

### ISSUE THREAD

**Issue by gajotnt** [arendst/Sonoff-Tasmota#1672]
Right now i have 7 devices using Tasmota, soon will be alot more, for now i can remenber all the IP for easy access to all of then, but when i get more, it will be alot harder, what do you guys use to keep track of the devices?
A document with links/names (html, word)? Or something diferent?

**Comment by davidelang** [comment]
I set fixed DHCP reservations in my router and define the name in DNS to go 
along with it.

I am running LEDE on my router, which makes doing this sort of thing trivial

**Comment by gajotnt** [comment]
Yes I also have the dnsnames and DHCP reservations, but still, soon it will be alot of devices to remember the names xD
Was just wondering what "y'all" used. 
Think I'm going to make a HTML file with links to the devices.

**Comment by calcipher49** [comment]
I use dnsmasq as DHCP server and I fix IP address knowing mac address (using dhcp-host command) for each sonoff device.

**Comment by thomasnordquist** [comment]
Use a MQTT broker which every device connects to, give every device a name and forget about their IP addresses.

I for one use mosquitto, it is very easy to set up.

MQTT allows you to send and receive status updates from your devices.

With DNS-only solutions you loose the abstraction and bi-directional communication and MQTT offers.

Worth mentioning: I believe the tasmota devices advertise their names using MDNS, so they should always have the same name, even without a dnsmask setup.

**Comment by arendst** [comment]
Prefer MQTT but I do use dnsmasq too ;-)

**Comment by davidelang** [comment]
On Mon, 22 Jan 2018, Thomas Nordquist wrote:

> With DNS-only solutions you loose the abstraction and bi-directional communication and MQTT offers.

why does having predictable, unique DNS names loose the bi-directional 
communications?

**Comment by thomasnordquist** [comment]
Maybe I explained it badly.
With MQTT you not only have solved the naming and you get real time updates
of your device.

If for instance someone turns on your 220V socket with the hardware button,
you'll be notified instantaneously.
So you don't need to poll for changes.

(You can "subscribe" to topics, if the topic "sonoff/some_device/POWER"
changes the MQTT server sends a notification to all clients which have
subscribed to this specific topic)

**Comment by gajotnt** [comment]
Simple html file with an iframe, and does the job of giving me easy acess to all my devices for when i need to update them or change any settings :)

![devices](https://user-images.githubusercontent.com/25504364/35241216-44d6d8fa-ffa5-11e7-8154-6c17d79fdcfe.JPG)

**Comment by reloxx13** [comment]
you could take a look at my [sonweb](https://github.com/reloxx13/SonWEB)

**Comment by gajotnt** [comment]
Awesome, i knew There had to be something like this :)
