### ISSUE TITLE
Lag on Sonoff Tasmota Basic Switch

### ISSUE THREAD

**Issue by kckepz** [arendst/Sonoff-Tasmota#1673]
I've flashed my Sonoff Basic switch with the Atom PlatinumIO application, very easy process thank goodness.  I've connected a light rocker switch to my Sonoff Tasmota and find that now and then (quite often) there is a lag when I activate it from my light switch, the button on the Sonoff or from the webpage.  Silly question but, is that the current normal behaviour of the Sonoff with Tasmota firmware?  If it isn't, how do I fix this?  It's really annoying.

Please help.

EDIT:  I should add, the lag is sometimes up to 5 seconds.
[https://photos.app.goo.gl/e6KtWY1Pv2ldAYso1](https://photos.app.goo.gl/e6KtWY1Pv2ldAYso1)

**Comment by gajotnt** [comment]
Is the MQTT server set right? This once happened to me and it was because i dindnt set the MQTT server and it was always trying to connect.

**Comment by kckepz** [comment]
Wow!  Was that all it was.... lol.  I'm not using a MQTT server but it was enabled on my Sonoff Tasmota.  I've turned that off and then VOILA!

Thank you @gajotnt

**Comment by gajotnt** [comment]
:)
