### ISSUE TITLE
RF Bridge Learn RF fails on Intertechno Codes

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#1682]
RF Bridge fails to learn this code (Intertechno):
RfSync 11320; RfLow 360; RfHigh 1090; RfCode #150551

If is send that code manually via console or MQTT the Intertechno Poweroutlet switches. 

it decodes following (false!) and learning needs many attempts and when the saved result fails:

15:49:56 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11280,"Low":370,"High":1080,"Data":"15115F","RfKey":"None"}}
15:49:58 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11290,"Low":370,"High":1080,"Data":"151154","RfKey":"None"}}
15:49:58 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11290,"Low":370,"High":1080,"Data":"15155F","RfKey":"None"}}
15:50:01 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11290,"Low":370,"High":1080,"Data":"15155F","RfKey":"None"}}
15:50:04 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11280,"Low":370,"High":1080,"Data":"151454","RfKey":"None"}}
15:50:04 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11280,"Low":370,"High":1080,"Data":"15155F","RfKey":"None"}}
15:50:08 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11290,"Low":370,"High":1080,"Data":"15155F","RfKey":"None"}}
15:53:18 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11280,"Low":370,"High":1080,"Data":"15155F","RfKey":"None"}}
15:53:20 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11340,"Low":360,"High":1090,"Data":"15155F","RfKey":"None"}}
15:53:22 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11290,"Low":370,"High":1080,"Data":"150551","RfKey":"None"}}
15:53:22 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11290,"Low":370,"High":1080,"Data":"15155F","RfKey":"None"}}
15:53:25 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11300,"Low":370,"High":1090,"Data":"15155F","RfKey":"None"}}
15:53:27 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11290,"Low":370,"High":1080,"Data":"150551","RfKey":"None"}}
15:53:29 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11330,"Low":360,"High":1090,"Data":"15055F","RfKey":"None"}}
15:53:31 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11320,"Low":370,"High":1080,"Data":"15055F","RfKey":"None"}}
15:53:36 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11290,"Low":370,"High":1080,"Data":"15155F","RfKey":"None"}}
15:53:37 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11280,"Low":370,"High":1080,"Data":"150551","RfKey":"None"}}
15:53:38 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11310,"Low":370,"High":1080,"Data":"15155F","RfKey":"None"}}
15:53:39 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":11330,"Low":370,"High":1080,"Data":"15055F","RfKey":"None"}}

BUT: This code is recognized correct and can be learned (in first attempt)!
15:58:53 MQT: tele/sonoff-8E8329/RESULT = {"RfReceived":{"Sync":12900,"Low":1230,"High":450,"Data":"35750C","RfKey":2}}

**Comment by Oimel1981** [comment]
Send your code with "RFCode #150551" and then save it with "RfKey<x> 4"
