### ISSUE TITLE
Multiple controllers

### ISSUE THREAD

**Issue by dixonjamesa** [arendst/Sonoff-Tasmota#1686]
Hi there. Wondering what the agreed/best way of having multiple switches control one relay might be...
I have two sonoff T1 duals. One has both relays connected to two lights. The other has one switch controlling a third light, but I would like the second switch to control one of the lights attached to the first T1.
Hope that makes sense?

**Comment by ionciubotaru** [comment]
configure switchTopic and switchMode to send a proper mqtt message to toggle the relay https://github.com/arendst/Sonoff-Tasmota/wiki/Understanding-SwitchMode-and-SwitchTopic

If you need a more complex logic use your HA system to send mqtt commands to toggle relays when it receives a switch change message
