### ISSUE TITLE
Custom Variables for HomeKit and other

### ISSUE THREAD

**Issue by profesionalTI** [arendst/Sonoff-Tasmota#1687]
Hi, I work on Thermostat with Sonoff Basic and Sonoff TH16. I need to create a some variables and it's can change by MQTT, if power lost, they recover last value, the variables for HomeKit Thermostat are:

CurrentHeatingCoolingState
TargetHeatingCoolingState
CurrentTemperature
TargetTemperature
TemperatureDisplayUnits
CoolingThresholdTemperature
CurrentRelativeHumidity
HeatingThresholdTemperature
Name
TargetRelativeHumidity

Many HomeKit accessory have another variables, but I need to know how modify Tasmota to insert this variable, and create custom Tasmota por another HomeKit accessory.

We need to request and update this value by MQTT and recover the last value if power lost.

Thanks for any help.
@arendst @solucionesmipc

**Comment by ascillato** [comment]
Hi, If this solves your issue, please close it. Thanks :+1:
