### ISSUE TITLE
beebotte mqtt

### ISSUE THREAD

**Issue by drbeat** [arendst/Sonoff-Tasmota#1689]
hi,

I can not connect to the beebotte mqtt https://beebotte.com/

cloudmqtt works fine but somehow it does not want to connect to the mqtt of beebotte

not sure if it is regarding the way beebotte authenticates by leaving the pw empty

https://beebotte.com/docs/mqtt#auth

> When establishing a connection, you provide token:your_channel_token as username and leave the password blank. If the given token is not valid (not associated to any channel), the connection will be dropped. This authentication provides read and write access to only one channel: the one the token is associated with. If you think the token was compromised, you can simply regenerate a new token for the corresponding channel.

anyone knows more or already tried that?

**Comment by deviant-studio** [comment]
same issue. can't get it to work
