### ISSUE TITLE
Mqtt and change sonoff type

### ISSUE THREAD

**Issue by martinlindjarv** [arendst/Sonoff-Tasmota#1701]
I tried to find from wiki how to change type with mqtt but failed. 

The story is that if i compile my own firmware at the beginning i define type as basic but image will go to touch. After first boot i’ll have to go to web and change type and then disable web. 

My question - can somebody help me to change type over mqtt?

P.s Thank you for great firmware!

Martin

**Comment by arendst** [comment]
The commands module and modules are made for you.....

**Comment by martinlindjarv** [comment]
Excellent, thank you!

Looked and tried to find - but it slipped ... 

Martin
