### ISSUE TITLE
2 basics latest update with different iDs showing up as one.

### ISSUE THREAD

**Issue by mestes136** [arendst/Sonoff-Tasmota#1702]

**Comment by mestes136** [comment]
It is being reported the same as the trouble shooting described for devices with the same “client_ID”. But mine have different project friendly and host names. Any help would be appreciated!

**Comment by ascillato** [comment]
Hi, I don't understand. Please, expand your explanation.

**Comment by Frogmore42** [comment]
You need to change the Topic name on the MQTT config page.  If you have done this already, you will need to show some logging from both devices.
