### ISSUE TITLE
Sonoff basic firmware upgrade webinterface

### ISSUE THREAD

**Issue by marcgrc** [arendst/Sonoff-Tasmota#1710]
hello everyone I have a problem.
I can not update the firmware with a web interface.
the line that gives is this
http://domus1:80/api/arduino/sonoff.ino.bin
 but when you restart the version remains the same.
thank you so much

**Comment by ionciubotaru** [comment]
Try to download sonoff.ino.bin from your computer using chrome or other browser to check if the address is correct.

**Comment by marcgrc** [comment]
from where I unload sonoff.ini.bin ??

**Comment by ionciubotaru** [comment]
from http://domus1:80/api/arduino/sonoff.ino.bin 
I'm not sure this address is correct - if you are not familiar with web server try to upload the bin file via web interface manually

**Comment by marcgrc** [comment]
Ok thank
http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin
It’s ok
I have another question 
Before to flash sonoff basic 

just bought you have to do something ??

**Comment by SodoffBaldrick** [comment]
If it's OTA then no. Just go for it. 
Perhaps back up your settings if you're at all bothered by that, but by default it won't overwrite any settings.

**Comment by marcgrc** [comment]
Sorry 
OTA ????
