### ISSUE TITLE
Remote access. Port forwarding to sonoff. No access. 

### ISSUE THREAD

**Issue by storm66-ag** [arendst/Sonoff-Tasmota#1711]
Hello. I use sonoff tasmota FW. Thank you for it.  Everything is working, but web access works in local network only. If set port forwarding from Internet, using wifi router, that web page is not downloads, but appear login:password window and it's all. No web panel, not menu. But in local lan its available. 
I believe it may latency ????

**Comment by mzhur** [comment]
Are you use the DHCP configuration on Sonoff?
I'm not sure, but it should be problem in router firewall probably. 
And one more think, some internet providers close the port 80, and some times ports below 1024 for incoming connection.
Would you try to move the tasmota web server port up to 10 000 in the user_config.h.

**Comment by storm66-ag** [comment]
Yes, DHCP configuration used. Is  port 80 only using  in tasmota SW for web access, or same else ports? 
I see the login and password window, after insert I see white  screen. If so the firewall is working correctly and provider is not blocking port 80. May be this from hight latency? I used LTE network with: 
round-trip min/avg/max/stddev = 25.645/180.648/571.087/139.173 ms

**Comment by mzhur** [comment]
Ok, first time, i'm not clear understand the situation. I don't know about

**Comment by mzhur** [comment]
the latencity influence to the tcp/ip engine in esp8266

**Comment by storm66-ag** [comment]
I have WiFi router with Build in lte modem. Sonoff connected to WiFi network, and in local network everything working good. But I need accces to sonoff module from internet. I set port forwarding on router. The router has public IP address. And doesn’t show web page from internet.

**Comment by mzhur** [comment]
I try to test it with my sonoff during the weekend...

**Comment by storm66-ag** [comment]
Ok, try please.  And use last software please.

**Comment by storm66-ag** [comment]
I try with other provider and other router, its everything ok.

**Comment by storm66-ag** [comment]
its working on sonoff TH. But for sonoff basic is not working......

**Comment by storm66-ag** [comment]
![image 2018-01-28 14 55 25](https://user-images.githubusercontent.com/35832163/35480929-47673dd6-043b-11e8-984c-622a5d799782.jpg)

**Comment by storm66-ag** [comment]
This is that I get.

**Comment by mzhur** [comment]
I try with my modem and Sonoff Basic. In my case it work, but i have fasters pings...

**Comment by storm66-ag** [comment]
With fast ping it’s working very well, but if round trip delay is more than 150-200 ms - it’s not working...

**Comment by sonoffheld** [comment]
i have the same Problems with openvpn thats not worked .
with an ssh connection over a tunnel and proxy everything works fine.
