### ISSUE TITLE
alexa read temp from WeMos D1

### ISSUE THREAD

**Issue by cobra85ec** [arendst/Sonoff-Tasmota#1713]
can alexa read temp from WeMos D1 mini with DHT11

**Comment by SodoffBaldrick** [comment]
Not directly I believe. You'd want to have an MQTT broker installed somewhere which is connected to Amazon.
So the WeMos reports the status via MQTT to a server. Alexa is configured to connect to the server and read the variable for that particular sensor.

Have a look into Home Assistant.

**Comment by cobra85ec** [comment]
i have MQTT on a pi3 with node-red also...

**Comment by Jason2866** [comment]
Install OpenHab on the Pi. With the HueEmulation (you have to install via Paper UI) is this possible.
You have to "Tag" this item... Alexa will discover it...
I use this in my Homeautomation with a DHT22 (more accurate).
