### ISSUE TITLE
new wiki page - Expand Sonoff 4CH with jack plug 

### ISSUE THREAD

**Issue by gtortone** [arendst/Sonoff-Tasmota#1718]
Hi @arendst,
I just finished this wiki article: https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-4CH but images are loaded on my fork of Sonoff-Tasmota (https://github.com/gtortone/Sonoff-Tasmota/tree/development/_temp_imgs)...

what do you think about transferring them on your wiki repo ?

**Comment by arendst** [comment]
Will do and let you  know when done.

**Comment by arendst** [comment]
Done
