### ISSUE TITLE
Announcement: New Domoticz plugin for Tasmota

### ISSUE THREAD

**Issue by emontnemery** [arendst/Sonoff-Tasmota#1731]
### Domoticz plugin for autodetection ot Sonoff-Tasmota devices

Benefits over Domoticz "dummy device" method:
- Auto detection of devices
- Domoticz state is synchronized with device state
- Note: Buttons are not yet supported
- Note: Sensors are not yet supported

Instructions here: https://github.com/emontnemery/domoticz_mqtt_discovery

**Comment by mvveelen** [comment]
Nice ! 

But where can I find a Sonoff.bin that's newer than 5.11.1 ?

**Comment by ascillato** [comment]
Now there is the 5.11.1g but you have to compile it. See the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more info.

**Comment by mvveelen** [comment]
Ah, so then I have to use Atom or such..... thanks.
