### ISSUE TITLE
SerialException when rebooting after flashing

### ISSUE THREAD

**Issue by Timmiej93** [arendst/Sonoff-Tasmota#1737]
Hi all,
I followed [this](https://www.youtube.com/watch?v=n4MDRm2yAJg) tutorial video by QuickPi to try and get my sonoff up and running. Up until the 5:00 mark, it all seems to work. However, when I have the terminal / console window open and disconnect and connect the 3.3v supply, I immediately get an error.

Upon removing power:
`␀` (nul icon/character)

Upon reconnecting power:
```Exception in thread rx:
Traceback (most recent call last):
  File "C:\Users\Tim\.platformio\python27\Lib\threading.py", line 801, in _
_bootstrap_inner
    self.run()
  File "C:\Users\Tim\.platformio\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\users\tim\.platformio\penv\lib\site-packages\serial\tools\miniterm.py", line 445, in reader

    data = self.serial.read(self.serial.in_waiting or 1)
  File "c:\users\tim\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 293, in read
    raise SerialException("GetOverlappedResult failed ({!r})".format(ctypes.WinError()))
SerialException: GetOverlappedResult failed (WindowsError(5, 'Access is denied.'))
```

I tried googling this issue, but haven't had any luck. I also tried following [this](https://www.youtube.com/watch?v=-JxPWA-qxAk) video tutorial by BRUH Automation, which uses the Arduino IDE. This one had pretty much the same effect: up until the 11 minutes mark, I can follow along perfectly fine, but the device never shows up in the network.

Since it may be relevant: I also wasn't able to get the sonoff to work with the original ewelink app (android). I tried all kinds of connection techniques. Each time it found the device (showing 'found first gen. device [devicecode]'), but it never got past that. When the blue bar in that app reached the 2/3rds mark, the process stops, saying it can't connect.

Would this indicate that the sonoff is a bust, or is there something else going on?

Edit:
This just caught my eye:
> Only Flash Mode DOUT is supported. Do not use Flash Mode DIO / QIO / QOUT as it might seem to brick your device.

The video by BRUH Automation used DIO. I stupidly followed that video before looking at the GitHub. Would this be an indication of a bricked device?

**Comment by umar14** [comment]
I have a similar issue. I kept flashing serially using Arduino IDE with DIO setting. Got nothing. Then flashed using DOUT and the Serial RX LED on my CH340 Serial->USB converter is ON and serial port is not accessible. Firmware uploads fine in both cases but I can't access the serial port. It's stuck. Can I assume the device is bricked? The firmware uploads successfully, it's just that the program doesn't run.
