### ISSUE TITLE
External button

### ISSUE THREAD

**Issue by Kiwifranky** [arendst/Sonoff-Tasmota#1742]
HI,

I want to connect a free GPIO to a button and on a push of this button I want to receive a MQTT message. The button should not change the relais, but only be another digital input which is broadcast via MQTT. I did not find the right commands but maybe there exists something like this already in TASMOTA. (I want the message dispatched immediately not at the next status report!)

Your help is appreciated

Frank

**Comment by Kiwifranky** [comment]
Found the solution...

Setup one UserGPIO as Relay2 and an other as Switch2. Now I get a MQTT message when the state of the input changes...

**Comment by gertmenke** [comment]
Is this also possible without sacrificing a UserGPIO for a virtual relay?

**Comment by Kiwifranky** [comment]
I can't remember exactly, but I think the software will only activate the mechanism for relay/button2 when both are found... Try it...
