### ISSUE TITLE
Sonoff RF Bridge learn manually to a QH-C-CE-3V button

### ISSUE THREAD

**Issue by maartenpaauw** [arendst/Sonoff-Tasmota#1748]
My Sonoff RF Bridge wasn't able to learn from a RF button (QH-C-CE-3V).

With my Arduino and a RF receiver I was able to get te following information:

```
Decimal: 125680 (17Bit) Binary: 11110101011110000 Tri-State: not applicable PulseLength: 368 microseconds Protocol: 0
Raw data: 5844,1076,1124,344,1124,348,1120,348,1124,344,392,1080,1124,344,392,1080,1128,340,396,1072,1128,344,1124,344,1128,344,1128,344,396,1072,396,1076,400,1068,400,
```
How do I configure my Sonoff RF Bridge to listen to this button?

**Comment by Jason2866** [comment]
I dont think that is possible. The decoding is not done by the ESP. This is done by the chip  EFM8BB1.
This chip is connected to the ESP (serial). I dont think that your protocol is implemented...
May you have a look at this firmware. There you can input and save received codes.
https://bitbucket.org/xoseperez/espurna
