### ISSUE TITLE
how can I modify the program to notify the status of a sonof in mqtt every given time

### ISSUE THREAD

**Issue by vivi202** [arendst/Sonoff-Tasmota#1753]
sorry for my bad english thanks in advice

**Comment by smadds** [comment]
From the web interface: Configuration, Configure Logging, Telemetry period. Set to number of seconds between updates.

From MQTT use command teleperiod (https://github.com/arendst/Sonoff-Tasmota/wiki/Commands)

**Comment by smadds** [comment]
Why would you want to?

The point of MQTT is that devices publish updates **when something changes** - and that change is passed on to subscribers. It saves endless polling traffic on the network. So, just subscribe to a topic and wait for an update.

To check the device is still alive, you can define the logging period (mqtt command teleperiod or from the web interface - Configuration, Configure logging, Telemetry period) and subscribe to tele messages.
