### ISSUE TITLE
Version 5.11.1h Formatting error Sonoff POW main page

### ISSUE THREAD

**Issue by chkbln** [arendst/Sonoff-Tasmota#1754]
Hello
With the version 5.11.1h, the display of the measured values on the Sonoff POW looks like shown in the picture. Since my formatting is missing from my point of view. Applies to IE11, Firefox. I have not tested other browsers yet.
Best regards
![grafik](https://user-images.githubusercontent.com/11814828/35592487-63635726-060d-11e8-9b1a-f8f82361e492.png)

**Comment by arendst** [comment]
Fixed just now ;-)

**Comment by chkbln** [comment]
Hello

works again. Thank you
