### ISSUE TITLE
Pre-define IDX value in config prior to flashing

### ISSUE THREAD

**Issue by Reconos87** [arendst/Sonoff-Tasmota#1756]
Sorry if i've somehow missed it.

But i can't seem to find a place to input my IDX in the settings files.

The reason for this is that i keep 1 folder per device that, and all settings set in user_config, so that if i screw up, it would be quite easy to restore the device.

If this is not possible by default, i'd like it as a feature request :+1: 

Keep up the good work!

**Comment by arendst** [comment]
Defeats the purpose of one size fits (almost) all.
