### ISSUE TITLE
gpio3 or another (not gpio14) can be used as a switch?

### ISSUE THREAD

**Issue by fgvicente** [arendst/Sonoff-Tasmota#1759]
I have seen that the gpio3 (TX) can be used as a switch. But I do not know how to do it. I currently use gpi14 for a dht11 and would like to use the gpio3 or another to connect it to the wall switch. 

Can someone help me with this?
thanks in advance.

**Comment by gajotnt** [comment]
Yes it can.
But i think you have to turn off Serial Logs

**Comment by fgvicente** [comment]
not problem with to turn off Serial Logs.

 @gajotnt you know how to set it. can i help me?
