### ISSUE TITLE
Virtual device feature request

### ISSUE THREAD

**Issue by nosaj66au** [arendst/Sonoff-Tasmota#1764]
I have been looking at ways to maintain the same "out of the box" Tasmota version across my entire HA system, no "Firmware specials". I have solved my problem with a workaround and other may be interested in and this enhancement could create some interesting possibilities.

**Problem:** Ultrasonic Level Measurement - Tasmota has all the MQTT infrastructure and network setup but doesn’t support the sensor if I modify the firmware for just for this sensor I break the standards convention I would like to uphold.

**Solution:** All I needed was a tiny Arduino, in my case Digispark (AtTiny85) and used the serial cmd interface on the ESP8266 (Wemos D1 Mini) and tasmota firmware. I selected a random pin and tied it to ground and made it a counter. Bingo!!! 
My Digispark read and evaluates the sensor providing a value, then send a command to Tasmota via serial to set the counter to x. Tasmota does the rest. In my case I used the Relay1 to stop and start the pump. 

**Feature Request:** Can we have a Few of Virtual devices that have no physical pins just a memory space, each with a name accessible by the commands. This will prevent the need to use the counter space and pin like I have.
Jason

**Comment by ascillato** [comment]
Now are available the commands VAR and MEM for that.

Please, see the wiki.

Thanks
