### ISSUE TITLE
Inform about state Lights after switch on wall physical button 

### ISSUE THREAD

**Issue by radebebek** [arendst/Sonoff-Tasmota#1769]
Hello All,

I have this scheme wiring: http://prntscr.com/i0qrfb

I used homebridge plugin and iphone app HOME and I have problem about inform state.

Example:

1. State Lights on HOME app is OFF.
2. Turn on Lights with HOME app on R1 relay, snd Sonoff PRO switch reley and Lights is ON. On app HOME change state to ON.
3. When I pressing physical key "WALL SWITHC" Disconnect Electric Cricuit and turn off Light.
State continue ON on HomeAPP.
How to inform app that state is change? Can you help me this plugin?

Rade

**Comment by mattlward** [comment]
I am not sure that it could notify on that state change.  Nothing affects the relay and therefore the relay, which caused the action is still on.  One option would be to change the light switch to a device that can transmit a signal that either the device driving the relay or an HA server would receive and then it would turn the light off, maintaining state.  

For example if you remove the relay from the process and have an extension cord with a light plugged in to it.  If you unplug the light that does not kill power at the business end of the extension cord, it only removes power from the bulb causing it to go out.

You will really need something to provide that feedback.
