### ISSUE TITLE
Disable button usage

### ISSUE THREAD

**Issue by alescolos** [arendst/Sonoff-Tasmota#1770]
Hi, I would like to disable button usage 
mentioned here [https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage](url)

I want that the main button works as a triggering relay button and DOES NOT enable others working mode (AP MODE etc...) because I use it as main button to trigger the relay and sometime is pushed too many times (from childrens) and unfortunately others working modes are enabled.

Is possible to do that?
Thank you

**Comment by gajotnt** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

Setoption13 ...

**Comment by alescolos** [comment]
thank you so much :D
