### ISSUE TITLE
calling your attention to a technique of saving ram (strings in progmem)

### ISSUE THREAD

**Issue by davidelang** [arendst/Sonoff-Tasmota#179]
I haven't looked to see if you are already doing this, if not this could potentially save some ram for fixed strings.

https://gist.github.com/sticilface/e54016485fcccd10950e93ddcd4461a3

On low memory devices like the arduino and esp8266 you do not want strings to be stored in RAM. This occurs by default on these systems. Declare a string const char * xyz = "this is a string" and it will use up RAM.

The solution on these devices is to allow strings to be stored in read only memory,

**Comment by arendst** [comment]
David thnx for the info. Most strings are already in ROM though and that also is reaching the magical border of (1G - 64k) / 2...
