### ISSUE TITLE
Device Crash after alot cmnd Requests 

### ISSUE THREAD

**Issue by reloxx13** [arendst/Sonoff-Tasmota#1793]
Heya,

since 5.11.1i (maybe before, but not with stable 5.11.1) the device is crashing over ~115 request with 
http://SonoffIP/cm?cmnd=Status%200

It does not matter how fast you do those requests, its always crashing after that amount of requests.

i reproduce this with just spaming ctrl+r.

i noticed this by sonweb with a refrshtime of 15sec its crashing the devices after 1-2h.

Restart Reason says only "Software Watchdog".

i tried to reduce sleep from 150ms to 50ms but no change.

Heya,

since 5.11.1i (maybe before, but not with stable 5.11.1) the device is crashing over ~115 request with 
http://SonoffIP/cm?cmnd=Status%200

It does not matter how fast you do those requests, its always crashing after that amount of requests.

i reproduce this with just spaming ctrl+r.

i noticed this by sonweb with a refrshtime of 15sec its crashing the devices after 1-2h.

Restart Reason says only "Software Watchdog".

i tried to reduce sleep from 150ms to 50ms but no change.

 {
  "Status": {
    "Module": 1,
    "FriendlyName": "sOnOff-1",
    "Topic": "sonoff",
    "ButtonTopic": "0",
    "Power": 1,
    "PowerOnState": 3,
    "LedState": 1,
    "SaveData": 1,
    "SaveState": 1,
    "ButtonRetain": 0,
    "PowerRetain": 0
  },
  "StatusPRM": {
    "Baudrate": 115200,
    "GroupTopic": "sonoffs",
    "OtaUrl": "http://192.168.178.XX:XX/data/firmwares/sonoff-minimal.bin",
    "Uptime": 0,
    "Sleep": 50,
    "BootCount": 13,
    "SaveCount": 23,
    "SaveAddress": "FA000"
  },
  "StatusFWR": {
    "Version": "5.11.1i",
    "BuildDateTime": "2018.02.04 18:43:21",
    "Boot": 31,
    "Core": "2_4_0",
    "SDK": "2.1.0(deb1901)"
  },
  "StatusLOG": {
    "SerialLog": 0,
    "WebLog": 4,
    "SysLog": 0,
    "LogHost": "domus1",
    "LogPort": 514,
    "SSId1": "XXX",
    "SSId2": "XXX",
    "TelePeriod": 300,
    "SetOption": "00000001"
  },
  "StatusMEM": {
    "ProgramSize": 457,
    "Free": 544,
    "Heap": 23,
    "ProgramFlashSize": 1024,
    "FlashSize": 1024,
    "FlashMode": 3
  },
  "StatusNET": {
    "Hostname": "sOnOff-1",
    "IPAddress": "192.168.178.XX",
    "Gateway": "192.168.178.1",
    "Subnetmask": "255.255.255.0",
    "DNSServer": "192.168.178.1",
    "Mac": "2C:3A:E8:XX:XX:XX",
    "Webserver": 2,
    "WifiConfig": 4
  },
  "StatusTIM": {
    "UTC": "Sun Feb 04 19:35:18 2018",
    "Local": "Sun Feb 04 20:35:18 2018",
    "StartDST": "Sun Mar 25 02:00:00 2018",
    "EndDST": "Sun Oct 28 03:00:00 2018",
    "Timezone": 1
  },
  "StatusSNS": {
    "Time": "2018.02.04 20:35:18",
    "Switch1": "ON"
  },
  "StatusSTS": {
    "Time": "2018.02.04 20:35:18",
    "Uptime": 0,
    "Vcc": 3.496,
    "POWER": "ON",
    "Wifi": {
      "AP": 1,
      "SSId": "XX",
      "RSSI": 100,
      "APMac": "34:31:C4:XX:XX:XX"
    }
  }
}

**Comment by curzon01** [comment]
Try the same with same version you faulty testet but compile it using lib 2.3.0.

**Comment by reloxx13** [comment]
5.11.1e working fine with 2.40 (20h runtime now).

**Comment by arendst** [comment]
Pls try 5.11.1i with 2.3.0 too

**Comment by reloxx13** [comment]
7h uptime, confirm fixed 👍
