### ISSUE TITLE
Wait for Backlog before Restart

### ISSUE THREAD

**Issue by reloxx13** [arendst/Sonoff-Tasmota#1819]
Heya,

is it correct that the device is restarting instant if i change the NtpServer by console?

this also stops the backlog. if ntpserver1 is in the middle, the rest wont get saved/changed cuz the device restarted.

` Backlog Hostname Steckdose-1; IPAddress1 0.0.0.0; IPAddress2 192.168.178.1; IPAddress3 255.255.255.0; IPAddress4 192.168.178.1; NtpServer1 0.de.pool.ntp.org; AP 1; SSId1 YYY; SSId2 AAA; WifiConfig 4;`

The new ntpserver1 gets saved.

22:13:44 CMD: NtpServer1 0.de.pool.ntp.org
22:13:44 RSL: RESULT = {"NtpServer1":"0.de.pool.ntp.org"}

`{"RestartReason":"Software/System restart"}`

**Comment by reloxx13** [comment]
Okay, i just checked wiki again. The restart is normal, but would it be possible to wait for the backlog done before restart?

**Comment by reloxx13** [comment]
Checked with 5.11.1e, device is restarting AFTER backlog is done and everything got saved.

`Backlog Hostname Steckdose-1; IPAddress2 192.168.178.1; IPAddress3 255.255.255.0; IPAddress4 192.168.178.1; NtpServer1 0.de.pool.ntp.org; AP 1; SSId1 xxx; SSId2 ccc; Password2 yyy; WifiConfig 4;`

**Comment by arendst** [comment]
Checking...

**Comment by reloxx13** [comment]
thanks 👍 will it test it in the evening :)

**Comment by madduck** [comment]
This still seems to be an issue on v13. I cannot reliably execute a `Backlog` even if I can assure that nothing else happens on the device while the Backlog is executed.
