### ISSUE TITLE
location information

### ISSUE THREAD

**Issue by chkbln** [arendst/Sonoff-Tasmota#1820]
Hello Theo
It would be possible to implement location information (e.g., kitchens). The user can enter these via the frontend or the console. The location information could then be output via info and MQtt.

Best regards

**Comment by curzon01** [comment]
Why not using web interface "Configuration->Configure Other->Friendly Name" or command "[FriendlyName](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#management)"?

This information is also published using command "Status".

**Comment by ascillato** [comment]
Hi @chkbln 

If your issue was solved, please close it. Thanks :+1:
