### ISSUE TITLE
tasmota 5.11.1 MQTT Payload issues

### ISSUE THREAD

**Issue by Caswell1000** [arendst/Sonoff-Tasmota#1827]
1. I flashed Tasmota 5.11.1 (Thanks Arends for the dev work you are doing), I configured MQTT using the available menus, and tested them on the console menu. "Power ON", "Power OFF", "Power 1", etc, all work on the console. 
![image](https://user-images.githubusercontent.com/35820171/35958663-976a693a-0caa-11e8-8be8-e3030e8ef2e5.png)

2. I installed an app called MQTT dashboard on Android, and sent a topic like this 
/cmnd/Testchip/Power  

and it results in this output (which seems to be correct):

![image](https://user-images.githubusercontent.com/35820171/35958785-4c36d7d6-0cab-11e8-88ca-0891a8efca76.png)

3. When I send the same topic with a payload (/cmnd/Testchip/Power ON), I get : 

![image](https://user-images.githubusercontent.com/35820171/35958853-adf56abe-0cab-11e8-880b-46979991944b.png)

All topics with payloads, whether numerical (1, 2, 3, ...) or alphabetical ("ON", "OFF", "TOGGLE") result in:

![image](https://user-images.githubusercontent.com/35820171/35958913-e29272f8-0cab-11e8-8599-dc129b056a0d.png)

I am very keen to solve this problem, but my attempts with different combinations and different MQTT broker apps yield the same, please advise how I can change my Topic to make Payloads work.

**Comment by curzon01** [comment]
Nobody can help if an issue can not be reproduced. And for reproduce an issue, the tester needs to do the same as you. And you do not real want that a tester try every of the hundred apps with thousand of possible configuration variety.

An android app "

> MQTT Dashboard

" does not exist, it exists "_IOT MQTT Dashboard_", "_Linear MQTT Dashbard_" and several other "*MQTT Dash*" apps. Which of these hundred apps do you are using? And how did you configure it?


**In general**
- the MQTT implementation is essential in tasmota and it works as expected
- do not use leading / in topics. It is allowed but it produce an unnecessary empty topic level with a zero character at front

**Try reproduce**
A simple test using mosquitto and the same Tasmota configuration you re using confirms that the MQTT on Tasmota is working as expected. The problem can only be the Android app you are using but we do not know which app and how (config).

Here the tests with same config as you on Tasmota side but using command line mosquitto_pub for for publishing topics:

```
CMD: Status 6
MQT: /stat/Testchip/STATUS6 = {"StatusMQT":{"MqttHost":"172.17.9.3","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0EBA54","MqttUser":"mqttdev","MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
CMD: Topic
MQT: /stat/Testchip/RESULT = {"Topic":"Testchip"}
CMD: FullTopic
MQT: /stat/Testchip/RESULT = {"FullTopic":"/%prefix%/%topic%/"}
```

`$ mosquitto_pub -h localhost -u mqttdev -P ****** -t '/cmnd/Testchip/Power' -m ''`

```
MQT: /stat/Testchip/RESULT = {"POWER":"OFF"}
MQT: /stat/Testchip/POWER = OFF
```

`$ mosquitto_pub -h localhost -u mqttdev -P ****** -t '/cmnd/Testchip/Power' -m 'ON'`

```
MQT: /stat/Testchip/RESULT = {"POWER":"ON"}
MQT: /stat/Testchip/POWER = ON
```
`$ mosquitto_pub -h localhost -u mqttdev -P ****** -t '/cmnd/Testchip/Power' -m '1'`

```
MQT: /stat/Testchip/RESULT = {"POWER":"ON"}
MQT: /stat/Testchip/POWER = ON
```

**Comment by Caswell1000** [comment]
Thank you, Its IoT MQTT Dashboard, and I am iot.eclipse.org as a broker, the screenshot is shown below:

![image](https://user-images.githubusercontent.com/35820171/35970600-9c23756a-0cd3-11e8-91e3-7e73b07ba5e5.png)

The screenshot of my configuration is as follows:

![image](https://user-images.githubusercontent.com/35820171/35970622-b26d6e98-0cd3-11e8-8615-76e60f403219.png)

The app shows that there is connection to the broker

![image](https://user-images.githubusercontent.com/35820171/35970663-e00c4a04-0cd3-11e8-87ae-b8963e7def93.png)

Is there something wrong with the topic, apart from the leading "/", please assist, I am a noob, but I also read a lot, it could be that I am missing something small, the sonoff is on "Pulsetime 10"

Thanks for taking your time to respond.

**Comment by arendst** [comment]
Remove the ``on`` and add it to field ``Value to Publish`` as that is what you want; you want to publish the ``On`` value for topic ``/cmnd/Techchip/power``. Keep reading you're almost there ;-)

**Comment by Caswell1000** [comment]
Brilliant, this works perfectly, what's the proper way to subscribe on the iot mqtt bash board app if you want to get the messages from the sonoff in the app, I tried the one below, but I get "n/a" , otherwise thanks a lot for the advise, I'm so excited. Thank you very much. 

![img-20180208-wa0012](https://user-images.githubusercontent.com/35820171/35974265-07dbec58-0ce1-11e8-85c0-6b8a231c2458.jpg)

**Comment by curzon01** [comment]
@Caswell1000: You always do the same mistake - do not add parameters (here like `-n`) to topics - a subscribe topic `/cmnd/Testchip/status -n` does not exist, there exist for example `/stat/Testchip/STATE` having a JSON object.

Please carefully read [MQTT Topic definition](https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Features#mqtt-topic-definition), it's already described.

**Comment by Caswell1000** [comment]
Thank you @curzon01 , "/cmnd/Testchip/Power" in the subscription returns the value I have used under value to publish, my hope is to get something that the sonoff publishes, i.e. a direct status message from sonoff, not what I put under value to publish. I actually need to subscribe to a stat message, but "/stat/Testchip/Power" returns n/a so does "/cmnd/Testchip/status", perhaps the subscription is meant to just give you the same value one puts under value to publish. 

In graphics: When The Publication is:

![image](https://user-images.githubusercontent.com/35820171/35991171-ff1744ae-0d0e-11e8-9730-bbea35c3c177.png)

And the Subscription is:

![image](https://user-images.githubusercontent.com/35820171/35990933-552edc4a-0d0e-11e8-843d-66362128043e.png)


the result is :

![image](https://user-images.githubusercontent.com/35820171/35990975-702223f4-0d0e-11e8-852b-ff8540eafc30.png)


but when the subscription is:


![image](https://user-images.githubusercontent.com/35820171/35991033-97147246-0d0e-11e8-9ef0-9caee8ab2ec4.png)

I get : 

![image](https://user-images.githubusercontent.com/35820171/35991658-8a007f30-0d10-11e8-9bec-b6a185f82edc.png)

How do I get a status report from the sonoff??

Thanks for all the help that you are providing.

**Comment by tyjtyj** [comment]
Try enable json converter

**Comment by curzon01** [comment]
/stat/Testchip/POWER

not

/stat/Testchip/power

**Comment by Caswell1000** [comment]
Many Thanks, everything is now in order,  /stat/Testchip/POWER worked, I appreciate all the help I've had.

**Comment by centiane** [comment]
Hi , I use same app but i not found for me.
This is mi config MQTT in sonoff Tasmota.
![mqtt](https://user-images.githubusercontent.com/40582531/41879711-1873e8ac-78db-11e8-8a57-ddc3c268d23c.png)

and this is mi Broker
![mqtt_cat](https://user-images.githubusercontent.com/40582531/41879778-63a273f2-78db-11e8-8f4e-cf5bc4732da0.png)

how activate a power1 on?
I am a novice, and sorry for my english.
Regards Centiane.
