### ISSUE TITLE
Schemes are wrong when using #3 GRBW for SK6812 LEDs

### ISSUE THREAD

**Issue by roesl** [arendst/Sonoff-Tasmota#1847]
Hello,

I flashed firmware for SK6812 LEDs using   #define USE_WS2812_CTYPE     3                 // WS2812 Color type (0 - RGB, 1 - GRB, 2 - RGBW, **3 - GRBW**)

The colour schemes are now not as expected.

**Comment by roesl** [comment]
Please respond to my issue - thank you

**Comment by roesl** [comment]
Why doesnt respond anybody to my issue ??

**Comment by ascillato** [comment]
Hi @roesl 

Sorry that your issue was left unresponded. There were too many issues.

which option is the one you required? GRBW?

how that option is doing on your WS2812?

**Comment by roesl** [comment]
Hi @ascillato 

I will flash the actual firmware this week and check it again because I use the Ffrmware from McLighting in the moment
