### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by gemitro** [arendst/Sonoff-Tasmota#185]
I can't upload Tasmota 4.0.3 (with static ip) to Sonoff basic using Arduino IDE.
It compiles but when i try to upload it gives me the following errors.

[Sonoff.txt](https://github.com/arendst/Sonoff-Tasmota/files/835707/Sonoff.txt)

**Comment by lucwuyts** [comment]
I guess: wrong com-port

**Comment by davidelang** [comment]
On Sat, 11 Mar 2017, lucwuyts wrote:

> I guess: wrong com-port

or tx/rx reversed

**Comment by gemitro** [comment]
Both com port and tx/rx are ok.
I have successfully upload Tasmota more than 10 times when suddenly this happened.

**Comment by lucwuyts** [comment]
The error message is :  espcomm_open failed
Maybe the port is in use by another program?
Try to open the port with a terminal program?

**Comment by gemitro** [comment]
Maybe I damaged the usb to serial TTL when accidentally reversed the 3.3V to the ground for three minutes.

**Comment by macadamer** [comment]
On your USB/Serial dongle, connect together TX and RX and use the serial monitor tool in the Arduino IDE to send some characters, which should appear in the monitor main window if the dongle is working.

**Comment by gemitro** [comment]
Thanks
I connected together TX and RX on the USB/Serial dongle and sent a few characters with the serial monitor in the Arduino IDE as you suggested, but nothing appeared in the monitor main window.

**Comment by macadamer** [comment]
Ho hum!
