### ISSUE TITLE
Cannot set Friendly Name via web interface

### ISSUE THREAD

**Issue by laacz** [arendst/Sonoff-Tasmota#1850]
Installed Tasmota (Sonoff-Tasmota 5.12.0a, flashed via Arduino IDE) on Wemos D1 mini pro. Set module type to 18 (Generic). There is no "Friendly Name" input in "Configure Other":

![image](https://user-images.githubusercontent.com/181486/36062180-756a5284-0e6f-11e8-90ed-af1089247b3f.png)

**Comment by arendst** [comment]
Well if you do not configure any GPIO to be used as relay there is no need for a friendly name. 

I will change it in next pre-release to provide at least one friendly name option.
