### ISSUE TITLE
Updating to new firmware

### ISSUE THREAD

**Issue by Slip7000** [arendst/Sonoff-Tasmota#186]
Hi All,

Please share a small guide how and where to get the updated firmware and how to please.

**Comment by davidelang** [comment]
On Sat, 11 Mar 2017, Slip7000 wrote:

> Please share a small guide how and where to get the updated firmware and how to please.

The wiki goes through the steps that you need to use to compile the firmware and 
flash it. Is there something you have specific questions about?

David Lang

**Comment by Slip7000** [comment]
The option on the Sonoff itself gives an URL option or "Upgrade by file upload"

how can I use them?

TX

**Comment by Slip7000** [comment]
![sonoff upgrade slide](https://cloud.githubusercontent.com/assets/17448977/23823316/55c33dc8-0679-11e7-9226-079a7e753496.PNG)

**Comment by davidelang** [comment]
On Sat, 11 Mar 2017, Slip7000 wrote:

> The option on the Sonoff itself gives an URL option or "Upgrade by file upload"
>
> how can I use them?

compile the new firmware, and then either put it on a webserver (and use the URL 
option) or select it with the 'choose file' option and hit upgrade.

If you are using the arduino IDE, you can select the OTA option and have it 
compile and upload the file to the webserver (if you have the webserver setup 
for it)

**Comment by decologne** [comment]
Try the next url for update:
http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin

**Comment by davidelang** [comment]
did your question get answered? if so, can we close this issue?

**Comment by Slip7000** [comment]
Hi David I did not use the URL, but thank you very much for all your time and trouble. 
I reloaded the Sonoff with the new firmware via Atom as I received my new once and they also needed firmware for out of the box.

Thank you
