### ISSUE TITLE
[Question] Dose this Sonoff works with Tasmota?

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#1861]
Sonoff Touch 2 gang. 
https://www.aliexpress.com/item/32843738341/32843738341.html

**Comment by arendst** [comment]
Yes.

**Comment by shayshtern** [comment]
Thank you. 
May I ask so what's the difference between sonoff touch and sonoff T1?

**Comment by ascillato** [comment]
Hi

Sonoff T1 is for UK switch boxes and the Touch is for US switch boxes.

Please see the dimentions at:

http://sonoff.itead.cc/en/products/residential/sonoff-t1
http://sonoff.itead.cc/en/products/residential/sonoff-touch

Thanks
