### ISSUE TITLE
Problem with sonoff Basic to Flash

### ISSUE THREAD

**Issue by surftier** [arendst/Sonoff-Tasmota#1864]
Hello,
i get an Sonoff basic th v1.1 2017-5-5 and a sonoff pow. The pow was easy to flash with arduino IDE,
but the basic will not work. If I flash it with the arduino IDE the progress bar went from 0 to 100%. 
After Reboot I got a Bootloop. But i don't know why.
`
00:00:00 Projekt basic01 Sonoff (Topic sonoff, Fallback DVES_067421, GroupTopic sonoffs) Version 5.11.1
00:00:00 WIF: verbinden mit AP1 WLAN90a in Modus 11N wie sonoff-5153...

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v60000608
~ld
⸮
00:00:00 Projekt basic01 Sonoff (Topic sonoff, Fallback DVES_067421, GroupTopic sonoffs) Version 5.11.1
00:00:00 WIF: verbinden mit AP1 WLAN90a in Modus 11N wie sonoff-5153...

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v60000608
~ld
`
I don´t know what went wrong.
Is the ESP8266 Chip broken
Sorry for my bad English

Andre

**Comment by Jason2866** [comment]
Hi,
did you flash with Option DOUT?
I had one NodeMCU which was "dead" i managed to recover it ONLY with esptool
[ESPTool_WriteFlash.txt](https://github.com/arendst/Sonoff-Tasmota/files/1714568/ESPTool_WriteFlash.txt)

**Comment by surftier** [comment]
Hi, 
the Problem is solved.
It was caused of my self. I used the sonoff Basic with the Voltage out of the Programadapter to check it run. As I plugged the Basic to Mains the Basic work fine...
