### ISSUE TITLE
Sonoff SV

### ISSUE THREAD

**Issue by mcfarlde** [arendst/Sonoff-Tasmota#1876]
Hi, its been awhile since I used Atom and Platformio, so updated everything 1.6.0/2.4.0 and try 5.12 as regular Sonoff.  Get this:00:00:00 Project sonoff Sonoff138 (Topic sonoff, Fallback DVES_053E5B, GroupTopic sonoffs) Version 5.12.0
00:00:00 WIF: Connecting to AP1 58F in mode 11N as sonoff-7771...

Exception (28):
epc1=0x40229adc epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000001 depc=0x00000000

ctx: cont
sp: 3fff34c0 end: 3fff3b80 offset: 01a0
Any ideas?

**Comment by Frogmore42** [comment]
try 2.3.0, many people have had issues with 2.4.0 (though some have been successful).

**Comment by mcfarlde** [comment]
I'm assuming it is a bad SV and moving on.
