### ISSUE TITLE
Where to put #define USE_MINIMAL?

### ISSUE THREAD

**Issue by oxcxsxixbxaxn** [arendst/Sonoff-Tasmota#1883]
Hi, 
I ran into problem with firmware being too big to upgrade via the config webpage.
I tried putting #define USE_MINIMAL  into the user_config.h but the resulting firmware.bin was the same size...  Where should this directive go?  In the end I just downloaded a minimal image from the github, but was wondering how to build this myself...

Cheers

**Comment by jhlweb** [comment]
Just remove the slashes before `"//#define BE_MINIMAL" ` its almost at the end of the user_config.h file

**Comment by oxcxsxixbxaxn** [comment]
Ah, so it is...   serves me right for reading the wiki...

Thanks
