### ISSUE TITLE
MQTT_TOPIC

### ISSUE THREAD

**Issue by ionciubotaru** [arendst/Sonoff-Tasmota#190]
When the configuration is reset or on the first upload all Sonoffs will publish on the same topic.
`#define MQTT_TOPIC             PROJECT           // [Topic] (unique) MQTT device topic`

A good enhancement will be:
`#define MQTT_TOPIC      "%s-%04d"   `

**Comment by arendst** [comment]
Search issues. Has been answered many times.

**Comment by ionciubotaru** [comment]
Sorry, my mistake
