### ISSUE TITLE
Sonoff timer function. 

### ISSUE THREAD

**Issue by echo4019** [arendst/Sonoff-Tasmota#1902]
Hi, 

Does anyone know if there is an easier way to set a timer for activation/deactivation on Home Assistant?

As far as I know the only way to turn on or off the Sonoff through Home Assistant at a specific time and date is to create an automation for it. 

Is there any way of doing this through the front end, much like the Sonoff software allows before flashing?

Thanks.

**Comment by reloxx13** [comment]
if you got a server/raspy you could just make a cronjob which curls a https command.

**Comment by ascillato** [comment]
Now Tasmota has Timers.

Please read the wiki for further information.
