### ISSUE TITLE
Sonoff POW not detecting Energy stats

### ISSUE THREAD

**Issue by ivelinu** [arendst/Sonoff-Tasmota#1907]
My Sonoff POW with Tasmota looks like does not get the Energy data:

15:44:52 MQT: tele/MissSilvia/SENSOR = {“Time”:“2018-02-13T15:44:52”,“ENERGY”:{“Total”:0.000,“Yesterday”:0.000,“Today”:0.000,“Period”:0,“Power”:0,“Factor”:0.00,“Voltage”:0,“Current”:0.000}}

This is what I get from the console of my Tasmota flashed device.
Has anyone experienced such issue?
It refreshes every 5 min or so but everything is 0.

**Comment by reloxx13** [comment]
Calibrated?
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Pow#calibration

**Comment by ivelinu** [comment]
I did not, but is it possible every single reading to be 0 not even little deviation but 0?

**Comment by Frogmore42** [comment]
That is not normal.  Even uncalibrated it should be showing something, assuming its relay is on and you have a large load attached.  If you only have a really small load or it is off, it will return 0.

Which version are you using?

**Comment by ivelinu** [comment]
@Frogmore42 
I agree I have coffee machine attached to it with at least 800W and about 12A.
I am using Sonoff-Tasmota 5.11.1.
I am more to that something is missing in the code for the Sensors to work, may be wrong version, or commented out code by default that I need to uncomment. I do not have much experience with flashing these devices this is my second one and 1st with sensors like that.

Sonoff Pow Module
Miss Silvia

Voltage | 0 V
-- | --
0.000 A
0 W
0.00
0.000 kWh
0.000 kWh
0.000 kWh

**Comment by ivelinu** [comment]
I wired it by specs on Sonoff since it was weird one, but I am sure the wiring is fine. The device is actually older one I got it March/April 2017. Could it be the device, and what in the device?

**Comment by jpvissers** [comment]
I had the same problem after flashing with Tasmota. I changed the module for Sonoff Pow R2 to Sonoff Pow and now it works perfect.

**Comment by mcoms** [comment]
I also have this problem with Sonoff-Tasmota 5.13.1 and a Sonoff POW R2:

![image](https://user-images.githubusercontent.com/517837/40584634-3b534d28-619c-11e8-96e8-ee2ce6f85ea1.png)

```
10:41:37 MQT: sonoff/stat/washing-machine/RESULT = {"POWER":"ON"}
10:41:37 MQT: sonoff/stat/washing-machine/POWER = ON
10:44:47 MQT: sonoff/tele/washing-machine/SENSOR = {"Time":"2018-05-27T10:44:47","ENERGY":{"Total":4.440,"Yesterday":0.000,"Today":0.000,"Period":0,"Power":0,"Factor":0.00,"Voltage":0,"Current":0.000}}
10:49:48 MQT: sonoff/tele/washing-machine/SENSOR = {"Time":"2018-05-27T10:49:48","ENERGY":{"Total":4.440,"Yesterday":0.000,"Today":0.000,"Period":0,"Power":0,"Factor":0.00,"Voltage":0,"Current":0.000}}
```

This is with the washing machine running and using a few amps. The line voltage is definitely above zero. What's weird is sometimes it just starts working on its own (and recording the real values), sometimes it works from the start when I MQTT the device ON, other times it just records all zeros all the time.

**Comment by arendst** [comment]
If it's a R2 enable more weblogging (weblog 4) for a few seconds and check if the serial received data doesn't have a checksum error.

**Comment by mcoms** [comment]
```
11:09:43 WIF: Checking connection...
11:09:43 WIF: Connected
11:09:43 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 86 86 F1 F3 EF 20 55
11:09:43 CSE: Checksum failure
11:09:43 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 81 55 F1 F3 F0 EB 55
11:09:43 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 81 55 F1 F3 F1 EC 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 81 55 F1 F3 F3 EE 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 81 55 F1 F3 F4 EF 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 81 55 F1 F3 F4 EF 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 81 55 F1 F3 F5 F0 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 78 04 F1 F3 F6 97 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 78 04 F1 F3 F8 99 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 78 04 F1 F3 F9 9A 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 78 04 F1 F3 FA 9B 55
11:09:44 CSE: Checksum failure
11:09:44 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 78 04 F1 F3 FB 9C 55
11:09:44 CSE: Checksum failure
11:09:45 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 71 6E F1 F3 FC 00 55
11:09:45 CSE: Checksum failure
11:09:45 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 71 6E F1 F3 FD 01 55
11:09:45 CSE: Checksum failure
11:09:45 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 2F C2 4E 91 48 01 71 6E F1 F3 FF 03 55
11:09:45 CSE: Checksum failure
11:09:45 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 27 C3 4E 91 48 01 71 6E F1 F4 00 FE 55
11:09:45 CSE: Checksum failure
11:09:45 SER: Received 5A 02 CC 68 00 03 04 00 3D AE 00 27 C3 4E 91 48 01 71 6E F1 F4 00 FE 55
```

Oh, yup, plenty of checksum failures! What does that mean?

**Comment by mcoms** [comment]
Thanks! As it happens it's just started working on its own again:

```
11:24:15 WIF: Checking connection...
11:24:15 WIF: Connected
11:24:15 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 05 72 90 4E 91 48 1B AE 36 61 22 50 29
11:24:15 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 04 E3 BC 4E 91 48 1D 47 9B 61 22 50 C5
11:24:15 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 04 E3 BC 4E 91 48 1E E0 01 61 22 50 C5
11:24:15 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 04 E3 BC 4E 91 48 20 7A 65 61 22 50 C5
11:24:15 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 04 E3 BC 4E 91 48 22 13 CA 61 22 50 C5
11:24:15 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 04 E3 BC 4E 91 48 23 AD 2F 61 22 50 C5
11:24:15 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 04 E3 BC 4E 91 48 25 46 94 61 22 50 C5
11:24:16 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 04 E3 BC 4E 91 48 26 DF F9 61 22 50 C4
11:24:16 SER: Received 55 5A 02 CC 68 00 03 05 00 3D AE 04 E3 BC 4E 91 48 28 79 5E 61 22 50 C5
11:24:16 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 2A 12 C3 61 22 50 C7
11:24:16 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 2B AC 28 61 22 50 C7
11:24:16 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 2D 45 8D 61 22 50 C7
11:24:16 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 2E DD F3 61 22 50 C6
11:24:16 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 30 77 58 61 22 50 C7
11:24:16 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 32 11 BC 61 22 50 C7
11:24:16 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 32 11 BC 61 22 50 C7
11:24:16 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 32 11 BC 61 22 50 C7
11:24:17 SER: Received 55 5A 02 CC 68 00 03 07 00 3D AE 04 E3 BC 4E 91 48 32 11 BC 61 22 50 C7
```

I see the `55` has moved too... Not sure what might cause an extra byte on the serial port/it to be shifted... Maybe a noisy washing machine? 😁

Thanks for you help!

**Comment by arendst** [comment]
Currently testing this code replacing the lines around 374 in file xdrv_03_energy.ino
```
    if ((0x5A == serial_in_byte) && (serial_in_byte_counter)) {  // 0x5A - Packet header 2
      if (serial_in_byte_counter > 1) {       // Sync buffer with data (issue #1907)
        serial_in_buffer[0] = serial_in_buffer[--serial_in_byte_counter];
        serial_in_byte_counter = 1;
        AddLog_P(LOG_LEVEL_DEBUG, PSTR("CSE: Fixed out-of-sync"));
      }
      cse_receive_flag = 1;
    } else {
      serial_in_byte_counter = 0;
    }
    serial_in_buffer[serial_in_byte_counter++] = serial_in_byte;
```
Might take some time before the out-of-sync occurs...

**Comment by digiblur** [comment]
Just happened to see this with some S31's I flashed yesterday, noticed the commit and did a test.  I'm still seeing the checksum errors.  I checked in platform IO and I see the above code in the energy.ino file with the 1907 reference.  Energy monitoring seems to be working fine though from what I can tell.

23:35:02 SER: Received 55 5A 02 D8 20 00 05 DB 00 3E E9 01 A4 E6 50 85 48 05 7E 20 71 1E 40 1B
23:35:02 SER: Received 55 5A 02 D8 20 00 05 DB 00 3E E9 01 A4 E6 50 85 48 05 8D 46 71 1E 40 50
23:35:02 SER: Received 55 5A 02 D8 20 00 05 DB 00 3E E9 00 DD D2 50 85 48 05 71 1E 41 75 55 5A
23:35:02 CSE: Checksum failure
23:35:02 SER: Received 55 5A 02 D8 20 00 05 DB 00 3E E9 00 DD D2 50 85 48 05 8D 46 71 1E 42 76
23:35:02 SER: Received 55 5A 02 D8 20 00 05 DB 00 3E E9 00 DD D2 50 85 48 05 E5 BE 71 1E 42 46
23:35:02 SER: Received 55 5A 02 D8 20 00 05 DB 00 3E E9 00 DD D2 50 85 48 05 E5 BE 71 1E 42 46
23:35:02 SER: Received 55 5A 02 D8 20 00 05 DB 00 3E E9 00 DD D2 50 85 48 05 E5 BE 71 1E 43 47
23:35:02 SER: Received 55 5A 02 D8 20 00 05 DB 55 5A 02 D8 20 00 05 DD 00 3E E9 00 DD D2 50 85
23:35:02 CSE: Checksum failure
23:35:03 SER: Received 55 5A 02 D8 20 00 05 DD 00 3E E9 00 DD D2 50 85 48 05 E5 BE 71 1E 44 4A
23:35:03 SER: Received 55 5A 02 D8 20 00 05 DD 00 3E E9 00 DD D2 50 85 48 06 06 4F 71 1E 44 FD
23:35:03 SER: Received 55 5A 02 D8 20 00 05 DD 00 3E E9 00 DD D2 50 85 48 06 06 4F 71 1E 44 FD
23:35:03 SER: Received 55 5A 02 D8 20 00 05 DD 00 3E E9 00 DD D2 50 85 48 06 06 4F 71 1E 45 FE
23:35:03 SER: Received 55 5A 02 D8 20 00 05 DD 00 3E E9 00 DD D2 50 85 48 06 06 4F 71 1E 45 FE

23:40:52 MQT: tele/SNF-Washer/SENSOR = {"Time":"2018-05-27T23:40:52","ENERGY":{"Total":1.736,"Yesterday":0.207,"Today":1.529,"Period":0.0,"Power":0.0,"Factor":0.00,"Voltage":123.6,"Current":0.000}} 

23:42:02 MQT: tele/SNF-Dryer/SENSOR = {"Time":"2018-05-27T23:42:02","ENERGY":{"Total":2.699,"Yesterday":0.191,"Today":2.508,"Power":14.8,"Factor":1.00,"Voltage":124.7,"Current":0.106}}

**Comment by arendst** [comment]
The Checksum errors as seen above are expected as you can see that the complete message of 23 bytes was not received. In fact you see two messages intertwined...

The main thing is that after the checksum error it syncs correctly and is able to provide some valid data. The patch provides for syncing.

Do you happen to have serial logging enabled? This might interfere with the serial data coming from the energy monitoring chip. If so execute command ``seriallog 0`` to stop the serial interface for user IO.

**Comment by digiblur** [comment]
I have seriallog 0 already set as that was my first thought.  Sounds like my error is much different than the others and I'm using getting a checksum every once in a while which is ignored by the system.  I just thought to report it here and I'm glad it isn't an issue.  

Yes, it is providing data and working pretty well.  I've already started using it for various automations based on the wattage each device is pulling to determine their state.  Easy way to do it without directly connecting some GPIO pins to the washer and dryer....aka don't ruin the wife's equipment!  

Hats off to you and the contributors with this project.  You've all done an amazing job of harnessing so much out of the little ESP8266.  Amazing.  Thanks for all that you do.
