### ISSUE TITLE
Device Discovery

### ISSUE THREAD

**Issue by Schnittcher** [arendst/Sonoff-Tasmota#1913]
Is there a way to find all Tasmota devices on the network and get the Topic?

**Comment by ascillato** [comment]
Nice Idea, I ask for a feature like that for SonWEB

**Comment by reloxx13** [comment]
German SH Script can be found here: http://forum.creationx.de/forum/index.php?thread/503-soncheck2-tasmota-ger%C3%A4te-ohne-webserver-finden-und-konfigurieren/

Todo for SonWEB :p

**Comment by emontnemery** [comment]
You can also easily find all devices by enabling MQTT discovery:
Either setoption19 1, or set `#define HOME_ASSISTANT_DISCOVERY_ENABLE 1` in `user_config_override.h`
You will now get a list of all tasmota devices by subscribing to MQTT topic `homeassistant/#`

**Comment by ascillato** [comment]
Device Discovery is now available on SonWEB. :+1:
