### ISSUE TITLE
 #error "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increase it to at least 427"

### ISSUE THREAD

**Issue by Slip7000** [arendst/Sonoff-Tasmota#192]
Morning All,

Please assist I'm trying to load the latest firmware onto a Sonoff via Arduino and getting this error:

 #error "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increase it to at least 427"

Thank you 
@Slip7000

**Comment by davidelang** [comment]
The error message is straightforward, you need to edit the file PubSubClient.h 
and change the value of MQTT_MAX_PACKET_SIZE to be at least 427.

Have you tried to do this?

**Comment by Slip7000** [comment]
Where can I find the this PubSubClient.h file ?

**Comment by Slip7000** [comment]
This is the Complete error:

Arduino: 1.6.12 (Mac OS X), Board: "Generic ESP8266 Module, 80 MHz, 40MHz, DIO, 115200, 1M (64K SPIFFS), ck, Disabled, None"

sonoff:148: error: #error "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increase it to at least 427"
   #error "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increase it to at least 427"
    ^
/Users/SlipPro/Box Sync/Sonoff/Sonoff-Tasmota-master/sonoff/sonoff.ino:155:75: fatal error: ArduinoJson.h: No such file or directory
 #include <ArduinoJson.h>                    // WemoHue, IRremote, Domoticz
                                                                           ^
compilation terminated.
exit status 1
#error "MQTT_MAX_PACKET_SIZE is too small in libraries/PubSubClient/src/PubSubClient.h, increase it to at least 427"

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by davidelang** [comment]
as the error message says, you find it in libraries/PubSubClient/src

This is where you installed the pubsub library as you were setting things up.

**Comment by davidelang** [comment]
This is showing two error messages, first you set the variable larger, second 
you need to install the arduinoJson library.

**Comment by Slip7000** [comment]
ok I'm still having a problem, found the file and it was already at 512 like below

#define MQTT_MAX_PACKET_SIZE 512

**Comment by khcnz** [comment]
I had this problem as well - are you on windows and using Arduino IDE? I found the same issue but Arduino IDE was using a copy in Documents/Arduino/Libraries/ and not Documents/Arduino/Sonoff-Tasmota/Libraries/

I ended up creating a junction from Documents/Arduino/Libraries/ to Documents/Arduino/Libraries/

**Comment by Slip7000** [comment]
Thank you, I'll try tonight. I'm using Mac and did change the root Libraries in the options of Arduino but still getting the error. I also reinstalled the app completely, but will try on windows tonight. 

Will let you know...

**Comment by davidelang** [comment]
IF you changed it and are still getting the error, then there is another copy of 
the library around somewhere on your system and the one you changed is not what 
the system is actually using.

On mac, you can do

find / -name PubSubClient.h

and have it report back all the places the library exists.

**Comment by Slip7000** [comment]
Thank you, got it working. I tried Atom and open the Sonoff file there changed the config and uploaded successful.

Thank you for everybody help
