### ISSUE TITLE
Hue Emulation as a "Hue client" (without bridge)

### ISSUE THREAD

**Issue by JoeWiseman** [arendst/Sonoff-Tasmota#1924]
Would it be possible to emulate a "pure Hue client" (without the bridge/gateway) emulation for the Sonoff-devices, so that they can be connected and controlled by one Hue bridge?

I hope that this can be done wihout much effort .... 

Regards
Joe

**Comment by Frogmore42** [comment]
The Hue client is not Wi-Fi as far as I know.  So I don't believe it is possible.  But, I think the Hue app might be able to handle more than one bridge.  I know the Smart Things app can.

**Comment by Frogmore42** [comment]
https://www.engineersgarage.com/contribution/zigbee-vs-wi-fi

**Comment by JoeWiseman** [comment]
Hi @Frogmore42 
thanks a lot for explaining the differences in communicating to an bridge and client.
So that seems to be an dead end for me.
Thanks again!
Joe
