### ISSUE TITLE
Sonoff T1 EU 2ch partial/failed flash upload

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#1936]
Hello,

I have a Sonoff T1 EU 2ch and tried to flash it,
I followed the instructions but on 75% of the upload it failed, possibly it lost contact.
Now I have a partially uploaded ESP

How can I reprogram it?
The instructions do not work any more.

Thank you.

**Comment by reloxx13** [comment]
unplug and replug, dont forget boot in flash mode (gpio0 to gnd).

flashing by usb/Serial is independent of firmware.

if you used 5V while flashing your chip could be broken now.

**Comment by ageorgios** [comment]
where is gpio0 on a Sonoff T1 EU?

**Comment by reloxx13** [comment]
wiki dude

**Comment by ageorgios** [comment]
Thanks for the info!
Is GPIO02 that the wiki describes the GPIO0?
