### ISSUE TITLE
disable hold button reset behaviour

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#1945]
When holding a button on the Sonoff T1 (EU) it beeps and restarts around on 3-4 seconds.

This is my configuration:
backlog setoption13 1; setoption0 0; setoption32 100;

**Comment by ascillato** [comment]
Hi

What is the question? 

As in the wiki, it is a feature of this firmware

Please, see https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage

**Comment by ageorgios** [comment]
wow you are right.

Is there a way to disable this?

**Comment by ascillato** [comment]
Yes.
Read the wiki
;)

**Comment by ageorgios** [comment]
please help is a little bit long

**Comment by ascillato** [comment]
There are a lot of options for the behaviour of the button. As I don't know what you want just go to https://github.com/arendst/Sonoff-Tasmota/wiki/Commands and check for the one that it is better for you.

**Comment by ageorgios** [comment]
I think there is no way of disabling the reset behaviour

**Comment by emontnemery** [comment]
Use command setoption13 1

**Comment by SergiusTheBest** [comment]
@ageorgios Did you manage to disable those beeps?
