### ISSUE TITLE
backlog pulsetime

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#1946]
version 5.12.0

 `backlog pulsetime1 10; power1 on; pulsetime1 30`
expected:
Turns off at 1sec and the next time someone powers on the switch turns off at 3sec
now:
does not turn off at 1sec

`backlog setoption13 1; setoption14 1; setoption0 0; setoption32 100; PowerOnState 0; timezone 2; setoption3 0; setoption1 1; ledstate 0;`
expected:
do everything without restart
now:
does a restart

**Comment by reloxx13** [comment]
1 sec is pulsetime 101 

what is your sleep config?

which firmware version?
