### ISSUE TITLE
more colour schemes like McLighting project

### ISSUE THREAD

**Issue by roesl** [arendst/Sonoff-Tasmota#1952]
ist it possible to add more schemes to the firmware ?

**Comment by roesl** [comment]
see https://github.com/kitesurfer1404/WS2812FX

**Comment by roesl** [comment]
no idea ??

**Comment by roesl** [comment]
Why doesnt respond anybody to my issue ??

**Comment by ascillato** [comment]
Cool! 53 effects! 

I add the enhancement label to be taken into account.

Thanks! :+1:

**Comment by ascillato** [comment]
Similar issues added for reference:

#285
#2906

**Comment by ascillato** [comment]
Continuation of this issue at #3480
