### ISSUE TITLE
Flash 5.12.0 on Sonoff Basic R2 doesn't work

### ISSUE THREAD

**Issue by rhpape** [arendst/Sonoff-Tasmota#1973]
I just received a new batch of Sonoff Basic's, which came with a suffix 'R2'. On the print it status Sonoff Basic R2 v1.0, dated 2017-10-11. I tried to flash to flash a number of them a couple of times with version 5.12.0, which completes without error (PlatformIO), but after restart they don't seem to connect to Wifi (using SSID1 set in user_config.h). I took the 5.12.0 version of userr_config.h, not a copy of one of the older versions. Also using the 4 short press on the button doesn't bring up an AP to connect to. 

Flashing them with 5.10.0 works fine, after which an OTA upgrade with precompiled 5.12.0 also works fine.

**Comment by Jason2866** [comment]
Use 5.12.0b latest development version 5.12 master doesnt work stable in my setup too

**Comment by sumasage** [comment]
I'm getting the same problem.  I got the same sonoff batch as rhpape.  The Sonoff would connect to the wifi and i have a ping test that ping the sonoff constantly.  The sonoff would connect for a few mins after restart but then it gradually lose connection, ping test time out.  I did some extensive test to see if it is my wifi router or the sonoff.  It came down that it the sonoff is fine after flashing tasmota with wifi info (no drop in ping test for about 5 mins) but as soon as i config it with MQTT info it start to lose connection.  

Will try what you guys suggested.

**Comment by xMadelain** [comment]
HI,
Got the same but I can't even go in flash mode. How to you go to ?
Regards,

**Comment by sumasage** [comment]
I got mine to work via instructions from the original poster:

"Flashing them with 5.10.0 works fine, after which an OTA upgrade with precompiled 5.12.0 also works fine"

To get into flash mode press and hold the button before you apply power. There doesn't seem to be any light indication that it is in flash mode but it is in flash mode.

**Comment by Jason2866** [comment]
Dont use IwIP 1.4. It is instable. Use older version

**Comment by xMadelain** [comment]
@rhpape ,
Hi could you confirm that u manage to flash sOnOff Basic R2 V1.0
I can't . Seems I can't enter in flash mode (external alimentation ..... )
Could you describe your full process
Regards

**Comment by Jason2866** [comment]
@xMadelain I have flashed successfully 4 sonoff basic wifh date 2017-10-11.
As described in the wiki. https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Basic#serial-connection
Used latest developer firmware

**Comment by xMadelain** [comment]
Hi @Jason2866 
So I've already soldered the 4 pins head
"_For flashing the sonoff basic V1.1, please hold the button while connecting the Plus Pole. The LED remains off until the flashing process is done and the board is rebooted." => doesn't work

Now do you mean that I have to solder a wire from ESP 8266 pin to where (no show on image) ? (One image is missing)
And how do you go to flash mode then ?
Sorry to insist on the details but I try to flash it for more than a week now !
Regards

**Comment by Jason2866** [comment]
Hi,
what usb to serial adapter do you have? It has to be a 3.3 Volt type. Is the driver correct installed?
Furthermore some serial adapter do not deliver enough current  to power the esp.
Next chance for failure is the flaher program. Some people had problems to flash with Atom.io or 
with the Arduino Ide. In this case the flasher tool esptool is always a good choice. 
All know real! Sonoff Basic are able to flash as described in the wiki.
Failure in flash is always! one of the reasons above.

**Comment by Jason2866** [comment]
The problems described in start of topic wasnt a flash problem.
It was a problem in the software. This problem is fixed in actual firmware release.

**Comment by xMadelain** [comment]
Hi,
I use an external YwRobot  (https://www.amazon.fr/gp/product/B00QV7NXCS/ref=oh_aui_detailpage_o09_s00?ie=UTF8&psc=1)
=> It delivers 3.3V and 1A to sOnOff directly
My serial adpater is ) (https://www.amazon.fr/gp/product/B00AFRXKFU/ref=oh_aui_search_detailpage?ie=UTF8&psc=1)
=> TX and RX are 3.3 V. TX and RX go to sOnOff and GND to GND of external power
For flashing I tried
On W10 : flash.cmd, EspEasy Dowload tool
On Pi : esptool.py
I try this on 3 sOnOff ( all R2 V1.0 as amazon.fr only delivers this one currently)
==>All said that they can't connect

**Comment by Jason2866** [comment]
Your serial adapter is 5 Volt!! as far as i can see on the pictures on Amazon.
Does you have exact these one? Or do you have one with a little switch to switch between 3.3V and 5V?
Maybe if you are un lucky, if you used 5V, the sonoff is dead. You have to use everywhere 3.3V!

**Comment by sumasage** [comment]
Here is the video tutorial that I used to flash tasmota https://youtu.be/c2IUIUnxjUY

Skip to minute 9

**Comment by xMadelain** [comment]
Hi,
I use external adapter to power sOnOff yWrobot
From my serial adapter Voltage on Tx and Rx are 3.3v
So seems to be good ?

sOnOff still working with EWeLink so it should not be dead ?
Regards

**Comment by Jason2866** [comment]
On your USB serial adapter have to written or printed on the PCB that the logical levels are 3.3V compatible.
If not and only 5V is printed and no 3.3V is seen, i am thinking your adapter is the problem...
I had never the need to power the sonoffs via extern power supply. Just connect the 4 wires (tx rx 3.3v and gnd) and push button and plugin. Flash always worked this way. After that disconnect all wires, assemble the unit and plugin....

**Comment by xMadelain** [comment]
Hi @Jason2866 
I don't use the 5V output, only TX,RX, GND and I have soldered a pin for the 3.3V.
But again I don't use serial adapter to power sOnOff (external 3.3 V)
Voltage on TX and RX are 3.3 v => what about your voltage on those pins ?
I will try another serial adapter with a 3/5V selector.

**Comment by Jason2866** [comment]
You can try it with your adapter without the external power supply. Use the 3.3V pin.
What was your reason to use a external power supply? Normally there is no need for.

**Comment by xMadelain** [comment]
I’ve of course try like that
But always same issue : can’t connect
I’ve read some posts using external power that’s why I also tried....

**Comment by mknuepfer** [comment]
I successfully flashed 5.12.0 to my Sonoff Basic R2 (2017-10-11). The trick was to use the Generic ESP8285 Module. I think the R2 Version is based on the 8285 chipset.

These are the settings i used to flash the device:
 
![image](https://user-images.githubusercontent.com/2243917/37917750-89553e26-311f-11e8-9ef8-97376d185f2b.png)

**Comment by xMadelain** [comment]
Hi,
With same Serial adapter, program (espeasy dowload TOOL) I manage to flash sOnOff TH16 !
@mknuepfer, 
you flash yours with which tool, i don't recognize this screen  (Arduino IDE ?) ?
you enter in flash mode as usually (hold button and insert serial adapter ) ?
Thanks

**Comment by mknuepfer** [comment]
Yes, it's the Arduino IDE. I enter flash mode by holding the button pressed while connecting my FTDI to the USB of my Laptop.

**Comment by Jason2866** [comment]
There are many fake FTDI adapter around. The often fail...
Try one with a ch340 or a ch341 chip

**Comment by Jason2866** [comment]
If you plugin the usb adapter a COM Port is assigned in Windows?
If yes which Nr?

**Comment by xMadelain** [comment]
COM5

I have already flash sOnOff TH16 , oldest sOnOff basic with this config
Here I can’t flash sOnOff basic R2 v1.0

**Comment by Jason2866** [comment]
Could you upload a photo of your sonoff. I am in doubt if flashing doesnt work it is original

**Comment by xMadelain** [comment]
Thanks
Already done
I may have an issue with my config (it was ok with TH16)
What is your flashing config (hardware &software)
How do you enter flash mode ?


Xavier MADELAIN

**Comment by xMadelain** [comment]
Xavier MADELAIN

**Comment by Jason2866** [comment]
Win10 64 bit pro latest patches  Atom.io  I can use the button upload in Atom.io
I just press the button on the sonoff and then i plugin the usb adapter.
Start Upload in Atom.io if upload start (after the compile process) i release the button
So nothing special

**Comment by xMadelain** [comment]
Do you hold down the button until upload start ?

**Comment by Jason2866** [comment]
Maybe your driver installation for the serial adapter in windows is in some way buggy.
But on the other side flashing via Pi you said fails too.
Realy strange?!

**Comment by rhpape** [comment]
@Jason2866 My guess was also that it was a firmware issue, as the flashing itself completed successfully. I've no been able to flash with one of the newer versions yet. Did you really confirm this already (then I can close this issue)?
@xMadelain I use the exact instructions as on the Wiki (using PlatformIO). Except that I manually hold the pinheader on the sonoff pcb (saves me soldering ;-) ) and then plug in the USB.

**Comment by Jason2866** [comment]
@rhpape 
Do you can upload a photo of your sonoff? I want to compare it with that i have.
Maybe there a fakes around

**Comment by rhpape** [comment]
![c8449e3f-1d27-45ce-92bc-8fa8dfeae191](https://user-images.githubusercontent.com/32158920/38582593-914ac9a0-3d10-11e8-95c0-c57186b24b22.jpeg)
![40ad56ec-785b-4347-81c1-8d8ede7de955](https://user-images.githubusercontent.com/32158920/38582594-916b8320-3d10-11e8-88ed-9a0fa0b68955.jpeg)

Not the best ever, does this work?

**Comment by xMadelain** [comment]
Mine are the same
@RobertP
So you never also manage to flash a R2 ? 
What errors do u have ? ( com failure or ?)

Xavier

**Comment by rhpape** [comment]
@xMadelain the flashing itself worked fine (no errors). The device just doesn't come up after reboot.

**Comment by Jason2866** [comment]
I have 2 off this R2 sonoff basic. The work as every other of my sonoff basics

**Comment by xMadelain** [comment]
Hi
New test with my last sOnOff Basic T2 in stock.
IT WORKS......
Same Adapter, Same program (esptool.py on RasPi, No external power)

Note : Only changes :
-I've soldered only 4 pins....
-No previous tests with eWeLink => Will try to reset others...

**Comment by wfdudley** [comment]
I've got a dozen of the Rev 1 boards, and they work great with 5.12.0e.  I bought two more units and got R2's with the 2017-10-11 date code (silk screen).  I've tried them with 5.10.0, 5.12.0e, and 5.14.0b.  One unit seems to "sort-of" work with 5.10, in that it reliably connects to wi-fi, and then it struggles to maintain a connection to my mosquitto server (which is across the country).  That unit could not connect to wi-fi using either 5.12 or 5.14 -- it kept timing out before even getting to authentication.  The other unit cannot connect to wi-fi using any of 5.10, 5.12, or 5.14.  The R2 units definately have a problem with Tasmota.  I can upload serial port output if that's useful, or I can ship these units to the developer.  I'm located in New Jersey, USA

**Comment by Jason2866** [comment]
No, the dont have in general a problem. Every sonoff i have works. I have R2 too
Which arduino version do you use? Try it with version 1.5.0 (2.3.0)
Erase the ESP completly. Flash it with DOUT Option as described in Wiki
and you will have a fully working device.

**Comment by Jason2866** [comment]
Hi wfdudley,
means use ESP/Arduino library 2.3.0
See wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite
I suggest to use Atom.io or Visual Studio Code. Much easier to use for complexer projects then Arduino IDE.

**Comment by wfdudley** [comment]
Jason,
I'm sorry, but I don't see any mention of "ESP/Arduino library 2.3.0" on
the linked page.

Can you be more specific?  An exact link?  I searched for the string "ESP"
and found
exactly 4 ESP references, none of which seemed to be to a library.

I don't know anything about Atom.io, but Visual Studio sounds like a
Windows thing,
and don't have Windows on any computer, nor would I use it if I did.

Thanks,
Bill Dudley


This email is free of malware because I run Linux.

**Comment by Jason2866** [comment]
Hello Bill,
Platformio is a multi platform ide. Take a look
https://platformio.org/platformio-ide
Try it and you dont have to search for libraries and other stuff...
Theo has setup everything for that. Just install as in wiki described and everything works hassle free.
Standard config from Theo uses Esp arduino library 2.3.0

**Comment by wfdudley** [comment]
Jason,

Thanks, that's a bit of a help.  So, the Arduino IDE doesn't work with
Sonoff Basic R2.
I should think that should be mentioned somewhere on the wiki.

I've been clicking around on platformio.org, and now it asks me to choose
between "Atom" and "VSCode".  I clicked on the "Compare" icon and
am not any more knowledgable afterwards.  Is clang (C compiler) included
in the Atom package, or is that something I have to chase down?

I don't really know: which do I choose, Atom or VSCode ?

Thanks,
Bill Dudley


This email is free of malware because I run Linux.

**Comment by wfdudley** [comment]
I'm going to install the Atom version and see how far I get.

Bill Dudley


This email is free of malware because I run Linux.

**Comment by wfdudley** [comment]
This is turning into a train-wreck.

This page:

https://github.com/arendst/Sonoff-Tasmota/wiki/PlatformIO

Says:

"Copy all files from the Tasmota release Source code into your platformIO
base folder."

What is the Source code -- the directory called "sonoff" under
"Sonoff-Tasmota-development" ?

What is my "platformIO base folder" ?  ~/.platformio ?  My "home"
direcotory (~) ?

I didn't know, so I told Platformio to open "Sonoff-Tasmota-development".

I made my changes to user_config.h.  Why is the actual editor window such a
small part of the screen?
Why is half the screen covered with the "Welcome" screen?  I managed to
kill that, and move the
divider over so the editor filled the screen, but why is that necessary?

Then I clicked on the "Build" icon.

I get the error message "Cannot find active Platformio project".  What does
that mean, and
how do I fix it.

Thanks,
Bill Dudley





















This email is free of malware because I run Linux.

**Comment by Jason2866** [comment]
Hello Bill,
here is a tutorial https://github.com/arendst/Sonoff-Tasmota/wiki/Beginner-Guide---Create-your-own-Firmware-Build

**Comment by Jason2866** [comment]
Hi again,
if you want to use Arduino IDE. Here is a tutorial
https://github.com/arendst/Sonoff-Tasmota/wiki/How-to-Flash-the-RF-Bridge
It is for RF Bridge but setup is the same for every device!

**Comment by Jason2866** [comment]
Do not add a new project folder!
You have to open the project folder as in tutorial described

**Comment by wfdudley** [comment]
I did "open project folder", I did not do "new project folder" and it's
still horribly broken.

Bill Dudley

This email is free of malware because I run Linux.

**Comment by wfdudley** [comment]
"No configuration to build this project exists".

Bill Dudley


This email is free of malware because I run Linux.

**Comment by wfdudley** [comment]
I've deleted a lot of my useless comments about platformio, which was a distraction and wasted a great deal of time.  There is still not a solution for the "Basic R2 doesn't work" problem as of the time I write this.

**Comment by ioudeveldhuis** [comment]
@wfdudley Please see if this ( https://github.com/arendst/Sonoff-Tasmota/issues/2868#issuecomment-399142851 ) solution works for you too, it worked for me (sonoff basic R2, V1.0 2017-10-11 1803 on silkscreen).

**Comment by wfdudley** [comment]
I found (and wrote in a different thread) that my R2's work if I do the "reset the device" using the Sonoff button.  This causes the code to refresh the wifi params from the code in flash (as opposed to using the values in EEPROM, I guess) and then the devices connect to wifi OK.  I haven't needed to use different libraries, old versions, etc.  I don't know why the R2's work differently than the R1's on a fresh install of Tasmota, but they do.

**Comment by ascillato2** [comment]
Hi,

Closing this issue as there is a solution to it, erasing all flash and then flashing last Tasmota version. Please ask to reopen if needed. Thanks.
