### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by kskenyon** [arendst/Sonoff-Tasmota#1975]
lib/Mutichannel_Gas_Sensor/examples/UpdateFrimware/UpdateFrimware.ino

Multichannel
Firmware

**Comment by reloxx13** [comment]
heya,

you should post it here: https://github.com/Seeed-Studio/Mutichannel_Gas_Sensor

its just a library which tasmota uses

**Comment by kskenyon** [comment]
Thanks, I let him know.

K

**Comment by jhlweb** [comment]
@kskenyon please close this issue
