### ISSUE TITLE
ESP.getCoreVersion() returns 00000000

### ISSUE THREAD

**Issue by camdiep2** [arendst/Sonoff-Tasmota#1981]
Hi all,

I upgrade ESP8266 Board from version 2.3 to 2.4.0. When I check ESP.getCoreVersion(), my fw displays 00000000. This is normal or my fw has issue.

ESP.getSdkVersion() returns 2.1.0(deb1901)

**Comment by camdiep2** [comment]
my Arduino IDE has issue , just reinstall it and the issue is resolved. Thanks.

**Comment by sej7278** [comment]
i'm seeing the same thing:

```
SDK version:  2.2.1(cfd48f3)
Core version:  ffffffff
```

**Comment by laercionit** [comment]
Same problem...

**Comment by sreekants** [comment]
Is this what you are looking for?
------
  Serial.println( ESP.getCoreVersion() );
  Serial.println( ESP.getSdkVersion() );
-------
2_4_0
2.1.0(deb1901)

**Comment by sreekants** [comment]
Sorry.. I thought markups did not work here..  :-)
