### ISSUE TITLE
temres command

### ISSUE THREAD

**Issue by andyd999** [arendst/Sonoff-Tasmota#1994]
Hi

I`m new to tasmota and just flashed my sonoff th16 to try get decimals on the temp readout.  I see i can use tempres to achieve.  Question is how do i achieve this? do i need to edit one of the files prior to upload? or can it be done afterwards? totally new and alien to me so help appreciated

**Comment by reloxx13** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by andyd999** [comment]
Thanks I found that bit.  But how do i actally change/set the option? for example I want tempearture displayed to 2 decimal places

**Comment by SodoffBaldrick** [comment]
Log on to the Sonoff
Click "Console"
Type "TempRes 2" (without the quotes)
Press Enter.

Done :)

**Comment by andyd999** [comment]
Thanks Sodoffbaldrick.  And it will it keep the setting permanently? or just until power on/off?

**Comment by SodoffBaldrick** [comment]
Permanently. Including flashing new versions of tasmota OTA :-)

**Comment by reloxx13** [comment]
if savedata 1 (Default 1) is set.
