### ISSUE TITLE
No DHT22 sensor selectable

### ISSUE THREAD

**Issue by dYna77** [arendst/Sonoff-Tasmota#2004]
Hi,

i am on 5.12.0c and use the "Generic Module" on a bare ESP8266.
On GPIO0 i have a DHT22 sensor, but i cant select it in the configuration menu.
Is this not available with the module i use?

EDIT: I compiled with this enabled: env_default = sonoff
Thanks!

**Comment by curzon01** [comment]
Use "03 SI7021", that's the DHT22 sensor too.

**Comment by dYna77** [comment]
Thank you.
I did not find a mention of this at https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-Configuration

**Comment by curzon01** [comment]
There is: see subsection [Single wire sensor](https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-Configuration#single-wire-sensor) - DHT22 (3), AM2302 (3), AM2321 (3), SI7021 (3) are all the same sensor (=3) type.

**Hint**: Use also github _Search_ function
![2018-02-24 12-55-42](https://user-images.githubusercontent.com/6636844/36630160-27616d54-1962-11e8-9424-cc22f998248a.png)

**Comment by jhlweb** [comment]
@dYna77 if this is solved please close this issue

**Comment by jamman9000** [comment]
Issue is closed, but answer should be corrected to say he/we should use the AM2301 selection when using the DHT22, if you go look at the issue referenced with the quote, the longer explanation helps better clarify which should be used for what. Apparently, the AM2301 uses the same handler as DHT22 so they "consolidated" them into one selection. Then took the old DHT22 selection and changed it to the SI7021.
