### ISSUE TITLE
Timer issue / garage door option 

### ISSUE THREAD

**Issue by djtonyd** [arendst/Sonoff-Tasmota#2009]
hi all is there a way to set a timer on the sonoff just inside the software/web interface so when you press on  it turns the relay on for a split sec then off auto on the interface as im going to connect the load side to a contactor then use the NO to allow my garage to open as it needs a pulse function and i dont want constant 12v on it nor 240v on the sonoff coming out.

**Comment by Oxyandy** [comment]
search google sonoff pulsetime

**Comment by djtonyd** [comment]
i dont want to use the GPIO functions just the web on/off in order to make it pulse will this still work?

**Comment by Oxyandy** [comment]
pulsetime X will mean anytime relay is activated, will stay on for x
whichever way you turn it on

**Comment by djtonyd** [comment]
ok so i would type in the console pulsetime <0.1> ?

**Comment by Oxyandy** [comment]
Yeah maybe, I have never gone below 1 before.. so not sure about the point should be in wiki

**Comment by Oxyandy** [comment]
pulsetime 1
as console (web console window) will mean 1 second
right syntax

**Comment by djtonyd** [comment]
just entered it works like a charm :) happy days thanks heaps
