### ISSUE TITLE
unable to connect to sonoff touch switch

### ISSUE THREAD

**Issue by vpomax** [arendst/Sonoff-Tasmota#2015]
I flashed my first Sonoff Touch with Tasmota, all went ok, its IP is 192.168.1.80... but in the console of Tasmota I read the following errors:

00:00:00 Project sonoff Sonoff Touch Corr (Topic sonoff, Fallback sonoff-corr, GroupTopic sonoffs) Version 5.12.0
00:00:00 WIF: Connecting to AP1 TIM-90987215 in mode 11N as sonoff-2090...
00:00:03 WIF: Connected
00:00:03 DNS: Initialized
00:00:03 HTP: Web server active on sonoff-2090.local with IP address 192.168.1.80
00:00:03 UPP: Multicast (re)joined
00:00:04 UPP: Multicast (re)joined
00:00:06 MQT: Attempting connection...
12:11:46 MQT: Connect failed to 192.168.1.80:1883, rc -2. Retry in 10 sec
12:11:47 UPP: Multicast (re)joined
12:11:58 MQT: Attempting connection...
12:12:04 MQT: Connect failed to 192.168.1.80:1883, rc -2. Retry in 10 sec
12:12:05 UPP: Multicast (re)joined
12:12:16 MQT: Attempting connection...
12:12:22 MQT: Connect failed to 192.168.1.80:1883, rc -2. Retry in 10 sec
12:12:23 UPP: Multicast (re)joined

**Comment by Oxyandy** [comment]
ITSELF 00:00:03 HTP: Web server active on sonoff-2090.local with IP address **192.168.1.80**
MQT BROKER ON SAME IP ?

**Comment by chris-008** [comment]
your btoker ip should be 192.168.1.80 like you mentioned, not 192.168.1.2
All your topics have to be unique per device eg. sonoff1, sonoff 2,...
-->  state_topic: "stat/sonoff1/POWER" for your frst device,  state_topic: "stat/sonoff2/POWER" for your second device and so on

**Comment by chris-008** [comment]
topic names have to be unique
