### ISSUE TITLE
Sonoff 4CH Pro (R2) Supported?

### ISSUE THREAD

**Issue by FamJohansson** [arendst/Sonoff-Tasmota#2018]
Hi,
Thank you for a wonderful job you've done with Sonoff Tasmota.

I'm trying to flash my Sonoff 4CH Pro R2 with the firmware but I do not get it uploaded. A little bit uncertain of what I'm doing wrong. 

I have no trouble flashing the Sonoff 4CH Pro. (Current version 5.12.0c)

I'm unsure of the following:
-Supports sonoff Tasmota Sonoff 4CH Pro R2?
-How do I put Sonoff 4CH Pro R2 in flash mode?

**Comment by Jason2866** [comment]
Tried https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-4CH

**Comment by FamJohansson** [comment]
There are two versions of 4CH pro I have R2 version ..
see pictures
![fullsizeoutput_8a4a](https://user-images.githubusercontent.com/16057186/36645434-16e6e118-1a69-11e8-9867-e6b98c5fd83a.jpeg)
![fullsizeoutput_8a4f](https://user-images.githubusercontent.com/16057186/36645435-1705236c-1a69-11e8-9dd3-9f64dfdbc817.jpeg)

**Comment by nmaggioni** [comment]
On the R2 model the GPIO0 pad is broken out to a small pad to the right of the ESP package, as per [my other comment](https://github.com/arendst/Sonoff-Tasmota/issues/2021#issuecomment-371227748):

![GPIO0 pad](https://user-images.githubusercontent.com/3594528/37109801-58fb97a4-223b-11e8-969c-1131dcfa6ee1.jpg)

**Comment by FamJohansson** [comment]
@nmaggioni
Thanks this solved my question..

**Comment by nmaggioni** [comment]
@FamJohansson You're welcome, consider closing this issue if it's fixed.

**Comment by FamJohansson** [comment]
Hello again @nmaggioni 
Do yo have any clue how to flash this one?      
 
https://www.aliexpress.com/item/SONOFF-AC85-250V-4-Channel-Automation-Module-Jog-Inching-WIFI-Wireless-Smart-Switch-Relay-rf-receive/32835664788.html?spm=a2g0s.9042311.0.0.fbFZOL
![t5plp0ejt uvr52rb02u5w](https://user-images.githubusercontent.com/16057186/37123346-2f422f58-2264-11e8-81f9-9b1e44d040cb.jpg)

**Comment by sigalou** [comment]
For Flash, I did a tutorial on my site (in French). Good continuation.
http://sigalou-domotique.fr/index.php/17-sonoff-4ch-pro-r2

**Comment by FamJohansson** [comment]
@sigalou
Have you tested this one?

https://www.aliexpress.com/item/32835664788/32835664788.html

Can’t see how to flash it,

**Comment by Jason2866** [comment]
Looks interesting, but i am pretty sure it is not a genuine sonoff.
ITEAD had never used an extra power supply board (this looks like a cheap one)
and the integrate the ESP on the main PCB on actual board revisons.
Furthermore this board istnt listed on the website from ITEAD

**Comment by ascillato** [comment]
Hi @FamJohansson 

If your issue is solved, please close it. Thanks! :+1:

**Comment by KierkelsD** [comment]
@FamJohansson , could you tell us how you have resolved your problem?

Thanks

**Comment by Frigorio** [comment]
> Hello again @nmaggioni
> Do yo have any clue how to flash this one?
> 
> https://www.aliexpress.com/item/SONOFF-AC85-250V-4-Channel-Automation-Module-Jog-Inching-WIFI-Wireless-Smart-Switch-Relay-rf-receive/32835664788.html?spm=a2g0s.9042311.0.0.fbFZOL
> ![t5plp0ejt uvr52rb02u5w](https://user-images.githubusercontent.com/16057186/37123346-2f422f58-2264-11e8-81f9-9b1e44d040cb.jpg)

https://www.letscontrolit.com/wiki/index.php/Sonoff_DIY_4ch

**Comment by itajackass** [comment]
Hi i'm little bit OT but i've found some pic here... Is it possible to install an external antenna on R2 version? In normal version was a pad where we can solder an ipex connector. But in R2 i don't see anything. Can someone help me?
