### ISSUE TITLE
MQTT - No Authentication

### ISSUE THREAD

**Issue by pauly7300** [arendst/Sonoff-Tasmota#204]
Does the firmware support no authentication to MQTT server?

**Comment by davidelang** [comment]
yes. just don't set a password

**Comment by davidelang** [comment]
did you have another question or can this issue be closed now?

**Comment by pauly7300** [comment]
thanks @davidelang .  I was thrown off because the password field is populated with dots regardless of a password being set or not.  I realize memory is precious but it might be a nice addition to add a boolean checkbox for anonymous auth.  Thanks again.
