### ISSUE TITLE
Sonoff Touch, delay between toggle

### ISSUE THREAD

**Issue by azor1an** [arendst/Sonoff-Tasmota#2045]
Hi, I'm trying to configure a Sonoff Touch so it behaves like the following:
- toggle state immediate when I touch the button
- minimal wait time between accepting a new touch input 

I've done "SetOption13 1", which makes the relay toggle almost instant after I touch the button, however this only happens reliably if it has been been a few seconds from the last button toggle. If I touch the button too quickly after the last button press it most of the time ignores that touch.

Is there any other config option that I can set to minimize this delay between accepting button touches?
thanks.

**Comment by ionciubotaru** [comment]
Check your mqtt server, the strength of you wireless signal - a poor mqtt connection can cause those delays

**Comment by azor1an** [comment]
you are right @ionciubotaru. I moved the MQTT server closer to the switch and it now reacts very quickly.
