### ISSUE TITLE
Flashing Sonoff POW works, but not S20

### ISSUE THREAD

**Issue by Hekoweb** [arendst/Sonoff-Tasmota#2046]
Hi,

I tried to flash my Sonoff S20 without success, these messages came up:

Looking for upload port...
Auto-detected: COM5
Uploading .pioenvs\sonoff-DE\firmware.bin

warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
*** [upload] Error -1
 [ERROR] Took 35.02 seconds
 

Building went fine.
The COM-Port was correctly recognized as COM5. I pressed the button to start upload mode. 

I tried it with another new S20, same problem.

Than I tried it with the same firmware and the same adapter on a Sonoff POW --> And that worked!

Is there something different with the S20? Any ideas?

**Comment by curzon01** [comment]
interchange TX/RX lines

**Comment by Hekoweb** [comment]
I had two issues, a cold solder joint and ones incorrect TX/RX connections.
Now it works.
