### ISSUE TITLE
Can't find pinout for Sonoff basic switch version 2.0

### ISSUE THREAD

**Issue by cpiekacz** [arendst/Sonoff-Tasmota#2049]
I've got a new version 2.0 of the Sonoff basic switch and I can't find the pinout layout anywhere. Can someone help me with that?

![img_9135](https://user-images.githubusercontent.com/3659796/36812680-44dd71e8-1cd2-11e8-9a7c-fc06b1e8cbdb.jpg)

**Comment by reloxx13** [comment]
its a powstro and not a sonoff.

**Comment by reloxx13** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/PowStro

also blame the seller and try to get a refund if he sold it as sonoff, those are fake sonoff.

but they work, too. just give some more tin on the two 230v path (on the button of your image).

**Comment by cpiekacz** [comment]
Thanks a lot guys. I've contacted the seller and will try to get a refund.
