### ISSUE TITLE
WiFi in idle only with esp-open-rtos

### ISSUE THREAD

**Issue by surfskidude** [arendst/Sonoff-Tasmota#2050]
I have the esp-open-rtos working with a standard ESP8266, but I cannot get this to work on the Sonoff 4ch. I have the serial connected and my code prints out that it just sits in state STATION_IDLE

Ref: https://github.com/SuperHouse/esp-open-rtos/

**Comment by reloxx13** [comment]
so, ask at the rtos repo?!
