### ISSUE TITLE
Sonoff T1 2CH Modul Sonoff-Tasmota 5.12.0 Alex Hue Bridge Emulation

### ISSUE THREAD

**Issue by Fabian2009** [arendst/Sonoff-Tasmota#2052]
Hello,

I am using the following setup:
Sonoff T1 2CH Modul Sonoff-Tasmota 5.12.0 (German version) Alex Hue Bridge Emulation

I can turn on/off both lights connected using the domoticz app on my phone and also using Homebridge app + Siri.
While using Alexa app it shows me the current status of the lamp (on/off) but I cannot change it. When changing it with another app, I can see the live status changing. 
When using the Belkin WeMo emulation, everything works fine, but I can only use one of the connected lamps.

Does anybody have any idea how to fix this issues ?

**Comment by reloxx13** [comment]
workaround can be found here: https://github.com/esp8266/Arduino/issues/4235
