### ISSUE TITLE
Restfull URL to restart?

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#2055]
Hi,

is there an URL to initiate a restart? On the main page there is a button to do a restart, but in case of low memory this button is not visible. Therefore a restfull call would help. Authentication and admin web for sure must be ensured. There are some calls

**Comment by stefanbode** [comment]
Self found. With this configuration, you also avoid deleting parameters
http://192.168.178.25/sv?r=1

**Comment by curzon01** [comment]
So please close the issue if it is solved
