### ISSUE TITLE
Looking for Sonoff Tasmota beta testers for Yeti app

### ISSUE THREAD

**Issue by luisfpinto** [arendst/Sonoff-Tasmota#2056]
Hello! 

I've decided to implement Sonoff into [Yeti](https://getyeti.co), a mobile app (Android & iOS) to control smart home devices.  I've started adding control for switches and I hope I can add sensors soon. 
Before releasing the switch control to production I would like some of you to test the App to see if the sonoff tasmota implementation it's working or not. This would be really helpful

**EDIT: The newest version of the app has been released and controls Sonoff**. **See** 
[Controlling your Sonoff Tasmota with Yeti
](https://getyeti.co/posts/controlling-your-sonoff-tasmota-with-yeti)

Thank you so much in advance!

**Comment by th3magpi3** [comment]
Hey man, might want to make this public...

![image](https://user-images.githubusercontent.com/6315204/36858569-4eaf73ca-1d30-11e8-9246-7a79a2227490.png)

**Comment by luisfpinto** [comment]
> @ th3magpi3 Hey man, might want to make this public...

I'm so sorry, you're right!! I think you should have access to it now.

**Comment by ascillato** [comment]
:+1:

**Comment by mizrachiran** [comment]
Hi @luisfpinto 
How it's going with this integration? I would love to see tasmota in Yeti.
do you need help with testing \ anything else?

**Comment by luisfpinto** [comment]
Hey @mizrachiran Yes for sure! We are right now in the beta testing process. Could you please introduce your email in the form? Remember to introduce the same email you use in the Play/App Store! 

Thank you so much!

**Comment by mizrachiran** [comment]
I filled the form with the same email.
should I re-download the app on my phone?

**Comment by luisfpinto** [comment]
You've received an email with the invitation! 👍

**Comment by mizrachiran** [comment]
Thanks Luis.
it seems like the app doesn't auto discover my tasmota devices.
did I miss anything?

**Comment by Stevehans** [comment]
Will yeti support the on board timers recently implemented in tasmota?

**Comment by luisfpinto** [comment]
Hey! I'll take a look at the documentation and see if I can include it in the next release!

**Comment by luisfpinto** [comment]
Hey @Stevehans, 

I will postpone this implementation as this can already be done with Routines inside Yeti!
Let me know if you have any issue with this functionality inside the app!

**Comment by ascillato** [comment]
Hi, Yeti can find my tasmota devices and work vey well. But the timers are running on the phone. If I go away from home, my timers are not going to work. Can be added an option to configure the Tasmota Timers that already have the firmware?
thanks

Great App!!!

**Comment by Stevehans** [comment]
Problem with routines is that if there is an issue with the cloud service (sonoff/ewelink issues being a classic example) then the central heating or whatever stops.

Having the ability to control the timers is a must I think.

**Comment by luisfpinto** [comment]
Right now timers are controlled by Yeti locally through routines so we are not using any cloud service @Stevehans.

As @ascillato says, you're away timers won't work because Yeti is not on the same network. As an immediately solution if you have a tablet you can install Yeti on it and leave it at home. 

However, I will try to add timers control for the next releases ;) We need to do some more changes before releasing this.
