### ISSUE TITLE
Trying to Flash Sonoff Basic

### ISSUE THREAD

**Issue by veekay1234** [arendst/Sonoff-Tasmota#2062]
My first attempt at flashing Sonoff.  Windows 10.  Using FTD1232.  Arduino 1.8.5.
Any help is appreciated. 
![sonoff](https://user-images.githubusercontent.com/6900418/36879485-17fcbc7c-1d92-11e8-9db8-5f09c82b95db.jpg)

 Arduino: 1.8.5 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, nodemcu, 26 MHz, 40MHz, DOUT, 1M (no SPIFFS), v1.4 Prebuilt, Disabled, None, 115200"

Sketch uses 519612 bytes (50%) of program storage space. Maximum is 1023984 bytes.
Global variables use 51876 bytes (63%) of dynamic memory, leaving 30044 bytes for local variables. Maximum is 81920 bytes.
C:\Users\lenovo-Flex2\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.12/esptool.exe -vv -cd nodemcu -cb 115200 -cp COM4 -ca 0x00000 -cf C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_868828/sonoff.ino.bin 
esptool v0.4.12 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to nodemcu
	setting baudrate from 115200 to 115200
	setting port from  to COM4
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	espcomm_upload_mem
	setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
Uploading 523760 bytes from C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_868828/sonoff.ino.bin to flash at 0x00000000
	erasing flash
	size: 07fdf0 address: 000000
	first_sector_index: 0
	total_sector_count: 128
	head_sector_count: 16
	adjusted_sector_count: 112
	erase_size: 070000
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	setting serial port timeouts to 15000 ms
	setting serial port timeouts to 1000 ms
	espcomm_send_command: receiving 2 bytes of data
	writing flash
.............................................................	read 0, requested 1
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
warning: espcomm_send_command: wrong direction/command: 0x01 0x03, expected 0x01 0x04
closing bootloader
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

ALSO Tried esptool method:
 .\esptool.exe -vv -cb 115200 -cp com4 -ca 0x00
000 -bz 1M -bm dout -cf .\sonoff.bin
esptool v0.4.12 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
        setting baudrate from 115200 to 115200
        setting port from  to com4
        setting address from 0x00000000 to 0x00000000
setting flash size from 512K to 1M
setting flash mode from qio to dout
        espcomm_upload_file
        espcomm_upload_mem
        setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
        flush start
        setting serial port timeouts to 1 ms
        setting serial port timeouts to 1000 ms
        flush complete
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
Uploading 496960 bytes from .\sonoff.bin to flash at 0x00000000
        erasing flash
        size: 079540 address: 000000
        first_sector_index: 0
        total_sector_count: 122
        head_sector_count: 16
        adjusted_sector_count: 106
        erase_size: 06a000
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        setting serial port timeouts to 15000 ms
        setting serial port timeouts to 1000 ms
        espcomm_send_command: receiving 2 bytes of data
        writing flash
...................................................................     read 0, requested 1
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
closing bootloader
        flush start
        setting serial port timeouts to 1 ms
        setting serial port timeouts to 1000 ms
        flush complete
error: espcomm_upload_mem failed

More Esptool cmds:

python.exe .\esptool.py --after no_reset --no-stub -p com4 chip_id
esptool.py v2.3.2-dev
Connecting...
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Enabling default SPI flash mode...
Chip ID: 0x00a3384d
Staying in bootloader.

python.exe .\esptool.py --after no_reset --no-stub -p com4 flash_id
esptool.py v2.3.2-dev
Connecting...
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Enabling default SPI flash mode...
Manufacturer: 5e
Device: 4014
Detected flash size: 1MB
Staying in bootloader.

**Comment by dYna77** [comment]
Did you set the Sonoff in programming mode by pushing the button (GPIO0 to GND)  while/before powering it up?

**Comment by jeylites** [comment]
In addition to @dYna77 post make sure you have the RX and TX in the right ports. Check wiki for more details.  

USB FTDI (RX) -> (TX) Sonoff
USB FTDI (TX) -> (RX) Sonoff

**Comment by veekay1234** [comment]
Thanks for your suggestions.  I had followed the correct process.  Fortunately I was able to install the firmware by using my desktop computer instead of laptop.  Also it runs on Windows 7 32bit.  Not sure why one worked and the  other didn't.
