### ISSUE TITLE
How to enable DHT in Sonoff-Tasmota

### ISSUE THREAD

**Issue by decologne** [arendst/Sonoff-Tasmota#207]
Which module must I select in Sonoff-Tasmota to enable DHT sensor  and which IO pin 
is preferred for WeMos mini board ?

Thanks, Jan van Keulen

**Comment by arendst** [comment]
High eau, for DHT sensor selection you'll have to find out what model of DHT you have. What GPIO you want to use is up to you but you may have to add a resistor of 10k to 3V3 as you are not using a Sonoff device.

See https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-Configuration how to configure.

**Comment by decologne** [comment]
It's working !
Thanks/Bedankt Theo
