### ISSUE TITLE
Sonoff POW info

### ISSUE THREAD

**Issue by Gary202** [arendst/Sonoff-Tasmota#2077]
Is there a way to show voltage even when the sonoff POW relay is off "open"

I have a sonoff POW v2.0 and i have moded the sonoff for the relay controls something else and moniters the voltage of the who project.

I would like to show voltage and ampage draw even if the relay of open.

Gary

**Comment by MimbaMonkeyHouse** [comment]
Been wanting to do this for a while. Cheers for sharing

**Comment by Gary202** [comment]
Thank you
