### ISSUE TITLE
Feature suggestion - Multiple network configurations

### ISSUE THREAD

**Issue by prabbit237** [arendst/Sonoff-Tasmota#2101]
Any possibility of setting up two sets of network settings? I.e. if you have AP1 and AP2, having one set of IPs, etc for AP1 and a different set for AP2 would be helpful.

In my case, the ESP8266 doesn't seem to like the DHCP on my phone's hotspot so I need to use a static IP. But when it's connecting to my router, the DHCP works fine and is also on a different network range. And the MQTT server may be local on one and a remote server on the other. So if I set the IP statically, it works on one and not on the other, etc.

Having something like the following, where it pulls settings depending on which AP it connected to, would work great for both:

#define WIFI_IP_ADDRESS_AP1        "192.168.43.254" 
#define WIFI_GATEWAY_AP1           "192.168.43.1"   
#define WIFI_SUBNETMASK_AP1        "255.255.255.0"
#define WIFI_DNS_AP1               "192.168.43.1"    
#define MQTT_HOST_AP1            "my.remotemqtthost.com"
#define WIFI_IP_ADDRESS_AP21        "0.0.0.0" 
#define WIFI_GATEWAY_AP2           "192.168.43.1"   
#define WIFI_SUBNETMASK_AP2        "255.255.255.0"
#define WIFI_DNS_AP2               "192.168.43.1"    
#define MQTT_HOST_AP2            "192.168.1.100"

**Comment by arendst** [comment]
Get DHCP working on your phone.

**Comment by prabbit237** [comment]
Yes, I'd prefer if it'd work using DHCP on the phone (and am still trying things to see why it's not.) It works fine on the phone hot-spot otherwise but just will not pick up the DHCP lease and, being a cell phone, no (easy) real access to the logs, etc to determine why. Of course, it'd also be nice to have this feature of different network settings for different networks on a Windows computer and Microsoft hasn't implemented it after all these years so maybe it's not as universally "hey, this is a great idea" as I think it is *laugh*

Well, it's not a huge issue and many IoT things live in just one location and on one network most of the time so it's not really that big of a deal. If it's implemented, "Hey, great!" and if it's not, "oh, well." It's nice even having two possible networks that it can bounce between (Amazon Echo? Google Home? Roku? You guys listening here?)
