### ISSUE TITLE
MQTT Setting: Host and Topic is lost

### ISSUE THREAD

**Issue by Marty56** [arendst/Sonoff-Tasmota#2107]
When changing the host or the topic in the MQTT configuration, the settings are saved as expected and communication to MQTT broker is working.
But when revising the MQTT configuration settings, the default settings from the user_config.h shows up again and NOT the previously newly entered data.

**Comment by arendst** [comment]
As designed.

**Comment by Marty56** [comment]
Makes no sense to TMHO and confuses user.
