### ISSUE TITLE
Domoticz Multiple IDX for PWM Dimmers 

### ISSUE THREAD

**Issue by jimpetre** [arendst/Sonoff-Tasmota#2111]
Query more than an issue;

I'm using a Magichome/Arilux controller. Is there any way to assign individual IDX's to the relevant GPIO's as per board pinouts for PWM  to allow separate control in domoticz?

Using a 'generic' module type IDX can be assigned to pin if selecting 'relay' as output type but there is no dimming control of this. at present i have the device configured as a Sonoff LED and this allows an IDX to be assigned but control is only possible for one GPIO  

to be clear i don't want to control RGBW with the magic home but to drive separate Single color led strips as individual devices.  

Thanks

**Comment by gcannar** [comment]
Same problem here! Flashed MagicHome with Tasmote, all ok!
Created a virtual RGB in domoticz but i can control only the on off function , no colors no dimmer...how to set the IDX? Domoticz give me "32" for the RBG switch...and i set in Tasmota IDX to 32...
But how to set other mqtt command sush color and dim? 
Domoticz have just one IDX for all the thing...

Some one can help me? :)

Thanks.

**Comment by arendst** [comment]
Does Domoticz support RGB with MQTT interface now? It didn't a few month ago...

**Comment by jimpetre** [comment]
I’m. It sure, I just want to be able to control all each gpio with a different idx... ie set a different dummy switch per pin assigned to an idx defined in the web interface / user config.h

**Comment by jimpetre** [comment]
Sorry that reply wasn’t very clear. I have no desire to control RGB, (searching through previous issues this doesn’t seem possible with Domoticz) but... I’d like to control dimming for each mosfet channel of the magic Home as an individual device.

 If you select ‘Relay’ as ‘type’ in the web config it gives you an idx to configure with Domoticz but selecting PWM it doesn’t. Is there any way to do this?

**Comment by jimpetre** [comment]
You da man!


On 20 Mar 2018 15:15, "Theo Arends" <notifications@github.com> wrote:

Dimming for each channel will be possible from release 5.12.0h using
command channel 0..100

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/arendst/Sonoff-Tasmota/issues/2111#issuecomment-374635706>,
or mute the thread

**Comment by ascillato2** [comment]
Closing this issue as it is fixed.

**Comment by mVik85** [comment]
> Still no way to assign different IDX's to PWM1,2,3,4,5? as you would with relay 1,2,3,4,5?

If anyone would wonder about this (like me until 5 minutes ago), here the answer:
https://github.com/emontnemery/domoticz_mqtt_discovery
