### ISSUE TITLE
Request: Add Temperature decimal place in 0.1 increments at the CO2 sensor MH-Z19b

### ISSUE THREAD

**Issue by FabianHM** [arendst/Sonoff-Tasmota#2112]
Hello,
please add the Temperature decimal place in 0.1 increments, not just rounded to 0.5 degrees at the CO2 sensor MH-Z19b.
Thanks
Fabian

**Comment by arendst** [comment]
As far as I know the MHZ19B undocumented temperature value is a plain integer without decimals...

**Comment by FabianHM** [comment]
Okay, then I use for Temperature the suitable one AM2301 additionally, that works fine
