### ISSUE TITLE
Settings for custom drivers

### ISSUE THREAD

**Issue by issacg** [arendst/Sonoff-Tasmota#2138]
In the new-ish driver configuration, there's room for user-defined drivers which, presumably, aren't intended to be merged into the project.  Is there a recommended way to add settings to be saved to the flash chip for custom drivers, rather than patching the SYSCFG struct?

**Comment by arendst** [comment]
There is no defined way of using the Settings area other than that I try to cram it in and fix backward compatibility too ;-).

For new custom drivers just add new variables to the end of the settings struct and I will try to fix it if it will be released.
