### ISSUE TITLE
NEW OPTIONS

### ISSUE THREAD

**Issue by Zoltant7** [arendst/Sonoff-Tasmota#2144]
Hi!
We have new options in Arduino IDE , under GENERIC 8266 there is under Erase Flash :
1,Sketch
2, Sketch + WIFI
3,Flash all

For tasmota which one is the proper opt??
Thanks

**Comment by arendst** [comment]
For now the settings below seem to work fine:

![image](https://user-images.githubusercontent.com/11044339/37293676-4ccee0e4-2614-11e8-85f3-48c63516f63a.png)

This might change if problems arise...
