### ISSUE TITLE
Feature Request: Interlocking switching delay

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#2148]
Hello,

I would like to propose a feature that enhances the Interlocking ability of the sonoff devices.
It would really add value to have a delay when interlocking between the switches happens.
To make it clear:

NOW:
Turn on switch1 -> Switch1 ON
Turn on switch2 -> Switch1 OFF, Switch2 ON

WITH DELAY FEATURE
Turn on switch1 -> Switch1 ON
Turn on switch2 -> Switch1 OFF, DELAY, Switch2 ON

I currently have a Sonoff T1 2CH driving a window motor with 
https://github.com/ageorgios/homebridge-tasmota-mqtt-motor
but when using interlock switching I would like to see a small delay (preferably a variable) to let the motor rest before driving on the opposite direction.

Thank you.

**Comment by arendst** [comment]
Use backlog functionality with delay command
