### ISSUE TITLE
[Help wanted] Disable Sonoff 4ch pro RF

### ISSUE THREAD

**Issue by SaverioConigliaro** [arendst/Sonoff-Tasmota#2166]
Hey There,
I nave a tasmota flashed Sonoff 4ch pro connected to severamente house lights and i keep getting interference from the allarm wireless PIR. Every time i trigger the PIR by moving somewhere in front of It then my house lights switch on and off!!!
Since I don't Plan to use any remote Command... Is It possible to Disable radio (RF not wifi) interface?

**Comment by arendst** [comment]
RF is not controlled by Tasmota.

- Unlearn the RF code from your PIR see itead website how to.
- Remove RF antenna
- Cut PCA circuit controlling RF signal

**Comment by SaverioConigliaro** [comment]
Could you tell me where is the RF antenna in the SONOff 4 ch pro? Is this cutting going to influence wifi signal too?

**Comment by SaverioConigliaro** [comment]
I didn't put an RF from the SONOff into my PIR!!!! This PIR is One of the components offline my allarm wireless system!!! PIR RF programming were performed by my allarm Central not by sonoff!!!! But when this PIR is triggered It trigger sonoff relè too!!!!

**Comment by arendst** [comment]
It can only trigger the relay when Sonoff Pro has learned it. As Sonoff Pro learns as soon as you hold the button for a few seconds chances are you did it without knowing.

See wiki where to find the coiled RF antenna. Removing it has no consequences for wifi.

**Comment by SaverioConigliaro** [comment]
You mean that while putting SONOff into the Wall i pressed the button without knowing It and It catched the code from the PIR sensor above my head???? LOL

**Comment by SaverioConigliaro** [comment]
Last question: to replicate this behaviour (cause It could be usefull...) Do I have to trigger the PIR by moving in front of It while pressing the SONOff button?

**Comment by arendst** [comment]
Depends. If the PIR sends RF every second then it's not needed but you probably have to, yes.

**Comment by SecurityAddicted** [comment]
This can be useful to disable the RF part: https://github.com/arendst/Sonoff-Tasmota/issues/911#issuecomment-331694747

**Comment by Snipercaine** [comment]
Opposite question:   I want to use the RF bridge to control the 4ch pro.  Is that possible?

**Comment by ascillato** [comment]
Hi @Snipercaine ,

I think it should be possible. I don't have a 4Ch Pro to test it now, but the SOnOff Bridge can send any RF code and the SOnOff 4Ch Pro can learn any of these codes.

So, if you set your 4Ch in learning mode and you press any of the keys on the main page of your Sonoff Bridge, it should be working.

Besides, you can control the 4Ch from the Bridge using MQTT or directly (device to device) using RF or by websend command or by KNX.

Hope this helps.

BTW, Love your videos! :+1:
