### ISSUE TITLE
Issuing /cmd/IPAddress1 192.168.0.251 sets static IP as expected but does not restart Sonoff Basic as expected

### ISSUE THREAD

**Issue by emeyedeejay** [arendst/Sonoff-Tasmota#2180]
Issuing /cmd/IPAddress1 192.168.0.251 sets static IP as expected but does not restart Sonoff Basic as expected per documentation - issuing of "Restart 1" required to restart Sonoff Basic.

Not a major issue but thought it worth reporting.

Make sure these boxes are checked before submitting your issue - Thank you!

- [x] What hardware you are using
Sonoff Basic
- [x] Provide the output of command ``status 0``
status 0
21:05:04 RSL: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":"Sonoff","Topic":"sonoff","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
21:05:04 RSL: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","Uptime":"0T00:01:54","Sleep":0,"BootCount":1116,"SaveCount":2242,"SaveAddress":"FA000"}}
21:05:04 RSL: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"5.12.0","BuildDateTime":"2018-02-09T14:54:51","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
21:05:04 RSL: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"JNET","SSId2":"indebuurt2","TelePeriod":300,"SetOption":"00000009"}}
21:05:04 RSL: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":485,"Free":516,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
21:05:04 RSL: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"IrrigationPowerSwitch","IPAddress":"192.168.0.251","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"5C:CF:7F:72:D7:2C","Webserver":2,"WifiConfig":2}}
21:05:04 RSL: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"domus1","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_72D72C","MqttUser":"DVES_USER","MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
21:05:04 RSL: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Fri Mar 16 20:05:04 2018","Local":"Fri Mar 16 21:05:04 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1}}
21:05:04 RSL: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2018-03-16T21:05:04"}}
21:05:04 RSL: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2018-03-16T21:05:04","Uptime":"0T00:01:54","Vcc":3.248,"POWER":"ON","Wifi":{"AP":1,"SSId":"JNET","RSSI":100,"APMac":"A4:2B:B0:C3:74:2E"}}}

- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

**Comment by ionciubotaru** [comment]
try:
`cmnd/sonoff/backlog IPAddress1 192.168.0.25;restart 1`

read about `backlog`

**Comment by emeyedeejay** [comment]
Thanks ... will check out backlog. I got it working by issuing a restart command.
The documentation just needs updating (or changing the IP address need to force a restart per the current documentation.)

**Comment by arendst** [comment]
That was the case but hen it makes sense to wait for a restart as you would probably also want to change the gateway and the netmask. So it was decided to get rid of the restart functionality some time ago.

Pls feel free to update the wiki with your findings.

**Comment by emeyedeejay** [comment]
Makes sense... thank you.

I will edit as suggested :thumbs up:

( @arendst  Theo, thank you for a wonderful firmware. Got it all going now Sonoff basic -> Tasmota -> Domoticz -> Controlicz -> Google home and any MQTT based system too. Wonderful!)

**Comment by emeyedeejay** [comment]
Documentation edited ... closing
