### ISSUE TITLE
Offer GPIO09/10 in DOUT Mode

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#2191]
- Hardware ESP8266-12F

If I understand [SPI Flash Modes](https://github.com/espressif/esptool/wiki/SPI-Flash-Modes) correctly, GPIO09 and GPIO10 are not used in DOUT mode. That allows to use GPIO09/10 just as regular GPIOs.

**Comment by arendst** [comment]
Offer on what device?

It's only valid on ESP8285 as all ESP8266 are wired for QIO flash so even at DOUT you are still not able to use the GPIOs as they will interfere with your flash.
