### ISSUE TITLE
i miss SPI_CLK (clock)

### ISSUE THREAD

**Issue by 1hotte** [arendst/Sonoff-Tasmota#2193]
#Hello , sorry my english is bad. 

I found the , SENSOR_SPI_CS, and 
 SENSOR_SPI_DC  . I miss the SENSOR_SPI_Clk selction.

How to activate  GPIO_SPI_CLK,        // SPI Clk library fixed pin GPIO14
found on Sonoff_template.h
How to activate it.

- [x] What hardware you are using
ESP8266

**Comment by arendst** [comment]
You don't have to enable it as it says: GPIO_SPI_CLK, // SPI Clk library fixed pin GPIO14

This means it will always use GPIO14.

**Comment by 1hotte** [comment]
THX
