### ISSUE TITLE
Double Recognized Sonoffs with Hue Emulation when Echo Dot 2. Generation is connected

### ISSUE THREAD

**Issue by motorrad** [arendst/Sonoff-Tasmota#2198]
Make sure these boxes are checked before submitting your issue - Thank you!

Im using 2 X Echo Show 3 X Echos 1 X Sonos One 2 X Echo Spot and after Connecting an Echo Dot 2.nd Generation the Philips Hue Emulation is discovered two Times for every Sonoff device :
First as : Royal Philips Electronics intelligentes Gerät 
Second as : Philips Hue
Belkin Emulation remains ok.
I am using the v5.12.0 Firmware.
When I disconnect the Echo Dot there are only Royal Philips Electronics intelligentes Gerät devices which will be found.

**Comment by motorrad** [comment]
THX@arendst  for Setting help wanted Label :-)

**Comment by vw2audi** [comment]
Hi i have exactly the same problem. Any sollution?
