### ISSUE TITLE
Sonoff RF issue

### ISSUE THREAD

**Issue by mverzakov** [arendst/Sonoff-Tasmota#22]
Hi!
I'm struggling with a Sonoff RF Problem.
I'm trying to pair my RF button with sonoff rf. (I don't havany special connection for R21 )
So I pushed button on RF module, LED blinked red one time. I bushed my RF button and LED blinked 3 times.
Now, every time I push my RF button, Sonoff's Led blinks red, but power doesn't switch.
Could you please help me?

**Comment by MacWyznawca** [comment]
I have the same problem. Sonoff RF learned remote control. Pressing the remote control, causing LED light red, but does not switch. I set Sonoff RF module in configuration.

**Comment by mverzakov** [comment]
I was somehow able to control Sonoff RF with a remote. 
I'm not sure what was the problem.

**Comment by davidelang** [comment]
I'mm close this issue since you seem to have it working, you can re-open it if you still have problems.
