### ISSUE TITLE
Is it possible to run Access Point-based WebConfig mode and WPS-setup mode simultaniously?

### ISSUE THREAD

**Issue by KonstantinMastak** [arendst/Sonoff-Tasmota#220]
This is not a feature request yet, but rather a theoretical question. Will be glad if you could answer based on your experience. Currently we choose with button if we need to load Tasmota with WebConfig mode or with WPS mode. Is it possible from technical point of view to make WebConfig and WPS modes work simultanously? Or is there any core library problem that prevents from doing so?

**Comment by arendst** [comment]
Try it and let me know.

**Comment by KonstantinMastak** [comment]
It seems that WPS works only in STA mode. If it's AP or AP+STA, it does work, unfortunately...

**Comment by davidelang** [comment]
that makes sense. So since the two modes are not compatible, I'll close this issue.
