### ISSUE TITLE
SHT3X-0x45 Temperature and Humidity labels and json object issue

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#2207]
Make sure these boxes are checked before submitting your issue - Thank you!

- [x] What hardware you are using: Wemos D1 Mini Pro + SHT30

Are these labels for indicating temperature and humidity new? The "-0x45" is seen since tasmota version 5.12.0g. Screenshot below is version 5.12.0h

![screen shot 2018-03-20 at 18 48 45](https://user-images.githubusercontent.com/25717738/37672959-5bce4d8a-2c6f-11e8-8b2c-f82a56d228bd.png)

Just found out that also the dash (-) in the name of the json is giving issues when using the json object in javascript. Please consider renaming it into SHT3X_0x45 instead. 

Thanks :)

**Comment by arendst** [comment]
Yep. it now supports two of them. The dash was there all the time on other sensors so I suggest to google around for a javascript solution.

**Comment by RaymondMouthaan** [comment]
Theo that was just the post i was checking haha .. 

I've fixed it using the bracket notation instead of the dot notation. 

So my function in node-red looks like this:
 
```
// Prepare SHT3X-0x45 Temperature and Humidity for InfluxDB
msg.payload = msg.payload["SHT3X-0x45"];
msg.measurement = msg.topic.match(".*/(.*)/.*")[1];
return msg;
```

Thanks for pointing me in a different direction :-)

**Comment by arendst** [comment]
Glad I could help ;;;---)))

**Comment by mrteausa** [comment]
Hello, I put this value_template: '{{ value_json["SHT30-0x45"].Temperature }}' on the configuration.yaml in HA it does not get the reading why??

**Comment by cmccambridge** [comment]
@mrteausa - There's a typo in the template you quoted. The correct name for the JSON field is `SHT3X-0x45`, as in: `{{ value_json['SHT3X-0x45'].Temperature }}`.
