### ISSUE TITLE
sonoff:42: error: #error Please use stable lwIP v1.4

### ISSUE THREAD

**Issue by PETEIOT** [arendst/Sonoff-Tasmota#2210]
I continue to get this error even if I only verify the code, I have changed the packet size in PubSubClient 1000 I've tried different boards, restarting, re-downloading any idea? 

Running windows, 

sonoff:42: error: #error Please use stable lwIP v1.4

   #error Please use stable lwIP v1.4

    ^

exit status 1
#error Please use stable lwIP v1.4

**Comment by mscreations** [comment]
Make sure you setup Arduino IDE similar to below (at least for the development branch):

IF you are on the master branch, then choose one of the v1.4 options. 

![image](https://user-images.githubusercontent.com/1254904/37688994-21c960ca-2c79-11e8-9f17-580e97068cb3.png)

**Comment by PETEIOT** [comment]
OK so I was thinking there was a problem with my options  I don’t have those same options I’m missing the flash mode and the one that you’re referring to and if you others is there something I need to turn on?

**Comment by mscreations** [comment]
I forgot to mention that you also should go into Board Manager (Board submenu) and make sure esp8266 version is 2.4.1. I've had the most success with this particular version and setup.

![image](https://user-images.githubusercontent.com/1254904/37689704-0e19b756-2c7d-11e8-9995-eac752afc9e2.png)

**Comment by PETEIOT** [comment]
That was it thanks mscreations!

**Comment by Sovatna** [comment]
Thanks @mscreations you also solve my doubt.
