### ISSUE TITLE
Add blade counter in shutter mode

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#2212]
Rating the current shutter position is quite complicated. The runtime of the shutter needs to be clocked exactly and exponentially multiplied with the dynamic radius of the shutter winding on the shaft.

I suggest to mount pieces of adhesive magnetic stripe on each shutter blade and a hall sensor connected to a GPIO in the shutter box. That way the position of the shutter can be calculated easily:

**pos = 100% / blades * counter**

**Comment by renne** [comment]
As the WLAN connection can fail I suggest to implement this directly in Tasmota.

**Comment by stefanbode** [comment]
I have now addressed this issue in my mod of Tasmota. You will find it under stefanbode. Functionality is to open close and set to any value between 0 and 100. All calculation and Relay control is done in the firmware. Please read the wiki carefully how to set it up and let me know if you need support.

**Comment by ascillato2** [comment]
Hi,

Continuing this issue at: #3137
