### ISSUE TITLE
Sonoff touch not connecting anymore

### ISSUE THREAD

**Issue by Sholofly** [arendst/Sonoff-Tasmota#2241]
After operating a few weeks succesfully, my sonoff touch is not working anymore. after upgrading to the latest tasmota firmware it worked for a day but now, the wifi led is blinking for a few seconds, stays on for a seconds, blinks twice and then turns off. This is repeating continuously. I can't connect tot any wireless interface anymore.. anyone an idea how to fix?

**Comment by WagnerBeccard** [comment]
I think I had the same issue with my basic..
Try this out 

https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#esptool-usage

**Comment by Sholofly** [comment]
Thanks for the reply. I have switched it for a spare T1 version so can't test it for know. I'll try your suggestion later.

**Comment by netruner** [comment]
I upgrade sonoff Touch from original system.
WiFi after upgrade signal strength is fatal ping 93% lost

**Comment by Sholofly** [comment]
Touch is broken. Thank you @WagnerBeccard for you suggestion. No luck!
