### ISSUE TITLE
Timer feature

### ISSUE THREAD

**Issue by species5618** [arendst/Sonoff-Tasmota#2243]
love the timers you have just added.
is it possible to have a very simple extension, 
instead of switch on/off at xx:xx time, switch on/off in xx mins yy seconds,

use case is fail safe , turn something on, and know it will be off  XXmins, even if there is a control failure

**Comment by reloxx13** [comment]
use pulsetime command?^^

**Comment by species5618** [comment]
pulsetime is spot on thanks
