### ISSUE TITLE
SerialSend -> unknown command

### ISSUE THREAD

**Issue by dYna77** [arendst/Sonoff-Tasmota#2244]
I am using a Sonoff Basic with version 5.12.0d and am trying to use the hardware serial.
When i enter SerialSend i get the following:
`CMD: SerialSend
 MQT: stat/sonoff/RESULT = {"Command":"Unknown"}`

`CMD: SerialLog
MQT: stat/sonoff/RESULT = {"SerialLog":"1 (Active 1)"}`

`17:28:24 CMD: status 0
17:28:24 MQT: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":"wohnzimmer","Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
17:28:24 MQT: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.2.50/sonoff.ino.bin","Uptime":"0T01:20:09","StartupUTC":"2018-03-24T15:08:15","Sleep":0,"BootCount":10,"SaveCount":53,"SaveAddress":"F7000"}}
17:28:24 MQT: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"5.12.0d","BuildDateTime":"2018-03-23T10:18:19","Boot":6,"Core":"2_4_0","SDK":"2.1.0(deb1901)"}}
17:28:24 MQT: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":1,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId1":"nodeone","SSId2":"","TelePeriod":300,"SetOption":"00000009"}}
17:28:24 MQT: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":496,"Free":504,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
17:28:24 MQT: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"wohnzimmer","IPAddress":"192.168.2.129","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"60:01:94:68:F8:B9","Webserver":2,"WifiConfig":3}}
17:28:24 MQT: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.50","MqttPort":1883,"MqttClientMask":"wohnzimmer","MqttClient":"wohnzimmer","MqttUser":"sonoff","MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
17:28:24 MQT: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Sat Mar 24 16:28:24 2018","Local":"Sat Mar 24 17:28:24 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1}}
17:28:24 MQT: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2018-03-24T17:28:24","Switch1":"OFF"}}
17:28:24 MQT: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2018-03-24T17:28:24","Uptime":"0T01:20:09","Vcc":3.483,"POWER":"OFF","Wifi":{"AP":1,"SSId":"nodeone","RSSI":88,"APMac":"C4:6E:1F:AA:1E:99"}}}
17:28:28 MQT: tele/sonoff/STATE = {"Time":"2018-03-24T17:28:28","Uptime":"0T01:20:13","Vcc":3.484,"POWER":"OFF","Wifi":{"AP":1,"SSId":"nodeone","RSSI":100,"APMac":"C4:6E:1F:AA:1E:99"}}
17:28:28 MQT: tele/sonoff/SENSOR = {"Time":"2018-03-24T17:28:28","Switch1":"OFF"}`

**Comment by arendst** [comment]
Pls upgrade to latest development version as serial is introduced in v5.12.0h
