### ISSUE TITLE
Sonoff T1 2CH eu - rebooting with default config by itself...

### ISSUE THREAD

**Issue by alexjoni** [arendst/Sonoff-Tasmota#2255]
Hi,

I have just flashed a T1 2ch EU with Tasmota 5.12.0i (d564615b7d70b493925f2045699ed94b36e7ccdd),
however I see a strange behaviour.
After flashing the device connects to wifi, gets an ip and I get to the Tasmota page.
I can select the proper config (touch 2ch, mqtt names, etc) and it restarts with the proper values.
But if I leave it on, without any input, I see after a while it reboots and loads the default config values.

I managed to grab a screenshot from the console https://ibin.co/w800/3w5Mb7Ev0QWK.png
In that screenshot the mqtt server is set on purpose to a wrong IP address, to see if the CFG: Use defaults doesn't come from MQTT (although I see no reason for that).

I also tried resetting the flash config area, using a new #define CFG_HOLDER             0x20180325

I see the same behaviour even with the module configured as a basic...

- [x] Provide the output of command ``status 0``
13:13:26 CMD: status 0
13:13:26 MQT: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
13:13:26 MQT: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin","RestartReason":"Software/System restart","Uptime":"0T00:02:33","StartupUTC":"2018-03-25T11:10:53","Sleep":0,"BootCount":1,"SaveCount":3,"SaveAddress":"F9000"}}
13:13:26 MQT: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"5.12.0i","BuildDateTime":"2018-03-25T13:58:36","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
13:13:26 MQT: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"192.168.1.3","LogPort":514,"SSId":["xxxx","yyyy"],"TelePeriod":300,"SetOption":["00008009","55A18000"]}}
13:13:26 MQT: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":475,"Free":528,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
13:13:26 MQT: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-6837","IPAddress":"192.168.1.129","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"60:01:94:A1:5A:B5","Webserver":2,"WifiConfig":3}}
13:13:26 MQT: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.3","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A15AB5","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
13:13:26 MQT: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Sun Mar 25 11:13:26 2018","Local":"Sun Mar 25 13:13:26 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":2}}
13:13:26 MQT: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2018-03-25T13:13:26"}}
13:13:26 MQT: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2018-03-25T13:13:26","Uptime":"0T00:02:33","Vcc":4.094,"POWER":"ON","Wifi":{"AP":1,"SSId":"xxxx","RSSI":100,"APMac":"E8:94:F6:67:9B:97"}}}
- [x] What hardware you are using
Using Sonoff T1 R2 EU, Touch board v1.0

**Comment by emontnemery** [comment]
This happens if you don't have the relay board connected.

**Comment by alexjoni** [comment]
I can confirm, after installing it in place (plugged into the relay board) it behaves ok.
I had a reboot+default config loaded when plugging in the touch cover (probably caused a reset?)

**Comment by emontnemery** [comment]
The reset to default happens when you long press touch button, this is tasmota default behaviour. Without the relay board, this long press is also detected, I think it's some kind of watchdog when the auxiliary micro controller detects malfunction of the relay board.
Any way, special behaviour for long press  makes no sense for a wall switch IMHO. You can use 'setoption13 1' to disable this behaviour, it will also make the touch button respond instantly. It also disables multiple click special functions.

**Comment by jpadie** [comment]
Well spotted emontnemery. The issue also prevents using touch to programme an RF code   
But unfortunately thale fix is not a sensible solution.  Better perhaps would be to increase this reset functionality to 30secs.  
But also there should be a way to prevent a config reset whilst maintaining other functionality. Otherwise some wag might reset the device for a 'laugh'.
