### ISSUE TITLE
New version of Sonoff B1

### ISSUE THREAD

**Issue by timosntr** [arendst/Sonoff-Tasmota#2274]
Hardware: Sonoff B1 "V1.0.3"
`Status0` got me this:
`{"Status":{"Module":26,"FriendlyName":["Sonoff"],"Topic":"bettschrank","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
{"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin","RestartReason":"External System","Uptime":"0T00:01:43","StartupUTC":"2018-03-28T13:11:40","Sleep":0,"BootCount":6,"SaveCount":27,"SaveAddress":"F9000"}}
{"StatusFWR":{"Version":"5.12.0h","BuildDateTime":"2018-03-28T14:26:08","Boot":4,"Core":"2_4_0","SDK":"2.1.0(deb1901)"}}
{"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Searching...","BriSant"],"TelePeriod":300,"SetOption":["00008009","55818000"]}}
{"StatusMEM":{"ProgramSize":499,"Free":504,"Heap":19,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
{"StatusNET":{"Hostname":"bettschrank-0955","IPAddress":"192.168.0.130","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"BC:DD:C2:F8:23:BB","Webserver":2,"WifiConfig":3}}
{"StatusMQT":{"MqttHost":"192.168.0.81","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_F823BB","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
{"StatusTIM":{"UTC":"Wed Mar 28 13:13:23 2018","Local":"Wed Mar 28 14:13:23 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1}}
{"StatusSNS":{"Time":"2018-03-28T14:13:23"}}
{"StatusSTS":{"Time":"2018-03-28T14:13:23","Uptime":"0T00:01:43","Vcc":3.573,"POWER":"OFF","Dimmer":100,"Color":"FF3D3D906F","HSBColor":"0,76,100","Channel":[100,24,24,56,44],"CT":304,"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":2,"SSId":"BriSant","RSSI":100,"APMac":"54:67:51:6F:10:28"}}}`

Today I got my second pair of Sonoff B1, I opened it and got this:
![img_4125](https://user-images.githubusercontent.com/33757112/38030541-3721d03a-3299-11e8-91a4-e6b460b72739.jpg)
As you can see the layout is a bit different, but it is also possible to flash Tasmota to it. The problem is, that if I configure the module as an Sonoff B1, it will do nothing if I want it to power on.
I got two of the new ones and both have this problem.

Maybe someone else got the new ones and can help? Otherwise it would be a good future improvement in Tasmota to support those.

**Comment by arendst** [comment]
Have a look at module AiLight and see if that works.

**Comment by timosntr** [comment]
Thank you very much, that worked! Mysterious, from the outside it looked like an Sonoff B1 and i ordered it as one. The board itself looks like a AiLight, as i found out on google.
