### ISSUE TITLE
New model SONOFF T1 US 1-2-3 gang

### ISSUE THREAD

**Issue by cirolaferrara** [arendst/Sonoff-Tasmota#2275]
New model SONOFF T1 US 1-2-3 gang is out

**Comment by emontnemery** [comment]
@cirolaferrara It's a wiki, if you can create issue you can also edit the wiki..

**Comment by emontnemery** [comment]
Sorry, I put a comment in wrong issue!

**Comment by PiOver2** [comment]
I have flashed T1 R2 US TOUCH BOARD V1.0 successfully by touching pad P3 while pressing switch S1 to enter flash mode.

**Comment by dcazarez05** [comment]
Hi @PiOver2 Did you mean you can install another firmware like Tasmota or something like that?
If yes, Can you share how you do it please?

**Comment by gonzunigad** [comment]
It also worked for me touching P3 while pressing S1. 
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-T1-UK-and-T1-EU/

Connect the serial adapter to J3 
Module - Serial USB
- 3v3 -> 3v3
- Rx -> Tx
- Tx -> Rx
- GND -> GND

Then, once connected and powered up, touch pad 3 (the one next to to esp8265) and the, without releasing pad 3, press Switch 1 (above). 

Once I was on flashing mode, I compiled tasmota on arduino using these settings (Generic esp8265. Not 8266)

![image](https://user-images.githubusercontent.com/1103494/41577781-c5f6463e-735c-11e8-922d-f6d693355f07.png)
I think you can just upload the sketch, but what I always do, is to program it using [esptool](https://github.com/espressif/esptool). 

![image](https://user-images.githubusercontent.com/1103494/41577821-12250a9a-735d-11e8-92b0-8a0cc677f352.png)

That worked for me.

**Comment by MYLE-01** [comment]
I have did it also 

What did got the bin file only used espeasy to flash it then used termite  to send all info I needed and order 3 more next time i'm try the backlog thing

**Comment by zomars** [comment]
Have anyone had luck using SonOTA?

**Comment by cirolaferrara** [comment]
Yes. I flashed it with sonota

**Comment by zomars** [comment]
@cirolaferrara what firmware did you have when you flashed? I'm on 1.8 and it's stuck before 
FinalPhase.

**Comment by cirolaferrara** [comment]
I'm sorry. I don't rembember. Anyway remember to disable firewall
