### ISSUE TITLE
Publishing MQTT messages only using GPIO1 and GPIO3 for HA automations

### ISSUE THREAD

**Issue by tatunts** [arendst/Sonoff-Tasmota#2281]
Hello everyone!

I was wondering: is it possible to use GPIOs TX (01) and RX (03) just to publish MQTT messages using a regular 3 button switch?

This is my setup:

![b3b257df9240d25996612dfe37ef30667251412f](https://user-images.githubusercontent.com/25224882/38053939-d4d93d7e-32ab-11e8-81f1-7697c5f23d3e.jpg)

![b24841d643cad01b0191e8510aa26b620ecb34cc](https://user-images.githubusercontent.com/25224882/38053968-e886bcb6-32ab-11e8-9908-6f6f20e2eccf.jpg)

I’ve used the GND wire on all three buttons. This works if set relay on GPIOs 14, TX and RX (it turns the one and only relay on and off successfully) but no luck setting other switch type like this:

![e03d6926b24a7f682bf986adaeeb45747bdff853](https://user-images.githubusercontent.com/25224882/38054001-feb7b1fc-32ab-11e8-92a8-17db6a8cc032.jpg)

My idea is when I press buttons 2 or 3 (GPIO TX/RX) a message is published via MQTT so I can use it with an automation (MQTT trigger) to turn on/off a ceiling fan, for example, and so on.

Is it possible?

I wish I could just publish a MQTT message when the contacts are shorted (TX or RX and GND).

The odd part is if I set TX and RX to switch1, they both work just fine! Exactly like GPIO14 does. If I change to anything else, nothing is shown on the console screen. I’ve tried almost every option there.

I really think this could open a lot of possibilities with this already incredible device.

Thanks!

**Comment by emontnemery** [comment]
Yes, this is possible, check the wiki here:
https://github.com/arendst/Sonoff-Tasmota/wiki/Understanding-SwitchMode-and-SwitchTopic

**Comment by roguestreak** [comment]
I do hope you're going to ensure those power lines are pushed all the way in and not hanging in the breeze?

**Comment by tatunts** [comment]
Thanks a lot @emontnemery! I will check it out. 

No worries @roguestreak, this is only a test prototype.

Thanks!!

**Comment by ascillato** [comment]
Hi,

I think that rules should solve your request. Can you share the rules you used?

I'm very interested on this because it should be a very common **use case** of a sonoff basic.

**Comment by tatunts** [comment]
Hello!

I could not make this work. Have not tried to do it with rules, if anyone could share an example it would be very appreciated!

Thanks.

**Comment by ascillato** [comment]
Hi,

Can you make something like [this](https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#2-execute-any-mqtt-message-when-a-button-is-pressed) example of the wiki?

**Comment by tatunts** [comment]
Hello @ascillato!

No, sorry. The odd thing is that even with seriallog off, nothing is shown on console. I've set the GPIOs to button, switch, relays, nothing happens.

Thanks!

**Comment by ssinseeme** [comment]
have you tried NodMCU it has more GPIOs. or you want just tried it on Sonoff?
I am trying to do the same thing actually with NodeMCU

**Comment by tatunts** [comment]
I have not tried with a NodeMCU. Hope you can share your results!

**Comment by ascillato2** [comment]
Hi,

Any updates?

**Comment by tatunts** [comment]
Hello! Yes! Got it working by setting the board as generic, like this:

![image](https://user-images.githubusercontent.com/25224882/43041466-ded7ae46-8d37-11e8-991f-f4c902bce337.png)

These are the results on logs: 

![image](https://user-images.githubusercontent.com/25224882/43041472-29442d88-8d38-11e8-9e4e-ec002a2781c0.png)

Here you can see it working: https://photos.app.goo.gl/JdnB76mZkuPMPzTU7

Here is the backlog used: `Backlog Module 18; GPIO0 9; GPIO1 10; GPIO2 0; GPIO3 11; GPIO4 0; GPIO5 0; GPIO12 17; GPIO13 52; GPIO14 9; GPIO15 18; GPIO16 19; SetOption13 1; SetOption26 0; SwitchTopic 1; switchmode1 3; switchmode2 3; switchmode3 3; switchmode4 3; SerialLog 0`

**Comment by ascillato** [comment]
Great! Thanks for share :+1:
