### ISSUE TITLE
ESP-12 Ai thinker analog pin anable

### ISSUE THREAD

**Issue by hwarang098tkd** [arendst/Sonoff-Tasmota#2282]
HI all!!!
I have this module.
 https://www.google.gr/search?biw=1920&bih=930&tbm=isch&sa=1&ei=Hvm7WrnTKIar6ASghb7IAw&q=ai+thinker+esp8266&oq=ai+thinker&gs_l=psy-ab.3.1.0i19k1l8j0i30i19k1.9403.11675.0.13168.4.4.0.0.0.0.182.657.0j4.4.0....0...1c.1.64.psy-ab..0.4.655...0i8i7i30k1j0i7i30k1j0i7i30i19k1.0.iQ4vqsqnBCU#imgrc=yPJgq3u_aou4bM:

i flash tasmota code and set it to 18-Generic
How to enable analog pin to set a simple photoresistor?????. https://www.google.gr/search?q=photoresistor&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjej7mt7I_aAhXKbZoKHVeyAhsQ_AUICigB&biw=1920&bih=930#imgrc=TM1Z4p2_KbWgJM:

**Comment by Frogmore42** [comment]
see https://github.com/arendst/Sonoff-Tasmota/issues/1365
