### ISSUE TITLE
Support integrating AM2320 humidity/temperature sensor I2C

### ISSUE THREAD

**Issue by florty** [arendst/Sonoff-Tasmota#2287]
Hardware: ESP8266

I do have the necessary code read the sensor's data, but I would like some help integrating it. 
 Any hints will be appreciated. 

Thank you.

**Comment by roguestreak** [comment]
I'd like this integrated too, I found a thread from a while ago discussing it but it seemed to just get dropped?

**Comment by arendst** [comment]
Well the following from Adafruit is a good reason to not include it:

![image](https://user-images.githubusercontent.com/11044339/38131620-156883f6-3408-11e8-8191-db4a600158a8.png)

**Comment by roguestreak** [comment]
So you won't support it because adafruit reckon it's probably not as accurate as the datasheets say it is??

**Comment by Frogmore42** [comment]
I think he's saying if you want a inaccurate sensor get one of the already supported ones, ie the DHT11 or 22.  Or for only a little, sometimes not even, more get an accurate one like the SHT, BME, HTU sensors that are also already supported.  

If you really want to use the AM2320, it is not too hard to use the new user sensor capability.  There was some discussion in another issue and someone had some sample code for proportional control, which would help, as would looking at the implementation of the other humidity sensors.

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.

**Comment by lrswss** [comment]
https://github.com/lrswss/tasmota-am2320-i2c-driver

**Comment by nightphobos** [comment]
https://github.com/nightphobos/tasmota-am2320-i2c-driver - fixes & binary for 9.5.0

**Comment by ascillato** [comment]
@nightphobos

Hi, please, can you make a PR with your new driver to Tasmota? Thanks

**Comment by nightphobos** [comment]
@ascillato I'll be glad to, wait for pull request this week

**Comment by nightphobos** [comment]
@ascillato added as optional functional, because this i2c address has conflict with more popular modules.
https://github.com/arendst/Tasmota/pull/12485
