### ISSUE TITLE
Support OpenThermGateway

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#2295]
European boiler and air-conditioning manufacturers started about the year 2000 to switch to the[ Opentherm](https://www.opentherm.eu/) [bus/protocol](http://www.domoticaforum.eu/uploaded/Ard%20M/Opentherm%20Protocol%20v2-2.pdf) to control their devices.

[This circuit](http://ihormelnyk.com/page/arduino_opentherm_controller) interfaces a microcontroller with an OpenTherm device. Adding OpenTherm-support in Tasmota allows to control boilers and air-conditioning units via MQTT.

**Comment by renne** [comment]
[Opentherm Arduino IDE library](https://github.com/jpraus/arduino-opentherm), circuits and PCB.

**Comment by ascillato2** [comment]
Hi, there is someone working on a Tasmota's driver for this sensor?

**Comment by ascillato2** [comment]
Closing as nobody seems to be interested on making a driver for this.

Added the label hold over to take it into account for future reference.
