### ISSUE TITLE
Cant load webserver

### ISSUE THREAD

**Issue by prasad7676** [arendst/Sonoff-Tasmota#230]
after flash firmware successfully i cant open web page using sonoff-4339.local...or ip add.

after change little bit on code i can connect to mqtt but cant get GUI...Please help me...thanks
<img width="1336" alt="screen shot 2017-03-18 at 4 49 55 pm" src="https://cloud.githubusercontent.com/assets/12240044/24076294/0a9d195e-0bfb-11e7-8006-efd60f99bc19.png">

**Comment by arendst** [comment]
Use another browser.

**Comment by davidelang** [comment]
you would need to provide information about what happens when you try to connect to the webserver

**Comment by ionciubotaru** [comment]
try to connect from you mobile phone
be sure the ip is the correct one and use the IP to connect

**Comment by prasad7676** [comment]
Thanks evry one i try mobile browser and work there. Thank you very much
