### ISSUE TITLE
Adding MQ2-9 sensor request after testing in 5.12.0i - ready ino exists

### ISSUE THREAD

**Issue by roblad** [arendst/Sonoff-Tasmota#2316]
Hi,

I am requesting again for adding support for MQ sensors log() and pow() functions have not caused any problem for sonoff 4ch pro even. See the Stefan testing:

https://github.com/stefanbode/Sonoff-Tasmota/blob/master/sonoff/xsns_94_MQ_SENSOR.ino

https://github.com/stefanbode/Sonoff-Tasmota/wiki/MQ-Sensor-support

Some people instead of me reported no problem.

**Comment by kevinshane** [comment]
yes please! will be more useful, thanks
