### ISSUE TITLE
success!!   i Think

### ISSUE THREAD

**Issue by mentallybewildered** [arendst/Sonoff-Tasmota#2318]
I'm a neaderthal, I admit it. after nearly a full weekend committed to flashing one POW, I was about to give up, and start polishing it with a hammer. I felt overwhelmed at what I was faced with, esptools? atom? platformIO? after numerous youtube vids, I finally sat down with 2 laptops and the POW. One laptop with the software, one for instructions, and followed the pages here to flash using Visual Studio. 
I followed it word for word, but still after numerous attemptsat flashing, I was getting the same results, I could access its webpage, change settings, see things happening on mqtt.fx, but I couldn't toggle the relay from the webpage, and the status didn't show what the relay was doing (on or off). 
I realised I could alter it from the console though. 
confused and dejected, I was about to give up, maybe even come on here to ask if there was anyone who could point out the stupid mistake I seemed be be consistently making. 
I was about to go round to the shop to clear my head a bit, when I saw the ipad, and just out of curiosity, I jabbed in the ip address, waited a second, then pressed the toggle button

Oh the joy, the elation, when the little relay clicked, and the LEDs went out.

I don't know if everything is actually working as it should be, and what problems ill encounter trying to connect it to openhab/alexa etc, but I think I'm going to reduce the possibility, by taking the winblows laptop out, and running over it repeatedly with the car :-D

**Comment by ascillato** [comment]
Hi,

So, your issue is solved ? I don't understand your specific question.
