### ISSUE TITLE
Support Kelvin unit for color temperature

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#2326]
I suggest to support the unit Kelvin for colour temperature by using SetOption to specify the colour temperature of the red, green, blue, cold white and warm white strip. If the desired color temperature is between cold white and warm white use cross-fade. If the colour temperature remains under or exceeds the range off the white stripes I suggest to use [Tanner Hellands algorithm for Kelvin-to-RGB conversion](http://www.tannerhelland.com/4435/convert-temperature-rgb-algorithm-code/).

**Comment by arendst** [comment]
Well give it a try and let me know your experience using both a ws2812 led string and some pwm controlled  led.. Verify if you manage to get the same color temperature using the same kelvin value...

**Comment by renne** [comment]
On my ToDo list ...
