### ISSUE TITLE
Missing pictures in "S20 Smart Socket" Wiki Page

### ISSUE THREAD

**Issue by pReya** [arendst/Sonoff-Tasmota#2330]
Unfortunately most of the pictures from the [Wiki page about the "S20 Smart Socket"](https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-S20-Smart-Socket) are not working anymore. Seems they were deleted at the image hoster. Maybe they can be reuploaded somewhere else? Why not put them in the repo? I'd love to help, but I don't have the original pictures.

**Comment by curzon01** [comment]
try asking author [BrutalBirdie](https://github.com/BrutalBirdie) who has made the first version with pic-upload.de references, see [page history](https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-S20-Smart-Socket/_history)

**Comment by BrutalBirdie** [comment]
If I can find my S20 Switches I will take new pictures asap.

**Comment by BrutalBirdie** [comment]
@pReya we could use the pictures from the official Sonoff S20 CE-EMC Report until someone someone (me) can make pictures again.
https://www.itead.cc/wiki/images/3/38/Sonoff_S20_CE-EMC_Report.pdf Page 46

**Comment by pReya** [comment]
I'm flashing my S20 today or tomorrow. I'll take pictures along the way, so don't worry about finding yours. I just thought maybe you have the pictures still on your hard drive somewhere.

**Comment by pReya** [comment]
Sorry, I never got around to take pictures of mine. Thanks for uploading yours again.
