### ISSUE TITLE
AP mode network security key

### ISSUE THREAD

**Issue by jepean** [arendst/Sonoff-Tasmota#2338]
Hi,

I flashed Tasmota using ESPtool and hit the button to go to AP mode. But when I try to connect to the AP, I am prompted for a network security key? I have no idea what this key is. Where do I find it?

I using Windows 7, by the way.

**Comment by reloxx13** [comment]
Your wifi password...

**Comment by jepean** [comment]
Seriously? Am I that stupid? So sorry!

**Comment by reloxx13** [comment]
shit happens :D

**Comment by reloxx13** [comment]
but i cannot see "secruity key" in the english translation file, are you sure you flashed tasmota on it? sounds like it is the orginal firmware.

EN Translation:
https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/language/en-GB.h

**Comment by jepean** [comment]
I have no idea what happened, but it must have been some kind of glitch in my computer because when I tried the <Four button presses -> AP mode> today it worked fine. No password promt as I expected, and I was able to configure the Sonoff's wifi settings through the browser.

Thank you for your replies!
