### ISSUE TITLE
Support - iTead Sonoff Pow R2

### ISSUE THREAD

**Issue by mirino75** [arendst/Sonoff-Tasmota#2340]
Hi,

iTead Sonoff Pow **R2** - When will the device be supported? Not yet in the supported list ...

thx
mirino

**Comment by Merwenus** [comment]
anyone made it work?

**Comment by arendst** [comment]
Still waiting for mine.

As I said before pls try selecting module S31 as it's probably the same pin layout and it definitely uses the same energy monitoring chip (CSE7766) as the S31.

**Comment by arendst** [comment]
UPDATE:

Received mine today and as expected it works "out of the box" when configured as module S31.

Important note: The power connection of the Pow R2 is different from to previous Pow so be carful if you replace an old Pow with a R2 version:
```
- Old version: Lout-E-E-N-N-Lin
- New R2 version: Lout-E-E-Lin-N-N
```
So if you connect it wrong it will blow the fuse as Lin will connected to N ;-)

To make use as easy as possible I'll add the Sonoff Pow R2 as new module anyway.
