### ISSUE TITLE
Sonoff multi http

### ISSUE THREAD

**Issue by Bashface** [arendst/Sonoff-Tasmota#2349]
You know how you can use the URLs to controll your sonoff touch 
http://sonoff/cm?cmnd=Power%20TOGGLE
http://sonoff/cm?cmnd=Power%20On
http://sonoff/cm?cmnd=Power%20off

What if you have a sonoff touch 2 channel 
What URLs would you use to controll the second channel

**Comment by Schnullerbua** [comment]
the right command is 
http://you.sonoff.ip/cm?cmnd=power1 off for channel one and "=power2 on" or off. that's not a Issue
