### ISSUE TITLE
[WIKI] Wemos D1 Mini wiki page added

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#2350]
Hi all,

Just to inform you all, I've added [Wemos D1 Mini](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos%20D1%20Mini) to the Tasmota wiki. 

I'll update as soon as I receive other sensors to work with Wemos D1 Mini.

Cheers,
Ray

**Comment by 0n3-70uch** [comment]
Thanks Ray :-)

**Comment by RaymondMouthaan** [comment]
@kdjordjev may i suggest to open a new issue for this?
