### ISSUE TITLE
HA mqtt light throws error when receving message from sonoff

### ISSUE THREAD

**Issue by engrbm87** [arendst/Sonoff-Tasmota#2351]
Make sure these boxes are checked before submitting your issue - Thank you!

When i configure the light component to control WS2812 light connected to the Sonoff and i use "stat/sonoff/RESULT" as the topic for the state, brightness and color, i will get the below error if the TOPIC message is missing the brightness or color keys (for example if i turn off the light the message will only include {"POWER" : "OFF"}) :
`File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/light/mqtt.py", line 247, in brightness_received
    device_value = float(templates[CONF_BRIGHTNESS](payload))
ValueError: could not convert string to float: `

This will not cause a problem unless i have a switch and WS2812 connected to the same Sonoff. In this case if i try to turn on the switch, the received RESULT message will cause the above error and thus the switch state will not be updated to show that it is ON. it will physically turn ON, but it will remain OFF in HA.
A suggestion would be to make a unique RESULT topic for the light components (LIKE `RESULTL`)

- [x] What hardware you are using
  Sonoff Basic
- [ ] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

**Comment by arendst** [comment]
Stop configuring Hass yourself and use the Mqtt discovery feature.
