### ISSUE TITLE
AP mode when no wifi

### ISSUE THREAD

**Issue by akhilasuraj** [arendst/Sonoff-Tasmota#2354]
i'm using esp8266 esp 1 module. i'm so interested in tasmota firmware because, it swiches to AP mode when no wifi is detected..i can't use full tasmota in my esp 1 because it's too heavy and my esp module has only 512KB memory.. all i need is to swich to AP mode when there is no wifi ...so anyone please help....thanks

**Comment by reloxx13** [comment]
read user_config.h in sourcecode

read wiki Button Functionality

**Comment by akhilasuraj** [comment]
Thanks ... I'll look into it...thanks again...
👍
