### ISSUE TITLE
Hi! is there recommended settings?

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#2361]
for example in:
  Configure Logging  :
   Telemetry period

**Comment by Frogmore42** [comment]
That would depend on what you are trying to achieve.  You only need logging to help figure out issues, unless you are in a high security environment and need to log everything that happens for compliance reasons.  If that last part is the case, Tasmota is probably not the best option.

For telemetry period, it once again depends on what you are measuring and what you are doing with the data.  Some things change rapidly and that information is interesting.  Other things move much more slowly and every 5 min would still be not very interesting.
