### ISSUE TITLE
sonoff hostname

### ISSUE THREAD

**Issue by andyd999** [arendst/Sonoff-Tasmota#2363]
If i change the hostname to say livingroom_light cmd hostname displays correctly but i cant ping the hostname or use the hostname in chrome browser.  what am I doing wrong?

**Comment by RaymondMouthaan** [comment]
Have you tried <your_hostname>.local ?

**Comment by andyd999** [comment]
Yeah that dossnt work either Raymond but thanks

**Comment by Frogmore42** [comment]
Did it work before you changed the name?
It has never worked for me either, but I assume that is because I don't have a bonjur server.  It hasn't been enough of an issue for me to spend a lot of effort figuring out what is missing.

**Comment by andyd999** [comment]
I already have itunes installed. If i add the .local e.g. livingroom_light.local it still doesn't work

**Comment by bollitec** [comment]
only for your info regarding Apple Bonjour service: https://learn.adafruit.com/bonjour-zeroconf-networking-for-windows-and-linux/overview
... in short: Bonjour w/o install itunes 
- download apple itunes installer, 
- unzip the itunes[32|64]setup.exe, 
- look for Bonjour[32|64].msi and double click on it to install the service only

**Comment by ascillato** [comment]
Hi @andyd999 

Could you manage to solve this issue?

**Comment by andyd999** [comment]
No mate never resolved

**Comment by Frogmore42** [comment]
Do you have bonjour running?
Without that it won't work.
