### ISSUE TITLE
Sonoff RF Bridge Randomly sent learned codes every reboot

### ISSUE THREAD

**Issue by tensopiseth** [arendst/Sonoff-Tasmota#2365]
Please help 
i got problem sonoff rf bridge randomly sent out learned code..
really annoying when boot or power out..
any solution??

**Comment by Jason2866** [comment]
Anything connected on Gpios?
Bad power supply?

**Comment by tensopiseth** [comment]
hmm.. i don't do anything after flash tasmota and selected model type to sonoff bridge and reboot it sent out code from 1 to 10 ( in console )
maybe i need to type some command?

**Comment by tensopiseth** [comment]
ohh and ofor power supply it use micro usb to power i use powerbank 5v 2.1A for testing.

**Comment by tensopiseth** [comment]
Now my problem seem to be fix by up date to 5.12.0j-mod-1.18.10
thanks to @arendst

**Comment by tensopiseth** [comment]
Hmm Sth to do with MQTT
after i enable MQTT it same as before 

15:45:32 MQT: tele/sonoff433/INFO3 = {"RestartReason":"Software/System restart"}
15:45:32 MQT: stat/sonoff433/RESULT = {"Command":"Unknown"}
15:45:32 MQT: stat/sonoff433/RESULT = {"Command":"Unknown"}
15:45:32 MQT: stat/sonoff433/RESULT = {"Command":"Unknown"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey1":"Learned sent"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey3":"Default sent"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey4":"Default sent"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey8":"Default sent"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey7":"Default sent"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey5":"Default sent"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey6":"Default sent"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey9":"Default sent"}
15:45:32 MQT: stat/sonoff433/RESULT = {"RfKey10":"Default sent"}

**Comment by tensopiseth** [comment]
for some resion it has been fix on Sonoff-Tasmota 5.13.1a thanks to Theo Arends

**Comment by 1shkoda1** [comment]
Installed 9.1.0. Have the same issue
