### ISSUE TITLE
tsasmota h801 led controller, cant control within domoticz

### ISSUE THREAD

**Issue by ActionHenk666** [arendst/Sonoff-Tasmota#2366]
Hi i have a H801 led controller flashed succesfull with the latest tasmota. 

I have the sonoff webinterface in front of me and it works, but...

The only thing i can control in domoticz is turn it on and off with the domoticz RGB controller dummy device.

However i can't controll the dim level and the colors with domoticz, what am i doing wrong ? 

I already set setoption15 on.

I already have 8 x sonoff basics, 2 x th16 with temp and mosture sensors, a sonoff dual and a sonoff pow up and running in domoticz without problems, 

I can control colors and dim level within the sonoff webinterface, so it is working. 

Please help me out, greetings!

**Comment by 0n3-70uch** [comment]
Hi, there is no Domoticz RGB support at the moment... Have the same problem :).

**Comment by ActionHenk666** [comment]
Yeah i kinda found out after a lot of trying. Seems there are people can control RGB with espeasy and some scripts, but it involves 3 dimmer dummy's. One dimmer dummy a color. I'm not gonna try that. 

Let's hope support will come soon, tasmota supports it just fine, can't understand why domoticz can't control it, it seems just so easy. 

Thanks!

**Comment by stas-demydiuk** [comment]
Hi

I've created python plugin for domoticz which allows to control H801 with Tasmota firmware via MQTT
https://github.com/stas-demydiuk/domoticz-h801-tasmota-plugin

**Comment by ActionHenk666** [comment]
Very very cool!!, I am already controlling it with http commands in domoticz.


Alarm activated = red, 
alarm deactivated = green.
Cooking = White, 
hot weather outside = warm Yelow, 
Normal weather outside = yellow
Cold weather = green 
Icy weather = blue

Etcetera, so i already found a workarround tot get a lot of those units working in my home but your plugin sounds promising. Only thing i reget is that i need to install another phyton plugin :( i really like to get it as plug and play as possible.

Anyway, keep up the good work!!! And thanks for your reply, i will try this as it seems switching colors is a lot easyer!!!
