### ISSUE TITLE
Missing Dimmer quotes in JSON

### ISSUE THREAD

**Issue by ardeus-ua** [arendst/Sonoff-Tasmota#2374]
- [ ] What hardware you are using 
5.12.0i
- [ ] Provide the output of command ``status 0``
{"Status":{"Module":1,"FriendlyName":["lrled","lrled2"],"Topic":"lrled","ButtonTopic":"0","Power":2,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}

I am trying to configure Brightness value receiving by HomeAssistant for WS2812 connected to Sonoff Basic. When I send the command "color2 aa00aa" I receive the following response:
{"POWER2":"ON","Dimmer":4,"Color":"0A000A","HSBColor":"300,100,4","Channel":[4,0,4]}
where Dimmer value cannot be recognized since it's unquoted.
Is this possible to include Dimmer value into quotes or is there any other solution for this?

**Comment by arendst** [comment]
See https://www.json.org/

As dimmer is a value and not a string it is not quoted
