### ISSUE TITLE
ESP wont start with 8ch relay connected

### ISSUE THREAD

**Issue by xcruell** [arendst/Sonoff-Tasmota#2380]
Hello!
I have a strange problem. When i apply power to the d1 mini with the [8ch relay](https://www.amazon.com/Eight-Relay-Module-Optocoupler-Arduino/dp/B079DHY22L/ref=sr_1_4?ie=UTF8&qid=1523040710&sr=8-4&keywords=8ch+relay) connected, it just wont start. When i disconnect VCC from the 8ch relay, it startes flawlessly. no problems either when connecting after it started. 
Thats the serial output i get, when i start the d1 mini with vcc connected: 
> rd␀l��|␀�$�|␃␌␄␌�␌$�␄c|��␃�␛�{�#�␄c��o'�do'���␌#�#�lsds$�␒␛g��<�␃��n<␀␄go<��`␃

I hope someone can help me..

Make sure these boxes are checked before submitting your issue - Thank you!

- [x] What hardware you are using
 Wemos D1 Mini
- [ ] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

**Comment by Frogmore42** [comment]
How are you powering the D1 Mini?  Many computer USB ports can't supply enough power.  Try using a powered USB hub.

**Comment by Frogmore42** [comment]
If you are not changing the code, you should probably use one of the pre-built binaries.

**Comment by xcruell** [comment]
Im powering it over a USB port of my computer. But i dont see what difference that would make. Since it works over the USB port. It just wont start with the powered 8ch relay.

**Comment by Frogmore42** [comment]
Do you have the relay connected to GPIO 0?
The relay board might be holding down the lines, which will cause the esp8266 to go into download mode.

**Comment by xcruell** [comment]
Yeah thats what i thought too, but nothing is connected to D3 (GPIO 0 on d1 mini) nor D0.
It still wont boot. Only when i cut the VCC and connect it afterwards.

**Comment by xcruell** [comment]
OH! I got it.. kinda.
The GPIO 0 thing got me thinking, so i tried each pin after another. And i found out that it works when nothing is connected to GPIO 0 AND GPIO 15.
But that only gives me 6 out of 8 Relays. Is there a way to workaround that?

thanks so far!

**Comment by Dickesplumpel** [comment]
Look here:
https://www.forward.com.au/pfod/ESP8266/GPIOpins/index.html

**Comment by xcruell** [comment]
Thank you! i just found this site seconds before i saw your comment ;)

**Comment by xcruell** [comment]
Works flawlessly now.
Thank you guys very much for your help and effort!
