### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#2381]
I Have a Sonoff 4CH and would like to know if it is possible to increase the number of Timers available from 16 to maybe 32?

**Comment by andyd999** [comment]
The timer would need to be implemented in the managing software such as home assistant. Tasmota doesn't have any timers it's just an mqtt facilitator

**Comment by curzon01** [comment]
@andyd999 - not true, since 5.12.0i: [Timers](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#timers)

**Comment by Lawrencezarb** [comment]
Yes, the Timers are built into Tasmota since 5.12.0i. I just need more that 16 for the 4CH unit. The real issue is that for an on-off time setting, it requires the use of 2 of the times, which limits to 8 on-off sequences.

**Comment by curzon01** [comment]
@Lawrencezarb - it's not user definable but you can try enhance MAX_TIMERS if you are familary with C code, But be aware your version then is incompatible with Thoes and resetting settings after doing that is also a good idea. If you don't understand how to handle all of that, I suggest to leave it as is.

**Comment by Lawrencezarb** [comment]
I'm not familiar with C code, was hoping that Theo could make a release with the increased number of timers....

**Comment by Lawrencezarb** [comment]
Well thanks curzon01, it worked, I increased the MAX_TIMERS from 16 to 32 in sonoff.h and I now have 32 timers.
