### ISSUE TITLE
34 MagicHome module bug

### ISSUE THREAD

**Issue by vMeph** [arendst/Sonoff-Tasmota#2382]
using tasmona version 5.12.0i

i got a Homemagic RGB Wifi Module
https://pt.aliexpress.com/item/DC-5V-12V-24V-Mini-Bluetooth-WiFi-LED-RGB-RGBW-Controller-iOS-Android-APP-24Key-IR/32815415160.html
with the 34 MagicHome module type choice, the blue light doesnt work, for moments i tought that the module was dead on the blue pin 
when switching to 37 Arilux LC01 module type choice the module works perfect

**Comment by FoxRomeo** [comment]
Try out this:
https://github.com/arendst/Sonoff-Tasmota/issues/1810#issuecomment-366464127

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.
