### ISSUE TITLE
What is the change of the Sonoff POW2 and is it supported by Tasmota?

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#2388]
There is a new version available, that says it is more accurate in measuring current. Any info here from the makers with this device. The price is currently double compared to the POW. But this may change quickly.

Are there any changes required in the firmware?

**Comment by Leseratte10** [comment]
The "Dual R2" is supported by Tasmota (just select it in the module list). Or is this a third new version?

**Comment by arendst** [comment]
#2340
