### ISSUE TITLE
remote configuration backup

### ISSUE THREAD

**Issue by or78rXxZ** [arendst/Sonoff-Tasmota#2394]
Make sure these boxes are checked before submitting your issue - Thank you!

- [ ] What hardware you are using
- [ ] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

This is a generic request for Tasmota. Is it possible for a server to pull the configuration from a device that has Tasmota installed? I have not been able to find this. If not could this enhancement be added?

**Comment by curzon01** [comment]
Possible ideas:
# use saved (Backup Config) configuration file and post it using curl
# if already ble to use MQTT wirh your device use MQTT command Backlog and set each neccessary setting command by command

your question is too common, there are a lot of possibilities depending on condition situation you have

**Comment by curzon01** [comment]
curl and POST request to Url for Web GUI “Backup Configuratuon“

**Comment by or78rXxZ** [comment]
wget sonoff_ip_address/dl
This should be documented
Thanks

**Comment by arendst** [comment]
Nice to know ;-)
