### ISSUE TITLE
"Fri" should be "Fre" in de-DE.h

### ISSUE THREAD

**Issue by esp32x** [arendst/Sonoff-Tasmota#2403]
"**Fri**" should be "**Fre**" in de-DE.h

#define D_DAY3LIST "SonMonDieMitDonFreSam"

**Comment by arendst** [comment]
How about So,Mo,Di,Mi,Do,Fr,Sa like I did in dutch, by entering a space for the third character, instead of the three letter words?

**Comment by curzon01** [comment]
Theo, yes same as for dutch - nobody use a 3 char shortcut e. g. "Fre" for friday in Germany.

**Comment by reloxx13** [comment]
blank space cheater 8D
