### ISSUE TITLE
I2C connection to Sonoff Basic

### ISSUE THREAD

**Issue by Hugo477** [arendst/Sonoff-Tasmota#2408]
I would like to connect BMP280 to Sonoff Basic and want to avoid additional soldering to GPIO4..
Connected SCL to GPIO1, SDA to GPIO3, VCC and GND.
Disabled SerialLog/Enabled SerialLog.
But does not work in both cases.
Am I mistaken somewhere?

**Comment by arendst** [comment]
Try to swap SCL/SDA. I did manage to get a BH1750 running this way.

**Comment by Hugo477** [comment]
Great!  SCL to GPIO3, SDA to GPIO1 and SerialLog OFF works. Thanks.

**Comment by aenertia** [comment]
What about GPIO13 (the Status LED?) I feel like this should be a toggle drop down in default build in Tasmota. Any reason why it isn't?

I would rather sacrifice the LED GPIO than the Serial.
