### ISSUE TITLE
CZE translation correction

### ISSUE THREAD

**Issue by Hugo477** [arendst/Sonoff-Tasmota#2410]
Please change CZE version in the following way:

Parametry modulu = Nastavení modulu

Configure timer = Nastavení časovače
Timer parameters = Nastavení časovače
Pon = Po, Úte = Út, Stř = St, Čtv = Čt, Pát = Pá, Sob = So, Ned = Ne
Output = Výstup, Power = Napájení
Vypnutý = Vyp, Sepnutý = Zap, Přepni = Přep, Blikání coud stay
Arm = Zajistit, Repeat = Opakovat
Time = Čas

Jiná nastavení = Další nastavení, Jiné parametry  = Další nastavení

**Comment by arendst** [comment]
Pls provide changes in language file as I won't be searching the differences in czech. You can insert it in here between three "left quotes" (the left most top key below Esc at your keyboard).

**Comment by Hugo477** [comment]
OK. I will play with the whole CZ language file. 
BTW is there any limitation regarding number of characters? I am aware that less is better.

**Comment by arendst** [comment]
Your awareness is good.

What also matters is display on screen; too long strings will make the web gui look awful. I suggest you do test the web gui regarding strings being too long.

**Comment by Hugo477** [comment]
Done.
