### ISSUE TITLE
devices not responding hue emulation alexa

### ISSUE THREAD

**Issue by nikki-reprap** [arendst/Sonoff-Tasmota#2414]
HI i have installed the latest build on a nodemcu and setup 4 relays I have enabled hue emulation and alexa finds all 4 devices but when i try to switch them all i get is  "device not responding"

Thanks Nikki

**Comment by reloxx13** [comment]
alexa bug/library workaround:
https://github.com/arendst/Sonoff-Tasmota/issues/1639#issuecomment-360218536

**Comment by nikki-reprap** [comment]
Thank You. The work around works perfectly

Thanks Nikki
