### ISSUE TITLE
Sonoff Dual R2 Blue LED flashes after flashing

### ISSUE THREAD

**Issue by scouseboy999** [arendst/Sonoff-Tasmota#2437]
Make sure these boxes are checked before submitting your issue - Thank you!

Sonoff Dual R2
- [ ] Provide the output of command ``status 0`` unable to supply this information

I am sorry if the information here is not in the correct format, this is my first time.

I have flashed a Sonoff dual R2 with the Tasmota master branch.
Following the flashing guide, I used platformIO to modify my parameters, build and upload the firmware to the Dual.
PlatformIO informs me that the upload was a success.  After flash, I removed the power and the link between GPIO0, the reapplied the power.  I do not see the device on my network and the blue led flashes many times, goes solid on and the flashes twice - this repeats as long as the power is connected.

Grateful for any advice as to what may be causing this.  I have tried a re-flash, and still have the same issue.  I also have the same issue on another dual that I have flashed.

**Comment by Geitde** [comment]
I had the same issue. The Accesspoint fields of your settings are "", which means it tries to connect to an accesspoint with no name and no password. 

I tried to build the latest developer version myself. Just checking out and compiling does not work.

In my opinion it is a bug that the default AP can even be "". There always should be some some default, if the source is unchanged and if the settings stored are somehow broken they should fall back to indebuurt1 stuff. Somehow they did not.

When hooking up some serial monitor I got the "Connecting to AP1" messages without a proper AP name following, so it was clear what is going wrong.

**Comment by reloxx13** [comment]
If WIFI connection fails, its in WPS Mode.

Read Wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage

**Comment by scouseboy999** [comment]
Thanks for the information.  My knowledge continues to grow.  I could not
find any information regards the blue flashing led (indicating WPS mode),
however, using the serial monitor in PlatformIO it become very obvious what
the problem was. Thanks to Geitde for the pointer on this.

**Comment by Geitde** [comment]
@reloxx13 

Well, not everyone has WPS at its hand. My router is out of distance and not even in the same building. I for sure cannot move the wall over to the router or the router closer to the wall. For me it is even hard to deal with flashing it, while it is inside the wall near the ceiling. 

Having WPS mode as default fallback is kind of odd in this case. Switching to AP Mode would be much more handy these days, as everyone has a tablet or handy to connect and config the tasmota device on location. 

In fact "" should never even be tried as AP name. No matter what happend and what the reason for the empty name is. It should always fall back to some default that cannot be changed in config or config.h, even if it is just using existing strings like "sonoff" or "tasmota" to search for. Those ones you can configure your AP to, without having to open walls. 

No clue what exactly happend in my case. I build minimal and standard version, flashed the minimal and used that without an issue to update to 5..12.0k, which kicked my ass after setting up timers and reboot

Anyway, I am kind of stuck. 5.12.0 works fine, but has no timers, which I need and 5.12.0k has timers, but fails badly when it comes to Hue emulation, which I also need.

**Comment by reloxx13** [comment]
Here is the workaround for HUE Emulation:
https://github.com/arendst/Sonoff-Tasmota/issues/1639#issuecomment-360218536


Someone prefers WPS, another one not.

Example:
Imagine your 20+ devices are hidden in the wall, behind lamps etc, and somehow they reset and your wifi config is gone. Starting WPS Mode at your router would be easier to rejoin them to the Wifi as connecting each device manual.

But yep, i would prefer AP Mode, too.

**Comment by Geitde** [comment]
I have just 12 devices right now and since the host names are pointing out their location maintaining is quite easy.

In your scenario i would simply plug in my Tasmota-AP. In fact I have some old insecure router here, I only use to configure tasmota devices searching for indebuurt1. I plug it in and all new devices appear via DHCP in my network and the router shows the ip in its log. That is why this empty AP name is so annoying.

Since the Sonoffs usually not only loose network settings I would have to configure them anyway to their original ip, host/friendly names and switch behaviour and so on  The simplest way for me to do this is to load the old config for the specific location from a backup file.

SonWeb is not much help here, too, Yes, it is helpful to quickly detect the thingies ip and enter the web interface, Thats all for the installation procedure involving SonWeb.

**Comment by radebebek** [comment]
I have the same mistake, someone found a solution? @Geitde  @scouseboy999 @reloxx13
