### ISSUE TITLE
Add Random Function for the Timer

### ISSUE THREAD

**Issue by FabianHM** [arendst/Sonoff-Tasmota#2447]
Hello,
Is it possible for the Timer to include a random Function as a presence simulation?

The calling and ending of the random function should be done via the normal commands.

Thanks and greetings
Fabian

**Comment by species5618** [comment]
great idea, for security purposes, 
keeps people watching lights on and off , an thinking its a timer
some commercial devices i have seen offer +/- **X** minutes

**Comment by renne** [comment]
Homematic e.g. offers a random offset for timers.

**Comment by Geitde** [comment]
yeah, such option would be great and just needs one byte per timer where the value would be stored.

The offset should go in both directions. So a value of 15 would result in random timers between -15 and +15 minutes.

**Comment by renne** [comment]
`random time = (setpoint - offset) + (random number % (offset * 2))`

**Comment by FabianHM** [comment]
Thank you Theo for the realization of my idea :-)
Unfortunately, I do not understand without explanation the function of the Random Timer. The following entry did not lead to success. My goal is that at sunset until sunrise, the random circuit takes place in selectable intervals.

![zeitplan](https://user-images.githubusercontent.com/26110738/39014894-e7dfa602-441b-11e8-8d25-f9d713442cc7.JPG)

**Comment by arendst** [comment]
The general feeling about the random functionality is that it takes place only once around the set time at + or - max 15 minutes. This allows for a random switch to keep the burglars out (they think).

You have to fix your goal using rules and rule#timers.

**Comment by localhost61** [comment]
@arendst , in the Timer Json, the (undocumented) "Window" parameter is not yet parsed. So one cannot change the random field of Timers from the CLI.
`15:20:00 CMD: timer1`
`15:20:00 RSL: RESULT = {"Timer1":{"Arm":1,"Mode":0,"Time":"15:10","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":3}}`
`15:20:15 CMD: timer1 {"Arm":1,"Mode":0,"Time":"15:10","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":3}`
`15:20:15 RSL: RESULT = {"Timer1":"Invalid JSON"}`
`15:20:25 CMD: timer1 {"Arm":1,"Mode":0,"Time":"15:23","Days":"1111111","Repeat":0,"Output":1,"Action":3}`
`15:20:25 RSL: RESULT = {"Timer1":{"Arm":1,"Mode":0,"Time":"15:23","Window":0,"Days":"1111111","Repeat":1,"Output":1,"Action":3}}`

**Comment by localhost61** [comment]
Ok! I thought is was not yet implemented. The issue was not were I thought :-).
