### ISSUE TITLE
Error during compile "cannot find -lmesh"

### ISSUE THREAD

**Issue by dweston** [arendst/Sonoff-Tasmota#2449]
- [ x] What hardware you are using
MacOS 10.10.5
Arduino IDE 1.8.5 installed as portable config using guidance here:
    http://forum.arduino.cc/index.php?topic=539551.msg3678998#msg3678998
ESP8266 Board version 2.4.1
Tasmota install followed as per:
    https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE

Arduino IDE configuration:
Arduino: 1.8.5 (Mac OS X), Board: "Generic ESP8266 Module, Serial, 80 MHz, nodemcu, 26 MHz, 40MHz, DOUT, 1M (no SPIFFS), v2 Lower Memory, Disabled, None, 115200"

When first set-up was attempted the 'v1.4 Prebuilt' option was not available in the "IwIP Variant:" drop down menu.
The only options available were:
v2 Lower Memory
v2 Higher Bandwidth
v1.4 Higher Bandwidth
v1.4 Compile from source

The "v2 Lower Bandwidth" LwIP variant option was selected as per previous advice (issue #2448). However compiling 'sonoff.ino'  failed with the message: 'cannot find -lmesh'. 

Checking the 'IwIP Variant:' options menu again after the first compile attempt revealed that the 'IwIP variant:' menu items had entirely changed.

Following the first compile attempt the options had become:
"v2 Prebuilt (MSS=536)
v2 Prebuilt (MSS=1460, unstable)
v1.4 Prebuilt
v1.4 Compile from source"

Same 'cannot find -lmesh' compile error arises.

On the second 
- [  ] Provide the output of command ``status 0``
Did not reach that stage.
- [ cannot find -lmesh] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

**Comment by arendst** [comment]
#2448
