### ISSUE TITLE
Sonoff Dual R2 MQTT only one cmnd POWER

### ISSUE THREAD

**Issue by BigWumpus** [arendst/Sonoff-Tasmota#2458]
Hallo,
habe heute meinen Sonoff DUAL R2 bekommen und TASMOTA 5.12.00 mit ATOM.IO geflasht.
Es gibt in den Einstellungen zwei Felder für "friendly name" mit "Sonoff" und "Sonoff2" vorbesetzt. Wozu?
Schlimmer ist aber, daß im ioBroker im MQTT-Adapter nur ein cmnd-Datenpunkt "POWER" auftaucht, der nur das erste Relais schaltet. im stat-Zweig gibt es erwartungsgemäß POWER1 und POWER2.
Ich habe/mußte die Ansteuerung jetzt auf http-Requests umbauen.

**Comment by Leseratte10** [comment]
Friendly name ist dafür da, wenn du den Sonoff mit Alexa ansteuerst, um den beiden angeschlossenen Geräten einen Namen geben zu können. 

Tauchen die POWER-Einträge im iobroker auf, wenn du einfach mal einen MQTT-Befehl dahin schickst?

**Comment by BigWumpus** [comment]
Nein, die Einträge erscheinen auch nach der Benutzung (über Knöpfe oder URL-Requests) nicht auf.

**Comment by Leseratte10** [comment]
Nicht über Knöpfe oder URL. Über MQTT. Unter Linux z. b. mit `mosquitto_pub -t "cmnd/sonoff/POWER2" -u DVES_USER -P DVES_PASS -m true -h 127.0.0.1 -i client -p 1883`

(Username, Passwort und IP evtl. anpassen)
Obwohl das prinzipiell auch ohne funktionieren müsste ...

**Comment by BigWumpus** [comment]
Ich habe im ioBroker die beiden topics für cmnd/.../POWER1 und 2 per Hand angelegt, nach dem existierenden Eintrag ...POWER. Ich kann sie mit ON und OFF beschreiben und die bereits vorhandenen stat-Topics gegen entsprechende Rückmeldung. Der Schalter selbst liegt zu Hause auf dem Schreibtisch.

**Comment by BigWumpus** [comment]
Ach ja, die stat/.../POWER1 und ...POWER2 sind jetzt ohne Updates und werden wohl nicht mehr gemeldet.
