### ISSUE TITLE
how to change core 2.4.0?

### ISSUE THREAD

**Issue by vMeph** [arendst/Sonoff-Tasmota#2469]
how to change core from 2.4.0 to 2.3 using atom platformio

**Comment by Frogmore42** [comment]
find the file platformio.ini
Find this line
`;platform = espressif8266@1.5.0  ; v2.3.0`
remove the semi-colon
remove the line (or comment it out) that specifies the platform without the version

**Comment by curzon01** [comment]
[Theo's Tasmota Tips](https://github.com/arendst/Sonoff-Tasmota/wiki/Theo's-Tasmota-Tips#20180103---tasmota-is-ready-for-esp8266arduino-version-240)

**Comment by vMeph** [comment]
thanks alot
