### ISSUE TITLE
Where is GPIO2 on sonoff 4ch PRO

### ISSUE THREAD

**Issue by margusveer** [arendst/Sonoff-Tasmota#2477]
I wan't to testing to add DHT22 to 4ch pro to get temp and humidity, but I can't find any tips about GPIO -layout on 4ch PRO

**Comment by curzon01** [comment]
See Wiki [Sonoff 4CH Pro](https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-4CH-and-4CH-Pro#sonoff-4ch-pro) - the picture for 4CH Pro board shows the "ESP Program Header on the left side. **GPIO2** is pin **SDA**

**Comment by lobocobra** [comment]
And then close the issue please?

**Comment by margusveer** [comment]
Thanx @curzon01
