### ISSUE TITLE
Temperature and Humidity Sensors

### ISSUE THREAD

**Issue by raisude** [arendst/Sonoff-Tasmota#248]
Just one question: when attaching a  DHT22 Sensor to the Sonoff Basic should there be an Output of the values on the startpage of the Webserver? https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-Configuration#i2c-sensor Shows something like that. But I have configured one DHT22 but I don`t have such Output.

Regards Rainer

**Comment by davidelang** [comment]
Yes, once you have set the gpio setting to say that a specific gpio is connected 
to a sensor, you should start seeing that sensor data in the logs (and on the 
main webserver page). note that the logs are set by default to be reported every 
5 min.

You may have to restart the device after you have configured it.

**Comment by decologne** [comment]
To get more information of the working of DHT, connect your device by webserver, set Logging webserver in mode More debug, start Webserver Console and restart your device. Now you get more detail info.

**Comment by lkhaskjdhlkashd** [comment]
I have a similar problem with a "dallas 18B20" temp sensor, i enabled the option USE_DS18x20 in user_config.h

Connected the sensor directly to the Sonoff Basic on pin 1-4-5
1 - VCC
4 - GND
5 - DATA

Is there something i forgot to do?

I noticed that there is an internal temperature sensor... how can i enable that?

**Comment by raisude** [comment]
Are you sure you`re using the right pins. In my case the problem was that I inverted VCC and ground. This because of there are some wrong pictures in the web. And pin 1 VCC is the only one not round but square coded on the board.

**Comment by lkhaskjdhlkashd** [comment]
Pretty sure --> [https://i.imgur.com/RRA6LOw.jpg](url)

**Comment by raisude** [comment]
and in configure menu you`re using gpio14 Type4 18B20. And the other gpios are none or at least no sensor type of the same group as the 18B20?

**Comment by lkhaskjdhlkashd** [comment]
I cant select Type4 18B20,

See the link for an image --> [https://i.imgur.com/wItmIpL.png](url)

**Comment by davidelang** [comment]
what version are you running?

on current versions you need to configure the gpio that you have the sensor 
connected to to the appropriate sensor type

I'm not sure what internal temp sensor you are talking about.

**Comment by lkhaskjdhlkashd** [comment]
It works, i forgot the resistor,,, :-|

**Comment by davidelang** [comment]
closing this issue as it's now working
