### ISSUE TITLE
4 channel relay works opposite

### ISSUE THREAD

**Issue by ashishcchauhan** [arendst/Sonoff-Tasmota#2489]
Make sure these boxes are checked before submitting your issue - Thank you!

- [x] What hardware you are using
- [ ] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

**Comment by ashishcchauhan** [comment]
I Flash tasmota on NodMCU and controlling 4 relay board, Its works but there is little problem.
When I trigger, It works opposite, means when I turning ON my relay goes OFF and When I  turning OFF it goes ON.
So Please help me to solve this problem.

My tasmota settings are below.
Module type is 18.Generic
D6 GPIO12 Relay1      -   Relay 01 
D7 GPIO13 Led1i       -   Relay 02
D5 GPIO14 Sensor     -   Relay 03
D8 GPIO15                  -   Relay 04
It will be very helpful to me if you can solve this problem.
Sorry  for my English.
Thanks,﻿

**Comment by Jason2866** [comment]
This is easy to solve. Just use the inverted relay option. Example
Relay1i

**Comment by ashishcchauhan** [comment]
hey jason,
 thank for your reply but i am newbie in this project so I not understanding what you suggested can you explain  little more.

Thanks.

**Comment by Jason2866** [comment]
Open the web interface of your NodeMCU  (http://....)
Goto configuration -> configuration module ->  choose the Gpio pin with the wrong on off behaviour 
and change it from Relay1 to Relay1i.
Save this configuration  (blue button, bottom of the page)
The i in Relay1i stands for inverted. So the relay acts you want to

**Comment by ashishcchauhan** [comment]
Thank you sooooo much jason....its don....thanks again....

**Comment by issa13** [comment]
But how can I open the Web page of my NodeMCU??
