### ISSUE TITLE
Configuring nodemcu led-switch-relay

### ISSUE THREAD

**Issue by stephanfx** [arendst/Sonoff-Tasmota#2500]
![untitled sketch_bb](https://user-images.githubusercontent.com/648346/39045447-40c6c95e-4493-11e8-8fd7-03840b88048f.png)

I have the above circuit setup with the nodemcu. I have it where the leds lights up when the relay is switched on, the problem I am experiencing is that the Led1 in the drop down lights up no matter what relay is switched to on with the button. Is it possible to set that Led1 switches on when relay 1 is switched on, Led2 is switched on when relay2 is switched on.

Any advise would be appreciated.

**Comment by Jason2866** [comment]
What i dont understand, why not connecting the LEDs on the relay GPIO?

**Comment by stephanfx** [comment]
The relay board is this one [https://www.sunfounder.com/4-channel-5v-relay-shield-module.html](https://www.sunfounder.com/4-channel-5v-relay-shield-module.html). I can't see gpios, also, im a noob 😀
