### ISSUE TITLE
SONOFF POW - Add reactive, active, apparent power etc. - like in espurna software

### ISSUE THREAD

**Issue by PitPaul** [arendst/Sonoff-Tasmota#251]

**Comment by arendst** [comment]
Here are the results using XosePerez calculations:

- His Active Power is the result shown as Power
- His Apparent Power is the multiplication of Voltage and Current
- His Reactive Power is either 0 if Power Factor = 1 or the Square root of Square Apparent - Square Active

So the results are there, you just have to calculate it yourself :-)

**Comment by PitPaul** [comment]
Ok, so it is simple electrotechnic formula - thanx

**Comment by khcnz** [comment]
Hi @PitPaul perhaps you could detail on the wiki for others in the future? https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Pow

**Comment by andrethomas** [comment]
@khcnz I think for people who are confused there is always this https://en.wikipedia.org/wiki/AC_power
