### ISSUE TITLE
[update] Wemos Wiki with HC-SR04 Ultrasonic Sensor

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#2511]
Tasmota 5.12.0m supports the HC-SR04 Ultrasonic Sensor, thanks to @nferreyra and @arendst 

The [Wemos Wikipage](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos%20D1%20Mini) has been updated accordingly.

**Comment by FabianHM** [comment]
@RaymondMouthaan: 
I think the Wemos Wiki is a great idea!
I would like to contribute something, but I dont't know how to adjust the Postings in guthub.
Here are the screenshots of my Sensors MHZ-19b for CO2:
![wemos feinstaub1](https://user-images.githubusercontent.com/26110738/39083903-d305ca16-456c-11e8-8d2e-72cf7d6f8a89.JPG)
![wemos feinstaub2](https://user-images.githubusercontent.com/26110738/39083904-d6661170-456c-11e8-8f12-e2c7a6f8d2e2.JPG)
and the SDS0X1 fine dust sensor:
![wemos co2](https://user-images.githubusercontent.com/26110738/39083906-e152b732-456c-11e8-8fa9-bcaec773e18b.JPG)
![wemos co2 config](https://user-images.githubusercontent.com/26110738/39083907-e3fe5cc0-456c-11e8-8fa0-48835619e6f9.JPG)

I hope can provide this in next time in the WeMos Wiki.
Greetings Fabian

**Comment by RaymondMouthaan** [comment]
@FabianHM , thanks hope it helps others 😌.

Could you provide the english versions of your screenshots , then ill make sure the wiki gets updated accordingly.

**Comment by tassheloff** [comment]
I cant find it... my sensors numbers arrive to 65 max (PSM5003). How i can enable  HC-SR04?

**Comment by RaymondMouthaan** [comment]
@tassheloff thats most probably because you haven't flashed your wemos with Sonoff-Tasmota 5.12.0m ?

**Comment by tassheloff** [comment]
mmm i read 5.12.0. where i grab 5.12.0m?

**Comment by RaymondMouthaan** [comment]
@tassheloff you can get it from this GitHub and compile it yourself .. the tasmota wiki has the steps documented how to ...

**Comment by tassheloff** [comment]
ok found under development right?

**Comment by RaymondMouthaan** [comment]
You got that right ;)

**Comment by tassheloff** [comment]
Really thanks :). i'm trying :)

**Comment by roger443** [comment]
This is great. Got it up and running in no time and it's given me yet another way of working out the status of the garage roller door.  A question though ... is there an MQTT cmnd to query  the current distance or do I just do it through watching SENSOR telemetry?

**Comment by RaymondMouthaan** [comment]
I think there is no mqtt command to instantly get the sensor data. As you suggested you can use TelePeriod to have the sensor published to mqtt frequently.
I've you need the sensor data instantly, i suggest you to use STATUS 10 via web (rest):

```
http://<ip-address>/cm?cmnd=Status%2010
```

This returns a json like:
```
{
  "StatusSNS": {
    "Time": "2018-04-25T09:45:05",
    "BME280": {
      "Temperature": 25.9,
      "Humidity": 40.5,
      "Pressure": 1009.8
    },
    "TempUnit": "C"
  }
}
```

Maybe there is a better way, but this how i currently use it.

**Comment by arendst** [comment]
Well if there is a rest then there is a MQTT too as they all use the same internals:

**Comment by RaymondMouthaan** [comment]
Yes indeed, just looked into it 

Just publish 10 to cmnd/wemos-8/STATUS which results:

```
10:09:03 MQT: stat/wemos-8/STATUS10 = {"StatusSNS":{"Time":"2018-04-25T10:09:03","BME280":{"Temperature":26.9,"Humidity":38.1,"Pressure":1010.0},"TempUnit":"C"}}
```

**Comment by roger443** [comment]
Thanks to both of you Raymond & Theo.  MQTT Status 10 works, giving me on-demand updates.  (I didn't try the rest).

**Comment by FabianHM** [comment]
@RaymondMouthaan 
Hi Ray, 
Actually, I already wanted to send you screenshots to other sensors. Unfortunately, I can not compile the current version of Tasmota for Wemos. The settings have changed, can you tell me what needs to be set now?
Greetings Fabian

**Comment by RaymondMouthaan** [comment]
@FabianHM 

I've been flashing my Wemos devices for several weeks now with these settings (suggested by Theo) without any issues:
```
[env:wemos-d1-mini]
platform = espressif8266
framework = arduino
board = esp01_1m
board_flash_mode = dout
build_flags = -Wl,-Tesp8266.flash.1m0.ld -DMQTT_MAX_PACKET_SIZE=1000 -DUSE_CONFIG_OVERRIDE
lib_deps = PubSubClient, NeoPixelBus, IRremoteESP8266, ArduinoJSON
extra_scripts = pio/strip-floats.py

; *** Serial Monitor options
monitor_baud = 115200

; *** Upload Serial reset method for Wemos and NodeMCU
upload_resetmethod = nodemcu
upload_speed = 115200
;upload_port = COM6

; *** Upload file to OTA server using SCP
;upload_port = user@host:/path
;extra_scripts = pio/strip-floats.py, pio/sftp-uploader.py

; *** Upload file to OTA server using HTTP
;upload_port = domus1:80/api/upload-arduino.php
;extra_scripts = pio/strip-floats.py, pio/http-uploader.py
```
