### ISSUE TITLE
external switches sonoff ch4 r2

### ISSUE THREAD

**Issue by xunil79** [arendst/Sonoff-Tasmota#2512]
opening the plastic shell I see the pins for the UART but no others pins for GPIO. I need to use GPIO for some switches. Is there any way to use external switches?

**Comment by Leseratte10** [comment]
You could use RX and TX (GPIO 3 and GPIO 1) as switches in Tasmota, if you disable serial logging.

**Comment by xunil79** [comment]
only 2 switches?

**Comment by Frogmore42** [comment]
There are 4 switches on the device, you could extend the wires and put switches on them, as long as you don't need to use the ones on the device.

It looks like there are 3 user gpios on the pro.  If you need more, get another esp8266 based device and you can have more.

**Comment by Leseratte10** [comment]
If you solder directly to the switches in the device, these only work for momentary push buttons, same as the ones on the device. If you need the more specific SwitchMode settings to work, you only have two (without soldering) or three (with soldering).
