### ISSUE TITLE
S31 Wrong Energy Reporting

### ISSUE THREAD

**Issue by chvicky** [arendst/Sonoff-Tasmota#2513]
HI There,

i have recently flash S31 firmware and notice its reporting wrong energy usage

before flashing its shows 930W load and after flash its start showing 1178W load
there is more then 200W Difference

i have check with other energy monitor they shows corrent 928W to 935W but its shows Wrong

please check and solve issue or tell me how i can solve problem

**Comment by arendst** [comment]
Calibrate your s31 as documented in the wiki for a sonoff pow.

**Comment by chvicky** [comment]
Thanks Buddy
