### ISSUE TITLE
[update] Wemos Wiki with BME280 Temperature, Humidity and Pressure Sensor

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#2523]
Hai all,

Just received my BME280 sensor and updated [Tasmota - Wemos wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos%20D1%20Mini) accordingly. 

Greetz,
Ray

**Comment by ascillato** [comment]
:+1:
