### ISSUE TITLE
how to retrieve config without webserver

### ISSUE THREAD

**Issue by or78rXxZ** [arendst/Sonoff-Tasmota#2530]
Make sure these boxes are checked before submitting your issue - Thank you!

- [ ] What hardware you are using
- [ ] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

In the webserver using Configuration->Backup Configuration you can save the device config. Without a webserver how do I do this?

**Comment by arendst** [comment]
You can't.

There was a command cfgdump but that provided the config in text mode without the possibility to upload.

**Comment by or78rXxZ** [comment]
Is cfgdump still available?

**Comment by arendst** [comment]
Up until 5.12.0l.

After that it's gone, over, finito, foetsie.

**Comment by or78rXxZ** [comment]
I was a Unix system administrator for 23 years. I have cold sweats if I can't backup something :)
