### ISSUE TITLE
Installing a Pzem004t current with Tasmota and Nodemuc

### ISSUE THREAD

**Issue by PETEIOT** [arendst/Sonoff-Tasmota#2532]
Ok I Have tried a few different configurations to get the PZEM004T sensor to work on a Nodemcu but I can’t get it to give me any readings. I’m hooking up the (PZEMTx to D7) and the (PZENRX to D8) Using the generic board in the most recent Tasmota, can somebody please tell me what the best way to hook this up is. Thanks!

**Comment by curzon01** [comment]
swap Tx/Rx lines for test
