### ISSUE TITLE
Flashing tasmota on wemos d1 mini with esptool

### ISSUE THREAD

**Issue by blynk7843** [arendst/Sonoff-Tasmota#2534]
Hi!
I flashed my wemos d1 mini with esptool, but something went wrong (I did’t received any error message, but have no access to WiFi and pressing the button on the wemos doesn’t give me any access to the it).
That said, I am assuming the command I gave was wrong. Which is the right one?
(Wemos d1 mini has 4MB memory)
Thanks

**Comment by curzon01** [comment]
reconnect your wemos to pc, start a serial terminal program for the wemos serial inerface with 115200 baud and see what's happend on screen.

If Tasmota is up and serial log not disabled (this is the default), you will see some Tasmota boot message `00:00:00 Project sonoff...`

The right one for flashing depends on what program you are using - there is not enough info to help

**Comment by blynk7843** [comment]
@curzon01 I am flashing sonoff.bin 5.12.0 with esptool.py 2.3.1
serial monitor tells me that nothing has been installed 
Here is what I did:
Mac-mini-di-Mac:~ macmini$ ls /dev/cu.*
/dev/cu.Bluetooth-Incoming-Port	/dev/cu.wchusbserial1460
Mac-mini-di-Mac:~ macmini$ esptool.py --port /dev/cu.wchusbserial1460 erase_flash
esptool.py v2.3.1
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 6.9s
Hard resetting via RTS pin...
Mac-mini-di-Mac:~ macmini$ esptool.py --port /dev/cu.wchusbserial1460 --baud 115200 write_flash --flash_size=detect -fm dout 0x0 ~/Downloads/sonoff.bin
esptool.py v2.3.1
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0340
Compressed 496960 bytes to 342591...
Wrote 496960 bytes (342591 compressed) at 0x00000000 in 30.6 seconds (effective 129.8 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
Mac-mini-di-Mac:~ macmini$

**Comment by curzon01** [comment]
I successfully used esptool.py with NodeMCU, ESP-01, ESP-12, Wemos D1 and the following parameter:

##### Read MAC
`esptool.py --port /dev/ttyUSB0 read_mac`

##### Read Chip ID
`esptool.py --port /dev/ttyUSB0 chip_id`

##### Read Flash ID
`esptool.py --port /dev/ttyUSB0 flash_id`

##### Backup original firmware
`esptool.py --port /dev/ttyUSB0 read_flash 0x00000 0x100000 sonoff_image.bin`

##### Erase flash (optional)
`esptool.py --port /dev/ttyUSB0 erase_flash`

##### Flash Tasmota Firmware
`esptool.py --port /dev/ttyUSB0 write_flash -fs 1MB -fm dout 0x0 sonoff.bin`

**Comment by blynk7843** [comment]
Thanks!
I did it :-)

**Comment by kovaccs** [comment]
Hi!  Wemos D1 mini after flashing sonoff.bin with esptool doesn't connect wifi (default ssid: indebuurt1).
Any tip?
