### ISSUE TITLE
Is their any way to turn on a relay wait for 3 sec and make it off by using single mqtt command.

### ISSUE THREAD

**Issue by aaamitsingh** [arendst/Sonoff-Tasmota#2535]
Is their any way to turn on a relay wait for 3 sec and make it off by using single mqtt command.

**Comment by curzon01** [comment]
Yes, two possible solutions
- use `PulseTime<x> 30` [command](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#main) once to configure on interval for 3 sec. Then your relay will stay on for 3 sec and switch off automatically when use single "Power<x> ON" command
- use [Backlog](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#using-backlog) command with Delay, e.g. a MQTT payload "Backlog Power1 ON;Delay 30;Power1 OFF" will switch relay 1 on, wait 3 sec and switch relay 1 off
