### ISSUE TITLE
Dht11 not showing up on 5.12.0i

### ISSUE THREAD

**Issue by kornfool** [arendst/Sonoff-Tasmota#2545]
Dht11 not showing up on wemos d1 mini,tried a few gpio but still not showing up,able to get pir sensor to works.

**Comment by Jason2866** [comment]
Does the sensor work? Is the resistor between output und vcc installed?

**Comment by kornfool** [comment]
I had 3 pcs which don't show up,my dht11 had resistor installed,just can't figure out

**Comment by Jason2866** [comment]
Which device? I have a NodeMcu which some sensors do not work.
On a WeMini the are all working!
Try the senor(s) on a other device

**Comment by ascillato** [comment]
Hi

If your issue is solved, please close it. Thanks
