### ISSUE TITLE
power on state 2 doesn't working with mqtt

### ISSUE THREAD

**Issue by Grin00** [arendst/Sonoff-Tasmota#2546]
Hi! At first I want to apologize I'm new to automation
 I am using sonoff basic with tasmota firmware and HassIo
{"Status":{"Module":1,"FriendlyName":"Sonoff","Topic":"sonoff","ButtonTopic":"0","Power":-2,"PowerOnState":2,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
My circuit works like this:
Power to the module Sonoff is always active. I can controlling sonoff by  mqtt mosquitto on hassIo and manually (break the power circuit with the wall switch, before this, setting POWERONSTATE 2 at the sonoff)
 
Problem is that, when I push my wall switch relay toggle on 4-5 seconds and than goes off 

00:00:00 Project sonoff Sonoff (Topic sonoff, Fallback DVES_73F6F3, GroupTopic sonoffs) Version 5.12.0d-2_4_0
00:00:00 WIF: Connecting to AP1 GrinLink Wi-fi in mode 11N as sonoff-5875...
00:00:04 WIF: Connected
00:00:04 DNS: Initialized
00:00:04 HTP: Web server active on sonoff-5875.local with IP address 192.168.0.101
00:00:06 MQT: Attempting connection...
00:00:06 MQT: Connected
00:00:06 MQT: tele/sonoff/LWT = Online (retained)
00:00:06 MQT: cmnd/sonoff/POWER = 
00:00:06 MQT: tele/sonoff/INFO1 = {"Module":"Sonoff Basic","Version":"5.12.0d","FallbackTopic":"DVES_73F6F3","GroupTopic":"sonoffs"}
00:00:06 MQT: tele/sonoff/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoff-5875","IPAddress":"192.168.0.101"}
00:00:06 MQT: tele/sonoff/INFO3 = {"RestartReason":"Power on"}
00:00:06 MQT: homeassistant/light/sonoff/config =  (retained)
00:00:06 MQT: homeassistant/switch/sonoff/config =  (retained)
00:00:06 MQT: stat/sonoff/RESULT = {"POWER":"OFF"}
00:00:06 MQT: stat/sonoff/POWER = OFF
20:43:40 MQT: stat/sonoff/RESULT = {"POWER":"OFF"}
20:43:40 MQT: stat/sonoff/POWER = OFF

How to fix it?

**Comment by Jason2866** [comment]
Hass.io has the messages stored (retained) and send it if device is reachable again.
I dont use Hass, i am sure you will get help from otherHass users to get this solved
