### ISSUE TITLE
SI7021 or AM2301? suggestion

### ISSUE THREAD

**Issue by vedatorkun** [arendst/Sonoff-Tasmota#2547]
Which sensor should I buy for sonoff th16 tasmota?
SI7021 or AM2301? Also what is the difference between them ?, please help me.

**Comment by Frogmore42** [comment]
http://www.kandrsmith.org/RJS/Misc/Hygrometers/calib_many.html

**Comment by vedatorkun** [comment]
Thank you for the article link. I just want to measure the room temperature and humidity as the price / performance maximum. Of course do should not cause problems in tasmota process.

**Comment by Frogmore42** [comment]
What are you doing with the data?
How accurate do you want it to be?

The cheap sensors are inexpensive and not at all accurate.

I like the BME280.  It is reasonably priced and appears quite accurate.

**Comment by vedatorkun** [comment]
I will use it with my home assistant (hass.io). My target is just to learn room temperature and humibility. They sell these two models together with the "sonoff th16" device in aliexpress. I want tasmota to be faultless.
