### ISSUE TITLE
Small char array for mqtt hostname. 

### ISSUE THREAD

**Issue by miklik72** [arendst/Sonoff-Tasmota#2550]
Hi,

I can not set mqtt hostname for IBM Watson IoT service because they are using very long domain name like "xxxxxx.messaging.internetofthings.ibmcloud.com" and is not possible (i did not find) use CNAME on own DNS or IP because IBM probably checking FQDN of hostname (customer identificator xxxxxx).
Example I'm able connect from workstation by telnet to xxxxxx.messaging.internetofthings.ibmcloud.com 1883 but not with xxxxxx.foobar.cz or IP.
I tried increase char array mqtt_host from 33 to 50 in structure Settings in source file settings.h but it is not running on the ESP8266(Sonoff Touch).

char          mqtt_host[33];             // 1E9

This hexa index in the comment probably something mean, probably it is some offset in EEPROM or ...

Will be possible increase mqtt_host to at least 50 characters?

thanks
Martin Mikala

- Sonoff Touch
- Tasmota 5.12.0

**Comment by miklik72** [comment]
Hi,

Thanks for answer and of course mistake has been between keyboad and seat. I set bad CNAME on DNS.
IP is not good use because IBM is changing IP sometime or moving service between servers.

So now I moved from rc -2 to rc -4. :-)

**Comment by arendst** [comment]
Apart from their hostname they also seem to need a password longer than Tasmota supports.

I suggest you make your own version with bigger string length and be prepared to loose all current settings as the lay-out will change but once configured you should be good to go.

Just look for Settings.mqtt_host and mqtt_pwd in file settings.h and change the default of 33 to whatever you like.

**Comment by miklik72** [comment]
I had to shorting also client ID to less than 32 chars. So now I'm able see log messages on the Watson IoT page.
IBM is using similar like this d:xxxxxx:sonofftouch:swTatka


Now I'm solving problem with topic that will be like IBM need.

_The topic is not valid: iot-2/evt/sonoff/fmt/txt/LWT The topic does not match an allowed rule._

**Comment by pskifast** [comment]
I am trying to connect tasiota-flashed Sonoff basic to IBM IoT cloud. However I cannot reproduce your success. Could you please elaborate on the procedure?

**Comment by pskifast** [comment]
> I had to shorting also client ID to less than 32 chars. So now I'm able see log messages on the Watson IoT page.
> IBM is using similar like this d:xxxxxx:sonofftouch:swTatka
> 
> Now I'm solving problem with topic that will be like IBM need.
> 
> _The topic is not valid: iot-2/evt/sonoff/fmt/txt/LWT The topic does not match an allowed rule._

I am trying to connect tasmota-flashed Sonoff basic to IBM IoT cloud. However I cannot reproduce your success. Could you please elaborate on the procedure?

**Comment by miklik72** [comment]
Hi,
I've lost this configuration because I set there local MQTT server later. But I set it in config file user_config.h and rebuilded source code and flashed to sonoff.
