### ISSUE TITLE
WiFi connection failure

### ISSUE THREAD

**Issue by arturodiazad1** [arendst/Sonoff-Tasmota#2551]
hi, all the basic Sonoff in which install TASMOTA with 5.10 perfect but those that I have recently installed with the version 5.12 only Connect with the Wi-Fi on some occasions, I do not know what to do, I check it in the Arduino terminal and continuously give connection failure, has someone happened to me or can you help me solve it?

Make sure these boxes are checked before submitting your issue - Thank you!

- [ ] What hardware you are using
- [ ] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

**Comment by reloxx13** [comment]
Provide the output of command status 0

**Comment by MatzeJoerling** [comment]
what about reading the wiki, perhaps the commands section:
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

So, open your console (serial, web, mqtt also possible) and type "status 0"
Post the output!

**Comment by arturodiazad1** [comment]
This is what happens, the module does not connect to the Wi-Fi network, only in some cases it connects to the network. This is suspending me since downloading version 5.12 all the accessories that are working with vrsion 5.10 work perfect.


![captura de pantalla 2018-04-27 a las 10 40 45](https://user-images.githubusercontent.com/17935877/39357384-0f071588-4a13-11e8-910f-4841f5b1e655.png)

**Comment by arturodiazad1** [comment]
You can't comment at this time — your comment cannot be blank.

![captura de pantalla 2018-04-27 a las 10 24 06](https://user-images.githubusercontent.com/17935877/39357873-6a50d2f2-4a14-11e8-8033-d50b1e8a5d8b.png)

**Comment by Frogmore42** [comment]
You might try using core 2.3.0 instead of the 2.4.0 you are currently using.  Some people have had connection problems with 2.4.0.

**Comment by titomontes** [comment]
I know what question comes next: How do I get to change the Core version?? before flashing?

Thanks

**Comment by arturodiazad1** [comment]
update the libraries to the latest version and the connection problems have been solved. thank you very much
