### ISSUE TITLE
Can Tasmota firmware be flashed via espurna webpage?

### ISSUE THREAD

**Issue by slother** [arendst/Sonoff-Tasmota#2556]
I have found information that it is possible to flash tasmota->espurna, but can you do the opposite? espurna->tasmota? 

Coming from tasmota and I dont want to remove my sonoffs from wall just to flash it.

**Comment by Jason2866** [comment]
I did this successfully. In worst case you have to reflash with the USB Adapter.

**Comment by lobradov** [comment]
I didn't had any trouble moving from one to the other (both ways).

As a plus, seems Espurna would keep the config if you go back to it (Espurna -> Tasmota > espurna) while Tasmota would be reset to factory settings.

**Comment by vMeph** [comment]
i have espurna and cant get back to tasmota, wont show in my wifi device any toughts?
