### ISSUE TITLE
OLED Display support

### ISSUE THREAD

**Issue by rlust** [arendst/Sonoff-Tasmota#2557]
Checking to see if any display support is planned for the future?
I see great value in using OLED displays for non SONOFF devices, like WEMOS.

**Comment by arendst** [comment]
I have some display support running for over a year but it is very user unfriendly as it only allows displaying of MQTT messages without user intervention. Displays supported are LCD, Oled, TFT and up to 8 matrices. AT home they run fine.

I might release a branch without support just for you to see what is possible.

**Comment by rlust** [comment]
Got it loaded, not sure has to set options?
I am using a IC2 old display.
Anyone have any luck here?

**Comment by arendst** [comment]
Currently all displays have the possibility to show life MQTT messages. This probably only works when the default prefixes are used. The display driver receives all tele messages and decodes the JSON text and should display information like

![img_20180430_152549](https://user-images.githubusercontent.com/11044339/39429673-e4cfa1ba-4c8b-11e8-9065-96e2789c775d.jpg)
Settings:
```
14:39:16 CMD: displaymodel
14:39:16 MQT: stat/wemos9/RESULT = {"DisplayModel":2}
14:39:20 CMD: displaymode
14:39:20 MQT: stat/wemos9/RESULT = {"DisplayMode":5}
14:39:33 CMD: displayrefresh
14:39:33 MQT: stat/wemos9/RESULT = {"DisplayRefresh":2}
14:39:45 CMD: power
14:39:45 MQT: stat/wemos9/RESULT = {"POWER":"ON"}
14:39:45 MQT: stat/wemos9/POWER = ON
14:39:56 CMD: displayrows
14:39:56 MQT: stat/wemos9/RESULT = {"DisplayRows":8}
14:40:01 CMD: displaycols
14:40:01 MQT: stat/wemos9/RESULT = {"DisplayCols1":21}
```
![img_20180430_152615](https://user-images.githubusercontent.com/11044339/39429731-1b09f456-4c8c-11e8-9c8d-948ec4a08fb8.jpg)
Settings:
```
15:41:23 CMD: displaymodel
15:41:23 MQT: stat/ticker/RESULT = {"DisplayModel":3}
15:41:28 CMD: displaymode
15:41:28 MQT: stat/ticker/RESULT = {"DisplayMode":5}
15:41:34 CMD: displayrefresh
15:41:34 MQT: stat/ticker/RESULT = {"DisplayRefresh":1}
15:41:38 CMD: power
15:41:38 MQT: stat/ticker/RESULT = {"POWER":"ON"}
15:41:38 MQT: stat/ticker/POWER = ON
15:41:49 CMD: displayrows
15:41:49 MQT: stat/ticker/RESULT = {"DisplayRows":2}
15:41:54 CMD: displaycols
15:41:54 MQT: stat/ticker/RESULT = {"DisplayCols1":32}
```
![img_20180430_152623](https://user-images.githubusercontent.com/11044339/39429764-3cae71fe-4c8c-11e8-821d-fd968021b955.jpg)
Settings:
```
15:42:46 CMD: displaymodel
15:42:46 MQT: stat/lcd/RESULT = {"DisplayModel":1}
15:42:50 CMD: displaymode
15:42:50 MQT: stat/lcd/RESULT = {"DisplayMode":4}
15:42:58 CMD: displayrefresh
15:42:58 MQT: stat/lcd/RESULT = {"DisplayRefresh":2}
15:43:01 CMD: power
15:43:01 MQT: stat/lcd/RESULT = {"POWER":"ON"}
15:43:01 MQT: stat/lcd/POWER = ON
15:43:07 CMD: displayrows
15:43:07 MQT: stat/lcd/RESULT = {"DisplayRows":2}
15:43:11 CMD: displaycols
15:43:11 MQT: stat/lcd/RESULT = {"DisplayCols1":16}
15:43:24 CMD: displayaddress
15:43:24 MQT: stat/lcd/RESULT = {"DisplayAddress1":39}
```
![img_20180430_152637](https://user-images.githubusercontent.com/11044339/39429814-62e85812-4c8c-11e8-980f-2cebb3e54059.jpg)
Settings:
```
15:44:10 CMD: displaymodel
15:44:10 MQT: stat/tft/RESULT = {"DisplayModel":4}
15:44:14 CMD: displaymode
15:44:14 MQT: stat/tft/RESULT = {"DisplayMode":5}
15:44:21 CMD: displayrefresh
15:44:21 MQT: stat/tft/RESULT = {"DisplayRefresh":2}
15:44:24 CMD: power
15:44:24 MQT: stat/tft/RESULT = {"POWER":"ON"}
15:44:24 MQT: stat/tft/POWER = ON
15:44:28 CMD: displayrows
15:44:28 MQT: stat/tft/RESULT = {"DisplayRows":2}
15:44:34 CMD: displaycols
15:44:34 MQT: stat/tft/RESULT = {"DisplayCols1":20}
```

**Comment by Jason2866** [comment]
THANK you!
More explenations as hoped!
With that the last open point in my Smart Home project is going to be solved.
I need a few simple and cheap devices that displays some parameters (temperature, humidity)😃

**Comment by rlust** [comment]
Thanks so much Arendst, your work is invaluable!
Well done as always!

Jason2886, are you able to work with me on this to understand how you got a display?
My email is rlust_at_mac.com

**Comment by Jason2866** [comment]
@rlust 
Which type of display do you want OLED or LCD Dot Matrix (how many rows and lines)?
To find is really simple. For OLED search for SSD1306 and for LCD with a I2C interface
For example https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20180430063646&SearchText=Ssd1306
or
https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20180430063755&SearchText=Lcd+i2c

**Comment by rlust** [comment]
I have an OLED .96 like option 1
128x64
What changes did you make in 06_display.ino?
I am able to scan I2C and see the address 0x3c.

**Comment by Jason2866** [comment]
@arendst  Nice, reliable and quick solution. I like it too. In my very early years it was part of my job. Would be nice to own a electric wire rapp machine for private use...

**Comment by arendst** [comment]
In my early days, fixing backplanes,  I used a battery powered wire-wrap tool too but the battery has left this planet so I have to use an old, once bought from Tandy wire-wrap manual tool which does the job perfectly.

**Comment by Jason2866** [comment]
@rlust  just added in user_config.h
around line 264:
    #define USE_DISPLAY                            // Add I2C code for Diplays 

Nothing changed in 06_display.ino
Time and Date is on the display at start. I´m not at home so i can try the commands from Theo
later the day....

**Comment by Jason2866** [comment]
@arendst  I know this hand wrap tool too. Mine still works pretty well after many years! 
And it is a good training for the hand muscels ;-)

**Comment by rlust** [comment]
Got it working!!!
It is picking up all of my temperature readings.
This is fantastic! 
Thanks Jason for the guidance!
arendst you made my day, this really is a great feature!!!!!!
Now to pull out my old wire wrap toll and get a larger display.
I also spent to many days back in tech school doing wire wrap :)

**Comment by arendst** [comment]
I use a 5V/3A power supply feeding the matrix unit. From there I use USB cables to TFT and LCD. The oled is currently fed by a USB to FTDI converter as the onboard USB connector broke off the board within an hour of use ;-(

**Comment by ascillato** [comment]
Amazing! Thanks for sharing :+1:

**Comment by sharpn** [comment]
Is there a specific build that needs to be uploaded to the device to get this working?

**Comment by Jason2866** [comment]
Yes, branch development-display

**Comment by bollitec** [comment]
@arendst, many thanks for your picture with wemos and tft display, can you please send a higher resolution or the pin assignments (wemos - tft) ?

Like to test the branch and have some idea with touch screen display from raspi.


Thanks a lot!

**Comment by abaszczok** [comment]
Guys... I can not get it running... I setup display mode model etc... I got OLED 128x64 + D1 mini, which device type did you select in config module?? "generic?" .. I put #define USE_DISPLAY.. what else I'm missing/??? I tested this display + D1 on ESPeasy - the depslay is OK.. any hints?

**Comment by abaszczok** [comment]
Got it working.... pull up resistors 4,7k - ESPeasy you dont need to use them - they are internally proramable.. 
@arendst - you'r my hero !!! - keep it rolling

**Comment by Jason2866** [comment]
If someone doesnt know how to connect the TFT Display (SPI).
Take a look here:
http://microcontrollerkits.blogspot.de/2015/11/esp8266-wifi-tftlcd.html
CS and DC has to be cofigured over web console in module generic. See picture
![screenshot_20180526-144604](https://user-images.githubusercontent.com/24528715/40576288-b7e0759a-60f3-11e8-8c44-adb38087a16a.png)
I used not GPIO 2 and 5 as in descriptio example. I used GPIO 15 and 16.

**Comment by vMeph** [comment]
hi @arendst was trying this comands not working

```
21:04:49 CMD: displaymode1
21:04:49 MQT: stat/sonoff/RESULT = {"Command":"Unknown"}
```

**Comment by Jason2866** [comment]
Habe you used the correct branch Development-Display?

**Comment by vMeph** [comment]
Yes mate

**Comment by Jason2866** [comment]
You have enabled user_config_override.h ? In this file is the display part enabled.
Does the connected Display shows anything? Just out of the box it shows time and date.

**Comment by vMeph** [comment]
Got it to work mate

**Comment by Jason2866** [comment]
What was missing?

**Comment by vMeph** [comment]
enable user_config_override.h  :)

**Comment by vMeph** [comment]
@jason2866  anyway to keep values info steady, everytime updates info it keeps moving down
wondering if any command exits to keep them updating in the same place

**Comment by Jason2866** [comment]
I had this top, If i remember correct there is a command displaycols and displayrows. You have to set the values here of your display

**Comment by Dees7** [comment]
Hello.
Is origin/developmet support Display?
I use ea43540 and connect TFT LCD 1.8 (128x64) with config
![g](https://user-images.githubusercontent.com/14229113/44631549-30d8e500-a987-11e8-8e3d-1672260af0a2.PNG)
but after save SDA and CLK reset
![b](https://user-images.githubusercontent.com/14229113/44631625-308d1980-a988-11e8-84fc-3a8126f6a5e7.PNG)

Display works but in mirror mode and with lines
![img_20180826_232321](https://user-images.githubusercontent.com/14229113/44631736-c37a8380-a989-11e8-9a38-03f57f1959dc.jpg)

MQT: stat/sonoff/RESULT = {"DisplayModel":4}
MQT: stat/sonoff/RESULT = {"DisplayAddress1":113}
MQT: stat/sonoff/RESULT = {"DisplayRows":8}
MQT: stat/sonoff/RESULT = {"DisplayCols1":21}

BMP280 doesn't work with display in this config.
What do I wrong?

**Comment by arendst** [comment]
As the interface is SPI you will need to know it uses 5 signal lines. Tasmota currently only supports hardware SPI. This always uses pins 12, 13 and 14 in addition to user selectable SPI CS and SPI DC.

So in your case connect 12 to MISO (if used)
13 to MOSI
14 to CLK
and any of the other gpios to cs and dc

Other gpios can be used for I2C

**Comment by arendst** [comment]
Use displayrotate 0 to 3 for correct rotation.  Only rotation 0 supports hardware scroll.

**Comment by Dees7** [comment]
Yes after connnecting as @arendst said BME280 works but display steel mirrored and shows a lot of noise.

**Comment by Jason2866** [comment]
Maybe you have to use pullup resistors on all data connections. And a breadboard can make troubles too.
Try to connect everything without it. Use short wires. Electronic can be a pain...

**Comment by andrethomas** [comment]
@Dees7 Are you sure about the driver for that lcd?

**Comment by Dees7** [comment]
@andrethomas yes I'm shure about LCD. I've tested it.
@Jason2866 you have the same LCD TFT 1.8 tested? This works with test sketch well.

**Comment by Jason2866** [comment]
I have this display
https://www.aliexpress.com/item/2-8-inch-TFT-LCD-Module-without-Touch-Panel-ILI9341-Drive-IC-240-RGB-320-SPI/32764300681.html?spm=a2g0s.9042311.0.0.27424c4dWb2ZWj

**Comment by simo26246** [comment]
Hi all, I've read through this and am still having a little difficulty. I'm trying to connect a display - 

https://www.aliexpress.com/item/0-96-inch-IIC-SPI-Serial-128X64-Yellow-Blue-OLED-Display-Module-I2C-LCD-Screen-Board/32779485021.html?spm=2114.search0604.3.9.5b3758e8dJJGLc&ws_ab_test=searchweb0_0,searchweb201602_3_10065_10068_10130_10547_10059_10548_10696_100031_10084_10083_10103_451_10618_5016315_452_10307_10131_10132_5015615_10133,searchweb201603_45,ppcSwitch_5&algo_expid=79e93466-11bf-42de-9e2d-5d49db3c7070-1&algo_pvid=79e93466-11bf-42de-9e2d-5d49db3c7070&transAbTest=ae803_2&priceBeautifyAB=0

But I can't figure out which pins to connect to what, and how to set it up as a generic chip (I'm using a wemos d1 mini) in the config menu.

I know this is super basic, but I'm super new at this - any help would be really appreciated!

**Comment by Jason2866** [comment]
You have to connect:
![image](https://user-images.githubusercontent.com/24528715/45364003-51d14500-b5d9-11e8-900a-63cd347249fa.png)
and to solder the jumpers R1, R4, R6, R7, R8:
![image](https://user-images.githubusercontent.com/24528715/45364058-77f6e500-b5d9-11e8-895c-195ce4a17a86.png)
You have bought not the easiest one for beginning :-)

**Comment by simo26246** [comment]
Thanks for the reply. That all sounds like it needs to go in the too hard basket, and I'll just buy new screens, haha.

**Comment by andrethomas** [comment]
@simo26246 Its simple enough to solder t he bridges where they are marked on the pc board? Why waste a good lcd

**Comment by simo26246** [comment]
When you say solder them, you mean just bridge them together with solder?

What would my pin config for a generic device be in the sonoff firmware? Obviously ground and vcc don't need to be setup, but what about the other pins? 

I just need to connect the SDA and SCL? Like this? - (yes, I know this isn't the development branch firmware - it's on another device, and wanted to make sure I got it right before stuffing around again)
![testconfig](https://user-images.githubusercontent.com/29731489/45467431-c2559e80-b75e-11e8-8121-caa83fc2a3ac.PNG)

Then connect them to the corresponding pins on the d1 mini? Really appreciate the help guys!

**Comment by ascillato2** [comment]
Closing issue as now it is implemented in Tasmota. Thanks everyone for sharing ideas.

**Comment by AalianKhan** [comment]
is it possible to show the status of a relay on these displays? it will be a really cool feature.

**Comment by Jason2866** [comment]
@AalianKhan 
Yes, i agree. But isnt easy. How todo? So many different displays. And if done everyone has different wishes...
You can do it via rules!

**Comment by last0tt0man** [comment]
is it  possible to use SSD1306 128x32 model ? I'm trying all combinations but fonts wrong. 
only displaymode 1 date&time working correctly.
![img_20181105_141252](https://user-images.githubusercontent.com/30460524/47995033-22d0de80-e105-11e8-8297-d4ea50942e26.jpg)
![img_20181105_141320](https://user-images.githubusercontent.com/30460524/47995041-295f5600-e105-11e8-92c0-cd20c048410b.jpg)

**Comment by Jason2866** [comment]
Try a different font size. If that doesnt help old settings or fragments are in flash
Delete whole flash and try again. I had the same problem...
After a clean start it worked

**Comment by ceraz68** [comment]
@simo26246. I'm configured exactly like you Wemos D1 mini and oled shield 64×48 pixels. I flashed the sonoff-dislay.bin 6.3.0 (not sonoff.bin - read release notes). Perform I2Cscan and check displayaddress is set to 60. Don't forget to toggle the wemos On.

Only working command seems to be displaymode. Other commands do not work for me such as displaytext. Displayed date does not scale and can't displaytext.

**Comment by Jason2866** [comment]
You have to set DisplayMode 0  to use DisplayText commands.
[DisplayText.docx](https://github.com/arendst/Sonoff-Tasmota/files/2568264/DisplayText.docx)

**Comment by ceraz68** [comment]
@Jason2866 : thanks that was really dumb, I was convinced I read somewhere that displaymode 0 meant display off.

Still no luck for me on the wemos mini D1 with oled shield 64×48 pixels. Displaytext doesn't show text in mode 0. Just a black screen.

16:44:52 CMD: displaymode
16:44:52 MQT: stat/sonoff/RESULT = {"DisplayMode":0}
16:45:00 CMD: displayrows
16:45:00 MQT: stat/sonoff/RESULT = {"DisplayRows":8}
16:45:07 CMD: displaycols
16:45:07 MQT: stat/sonoff/RESULT = {"DisplayCols1":25}
16:45:22 CMD: power
16:45:22 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
16:45:22 MQT: stat/sonoff/POWER = ON
16:45:33 CMD: DisplayText [z]
16:45:33 MQT: stat/sonoff/RESULT = {"DisplayText":"[z]"}
16:45:44 CMD: DisplayText [s1l1c1]Hello how are you?
16:45:44 MQT: stat/sonoff/RESULT = {"DisplayText":"[s1l1c1]Hello how are you?"}
16:45:56 CMD: displaymode 2
16:45:56 MQT: stat/sonoff/RESULT = {"DisplayMode":2}

In displaymode 2, text scrolls but truncated. For the second line, I only see "aymode 2" on the screen. So there must be display mis-alignment somewhere. Tried changing the displayrows and displaycols to match font size but this doesn't improve.

I'm wondering if I need to add more settings to the module or the OLED is incompatible. I only assigned  I2C SDA and SCL like simo26246 above.

**Comment by Jason2866** [comment]
Hmm, try to "play" with
sp = set text size (scaling factor 1...4) (only for classic GFX font)
fp = set font (1=12, 2=24,(opt 3=8)) if font==0 the classic GFX font is used
I tried the module only (not installed) and i remember i had the same problem
and i got it working with changing one of these...

**Comment by Jason2866** [comment]
@simo26246 
I think i knew what is missing to bring your display to working.
See here https://github.com/arendst/Sonoff-Tasmota/issues/4334#issuecomment-439006127
You have for working with Tasmota (I2C) resistors on Position R1, R4, R6, R7 and R8 coud be left open.
**Urgent you have to connect Pin CS with GND!**

**Comment by raidolo** [comment]
@Jason2866  downloaded!
I'm sorry, I've just realized that the SH1106 is an I2C display. Mine is SPI. 
The product is this:
https://www.az-delivery.de/collections/displays/products/1-8-zoll-spi-tft-display?ls=en&cache=false&curr=eur  
And it seems it has a ST7735 controller! 

At the moment is not supported even in the Gemu2015 release.

Thanks again anyway, you pointed me in the right direction!
I'll try to include the support for it by myself.

**Comment by raidolo** [comment]
Ok I've implemented the ST7735 adafruit Lib in the latest tasmota code. I had to update also the GFX Library as well
It seems working very good now! 


![whatsapp image 2018-11-17 at 00 45 00_edit](https://user-images.githubusercontent.com/25846804/48653208-e43ffb80-ea03-11e8-966d-9734002b854c.jpg)
![whatsapp image 2018-11-17 at 00 49 46_edit](https://user-images.githubusercontent.com/25846804/48653207-e43ffb80-ea03-11e8-980f-a89d7d391724.jpg)

**Comment by ceraz68** [comment]
Finally got DisplayText working on Wemos D1 mini OLED shield 64x48. As tasmota documented support is limited to 128x64 I expected some limitations. 

"Displaytext [s1l1c1]Hello how are you?"  as described in the wiki wasn't working for me. I tried different size, font, display models. Then I tried using x, y positions instead of line and column .... bingo! 

Upper left position corresponds to x=35 and y=20. Then I realised that displaytext works from line 3 column 7, so the text was being displayed out of the screen bounds, duh!

Changing the number of rows/lines seems to have no effect. Below are my display settings:

CMD: display
MQT: stat/sonoff/RESULT = {"Display":{"Model":2,"Mode":0,"Dimmer":1,"Size":1,"Font":0,"Rotate":0,"Refresh":2,"Cols":[22,8],"Rows":8}}

**Comment by shivasiddharth** [comment]
@raidolo , Can you please share the changes you made ?

**Comment by raidolo** [comment]
@shivasiddharth, would be a bit long to write it in a post. Essentially I've cloned the ili9341 driver, which basically has the same controls, I've dropped in the Adafruit ST7735 Library and the latest Adafruit GFX 1.3.2. Then added some functions missing in the ST7735 cpp file, such as scrollTo(). Then I've add a new USE_DISPLAY_ST7735 define. I'm thinking of forking the tasmota sources, but it would be near impossibile for me alone to manage that, and I'm not really sure I've done all the things to support the new driver correctly. I'm still learning how tasmota works and something is not really clear, I'm not a full time developer. What do you think is the best way to share the modifications? (I've also integrated the latest IRRemote libraries because I needed the latest ir_Daikin.h)

**Comment by shivasiddharth** [comment]
Can you fork https://github.com/gemu2015/Sonoff-Tasmota and upload your changes ? If its too much to ask, may be then you can just zip the folder and attach the zip here.

**Comment by AalianKhan** [comment]
hello, I have a 20x4 LCD display I have set the rows to 4 and columns to 20. everything works fine but I can't seem to displays stuff at row 4. I have tried using x and y coordinates but still no luck. here are my display settings 
`{"Display":{"Model":1,"Mode":0,"Dimmer":1,"Size":1,"Font":1,"Rotate":0,"Refresh":2,"Cols" [20,8],"Rows":5}}`

**Comment by arendst** [comment]
This sounds correct https://github.com/arendst/Sonoff-Tasmota/issues/2557#issuecomment-416267793 but this also works:
```
2.2 TFT SPI 240x320 --> Wemos D1 mini
TFT ------   Wemos ------
1 Vcc        3V3
2 Gnd        Gnd
3 CS         D8  GPIO15
4 Reset      Rst
5 DC/RS      D0  GPIO16
6 SDI/MOSI   D7  GPIO13
7 SCK        D5  GPIO14
8 LED        D2  GPIO04 
9 SDO/MISO   D6  GPIO12
```
with following config:
![image](https://user-images.githubusercontent.com/11044339/49510863-cc80c800-f889-11e8-9db7-d9d36240fcec.png)

**Comment by dr-apple** [comment]
Thank you very much :-) It Works !

**Comment by moneybag** [comment]
It works for my LCD-Display. 
But how can I make published MQTT-Data visible on the LCD?

**Comment by red-kooga** [comment]
> @shivasiddharth, would be a bit long to write it in a post. Essentially I've cloned the ili9341 driver, which basically has the same controls, I've dropped in the Adafruit ST7735 Library and the latest Adafruit GFX 1.3.2. Then added some functions missing in the ST7735 cpp file, such as scrollTo(). Then I've add a new USE_DISPLAY_ST7735 define. I'm thinking of forking the tasmota sources, but it would be near impossibile for me alone to manage that, and I'm not really sure I've done all the things to support the new driver correctly. I'm still learning how tasmota works and something is not really clear, I'm not a full time developer. What do you think is the best way to share the modifications? (I've also integrated the latest IRRemote libraries because I needed the latest ir_Daikin.h)

Hi could you fork and not manage, i have been trying to add a nokia display without success i have several ST7735 displays i was going to try next it would save a lot of work.
Thanks

**Comment by raidolo** [comment]
@red-kooga @shivasiddharth   (cc. @arendst ) 

I've created a new branch: 

https://github.com/raidolo/Sonoff-Tasmota/tree/ST7735-irDaikin

I've forked and committed my changes for these things:

- Added Adafruit ST7735 Display library for the SPI displays: 
Created a new display driver based on the ili9341 driver:  **xdsp_05_st7735.ino** 
You should set SPI CS and DC pins in the module configuration using the web ui. 
(I've set mine to GPIO15 D8 and GPIO16 D0 on my Wemos nodemcu replica)

- Upgraded to the latest IRRemote library for Daikin AC conditioner and implemented Daikin HVAC in **xdrv_05_irremote.ino**
You have to use IRHvac commands as all other hvacs systems, all modes supported Auto, Heat, Cool, Dry, Fan, I need to implement Swing modes and Confort modes supported by the new lib
 
Please try it and let me know the results!

**Comment by red-kooga** [comment]
Thanks raidolo, I will try soon as I can

**Comment by bastelfix** [comment]
Hi @raidolo 
just tested your fork with an 1,77" 160(RGB)x128 ST7735 SPI-Display.
With v6.4 i got mirrored display content and some obstacles like here: https://github.com/arendst/Sonoff-Tasmota/issues/2557#issuecomment-416060488
With your forked version it works fine, besides from some lines "eaten" at the top (maybe one or two pixels, may be hardwareproblem with this cheap thing) and crappy green bars. If you need photos please tell me.

Pinout from  "1,77" 160(RGB)x128 ST7735 SPI-Display" to Wemos D1 mini
1 – GND – Ground
2 – VCC – 3.3V
3 – SCL – Serial Clock --> D5/SCK/GPIO14
4 – SDA – Serial Data Input --> D7/MOSI/GPIO13
5 – EWA – LCM Reset (bei Betrieb HIGH)
6 – DC – Data/Command Control -->D0/GPIO16
7 – CS – Chip Select -->D1/GPIO5
8 – BLK – Beleuchtung --> ?  (theres a toggle button at webgui, anyone know which port it is toggling? do i need to define a led/relay to toggle it?)

**Comment by raidolo** [comment]
@bastfix my 1.8” works pretty good. 
It’s the original adafruit lib so, I dunno if you have hardware problems. You could try to upload the graphictest sketch first (you have the ino file in the examples for inside the library itself), just to be sure it’s not related to the driver I wrote.
Yeah, post some photos!

**Comment by raidolo** [comment]
@bastelfix Uh, the green bar are probably my fault, I’ve set them somewhere in the code while testing! Sorry for that, I’ll fix them tomorrow if I have sometime, but it’s not an issue with the display. I didn’t notice them before the upload because I’m using displaymode 0, to set my own text with the displaytext commands.
You have to set Display rows and cols via console commands, if you want to rotate the display, otherwise you end with screwed text. It’s not something to be set in the code, they are dynamic and should be set accondingly with the display size.

**Comment by raidolo** [comment]
@bastelfix  I've committed few changes to bring back the default behaviour of tasmota 6.3 with DisplayModes 1-5

https://github.com/raidolo/Sonoff-Tasmota/commit/d4c1f26427079512aca1c249f0caceec27c5eade

You still have to set DisplayCols Rows, and Rotation.
Here are mine:

09:56:03 MQT: stat/thermo/RESULT = {"DisplayCols1":27}
09:56:09 CMD: DisplayRows
09:56:09 MQT: stat/thermo/RESULT = {"DisplayRows":15}
09:56:16 CMD: DisplayRotate
09:56:16 MQT: stat/thermo/RESULT = {"DisplayRotate":1}

Hope that helps.

Cheers!

**Comment by AalianKhan** [comment]
Is It possible to make little icons/picture/drawings for an LCD display? I want to show this icon 🔥 but I only have an LCD display

**Comment by Edelfalke** [comment]
Hello Raidolo,

i have tried your code,  but it won't compile.
I've got a lot of errors: 

`xdrv_03_energy:169:29: error: invalid use of Boolean expression as operand to 'operator--'

     energy_power_steady_cntr--;

                             ^

xdrv_03_energy:197:95: error: invalid initialization of reference of type 'byte& {aka unsigned char&}' from expression of type 'bool'

     if (EnergyMargin(0, Settings.energy_min_power, energy_power_u, flag, energy_min_power_flag)) {

                                                                                               ^

xdrv_03_energy:139:9: error: in passing argument 5 of 'boolean EnergyMargin(byte, uint16_t, uint16_t, byte&, byte&)'

 boolean EnergyMargin(byte type, uint16_t margin, uint16_t value, byte &flag, byte &save_flag)

         ^

xdrv_03_energy:201:95: error: invalid initialization of reference of type 'byte& {aka unsigned char&}' from expression of type 'bool'

     if (EnergyMargin(1, Settings.energy_max_power, energy_power_u, flag, energy_max_power_flag)) {

                                                                                               ^

xdrv_03_energy:139:9: error: in passing argument 5 of 'boolean EnergyMargin(byte, uint16_t, uint16_t, byte&, byte&)'

 boolean EnergyMargin(byte type, uint16_t margin, uint16_t value, byte &flag, byte &save_flag)

         ^

xdrv_03_energy:205:101: error: invalid initialization of reference of type 'byte& {aka unsigned char&}' from expression of type 'bool'

     if (EnergyMargin(0, Settings.energy_min_voltage, energy_voltage_u, flag, energy_min_voltage_flag)) {

                                                                                                     ^

xdrv_03_energy:139:9: error: in passing argument 5 of 'boolean EnergyMargin(byte, uint16_t, uint16_t, byte&, byte&)'

 boolean EnergyMargin(byte type, uint16_t margin, uint16_t value, byte &flag, byte &save_flag)

         ^

xdrv_03_energy:209:101: error: invalid initialization of reference of type 'byte& {aka unsigned char&}' from expression of type 'bool'

     if (EnergyMargin(1, Settings.energy_max_voltage, energy_voltage_u, flag, energy_max_voltage_flag)) {

                                                                                                     ^

xdrv_03_energy:139:9: error: in passing argument 5 of 'boolean EnergyMargin(byte, uint16_t, uint16_t, byte&, byte&)'

 boolean EnergyMargin(byte type, uint16_t margin, uint16_t value, byte &flag, byte &save_flag)

         ^

xdrv_03_energy:213:101: error: invalid initialization of reference of type 'byte& {aka unsigned char&}' from expression of type 'bool'

     if (EnergyMargin(0, Settings.energy_min_current, energy_current_u, flag, energy_min_current_flag)) {

                                                                                                     ^

xdrv_03_energy:139:9: error: in passing argument 5 of 'boolean EnergyMargin(byte, uint16_t, uint16_t, byte&, byte&)'

 boolean EnergyMargin(byte type, uint16_t margin, uint16_t value, byte &flag, byte &save_flag)

         ^

xdrv_03_energy:217:101: error: invalid initialization of reference of type 'byte& {aka unsigned char&}' from expression of type 'bool'

     if (EnergyMargin(1, Settings.energy_max_current, energy_current_u, flag, energy_max_current_flag)) {

                                                                                                     ^

xdrv_03_energy:139:9: error: in passing argument 5 of 'boolean EnergyMargin(byte, uint16_t, uint16_t, byte&, byte&)'

 boolean EnergyMargin(byte type, uint16_t margin, uint16_t value, byte &flag, byte &save_flag)

         ^

xdrv_03_energy:258:30: error: invalid use of Boolean expression as operand to 'operator--'

           energy_mplr_counter--;

                              ^

exit status 1
invalid use of Boolean expression as operand to 'operator--'`

How can i compile this code?

**Comment by grego1981** [comment]
Hi all, newbie here! I have compiled the latest developement with following https://github.com/arendst/Tasmota/wiki/Displays and when trying to run display command i get {"Command":"Unknown"} is there something else I must do?

**Comment by adamrunner** [comment]
@grego1981 - I got the same results, you need to be sure to configure the screen properly first with the correct pin mappings within the Module menu first.

**Comment by saikek** [comment]
Check that you have `tasmota` module uncommented in `platformio.ini`. 
I've just tested my 16x2 and 128x32 displays and after few hours they are working!

**Comment by maddingamer** [comment]
Hi all, I'm trying to use SSD1306 OLED display. 
But whatever I do, screen keeps dark. 
Using commands like displaytext returning no errors. 
GPIOs set in configuration. 
I2Cscan finds device at 0x3c. 

Any ideas? :)

**Comment by saikek** [comment]
> Hi all, I'm trying to use SSD1306 OLED display.
> But whatever I do, screen keeps dark.
> Using commands like displaytext returning no errors.
> GPIOs set in configuration.
> I2Cscan finds device at 0x3c.
> 
> Any ideas? :)

Could you try running `all` commands - like setting mode, resolution, displaymode, displaymodel ?
Start with displaymode that prints just local time.
Also try `mqtt_topic/cmnd/POWER off`  and `mqtt_topic/cmnd/POWER on`. 

That helped me, but i was not able to find patterns for that.

**Comment by maddingamer** [comment]
reflashed my device after couple of days off.. now it just works magically ^^
Now I only have to figure out on how to increase size of the text displayed and how to display mqtt stuff.. thx tho saikek :)

**Comment by ril3y** [comment]
I know this thread has some old content in it but is it still required to use the development branch to get OLED i2c displays working?

**Comment by saikek** [comment]
> I know this thread has some old content in it but is it still required to use the development branch to get OLED i2c displays working?

No, it works on release 8.10 version for me.

**Comment by Quart666** [comment]
I got a D1 Mini and the 2.4TFT. D1 now attached to back of TFT. Tested it with simple Arduino code and it work. But how do I got this to work with Tasmota.
Can i use the tasmota-display.bin, and just flash with that image?
Or do i have to compile from Source code package?

**Comment by scargill** [comment]
I am struggling with the SH1106 display - compiled tasmota with that display in...... 

it is appearing at address 3C (correct)

it is wired correctly - "displaymode 0" (no quotes) produces nothing. "displaymode 1" gives me what looks like it might be a line of time followed by a line of date... but garbled -where the seconds would be is changing every second.    "displaytext hello" - indeed "displaytext ANYTHING" does zilch.
![2021-01-09 11_46_34-Your Phone](https://user-images.githubusercontent.com/1889411/104089977-96398200-5273-11eb-84c4-48e5d5cef1bd.png)

**Comment by A1121218** [comment]
can someone help me I want write coding. but confused where to start
