### ISSUE TITLE
Rule Trigger Analog0 possible?

### ISSUE THREAD

**Issue by timtimsson** [arendst/Sonoff-Tasmota#2560]
Hello,
is a Trigger Analog0 possible?
`Rule on Tele-Analog0<>=xxxx do publish xxxxx endon`
`Rule on Analog0<>=xxxx do publish xxxxx endon`
Thanks!

**Comment by arendst** [comment]
Give it a try and let us know

**Comment by timtimsson** [comment]
tried out, unfortunately not possible...

**Comment by arendst** [comment]
Was afraid it wouldn't work. Problem is the JSON message. Two solutions possible, I have to change the JSON message or invent code to detect difference between JSON single/second level message value.

I'll leave it for the moment...

**Comment by timtimsson** [comment]
.. i would prefer this:  :)))
`xxx/tele/SENSOR {"Time":"2018-04-28T12:50:11","Switch1":"1","Analog0":{"A0":879},"BME280":{"Temperature":25.0,"Humidity":46.1,"Pressure":1000.4},"TempUnit":"C"}`

> I'll leave it for the moment
--> sure, i understand this!

**Comment by arendst** [comment]
And then I couldn't leave it as it adds useful functionality.

Give it a go!

**Comment by timtimsson** [comment]
... you are a very crazy guy! only a half day an the code is changed!
it works now perfectly with the new rules...

!Thank you for your fantastic work and the great tasmota!
