### ISSUE TITLE
Failed to learn RfKey on the bridge

### ISSUE THREAD

**Issue by DenisAntoine** [arendst/Sonoff-Tasmota#2563]
Hello,

**Comment by DenisAntoine** [comment]
I've installed the firmware on a Sonoff RF Bridge and trying to send commands with the console. I'm trying to pair a RF device by using the RfKey1 2 command but it is not recognized. I received a command Unknown response. Do I miss something in the configuration? 
![image](https://user-images.githubusercontent.com/38815720/39398900-0a61ec44-4b15-11e8-8e8e-a6882a38cfb3.png)

**Comment by ascillato** [comment]
Hi,

On the configuration menu, go to module configuration, and select sonoff bridge.

The command is unknown because you have the sonoff basic module selected

**Comment by DenisAntoine** [comment]
Hi,
It was easy. Actually I was lookig for more complex options in the user settings.
Thanks a lot for your support
