### ISSUE TITLE
Sonoff switches off when Wall switch is used

### ISSUE THREAD

**Issue by Extinguo** [arendst/Sonoff-Tasmota#2565]
My Sonoff Basic turns off when I use the wall switch to toggle it even though the wall switch is only connected to the sonoff via GPIO. There is also a resistor to avoid flickering. It completely shuts down. Neither MQTT nor the webserver are available.

Output of "status 0":
```
19:18:20 MQT: stat/sonoffSchlafzimmer/STATUS = {"Status":{"Module":1, "FriendlyName":"Sonoff", "Topic":"sonoffSchlafzimmer", "ButtonTopic":"0", "Power":1, "PowerOnState":3, "LedState":1, "SaveData":1, "SaveState":1, "ButtonRetain":0, "PowerRetain":0}}
19:18:20 MQT: stat/sonoffSchlafzimmer/STATUS1 = {"StatusPRM":{"Baudrate":115200, "GroupTopic":"sonoffs", "OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin", "Uptime":0, "Sleep":0, "BootCount":184, "SaveCount":234, "SaveAddress":"FA000"}}
19:18:20 MQT: stat/sonoffSchlafzimmer/STATUS2 = {"StatusFWR":{"Version":"5.9.1", "BuildDateTime":"2017-11-13T21:43:41", "Boot":6, "Core":"2_3_0", "SDK":"1.5.3(aec24ac9)"}}
19:18:20 MQT: stat/sonoffSchlafzimmer/STATUS3 = {"StatusLOG":{"SerialLog":2, "WebLog":2, "SysLog":0, "LogHost":"domus1", "LogPort":514, "SSId1":"Fritz2", "SSId2":"indebuurt2", "TelePeriod":300, "SetOption":"55800009"}}
19:18:20 MQT: stat/sonoffSchlafzimmer/STATUS4 = {"StatusMEM":{"ProgramSize":471, "Free":532, "Heap":24, "ProgramFlashSize":1024, "FlashSize":1024, "FlashMode":3}}
19:18:20 MQT: stat/sonoffSchlafzimmer/STATUS5 = {"StatusNET":{"Hostname":"sonoffSchlafzimmer-5540", "IPAddress":"192.168.178.90", "Gateway":"192.168.178.1", "Subnetmask":"255.255.255.0", "DNSServer":"192.168.178.1", "Mac":"5C:CF:7F:72:15:A4", "Webserver":2, "WifiConfig":2}}
19:18:20 MQT: stat/sonoffSchlafzimmer/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.178.86", "MqttPort":1883, "MqttClientMask":"DVES_%06X", "MqttClient":"DVES_7215A4", "MqttUser":"DVES_USER", "MAX_PACKET_SIZE":512, "KEEPALIVE":15}}
19:18:20 MQT: stat/sonoffSchlafzimmer/STATUS7 = {"StatusTIM":{"UTC":"Sat Apr 28 18:18:20 2018", "Local":"Sat Apr 28 19:18:20 2018", "StartDST":"Sun Mar 25 02:00:00 2018", "EndDST":"Sun Oct 28 03:00:00 2018", "Timezone":1}}
19:18:21 MQT: stat/sonoffSchlafzimmer/STATUS10 = {"StatusSNS":{"Time":"2018-04-28T19:18:20", "Switch1":"ON"}}
19:18:21 MQT: stat/sonoffSchlafzimmer/STATUS11 = {"StatusSTS":{"Time":"2018-04-28T19:18:21", "Uptime":0, "Vcc":3.215, "POWER":"ON", "Wifi":{"AP":1, "SSId":"Fritz2, "RSSI":96, "APMac":"34:31:C4:65:57:09"}}}
```

Any ideas what the problem might be?

**Comment by Frogmore42** [comment]
That usually indicates a wiring error.  How exactly do you have things wired?

**Comment by Extinguo** [comment]
That's also what I assumed so I double checked it. The wiring to the lamp is connected to the output of the sonoff. Constant Power is applied to the input. Also wired a resistor to 3.3v/gpio14. Additionally I connected the wallswitch

**Comment by Frogmore42** [comment]
What size/value resistor did you use and how exactly did you wire the wall switch.  My guess is that you used a low value resistor (not something high like 4-10KOhm, which would be appropriate) and that your switch is hooked to ground and GPIO14.  When you close the switch, it connects the resistor to ground.  If the resistor is too low of a value, it will essentially short the power supply of the Sonoff and it will turn off.  Remove the resistor and see if that makes a difference.

Where is the Sonoff?  It is in the same box as the switch or a long distance away.

**Comment by Extinguo** [comment]
4.7k connected resistor to GPIO14 and 3.3v. I do have another 10k resistor lying around. Should I try to replace them? 
Switch is hooked up to ground and GPIO14
Sonoff is in the branching dose, about 2.5m away from the switch.

The weird thing is: I have another sonoff working perfectly fine in the same configuration. The problem first occured after updating went wrong and I had to reflash it. Already tried another brand new Sonoff and copying the configuration from the working sonoff 

Thanks for your help by the way.

**Comment by Frogmore42** [comment]
I don't know what else to tell you.  There is no way shorting GPIO 14 to ground should cause the Sonoff to shutdown.  Try it with a local switch.  Do you have a way to measure the actual value of the resistor?  Perhaps it is not what you think it is.

**Comment by Frogmore42** [comment]
The 4.7k resistor should be fine.

**Comment by ascillato** [comment]
Hi,

If your issue is solved, please close it. Thanks! :+1:
