### ISSUE TITLE
Provide MQTT controllable variables for use in rules

### ISSUE THREAD

**Issue by Stevehans** [arendst/Sonoff-Tasmota#2566]
I'd like to be able to push values from MQTT to affect rules (specifically I'd like to push a value for use in a thermostat).

I can see that variables have now been added, it would be great to be able to set these using MQTT commands so the value of a trigger point could be pushed to the device.

Such that the rule could be coded:-

on SENSOR#Temperature>%var1% do.....

**Comment by arendst** [comment]
To use values you simply send the complete rule again with your changed value. It's available now.

**Comment by Stevehans** [comment]
That would mean duplicating the rules for each of the potential controls that could change a value (and in fact, difficult to change more than one variable).

I'll cover this when I fork and see if you can accept the changes

**Comment by Stevehans** [comment]
Custom variables var and mem now addresses this.

Thanks, closing
