### ISSUE TITLE
Sonoff TH16 LED error

### ISSUE THREAD

**Issue by stoinov** [arendst/Sonoff-Tasmota#2572]
On my Sonoff TH16 with 5.12 and 5.10 before that, both LEDs are turning ON and OFF based on the relay.
As per [this post](https://loads.pickle.me.uk/2016/10/30/flashing-custom-firmware-to-a-sonoff-th10/16/), GPIO 13 is the Blue LED which should be linked to the WiFi status but it's not.

Flashed using the latest release bin.

**Comment by Frogmore42** [comment]
That post is not about Tasmota.  Here are the options for Tasmota
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#main
Look at Ledstate
What you are seeing is the normal default state.

**Comment by stoinov** [comment]
Thanks - that helped. ledpower 1 and ledstate 0 made it work as expected.
