### ISSUE TITLE
Sonoff POW R2 - Cannot get it to flash mode

### ISSUE THREAD

**Issue by completelyClueless** [arendst/Sonoff-Tasmota#2577]
Hi folks,

I cannot get my new POW R2 v1.0 to flash mode

Can you please post an image with marked GPIO0 ?
Thanks in advance

KR 
cc

**Comment by curzon01** [comment]
have a look on issue #1203

**Comment by completelyClueless** [comment]
Sorry, but it is not the same board
As i wrote above I have a POW R2 v1.0, not a POW (R1) v2.0
My board looks quite different...

**Comment by arendst** [comment]
GPIO00 is the button! so keep the button pressed when applying power to the serial interface and get going. The same procedure as before with the Pow non-R2

**Comment by completelyClueless** [comment]
Thank you - I was already confused from other/older postings...
