### ISSUE TITLE
Information to use RF remote with Sonoff WIFI Pro R2 on Tasmota 5.11.1

### ISSUE THREAD

**Issue by dastrix80** [arendst/Sonoff-Tasmota#2578]
Hi All,

Everything working nicely but I cannot work out how to pair the RF remote. RF remote worked fine on stock firmware, is there something I need to do different to pair my RF remotes with this unit now running Tasmota?

Thankyou

**Comment by dastrix80** [comment]
Edit: fixed. I had to power it from DC/AC for the RF process to work.

**Comment by ascillato** [comment]
great! please close the issue. thanks!
