### ISSUE TITLE
Backup -> Restore (master 5.13)

### ISSUE THREAD

**Issue by timtimsson** [arendst/Sonoff-Tasmota#2591]
Hello,
i have a proplem with backup -> restore in 5.13 master....

Program Version: **5.12.0**
Core/SDK Version:  **2_4_0_RC2/2.1.0(7106d38)**
backup->restore ok

then:
->upgrade with minimal -> upgrade 5.13 -> old config ok (WiFi, MQTT, module,gpios)
all sensor, rules etc works fine!
(Program Version: **5.13.0**
Core/SDK Version: **2_4_1/2.2.1(cfd48f3)**)
**but**
backup->restore: after reboot crash....

I take 2 different 8266-boards - same problem...

Does anybody have the same problem?
What am I doing wrong?

**Comment by arendst** [comment]
You're right. Problem. Will investigate.

**Comment by arendst** [comment]
It will fail with all core versions.

The cause is the new size of the configuration settings area overflowing the default HTTP_UPLOAD_BUFLEN of 2048 bytes.

Has been solved in development branch 5.13.0a
