### ISSUE TITLE
Bulgarian version not working

### ISSUE THREAD

**Issue by brandyhs** [arendst/Sonoff-Tasmota#2592]
Hello, i update the version to 5.13 classic and then i see there is a bg version.I updated it via OTA and my sonoff basic stop working. i tried to flash this firmware via esptool and not working again.Please fix it

**Comment by w2cker** [comment]
I also have problems with the dutch verion. Flashing the minimal version is working. The dutch precompiled bin version is not working. I tried a old sonoff and a new 2.0 version. Flashing back the old firmware restores the sonoff.

**Comment by arendst** [comment]
See update above

**Comment by arendst** [comment]
Dutch no problem either.

![image](https://user-images.githubusercontent.com/11044339/39482688-56a8b648-4d70-11e8-9062-2586348cc7da.png)

**Comment by w2cker** [comment]
I have tried flashing again. Now with the update 5.13.1 version. OTA to minimal is fine. Second step to 5.13.1 is flash fine but after reboot Wifi is not working. The led is flashing about twice every 2 seconds, and a Sonoff wifi_AP is sometimes visible, however unable to connect. Flashing by serial cable also has no effect.

**Comment by brandyhs** [comment]
my problem is the same as w2cker's
