### ISSUE TITLE
5.12 minimal seems not to be minimal

### ISSUE THREAD

**Issue by ACCakut** [arendst/Sonoff-Tasmota#2596]
I tried to update my Sonoff Basic and failed several times using the minimal-image from GitHub-releases (422 KBytes, MD5:1d570b43d33926cbeb005905ea85dbf8) but http://sonoff.maddox.co.uk/tasmota/sonoff-minimal.bin (433 KBytes, MD5: 7fb6d942ef382f92966355c2479e386b) worked like a charm.

First flashed with Arduino. 1MB no SPIFFS.

**Comment by arendst** [comment]
Released v5.13.1 is minimal and works as expected if downloaded form Github. I do not control Maddox versioning.

**Comment by ACCakut** [comment]
Since the new release is online the issue is not that relevant anymore and I close ;-)
