### ISSUE TITLE
[Wiki] NeoPixelBus.h is missing in Prerequisite

### ISSUE THREAD

**Issue by CWempe** [arendst/Sonoff-Tasmota#26]
Like mentioned in https://github.com/arendst/Sonoff-Tasmota/issues/6 you need to install the NeoPixelBus library to compile the default sonoff sketch.

This is not mentioned in the Wiki, yet.
https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite#arduino-ide-preparation

**Comment by ThomDietrich** [comment]
You should be able to edit the Wiki yourself ;)

**Comment by CWempe** [comment]
Done.
https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite/dda244269ef6dc3955e67dd981ea7ce59835c848

**Comment by ThomDietrich** [comment]
looks good ;)
