### ISSUE TITLE
Sonoff Dual

### ISSUE THREAD

**Issue by raisude** [arendst/Sonoff-Tasmota#260]
In the Module parameters of the sonoff dual gpio4 is used to configure a sensor. Where can i find gpio4 on the board?

Regards Rainer

**Comment by khcnz** [comment]
Use these resources
https://www.itead.cc/wiki/images/1/1d/Sonoff_Dual_View.pdf
http://tinkerman.cat/wp-content/uploads/2016/12/20161206_234331s.jpg
https://espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf

From that it appears its the unconnected pin on the bottom right of the ESP - i hope you have a fine soldering iron and you probably want to consider an external resister.

There wasn't an immediate google search that returned the result so it would be great if  you could capture on the wiki

**Comment by Satellietje** [comment]
![22-3-2017 20-37-00](https://cloud.githubusercontent.com/assets/26080895/24217260/91b49448-0f3f-11e7-856b-47b2e6f0cf30.png)

**Comment by raisude** [comment]
Is this one wire as a bridge. Or are this two wires? And where can I connect the data wire of the sensor?

Regards Rainer

**Comment by davidelang** [comment]
that would be the sensor data wire. Your sensor probably also needs 3.3v and ground connections (depending on what you are connecting)

**Comment by raisude** [comment]
But the picture shows to solder points on the board. By looking at the picture I see one orange wire on the top and one yellow bellow. The yellow one ist the data connection? And what is the other one?

**Comment by Satellietje** [comment]
The Orange is GPOI0 for start programming

**Comment by Satellietje** [comment]
![relais](https://cloud.githubusercontent.com/assets/26080895/24261973/f3627386-0ff8-11e7-94b2-d4f3ef612b93.png)

Lovely toys, the sonoff :-)

**Comment by davidelang** [comment]
It appears that this issue has been solved, if there are other questions, please reopen this issue.
