### ISSUE TITLE
include pubsubclient.h

### ISSUE THREAD

**Issue by Knut91** [arendst/Sonoff-Tasmota#2601]
Hi

I am a really amateur and cant figur this out.
I tried updating everything and to download everything again, but i get the same error everytime, i dont know what i am doing wrong when it worked last week.

I saw and did this one:  

 _**Prerequisites:
    - Change libraries/PubSubClient/src/PubSubClient.h
        #define MQTT_MAX_PACKET_SIZE 1000**_

This is the error:

C:\Users\km_st\Downloads\Sonoff-Tasmota-development\Sonoff-Tasmota-development\sonoff\xdrv_00_mqtt.ino:68:26: fatal error: PubSubClient.h: No such file or directory

 #include <PubSubClient.h>

                          ^

compilation terminated.

exit status 1
Error compiling for board Generic ESP8285 Module. 

Thanks in advanced

**Comment by Knut91** [comment]
Thank you for the help!

I will try this today !

**Comment by alton76** [comment]
If you are still going with the IDE route, check your arduino library if
you have the Pub Sub client flies.

On the latest Tasmota versions you don't have to change anything. Just copy
the flies into the right folders and you good to go.

**Comment by Knut91** [comment]
I tried That, But i got the same error anyway...

**Comment by Knut91** [comment]
Thank you for the tip Jason2866 , it work great with platformIO !
