### ISSUE TITLE
firmware upgrade OTA problem

### ISSUE THREAD

**Issue by chris-008** [arendst/Sonoff-Tasmota#2602]
Hi,
Referring to a previous issue #1710, i still have a similar problem:
while trying to upgrade a Sonoff TH10 module , flashed with  a minimal 5.10.0 version, I get next message in the web interface:
Upgrade started ...
Device will restart in a few seconds

This screen stays like this for minutes and I hear the module clicking every now and then but nothing much happens. When I press the main menu button, the module doesnt get recognized anymore via the web browser and I have to reflash all over.

any ideas what could go wrong?
I am using http://sonoff.maddox.co.uk/tasmota/sonoff.bin  as an OTA link

since http://domus1:80/api/arduino/sonoff.ino.bin is not working.

 thanks for your feedback!

**Comment by chris-008** [comment]
Thanks for the update. 
I just copied all parameters from my last working veriosn 5.10.
However, with this new 5.13.1 firmawre I get a COM port problem:
Use manually specified: COM5
error: cannot access COM5

When i do the same with ver 5.10, all is working fine (port gets selected automatically)
Where should I change this setting in ver 5.13.1?

; *** Upload Serial reset method for Wemos and NodeMCU
;upload_speed = 115200
upload_speed = 512000
upload_resetmethod = nodemcu
upload_port = COM5  //tried all from 1 to 5

**Comment by Frogmore42** [comment]
Don't specify the com port or figure out which com port it really is.  On Windows you can use Device Manager to list all the com ports on your PC.

**Comment by chris-008** [comment]
Thanks for your feedback. I use a MacBook. Wit a precious firmware Version (5.10.0) , the same port (5) is auto detected and works just fine?

**Comment by Frogmore42** [comment]
I don't have a Mac so I don't know what error it gives if the com port is already open.  On Windows, the tool automatically detects the right com port on all my PCs.  I can also use Device Manager to see all the com ports.  I don't know if the Mac has a similar tool.

I don't believe the FW makes a difference on finding or opening the com port.  So either the com port is in use (did you have the serial monitor on earlier) or it is something else.

**Comment by chris-008** [comment]
This is what I found:


FT232R USB UART:

  Productcode:	0x6001
  Fabrikantcode:	0x0403  (Future Technology Devices International Limited)
  Versie:	6.00
  Serienummer:	A50285BI
  Snelheid:	Maximaal 12 Mb/sec
  Fabrikant:	FTDI
  Locatiecode:	0x14200000 / 12
  Beschikbare stroom (mA):	500
  Vereiste stroom (mA):	90
  Extra stroom in werking (mA):	0

So no specific port mentioned.
Isn't there a way to have the port detected automatically, as in previous builts?

**Comment by chris-008** [comment]
in eg. 5.10 (working version) there is this code:

:[env:sonoff]
platform = espressif8266
framework = arduino
board = esp01_1m
board_flash_mode = dout
build_flags = -Wl,-Tesp8266.flash.1m0.ld -DMQTT_MAX_PACKET_SIZE=512
lib_deps = PubSubClient, NeoPixelBus, IRremoteESP8266, ArduinoJSON

; *** Serial Monitor options
monitor_baud = 115200

; *** Upload Serial reset method for Wemos and NodeMCU
;upload_resetmethod = nodemcu

In the 5.13 version:
; *** Upload Serial reset method for Wemos and NodeMCU
;upload_speed = 115200
upload_speed = 512000
upload_resetmethod = nodemcu
upload_port = COM5

uncommenting the last two lines compared to the 5.10 built creates new errors.

**Comment by Frogmore42** [comment]
Since you don't have a Wemos/NodeMCU, you don't need to uncomment that line.  I never specify a COM port and it always finds it, so I don't believe you need to uncomment the COM port line either.  512000 is also way too fast for most adapters that use long wires.  So, make it look like it did before, ie comment everything except the line that has the upload speed of 115200.

**Comment by chris-008** [comment]
So the 5.13.1 upload worked like a charm.
The update procedure however is still a bit of a mystery...

After I tried to upgrade the firmware from minimal to standard sonoff firmware through the web interface (after resetting the module first), I get the update screen hanging indefinitely 

<img width="425" alt="schermafbeelding 2018-05-08 om 23 16 45" src="https://user-images.githubusercontent.com/32146240/39784507-e90a5750-5318-11e8-83a9-17b16c261bc3.png">

and got next readout from Atom, indicating a WIFi connect problem:

<img width="964" alt="schermafbeelding 2018-05-08 om 23 27 10" src="https://user-images.githubusercontent.com/32146240/39784120-a27b4638-5317-11e8-9d44-a315ec8fd76c.png">

The module is an an infinite loop searching for wifi, with LEDS flashing in intervals.

I have WIFI_MANAGER as wifi config tool set.

**Comment by chris-008** [comment]
Wifi manager doesn't seem to work either, 192.168.4.1. is not showing the UI.

**Comment by Frogmore42** [comment]
Some people have a problem with core 2.4.0 (which the FW you built is using).  You might try rebuilding the FW with 2.3.0.  There should be a line near the top that tells PlatformIO which core to use.  I believe there are several lines there (to show the possibilities).  Uncomment the one with 2.3.0 and comment the one that is currently uncommented.

**Comment by chris-008** [comment]
Do you mean this part:
<img width="648" alt="schermafbeelding 2018-05-11 om 00 08 55" src="https://user-images.githubusercontent.com/32146240/39896712-95d4ac96-54af-11e8-9bb8-5a8a70b8c31b.png">

**Comment by Frogmore42** [comment]
Yes, that is the part, comment the one that doesn't specify and uncomment the one with 2.3.0

**Comment by chris-008** [comment]
Hi Frogmore,  thanks again for the feedback, will try soon.

**Comment by chris-008** [comment]
Hi, So I changed as per your proposal:

[common] ; ************************************************************
; *** Esp8266 core for Arduino version
platform = espressif8266@1.5.0  ; v2.3.0
;platform = espressif8266@1.6.0  ; v2.4.0
;platform = espressif8266@1.7.0  ; v2.4.1
;platform = espressif8266

Still the module hangs in upgrade mode. 
Every 45s. I hear the module clicking but no upgrade still.

**Comment by Frogmore42** [comment]
If you have a serial connection, there is no need to upgrade.  Just flash the full version, not the minimal one.  The minimal one is for use with Over The Air FW update.

Include the log if you have any more problems.

**Comment by chris-008** [comment]
No, it doesn't help

**Comment by mikeyford** [comment]
Quick note for any mac OSX users that come across this, as I did:

Replace `COM5` in platformio.ini with the full path to your serial-usb device. You can find the path by entering `ls -l /dev/tty.*` in the terminal. For example, I changed my entry to this:
`upload_port = /dev/tty.usbserial-A602286D` and was good to go.
