### ISSUE TITLE
wifi/network problems 5.13.1

### ISSUE THREAD

**Issue by alofi198** [arendst/Sonoff-Tasmota#2605]
Hello,
i have a problem with sonoff basic and wemos d1 mini, after flashing the new 5.13.1 i have bad wifi/network connections (connection lost). the devices are not far awaye from the ap.
with 5.12 i had no problems
wificonfig is "0"

thanks

**Comment by mpuff** [comment]
Hello,
i had the same issue with the 5.12 and the sonoff t2 (4 devices), i lost many pings.
i had flashed back to 5.11, now all t2 working very well.

**Comment by KoLSMS** [comment]
Hello,

same problem here! wifi quality is poor with 5.13.1, i have changed not the postions of my sonoffs, after upgrade to 5.13.1 there were not longer reachable via wifi... when i bring them near to my router all works again so there must be an error with the wifi in this update...

maybe it will be fixed?!?! thx for help

**Comment by curzon01** [comment]
If you compile your firmware by yourself, try [switch to lib 2.3.0](https://github.com/arendst/Sonoff-Tasmota/wiki/Theo's-Tasmota-Tips#20180103---tasmota-is-ready-for-esp8266arduino-version-240) instead of the default 2.4.0.

Personaly I still have a lot of Wifi and Web-Interface troubles using lib 2.4.0 and the last binary release was compiled using lib 2.4.0. When I'm using same Tasmota version which causes troubles using lib 2.3.0 all problems are gone. This is not common but try this step.

**Comment by KoLSMS** [comment]
maybe the devs here compile a new version with lib 2.3.0 because there are many users with the wifi issue?!?! would be great, i am no expert and do not know how to comile a new Tasmota with 2.3.0 lib :(

**Comment by rlust** [comment]
Having wifi issues also, has become very unstable with the latest releases.

**Comment by alofi198** [comment]
@curzon01 
i have compiled my firmware with lib 2.3.0, upload it via web but same issue...
in the platformio.ini i uncomment "platform = espressif8266@1.5.0  ; v2.3.0"

**Comment by alofi198** [comment]
fyi
when i compile with lib 2.4.1 i have no problems with wifi!

**Comment by Jason2866** [comment]
My test device works without any problem since 1 day...
![screenshot_20180502-193935](https://user-images.githubusercontent.com/24528715/39539721-b9b6fe7c-4e40-11e8-9f35-49f0cc3405f5.png)

**Comment by KoLSMS** [comment]
This is 5.13.0a and not 5.13.1.......

**Comment by dezral** [comment]
my Sonoff basic also does wifi very bad with 5.13.1, im back om 5.12.0 and working again.. my Sonoff TH10(with sensor) have no problems.

im using the release bin file sonoff.bin and upgraded through web interface.

i even try'd resetting the 5.13.1 to default settings and setup again.. no lock.

**Comment by Jason2866** [comment]
Makes no difference. Compiled 5.13.1a is working too. 
I use Arduino 2.3.0. With later versions i do have problems with wifi (reconnects) 
and unresponsive web interface

**Comment by tikkerei** [comment]
Same here, after updating from 5.12.0 -> 5.13.1 all sonoff's basics have wifi problems. The sonoff S20 switches no problems.

**Comment by Einstein67** [comment]
No Problem here with the Basics, compiled with "Core-/SDK-Version | 2_3_0/1.5.3"

All are working fine. WLAN is quite good!

**Comment by raneri** [comment]
Same here. I want to add that, for me and my Sonoff Basic, problems starts only when I configure it with my MQTT server. Before that, WiFi/web control seems to work properly. No problems at all with 5.12.0

**Comment by C05M1N** [comment]
5.12.0 was fine for me either
**but**
after ota update from 5.12.0 -> 5.13.1 wifi keeps disconnecting

**Comment by nunoronconcouto** [comment]
I downgrad to 5.13.0 and the problems stop.

**Comment by rlust** [comment]
I recompiled 5.13a with Arduino 2.3.0 on SONOFF basic Sonoff TH and WEMOS D1 mini, and now they have stayed connected for 10 hours, prior dropping every few minutes. Was using 5.1.3 prior.

**Comment by wongnam** [comment]
My Sonoff Basic, Sonoff S22, Sonoff Dual R2, Sonoff Bridge, Sonoff Touch US are working normally with no WIFI issue.
Firmware info:
- Self compiled version 5.13.1 (using latest version of VSC+PlatformIO)
- ESP8266 Core version 2.3.0
- Tasmota-MQTT

![image](https://user-images.githubusercontent.com/36041520/39558877-720b76bc-4ebc-11e8-8179-de2e10b7f7a6.png)

Regards,

**Comment by alofi198** [comment]
i use Atom with platformio, i have compiled with core lib 2.4.1... no more problems with wifi

![grafik](https://user-images.githubusercontent.com/38906755/39566764-f4d43a02-4ebc-11e8-8ea4-d1e17492f73c.png)

**Comment by alton76** [comment]
Give Tasmota 5.13.1a and ESP V2.4.1 a try. I've been running for two days
straight, no complains.


Previously I was running Tasmota 5.12.1i and V2.4.0 and V2.30, lots of
problems, frequent disconnection, unable to reach web server.

**Comment by KoLSMS** [comment]
I switched back to 5.12.0, will wait for official fix for the wifi problems, maybe in the next release...

**Comment by bachya** [comment]
Same here. Both of my existing Sonoffs are close to their AP (90+%) and ran flawlessly for months on 5.12 Upgraded to 5.13.1 last night and since then, both sporadically drop offline on a regular basis. Updated OTA, first using the `minimal` variant (just in case), then using the regular variant.

**Comment by wasi54** [comment]
One more Test with 5.13.0a, core 2.3.0. Compiled with atom and plattformio.
Also OK and stable.
![sonoff-th_2018-05-03_22-29-39](https://user-images.githubusercontent.com/6075168/39601296-c08fe72c-4f21-11e8-9d66-723c6933f1ae.png)

**Comment by wasi54** [comment]
TH Module, ws OK with 5.13.0a and core 2.3.0. Now failed with core 2.4.1 and compiled with atom and plattformio.
```
PING 192.168.0.1 56(84) bytes of data.
64 bytes from 192.168.0.1: icmp_seq=13 ttl=255 time=810 ms
--- 192.168.0.1 ping statistics ---
28 packets transmitted, 1 received, 96% packet loss, time 27686ms
rtt min/avg/max/mdev = 810.227/810.227/810.227/0.000 ms
```
Webserver not responding either!

**Comment by bachya** [comment]
Following up: I've been running 5.13.1 with ESP 2.4.1 for 24 hours with no issues.

**Comment by JueBag** [comment]
Did observe the reconnection problem on  the version 5.13.1 downloaded from maddox.

**Comment by JueBag** [comment]
Did some more test:
When using the update as provided by http://sonoff.maddox.co.uk/tasmota/sonoff.bin it uses Tasmota 5.13.1 with Core/SDK Version  2_4_0/2.1.0(deb1901).
On this version I do get connection problems,  starting single with MQTT reconnects soon to be reconnects by the minute.
Reverting back to 5.12.0 using 2.3.0 this problem is gone.

**Comment by JueBag** [comment]
Absolutely true!
However both versions used so far are only downloaded ( either from the site posted above or from GitHub as for the 5.12.0 version). Doing the regression test on both did take a while.
Just wanted to point the differences. 
What I read in that whole thread a test with 5.13.1 using 2.4.1 could be woth a try. Since I didn't compile with different library's yet,  that will take some time.

**Comment by leranp** [comment]
I'm also have connections problem after update from 5.12 to 5.13.1, it's happening only with Sonoff basic RF, the rest of the devices are o.k

**Comment by apastuszak** [comment]
Are there instructions on how to compile a Sonoff minimal and regular sonoff image for OTA uploads?  It looks like using anything other that 2.4.0 seems to resolve the issue.  But I really don't want to gather all my Sonoffs up and serially flash them.

**Comment by ConfusedTA** [comment]
Updated my 5x Sonoffs to 5.13.1 using OTA method from http://sonoff.maddox.co.uk/tasmota/sonoff.bin

2 of them are stuck on the "minimal" firmware and won't connect to my WiFi, the other 3 have updated, and only 1 (a T-1) is working. The others that have at least completed the update are continually rebooting.

I've managed to downgrade these 3 to 5.12, but my other two might need some manual intervention to get them up and running again. Thankfully they're only running my heating, and it's currently blisteringly hot here, so I can spend the next couple of days looking into it, but a shame so many of us seem to have encountered such a serious issue, especially when the OTA update has worked spectacularly well in the past.

Despite my complaints above, I must extend my thanks for the work you put into this :)

**Comment by apastuszak** [comment]
@Jason2866 Can these be used to do an OTA update?

**Comment by Jason2866** [comment]
@apastuszak 
If you compile yourself you upload it via the webconsole "Upgrade by file upload"

**Comment by apastuszak** [comment]
Compiled using Platform I/O using Core 2.4.1.  Flashed one switch just now and it's up and running without issues.  Granted it has only been 5 minutes, but the provided binaries crapped out pretty much instantly.

Sounds like we may just need binaries. recompiled and rereleased.

**Comment by JueBag** [comment]
Running a test with a self-compiled version using 5.13.1 and 2.4.1 on a sonoff th as well. Let's wait till tomorrow.

**Comment by JueBag** [comment]
VSCode with PlatformIO

**Comment by apastuszak** [comment]
@jeylites I also compiled using Visual Studio Code with Platform IO.  I uncommented the line that made it use 2.4.1.  It's up a running on one Sonoff Basic.

I'm able to use HomeAssistant to turn the switch on and off, and my automations are working and sending alerts to my phone.   I can put my binaries up somewhere if you wan to give them a try.

**Comment by jeylites** [comment]
I wonder if the kind compiler used has got any influence in core 2.4.1 reliability? I have yet to toy with Platform Io, see complicated to set up for me...

**Comment by JueBag** [comment]
The sonoff TH semi to be running stable, only one MQTT reconnect since yesterday. The sonoff RF however is showing those now once per hour.
Will continue to monitor.

**Comment by jeylites** [comment]
@JueBag 
> The sonoff TH semi to be running stable, only one MQTT reconnect since yesterday. The sonoff RF however is showing those now once per hour.
Will continue to monitor.

good to know, I flashed Sonoff T1 UK 12 hours ago with Platform Io 1.26.1 OSX, so far no MQTT connections problem. Same setup with Arduino IDE 1.8.5 OSX I had MQTT receiving issues couple mins in despite having a solid wifi and broker connection. Not sure what is going on but seem working now. Config as follow. The only problem I have now is web server becomes unresponsive after a while, the only way to gain access is a router reboot or sonoff reboot. During that time, I'm still able to control the switches through MQTT.

Core 2.4.1
Tasmota 5.13.1a

**Comment by jeylites** [comment]
**Status 0** 

```
01:27:40 MQT: stat/ve1/STATUS = {"Status":{"Module":30,"FriendlyName":["VE 1","VE 12","VESHINU 13"],"Topic":"ve1","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
01:27:40 MQT: stat/ve1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Exception","Uptime":"0T01:27:37","StartupUTC":"","Sleep":0,"BootCount":14,"SaveCount":97,"SaveAddress":"FB000"}}
01:27:40 MQT: stat/ve1/STATUS2 = {"StatusFWR":{"Version":"5.13.1a","BuildDateTime":"2018-05-09T13:43:48","Boot":31,"Core":"2_4_1","SDK":"2.2.1(cfd48f3)"}}
01:27:40 MQT: stat/ve1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SUGAR1","SUGAR2"],"TelePeriod":300,"SetOption":["0200A009","55818000"]}}
01:27:40 MQT: stat/ve1/STATUS4 = {"StatusMEM":{"ProgramSize":472,"Free":528,"Heap":17,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
01:27:40 MQT: stat/ve1/STATUS5 = {"StatusNET":{"Hostname":"ve1-1256","IPAddress":"192.168.0.24","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"60:01:94:97:44:E8","Webserver":2,"WifiConfig":4}}
01:27:40 MQT: stat/ve1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.200","MqttPort":1883,"MqttClientMask":"24","MqttClient":"24","MqttUser":"admin","MqttType":2,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
01:27:40 MQT: stat/ve1/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 01:27:40 1970","Local":"Thu Jan 01 01:27:40 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":8}}
01:27:40 MQT: stat/ve1/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T01:27:40"}}
01:27:40 MQT: stat/ve1/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T01:27:40","Uptime":"0T01:27:37","POWER1":"ON","POWER2":"OFF","POWER3":"OFF","Wifi":{"AP":1,"SSId":"SUGAR1","RSSI":100,"APMac":"88:D7:F6:02:18:80"}}}
```

**Comment by wasi54** [comment]
@jeylites 
Core 2.4.1 with Tasmota 5.13.1a bult with atom and platformio
Yes, the webserver becomes unresponsive after a while on my sonoffs to (Basic, T and Pow). Also MQTT connection remains stable. 
And the verry good thing is, every on my sonnoffs can be restartet vie MQTT commands and up/downgradet as well, even while website is unresponsive.
So, no need for router reboot.

**Comment by apastuszak** [comment]
@wasi54 Have you tried 5.13.1?

**Comment by wasi54** [comment]
No longer Problem with the Webserver with
Program Version: 5.13.1a
Build Date & Time: 2018-05-08T00:42:09
Core/SDK Version: 2_4_1/2.2.1(cfd48f3)
Uptime: 1T01:02:22
Free Memory: 20kB

Disabled as mutch as possible which i do not need like sensors which i not have, mDNS Discovery and more to get Free Memory > 20kB.

**Comment by wasi54** [comment]
@apastuszak 
I have some with 5.13.0 / 2_3_0/1.5.3(aec24ac9)  uptime more than 8 day's and stable.
Currently i have no device with  5.13.1 !

**Comment by JueBag** [comment]
I have all actually used sonoff switches (dual R2, RF and TH) on the self-compiled version 5.13.1 ( using  

2_4_1/2.2.1(cfd48f3)).

I see occasional the following log entrys:

>13:15:53 DNS: initialisiert
>13:15:53 MQT: Verbindungsversuch...
>13:15:53 MQT: verbunden
>13:15:53 MQT: tele/sonoff_TH/LWT = online (beibehalten)
>13:15:53 MQT: cmnd/sonoff_TH/POWER = 

As they are not coming more then once an hour I'll stick with this one for the time being.
Have also observed times when the webserver was unresponsive,  MQTT commands where performed on time during those occasions.

**Comment by wongnam** [comment]
Last time all my sonoff used 
- self compile FW (VSC + PlatformIO)
- Tasmota 5.13.1
- ESP8266 core version 2.3.0
- Tasmota MQTT
- wifi signal are in good condition.

My sonoff (Basic, S22, Dual R2, RF Bridge, Touch US) encountered the same issue with the WebServer was unresponsive but MQTT pub and sub were still performed accordingly.

My workaround:
- self compile FW (VSC + PlatformIO)
- Tasmota 5.13.1
- ESP8266 core version 2.3.0
- ESPMQTT ( the third library)

Now all sonoff are working normally for a couple of days. 
I am still monitoring them.

Regars.

**Comment by joopy** [comment]
Had the same problems, I fixed it with recompiling and installing 5.13.1a with arduino ide.

**Comment by brainnex** [comment]
Hello everybody,
I just updated one Sonoff RF to the provided 5.13.1 .bin and have massive Wifi/Mqtt problems like other here reported. It has become unusable. Has anybody a 5.13.1a bin?? Before I was on 5.12 without any problems. Would like test this release.

Tasmota 5.13.1:
Program Size	529kB
Free Program Space	472kB
Free Memory	18kB

**Comment by apastuszak** [comment]
It's pretty easy to compile yourself.  I could make you some binaries.  But I need to know your timezone and your timezone rules to get it right.

**Comment by joopy** [comment]
Sonoff-Tasmota 5.13.1a by Theo Arends my sonoff bin's but wouldn't work unless you have the same wifi setup.
http://www.dampsap.nl/tasmota/sonoff-TSL2561.bin
http://www.dampsap.nl/tasmota/sonoff.bin

**Comment by ascillato** [comment]
Hi, I also made the bins for testing in all languages at https://github.com/ascillato/Sonoff-Tasmota_KNX/releases/tag/v5.13.1a
Compiled using ESP8266 Board Library v2.3.0 and lwIP v1.4

**Comment by brainnex** [comment]
thanks Joopy, your version works like a charm. Wifi/mqtt problems are gone. My sonoff kept my Wifi Settings. Just OTA flashed and worked.

**Comment by ascillato** [comment]
From the console you can type timezone 1 and it will change

**Comment by daballiemo** [comment]
I experienced the same problems with 5.13.1a on 17 out of 22 devices. Now back at 5.12.0 and all is stable again

**Comment by arendst** [comment]
@ascillato AFAIK there is no choise for lwIP 1.4 in core 2.3.0...

If you need it for knx can you pls test knx with core 2.3.0 before I release?

I'm off today so do not expect a release before wednesday.

**Comment by mcc05** [comment]
So I've turned off auto discovery e.g mDNS in userconfig.h in all Tasmota build since 5.12 and I don't have any MQTT connection issues

**Comment by electrontube** [comment]
General question:

Is it really a good idea to compile with Core 2.3.0?
Please remember the KRACK vulnerability!

I think we urgently need a version that runs stable on core 2.4.x

**Comment by ascillato** [comment]
Hi,

Up to now, the core 2.4.1 has a lot of wifi issues. You can compile Tasmota with 2.4.1 and use it, but sleep is disabled (because it hungs the device). It is not stable. Nevertheless, I have few Tasmotas with 2.4.1 for testing. Yes, works, but sometimes it hungs. I also have other small proyects with esp8266 and 2.4.1 and with the same problems.

Hope that the people from esp8266/arduino make a new release of the core soon :+1:

**Comment by erwini** [comment]
Hi,
Tested also my sonoff stuff. Strange results
Images got precompiled from the website
All tested on the same physical **sonoff basic modul**.
- ok: 
tasmota  version 5.11.1, Core-/SDK-Version: 2_3_0/1.5.3(aec24ac9), Build Date: 2018.01.07 21:51:30, imagename: sonoff-DE.bin
- bad:
tasmota version 5.12.0, Core-/SDK-Version: 2_3_0/1.5.3(aec24ac9), Build Date: 2018.02.09 14:55:34, imagename: sonoff-DE.bin
- ok:
tasmota version 5.12.0, Core-/SDK-Version: 2_3_0/1.5.3(aec24ac9), Build Date: 2018.02.09 14:55:34, imagename: sonoff-ds18x20.bin
- very bad:
tasmota version 5.14.0, Core-SDK-Version: 2_3_0/1.5.3(aec24ac9), Build Date: 2018.05.15 15:18:52, imagename: sonoff-allsensors.bin

AP is 4m away
- ok means: WIFI stable, Pings ok
- bad means: WIFI stable but with long delay and many packet loses, some pings are working
- very bad: No WIFI connection. Connection with tablet 5cm away not possible ("192.168.4.1 mode")

Tested as well with **sonoff socket modul**
All above tested images run perfect on this device.

Interesting:
- Core/SDK Version is equal on all images
- different language breaks the WIFI in 5.12.0 on **sonoff basic modul**. What is different between them ?

Hope it helps to figure out, why 5.14.0 is not working with **sonoff basic modul**

**Comment by wasi54** [comment]
@erwini 
Can you check the "Free Memory" for binaries with ok and bad binaries?
Different languages may consume more Memory.
5.14.0 is running since weeks without issues on my side with both core 2.3.0 and 2.4.1 with lwIP 1.4. as long the free Memory is at least 18kB or higher.
Also with:
![image](https://user-images.githubusercontent.com/6075168/41376803-99be46ee-6f5a-11e8-907e-8f044e1c6c3c.png)
![image](https://user-images.githubusercontent.com/6075168/41376843-b00eef2a-6f5a-11e8-8575-c319ca5a0a67.png)

**Comment by wasi54** [comment]
@arendst 
Meanwhile i have compiled 5.14.0 with 
![image](https://user-images.githubusercontent.com/6075168/41456200-02da5750-7080-11e8-8077-dd7fd5a37579.png)
and 
![image](https://user-images.githubusercontent.com/6075168/41456231-1c47a4e0-7080-11e8-8a16-5bc83273589d.png)
This works fine and stable on a basic, TH and Dual-V2 Module!
While firmware with the Buildflag
![image](https://user-images.githubusercontent.com/6075168/41456327-63e12bbe-7080-11e8-96be-a3f67b7c200b.png) only works on TH and Dual-V2.
On the Basic Module it results with:
00:00:10 MQT: tele/sonoff/INFO3 = {"RestartReason":"Fatal exception:28 flag:2 (EXCEPTION) epc1:0x40270f8e epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000"}

**Comment by erwini** [comment]
Meanwhile setup platform.io for compilation without luck.
Moved to arduino ide 1.8.5. Compiled there version 6.0.0a
Tested with a sonoff basic modul with english language.
Core/SDK Version: 2_4_1/2.2.1(cfd48f3)
Tested wlan and it works perfect.

**Comment by erwini** [comment]
Compiled with german language. Wlan works perfect. Conclusion: use the newest software.

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.
