### ISSUE TITLE
Any way to "discover" sonoff tasmota devices on WiFi only (no Internet)

### ISSUE THREAD

**Issue by anoop-r-kulkarni** [arendst/Sonoff-Tasmota#2606]
I have been successfully using the MQTT discovery and scanning status messages helps me build a list of devices currently powered on and connected to the WiFi. I am looking for solutions to see if this equivalent discovery is possble in "no Internet" scenario (that is WiFi only). If I am using an Android app for this, is my only solution to build a local MQTT broker in the app or is there a simpler way of discovering connected devices that are powered on at a given instant?

Thanks and regards
~anoop

**Comment by Jason2866** [comment]
Take a look in your DHCP Server. Normally this is your router. You can see here which device has a lease and the IP and in most cases the name of the device...

**Comment by enesbcs** [comment]
There are a network scanner named ESPFinder-python which shows active Tasmota and ESPEasy devices on the LAN. Mainly for linux, partially works for windows. For android i have no idea.
![espfinder](https://user-images.githubusercontent.com/31168072/39629956-25b2658a-4fae-11e8-9a41-6ed8912a696a.jpg)

**Comment by anoop-r-kulkarni** [comment]
Thanks.. did it the brute force way by pinging each IP for 255 devices in the subnet..

**Comment by ascillato** [comment]
Hi,

You can use also https://github.com/reloxx13/tasmoAdmin

**Comment by anoop-r-kulkarni** [comment]
thank you.

I am stll trying to figure out an optimal setup. We have 30+ TH16 
connected to ducted Air Conditioners at a faciltiy and other than MQTT, 
trying to figure out what is the most optimal way of accessing all the 
devices with the local WiFi

Will explore TasmoAdmin as well.

Thanks a lot..

Best,
~anoop

------------------------------------------------------------------------

*From:* Adrian Scillato
*Sent:* Saturday, June 02, 2018 10:00AM
*To:* Sonoff-Tasmota@noreply.github.com
*Cc:* anoop.r.kulkarni@gmail.com, state_change@noreply.github.com
*Subject:* Re: [arendst/Sonoff-Tasmota] Any way to "discover" sonoff 
tasmota devices on WiFi only (no Internet) (#2606)

Hi,

You can use also https://github.com/reloxx13/tasmoAdmin

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub 
<https://github.com/arendst/Sonoff-Tasmota/issues/2606#issuecomment-394057426>, 
or mute the thread

**Comment by ldijkman** [comment]
esp32 as scanner / webserver
and serves a control webpage of scanned found devices
forward 1 esp32 to control all tasmotas from anywhere 

https://www.youtube.com/watch?v=ksKX85hvpI0

**Comment by sfromis** [comment]
Warning: Ancient thread....

Without the benefits of using MQTT (recommended), one simple way of Wifi Tasmota device discovery would be to sweep the available IP addresses with http requests, and look for response headers like:
`Server: Tasmota/15.2.0.3 (ESP8266EX)`

You could also have the http request be a command like `http://192.168.0.123/cm?cmnd=Status` to get some more data.
