### ISSUE TITLE
Support incrementing a value (published by MQTT) as the button is pressed and held

### ISSUE THREAD

**Issue by foxy82** [arendst/Sonoff-Tasmota#2607]
I'm thinking of using these in a slightly different way to standard.

I want to install something like the Sonoff T1 in a wall box with 240v power but nothing connected to the relays. I'd then like to press and hold the switch and every 0.5 seconds (configurable) it would increment a value from 0 to 100 (to represent a dimming percentage) I'd then use Openhab or Home Assistant to use this value to send a message to other home automation devices (e.g. Z Wave dimmers/hue bulbs). 

Is this something that could be done? If so what code would need to be changed?

**Comment by Leseratte10** [comment]
I'd like to have something like this as well - on button HOLD, tell the MQTT broker how long the button was held.
