### ISSUE TITLE
no space available on S20, even with minimal

### ISSUE THREAD

**Issue by fragolinux** [arendst/Sonoff-Tasmota#2610]
starting from tasmota 5.12.0-IT(alian) on sonoff s20, tried to upload 5.13.1 minimal (433kb) before doing the 5.13.1-IT, but it says not enough space on device... tried 5.12.0-minimal (422kb), same issue... so, how to update to latest firmwares if even minimal ones are too big? :(
p.s.: not online ota, i downloaded .bin files from releases page

**Comment by Leseratte10** [comment]
What does the information page say? How much space is currently used and how much is free? If you have less free flash than the minimum requires for some reason, OTA wouldn't work and you'd need to flash over serial.

**Comment by fragolinux** [comment]
@Leseratte10 
sorry if translation is not perfect, i'm on an italian firmware as said so those infos are in italian, here the relevant parts

ESP Chip Id	364171
Flash Chip Id	1327328
Flash Size	1024kB
Program Flash Size	4096kB
Program Size	486kB
**Free Space Program Memory	516kB**
Free Memory	22kB

**Comment by arendst** [comment]
The program flash size is wrong. Should have been 1024 if you used the initial linker 1MnoSpiffs as shouting from the readme.md.

Also your physical flash is 1024.

Only solution is serial upload using the correct memory model.

**Comment by fragolinux** [comment]
ok, i'll do it tomorrow, thanks both :)

**Comment by fragolinux** [comment]
all done, thanks! Flashed as you said, then tried, it worked, so i tried to do an ONLINE ota to same firmware but minimal, no problems, then i remade OTA but this time by uploading latest "IT" firmware from my pc, no problems!
