### ISSUE TITLE
5.13.0 or 5.13.1: not flash or upgrade 

### ISSUE THREAD

**Issue by RWGaMeR** [arendst/Sonoff-Tasmota#2611]
Good morning,
I tried the firmware (5.13.0 - 5.13.1) on two Sonoff Basic, but only give problems because they do not remain active or do not remain active the WiFi and the MQTT protocol from many problems.

I wait for these problems to be solved

**Comment by reloxx13** [comment]
change and try 2.3.0 framework

**Comment by RWGaMeR** [comment]
Do i have to do?

**Comment by RWGaMeR** [comment]
@reloxx13 Do i have to do?

**Comment by reloxx13** [comment]
build the firmware yourself (suggest to use atom and platformio ([Guide](https://github.com/arendst/Sonoff-Tasmota/wiki/Beginner-Guide---Create-your-own-Firmware-Build)).


change to 
`platform = espressif8266@1.5.0  ; v2.3.0`
in the platformio.ini file


i noticed wifi disconnects with 2.4.0 and 2.4.1, check your router log to get the disconnects. mine was flooded with disconnects every few minutes.

**Comment by RWGaMeR** [comment]
@reloxx13  Thanks, I'll try tomorrow

**Comment by nunoronconcouto** [comment]
i downgrade to 5.13.0...

**Comment by RWGaMeR** [comment]
@nunoronconcouto 
I have already downgraded to 5.13.0, but it does not work well the same, I had to go back to 5.12.0

**Comment by pReya** [comment]
Same problem here, many WiFi disconnects with 5.13.1 (precompiled binary version).

**Comment by alton76** [comment]
Give Tasmota 5.13.1a and ESP V2.4.1 a try. I've been running for two days
straight, no complains.


Previously I was running Tasmota 5.12.1i and V2.4.0 and V2.30, lots of
problems, frequent disconnection, unable to reach web server.

**Comment by RWGaMeR** [comment]
@alton76 
I with the 5.12.0 firmware I had no problems, only after I put 5.13.1 I had a lot of problems and I came back to 5.12.0, today text as said that they suggested

**Comment by alton76** [comment]
What ESP Version?

**Comment by RWGaMeR** [comment]
@alton76 

I use a basic sonoff that has esp8266

**Comment by RWGaMeR** [comment]
@reloxx13 
I tried as you suggested but I have not solved the problem
