### ISSUE TITLE
Sonoff Rf Bridge ignores MQTT configured %fulltopic% in status message

### ISSUE THREAD

**Issue by DonStefano** [arendst/Sonoff-Tasmota#2615]
Hardware: Sonoff Rf Bridge V2.0
Self compiled Tasmota-Version 5.12.0o with VS-Code / PlatformiIO

output of command ``status 0``:
`10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS = {"Status":{"Module":25,"FriendlyName":["openHAB1-RFBridge1"],"Topic":"openHAB1_RFBridge1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":0,"SaveData":0,"SaveState":1,"ButtonRetain":0,"PowerRetain":1}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS1 = {"StatusPRM":{"Baudrate":19200,"GroupTopic":"sonoffs","OtaUrl":"http://openhab1:9999/data/firmwares/sonoff-minimal.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:50","StartupUTC":"2018-05-03T08:56:39","Sleep":0,"BootCount":1815,"SaveCount":3644,"SaveAddress":"FB000"}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS2 = {"StatusFWR":{"Version":"5.13.1a","BuildDateTime":"2018-05-03T10:54:48","Boot":31,"Core":"2_4_0","SDK":"2.1.0(deb1901)"}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["Kunibert","indebuurt2"],"TelePeriod":300,"SetOption":["00000029","55818000"]}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS4 = {"StatusMEM":{"ProgramSize":474,"Free":528,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS5 = {"StatusNET":{"Hostname":"openHAB1-RFBridge1","IPAddress":"192.168.6.51","Gateway":"192.168.6.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.6.1","Mac":"DC:4F:22:82:D7:69","Webserver":2,"WifiConfig":3}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS6 = {"StatusMQT":{"MqttHost":"openHAB1","MqttPort":1883,"MqttClientMask":"openHAB1_RFBridge1","MqttClient":"openHAB1_RFBridge1","MqttUser":"","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS7 = {"StatusTIM":{"UTC":"Thu May 03 08:57:29 2018","Local":"Thu May 03 10:57:29 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":99}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS10 = {"StatusSNS":{"Time":"2018-05-03T10:57:29"}}
10:57:29 MQT: openHAB1_RFBridge1/stat/STATUS11 = {"StatusSTS":{"Time":"2018-05-03T10:57:29","Uptime":"0T00:00:50","Vcc":3.486,"Wifi":{"AP":1,"SSId":"Kunibert","RSSI":44,"APMac":"44:4E:6D:1E:53:E7"}}}`

The result is sent this way:
`11:36:38 MQT: stat/openHAB1_RFBridge1/RESULT = {"RfCode":"#550115"}
11:36:38 MQT: stat/openHAB1_RFBridge1/RESULT = {"RfCode":"#554115"}
11:36:39 MQT: stat/openHAB1_RFBridge1/RESULT = {"RfCode":"#551115"}`

As you see, %prefix% is sent before %topic%. However it is configured to send it the other way round:
![openhab1-rfbridge1_mqtt-config](https://user-images.githubusercontent.com/15259740/39567243-9f051e1e-4ebe-11e8-93de-1a677ffe89d2.png)

It does respect configuration when sending telemetry:
`10:35:06 MQT: openHAB1_RFBridge1/tele/STATE = {"Time":"2018-05-03T10:35:06","Uptime":"3T02:01:07","Vcc":3.486,"Wifi":{"AP":1,"SSId":"Kunibert","RSSI":42,"APMac":"44:4E:6D:1E:53:E7"}}`

It also receives commands sent via %topic%/%prefix%.

**Comment by arendst** [comment]
Change MQTTClient to something different from topic and you're good to go.
