### ISSUE TITLE
extending Tasmota

### ISSUE THREAD

**Issue by timwilky** [arendst/Sonoff-Tasmota#2616]
I have added LCD support to my Tasmota environment. But in doing so I had to add a new command to manage the I2C address.

The issue I experienced was that there is a conditional compilation whilst defining the kTasmotaCommands array.
#ifdef DEBUG_THEO
  "|" D_CMND_EXCEPTION
#endif

Therefore if people make the logical mistake I made and add their new commands at the end of the TasmotaCammands enumeration and the kTasmotaCommands array, they become out of sync if the DEBUG_THEO flag is not in place!

**Comment by arendst** [comment]
See branch development_display for a better solution.

**Comment by arendst** [comment]
See #2557 too

**Comment by ascillato** [comment]
Hi,

If your issue was solved, please, close it. Thanks :+1:
