### ISSUE TITLE
Wemos D1 mini can not connect wifi

### ISSUE THREAD

**Issue by kdjordjev** [arendst/Sonoff-Tasmota#2621]
Just flashed my wemos d1 mini, but can not get to it. 
Followed the instructions from [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos%20D1%20Mini). It reported successful flash

**I can not get to the wifi and set it up.** 
**The device monitor fails to connect to the AP and i do not see the device in my network**

I also modified the user config to setup a fixed IP and recompiled but somehow the status reports 0.0.0.0

- [ ] What hardware you are using

wemos D1 mini 4Mb

- [ ] Provide the output of command ``status 0``

> 00:00:28 CMD: status 0
00:00:28 RSL: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
00:00:28 RSL: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:24","StartupUTC":"","Sleep":0,"BootCount":147,"SaveCount":148,"SaveAddress":"F8000"}}
00:00:28 RSL: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"5.13.1","BuildDateTime":"2018-05-03T18:07:33","Boot":31,"Core":"2_4_0","SDK":"2.1.0(deb1901)"}}
00:00:28 RSL: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["",""],"TelePeriod":300,"SetOption":["00008009","55818000"]}}
00:00:28 RSL: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":531,"Free":472,"Heap":22,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3}}
00:00:28 RSL: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-7888","IPAddress":"0.0.0.0","Gateway":"192.168.2.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.27","Mac":"B4:E6:2D:23:9E:D0","Webserver":2,"WifiConfig":3}}
00:00:28 RSL: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_239ED0","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:00:28 RSL: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 00:00:28 1970","Local":"Thu Jan 01 00:00:28 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":1,"Sunrise":"07:43","Sunset":"16:03"}}
00:00:28 RSL: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:00:28"}}
00:00:28 RSL: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:00:28","Uptime":"0T00:00:24","Vcc":3.017,"POWER":"OFF","Wifi":{"AP":1,"SSId":"","RSSI":100,"APMac":"FF:FF:FF:FF:FF:FF"}}}

- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

> Executing task: platformio.exe device monitor <

> > Executing task: platformio.exe device monitor <

>--- Miniterm on COM3  115200,8,N,1 ---
>--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
>00:00:40 APP: Restarting
> ets Jan  8 2013,rst cause:2, boot mode:(3,0)
>load 0x4010f000, len 1384, room 16
>tail 8
>chksum 0x2d
>csum 0x2d
>v4ceabea9
>~ld
>00:00:00 Project sonoff Sonoff (Topic sonoff, Fallback DVES_239ED0, GroupTopic sonoffs) Version 5.13.1-2_4_0
>00:00:00 WIF: Connecting to AP1  in mode 11N as sonoff-7888...
>00:00:10 WIF: Connect failed with AP timeout
>00:00:10 WIF: Connecting to AP1  in mode 11N as sonoff-7888...

**Comment by Frogmore42** [comment]
You have a blank SSID, which is the default as I recall.

I normally use user config override to set the SSID of my network to make initial setup easier.  Since you have uploaded FW already, you will need to change cfg_holder to a different value and then download the new FW.  After you verify the networking works, change the cfg holder back so you can use standard released FW.

**Comment by kdjordjev** [comment]
thank you
