### ISSUE TITLE
Wifi Connect Issue (Password)

### ISSUE THREAD

**Issue by Blade2021** [arendst/Sonoff-Tasmota#2622]
- [x] What hardware you are using
Sonoff Basic

I've already debugged this issue but wanted to make it known.  It took me about an hour to figure it out but the * character is not allowed in the password field to connect to a network.  This will cause the sonoff to say the password is incorrect.

**Comment by lvta0909** [comment]
#1377

**Comment by Blade2021** [comment]
Thanks Ivta0909, I didn't realize there was an issue already open.
