### ISSUE TITLE
Extend Tasmota with SX1509 (I2C) as Sensor

### ISSUE THREAD

**Issue by bollitec** [arendst/Sonoff-Tasmota#2625]
Hey there,

as first many many thanks for this agile and superb project. 
Thanks @arendst, @jason2866 and all the others!!!

**Main first objectives:**
Append SX1509 as Sensor to send and/or receive 16bit value.
Examples:
a) LED matrix 8x8 - send hex value to set them on/off
b) Keyboard 64 keys - receive actual key pushed

**Maybe future topics:**
- the board is able to use PWM, so the LED's can be dimmed
- 16bit analog to digital converter (there are a lot of chips available)
- extend GPIO's for tasmota pin management
- digital to analog 16bit sound processor
- ... see also https://learn.sparkfun.com/tutorials/sx1509-io-expander-breakout-hookup-guide

**My Cases:**
(A)
I'd like to implememt a door control system for the cellar. There are few measurements required.
- door open/closed
- key inserted yes/no
- key lock activated yes/no
- door lock in place yes/no
- power of control system exist yes/no
- parallel a keyboard to to switch lamps on/off 
=> 5bit for status and 4bits for keyboard = 9 GPIO's 
... wouldn't a problem with SX1509 as GPIO extension.

All bits together support then a workflow in an automation system. For example, if door lock not in place => alarm; if door open without ( key inserted and key lock inactive ) => alarm.
The management can taken over by an automation software, but as first the hardware with Tasmota software need the function to get the information, a 16bit value.

(B)
An other simple workflow with such an implementation are LED matrixes. A 8x8 matrix show actual status. SX1509 is able to address 4 ones in same I2C (same ESP8266). 
- second SX1509 show with 8x8 LED the status of case (A)

It's at all an idea to extend functionality of Tasmota in combination of Home Automation. 
Would be really great, if this would possible to append and Tasmota support IoT for the future :-)

Thanks a lot again, for this great job! 
Love this project,
sincerelly
Joerg

**Comment by Jason2866** [comment]
I have 0% done for this great software from @arendst 
Just helped other a little for the this nice piece of software that made really great things easy possible!
So i cant help because i am not a programmer, just a user who uses tasmota...
