### ISSUE TITLE
Rules?

### ISSUE THREAD

**Issue by rene9900** [arendst/Sonoff-Tasmota#2627]
i have used espeasy, which i read is the inspiration to the development of rules to tasmota, great, that was the reason i used espeasy, and a little bit the deepsleep feature :)

but im missing the window from espeasy to get a good overview of the rules codes, as in espeasy.
running everything from console seems a bit messy, or am i missing some other smart feature?
i did enable rules as descriped and can add rules trough terminal,but when i type in terminal rule the action feature in timers changes to rule only and i can't figure out how to change it back?

**Comment by ascillato** [comment]
Hi,

You should have as outputs also the relays but if you have none defined, you will have only rules as output.

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.
