### ISSUE TITLE
TIPP: Sonoff S20 for 7,20€ / $8.71

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#2630]
Hi, a bit off topic but interesting for some guys here. You can order two Sonoff S20 EU (separate order) from this shop:
https://www.rosegal.com/decorative-crafts/sonoff-s20-wifi-smart-switch-socket-with-wireless-remote-control-2192964.html

Just use this coupon code:
DSRGAE2

Greetings Fabi

EDIT:
Change the currency to euro (or whatever you want) at the top right corner. This trick will skip the PayPal exchange costs.

Sonoff Basic for 3,47€ / $4.20:
https://github.com/arendst/Sonoff-Tasmota/issues/2653

**Comment by znanev** [comment]
@0n3-70uch Thank you!

Just ordered two, price is $8.71 for one (shipping included), which is even lower than the average on Aliexpress (~ $12).

It is just worth mentioning that your code is applied once you create an account at Rosegal. I was about to skip the offer when I couldn't see the discount at first.

**Comment by 0n3-70uch** [comment]
You are welcome :-).

Tipo for European guys:
Change the currency to euro at the top right corner. This trick will skip the PayPal exchange costs.

**Comment by MichiM2** [comment]
When i look at  https://www.rosegal.com/decorative-crafts/sonoff-s20-wifi-smart-switch-socket-with-wireless-remote-control-2192964.html today it shows me a price of € 13,09.

**Comment by 0n3-70uch** [comment]
Tested with coupon code?
DSRGAE2

**Comment by MichiM2** [comment]
Thanks for the hint. I tried it now with Code an it really worked.

**Comment by 0n3-70uch** [comment]
Great :-)

**Comment by 0n3-70uch** [comment]
Haha next deal:
https://github.com/arendst/Sonoff-Tasmota/issues/2653

**Comment by ascillato** [comment]
Great!
