### ISSUE TITLE
Publish Sonoff Basic MQTT discovery as a light?

### ISSUE THREAD

**Issue by jjlawren** [arendst/Sonoff-Tasmota#2634]
Is it possible for the Home Assistant MQTT discovery topic to publish a Sonoff Basic as a basic on/off light instead of a switch?

**Comment by jjlawren** [comment]
I've been able to achieve this by adding an ifdef to `xdrv_07_home_assistant.ino`, but it's pretty hacky. Would be nice if this was a supported option.

**Comment by arendst** [comment]
Fixed using command SetOption30 in v6.0.0b
