### ISSUE TITLE
Rule enchansment for value "Switch1":"OFF" / "ON" state check in TELE-

### ISSUE THREAD

**Issue by roblad** [arendst/Sonoff-Tasmota#2635]
Make sure these boxes are checked before submitting your issue - Thank you!

-[x] What hardware you are using Wemos D1

Hi,

Could you add a checking of state Switch ON/OFF in TELE in SENSOR string "Switch1":"OFF"

**Comment by wongnam** [comment]
I try Rule on Switch1#State=ON do Power1 ON endon, maybe the rule does not effect with Switch#State=ON or Switch#State=1 but it effect with  Switch#State

**Comment by roblad** [comment]
Hi,


I have 

rule on Switch#state=ON do publish cmnd/podlewanie/POWER4 1 endon 

and it does not work

**Comment by arendst** [comment]
Right. Did some tests and it works but....

- The correct syntax for a switch rule is one of the following:
```
- rule on Switch1#state=on do …
- rule on Switch1#state=off do …
- rule on Switch1#state=toggle do …
```
- When switchmode is 0 (toggle) the trigger for a switch change will only provide a state of ``toggle``
- when switchmode is 1 (follow) the trigger for a switch change will provide either a state of ``on`` or ``off``

So to get what you want (I think) is execute command ``switchmode 1`` once and make a rule like
```
rule on Switch1#state=ON do publish cmnd/podlewanie/POWER4 1 endon
```

**Comment by arendst** [comment]
BTW rules currently do NOT work on a tele or status message containing switch.

As switch is in the root of the JSON message the rules code does not handle this correctly.

**Comment by arendst** [comment]
Did you try switchmode 2? It works for me as expected.

**Comment by roblad** [comment]
let me update firmware :-)

**Comment by roblad** [comment]
Hi,


No both switch mode 2 and 1 does not work, even when i disabled domoticz

19:12:29 CMD: rule
19:12:29 MQT: stat/woda/RESULT = {"Rule":"ON","Once":"OFF","Rules":"on Switch1#state=ON do publish cmnd/podlewanie/POWER4 1 endon"}
19:12:36 CMD: switchmode 1
19:12:36 MQT: stat/woda/RESULT = {"SwitchMode1":1}
19:12:45 MQT: cmnd/deszcz/POWER = OFF
19:12:46 MQT: cmnd/deszcz/POWER = ON
19:12:47 MQT: cmnd/deszcz/POWER = OFF
19:12:49 MQT: cmnd/deszcz/POWER = ON

I do not have any device any relay on that wemos d1 module

**Comment by Schubi1** [comment]
@roblad 
had the same problem and tried for many hours.
My rule is now working replace Switch1#sate=ON with Switch1#state=1 and Switch1#state=OFF with Switch1#sate=0
Hope it helps!

**Comment by ascillato2** [comment]
Hi

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks
