### ISSUE TITLE
Sonoff Dual R2 OTA update doesn't work

### ISSUE THREAD

**Issue by AlessandroEmm** [arendst/Sonoff-Tasmota#2637]
Hey there 

I have 5.11.1 on on my R2s (got multiples ones) and I cannot make it update to neither 5.12 or 5.13.x 

All I have in the logs with the Level set to 4 after trying Upload and URL-based-OTA:

2:13:33 UPL: File sonoff-classic.bin ...
22:13:50 UPL: Successful 506112 bytes. Restarting

I'm not sure it ever reboots whatsoever, no update is happening.

I flashed them initially with SonOTA.

I have no problems doing the same on all my non-R2 Duals.

Anyone having similar issues?

Thanks a lot!
Alessandro

**Comment by Frogmore42** [comment]
status 0?

**Comment by AlessandroEmm** [comment]
Surre, sorry: 
`22:19:45 RSL: stat/KleinesZimmerOben/STATUS = {"Status":{"Module":39,"FriendlyName":"KleinesZimmerOben","Topic":"KleinesZimmerOben","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","Uptime":1193,"Sleep":250,"BootCount":13,"SaveCount":105,"SaveAddress":"FB000"}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS2 = {"StatusFWR":{"Version":"5.11.1","BuildDateTime":"2018-01-07T21:51:09","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"B","SSId2":"indebuurt2","TelePeriod":300,"SetOption":"55804009"}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS4 = {"StatusMEM":{"ProgramSize":484,"Free":516,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS5 = {"StatusNET":{"Hostname":"KleinesZimmerOben","IPAddress":"10.0.1.5","Gateway":"10.0.1.1","Subnetmask":"255.255.255.0","DNSServer":"10.0.1.1","Mac":"60:01:94:9E:91:07","Webserver":2,"WifiConfig":2}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS6 = {"StatusMQT":{"MqttHost":"10.0.1.250","MqttPort":1883,"MqttClientMask":"DVES_X","MqttClient":"DVES_9E9107","MqttUser":"DVES_USER","MAX_PACKET_SIZE":512,"KEEPALIVE":15}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS7 = {"StatusTIM":{"UTC":"Sat May 05 21:19:45 2018","Local":"Sat May 05 22:19:45 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS10 = {"StatusSNS":{"Time":"2018-05-05T22:19:45"}}
22:19:45 RSL: stat/KleinesZimmerOben/STATUS11 = {"StatusSTS":{"Time":"2018-05-05T22:19:45","Uptime":1193,"Vcc":3.222,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"B","RSSI":100,"APMac":"64:A5:C3:6F:E5:7E"}}}`

**Comment by Jason2866** [comment]
Do you use no mqtt broker?
Your device isnt connected to one.
Which file do you use for update? Self compiled or?

**Comment by Jason2866** [comment]
I think the download version uses sdk 2.4.0. This version makes sometimes problems.
I always use sdk 2.3.0. Try to compile your own version. It isnt complicated, just follow the wiki
and install Platformio IDE.

**Comment by AlessandroEmm** [comment]
@Jason2866 will try - but why does it only fail on R2's all the other ones work just fine 🤔

**Comment by Jason2866** [comment]
I dont know for some 2.4.0 works perfect for others not.
I tried 2.4.0 and i had problems with all my sonoffs i tried.
With some of my Wemos mini it worked without any problems?!
So just try and when problem is gone😃
