### ISSUE TITLE
WiFi SSID/Password may not contain special characters

### ISSUE THREAD

**Issue by moritz89** [arendst/Sonoff-Tasmota#2639]
**Hardware:** Sonoff 4CH Pro R2

**Output Messages:**

    00:00:02 WIF: Attempting connection...
    00:00:03 WIF: Attempting connection...
    00:00:04 WIF: Attempting connection...
    00:00:05 WIF: Attempting connection...
    00:00:06 WIF: Attempting connection...
    00:00:07 WIF: Connect failed as AP cannot be reached
    00:00:07 WIF: Connecting to AP1 MoIn_5GHz in mode 11N as sonoff-3815...

SSID and the non-alphanumeric characters present in the passwords that were tried and did not work:

- `PROTOHAUS` with characters `-` and `#`
- `MoIn_5GHz` with characters `.` and `-`
- `Moritz's iPhone` with only simple and capital letters

SSID and password combinations that work:

- `Hello` with only simple and capital letters
- `SDGintern` with only numbers

Is this a known undocumented limitation or is it a novell bug? The cause was highlighted in this [bug report](https://github.com/arendst/Sonoff-Tasmota/issues/1377) by njloki30. Additionally, how can `status 0` be printed? Using master branch (f20e9b8) with the following settings in platformio.ini

```
env_default = sonoff

...

[common] ; ************************************************************
; *** Esp8266 core for Arduino version
;platform = espressif8266@1.5.0  ; v2.3.0
platform = espressif8266@1.6.0  ; v2.4.0
;platform = espressif8266@1.7.0  ; v2.4.1
;platform = espressif8266

framework = arduino
board = esp01_1m
board_flash_mode = dout
```

**Comment by arendst** [comment]
Opening another issue for the same problem doesn't help. See #1377.
