### ISSUE TITLE
Add Charlieplexing support for GPIOs

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#2640]
The ESP8266/ESP32-GPIOs support tristate-operation (output high | input high resistance | output low). This can be used to control 2 interlocked LEDs/optical couplers with 1 GPIO for e.g. status LEDs or shutter motors.

[Charlieplexing](https://en.wikipedia.org/wiki/Charlieplexing) allows to control LED matrices with few GPIOs: 

#LED = #GPIO<sup>2</sup> - #GPIO.

[Charlieplexing Video](https://www.youtube.com/watch?v=Bx5GLyJSWPk)

**Comment by ascillato** [comment]
Hi

Thanks for the information. Cool technique. 

By now Tasmota do not support tristate output due this software is intended for sonoff devices. 

Thanks
