### ISSUE TITLE
question: Found These PIR

### ISSUE THREAD

**Issue by MYLE-01** [arendst/Sonoff-Tasmota#2641]
https://www.ebay.com/itm/5pcs-Mini-IR-Infrared-Pyroelectric-PIR-Body-Motion-Human-Sensor-Detector-Module/222218187242?epid=595198651&hash=item33bd3c71ea:g:5DkAAOSw6n5XrvZx

looks like they only need 3.3v 

could we put on to gpio14

**Comment by Jason2866** [comment]
Should work, in my opinion to expensive

**Comment by MichiM2** [comment]
The Mini-PIR works well with the 3v3 from the Sonoff Basic. If you remove the 3 Pins from the PIR, and drill a hole into the Sonoff Basic, you could install it easyly inside the Basic and wire it to the GPIO14, 3v3 and GND-Pins. 
Be sure not come too near the 230V lines!

**Comment by MYLE-01** [comment]
thanks 
Just order some
