### ISSUE TITLE
hpa to mmhg

### ISSUE THREAD

**Issue by eeak** [arendst/Sonoff-Tasmota#2642]
How can I switch the format of the pressure from hpa to mmhg?

**Comment by arendst** [comment]
With your HA tool

**Comment by eeak** [comment]
Sorry, what do you mean by the HA tool?

**Comment by arendst** [comment]
HA = HomeAutomation tool like Domoticz, Node-Red etc. Any user front-end.

**Comment by edgiru** [comment]
Hello
I have the same question. How to change the format? On screen i2C (SSD1306 OLED 128x64) hpa to mmhg? (In home automation everything is fine there I did mmhg)
![IMG-20191018-WA0025](https://user-images.githubusercontent.com/4624056/67099836-4b8f9e00-f1c7-11e9-94ed-3b9cc2bf91ad.jpeg)

**Comment by edgiru** [comment]
16:56:13 MQT: tele/cabinet/SENSOR = {"Time":"2019-10-18T16:56:12","BME280":{"Temperature":23.5,"Humidity":38.8,"Pressure":754.2},"**PressureUnit":"mmHg**","TempUnit":"C"}

**Comment by arendst** [comment]
OK. Little bug. Will fix now.
