### ISSUE TITLE
TIPP: Sonoff Basic for 3,47€ / $4.20

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#2653]
Hi, the second Sonoff deal from the same shop. Now the Sonoff Basic (you can order two devices in seperate orders):
https://www.rosegal.com/iphone-cases/sonoff-basic-dual-channel-wifi-wireless-smart-switch-for-diy-home-safety-2205777.html

Just use this coupon code:
DSRGMAY7

Tipp:
Change the currency to euro (or whatever you want) at the top right corner. This trick will skip the PayPal exchange costs.

Greetings Fabi

Sonoff S20 for 7,20€ / $8.71:
https://github.com/arendst/Sonoff-Tasmota/issues/2630

**Comment by 0n3-70uch** [comment]
Sold out :-(.

**Comment by 0n3-70uch** [comment]
Back in stock :-).

**Comment by znanev** [comment]
Thanks again!

Just ordered two - couldn't miss them for $4.09 per device, delivered!

**Comment by 0n3-70uch** [comment]
Yeah so crazy. An ice cream is more expensive :-).

**Comment by ascillato** [comment]
Great!
