### ISSUE TITLE
Feature-Request: Support TX20 Wind Sensor

### ISSUE THREAD

**Issue by Silencer80** [arendst/Sonoff-Tasmota#2654]
I would like to operate the following wind sensor on a Tasmota device:

https://www.amazon.de/Technoline-TX-20/dp/B01HXZ3KLA

The sensor must be connected as follows:

Yellow ground (GND)
Green mass (DTR)
Red 3.3V (Vcc)
Black GPIO_2 (TxD)

The protocol is described here:

https://www.john.geek.nz/2011/07/la-crosse-tx20-anemometer-communication-protocol/
http://fabrizio.zellini.org/decoding-la-crosse-tx20-anemometer-with-arduino

Code for the ESP8266 has already been implemented:

https://github.com/bunnyhu/ESP8266_TX20_wind_sensor

The following website is in German, but has a working solution without the tasmota framework:

http://blog.bubux.de/windsensor-tx20-mit-esp8266/

This sensor would be a great addition to Tasmota. Unfortunately I can't (bad software developer) implement that by myself. I own the hardware and I would like to support an implementation with tests.

Thanks a lot!
-Boris

**Comment by TheEggi** [comment]
Added a PR: https://github.com/arendst/Sonoff-Tasmota/pull/3146
