### ISSUE TITLE
SonOff Basic - with 5.13.1 every 5 seconds the full stat-reports via MQTT - my server is overloaded

### ISSUE THREAD

**Issue by BigWumpus** [arendst/Sonoff-Tasmota#2657]
Hello,
yesterday I installed the 5.13.1 binary from this site to a Touch and to some Basics. Now the website of them are only reachable via my cellphone (WiFi). iobroker can work with them and switch them. SonWeb is also finding them.
But the devices send every 5 seconds a lot of stat-reports via MQTT. Today in the morning my server was not working any more, because of overload. Any command needs around 5-10 Seconds to switch the device.
I also tried the option teleperiod, but it doesn't change anything.

**Comment by RaymondMouthaan** [comment]
Most probably you have setup Sonweb to update ever 5 seconds. This requests every device via rest, but the devices publishes the results (STATUS 0) also to mqtt. This might overload your mqtt server. 

Change the refresh settings to for example 15 seconds and see if your issue is solved.
