### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by rlust** [arendst/Sonoff-Tasmota#2662]
Make sure these boxes are checked before submitting your issue - Thank you!

- [ ] What hardware you are using Docker
- [ ] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: 

Docker image failed with the following error, even after a restart:
Here is the error when trying to login.

Parse error: syntax error, unexpected '' => '' (T_CONSTANT_ENCAPSED_STRING) in /app/sonweb/includes/Config.php(58) : eval()'d code on line 3

**Comment by ascillato** [comment]
Hi,

This is the repository of Sonoff-Tasmota

The SonWEB is at https://github.com/reloxx13/SonWEB

Please, open the issue there.

Thanks.
