### ISSUE TITLE
[Update] MHZ-19B CO2 Sensor added to Tasmota Wemos Wiki

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#2665]
Hai All,

Just to inform you guys, the [Tasmota Wemos Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos%20D1%20Mini) has been update for MHZ-19B CO2 Sensor.

Thanks to @FabianHM for providing the screenshots and info about this sensor. 👍

**Comment by ascillato** [comment]
:+1:
