### ISSUE TITLE
[Update] RCWL-0516 Microwave Radar Sensor added to Tasmota Wemos Wiki

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#2667]
Hai All,

Just to inform you guys, the [Tasmota Wemos Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos%20D1%20Mini) has been updated for RCWL-0516 Microwave Radar Sensor.

Greetz!

**Comment by MatzeJoerling** [comment]
working well for me! 
I dont log false positives, also dont care. 
it makes the light on and off, and if it is on one more time ...  

i would not use it for alarm system!!!  

check this: https://github.com/jdesbonnet/RCWL-0516

**Comment by RaymondMouthaan** [comment]
No false positives here. I prefer this accurate sensor over the HC-SR501 (PIR).

**Comment by aihysp** [comment]
can someone please tell me what sensor to put under this GPIO?
i am getting allot of issues with Switch1-4
