### ISSUE TITLE
Wifi not working on mains

### ISSUE THREAD

**Issue by gid204** [arendst/Sonoff-Tasmota#267]
When I have my sonoff basic hooked up to serial port via pc it connects and is completely reachable on the network. However when I disconnect serial and connect via mains wifi fails to connect to my home network. I try to reconfigure with 4 button presses but the wifi configuration doesn't even pop up.

Any help is greatly appreciated :)

**Comment by davidelang** [comment]
we've seen some devices with cold solder joints in them. If there is a bad joint 
it could either not provide proper power, or generate so much noise that it 
affects wifi

**Comment by gid204** [comment]
Ok thanks for that, I'll try it out again with one of the other ones I have otherwise I'll get some new ones  ordered. thanks for your help :)

**Comment by smadds** [comment]
Does the LED light up OK & can you hear the relay click when you single press the button?

**Comment by gid204** [comment]
Yes led lights up just fine.
On serial connection it lights up and then connects to network

On mains it lights up and then just flashes as it can't connect to network. I try to force it with 4 button press but it just doesn't react to it. Button works though because when I press it the light turns on and off...

**Comment by citrusfizz** [comment]
thats interesting, if the relay is working, the ESP8266 is working. 
Can you check any logs on your Accesspoint to see if it try to connect?

**Comment by davidelang** [comment]
any further info on this issue?

**Comment by gid204** [comment]
Unfortunately not..been busy with uni last few days. Going to try troubleshoot a few more things then will opt for purchasing replacements.

These units were bought off eBay (still came in the official box). I'll get them off itead site this time..

**Comment by Shaewen-Chronicles** [comment]
Ich habe the exact same issue in the WiFi log it says the Device is connecting and then lossing the connection but if i have it sitting at the same place with seriell connection its working fine.

**Comment by ekgerke** [comment]
I had an issue with wifi dropping with one module. Turned out that I had a defective LED bulb that somehow interfered with wifi. Replacing the bulb ended the problem for good.

**Comment by Shaewen-Chronicles** [comment]
Okay i will trie it with the bulb removed

**Comment by Shaewen-Chronicles** [comment]
No even with the bulb removed it gets no Wifi connection

**Comment by davidelang** [comment]
did you check for bad solder connections on the device?

**Comment by Shaewen-Chronicles** [comment]
I think i will do that tomorrow

**Comment by gid204** [comment]
my new units came (directly from itead and not eBay).
They seem to be working perfectly now :)

**Comment by boko6** [comment]
Hi, I have exactly the same issue, as in issue 391, the only difference with the rest of sonoffs that i have is that this one was working and linked with the ewlink app

**Comment by glsf91** [comment]
I had the same problem with a Sonoff basic but solved (I hope). See my reply in #391
