### ISSUE TITLE
Documentation for setting lattitude, longitude and timezone?

### ISSUE THREAD

**Issue by apastuszak** [arendst/Sonoff-Tasmota#2675]
Make sure these boxes are checked before submitting your issue - Thank you!

- [X ] Sonoff Basic
- [] Provide the output of command ``status 0``
- [ ] If you have a stack dump decode it: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst
- [ ] For better debug messages: https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

Is there documentation anywhere on how to set your geographic location and timezone?  Can this be added to the wiki?

**Comment by Jason2866** [comment]
Is described in wiki "Commands"
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by apastuszak** [comment]
I don't see a way in the provided command to cofigure when DST starts and when it ends.  Can that only be done at compile time?

**Comment by Jason2866** [comment]
Yes

**Comment by apastuszak** [comment]
Hmm...  It would be nice if you could set that from the console.  With rules now in Tasmota, having proper time settings might be a kind of important.

**Comment by ascillato** [comment]
Hi @apastuszak I also thinks that DST and STD should be modified by commands. Can you make a PR for that?

**Comment by apastuszak** [comment]
I just did that!

https://github.com/arendst/Sonoff-Tasmota/issues/2721

**Comment by ascillato** [comment]
A PR is a Pull Request that means code to be added.

You have just open another issue. 

I agree with you about adding those commands 

I was asking if you have or you can program the code to add those commands, so as to make a Pull Request?

**Comment by apastuszak** [comment]
Closed.
