### ISSUE TITLE
Request:  Best way to implement code for custom sensor/protocol... 

### ISSUE THREAD

**Issue by TLCary** [arendst/Sonoff-Tasmota#2676]
Hot tub has an RJ12 Jack for the display, it uses a 40kHZ Clock/Data signal that directly drives the segments of an led display, (just three digits).   I have the C code that extracts the values, it triggers on the rising edge of the signal, recognizes the patterns, etc.  My question, can I get some direction on the best way to implement this as a custom sensor?  Or might there be enough interest to formally make a new sensor type.  It looks like many many Spas use this same protocol.

**Comment by arendst** [comment]
Just try to implement a stand alone sensor type. This makes implementing (if ever) easiest as ther are no changes needed in the other files.

Take a look at the xsns_ files for inspiration.
