### ISSUE TITLE
Sonoff RF vs Sonoff RF Bridge

### ISSUE THREAD

**Issue by benzino77** [arendst/Sonoff-Tasmota#2686]
Is there any different in 433MHz receiver on those devices? I can successfully receive codes from my remote controlers (#1095) on RF Bridge, but I cannot do the same on Sonoff RF. Double push, short red blink... and then nothing happens when I'm pushing remote buttons. 

On Sonoff RF tehere is flushed Tasmota 5.13.1a

**Comment by Jason2866** [comment]
Sonoff RF, the receiver is only for this device to switch it on and off. It is a receiver which can learn
some RF Transmitter. Thats it. No more function.
Rf Bridge receives and send the received commans via mqtt. Complete different usage.
With the RF Bridge and a HA System you can make every device switchable with a RF transmitter

**Comment by benzino77** [comment]
Maybe I was unclear. I'm talking about the **receiver** part. The point is that RF Bridge can learn my remote controlers codes and Sonoff RF not. I don't care about the transmitter part in this case - I'm talking only about learning/receiving.

**Comment by Jason2866** [comment]
Really strange, the decoder chip is the same...
Try a different RF Transmitter

**Comment by benzino77** [comment]
Yeah, I also think that this is strange.

I will not be able to check other remote controler because I don't have one.
I have only two remote controllers, one is based on PT2264 and the other one on HX2262 chip.

**Comment by sleezy100** [comment]
If you have loaded Tasmota to the sonoff RF you had to bridge two of the pads on the main board to get it to go into flash mode. You have to undo the bridging so that the Sonoff will go into learning mode.

**Comment by benzino77** [comment]
I didn't have to bridge two pads to flash Tasmota on the device. That procedure was proper to older version of Sonoff RF (the wiki should be updated). For newer versions this procedure is proper: shortcat the bottom pad of R21 to the ground during power up. Have a look here: [how to put Sonoff RF in flash mode](https://bitbucket.org/xoseperez/espurna-original/wiki/Hardware#markdown-header-iteadstudio-sonoff-rf).
Anyway the device is flashed, GPIO0 is not pulled down anymore.

**Comment by sleezy100** [comment]
The only other thing i found when i did mine was when you follow the itead instructions for how to program the remote. Quick press the button twice then press the remote button. The led only goes red when it accepts the remote code.

**Comment by benzino77** [comment]
Does anyone has similar problem?
