### ISSUE TITLE
SONOFF always unavalible with MQTT

### ISSUE THREAD

**Issue by rt400** [arendst/Sonoff-Tasmota#2687]
hi ,
i have sonoff basic with tasmota 5.13.1.1.a work on HA and mqtt.
but he all the time show in ha that is unavailable...
if i downgrade to 5.12 he works fine ..
what the different between those versions?

**Comment by Jason2866** [comment]
Trace your mqtt traffic. I have 5.13.1a installed on some devices (long term test)
All my devices work as the should with my Home Automation System OpenHab.
I think you have to search in your HA.

**Comment by benzino77** [comment]
There were some changes in JSON format regarding `Rules`. Maybe this is problem.
