### ISSUE TITLE
Sonoff RF keeps turning off when using RF remote

### ISSUE THREAD

**Issue by sleezy100** [arendst/Sonoff-Tasmota#2688]
I have upgraded my Sonoff RF to 5.13.1 and all was fine. Now, every time i use the rf remote to switch on, after a few seconds it switches itself of again. I then switch on again and after a few seconds it switches off again. If i switch it on by using HA everything works as it should. Anyone have any ideas ?????

**Comment by Leseratte10** [comment]
Sounds like your home automation system is overriding the state of the sonoff. You need to fix that setting (probably "persistence" or something like that) in your HA system.

**Comment by Jason2866** [comment]
It looks that your HA has stored a retain message an sends this again and agian.
This is a know behaviour from HA.
See #2140

**Comment by Jason2866** [comment]
I am out here, i dont use HA. I am a OpenHab user

**Comment by sleezy100** [comment]
I have down graded to 5.12.0 and all is fine again.  There is obviously something within 5.13.1 not quite right.
