### ISSUE TITLE
Switch vs Button inputs and Wiki information

### ISSUE THREAD

**Issue by flashtel** [arendst/Sonoff-Tasmota#2691]
Hi,

I really found the "Understanding SwitchMode and SwitchTopic" in the Wiki to be very well written. I spent at least 4 hours last night trying to get it to work only to realise I had the input configured as a button. In addition there are 2 Wiki articles, "Button Functionality" and "Button Multi Press" which seems to have some duplication.

There is some information on Button Topic in the commands reference as well but it is not entirely clear to me.

I am hoping/requesting someone might be able to articulate exactly the difference between switch vs button, given switch can be used with a button when set with switchmode=0 or switchmode=4, I assume in this configuration without Button Multi Press or the Button Functionality features.

I also assume additional functionality is applied to button0 for the reset function and so forth, these would not be present on button1+ ?

I thought it might also might be worthwhile to combine all these Wiki articles into one, I' suggest called "switch and button inputs" using the information already available and the additional I'm requesting.

I just started to look at the rule functionality and this looks very powerful, information on how a button press/multi press or switch state change is read with rules would be very useful.

I'm happy to write up a WIKI entry to contribute if I can get clear on the the differences between the inputs and how the data output works.

Thanks
Paul

**Comment by poggenpower** [comment]
Got suck on the same topic. What are the differences between Button and Switch?

**Comment by vontrapp** [comment]
I can't find any information on this nuance either.
