### ISSUE TITLE
ability to use mDNS in MQTT & OTA server address

### ISSUE THREAD

**Issue by wiktorschmidt** [arendst/Sonoff-Tasmota#27]
Can be helpful in all the DHCP environments.

**Comment by arendst** [comment]
Shoudn't that just work with current code? That's the mDNS message popping up during MQTT connection.

See description in pull request from the 3.2 version.

**Comment by wiktorschmidt** [comment]
Hmm... I'll double check.
-- 

--
Wiktor Schmidt, +48 601 165 799
https://www.linkedin.com/in/wiktorschmidt
