### ISSUE TITLE
Group Topic setting via web config portal?

### ISSUE THREAD

**Issue by JonSilver** [arendst/Sonoff-Tasmota#270]
Currently the group topic cannot be set through the web config portal. Please could we have this added to the Config Other page?

**Comment by arendst** [comment]
All parameters can be set through the web page using console input. Use command grouptopic and Bob's your uncle.

**Comment by ascillato2** [comment]
Hi,

If using the console is not enough for you. You can use TasmoAdmin to set via web those parameters. :+1:
