### ISSUE TITLE
Sonoff Basic delivered with soldered GPIO

### ISSUE THREAD

**Issue by gcb2018** [arendst/Sonoff-Tasmota#2700]
Yesterday I received a new batch of Sonoff Basics and to my surprise all the holes are soldered and now I am no longer able to flash it... Is there anyone else who has had the same? Is this something new? And more importantly: do you know what to do? Can I desolder it (I have no experience with this at all).

Thanks!

**Comment by Frogmore42** [comment]
There are two main ways of removing solder, braid or solder sucker (aka desoldering pump).  The braid is usually a cheaper first cost and pretty easy to use.  The solder sucker is generally cheaper over the long run and sometimes works better.  It should be pretty easy to remove the solder to add a header with either method.  I am sure there are lots of YouTube videos on how to do it, if you need guidance.

**Comment by tobox** [comment]
If you have neither braid nor a solder sucker, you can try to solder each pin individually by heating up the solder and inserting the pin at the same time. Not pretty, but it should work.

You can also try SonOTA, if you just want to flash the firmware.

**Comment by Leseratte10** [comment]
If its a very new batch with even hardware changes (soldered holes) I doubt the firmware is low enough for SonOTA.

**Comment by Jason2866** [comment]
May you could post a picture off the new version?

**Comment by localhost61** [comment]
@gcb2018,  to empty the hole, try this trick... Heat a hole with the tip on an iron and once the solder is liquid shock the PCB on the table in order to let it go away due to centrifugal force.
It works not so well if there is too little solder, or if it's not warm enough then try to add more solder and retry.
Take care with heavy components like the transformer they don't like to be shocked, keep them in the palm of the hand.

**Comment by gcb2018** [comment]
SonOTA won't work as the FW is too new. I attached an image. I will try your advice. 

has anyone been successful with desoldering AND is it still flashable?
![img_0914](https://user-images.githubusercontent.com/39203078/39957109-644f24be-55ed-11e8-829d-10f83d3285c4.jpg)

**Comment by Jason2866** [comment]
This is not a new sonoff basic version. It will work... just holes with solder.  @localhost61 methode will work
@volkerrichert This is a know issue. Many users have problems with 2.4.0 (1.6) and 2.4.1 (1.7) Version 2.3.0 (1.5) will always work.

**Comment by MYLE-01** [comment]
@gcb2018 
Bugger  Just order some more
they must done for a reason
would love to know the count they have sold and the number that are using there software. i bet there are more hack ones than using there software.

**Comment by volkerrichert** [comment]
@Jason2866 : ok, good to know in detail. At this point i just want to give a hint to @gcb2018 not to run into the same issue.

**Comment by gcb2018** [comment]
Today I received the soldering iron (fine tip). And I think I already messed up two Sonoffs... so I guess I should practice some more or just ask a professional to fix it for me. It's kind of discouraging though.

After soldering I tried flashing it and Arduino gives me ZERO errors. It goes up to 100% just like the other Sonoffs I flashed. I was really happy but after hooking it up to the wall outlet there is no led-light and the sonoff does not show up on the network. Did I mess it up or is this expected behaviour and am I missing something? 

Thanks for your help!

**Comment by gcb2018** [comment]
Do you mean attaching it with the FTDI to my Mac -> open Arduino -> Tools -> Serial Monitor? If yes, it's empty. 

I used the following settings:
<img width="378" alt="screen shot 2018-05-18 at 22 57 13" src="https://user-images.githubusercontent.com/39203078/40257601-10eda67c-5aef-11e8-9bf8-c3b4f3f5ed36.png">

I tried both 1M (no spiffs) as 1M (64K spiffs)

**Comment by arendst** [comment]
No QIO, No v2 Lower Memory.

pls  re-read wiki - arduino ide

**Comment by gcb2018** [comment]
THANK YOU. This worked! You are my hero :)

**Comment by regoobgib** [comment]
I received 12 basics with the soldered holes.  I was able to get them flashed without desoldering, placed jumper wires from ftdi to 90degree header pins, held them on soldered points and managed to flash using ArduinoIDE.  It was a pain, but it did work.

**Comment by ascillato** [comment]
Happy to know that now it is working for you! :+1: Please, close this issue. Thanks.

**Comment by loudmicro** [comment]
🤔 I opened the holes but there's no way my pc can see the board, tried with arduino Ide and espflasher.exe and py but they can't find the sonoff

**Comment by Frogmore42** [comment]
@loudmicro you'll need to provide more information.  Please review the basics of flashing, if you still don't get it to work, open a new issue and provide complete information about what you tried.  You said the PC can't see your board, what does that mean, ie what is the exact error message you got that leads you to believe this.

**Comment by semiautomatix** [comment]
@loudmicro have you tried using Termite to view the terminal output from the connected device?

**Comment by kelvinn** [comment]
Belated comment on closed issue for anybody finding this...

Friend asked to solder on headers, yet found out the holes were filled in. Unable to get solder wick to suck it up, so had to put in each pin individually, and it took a while.

Next time I do it I'm going to print one of these to just hold the programmer to the solder-filled pins:

https://www.thingiverse.com/thing:2980893

**Comment by meingraham** [comment]
One potential issue is that with the holes filled in, the pogo pins on the clip may not align on the contacts. You can use a 0.9mm drill bit to "cut" a bit of an indentation (I just spin the bit in with my hand - not a electric drill!) into the solder for the pins to seat. Of course, the drill bit can completely drill out the solder too.

**Comment by kelvinn** [comment]
Good idea - probably worthwhile I look at getting one... something like this?

https://www.adafruit.com/product/2120

**Comment by meingraham** [comment]
@kelvinn

I got these - https://www.ebay.com/itm/392124866294

**Comment by kelvinn** [comment]
Bought! Now I can expect to do the next Sonoff on... Feb 6th when the bits arrive.

Cheers.
