### ISSUE TITLE
Feature request - More inputs

### ISSUE THREAD

**Issue by gittyhubbyfrankybobby** [arendst/Sonoff-Tasmota#2706]
There's the ability to control 8 outputs (relays) but no ability to have 8 inputs? I would like to see 8 switches and/or 8 buttons.

**Comment by Jason2866** [comment]
Well, when thinking HA system to the end. This makes sense.
One ore more Device(s) for input. One ore many devices for output.
Freedom of choice is always good...

**Comment by ascillato** [comment]
:+1:

**Comment by arendst** [comment]
8 switch support released as 6.0.0b today
