### ISSUE TITLE
Request: localIP address

### ISSUE THREAD

**Issue by decologne** [arendst/Sonoff-Tasmota#273]
With version 4.0.0 it is possible to define static IP address of the device. Is it also possible to change this localIP address by webserver console command ?

**Comment by arendst** [comment]
Nope

**Comment by decologne** [comment]
Jammer.

**Comment by arendst** [comment]
Implemented in next release

**Comment by decologne** [comment]
It's working fine with version 4.1.0.
Thanks for implementing.
