### ISSUE TITLE
Sonoff Wifi Pro 4CH R2 hangs?

### ISSUE THREAD

**Issue by dastrix80** [arendst/Sonoff-Tasmota#2733]
hi all,

since running Tasmota 5.11.1 on occasion my unit will lock up with the red LED lights permanently illuminated on the right side of the unit. Can anyone suggest some troubleshooting techniques? Even after a reset it will do the same thing.

It essentially requires me to disconnect the dry contacts connected into the relays for it to power up

Then it works again for a while

thanks

**Comment by ascillato** [comment]
Hi,

Please provide information as the Troubleshooting Template:

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ ] Hardware used : 
- [ ] Provide the output of command ``status 0`` :

**(Please, remember to close the issue when the problem has been addressed)**
