### ISSUE TITLE
Signalling from one switch to another for 2-way simulation

### ISSUE THREAD

**Issue by kaotix** [arendst/Sonoff-Tasmota#2739]
This is a request for help if anyone has done anything similar or could point me in the right direction.

I currently have the upstairs of my house wired with 1 button switches - apart from on the stairs where I have a 2-way switch that is for the light upstairs but can be controlled at the bottom of the stairs as well. Very common setup it's simply two 2-way switches connected to the light upstairs.

This is, however, where I hit issues with the Sonoff switches. I have yet to find any that have 2-way capability on a 4-gang switch (downstairs is a 4 button panel)
So, my thoughts were around using the downstairs panel that I've bought, wire up the switches like they are now and have the upstairs light changed to just an L1 (1-way) but have the switch upstairs simply fire off an MQTT push to turn the light on/off at the downstairs switch meaning there's no need to actually wire the light up stairs to the up stairs switch and thus removing the need for 2-way.

Unless someone has a better idea or could actually tell me if my idea is possible with the tasmota firmware?
Thanks in advance.

**Comment by kaotix** [comment]
@ascillato Thanks for the info, I'm going to rig it all up on the bench and test it to make sure I fully understand what you've explained as it's not something I've done with this firmware at the moment.

@MYLE-01 Also thanks for the info, I've not used Home Assistant so I'll look into that.

**Comment by ascillato** [comment]
@kaotix 

Another solution you can try is a direct device to device communication using KNX. Be aware of compiling and using the last version v5.14.0a of the development branch

**Comment by ascillato** [comment]
The configuration for that is also on the wiki.

**Comment by ascillato** [comment]
The best is using both solutions together :)

**Comment by ascillato** [comment]
Remember that if your wifi Router stop working, these solutions won't work.

**Comment by digiblur** [comment]
If they are already in a 3way(US)/2 way config you can use this type of install.  
https://www.youtube.com/watch?v=l-CM8JQmges

**Comment by ascillato** [comment]
Nice video! Thanks for sharing
