### ISSUE TITLE
Device Restart on WiFi Signal Lost

### ISSUE THREAD

**Issue by chvicky** [arendst/Sonoff-Tasmota#2743]
Hi There,

when wifi signal lost / not found / low signal device restart itself and load on it also restart
its should not restart on LOST WiFi signal

- [x] Hardware used :  SONOFF S31
- [X] Provide the output of command ``status 0`` :
09:16:38 RSL: STATUS = {"Status":{"Module":41,"FriendlyName":["S31Nomi"],"Topic":"sonoffs31n","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
09:16:38 RSL: STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","RestartReason":"Software/System restart","Uptime":"0T00:35:14","StartupUTC":"2018-05-16T07:41:24","Sleep":0,"BootCount":412,"SaveCount":1297,"SaveAddress":"FA000"}}
09:16:38 RSL: STATUS2 = {"StatusFWR":{"Version":"5.13.1","BuildDateTime":"2018-05-01T20:59:22","Boot":31,"Core":"2_4_0","SDK":"2.1.0(deb1901)"}}
09:16:38 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["Daimond","AB-E"],"TelePeriod":300,"SetOption":["00000001","55818000"]}}
09:16:38 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":529,"Free":472,"Heap":20,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3}}
09:16:38 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoffs31n-1791","IPAddress":"192.168.17.22","Gateway":"192.168.17.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.17.1","Mac":"5C:CF:7F:7D:26:FF","Webserver":2,"WifiConfig":3}}
09:16:38 RSL: STATUS7 = {"StatusTIM":{"UTC":"Wed May 16 08:16:38 2018","Local":"Wed May 16 09:16:38 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:07","Sunset":"20:26"}}
09:16:38 RSL: STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
09:16:38 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-05-16T09:16:38","ENERGY":{"Total":383.098,"Yesterday":46.133,"Today":44.365,"Power":775,"Factor":0.98,"Voltage":228,"Current":3.472}}}
09:16:38 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-05-16T09:16:38","Uptime":"0T00:35:14","Vcc":3.486,"POWER":"ON","Wifi":{"AP":1,"SSId":"Daimond","RSSI":42,"APMac":"64:66:B3:13:67:EC"}}}

**Comment by ascillato** [comment]
Hi,

The problem seems to be the ESP Library yout firmware has (`"Core":"2_4_0"`). That one has bugs related to WIFI.

Please, recompile using ESP Lib 2.3.0 or download the latest release [v5.14.0](https://github.com/arendst/Sonoff-Tasmota/releases)

**Comment by chvicky** [comment]
Thanks for replay 

i have updated it to  v5.14.0 but same problem

if wifi signal lost its restart itself due to restart relay click and load/computer running on it restart

**Comment by wongnam** [comment]
Try to use wificonfig 5
Disable wifi config but retry same AP without restart and flash writes

**Comment by chvicky** [comment]
Thanks problem solved, thanks for help
