### ISSUE TITLE
MQTT Websockets

### ISSUE THREAD

**Issue by loxK** [arendst/Sonoff-Tasmota#2749]
Some MQTT broker like mosquitto, do suppport MQTT over websockets. 

Wouldn't it be faster/ more responsive and less "ressource hungry" ?

**Comment by Frogmore42** [comment]
What resources concern you?
What speed issues have you seen?
Web sockets aren't necessarily less resource intensive, nor faster.

**Comment by Frogmore42** [comment]
Web sockets make it easy for browser apps to use networking/TCP.  Since Tasmota is not running in a browser, there is no reason to use web sockets.  To do so would require more resources and likely be slower.

Or, did you have something else in mind?

**Comment by ionciubotaru** [comment]
try Paho, for me works like a charm for years.

```
client = new Paho.MQTT.Client(mqttBrokerURI, "browser-" + (new Date().getTime()));
client.onConnectionLost = onConnectionLost;
client.onMessageArrived = onMessageArrived;
function mqttConnect() {
  client.connect({
  //    userName: mqttUsername,
  //    password: mqttPassword,
    cleanSession: false,
    onSuccess: onConnect
  });
}
function onConnect() {
 console.log("connected");
 client.subscribe("+/+/LWT");
 client.subscribe("stat/+/RESULT");
 client.subscribe("tele/+/STATE");
}
function onConnectionLost(responseObject) {
  if (responseObject.errorCode !== 0) console.log("connection lost:" + responseObject.errorMessage);
}
.............................
```

**Comment by chkr1011** [comment]
I would also like to see an option to use MQTT over WebSockets instead. The reason is that some brokers are only available over WebSockets. 

For example: When hosting an Azure App Service only HTTP endpoints are available and thus only MQTT over WebSockets will work. The ESP32 IDF already supports MQTT over WebSockets.

**Comment by edwinspire** [comment]
Does Tasmota currently support MQTT over WebSocket?

**Comment by sfromis** [comment]
No, Tasmota uses the standard MQTT protocol.
