### ISSUE TITLE
[Update Tasmota WIKI] Wemos D1 Mini - BME680 sensor added

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#2753]
Hello all,

Today I received my BME680 - Temperature, Humidity, Pressure and Gas Sensor. I've updated the [Tasmota Wemos Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos%20D1%20Mini) accordingly.

Cheers,
Ray

**Comment by ascillato** [comment]
:+1:

**Comment by FabianHM** [comment]
What does the unit "Kilo Ohm" have to do with Gas? Is this Serial Output?

**Comment by FabianHM** [comment]
@RaymondMouthaan : Yes, this is the correct anwear of my Question, but I meant something else ;-)
I just ordered this sensor for my project Heating-Room. I have planned with the sensor to monitor whether possibly gas leaks in the heating rom and this is the sensor apparently not suitable.

My hope was an output similar to the rove - multichannel gas sensor (which was too expensive for me)
https://github.com/arendst/Sonoff-Tasmota/pull/1245
![33229694-414cfca6-d1dc-11e7-9c33-b400e6e4ebd0](https://user-images.githubusercontent.com/26110738/40167092-6757392c-59c0-11e8-9bfc-2f243517afd0.png)
Does anyone have an idea how I can use the BME 680 for my needs?
Greetings Fabian

**Comment by ascillato** [comment]
:+1:

**Comment by moneybag** [comment]
What about IAQ ?

**Comment by djscolla** [comment]
Please DELETE the photo of your fantasy. Because in google image this photo is in 1° page. 
And I buy it! For nothings... ty
