### ISSUE TITLE
DS18x20 sensor shows 0.0 temperature

### ISSUE THREAD

**Issue by anoop-r-kulkarni** [arendst/Sonoff-Tasmota#2756]
Anything am I missing? AM2301 shows correct temperature and humidity but DS18x20 sensor always shows 0.0 only. (Release 5.13.1a) Both are configured on the GPIO14 pin)

Thanks
~anoop

**Comment by anoop-r-kulkarni** [comment]
wow ! let me try a few other DS18x20 sensors then ! thanks for the headsup !

~anoop

**Comment by localhost61** [comment]
;-)

**Comment by wongnam** [comment]
Did you try to pull up the signal with resistor as below picture.
![4b9f24c4-679f-4df3-8db9-f889e9b21535](https://user-images.githubusercontent.com/36041520/40183118-323c72f0-5a17-11e8-8c64-8050e790b998.jpeg)

**Comment by anoop-r-kulkarni** [comment]
Yes I understand. I meant, in each case, I had configured them as being connected to the GPIO14 pin. Also, I have bought the sensor (pic: https://www.golden-computer.com/sonoff-ds18b20-waterproof-temperature-sensor-for-th16.html) - so not sure I can really do the resistor etc.. as it looks a simple plug-n-play sensor..

Thanks

~anoop

**Comment by wongnam** [comment]
I had 1 DS18B20 also connected to GPIO14 of my sonoff basic that it must connect a pull up resistor to let it work.

**Comment by wongnam** [comment]
Need considering to have a pull up resistor If you connect a Sonoff DS18B20 to Sonoff basic with Tasmota FW.

No need resistor if connect it to TH16 or S22 due to in side the Sonoff switch already soldered a pull up resistor.

**Comment by anoop-r-kulkarni** [comment]
I am connecting to sonoff TH16

**Comment by Frogmore42** [comment]
Well, that still leaves the connector in the TH16.  I have a TH10 that has a jack that is very loose and the sensor didn't work.  I replaced it with a new better quality jack and everything is working fine.

**Comment by wongnam** [comment]
Yep, me too. I have a sonoff S22 that has a jack hole indented very deep so that the temperature sensor jack  lốe the connection.

**Comment by anoop-r-kulkarni** [comment]
Thanks all for the leads. I had bought one DS18B20 from some supplier and then ordered a batch of 50 from ITEAD. The ones from new batch are showing correct values.. Will trash the lone sensor that gives 0.0.

Am also closing the issue..

~anoop
