### ISSUE TITLE
Tasmota working only with an amazon fire tv stick? No echo or dot.

### ISSUE THREAD

**Issue by charliesz** [arendst/Sonoff-Tasmota#2771]
Hello everyone,
like most people with an issue I am totally new to smart homes, alexa and tasmota. I have only one Sonoff S20 with Tasmota Version 5.14.0 20180515 running. The web interface works like a charm but with alexa on my fire tv stick (2. gen) the sonoff won't be discovered. I tried searching over the alexa interface on my computer in the same network as the sonoff and the fire tv stick (2.3 Ghz). Alexa on my fire tv stick doesn't discover anything either.
I'm wondering if I do need an echo or dot device to get the sonoff discovered, but I couldn't get any answer to that for now.
I don't have any smart home server running like IObroker or similar and I don't have any smart home skills installed.

Thank you for your help and thank you anyway for this really nice software.

cheers

charlie

Edit: typos

**Comment by Jason2866** [comment]
You need at least one echo (dot). Only the app on a device doesnt work.
