### ISSUE TITLE
Changes to generic module

### ISSUE THREAD

**Issue by uberflyx** [arendst/Sonoff-Tasmota#2783]
Hi All

I like to use the generic module even on Sonoffs like the 4CH so that I can customize the switch order, etc. I solder wires to the on board buttons. In any case, the generic module is less generic than it can be as GPIO 9 and 10 are stuck on 0 for flash. Below I have pasted a modified version and made these USER so that the generic module can also be used with the 4CH or other ESP8285 modules. Wemos should leave these on NONE in the config obviously... Sorry it's not a PR - I'm in a rush and don't have a nice fork at the mo.

Thanks

"Generic",         // Any ESP8266/ESP8285 device like WeMos and NodeMCU hardware (ESP8266)
     GPIO_USER,        // GPIO00 D3 Wemos Button Shield
     GPIO_USER,        // GPIO01 TX Serial RXD
     GPIO_USER,        // GPIO02 D4 Wemos DHT Shield
     GPIO_USER,        // GPIO03 RX Serial TXD and Optional sensor
     GPIO_USER,        // GPIO04 D2 Wemos I2C SDA
     GPIO_USER,        // GPIO05 D1 Wemos I2C SCL / Wemos Relay Shield (0 = Off, 1 = On) / Wemos WS2812B RGB led Shield
     0, 0, 0,          // Flash connection
     GPIO_USER,        // GPIO09 Set to none on Wemos (flash)
     GPIO_USER,        // GPIO10 Set to none on Wemos (flash)
     0,                // Flash connection
     GPIO_USER,        // GPIO12 D6
     GPIO_USER,        // GPIO13 D7
     GPIO_USER,        // GPIO14 D5
     GPIO_USER,        // GPIO15 D8
     GPIO_USER,        // GPIO16 D0 Wemos Wake
     GPIO_ADC0         // ADC0   A0 Analog input
  },

**Comment by arendst** [comment]
I'm glad you found this solution. I won't change the config though for the simple reason I envision lots of issues from people not getting the grasp between ESP8285 and ESP8266. Most of them do not even know they have one of those chips...
