### ISSUE TITLE
Build firmware.bin

### ISSUE THREAD

**Issue by SzilagyiR** [arendst/Sonoff-Tasmota#279]
HI!

How can I create custom firmware.bin with edited user_config.h file?
I want to update firmware over webserver.

Thanks: Robert

**Comment by davidelang** [comment]
Take a look at the wiki. Read through the "Getting Started" section. It will 
probably answer your questions.

**Comment by smadds** [comment]
You can use the Arduino IDE: _Sketch, Export Compiled Binary_.
It will compile & save the binary image.

**Comment by SzilagyiR** [comment]
Thanks, I missed it!

**Comment by SzilagyiR** [comment]
When I try it, I gave this error:

![ardionoproblem](https://cloud.githubusercontent.com/assets/26599357/24373062/65c71eb0-1330-11e7-804f-e94cb3e498a7.png)

**Comment by davidelang** [comment]
look at the getting started section in the wiki, you are missing libraries that you need to install

**Comment by SzilagyiR** [comment]
Thanks, I look after it!

**Comment by SzilagyiR** [comment]
It works, thanks!

**Comment by seetendra** [comment]
Just a question on this . when we export the binary file do we know where is it stored

**Comment by andrethomas** [comment]
> Just a question on this . when we export the binary file do we know where is it stored

Usually for Arduino (as seen in the cases above) the exported bin file will be in the same folder as the code you are compiling.
