### ISSUE TITLE
Feature Request: Increase the space for rules

### ISSUE THREAD

**Issue by ascillato** [arendst/Sonoff-Tasmota#2791]
**Have you look for this feature in other issues and in the wiki?**

YES

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

At this moment, a lot of things can be achieved trough the rules feature, but with some more space, more complex solutions also can be achieved. For example, a complete example of a simple version of a Thermostat (showed below) uses 456 bytes, that it is too close to the limit of 512 bytes. So, for a complete thermostat with mode selection (OFF, CONFORT, NIGHT and FROST PROTECTION) where the modes will just change the uppper and lower setpoints for temperature, will be needed more space to be acomplished.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

To be increased the actual available 512 Bytes for rules between 800-1000 bytes.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

None

**Additional context**
_Add any other context or screenshots about the feature request here._

Following example.

--------------------------------------------------------------------------------------------------------------

**SIMPLE THERMOSTAT EXAMPLE**

As example, to be used on a Sonoff TH10 with Sensor Si7021

This example turn on and off an output based on the temperature value and the upper set point and the lower set point.
It waits until is enabled by pressing the button or by mqtt message 1 to mem1. This value is remembered. So if power cycle occurs, will resume operation.
The set point values can be changed on the fly by mqtt or console commands
If the Temperature sensor disconnects, the outputs will shutdown until the sensor is back again and will resume operation.
When the device is power up, the thermostat also waits until the sensor value to resume operation.

Inital Config:

* Available physical button as **switch1**
* **Relay1** will be used the controller

Inital config on console:

* `switchmode1 3`  <- Use the switch1 as pushbutton and disable the link between the button and the relay. The relay is now controlled by the rules and not by the button.
* `rule 1 `        <- turn on rules
* `rule 4`        <- turn off one-shot rule
* `teleperiod 60`  <- check temp every minute
* `setoption26 1`  <- use power1 on mqtt messages
* `setoption0 0`   <- dont save relay status on eeprom
* `poweronstate 0` <- start all relays off
* `mem1 0`         <- thermostat status: 0-off 1-enabled - View or set by MQTT cmnd/sonoff/mem1
* `mem2 25`       <- setpoint Temp upper limit - View or set by MQTT cmnd/sonoff/mem2
* `mem3 23`        <- setpoint Temp lower limit - View or set by MQTT cmnd/sonoff/mem3
* `var1 0 `       <- thermostat actual status: 1-OK 0-NOT READY - View by MQTT cmnd/sonoff/var1

Rules:

On boot start a watch dog timer to check temp sensor connection.
`rule on system#boot do backlog ruletimer1 70 endon`

An available button is configured as switch to set thermostat ON or OFF
`on switch1#state do backlog event toggling1=%mem1% endon`
`on event#toggling1=0 do backlog mem 1 endon`
`on event#toggling1=1 do backlog mem 0; var1 0; power1 0 endon`

Check temp sensor connection. If fails, set to off and turn off thermostat. Also continue checking
`on rules#timer=1 do backlog var1 0; ruletimer1 70; power1 0 endon`

Resets checking timer if temperature is connected
`on tele-SI7021#temperature do backlog var1 1; ruletimer1 70; event control=%value% endon`

Thermostat control - upper limit and lower limit
`on event#control>%mem2% do power1 0 endon`
`on event#control<%mem3% do power1 %var1% endon`

Thermostat can be turned On by:

* pushing button
* by command on local console: mem1 1
* by command on any other console: publish cmnd/sonoff/mem1 1
* or MQTT at: cmnd/sonoff/mem1 1

Thermostat can be turned Off by:

* pushing button
* by command on local console: mem1 0
* by command on any other console: publish cmnd/sonoff/mem1 0
* or MQTT at: cmnd/sonoff/mem1 1

To get the status:

* `mem1`        <- thermostat status: 0-off 1-enabled - View or set by MQTT cmnd/sonoff/mem1
* `mem2`       <- setpoint Temp upper limit - View or set by MQTT cmnd/sonoff/mem2
* `mem3`         <- setpoint Temp lower limit - View or set by MQTT cmnd/sonoff/mem3
* `var1`        <- thermostat actual status: 1-OK 0-NOT READY - View by MQTT cmnd/sonoff/var1

Everything together:

INITIAL CONFIG:

`backlog rule 1; rule 4; teleperiod 60; setoption26 1; setoption0 0; poweronstate 0; mem1 0; mem2 25; mem3 23`

RULES:

`rule on system#boot do backlog ruletimer1 70 endon on Switch1#State do backlog event toggling1=%mem1% endon on event#toggling1=0 do backlog mem 1 endon on event#toggling1=1 do backlog mem 0; var1 0; power1 0; endon on rules#timer=1 do backlog var1 0; ruletimer1 70; power1 0; endon on tele-SI7021#temperature do backlog var1 1; ruletimer1 70; event control=%value%; endon on event#control>%mem2% do power1 0 endon on event#control<%mem3% do power1 %var1% endon`

EXAMPLE RULES WITHOUT TEMP SENSOR TO TEST THE THERMOSTAT RULES

`rule on system#boot do backlog ruletimer1 70 endon on Switch1#State do backlog event toggling1=%mem1% endon on event#toggling1=0 do backlog mem 1 endon on event#toggling1=1 do backlog mem 0; var1 0; power1 0; endon on rules#timer=1 do backlog var1 0; ruletimer1 70; power1 0; endon on event#temp do backlog var1 1; ruletimer1 70; event control=%value%; endon on event#control>%mem2% do power1 0 endon on event#control<%mem3% do power1 %var1% endon`

TESTS:

* Push the button1. The thermostat changes to ENABLED (mem1=1)
* on console: event temp=20 (now the system receives like a tele message from temperature sensor) and will turn on the relay1 (to heat)
* on console: event temp=26 (the thermostat turn off the heater)
* on console: event temp=22 (the thermostat turn on the heater)
* wait more than a minute without using the event temp and the thermostat will turn off as there is no temperature value (like a sensor error or disconnection)
* will resume when using again the event temp

_This example was added also to the wiki on rules._ 

--------------------------------------------------------------------------------------------------------------

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Increasing space is not the biggest issue. The main problems are how to manage the rules and how to get them loaded into to the bigger area...

Currently using web or serial console the complete rule is loaded into the serial or web buffer before it is parsed into the final destination within Settings. Larger rules means larger serial/web buffers resulting in permanent loss of precious RAM. Using MQTT it assigns a temporary receive buffer which makes loading rules easier. A better way would be to manage a single rule within the rule set but that opens up a whole a new can of worms...


Also larger rule space will result in more rules to service within a small timeframe (currently around 1 second) to handle all possible sensor changes.

To ease my mind I stay on 512 character for the moment unless I suddenly wake-up with a great rule management idea...

**Comment by ascillato** [comment]
You are right. It makes things more complex.

One idea to keep it simple could be to have the actual RULE command as it is, and another RULE2 command. They can be independent from each other, and they can be turn on or off independently.

One cool thing about this approach is that you can have a group of rules with ONE-SHOT on and other group without it.

what do you think?

**Comment by arendst** [comment]
Great idea! and so simple! I'll drop all my problems with you!!!!

**Comment by ascillato** [comment]
Thanks :+1:
