### ISSUE TITLE
SONOFF 4 CH PRO Glitching

### ISSUE THREAD

**Issue by Michaelillingby** [arendst/Sonoff-Tasmota#2793]
Sometimes on reboot/restart one of the 4 channels will turn on randomly. 

I have turned off INCHING, by setting K6 to 1, and k5 (1-4) to 1

I am using this for Lawn irrigation, so having a zone randomly come on and stay on is undesirable to say the least

Also, make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ X] Searched the problem in issues and in the wiki
- [X ] Hardware used : SONOFF 4 CH PRO
- [ X] Provide the output of command ``status 0`` :

**To Reproduce**
Steps to reproduce the behavior: REBOOT and sometimes when switching between menus

**Expected behavior**
Nothing, just stay OFF, or default to OFF on restart/Reboot

04:54:11 RSL: stat/sonoff4ch/STATUS = {"Status":{"Module":23,"FriendlyName":["Zone 1","Zone 2","Zone 3","Zone 4"],"Topic":"sonoff4ch","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
04:54:11 RSL: stat/sonoff4ch/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:03:43","StartupUTC":"2018-05-21T03:50:28","Sleep":0,"BootCount":16,"SaveCount":158,"SaveAddress":"F6000"}}
04:54:11 RSL: stat/sonoff4ch/STATUS2 = {"StatusFWR":{"Version":"5.14.0a","BuildDateTime":"2018-05-20T20:12:04","Boot":6,"Core":"2_4_1","SDK":"2.2.1(cfd48f3)"}}
04:54:11 RSL: stat/sonoff4ch/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Michael's Wi-Fi Network",""],"TelePeriod":300,"SetOption":["00008009","55A18000"]}}
04:54:11 RSL: stat/sonoff4ch/STATUS4 = {"StatusMEM":{"ProgramSize":565,"Free":436,"Heap":16,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","00000000","17B6179A","00000000"]}}
04:54:11 RSL: stat/sonoff4ch/STATUS5 = {"StatusNET":{"Hostname":"sonoff4ch-3929","IPAddress":"10.0.1.80","Gateway":"10.0.1.1","Subnetmask":"255.255.255.0","DNSServer":"10.0.1.1","Mac":"60:01:94:9F:4F:59","Webserver":2,"WifiConfig":3}}
04:54:11 RSL: stat/sonoff4ch/STATUS6 = {"StatusMQT":{"MqttHost":"10.0.1.2","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_9F4F59","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
04:54:11 RSL: stat/sonoff4ch/STATUS7 = {"StatusTIM":{"UTC":"Mon May 21 03:54:11 2018","Local":"Mon May 21 04:54:11 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:01","Sunset":"20:32"}}
04:54:11 MQT: stat/sonoff4ch/STATUS10 = {"StatusSNS":{"Time":"2018-05-21T04:54:11"}}
04:54:11 RSL: stat/sonoff4ch/STATUS11 = {"StatusSTS":{"Time":"2018-05-21T04:54:11","Uptime":"0T00:03:43","Vcc":3.520,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"Michael's Wi-Fi Network","RSSI":100,"APMac":"6C:70:9F:DE:EB:80"}}}

**Comment by wongnam** [comment]
Maybe MQTT broker retain the last sent mesage.
Try to evaluate as below:
1 - turn on by mqtt(dashboard/App) then turn off it by the button. Restart it. -> expect it will auto turn on.
2- turn off by mqtt. Restart it -> expect it will stay off.

If above was happen, mean that your Mqtt broker retain the last sent massage. Find solutions to fix.
