### ISSUE TITLE
[Update Tasmota WIKI] Python HTTP server for OTA upgrades

### ISSUE THREAD

**Issue by gtortone** [arendst/Sonoff-Tasmota#2804]
Hi,
a new wiki page is available to learn how to use Python HTTP server for OTA upgrades:
https://github.com/arendst/Sonoff-Tasmota/wiki/Python-HTTP-Server

@arendst please move image included in this wiki page on your GIT space... thanks !

**Comment by arendst** [comment]
Thnx! @gtortone image moved also.
