### ISSUE TITLE
Sonoff Touch Flashing Error!

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#2812]
I can't get success with flashing sonoff touch!! 
this is the logs from Atom:

Linking .pioenvs\sonoff\firmware.elf
Checking program size
text       data     bss     dec     hex filename
530491    10908   43096  584495   8eb2f .pioenvs\sonoff\firmware.elf
Building .pioenvs\sonoff\firmware.bin
Configuring upload protocol...

Looking for upload port...
Use manually specified: COM3
Uploading .pioenvs\sonoff\firmware.bin
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
*** [upload] Error -1
 [ERROR] Took 9.84 seconds

please any help?
all connector or corect after tons of check! 

THANKS!!

**Comment by ricadelic** [comment]
I had this too, no matter how i connected it. I ended up updating via the wireless method, that worked.

**Comment by shayshtern** [comment]
@ricadelic I tried the wireless method, how did u get find the Wi-Fi? cause I can't find it. did u power your sonoff Touch with an FTDI or power it with the 220V in wall?

**Comment by appde** [comment]
@shayshtern Reducing upload_speed in platformio.ini file fixes most of the issues:
```
upload_speed = 115200
;upload_speed = 512000
```

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.
