### ISSUE TITLE
Sonoff Pow Jack Plug

### ISSUE THREAD

**Issue by jannnfe** [arendst/Sonoff-Tasmota#2818]
Hello,
I was wondering if it is possible to retrofit a Jack Plug with the Sonoff Pow, for example to connect a thermometer. Then I looked at both devices (Sonoff Pow and Sonoff TH10 / 16) a little closer and found that this should actually be possible. This is also possible with the Sonoff 4CH, as you can already read in the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-4CH).

You just have to buy a Jack Plug and connect it to GPIO3 Serial In. How exactly you have to connect this I wanted to ask from you here. Can someone please tell me exactly what I need and how I have to wire the whole thing for it to work?

Some Pictures:
![img_1892](https://user-images.githubusercontent.com/30130742/40498928-b21f5eba-5f80-11e8-96b6-dc205a7b362e.JPG)
![img_1894](https://user-images.githubusercontent.com/30130742/40498929-b25355bc-5f80-11e8-8eef-ece78f2b2f17.JPG)
![img_1895](https://user-images.githubusercontent.com/30130742/40498930-b271bc00-5f80-11e8-910c-6983440992fe.JPG)
![img_1896](https://user-images.githubusercontent.com/30130742/40498931-b29e7682-5f80-11e8-8931-22c4693a6773.JPG)

Thanks! :)

**Comment by gtortone** [comment]
Hi,
I did it on Sonoff-4CH:
https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-4CH

**Comment by jannnfe** [comment]
Hey @gtortone,
Yes, I have already said in my post, but the whole thing on the Sonoff Pow looks a little different. There is no R35 pad and how do I have to wire the entire Sonoff Pow. I'm really bad in something and I hope someone can say exactly what I have to do.
Thanks :)

**Comment by MatzeJoerling** [comment]
take rx/tx and use them for i2c or connect a sensor! dissable SERIAL logging in tasmota, done.
Connector J3! 
https://www.itead.cc/wiki/images/5/52/Sonoff_POW_Schematic.pdf

**Comment by jannnfe** [comment]
Hello @MatzeJoerling,
So I do not need a 4.7Kohm pullup resistor between DATA pin and 3.3V as it @gtortone did? I simply use either RX or TX for data transfer right?
![temperature-sensor-dallas-pinout-diagram](https://user-images.githubusercontent.com/30130742/40505281-ffd1b460-5f93-11e8-81df-7c879512a666.jpg)


The jack plug is not required but is the more elegant solution. That's why I wanted to ask what exactly on which "ring" is the jack connection?
![img_1905](https://user-images.githubusercontent.com/30130742/40505526-c167c7f4-5f94-11e8-9809-e580d760a07e.png)
Thanks! :)

**Comment by MatzeJoerling** [comment]
Hi, pullup would be nice, more reliable. with only one ds18b20 it will work without, i belive.
according to https://www.itead.cc/wiki/images/3/39/Sonoff_TH10A%2816A%29_schmatic.pdf J2 i would suggest that 
4: GND / 2: VCC and 3/1 Data for 2 inputs?
![image](https://user-images.githubusercontent.com/25864208/40507799-24c4f396-5f98-11e8-8355-b1e5c0160d1c.png)

try it.

**Comment by Jason2866** [comment]
The resistor is neccersary, without it will not work!

**Comment by jannnfe** [comment]
Okay so i put one 4.7Kohm pullup resistor between VCC and RX right? I'm not using TX.
[This resistor](https://www.ebay.de/itm/200x-SMD-0805-Widerstand-4-7k-1-0-125W-150V-ROYAL-OHM-0805S8F4701T5E/181750949484?hash=item2a5133666c:g:2bEAAOSwpDdVXFDg) or [this resistor](https://www.ebay.de/itm/10x-Widerstand-4-7KOhm-DHT-DS18B20-Metallfilm-Resistor-4-7K-Arduino-Raspberry/252712608097?hash=item3ad6d86161:g:vCQAAOSwVtZaD3J-) or it doesn't matter?
![bildschirmfoto 2018-05-24 um 21 55 20](https://user-images.githubusercontent.com/30130742/40511037-d2e9123a-5f9e-11e8-9547-07186b0f4ee0.png)

I connect VCC, GND and RX to jack plug.
According to [this file](https://www.itead.cc/wiki/images/4/40/DS18B20.pdf) about DS18B20 Sensor, one of the four Pins of the Jack is not connected, so we have only 3 Pins. Wiring the jack plug i have to try i think :D
But [this 4 pin Jack socket](https://www.aliexpress.com/item/10pcs-2-5mm-Phone-Jack-4-contacts-4-conductors-TRRS-Audio-Stereo-Socket-Through-Hole-Right/32788968290.html?spm=a2g0s.8937460.0.0.4ae52e0euU8v08) should work right?

Thanks for all your help! I do not want to do anything wrong and do not order anything wrong, because things from China are on the way for a long time! :)

**Comment by arendst** [comment]
If you continue on this path I would like to send you my best wishes in your afterlife...

As stated on the pow wiki page never connect a sensor to a pow. Your choosen sensor is my favorite as the casing is connected to Gnd/AC power on Pow.

May the force be with you (and wear a rubber underpants).

**Comment by Frogmore42** [comment]
Please re-read the wiki page on the Pow and then reread it again.

Connecting sensors to the pow is at best dangerous and possibly deadly.  While it is possible to do it, Tasmota (by design) does not support it and it will allow to configure the sensor.

More than one person has destroyed a pow by accident trying to do this.

It is a best practice to separate your low voltage sensors from you high voltage things.  The pow makes it impossible to do this.  The TH10/16 have some separation and are reasonably okay, but I am no longer adding sensors to them. I now use wemos D1 Mini devices for all my sensors.  This is much safer but a little more expensive.

**Comment by jannnfe** [comment]
Okay thanks for the feedback! That would have become something. This would have done the subject then. Thank you anyway for the lively help until then.

**Comment by Jason2866** [comment]
Thx @arendst for your comment. I didnt realized that the device is a pow!
I use all my sensors on Wemos minis too so i do not think about ac power.
In future i will double check before writing maybe dangerous....

**Comment by jannnfe** [comment]
@arendst @Frogmore42 One last question. Whats about the Sonoff Dual? Can I add a Sensor as described above on this Sonoff?

**Comment by ascillato** [comment]
Please,

This is a very **_DANGEROUS_** situation. **_DO NOT TRY THIS_**.

## Please, change the title of the issue to NOT DO THIS.

# **_You WILL BE ELECTROSHOCKED!!!!_**

Only use sensors on a WEMOS, NODEMCU, SONOFF SV (Safe Voltage) and on any Sonoff **_prepared_** for a sensor.

AVOID PUT PEOPLE LIFES IN DANGER !!!!!

**Comment by AlexTransit** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/1941#issuecomment-366917098

**Comment by ascillato** [comment]
The devices that uses Mains AC (220v or 110v) and also uses sensors or parts that a human could touch, those devices use a optocoupler that separate the main AC (220v or 110v) from the 5v or 3.3v. This optocoupler link is a link by light. Is a device with a LED emiter and a LED Receiver. No direct connection. So the low voltage section is safe and disconnected from the mains.

Sonoff POW do not use an optocoupler. It uses a direct link between the power measurement chip (that is connected to main ac) and the ESP8266 chip.

That's why, your sensor WILL BE on mains AC and you WILL BE ELECTROCUTED.

**Comment by ascillato** [comment]
@jannnfe 

If you need the temperature value, use a sonoff TH.

If you do not want to buy that, use a cheap nodemcu with the temp sensor and took the decisions on that device and send the command to your sonoff dual. you can use MQTT, KNX, etc. There are plenty of safe options.

**Comment by zauberer69** [comment]
![40505526-c167c7f4-5f94-11e8-9809-e580d760a07e](https://user-images.githubusercontent.com/40359220/41536847-092636f4-7307-11e8-97e2-5673bf42170e.png)

Solution:
4 -> VCC
3 -> GND
1 -> Data

**Comment by ascillato** [comment]
@zauberer69

That is not a solution. That is a call for death. Please DO NOT CONNECT SENSORS TO A SONOFF POW. 

VERY DANGEROUS

read all the thread before posting.

**Comment by AlexTransit** [comment]
3 -> GND
GND internal connected to ACC line.
https://github.com/arendst/Sonoff-Tasmota/issues/1941

**Comment by DIYglenn** [comment]
Hmm, I just did the 4ch mod, is it just as dangerous there?
