### ISSUE TITLE
rules => publish to any other tasmota without a broker

### ISSUE THREAD

**Issue by gemu2015** [arendst/Sonoff-Tasmota#2821]
it would be nice to publish in rules to any other device like

=> publish http://192.168.178.86/cm?cmnd=POWER1 ON

without the need of any broker

**Comment by arendst** [comment]
Alas, MQTT needs a broker.

Alternative is HTTP (webserver). I'm investgating ...

**Comment by arendst** [comment]
I'll look at HTTP too...
