### ISSUE TITLE
How to set MQTT topic as Hostname in a group?

### ISSUE THREAD

**Issue by anoop-r-kulkarni** [arendst/Sonoff-Tasmota#2822]
Typically, here is my scenario:

MQTT GroupTopic:  sonoffs
MQTT Topic: sonoff
Hostname: sonoff-6723 (from the MAC)

I have some 50 devices with similar settings in a facility. Is there a command(s) in which I can set the MQTT Topic as "sonoff-6723" and for all other devices by their hostname  in the group "sonoffs" ?

Appreciate your assistance..Many thanks
~anoop

**Comment by wasi54** [comment]
You may directly use the "Fallback-Topic" "DVES_??6723" which is also built from MAC
