### ISSUE TITLE
[Info] SonWEB renamed to TasmoAdmin

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#2823]
Hai all,

On behalf of @reloxx13 and myself, I like to inform you about SonWEB which has been renamed to TasmoAdmin, since it covers more then Sonoff devices only (i.e. Wemos).

_"TasmoAdmin (previously SonWEB) is an administrative Website for Devices flashed with Sonoff-Tasmota."_

- [Github TasmoAdmin](https://github.com/reloxx13/TasmoAdmin)
- [Docker Hub TasmoAdmin](https://hub.docker.com/r/raymondmm/tasmoadmin)
- [Hassio Addon](https://github.com/hassio-addons/addon-sonweb) (thanks to @frenk, @ascillato 👍)

__note: the project is still in renaming phase, so you might encounter some issues.__

Cheers,
Ray

**Comment by ascillato** [comment]
:+1:
