### ISSUE TITLE
Sonoff basic as a numb switch to respond on switch only

### ISSUE THREAD

**Issue by c3reeman** [arendst/Sonoff-Tasmota#2825]
Hi,

First of all loving the tasmota and thanks to those involved, I baught some cheap Sonoff basics as a trial, and I love them so much with Tasmota I’ve just orderd 40 more and a few Pow R2’s and finally some Sonoff temp sensors, I’m building a junction box full Of tasmota’s as a lighting wiring hub for a barn conversion I’m currently on with.  

Anyways my question I’m linking a Sonoff basic into some existing motion sensors The motion sensors are driving a 230v (uk) relay that are then linked into the Sonoff basic for the 5v switching and it’s working much the same as a basic light switch so running on gpio14 09 switch 1, and it’s working great motion sensed turning Sonoff on after physical motion sensor timer runs 
Out Sonoff turned off following the 240 relay, however.... my potential problem is if the Sonoff is turned on or off via home assistant or tasmota page it could potentially become out of sync flipping the output so motion actually turned it off and no motion puts it on....

Is it possible to set the tasmota as a numb switch only responding to the physical switch input ? My logic for doing this is to purely use it as a flag in home assistant to turn other lights on around the house that are also connected with Sonoff basics, so the Sonoff won’t actually have a physical output connected as such it’s just a flagging system

Hope this make sense and look forward to any replies 

Thanks

**Comment by c3reeman** [comment]
One solution I did think of was to use the pulse timer function and set it at about 10 minutes ( the outside motion sensors are set at 8 minutes ) this way if it did some how get inverted it would always reset it’s self after 10 minutes ? Appreciate it if anyone has a better simpler option

**Comment by Dickesplumpel** [comment]
I am not really shure what you want to know but it looks like your switch is set to TOGGEL (default) that sometimes can flip around so that on and off is changed, set it in the console to FOLLOW (switchmode1 1) or FOLLOW inverse (switchmode1 2) - example is for switch1. See tasmota commands for more details: 
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by c3reeman** [comment]
Ah that’s the one, thankyou ... I had a play with switch modes before posting and didn’t think it worked as I needed but after you suggested I’ve just had another play and noted It actually works perfectly
