### ISSUE TITLE
GPIO3 not working correctly as PWM output

### ISSUE THREAD

**Issue by Flori1989** [arendst/Sonoff-Tasmota#2831]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [x] Hardware used : ESP-01
- [x] Provide the output of command ``status 0`` :
``23:18:40 MQT: stat/sonoff-rgb2/STATUS = {"Status":{"Module":18,"FriendlyName":["Sonoff RGB2"],"Topic":"sonoff-rgb2","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"External System","Uptime":"0T00:01:09","StartupUTC":"2018-05-25T22:17:31","Sleep":0,"BootCount":19,"SaveCount":150,"SaveAddress":"F6000"}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS2 = {"StatusFWR":{"Version":"5.14.0","BuildDateTime":"2018-05-25T23:26:16","Boot":31,"Core":"2_4_1","SDK":"2.2.1(cfd48f3)"}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["LordWLAN",""],"TelePeriod":300,"SetOption":["00008009","55818000"]}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS4 = {"StatusMEM":{"ProgramSize":551,"Free":452,"Heap":14,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS5 = {"StatusNET":{"Hostname":"sonoff-rgb2-6475","IPAddress":"192.168.178.25","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"60:01:94:0B:59:4B","Webserver":2,"WifiConfig":3}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.178.51","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0B594B","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS7 = {"StatusTIM":{"UTC":"Fri May 25 22:18:40 2018","Local":"Fri May 25 23:18:40 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"04:56","Sunset":"20:37"}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS10 = {"StatusSNS":{"Time":"2018-05-25T23:18:40"}}
23:18:40 MQT: stat/sonoff-rgb2/STATUS11 = {"StatusSTS":{"Time":"2018-05-25T23:18:40","Uptime":"0T00:01:09","Vcc":3.247,"POWER":"ON","Dimmer":99,"Color":"FCFCFC","HSBColor":"0,0,99","Channel":[99,99,99],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"LordWLAN","RSSI":86,"APMac":"38:10:D5:FB:EB:B2"}}}``

**(Please, remember to close the issue when the problem has been addressed)**

I have an ESP-01 flashed with Tasmota to control an RGB-LED via PWM. When changing the dimmer the Led on GPIO3 tends to go off instead of showing the correct value. It only will go on again if I change the dimmer value one or two more times. I have already tested some other Leds and another ESP-01 module. It's still the same.
Is there any way to fix this behaviour?

**Comment by arendst** [comment]
Expect problems on GPIO03 as it is the Serial input too. Select another GPIO.
