### ISSUE TITLE
sonoff basic switch2 switches relais1

### ISSUE THREAD

**Issue by Dickesplumpel** [arendst/Sonoff-Tasmota#2832]
Only to notice:
The ailight bulb works with setoption26 on and rule sending domoticz/in but when I try the same on a sonoff basic switch2 switches relais1 when no relais2 is defined. With dummy relais2 on unused GPIOx everything works fine. I don't know if its a bug or if its meant to be working like this. In my case it works and thats enough for me but maybe in other cases there may be trouble - don't know!

**Comment by Jason2866** [comment]
This is the known and wanted behaviour.

**Comment by Dickesplumpel** [comment]
Thanks!
