### ISSUE TITLE
Magichome i dont have slider for cold  to warm 

### ISSUE THREAD

**Issue by dr-apple** [arendst/Sonoff-Tasmota#2834]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ x] Hardware used : 
- [ x] Provide the output of command ``status 0`` :
13:00:12 MQT: stat/kueche_Licht_4/STATUS = {"Status":{"Module":34,"FriendlyName":["Küche Licht 4"],"Topic":"kueche_Licht_4","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:09:38","StartupUTC":"2018-05-26T11:50:34","Sleep":0,"BootCount":22,"SaveCount":101,"SaveAddress":"3F7000"}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS2 = {"StatusFWR":{"Version":"5.14.0b","BuildDateTime":"2018.05.25 18:44:06","Boot":31,"Core":"2_4_0_RC2","SDK":"2.1.0(7106d38)"}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Mega_Wlan_2.4GHZ_FB",""],"TelePeriod":300,"SetOption":["00108009","55A18000"]}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS4 = {"StatusMEM":{"ProgramSize":504,"Free":516,"Heap":10,"ProgramFlashSize":4096,"FlashSize":1024,"FlashMode":2,"Features":["00000407","07802790","00000000","00000092","00000000"]}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS5 = {"StatusNET":{"Hostname":"Kueche Licht 4","IPAddress":"192.168.0.143","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"5C:CF:7F:C6:7B:35","Webserver":2,"WifiConfig":3}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.5","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C67B35","MqttUser":"drapple","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS7 = {"StatusTIM":{"UTC":"Sat May 26 12:00:12 2018","Local":"Sat May 26 13:00:12 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"04:55","Sunset":"20:38"}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS10 = {"StatusSNS":{"Time":"2018-05-26T13:00:12"}}
13:00:12 MQT: stat/kueche_Licht_4/STATUS11 = {"StatusSTS":{"Time":"2018-05-26T13:00:12","Uptime":"0T00:09:38","Vcc":3.513,"POWER":"OFF","Dimmer":100,"Color":"FF000000","HSBColor":"0,100,100","Channel":[100,0,0,0],"Scheme":2,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"Mega_Wlan_2.4GHZ_FB","RSSI":76,"APMac":"20:A6:CD:88:8A:41"}}}
**(Please, remember to close the issue when the problem has been addressed)**

I have 3 Magichome device, but only 1 have the slider for cold to warm :

![bildschirmfoto 2018-05-26 um 14 02 25](https://user-images.githubusercontent.com/15102858/40575873-601170b8-60ed-11e8-940c-e3d1b4e1cc4d.png)

![bildschirmfoto 2018-05-26 um 14 02 34](https://user-images.githubusercontent.com/15102858/40575877-6d520148-60ed-11e8-89d9-914cfb4e82dc.png)

All devices have the same firmware...

Have set SetOption15 1 !

What can i do to became the slider ?

**Comment by arendst** [comment]
One has only two PWMs configured (Cold/Warm), the other have three PWMs configured (RGB)
