### ISSUE TITLE
Issue flashing Sonoff T1 1CH and T1 2CH

### ISSUE THREAD

**Issue by tuchocaldera** [arendst/Sonoff-Tasmota#2844]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ ] Hardware used : 
- [ ] Provide the output of command ``status 0`` :

**(Please, remember to close the issue when the problem has been addressed)**
I have been flashing Sonoff T1 1CH and T1 2CH and have experienced the following: After successfully flashing Sonoff T1 1CH I proceeded to configure it as "T1" but I realized that physically the button didn't work (!?). I decided then to configure it as "Touch" and it worked normally there. Then I flashed the T1 2CH and configured it as "T1 2CH". Again I could verify that one of the buttons physically didn't work and I could not recover it. Through mit netværk and my phone the 2 channels work perfectly. I don't know what is happening. Is there anyone who has experienced something similar?. Is there a solution to the problem?
I am using firmware Sonoff-Tasmota Arduino IDE

**Comment by curzon01** [comment]
Dupilcate issue #2835
