### ISSUE TITLE
google cloud MQTT support

### ISSUE THREAD

**Issue by upendrawww9** [arendst/Sonoff-Tasmota#2849]
Do you support Google Cloud MQTT service.??
Now we have only cloudmqtt support.

Regards
Upendra

**Have you look for this feature in other issues and in the wiki?**
YES
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
As it only supports TLS 1.2 tasmota does not support it. Not enough resources available on a tasmota running esp8266.

**Comment by mikizvi** [comment]
Hi,

I found a way to bridge MQTT's where your local home Mosquitto can talk TLS 1.2 to the remote MQTT server.  Details are in the Kapppelt gBridge doc, referenced from [here](https://github.com/arendst/Sonoff-Tasmota/issues/2146#issuecomment-445438821).

Michael.
