### ISSUE TITLE
Sleep & Pulsetime

### ISSUE THREAD

**Issue by BigWumpus** [arendst/Sonoff-Tasmota#2850]
SLEEP does stretching time in SONOFF-Devices, so PULSETIME does wrong

OK

I think, there should be a reminder in the documentation of the commands and options, so the users are aware of this!
Today I run in the same trouble...

**Comment by curzon01** [comment]
It is
[Energy Saving Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Energy-Saving)

**Comment by ascillato2** [comment]
Hi,

As the root cause of this and other issues is SLEEP, we can put all them together in #3581 so as to track the problem and try to search a solution.

**Comment by ascillato** [comment]
Solved
