### ISSUE TITLE
"arendst/Sonoff-Tasmota" + "martin-ger/esp_wifi_repeater"

### ISSUE THREAD

**Issue by skyttan5** [arendst/Sonoff-Tasmota#2852]
Hi,
I'm curious to know if it possible to combine Tasmota and esp_wifi_repeater so that devices with the Tasmota firmware can also work as Wifi NAT routers?

The purpose of this feature is obviously to extend the wifi signal and hopefully create a wifi mesh network

**Comment by Leseratte10** [comment]
I highly doubt the ESP has enough flash and memory to handle all of that at once ...

**Comment by Frogmore42** [comment]
In addition the esp8266 would be extremely slow at that.  If you need a repeater, get one.  But many of the wireless ones can actually make things slower since they take up valuable air time repeating things.
