### ISSUE TITLE
Choose for power/state to be published as 0/1 instead of OFF/ON

### ISSUE THREAD

**Issue by McCloud** [arendst/Sonoff-Tasmota#286]
As said above, it would be ideal if I could switch between them or be able to change them.  Some of the MQTT related stuff I'm using is sometimes looking for a 0/1 instead of OFF/ON.

**Comment by davidelang** [comment]
This can be set in user_config*

**Comment by McCloud** [comment]
Yeah, I already saw that.  Any intent to add that to the commands list or UI so it can be changed without unique compiles?

**Comment by davidelang** [comment]
not at this time.

**Comment by arendst** [comment]
Will do in next version.

**Comment by McCloud** [comment]
Other two commands work, but "statetext2 1" seems to never actually update and keeps putting out "ON" as the setting

**Comment by arendst** [comment]
And why do you think it won't work....

RTFW and use only 10 characters at most.

**Comment by McCloud** [comment]
You're totally right, for whatever reason a reboot fixed it, before even simple test cases like "14:47:33 CMND: statetext2 ontest" were still returning the previous value. 

Thanks
