### ISSUE TITLE
Wemos D1 mini: No NTP, constant clock resets

### ISSUE THREAD

**Issue by titomontes** [arendst/Sonoff-Tasmota#2860]
Hello again

I just flashed a Wemos D1 mini (still trying to figure out mqtt for reading motion sensor/luminance/temp/humidity). Problem is, it doesn´t get the time from the time servers provided. Every reboot resets the clock, also. I figure there will be no timers available; is there anything to change in user_config.h?

```
00:14:12 MQT: stat/wemos1/STATUS = {"Status":{"Module":18,"FriendlyName":["Wemos1"],"Topic":"wemos1","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":1,"PowerRetain":1}}
00:14:12 MQT: stat/wemos1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"wemoss","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin","RestartReason":"Exception","Uptime":"0T00:14:07","StartupUTC":"","Sleep":0,"BootCount":26,"SaveCount":463,"SaveAddress":"F5000"}}
00:14:12 MQT: stat/wemos1/STATUS2 = {"StatusFWR":{"Version":"5.14.0b","BuildDateTime":"2018-05-29T20:06:28","Boot":31,"Core":"2_4_0","SDK":"2.1.0(deb1901)"}}
00:14:12 MQT: stat/wemos1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Montes01",""],"TelePeriod":300,"SetOption":["000280E9","55818000"]}}
00:14:12 MQT: stat/wemos1/STATUS4 = {"StatusMEM":{"ProgramSize":542,"Free":460,"Heap":13,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3,"Features":["00000809","0FDAE794","00000000","17BE179A","00000000"]}}
00:14:12 MQT: stat/wemos1/STATUS5 = {"StatusNET":{"Hostname":"wemos1-6219","IPAddress":"192.168.1.50","Gateway":"192.168.1.2","Subnetmask":"255.255.255.0","DNSServer":"80.58.61.250","Mac":"68:C6:3A:CA:78:4B","Webserver":2,"WifiConfig":3}}
00:14:12 MQT: stat/wemos1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.10","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_CA784B","MqttUser":"tito1","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:14:12 MQT: stat/wemos1/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 00:14:12 1970","Local":"Thu Jan 01 00:14:12 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":1,"Sunrise":"07:38","Sunset":"16:58"}}
00:14:12 MQT: stat/wemos1/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:14:12","Switch1":"OFF","AM2301":{"Temperature":30.1,"Humidity":50.2},"TSL2561":{"Illuminance":9.450},"TempUnit":"C"}}
00:14:12 MQT: stat/wemos1/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:14:12","Uptime":"0T00:14:07","Vcc":2.973,"POWER":"ON","Wifi":{"AP":1,"SSId":"Montes01","RSSI":76,"APMac":"34:97:F6:61:67:C0"}}}
```
Also, if anyone could help out setting up the MQTT config I would really appreciate it.

Cheers

**Comment by Frogmore42** [comment]
It looks like you have MQTT set up.  You probably are having issues with core 2.4.0 like many others.  I would suggest recompiling with core 2.3.0 and see if that makes things better.

**Comment by titomontes** [comment]
Yes , but the bug supposedly affects all boards, not just de wemos. I have another 10 sonoffs that work flawlessly with the correct time, so I wonder if this is a wemos related bug.

**Comment by Frogmore42** [comment]
If you search the issues, I am sure you will find lots of examples where ONLY particular boards had an issue with 2.4.x.  If it is working for you great, use it.  If you are having a wired issue, one of the first things to try is change to 2.3.0.

Your "Heap":13 indicates this device is probably suffering from the issue.  That is a pretty low value for heap.

**Comment by ascillato** [comment]
Hi,

Could you manage to solve it?

**Comment by titomontes** [comment]
Nope, it's still an issue. I don't see how only the NTP time can be affected by the issue, Also, I have no clue on how to compile in another version...

**Comment by Frogmore42** [comment]
See this issue for help with changing the core: https://github.com/arendst/Sonoff-Tasmota/issues/2689

If you are happy with the performance of what you have, please stay with it.  If not, the next thing to try is to use a core that is known to not have issues with WiFi connectivity (instead of one that is known to have strange issues sometimes).

The 2.4.x cores have caused a lot of people a lot of grief, but they have also worked flawlessly for a lot of people.  The usage of it might or might not be causing the issue you are seeing.  No one will know until you choose to try it.  Many others were surprised when it fixed their issue, maybe you will be too.

**Comment by ascillato2** [comment]
Hi,

Please, try last release to see if solves your issue. Thanks

**Comment by ascillato2** [comment]
Hi

Seems that you are using fixed IP. If that is the case, you need to check if your gateway and dns configuration are ok. If not, Tasmota can not connect to internet to sync Time with NTP Servers. 

If you managed to solve your issue, please close it. Thanks

**Comment by ascillato** [comment]
Hi, any news on this issue?

**Comment by ascillato2** [comment]
Hi,

Closing this issue as there is no feedback. Please, ask to reopen if needed. Thanks
