### ISSUE TITLE
Add optional retain flag to Publish command

### ISSUE THREAD

**Issue by yoh-there** [arendst/Sonoff-Tasmota#2861]
This is related to #2851 

If a rule is used to determine a state (in said example the dimmer state), it would be nice if optionally a retained MQTT message instead of a normal message could be published. This would avoid using an automation hub solely for that purpose. As I don't think a second parameter is feasible in the tasmota command architecture, maybe an approach is to implement a PUBLISHRETAIN command.

Thank you for considering.

**Comment by ascillato** [comment]
Hi,

On the file _user_config.h_ you can set at [line 89](https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/user_config.h#L89):

```
#define MQTT_BUTTON_RETAIN     0                 // [ButtonRetain] Button may send retain flag (0 = off, 1 = on)
#define MQTT_POWER_RETAIN      0                 // [PowerRetain] Power status message may send retain flag (0 = off, 1 = on)
#define MQTT_SWITCH_RETAIN     0                 // [SwitchRetain] Switch may send retain flag (0 = off, 1 = on)
```

**Comment by yoh-there** [comment]
I know, and it can even be set with Options (ie for POWER), but that is not what I meant. I meant when using the Publish command in a rule.

**Comment by ascillato** [comment]
@yoh-there 

PR #3593 with command `PUBLISH2` for sending retained MQTT messages

**Comment by yoh-there** [comment]
Thank you, great job

**Comment by ascillato** [comment]
Sorry for the delay. Thanks for the patience :+1:
