### ISSUE TITLE
Add iFan02 support

### ISSUE THREAD

**Issue by apastuszak** [arendst/Sonoff-Tasmota#2869]
Sonoff now has a ceiling fan controller.

https://www.itead.cc/sonoff-ifan02-wifi-smart-ceiling-fan-with-light.html

Would be nice if Tasmota worked with it.

**Comment by ascillato** [comment]
It is already open that request at https://github.com/arendst/Sonoff-Tasmota/issues/2839
Please, let's close this issue and we can leave the previous one as a follow up. thanks
