### ISSUE TITLE
Power State on WiFi Connection loss

### ISSUE THREAD

**Issue by HavoK-at** [arendst/Sonoff-Tasmota#287]
Hey!

Is it possible to add a default state for power on WiFi connection loss? 
I just want to be sure my stuff is turned off even if the sonoff loses connection.
Short question, what is the purpose of BlinkCount and BlinkTime?

Thanks!

**Comment by davidelang** [comment]
There is a default state on poweron, but not on wifi/mqtt connection loss. I suspect that you loose connection a lot more frequently than you imagine, but it's worth experimenting with.

**Comment by sebastianlorenzen** [comment]
I have "the same issue" My sonoffs are going on and off after network issues. sometimes if just blinks, sometimes to light stays on for hours.

**Comment by cduvenhorst** [comment]
+1

**Comment by cduvenhorst** [comment]
Try to disable persistence in the broker ....
Seems to be a persistence problem.

**Comment by sebastianlorenzen** [comment]
I'm using mosquito as broker. Afaik it is off by default. Will double check this.
Any other suggestions?

**Comment by ascillato2** [comment]
Hi,

This issue has been addressed. Please search in the issues list. Closing this issue. Please reopen if needed. Thanks.
