### ISSUE TITLE
Sonoff 4CH pro flashing

### ISSUE THREAD

**Issue by JPSINHA** [arendst/Sonoff-Tasmota#2877]
I am using Sonoff 4CH after sucessful falsh and uploading the current firmware. But now I tried to flash the Sonoff 4CH Pro I am not getting success as I tried to upload it gives message
"Detected non-PlatformIO ‘Monitor_Speed’ option in ‘[env:sonoff]’section"
can any body help me

**Comment by ascillato** [comment]
Seems you delete that entry on platformio.ini. Copy the file again from tasmota.
