### ISSUE TITLE
POW PowerDelta tresholds

### ISSUE THREAD

**Issue by Lu-Fi** [arendst/Sonoff-Tasmota#2880]
Please add or use existing tresholds (eg. PowerHigh / PowerLow) for PowerDelta.
It's currently not really usable if Consumption is normaly ~0-5W.
Every minimal sensor difference will fire an MQTT Message.

**Comment by IVI053** [comment]
I have the same problem. Only percentage for `powerdelta` has the problem that it fires to much on low values and to less on high.
So for high i can set `teleperiod` according to my demands but as the measurements are not too accurate you have noise when nothing draws power and 0 to 1-2W is already 100-200%. While that change is insignificant setting it to 200% to filter this out means at arround 100W already getting a too huge needed change IMHO.

**Comment by IVI053** [comment]
*bump*

**Comment by ascillato** [comment]
Hi,

What about using rules to set exactly the energy report that fit your requirements like:

```
rule 1
rule 4
rule on Energy#Power>5 do publish stat/sonoff/energy %value% endon
```

**Comment by ascillato2** [comment]
Hi,

Please, share your results when you have time. Thanks.

**Comment by IVI053** [comment]
Wouldn't it flood mqtt with every change above 5 with this rule?

**Comment by ascillato** [comment]
Hi, no because the rule is one-shot
