### ISSUE TITLE
conflict when connecting 2 device at the same time.

### ISSUE THREAD

**Issue by phutruong1801** [arendst/Sonoff-Tasmota#2889]
Hi everyone!

i have the issue . it's make me extremely headache. can't find out reason

i'm using the hassio, which's running on raspberry pi. everything working perfectly with my DIY mqtt. The thing happen when i decide to use Sonoff T1 US version 2 gang  - 4 devices, flashing its with tastoma. it's running perfect with a single device. i mean. with  just one Sonoff T1. i can control its via physical button( on the panel glass) and of cause via home assistant webpage and app.

But. When i'm running the second Sonoff T1. i can't control it via a physical . Everytime i turn on. it will immediately turn off. And it's happen with both devices. i was try many configurate.yaml diffirent.  however when i control it via webpage of hassio or app home assistant. it's work.

P/s i's flash the tastoma via arduino IDM. and the user_config.h just changing some basic, such like:
-Wifi mode when can't connect to wifi
- time UTC and long/Lo.
Here is my configurate.yalm
light 1:
  - platform: mqtt
    name: "Bath 1"
    command_topic: "cmnd/sonoff2/power1"
    state_topic: "stat/sonoff2/POWER1"
    value_template: "{{value_json.POWER1}}"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
light 2:
  - platform: mqtt
    name: "Bath 2"
    command_topic: "cmnd/sonoff2/power2"
    state_topic: "stat/sonoff2/POWER2"
    value_template: "{{value_json.POWER2}}"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
    
light 3:
  - platform: mqtt
    name: "Work Light 1"
    command_topic: "cmnd/sonoff_work/power1"
    state_topic: "stat/sonoff_work/POWER1"
    value_template: "{{value_json.POWER1}}"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true
    
light 4:
  - platform: mqtt
    name: "Work Light 2"
    command_topic: "cmnd/sonoff_work/power2"
    state_topic: "stat/sonoff_work/POWER2"
    value_template: "{{value_json.POWER2}}"
    payload_on: "ON"
    payload_off: "OFF"
    qos: 1
    retain: true

**Comment by sleezy100** [comment]
I use 2 x sonoff t1's    1x 3 way and 1 x 2 way all working fine. My yaml file is the same as yours except i do not use the line    value_template:  in any of coding.

**Comment by curzon01** [comment]
@sleezy100 - retain message can result in different situations even you have the same config.

Retain unfortunately reflects not 'it is' state, it reflects some state which could not be the same as the reality. That's why retain is not a good idea except you know what you want and need

**Comment by phutruong1801** [comment]
Basicly.  when i'm just connect ONE sonoff T1 US ( version US- which was released on 2018). Just one.--- it's   work perfectly. toggle the statement on web interface( home assistant) and physical . but when connect from the second devices. it's can't receive the statement. and can't be control via physical.
Look like the problems is return flag. i was try to disable return flag in both configurate.yalm and the sonoff. but still the same. however when i try to use the node-red to control. it's absolutely perfect. 
so the final choise is control via node-red and node-red control sonoff. 
If anyone have solution for my issues. please share.

**Comment by curzon01** [comment]
Try to find out what's happened on mqtt broker on different situations by observing the topic '#' wuth a program of your choice.

**Comment by phutruong1801** [comment]
For Future, Who have the issue like me. it's conflicted because i don't declare the Client_ID or use the same Client_ID for all tasmato devices. just use One different Client_ID for next devices.

**Comment by ascillato** [comment]
Hi

If your issue is solved, please close it. Thanks
