### ISSUE TITLE
Time and timezones

### ISSUE THREAD

**Issue by tam481** [arendst/Sonoff-Tasmota#289]
Hello,
The clocks changed this morning in the UK and I updated to version 4.1.0 then reset the configs and now the time is showing as "{"Time":"1970-01-01T00:00:32", "Uptime":0, "Vcc":3.179, "POWER":"OFF","

I did a reset 2 as well as timezone 99 and just timezone which shows that it's 99 as expected.

How can I fix this?

**Comment by ionciubotaru** [comment]
I get this only when NTP servers are not available

**Comment by tam481** [comment]
Thank you.
Changed my NPT server and TIME_DST and TIME_STD fixed the issue.

Thanks a lot
