### ISSUE TITLE
Sonoff TH16 Switch and Si7021 Sensor Specific Articles for Flashing Tasmota

### ISSUE THREAD

**Issue by mxplea10** [arendst/Sonoff-Tasmota#2894]
The Sonoff TH16 switch is listed as a support device; however, I haven't been able to find the specific article for this switch.  I ordered the switch and sensor last night and would like to locate the documentation for flashing the Sonoff TH16 with Tasmota.  Also, I haven't been able to locate specific documentation for the Sonoff TH Sensor Si7021.  Can someone provide a link, or links, to the specific articles for the Sonoff TH16 Switch and Sensor Si7021 or tell me if it's similar to flashing any of the other Sonoff products?

**Comment by Frogmore42** [comment]
It is pretty much the same as the others.  See here for the serial lines:
https://github.com/arendst/Sonoff-Tasmota/wiki/GPIO-Locations

You need to get the serial lines in the right way, you can tell by cycling power on the TH1X (do not plug it in to line voltage, you need to provide 3V3 on the VCC line).  Note that many USB to serial converters can't provide enough power for flashing reliably.

Once you have it flashed you have to select the module type, let it restart and the select the pins to match the type of sensor you have.  All modules are similar, but sometimes use different gpio pins.

**Comment by mxplea10** [comment]
Thanks
