### ISSUE TITLE
Adjust temperature ?

### ISSUE THREAD

**Issue by fennec622** [arendst/Sonoff-Tasmota#2895]
it's possible to adjust temperature?

I need to subtract 2°C to detected temperature

Thanks a lot

**Comment by reloxx13** [comment]
nope, you should do that with a HomeAutomation Software

**Comment by fennec622** [comment]
thanks

i try but in domoticz you can't adjust temperature from virtual device

**Comment by gizmocuz** [comment]
@fennec622 , Solved in domoticz beta 9564

**Comment by ascillato** [comment]
Hi,

If your issue is solved, please close it. Thanks! :+1:
