### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#2898]
Can someone explain or point me in the right direction about the different types and levels of logging.

My aim is to be able to check the log to see when or if a rule has been executed.

At the moment the log on the console page keeps filling up with Status updates.

**Comment by arendst** [comment]
There are just four levels of logging with increasing message types so just experiment to find the one showing what you want but not too much.

**Comment by ascillato** [comment]
If your issue was solved, please close it. Thanks
