### ISSUE TITLE
slow switch time when pressing the button on Sonoff S20

### ISSUE THREAD

**Issue by redviper2100** [arendst/Sonoff-Tasmota#290]
Hi,

I have a little issue regarding the Sonoff S20 when pushing the button on the plug. It takes around one second for the relay to react after pushing the button. If I switch it by MQTT or the built-in http command the relay switches almost instantly.

How can I solve this?

Thanks!

**Comment by davidelang** [comment]
look at the logs to see exactly what's happening when you hit the switch, set 
the log level to more debugging

then put the logs here.

**Comment by redviper2100** [comment]
Here is the output after pressing the button:

> 16:31:28 APP: Multipress 1
16:31:29 MQTT: domoticz/in = {"idx":14,"nvalue":1,"svalue":""}
16:31:29 MQTT: stat/Switch1/RESULT = {"POWER":"ON"}
16:31:29 MQTT: stat/Switch1/POWER = ON
16:31:29 Config: Saved configuration (1364 bytes) to flash at F8 and count 117
16:31:29 RSLT: Receive topic domoticz/out, data size 236, data {
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Light/Switch",
   "id" : "0001405E",
   "idx" : 14,
   "name" : "Switch1",
   "nvalue" : 1,
   "stype" : "Switch",
   "switchType" : "On/Off",
   "unit" : 1
}

16:31:29 DMTZ: idx 14, nvalue 1

**Comment by redviper2100** [comment]
So is it possible to set a smaller delay? For example to wait only a half of a second to decide? 

If so, where could I change the code?

Thank you.

**Comment by davidelang** [comment]
search for multiwindow in sonoff.ini

**Comment by davidelang** [comment]
I'm going to go ahead and close this, continue to comment or re-open it if you have more questions.

**Comment by bbbenji** [comment]
I have the same issue an found the following

`uint8_t multiwindow[4] = { 0 };       // Max time between button presses to record press count`

Am I understanding correctly that it is already set to 0 wait time? I also find it much easier to update my Sonoff Touches using the prebuilt images therdore I believe there should be no wait time at all as default.

**Comment by davidelang** [comment]
no wait time means that all the multipress functions will not work. That's not 
appropriate for the pre-built images.

**Comment by bbbenji** [comment]
I understand. Perhaps an option in the UI would be a better idea. Though it's my fault I didn't read the documentation and was unaware of the multipress feature.

For future reference I found the current solution for this. In the console input `SetOption13 1`. This will enables the single press only feature.
