### ISSUE TITLE
"

### ISSUE THREAD

**Issue by petonic** [arendst/Sonoff-Tasmota#2908]
**Describe the bug**

Also, make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues and in the wiki
- [x] Hardware used : 
- [x] Provide the output of command ``status 0`` :

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Error?

Closing.

**Comment by petonic** [comment]
Well, there is an error, but I'm trying to determine if it's in my head or in the code :-)  If it's the latter, i'll come back with more details.  Premature.  Thx.
