### ISSUE TITLE
Tasmota - two d1 mini VS reed switch status

### ISSUE THREAD

**Issue by lscosta90br** [arendst/Sonoff-Tasmota#2917]
Hello boys,

My environment looks like this:
Case 1 - D1 mini (tank 1000)
     1 x relay
     2 x Level sensor reed switch - closed circuit (1 - on)
![image](https://user-images.githubusercontent.com/29935375/40999422-30655c16-68e1-11e8-9005-c27540b83049.png)

Case 2 - mini D1 (tank 3000)
     1 x relay
     2 x Level sensor reed switch - closed circuit (0 - off)
![image](https://user-images.githubusercontent.com/29935375/40999322-e8239f8a-68e0-11e8-98c8-b7a6e1fa1599.png)

I made the measurements with the multimeter and the sensors and they are all going on.

Which command checks if there is a different configuration between the firmware?
And how do I record the same setup?

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ ] Hardware used : 
- [ ] Provide the output of command ``status 0`` :

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Frogmore42** [comment]
It is not clear what your question is.
The wiki and other pages have some information about switches and buttons and topics.  Reading those might answer your question.

On the module configuration page, you set what function each GPIO has.  
Sounds like you have two switches and one relay for each device.  But it is not clear what behavior you want.  Depending on that, you might need NodeRED or some Home Automation system to implement it.
