### ISSUE TITLE
Yeti now supports Password-Protected sonoff

### ISSUE THREAD

**Issue by luisfpinto** [arendst/Sonoff-Tasmota#2923]
Hello guys,

I wanted to share with you that in the newest version of [Yeti](https://github.com/arendst/Sonoff-Tasmota/wiki/Yeti) for [Android](https://go.onelink.me/app/5c49a21e) & [iOS](https://go.onelink.me/app/20664d48), Yeti now supports password protected devices.

 To introduce the password follow the steps below:

1. After the first scan if you have a sonoff password-protected Yeti won't find it. 
2. In the home screen tap in the + button and select "Configure Brands", look for sonoff and tap "connect"
3. Tap "Advanced Options" and there you can introduce the password manually

**Comment by ascillato** [comment]
Great!

Can you update the wiki with that?

Thanks :+1:

**Comment by luisfpinto** [comment]
Yes for sure! I'll be adding all info right now 😉
