### ISSUE TITLE
Use external button for button1 on sonoff basic

### ISSUE THREAD

**Issue by jptrsn** [arendst/Sonoff-Tasmota#2924]
I'm having quite a bit of difficulty getting an external button to work with my sonoff basic. I managed to break off the factory-installed button tip, so I can no longer use the built-in button. I'm trying to use an external momentary switch to replicate the functionality, but I can't set any of the available pins to Button1. 

Setting the module type to generic doesn't seem to work, it keeps reverting back to sonoff basic. I'm using GPIO3 as the input. If I set the type to Switch1, it toggles the relay (but toggles back on button release), so I know I'm using the correct input. I haven't had any success with rules, can't get anything to happen, even using the example rules defined in the wiki.

**Comment by ascillato** [comment]
Hi,

>  I set the type to Switch1, it toggles the relay (but toggles back on button release), so I know I'm using the correct input

So, a wall switch is not working with that?

**Comment by jptrsn** [comment]
I'm using a momentary push-button switch, not a wall switch. My issue is that the switch1 behaviour would work for a toggle, but not for a momentary. Because the module is set to a sonoff basic, I can't set any pin to Button1, as it's not in the list.

**Comment by ascillato** [comment]
If toggles back on button release, means that it is on switch type.

If you want the pushbutton that the sonoff basic has, to be a wall switch you should configure as generic module and set the correct pins for led, relay and switch.

**Comment by jptrsn** [comment]
My problem is that I'm not able to set it to generic - it always reverts back to a basic.

**Comment by ascillato** [comment]
ah, ok, that is the problem.

if you type `SaveData `on the console what is the output?

**Comment by jptrsn** [comment]
I get this output: 
`21:58:20 CMD: saveData
21:58:20 RSL: stat/sonoff/RESULT = {"SaveData":"ON"}`

I briefly had it working as a generic module, but it seems to have reverted itself back to a basic module. I'm not sure why it doesn't retain the settings for a generic module.

**Comment by ascillato** [comment]
going back to previous config after showing generic? very strange indeed. Do you have any mqtt server sending a `reset 1` command?

If not, may be a solution for that configuration problem to flash again. Do a full flash erase before.

**Comment by jptrsn** [comment]
I don't think my MQTT server could be sending a reset command. I'm seeing a lot of connection issues, where the device's web UI stops responding momentarily, but not when expected (i.e. when its rebooting).

I just flashed it today with the latest. Initially I tried OTA, but that seemed to have wiped my wifi config, and without a button to get it to operate in wifi manager mode, it needed to be reflashed.

I've got it working now as a generic module. I'll keep an eye on it for the next few hours, and if it behaves, I'll close this issue.

**Comment by jptrsn** [comment]
Nope, it just reverted back to stock.

**Comment by jptrsn** [comment]
Has that changed in a recent version? I had this one and currently have another sonoff with the same broken pushbutton running 5.12.0 without any issue.

**Comment by ascillato** [comment]
No, it does not changed. Your other broken pushbutton seems not to be floating, may be the pull up or pull down resistor (I dont recall now) on that GPIO is ok.

The commands had worked?

**Comment by jptrsn** [comment]
The commands did not work. I had it running as a generic module but it's now reverted somehow.

The failure mode for the buttons is that I knocked off the long rod on top. There isn't any damage to the board, so it's unlikely that a floating pin would be the result. The switch body itself came apart, but the soldered connections to the board are still intact, and if I short the pins I can get it to function (that's how I got it into upload mode).

**Comment by ascillato** [comment]
So, can you reflash it with the generic module set?

in the file _user_config.h_ change the _line 51_ from

`#define MODULE                 SONOFF_BASIC`

to 

`#define MODULE                 WEMOS`

**Comment by jptrsn** [comment]
Some interesting things show up in the console if I catch it at the right time.

`"RestartReason":"Fatal exception:3 flag:2 (EXCEPTION) epc1:0x4020e261 epc2:0x00000000 epc3:0x00000000 excvaddr:0x40035908 depc:0x00000000"`

**Comment by jptrsn** [comment]
```
00:00:00 Project sonoff basic_b (Topic sonoff/basic_b, Fallback DVES_86FDC4, GroupTopic sonoffs) Version 6.0.0a-2_3_0
00:00:00 WIF: Connecting to AP1 IoT_LoCaL in mode 11N as sonoff/basic_b-7620...
00:00:05 WIF: Connected
00:00:05 DNS: Initialized
00:00:05 HTP: Web server active on sonoff/basic_b-7620.local with IP address 192.168.2.125
23:14:16 MQT: Attempting connection...
23:14:16 MQT: Connected
23:14:16 MQT: tele/sonoff/basic_b/LWT = Online (retained)
23:14:16 MQT: cmnd/sonoff/basic_b/POWER = 
23:14:16 MQT: tele/sonoff/basic_b/INFO1 = {"Module":"Generic","Version":"6.0.0a","FallbackTopic":"DVES_86FDC4","GroupTopic":"sonoffs"}
23:14:16 MQT: tele/sonoff/basic_b/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoff/basic_b-7620","IPAddress":"192.168.2.125"}
23:14:16 MQT: tele/sonoff/basic_b/INFO3 = {"RestartReason":"Software/System restart"}
23:14:17 MQT: stat/sonoff/basic_b/RESULT = {"POWER":"ON"}
23:14:17 MQT: stat/sonoff/basic_b/POWER = ON
23:14:22 MQT: stat/sonoff/basic_b/RESULT = {"POWER":"OFF"}
23:14:22 MQT: stat/sonoff/basic_b/POWER = OFF
23:14:24 MQT: tele/sonoff/basic_b/STATE = {"Time":"2018-06-06T23:14:24","Uptime":"0T00:00:15","Vcc":3.162,"POWER":"OFF","Wifi":{"AP":1,"SSId":"IoT_LoCaL","RSSI":100,"APMac":"B0:48:7A:FE:1A:FC"}}
23:14:24 MQT: tele/sonoff/basic_b/SENSOR = {"Time":"2018-06-06T23:14:24","DHT11":{"Temperature":22.0,"Humidity":49.0},"TempUnit":"C"}
23:14:25 MQT: stat/sonoff/basic_b/RESULT = {"POWER":"ON"}
23:14:25 MQT: stat/sonoff/basic_b/POWER = ON
23:14:50 MQT: stat/sonoff/basic_b/RESULT = {"POWER":"OFF"}
23:14:50 MQT: stat/sonoff/basic_b/POWER = OFF
23:14:50 MQT: stat/sonoff/basic_b/RESULT = {"POWER":"OFF"}
23:14:50 MQT: stat/sonoff/basic_b/POWER = OFF
23:14:58 MQT: stat/sonoff/basic_b/RESULT = {"Reset":"Reset and Restarting"}
23:14:58 MQT: stat/sonoff/basic_b/RESULT = {"POWER":"ON"}
23:14:58 MQT: stat/sonoff/basic_b/POWER = ON

```

**Comment by ascillato** [comment]
strange

please provide the command `status 0` output

**Comment by ascillato** [comment]
mmmmm, interesting....

please confirm if it is working now

**Comment by jptrsn** [comment]
That appears to have resolved the issue. Does this mean that TX and RX are not compatible with use as GPIO? I tried disabling the serial output with the command `serialLog 0` but the issue persisted.

One other thing I could try is using either TX or RX with my DHT11, and use GPIO14 for the button.

**Comment by ascillato** [comment]
Seems that using TX and RX as gpio makes conflict on esp8266 boot time. May be in the esp8266 datasheet is explained how to connect them to use as gpio. May be is not as direct as the rest.

Happy to know that your issue is solved. Please close it. Thanks.
