### ISSUE TITLE
stale bot spam

### ISSUE THREAD

**Issue by davidelang** [arendst/Sonoff-Tasmota#2925]
**Describe the bug**

the stale bot seems to be repeatedly sending notices on the same issues, saying that it is closing issues, but not actually closing them

Please either turn of the stale bot or make it actually do what it's claiming to do rather than repeatedly spamming waters with the same messages

**Comment by ascillato** [comment]
Hi David

Yes, was my mistake yesterday with a unintended merge. Sorry. It is Fixed now. You can close the issue if you see that it is ok now.

Thanks

**Comment by davidelang** [comment]
it hasn't been a consistant issue, things seem fine for a few weeks and then I 
get hundreds of stale bot messages in a day.

If you (or someone else more active in the project than I currently am) are 
watching the repo and don't have these auto-forwarded to a folder (so that you 
will _know_ if it runs out of control), go ahead and close this issue.

David Lang
