### ISSUE TITLE
report of instant power and intensity back to zero when pzem004 is offline 

### ISSUE THREAD

**Issue by biotecov** [arendst/Sonoff-Tasmota#2932]
Sorry if my request is not pertinent or inconsistent with other requirements out of my knowledge.

I've attached a pzem004 to a d1-mini with latest tasmota, and it works great. However, if the pzem004 is shut down, tasmota will continue reporting the latest instant intensity and power readings forever, instead of zero. I intend to power pzem004 from the same line as the device it monitors, so when the device's power is cut, pzem's power is cut as well, but tasmota will continue showing the same (fake) intensity.

Would it be possible that when pzem stops responding, reported instant values drop to zero? Or being able to configure somehow if the latest readings should be repeated forever or not? Of course, total energy should be kept unmodified in any case.

Thanks for this excelent software.

**Comment by adityama** [comment]
I see this addressed in latest release (Dev) of Tasmota. Tasnmota will reset all values to zero if do not receive anything from PZEM for over 4 seconds
