### ISSUE TITLE
S31 SONOFF

### ISSUE THREAD

**Issue by tcpipchip** [arendst/Sonoff-Tasmota#2933]
Sir,

Where do i define in the ARDUINO SONOFF SOURCE to use S31 sonoff ?

Today is working very nice with POWER ON and OFF

Thank you!

**Comment by ascillato** [comment]
Hi,

Please, on the webmenu go to **configuration** then **module configuration** and select your **module** there.

If what you want is to define the module **before compiling and flashing**, in the _user_config.h_ file change the line 51:

from

`#define MODULE                 SONOFF_BASIC`

to

`#define MODULE                 SONOFF_S31`

If this solves your question, please close this issue. Thanks :+1:

**Comment by tcpipchip** [comment]
Sir ascillato, thank you again for you fast answer!

I will test soon!!!!

Thanks

Miguel

**Comment by tcpipchip** [comment]
Solved! Excelent! Thanks!
