### ISSUE TITLE
cannot flash basic (soldered pins) 

### ISSUE THREAD

**Issue by loudmicro** [arendst/Sonoff-Tasmota#2936]
hello, I received a couple of sonoffs and they came with soldered pins (http://imgur.com/gallery/pQAbSWa), I unsoldered them but there is no way to flash them, tried with arduino Ide and the espflasher but it's like the pc can't see them. they do work (led flashes when turned on regularly and they also enter flash mode) I've seen similar issues but still no fix (they come with 1.6 so sonota is not working either)

**Comment by ascillato** [comment]
Hi

This is a duplicate issue. Please see #2700

Please close this one. Thanks.
