### ISSUE TITLE
Sonoff Ifan02 Support

### ISSUE THREAD

**Issue by thundergreen** [arendst/Sonoff-Tasmota#2943]
**Have you look for this feature in other issues and in the wiki?**
yes
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I'd like having Ifan working with Home-Assistant
**Describe the solution you'd like**
add support for Ifan02
**Describe alternatives you've considered**
-
**Additional context**
here the link to the device:

https://www.itead.cc/sonoff-ifan02-wifi-smart-ceiling-fan-with-light.html

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
duplicate issue

please see #2839

thanks
