### ISSUE TITLE
Sonoff POW, overcurrent?

### ISSUE THREAD

**Issue by tomasroud** [arendst/Sonoff-Tasmota#2944]
Hi,

POW is working on USB correctly (Wifi, MQTT. all OK), but is dead when connected to a line.
I use POW to connect a boiler with 8A current max for ca one year.
A fuse on POW is interrupted, so there had to be more as 15A current, but the boiler has max 8A.
A circuit breaker in wall has max 16A and is still on.

I think short circuit had to be in POW only.
I am scary to change POW fuse :(

Have you ever seen this?
What can I do to avoid this situation?
![2018-06-08 21 46 08](https://user-images.githubusercontent.com/9718240/41179136-ea1e31ac-6b69-11e8-9cc1-6ba000c8bfdc.jpg)

**Comment by Frogmore42** [comment]
That certainly looks no longer safe.  I would get a new one.  I would also double check that the load doesn't sometimes exceed 8A.  Also, is the load on for long periods, like hours?  That might be part of the problem.

Have you been keeping records of the load and can you see the peaks?

**Comment by Jason2866** [comment]
One part of the board looks to me as had it contact with water (corrosion).....
Could this be?

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.

**Comment by tomasroud** [comment]
The second one lasts 2 months. As you can see, the problem must be in the hardware. The same place is brown :( So, daily turn on and off lasts 2 months :( The harware of POW is not suitable to measure and switching a boiler with 8A current.
![2018-07-31 22 24 45](https://user-images.githubusercontent.com/9718240/43485368-52d8b444-9511-11e8-80a7-90ee41c6ebc9.jpg)
![2018-07-31 22 23 56](https://user-images.githubusercontent.com/9718240/43485374-57332592-9511-11e8-9da6-6131b1c69013.jpg)

**Comment by Jason2866** [comment]
If i where you i would switch with the POW a power relay which has contacts that can drive easily 16A or more...

**Comment by tomasroud** [comment]
Ohhh man, that is the point of it!!!! Thank you very much. The consuption is stable, so I can calculate the time. Bye bye POW. Tomorrow I will do that with basic only. You are smarter as fox is. Thank you again. Problem solved. BTW still the POW is not recomended to switch 8A current daily.

**Comment by Frogmore42** [comment]
I thought the picture looked familiar.  There was a recall of the POWs 

> here is a production defect in a small minority of Sonoff TH16 and POW that were produced from Dec 2016 to Jan 2017

comment from March 2017
https://community.openhab.org/t/itead-sonoff-switches-and-sockets-cheap-esp8266-wifi-mqtt-hardware/15024/134

Your picture looks exactly like the one that failed in that thread and for which they did the recall.  Yours sound like they are old enough to be from the batch.
