### ISSUE TITLE
Having trouble giving SSID and erasing firmware

### ISSUE THREAD

**Issue by AalianKhan** [arendst/Sonoff-Tasmota#2945]
I am trying to flash a sonoff dual R2 with tasmota and I successfully flashed it but I am trying to give my SSID and password of my wifi through Termite (a serial communication program) but when I do shows this

> 00:42:27 MQT: Attempting connection...
00:42:28 DNS: Query done. MQTT services found 0
00:42:28 MQT: Connect failed to :1883, rc -2. Retry in 10 sec
ssid1 5920 Talisman
00:42:32 CMD: ssid1 5920 Talisman
00:42:32 RSL: stat/sonoff/RESULT = {"SSId1":"5920 Talisman"}
00:42:34 APP: Restarting
ets Jan  8 2013,rst cause:1, boot mode:(1,7)
ets Jan  8 2013,rst cause:4, boot mode:(1,7)
wdt reset

to me it looks like the `wdt reset` messes up everything 

Then I tried to erase the firmware first by esp tool so I downloaded python and runned 

`pip install esptool`

And then I put my sonoff to programming mode and connect it and started to erase the firmware but when I typed the erase firmware command it said failed to process.

> Microsoft Windows [Version 10.0.16299.461]
(c) 2017 Microsoft Corporation. All rights reserved.
C:\Users\Aalian khan\AppData\Local\Programs\Python\Python36-32\Scripts>esptool.py --port COM8 erase_flash
failed to create process.
C:\Users\Aalian khan\AppData\Local\Programs\Python\Python36-32\Scripts>_

and now when I try to just open espeasy to flash it automatically says `Failed to flash`
https://drive.google.com/open?id=1wk6Eol1uQmQZzQiJuKc7HhczL1khMmyn 
Please help

**Comment by Jason2866** [comment]
Are you sure that you are in flash mode?

**Comment by Jason2866** [comment]
Plz post the status messages of your erasing / flashing attempts

**Comment by AalianKhan** [comment]
yes I put a female jumper wire at `BUTTON 0` and `GND` on my sonoff dual R2 and I also added the scripts you wanted

**Comment by AalianKhan** [comment]
I redownloaded esp easy and
