### ISSUE TITLE
Update Tasmota 5.12.0j OTA not working

### ISSUE THREAD

**Issue by AlexanderSch90** [arendst/Sonoff-Tasmota#2948]
Hey i can not Upgrade to a other Firmware include minimal because my free Programm Space is to low. 
Is there a way to flash OTA?

Flash Size | 1024kB
Program Flash Size | 1024kB
Program Size | 541kB
Free Program Space | 396kB
Free Memory | 21kB

Thanks!

**Comment by AlexanderSch90** [comment]
Mh ok it is a Lingan SWA1. Have i make a mistake by serial flashing or is with this hardware no ota upgrade available?

**Comment by Jason2866** [comment]
with this low memory no OTA upgrade is possible.

**Comment by Frogmore42** [comment]
How did you flash it the first time?  It looks like was done with a different profile than normal.   At this point, you will have to use serial flash.

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.
