### ISSUE TITLE
Onewire device, MAX31850K thermocouple amplifier

### ISSUE THREAD

**Issue by Beef-well** [arendst/Sonoff-Tasmota#295]
The MAX31850K is a one wire device that responds to the same commands as a DS18b20. The only difference I know of is the family number starts with 3B. I've tried adding a 3B entry to line 66 and line 174 of xsns_ds18x20.ino. In the previous program I used with this device that was all that needed to be done and it worked. Is there another place that the family number needs to be added?

**Comment by Beef-well** [comment]
Ha Ha, NM it works. Just had to add the family number in 3 locations and it picks right up.

 Line 165 of xsns_ds18x20.ino under "Presentation" Added
`
case 0x3B:
      strcpy_P(dsbstype, PSTR("MAX31850K"));
      break;
`
Line 64 CRC check
`
(ds18x20_addr[num_sensors][0]==0x3B
`
Line 155
`
case 0x3B:  // MAX31850K
        t = ((data[1] << 8) + data[0]) * 0.0625;
        if(S) t = ds18x20_convertCtoF(t);
        break;
`

**Comment by Beef-well** [comment]
Ok so technically it works, but I end up with this on the WebUI.
![capture](https://cloud.githubusercontent.com/assets/8888845/24359991/f36edca6-12d3-11e7-90e5-e23e4bcab94f.PNG)

**Comment by davidelang** [comment]
that would seem to indicate that it's responding to multiple ids on the one-wire bus.

**Comment by Beef-well** [comment]
Well I found that it works normally if Line 165 is left as 
`
case 0x3B: strcpy_P(dsbstype, PSTR("DS18B20")); break;
`
I tried to customize the device type by using
`
case 0x3B: strcpy_P(dsbstype, PSTR("MAX31850K")); break;
`
that seems to put into a loop and adds max number of sensors even though there are only 2.

**Comment by davidelang** [comment]
it shouldn't use the same device type, should it?

**Comment by Beef-well** [comment]
No, but it works. It just sees another DS18B20 with a different family number.

**Comment by arendst** [comment]
Implemented in next release. Please test.

**Comment by Beef-well** [comment]
Works beautifully. You are sir are a wizard. Thank you so much.
