### ISSUE TITLE
Wemo emulation seems to support only 1 device/relay (ver 4.0.7)

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#296]
Only the first "Friendly name" seems to be published to WEMO. Is hard coded in xdrv_wemohue.ini line 356 ff.
---
  setup_xml.replace("{x1}", sysCfg.friendlyname[0]);
----
For more than one relay this should loop over the friendly names defined and publish all switches.

**Comment by stefanbode** [comment]
For sure two many dependencies to replace this by https://bitbucket.org/xoseperez/fauxmoesp.
But maybe it helps to find out how to get more than one device connected.

**Comment by altelch** [comment]
Hi,

Wemo Emulation is supposed for one relay devices only. If you need more, 
please use the HUE Emulation.

Greetings,

      Heiko.


Am 27.03.2017 um 16:23 schrieb stefanbode:

**Comment by stefanbode** [comment]
Thanks for the reply. The Wemo is just convenient because you need no external HUB running. AFAIK this is required for HUE. I used the emulation from OpenHAB. Works, but again another component to rely on to work. You can close as enhancement request

**Comment by altelch** [comment]
Hi,

no, the HUE Emulation emulates the HUB and presents all devices as HUE 
devices behind the HUB. Works with Echo even with brightness controll if 
you connect a LED strip instead of a normal light.

Greetings,


     Heiko.

Am 27.03.2017 um 19:50 schrieb stefanbode:

**Comment by stefanbode** [comment]
you can close. the HUE stuff is working excellent. Also with Alexa. No need to use WeMo.

**Comment by uros76** [comment]
Hi. Reading this it seems like HUE works with Alexa without HUE bridge. How did you do that, which Alexa skill did you use?

**Comment by Magic73** [comment]
The worst thing to use HUE emu, it that every device will be recognized as Light.

then, if you say: "Alexa, turn on/off all the lights" you turn on/off everithing. event the non-light (like a sonoff switch used to control something else).
