### ISSUE TITLE
Switch off after restart

### ISSUE THREAD

**Issue by pablofiscella** [arendst/Sonoff-Tasmota#2965]
Hi my  device when it restarts it shuts down.
PowerRetain Is on
Thanks

**Comment by ascillato** [comment]
Hi, That is insufficient information so as to provide some kind of help. Please provide all the information of the troubleshooting template:

![arrowkk2](https://user-images.githubusercontent.com/35405447/41207117-37474f4a-6ce6-11e8-9380-595cb483a7a6.gif)

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ ] Hardware used : 
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**
