### ISSUE TITLE
not a bug, but calibration on SI1145

### ISSUE THREAD

**Issue by gnkarn** [arendst/Sonoff-Tasmota#2966]
**Describe the bug**

UV index calculation is offset by  0.23 points

tested on node mcu 1.0 , 
```
STATUS 0 OUTPUT HERE
```

**To Reproduce**
using SY1145 , wait until  sun down , and the remaining uv indication is still non zero .

**Expected behavior**
indicate zero , on total darkness when sun is down .
**Screenshots**
![screen shot 2018-06-10 at 19 37 01](https://user-images.githubusercontent.com/3314004/41207077-b2fbde86-6ce5-11e8-8162-9f4d487f3a56.png)

**Additional context**
i will check the IR, and visible tomorrow .
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

Interesting. It should be zero? See this [link](https://www.quora.com/What-happens-to-uv-rays-at-night-when-there-is-no-sun)

**Comment by ascillato** [comment]
Also see this https://www.allaboutcircuits.com/projects/how-to-perform-uv-monitoring-with-the-adafruit-si1145/

**Comment by ascillato** [comment]
Hi, @gnkarn 

Any news about this?

**Comment by gnkarn** [comment]
??  Don’t know what you mean. 
There is a problem with the values reported by the library , it is probably not a big deal as if it. Is only an offset it can be solved on the user side just by compensating with a substraction .

My intention was just a watch out .

I willl also report the visible and ir values, but it has been totally cloudy these days , so no new data so far .

**Comment by ascillato** [comment]
Hi,

I was just asking if the value of 0.23 UV Index by night need to be zero or not. In the first link, they said that by night you will have few UV due to reflection from the atmosphere, so a little UV measurement could be ok ? I'm asking.
The second link shows a display and a UV Index sensor, and it is showing 0.02 Index inside a house.

So, that is my question. 0.23 UV Index by night is not Ok ? I don't know, that's why I'm asking you.

**Comment by ascillato** [comment]
Hi. Any news on this? Or we just close this issue? Thanks.

**Comment by gnkarn** [comment]
You can close it , I’m not able to compare the values against a “calibrated source”, as said in my opinion the values have an offset , that can be removed on the user side , probably is something that could be mentioned on the docs. Thanks
