### ISSUE TITLE
Query the CFG_HOLDER used ?

### ISSUE THREAD

**Issue by mrohner** [arendst/Sonoff-Tasmota#2968]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [X ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ X] Hardware used : many esps
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

I finally understand the CFG_Holder. Now I must admit that I f**d up by using different containers and cannot remember which numbers I used for which device. Any possibility to query the FCA or to lookup the CFG_Holder value used for a particular device? I will use 0x20161209 in the future.

**Comment by ascillato** [comment]
ups, sorry. there is no command or way to know that as far as I know
