### ISSUE TITLE
Sonoff POW R2 doesnt work, after set it to on, it will automatically goes off

### ISSUE THREAD

**Issue by mpuff** [arendst/Sonoff-Tasmota#2970]
Hello,

i have flashed a sonoff pow r2 2017-11-30
when i will turn it on, it gets automatically off.
no led lights when i turn it on, when i push the button, the led is red and blue.
when i push the button, the status doesnt change in the gui, ist always off
i also get status 8 data

thank you

**Comment by ascillato** [comment]
Hi. Could you be so kind of posting the output of the status 0 command on the console? Thanks

**Comment by mpuff** [comment]
It was not working because i had a overloaded network, i have tried the pow on another router, on that it works
