### ISSUE TITLE
Corrupted picture in wiki

### ISSUE THREAD

**Issue by jnt2007** [arendst/Sonoff-Tasmota#2975]
**There is corrupted picture on Sonoff Basic wiki page**

**To Reproduce**
_Just open you wiki page https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Basic_

**Expected behavior**
_All pictures looks good_

**Screenshots**
![image](https://user-images.githubusercontent.com/25607714/41274677-f4ac4e3c-6e26-11e8-8b26-743c7235fb08.png)

**Just repalce corrupted picture:)**

**Comment by ascillato2** [comment]
It is working now. Thanks.

**Comment by jnt2007** [comment]
@ascillato2 Excuse me, but no, it's not working now. I tried in Chome browser on Ubuntu and on my iPhone. Picture still corrupted...

**Comment by ascillato** [comment]
![screenshot_2018-06-12-04-26-51](https://user-images.githubusercontent.com/35405447/41275961-00a629ac-6df9-11e8-9ae3-cd7ad461a3ba.png)

**Comment by jnt2007** [comment]
So strange, because I can't see picture complete in a different browsers and devices (deleting cookies and cache does not effect). Maybe it's a GitHub issue with UPLINK to my location.

Can you reupload picture? It mitght be a key to resolve problem for me...

**Comment by ascillato** [comment]
Wiki Edited.

Please, check again. Thanks

**Comment by jnt2007** [comment]
No changes...(
