### ISSUE TITLE
[Question] Solder an extra LED on Sonoff SV

### ISSUE THREAD

**Issue by BrutalBirdie** [arendst/Sonoff-Tasmota#2976]
Hello guys, I wanna solder an extra LED to the GPIO4, GPIO5 or GPIO14, but so far I had no success.
I want the LED to turn on the same way as the on-board LED.
"Why tho?" you might ask, well the SMD LED is broken and I don't have an a spare SMD LED.
Is there a way to solder and extra LED to the GPIOs?

Thanks for reading and looking forward to a solution :)

**Comment by znanev** [comment]
Hi,

I see no problem soldering an additional LED to some of the free GPIO pins.

Solder LED's anode to +3.3V, solder one end of a 1K resistor to LED's cathode, and the other end of the resistor to your chosen GPIO pin.

Then you'll probably have to configure your module as Generic and set the appropriate GPIO pins functions.

**Comment by BrutalBirdie** [comment]
`configure your module as Generic and set the appropriate GPIO pins functions`
Uhmmm... can you maybe help me with that part ? :rofl:

**Comment by BrutalBirdie** [comment]
Okay figured it out myself, with a bit of reading and studying the schematics.
![screenshot](https://puu.sh/AEtDI/af3a2b6fab.png)

**Comment by znanev** [comment]
@BrutalBirdie Good job! I was about to post you a similar screenshot, but I'm glad that you figured it out yourself :)
