### ISSUE TITLE
Confused about latest available binary

### ISSUE THREAD

**Issue by matrix200** [arendst/Sonoff-Tasmota#2985]
If I understand correctly, several releases have been done since 5.1.4
Yet the OTA and manual check shows that the latest binaries are still 5.1.4
Is there going to be a set of binaries for 6.0 released at some point?

Also I think its wrong, that OTA invoked by using GUI or console, doesn't compare the latest available binary to the currently installed version.
Because of that my device just flashed over the same version which surely isn't healthy for the flash endurance, not to mention caused two power cycles which were totally unnecessary.

**Comment by reloxx13** [comment]
Dev build is at 6.0.0 and not released now.

latest release:: https://github.com/arendst/Sonoff-Tasmota/releases/latest

**Comment by matrix200** [comment]
Thanks, I think I will wait until Theo Arends decides it is stable enough and builds the binaries.
Prefer not to run code that hasn't been fully tested on the main switch connecting all my computers to the mains.
