### ISSUE TITLE
Delay on Power Restore

### ISSUE THREAD

**Issue by rahulgurg** [arendst/Sonoff-Tasmota#2991]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [x] Hardware used : Sonoff Pow
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

If someone could guide me with the best way. After power is restored on a Tasmota how do I put in a 10 minute delay for power on. I want the device to be powered on automatically but with a 10 minute delay.
I have tried pulsetime and other ways but not able to do it, so if anyone could give the exact command which I can put in the console or any delay switch I could make in HomeAssistant etc.

Thanks.

**Comment by ascillato** [comment]
Delay of 10 minutes after sonoff power up:

Type in console:

```
PowerOnState 0
rule 1
rule on system#boot do ruletimer1 600 endon on ruletimer1 power on endon
```

For more information see rules in wiki.

If this solves your issue, please close it. Thanks :+1:

**Comment by rahulgurg** [comment]
I have tried this on two different Sonoff's the rules gets implemented fine and the ruletimer1 also reduces till zero but there is no power on.

I have tried the commands in sequence with a reduced timer but somehow the "power on" command does not function at the end of timer.

**Comment by andrethomas** [comment]
What device are you using? If it has multiple relays then you need to be specific POWER1 or POWER2 etc

In my case power on only triggers the first relay (POWER1)

![image](https://user-images.githubusercontent.com/470015/41407598-2911e84e-6fd0-11e8-8660-ad8db15a7fb6.png)

Needless to say I have a dual so there is POWER1 and POWER2 but power on only powers up POWER1

**Comment by rahulgurg** [comment]
Thanks a lot for your help, somehow this is still not working.

I have tried with a Sonoff Pow and a Sonoff TH module and have tried both the ways as Power on and power1 on but these are not working.

The timer is working fine reducing till 0 but the commands are not executing have also tried by doing "do power on" but still no use.

Any other ideas?

**Comment by rahulgurg** [comment]
I tried with a Sonoff Dual and it worked dont know why its not working with a Sonoff Power and Sonoff TH

**Comment by andrethomas** [comment]
Does it work if you manually enter the commands in the console like I did?

**Comment by rahulgurg** [comment]
I have tried again with the following cmd "rule on system#boot do ruletimer1 20 endon on ruletimer1 power on endon"    The following is the output after restart (poweronstate is 0):

00:00:00 Project sonoff Sonoff6-AC-1 (Topic sonoff6, Fallback DVES_0DC54E, GroupTopic sonoffs) Version 5.14.0-2_3_0
00:00:00 WIF: Connecting to AP1 ASUS-2.4 in mode 11N as sonoff6-1358...
00:00:04 WIF: Connected
00:00:04 DNS: Initialized
00:00:04 HTP: Web server active on sonoff6-1358.local with IP address 192.168.2.19
00:00:05 MQT: Attempting connection...
00:00:06 MQT: Connected
00:00:06 MQT: tele/sonoff6/LWT = Online (retained)
00:00:06 MQT: cmnd/sonoff6/POWER = 
00:00:06 MQT: tele/sonoff6/INFO1 = {"Module":"Sonoff TH","Version":"5.14.0","FallbackTopic":"DVES_0DC54E","GroupTopic":"sonoffs"}
00:00:06 MQT: tele/sonoff6/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoff6-1358","IPAddress":"192.168.2.19"}
00:00:06 MQT: tele/sonoff6/INFO3 = {"RestartReason":"Software/System restart"}
00:00:06 RUL: SYSTEM#BOOT performs "ruletimer1 20"
00:00:06 MQT: stat/sonoff6/RESULT = {"RuleTimer1":20}
22:35:23 MQT: stat/sonoff6/RESULT = {"POWER":"OFF"}
22:35:23 MQT: stat/sonoff6/POWER = OFF
22:35:30 MQT: tele/sonoff6/STATE = {"Time":"2018-06-14T22:35:30","Uptime":"0T00:00:14","Vcc":3.170,"POWER":"OFF","Wifi":{"AP":1,"SSId":"ASUS-2.4","RSSI":60,"APMac":"10:BF:48:D8:85:E8"}}
22:35:30 MQT: tele/sonoff6/SENSOR = {"Time":"2018-06-14T22:35:30","AM2301":{"Temperature":37.0,"Humidity":27.5},"TempUnit":"C"}
22:35:33 CMD: ruletimer1
22:35:33 MQT: stat/sonoff6/RESULT = {"RuleTimer1":8}
22:35:45 MQT: tele/sonoff6/STATE = {"Time":"2018-06-14T22:35:45","Uptime":"0T00:00:29","Vcc":3.170,"POWER":"OFF","Wifi":{"AP":1,"SSId":"ASUS-2.4","RSSI":58,"APMac":"10:BF:48:D8:85:E8"}}
22:35:45 MQT: tele/sonoff6/SENSOR = {"Time":"2018-06-14T22:35:45","AM2301":{"Temperature":37.0,"Humidity":27.5},"TempUnit":"C"}
22:36:01 MQT: tele/sonoff6/STATE = {"Time":"2018-06-14T22:36:00","Uptime":"0T00:00:44","Vcc":3.170,"POWER":"OFF","Wifi":{"AP":1,"SSId":"ASUS-2.4","RSSI":56,"APMac":"10:BF:48:D8:85:E8"}}
22:36:01 MQT: tele/sonoff6/SENSOR = {"Time":"2018-06-14T22:36:01","AM2301":{"Temperature":37.0,"Humidity":27.4},"TempUnit":"C"}

**Comment by ascillato** [comment]
Hi

Sorry. The rule was wrong. For rule syntax see wiki.

It is `Rules#Timer=1` instead of `ruletimer1`.

So complete should be:

Delay of 10 minutes after sonoff power up:

Type in console:

```
PowerOnState 0
rule 1
rule on system#boot do ruletimer1 600 endon on Rules#Timer=1 power on endon
```

**Comment by rahulgurg** [comment]
Yes the following works perfectly fine.

rule on system#boot do ruletimer1 600 endon on rules#timer=1 do power on endon

** Thanks a lot for all your help.**

**Comment by marcobaessapinto** [comment]
I have been trying to set this up on a sonoff 4ch, but so far Above commands on console would only affect relay number 1. How to enable for relays 2, 3 and 4?

**Comment by andrethomas** [comment]
```
rule on system#boot do ruletimer1 600 endon on Rules#Timer=1 do backlog power1 on;power2 on;power3 on;power4 on endon
```

> Additionally is it possible to implement this delay on power restore and revert to previous state before power cut? Like, if the relay was off, after the set delay timer would stay off, and if it was on would stay on?

Probably some fancy footwork with complex rules would make this happen if you're really persistent.
