### ISSUE TITLE
Alexa support for Tasmota with Yeti

### ISSUE THREAD

**Issue by luisfpinto** [arendst/Sonoff-Tasmota#2993]
Hello,

As you probably know, [Yeti ](https://getyeti.co) is now compatible with Tasmota devices. [Wiki Tasmota Yeti](https://github.com/arendst/Sonoff-Tasmota/wiki/Yeti)

Soon we'll implement Alexa support for Yeti so this means that users will be able to control their tasmota devices with Alexa.

Right now we're opening a beta test program so people who want to have early access and try Alexa and provide some feedback can [sign up here](https://goo.gl/forms/EAPo3g3fi0vFouR02)

Thank you so much!

**Comment by ascillato** [comment]
Great!
