### ISSUE TITLE
Sonoff manager alternative:

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#3005]
Hello,
I have like 1-5 sonoff in a house without HomeAssistant or a manager.
I looking got a manager the simplest way to share it over the internet so I can use all of them without being home and without install HA or else.
thanks!

**Comment by Lawrencezarb** [comment]
What about SonWeb or Tasmoadmin, as it is know now?

Its what I use.

**Comment by shayshtern** [comment]
Can I share it and set a user password to it?

**Comment by Lawrencezarb** [comment]
yes.
https://github.com/reloxx13/TasmoAdmin

**Comment by ascillato** [comment]
Hi,

If this solves your issue, please close it. Thanks. :+1:
