### ISSUE TITLE
Sonoff RF bridge wifi

### ISSUE THREAD

**Issue by clementchik0308** [arendst/Sonoff-Tasmota#3013]
Found RF bridge wifi led always off.
Any chance to control the wifi led on when wifi connected in tasmota?

**Comment by ascillato** [comment]
Hi,

You can control the status of the led with `ledpower `and `ledstate `commands. Please see wiki for more details: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

If you can not control your led behaviour with those commands, your device might be defective. My sonoff bridge uses its wifi led by default.

If this solves your issue, please close it. Thanks :+1:
