### ISSUE TITLE
RF Bridge Limitation to 24bit Codes

### ISSUE THREAD

**Issue by haegar33** [arendst/Sonoff-Tasmota#3014]
I understand that my Sonoff RF Bridge with Tasmota 5.14.0 is not able to decode RF Codes other than 24bit length? I got a very old set of RF power plugs (Company REV) which works fine. I got just now a Brennenstuhl Comfort Line power plug set where I cannot learn any rfkey. Actually in the console I see different codes every time I press the same key on the remote control.
Questions:
- is there a list of compatible RF power plug sets which works with Tasmota?
- can I solve this issue with an update to V6.0 and the additional new efm8bb1 firmware?

**Comment by Jason2866** [comment]
With Tasmota and original efm8bb1 software the supported rf power plugs are the same as with ITEAD firmware.
Just try the efm8bb1 portisch firmware. For me it works better for the code 2262.
The actual build supports not really more codes than the original but has options for doing that.
Not an ready solution out of the box

**Comment by haegar33** [comment]
well now I have a chicken and egg problem as my bridge has now Tasmota and no longer the original ITEAD firmware, so no testing which power plugs are compatible. Actually it would be nice if the Wiki would contain such a list based on the experience of users. Brennenstuhl plugs do not work.

**Comment by wongnam** [comment]
In my experience, i will backup the the factory original FW before i flash it with 3rd party FW.

**Comment by Jason2866** [comment]
@haegar33 
TASMOTA doesnt change anything in compability which devices are supported!
Brennenstuhl may work if you use the EFM Firmware from Portisch (now included in development Tasmota). You have to flash this firmware in a extra step!

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.

**Comment by sroettgermann** [comment]
I'm currently trying to run the brennestuhl device in combination with the RF bridge and the Portisch firmware. But it gave me no results. I'm not able to receive any code. :(

**Comment by wongnam** [comment]
Please note that it only support RF 433Mhz not 315Mhz.

**Comment by Jason2866** [comment]
@sroettgermann  look at https://github.com/Portisch/RF-Bridge-EFM8BB1 and try it with
Bucket sniffing using command 0xB1
