### ISSUE TITLE
Support hostname in topic/fulltopic/client name

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#3018]
Tasmota supports saving and restoring the configuration which allows easy provisioning of multiple devices by just copying the configuration. Currently topic and client name have to be adjusted manually per device.

I suggest to support a hostname variable like `%hostname%` in the client name and (full-)topic fields.

**Comment by renne** [comment]
Push

**Comment by ascillato** [comment]
Just for reference: #3786

**Comment by ascillato2** [comment]
Closing as the request has been added.

Thanks
