### ISSUE TITLE
Belkin Wemo emulation

### ISSUE THREAD

**Issue by tarasfrompir** [arendst/Sonoff-Tasmota#3020]
Please create a temperature sensor for Belkin Wemo emulation, and also create additional devices present in SONOOFF devices

**Comment by Frogmore42** [comment]
Why?
What do you expect to do with it?
In the quick search that I did, Wemo doesn't have any temperature sensors, so it is currently impossible to do what you want in wemo mode.

But, if your goal is to automate something based on temperature with Sonoff devices, that is easy with Tasmota.  You will need to setup a mqtt broker and some type of home automation.  There are lots of choices for that.

**Comment by tarasfrompir** [comment]
Sorry, i dont like mqtt. I like UPNP protocol.

**Comment by Frogmore42** [comment]
Not sure what you have against MQTT, nor why you are a fan of UPNP.  But, I could find no evidence that Wemo has any temperature sensor support.  So you'll probably be waiting a long time for Tasmota to support something that doesn't exist, especially when there is that type of functionality already supported with MQTT.

**Comment by ascillato** [comment]
Hi

The actual Wemo Support is only for Lights. Sorry.
