### ISSUE TITLE
Sonoff restarts itself and doesn't connect to WiFi

### ISSUE THREAD

**Issue by sagilo** [arendst/Sonoff-Tasmota#3024]
When used with serial connection it works perfectly.
As i disconnect the serial and connect it to the power cables, the led blinks, sometimes gets solid and then restarts itself.
I can't access its webserver and the MQTT doesn't respond as well.

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://forum.digital-pig.com/)
- [x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [x] Hardware used : Sonoff basic. Flashed using Atom/platformIO on macOS Sierra.
- [x] output of command ``status 0`` :
```
17:49:03 CMD: status 0
17:49:03 SRC: WebConsole from 192.168.1.143
17:49:03 RSL: Received Topic /status, Data Size 1, Data 0
17:49:03 RSL: Group 0, Index 1, Command STATUS, Data 0
17:49:03 MQT: stat/sonoff-001/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff-001"],"Topic":"sonoff-001","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":1}}
17:49:03 MQT: stat/sonoff-001/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Hardware Watchdog","Uptime":"0T00:00:32","StartupUTC":"2018-06-20T16:48:31","Sleep":0,"BootCount":82,"SaveCount":152,"SaveAddress":"F8000"}}
17:49:03 MQT: stat/sonoff-001/STATUS2 = {"StatusFWR":{"Version":"6.0.0a","BuildDateTime":"2018-06-19T23:27:35","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
17:49:03 MQT: stat/sonoff-001/STATUS3 = {"StatusLOG":{"SerialLog":4,"WebLog":4,"SysLog":4,"LogHost":"192.168.1.143","LogPort":514,"SSId":["lhome_2_4","lhome_5"],"TelePeriod":300,"SetOption":["00008029","55818000"]}}
17:49:03 MQT: stat/sonoff-001/STATUS4 = {"StatusMEM":{"ProgramSize":536,"Free":464,"Heap":17,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","0C000000","17B6179A","00000000"]}}
17:49:03 MQT: stat/sonoff-001/STATUS5 = {"StatusNET":{"Hostname":"sonoff-001-2446","IPAddress":"192.168.1.6","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"5C:CF:7F:71:C9:8E","Webserver":2,"WifiConfig":3}}
17:49:03 MQT: stat/sonoff-001/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.130","MqttPort":1883,"MqttClientMask":"home-assistant-1","MqttClient":"xxx","MqttUser":"xxx","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
17:49:03 MQT: stat/sonoff-001/STATUS7 = {"StatusTIM":{"UTC":"Wed Jun 20 16:49:03 2018","Local":"Wed Jun 20 17:49:03 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"04:46","Sunset":"20:57"}}
17:49:03 MQT: stat/sonoff-001/STATUS10 = {"StatusSNS":{"Time":"2018-06-20T17:49:03"}}
17:49:03 MQT: stat/sonoff-001/STATUS11 = {"StatusSTS":{"Time":"2018-06-20T17:49:03","Uptime":"0T00:00:32","Vcc":2.922,"POWER":"ON","Wifi":{"AP":1,"SSId":"ssid","RSSI":100,"APMac":"A0:04:60:CB:35:C0"}}}
```

Thank you

**Comment by Frogmore42** [comment]
It is standard to fill out the template.  Not doing so means someone has to take the time to ask you to provide all the information in the template.  There are many reasons why things can not work.  Having all the information details about what you are using and what you have tried means we don't have to waste time.

There can be hardware (your device is defective), software compilation, and configuration issues that could cause the problem.

**Comment by sagilo** [comment]
Hi @Frogmore42 
I've followed the template.
I've searched all the relevant places, mentioned the used HW, but I can't provide the `status 0` command output since the device won't start/connect.
I **highly appreciate** the effort every person puts in assisting the other, and I do my best to provide all the necessary information up front.

That said, Ill be happy if you could please point me to what is missing in the post so it will be more clear.

Thank you

**Comment by Frogmore42** [comment]
You erased all of the template, so no one else knows what you did.

Provide 0 when it is connected to serial where you said it worked.  That will indicate all the details of excatly what you are running.  There are a few ways you could have done it and some of them cause issues for some devices some times.

You may have a broken device.  If you only have one, it is hard to know.

You may have misconfigured something, if you only have one device and have never configured something before it is easy to make a mistake.

Also provide the log showing it working on serial.  This usually indicates most things are configured well.

There have been a few cases of people having devices that didn't work when plugged in that were hardware related.

**Comment by reloxx13** [comment]
> Make sure these boxes are checked [x] before submitting your issue - Thank you!
> 
> - [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
> - [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
> - [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
> - [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
> - [ ] Hardware used : 
> - [ ] Provide the output of command ``status 0`` :
> ```
> STATUS 0 OUTPUT HERE
> ```
> 
> **(Please, remember to close the issue when the problem has been addressed)**
>

**Comment by sagilo** [comment]
@Frogmore42 @reloxx13 Thank you for clarifying.
I've updated the thread with (hopefully) all the necessary information.

**Comment by Frogmore42** [comment]
The log has this:
"RestartReason":"Hardware Watchdog"

That is making it look more likely that you have an at least somewhat defective device.  It could be the 5V supply is not stable or it could be something else.  I would suggest getting a different one.  I had one dual that I could never get to work correctly.  If it had been my first Sonoff device, I would have been much more confused than I was.

The log indicated it was connected to MQTT, so assuming you tried it plugged in at the same location, it seems the 5V and 3V3 power supplies are the likely culprits.  Unless you have experience repairing electronic circuits, it is probably time for a new one.

**Comment by sagilo** [comment]
Bummer .. 
I'll try another one.
@Frogmore42  Thanks a lot!
