### ISSUE TITLE
Counter2 in Domoticz

### ISSUE THREAD

**Issue by zuevav** [arendst/Sonoff-Tasmota#3032]
Hi, can you help me? how to see Counter2 in Domoticz, I see special line in firmware for Counter1, but for Counter2 - no.

**Comment by arendst** [comment]
Use rules. See wiki - rules about an example using temperatures send to domoticz

**Comment by zuevav** [comment]
Thank you, I do it!
Console command:
rule on
rule on tele-COUNTER#C2 do %value% do publish domoticz/in {"idx":23,"svalue":"%value%"} endon
