### ISSUE TITLE
MQTT - Status add to ON & OFF the Topic (name of the device)

### ISSUE THREAD

**Issue by kobibeja** [arendst/Sonoff-Tasmota#3033]
Hello
How it's possible to get via MQTT the status of the  Sonoff-Tasmota with the topic (device name)?
For example,
by default the responding is {"POWER":"OFF"} and I'm asking to get {"topic":"POWER":"OFF"}
the Topic is from MQTT parameters page.

Thx
Kobi

**Comment by ascillato** [comment]
Hi

The topic is already in the MQTT message:

/stat/TOPIC/power1 on

Please, review MQTT protocol to understand it better at: https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Overview

Thanks
