### ISSUE TITLE
Daylight Saving Time problem

### ISSUE THREAD

**Issue by gemitro** [arendst/Sonoff-Tasmota#304]
Daylight Saving Time doesn't work for both old and new configurations (after Last, Sun, Mar).

**Comment by gthb96** [comment]
Same problem on my end.

**Comment by aferraz** [comment]
Same for me

**Comment by arendst** [comment]
Set timezone to 99 and update user_config.h TIME_DST and TIME_STD for your location

**Comment by gemitro** [comment]
OK thanks.
i updated user_config.h TIME_DST and TIME_STD but I didn't read the comments in line 112 (Timezone)!!

**Comment by gthb96** [comment]
Quick question.
Uptime was counted every hour 2:30 but since I am on 4.1.1 it gets counted every hour 2:00.

Is it because of changing the timezone or got that changed in the code? Just curious...

**Comment by arendst** [comment]
result of #302. It's now around xx:02:00 as you noticed.
