### ISSUE TITLE
Sonoff 4Ch pro R2 RF door contact issue

### ISSUE THREAD

**Issue by robgardien** [arendst/Sonoff-Tasmota#3043]
I am using a sonoff 4CH r2 and I am not able to properly connect a door contact. Of turns on a switch but turns it off after a few seconds. 

Normal operation is working so I was wondering if its possible to change the jumper or software settings for RF

**Comment by Frogmore42** [comment]
Also all the hardware you have added to the Pro.

**Comment by ascillato2** [comment]
Hi,

More information is needed. Please, reopen this issue and share all the information requested in the troubleshooting template. Thanks
