### ISSUE TITLE
Sonoff Touch Tasmota pushbutton

### ISSUE THREAD

**Issue by ziboo06** [arendst/Sonoff-Tasmota#3047]
Hi everybody,

I flashed my sonoff touch with tasmota and i can't set it in the pushbutton mode. 
I configured the module as a sonoff touch module, put GPIO3 as 09 Switch1and used the command swithmode1 3 through the console.

Can someone help me?
Thx :)

**Comment by ascillato** [comment]
Please provide all the information of the troubleshooting template:

> Make sure these boxes are checked [x] before submitting your issue - Thank you!
> 
> - [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
> - [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
> - [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
> - [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
> - [ ] Hardware used : 
> - [ ] Provide the output of command ``status 0`` :
> ```
> STATUS 0 OUTPUT HERE
> ```
> 
> **(Please, remember to close the issue when the problem has been addressed)**
>

**Comment by gsaslis** [comment]
@ziboo06 wondering if you figured this out?
