### ISSUE TITLE
RF bridge transmitter range is too limited 

### ISSUE THREAD

**Issue by ddvkid** [arendst/Sonoff-Tasmota#3054]
Your firmware is awesome! Thanks for your work.
I had successfully flashed my Sonoff rf bridge with Raspberry pi, it works except the transmitter range was too limited, like 20-30 cm only! 
The transmitter works fine with original sonoff firmware.
My rf bridge is v2 and I was using sonoff-allsensors.bin v5.14.0.
Did I miss something?

**Comment by Jason2866** [comment]
Your RF Bridge seems defect. The Bridge has a good transmitter.  
My R2 does easily switch about 10 Meter through walls...

**Comment by ddvkid** [comment]
But it worked all good with the original sonoff firmwork and ewelink app. 😓

**Comment by Jason2866** [comment]
Maybe you destroyed it...
The Rf transmit part is completly independent from the ESP part .
