### ISSUE TITLE
Will a Sonoff Basic (3.3 volts) power a HC-SR501 PIR Motion Sensor?

### ISSUE THREAD

**Issue by sparkgap** [arendst/Sonoff-Tasmota#3059]
Does anybody know........
Will a Sonoff Basic (3.3 volts) power a HC-SR501 PIR Motion Sensor?
Some places it indicates 3.3v is sufficient.
Will the Sonoff regulator overheat?
The Motion Sensor will be connected to GPIO14.

**Comment by Lawrencezarb** [comment]
MMy HC-SR501 is powered by my sonoff, but you need to feed bypass the voltage regulator on the PIR and feed the 3.3v directly to the board. There are several online instrcutions for this. as below

https://randomnerdtutorials.com/modifying-cheap-pir-motion-sensor-to-work-at-3-3v/

**Comment by sparkgap** [comment]
Great.  Thanks

**Comment by pcpaulo** [comment]
i have followed the instruction to bypass the 3.3v, i am using lowest sensibility but my sonnoff still giving false detection.

Any suggestion?
