### ISSUE TITLE
External button

### ISSUE THREAD

**Issue by gemitro** [arendst/Sonoff-Tasmota#306]
Does anyone know to which pins i must solder a cable in order to  toggle the relay of Sonoff TH16 using an external button?

**Comment by davidelang** [comment]
you can use any available gpio and define it as switch1

**Comment by gemitro** [comment]
Should i connect the other cable to ground.

**Comment by davidelang** [comment]
yes, wire the switch from the gpio pin to ground

**Comment by gemitro** [comment]
Thanks

**Comment by spacefolder** [comment]
Hi Guys! Sorry for reopening the thread, but it's a very related question. I have access to GPIO 04 on a TH16 (soldered to the available pad). I can use an external switch without problems, but I can not use it a a push button. (Button 2,3 and 4 don't seem to work) How can I achieve this? Thanks, and cheers!

**Comment by davidelang** [comment]
when you say it doesn't work, what is happening?

what do you expect to happen instead?
