### ISSUE TITLE
sonoff/xsns_26_lm75ad.ino shown as modified even there's not

### ISSUE THREAD

**Issue by curzon01** [arendst/Sonoff-Tasmota#3063]
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://forum.digital-pig.com/)
- [x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ ] Hardware used : 
Not relevant

After fresh clone the repository the file sonoff/xsns_26_lm75ad.ino is always shown as modified even it's still same as on repo.

**Reproduce:**
```
cd ~/tmp
git clone https://github.com/arendst/Sonoff-Tasmota.git
cd Sonoff-Tasmota
git status
On branch development
Your branch is up-to-date with 'origin/development'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   sonoff/xsns_26_lm75ad.ino

no changes added to commit (use "git add" and/or "git commit -a")

```

Reason: All other files using LF as line end, this file might be edited by a Windows user and ends with CR/LF.

Solution: Even change line endings to LF or better - set
`* text=off`
in .gitattributes

**Comment by arendst** [comment]
Just fixed
