### ISSUE TITLE
AIlight model E27 , do not work properly with home assistant

### ISSUE THREAD

**Issue by gnkarn** [arendst/Sonoff-Tasmota#3065]
**Describe the bug**
the mqtt configuration for this light is not clear , as it  white property is not adequately reflected on the docs .
by using the home assistant mqtt light configuration as follows : 
- platform: mqtt
  name: "luz living1"
  optimistic: false
  state_topic: "stat/RGBliving1/POWER"
  command_topic: "cmnd/RGBliving1/POWER"
  state_value_template: "{{ value_json.POWER }}"
  on_command_type: "last"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  brightness_state_topic: "stat/RGBliving1/DIMMER"
  brightness_command_topic: "cmnd/RGBliving1/DIMMER"
  brightness_value_template: '{{ value_json.Dimmer }}'
  brightness_scale: 100
  rgb: true
{"POWER":"ON","Dimmer":3,"Color":"7,7,7,0","HSBColor":"0,0,3","Channel":[3,3,3,0]}  
  rgb_state_topic: "stat/RGBliving1/RESULT"
  rgb_command_topic: "cmnd/RGBliving1/COLOR"
  rgb_command_template: "{{ '%02x%02x%02x00' | format(red, green, blue) }}"
  retain: true
  white_value: true
  white_value_command_topic: "cmnd/RGBliving1/channel4" # formato de 0-100
{"POWER":"ON","Dimmer":100,"Color":"FF0000FF","HSBColor":"0,100,100","Channel":[100,0,0,100]}
  white_value_state_topic: "stat/RGBliving1/RESULT"  
  white_value_scale: 100
  white_value_template: "{{ value_json.Channel[3] }}"
  availability_topic : "tele/RGBliving1/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"

in this case , the power on command works , color works, brightness works, and white command works ,
but in all cases the command   does NOT persists and an OFF command is received to power off the light .

**I dont know what the reason is , but suspect of a problem with the status , and received status NOT matching the send command .**

i also tried the autodiscovery , but the information receivbed from  tasmota is incomplete in this case to properly configure the light . ( only the power , and brightness are configured) .

**Comment by ascillato** [comment]
Please, provide the information requested in the troubleshooting template AND also the output of the console when that behaviour occurs:

> Make sure these boxes are checked [x] before submitting your issue - Thank you!
> 
> - [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
> - [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
> - [ ] Searched the problem in the forum (https://forum.digital-pig.com/)
> - [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
> - [ ] Hardware used : 
> - [ ] Provide the output of command ``status 0`` :
> ```
> STATUS 0 OUTPUT HERE
> ```
> 
> **(Please, remember to close the issue when the problem has been addressed)**
