### ISSUE TITLE
How to cancel setting RF switch in SONOFFT1

### ISSUE THREAD

**Issue by SUGINACH** [arendst/Sonoff-Tasmota#3068]
I Flash MY SONOFF T1
And set a RF switch to turn on the device
Such https://www.aliexpress.com/item/Newest-SONOFF-T433-86-Type-Wall-Panel-433MHz-Wireless-RF-Remote-Control-Transmitter-Support-All-SONOFF/32852333652.html
But I do not know how to undo the setting
I want the device not activated by this switch anymore
I tried to connect the T1 to another RF switch but it did not cancel the previous RF Switch

**Comment by arendst** [comment]
See https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF#procedure

**Comment by SUGINACH** [comment]
waht about sonoff t1?

**Comment by arendst** [comment]
Same procedure. Try it first and come back with your result.

**Comment by SUGINACH** [comment]
I probably do not understand
I have a SONOFF T1 with two channels
One of the channels has been set up for a remote control that I do not want to control this channel
If I press this channel's touch button three times nothing happens it just turns on and off and turns on
I apparently did not understand what I was supposed to press

**Comment by SUGINACH** [comment]
PS
Your firmware is the best thing that happened to me in the context of a smart home
Thanks for everything
Keep up with the good work
I hope it will benefit you at least as it is beneficial to me

**Comment by arendst** [comment]
On the PCA of the T1 is a separate small button to reset both 434MHz remembered signals.

**Comment by SUGINACH** [comment]
In the end, I got along differently
I pressed the touch button until two beeps sounded
Then I pressed the RF I wanted to delete
And the connection between the remote control and the button has been canceled
thanks anyway
And again
Thank you very much for all the investment in this wonderful software And on support

**Comment by ascillato2** [comment]
Great to know that your issue is solved. Closing.
