### ISSUE TITLE
Pre built image missing Wifi credentials

### ISSUE THREAD

**Issue by lggrizendi** [arendst/Sonoff-Tasmota#3074]
Pre built image missing Wifi credentials since release v5.12.0 so it` make impossibilite to connect to esp8266

#define STA_SSID1              "indebuurt1"      // [Ssid1] Wifi SSID
#define STA_PASS1              "VnsqrtnrsddbrN"  // [Password1] Wifi password

**Comment by ascillato** [comment]
Yes, the prebuilt will NOT HAVE your credentials. You have to set those using the AP mode.

Please read the wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Initial-Configuration

**Comment by lggrizendi** [comment]
thanks

**Comment by ascillato** [comment]
Please, if your question is addressed, close this issue. Thanks :+1:
