### ISSUE TITLE
Setting SwitchTopic only for HOLD

### ISSUE THREAD

**Issue by vic10us** [arendst/Sonoff-Tasmota#3077]
When using SwitchMode 5 and 6 it forces ALL relay handling via MQTT. This can be useful, but it can be a problem when you lose wifi.

I good option would be to set a HoldTopic so that it's not necessary to redirect all functions to MQTT.

I would contribute, but my skillset is restricted to C#, Java and JavaScript. :)

**Comment by ascillato2** [comment]
Hi,

It is already implemented. 

If you want to change the switchtopic behaviour you can use rules. Please, see example at the wiki at [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#12-controlling-timers-enable-from-a-switch).

Thanks.
