### ISSUE TITLE
Mark GPIO0 and GND solder-pads on H801 image

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#3082]
The [PCB image of the H801](https://github.com/arendst/Sonoff-Tasmota/wiki/H801) has no solder-pad markings at J3. The solder-pad right next to U2 is GPIO0 and the solder-pad right next to GPIO2 is GND.

**Comment by ascillato** [comment]
Added. Thanks for sharing. :+1: 

Please, close this issue. Thanks :+1:
