### ISSUE TITLE
How can i enable connectivity to app sonoff pow r2 

### ISSUE THREAD

**Issue by albionbeka** [arendst/Sonoff-Tasmota#3091]
I dont know how to enable connectivity to my own app and how can the app scan for sonoff pow r2

**Comment by ascillato** [comment]
Hi,

In the wiki is all the information about REST API, MQTT, and KNX.

You also can use Yeti app for your phone.

Remember that Tasmota is a firmware for sonoff devices that allow connection to MQTT for home automation.

**Comment by ascillato** [comment]
Your question is addressed? You need something else?

If not, please close this issue. Thanks :+1:

**Comment by albionbeka** [comment]
I need to make my own tho i need to make it in albanian language thats why

**Comment by ascillato** [comment]
Ok, I understand. You want to make your own. Perfect. So, what else do you want?

If the only thing is the translation to albanian, talk to @luisfpinto and his team that are developing the phone app called Yeti, that it is very good and well designed app. If you want, you can help them with the translation to albanian.

Also here, Tasmota has several translations but Albanian is missing and also you can help on that if you want.

**Comment by albionbeka** [comment]
And to make some other features

**Comment by ascillato** [comment]
Ok, Cool.

Please, keep us posted. Thanks :+1:
