### ISSUE TITLE
Domoticz Dummy Inputs to trigger local rules

### ISSUE THREAD

**Issue by Biggav87** [arendst/Sonoff-Tasmota#3092]
Hi

I'm trying to add dummy inputs from domaticz to to a 4ch sonoff to trigger rules local to the sonoff.

My situation is that i am trying to change the colour of the pool lights that are connected to the  sonoff module. In order to do this the device requires that it is switched off and on in quick succession and a specific sequence. I have found that the performance of the network doesn't allow this to happen however if i could sent a single command i believe the sonoff module could handle it locally.

Here is the link to the light manual for clarity on what sequence is required.
[https://www.astralpool.com.au/sites/default/files/products/manuals/INST%20379%20SLX-FLX%20QUICK%20START%20GUIDE%202018-05-7_0.pdf](url)

I was thinking if i could have 2 dummy inputs, one to run a rule to enter the colour change mode and the second to step through the colours.

I look forward to your feedback.

**Comment by ascillato** [comment]
You can trigger a rule by mqtt

cmnd\topic\event name

And a rule like

Rule1 1 
Rule1 on event#name do power1 1 endon

See wiki for more examples
