### ISSUE TITLE
volkszaehler.org function

### ISSUE THREAD

**Issue by cyclemat** [arendst/Sonoff-Tasmota#3095]
i have seen the new smart house smartmeter con be read via a TTL Reader can you add a function for this so you didnt have use a complete Raspberry for only on sensor on http://wiki.volkszaehler.org/ you can fin all infomations would be nice

**Comment by gemu2015** [comment]
i implemented this into tasmota several month ago and made a pull request
 
https://github.com/arendst/Sonoff-Tasmota/pull/2377

you can try it from my repo

**Comment by cyclemat** [comment]
oh thanks will try

**Comment by ascillato2** [comment]
Hi,

Your question seems to be addressed. Closing this issue. Please, reopen if you need something else. Thanks :+1:
