### ISSUE TITLE
HC-SR501 PIR motion detector as switch not working as expected

### ISSUE THREAD

**Issue by mihalski** [arendst/Sonoff-Tasmota#31]
Is POWER = OFF the intended result when motion is detected? Or is there some further configuration to the type of switch required to make this work more reliably.

And on another identical device with identical configuration and hardware I am getting mostly "correct" behaviour except that sometimes when it is triggered it wobbles from On to OFF to ON a few times changing every 4/5 seconds.

Perhaps there needs to be 30 seconds or so of "calibration" before the firmware takes any readings from a PIR sensor? That was my impression though I don't know if that just means unpredictable behaviour for the first 30 seconds or whether it sets the tone for future readings.

PS. I think it may have stabilised now.. I Manually toggled the switch to OFF over the web interface while no motion was being detected and so far so good.. Going to continue testing to see if the behaviour remains consistent.

EDIT: SWITCH_MODE needs to be FOLLOW right? I just can't get reliable behaviour.. I switched from TOGGLE to FOLLOW and it was acting weird and ignoring motion.. So I tried FOLLOW_INV and it worked INVERSELY like I described in the first paragraph so I tried going back to FOLLOW and it didn't work at all.. Now a few minutes later it's inverted itself again.. No idea what's going on. Hope to hear from others trying to use this sensor with this firmware.. I have about 15 of these sensors and I set them all the same and switch them around to make sure it's not a faulty sensor.

EDIT2: OK.. Things appear to have stabilised.. Not sure if why or how. We'll see how it continues.

**Comment by Hogesyx** [comment]
Are you powering it with 5V or 3.3V with bypass modification?

**Comment by mihalski** [comment]
I've tried both. No difference. They were mostly stable overnight, but one of them had a tiny bit of jitter.. Thinking to maybe set up some sort of camera triggering just to see if there is actual motion that I'm not aware of.

Mostly satisfied.. Though I wish there was some sort of software smoothing so that I could set the duration that the sensor reports as active and the delay between retriggering. The resistor based hardware controls just aren't good enough. I'd like to say if triggered show active for 1 minute and then don't retrigger  for another 30 seconds (or something like that).

**Comment by Nayar** [comment]
I use my sensor only to detect motion then send an MQTT message. My homeassistant server then decides whether to turn on the lights or not. I get much more control

**Comment by Reinhartd** [comment]
I have the same problem, every few seconds is switched from on to off. I have changed the hc-sr501 and now everything is ok. PS. My Sensor is plugged on 5V.
