### ISSUE TITLE
1 Million Downloads !!!!

### ISSUE THREAD

**Issue by ascillato** [arendst/Sonoff-Tasmota#3100]
# Tasmota has reached 1 Million Downloads!!

### Thanks to Theo (@arendst) and to everyone that have contributed to this!

-------------------

**Special mention to the people who had contributed to Tasmota (in no particular order):**

@arendst @davidelang @reloxx13 @RaymondMouthaan @Jason2866 @Frogmore42 @curzon01 @luisfpinto @Snipercaine @ascillato @colinl @flexiti @ErikAndren @smadds @soif @gtortone @renne @znanev @StofLE @prabbit237 @sammy2360 @Drachenkaetzchen @altelch @ThomDietrich @envy 
@johannesbonn @RocketSience @jeylites @Winni66 @misc2000 @killadm @crankyoldgit @don-willingham @Staars @vivianlink @IVI053 @Geitde @gnkarn @Lawrencezarb @stefanbode @roblad @ionciubotaru @sisamiwe @wongnam @cputoaster @daenny @gemu2015 @JohannWeging @egs2003 @kenmcc @Stevehans @IceStuff @CapnBry @danielztolnai @foxel @codeworkx @jonatanolofsson @emontnemery @jonlidgard @nisof @labastov @KPK75 @palich2000 @kabongsteve @dino-de @filzek @Hogesyx @brainnex @fragolinux @Leseratte10 @kan3nas @ThierryM @anduchs @nferreyra @Smoffitz @Hugo477 @dasMopo @gemu2015 @jjlawren @aidanmountford @danielztolnai @OperatorB @johngouk @issacg @piotrpad @RTurala @roman-vn @joba-1 @WoHinDu @aidanmountford @oglodyte @domdomegg @palich2000 @projectkk2glider @bensuffolk @Sergey-SRG @0n3-70uch @OlivierFrancais @PheiPheiPhei @aidanmountford @Big4SMK @wouterbaake @zewelor @vanyid @foxsam21 @H4ndl3 @bashlikova @palich2000 @casualoak @pgollor @zerog2k @mortenmathiasen @VinceMasuka @MikePRoberts @KPK75 @tom211 @mitkodotcom @RemCom @mzealey @pascalsaul @mzealey @wiktorschmidt @PeteBa @FoxRomeo @syssi @vicfergar @BrettSheleski @jwrw @maartendamen @HellGL @joecotton @pimvanpelt @SirAd @khcnz @AlexTransit @mapero @Nayar @legotheboss @haegar33 @Kielkopf @matt-downs @darkstarlabs @chaosmaster @RoganDawes @runbren @AndyWhittaker @cendern @ajaypala @markcarline @sergicastellsague @rkoripalli @maciboy @krahl @newzealandpaul @vicfergar @meanderfox @leothehuman @joke24 @taylormia @chris-thorn @MYLE-01 @myhd @IainPHay @meneelyt @LarsPedersen @schmic @ulab @vzorglub @apastuszak @darkstarlabs @JueBag @ACCakut @MichiM2 @vzorglub @irl @BrutalBirdie @smoke007 @lszeremeta @mwuertinger @Smoffitz @KBrownConsulting @RodrigoTomeES @Schnittcher @KaaNee @LachlanB96 @mehuman @Skaronator @Bolukan @wasiflaeeq @akasma74 @alekc @Goobaroo @emeyedeejay @xbmcnut @RodrigoTomeES @geek65535 @FlorianKempenich @nmaggioni @aspitznyc @TylerDurden23 @domdomegg @Herschdorfer @Cooper-Dale @lance36 @xbmcnut @erew123 @glogiotatidis @tobox @mogwai2 @pascalsaul @GillesDebunne @Confectrician @NameTakenAgain @kozy @namadori @geekypenguin @PointFlare @mitchwd @rhodopsik @juan11perez @rhodopsik @jimmyw @foxsam21 @doppiaemme @elbow @SodoffBaldrick @haroldb @SupraJames @0xDEAD @hs06 @terba @lobocobra @edit21 @ameuret @mushudog @phedders @taylormia @kuzavas @toddrobinson @saerdnaer @nconder @bphermansson @eimix @patbeirne @Xeroxxx @jhlweb @lobradov @tom211 @ageorgios @sillyfrog @papaiatis @ulab @gerardovf @cputoaster @PeteBa @phedders @bdjohnson79 @pnuding @Ghostbird @Espablo @Saxtus @joecotton @hkortier @laithalsunni @StevenLangdale @henriklewander @tam481 @aequitas @andrew-from-pretoria @dalmoz @Stalkk @anton101101 @ronnicek @jwrw @terba @Mikk36 @dontpanic21 @gajotnt @pasz1972 @off14 @mihalski @chriscohnen @JshWright @khcnz @ecsfang @CWempe @digiblur @Hogesyx @lionhe1966 @acejacek @MacWyznawca @Giotino @binderth @asterix555 @Dietmar-Franken

And everyone who has contribute to this project with PR, ideas, issues, wiki, etc. 

# Thanks ! :+1: 

_(if your name is missing, sorry about that and also thanks to you)_

**Comment by ascillato** [comment]
@AndyWhittaker
@cendern
@ajaypala
@markcarline
@sergicastellsague
@rkoripalli
@maciboy
@krahl
@newzealandpaul
@vicfergar
@meanderfox
@leothehuman
@joke24
@taylormia
@chris-thorn
@MYLE-01
@myhd
@IainPHay
@meneelyt
@LarsPedersen
@schmic
@ulab
@vzorglub
@apastuszak
@darkstarlabs
@JueBag
@ACCakut
@MichiM2
@vzorglub
@irl
@BrutalBirdie
@smoke007
@lszeremeta
@mwuertinger
@Smoffitz
@KBrownConsulting
@RodrigoTomeES
@Schnittcher
@KaaNee
@LachlanB96
@mehuman
@Skaronator
@Bolukan
@wasiflaeeq
@akasma74
@alekc
@Goobaroo
@emeyedeejay
@xbmcnut
@RodrigoTomeES
@geek65535
@FlorianKempenich

**Comment by ascillato** [comment]
@nmaggioni
@aspitznyc
@TylerDurden23
@domdomegg
@Herschdorfer
@Cooper-Dale
@lance36
@xbmcnut
@erew123
@glogiotatidis
@tobox
@mogwai2
@pascalsaul
@GillesDebunne
@Confectrician
@NameTakenAgain
@kozy
@namadori
@geekypenguin
@PointFlare
@mitchwd
@rhodopsik
@juan11perez
@rhodopsik
@jimmyw
@foxsam21
@doppiaemme
@elbow
@SodoffBaldrick
@haroldb
@SupraJames
@0xDEAD
@hs06
@terba
@lobocobra
@edit21
@ameuret
@mushudog
@phedders
@taylormia
@kuzavas
@toddrobinson
@saerdnaer
@nconder
@bphermansson
@eimix
@patbeirne
@Xeroxxx
@jhlweb
@lobradov
@tom211

**Comment by ascillato** [comment]
@ageorgios
@sillyfrog
@papaiatis
@ulab
@gerardovf
@cputoaster
@PeteBa
@phedders
@bdjohnson79
@pnuding
@Ghostbird
@Espablo
@Saxtus
@joecotton
@hkortier
@laithalsunni
@StevenLangdale
@henriklewander
@tam481
@aequitas
@andrew-from-pretoria
@dalmoz
@Stalkk
@anton101101
@ronnicek
@jwrw
@terba
@Mikk36
@dontpanic21
@gajotnt
@pasz1972
@off14
@mihalski
@chriscohnen
@JshWright
@khcnz
@ecsfang
@CWempe
@Hogesyx
@lionhe1966
@acejacek
@MacWyznawca
@Giotino
@binderth
@asterix555
@Dietmar-Franken

**Comment by ascillato** [comment]
# Thanks !!! :+1:

**Comment by ascillato** [comment]
Let's Thanks Theo for this great project!

**Comment by reloxx13** [comment]
![cheers](https://media1.tenor.com/images/1c2eb6a89bccd76132feefc2280dee35/tenor.gif?itemid=4884466)

thanks to all for the effort!

**Comment by 0n3-70uch** [comment]
Wow so great.... :+1: -)
Have a nice weekend.

**Comment by RaymondMouthaan** [comment]
Congrats to you all, but especially Theo 🎉(@arendst)🍾

**Comment by arendst** [comment]
Thx to all who keep this show on the road.

I'll go for the next million.

**Comment by FlorianKempenich** [comment]
Thank you for making me feel like a movie hacker! 😄 😄 💯 🎉

![img_20180308_104916_bokeh](https://user-images.githubusercontent.com/10831649/42114103-b971c8c0-7be5-11e8-82e6-4da007cd69eb.jpg)

**Comment by misc2000** [comment]
Congrats 🍾 to Theo @arendst  everyone involved and also to Adrian @ascillato for the KNX part. 👍
Without this work my pool whould never be able to go online  😄

**Comment by domdomegg** [comment]
:champagne: :tada: :fireworks:

Congrats and thanks to everyone, especially @arendst :1st_place_medal:

**Comment by newzealandpaul** [comment]
Congrats @arendst. Your work is absolutely amazing. You have made my life better. Sonoff-Tasmota is the best IOT platform I have ever used :) ❤️

**Comment by digiblur** [comment]
Wow! That's awesome! Such an amazing project. Still impresses me how much power has been pulled out of this little chip.

**Comment by Snipercaine** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/b8b01acf-113e-4801-b09f-6403c66e3c4a-c7ec0e5a-8f72-497e-8a95-f3c3af0d1cb6-v1.png?transparent=1&palette=1&width=246)
You've made it possible for non-coders (like me) to enjoy Home Automation and electronics beyond anything we could have done without you. 
Thanks!!
Here's to 2 Million soon!!
-DrZzs

**Comment by JuliusLedoux** [comment]
Thank you for all the hard work. You make a great piece of software for all the tinkerers out there! Well done!! I am really grateful!

**Comment by ascillato** [comment]
:smile:

**Comment by arendst** [comment]
??? 😀

**Comment by ulab** [comment]
> Tasmota has reached 2 million downloads!

Sonoff should just start shipping this as the default firmware ;-)

**Comment by Jason2866** [comment]
A W E S O M E ! !

**Comment by RaymondMouthaan** [comment]
Awesome!!! Thanks to you all 🎉🎉🎉

**Comment by davidelang** [comment]
On Sat, 17 Nov 2018, Balu wrote:

>> Tasmota has reached 2 million downloads!

with who knows how many units flashed per download

> Sonoff should just start shipping this as the default firmware ;-)

<sarcasam>
ahh, but then they wouldn't have their cloud management software lockin (for 
whatever value that actually provides)
</sarcasam>

David Lang

**Comment by MYLE-01** [comment]
I have 16 with one download and have 5 more on the way 

Thanks guys

**Comment by arendst** [comment]
Thank you all for your kind words and support. Tasmota keeps on growing every day due to many supporters of great ideas and solutions.

Let's keep it that way!

**Comment by Jason2866** [comment]
Thank you Theo for your great work and awesome support

**Comment by meingraham** [comment]
Thank you @arendst  Theo (and team) for the fantastic project! 1 million downloads in the last 2 months. 1 million in the 5 months prior to that. Not sure about the first 1 million, but the expansion of its use is phenomenal!

**Comment by apastuszak** [comment]
Now how do we get iTead to offer it as a build to order option?

**Comment by GianCann** [comment]
Great, great work, guys!

I discovered Tasmota about two months ago, and I follow the developments of this great little software every day!

**Comment by RaymondMouthaan** [comment]
@arendst (Theo) and all others who participated this great project, congratulations!!!
Tasmota makes HA effective and fun! Thank you!

**Comment by smadds** [comment]
I'd like to add my thanks to all the others. Thanks for starting it, Theo, and thanks for sticking with it too!

**Comment by ascillato** [comment]
To this 3 million downloads, we need to add also the downloads from development branch at http://thehackbox.org/tasmota/ (Thanks @andrethomas), the repository clones and forks.

All this thanks to the continuos help and support from the Tasmota community :+1:

**Comment by ascillato** [comment]
# Tasmota has reached 4 million downloads!!!!

**Comment by arendst** [comment]
Congrats to the ever increasing amount of contributors.

**Comment by ascillato2** [comment]
# Tasmota has reached 5 millions downloads!!!!

**Comment by Tommy-LSA** [comment]
Time to set up a „Tasmota Foundation“ ;)

Von meinem iPhone gesendet
