### ISSUE TITLE
[Feedback wanted] Alexa issues after 6.0.0b WIFI Test changes

### ISSUE THREAD

**Issue by reloxx13** [arendst/Sonoff-Tasmota#3101]
Anyone else getting Alexa Problems ("Device does not respond") since 6.0.0b?

After this commit:
https://github.com/arendst/Sonoff-Tasmota/commit/20a53950ff208314cb609cb3ecf640c4bf5c4d85

Please provide Feedback 👍 

---

Before this commit Alexa had no issues with the devices, now she tells me often the device does not respond.
After 2-3 times giving the command to power on the device, it will power on.

6.0.0b@2.3.0 and WemoEmu

**Comment by Jason2866** [comment]
Works without any problem. Tested with my easy accessibly sonoff basic "Couch" Modul.
A reading lamp voice controlled via Alexa. So i have not to stand up if i need a light for reading😆

**Comment by nivek88** [comment]
Yes, having the same problems!
