### ISSUE TITLE
Hardware reset by power consumption

### ISSUE THREAD

**Issue by detsadrb** [arendst/Sonoff-Tasmota#3117]
Does anybody can develop feature like this:

when power consumption more or Less then input value — sonoff switch off or switch off (delay 3 sec) and turn on. It will amazing if i could to do hardware reset with sonoff pow.

**Comment by Frogmore42** [comment]
You can easily do this using NodeRED and probably other home automation systems too.  I do something even more complicated to control my dehumidifier.

**Comment by Frogmore42** [comment]
If this answers your question, please close the issue.

**Comment by curzon01** [comment]
Without an external system use [Rules](https://github.com/arendst/Sonoff-Tasmota/wiki/Rules) with a [Backlog command](https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#command)
