### ISSUE TITLE
MqttRetry Time not avaliable in user_config.h

### ISSUE THREAD

**Issue by charinduedirisuriya** [arendst/Sonoff-Tasmota#3128]
I noticed while going through the user_config.h file the MqttRetry time was not defined, but this feature is defined in the commands page, https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#mqtt-specific
under MqttRetry

**Comment by ascillato2** [comment]
Hi,

If you want to change the default value (10) you can add in your _user_config.h_ file:

```
#undef  MQTT_RETRY_SECS
#define MQTT_RETRY_SECS        10
```
