### ISSUE TITLE
Minor  editing issue with Flashing on Raspberry Pi

### ISSUE THREAD

**Issue by neuman1812** [arendst/Sonoff-Tasmota#3136]
Inital Copy and Paste of the directions from here https://github.com/arendst/Sonoff-Tasmota/wiki/Flash-Sonoff-using-Raspberry-Pi ,   Led to a few minor Problems.   I detailed my results and solutions in the reddit post here:

https://old.reddit.com/r/sonoff/comments/8wb6dy/trying_to_flash_a_th16_with_raspberry_pi_no_luck/

using Raspberry Pi3 and Th10/16

1: Pinout Directions. [See here](https://i.imgur.com/1MZc7nr.jpg)

Note the location of the rx/tx pins. I had them backwards initially.

2: A copy paste from the Wiki page gives the wrong -(dash) mark

Original: esptool.py —port /dev/ttyS0 erase_flash
Modified: esptool.py --port /dev/ttyS0  erase_flash

3: Error in file Size to write (esptool write_flash: error: argument --flash_size/-fs: 1mb is not a known flash size.)

Original Command: esptool.py --port /dev/ttyS0  write_flash -fs 1mb -fm dout 0x0 sonoff-allsensors.bin 
Modified Command: esptool.py --port /dev/ttyS0  write_flash -fm dout 0x0 sonoff-allsensors.bin

4: SSID and Password

In the Directions to modify your SSID and Password you would use :

ssid _yourSSID_

password _yourPassword_

Do NOT include the underscores __

Thats it. Once I removed power and added it back in, I was able to access the WebGUI.

**Comment by ascillato2** [comment]
Thanks :+1: 

Added to the wiki.
