### ISSUE TITLE
Logo proposal for Sonoff-Tasmota

### ISSUE THREAD

**Issue by orlant** [arendst/Sonoff-Tasmota#3138]
Hi how are you, I am a graphic designer and I would like to introduce you to this idea of ​​logo that I have created for Sonoff-Tasmota and Sonoff -Tasmota_KNX taking into account that I made this design by inspiration of the Initials of the name of this project. This logo is very easy to recognize. even if we delete the letters, you can use it with an ideal LogoMark for that project ... I hope you take into account this contribution, any modification I am made to order

![sonoff](https://user-images.githubusercontent.com/40074778/42345737-58f75cf2-806e-11e8-8ede-6da84f1a9ceb.jpg)
![1](https://user-images.githubusercontent.com/40074778/42345752-68fd8c98-806e-11e8-9426-4aaba719e199.jpg)

application of the logo in the firmware
![5](https://user-images.githubusercontent.com/40074778/42345820-98c7266e-806e-11e8-9ed4-78db62772a46.jpg)
![sonoff_update_02](https://user-images.githubusercontent.com/40074778/42345836-a2bdb3b8-806e-11e8-93a8-f67f43d5ad2b.jpg)

I hope you like my idea, any modification of colors and font you want I am ordering ... there are both versions.

**Comment by arendst** [comment]
Nice idea.

To add the logo to the webpage how many bytes would be have to be used keeping in mind that any bytes used for the logo cannot be used for functionality ;-)

**Comment by orlant** [comment]
Does it refer to the number of bytes that the design has? Is there a recommendation or modification that I could make for your use ??? possible solution is that I can minimize the number of bytes of the logo ...

**Comment by arendst** [comment]
I hope the logo would not use as much as up to 60 bytes ….

**Comment by orlant** [comment]
To complete this task by personal recommendation we can leave the LOGO / ICON ... which does not contain the letters of the project, for the use of its functionality it helps to avoid the number of bytes ... anyway I will reduce to 60 bytes all the designs made seems ... I'll show you

**Comment by orlant** [comment]
I'm sorry sir theo 60 bytes is very little and it will not even be seen how small it would be, if I could use at least 1kb I could do something for you !!!

**Comment by ascillato** [comment]
Hi,

@orlant 

Sonoff Tasmota is mainly a MQTT device with an extra of KNX between other functions (HTTP, SERIAL, TIMERS, etc), so I think it is not needed the KNX name. Also, I have just realized that It is going to be a trademark problem using a registered brand name as KNX and also SONOFF. Both names are trademark protected and can not be used.

I think that you should use just TASMOTA and a Icon.

_(Also, please edit the title of this issue to english)_

@arendst 

If you want add a logo, one option that don't use flash memory space could be just have the logo at your repository and be linked from the Tasmota webpage (if the device have internet, the logo will be displayed, if not, just a name will be shown)

**Comment by orlant** [comment]
ok I am willing to make the changes that are important, with pleasure but it would be a shame because Mr. theo requires me that the logo has a maximum size of 60 bytes, it is very low resolution and the design is lost ...
If the proposal that you have given Mr. Theo takes it into account, it would be great because you can see the result obtained added to your repository. that would be the first benefit and second benefit will be visible on the website. if you think it is necessary I can make the modifications.
"Let's hope Mr. Theo says" ..

(@ascillato I've edited the title from Spanish to English three times and it's still the same, I'll try again)

**Comment by ascillato** [comment]
Hi,

@orlant 

You write first in my repository at https://github.com/ascillato/Sonoff-Tasmota_KNX/issues/151 and I was trying to explain to you that there is not a separate software with KNX. There is just this Tasmota Repository. The other is the same but I use that for tests. The original is Theo's.
That's why, a logo should be without the KNX word, also due to it is registered to knx.org

**Comment by ascillato** [comment]
Also a better resolution logo can be used in this repository.

**Comment by orlant** [comment]
perfect and I am much more understood ... I will make all the necessary corrections and I will work based on the LOGOTasmota Root Project ... if it is necessary in the future it makes some edition I commit myself with you to be here!

**Comment by orlant** [comment]
I would like to show you the modifications I have made for you! along with a variation of the ST logo model in black and white version   

![liss](https://user-images.githubusercontent.com/40074778/42400148-7969cdaa-813e-11e8-9828-f072bcfcea39.png)

**Comment by wongnam** [comment]
please be aware of license right, you should not put the "Sonoff" before the "TASMOTA" word. because it's a brand name off Itead products.
i suggest only use TASMOTA to create a logo is enough the meaning.

**Comment by orlant** [comment]
Thanks a lot for the suggestion. well there and I made the correct modification.

**Comment by wongnam** [comment]
as my idea for the modern logos world, a logo is always simple and easy to identify is the best.

btw, i very like the only text in your design to use as TASMOTA logo :)
![tasmota_logo](https://user-images.githubusercontent.com/36041520/42406381-9a0363e0-81d0-11e8-82c8-ea71df7f8277.PNG)

**Comment by pascalsaul** [comment]
Best solution is to use Base64 encoding so you don't need internet en you can embed it into the HTML.

See: https://varvy.com/pagespeed/base64-images.html

**Comment by roguestreak** [comment]
I reckon the kerning on the left of the "A" needs reducing in both cases, tucking it under the "T" slightly to reduce the apparent gap.  I'd also slightly increase the kerning in general for the "SMO" as to me they are a bit squished.
