### ISSUE TITLE
Override loglevel per command

### ISSUE THREAD

**Issue by i3laze** [arendst/Sonoff-Tasmota#3140]
Weblog of my device is overrun by STATE requests every 5 minutes from HomeBridge. 
I didn’t find how to increase weblog buffer (aprox. 35 strings for now). 
What I’m interested in is: POWER, RESULT and SRC outputs only. This way I can’t view what happened 6 hours ago.
All of this is solvable by deploying an external syslog, but it’s a bit excessive.

As I mentioned previously here: https://github.com/arendst/Sonoff-Tasmota/issues/2843#issuecomment-393448953,
It’s gonna be nice for the user to be able to move some commands between log levels.
Like STATE -> lvl 3, SRC -> lvl 2

**Comment by Jason2866** [comment]
Due to limited Memory of the ESP there is simply "no room" for storing more...
If you need things like that you have to do it extern.
Maybe @arendst finds your idea nice and it is possible to realize LOG Level defining

**Comment by arendst** [comment]
As loglevels are incremental there is always the problem of having too much info at some time. The current log levels are fine and more will just open up a big can of worms where some want it on level 10 and others on level 12...

As you already noticed the external syslog server is the way to go. If you have a Linux server around logging is just some small config on the server to make it available for all your devices.

**Comment by i3laze** [comment]
Thanks. Seems external syslog with filtering is a way to go.
