### ISSUE TITLE
several delay for external buton when internet lost

### ISSUE THREAD

**Issue by solucionesmipc** [arendst/Sonoff-Tasmota#315]
hi:

i connected external button to gpio14 and ground, 
if internet is lost then actions from external button takes several time to execute

is possible to change order of somehing in code to execute action inmediately with or without internet?

thanks Diego.

**Comment by ionciubotaru** [comment]
This happens because MQTT tries to reconnect. Please disable all internet service (MQTT, RSYSLOG, timeserver) and you will not see delays any more.

**Comment by solucionesmipc** [comment]
i understand it

is there some intermediate solution , i want to keep mqtt functionality

thanks for your answer.

**Comment by ionciubotaru** [comment]
no, you have to manually choose between mqtt and no mqtt
better use a local mqtt server, is faster, more stable and you can use it with no encryption

**Comment by jonathanmbradshaw** [comment]
if you need to export the switch status to an external MQTT instance you might consider using an MQTT bridge from the local to the remote.

**Comment by davidelang** [comment]
the delay you are complaining about is due to a bug in a library that is used by tasmota, when it initiates a connection to the mqtt server, it can do nothing else until it either connects or times out.

run a local mqtt server or disable mqtt to avoid this problem

**Comment by solucionesmipc** [comment]
hi

thnks for your answer, do you know some similar project without that bug?

thanks again

**Comment by davidelang** [comment]
it would have to be one that doesn't use the standard Arduino based TCP 
libraries.

someone mentioned some async TCP library, but I don't know any details around 
that.

if you are not using mqtt, disable it. If you are, have it connect to a local 
server so you aren't dependent on the Internet.

**Comment by solucionesmipc** [comment]
do you believe can i change the time for timeout?

what file should i modify?
