### ISSUE TITLE
Sonoff Homekit TempSensor

### ISSUE THREAD

**Issue by BertanKatze** [arendst/Sonoff-Tasmota#3153]
Hi, I just want to connect a ds18b20 temp sensor to my Sonoff and connect it to Apple HomeKit using HAP-NodeJS and a Raspberry Pi with the MQTT service. Does anybody know how to? Thanks!

**Comment by Jason2866** [comment]
Hi @BertanKatze 
Here you will probably get no help for your questions. This is github for Tasmota issues.
You have a question that is not a problem nor really Tasmota related.
How to connect a ds18b20 is described in wiki and the temperature is sended via mqtt.
https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-Configuration
So you better ask for help in a forum for homekit and HAP-NodeJS

**Comment by BertanKatze** [comment]
Thank  you @Jason2866. I’m sorry for that. I’m new to GitHub. I hope that I didn’t make you busy with an unrelated question. And again, a huge thanks for your help😊

**Comment by Jason2866** [comment]
Your welcome. Please close this issue. Thank you.
