### ISSUE TITLE
Provide LED Control for 4CH Pro Relay LEDs

### ISSUE THREAD

**Issue by meingraham** [arendst/Sonoff-Tasmota#3154]
Currently only the blue "power" LED can be configured. Add feature to set the behavior of the four relay LEDs using commands such as LedPower<x> and LedState<x> similarly to how Power<x> allows control of each individual relay.

**Comment by Frogmore42** [comment]
Can't be done without a soldering iron.  The LEDs on Sonoff devices are directly connected to the same GPIO as the respective relay.

**Comment by meingraham** [comment]
Ah... my bad. Wishful thinking.
