### ISSUE TITLE
Add Wi-Fi State LED Option

### ISSUE THREAD

**Issue by meingraham** [arendst/Sonoff-Tasmota#3155]
Add feature so that the power LED provides feedback as to the current Wi-Fi connection status. If the Sonoff connects to Wi-Fi successfully, follow the LED function as configured for the device (LedPower, LedState). However, if the device does not connect to Wi-Fi successfully, slow blink the power LED. As an option, this requested behavior can be configured. with a compile-time parameter or via a Console command.

**Comment by arendst** [comment]
Released in development branch v6.1.0a as blinkyblinky.

Default on and overrules LedState but NOT LedPower. Can be disabled by command ``SetOption31 1`` to keep the led functional as before.
