### ISSUE TITLE
Friendlyname must be different for DUAL / v1.3.3

### ISSUE THREAD

**Issue by BigWumpus** [arendst/Sonoff-Tasmota#3161]
(I think so).
my Sonoff DUAL R2 has two frindlynames (per default: sonoff sonoff2) in order to identufy the two relais to alexa.
The Config-menu in TasmoAdmin 1.3.3 schows two friendlynames, both the same. The setup in the webmenue is with different names.

**Comment by reloxx13** [comment]
wrong github
https://github.com/reloxx13/TasmoAdmin/issues

also, got this as todo already ;)


<?php //@TODO: add multi firendlyname as 5.12.0h its an array! ?>

**Comment by reloxx13** [comment]
fixed in next version

**Comment by BigWumpus** [comment]
Sorry, not my day
