### ISSUE TITLE
sleep will stop config of the sonoffs / 1.3.3

### ISSUE THREAD

**Issue by BigWumpus** [arendst/Sonoff-Tasmota#3162]
the value for the sleep-config must be 25,50,... I you set other values in the web-config, TasmaAdmin can not change the config, unless you change this parameter.

**Comment by reloxx13** [comment]
wrong github dude :D

https://github.com/reloxx13/TasmoAdmin/issues

**Comment by BigWumpus** [comment]
Sorry, not my day
