### ISSUE TITLE
SerialSend as hex

### ISSUE THREAD

**Issue by KPK75** [arendst/Sonoff-Tasmota#3168]
**Have you look for this feature in other issues and in the wiki?**
Yes

**Is your feature request related to a problem? Please describe.**
Yes, support for LCTech modules

**Describe the solution you'd like**
Ability to send serial commands via MQTT like SerialSend4 0xA00101A2

**Comment by bastelfix** [comment]
check this: https://community.openhab.org/t/looking-for-a-mqtt-to-ir-device/46455/7

**Comment by Jason2866** [comment]
Hello @KPK75 
Only this is possible
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#serial-bridge
@arendst did the design decision not implementing sending Serial Raw only printable character.
See #2190

**Comment by ascillato** [comment]
Hi @arendst 

Is it possible to be added a command SerialSend4 to send Hex values?

**Comment by ascillato2** [comment]
Added by Theo.

Closing issue. 

Thanks :+1:
