### ISSUE TITLE
big problems calling the configuration page

### ISSUE THREAD

**Issue by dr-apple** [arendst/Sonoff-Tasmota#3170]
I have big problems calling the configuration page.

Either the site just breaks or it is empty or it is displayed but you can not see any settings and all dropdown fields are empty and you can not select anything.

No matter with which browser I try it always the same ;-(

**Comment by curzon01** [comment]
Please do not pass the requested information when posting an issue. I assume what could cause the problem but guessworking cost a lot of time.
Please post at minimum Status 0 info or if not possible if you use which release binary or self-compiled, how compiled (Arduino, Atom...) which version you use and which lib you select

**Comment by reloxx13** [comment]
http://yourdeviceip/cm?cmnd=status%200

if you cannot reach the console web page.

**Comment by ascillato2** [comment]
Hi

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks.
