### ISSUE TITLE
Support for ESP-01 DHT11 Temp sensor module

### ISSUE THREAD

**Issue by vaidyasr** [arendst/Sonoff-Tasmota#3171]
I would like to know whether Tasmata supports ESP-01 DHT11 Temp sensor module?.
[https://www.aliexpress.com/item/ESP8266-ESP-01-ESP-01S-DHT11-Temperature-Humidity-Sensor-Module-ESP8266-Wifi-NodeMCU-Smart-Home-IOT/32845741344.html](url)

**Comment by Jason2866** [comment]
I short yes. But i would not buy a DHT11 (unaccurate). 
Better choice take a WeMos mini and a BME280 (Modul) you will find both on Aliexpress

**Comment by ascillato2** [comment]
Seems that your issue is solved. If not, please reopen it. Thanks
