### ISSUE TITLE
Issue of Sonoff Touch (2 gang) as Roller Shutter

### ISSUE THREAD

**Issue by Sunrise17** [arendst/Sonoff-Tasmota#3176]
@davidelang , @arendst , i have uploaded 6.1.0 to Sonoff Touch (2 gang model) to use it as Roller Shutter switch. I have adjusted Setoption14 1, Setoption 13 1 and when i use it with following homebridge plugin below, it works well during open/close switch on main menu and even over Siri (to ask percentage). But on Slider, there is some weird issue to update current state of the switch as seen in the video following below, i will be glad if you can share your comments.

[homebridge-tasmota-mqtt-motor Plugin](https://github.com/ageorgios/homebridge-tasmota-mqtt-motor)

[Video Link](https://www.youtube.com/watch?v=GXmC4nBuQmY)

**Comment by chriskmn** [comment]
I have an issue with SetOption14 1: turning off an switched-off port turns off also the other port if it is active. Can that be your problem also ?

**Comment by opendore** [comment]
Also me, same issue...any idea?

**Comment by stefanbode** [comment]
If you use it for shutters you may better go with this fork: https://github.com/stefanbode/Sonoff-Tasmota/wiki/Shutter-blinds-working-with-two-relays. To work with pulsetime is more than nasty.

**Comment by ascillato2** [comment]
Hi,

Continuing this issue at: #3137
