### ISSUE TITLE
v6.1.0 WiFi Manager (AP Mode 192.168.4.1) doesn't start

### ISSUE THREAD

**Issue by i3laze** [arendst/Sonoff-Tasmota#3180]
I used RU and didn't test EN firmware, but tried erasing/flashing fresh new Sonoff Basic three times.

Quickly pressing button 4 times - LED starts blinking,
but Sonoff-ID SSID doesn't appear in WiFi networks list like at all.

Just flashed v5.14 - 4 presses and autoconfig SSID is right here. Please investigate.

**Comment by andrethomas** [comment]
Is there any output on the serial port?

**Comment by i3laze** [comment]
I'll try to reproduce on another unit. Hold on for an hour.

**Comment by andrethomas** [comment]
The content in the serial output is questionable... should not have all those special characters.

Have you tried configuring wifi from the serial console, enter commands

ssid1 "mywifiapname"
password1 "mywifipassword"

**Comment by andrethomas** [comment]
Correction, dont include the "'s

Just

ssid1 mywifiapname
password1 wifipassword

**Comment by i3laze** [comment]
Nah, I've deployed v5.14 back in production.
Let's wait for anyone else to confirm the issue.

**Comment by i3laze** [comment]
I guess it was solved in v6.1.1:
https://github.com/arendst/Sonoff-Tasmota/issues/3177
Will give a try today.

**Comment by ashfaaaa** [comment]
I have the problem on v6.1.1  I just flashed tasmota and im  unable to connect with button 3 press and button 4 press ( led blinks) no ap found when i search for it.

**Comment by ascillato2** [comment]
Please, see #3224

If your issue is not solved, please reopen it. Thanks
