### ISSUE TITLE
Sticky MAC Adress Option for AP 

### ISSUE THREAD

**Issue by razer4908** [arendst/Sonoff-Tasmota#3189]
Hi,
first of all thank you very much for this awesome firmware. 
Do you think it is possible to implement an option, so that the Sonoff always connect to the same Router (via MAC-Address) ? APMac is already visible in the console view so think an Input Mask for the APMac to check the equality of the AP MAC is the Solution.

Background: 

I have 2 Wifi AP´s named the same so that for example mobile phones can switch the AP easily when i go downstairs, But sometimes the Sonoffs also switch to the AP with the lower signal strength. So if i can set an MAC-Address to fix the Sonoff to an specific AP would be awesome. 

Greetings from Germany
Dominic

**Comment by Frogmore42** [comment]
Tasmota is using the Wifi code from the esp8266 Arduino project.  I don't believe it supports what you want.  So, I don't believe you can do it.

I have two APs but they are some distance apart.  I gave them unique names, so I could see which one was connected.  It also makes it easier to control which one things use for connection.

**Comment by ascillato2** [comment]
Just for reference to a similar request. #2711

**Comment by ascillato2** [comment]
Hi,

It is not supported by now. As the ESP8266 wifi libraries are still in development and still have some issues, Tasmota is keeping WIFI management as simple as it can be, in order to avoid as many problems as it can.

So, by now it is not going to be implemented. When the esp8266 libraries got more mature we can add more features.

Thanks for your comments.

Added the goodtip label in order to take your request the in future

**Comment by leifclaesson** [comment]
It's been almost two years. I'm looking for the same thing. I'm planning to have a large amount of WiFi lights in my ceiling, and will need them to be _off_ rather in standby when not in use, so fast connection is absolutely crucial. Apparently it's possible to connect to the AP in 450ms with static IP and pre-configured BSSID.

WiFi.begin() *does* seem to support specifying BSSID and channel as a parameter, and these lights and the access point will _not_ be moving around.

The esp8266 libraries seem to support it, what's missing is support in Tasmota.

**Comment by s-hadinger** [comment]
@leifclaesson I did a quick and dirty test and indeed the connection happens real fast. Theo confirmed he will explore.

**Comment by ajw107** [comment]
Could you make  it possible to configure the BSSID, therefore forcing it to connect to a specific AP.  This would be really useful, and what the OP seemed to want too.

**Comment by SteveDinn** [comment]
I would love to have this feature. Currently a few of my tasmota devices always seem to want to connect to a remote node of my mesh wifi network, I can't seem to get them to pick any of the closer ones. BSSID would force it.

**Comment by martymarty004** [comment]
This would be the perfect solution for anyone who has multiple APs near each others

**Comment by DL6ER** [comment]
I'm also using a Mesh WiFi with three access points spread across the entire house. They all have the same SSID. Even when I place my tasomtized Sonoff next to one of the APs, it picks one of them by random, and then reports a signal quality of less than 30-40%.

I've seen https://github.com/Jason2866/Tasmota/pull/17 which stores BSSID for quick reconnect. A similar feature could be added to upstream Tasmota with customizable BSSID, what do you think? @ascillato2

**Comment by DL6ER** [comment]
My plans are to extend the simple results
![Screenshot from 2020-12-25 10-03-38](https://user-images.githubusercontent.com/16748619/103129302-8b3df980-4698-11eb-875e-181bef4fe522.png)
to a list of individual AP/BSSIDs maybe like
![Screenshot from 2020-12-25 10-18-36](https://user-images.githubusercontent.com/16748619/103129870-985be800-469a-11eb-98d6-91266925c02e.png)


@arendst If you think this is something worth adding and is going to be accepted, I'm willing to work on this and see if it is possible.

**Comment by arendst** [comment]
Don't bother. I fought an earlier fix for over a month to get it stable again for all users so no plans to change this process again.

I suppose you did look at using ``SetOption56`` and ``SteOption57`` to manage your issue.

Anyway, I have two unifi AP's with same SSID and my devices just select the most powerful connection. Once done I do ``SO56 0`` fixing my latest BSSID.

**Comment by DL6ER** [comment]
Thanks for pointing me towards `SO 57`. For whatever reason, I have only seen `SO 56` so far and will try `57` now.

So my contribution will reduce to improving the WiFi scanner result display because this gives some nice extra info: https://github.com/arendst/Tasmota/pull/10253

**Comment by RaphaelSquair** [comment]
hey guys , any plays to reopen this feature?, here in brazil we have company routers that are completely useless even with a stronger signal, this feature would enable us to chose witch AP we want to connect without having to use so56 and so57
