### ISSUE TITLE
Could you tell me how nodemcu can be correctly brushed in and brushed in? I saw that the device supported in Wiki has node MCU.

### ISSUE THREAD

**Issue by gldon** [arendst/Sonoff-Tasmota#3190]
**Have you look for this feature in other issues and in the wiki?**

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

I don't understand your question. Please explain a bit more.

**Comment by ascillato2** [comment]
Hi,

As there was no feedback, I'm closing this issue. Please, reopen it when having the information requested so we can help you with your problem. Thanks.
