### ISSUE TITLE
Local Staircase Functionality

### ISSUE THREAD

**Issue by Sandominion** [arendst/Sonoff-Tasmota#3197]
I am a new user of Sonoff products. After some problems I managed to update the Sonoff TH with TASMOTA 5.14.0 and configered the temp- and humility sensor. My aim is to use it for watering my garden by powering the garden pump. Independend on the way of activation (remote or with the button on Sonoff), it should switch off itself after 30min of activity (even if the WiFi connection has got lost). Unfortunately I couldn't find any possibility to configure this behavior on the Sonoff itself. The discussed solutions I found, all base on a procedure inside a central control (e.g. FHEM) which I don't have and won't help. Is there any chance to get this without develop it by myself? Is this feature interesting for this community at all? Is there any other system to solve my issue easier (e.g. EspEasy)?
Kind regards
Sandominion

**Comment by arendst** [comment]
Search wiki for timers and/or rules

**Comment by Sandominion** [comment]
Thanks for the hint about Rules. Now it works - even without change of code ot config file.
I couldn't use the given example "10. Simple Staircase Timer" because it won't work with remote activation. My solution was to send via console the following commands (just in case somebody want's to solve a similar issue):
rule 1
rule 4
poweronstate 0
rule on Power1#State=1 do ruletimer1 1800 endon on rules#timer=1 do power1 off endon
