### ISSUE TITLE
Sensor API documentation

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#3199]
@arendst  @ascillato2 @everyone

I've started a [sensor API documentation](https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-API) in the wiki.

Feel free to contribute!

**Comment by arendst** [comment]
Way to go!!

**Comment by ascillato** [comment]
Cool :+1:

**Comment by ascillato2** [comment]
Great Job!
