### ISSUE TITLE
Setting Wifi Settings via AP mode does not save the password?

### ISSUE THREAD

**Issue by rustymh** [arendst/Sonoff-Tasmota#3209]
Hi guys
Can you please assist. I'm trying to insert wifi settings via AP mode.  It seems like it's not saving the password therefor keep on failing to connect to any wifi network.
I have done a few attempts resetting the device to default settings as well to fix the issue, but no luck.
I have also tried increasing the SAVE_DATA value.

00:00:00 WIF: Connecting to AP2 ZTE BLADE A601 in mode 11N as sonoff-0546...
00:00:07 WIF: Connect failed as AP cannot be reached
00:00:07 WIF: Connecting to AP1 HUAWEI-B618-2A1D in mode 11N as sonoff-0546...
00:00:19 WIF: Connect failed with AP incorrect password
00:00:19 WIF: WifiManager active for 3 minutes
00:00:20 HTP: Web server active on sonoff-0546 with IP address 192.168.4.1
00:02:00 RSL: UPTIME = {"Time":"1970-01-01T00:02:00","Uptime":"0T00:01:59"}
00:03:23 APP: Restarting

EDIT: It Connected with my phone's Hotspot. The issue seems to be with my router only.  Why would this be?

Thanks

**Comment by Frogmore42** [comment]
There is a reason the template has all those questions in it.  Without answering them, we have to guess exactly how you have things set up and configured and exactly what you are running.  There are many ways that things can go wrong, fixing it is a process of elimination.

But, I'll guess.  You have a Fritzbox router.

**Comment by Jason2866** [comment]
@Frogmore42 just i wanna know: Is the Fritzbox a diva with ESP/Tasmota?

**Comment by Frogmore42** [comment]
Seems like it.  Some people who have had problems with WiFi have been using it.

**Comment by Jason2866** [comment]
For me the Fritzbox is overhyped.... Too many propitary stuff and features.

**Comment by andrethomas** [comment]
@rustymh Does your wifi password contain any escape characters?

**Comment by Jason2866** [comment]
@rustymh   You are not using minimal version? With minimal nothing can be saved!

**Comment by rustymh** [comment]
@Frogmore42 Sorry missed the questions I think.  Router is a HUAWEI-B618.
@Jason2866 No using the normal sonoff version.
@andrethomas My password uses ! , @ , digits and CAPS.

**Comment by andrethomas** [comment]
@rustymh and not things like \ or % ?

**Comment by rustymh** [comment]
@andrethomas no \ or % characters in my password.  But you helped solved the problem. I removed the @ character from my password and it connected. Thanks

**Comment by andrethomas** [comment]
@rustymh Happy to help. 

If you feel your issue is resolved please close this issue.

Thanks
