### ISSUE TITLE
H801 RGBWW Dimmer Control RGB over Web HTTP

### ISSUE THREAD

**Issue by manolisgr81** [arendst/Sonoff-Tasmota#3210]
Hi Guys,

I have a couple of the H801 Dimmer RGBWW modules and have successfully upgraded firmware to the latest Tasmota one.

I can now control W1 and W2 outputs by the 2 sliders in Web interface Warm/Cold and Bright/Dark.

This works perfectly fine and I have also assigned the light switch option in so that I can turn on and off the led strips from my wall switch working fine also.

Only thing left now is to be able to control the RGB part of the led strip that for time being I cannot use colors only 2 Whites .

I have already run the command Setoption15 1 which is meant to enable RGB function on these but apart from these there are no sliders on web interface.

Any Ideas how I can control the RGB part from the web interface?

Any suggestion will be very much appreciated.

Thanks

**Comment by Jason2866** [comment]
With this commands:
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#ws2812-ailight-sonoff-led-b1-bn-sz01-h801-and-magichome

No Web Control

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please, reopen if needed. Thanks
