### ISSUE TITLE
add support for Tm1637 please?

### ISSUE THREAD

**Issue by wehmann007** [arendst/Sonoff-Tasmota#3218]
is it possible to add support for TM1637?
i am using a seven segment display with the TM1637. it works on a sonoff dual r2 with easyesp.
but i want to switch to tasmota.
but i need the display for my project to show the time.

**Comment by arendst** [comment]
I'll think about it. There are some tricks needed to have a 1 second update of user selectable data and keep other users away requesting even more display features...

**Comment by ascillato2** [comment]
#3315
