### ISSUE TITLE
Add DAIKIN AC IR protocol to IRhvac command

### ISSUE THREAD

**Issue by aymeric106** [arendst/Sonoff-Tasmota#3228]
If someone with the knowledge could add the Daikin protocol to IRhvac or IRSend command.

It's documented here

https://github.com/blafois/Daikin-IR-Reverse

and here

http://rdlab.cdmt.vn/project-2013/daikin-ir-protocol

Thank you

**Comment by aymeric106** [comment]
In fact, it's already in the library ...
https://github.com/arendst/Sonoff-Tasmota/tree/development/lib/IRremoteESP8266-2.2.1.02/examples/TurnOnDaikinAC

**Comment by sommo** [comment]
when sending via console 
irhvac { "Vendor": "Daikin", "Power": 0}
i recieve this errors, here if i try to use the vendor Toshiba (no problem), but no lucky with Daikin,
it seems it doesn't find the library):

17:36:27 CMD: irhvac { "Vendor": "Toshiba", "Power": 0}
17:36:27 MQT: stat/sonoff/RESULT = {"IRHVAC":"Done"}
17:36:36 CMD: irhvac { "Vendor": "DAIKIN", "Power": 0}
17:36:36 MQT: stat/sonoff/RESULT = {"IRHVAC":"Wrong VENDOR, MODE or FANSPEED"}
17:37:32 CMD: irhvac { "Vendor": "Daikin", "Mode": Auto}
17:37:32 MQT: stat/sonoff/RESULT = {"IRHVAC":"Wrong VENDOR, MODE or FANSPEED"}

**Comment by sommo** [comment]
i upgraded the firmware of my tasmota, from minimal before and to all-sensor after,
could depend from the first flashing? i need to reflashing via platform.io for example by adding all the libraries? or flashing to allsensor, add it self the last daikin ir library?

**Comment by aymeric106** [comment]
It's already in the base IR library, but not implemented in the IRhvac command.
There's a couple of PR, for two other manufacturer
https://github.com/arendst/Sonoff-Tasmota/pull/3227 (Fujitsu)
and 
https://github.com/arendst/Sonoff-Tasmota/pull/3274 (midea/komico)

Aymeric

**Comment by sommo** [comment]
Hope it will be implemented

**Comment by ascillato** [comment]
Gathering together duplicated DAIKIN issues in one issue at #3423
