### ISSUE TITLE
block GPIO 0 to null flash start

### ISSUE THREAD

**Issue by jsalinaszgz** [arendst/Sonoff-Tasmota#3229]
Hi.

it can be done that it does not start sonoff in flash mode. For example, if the electricity in the house goes out and the gpio0 is grounded in the wall switch?

thanks

**Comment by Frogmore42** [comment]
No, don't use GPIO on a non-momentary switch.  The function of GPIO 0 which invokes the bootloader is hard-coded into the chip and can't be changed.

**Comment by ascillato2** [comment]
Hi, gpio 0 behaviour is internal of the esp8266.

Tasmota have no control over that.
