### ISSUE TITLE
Sonoff showing as available after setting up wifi

### ISSUE THREAD

**Issue by Caswell1000** [arendst/Sonoff-Tasmota#3240]
I've set up wifi on sonoff tasmota latest version, most times it works as expected, but sometimes it blinks continously and enters AP mode, what causes this, and is there a way to prevent it from entering this mode?

**Comment by Jason2866** [comment]
Try command:

WifiConfig 5 

Disable wifi config but retry same AP without restart and flash writes

**Comment by maciboy** [comment]
Let me guess, it's a Sonoff Basic?
It's an ongoing issue, see e.g. #3177

**Comment by Caswell1000** [comment]
@Jason2866 it seems to have worked, thanks....
