### ISSUE TITLE
ESPTOOL issue with <argument #2>

### ISSUE THREAD

**Issue by mike2nl** [arendst/Sonoff-Tasmota#3244]
Yes, i searched if there any information about it.
i used external sources from Ch. Klippel <ck at atelier-klippel dot de>

Issue with the esptool which is possible not well documented in:
-> https://github.com/arendst/Sonoff-Tasmota/wiki/Esptool <-
I use not the phyton version which is advised on that wiki page.

There you can find the information:
-> Optional: Erase firmware
-> Ensure the device is in firmware upload mode.
-> Erase the complete flash memory holding the firmware with the following command:
-> 
-> esptool.py --port COM5 erase_flash

But it does'nt work with the -> esptool.exe <- so as in the give information!

The tool i used is to find in the Arduino IDE package. In my case under:
-> C:\arduino-1.8.5\portable\packages\esp8266\tools\esptool\0.4.13

--------------------------------------------------------
Open the cmd.exe as administrator, goto to your folder
where you can find your esptool and then type: esptool -h then use 'Enter'

Here is a short list of commands:

esptool v0.4.13 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
ESP8266/ESP32 build and upload helper tool
Maintained by Ivan Grokhotkov: https://github.com/igrr/esptool-ck

The program interprets arguments given on the command line, and in the order
they are given.

-cp <device>
    Select the serial port device to use for communicating with the ESP.
    Default is /dev/ttyUSB0 on Linux, COM1 on Windows, /dev/tty.usbserial on Mac OS.

-cb <baudrate>
    Select the baudrate to use, default is 115200.

-ce
    Erase flash.

Commands tested and they are working 100% (COM18 in my case, yours can be different):
-> esptool -cp COM18 -cb 19200 -ce
-> esptool -cp COM18 -cb 115200 -ce

Possible Theo can fix the issue, Thank You.

**Comment by ascillato** [comment]
Hi

esptool is different than esptool.py explained in the wiki. 

It is good to add also this information to the wiki. 

Thanks

**Comment by arendst** [comment]
Pls do NOT updage the esptool info in the wiki.

There  is apples and pears, both fruit but...

The esptool from the wiki is the original tool as provided from the espressif github. The one noticed here is a stripped down version used by the arduino ide. The latter is NOT to be used as documented in the wiki.

**Comment by mike2nl** [comment]
arendst,
Thanks for the information and it's good to know that it is a stripped down version.
Ok will take a deeeeeeper look in it ;-). I mean the phyton version.
