### ISSUE TITLE
Sonoff Touch as a trigger

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#325]
Hello,

Can we use sonoff touch wall button as a button trigger for home automation and not only for operating the switch that the hardware is on?

Thank you.

**Comment by davidelang** [comment]
yes, look at buttontopic if you want it to send a command rather than switch the 
local hardware.
k

**Comment by ageorgios** [comment]
can it be done on a S20 Socket Module also?
where is the buttontopic configuration? is it available on the web interface?

**Comment by davidelang** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

it can be entered on the web console, I would have to look through all the 
configuration options to see if it's in another menu as well.

this can apply to the button on any sonoff device.

**Comment by davidelang** [comment]
closing this issue as it seems the discussion has wound down. please re-open if you still have a problem
