### ISSUE TITLE
HTTP OTA Update Connection Refused

### ISSUE THREAD

**Issue by MaxBec** [arendst/Sonoff-Tasmota#3251]
Hey guys,

I tried to setup the flask WebServer as described here [(](https://github.com/arendst/Sonoff-Tasmota/wiki/Python-HTTP-OTA-Server). The server is running and I can access the bin file via any browser in my network. But when it comes to upgrade 1 on the spinoffs, I only get the message: "Connection Refused"

Any idea what I am doing wrong?

**Comment by Chopin85** [comment]
Same Problem.

**Comment by ascillato** [comment]
Hi, please check https://github.com/arendst/Sonoff-Tasmota/issues/3289. Thanks

**Comment by ascillato2** [comment]
Hi,

Closing this issue as there is no feedback. Ask to reopen this issue if you need it. Thanks
