### ISSUE TITLE
sOnOff SC Tempeperature and Hmuidity issue

### ISSUE THREAD

**Issue by mike2nl** [arendst/Sonoff-Tasmota#3259]
..

**Comment by curzon01** [comment]
You can still use GPIO2 for sensors if you disable the serial logging

**Comment by mike2nl** [comment]
curzon01,
that's right but not the way of working. |But forget i close and do my own work in the future.
Thanks and goby tasmota.

**Comment by ascillato2** [comment]
Issue deleted by its author (??) Closing...
