### ISSUE TITLE
Multiple DS18B20 in Domoticz

### ISSUE THREAD

**Issue by lkhaskjdhlkashd** [arendst/Sonoff-Tasmota#326]
Hi!

First off all, Great work on the Sonoffs!

I wonder if it is possible to have 2 DS18B20 sensors on 1 Sonoff added in Domoticz.
1 Works perfectly, but when i connect another sensor parallel to the first on, it shows up on the webpage and in the log file, but i cant find a way to add the second sensor in Domoticz..

Greetings
-Ikhas

**Comment by davidelang** [comment]
that sounds like a Domoticz issue. the tasmota firmware sends all the sensor output in one json message, so your home automation software would need to look for the second temp sensor.

I'm going to go ahead and close this as it doesn't look like a tasmota issue. If you disagree please re-open the issue (and you may want to update the wiki documentation for Domoticz when you figure this out)

**Comment by Bodzio122333** [comment]
Hello,
I connected two ds18b20 to Wamos D1 mini but I see one idx temperature in Configuration Domiticz menu. So module send one temprature to Domoticz. Please give me information how add two ds18b20 to domoticz.

![image](https://user-images.githubusercontent.com/21276867/30296243-c860539c-9743-11e7-90b8-6f43998ee46f.png)
![image](https://user-images.githubusercontent.com/21276867/30296261-e2e36cc2-9743-11e7-91e5-2be14263e0bc.png)
