### ISSUE TITLE
SOnOff-SC, friendly name missing

### ISSUE THREAD

**Issue by mike2nl** [arendst/Sonoff-Tasmota#3260]
...

**Comment by ascillato** [comment]
If you don't have any relay or output defined, you will not have a friendly name to be used by Alexa u other.

Hostname is different than friendly name. The first one is the wifi name of the device, the second one is the name of the Output defined.

No output, no friendly name

**Comment by mike2nl** [comment]
I know that because i engineer networks in HighSpeed EthernetPowerLink EPL.
So there is something missing in the code.
I had taken a deep look into the code from tasmota and found serveral places where 
changings can be done to fix it.

**Comment by reloxx13** [comment]
again:

`If you don't have any relay or output defined, you will not have a friendly name to be used by Alexa`

show us your device config page with a relay set or confirm that you set a relay, saved, waited for restart and there is still no friendly name input.

**Comment by mike2nl** [comment]
relox,
i have one output to switch the green LED near the power USB connector.
In my other post you can find it think.
I can swicht also the extra LED connector on and off.
Is that output enough?
I'm not a beginner in coding and must read unknown code too on daily base.

A friendly name is one part but i will discusse that not right here because it's not the right place.
I have shown something and when Theo say no, no stop for me i code it and can publish the code. Thats it.

**Comment by mike2nl** [comment]
ascilloato,
it was no my intention to do so, really. I understand the way of working in these types of groups and i'm happy when people are willing to help. I help where i can and that a lot when i look in Android and industrial coding.

And i'm more then happy that you had found it ;-). THANK YOU

I hope we could clear it up because i wish to work a longer time with tasmota i had tested many other distributions around sonoff and tasmota is one of the best, when not the best so far i have seen.

**Comment by mike2nl** [comment]
ascilloato,
to be honest: 
i'm working for many years now here on github for posting and addtions to many different wiki's,
but never ever i had done a PR (PullRequest). I hope i get it otherwise i will call for help.

Solution is here quick and slappy ;-), because i have not much time over these weeks.
Tools:
- Notepad++

- changes in file:
 -> xdrv_02_webserver.ino

- search for: 
-> void HandleInformation()
-> in line: 1213

- search for: 
-> if (SONOFF_IFAN02 == Settings.module) { maxfn = 1; }
-> in line: 1244

- action: set this line in comment by adding two slashes in front of the line '//'

- action: add a new line and fill it with: 
-> if ((SONOFF_IFAN02 == Settings.module) || (SONOFF_SC == Settings.module)) { maxfn = 1; }
-> in line 1245

- verrify it
- compile and upload
- test it

Figure 1:
![friendlyname sc ok](https://user-images.githubusercontent.com/5562918/42925373-42ffa36c-8b2e-11e8-83f7-008497d51f83.PNG)

Next step the PR, hope it works.

What would very nice if one or two users can do the same to get some feedback if it's working
for them too.

**Comment by ascillato2** [comment]
Issue deleted by its author (??) Closing...
