### ISSUE TITLE
Anyone compiling source from command line on Linux ?

### ISSUE THREAD

**Issue by andrethomas** [arendst/Sonoff-Tasmota#3261]
**Have you look for this feature in other issues and in the wiki?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Whats the best way to build from the command line on Linux without using ide

**Describe alternatives you've considered**
Manual compilation with different user_config, but its a pain

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by andrethomas** [comment]
Actually forgot I found this - will try it first 📦 

https://www.anginf.de/?p=600

**Comment by andrethomas** [comment]
Compiles, but cannot figure out how to make it create a binary

**Comment by andrethomas** [comment]
Perhaps for clarity - I want to see the viability of creating a web-based firmware generator that allows selection of user_config parameters and then compiles a custom firmware binary for yourself.

**Comment by andrethomas** [comment]
Something like this https://nodemcu-build.com/ but specifically for Tasmota firmware

**Comment by reloxx13** [comment]
"should" be easy woth platformio cli

http://docs.platformio.org/en/latest/quickstart.html#process-project

**Comment by hipek** [comment]
Hi,

I'm using debian stable (9.5) to compile firmware. Here are steps to prepare env and use it from shell:
1) Install python as root
`apt update && apt install python python-pip`
it will install python2.7 (platformio doesn't work with python3.x yet)
2) then as normal user (not root) install platformio
`pip2 install -U platformio`
platformio command should be available here `ls ~/.local/bin/platformio`
3) go to tasmota main dir (the one with `platformio.ini` file) and execute
`~/.local/bin/platformio run`
after successful compilation firmware should be available here: `ls .pioenvs/sonoff*/firmware.bin`

Optional step: you can update platformio with command `~/.local/bin/platformio platform update`

Maybe it will help someone :)
Enjoy!

**Comment by andrethomas** [comment]
Thanks @hipek seems to work.
