### ISSUE TITLE
Many relays and switches

### ISSUE THREAD

**Issue by cody82** [arendst/Sonoff-Tasmota#3263]
I am trying to use Tasmota on a NodeMcu 1.0 with 4 relays and 4 switches.

The 4 relays work, but I can only get 3 switches to work.
Those pins dont seem to work as switches:
GPIO 1, 3, 14, 16
The LED blinks at least when pressing the GPIO16 switch, but the relay does not switch.
I am using switchmode 4 on all switches.

Is this normal behaviour or am I doing something wrong?
Can I get 4 relays and 4 switches working with that hardware?

My configuration:
![tasmota](https://user-images.githubusercontent.com/363688/42905566-bbbd9486-8ad8-11e8-92d3-5665e1a66a1a.png)

**Comment by Frogmore42** [comment]
https://tttapa.github.io/ESP8266/Chap04%20-%20Microcontroller.html

Don't use GPIO: 0, 1, 2, 6-11, 15, 16 if you can avoid it. 3 is RX, so best to avoid also. That leaves 4, 5, 12, 13, 14 that don't have constraints. The others can be used, but you have to mind the constraints.

**Comment by ascillato** [comment]
Very useful information. Added to the wiki at: https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs#gpio-overview

**Comment by cody82** [comment]
So 14 should work, but it does not for me.
15 should work with external pull up.
16 should work with pull up(?) or with inverse logic, pulling it high on button press.
Will try tomorrow.

**Comment by cody82** [comment]
With an external pull up, the switch on GPIO16 works. Thank you!

**Comment by effelle** [comment]
@cody82 I'm configuring the same setup, would you gently tell me what gpios have you used to configure the 4 relays and what gpios did you use as switches on generic module?  Thanks!

**Comment by cody82** [comment]
@effelle It is the same configuration as in my first posting.

**Comment by effelle** [comment]
@cody82 : Already solved, but with another order since on my NodeMCU seems I can't use GPIO16 as a switch even with a pull up. I don't remember my working configuration, made without any pull-up/down, but I'll post it as soon as I back home (for the sake of knowledge).

**Comment by Frogmore42** [comment]
When you add a pull-up to a built-in pull down, you get a middle.  This a generally not good idea.  But, that is probably not the issue you are seeing.
This site says
https://nodemcu.readthedocs.io/en/master/en/modules/gpio/
You can't use GPIO16 as an interrupt source.  I haven't looked at the code recently, but I would not use GPIO16 as an input.  But, it would probably work fine as an output to control a relay.

**Comment by effelle** [comment]
@Frogmore42: yes, I'm  aware and I'm using GPIO16 just for relay.
