### ISSUE TITLE
MQTT broker mDNS hostname not resolved

### ISSUE THREAD

**Issue by gfrancesco** [arendst/Sonoff-Tasmota#3275]
Hi,
I'm using a Sonoff S26 plug with 6.1.1 fw and the embedded MQTT broker in Home Assistant on a Rapberry Pi.

In the MQTT configuration I want to use the local hostname of the HA broker **hassio.local** instead of the local IP address, but the plug fails to connect. If I replace **hassio.local** with the local IP it connects without problems.

I can connect to the broker using the **hassio.local** hostname from my laptop using the MQTTfx standalone client. I can also connect to the HA webinterface from my browser using the same hostname.

Thanks

**Comment by andyfitter** [comment]
I’ve never managed to get hostnames to work in the mqtt config either. Sadly I’ve always had to hard code IP addresses.

**Comment by Jason2866** [comment]
I use the Static Host Service in my router (hassio.local = xxx.xxx.xxx.xxx IP of Broker)
Use command: Mqtthost hassio.local
So you have only 1 hardcoded IP Adress and you dont need mDNS

**Comment by arendst** [comment]
I don't use .local as alternative for static addresses. In fact I never used mDNS as I use a dnsmasq server providing decent name resolution for my devices.

So I probably have to say it was never meant to work from device outward. It should work from outside to device but then again I've never used it.

**Comment by gfrancesco** [comment]
Thanks for clarifying the issue, I will update the wiki accordingly in the next days.

**Comment by xescure** [comment]
Are there plans to enable mDNS addresses as MQTT hosts? It would simplify my installation in multiple homes by a lot

**Comment by Jason2866** [comment]
No, we are discussing now and than to drop mDNS support completely.
There will be no additional feature for mDNS added in Tasmota

**Comment by gerritv** [comment]
My solution is to run avahi in a container. It publishes _mqtt as mqtt.local. Tasmota happily finds that by leaving the Host field of MQTT config blank. Edit the files in avahi/services to set up _mqtt (and remove _ssh). If all your services are on one host then this one mqtt.local will work for all the needed ports such as :8123 for HomeAssistant. Tasmota looks for mqtt.local for the MQTT server if the Host filed is blank. (Once connected you will see an IP address but officially the field is still empty.)
```
mDNS:
  # This container exists to provide an mDNS target for mqtt.local to the Tasmota's
    image: solidnerd/avahi
    container_name: mDNS
    hostname: mqtt
    network_mode: host
    volumes:
    - ./avahi:/etc/avahi:ro
```

You put the avahi configs local, and map into the docker container. See 

> https://github.com/solidnerd/docker-avahi

for details.

This avoids me setting up a DNS server (YetAnotherThingToManage), and lets me move the HomeAssistant stuff to different IP's without having to visit every gadget. This is the goal of zeroconf/mDNS.

Gerrit
