### ISSUE TITLE
Sonoff 4ch Pro r2 PowerOnState/PowerRetain

### ISSUE THREAD

**Issue by Thorhammerk** [arendst/Sonoff-Tasmota#3276]
Hi,
I'm using a Sonoff 4ch Pro r2 with FW 6.1.1. When i restart the sonoff, relay1("POWER1":"ON") is always switched ON. So i tried different combinations with the PowerOnState and the PowerRetain without luck.
13:19:13 MQT: sonoff/ABBeregnung/stat/RESULT = {"PowerOnState":0}
13:19:34 MQT: sonoff/ABBeregnung/stat/RESULT = {"PowerRetain":"ON"}

So the goal is when the Sonoff restarts, all relays must be OFF.

THX

**Comment by ascillato** [comment]
Hi,

Please, be kind and provide all the information of the troubleshooting template, so we can help you with your issue.

Thanks.

**Comment by Thorhammerk** [comment]
Hi,

sure no problem.

15:12:11 CMD: status 0
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS = {"Status":{"Module":23,"FriendlyName":["ABBeregnungMGV1","ABBeregnungMGV2","ABBeregnungMGV3","ABBeregnungMGV4"],"Topic":"ABBeregnung","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":1}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin","RestartReason":"Software/System restart","Uptime":"0T01:48:37","StartupUTC":"2018-07-20T12:23:34","Sleep":0,"BootCount":22,"SaveCount":534,"SaveAddress":"F5000"}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS2 = {"StatusFWR":{"Version":"6.1.1","BuildDateTime":"2018-07-14T15:57:03","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["system.bifroest.wlan","indebuurt2"],"TelePeriod":300,"SetOption":["00002029","55818000"]}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS4 = {"StatusMEM":{"ProgramSize":535,"Free":468,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","0C000000","23B6179E","00000000"]}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS5 = {"StatusNET":{"Hostname":"ABBeregnung","IPAddress":"192.168.178.100","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"60:31:97:A3:42:67","Webserver":2,"WifiConfig":3}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.178.87","MqttPort":1883,"MqttClientMask":"ABBeregnung","MqttClient":"ABBeregnung","MqttUser":"sonoffmqtt","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS7 = {"StatusTIM":{"UTC":"Fri Jul 20 14:12:11 2018","Local":"Fri Jul 20 15:12:11 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:08","Sunset":"20:44"}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS10 = {"StatusSNS":{"Time":"2018-07-20T15:12:11"}}
15:12:11 MQT: sonoff/ABBeregnung/stat/STATUS11 = {"StatusSTS":{"Time":"2018-07-20T15:12:11","Uptime":"0T01:48:37","Vcc":3.178,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"system.bifroest.wlan","RSSI":54,"APMac":"42:2A:A8:67:89:8A"}}}

Thanks

**Comment by ascillato** [comment]
Hi,

Using your Status 0

```
{"Status":{"Module":23,"FriendlyName":["ABBeregnungMGV1","ABBeregnungMGV2","ABBeregnungMGV3","ABBeregnungMGV4"],"Topic":"ABBeregnung","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":1},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin","RestartReason":"Software/System restart","Uptime":"0T01:48:37","StartupUTC":"2018-07-20T12:23:34","Sleep":0,"BootCount":22,"SaveCount":534,"SaveAddress":"F5000"},"StatusFWR":{"Version":"6.1.1","BuildDateTime":"2018-07-14T15:57:03","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["system.bifroest.wlan","indebuurt2"],"TelePeriod":300,"SetOption":["00002029","55818000"]},"StatusMEM":{"ProgramSize":535,"Free":468,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","0C000000","23B6179E","00000000"]},"StatusNET":{"Hostname":"ABBeregnung","IPAddress":"192.168.178.100","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"60:31:97:A3:42:67","Webserver":2,"WifiConfig":3},"StatusMQT":{"MqttHost":"192.168.178.87","MqttPort":1883,"MqttClientMask":"ABBeregnung","MqttClient":"ABBeregnung","MqttUser":"sonoffmqtt","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Fri Jul 20 14:12:11 2018","Local":"Fri Jul 20 15:12:11 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:08","Sunset":"20:44"},"StatusSNS":{"Time":"2018-07-20T15:12:11"},"StatusSTS":{"Time":"2018-07-20T15:12:11","Uptime":"0T01:48:37","Vcc":3.178,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"system.bifroest.wlan","RSSI":54,"APMac":"42:2A:A8:67:89:8A"}}}
```

with decode-status.py, gives the output:

```
Decoding information for device ABBeregnungMGV1 from status report taken at 2018-07-20T15:12:11

Options
   0 (ON ) Save power state and use after restart
   1 (OFF) Restrict button actions to single, double and hold
   2 (OFF) Show value units in JSON messages
   3 (ON ) MQTT
   4 (OFF) Respond as Command topic instead of RESULT
   5 (ON ) MQTT retain on Power
   6 (OFF) MQTT retain on Button
   7 (OFF) MQTT retain on Switch
   8 (OFF) Convert temperature to Fahrenheit
   9 (OFF) MQTT retain on Sensor
  10 (OFF) MQTT retained LWT to OFFLINE when topic changes
  11 (OFF) Swap Single and Double press Button
  12 (OFF) Do not use flash page rotate
  13 (ON ) Button single press only
  14 (OFF) Power interlock mode
  15 (OFF) Do not allow PWM control
  16 (OFF) Reverse clock
  17 (OFF) Allow entry of decimal color values
  18 (OFF) CO2 color to light signal
  19 (OFF) HASS discovery
  20 (OFF) Do not control Power with Dimmer
  21 (OFF) Energy monitoring while powered off
  22 (OFF) MQTT serial
  23 (OFF) Rules until 5.14.0b
  24 (OFF) Rules once mode until 5.14.0b
  25 (OFF) KNX
  26 (OFF) Use Power device index on single relay devices
  27 (OFF) KNX enhancement
  28 (OFF) RF receive decimal
  29 (OFF) IR receive decimal
  30 (OFF) Enforce HASS light group

Features
  Language LCID = 2057
  MQTT_HOST_DISCOVERY
  MQTT_PUBSUBCLIENT
  PIO_FRAMEWORK_ARDUINO_LWIP_HIGHER_BANDWIDTH
  USE_ADC_VCC
  USE_ARILUX_RF
  USE_BH1750
  USE_BMP
  USE_DHT
  USE_DISCOVERY
  USE_DOMOTICZ
  USE_DS18B20
  USE_EMULATION
  USE_ENERGY_SENSOR
  USE_HOME_ASSISTANT
  USE_HTU
  USE_I2C
  USE_IR_RECEIVE
  USE_IR_REMOTE
  USE_LM75AD
  USE_MHZ19
  USE_NOVA_SDS
  USE_PMS5003
  USE_PZEM004T
  USE_RULES
  USE_SENSEAIR
  USE_SERIAL_BRIDGE
  USE_SGP30
  USE_SHT
  USE_SHT3X
  USE_SR04
  USE_SUNRISE
  USE_TIMERS
  USE_TIMERS_WEB
  USE_WEBSERVER
  USE_WS2812
  VTABLES_IN_FLASH
  WEBSERVER_ADVERTISE
```

So, you are saving the state of your outputs.

Please, use the following in the console:

```
PowerOnState 0
PowerRetain 0
SetOption0 0
```

And delete all retaing messages on your MQTT Broker as explained in https://github.com/arendst/Sonoff-Tasmota/wiki/PowerOnState-Configuration

All that should work. If not, please show your console log output at startup.

**Comment by Thorhammerk** [comment]
Hi,

ok, its not working. i set

```
PowerOnState 0
PowerRetain 0
SetOption0 0
```
deleted the whole mosquitto.db but still after restart as you can see {"POWER1":"ON"}

Here is the startup log
```
00:00:00 Project sonoff ABBeregnungMGV1 (Topic ABBeregnung, Fallback ABBeregnung, GroupTopic sonoffs) Version 6.1.1-2_3_0
00:00:00 WIF: Connecting to AP1 system.bifroest.wlan in mode 11N as ABBeregnung...
00:00:04 RSL: sonoff/ABBeregnung/stat/RESULT = {"POWER1":"ON"}
00:00:04 RSL: sonoff/ABBeregnung/stat/POWER1 = ON
00:00:04 RSL: sonoff/ABBeregnung/stat/RESULT = {"POWER3":"ON"}
00:00:04 RSL: sonoff/ABBeregnung/stat/POWER3 = ON
00:00:04 RSL: sonoff/ABBeregnung/stat/RESULT = {"POWER3":"OFF"}
00:00:04 RSL: sonoff/ABBeregnung/stat/POWER3 = OFF
00:00:06 WIF: Connected
00:00:06 DNS: Initialized
00:00:06 HTP: Web server active on ABBeregnung.local with IP address 192.168.178.100
00:00:06 MQT: Attempting connection...
10:47:48 MQT: Connected
10:47:48 MQT: sonoff/ABBeregnung/tele/LWT = Online (retained)
10:47:48 MQT: sonoff/ABBeregnung/cmnd/POWER = 
10:47:48 MQT: sonoff/ABBeregnung/tele/INFO1 = {"Module":"Sonoff 4CH Pro","Version":"6.1.1","FallbackTopic":"ABBeregnung","GroupTopic":"sonoffs"}
10:47:48 MQT: sonoff/ABBeregnung/tele/INFO2 = {"WebServerMode":"Admin","Hostname":"ABBeregnung","IPAddress":"192.168.178.100"}
10:47:48 MQT: sonoff/ABBeregnung/tele/INFO3 = {"RestartReason":"Software/System restart"}
10:47:49 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER1":"ON"}
10:47:49 MQT: sonoff/ABBeregnung/stat/POWER1 = ON
10:47:49 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER2":"OFF"}
10:47:49 MQT: sonoff/ABBeregnung/stat/POWER2 = OFF
10:47:49 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER3":"OFF"}
10:47:49 MQT: sonoff/ABBeregnung/stat/POWER3 = OFF
10:47:49 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER4":"OFF"}
10:47:49 MQT: sonoff/ABBeregnung/stat/POWER4 = OFF
10:47:55 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER1":"OFF"}
10:47:55 MQT: sonoff/ABBeregnung/stat/POWER1 = OFF
10:47:56 MQT: sonoff/ABBeregnung/tele/STATE = {"Time":"2018-07-21T10:47:56","Uptime":"0T00:00:15","Vcc":3.178,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"system.bifroest.wlan","RSSI":36,"APMac":"42:2A:A8:67:89:8A"}}
```

**Comment by ascillato** [comment]
Ok,

Please, try the command `weblog 4`, restart and post again the output of the console. With that, Tasmota should say what is the source of that power on.

**Comment by Thorhammerk** [comment]
Hi,

ok, here with ```weblog 4```. Not sure if it's important...the Sonoff is in ```interlock mode``` 

```
00:00:00 CFG: Loaded from flash at F5, Count 542
00:00:00 APP: Boot Count 28
00:00:00 Project sonoff ABBeregnungMGV1 (Topic ABBeregnung, Fallback ABBeregnung, GroupTopic sonoffs) Version 6.1.1-2_3_0
00:00:00 CFG: Saved to flash at F4, Count 543, Bytes 3584
00:00:00 WIF: Checking connection...
00:00:00 WIF: Attempting connection...
00:00:00 WIF: Patch issue 2186
00:00:00 WIF: Connecting to AP1 system.bifroest.wlan in mode 11N as ABBeregnung...
00:00:01 WIF: Checking connection...
00:00:01 WIF: Attempting connection...
00:00:02 WIF: Checking connection...
00:00:02 WIF: Attempting connection...
00:00:03 WIF: Checking connection...
00:00:03 WIF: Attempting connection...
00:00:04 APP: Button1 level 1-0
00:00:04 SRC: Button
00:00:04 RSL: sonoff/ABBeregnung/stat/RESULT = {"POWER1":"ON"}
00:00:04 RSL: sonoff/ABBeregnung/stat/POWER1 = ON
00:00:04 APP: Button3 level 1-0
00:00:04 SRC: Button
00:00:04 RSL: sonoff/ABBeregnung/stat/RESULT = {"POWER3":"ON"}
00:00:04 RSL: sonoff/ABBeregnung/stat/POWER3 = ON
00:00:04 APP: Button1 level 0-1
00:00:04 APP: Button1 level 1-0
00:00:04 SRC: Button
00:00:04 RSL: sonoff/ABBeregnung/stat/RESULT = {"POWER1":"OFF"}
00:00:04 RSL: sonoff/ABBeregnung/stat/POWER1 = OFF
00:00:04 WIF: Checking connection...
00:00:04 WIF: Attempting connection...
00:00:05 WIF: Checking connection...
00:00:05 WIF: Connected
00:00:05 DNS: Initialized
00:00:05 HTP: Web server active on ABBeregnung.local with IP address 192.168.178.100
00:00:06 APP: (UTC) Sat Jul 21 12:16:17 2018, (DST) Sun Mar 25 02:00:00 2018, (STD) Sun Oct 28 03:00:00 2018
13:16:18 MQT: Attempting connection...
13:16:18 MQT: Connected
13:16:18 MQT: sonoff/ABBeregnung/tele/LWT = Online (retained)
13:16:18 MQT: sonoff/ABBeregnung/cmnd/POWER = 
13:16:18 MQT: Subscribe to sonoff/ABBeregnung/cmnd/#
13:16:18 MQT: Subscribe to sonoff/sonoffs/cmnd/#
13:16:18 MQT: Subscribe to cmnd/ABBeregnung/#
13:16:18 MQT: sonoff/ABBeregnung/tele/INFO1 = {"Module":"Sonoff 4CH Pro","Version":"6.1.1","FallbackTopic":"ABBeregnung","GroupTopic":"sonoffs"}
13:16:18 MQT: sonoff/ABBeregnung/tele/INFO2 = {"WebServerMode":"Admin","Hostname":"ABBeregnung","IPAddress":"192.168.178.100"}
13:16:18 MQT: sonoff/ABBeregnung/tele/INFO3 = {"RestartReason":"Software/System restart"}
13:16:19 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER1":"OFF"}
13:16:19 MQT: sonoff/ABBeregnung/stat/POWER1 = OFF
13:16:19 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER2":"OFF"}
13:16:19 MQT: sonoff/ABBeregnung/stat/POWER2 = OFF
13:16:19 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER3":"ON"}
13:16:19 MQT: sonoff/ABBeregnung/stat/POWER3 = ON
13:16:19 MQT: sonoff/ABBeregnung/stat/RESULT = {"POWER4":"OFF"}
13:16:19 MQT: sonoff/ABBeregnung/stat/POWER4 = OFF
13:16:26 MQT: sonoff/ABBeregnung/tele/STATE = {"Time":"2018-07-21T13:16:26","Uptime":"0T00:00:15","Vcc":3.178,"POWER1":"OFF","POWER2":"OFF","POWER3":"ON","POWER4":"OFF","Wifi":{"AP":1,"SSId":"system.bifroest.wlan","RSSI":52,"APMac":"82:2A:A8:97:89:8A"}}
13:16:37 WIF: Checking connection...
13:16:37 WIF: Connected
13:16:57 WIF: Checking connection...
13:16:57 WIF: Connected
```

**Comment by ascillato** [comment]
In the log shows that your buttons are pressed. That is why it turns on. Just that.

See if those buttons are stuck or disconnected.

**Comment by Thorhammerk** [comment]
hi,

ok, i´ve checked all the buttons..they seems to be fine.
I´m away for a while and then i´ll erase the flash and start from the beginning.

I´ll let you know then if it works
@ascillato, big thanks for your kind support

**Comment by ascillato2** [comment]
Hi,

Closing this issue as there is no feedback. Ask to reopen this issue if you need it. Thanks

**Comment by Thorhammerk** [comment]
hi,

I only want to give the feedback.....somewhat delayed ;-)
I was able to use esptool to completly erase the flash. Then upload the firmware again . No relays on after reboot :-)
best regards

**Comment by netmaster01** [comment]
Hi. i am having this exact bug. i captured this event. below de logs

00:00:00 CFG: Saved to flash at F6, Count 2262, Bytes 2560
00:00:00 WIF: Checking connection...
00:00:00 WIF: Attempting connection...
00:00:00 WIF: Connecting to AP1 NetXtreme in mode 11N as sonoffgg1-6488...
00:00:01 WIF: Checking connection...
00:00:01 WIF: Attempting connection...
00:00:02 WIF: Checking connection...
00:00:02 WIF: Attempting connection...
00:00:04 WIF: Checking connection...
00:00:04 WIF: Attempting connection...
00:00:04 APP: Button2 level 1-0
00:00:04 RSL: stat/sonoffgg1/RESULT = {"POWER2":"ON"}
00:00:04 RSL: stat/sonoffgg1/POWER2 = ON
00:00:04 APP: Button4 level 1-0
00:00:04 RSL: stat/sonoffgg1/RESULT = {"POWER4":"ON"}
00:00:04 RSL: stat/sonoffgg1/POWER4 = ON
00:00:04 APP: (UTC) Sun Dec 02 04:14:59 2018, (DST) Sun Mar 25 02:00:00 2018, (STD) Sun Oct 28 03:00:00 2018
05:15:00 WIF: Checking connection...
05:15:00 WIF: Connected
05:15:00 DNS: Initialized
05:15:00 HTP: Web server active on sonoffgg1-6488.local with IP address 10.0.1.29
05:15:00 APP: Button2 level 0-1
05:15:00 RSL: stat/sonoffgg1/RESULT = {"POWER2":"OFF"}
05:15:00 RSL: stat/sonoffgg1/POWER2 = OFF
05:15:00 APP: Button4 level 0-1
05:15:00 RSL: stat/sonoffgg1/RESULT = {"POWER4":"OFF"}
05:15:00 RSL: stat/sonoffgg1/POWER4 = OFF
05:15:01 MQT: Attempting connection...
05:15:06 MQT: Connect failed to 10.0.1.10:1883, rc -2. Retry in 10 sec
05:15:17 MQT: Attempting connection...
05:15:17 MQT: Connected
05:15:17 MQT: tele/sonoffgg1/LWT = Online (retained)
05:15:17 MQT: cmnd/sonoffgg1/POWER = 
05:15:17 MQT: Subscribe to cmnd/sonoffgg1/#
05:15:17 MQT: Subscribe to cmnd/sonoffs/#
05:15:17 MQT: Subscribe to cmnd/DVES_A35958/#
05:15:17 MQT: tele/sonoffgg1/INFO1 = {"Module":"Sonoff 4CH Pro","Version":"5.13.1b","FallbackTopic":"DVES_A35958","GroupTopic":"sonoffs"}
05:15:17 MQT: tele/sonoffgg1/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoffgg1-6488","IPAddress":"10.0.1.29"}
05:15:17 MQT: tele/sonoffgg1/INFO3 = {"RestartReason":"Fatal exception:3 flag:2 (EXCEPTION) epc1:0x40246923 epc2:0x00000000 epc3:0x00000000 excvaddr:0x40000002 depc:0x00000000"}
05:15:18 MQT: stat/sonoffgg1/RESULT = {"POWER1":"OFF"}
05:15:18 MQT: stat/sonoffgg1/POWER1 = OFF
05:15:18 MQT: stat/sonoffgg1/RESULT = {"POWER2":"OFF"}
05:15:18 MQT: stat/sonoffgg1/POWER2 = OFF
05:15:18 MQT: stat/sonoffgg1/RESULT = {"POWER3":"OFF"}
05:15:18 MQT: stat/sonoffgg1/POWER3 = OFF
05:15:18 MQT: stat/sonoffgg1/RESULT = {"POWER4":"OFF"}
05:15:18 MQT: stat/sonoffgg1/POWER4 = OFF
05:15:25 WIF: Checking connection...
05:15:25 WIF: Connected
05:15:25 MQT: tele/sonoffgg1/STATE = {"Time":"2018-12-02T05:15:25","Uptime":"0T00:00:30","Vcc":3.486,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"NetXtreme","RSSI":100,"APMac":"14:CC:20:8E:C9:E6"}}
05:15:42 APP: Button1 level 1-0
05:15:42 MQT: stat/sonoffgg1/RESULT = {"POWER1":"ON"}
05:15:42 MQT: stat/sonoffgg1/POWER1 = ON
05:15:43 APP: Button1 level 0-1
05:15:45 WIF: Checking connection...
05:15:45 WIF: Connected
05:15:46 APP: Button4 level 1-0
05:15:46 MQT: stat/sonoffgg1/RESULT = {"POWER4":"ON"}
05:15:46 MQT: stat/sonoffgg1/POWER4 = ON
05:15:46 APP: Button4 level 0-1
05:15:47 APP: Button4 level 1-0
05:15:47 MQT: stat/sonoffgg1/RESULT = {"POWER4":"OFF"}
05:15:47 MQT: stat/sonoffgg1/POWER4 = OFF
05:15:48 APP: Button1 level 1-0
05:15:48 MQT: stat/sonoffgg1/RESULT = {"POWER1":"OFF"}
05:15:48 MQT: stat/sonoffgg1/POWER1 = OFF
05:15:48 APP: Button1 level 0-1
05:16:05 WIF: Checking connection...
05:16:05 WIF: Connected
05:16:25 WIF: Checking connection...
05:16:25 WIF: Connected
05:16:45 WIF: Checking connection...
05:16:45 WIF: Connected
05:17:05 WIF: Checking connection...
05:17:05 WIF: Connected
05:17:25 WIF: Checking connection...
05:17:25 WIF: Connected
05:17:45 WIF: Checking connection...
05:17:45 WIF: Connected
05:17:45 HTP: Console
05:17:58 HTP: Main Menu
05:17:59 HTP: Console
