### ISSUE TITLE
Wifi not working correctly on Electrodragon modules since Version 6

### ISSUE THREAD

**Issue by canis-ferrin** [arendst/Sonoff-Tasmota#3282]
Tested with Electrodragon SPDT module. 
Flasched ESPEasy: working.
Flasched Tasmota 5.12.0c: working.
Flashed Tasmota sonoff6.1.1c: Wifi only working for short times, mostly no ping answer.
Ping successful at approx. 10%

**Comment by ascillato** [comment]
Insufficient information to help you. Please, complete all the troubleshooting template

**Comment by canis-ferrin** [comment]
Where I find the all the troubleshooting template?

I found this:
"By releasing the firmware 5.12, the new ExpressIf library 2.4.0 is being used by default.
"
Possibly it is not working with the Electrodragon Boards.

**Comment by ascillato** [comment]
When you have clicked on new issue button, it shows you 3 options, bug report, feature request and troubleshooting. If you click on troubleshooting, you will have a template to complete some information that is very helpful for us.

Now you can copy and paste that, and complete all the information required. That will help us a lot.

**Comment by oriolism** [comment]
This wifi issue is affecting the sonoff basic too.

**Comment by Frogmore42** [comment]
If you want help, you really need to provide the requested information from the template.

Having said that, the WiFi in the underlying code, not Tasmota, has issues in some environments and on some devices.  You may be using a combination that is known to be frequently bad in which case switching to something that is known to be generally mostly okay would be good.  If you are already using that, your environment/device might be particularly sensitive to the issue.

**Comment by canis-ferrin** [comment]
This wifi issue is affecting the Wemos D1 mini (LOLIN) too.

**Comment by Frogmore42** [comment]
WiFi is provided by the underlying libraries, not Tasmota.  Core 2.3.0 has been providing the best results for most people, but it clearly doesn't work for everyone.  There have been some cases where some of the non English binaries have had issues.  It probably won't help, but you can try using the English one.

**Comment by ascillato** [comment]
Hi, please check https://github.com/arendst/Sonoff-Tasmota/issues/3289. Thanks

**Comment by canis-ferrin** [comment]
Problem is solved since Tasmota 6.1.1

**Comment by canis-ferrin** [comment]
but not completely, there are still several drops in WIFI connection
and bad ping times.

**Comment by ascillato2** [comment]
Hi,

please, share your `status 0` output

**Comment by ascillato2** [comment]
Hi,

Closing this issue as there is no feedback. Ask to reopen this issue if you need it. Thanks
