### ISSUE TITLE
How to upgrade tasmota Sonoff 5.12.x to latest version

### ISSUE THREAD

**Issue by NiekN** [arendst/Sonoff-Tasmota#3287]
i try to upgrade the software in a sonoff socket by firmware upgrade function
OTA Url
and  
Upgrade by file upload
 
both are not working 

![upgrade1](https://user-images.githubusercontent.com/32562791/43035932-a26d4e92-8cf7-11e8-933e-0e858b75556b.jpg)
![upgrade2](https://user-images.githubusercontent.com/32562791/43035933-a615008a-8cf7-11e8-94ce-d7a81e95ee6a.jpg)

**Comment by ascillato** [comment]
You need to use minimal first and then the full version you want.

See also the migration path. It is not direct.
