### ISSUE TITLE
Sonoff stop searching for Wi-Fi:

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#3294]
Every time my Internet get lost or My router gets off - I'm getting esp Wi-Fi for every device I have that anyone can login to it. How can I change it to have password to that configuration page or just set the Sonoff `OFF` and not search for Wi-Fi at all until u press sonoff manually? 
Thanks 💪🏾

**Comment by Frogmore42** [comment]
Read the wiki, search for commands
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#wifi

Wificonfig 5

Is probably what you want.

**Comment by ascillato2** [comment]
Hi,

If your question has been answered, please close this issue. Thanks :+1:

**Comment by ascillato2** [comment]
Hi,

Closing the issue. Please, if you still have problems, just give us some feedback and we can reopen your issue if you want. Thanks.
