### ISSUE TITLE
Sonoff bridge 433 Mhz with Tasmota and Node Red

### ISSUE THREAD

**Issue by foskolo** [arendst/Sonoff-Tasmota#3296]
Hi!

I flashed Tasmota on a Sonoff 433 Bridge and it works fine. I could learn some keys to switch lamps and this works in the Main menue of Tasmota.
Now I would like to integrate some buttons or switches in Node Red to send commands to the bridge to switch the lamps. I am learning Node Red and I don't know it very well so I need your help.

Do you have a simple flow for me with a button or a inject node to send (MQTT) a simple command to the bridge to switch on or off my lamps? The name of my sonoff bridge is simple "bridge".

When I press switch 1 ("ON") of the remote in the console I see for example:

08:14:39 MQT: tele/bridge/RESULT = {"RfReceived":{"Sync":10350, "Low":330, "High":1000, "Data":"15155F", "RfKey":"None"}}

How can I program this command in a button of Nodered?

Where can I found the meaning of "tele", "status" end other items for the Tasmota firmare? I found the commands of the bridge here: https://goo.gl/TaJRu9 but there are no examples so it is difficult for me to understand how use them.

Thank you!

**Comment by Jason2866** [comment]
Please read the wiki
https://github.com/arendst/Sonoff-Tasmota/wiki
If you dont understand you have to learn, there are tips in the wiki where to start.

**Comment by foskolo** [comment]
Hi Jason2866,

and thank you for your answer. 

I've read several Wikis and Websites/youtube vedeos and in NodeRed I can for example already get the messages from the Sonoff bridge when I push a button of the remote (through a MQTT node with topic "tele/bridge/RESULT"). This works.

But unfortunately I've not found the way to **send** back the commands to the Sonoff brigde to switch on or off the devices. I need oly the correct syntax to do it. (Using the parameters "Sync", "Low", "High", "Data").

If you have a link where I can found this, it would be nice. In the Wiki of Tasmota I don't find it.

thank you

**Comment by Jason2866** [comment]
Commands for the bridge
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#sonoff-rf-bridge-433
For the Home Automation Open Hab it looks like
Switch WohnFluter       "Wohnz. Fluter"         <light> (LR,gLight)     [ "Lighting" ] 
		{ mqtt=">[broker:cmnd/sonoff-8E8329/Backlog:command:ON:RfSync 11320; RfLow 360; RfHigh 1090; RfCode #150551],
                >[broker:cmnd/sonoff-8E8329/Backlog:command:OFF:RfSync 11320; RfLow 360; RfHigh 1090; RfCode #150554]" }
Here is backlog command used to send the commands RfSync, Rflow, Rfhigh and RfCode in one mqtt message.
Try to monitor you mqtt traffic for example with
https://mosquitto.org/man/mosquitto_sub-1.html

**Comment by foskolo** [comment]
Great Jason, thank you!

I'll try this. 

"Einen schönen Abend".

**Comment by Jason2866** [comment]
IF your poweroutlets use "Intertechno" code. Many in Germany sold ones do.
Your poweroutlets probably wont switch. Reason: The original firmware decodes the Intertechno code in most cases wrong.
Solution is there: Flash the alternative "Portisch" firmware for the EFM chip on the bridge.
All you need is included in Tasmota on github here :-)

**Comment by MatzeJoerling** [comment]
check out #2958

**Comment by ascillato2** [comment]
Hi,

Have you managed to solve your issue?

**Comment by haegar33** [comment]
You got to learn the corresponding rfkeys first. Best to do this is via the Sonoff Console on a web browser. Once learned you simply trigger the keys via MQTT like:

mosquitto_pub -t 'cmnd/sonoff/rfkey1' -m ''

when this is working you surely find a way to code this in Node-RED

**Comment by sarsw** [comment]
Did you resolve your issue?  Here's a trace of my rf receiving commands from my remote and then my subsequent node red backlog commands to try and get the sonoff rf (v2) to activate my switch. No good so far:

19:44:21 MQT: rf/tele/RESULT = {"RfReceived":{"Sync":13250,"Low":360,"High":1210,"Data":"541554","RfKey":"None"}}   on
19:44:24 MQT: rf/tele/RESULT = {"RfReceived":{"Sync":13300,"Low":350,"High":1190,"Data":"545557","RfKey":"None"}}   off

19:54:22 MQT: rf/stat/RESULT = {"RfSync":13300}
19:54:22 MQT: rf/stat/RESULT = {"RfLow":350}
19:54:23 MQT: rf/stat/RESULT = {"RfHigh":1190}
19:54:23 MQT: rf/stat/RESULT = {"RfCode":545557}

19:55:37 MQT: rf/stat/RESULT = {"RfSync":13250}
19:55:38 MQT: rf/stat/RESULT = {"RfLow":360}
19:55:38 MQT: rf/stat/RESULT = {"RfHigh":1210}
19:55:38 MQT: rf/stat/RESULT = {"RfCode":541554}

I'm running with the Portisch per my last entry here : https://github.com/arendst/Sonoff-Tasmota/issues/3025

For reference here's my node red flow for the off command:

[
    {
        "id": "963eb991.022ad8",
        "type": "inject",
        "z": "384d59f5.ef58c6",
        "name": "OFF",
        "topic": "",
        "payload": "rfsync 13300; rflow 350; rfhigh 1190; rfcode 545557",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 144.01739120483398,
        "y": 158.01042938232422,
        "wires": [
            [
                "1a0434a.5fcb8cb"
            ]
        ]
    },
    {
        "id": "1a0434a.5fcb8cb",
        "type": "mqtt out",
        "z": "384d59f5.ef58c6",
        "name": "",
        "topic": "rf/cmnd/Backlog",
        "qos": "1",
        "retain": "false",
        "broker": "bf7bd596.f29388",
        "x": 369.01734161376953,
        "y": 213.83317852020264,
        "wires": []
    },
    {
        "id": "bf7bd596.f29388",
        "type": "mqtt-broker",
        "z": "",
        "broker": "localhost",
        "port": "1883",
        "clientid": "",
        "usetls": false,
        "compatmode": true,
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "willTopic": "",
        "willQos": "0",
        "willPayload": ""
    }
]

**Comment by ascillato2** [comment]
Closing this issue as there is no feedback. Please, ask to reopen if you need anything else. Thanks
