### ISSUE TITLE
Ide config issue

### ISSUE THREAD

**Issue by jonydebu** [arendst/Sonoff-Tasmota#3303]
Need help with this issue , thanks. 

![image](https://user-images.githubusercontent.com/30730098/43048752-fd3d7d9c-8dec-11e8-9723-b4a6436c9511.png)

**Comment by brainnex** [comment]
did you checked the wiki?

[https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE](https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE)

**Comment by jonydebu** [comment]
Yes i did i follow the wiki word by word . ESP8266 board version 2.4.1 , Tasamota v 5.14 .
I´ve change  ```platform.txt``` ando also  ```boards.txt``` as last step .

**Comment by reloxx13** [comment]
check this point again, this "DOCTYPE" error comes from a 404 error page not found

and remove the space in "IDE Arduino" (to IDE_Arduino), better move teh complete arduino folder in root of c:\

Install ESP8266 board software

    Open Arduino IDE and select File - Preferences and add the following text for field Additional Boards Manager URLs: http://arduino.esp8266.com/stable/package_esp8266com_index.json and select OK.
    Open Tools - Boards ... - Boards Manager ... and scroll down and click on esp8266 by ESP8266 Community. Click the Install button to download and install the latest ESP8266 board software. Select Clos

**Comment by jonydebu** [comment]
Nice , it seems the issue was solved when i move the complete arduino folder to c:\ 
But now got another issue i paste it : 
![image](https://user-images.githubusercontent.com/30730098/43051073-b8ced40e-8e13-11e8-92d1-fa48d4b9a4a1.png)

**Comment by ascillato** [comment]
that could be:

GPIO0 is not to ground
ESP8266 has not power
Wrong COM PORT
RX, TX pins connected wrong to the board

**Comment by ascillato2** [comment]
Hi

@jonydebu 

Could you solve your issue?

**Comment by jonydebu** [comment]
Yes finally i´ve solved . The ESP was broken and do not go in pairing mode . I bought another one . Thanks for your help.
