### ISSUE TITLE
Sonoff Touch respons Unknown

### ISSUE THREAD

**Issue by smekcio** [arendst/Sonoff-Tasmota#331]
I have issue that it doesnt matter what command I send I always receive {"Command":"Unknown"} on topic stat/.../RESULT

**Comment by davidelang** [comment]
what commands have you attempted to send, how are you sending them (serial, web 
console, mqtt??)

**Comment by smekcio** [comment]
Im trying via:
- serial (ex. status/power on)
- web htttp (address/?cm=status)
- console (status/power on)
And tej most value for me mqtt by publishing on topics:
cmnd/sonoff/POWER with message ON or cmnd/sonoff/STATUS and Im always receiving {"Command":"Unknown"} on topic stat/.../RESULT

**Comment by smekcio** [comment]
The problem disappeared when I changed MQTT topic from salon/swiatlo (english: livingroom/light) to just "light".

**Comment by davidelang** [comment]
yes, '/' has special meanings in mqtt, so it should nto be used in a topic

**Comment by flanshaw** [comment]
I've got the same issue. Pressing the button (for over 4 seconds) to reset no longer work. any advice how i can reset to user_config.h.

**Comment by davidelang** [comment]
wee the troubleshooting page for the options to reset the device
