### ISSUE TITLE
timestd & timedst return invalid JSON

### ISSUE THREAD

**Issue by jcheger** [arendst/Sonoff-Tasmota#3322]
TimeSTD and TimeDST return an invalid JSON string: « "Offset":xx" ». The last quote is invalid.

Bug confirmed to appear on fw 6.1.1

    20:42:53 MQT: tasmota/anet/stat/RESULT = {"TimeStd":{"Hemisphere":0,"Week":0,"Month":10,"Day":1,"Hour":3,"Offset":60"}}
    20:42:53 MQT: tasmota/anet/stat/RESULT = {"TimeDst":{"Hemisphere":0,"Week":0,"Month":3,"Day":1,"Hour":2,"Offset":120"}}

**Comment by ascillato** [comment]
Hi,

I could not reproduce that issue.

What do you mean with invalid? If I change the values as explained in commands in the wiki, those values change accordingly.

**Comment by ascillato** [comment]
Ok.

I could reproduce it. @arendst 

is `"Offset":60"` and should be `"Offset":60`

Thanks for pointing this out :+1:

**Comment by ascillato2** [comment]
Tested ok!

Thanks :+1:
