### ISSUE TITLE
Pow won't go in AP mode

### ISSUE THREAD

**Issue by cirolaferrara** [arendst/Sonoff-Tasmota#3325]
I don't know why but my Sonoff POW flashed with Tasmota 5.14.0 after changed router (same SSID and same password) won't connect to my WIFI.
I'm trying to reset it with 40 seconds but without success. I tried with 4 short presses, but it don't go in AP mode. Sometimes it goes in Wifi smartconfig but asks me for a WEB password (but mine does not work).

I don't want to reflash by serial because it is inside the wall. Any help?

**Comment by ascillato** [comment]
Sorry. You will need to reflash by wire.

**Comment by ascillato2** [comment]
Hi,

Have you managed to solve your issue by flasing by wire?

**Comment by cirolaferrara** [comment]
flashed by wire 4 POWs and 1 BASIC. All same problem
