### ISSUE TITLE
IRreceive parsing raw data

### ISSUE THREAD

**Issue by jnt2007** [arendst/Sonoff-Tasmota#3326]
Hi.

I have Sonoff basic with connected TSOP IR receiver. After activating Samsung AC remote control more debug log write next:
```
00:00:14 IRR: RawLen 74, Bits 37, Value 3FFF4B54, Decode -292978525
00:00:15 IRR: RawLen 74, Bits 37, Value 3FFF4B54, Decode 961051959
```
I'm trying to understand how to send this IR signal via another Sonoff Basic with [this mod](https://github.com/altelch/SonoffIR).

How to decode into IRsend command?

**Comment by Jason2866** [comment]
What do you see on the webconsole (no debug modus) if ir received?

**Comment by jnt2007** [comment]
@jason2866 Nothing. No any info in web console if debug mode disabled.

**Comment by Jason2866** [comment]
Then it is not supported.

**Comment by jnt2007** [comment]
Maybe reading and sending raw data might be implemented in the future?

**Comment by ascillato2** [comment]
Hi,

Duplicated issue. See #2116

Thanks.
