### ISSUE TITLE
sonoff basic - flash form espeasy web interface to tasmota

### ISSUE THREAD

**Issue by lpt2007** [arendst/Sonoff-Tasmota#3328]
Hi

I flash tasmota (latest sonoff-allsensors.bin) from espeasy web interface. 

At end I get message update success. But now I can not connect to sonoff-basic (no light and if I press button once relay not click). 

I also try all this but not working.
[https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage](url)

**Comment by Frogmore42** [comment]
You will likely need to flash using serial.  There are things that could have gone wrong in the update, that once gone wrong can only be fixed by serial flash, which is the only recovery method that almost always works.

**Comment by ascillato2** [comment]
Hi,

Have you managed to solve your issue by flasing by wire?

**Comment by ascillato2** [comment]
Closing this issue as there is no feedback. Please, ask to reopen if you need anything else. Thanks
