### ISSUE TITLE
Clarification needed on wiki for rules command

### ISSUE THREAD

**Issue by haegar33** [arendst/Sonoff-Tasmota#3336]
There seems to be a discrepancy for the description of the rule command. In the wiki there seems to be commands like rule1, rule2 (without spaces) etc. Based on my experience with Tasmota 5.14 and now 6.1 there is only one rule command where all rules have to be defined in one batch. You enable rules with "rule 1" but not "rule1 1" ?
Please clarify, thanks!

**Comment by arendst** [comment]
5.14 only supports one rule group called rule
6.1 support three rule groups called rule1 (or rule), rule2 and rule3.

**Comment by haegar33** [comment]
Great! Should be added in the Wiki, thanks.
