### ISSUE TITLE
SONOFF Basic + DS18B20 sensor = temperature not visible on webpage

### ISSUE THREAD

**Issue by maseron** [arendst/Sonoff-Tasmota#3341]
**Describe the bug**

When I install sonoff.bin over OTA and add DS18B20, then temperature do not appear on front page, but if I set module to Generic and then specify DS18B20 sensor on gpio14 then I see temperature on first page, but it's gone if I set BPIO12 to Relay1. Then again I see only toggle button... I tested it with 5.14 and 6.1.1. tried also sonoff-allsensors.bin

- [X ] Searched the problem in issues and in the wiki
- [ X] Hardware used : SoOnOff Bacis V1.0 2017-10-11
- [ X] Provide the output of command ``status 0`` :
22:07:38 CMD: status 0
22:07:38 RSL: STATUS = {"Status":{"Module":18,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
22:07:38 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:06:23","StartupUTC":"2018-07-26T21:01:15","Sleep":0,"BootCount":17,"SaveCount":36,"SaveAddress":"F8000"}}
22:07:38 RSL: STATUS2 = {"StatusFWR":{"Version":"5.14.0","BuildDateTime":"2018-07-23T16:46:08","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
22:07:38 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Hidden",""],"TelePeriod":300,"SetOption":["00008001","55818000"]}}
22:07:38 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":553,"Free":448,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
22:07:38 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff-8102","IPAddress":"192.168.0.13","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"84:F3:EB:48:7F:A6","Webserver":2,"WifiConfig":2}}
22:07:38 RSL: STATUS7 = {"StatusTIM":{"UTC":"Thu Jul 26 21:07:38 2018","Local":"Thu Jul 26 22:07:38 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:15","Sunset":"20:37"}}
22:07:38 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-07-26T22:07:38"}}
22:07:38 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-07-26T22:07:38","Uptime":"0T00:06:23","Vcc":3.190,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Hidden","RSSI":88,"APMac":"DD:AA:DD:DD:DD:DD"}}}

**To Reproduce**
Install sonoff.bin 5.14 or 6.1.1. and conect DS18B20 sensor. Go to web page and check if it's possible to see temperature.
Change module to Generic and set only DS18B20 sensor on gpio14. Check the webpage.

**Expected behavior**
If the module is set to Sonoff basic and DS18B20 sensor is specified the temperature on web page is shown above toggle button.

**Screenshots**
![sonoffbasic-sensorsetview png](https://user-images.githubusercontent.com/20096524/43289321-25483c70-911a-11e8-962c-806031362211.png)
![sonoffbasic-sensorsetcfg](https://user-images.githubusercontent.com/20096524/43289322-256dfc94-911a-11e8-8829-52db73228dda.png)
![generic-relaysetview png](https://user-images.githubusercontent.com/20096524/43289323-258b5622-911a-11e8-8152-22133ba94e77.png)
![generic-relaysetcfg](https://user-images.githubusercontent.com/20096524/43289324-25a97a94-911a-11e8-93ee-d30dc97e5316.png)
![generic-norelaysetview](https://user-images.githubusercontent.com/20096524/43289325-25c557be-911a-11e8-947a-6202aea93e47.png)
![generic-norelaysetcfg](https://user-images.githubusercontent.com/20096524/43289326-25e28ed8-911a-11e8-80c1-251b3c5ef009.png)

**Comment by Frogmore42** [comment]
How do you have it wired?
Have you measured the resistance of the pull up?
Normally, you need a pull-up to get the DS18B20 to work.

**Comment by maseron** [comment]
Something strange.... today switched it on, set "Web log level" to "3 Debug" and all started to work... set back the log to "2 Info" and now it's working. Even if I change back the module to Sonoff Basic...

**Comment by curzon01** [comment]
Sensors can take a view seconds until they are visible - if you are too impatient then you do not see sensors. Wait a moment, sometimes a minute, and sensors are also visible on webinterface. I think this could be the reason of your issue.


If it is solved, please close your issue - you opened it, you can close it :smirk:

**Comment by maseron** [comment]
I do not think so, because spent like 3h to understood where is the problem...
Upgraded to 6.1.1 and it still works. So all good now.

**Comment by Frogmore42** [comment]
Actually, it can be related to wiring.  If the code doesn't see a sensor there, you will get the results you were seeing.  Double check that the resistor is actually the value you think it is.  More than one person has made a mistake and put a resistor that is ten times larger.  Doing that will get you results that are similar, as will having poor quality connections.

It's great that it is working for you now and I hope it continues to do so, but if not check the things I suggested.

**Comment by digidestination** [comment]
Hi, I had the same issue, finally it was wrong resistor. As soon as I added correct resistor, all worked well.
