### ISSUE TITLE
Module Number for Sensors

### ISSUE THREAD

**Issue by luisfpinto** [arendst/Sonoff-Tasmota#3346]
Hello,

From the Wiki documentation, I know that Sonoff SC is model number 21 but I would like to know all possible sonoff sensors models.

Thank you in advance!

**Comment by Frogmore42** [comment]
Use the source Luis 😉
https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/sonoff_template.h

**Comment by luisfpinto** [comment]
Thank you! @Frogmore42

**Comment by Frogmore42** [comment]
Since this seems to be answered, please close.
