### ISSUE TITLE
Sonoff LED Color

### ISSUE THREAD

**Issue by FilipLigaarden** [arendst/Sonoff-Tasmota#335]
Platform: HASS
MQQT broker: Built-in
I cant get setting color to work.
Have tried many different ways.
Note that the dimmer slider is working.
Yesterday i got the color adjustment slider to pop up, but it did nothing.
Is this command working?
Would it be possible to add a color slider in the web interface of the Sonoff LED?
In case im doing something wrong, here is my config.
config:
  - platform: mqtt
    name: "uteled"
    command_topic: "cmnd/uteled/POWER"
    state_topic: "stat/uteled/POWER"
    brightness_command_topic: "cmnd/uteled/Dimmer"
    brightness_state_topic: "stat/uteled/Dimmer"
    color_command_topic: "cmnd/uteled/Color"
    color_temp_state_topic: "stat/uteled/Color"
    brightness_scale: 100
    
    
    optimistic: false
    retain: true

**Comment by davidelang** [comment]
remember that the sonoff LED is not a RGB strip, it just has warm white a cool white LEDs and you can adjust these two different white 'colors' a bit.
