### ISSUE TITLE
Sonoff T1 2-Gang as Relai

### ISSUE THREAD

**Issue by Phil795** [arendst/Sonoff-Tasmota#3358]
Is it possible to configure the Sonoff T1 with 2 switches in a way that only either works or not?

I would like to automate my roller shutters. The motor may either run up or down. But not both at the same time.
Since the motor has an end position switch-off, a permanent current flow would not be a problem. How can I prevent both switches from being pressed at the same time?

**Comment by Jason2866** [comment]
Take a look at SetOption14

**Comment by ascillato2** [comment]
Hi, if your question has been addressed, please close this issue. Thanks.

**Comment by Phil795** [comment]
Thanks this answer solved my issue :-)
