### ISSUE TITLE
Question: Sonoff Touch reconfigure functionality

### ISSUE THREAD

**Issue by firzanarmani** [arendst/Sonoff-Tasmota#3360]
Hi,

I would like to know if it is possible to reconfigure the button/touch functionality, i.e the button usage as per https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage.

My case scenario is this. When I single-press/touch the button, instead of toggling the relay, I would like it to simply send a MQTT message (instruction to trigger another device or something). When I double-press the button, it will perform the regular relay toggle with the appropriate status change.

Can anyone point me in the correct direction of how to perform this?

**Comment by Jason2866** [comment]
Take a look here:
https://github.com/arendst/Sonoff-Tasmota/wiki/Control-other-devices

**Comment by ascillato2** [comment]
Hi, if your question has been addressed, please close this issue. Thanks.
