### ISSUE TITLE
Latest develop 6.1.1c deletes config when upgrading from earlier version

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#3363]
*Config is lost from upgrade 6.1.1b to latest 6.1.1c**

Tried on a Sonoff Basic and a WemosD1 mini.
Used self compiled version. Here is my user_config_override.h
[user_config_override.h.log](https://github.com/arendst/Sonoff-Tasmota/files/2238076/user_config_override.h.log)

`/*
  user_config_override.h - user configuration overrides user_config.h for Sonoff-Tasmota

  Copyright (C) 2018  Theo Arends

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef _USER_CONFIG_OVERRIDE_H_
#define _USER_CONFIG_OVERRIDE_H_

// force the compiler to show a warning to confirm that this file is inlcuded
#warning **** user_config_override.h: Using Settings from this File ****

/*****************************************************************************************************\
 * USAGE:
 *   To modify the stock configuration without changing the user_config.h file:
 *   (1) copy this file to "user_config_override.h" (It will be ignored by Git)
 *   (2) define your own settings below
 *   (3) for platformio:
 *         define USE_CONFIG_OVERRIDE as a build flags.
 *         ie1 : export PLATFORMIO_BUILD_FLAGS='-DUSE_CONFIG_OVERRIDE'
 *         ie2 : enable in file platformio.ini ;build_flags = -Wl,-Tesp8266.flash.1m0.ld -DUSE_CONFIG_OVERRIDE
 *       for Arduino IDE:
 *         enable define USE_CONFIG_OVERRIDE in user_config.h
 ******************************************************************************************************
 * ATTENTION:
 *   - Changes to SECTION1 PARAMETER defines will only override flash settings if you change define CFG_HOLDER.
 *   - Expect compiler warnings when no ifdef/undef/endif sequence is used.
 *   - You still need to update user_config.h for major define USE_MQTT_TLS.
 *   - All parameters can be persistent changed online using commands via MQTT, WebConsole or Serial.
\*****************************************************************************************************/

// -- Master parameter control --------------------
#undef  CFG_HOLDER
#define CFG_HOLDER        4617                   // [Reset 1] Change this value to load SECTION1 configuration parameters to flash

#undef  SERIAL_LOG_LEVEL
#define SERIAL_LOG_LEVEL       LOG_LEVEL_NONE    // [SerialLog] (LOG_LEVEL_NONE, LOG_LEVEL_ERROR, LOG_LEVEL_INFO, LOG_LEVEL_DEBUG, LOG_LEVEL_DEBUG_MORE)

#undef  OTA_URL
#define OTA_URL                "http://192.168.2.20/web/tasmota/sonoff.bin"  // [OtaUrl]

// -- Setup your own Wifi settings  ---------------
#undef  STA_SSID1
#define STA_SSID1         "SSID"     // [Ssid1] Wifi SSID
//#define STA_SSID1         "gkkxXh"     // [Ssid1] Wifi SSID

#undef  STA_PASS1
#define STA_PASS1         "Password"         // [Password1] Wifi password
//#define STA_PASS1         "4WPgRjFk"         // [Password1] Wifi password

#undef  WIFI_CONFIG_NO_SSID                                                 
#define WIFI_CONFIG_NO_SSID    WIFI_SERIAL       // Default tool if wifi fails to connect and no SSID is configured
                                                 //   (WIFI_SMARTCONFIG, WIFI_MANAGER, WIFI_WPSCONFIG, WIFI_SERIAL)
                                                 //   *** NOTE: When WPS is disabled by USE_WPS below, WIFI_WPSCONFIG will execute WIFI_MANAGER ***
                                                 //   *** NOTE: When WIFI_MANAGER is disabled by USE_WEBSERVER below, WIFI_MANAGER will execute WIFI_SMARTCONFIG ***
                                                 //   *** NOTE: When WIFI_SMARTCONFIG is disabled by USE_SMARTCONFIG below, WIFI_SMARTCONFIG will execute WIFI_SERIAL ***

#undef  WIFI_CONFIG_TOOL
#define WIFI_CONFIG_TOOL  WIFI_WAIT             // [WifiConfig] Default tool if wifi fails to connect
                                                //   (WIFI_RESTART, WIFI_SMARTCONFIG, WIFI_MANAGER, WIFI_WPSCONFIG, WIFI_RETRY, WIFI_WAIT, WIFI_SERIAL)
// -- Wifi Config tools ---------------------------
#undef  USE_WPS                                  // Add support for WPS as initial wifi configuration tool (+33k code, 1k mem (5k mem with core v2.4.2+))
#undef  USE_SMARTCONFIG                          // Add support for Wifi SmartConfig as initial wifi configuration tool (+23k code, +0.6k mem)
//#define USE_WPS                                  // Add support for WPS as initial wifi configuration tool (+33k code, 1k mem (5k mem with core v2.4.2+))
//#define USE_SMARTCONFIG                          // Add support for Wifi SmartConfig as initial wifi configuration tool (+23k code, +0.6k mem)

// -- OTA -----------------------------------------
#undef  USE_ARDUINO_OTA                          // Add optional support for Arduino OTA (+13k code)

#undef  WIFI_IP_ADDRESS
#define WIFI_IP_ADDRESS   "0.0.0.0"             // Set to 0.0.0.0 for using DHCP or IP address

#undef  WIFI_SUBNETMASK
#define WIFI_SUBNETMASK   "255.255.255.0"       // [IpAddress3] If not using DHCP set Network mask

#undef  WIFI_GATEWAY
#define WIFI_GATEWAY      "192.168.2.1"         // if not using DHCP set Gateway IP address

#undef  WIFI_DNS
#define WIFI_DNS          "192.168.2.1"         // If not using DHCP set DNS IP address (might be equal to WIFI_GATEWAY)

// -- Setup your own MQTT settings  ---------------
#undef  MQTT_HOST
#define MQTT_HOST         "192.168.2.114"       // [MqttHost]

#undef  MQTT_PORT
#define MQTT_PORT         1883                   // [MqttPort] MQTT port (10123 on CloudMQTT)

#undef  MQTT_USER
#define MQTT_USER         "openhabian"         // [MqttUser] Optional user

#undef  MQTT_PASS
#define MQTT_PASS         "openhabian"         // [MqttPassword] Optional password

#undef  EMULATION
#define EMULATION         EMUL_HUE          // [Emulation] Select Belkin WeMo (single relay/light) or Hue Bridge emulation (multi relay/light) (EMUL_NONE, EMUL_WEMO or EMUL_HUE)

#undef  NTP_SERVER1
#define NTP_SERVER1       "ptbtime1.ptb.de"  // [NtpServer1] Select first NTP server by name or IP address (129.250.35.250)

#undef  LATITUDE
#define LATITUDE          48.xxxxxx         // [Latitude] Your location to be used with sunrise and sunset

#undef  LONGITUDE
#define LONGITUDE         11.xxxxxx         // [Longitude] Your location to be used with sunrise and sunset

#undef  APP_TIMEZONE
#define APP_TIMEZONE           99                // [Timezone] +1 hour (Amsterdam) (-13 .. 14 = hours from UTC, 99 = use TIME_DST/TIME_STD)

#undef  APP_SLEEP
#define APP_SLEEP              1                 // [Sleep] Sleep time to lower energy consumption (0 = Off, 1 - 250 mSec)

#undef  WS2812_LEDS
#define WS2812_LEDS            24                // [Pixels] Number of WS2812 LEDs to start with (max is 512)

#undef  MQTT_LIBRARY_TYPE
#define MQTT_LIBRARY_TYPE      MQTT_PUBSUBCLIENT   // Use PubSubClient library
//#define MQTT_LIBRARY_TYPE      MQTT_TASMOTAMQTT    // Use TasmotaMqtt library (+4k4 code, +4k mem) - non-TLS only

#undef  USE_DOMOTICZ                           // Enable Domoticz (+6k code, +0.3k mem)
#undef  USE_HOME_ASSISTANT                     // Enable Home Assistant Discovery Support (+2k code)
#undef  USE_KNX                                // Enable KNX IP Protocol Support (+23k code, +3k3 mem)

#undef  USE_DISCOVERY                          // Enable mDNS for the following services (+8k code, +0.3k mem)

#define USE_I2C                                // I2C using library wire (+10k code, 0k2 mem, 124 iram)
#undef  USE_SHT                                // Add I2C emulating code for SHT1X sensor (+1k4 code)
#undef  USE_SHT3X                              // Add I2C code for SHT3x or SHTC3 sensor (+0k7 code)
#undef  USE_HTU                                // Add I2C code for HTU21/SI7013/SI7020/SI7021 sensor (+1k5 code)
#undef  USE_LM75AD                             // Add I2C code for LM75AD sensor (+0k5 code)
#undef  USE_SGP30                              // Add I2C code for SGP30 sensor (+1k1 code)
#undef  USE_BH1750                             // Add I2C code for BH1750 sensor (+0k5 code)
#define USE_TSL2561                            // Add I2C code for TSL2561 sensor using library Joba_Tsl2561 (+2k3 code)
#define USE_MHZ19                              // Add support for MH-Z19 CO2 sensor (+2k code)
#undef  USE_SENSEAIR                           // Add support for SenseAir K30, K70 and S8 CO2 sensor (+2k3 code)
#undef  USE_PMS5003                            // Add support for PMS5003 and PMS7003 particle concentration sensor (+1k3 code)
#undef  USE_NOVA_SDS                           // Add support for SDS011 and SDS021 particle concentration sensor (+0k7 code)
#undef  USE_PZEM004T                           // Add support for PZEM004T Energy monitor (+2k code)
#undef  USE_SDM120                             // Add support for Eastron SDM120-Modbus energy meter (+1k7 code)
#undef  USE_SDM630                             // Add support for Eastron SDM630-Modbus energy meter (+2k code)
#undef  USE_BME680
#undef  USE_LM75AD                             // Enable LM75AD sensor (I2C addresses 0x48 - 0x4F) (+0k5 code)
#define USE_APDS9960                           // Enable APDS9960 Proximity Sensor (I2C address 0x39). Disables SHT and VEML6070 (+4k7 code)

#undef  USE_ARILUX_RF                          // Add support for Arilux RF remote controller (+0k8 code, 252 iram (non 2.3.0))
#undef  USE_IR_HVAC                            // Support for HVAC system using IR (+2k code)
#undef  USE_SR04                               // Add support for HC-SR04 ultrasonic devices (+1k code)

#define USE_TM1638                             // Add support for TM1638 switches copying Switch1 .. Switch8 (+1k code)
#define USE_MPR121                             // Enable MPR121 controller (I2C addresses 0x5A, 0x5B, 0x5C and 0x5D) in input mode for touch buttons (+1k3 code)
  #define USE_MCP230xx                           // Add I2C code for MCP23008/MCP23017 for GP INPUT ONLY providing command Sensor29 for configuration (+2k2 code)
    #define USE_MCP230xx_displaymain             // Display pin status on Tasmota main page (+0k2 code)
    #define USE_MCP230xx_webconfig               // Enable web config button and form to Tasmota web interface (+2k1 code)

//#define DISPLAY_CONFIG

#ifdef DISPLAY_CONFIG  // ****************************************************************************

#ifdef USE_I2C
  #define USE_DISPLAY                            // Add I2C Display Support for LCD, Oled and up to eigth Matrices (+19k code)
    #define MTX_ADDRESS1       0x71              // [DisplayAddress[1]] I2C address of first 8x8 matrix module
    #define MTX_ADDRESS2       0x74              // [DisplayAddress[2]] I2C address of second 8x8 matrix module
    #define MTX_ADDRESS3       0x75              // [DisplayAddress[3]] I2C address of third 8x8 matrix module
    #define MTX_ADDRESS4       0x72              // [DisplayAddress[4]] I2C address of fourth 8x8 matrix module
    #define MTX_ADDRESS5       0x73              // [DisplayAddress[5]] I2C address of fifth 8x8 matrix module
    #define MTX_ADDRESS6       0x76              // [DisplayAddress[6]] I2C address of sixth 8x8 matrix module
    #define MTX_ADDRESS7       0x00              // [DisplayAddress[7]] I2C address of seventh 8x8 matrix module
    #define MTX_ADDRESS8       0x00              // [DisplayAddress[8]] I2C address of eigth 8x8 matrix module
#endif  // USE_I2C

// -- SPI sensors ---------------------------------
#define USE_SPI                                  // SPI using library TasmotaTFT
#ifdef USE_SPI
  #ifndef USE_DISPLAY
  #define USE_DISPLAY                            // Add SPI Display support for 320x240 and 480x320 TFT
  #endif
#endif  // USE_SPI

#endif  // DISPLAY_CONFIG ****************************************************************************

#endif  // _USER_CONFIG_OVERRIDE_H_`

**Comment by Jason2866** [comment]
Wow, that was fast!!

**Comment by arendst** [comment]
Yes! I had it fixed locally but it missed the last push.
