### ISSUE TITLE
Domoticz DISABLE

### ISSUE THREAD

**Issue by brinzlee** [arendst/Sonoff-Tasmota#3366]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [x ] Hardware used : 
Sonoff Basic
I'm trying to use a Sonoff Basic with firmware 6.1.1c with HomeAssistant HASS:IO and mosquitto MQTT...I have had success with this in the past with lower versions of firmware controlling these modules. However I can't control the new versions. I can't seem to be able to disable Domoticz is this a bug or am I doing something wrong
//#define USE_DOMOTICZ.
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
What makes you think that you cannot disable domoticz?

**Comment by brinzlee** [comment]
When I monitor mosquitto_sub all I'm getting is {POWER1":"domitcz/out!}
I can't control the sonoff with a simple on/off command like I used too
  - platform: mqtt
    name: "First Sonoff Switch"
    state_topic: "stat/sonoff/POWER"
    command_topic: "cmnd/sonoff/power"
    availability_topic: "tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

**Comment by arendst** [comment]
Cannot reproduce.

I don't understand the message {POWER1":"domitcz/out!} as Tasmota does not formulate such a message.

**Comment by arendst** [comment]
Unless your settings are corrupt due to going up and down in version loads.

You might also want to try and execute commands ``statetext`` to verify the correct power on/off/toggle/hold messages. See wiki regarding statetext syntax.

**Comment by brinzlee** [comment]
This is from the console

13:37:12 MQT: stat/sonoff/POWER1 = domoticz/out
13:39:44 MQT: tele/sonoff/STATE = {"Time":"2018-07-29T13:39:44","Uptime":"0T01:20:17","Vcc":3.514,"POWER1":"domoticz/out","Wifi":{"AP":1,"SSId":"SKY59E4B LO","RSSI":92,"APMac":"10:6F:3F:7F:02:8A"}}
13:44:44 MQT: tele/sonoff/STATE = {"Time":"2018-07-29T13:44:44","Uptime":"0T01:25:17","Vcc":3.514,"POWER1":"domoticz/out","Wifi":{"AP":1,"SSId":"SKY59E4B LO","RSSI":94,"APMac":"10:6F:3F:7F:02:8A"}}
13:49:44 MQT: tele/sonoff/STATE = {"Time":"2018-07-29T13:49:44","Uptime":"0T01:30:17","Vcc":3.514,"POWER1":"domoticz/out","Wifi":{"AP":1,"SSId":"SKY59E4B LO","RSSI":94,"APMac":"10:6F:3F:7F:02:8A"}}
13:54:44 MQT: tele/sonoff/STATE = {"Time":"2018-07-29T13:54:44","Uptime":"0T01:35:17","Vcc":3.514,"POWER1":"domoticz/out","Wifi":{"AP":1,"SSId":"SKY59E4B LO","RSSI":88,"APMac":"10:6F:3F:7F:02:8A"}}
13:59:44 MQT: tele/sonoff/STATE = {"Time":"2018-07-29T13:59:44","Uptime":"0T01:40:17","Vcc":3.514,"POWER1":"domoticz/out","Wifi":{"AP":1,"SSId":"SKY59E4B LO","RSSI":88,"APMac":"10:6F:3F:7F:02:8A"}}
14:02:00 MQT: tele/sonoff/UPTIME = {"Time":"2018-07-29T14:02:00","Uptime":"0T01:42:33"}
14:03:07 MQT: stat/sonoff/RESULT = {"POWER1":"domoticz/out"}
14:03:07 MQT: stat/sonoff/POWER1 = domoticz/out
14:03:10 MQT: stat/sonoff/RESULT = {"POWER1":"domoticz/out"}
14:03:10 MQT: stat/sonoff/POWER1 = domoticz/out

**Comment by arendst** [comment]
See my last comment regarding statetext

**Comment by arendst** [comment]
Settings corruption may also be caused by not following the correct migration path as noticed in the 6.1.1 release docs...

**Comment by brinzlee** [comment]
OK so it's possible corruption however I didn't flash with OTA I used Arduino IDE....How do I reset the flash and start again

**Comment by brinzlee** [comment]
You are correct it was corrupt....I have now reset it and all is well....Thank you very much for your kind direction and assistance.....Superb piece of software....Note to self RTFM
