### ISSUE TITLE
TelePeriod - less than 10 seconds

### ISSUE THREAD

**Issue by Rapemortality** [arendst/Sonoff-Tasmota#3367]
Is there any possibility to reduce telemetry period to less than 10 seconds?

There is many things in automation that need quick reaction form automation system - and according to that actual data form sensors. Possibility to reduce "TelePeriod" to ~1-3 sec would be very helpfull.

**Comment by ascillato2** [comment]
Hi,

Sorry but no. Teleperiod is just for telemetry. 
For fast response you need to use MQTT or rules or http or knx.

**Comment by Klagio** [comment]
I would need fast updates, not fast response

**Comment by osulivanDE** [comment]
Is there an update? I also would need more frequent updates from my sensors. Why this 10s limit?

**Comment by barbudor** [comment]
No and there won't be.
If you want to publish some data more frequently, use Rules and the Publish command

**Comment by sfromis** [comment]
If the sensors are energy monitoring, check the `PowerDelta` command for faster responses.
