### ISSUE TITLE
Not connecting to second AP and not entering AP mode

### ISSUE THREAD

**Issue by MadDoct** [arendst/Sonoff-Tasmota#3372]
Tasmota is not connecting to second AP when the first isn't available and doesn't enter AP mode when both APs aren't available.

Also, make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues and in the wiki
- [x] Hardware used : NodeMCU v3 (lolin), flashed with 6.1.1c, compiled with core 2.3.0
- [x] Provide the output of command ``status 0`` :
```
stat/NodeMCUt/STATUS = {"Status":{"Module":18,"FriendlyName":["NodeMCUtasmota"],"Topic":"NodeMCUt","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
```

**To Reproduce**
1 - After being setup, when you power on the nodeMCU without the usual AP accessible, but with the second AP available, it never connects to the second AP.
2 - After being setup, when none of the APs are available, it doesn't enter AP mode.

**Expected behavior**
1 - It should connect to the second AP, when the first isn't available
2 - It should enter AP mode when neither of the usual APs are available

**Comment by ascillato** [comment]
Please, share the output of the command wificonfig

**Comment by MadDoct** [comment]
"WifiConfig":"5 (Wait)"

Should this be the default behaviour?!

**Comment by ascillato** [comment]
Wificonfig 5 is working as expected.

What you want is wificonfig 4.

Please, read the wiki. Thanks 

If this solves your issue, please close it. Thanks
