### ISSUE TITLE
Wemos D1 mini with latest tasmota version randomly turn on light 

### ISSUE THREAD

**Issue by tango156157** [arendst/Sonoff-Tasmota#3374]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [x ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [x ] Hardware used : 
- [ x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```
Sometimes my lights turn on randomly which is very annoying and  irritating. i am using Wemos d1 mini as a dual Dual channel model. Is this a Wifi issue or what ?
and other issue with that when i give command to Alexa, Alexa says device not responding but the light turn on

**Comment by reloxx13** [comment]
> Provide the output of command status 0
