### ISSUE TITLE
Downgrade v6.x to v5.x

### ISSUE THREAD

**Issue by kalety** [arendst/Sonoff-Tasmota#3376]
Hi!, yesterday I upraded one of mi sonoffs basic via OTA. It only responses over one minute, then drops connection... It's possible downgrade to previous version?.

Thanks in advance.

**Comment by mosix76** [comment]
hello,
I tried to downgrade via OTA a sonoff basic of mine to go back to the version 5.14... After an error on the uploading, the device didn't respond any more: no led flashing, no action pushing the button. So I tried again uploading the firmware by Platformio and ft232rl usb adapter. The downgrade went well, but the sonoff is like dead... doesn't respond. I hope to find a solution, thanks

**Comment by mosix76** [comment]
I've already tried keeping the button pressed for more of 40 sec, but the sonoff still not work. 
At this point I have another question: uploading the 5.14 firmware by platformio (with all previous settings) should rewrite everything (also the corrupt settings) or not?

In any case, this evening I'll try with the command by serial interface. 

PS: Theo, really incredible wonderful work with TASMOTA, and thank you for you help.

**Comment by wasi54** [comment]
No, uploading a firmware does not erase the settings, except you upload a firmware with a different CFG_HOLDER as with the previous firmware or as Theo wrote with pressing the button more than 40 sec.

**Comment by reloxx13** [comment]
[CFG_HOLDER](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#cfg_holder-explained)

[Clear Flash with ESPTOOL Point 3](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#esptool-usage)

**Comment by ascillato2** [comment]
Hi,

Closing this issue as your questions has been addressed. Ask to reopen this issue if you need it. Thanks
