### ISSUE TITLE
KNX Address add button disabled

### ISSUE THREAD

**Issue by mizrachiran** [arendst/Sonoff-Tasmota#3377]
Hi, 
I'm trying to setup KNX on my device. it seems like the add button in the lower section is disabled (Group Addresses to Receive Data from). See image below.
What am I doing wrong?

Thanks!

![image](https://user-images.githubusercontent.com/617155/43413719-7d90b28c-9439-11e8-8d73-1f705c907f45.png)

- [ X ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ X ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ X ] Searched the problem in the forum (https://forum.digital-pig.com/)
- [ ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [  X ] Hardware used : Custom
- [ ] Provide the output of command ``status 0`` :
```
{
"Status": {
"Module": 18,
"FriendlyName": [
"Sonoff",
"Sonoff2"
],
"Topic": "luxo-8",
"ButtonTopic": "0",
"Power": 1,
"PowerOnState": 3,
"LedState": 1,
"SaveData": 1,
"SaveState": 1,
"ButtonRetain": 0,
"PowerRetain": 0
},
"StatusPRM": {
"Baudrate": 115200,
"GroupTopic": "sonoffs",
"OtaUrl": "http://sonoff.maddox.co.uk/tasmota/sonoff-knx.bin",
"RestartReason": "Exception",
"Uptime": "0T00:14:46",
"StartupUTC": "2018-07-30T17:41:22",
"Sleep": 0,
"BootCount": 799,
"SaveCount": 1269,
"SaveAddress": "F5000"
},
"StatusFWR": {
"Version": "6.1.1",
"BuildDateTime": "2018-07-23T11:19:07",
"Boot": 31,
"Core": "2_3_0",
"SDK": "1.5.3(aec24ac9)"
},
"StatusLOG": {
"SerialLog": 2,
"WebLog": 2,
"SysLog": 0,
"LogHost": "",
"LogPort": 514,
"SSId": [
"Mizrachi_2.4Ghz",
""
],
"TelePeriod": 300,
"SetOption": [
"02008009",
"55818000"
]
},
"StatusMEM": {
"ProgramSize": 547,
"Free": 456,
"Heap": 11,
"ProgramFlashSize": 1024,
"FlashSize": 1024,
"FlashMode": 2,
"Features": [
"00000809",
"1FDAE594",
"0C000010",
"23B6179E",
"00000000"
]
},
"StatusNET": {
"Hostname": "luxo-8",
"IPAddress": "10.0.0.108",
"Gateway": "10.0.0.1",
"Subnetmask": "255.255.255.0",
"DNSServer": "8.8.8.8",
"Mac": "2C:3A:E8:3F:DB:4F",
"Webserver": 2,
"WifiConfig": 3
},
"StatusMQT": {
"MqttHost": "10.0.0.30",
"MqttPort": 1883,
"MqttClientMask": "luxo-8",
"MqttClient": "luxo-8",
"MqttUser": "DVES_USER",
"MqttType": 1,
"MAX_PACKET_SIZE": 1000,
"KEEPALIVE": 15
},
"StatusTIM": {
"UTC": "Mon Jul 30 17:56:08 2018",
"Local": "Mon Jul 30 18:56:08 2018",
"StartDST": "Sun Mar 25 02:00:00 2018",
"EndDST": "Sun Oct 28 03:00:00 2018",
"Timezone": 1,
"Sunrise": "05:21",
"Sunset": "20:32"
},
"StatusSNS": {
"Time": "2018-07-30T18:56:08",
"Switch1": "ON",
"Switch2": "OFF",
"Switch3": "ON"
},
"StatusSTS": {
"Time": "2018-07-30T18:56:08",
"Uptime": "0T00:14:46",
"Vcc": 3.11,
"POWER1": "ON",
"POWER2": "OFF",
"Wifi": {
"AP": 1,
"SSId": "Mizrachi_2.4Ghz",
"RSSI": 54,
"APMac": "94:10:3E:09:48:05"
}
}
}
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by mizrachiran** [comment]
Using the latest firmware 6.1.1

**Comment by mizrachiran** [comment]
just checked my debug logs. It seems that i have 10 malformed records 

21:47:03 KNX: CB: 10
21:47:03 KNX: CB #1: 1/1/81 to <null>
21:47:03 KNX: CB #2: 0/0/0 to <null>
21:47:03 KNX: CB #3: 0/0/0 to <null>
21:47:03 KNX: CB #4: 0/0/0 to <null>
21:47:03 KNX: CB #5: 0/0/0 to <null>
21:47:03 KNX: CB #6: 0/0/0 to <null>
21:47:03 KNX: CB #7: 0/0/0 to <null>
21:47:03 KNX: CB #8: 0/0/0 to <null>
21:47:03 KNX: CB #9: 0/0/0 to <null>
21:47:03 KNX: CB #10: 0/0/0 to <null>

**Comment by ascillato** [comment]
Hi,

Yes, that is the problem. The limit is 10 slots for KNX. If you have 10, the Add button get disabled.

That is a problem in your config, but there is a solution. KNX Driver has a startup check routine. To make it to reset the KNX config just change the module type or change some GPIOs to none and then restart.
After restart you can add your GPIO again.

**Comment by mizrachiran** [comment]
Thanks.
I tried to change the module configuration and it solved the issue.
I think it worth not saving illegal records or show them in the UI so it will be possible to remove them manually.

@ascillato, thanks again for the assistant and for developing the KNX feature in Tasmota.

**Comment by ascillato** [comment]
Yes, you are right. I will add another startup check for setting. Thanks
