### ISSUE TITLE
Yunshan Relay "PowerOnState 0"

### ISSUE THREAD

**Issue by meingraham** [arendst/Sonoff-Tasmota#3381]
TASMOTA 6.1.1b
Yunshan Relay Module

I set PowerOnState to 0. If I restart the device, the state of the relay when the device is powered down is retained when the device powers up. In other words, the PowerOnState is not "off".

**Comment by ascillato** [comment]
Hi,

Please, can you share your `status 0 `and the output of your console when you write the command `poweronstate 0` ?

**Comment by ascillato** [comment]
Another thing. Is your MQTT broker on? May be your broker is sending the POWER ON command.

Please also write `weblog 4` and do a restart and share the output of your console after restart. There will say the SOURCE of your power on

**Comment by ascillato** [comment]
Hi,

Is your MQTT broker on? May be your broker is sending the POWER ON command. (retain message)

Please write `weblog 4` in the console, then do a restart and share the output of your console after restarting. In that output, will say the SOURCE of your power on.

**Comment by meingraham** [comment]
I have not configured this switch in my MQTT broker yet. I am just figuring out how I should best set it up for the use case (Keurig on/off). 

> 01:37:04 MQT: stat/{MQTT Topic}/RESULT = {"PowerOnState":0}
01:37:08 CMD: status 0
01:37:08 MQT: stat/{MQTT Topic}/STATUS = {"Status":{"Module":33,"FriendlyName":["{FriendlyName}"],"Topic":"{MQTT Topic}","ButtonTopic":"0","Power":1,"PowerOnState":0,"LedState":0,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:10:11","StartupUTC":"2018-07-31T05:26:57","Sleep":250,"BootCount":7,"SaveCount":19,"SaveAddress":"F9000"}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS2 = {"StatusFWR":{"Version":"6.1.1b","BuildDateTime":"2018-07-30T23:04:44","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["{SSID}",""],"TelePeriod":300,"SetOption":["00008109","55818000"]}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS4 = {"StatusMEM":{"ProgramSize":424,"Free":576,"Heap":14,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3,"Features":["00000809","0F002B90","00000001","00000096","00000000"]}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS5 = {"StatusNET":{"Hostname":"{MQTT Topic}-XXXX","IPAddress":"{IP}","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"{MAC}","Webserver":2,"WifiConfig":5}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS6 = {"StatusMQT":{"MqttHost":"{MQTT Host}","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_{MAC ID}","MqttUser":"{MQTT User}","MqttType":2,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS7 = {"StatusTIM":{"UTC":"Tue Jul 31 05:37:08 2018","Local":"Tue Jul 31 01:37:08 2018","StartDST":"Sun Mar 11 02:00:00 2018","EndDST":"Sun Nov 04 02:00:00 2018","Timezone":99,"Sunrise":"06:35","Sunset":"20:30"}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS10 = {"StatusSNS":{"Time":"2018-07-31T01:37:08"}}
01:37:08 MQT: stat/{MQTT Topic}/STATUS11 = {"StatusSTS":{"Time":"2018-07-31T01:37:08","Uptime":"0T00:10:11","Vcc":3.151,"POWER":"ON","Wifi":{"AP":1,"SSId":"{SSID}","RSSI":100,"APMac":"{AP MAC}"}}}

**Comment by ascillato** [comment]
Please write` weblog 4 `in the console, then do a restart of your Tasmota and share the output of your console after restarting. In that output, will say the SOURCE of your power on.

**Comment by meingraham** [comment]
> 00:00:00 CFG: Loaded from flash at FA, Count 34
00:00:00 APP: Boot Count 12
00:00:00 SRC: Restart
00:00:00 Project sonoff Keurig Toggle Yunshan (Topic {MQTT Topic}, Fallback DVES_{MAC ID}, GroupTopic sonoffs) Version 6.1.1b-2_3_0
00:00:01 CFG: Saved to flash at F9, Count 35, Bytes 3584
00:00:02 WIF: Checking connection...
00:00:02 WIF: Attempting connection...
00:00:02 WIF: Patch issue 2186
00:00:02 WIF: Connecting to AP1 {SSID} in mode 11N as {MQTT Topic}-XXXX...
00:00:08 WIF: Checking connection...
00:00:08 WIF: Attempting connection...
00:00:13 WIF: Checking connection...
00:00:13 WIF: Attempting connection...
00:00:18 WIF: Checking connection...
00:00:18 WIF: Connect failed with AP incorrect password
00:00:21 APP: (UTC) Tue Jul 31 05:59:45 2018, (DST) Sun Mar 11 02:00:00 2018, (STD) Sun Nov 04 02:00:00 2018
01:59:47 WIF: Checking connection...
01:59:47 WIF: Connected
01:59:47 DNS: Initialized
01:59:47 HTP: Web server active on {MQTT Topic}-XXXX.local with IP address {IP}
01:59:54 MQT: Attempting connection...
01:59:54 MQT: Connected
01:59:54 MQT: tele/{MQTT Topic}/LWT = Online (retained)
01:59:54 MQT: cmnd/{MQTT Topic}/POWER = 
01:59:54 MQT: Subscribe to cmnd/{MQTT Topic}/#
01:59:54 MQT: Subscribe to cmnd/sonoffs/#
01:59:54 MQT: Subscribe to cmnd/DVES_{MAC ID}/#
01:59:54 MQT: tele/{MQTT Topic}/INFO1 = {"Module":"Yunshan Relay","Version":"6.1.1b","FallbackTopic":"DVES_{MAC ID}","GroupTopic":"sonoffs"}
01:59:54 MQT: tele/{MQTT Topic}/INFO2 = {"WebServerMode":"Admin","Hostname":"{MQTT Topic}-XXXX","IPAddress":"{IP}"}
01:59:54 MQT: tele/{MQTT Topic}/INFO3 = {"RestartReason":"Software/System restart"}
02:00:01 MQT: stat/{MQTT Topic}/RESULT = {"POWER":"ON"}
02:00:01 MQT: stat/{MQTT Topic}/POWER = ON
02:00:36 MQT: tele/{MQTT Topic}/STATE = {"Time":"2018-07-31T02:00:36","Uptime":"0T00:00:55","Vcc":3.137,"POWER":"ON","Wifi":{"AP":1,"SSId":"{SSID}","RSSI":100,"APMac":"{APMAC}"}}

**Comment by ascillato** [comment]
In the log it shows that your **power on** is due a retain message in your MQTT Broker. So your `poweronstate 0` is working. Your issue is that your broker is using retain messages.

You need to clear your MQTT broker and configure it to not to retain messages. For this last part, there are several issues with the solution for mosquitto.

**Comment by meingraham** [comment]
I see. The fact that the device "reported" its power state to the MQTT broker... then the broker retained that state. When the device reconnected to the MQTT broker, the broker sent the state that it had retained.

So, now I need to figure out how to have the broker not retain the state of my "TASMOTA" relays. The education never ends ;-) Thanks for the troubleshooting assistance. The issue is that in my automation hub, I want some items to retain their state but for items like these switches or lamps, etc., I want them to be off when the switch reconnects. I'll have to revisit my broker and openHAB configuration.

Thanks for your help.

Mike
