### ISSUE TITLE
Multiple DHT sensors

### ISSUE THREAD

**Issue by HellGL** [arendst/Sonoff-Tasmota#339]
Hello,
as follow up to issue #308 I created a patch to access up to 3 independent DHT sensors. I can't say how much additional ram or flash is used, but probably only a few bytes. Comments welcome.

[multi_dht2.patch.gz](https://github.com/arendst/Sonoff-Tasmota/files/902551/multi_dht2.patch.gz)

**Comment by ionciubotaru** [comment]
Test your code carefully and add a pull request. @arendst will decide or not to include it in the next release

**Comment by HellGL** [comment]
I am not sure if this correct, but at the moment I am sending all DHT sensor readings in one mqtt message:
`13:37:46 MQTT: tele/sonoff/SENSOR = {"Time":"2017-04-07T13:37:45", "DHT22_04":{"Temperature":19.4, "Humidity":42.7}, "DHT22_14":{"Temperature":19.8, "Humidity":43.5}}` 
Should I change the code to send a message for each sensor?

**Comment by arendst** [comment]
No keep it on one line please

**Comment by davidelang** [comment]
all sensors (of all types if there are multiple types) are sent as one sensor 
line.

**Comment by davidelang** [comment]
If you can create a pull request, it's easier to discuss and comment on the proposed changes. If you are not able to do that (or don't want to), please let us know and we'll fall back to less efficient processes.

**Comment by HellGL** [comment]
Now that I am back from vacation I added a pull request based on the latest (5.0.1) version.

**Comment by arendst** [comment]
Implemented in next release
