### ISSUE TITLE
iFan02 RF remote stopped working

### ISSUE THREAD

**Issue by ExplodingLemur** [arendst/Sonoff-Tasmota#3395]
My iFan02 stopped responding to its RF remote.  I've tried power-cycling the fan controller, I've tried holding the app bind button on the remote to get it to re-bind, but it's just not responding to it.  Has anyone else experienced this?  Is there a fix or did I just get a bad unit?  (It did work fine for about a week...)

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://forum.digital-pig.com/)
- [X] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [X] Hardware used : iFan02
- [X] Provide the output of command ``status 0`` :
```
04:37:31 CMD: status 0
04:37:31 RSL: stat/sonoff/STATUS = {"Status":{"Module":44,"FriendlyName":["Living room fan"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
04:37:31 RSL: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"External System","Uptime":"1T00:37:27","StartupUTC":"2018-08-02T03:00:04","Sleep":0,"BootCount":15,"SaveCount":73,"SaveAddress":"FB000"}}
04:37:31 RSL: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.1.1","BuildDateTime":"2018-07-14T15:57:03","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
04:37:31 RSL: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["HAILERIS-IoT",""],"TelePeriod":300,"SetOption":["00008009","55818000"]}}
04:37:31 RSL: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":535,"Free":468,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","0C000000","23B6179E","00000000"]}}
04:37:31 RSL: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-3950","IPAddress":"192.168.7.105","Gateway":"192.168.7.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.7.254","Mac":"60:01:94:AB:0F:6E","Webserver":2,"WifiConfig":2}}
04:37:31 RSL: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_AB0F6E","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
04:37:31 RSL: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Fri Aug 03 03:37:31 2018","Local":"Fri Aug 03 04:37:31 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:26","Sunset":"20:26"}}
04:37:31 RSL: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2018-08-03T04:37:31"}}
04:37:31 RSL: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2018-08-03T04:37:31","Uptime":"1T00:37:27","Vcc":3.122,"POWER1":"OFF","FanSpeed":0,"Wifi":{"AP":1,"SSId":"HAILERIS-IoT","RSSI":84,"APMac":"8A:8A:20:57:92:A0"}}}

```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by firzanarmani** [comment]
it's happened to me too. it only lasted less than a day. i didnt flash tasmota on it at first, was using ewelink then it just stopped responding to the remote. i suspect that it's a hardware problem but i don't really know how to go about it

**Comment by ExplodingLemur** [comment]
I've opened a ticket with iTead as well but they don't seem to answer any of their support tickets :/

**Comment by ExplodingLemur** [comment]
iTead's suggestion is to pop open the case of the RF remote, hold the battery in place and press and hold the button on the back of the remote PCB while power-cycling the fan controller.  I've not gotten that to work yet though.  I plan on replacing the capacitors in my unit to match the values from my old speed control so I'll touch up the RF RX module's solder joints while I'm in there.

**Comment by ExplodingLemur** [comment]
I reflowed all the pins for the little RF daughterboard and now it's working again.  I guess this part had poor solder joints.

**Comment by firzanarmani** [comment]
@ExplodingLemur how did you reflow the pins of the RF daugtherboard?
