### ISSUE TITLE
One button - two relays. Sequential switching.

### ISSUE THREAD

**Issue by nordeep** [arendst/Sonoff-Tasmota#3398]
Hi!

I have one button and two relays.
How I can implement sequential switching. Like the following scenario:

Initial state:
Relay1 - OFF, Relay1 - OFF

1st Button push - Relay1 - ON, Relay2 - ON
2nd Button push - Relay1 - OFF, Relay2 - ON
3rd Button push - Relay1 - ON, Relay2 - OFF
4th Button push - Relay1 - OFF, Relay2 - OFF
Optional:
Button HOLD - Relay1 - OFF, Relay2 - OFF

**Comment by Jason2866** [comment]
Maybe possible with rules:
https://github.com/arendst/Sonoff-Tasmota/wiki/Rules

**Comment by ascillato2** [comment]
Hi,

Closing this issue as your questions has been addressed. Ask to reopen this issue if you need it. Thanks
