### ISSUE TITLE
Not getting any Temp data from Tasmota

### ISSUE THREAD

**Issue by citrusfizz** [arendst/Sonoff-Tasmota#34]
Updated to Tasmota (first version and now todays version)
and i can't get any data for my Temp/Humidity sensor. 
I turned on 4 debug logging and i don't see anything that says its even trying to get the data. 
it is a dht22 sensor
i have configured gpio 14 for dht22  in the web interface and tried to set the other two GPIO options the same.  tried am2301 as the device in the web configuration.
tried setting the module as a Sonoff TH instead of basic. 
nothing give me any temp data. 

not sure what else to do to get data like i did in the previous git hub project. 
here is my user_config.h   minus the irrelevant parts. 
http://pastebin.com/xfdVWN29

thanks

here is my console output

00:00:00 Config: Loaded configuration from flash at 3F8 and count 13
00:00:00 APP: Bootcount 5
00:00:00 APP: Project sonoff Sonofftemp (Topic sonoff, Fallback DVES_1C9FD0, GroupTopic sonoffs) Version 3.9.11
00:00:00 Config: Saved configuration (1196 bytes) to flash at 3F7 and count 14
00:00:00 Wifi: Checking connection...
00:00:00 Wifi: Attempting connection...
00:00:00 Wifi: Patch issue 2186
00:00:00 Wifi: Connecting to AP1 CitrusNet in mode 11N as sonoff-8144...
00:00:01 Wifi: Checking connection...
00:00:01 Wifi: Attempting connection...
00:00:02 Wifi: Checking connection...
00:00:02 Wifi: Attempting connection...
00:00:03 Wifi: Checking connection...
00:00:03 Wifi: Attempting connection...
00:00:04 Wifi: Checking connection...
00:00:04 Wifi: Attempting connection...
00:00:05 Wifi: Checking connection...
00:00:05 Wifi: Attempting connection...
00:00:06 Wifi: Checking connection...
00:00:06 Wifi: Connected
00:00:06 mDNS: Initialized
00:00:06 HTTP: Webserver active on sonoff-8144.local with IP address 192.168.1.116
00:00:06 UPnP: Multicast (re)joined
00:00:08 UPnP: Multicast disabled
00:00:08 MQTT: Attempting connection...
00:00:09 mDNS: Query done with 0 mqtt services found
00:00:09 MQTT: Connected
00:00:09 MQTT: tele/sonoff/LWT = Online (retained)
00:00:09 MQTT: cmnd/sonoff/POWER = 
00:00:09 MQTT: tele/sonoff/INFO1 = {"Module":"Sonoff Basic", "Version":"3.9.11", "FallbackTopic":"DVES_1C9FD0", "GroupTopic":"sonoffs"}
00:00:09 MQTT: tele/sonoff/INFO2 = {"WebserverMode":"Admin", "Hostname":"sonoff-8144", "IPaddress":"192.168.1.116"}
00:00:09 UPnP: Multicast (re)joined
00:00:09 RTC: (UTC) Mon Feb 06 19:58:22 2017
00:00:09 RTC: (DST) Sun Mar 26 02:00:00 2017
00:00:09 RTC: (STD) Sun Oct 29 03:00:00 2017
20:58:23 MQTT: stat/sonoff/RESULT = {"POWER":"ON"}
20:58:23 MQTT: stat/sonoff/POWER = ON
20:58:30 MQTT: tele/sonoff/STATE = {"Time":"2017-02-06T20:58:30", "Uptime":0, "POWER":"ON", "Wifi":{"AP":1, "SSID":"CitrusNet", "RSSI":60}}
20:58:36 HTTP: Handle root
20:58:37 HTTP: Handle console
20:58:41 Wifi: Checking connection...
20:58:41 Wifi: Connected
20:59:01 Wifi: Checking connection...
20:59:01 Wifi: Connected

**Comment by arendst** [comment]
Only one gpio may be configured for DHT/AMxxx so that should be gpio14. Set the others to none.

See wiki > first steps regarding sensor config.

A power cycle after configuration might help.

**Comment by citrusfizz** [comment]
I guess i wasn't to clear,  i know that gpio14 is the one that needs to be set,  i just set the others in hopes something might trigger it to work.   i tried every combination with no luck.  I read the wiki however there is nothing in the hardware modification. Power cycled many times, each while making a change,  unlike the older firmware,  this one does not even output that its trying to get data.  the older firmware would say something like CRC error, or No data available.   this one doesn't appear to have anything.   thats why i posted my config.h and the console output.

**Comment by arendst** [comment]
OK let's start off from the beginning.

Without any sensor connected but with weblog set to 3 you should see at least the following lines after a restart:
```
00:00:00 Config: Loaded configuration from flash at F8 and count 117
00:00:00 APP: Bootcount 53
00:00:00 DHT: Max clock cycles 80000
00:00:00 APP: Project sonoff th1 (Topic th1, Fallback DVES_07C8FF, GroupTopic sonoffs) Version 3.9.12
```
The third line is from the DHT code calibrating it's timer. I do not see it in your log so apparently you did non configure any GPIO for a DHT sensor.

Look in the wiki > Sensor Configuration and retry.
![sh_016](https://cloud.githubusercontent.com/assets/11044339/22738532/13e9498a-ee08-11e6-9c96-1d23ad140b6a.jpg)

**Comment by citrusfizz** [comment]
@arendst I flashed the latest 3.9.13  and sensor is working fine again.  No other changes were made. 
Greatful for everything you have done with this project.   Cheers.
