### ISSUE TITLE
Cannot send commands to sonoff basic if topic contains /

### ISSUE THREAD

**Issue by sebastianlorenzen** [arendst/Sonoff-Tasmota#340]
I have configured my sonoff basic with the following topic:
sonoff/basic_01
When I send cmnd/snonoff/basic_01/POWER ON I get back an error "Unknown command"

Wen I rename the topic on the sonoff to only basic_01
The command cmnd/basic_01/POWER ON works as expected.

Is this by design?

I want to build structures of devices with he topic eg. snonoff/floor1/bed_room/light_01

**Comment by davidelang** [comment]
inmqtt '/' has special meaning, you cannop use it in a topic

**Comment by sebastianlorenzen** [comment]
Ah, good to know. Any best practice to structure topics with multiple devices? Maybe this should be added to the wiki.
Where do I do the structuring if not in the device?

**Comment by davidelang** [comment]
topics are limited in sizr (33 characters IIRC) and cannot contain a /, #, + but 
it can contain other characters (I wouldn't use ' '), so you can use - etc

k

**Comment by sebastianlorenzen** [comment]
maybe I got it wrong how to use topics.
Here are some best practices around topics I found:
http://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices
https://tinkerman.cat/mqtt-topic-naming-convention

So my question: how to use Sonoff with Tasmota in such a setup?

Can this be implemented, that the topic allows slashes?

**Comment by arendst** [comment]
Sonoff supports <cmnd>/<devicename>/<command> <action> where you can specify
- <cmnd> up to 10 characters long including a slash.
- <devicename> up to 32 characters long without slashes
- <command> recognized by sonoff and documented on wiki - command
- <action> to be performed by command.

That's my decision and it's final (for now).

**Comment by sebastianlorenzen** [comment]
fine for me. Just did not know it is implemented like this.
Will use other elements to structure the devices.
