### ISSUE TITLE
Arduino Core 2.4.2 Released

### ISSUE THREAD

**Issue by Courty40** [arendst/Sonoff-Tasmota#3400]
I saw Core 2.4.2 Released today on Arduino, any thoughts on if it will fix some of the issues we've been seeing ?

Courty

**Comment by Jason2866** [comment]
I tried it (my first build from Tasmota on Arduino IDE, i know why using VSC!!!)
Seems good at first look, boots up ;-)

![image](https://user-images.githubusercontent.com/24528715/43650276-aa4bf0bc-973f-11e8-8968-b035d3dc6340.png)

**Comment by akpuggy** [comment]
Can you please share how you were able to test since latest espressif8266 package is still 1.7.3? I only have 1.73 and 1.50 platforms installed in Atom, so not sure what to use in the platform.io file (platform = espressif8266@?).

**Comment by Jason2866** [comment]
On Platformio still not available... 
That was the reason i setup Arduino for Tasmota. And i know why i hate it Arduino and changed!

**Comment by andrethomas** [comment]
Works for me too - Can't help but wonder what the extra ~18k of flash will give us!

**Comment by andrethomas** [comment]
@Jason2866 
![image](https://user-images.githubusercontent.com/470015/43660624-ddaec734-975f-11e8-9f4d-6b3bd3c8890f.png)

You do know you can use a 4M linker script, right?

![image](https://user-images.githubusercontent.com/470015/43660677-fe55799c-975f-11e8-8262-a144ad4cc1c1.png)

**Comment by Jason2866** [comment]
@andrethomas 
Yes i know, was build quick and dirty on Arduino (did i say i hate it?).
I have the 4M definition in platformio.ini....

**Comment by andrethomas** [comment]
@Jason2866 Gotcha... was just checking :)

**Comment by Jason2866** [comment]
HueEmulation doesnt work :-(

**Comment by andrethomas** [comment]
I also find build time to be excessive compared to 2.4.1

**Comment by Frogmore42** [comment]
Looks like PlatformIO just released an update that includes this core:
https://github.com/platformio/platform-espressif8266/releases/tag/v1.8.0

**Comment by akpuggy** [comment]
Sweet! Can now try it out next week... haulted all sonoff projects waiting for this.

**Comment by Frogmore42** [comment]
Yeah, me too.

**Comment by Jason2866** [comment]
Compiles correct under Atom / Platformio and VSC / Platformio.
WemosMini boots up and behaviour seems normal.

![image](https://user-images.githubusercontent.com/24528715/44096642-0f5d9a42-9fdc-11e8-987c-c8677f266efe.png)

**Comment by Jason2866** [comment]
Works on Sonoff Basic

![image](https://user-images.githubusercontent.com/24528715/44099986-37acfcce-9fe4-11e8-8f4f-8a049582679e.png)

**Comment by arendst** [comment]
Stage is not 2.4.2 but the next beta version. I cannot get platformio to compile 1.8.0 as it complains about SCON python problems. Probably platformio problem but I won't reinstall platformio just now. I'll wait for someone to succeed ;-)

**Comment by andrethomas** [comment]
For me it compiles under Linux CLI but I just flashed it to a device and it reboots turning the relays on momentarily and then reboots again... damn... no i have to open something LOL

**Comment by Jason2866** [comment]
@arendst 
I have in platformio.ini
platform = espressif8266@1.8.0
I think the havent changend the name in release 1.8.0 (cfd48f3 is the same as in arduino release 2.4.2!)

**Comment by andrethomas** [comment]
My linux cli version still has this

```
;platform = espressif8266@1.7.3
; *** Esp8266 core for Arduino version latest beta
;platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
; *** Esp8266 core for Arduino current version
platform = espressif8266

```

**Comment by andrethomas** [comment]
Hmm

```
tasmota@tasmota:~/tasmota/development$ platformio platform update
Platform Espressif 8266
--------
Updating espressif8266                   @ 1.8.0          [Up-to-date]
Updating framework-arduinoespressif8266  @ 2.20402.0      [2.20402.1]
Uninstalling framework-arduinoespressif8266 @ 2.20402.0:        [OK]
PackageManager: Installing framework-arduinoespressif8266 @ 2.20402.1
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
framework-arduinoespressif8266 @ 2.20402.1 has been successfully installed!
Updating tool-esptool                    @ 1.413.0        [Up-to-date]
Updating toolchain-xtensa                @ 1.40802.0      [Up-to-date]

Platform Espressif 8266
--------
Updating espressif8266                   @ 1.5.0          [Fixed]
Updating framework-arduinoespressif8266  @ 1.20300.1      [Up-to-date]
Updating tool-esptool                    @ 1.409.0        [Up-to-date]
Updating toolchain-xtensa                @ 1.40802.0      [Up-to-date]

Platform Espressif 8266
--------
Updating espressif8266                   @ 1.6.0          [Fixed]
Updating framework-arduinoespressif8266  @ 1.20400.3      [Up-to-date]
Updating tool-esptool                    @ 1.409.0        [Up-to-date]
Updating toolchain-xtensa                @ 1.40802.0      [Up-to-date]

```

**Comment by andrethomas** [comment]
![image](https://user-images.githubusercontent.com/470015/44105555-5e320426-9ff2-11e8-8f3c-dcfd0b9bb447.png)

**Comment by Jason2866** [comment]
@andrethomas 
Looks good 👍

**Comment by Courty40** [comment]
I’ve had a couple of devices (the older ones) that have needed the flash/eeprom cleared and to start again before the are stable. May be related to some of the issues here ?

**Comment by Jason2866** [comment]
@Courty40 
Everyone (here in this thread) should the devices now get running with 1.8.0 aka 2.4.2 :-)
Using Platformio (Atom) with entry in platformio.ini
platform = espressif8266@1.8.0
and a `pio update`

**Comment by andrethomas** [comment]
@Jason2866 I'm tentative on jumping to conclusions on devices that are hard to get to :)

**Comment by Jason2866** [comment]
@andrethomas 
I did not say always the easy way :-) -> Dont fix aint broken

**Comment by andrethomas** [comment]
@Jason2866 Now you're just reminding me of a new way of comparative statement methods I learnt here which never occurred to me before

I always did
`if (variable == known)`
Here I learn
`if (known == variable)`

LOL

**Comment by arendst** [comment]
Well at least platformio now has the correct core 2.4.2 version when 1.8.0 is selected. See https://community.platformio.org/t/espressif-32-8266-new-boards-esp-prog-bug-fixes-for-esp-idf-and-arduino-frameworks/4766

Now someone has to find out if all problems with previous versions have been solved...

I know the Hue fix is not in the 2.4.2 webserver code so that still needs to be patched locally.

**Comment by arendst** [comment]
Do you experience quick webpage updates like with previous versions? I tried two wemos with 2.4.2 and they respond very slow; the answer is shown on serial interface at least three seconds before the webpage console is updated...

**Comment by wasi54** [comment]
Webpage update takes less than 0.1 sec. for Power on/off via mqtt and Wifi is stable and fast since 6.1.1c with STAGE!
I am using on Basic,Dual V2 and TH:
-DPIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
 
![grafik](https://user-images.githubusercontent.com/6075168/44165603-7f55cc00-a0c9-11e8-86b6-06a74a0d6a6d.png)

![grafik](https://user-images.githubusercontent.com/6075168/44165662-a6140280-a0c9-11e8-95fd-fb4b3a6de3f0.png)

**Comment by Jason2866** [comment]
@arendst 
I have the feeling that sometimes with 2.4.2 the webconsole reacts some milliseconds later than with 2.3.0
But it isnt laggy in any way! If i do the same thing again the response is faster as it is with 2.3.0.
For me is 2.4.2 is working fine so far. I will measure if sleep is working. If yes i will update some more devices (which are easily reachable)...

**Comment by arendst** [comment]
Just did a recompile and now it's working fine....

**Comment by andrethomas** [comment]
Wish I could recompile myself... perhaps I will also work fine :)

**Comment by Jason2866** [comment]
@andrethomas 
human code has self correction build in. No recompile neccersary;-)

**Comment by andrethomas** [comment]
@Jason2866 Not having to reboot for a few days and still work properly would be nice though :-)

**Comment by Jason2866** [comment]
@andrethomas Total off topic anyway. At my last reboot i lost some memory😎

**Comment by andrethomas** [comment]
@Jason2866 Yeah, make us a channel on Discord so we can goof off there.

I've uploaded the new code to the sonoff dual that controls my overhead lights in my lab... easy to get to in case it fails.

**Comment by Jason2866** [comment]
@andrethomas 
Just fired up Discord (first time): https://discord.gg/Ks2Kzd4

**Comment by andrethomas** [comment]
No memory leak so far...

**Comment by ascillato** [comment]
Hi,

Up to now, in my devices there was no freeze nor exception with v2.4.2 with lwIP 1.4 (at 80Mhz) since I flash them. It also seems that the webserver works faster. :smile: 

The only downside of v2.4.2 is that `sleep` will freeze the device. :disappointed: 

So, if you are going to use `SLEEP`, you need to use v2.3.0. If not, use v2.4.2 lwIP 1.4

In my tests, v2.4.2 with lwIP 2 led to reboots with exceptions.

**Comment by ascillato** [comment]
I like the Discord chat you have opened. What about making that the official chat for Tasmota? We can add that to the readme / wiki.

**Comment by Jason2866** [comment]
Hi @ascillato 
why not?! Let Us try. Maybe we can move  the non issue stuff out of here. 
A another benefit users can get a direct response there.

**Comment by ascillato2** [comment]
Hi,

Closing this issue as esplib v2.4.2 is working fine except from sleep feature.

Please, ask to reopen if needed. Thanks all for the tests and comments. :+1:
