### ISSUE TITLE
[Question] How to publish "Toggle" to topic

### ISSUE THREAD

**Issue by RaymondMouthaan** [arendst/Sonoff-Tasmota#3403]
Guess,

I've been reading [Understanding-SwitchMode-and-SwitchTopic](https://github.com/arendst/Sonoff-Tasmota/wiki/Understanding-SwitchMode-and-SwitchTopic), but it's not clear to me.

What i like to do, is to read "high" or "low" from a Wemos digital input and publish "toggle" to a topic, so basically when a button is pressed Tasmota publishes "toggle" to the topic and the same when the button is released.

Hope someone can point me in the right direction ...

Greetz,
Ray

**Comment by andrethomas** [comment]
What MQT output is generated when you change the state of your input pin? How did you configure the pin?

**Comment by andrethomas** [comment]
There is probably an easier way but I would just create a rule that responds to the Switch1=ON and Switch1=OFF and do publish xxx - Check the rules wiki for examples https://github.com/arendst/Sonoff-Tasmota/wiki/Rules

**Comment by RaymondMouthaan** [comment]
Maybe there is an easier way, but for now I am trying rules, but so far no success, because i am facing rules for the first time. Not sure yet how to set-up the correct rule for this.

**Comment by andrethomas** [comment]
`cmnd/wemos-1/POWER1`
Actually, the "wemos-1" is configured for a specific device in the MQTT configuration - in my test board below its still in the default of sonoff

![image](https://user-images.githubusercontent.com/470015/43677248-0be40494-97ff-11e8-92f7-b14ae489746f.png)

**Comment by RaymondMouthaan** [comment]
yeah thats what i know, but why is the toggle send to cmnd/2/POWER1 instead of cmnd/wemos-1/POWER1 ?

**Comment by andrethomas** [comment]
Does your full-topic still look like mine above?

**Comment by andrethomas** [comment]
You must use SwitchTopic=0, I guess

**Comment by RaymondMouthaan** [comment]
Yes it is
![screen shot 2018-08-04 at 16 01 01](https://user-images.githubusercontent.com/25717738/43677281-9dcd8380-97ff-11e8-9742-c8900670129f.png)

**Comment by andrethomas** [comment]
Issue command
switchtopic "wemos-1"

**Comment by RaymondMouthaan** [comment]
I've set back SwitchTopic to 0 (which is the default)
![screen shot 2018-08-04 at 16 02 44](https://user-images.githubusercontent.com/25717738/43677292-e11ebcbc-97ff-11e8-94de-618fab6019b7.png)

Toggle is not published anymore

**Comment by andrethomas** [comment]
Try
switchtopic "wemos-1"
?

**Comment by andrethomas** [comment]
Actually without the "

switchtopic wemos-1

Then I get

15:08:55 MQT: cmnd/wemos-1/POWER = TOGGLE

**Comment by RaymondMouthaan** [comment]
I just did, and your are the man!!!

That just did it, yeeaaaayyy 

However .. I think there is a bug ...

I tried the command like you said:
`switchtopic "wemos-1"`

which results in:
![screen shot 2018-08-04 at 16 07 30](https://user-images.githubusercontent.com/25717738/43677329-89683524-9800-11e8-8fe8-c2ab622ba6e9.png)

But those quotes should be there in the topic so I tried:
`switchtopic wemos-1` (without those quotes)

and its result is:
![screen shot 2018-08-04 at 16 09 46](https://user-images.githubusercontent.com/25717738/43677349-dcfe119a-9800-11e8-9768-afa2a97be800.png)

**Comment by andrethomas** [comment]
You just forced me to learn about switchtopic :)

Well done!

**Comment by RaymondMouthaan** [comment]
Hahaah great, but its not working for me without quotes :(

**Comment by RaymondMouthaan** [comment]
alright this becomes more strange ... 

`switchtopic wemos-1` fails as you could see in my previous screenshot
`switchtopic wemos-2` succeeded with the toggle as expected

**Comment by andrethomas** [comment]
Makes sense to use something other than current default topic

**Comment by andrethomas** [comment]
I get the same result if I use the same topic as my board uses... so it has to be different from the default

**Comment by RaymondMouthaan** [comment]
Yes, for testing I just changed the default topic wemos-1 from the mqtt config page to wemos-bla and set switchtopic wemos-1 on the command line, and now it works

**Comment by RaymondMouthaan** [comment]
I just wonder what if you have 2 or more switches, seems to me all switches share the same topic defined by switchtopic <topic> .. this makes it not possible to distinguish the switch that was pressed ..

but for now I am helped, since I am planning to only attach 1 switch to one Wemos.

@andrethomas thanks for your help!!! 👍

**Comment by andrethomas** [comment]
You're welcome.

Just tested multiple switches and it changes the POWERx (x)

```
15:28:17 MQT: cmnd/wemos/POWER1 = TOGGLE
15:28:18 MQT: cmnd/wemos/POWER2 = TOGGLE
```

POWER1 = Switch1
POWER2 = Switch2

**Comment by RaymondMouthaan** [comment]
Oooww thats really nice! .. could you post screenshots of your config and the exact commands ?

I didn't manage to get it work like you

**Comment by andrethomas** [comment]
Nothing different just configured Switch2 on another pin

![image](https://user-images.githubusercontent.com/470015/43677574-3b38a2f4-9804-11e8-8522-fffc8cf18ac2.png)

**Comment by RaymondMouthaan** [comment]
Aha while you posted your config .. I found out to configure RELAY 1 and 2 as well, this shows up as POWER1 and POWER2 👍

**Comment by andrethomas** [comment]
Good stuff, enjoy!

**Comment by RaymondMouthaan** [comment]
I will! .. Thanks again and enjoy your day 👍
