### ISSUE TITLE
add a device to the supported devices

### ISSUE THREAD

**Issue by alekseyn1** [arendst/Sonoff-Tasmota#3405]
Hello, hopefully admins can update the wiki with the following devices/boards. Brands differ widely but the board indication is the same "KS-602"
https://ucexperiment.wordpress.com/2017/11/14/reprogramming-a-lyasi-wifi-wall-switch-with-esp8285/

the article is mostly accurate. the only correction is that in the first part, to get the board into the flash mode, you need to connect the ground to the other side of the resistor and not the chip side as it states in the article.

Also the led behavior on those is the opposite from what it's supposed to be. It's on when the device is on and off when it's off.

These work well when selecting "sonoff touch" in the board config

**Comment by Frogmore42** [comment]
If you can create an issue, you can add to the wiki.  There should be an edit button/option.
