### ISSUE TITLE
Two ultrasonic sensors on nodemcu (US-100 and JSN-SR04Tv2)

### ISSUE THREAD

**Issue by rajil** [arendst/Sonoff-Tasmota#3407]
Hello,
I have two ultrasonic sensors [US-100](https://www.bananarobotics.com/shop/US-100-Ultrasonic-Distance-Sensor-Module) and [JSN-SR04T ](https://www.amazon.com/CHENBO-Waterproof-Ultrasonic-Integrated-Transducer/dp/B01MU0XG51) which i would like to use with nodemcu. Both these sensors work if they are connected alone to nodemcu. However, when both the sensors are connected the webui only shows the output from a single sensor.

My module setup is as follows:
![image](https://user-images.githubusercontent.com/379266/43677779-6f52e7ca-97cd-11e8-9c76-e5368ac79807.png)

The devices connected are:
ADS1115 on D2 and D1, and [pressure transducer](https://www.amazon.com/0-1-2-Pressure-Transducer-Sensor-Diesel/dp/B01IR2MANC) on A3 pin of ADS1115
US-100 on D5 (trigger) and D6 (echo)
JSN-SR04T on D7 (trigger) and D0 (ech0)

Only US-100 output is being shown on webui,

![image](https://user-images.githubusercontent.com/379266/43677823-2cbdae62-97ce-11e8-8c25-bf6885a91b8d.png)

How can i get both the ultrasonic sensors to show up?

Bonus question: Where is the LM75AD sensor reading coming from?

**Comment by andrethomas** [comment]
`Bonus question: Where is the LM75AD sensor reading coming from?`

You either have a LM75AD on the same I2C bus or another device which uses the same I2C address range... 0x48 - 0x4F and its a false detect

**Comment by andrethomas** [comment]
Hmm, the ADS is on the same range so its a false detect for sure... will have to look at the LM75AD driver to see if I can avoid false detect but it pretty much gives valid responses on anything from what I remember... for now disable LM75AD in the config file.

**Comment by andrethomas** [comment]
False detection should be solved by proposed PR https://github.com/arendst/Sonoff-Tasmota/pull/3408

**Comment by andrethomas** [comment]
@rajil 
To get back to you on the original problem - from what I can see in the driver code only a single SR04 device is supported - I do not think the code knows how to differentiate between the two modules you have connected at this time.

**Comment by ascillato2** [comment]
Hi,

> How can i get both the ultrasonic sensors to show up?

That feature is not supported by Tasmota.

If you feel your questions has been addressed, please close this issue. Thanks

**Comment by ascillato2** [comment]
Hi,

Closing this issue as there is no feedback. Please, ask to reopen if needed. Thanks.
