### ISSUE TITLE
Can be flashed? - not an issue

### ISSUE THREAD

**Issue by cirolaferrara** [arendst/Sonoff-Tasmota#3411]
Can be flashed with tasmota? https://www.amazon.it/dp/B077BR6Y1Q/ref=cm_sw_r_cp_apa_iDRzBb9F516D4

What do you think?

**Comment by andrethomas** [comment]
It would depend on what the electronics inside are - do you have one? Can you open it up and check?

**Comment by reloxx13** [comment]
looks like this: https://github.com/arendst/Sonoff-Tasmota/wiki/Lingan-SWA1

**Comment by reloxx13** [comment]
btw i would not buy from sellers who push the price a few days before a special offer

![grafik](https://user-images.githubusercontent.com/14855001/43689181-a1550d00-98f6-11e8-9cf2-48ed7eaa3ba4.png)

**Comment by andrethomas** [comment]
Indeed it does... worth the try

**Comment by cirolaferrara** [comment]
@reloxx13 I can't open it. I'm just asking before buy it. Anyway thanks
