### ISSUE TITLE
iFan02 Speed Increase and Decrease functions

### ISSUE THREAD

**Issue by LuckyStyle** [arendst/Sonoff-Tasmota#3415]
Feature Request:

It would be great if the iFan02 commands had the following:

FanSpeed + (increase speed by 1)
FanSpeed - (decrease speed by 1)

If speed at 3 then an increase would reset back to 0.

If speed at 0 then an a decrease would take speed back up to 3.

I have a sonoff basic wired to the fan controls at bottom of the fan by the light. I have an HA script that controls the speed of the fan when the switch is pulled, but it would so much better if the increase/decrease functionality was incorporated into tasmota.

**Comment by digiblur** [comment]
Can you do this with your home automation software?  I was planning on doing this with NodeRed myself with the button.

**Comment by LuckyStyle** [comment]
Yes , I have my Home Assistant running a script. Just thought it would nice to have that functionality included in the tasmota software.

**Comment by LuckyStyle** [comment]
Thank You So Much!

**Comment by RubberDinero** [comment]
Can a setoption be created to remove fanspeed looping? If 0 and - is sent, don't loop to 3? And if at 3 and + is sent, don't go to 0?
