### ISSUE TITLE
How to use the three switch mode?

### ISSUE THREAD

**Issue by 1043717432** [arendst/Sonoff-Tasmota#342]
Sonoff firmware has been programmed to write successfully, how to open the three switch mode?
May I ask how the e8266 firmware can be modified using three switch modes?

**Comment by davidelang** [comment]
what do you mean by "the three switch mode"?

**Comment by 1043717432** [comment]
Modify the relay?

**Comment by Satellietje** [comment]
Do you mean this?
3 additional relay at one sonoff basic.
on GPIO4 I have a temperature sensor, but it can also a watersensor or whatever.

![8-4-2017 6-50-27](https://cloud.githubusercontent.com/assets/26080895/24825818/b668596a-1c27-11e7-99d4-2fb6fc4930c2.jpg)

![8-4-2017 6-57-39](https://cloud.githubusercontent.com/assets/26080895/24825870/c080442a-1c28-11e7-8326-ab115a931cad.jpg)

**Comment by 1043717432** [comment]
@Satellietje 

Hello, powerful! Can you provide detailed contact maps? Temperature and humidity is how to connect ?
![qq 20170408141742](https://cloud.githubusercontent.com/assets/22461690/24826406/14118d26-1c68-11e7-8dd7-3fbf538574d0.jpg)
![qq 20170408141738](https://cloud.githubusercontent.com/assets/22461690/24826408/1596f0be-1c68-11e7-94ca-ce0808798fac.jpg)
I am to modify the e8266 programming sonoff, how to set the parameters in the Module sonoff parameters, I am a three touch switch.

**Comment by Satellietje** [comment]
This is GPIO4
![8-4-2017 9-10-58](https://cloud.githubusercontent.com/assets/26080895/24826661/59c719d0-1c3b-11e7-8b0c-aa8b57de5d58.jpg)

![8-4-2017 9-13-55](https://cloud.githubusercontent.com/assets/26080895/24826675/c129116e-1c3b-11e7-83bc-27fa849eaa71.jpg)

![8-4-2017 9-15-07](https://cloud.githubusercontent.com/assets/26080895/24826684/e51e9ea4-1c3b-11e7-87ca-df236852aaaf.jpg)

![8-4-2017 9-16-46](https://cloud.githubusercontent.com/assets/26080895/24826711/63c09a46-1c3c-11e7-9ba9-dd54fef47a87.png)

**Comment by AlexTransit** [comment]
![img_20170408_122705](https://cloud.githubusercontent.com/assets/15162113/24826781/34d87e04-1c57-11e7-903a-4b57d1d5d6a4.jpg)

**Comment by 1043717432** [comment]
@AlexTransit Hello, what is this?

**Comment by 1043717432** [comment]
@Satellietje Hello, thank you! I try to buy accessories!

**Comment by AlexTransit** [comment]
@1043717432 Hi. I remove led and use free gpio12.  :)

**Comment by Satellietje** [comment]
What's that for a switch in the picture

**Comment by 1043717432** [comment]
@AlexTransit  Hello, your picture is not clear, call gpio12 can do?

**Comment by 1043717432** [comment]
@Satellietje  Hello, use e8266 single fire switch, no zero line. I have written to sonoff, but there is a problem, I do not know how to set up to support the function of 2 or 3 relay switch. I want to know!

**Comment by 1043717432** [comment]
@Satellietje  Hello, may I ask you the first picture of the sonoff connection 3 relays, a detailed connection diagram?

**Comment by davidelang** [comment]
to set it up to support up to 4 relays, just wire the relays to GPIO pins and 
configure them as relay2, relay3, or relay4 (it can be done via the webserver in 
the module configuration page, or via commands, see the wiki for the commands)

**Comment by 1043717432** [comment]
@Satellietje  Hello, I have 2 switch and 3 switch 2 switch now, I can choose the sonoff basic parameter setting module, should be supported, but the 3 do not know how to choose the switch panel module parameters, after all, sonoff 4CH is 8285.

**Comment by 1043717432** [comment]
@Satellietje Hello, thank you for sharing!

**Comment by 1043717432** [comment]
@Satellietje After I go home, I'll upload 3 pictures.

**Comment by davidelang** [comment]
switches are inputs, relays are outputs. if you want the sonoff to turn 
something on and off you need to set it to be a relay, not a switch

**Comment by 1043717432** [comment]
@davidelang  Hello, I am not sonoff, just write the sonoff firmware e8266,

**Comment by davidelang** [comment]
I don't understand what you are saying.

**Comment by 1043717432** [comment]
@davidelang @Satellietje @AlexTransit  
![qq 20170409004706](https://cloud.githubusercontent.com/assets/22461690/24830730/24614134-1cbe-11e7-90fd-ded5e59e299d.jpg)

**Comment by davidelang** [comment]
that tells me nothing.

**Comment by davidelang** [comment]
closing this issue as there has been no response in two weeks. If you are still working on this, go ahead and re-open the issue.

**Comment by 1043717432** [comment]
@AlexTransit  hi，You remove the LED, GPIO12 re-access to other LED lights can be dimmed?
How to achieve
