### ISSUE TITLE
Button 1 always on

### ISSUE THREAD

**Issue by bruno-wladimir** [arendst/Sonoff-Tasmota#3420]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://forum.digital-pig.com/)
- [x ] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [ x] Hardware used : Sonoff T1 US
- [ ] Provide the output of command ``status 0`` :
```
When powering the Sonoff T1, button 1 is active by default, would it be a software or hardware problem? I already tested in 2 modules (2 gang and 3 gang) and the same error happens!

```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Have you read the wiki?
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-T1-UK-and-T1-EU

**Comment by bruno-wladimir** [comment]
Yes! I can flash the firmware perfectly, but the buttons are ON by default

**Comment by Frogmore42** [comment]
If you mean the relay turns the power on by default, there is a setting that controls that.  It is described in the wiki, as is how to change that.

If that is not what you mean by button 1 is active by default, you will need to use some other words to describe the behavior you are seeing.  Include the web/serial log showing the bad behavior.

**Comment by bruno-wladimir** [comment]
seems to be a hardware problem, even without firmware the button stays active!  I tested the same code in another module and it works perfectly

**Comment by Frogmore42** [comment]
Please close the issue then.

**Comment by bruno-wladimir** [comment]
@AdighaLogic  I think it's a hardware problem, even if the firmware is not active by default, your choice only applies to Firmware Tasmota right?

**Comment by AdighaLogic** [comment]
Correct, I believe you're right. if the firmware is not active by default, then it must be a hardware issue.
I just flashed 2 T1 US version 2 Ch and everything went smooth. but on the first power up the first button comes on automatically, so i set option 13 to 1 and that problem went a way.
