### ISSUE TITLE
Unable to compile for ESP8285 in PlatformIO

### ISSUE THREAD

**Issue by tofublock** [arendst/Sonoff-Tasmota#343]
Similar to #72 I'm unable to build for my Sonoff Touch using PlatformIO. It keeps telling me
`Error: The program size (473615 bytes) is greater than maximum allowed (434160 bytes)`
I've updated the IDE and am trying to compile the latest release (4.1.2).
What am I doing wrong?
Thanks!

> [env:esp8285]
> platform = espressif8266
> board = esp8285
> framework = arduino
> board_flash_mode = dout
> build_flags = -Wl,-Tesp8266.flash.1m64.ld -DMQTT_MAX_PACKET_SIZE=512
> lib_deps = PubSubClient, ArduinoJSON, NeoPixelBus, IRremoteESP8266

**Comment by davidelang** [comment]
you probably just need to disable some features in user_config.h to get it down 
to an acceptable size.

although, I'm not sure why it's listing as small a max size as it is.

David Lang
k

**Comment by MacWyznawca** [comment]
@tofublock 
You must „quoted” some options.
Ex. #define USE_I2C 
#define USE_WS2812 
#define USE_IR_REMOTE

**Comment by tofublock** [comment]
I've tried commenting out almost everything (I2C, DS18B20, WS2812, Domoticz) but still too big...

**Comment by davidelang** [comment]
what do you still have enabled?

**Comment by tofublock** [comment]
MQTT, webserver, discovery.

**Comment by tofublock** [comment]
Hm, if I do away with discovery as well it seems to work. But is that the way it should be?

**Comment by davidelang** [comment]
that probably dropped you below the size limit.

David Lang
k

**Comment by tofublock** [comment]
It actually didn't. Size is now 438240.
I flashed it and did an OTA upgrade with the official build. The info page now tells me

> Program flash size	1024kB
> Program size	464kB
> Free program space	472kB

Probably some wrong configuration in PlatformIO...
Thanks for the help so far!

**Comment by arendst** [comment]
Known problem with platformIO. That's why I provided an updated platformio.ini a month ago...

**Comment by tofublock** [comment]
As I said, I used the platformio.ini you provided and referenced in #72, but that didn't help. If I upload via OTA, do I get full functionality or is that stored in persistent memory?

**Comment by arendst** [comment]
As I said I provided an updated platformio.ini a month ago very different from the one shown in #72 as the platformio advertized esp8285 is totally different from the 'stock' esp8285 used by itead and most others. It's a mistery to me why they call their esp8285 board that way as it has a lot less flash available...

functionality is partly stored in memory but if you look at the released user_config.ino file you'll see what you miss by using the provided image.

**Comment by tofublock** [comment]
Okay, I see where my mistake was. I thought I still had to edit the board to say esp8285 instead of leaving it at esp01_1m. Everything is working perfectly now.
Thanks for the great support and for an awesome custom firmware! :)

**Comment by Slip7000** [comment]
Hi @tofublock 

So you only changed the: board_flash_mode = dout 
and it worked ?

**Comment by LexPrima** [comment]
@tofublock wow fiddling around for hours and all I had to do was change nothing. Thank you mate, it's working now.

**Comment by tofublock** [comment]
@Slip7000 Yeah, that's what did the trick for me.

A silly pitfall that made me feel pretty stupid. ;)

**Comment by Slip7000** [comment]
Thank you for the reply but I'm still facing this problem. Tried to changed them to dout qio and dio but no luck, on all the it loaded successful but no lights or not switching on at all. please help

On Apr 26, 2017, at 11:18 PM, tofublock <notifications@github.com<mailto:notifications@github.com>> wrote:


@Slip7000<https://github.com/Slip7000> Yeah, that's what did the trick for me.

A silly pitfall that made me feel pretty stupid. ;)

**Comment by tofublock** [comment]
@Slip7000 fresh clone, change nothing but the flash mode and it doesn't work?
