### ISSUE TITLE
Individual commands for Hue, Saturation and Brightness

### ISSUE THREAD

**Issue by titus-leistner** [arendst/Sonoff-Tasmota#3430]
**Have you look for this feature in other issues and in the wiki?**
Yes

**Is your feature request related to a problem? Please describe.**
I'm currently working on a HomeKit-MQTT-Bridge. HomeKit sends **different messages for H, S and B**. Therefore, a direct mapping is not possible.

**Describe the solution you'd like**
It would be a nice feature to have **individual commands for Hue, Saturation and Brightness**.

**Describe alternatives you've considered**
I can cache the current values for each device and concat them together if a new value occurs, but that is kind of a dirty hack and leads to more problems.

**Comment by gitolicious** [comment]
That would also be helpful for my [MagicHome LED controller](https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-LED-strip-controller) which has R, G, B and W values. Tried solving this in [NodeRed](https://nodered.org/) but ended up with a giant mess of conversions in order to link it to [openHab](https://www.openhab.org) items.

**Comment by kevinshane** [comment]
yes, please! It would be awesome when adding this type of bulb into homekit!

**Comment by ascillato** [comment]
Hi,

With the PR #3615 now has been added individual `HSBCOLOR` commands for better integration to HomeKit and OpenHab.

Usage:

`HSBCOLOR1 <x>` to set Hue
`HSBCOLOR2 <x>` to set Saturation
`HSBCOLOR3 <x>` to set Brightness

Still is supported previous command HSBCOLOR <hue>,<sat>,<bri>

Hope this solves your issue.

Please, test it.

**Comment by kevinshane** [comment]
Hi, not sure if it's a bug, when I type comand in webconsole
`HsbColor2 50` or `HsbColor3 20` it always reflect to `HsbColor1`, the `2` and `3` donsn't work at all?
```
10:36:52 CMD: HsbColor1 30 //Here I change Hue to 30, it's working
10:36:52 MQT: stat/ailight/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFA34700","HSBColor":"30,72,100","Channel":[100,64,28,0]}
10:36:52 MQT: stat/ailight/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFA34700","HSBColor":"30,72,100","Channel":[100,64,28,0]}
10:37:03 CMD: HsbColor3 20 //Here I want to change Bri to 20, but result in Hue changed
10:37:03 MQT: stat/ailight/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FF844700","HSBColor":"20,72,100","Channel":[100,52,28,0]}
10:37:03 MQT: stat/ailight/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FF844700","HSBColor":"20,72,100","Channel":[100,52,28,0]}
10:37:20 CMD: HsbColor2 50 //Here I want to change Sat to 50, but result in Hue again
10:37:20 MQT: stat/ailight/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFE04700","HSBColor":"50,72,100","Channel":[100,88,28,0]}
10:37:20 MQT: stat/ailight/RESULT = {"POWER":"ON","Dimmer":100,"Color":"FFE04700","HSBColor":"50,72,100","Channel":[100,88,28,0]}
```

**Comment by arendst** [comment]
Investigating...

**Comment by ascillato** [comment]
Ups!

Thanks :+1:

**Comment by ascillato** [comment]
@kevinshane Can you test is again with latest version? Thanks :+1:

**Comment by kevinshane** [comment]
Confirmed the latest version is working like a charm ^^
Thanks @ascillato for the PR and @arendst for the fix
