### ISSUE TITLE
Upload stalls at 86%.

### ISSUE THREAD

**Issue by phathak** [arendst/Sonoff-Tasmota#3446]
Hi,

I'm attempting to upload the firmware to a Sonoff basic R2 V1.0 using Atom and PlatformIO under High Sierra. I specified the upload port to be `upload_port = /dev/cu.usbserial-A50285BI
` in platformio.ini. The building goes well, then the upload stalls at 86%. As you can see in the screenshot below, the upload has been going on for 11 minutes. 

![screen shot 2018-08-09 at 10 55 19 pm](https://user-images.githubusercontent.com/13324297/43936777-28331c5c-9c28-11e8-9c65-bdd9ecf4fabd.png)

Any help is appreciated.
Thank you

**Comment by phathak** [comment]
Ok I’ll try that tonight. Thank you

Sent from my iPhone

On Aug 10, 2018, at 1:23 AM, Frogmore42 <notifications@github.com<mailto:notifications@github.com>> wrote:


Try lowering the baud rate. Maybe it is getting some error that it is not detecting properly.

**Comment by Frogmore42** [comment]
Since apparently that worked, please close this issue.

**Comment by phathak** [comment]
I was able to flash 4 out 5 sonoffs I have by retrying 5-6 times and eventually it would flash. There’s still one that doesn’t want to go through. Changed the upload speed and it didn’t catch any error and would stall the same way.

Thank you

Sent from my iPhone

On Aug 16, 2018, at 1:38 AM, Frogmore42 <notifications@github.com<mailto:notifications@github.com>> wrote:


Since apparently that worked, please close this issue.
