### ISSUE TITLE
ENERGY.Period not always sent

### ISSUE THREAD

**Issue by bennybubble** [arendst/Sonoff-Tasmota#3447]
I'm using a Sonoff power R2 with 6.1.1c and I notcied that the Period data is not always sent:

08:14:40 MQT: tele/sonoff192/SENSOR = {"Time":"2018-08-10T08:14:40","ENERGY":{"Total":1.886,"Yesterday":0.747,"Today":0.246,**"Period":8**,"Power":92,"Factor":0.59,"Voltage":236.7,"Current":0.652}}
08:19:01 MQT: tele/sonoff192/SENSOR = {"Time":"2018-08-10T08:19:01","ENERGY":{"Total":1.892,"Yesterday":0.747,"Today":0.252,"Power":0,"Factor":0.00,"Voltage":238.7,"Current":0.000}}

Is this by design or not?
I'm saving this data to display the energy used in 5 minutes interval.

-ben

**Comment by curzon01** [comment]
`Period` isn't sent if TelePeriod is set to 0 - set TelePeriod &ne; 0

**Comment by bennybubble** [comment]
Hi,

TelePeriod is set to 300 : **14:29:22 MQT: stat/sonoff192/RESULT = {"TelePeriod":"300"}**

-ben

**Comment by curzon01** [comment]
Another condtion **Period** will not shown is if internal tele period timer is zero - in that case there is no period data and it will not be part of the result.

So this is by design.

**Comment by bennybubble** [comment]
Hi,

Even if period = 0, it is still reported : 

[code snippet from console]
![image](https://user-images.githubusercontent.com/1083428/43961271-bafd2a00-9cb4-11e8-8577-da847846fe68.png)

1st line Period:8
2nd line NO period
3rd line Period:0

This is inconsistent and openhab (for my homeautomation) will issue an error (on the 2nd line) since it doesn't find Period.

-ben

**Comment by arendst** [comment]
Period is only send when teleperiod is finished for the simple reason that it calculates the power used between teleperiod moments. When an energy status is requested outside the teleperiod timestamp it cannot know the period power usage as it does not know the period time to calculate.

So update your openhab receiver to be clever enough to handle a message without a period field.
