### ISSUE TITLE
Upload Pictures BlitzwoIF SHP2

### ISSUE THREAD

**Issue by helmar74** [arendst/Sonoff-Tasmota#3448]
Hi,

I'm creating a Wiki Page for the BlitzwoIF SHP2.
Could someone Upload the pictures, so that I can link it?
Thanks a lot!
![blitzwoif_shp2_esp_pins](https://user-images.githubusercontent.com/25499089/43945384-3534d26a-9c82-11e8-8a46-95bb2a82ee65.png)
![blitzwoif_shp2_screws](https://user-images.githubusercontent.com/25499089/43945385-354fab6c-9c82-11e8-9d13-d405102a96bd.png)
![blitzwoif_shp2_shortwire_at_start](https://user-images.githubusercontent.com/25499089/43945386-356ba65a-9c82-11e8-808d-6f00a9520092.jpg)
![blitzwoif_shp2_cabeling](https://user-images.githubusercontent.com/25499089/43945387-358d35c2-9c82-11e8-8031-27754090e50c.jpg)

**Comment by curzon01** [comment]
You already has done this by creating and drop your images within this issue :grin:
- https://user-images.githubusercontent.com/25499089/43945384-3534d26a-9c82-11e8-8a46-95bb2a82ee65.png
- https://user-images.githubusercontent.com/25499089/43945385-354fab6c-9c82-11e8-9d13-d405102a96bd.png
- https://user-images.githubusercontent.com/25499089/43945387-358d35c2-9c82-11e8-8031-27754090e50c.jpg

**Comment by helmar74** [comment]
Haha! Thanks a lot.
I didn't know ;-)
