### ISSUE TITLE
rf bridge sonoff not RfReceived if the sensor does not stop emitting

### ISSUE THREAD

**Issue by turin400** [arendst/Sonoff-Tasmota#3450]
I have a problem with the rf bridge of sonoff, send by mqtt the svalue only when the emitter stops emitting. for example, with the emitter of four buttons when I stop pressing send svalue by mqtt. This is a problem when I use the digoo water sensor, when it detects water leak it emits but the bridge only sends it by mqtt to domoticz when it stops seeing water with which it does not work correctly. The same problem with the PIR.
I do not know if you could have it send the code by mqtt after the first telegram end even if the sensor is constantly sending the signal.
I feel my English, a greeting and good work.

**Comment by turin400** [comment]
That does not happen to me and that's what I need.
When the button on my remote control was held 4 buttons, nothing appears on the console and when I release the button, Rf is displayed.

I have the R2 version of the sonoff bridge.
There is no version of the bridge and of tasmota you have or if I have to configure something special.

Thanks for everything.

00:00:00 Project sonoff RFBridge433 (Topic RFBridge433, Fallback DVES_82517C, GroupTopic sonoffs) Version 6.1.1-2_3_0
00:00:00 WIF: Connecting to AP1 ATICO in mode 11N as RFBridge433...
00:00:06 WIF: Connected
00:00:06 DNS: Initialized
00:00:06 HTP: Web server active on RFBridge433.local with IP address 192.168.8.182
00:00:07 MQT: Attempting connection...
00:00:07 MQT: Connected
00:00:07 MQT: tele/RFBridge433/LWT = Online (retained)
00:00:07 MQT: cmnd/RFBridge433/POWER = 
00:00:07 MQT: tele/RFBridge433/INFO1 = {"Module":"Sonoff Bridge","Version":"6.1.1","FallbackTopic":"DVES_82517C","GroupTopic":"sonoffs"}
00:00:07 MQT: tele/RFBridge433/INFO2 = {"WebServerMode":"Admin","Hostname":"RFBridge433","IPAddress":"192.168.8.182"}
00:00:07 MQT: tele/RFBridge433/INFO3 = {"RestartReason":"Software/System restart"}
17:39:39 MQT: tele/RFBridge433/STATE = {"Time":"2018-08-11T17:39:39","Uptime":"0T00:00:15","Vcc":3.190,"Wifi":{"AP":1,"SSId":"ATICO","RSSI":100,"APMac":"FA:1A:67:A5:E0:E7"}}
17:39:51 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":12950,"Low":400,"High":1270,"Data":"D5D038","RfKey":"None"}}
17:39:51 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"14012472","Battery":57,"RSSI":10}
17:40:08 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":12950,"Low":400,"High":1270,"Data":"D5D038","RfKey":"None"}}
17:40:08 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"14012472","Battery":57,"RSSI":10}
17:40:22 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":12960,"Low":400,"High":1270,"Data":"D5D038","RfKey":"None"}}
17:40:22 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"14012472","Battery":57,"RSSI":10}

**Comment by Jason2866** [comment]
You are receiving something!

17:39:51 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":12950,"Low":400,"High":1270,"Data":"D5D038","RfKey":"None"}}
17:39:51 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"14012472","Battery":57,"RSSI":10}
17:40:08 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":12950,"Low":400,"High":1270,"Data":"D5D038","RfKey":"None"}}
17:40:08 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"14012472","Battery":57,"RSSI":10}
17:40:22 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":12960,"Low":400,"High":1270,"Data":"D5D038","RfKey":"None"}}

**Comment by Jason2866** [comment]
Are you sure that the remote is sending if button is pressed and hold?
It could be that your remote sends only when button is released.

**Comment by turin400** [comment]
I have this problem with the remote 4 buttons of sonoff with the PIR of sonoff, with the PIR de digoo and with the water leak detector of digoo.

When I press a button on the remote, the light goes on and when it goes off it goes off.

The problem is the detector of water leaks of digoo that as indicated in the first post the LED lights when it detects water and stays on while there is water leakage but only the bridge sends signal when it stops detecting water and the led goes off . The same problem with the remote control and the PIR.
At no time if you keep a button pressed send codes every three seconds as your example.

**Comment by Jason2866** [comment]
Hmm. I tried with my R2 Version of the bridge. Same result as i had before with my V1 bridge.
I use portisch firmware for the EFM chip (included in Tasmota project)
Still on firmware v.6.0.0 (no need for newer version on bridge)
`18:22:21 CMD: Status 0
18:22:21 MQT: stat/sonoff-82589D/STATUS = {"Status":{"Module":25,"FriendlyName":["Bridge2"],"Topic":"sonoff-82589D","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
18:22:21 MQT: stat/sonoff-82589D/STATUS1 = {"StatusPRM":{"Baudrate":19200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin","RestartReason":"Power on","Uptime":"0T00:02:11","StartupUTC":"2018-08-11T16:20:10","Sleep":1,"BootCount":35,"SaveCount":82,"SaveAddress":"F4000"}}
18:22:21 MQT: stat/sonoff-82589D/STATUS2 = {"StatusFWR":{"Version":"6.0.0a","BuildDateTime":"2018-06-07T15:55:57","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
18:22:21 MQT: stat/sonoff-82589D/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Jason_Home_WLAN",""],"TelePeriod":300,"SetOption":["00008009","55C18000"]}}
18:22:21 MQT: stat/sonoff-82589D/STATUS4 = {"StatusMEM":{"ProgramSize":513,"Free":488,"Heap":16,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0F8AAB84","0C000000","00080692","00000000"]}}
18:22:21 MQT: stat/sonoff-82589D/STATUS5 = {"StatusNET":{"Hostname":"sonoff-82589D-6301","IPAddress":"192.168.2.127","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"DC:4F:22:82:58:9D","Webserver":2,"WifiConfig":3}}
18:22:21 MQT: stat/sonoff-82589D/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.114","MqttPort":1883,"MqttClientMask":"sonoff-82589D","MqttClient":"sonoff-82589D","MqttUser":"openhabian","MqttType":2,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
18:22:21 MQT: stat/sonoff-82589D/STATUS7 = {"StatusTIM":{"UTC":"Sat Aug 11 16:22:21 2018","Local":"Sat Aug 11 18:22:21 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":99,"Sunrise":"06:00","Sunset":"20:35"}}
18:22:21 MQT: stat/sonoff-82589D/STATUS10 = {"StatusSNS":{"Time":"2018-08-11T18:22:21"}}
18:22:21 MQT: stat/sonoff-82589D/STATUS11 = {"StatusSTS":{"Time":"2018-08-11T18:22:21","Uptime":"0T00:02:11","Vcc":3.182,"Wifi":{"AP":1,"SSId":"Jason_Home_WLAN","RSSI":100,"APMac":"00:A0:57:1E:69:50"}}}`

**Comment by turin400** [comment]
I'm going to try the firmware version of tasmota and the rf to see if the same thing happens.

I'm going to take a while because I have to open it to modify it for the portisch firm.

I appreciate it a lot. I will tell you.
A greeting.

**Comment by turin400** [comment]
Yes now. Just press a button and keeping it begins to send codes.
It started working when I loaded the portisch firmware and with tasmota 6.1.1.
Thanks for everything.


20:54:20 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":13760,"Low":460,"High":1310,"Data":"010834","RfKey":"None"}}
20:54:20 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"67636","Battery":58,"RSSI":10}
20:54:22 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":13730,"Low":480,"High":1320,"Data":"010834","RfKey":"None"}}
20:54:22 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"67636","Battery":58,"RSSI":10}
20:54:24 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":13730,"Low":470,"High":1320,"Data":"010834","RfKey":"None"}}
20:54:24 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"67636","Battery":58,"RSSI":10}
20:54:27 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":13730,"Low":470,"High":1320,"Data":"010834","RfKey":"None"}}
20:54:27 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"67636","Battery":58,"RSSI":10}
20:54:29 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":13730,"Low":470,"High":1320,"Data":"010834","RfKey":"None"}}
20:54:29 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"67636","Battery":58,"RSSI":10}
20:54:31 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":13730,"Low":470,"High":1320,"Data":"010834","RfKey":"None"}}
20:54:31 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"67636","Battery":58,"RSSI":10}
20:54:33 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":13730,"Low":470,"High":1320,"Data":"010834","RfKey":"None"}}
20:54:33 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"67636","Battery":58,"RSSI":10}
20:54:35 MQT: tele/RFBridge433/RESULT = {"RfReceived":{"Sync":13730,"Low":480,"High":1320,"Data":"010834","RfKey":"None"}}
20:54:35 MQT: domoticz/in = {"idx":24,"nvalue":0,"svalue":"67636","Battery":58,"RSSI":10}

**Comment by terba** [comment]
I have the same problem using Tasmota 6.6.0.12 as described in this issue and also in #2434. Water leakage sensors and smoke detectors behave the same. Should I switch to *portisch*? @turin400: Does it still work reliably for you?

**Comment by turin400** [comment]
The firmware works very well.
