### ISSUE TITLE
Can't flash Tasmota to Sonoff basic

### ISSUE THREAD

**Issue by klrock** [arendst/Sonoff-Tasmota#3454]
I was able to backup the Sonoff Basic firmware using the following command
esptool.py --port COM6 read_flash 0x00000 0x100000 image1M.bin

C:\Windows\system32>esptool.py --port COM6 read_flash 0x00000 0x100000 image1M.b
in esptool.py v2.3.1 
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Uploading stub...
Running stub...
Stub running...
1048576 (100 %)
1048576 (100 %)
Read 1048576 bytes at 0x0 in 93.7 seconds (89.5 kbit/s)...
Hard resetting via RTS pin...

However, when I immediately tried this second command to upload tasmota, it responded: 
A fatal error occurred: Failed to connect to Espressif device: Timed out waiting
for packet header.
esptool.py --port COM6 write_flash -fs 1MB -fm dout 0x0 c:\other\sonoff.bin\sonoff.bin

C:\Windows\system32>esptool.py --port COM6 write_flash -fs 1MB -fm dout 0x0 c:\o
ther\sonoff.bin\sonoff.bin
esptool.py v2.3.1
Connecting........_____....._____....._____....._____....._____....._____.....__
___....._____....._____....._____

A fatal error occurred: Failed to connect to Espressif device: Timed out waiting
 for packet header

I cant understand why it could not locate the esp after it located it the first step.

Knowing that some PCs cant supply enough amps through the USB connection, I used a separate power supply provide 3.3 volts to the 3V3 pin.

Amy ideas?

**Comment by andrethomas** [comment]
GPIO0 (The push button) must be kept low (pressed) on power-up of the module to put it into flash mode and keep it down until flash is completed... did you try that?

**Comment by klrock** [comment]
Thanks for the response.
I tried your suggestion with same result.

These are the instructions found for flash mode:
To flash a new firmware to your Sonoff, you have to boot your Sonoff in flashing mode. Follow this 4 step process:
1) Connect your 3.3V FTDI programmer to your computer
2) Hold down the Sonoff button
3) Apply-power-to-sonoff
4) Then, you can release the Sonoff button
Now, your Sonoff should be in flashing mode and you can upload a new firmware.

**Comment by Frogmore42** [comment]
The error you are seeing is most likely because you don't have it in bootloader mode.  It can be tricky getting this to work.  It looks like the button on the Basic is connected to GPIO0.  You didn't show how you have things connected.  I would do the following:

1. Hold down the button for GPIO 0
2. Apply power to the Sonoff
3. Wait 3 seconds
4. Connect the programmer to your computer
5. Release the button

Now, you should be able to try flashing.

**Comment by andrethomas** [comment]
I have at least 2 sonoff basic modules that require me to hold the button down from power-up all the way until flashing is completed - the reason for this is unknown but worth exploring on your device.

**Comment by Jason2866** [comment]
@klrock 
Do it exactly like @Frogmore42 described.
If rx and tx is already connected with serial adapter connected to pc it can put the Esp in undefined status.

**Comment by klrock** [comment]
Sorry but I could not find anything under @Frogmore42 such as you describe below.  Could you please provide the specific link to this description?

**Comment by Frogmore42** [comment]
He meant follow the steps I listed above.  If you have the serial lines connected to the adapter that is connected to your computer, you can back drive the esp8266, which can cause the problem you are seeing.

**Comment by klrock** [comment]
Thanks for the details. While reviewing them, I realized that my supplemental 3.3 volt power supply was already powering the Sonoff by being attached to the UART. Since the method already requires both hands to hold the button and plug in the USB, I had to recruit my wife to turn on the power supply after the USB was attached but before the button was released.

Success is sweet!

**Comment by andrethomas** [comment]
@klrock Good going... sometimes you lose some, sometimes you learn some :)

Please close issue, thx!

**Comment by bobtncop** [comment]
I had the same problem trying to flash an older 8266 on basic sonoff switch...I tried everything with the switch...finally I gave up on the stupid boot switch and soldered another wire to GPIO0 next to the 470 micro farad capacitor and tied it to ground.  I then plugged the TTL usb adapter in...everything worked then.  Unplug from usb to cycle power then plug back in BUT this time, untie the wire to GPIO0 from ground and click connect on tasmota web installer...you can now change your wifi info and visit device.
![20240901_100006](https://github.com/user-attachments/assets/099e074d-57cb-4e89-bab6-87b136e9443e)
