### ISSUE TITLE
Change TEMP_RESOLUTION

### ISSUE THREAD

**Issue by HansWurst90** [arendst/Sonoff-Tasmota#347]
Is there a console command to change this without reflashing the device?

`#define TEMP_RESOLUTION        1                 // Maximum number of decimals (0 - 3) showing sensor Temperature`

**Comment by arendst** [comment]
Currently only by reflashing as you noticed.

**Comment by markbac17** [comment]
It would also be great if we could change Celsius to Fahrenheit without having to modify the firmware.
Perhaps a selection on the Configure other options?

**Comment by smadds** [comment]
Maybe better to return both C & F ? 
I know it's more data to transfer, but at least there would be no ambiguity as to what a temperature value was.

**Comment by arendst** [comment]
Implemented in next release
