### ISSUE TITLE
Send PulseTime with On command

### ISSUE THREAD

**Issue by mrmin24** [arendst/Sonoff-Tasmota#348]
Hi,

It would be nice to be able to override the PulseTime when sending a Power command, so that you can tell the relay to switch on for a specific time without overriding the pulsetime first with an additional command.  

e.g. /xxx/topic/ Power  ON_600   - irrigation goes on for 10mins

thanks for the great job

**Comment by ionciubotaru** [comment]
Modify pulse time before power command. Send 2 commands instead of one.

**Comment by mrmin24** [comment]
yes, but then you should check the pulsetime is set before sending second command.

**Comment by ionciubotaru** [comment]
After the pulsetime setup you receive a confirmation from sonoff with the new pulsetime settings.
If you did't receive it send the first command again.

For multiple power commands with different pulsetime set the desired pulsetime before every command.

**Comment by ascillato2** [comment]
Hi,

Seems that your question has been addressed. Closing this issue. Please reopen if needed. Thanks.
