### ISSUE TITLE
HELP WANTED: howto get OBI plug up and running?

### ISSUE THREAD

**Issue by wdenx** [arendst/Sonoff-Tasmota#3481]
Hi - I'm trying to flash several OBI plugs ("Wifi Stecker Schuko").  Erasing and flashing works fine,
butthe I cannot get any connection to WiFi...

-> esptool --port /dev/ttyUSB0 --baud 115200 erase_flash
esptool.py v2.3.1
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 2.9s
Hard resetting via RTS pin...
-> esptool --port /dev/ttyUSB0 write_flash -fs 1MB -fm dout 0x0 sonoff-DE.bin 
esptool.py v2.3.1
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Compressed 551216 bytes to 375292...
Wrote 551216 bytes (375292 compressed) at 0x00000000 in 33.4 seconds (effective 132.2 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

So far so good.  but now:

...
00:00:45 APP: starte neu

 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3fff3b98
~ld
   �
00:00:00 Projekt sonoff Sonoff (Topic sonoff, Fallback DVES_51AA83, GroupTopic sonoffs) Version 6.1.1-2_3_0
00:00:00 WIF: verbinden mit AP1  in Modus 11N wie sonoff-2691...
00:00:13 WIF: Verbindung fehlgeschlagen, da der AP nicht antwortet (timeout)
00:00:13 WIF: verbinden mit AP1  in Modus 11N wie sonoff-2691...
00:00:26 WIF: Verbindung fehlgeschlagen, da der AP nicht antwortet (timeout)
00:00:26 WIF: WPSConfig aktiv für 3 Minuten
00:00:45 APP: starte neu
...

This repeats infinitely.  What I observed:
- I can never detect any WLAN with SSID "sonoff-2691" or similar
- I can never get a connection using WPS
- The log says WPS is active for 3 minutes, but then just 19 seconds later the board resets.
- The documentation says 4 pulses at GPIO0 would select WLAN mode, but it seems it just resets the board.
- I also tried with "sonoff.bin" instead of "sonoff-DE.bin" - same behaviour, only the messages are in English then. 

What am I doing wrong?  All help welcome!

**Comment by ThinkPadNL** [comment]
When you have a serial console, you can also configure the wifi through the console:
ssid1 yournetwork
password1 yourpassword

It will then connect to your network

**Comment by Frogmore42** [comment]
Since you have it connected via serial, you can use the commands to configure it.  That is what I used to do before I started compiling my own version.

**Comment by wdenx** [comment]
I only get output on the serial line.  I see no echo when typing, nor do I see any reaction on anything I type.

I think there is something fundamentally broken as not even the timing appears to be right - it says "WPS is active for 3 minutes" but resets less than 20 seconds later.  This can't be normal?

But I see the same behaviour with both the English and the German images, and on 3 devices...

**Comment by curzon01** [comment]
for test, also try an [older stable one](https://github.com/arendst/Sonoff-Tasmota/releases/tag/v5.14.0)

**Comment by Frogmore42** [comment]
Take a look at all the other issues for flashing.
Make sure you are providing proper power.  Many USB adapters/ports don't provide enough power.

Make sure you have both TX and RX hooked up correctly.

What tool are using for terminal emulation?
Perhaps it is misconfigured or not a good choice.

Try completely erasing the flash before uploading the binary.

Try compiling the binary yourself with your WiFi information.

**Comment by wdenx** [comment]
Thanks for all attempts to help so far...
- I tried the stable image; this is what I get:
00:00:00 Project sonoff Sonoff (Topic sonoff, Fallback DVES_51AA83, GroupTopic sonoffs) Version 5.14.0-2_3_0
00:00:00 WIF: Connecting to AP1  in mode 11N as sonoff-2691...
00:00:13 WIF: Connect failed with AP timeout
00:00:13 WIF: Connecting to AP1  in mode 11N as sonoff-2691...
00:00:26 WIF: Connect failed with AP timeout
00:00:26 WIF: WPSConfig active for 3 minutes
00:00:46 APP: Restarting
i. e. exactly the same behaviour, including the broken timings
- I checked the power; it looks stable and clean.
- If Tx and Rx were not connected correctly, then erasing/flashing should not work, or would it?
- I'm using kermit (C-Kermit 9.0.302) as terminal emulation. And yes, I know how to do things like this.
- I always run erase_flash before wriing a new image; seems to work like a charm.
- Compiling myself... guess this is the last thing left.

**Comment by Frogmore42** [comment]
Looks like you will need to compile it yourself and see if that changes things.  It might also be that your device is defective somehow.  I have one or two devices that are and it would have been super frustrating if I had started with one of them.

How have you checked the power?  Do you have an oscilloscope?  If you do, take a close look and you will see just how much of a load the esp8266 can put on a regulator and how poorly most of them cope with it.  If you are powering it with the adapter and not an independent 3V3 supply, try using a good 3V3 regulator with a good 5V supply.

**Comment by arendst** [comment]
@wdex do you know the hardware connection between the button and the esp8266 in your Obi? There is an issue here about obi and people were able to use it. It might be that the button is NOT connected to GPIO0 and the initial firmware will therefore not be able to select another wifi configuration mode.

Regrading WPS 3 minutes most of the time is only 20 seconds. This is because WPS is serviced by the SDK (used by core, used by Tasmota) and SDK versions have changed over time where the WPS timeout is mostly only 20 seconds. So this is not a hardware/software problem of your device(s).

Tasmota does NOT local echo serial data so you will have to configure your tool to provide local echo. When you do receive data you must be able to enter command ``seriallog 3`` to receive even more data.

As you were able to update firmware the hardware serial connection was OK at that time; uploading firmware uses both Tx and RX signals.

As you are able to see some serial output the firmware seems to be loaded correctly and no need to re-compile your own.

Main task is to get serial going by configuring your serial tool correctly/usable.

**Comment by wdenx** [comment]
I was not able to get this running at al with any of the downloaded images.
I then built myself from sources, with my WiFi configuration pre-set, and this works like a charm.

Thanks for all your help!
