### ISSUE TITLE
Is there a command to put Sonoff RF into learning mode

### ISSUE THREAD

**Issue by umairyounus** [arendst/Sonoff-Tasmota#3483]
Sometimes it's difficult to reach to sonoff to double press the sonoff button to bring it into learning mode. Is there any command to bring sonoff into learning mode using the console?

Thanks

Umair

**Comment by Jason2866** [comment]
No, just via button.

**Comment by Jason2866** [comment]
I think no. Hardware limitation. The way ITEAD designend it makes it impossible (in my understanding of the circuit diagram).

**Comment by arendst** [comment]
@Jason2866 correct. The button double press is handled by the RF chip out of control of the esp8266.

**Comment by ascillato2** [comment]
Hi,

Closing this issue as your questions has been addressed. Ask to reopen this issue if you need it. Thanks
