### ISSUE TITLE
Better explain what is Sonoff Pow Factor

### ISSUE THREAD

**Issue by afaucogney** [arendst/Sonoff-Tasmota#3484]
Hello,

 It Could be classified as documentation bug, as I do not understand what is the Pow Factor:
- doc says :  The ratio of the real power flowing to the load to  the apparent power in the circuit.

Could someone give me more info and a real exemple.

Thanks

**Comment by arendst** [comment]
Search using google.

**Comment by Jason2866** [comment]
https://en.wikipedia.org/wiki/Power_factor

**Comment by ascillato2** [comment]
Hi,

Closing this issue as your questions has been addressed. Ask to reopen this issue if you need it. Thanks

**Comment by afaucogney** [comment]
@arendst @Jason2866 thanks for answering. Now I get it ! I apologize for having been seen as stupid, but..., it was not obvious that we talk about "Power Factor", the doc write just "Factor", as "Current", "Energy" ..., so the Power could be understood as the "Power" of the "Sonoff Power".
Additionally, first : I m not a native English speaker, and second : in France (I have some level in electrical science), we talk more about "Cos Phi" than "Power Factor".
