### ISSUE TITLE
Sensor API: Request FUNC_TELEPERIOD ?

### ISSUE THREAD

**Issue by andrethomas** [arendst/Sonoff-Tasmota#3486]
**Have you look for this feature in other issues and in the wiki?**
Yes

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Callback function FUNC_TELEPERIOD for use in sensors that require telemetry reporting other than appending the existing JSON used by callback FUNC_JSON_APPEND - i.e. only to be called when telemetry interval occurs.

Thanks

**Describe alternatives you've considered**
Maintain internal timer in driver and count on FUNC_EVERY_SECOND callbacks until telemetry period counter is reached and then inject telemetry response.

**Comment by arendst** [comment]
Just check for telemetry is 0 like some domoticz and knx sensor implementations and do your thing.

**Comment by andrethomas** [comment]
Will do, thanks
