### ISSUE TITLE
Sonoff SC and BME280

### ISSUE THREAD

**Issue by ilvenos** [arendst/Sonoff-Tasmota#3488]
Hi,
Is it possible to connect BME280 to Sonoff SC instead of TH11?
I see only one free GPIO when I chose Sonoff SC.

**Comment by Frogmore42** [comment]
You would have to find the other GPIOs and modify the template.  Unless you are really good with a soldering iron, it would be easier to get another device.

**Comment by Frogmore42** [comment]
The TH11 is connected to the other MCU, so you can't replace it.

**Comment by ilvenos** [comment]
@mike2nl  could you show me Your modules configuration in tasmota?
When I chosen Sonoff SC I have only one GPIO (GPIO2).
if I understand you correctly, you didnt chose Sonoff SC from tasmota settings?

**Comment by mike2nl** [comment]
@ilvenos 
no issue but you have to wait that i'm at home. Round the afternoon i'm
back and i will made some screenshots....

**Comment by ascillato** [comment]
@ilvenos

Hi,

Have you managed to solve your issue?

**Comment by ascillato2** [comment]
@mike2nl help please

**Comment by ascillato2** [comment]
Hi,

@ilvenos

Please, try to contact mike in discord chat.

As this issue is on HOLD since 17 ago, I'm closing it temporarily until you have time to continue with it. Please, as soon as you have more information/questions, ask to reopen this issue and we gladly continue with it. Thanks.
