### ISSUE TITLE
Added 433mhz RF to nodemcu

### ISSUE THREAD

**Issue by umairyounus** [arendst/Sonoff-Tasmota#3489]
Is it possible to connect RF receiver and transmitter to nodemcu? I can't find the option in the sensor list.

**Comment by curzon01** [comment]
- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues):

#1190, #2702, #3469

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

Closing this issue as your questions has been addressed. Ask to reopen this issue if you need it. Thanks
