### ISSUE TITLE
Sonoff S20 flashing upload is canceled

### ISSUE THREAD

**Issue by Smarti15** [arendst/Sonoff-Tasmota#3490]
Hi I'm trying to flash a Sonoff S20_EU_V1.3. Unfortunately, I always get the following message when uploading:

Configuring upload protocol ...
Looking for upload port ...
Use manually specified: COM5
Uploading .pioenvs \ sonoff-DE \ firmware.bin
warning: espcomm_sync failed
error: espcomm_open failed

error: espcomm_upload_mem failed
*** [upload] Error -1
 [ERROR] Took 20.88 seconds
Environment sonoff-DE [ERROR]
 [ERROR] Took 20.88 seconds

Do you have any idea what that could be?

I am also not sure if the S20 switches to flash mode. I hold the button, put the CP2102 in the USB port, now the red LED lights up, I let go of the button and the red LED lights for about 5 seconds and then goes out. Does not the LED have to light up constantly and should not go out at all?

http://www.bilder-upload.eu/show.php?file=56aec0-1534313219.jpg
http://www.bilder-upload.eu/show.php?file=103a86-1534313230.jpg
http://www.bilder-upload.eu/show.php?file=67544e-1534313241.jpg

**Comment by curzon01** [comment]
pls read [Wiki FAQ - Flashing Issues](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#flashing-issues)

**Comment by curzon01** [comment]
If you are not sure, try it
- reverse TX/RX lines, this will not damaged anything
- try holding button during the whole flash procedure incl. boot of device, this will not damaged anything

**Comment by Smarti15** [comment]
I found the mistake. The cables that came with the CP2102 were all broken. I replaced it and immediately everything worked out. :)

**Comment by curzon01** [comment]
**(Please, remember to close the issue when the problem has been addressed)**
