### ISSUE TITLE
BlitzWolf SHP2 Module not showing energy consumption

### ISSUE THREAD

**Issue by TheEggi** [arendst/Sonoff-Tasmota#3491]
I am currently trying to set up the BlitzWolf SHP2 Smart Plug and it seemed to be working fine, but the only thing (from the power info) working seems to the voltage. All the other values stay at 0.

![image](https://user-images.githubusercontent.com/1206407/44142237-ed78e1b2-a07f-11e8-8c7e-8bad7231ea18.png)

Is there anything I need to configure/set up in order for it to work?

**Comment by Jason2866** [comment]
Strange! What is connected? Does it consume power at the moment of the screenshot?
As far as i remember i just selected the module and it was running.

**Comment by arendst** [comment]
Should work just fine as long as the load is above 2W

**Comment by TheEggi** [comment]
Thank you for your answer - will receive a new unit probably this/start of next week and will retest it asap.

**Comment by TheEggi** [comment]
Retested it now with another device (ruined the first one but that was not really related) and it seems that for some reason it still showed only 0 for the energy consumption (flashed it pretty much with the default config in user_config.h - only changed MQTT/wifi/server settings). Reflashed it afterwards with the full sensor version (without any change) and back to the one I had ... and somehow it started to show the energy consumption. Will get a few more devices and update/close this issue if I can reproduce it.

**Comment by Jason2866** [comment]
I flashed 5 of this units and everyone is working fine. Every unit worked with 1st flash.
So i think it is your setup which is unreliable sometimes.

**Comment by ascillato** [comment]
Hi,

Have you managed to solve your issue?

**Comment by TheEggi** [comment]
As I wrote in the last comment, it seems to be working now and I guess it can therefore be closed. Never had any similar issues before and flashed many different devices before. If it happens again with any of the , soon to be arriving, Blitzwolf devices I will create a new issue (with hopefully more details).
