### ISSUE TITLE
10% of the OTA firmware uploads will fail, unless you reboot sonoff after OTA upgrade

### ISSUE THREAD

**Issue by lobocobra** [arendst/Sonoff-Tasmota#3496]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://forum.digital-pig.com/)
- [x] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [x] Hardware used : SONOFF BASIC, CH4, CH4-pro, POW
- [x ] Provide the output of command ``status 0`` : 
```
00:16:10 MQT: stat/sonoff/STATUS = {"Status":{"Module":7,"FriendlyName":["Sonoff","Sonoff2","Sonoff3","Sonoff4"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
00:16:10 MQT: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:01:27","StartupUTC":"2018-08-16T23:14:43","Sleep":0,"BootCount":8,"SaveCount":24,"SaveAddress":"F7000"}}
00:16:11 MQT: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.1.1c","BuildDateTime":"2018-08-17T01:08:20","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
00:16:11 MQT: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["domaincats",""],"TelePeriod":300,"SetOption":["0000C009","55818000","C0000000"]}}
00:16:12 MQT: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":424,"Free":576,"Heap":16,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0F002790","00000001","00000096","00000000"]}}
00:16:13 MQT: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-7800","IPAddress":"192.168.20.233","Gateway":"192.168.20.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.20.5","Mac":"60:01:94:83:FE:78","Webserver":2,"WifiConfig":5}}
00:16:13 MQT: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.20.90","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_83FE78","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:16:14 MQT: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Thu Aug 16 23:16:13 2018","Local":"Fri Aug 17 00:16:13 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:45","Sunset":"20:02"}}
00:16:15 MQT: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2018-08-17T00:16:14","Uptime":"0T00:01:31","Vcc":3.057,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"domaincats","RSSI":42,"APMac":"14:CC:20:AC:2D:4D"}}}
```

I am currently extending the basic firmware with some additional functions in order to operate shutters, oil heatings and water dispenser in the garden. Doing that I had to test the firmware several 100 times and 10% of the OTA uploads failed, ending with the need to reflash the firmware serial.
=> Did anyone else make a similar observation? 

BUT if I reboot the SONOFF device (I tried ch4, ch4-pro, basic, POW) after each OTA, the next OTA will work 100% (file upload). If I do not reboot it, then I have a 10% probability that the next OTA fails and the device will not react anymore.
=> This can be annoying if the device is installed fix somewhere.

The work-around is easy.... always reboot the SONOFF after an OTA upload. 
=> But if you forget to do that, you have a 10% chance that your device is blocked.
=> If others experience the same issue, I might look deeper into the issue, in order to find the cause or to add a function that reboots the SONOFF after a successfull OTA. I use version 6.1.1c, but as the latest changes of the code did not touch OTA, this should make no difference.

**Comment by reloxx13** [comment]
this is not a status 0 response, pls post a complete status 0 response.

**Comment by ascillato** [comment]
@lobocobra 

When you said reboot, are you meaning to reboot using the software (web button, console command, etc) or disconnecting power and connecting again?

**Comment by lobocobra** [comment]
Yes I mean that I just have to do a software reboot. I do not need to do a hard - reset.
=> The work around works fine for me, so I only would invest time, if others see it as a problem too. 

But as there are not many doing 100 uploads a day, I guess  I gonna close the topic soon.

**Comment by lobocobra** [comment]
As it seems this seems not to be a problem for a big part of the population. 
=> I will close the issue.

In case you have occasionally issues to make an OTA, you simply need to reboot by software the device after your OTA, in order to prevent, that you might have an issue on your next OTA.
