### ISSUE TITLE
Change state of GPIO over MQTT

### ISSUE THREAD

**Issue by bluebird11** [arendst/Sonoff-Tasmota#350]
Is it possible to set the state of a GPIO using MQTT, i.e. set it to high or to low?

**Comment by davidelang** [comment]
yes, define that gpio as a relay or LED and you can set it's state.
k

**Comment by bluebird11** [comment]
Thanks for the reply! What's the corresponding MQTT command? Led2..4 on/off?

**Comment by davidelang** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

it looks like ledstate1-ledstate4 would do what you want.

**Comment by davidelang** [comment]
closing this issue as there has been no response, if you are still working on this, please re-open this issue.

**Comment by bluebird11** [comment]
Sorry, I couldn't test it yet, thank you for your help!
