### ISSUE TITLE
HX711

### ISSUE THREAD

**Issue by pronsta** [arendst/Sonoff-Tasmota#3502]
Hi, 

Is HX711 for the load cell supported by tasmota? 

thanks

**Comment by Jason2866** [comment]
Not supported.

**Comment by ascillato2** [comment]
Seems that your question has been answered. Closing issue. Please, ask to reopen if needed. Thanks

**Comment by arendst** [comment]
Stay tuned

**Comment by mike2nl** [comment]
@arendst 
Saw it that the driver was now a tasmota one supported type. Well done...

- Question about the interface:
I saw a breakout board with one data and one clock connection and i mean that i have seen t
hat the driver uses two gpio"s? That's right?
One for GPIO_HX711_SCK and one for GPIO_HX711_DAT. 

Cool add-on to tasmota. Found something what i will build in the colder winter days:
https://www.instructables.com/id/Arduino-Load-Cell-Scale/

And the sensor is a 150KG with a precission of 0,02%, link: https://hackerstore.nl/Artikel/638.
The instrument amplifier will be this one so far i find nothing else: https://hackerstore.nl/Artikel/696

Ok the links are from a local dutch store but with picture everyone can find it.

**Comment by arendst** [comment]
So what's the question?

**Comment by arendst** [comment]
You provided all the answers already. The amp is the same as I use.

**Comment by arendst** [comment]
![img_20181014_112945](https://user-images.githubusercontent.com/11044339/47257596-443c9400-d490-11e8-9618-e24fa84302d4.jpg)

![img_20181014_113110](https://user-images.githubusercontent.com/11044339/47257597-47378480-d490-11e8-8a53-f70dea19270b.jpg)

![img_20181014_113353](https://user-images.githubusercontent.com/11044339/47257599-4e5e9280-d490-11e8-9748-f87b79d9468a.jpg)

**Comment by JoschaMiddendorf** [comment]
Is ist possible to add multiple (3) HX711 to one NodeMcu module?

**Comment by Jason2866** [comment]
No

**Comment by frodo1990** [comment]
Hello, yesterday I tried to get the HX711 up and running. The calibrate works and a weight of 3Kg are also displayed. That works great. But as soon as I take the ESP from the power or reboot, then the display shows 0Kg. Even if the weight of 3Kg is still on the sensors.

I would like to build the sensors under a water softener, so that I can read the weight of the salt tablets and send it via MQTT.

How can I save the value after a reboot? I have the Tasmota version 7.1.1 on the ESP.

**Comment by lalo-uy** [comment]
I have the same problem.
The module do not backup the calibration offset. It assume that power on is
with no load.
There is an option to backup the weight prior to reboot, but is useless in
a blackout.
I did not have time to make a PR.

**Comment by darkdevil373** [comment]
Is there any new Information?

**Comment by florinssk** [comment]
any new data about losing data after reboot ?

**Comment by jaymemaurice** [comment]
Since this issue is closed, I doubt anyone is looking at it. Is it that the module itself tares to 0kg on power loss like most scales seem to do!? Maybe this is the wrong module for an application that always has weight on it… do we have a data sheet?
