### ISSUE TITLE
Get esp deviceid or chipid as a success messsage for wifi smartconfig

### ISSUE THREAD

**Issue by amitavamighty** [arendst/Sonoff-Tasmota#3503]
Is it possible to get the esp deviceid or chipid along with the success message of smartconfig on my ESP8266 SmartConfig app or similar apps. Its necessary to identify which esp has successfully received the config if there are multiple esp's. Please suggest how to do that.

**Comment by arendst** [comment]
Smartconfig is a concept of the espressif  SDK. Ask them about smartconfig options.

**Comment by amitavamighty** [comment]
@arendst Can you tell me the file where I can check and edit the smartconfig responses/parameters in tasmota?
Thanks for the help.

**Comment by arendst** [comment]
Using the correct tool look for ``smartconfig`` in file support.ino

**Comment by ascillato2** [comment]
Seems that your question has been answered. Closing issue. Please, ask to reopen if needed. Thanks
