### ISSUE TITLE
MQTT with TLS on Sonoff S20

### ISSUE THREAD

**Issue by Mebus** [arendst/Sonoff-Tasmota#3504]
Hallo,

is it possible to enable TLS for MQTT on the Sonoff S20?

Thanks

Mebus

**Comment by Frogmore42** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/2845

**Comment by ascillato2** [comment]
Seems that your question has been answered. Closing issue. Please, ask to reopen if needed. Thanks
