### ISSUE TITLE
MQTT Command to Show Sensorstate like Powerstate

### ISSUE THREAD

**Issue by razor109** [arendst/Sonoff-Tasmota#3511]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://forum.digital-pig.com/)
- [X] Searched the problem in the discussion group (https://groups.google.com/d/forum/sonoffusers)
- [X] Hardware used : 
- [X] Provide the output of command ``status 0`` :

I Have a couple of doorsensors connected to my Sonoffs. I have everything connected to HomeAssistant. But when i restart HomeAssistant the state of the sensor is unknown. 

I configured the sensor like this:

  - platform: mqtt
    name: "Slaapkamer1 deur"
    state_topic: "cmnd/rolluiksk1/POWER3"
    availability_topic: "tele/sonoff-rolluik-sk1/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

i dont like to use the telemessage as source for the state because to frequent updates of the tele message will i think in the end with al lot of sensors clogg the MQTT server? 

With poweron of HomeAssistant i run an automation to request the current states of the relays. But i can not seem to find a command in MQTT to show this als result and my HASS can pick it up:

stat/<switchtopic>/POWER3 = OFF

Any idea's? I found Status 10 but it shows an output simmilar to TELE. 

Does SensorRetain help in this case? Although what happens when the state of the sensor changes during off-time from HASS will it not restore old state on startup and dont know about the change yet?

**Comment by ascillato** [comment]
Hi,

> i dont like to use the telemessage as source for the state because to frequent updates of the tele message will i think in the end with al lot of sensors clogg the MQTT server?

MQTT is very light and it is designed for that, so your MQTT Server should work fine with a lot of sensors.

> Any idea's? I found Status 10 but it shows an output simmilar to TELE.

Sensors are readed BEFORE Tasmota sends the TELE Message. So, You need to use the TELE Message. In the wiki are examples on how extract the JSON information for Home Assistant.

> Does SensorRetain help in this case? Although what happens when the state of the sensor changes during off-time from HASS will it not restore old state on startup and dont know about the change yet?

Better not to use retain messages and have the real information.

Hope this helps.

**Comment by andrethomas** [comment]
@razor109 

I configure my HA software to send a MQT message "status 11" to the device's topic and get an immediate response like:

`MQT: stat/lab/STATUS11 = {"StatusSTS":{"Time":"2018-08-18T16:58:37","Uptime":"3T22:28:15","Vcc":3.198,"POWER1":"ON","POWER2":"ON","Wifi":{"AP":1,"SSId":"Wireless","RSSI":88,"APMac":"00:00:00:00:00:00"}}}`

I do this on startup on node-red and then process the response to know the current state.

**Comment by andrethomas** [comment]
Maybe not clear, I send 11 to 'cmnd/lab/STATUS' via MQTT server and then get that response :)

**Comment by Frogmore42** [comment]
Unless you have thousands of devices send thousands of messages a sec.  I wouldn't worry about MQTT's ability to keep up.  Even a rpi can easily 10s of messages a second.

Here is a link to some performance testing of various MQTT servers at the many 1000s per second rate.  They certainly notice some issues.
https://www.google.com/url?sa=t&source=web&rct=j&url=http://www.scalagent.com/IMG/pdf/Benchmark_MQTT_servers-v1-1.pdf&ved=2ahUKEwjpkJCt9_bcAhVEKH0KHRgnBO8QFjAKegQIBhAB&usg=AOvVaw20CBovHIFCSYCHcTUblLcY

**Comment by ascillato2** [comment]
Hi,

If you think that your question has been answered, please close this issue. Thanks.
