### ISSUE TITLE
Relais module High Low Trigger

### ISSUE THREAD

**Issue by Satellietje** [arendst/Sonoff-Tasmota#352]
I have expand some sonoff basic modules with relay modules.
![13-4-2017 8-53-41](https://cloud.githubusercontent.com/assets/26080895/24993483/c6b7acbe-2026-11e7-854a-6a1ee3f8ea1f.png)

I noticed that when the toggle on the sonoff is Off the relais module using 0.6 Watt Power. When the toggle is On the module use 0.05 Watt.
![13-4-2017 8-54-35](https://cloud.githubusercontent.com/assets/26080895/24993502/e20f030e-2026-11e7-9849-4baac9be93cb.png)

 I think it has to do with high and low level trigger.

I've looked and I saw the command SwitchMode, but this comand on te sonoff console displays:
MQTT: stat/sonoff/RESULT = {"Command":"Unknown"}

Does anyone know how I can turn the operation of the relay module so that when the toggle is Off the relay is at rest. I can just use the NC instead of NO to switch.

**Comment by davidelang** [comment]
it's switchmode1 not just switchmode (for the first switch)

also note that switchmodeN is for switches and buttonmodeN is for the buttons. 
Buttons are the built-in buttons on the sonoffs, and switches were designed for 
added switches.

**Comment by Satellietje** [comment]
What am I doing wrong?

![afbeelding](https://cloud.githubusercontent.com/assets/26080895/24994514/78214da8-202b-11e7-847e-e0870ac67e7b.png)

**Comment by davidelang** [comment]
what does your module configuration look like? (/md via the web interface, configuration -> module)

**Comment by Satellietje** [comment]
Thanks for the tip!
There I found the solution :-)
