### ISSUE TITLE
Pulsetime problem with 6.1.1 ?

### ISSUE THREAD

**Issue by chriskmn** [arendst/Sonoff-Tasmota#3524]
Hello,

with FW 6.1.1.4 I have this issue with pulsetime ( look at the timestamp):

19:05:59 CMD: pulsetime
19:05:59 MQT: stat/sonoff-21/RESULT = {"PulseTime1":"1600 (Active 1550)"}
19:06:11 CMD: pulsetime
19:06:11 MQT: stat/sonoff-21/RESULT = {"PulseTime1":"1600 (Active 1548)"}
........
20:15:18 CMD: Pulsetime
20:15:18 MQT: stat/sonoff-21/RESULT = {"PulseTime1":"1600 (Active 1533)"}
20:15:40 CMD: Pulsetime
20:15:40 MQT: stat/sonoff-21/RESULT = {"PulseTime1":"1600 (Active 1529)"}
 
It seems that pulsetime timer somehow freezes and gets  reactivated if I access the webserver.

This is my status 0:

20:23:02 CMD: Status 0
20:23:02 MQT: stat/sonoff-21/STATUS = {"Status":{"Module":4,"FriendlyName":["Sonoff-21"],"Topic":"sonoff-21","ButtonTopic":"0","Power":1,"PowerOnState":0,"LedState":0,"SaveData":0,"SaveState":0,"ButtonRetain":0,"PowerRetain":0}}
20:23:02 MQT: stat/sonoff-21/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.0.180:81/sonoff.bin","RestartReason":"Power on","Uptime":"0T16:44:15","StartupUTC":"2018-08-19T01:38:47","Sleep":250,"BootCount":29,"SaveCount":36,"SaveAddress":"F8000"}}
20:23:02 MQT: stat/sonoff-21/STATUS2 = {"StatusFWR":{"Version":"6.1.1.4","BuildDateTime":"2018-08-12T16:52:01","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
20:23:02 MQT: stat/sonoff-21/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"192.168.0.180","LogPort":514,"SSId":["malibu","malibu"],"TelePeriod":120,"SetOption":["00008408","55818000","00000001"]}}
20:23:02 MQT: stat/sonoff-21/STATUS4 = {"StatusMEM":{"ProgramSize":456,"Free":544,"Heap":16,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","4F02E780","00000000","82A4009E","00000000"]}}
20:23:02 MQT: stat/sonoff-21/STATUS5 = {"StatusNET":{"Hostname":"sonoff-21-4598","IPAddress":"192.168.0.35","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"5C:CF:7F:F9:71:F6","Webserver":2,"WifiConfig":5}}
20:23:02 MQT: stat/sonoff-21/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.180","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_F971F6","MqttUser":"mosquitto","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
20:23:02 MQT: stat/sonoff-21/STATUS7 = {"StatusTIM":{"UTC":"Sun Aug 19 18:23:02 2018","Local":"Sun Aug 19 20:23:02 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":99,"Sunrise":"06:06","Sunset":"20:35"}}
20:23:02 MQT: stat/sonoff-21/STATUS10 = {"StatusSNS":{"Time":"2018-08-19T20:23:02","AM2301":{"Temperature":24.4,"Humidity":58.5},"TempUnit":"C"}}
20:23:02 MQT: stat/sonoff-21/STATUS11 = {"StatusSTS":{"Time":"2018-08-19T20:23:02","Uptime":"0T16:44:15","Vcc":3.112,"POWER":"ON","Wifi":{"AP":1,"SSId":"malibu","RSSI":74,"APMac":"BC:AE:C5:EB:95:69"}}}

**Comment by arendst** [comment]
If pulsetime then sleep 0

**Comment by ascillato** [comment]
Hi,

duplicated issue #2850

**Comment by chriskmn** [comment]
It‘s not extending the time. It gets stuck.

**Comment by chriskmn** [comment]
Hi, 

no it‘s not just the extention of time. It gets stuck. check timings..

**Comment by ascillato** [comment]
Hi, 

You have sleep to 250, so your pulsetime is being extended a lot. may be like by 250 times. This is a known problem. Sorry. May be in the future will be fixed. The other issue is open and tagged as enhancement.

**Comment by chriskmn** [comment]
Sleep 250 means that the ESP sleeps for 250ms and then awakes, processes all tasks and goes to sleep again. I measured the difference and came up to an extention of about 5 times which makes sense.

But now after a while the pulsetime counter gets stuck.

Still the same device in same pulsetime circle:

21:12:31 MQT: stat/sonoff-21/POWER = ON
21:15:13 CMD: Pulsetime 
21:15:13 MQT: stat/sonoff-21/RESULT = {"PulseTime1":"1600 (Active 1568)"}

**Comment by chriskmn** [comment]
Ok, thank you very much for the clarification
