### ISSUE TITLE
GPIO9,10 not exposed for Generic device

### ISSUE THREAD

**Issue by SupraJames** [arendst/Sonoff-Tasmota#3525]
For 'Generic' device, sonoff_template.h reserves GPIO pins 7-12 for 'flash control' use. however my Sonoff T1 units use GPIO 9 and 10 for their second and third buttons.

I've made local changes to my source and I've changed GPIO 9 and 10 to GPIO_USER and it's working fine.

Is this a difference between ESP8266 and ESP8285 devices?

**Comment by ascillato** [comment]
> Is this a difference between ESP8266 and ESP8285 devices?

Yes, exactly

That GPIO pins are not going to be exposed due to will make more problems that it solves.

See explanations at #3220, #2783, #2522

Thanks

**Comment by SupraJames** [comment]
For anyone who might come across this... All Hail SetOption81 ... :)

**Comment by ascillato** [comment]
SetOption51

**Comment by SupraJames** [comment]
Hmm it’s definitely 81 in 6.2.1 it’s the last option in the second block of options in settings.h

**Comment by ascillato** [comment]
Yes, but In last 6.2.1.17 is setoption51

**Comment by arendst** [comment]
Correct. See #3709. Still undocumented though ;-)
