### ISSUE TITLE
Present RSSI value as a negative value

### ISSUE THREAD

**Issue by xbmcnut** [arendst/Sonoff-Tasmota#3532]
Hi there,

Running 6.1.0 and have brought the RSSI into Home Assistant but the value reports as a positive rather than the correct negative value.

`{"Time":"2018-08-20T11:56:32","Uptime":"0T14:34:18","Vcc":3.176,"POWER":"ON","Wifi":{"AP":1,"SSId":"IoT","RSSI":70,`

**Comment by roguestreak** [comment]
Looks like the "RSSI" in Tasmota isn't actually RSSI but "WiFi signal strength in percent"
Maybe do a rough conversion in HA using real_RSSI = (tasmota_RSSI / 2) - 100

**Comment by ascillato2** [comment]
Hi,

@roguestreak is right. Tasmota is showing the WiFi signal strength in percent and not dBi.

If you think your question has been answered, please, close this issue. Thanks.

**Comment by xbmcnut** [comment]
Thanks. Does that mean I need two sensors? One to define the RSSI and another to define the template required to invert the number?

**Comment by ascillato** [comment]
> Does that mean I need two sensors? One to define the RSSI and another to define the template required to invert the number?

No, If you want only the signal strengh in dB just apply the formula in HomeAssistant when reading the JSON from Tasmota. Examples for that are in the wiki.

**Comment by ascillato** [comment]
Hi,

If you think your question has been answered, please, close this issue. Thanks.
