### ISSUE TITLE
Esp8266 Smartconfig app not receiving device ip

### ISSUE THREAD

**Issue by amitavamighty** [arendst/Sonoff-Tasmota#3538]
I am trying to configure my device using smartconfig. Console showing that it is getting connected with the WiFi router. But I am not getting the ip address of the device esp8266 smartconfig Apps in my mobile.
It says ESPTouch failed. 
Please help.

**Comment by Frogmore42** [comment]
I don't believe anybody can help you until you provide the requested information in the issue template.  With what you have provided, any answers would be guesses.

**Comment by ascillato2** [comment]
Closing as there is no feedback. Please, open a new issue with all the template completed. Thanks
