### ISSUE TITLE
WeMos Button 

### ISSUE THREAD

**Issue by svh1985** [arendst/Sonoff-Tasmota#3546]
Hello,

I was just wondering.. how can I use the button features as described on (https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage) with the WeMos D1 mini? I've connected the default button shield (pin D3) but it does not work. Do I need to do some additional config?

Thanks!

**Comment by Frogmore42** [comment]
Yes, you need to configure the GPIO to be a button.  See here for section of the UI that does it.
https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini#generic-module

**Comment by ascillato** [comment]
Hi, 

If you think that your question has been addressed, please close this issue. Thanks

**Comment by svh1985** [comment]
Hey, I've setup the module as followed.. but the button press doesn't trigger anything;
<img width="441" alt="garage_sensor_-_configureer_module" src="https://user-images.githubusercontent.com/5213210/44466080-b3784200-a61f-11e8-9f76-1fec8bc8197c.png">

**Comment by ascillato2** [comment]
You did not set any output. Please, read the wiki.

As a basic example use:

Button1 in gpio0
led1i in gpio2
Relay1 in gpio12

**Comment by svh1985** [comment]
Two more questions; 
1. I only want to use the button to control the 1 short press, 2 short press etc. actions. Do I need to set the relais(output) in order to use the button functions?
2. Is it possible to code these settings in the firmware as default? I don't want to specify wifi in the firmware but rather use the button action to launch the WiFiManager and configure wifi.

Thanks!
