### ISSUE TITLE
Support 7 segment display

### ISSUE THREAD

**Issue by qingz2004** [arendst/Sonoff-Tasmota#3555]
**Have you look for this feature in other issues and in the wiki?**
Yes.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Able to display temperature and humidity read from a sensor with a cheap 7 segment display.

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.letscontrolit.com/wiki/index.php/7_segment_display

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by gemu2015** [comment]
why not use OLED?  (is already supported!)
128x64 Pixels from 2-5 Euros

or character LCDS (also supported)

**Comment by qingz2004** [comment]
@gemu2015 Thanks! But I only need to display digits and 7 segment display is still much cheaper (less than half price).

**Comment by Frogmore42** [comment]
There are oleds that are very small and currently supported.  It has taken a long time to get that support, so don't know when 7 segment will come.  But, will come sooner if you do the work to integrate it 😀.

**Comment by qingz2004** [comment]
@Frogmore42 Got a link of a cheap OLED which is smaller than 7 segment and supported by Tasmota?
Thanks!

**Comment by Frogmore42** [comment]
I haven't tried these yet, but I expect them to work with the new support.
https://www.amazon.com/MakerFocus-Display-SSD1306-3-3V-5V-Arduino/dp/B0761LV1SD

They are available cheaper directly from China, but I like 2-day shipping and have had good luck with Maker Focus products.  I also hate wasting time on stuff that doesn't work, so my definition of cheap includes how much time I need to spend getting it to work..

**Comment by Frogmore42** [comment]
There are of course some very small 7-segment displays, but you didn't provide a reference for your definition of small.  I also like to be able to read my displays without needing to be closer than a few inches away.

**Comment by qingz2004** [comment]
@Frogmore42 Thanks! I will try that. Hope it works out of box.
It is cheaper from Aliexpress, but I have to wait for around 2 months.

**Comment by Jason2866** [comment]
@qingz2004 
I have ordered this some month ago and it is working with Tasmota.
https://www.aliexpress.com/item/1pcs-0-96-white-0-96-inch-OLED-module-New-128X64-OLED-LCD-LED-Display-Module/32640136921.html?spm=a2g0s.13010208.99999999.259.39c13c00rkUzgu

**Comment by qingz2004** [comment]
@Jason2866 How clear is it compare to 7 segment LED when it displays digits?
Thanks!

**Comment by Frogmore42** [comment]
The one I listed is similar to the one that @Jason2866  has used, only smaller (128x32 instead of 128x64).  Both displays are incredibly crisp, but they are quite small.  So depending on your age an eyesight, you might need glasses to read them :-)

**Comment by gemu2015** [comment]
if you display only a few digits with increased font size it is perfectly readable

but there are also versions with 1.3 inch which are better readable at small fonts

**Comment by qingz2004** [comment]
Perfect.
Thanks!

**Comment by Jason2866** [comment]
You can use a LCD Display too. Typ 1602  or 2004 (3.3 Volt) and a usual I2C board.
LCDs are cheap too...

**Comment by qingz2004** [comment]
@Jason2866 Are the LCDs supported?

**Comment by Jason2866** [comment]
Yes👍

**Comment by qingz2004** [comment]
Great! Thanks!

**Comment by andrethomas** [comment]
@qingz2004 Hi, yes the IC2 LCD's work very well - I have a few of them in use since the implementation of the display code a week or so ago.

If you feel your issue has been addressed please close this issue :) Thx

**Comment by qingz2004** [comment]
Thanks!
