### ISSUE TITLE
Support for Shelly1 and Shelly2 smart switches (pinMode change)

### ISSUE THREAD

**Issue by thehookup** [arendst/Sonoff-Tasmota#3559]
The Shelly1 and Shelly2 require pinMode(INPUT) for their switch terminals.  Tasmota automatically sets pinMode to INPUT_PULLUP when configured.

I have edited the sonoff.ino file to remove INPUT_PULLUP, but I wonder if there is a way to either add a GPIO type for switch-floating or a console command to set pullup true or false.

**Comment by ascillato** [comment]
Similar request #2525

We need to add a command for that.

**Comment by tmarquespt** [comment]
@thehookup does your .bin work on shelly2? Or is it shelly1 ONLY

Thanks

**Comment by arendst** [comment]
Only INPUT available in v6.1.1.9 as ``Button1n`` option. See changelog.

**Comment by ascillato2** [comment]
Implemented. Closing issue. Please, ask to reopen if needed. Thanks.
