### ISSUE TITLE
Can't put B1 into AP mode

### ISSUE THREAD

**Issue by asafl** [arendst/Sonoff-Tasmota#3568]
I flashed a Sonoff B1 R2 with the precompiled binary ver. 6.1.1, but since it has no "button", I can't seem to use the 4 button presses needed to put it into AP mode and configure the device. 
I tried connecting and disconnecting GPIO0 to GND 4 times, but it doesn't seem to work. Can't find any other viable solution anywhere. 
Any suggestions? 

Cheers
Asaf

**Comment by ascillato** [comment]
6.1.1 has the wifi AP as default. You don't need to press anything. After power on, you should see the Tasmota Wifi to connect to configure your wifi

**Comment by asafl** [comment]
Thanks! 
So if I don’t see it I probably messed something up... is there another way to know if the module is still alive?

**Comment by ascillato** [comment]
By connecting the Serial and seeing the output.

**Comment by asafl** [comment]
Thanks very much.

**Comment by ascillato** [comment]
You are welcome :+1:
