### ISSUE TITLE
SDM120

### ISSUE THREAD

**Issue by sewkol** [arendst/Sonoff-Tasmota#3572]
I uploaded the 6.1.1 version to the WeMos D1 mini, connected the Eastron SDM120 Modbus meter and Tasmota reads the data from the meter nicely.
But, how do I send the total energy consumption to the domoticz by mqtt? I can send current power, voltage, electricity but I do not see the option to send the total energy consumed.

**Comment by arendst** [comment]
Make a rule that sends the value to domoticz.

See wiki - rules https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#5-use-of-variables-and-tele-

**Comment by ascillato2** [comment]
Hi,

Closing as your question has been answered. Please, if you have further questions just ask to reopen this issue.

**Comment by Sergio-tix** [comment]
I don't understand how to write a rule. I want to send Active Power to MQTT (SDM120, iobroker).
Here is my rule:
`rule2 on tele-SDM120#ActivePower do ActivePower %value% do publish tele/sonoff/STATE {"ActivePower":%value%} endon`
It does not work, there is an error. What did I write wrong?
