### ISSUE TITLE
Pow2 based on CSE7759B  is reporting 0, button and web interface react differently

### ISSUE THREAD

**Issue by gabrielklein** [arendst/Sonoff-Tasmota#3573]
**Describe the bug**

I have a Sonoff Pow R2 based on the CSE7759B chipset.

* The webinterface keeps a status of a button when I switch it off/on - but this button doesn't seams to have action on the module.
* Everything is set to 0 on the main menu of the web interface.
* When I click on the button, the relay is correctly switched on/off, but the information is not transmitted to MQTT/web UI.

Please note that I've flashed a Pow R1 with success and I'm working on the latest version with PlatformIO. I have of course #define MODULE                 SONOFF_POW_R2. I did a "clean" of my building env - even changed the CFG_HOLDER to reset the configuration.

Also, make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ x ] Searched the problem in issues and in the wiki
- [ x ] Hardware used : Pow R2 V1.0 2017-11-30 
- [ x ] Provide the output of command ``status 0`` :
```
10:57:41 CMD: status 0
10:57:41 MQT: /sonoff/stat/sonoff/STATUS = {"Status":{"Module":43,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"External System","Uptime":"0T09:45:27","StartupUTC":"2018-08-24T00:12:14","Sleep":0,"BootCount":2,"SaveCount":7,"SaveAddress":"F5000"}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.1.1.7","BuildDateTime":"2018-08-24T02:11:18","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SOMETHING","SOMETHING"],"TelePeriod":300,"SetOption":["00008009","55818000","00000000"]}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":458,"Free":544,"Heap":20,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3,"Features":["00000809","0F8AE794","0C000000","23B6179E","00000000"]}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-0756","IPAddress":"10.0.0.246","Gateway":"10.0.0.1","Subnetmask":"255.255.255.0","DNSServer":"10.0.0.1","Mac":"A0:20:A6:16:42:F4","Webserver":2,"WifiConfig":5}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"10.0.0.60","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_1642F4","MqttUser":"","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Fri Aug 24 09:57:41 2018","Local":"Fri Aug 24 10:57:41 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"05:42","Sunset":"19:27"}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2018-08-24T10:57:41","ENERGY":{"Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
10:57:41 MQT: /sonoff/stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2018-08-24T10:57:41","Uptime":"0T09:45:27","Vcc":2.696,"POWER":"OFF","Wifi":{"AP":1,"SSId":"XXXXX","RSSI":92,"APMac":"C4:E9:84:EF:37:52"}}}
```

**To Reproduce**
Buy a Pow R2 and receive the version based on the CSE7759B.

**Expected behavior**
To report something for power, voltage, amps, ... and the button on the web interface to be reacting on the button of the module (and vice-versa). The button on the web interface to switch on/off the module.

**Screenshots**

![img_20180824_120705](https://user-images.githubusercontent.com/7228060/44579499-e0029a00-a796-11e8-9ec4-77fe433e4536.jpg)

![img_20180824_120611](https://user-images.githubusercontent.com/7228060/44579503-e264f400-a796-11e8-8219-abc45b1a6e72.jpg)

![2018-08-24-121018](https://user-images.githubusercontent.com/7228060/44579432-b5b0dc80-a796-11e8-8244-ee8120aa9036.jpg)

![2018-08-24-120952](https://user-images.githubusercontent.com/7228060/44579439-b8abcd00-a796-11e8-90c0-e2c9a5e07bd2.jpg)

**Comment by gabrielklein** [comment]
Related: https://github.com/arendst/Sonoff-Tasmota/issues/1907  https://github.com/arendst/Sonoff-Tasmota/issues/3425 
Interesting: https://github.com/xoseperez/espurna/issues/867

**Comment by arendst** [comment]
Ah, thnx. Didn't know there was another version (776B) in the wild. 

I'll start reading....

**Comment by arendst** [comment]
But in the end Xosez didn't have to change anything. The user just needs to add enough load to get a reading.

As said earlier, try to get some logging with a load of at least 5W.

**Comment by gabrielklein** [comment]
Sorry :( I'll check but I have a standard ESP8266 NodeMCUV3 that was "defective"...  and I was using it to power the +3.3v as my serial has an output of 5v. But it was not that defective....

I'll close this as soon as I've verified.

**Comment by gabrielklein** [comment]
Sorry problems on my side.

**Comment by peter06-tech** [comment]
Is it acceptable not to solder R25?
