### ISSUE TITLE
fatal error: core_version.h: No such file or directory

### ISSUE THREAD

**Issue by claudioita** [arendst/Sonoff-Tasmota#3574]
I receive this error while compiling

F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\arduino-builder -dump-prefs -logger=machine -hardware F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware -hardware F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\portable\packages -tools F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\tools-builder -tools F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr -tools F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\portable\packages -built-in-libraries F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\libraries -libraries F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\portable\sketchbook\libraries -fqbn=arduino:avr:uno -ide-version=10803 -build-path C:\Users\Claudio\AppData\Local\Temp\arduino_build_188535 -warnings=none -build-cache C:\Users\Claudio\AppData\Local\Temp\arduino_cache_678663 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avrdude.path=F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr -verbose F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino
F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\arduino-builder -compile -logger=machine -hardware F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware -hardware F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\portable\packages -tools F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\tools-builder -tools F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr -tools F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\portable\packages -built-in-libraries F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\libraries -libraries F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\portable\sketchbook\libraries -fqbn=arduino:avr:uno -ide-version=10803 -build-path C:\Users\Claudio\AppData\Local\Temp\arduino_build_188535 -warnings=none -build-cache C:\Users\Claudio\AppData\Local\Temp\arduino_cache_678663 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avrdude.path=F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr -verbose F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino
Using board 'uno' from platform in folder: F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\arduino\avr
Using core 'arduino' from platform in folder: F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\arduino\avr
Detecting libraries used...
"F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IF:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IF:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\Claudio\AppData\Local\Temp\arduino_build_188535\sketch\sonoff.ino.cpp" -o "nul"
"F:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IF:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IF:\Users\Claudio\Downloads\arduino-1.8.3-windows\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\Claudio\AppData\Local\Temp\arduino_build_188535\sketch\sonoff.ino.cpp" -o "C:\Users\Claudio\AppData\Local\Temp\arduino_build_188535\preproc\ctags_target_for_gcc_minus_e.cpp"
F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino:31:143: fatal error: core_version.h: No such file or directory

 #include <core_version.h>                   // Arduino_Esp8266 version information (ARDUINO_ESP8266_RELEASE and ARDUINO_ESP8266_RELEASE_2_3_0)

                                                                                                                                               ^

compilation terminated.

exit status 1

**Comment by ascillato** [comment]
Hi,

Seems that you did not install the required libraries.

Please read the instructions in the wiki

https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE
