### ISSUE TITLE
Bunch of errors trying to compile

### ISSUE THREAD

**Issue by claudioita** [arendst/Sonoff-Tasmota#3576]
I receive a bunch of errors

In file included from sketch\user_config.h:1:0,

                 from F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino:33:

F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\Adafruit_ESP8266/Adafruit_ESP8266.h:28:35: error: section attribute not allowed for 'Pchr'

 typedef const PROGMEM char        Pchr; // Ditto, kindasorta

                                   ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xdrv_05_irremote.ino: In function 'boolean IrSendCommand()':

xdrv_05_irremote:299:7: error: 'StaticJsonBuffer' was not declared in this scope

       StaticJsonBuffer<128> jsonBuf;

       ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xdrv_05_irremote.ino:299:7: note: suggested alternative:

In file included from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino:54:

F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

xdrv_05_irremote:299:29: error: 'jsonBuf' was not declared in this scope

       StaticJsonBuffer<128> jsonBuf;

                             ^

xdrv_05_irremote:301:17: error: 'class ArduinoJson::JsonObject' has no member named 'success'

       if (!root.success()) {

                 ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xdrv_07_domoticz.ino: In function 'boolean DomoticzMqttData()':

xdrv_07_domoticz:168:5: error: 'StaticJsonBuffer' was not declared in this scope

     StaticJsonBuffer<400> jsonBuf;

     ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xdrv_07_domoticz.ino:168:5: note: suggested alternative:

In file included from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino:54:

F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

xdrv_07_domoticz:168:27: error: 'jsonBuf' was not declared in this scope

     StaticJsonBuffer<400> jsonBuf;

                           ^

xdrv_07_domoticz:170:19: error: 'class ArduinoJson::JsonObject' has no member named 'success'

     if (!domoticz.success()) {

                   ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xdrv_09_timers.ino: In function 'boolean TimerCommand()':

xdrv_09_timers:364:11: error: 'StaticJsonBuffer' was not declared in this scope

           StaticJsonBuffer<256> jsonBuffer;

           ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xdrv_09_timers.ino:364:11: note: suggested alternative:

In file included from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino:54:

F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

xdrv_09_timers:364:33: error: 'jsonBuffer' was not declared in this scope

           StaticJsonBuffer<256> jsonBuffer;

                                 ^

xdrv_09_timers:366:21: error: 'class ArduinoJson::JsonObject' has no member named 'success'

           if (!root.success()) {

                     ^

xdrv_09_timers:373:68: error: 'class ArduinoJson::Internals::JsonObjectSubscript<char*>' has no member named 'success'

             if (root[UpperCase_P(parm_uc, PSTR(D_JSON_TIMER_ARM))].success()) {

                                                                    ^

xdrv_09_timers:377:69: error: 'class ArduinoJson::Internals::JsonObjectSubscript<char*>' has no member named 'success'

             if (root[UpperCase_P(parm_uc, PSTR(D_JSON_TIMER_MODE))].success()) {

                                                                     ^

xdrv_09_timers:381:69: error: 'class ArduinoJson::Internals::JsonObjectSubscript<char*>' has no member named 'success'

             if (root[UpperCase_P(parm_uc, PSTR(D_JSON_TIMER_TIME))].success()) {

                                                                     ^

xdrv_09_timers:408:71: error: 'class ArduinoJson::Internals::JsonObjectSubscript<char*>' has no member named 'success'

             if (root[UpperCase_P(parm_uc, PSTR(D_JSON_TIMER_WINDOW))].success()) {

                                                                       ^

xdrv_09_timers:412:69: error: 'class ArduinoJson::Internals::JsonObjectSubscript<char*>' has no member named 'success'

             if (root[UpperCase_P(parm_uc, PSTR(D_JSON_TIMER_DAYS))].success()) {

                                                                     ^

xdrv_09_timers:425:71: error: 'class ArduinoJson::Internals::JsonObjectSubscript<char*>' has no member named 'success'

             if (root[UpperCase_P(parm_uc, PSTR(D_JSON_TIMER_REPEAT))].success()) {

                                                                       ^

xdrv_09_timers:428:71: error: 'class ArduinoJson::Internals::JsonObjectSubscript<char*>' has no member named 'success'

             if (root[UpperCase_P(parm_uc, PSTR(D_JSON_TIMER_OUTPUT))].success()) {

                                                                       ^

xdrv_09_timers:432:71: error: 'class ArduinoJson::Internals::JsonObjectSubscript<char*>' has no member named 'success'

             if (root[UpperCase_P(parm_uc, PSTR(D_JSON_TIMER_ACTION))].success()) {

                                                                       ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xdrv_10_rules.ino: In function 'bool RulesRuleMatch(byte, String&, String&)':

xdrv_10_rules:220:3: error: 'StaticJsonBuffer' was not declared in this scope

   StaticJsonBuffer<1024> jsonBuf;

   ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xdrv_10_rules.ino:220:3: note: suggested alternative:

In file included from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino:54:

F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

xdrv_10_rules:220:26: error: 'jsonBuf' was not declared in this scope

   StaticJsonBuffer<1024> jsonBuf;

                          ^

xdrv_10_rules:222:13: error: 'class ArduinoJson::JsonObject' has no member named 'success'

   if (!root.success()) { return false; }               // No valid JSON data

             ^

xdrv_10_rules:231:35: error: 'ArduinoJson::Internals::enable_if<true, ArduinoJson::Internals::JsonObjectSubscript<const String&> >::type' has no member named 'success'

   if (!root[rule_task][rule_name].success()) { return false; }

                                   ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xplg_wemohue.ino: In function 'void HueLights(String*)':

xplg_wemohue:652:7: error: 'StaticJsonBuffer' was not declared in this scope

       StaticJsonBuffer<400> jsonBuffer;

       ^

F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\xplg_wemohue.ino:652:7: note: suggested alternative:

In file included from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from F:\Users\Claudio\Downloads\Sonoff-Tasmota-6.1.1\Sonoff-Tasmota-6.1.1\sonoff\sonoff.ino:54:

F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

xplg_wemohue:652:29: error: 'jsonBuffer' was not declared in this scope

       StaticJsonBuffer<400> jsonBuffer;

                             ^

Più di una libreria trovata per "ArduinoJson.h"
Usata: F:\Users\Claudio\Desktop\Sonoff-Arduino\libraries\ArduinoJson
Non usata: F:\Users\Claudio\Downloads\arduino-1.8.6-windows\arduino-1.8.6\libraries\ArduinoJson-5.11.2
exit status 1
'StaticJsonBuffer' was not declared in this scope

**Comment by ascillato** [comment]
Hi,

Please, follow the instructions of the wiki.

You are not installing the ibraries.

**Comment by ascillato** [comment]
Remember you can also use the precompiled bins at https://github.com/arendst/Sonoff-Tasmota/releases

**Comment by ascillato** [comment]
Have you installed the Tasmota libraries? It is just copy and paste.

**Comment by ascillato2** [comment]
Hi,

Could you solve your issue?
