### ISSUE TITLE
KNX support for PWM

### ISSUE THREAD

**Issue by jkx** [arendst/Sonoff-Tasmota#3577]
Hi, 
I m'driving LEDs strips or simple LEDs light from Tasmota (I used Weemos D1). This works fine.
But, i'm using KNX (mainly xaal/knx bridge), so I'm searching for a way to send / receive PWM 
values over KNX.

**Comment by ascillato** [comment]
Hi,

Have you tried using rules with the [KnxTx_Val1](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#knx) command and the [event#knxrx_val1](https://github.com/arendst/Sonoff-Tasmota/wiki/KNX-Features#usage-examples) ?

**Comment by jkx** [comment]
I'm facing several questions : 
1) what is the event matching color change. I tried something like rule on event#color do .. but doesn't work
2) sending / receiving RGB as float is bad.

**Comment by ascillato** [comment]
Could you sent / receive PWM values using KNX ?

**Comment by ascillato2** [comment]
Hi,

@jkx 

Any news?

**Comment by jkx** [comment]
I'm too busy the week to finish my test. I will look at this next week-end.

**Comment by ascillato2** [comment]
@jkx

As this issue is on HOLD since 24 aug, I'm closing it temporarily until you have time to continue with it. Please, as soon as you have more information/questions, ask to reopen this issue and we gladly continue with it. Thanks.

**Comment by henfri** [comment]
Hello,

knx does not send RGB as Float, but as three Integers (each is one group adress).
So, Red would be:
1/0/1 = 255
1/0/2 = 0 
1/0/3 = 0 

Would this make it possible to control RGB/PWM?

Greetings,
Hendrik

**Comment by ascillato** [comment]
Hi, color is not implemented yet in knx driver. It is on the to do list.
