### ISSUE TITLE
Wemos RFID RC522

### ISSUE THREAD

**Issue by leschNUX** [arendst/Sonoff-Tasmota#3588]
Hi,
is it possible to use Tasmota on a wemos with connected  RC522 RFID Reader Module?

Br

**Comment by CazMan** [comment]
Just for anyone looking for this solution, I found using the SerialBridge feature of tasmota can be used to integrate sensors and other feature currently not supported byTasmota (Connect a arduino nano to the device, send the sensor data over serial and the tasmota device publish it to MQTT...
[https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#serial-bridge](url)

**Comment by Gio-dot** [comment]
> Just for anyone looking for this solution, I found using the SerialBridge feature of tasmota can be used to integrate sensors and other feature currently not supported byTasmota (Connect a arduino nano to the device, send the sensor data over serial and the tasmota device publish it to MQTT...
> [https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#serial-bridge](url)

I, i tried this solution, but i can't get communication working between an arduino nano and a Wemos D1 mini Tasmota. Do you have some sketch example and/or connection example?
