### ISSUE TITLE
Wemos control external LED

### ISSUE THREAD

**Issue by flanshaw** [arendst/Sonoff-Tasmota#359]
Great firmware, been flashing my sonoffs all easter.

I've a wemos D1, reading analog0, DHT11 etc all  working great.. 

Ive read and re-read and can't figure out how to set D2 on wemoss to high/low, to control an LED?

12:25:36 CMND: gpio
12:25:36 MQTT: stat/wemos/RESULT = {"GPIO0":0 (None), "GPIO1":0 (None), "GPIO2":25 (Led1), "GPIO3":0 (None), "GPIO4":0 (None), "GPIO5":0 (None), "GPIO12":0 (None), "GPIO13":0 (None), "GPIO14":0 (None), "GPIO15":0 (None), "GPIO16":0 (None)}

stumpped...

**Comment by cobra85ec** [comment]
i need help with this also

**Comment by davidelang** [comment]
what gpio is D2 on?

**Comment by decologne** [comment]
Pin translation table for Wemos D1 mini:
https://www.wemos.cc/product/d1-mini.html

**Comment by davidelang** [comment]
ok, D2 is GPIO4 according to this link, so set gpio4 to either a led or relay 
output and then you can control it.

David Lang

**Comment by flanshaw** [comment]
Perfect. Set GPIO as relay1. Send cmnd/wemos/power1 and works..

Thanks

**Comment by cobra85ec** [comment]
how about controlling 2 relays..

**Comment by davidelang** [comment]
just define the gpios as relay2/relay3/etc

this firmware can be set to manage 4 relays, 4 LEDs, 4 switches, etc.

David Lang
