### ISSUE TITLE
Is there any guide line for extending code?

### ISSUE THREAD

**Issue by nardev** [arendst/Sonoff-Tasmota#3601]
Perhaps it has been asked already but i couldn't find.

Is there any guidelines for extending code other than digging through the coded for some time and figuring out myself?

Any code structure explanation article?
I thing it could be useful for people willing to add some features.

**Comment by ascillato** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/1828

**Comment by ascillato** [comment]
And of course the API in the wiki: https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-API

**Comment by andrethomas** [comment]
@nardev Please close this issue :) Thx

**Comment by ascillato2** [comment]
Hi,

If you have further questions, please ask to reopen this issue. Thanks
