### ISSUE TITLE
HTTP commands Sonoff S31

### ISSUE THREAD

**Issue by youreunwelcome** [arendst/Sonoff-Tasmota#3616]
is there an HTTP command that outputs just the power information for the S31, like the Volts, Amps and Wattage. Maybe its in the commands page and i'm just not getting it, but i cant figure it out.

**Comment by arendst** [comment]
See wiki - commands at the top where it explains how to use HTTP commands.
```
http://s31/cm?cmnd=status%208
```

**Comment by ascillato2** [comment]
Hi,

Closing this issue as the question has been answered. Please, ask to reopen if needed. Thanks
