### ISSUE TITLE
Reverse RF Procol with Sonoff RFBridge ?

### ISSUE THREAD

**Issue by afaucogney** [arendst/Sonoff-Tasmota#3619]
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Hardware used : RF Bridge v1.0
- [x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE

15:01:11 CMD: status 0
15:01:11 SRC: WebConsole from 192.168.1.40
15:01:11 RSL: Received Topic /status, Data Size 1, Data 0
15:01:11 RSL: Group 0, Index 1, Command STATUS, Data 0
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS = {"Status":{"Module":25,"FriendlyName":["Sonoff"],"Topic":"sonoff_rf_bridge","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS1 = {"StatusPRM":{"Baudrate":19200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Power on","Uptime":"0T00:02:43","StartupUTC":"2018-08-28T13:58:28","Sleep":0,"BootCount":18,"SaveCount":44,"SaveAddress":"F8000"}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS2 = {"StatusFWR":{"Version":"6.1.1","BuildDateTime":"2018-07-23T11:18:24","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Freebox-Syrah",""],"TelePeriod":300,"SetOption":["00008009","55818000"]}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS4 = {"StatusMEM":{"ProgramSize":537,"Free":464,"Heap":15,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","0C000000","23B6179E","00000000"]}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS5 = {"StatusNET":{"Hostname":"sonoff_rf_bridge-5173","IPAddress":"192.168.1.29","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.254","Mac":"60:01:94:8F:34:35","Webserver":2,"WifiConfig":3}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.15","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_8F3435","MqttUser":"homeassistant","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS7 = {"StatusTIM":{"UTC":"Tue Aug 28 14:01:11 2018","Local":"Tue Aug 28 15:01:11 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"06:01","Sunset":"19:41"}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS10 = {"StatusSNS":{"Time":"2018-08-28T15:01:11"}}
15:01:11 MQT: stat/sonoff_rf_bridge/STATUS11 = {"StatusSTS":{"Time":"2018-08-28T15:01:11","Uptime":"0T00:02:43","Vcc":3.183,"Wifi":{"AP":1,"SSId":"Freebox-Syrah","RSSI":100,"APMac":"E4:9E:12:B9:DB:A8"}}}

```

Hi all,

I setup a HA at home, and that pretty working well and powerfully. At home I have a couple of device I want to handle that are RF.

I bought a RF Bridge from Sonoff that I upgraded with the Tasmota Firmware. I also upgrade the RF copro with the tasmota dedicated firmware

The sonoff Bridge is connected throw the HA MQTT, and I can send HEX code over RF.

The question is wich code to send to control my devices ?

At first I tried to learned with the Tasmota (but nothing has been logged) to the sonoff console
Then I updgraded the RF copro, and now I get many moving things/data/protocol…
My devices are:

- Power Plug from Blyss (Castorama) with learn button
- Power Plug from OLNEC with configuration pin
- Smoke detector from Blyss with learn button
- Velux Shutter with Learn button

Do you guys have any relevant/efficient procedure or experience or tutorial or guess with those devices to reverse their protocol in order to control them with HA ?

Is RF Bridge with Tasmota sufficient for this job ?

Thanks a lot !

**Comment by Jason2866** [comment]
Hi @afaucogney 
no simple answer. You have to explore some things. For the start read the explenations
from Portisch (the maker of the EFM firmware) here: https://github.com/Portisch/RF-Bridge-EFM8BB1
You have to sniff the code. You will find examples with solutions in issues in Github there.
Good Luck!

**Comment by ascillato** [comment]
Hi,

If you feel that your question has been answered, please, remember to close this issue. Thanks
