### ISSUE TITLE
WifiManager AP name: sometimes ITEAD instead of Sonoff

### ISSUE THREAD

**Issue by KonstantinMastak** [arendst/Sonoff-Tasmota#362]
Sometimes (irregularly, maybe one of three or four tries) when I activate WifiManager AP mode my device brings access point with name "ITEAD-XXXX" instead of "Sonoff-xxxx". 

Did anybody face this except of me? How do you think, where can ESP keep this "ITEAD" constant if we change the flash?

**Comment by ionciubotaru** [comment]
Your flash rewrite was incomplete, please write it again via serial

**Comment by davidelang** [comment]
closing this issue. please re-open if you still have problems.

**Comment by lichtteil** [comment]
@KonstantinMastak I ran now into the same issue with my Sonoff basic switch. Flashed successfully 3 times with some code alternations and the webserver works but sometimes the ITEAD AP appears and it won't connect to my wifi. Did you solve this somehow?

**Comment by KonstantinMastak** [comment]
I noticed, that there are a lot of strange issues (maybe including the one you mentioned), if you try to use Sonoff right after you flashed it. You should remove power for several seconds and the re-power it again. Then it works much better. Soft reboot which follows flash doesn't help for some reason. Only hard reboot helps.

**Comment by lichtteil** [comment]
@KonstantinMastak Thanks for the fast reply, I'll give it a try :)
