### ISSUE TITLE
Use multiple Dallas DS18B20 on 1 pin with Domoticz

### ISSUE THREAD

**Issue by Dylantje** [arendst/Sonoff-Tasmota#3624]
Dear all.
Is there perhaps a option to use more the 1 dallas DS18B20 on 1 pin?
And the use this option in Domoticz?
I see in the sketch a option to use multiple dallas sensors..
Only i cannot let this work in to Domoticz.

So please some one? [ or a link to a how to? ]

**Comment by Jason2866** [comment]
It is possible, take a look in user_config.h
/```
/ -- One wire sensors ----------------------------
                                                 // WARNING: Select none for default one DS18B20 sensor or enable one of the following two options for multiple sensors
//#define USE_DS18x20                              // Optional for more than one DS18x20 sensors with id sort, single scan and read retry (+1k3 code)
//#define USE_DS18x20_LEGACY                       // Optional for more than one DS18x20 sensors with dynamic scan using library OneWire (+1k5 code)

```
Uncomment one of this 2 possible options for more sensors.
For use in Domoticz i dont know..

**Comment by ascillato** [comment]
Tasmota only supports one Temperature sensor for Domoticz and for KNX.

**Comment by ascillato** [comment]
To send the temperature value from extra sensor, you have to use rules. There is an example for what you want to do with domoticz in the wiki at: https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#5-use-of-variables-and-tele-

**Comment by ascillato2** [comment]
Duplicated issue: #2541
