### ISSUE TITLE
Sonoff 4CH Pro2 switch on afer restart

### ISSUE THREAD

**Issue by hubudavs** [arendst/Sonoff-Tasmota#3625]
If the switch S6 is in position "1" after a software restart from the console one of the channel switch on automatically. (version 6.1.1)
After switching S6 to 0 restart was successful.

**Comment by ascillato** [comment]
Please, complete the troubleshooting template in order to have the information needed and help you properly

**Comment by ascillato** [comment]
Please, share the `status 0`

**Comment by ascillato2** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-4CH-and-4CH-Pro#4ch-pro-dipswitch-configuration
