### ISSUE TITLE
Little help required on PFC8574 implementation

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#363]
Hi experts,

I'm just far in adding support for the I2C DIO module to Sonoff-Tasmoto. Some questions are open to getting it initally released in my fork.

- The power state seems to be binary-coded into "power" copied from sysCfg.power. This limits it to max 8 relays because the type is uint8_t.  (Correct YES/NO?) To avoid major changes the PFC addOn will not support more than 8 relays in total.
- There is a syntax quite often used with ? and : like "digitalWrite(pin[GPIO_REL1 +i], rel_inverted[i] ? !state : state);" Can someone explain how this is working. Never seen before.
- Where in the code after booting the relays will be initialized and set? I assume. sonoff.ino ~line 2200 with "if (sysCfg.savestate) setRelay(power);" depending on poweronstate

**Comment by davidelang** [comment]
On Wed, 19 Apr 2017, stefanbode wrote:

> Hi experts,
>
> I'm just far in adding support for the I2C DIO module to Sonoff-Tasmoto. Some questions are open to getting it initally released in my fork.
>
> - The power state seems to be binary-coded into "power" copied from sysCfg.power. This limits it to max 8 relays because the type is uint8_t.  (Correct YES/NO?) To avoid major changes the PFC addOn will not support more than 8 relays in total.

There are actually several things limiting it to 4 relays.

> - There is a syntax quite often used with ? and : like "digitalWrite(pin[GPIO_REL1 +i], rel_inverted[i] ? !state : state);" Can someone explain how this is working. Never seen before.

This is a test, it writes to the pin either !state or state depending on the 
value of rel_inverted, the ? is a test of the value before it, if that value is 
true, the first thing after the ? is used is written, otherwise the second thing 
after the ? is used (separated by a :)

David Lang

> - Where in the code after booting the relays will be initialized and set? I assume. sonoff.ino ~line 2200 with "if (sysCfg.savestate) setRelay(power);" depending on poweronstate
>
>
