### ISSUE TITLE
Amazon Alexa and Sonoff 4CH

### ISSUE THREAD

**Issue by ulfa** [arendst/Sonoff-Tasmota#364]
Hello, 

i use the software with a sonoff 4CH and i am able to switch the 4 switches via MQTT commands. 

Now i have Alexa at home, but i can only see the first switch (friendly name) in Alexa. The other three switches are not available in Alex. 

Does anybody has a solution, so i can see all four switches in Alexa?

**Comment by davidelang** [comment]
change the emulation that you are using. one emulation only supports a single 
switch, the other acts as a hub with multiple switches behind it.

**Comment by davidelang** [comment]
did this solve the problem for you?

**Comment by ulfa** [comment]
sorry, but i am at vacation. I will test it, when i am home again.

Von meinem iPhone gesendet

**Comment by ulfa** [comment]
Hi David,

now i am home again and tested the other emulation and this works fine.

Thank you for your help,
Ulf

2017-04-26 17:36 GMT+02:00 David Lang <notifications@github.com>:
