### ISSUE TITLE
delay 10000 in rule doesn't work as expected

### ISSUE THREAD

**Issue by aberguno** [arendst/Sonoff-Tasmota#3641]
instead of a 10min delay i get a 1min, any help? thanks

00:15:00 RUL: TIME#MINUTE|15 performs "backlog Power1 on;delay 10000;Power1 off"
00:15:00 MQT: stat/greenhouse/RESULT = {"POWER1":"ON"}
00:15:00 MQT: stat/greenhouse/POWER1 = ON
00:15:00 MQT: stat/greenhouse/RESULT = {"Delay":2}
00:15:01 MQT: stat/greenhouse/RESULT = {"POWER1":"OFF"}
00:15:01 MQT: stat/greenhouse/POWER1 = OFF

**Comment by ascillato** [comment]
Please, read the wiki at https://github.com/arendst/Sonoff-Tasmota/issues/2116

limit is 3600 that is 360 seconds

**Comment by ascillato2** [comment]
use ruletimer
