### ISSUE TITLE
Settings Lost with 6.1.1.14 when Upgrading

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#3643]
Hi @arendst 

I lost my config when upgrading a device from 6.1.1c with latest 6.1.1.14

Thx

**Comment by arendst** [comment]
You're welcome

**Comment by Jason2866** [comment]
It is a NodeMCU which runs without any problems before.
It is a test device so it doesent matter at all.
What informations i can provide?

**Comment by arendst** [comment]
Did you lose all or was the module just changed from what you had to Sonoff Basic?

**Comment by arendst** [comment]
I'm on discord now.

**Comment by arendst** [comment]
Should work fine now.

**Comment by Jason2866** [comment]
As usual faaaaaast :-)
