### ISSUE TITLE
Question about Tasmota, rules and triggers

### ISSUE THREAD

**Issue by sohnvonoff** [arendst/Sonoff-Tasmota#3645]
I use a SONOFF Dual R2 with Tasmota 6.0.1.
Is it possible to use "LedPower" as a trigger in a rule, as well as for example
"rule1 on POWER1#STATE=1 do power2 1 endon"
 then just for example 
"rule1 on LEDPOWER#STATE=1 do Power2 1 endon"

**Comment by ascillato** [comment]
Sorry, No,

Please, see wiki at rules for all availabre triggers
