### ISSUE TITLE
POW - MQTT update rate

### ISSUE THREAD

**Issue by pmknowles** [arendst/Sonoff-Tasmota#3648]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Hardware used : Sonoff POW R1
- [x] Provide the output of command ``status 0`` :
```
06:57:31 CMD: status 0
06:57:31 MQT: stat/sonoff-washerdrier-POW/STATUS = {"Status":{"Module":6,"FriendlyName":["Sonoff-washerdrier"],"Topic":"sonoff-washerdrier-POW","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
06:57:31 MQT: stat/sonoff-washerdrier-POW/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:34:58","StartupUTC":"2018-08-31T05:22:33","Sleep":0,"BootCount":19,"SaveCount":37,"SaveAddress":"F7000"}}
06:57:31 MQT: stat/sonoff-washerdrier-POW/STATUS2 = {"StatusFWR":{"Version":"5.14.0","BuildDateTime":"2018-05-15T15:18:02","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
06:57:32 MQT: stat/sonoff-washerdrier-POW/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["x",""],"TelePeriod":300,"SetOption":["00008009","55818000"]}}
06:57:32 MQT: stat/sonoff-washerdrier-POW/STATUS4 = {"StatusMEM":{"ProgramSize":487,"Free":516,"Heap":21,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":255}}
06:57:32 MQT: stat/sonoff-washerdrier-POW/STATUS5 = {"StatusNET":{"Hostname":"sonoff-washerdrier-POW-8074","IPAddress":"192.168.0.117","Gateway":"192.168.0.1","Subnetmask":"255.255.0.0","DNSServer":"192.168.0.1","Mac":"x","Webserver":2,"WifiConfig":3}}
06:57:32 MQT: stat/sonoff-washerdrier-POW/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.183","MqttPort":1883,"MqttClientMask":"sonoff-washerdrier","MqttClient":"sonoff-washerdrier","MqttUser":"openHAB","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
06:57:32 MQT: stat/sonoff-washerdrier-POW/STATUS7 = {"StatusTIM":{"UTC":"Fri Aug 31 05:57:32 2018","Local":"Fri Aug 31 06:57:32 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1}}
06:57:32 MQT: stat/sonoff-washerdrier-POW/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
06:57:32 MQT: stat/sonoff-washerdrier-POW/STATUS10 = {"StatusSNS":{"Time":"2018-08-31T06:57:32","ENERGY":{"Total":1.221,"Yesterday":0.831,"Today":0.391,"Power":106,"Factor":0.38,"Voltage":240,"Current":1.159}}}
06:57:32 MQT: stat/sonoff-washerdrier-POW/STATUS11 = {"StatusSTS":{"Time":"2018-08-31T06:57:32","Uptime":"0T00:34:59","Vcc":3.143,"POWER":"ON","Wifi":{"AP":1,"SSId":"pkm-24","RSSI":18,"APMac":"E4:18:6B:AA:51:74"}}}
```
I'm trying to understand the logic of the MQTT messages for the POW. It's sending a message approximately every 2 seconds while the washer is going and ignoring the logging period set in the MQTT page. It's not a problem as such I'd just like to know how it decides when to send a message. I've read the threshold section but I'm not sure that helps me. The POW page says the preferred method is the push and will send a message every 5 minutes if set to 300. Console doesn't show any status requests so I'm not sure why it is sending so many messages.
I downgraded from 6.1.1 to 5.14 to see if it changed anything but doesn't seem to.
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by curzon01** [comment]
Set `PowerDelta 0` - see Wiki for details

**Comment by pmknowles** [comment]
Thanks. It may be helpful if that was on the POW page of the wiki. I couldn't understand why the immersion heater wasn't doing it but the washer was. The immersion is steady state but the washer is constantly changing with motor restarts and water on/offs.

**Comment by curzon01** [comment]
I've made a note on [Pow page](https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Pow-and-Pow-R2#push-result-using-telemetry)

**Comment by pmknowles** [comment]
Thanks I started on 5.11 and missed the change
