### ISSUE TITLE
Survey/Best Practice:  Examples of 3d printed cases for Tasmota based projects

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#3650]
Hi together,

i just ordered a 3d printer (cant wait delivery...) **Main reason was i want/need cute cases for my "Things" builded with Tasmota!**

Cases for WemosMinis (and others) with Power Supply, Sensors, Displays, Switches, Buttons, Touch Inputs and many many more (mp3 Player / Loudspeaker)....

It would be great if you share your designs! 

Thx in advance!

**Comment by meingraham** [comment]
@Jason2866 where are your designs posted?

**Comment by ascillato** [comment]
A very complete website with lots of cases and stuff for 3D printing is https://www.thingiverse.com

**Comment by Jason2866** [comment]
@meingraham 
Still no designs. I am a beginner. Printer arrived today :-)

**Comment by Jason2866** [comment]
@ascillato Thx for the tipp/link

**Comment by ascillato** [comment]
Link added to the wiki
