### ISSUE TITLE
Switch a light but only at night

### ISSUE THREAD

**Issue by Kaimane** [arendst/Sonoff-Tasmota#3653]
I connected the HC-SR501 to GPIO14 and the light is switched on (and off) if the sensor detected a movement. Is there any solution to do that only at night? I thought about adding a TSL2561 but I found no possible way to bring the two sensors into dependence.
Next idea was using the variables %sunrise% and %sunset% ... If sunrise is true disable switching the light. If sunset is true enable switching the light.
But how to set this rules? Would it be possible?

**Comment by Jason2866** [comment]
Take a look in wiki
https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#examples

**Comment by ascillato** [comment]
Hi,

If you feel that your question has been answered, please remember to close this issue. Thanks
