### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by raisude** [arendst/Sonoff-Tasmota#366]
I have a sonoff basic. Gpio14 configured as Button2. Pushing the button noteingewiesen happens. Ehen configured as switch2 pushing the Button the Relais toggles. Releasing the button the Relais toggles again. 

What i have to do that configuration button2 funktions?

Regards Rainer

**Comment by davidelang** [comment]
hitting button2 trys to switch relay2, if you don't have a relay2 to switch, you won't see anything happen.

what is it you are trying to have happen when you press the switch connected to gpio14?

**Comment by raisude** [comment]
I have to momentanary Switches. Pressing ohne of them should do the same as the Button of the Sonoff. This means they should also toggle the Relay1.

**Comment by davidelang** [comment]
then configure gpio14 as switch1 and change switchmode1 until you get the 
behavior you are looking for.

**Comment by raisude** [comment]
I have done this. But doing this the Relais was switched off and on in unregular intervalls without doing anything.

**Comment by davidelang** [comment]
Then you need to add a pull-up resistor on gpio14

**Comment by raisude** [comment]
Which Kind of Resistor should this be?

**Comment by davidelang** [comment]
a 4-10k resister is common, really just about anything will do. connect it 
between gpio14 and 3.3v

**Comment by raisude** [comment]
Ok i will Text this what about the Second Switch? Momentary connected to on of the serial ports?

Also ohne resistor between the serial port and 3.3v. Of connecting the Second Switch parallel to the First?

**Comment by davidelang** [comment]
what do you want the second switch to do?

**Comment by raisude** [comment]
The same. Toggling Relais1.

**Comment by davidelang** [comment]
then you need to wire it in parallel with the first switch, not to a seperate 
GPIO. This firmware doesn't allow multiple GPIOs to have the same functionality.
k

**Comment by davidelang** [comment]
did this solve your problem?

**Comment by raisude** [comment]
Sorry for not giving feedback. The sonoff is in italy and during the week i'm in Germany. In italy i Bad no resistor so i can test it at the Weekend. 

So far thanks for your support. I will report on saturday.

**Comment by raisude** [comment]
Today I have tested the resistor between 3.3V and GPIO14. Seems that this solved the problem of the ghost switching ... .

Thanks for your support.

Regards Rainer

**Comment by davidelang** [comment]
please close the issue if it's resolved.
