### ISSUE TITLE
Sonoff basic web interface

### ISSUE THREAD

**Issue by vaidyasr** [arendst/Sonoff-Tasmota#3661]
My 2 sonoff's are running fine on Tasmota latest firmware. But can't access via web interface. I can able to ping to the IP address. What could be the issue?

**Comment by ascillato** [comment]
Please, as use the template

**Comment by ascillato2** [comment]
Hi, I could not reproduce your issue. Please, erase your flash and recompile and flash.

**Comment by Frogmore42** [comment]
Status 0 would at least give more of a hint as to what you are actually using.  I found that unless I completely erased the flash and then reflash do, my devices that were previously using an older version would not work when I updated them using new firmware with core 2.4.2.  The serial port output indicated that they were restarting.  So, that is another clue about what is happening.  What do yours say?

**Comment by vaidyasr** [comment]
I have flashed initially using tasmota OTA. Then I upgraded the firmware via web interface and it was successful. I can even control via mqtt using Hass now. But can't login via web interface. To erase and reflash do I need to open and do soldering?

**Comment by ascillato2** [comment]
Yes

**Comment by onkelbeh** [comment]
No, soldering not necessarily, on a Sonoff Basic Touch or S20 the ports are plated-through, so you can insert the pins of your serial cable in the board and press them a bit sideways with a finger while flashing. Then, dont forget to press the button while you insert the usb plug into your computer. If you have to flash them frequently it could be easier if you solder some pins.

**Comment by ascillato2** [comment]
Hi

Have you managed to solve your issue?

**Comment by vaidyasr** [comment]
Will be doing today evening.

**Comment by ascillato2** [comment]
Hi

Have you managed to solve your issue?

**Comment by ascillato2** [comment]
Hi,

No problem. When you have time to flash your sonoff again, please report it back. Thanks
