### ISSUE TITLE
item Openhab

### ISSUE THREAD

**Issue by MabsHA** [arendst/Sonoff-Tasmota#3662]
how do i create the item in openhab when i use wemos d1 mini with BH1750 and get the folowing MQTT

MQT: Mabs/SmartHouse/tele/Wemos/SENSOR = {"Time":"2018-09-01T11:30:18","BH1750":{"Illuminance":296}}

greeding Maurice

**Comment by Jason2866** [comment]
Should work:

`Number  Test_Illuminance  "Illuminance [%.1f Lux]"    { mqtt="<[broker:Mabs/SmartHouse/tele/Wemos/SENSOR:state:JSONPATH($.BH1750.Illuminance)]" }`

**Comment by Jason2866** [comment]
Better aks questions OpenHab related at:
https://community.openhab.org/

**Comment by MabsHA** [comment]
Yes!!!! works thank you very mutch
