### ISSUE TITLE
Request, esp8285 successful firmware, modify the GPIO position

### ISSUE THREAD

**Issue by 1043717432** [arendst/Sonoff-Tasmota#367]
Request, esp8285 successful firmware, know the location of the switch pins are gpio0, gpio4, gpio9, gpio10, how to modify the firmware so that you can use the 2 switches, respectively, the 3 switches, the use of the 4 switches?
Also want to access to the MQTT to send the control switch, but also access to temperature and humidity sensors to the gpio14, how to set the request firmware?
![qq 20170420231004](https://cloud.githubusercontent.com/assets/22461690/25237906/7dece546-261e-11e7-9d69-e4d58546647b.png)

**Comment by 1043717432** [comment]
My chip is ESP8285, after the success of Sonoff-Tasmota, I found the touch switch pin gpio0 and gpio4, and the other 1 switches are 3 touch switch, pins are gpio0, gpio4, gpio9, I want to ask how to modify the firmware, so can the normal use of the touch switch!

**Comment by davidelang** [comment]
This is all done in the module configuration

select the WeMos and you can then set any gpio to any function.

**Comment by 1043717432** [comment]
@davidelang  Thanks！！ I'll test it right away! Thank

**Comment by 1043717432** [comment]
@davidelang  Cannot start after modification!

**Comment by davidelang** [comment]
see what shows up in the logs (serial console if nothing else)

you can always reset your config and try again. You may have attempted to use a 
GPIO that conflicts with something else on your board.
k

**Comment by 1043717432** [comment]
@davidelang This is the IP address of the 86 box switch on the network, which means that it may not start successfully! Unable to learn log content!

**Comment by davidelang** [comment]
you can see the logs via the serial port (with the appropriate settings)

David Lang
k

**Comment by 1043717432** [comment]
@davidelang Query less, I use the Arduino ide firmware.

**Comment by davidelang** [comment]
using the arduino ide firmware doesn't mean that you can't see the serial 
port. AsI understand it, the IDE has a serial monitor specifially for that (I 
use other software)

**Comment by davidelang** [comment]
did you get this working?

**Comment by 1043717432** [comment]
@davidelang 
Please close the problem
