### ISSUE TITLE
Old Version 6.1.1 on Maddox

### ISSUE THREAD

**Issue by MaxBec** [arendst/Sonoff-Tasmota#3671]
Hey guys,

i entered this URL in OTAURL:
http://sonoff.maddox.co.uk/tasmota/sonoff.bin 

And if I send the command upgrade 1, then it still updates to 6.1.1
Is there still the old Version on maddox?

**Comment by Stuart-Richards** [comment]
I'm seeing the same, but also with the pre-compiled binaries from github. What's supposed to be the new 6.2.0 version is still reporting as 6.1.1?

**Comment by arendst** [comment]
Oops that would be bad. I'll check....

**Comment by arendst** [comment]
Just checked.

Github release v6.2.0 binaries at https://github.com/arendst/Sonoff-Tasmota/releases look fine to me. At least sonoff.bin and sonoff-sensors.bin I've just tested.

**Comment by ascillato2** [comment]
Closing as the question has been answered. Thanks.
