### ISSUE TITLE
Wrong layout for sonoff basic

### ISSUE THREAD

**Issue by mkh595** [arendst/Sonoff-Tasmota#3674]
**Describe the bug**
I upgraded Sonoffs basic from version 5.11 to 5.14 and to 6.2.0 via OTA successfully.
When I flashed version 6.2.0 directly and customized pins, layout changed

![basic5](https://user-images.githubusercontent.com/30566575/44957273-ba7d3b00-aed0-11e8-9471-64a59cbd860b.PNG)

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [X] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : Sonoff basic
- [X] _Provide the output of command_``status 0`` :
```
17:06:46 CMD: Status 0
17:06:46 MQT: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":["sonoff","sonoff2"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":7,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
17:06:46 MQT: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffxxx","OtaUrl":"http://192.168.1.15:80/arduino/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:38","StartupUTC":"2018-09-02T15:06:08","Sleep":0,"BootCount":3,"SaveCount":7,"SaveAddress":"F5000"}}
17:06:46 MQT: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.2.0","BuildDateTime":"2018-09-02T17:00:47","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
17:06:46 MQT: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":1,"LogHost":"192.168.1.15","LogPort":514,"SSId":["mkh","mkh-samsung"],"TelePeriod":300,"SetOption":["00008009","55818000","00000000"]}}
17:06:46 MQT: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":447,"Free":556,"Heap":20,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0F582794","24000001","230217A6","00000000"]}}
17:06:46 MQT: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-7489","IPAddress":"192.168.1.236","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.25.1","Mac":"60:01:94:68:DD:41","Webserver":2,"WifiConfig":5}}
17:06:46 MQT: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.14","MqttPort":1883,"MqttClientMask":"ESP_%06X","MqttClient":"ESP_68DD41","MqttUser":"","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
17:06:46 MQT: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Sun Sep 02 15:06:46 2018","Local":"Sun Sep 02 17:06:46 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":99,"Sunrise":"06:03","Sunset":"19:28"}}
17:06:46 MQT: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2018-09-02T17:06:46","Switch2":"ON"}}
17:06:46 MQT: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2018-09-02T17:06:46","Uptime":"0T00:00:38","Vcc":3.062,"POWER1":"OFF","POWER2":"OFF","Dimmer":10,"Fade":"OFF","Speed":1,"LedTable":"OFF","Wifi":{"AP":1,"SSId":"mkh","RSSI":62,"APMac":"2C:4D:54:83:7F:68"}}}
```

**To Reproduce**
See screenshots

**Expected behavior**

**Screenshots**

After initial flash of version 6.2.0 is layout correct

![basic1](https://user-images.githubusercontent.com/30566575/44957178-75a4d480-aecf-11e8-8900-e1d7237064fa.PNG)

Left side is device upgrade from version 5.14, right side flashed directly version 6.2.0

![basic2](https://user-images.githubusercontent.com/30566575/44957203-b1d83500-aecf-11e8-91b0-e58c9e90bc3a.PNG)

Same pins are set on the right side

![basic3](https://user-images.githubusercontent.com/30566575/44957236-3cb92f80-aed0-11e8-973c-5f33bde1d1ec.PNG)

After save

![basic4](https://user-images.githubusercontent.com/30566575/44957259-97eb2200-aed0-11e8-8c08-a23c25915302.PNG)

I uploade via file back version 6.1.1 and set pins to 00

![basic7](https://user-images.githubusercontent.com/30566575/44957660-87d54180-aed4-11e8-8e72-2d110caa3f1c.PNG)

layout is OK

![basic6](https://user-images.githubusercontent.com/30566575/44957671-bc48fd80-aed4-11e8-91d3-8abfaa8dcc50.PNG)

Same pins are set on the right side

![basic8](https://user-images.githubusercontent.com/30566575/44957713-18ac1d00-aed5-11e8-9eef-6969b2ad92c4.PNG)

layout wrong also in version 6.1.1

![basic9](https://user-images.githubusercontent.com/30566575/44957710-13e76900-aed5-11e8-991c-2cca69c56b69.PNG)

I returned back to version 5.11.1a, set same pins on right side

![basic10](https://user-images.githubusercontent.com/30566575/44957887-07b0db00-aed8-11e8-903b-cf4bb9083382.PNG)

and now is layout OK

![basic11](https://user-images.githubusercontent.com/30566575/44957901-5fe7dd00-aed8-11e8-9cb6-b63609956a3c.PNG)

**Additional context**

Could be this behaviour caused by fact that version 5.11.1 has different number for Button1 and PWM1?

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
As you said the latest version shuffled some GPIO around.

There is an issue here that explains it too. Can't find it just now.

Doesn't matter. The addition of more switches has shuffled some GPIOs around.

**Comment by ascillato2** [comment]
Hi,

Thanks for share a detailed information of this issue. We need to add this information to the wiki as a breaking change from old versions to last.

**Comment by mkh595** [comment]
I don't think that it is breaking change but it is bug as this happen only if PWM1-5 or PWM1i-5i is selected.

**Comment by ascillato2** [comment]
Sorry. Breaking Change means a change in the code that it is backward incompatible. So, those configurations were not ported properly from old version to the new version due to changes in the GPIO definition.

**Comment by ascillato2** [comment]
If you need more information, please follow the links. Thanks

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
