### ISSUE TITLE
MQTT config

### ISSUE THREAD

**Issue by sangt1989hn** [arendst/Sonoff-Tasmota#3688]
I upload fw tasmota with esptool 
1. MQTT of me, 
![capture](https://user-images.githubusercontent.com/36691791/45023895-d2d08f80-b061-11e8-8866-ba1cd2df36d2.PNG)
and it's show
![capture](https://user-images.githubusercontent.com/36691791/45023964-07444b80-b062-11e8-8a14-21e6e0db154a.PNG)
2. I don't use gpio 14 and gnd.
i have config gpio 14 on web - mode : (9) switch1 .
i use 2 jum with switch physical and nothing happen

**Comment by benzino77** [comment]
Is your mqtt_host's name "sonoff"?

**Comment by petez69** [comment]
Is "Sonoff" your MQQT broker, does it resolve on your network ?

**Comment by ascillato2** [comment]
It is better/faster to use the IP of your MQTT server in the HOST field.
