### ISSUE TITLE
ESP8285 support

### ISSUE THREAD

**Issue by robdejonge** [arendst/Sonoff-Tasmota#3698]
My understanding is that the ESP8285 is fully compatible with the ESP8266, except that it has more memory. I've found [some nice-looking wall switches](https://www.aliexpress.com/item/Cnskou-Manufacturer-Wifi-Touch-Switch-LED-Light-Wall-Smart-Home-Remote-Control-US-Switch-2-Gang/32834612307.html?spm=a2g0s.8937460.0.0.51802e0eYVJcMo) that use this controller, and would like to try and flash them with Tasmota.

Any experience out there with the ESP8285?

**Comment by Frogmore42** [comment]
Esp8285 actually is an esp8266 integrated with a 1MB flash part.  So, yes it is already supported and works fine.

**Comment by robdejonge** [comment]
That is excellent news. I've asked the supplier of the switch linked above for a photo of the PCB, with a bit of luck they'll send it so I can access the ease with which I can hook it up for flashing and then order one to give it a go.
