### ISSUE TITLE
How to use 2 HC-SR04 Ultrasonic Sensors

### ISSUE THREAD

**Issue by asking23** [arendst/Sonoff-Tasmota#3702]
I came to an Application where there is requirement for 2 Ultrasonic Sensors. In the Module Configuration i am able to select 2 Different Sensor PIN Definitations. But only 1 is displayed in the home screen menu of Tasmota Firmware

How to use 2 Ultrasonic sensors ?? with Tasmota Firmware ?

Please do needful.

**Comment by ascillato** [comment]
Not supported
