### ISSUE TITLE
Rule commands shortcuts?

### ISSUE THREAD

**Issue by HoerMirAuf** [arendst/Sonoff-Tasmota#3703]
Hi Volks,

I am using a ESP12 with tasmota to make IR Controlled Device Wifi Controlled.
A IR-Reciever on one GPIO a IR-Transmitter LED on a other GPIO.
The IR-Transmitter LED connected to the original Device-IR Receiver like a optocoupler.
All the IR Commands a know received by the ESP and the ESP hand off it to the Device by Rules.
Rule Example:
on IrReceived#Data=FFB04F do irsend {Protocol:NEC,Bits:32,Data:0xFFB04F endon

To hand off all IR Commands need a lot off rule Text and the rule memory is only 3x511 signs.

A lot off Space is wasted with repeated Text like "Irreceived#Data"  Is there a possibility to get shortcuts like IRR for IrReceived by example to save some rule space? Or a varaibale to set a repeated command?

**Comment by ascillato** [comment]
Not supported by now, but it is a very good Idea :+1:
