### ISSUE TITLE
Drop internal connections between sensors and actors in favor of rules

### ISSUE THREAD

**Issue by renne** [arendst/Sonoff-Tasmota#3705]
**Have you look for this feature in other issues and in the wiki?**
Yes.

**Is your feature request related to a problem? Please describe.**
If a rule is deactivated the internal connection between sensors (e.g. Switch1) and actors (e.g. Power1) is reactivated causing unexpected/unwanted behaviour.

**Describe the solution you'd like**
Generic GPIOs which send high and low events for rules instead of buttons/switches internally connected to actors.

**Describe alternatives you've considered**
Current situation: SwitchTopic + SwitchMode + internal connection = very complex and thus error-prone.

**Comment by ascillato** [comment]
Hi,

Your statement is too general. Can you give an example in which you find this behaviour?

**Comment by renne** [comment]
I'm using a motion detector with the staircase timer example. Sometimes I have to deactivate the rule over night. In that case Switch1 switches power of the H801 on and off which should not happen. It's quite annoying for guests if a 6000 lumen 6500k LED stripe switches on at night for 2 seconds at every movement while sleeping. ;-)

**Comment by ascillato** [comment]
Ok, but that was expected. Rule feature deactivated, switch will trigger the output.

I was thinking on doing somthing like you have implemented. May be, with your help/ideas we can develop a new rules example for that.

What about using a VAR1 to enable or disable the logic. So, each time the switch triggers, the rules feature will check that VAR1 is 1 (enabled) or 0 (disbaled) to continue or not with the logic.

Something like this was done in the example of the Thermostat.

What do you think?

If you want to chat and discuss this, you can find us now at the Tasmota Chat.
