### ISSUE TITLE
IDE-less building?

### ISSUE THREAD

**Issue by l29ah** [arendst/Sonoff-Tasmota#371]
Is it possible to compile the project w/o installing heavy GUI-driven tools and doing manual dependency management? I'd prefer to automate the firmware update process without resorting to horrible mouse-driving kludges.

**Comment by davidelang** [comment]
read this page https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite and 
look at the platformio section

**Comment by l29ah** [comment]
Oh, i've overlooked it. Thanks and sorry for the noise.
