### ISSUE TITLE
Control relay with button on Blitzwolf SHP2

### ISSUE THREAD

**Issue by kmgalanakis** [arendst/Sonoff-Tasmota#3712]
I've just flashed the SHP2 with Tasmota.

On the module configuration, which module I choose? I chose `Sonoff Pow` and everything seems to work fine but I cannot get the hardware button on the SHP2 to work.

Ideally, I would like to be able to control the relay with the hardware button as well. Is this kind of thing possible, or do I have to stick with the changing through the web interface?

Thank you in advance.

**Comment by ascillato** [comment]
Please, choose **_BlitzWolf SHP2_** from the module configuration

**Comment by kmgalanakis** [comment]
I was flashing an old version of the firmware but the latest version solved all my problems.

Awesome, thanks!
