### ISSUE TITLE
Fade in PWM mode

### ISSUE THREAD

**Issue by marekzehra** [arendst/Sonoff-Tasmota#3714]
Hi,
would it be possible to allow fade command also in PWM mode (SetOption15 0)?

I'm using H801 to control two white led strips (W1 and W2). Fade command is not found until SetOption15 is ON.

**Comment by arendst** [comment]
Not at the moment.

**Comment by albzn540** [comment]
Will it be added in the feature?

**Comment by vstonkus** [comment]
Currently I'm testing a prototype of using H801 for multiple led strips in my house. Fade looks awesome, but it only works if Option15 is turned ON. However multiple strips doesn't work well with Option15 enabled - if I use any RGB channel, it turns off white channels.

**Comment by Povilas1** [comment]
Can we expect this feature implemented in near future? It would be handy to use one H801 module for all my led strips.

**Comment by s-hadinger** [comment]
Yes, work in progress, see #6942
