### ISSUE TITLE
PowerOnState=1 and stat message

### ISSUE THREAD

**Issue by a-sp** [arendst/Sonoff-Tasmota#372]
It's my understanding that when the switch is powered on with a power cycle (with PowerOnState set to 1), the stat message is not generated.
Would it be possible to send the stat message also when the switch is automatically set to ON after a power outage?

**Comment by dy008** [comment]
Hi，I have same qusion!
but i just change sonoff.ino it:
#define APP_POWER              1            // Default saved power state On
and power on it sent PowerOnState set to 1!
just do it!

**Comment by arendst** [comment]
The stat message is generated ten seconds after power on allowing all communication and sensors to settle.

**Comment by davidelang** [comment]
it sounds like this is not needed, the message is already generated. reopen this issue if you disagree.

**Comment by a-sp** [comment]
Would it be possible to send the stat message immediately? After few seconds, my automation platform (home assistant) override the PowerOnState=1 and powers off the sonoff.

**Comment by davidelang** [comment]
It waits a few seconds before sending the first message to give everything time 
to settle.

This sounds like you need to change home assistant to not change it to what it 
considers the prior state when it comes up.
