### ISSUE TITLE
Blink: individual OFF/ON delay and/or Backlog: add repeat feature

### ISSUE THREAD

**Issue by TimelessNL** [arendst/Sonoff-Tasmota#3720]
Hi,

**First request:**
Would it be possible to let blink have a separate ON/OFF delay?
**Configuration**:
blink_time_on = 1 // 0.1sec
blink_time_off = 10 //1sec
**Result**:
relay ON --> delay 0.1sec --> relay OFF --> delay 1sec --> repeat

_I know this could be possible with a backlog, but unfortunately there is no way to repeat a backlog._
**Second request:**
Add a repeat feature to backlog :)

Please let me know what you think.

**Comment by ascillato** [comment]
Hi,

You can repeat a backlog with `ruletimer` command in a rule:

_Example:_
when you call the `event myblink` by command, by another rule or by mqtt, your sonoff will turn on relay 1, wait 1 second, turn off relay, wait 1 second and repeat.

```
pulsetime1 10
rule 1
rule on event#myblink do backlog power1 1; ruletimer1 2 endon on rules#timer=1 do event myblink endon
```

To stop the repeat cycle, type `rule 0`.

Hope this approach fit your needs.

**Comment by TimelessNL** [comment]
@ascillato2 I tried your suggestion, but unfortunately there is no way of creating a 0.1s on and 0.3s off interval repeat. Sorry if my first example was unclear. But I need my Tasmota to emulate a kW/h imp meter, so that's why I need such a short delay interval.

**Comment by ascillato** [comment]
Sorry, those short times are not supported by rules
