### ISSUE TITLE
Rules: Add system event Time#Hour

### ISSUE THREAD

**Issue by alpha197** [arendst/Sonoff-Tasmota#3722]
In Rules we can use Time#Minute as every minute trigger. But there is no correspondant Time#Hour for triggering hourly. There is "Time#Set" which seems to trigger hourly, but actually it is not a time based envent (triggers on NTP times sync).

I think it would be more consistent to use Time#Hour as another time-based system event.

Background: I need to turn on a power device every hour for 45 minutes. To keep it simple use a combination of rule and pulsetime:
`rule1 on Time#Minute|60 do power on endon`
`pulsetime 2800`
Every Hour (= minute modulo 60) the device is powered on for 45 minutes (=100+2700 seconds pulsetime).

Problem with this solution: 00.00h  (midnight) doesn´t trigger. Therefore something like "Time#Hour" would be great.

**Comment by ascillato** [comment]
Hi

It is already there. The trigger is called time#set

Please, read the wiki for more infomation. Thanks
