### ISSUE TITLE
Add counter_down function from "current time" of the Timer web page UI

### ISSUE THREAD

**Issue by honggiwei** [arendst/Sonoff-Tasmota#3725]
I want to control my relay on/off after some specific minutes , just like Regulating Timer Relay,
I entry web page of the Timer setting, but it need to know what current time it is, and need calculate the  added minutes we want then setting back into the desired time value.

Can web page add one new field inputed by offset value we want, and then auto calculate from current time,
just like sunrise and sunset function.
mybe show it work after 15 minutes, 30 minutes, 1 hours, 2 hours etc. from current time. to provide us to easy select.

I know:
"Plusetime" command can achieve, but counter interval not friendly use.
"Sunrise" or "Sunset" of the Timer web page UI, can enable offset value.
but not from "current time".

**Comment by ascillato** [comment]
Sorry. Pulsetime is exactly that.

I understand that a console is not as user friendly as a nice graphical menu. But the webmenu is flash and memory consuming. And there isn't much more memory to play around.

Please, consider using your home automation software as friendly UI to set the pulsetime you need.

Remember that Tasmota allows to receive commands by mqtt so, your HA can reconfigure Tasmota each time you need.

There are several tools with very nice UI that are getting better and better with more functions that can configure and manage Tasmota as

TasmoAdmin 
Yeti phone App
Home automation software like home assistant, openhab, domoticz, nodered, etc. 

Hope this helps.
