### ISSUE TITLE
S31 Lite

### ISSUE THREAD

**Issue by byrnes-patrick** [arendst/Sonoff-Tasmota#3731]
I know there is support is there for the S31 but could the S31 Lite also be added? It's the same as the S31, but without the power monitoring.

**Comment by ascillato** [comment]
If you choose S31, your device works fine?

**Comment by ascillato2** [comment]
Ok, Thanks.

Issue tagged.

**Comment by arendst** [comment]
Select Sonoff Basic for S31 lite.
