### ISSUE TITLE
sonoff basic with sensor dht11

### ISSUE THREAD

**Issue by lpt2007** [arendst/Sonoff-Tasmota#3735]
Hi,

I connected dht11 sensor to my sononff basic like this:
1 ------- 1 (VDD)
2 ------- 5 (GPIO14)
3
4 ------- 4 (GND)

I configured tasmota configuration/configure module:
GPIO14 Sensor ----- DHT11

Now can get TEM/HUM from sensor?

Any idea?

**Comment by ascillato2** [comment]
Hi,

Sorry. As you did not complete the troubleshooting template there is a lot of information missing in order to help you properly. Please, complete the template or better go to the Tasmota Chat. Thanks
