### ISSUE TITLE
I flash sonoff basic with latest sonoff.bin file trough OTA, now blinking light

### ISSUE THREAD

**Issue by lpt2007** [arendst/Sonoff-Tasmota#3736]
Hi,

I installed latest sonoff.bin 6.2.1 flie trough OTA. Now I get blinking led on my sonoff basic? I can't see device on my network? How to connect to device? What blinking light means?

**Comment by ascillato2** [comment]
Hi,

Sorry. As you did not complete the troubleshooting template there is a lot of information missing in order to help you properly. Please, complete the template or better go to the Tasmota Chat. Thanks
