### ISSUE TITLE
Interchange Option in Tasmota

### ISSUE THREAD

**Issue by DocGame69** [arendst/Sonoff-Tasmota#3739]
I have been looking for a long time for a reasonable solution for a Tasmota interchange. There are different approaches (relays, scripts in IOBroker etc.).
My question: Would not it be possible that a function is installed, in which one can enter the IP address of a "partner Tasmota". In this "Partner Tasmota" then the IP address of the other would be specified. When a device is switched on, the other one is also on and off in exactly the same way. To this white would have to be synonymous to realize a change circuit or I have a mistake?

Sorry vor the Bad Englisch (Google Translate :-) )

**Comment by andrethomas** [comment]
The simplest way would be to get a mqtt server on your lan (like mosquitto) and use a HA software such as home assistant, hassio or node-red

**Comment by ascillato2** [comment]
There are example or that in the wiki. You can control one device with another using mqtt broker, mqtt switchtopic, rules to publish mqtt commands, rules to send web commands and knx.

Hope this helps
