### ISSUE TITLE
Unclear Syntax in console windows setting up switchmode

### ISSUE THREAD

**Issue by the-Leitz** [arendst/Sonoff-Tasmota#375]
i'm trying to change te SwitchMode in the console window. but nothing seems to work.
i have tried
Switchmode=3
Swtichmode3
Switchmode 3
Cmd/Set/Switchmode3 etc
nowhere is a good description of how the syntax is used
are they the same as the mqtt commands do i have to use slashes , etc
i just want to set it up as a pushbutton, editing the firmware seems not the way to go, but there are settings there (why ?), from all the information i can find, i think the only way to configure this is inside the console.
i'm not using any server to control it.
Can somone tell explain how to correctly use the syntax in the console ?

**Comment by davidelang** [comment]
have you gone through the wiki page?

https://github.com/arendst/Sonoff-Tasmota/wiki/Understanding-SwitchMode-and-SwitchTopic

**Comment by the-Leitz** [comment]
Yep if i give the command switchmode=3 i get an error (unknown command) i tried it with cmnd/set etc but i always get the same error

**Comment by davidelang** [comment]
try "switchmode1 3"

**Comment by the-Leitz** [comment]
Nope same error
13:54:24 CMND: Switchmode1 3
13:54:24 RSLT: DataCb Topic sonoff, Group 0, Index 1, Type SWITCHMODE, Data
3 (3)
13:54:24 RSLT: RESULT = {"Command":"Unknown"}
13:55:27 CMND: Switchmode 1 3
13:55:27 RSLT: DataCb Topic sonoff, Group 0, Index 1, Type SWITCHMODE, Data
1 3 (1 3)
13:55:27 RSLT: RESULT = {"Command":"Unknown"}

Op 23 apr. 2017 14:45 schreef "David Lang" <notifications@github.com>:

**Comment by dy008** [comment]
I think the switchmode and 1 no need Space!

**Comment by the-Leitz** [comment]
I tried that same result :(

Op 23 apr. 2017 15:56 schreef "Bill Deng" <notifications@github.com>:

**Comment by davidelang** [comment]
are you sure you have a gpio configured as a switch? until you do that, the 
switchmode commands will not work.

**Comment by the-Leitz** [comment]
Gpio ? It is just working fine as a toggle switch, but it needs to act like
a pushbutton

Op 23 apr. 2017 16:11 schreef "David Lang" <notifications@github.com>:

**Comment by davidelang** [comment]
go to the module config page and look at the gpio settings there. you need to 
set the gpio that you have the switch connected to to be a switch, otherwise 
things aren't going to work.

**Comment by the-Leitz** [comment]
I want the relay to act as a pushbutton, are we talking about the same
thing ?

Op 23 apr. 2017 17:11 schreef "David Lang" <notifications@github.com>:

**Comment by davidelang** [comment]
in sonoff terms, a led or relay is an output, a switch or button is an input. if 
you want to have something tell the sonoff to do something, you need to 
configure it as a switch or button

if you want to configure the sonoff tell something else to change, you need to 
configure it as a LED or relay

so if you are hooking a switch up to the sonoff to tell it to turn the relay on 
and off, you need to confure the gpio that you wire the switch to as a switch or 
button. If you want it to change relay1 (the built-in relay), this will need to 
be switch1 (since button1 is already defined)

does this clarify things?

**Comment by the-Leitz** [comment]
Not really, are you saying that the switchmode command does not change the behavior of the relay ? But why gives it an error (unknown command)

**Comment by davidelang** [comment]
the switchmode command changes what happens when you press a switch.

to set a switchmode, you have to first have a switch defined to set the mode on.

so if you are wiring a switch to gpio14, then you first have to define gpio14 as 
switch1, then you can issue the switchmode1 command

**Comment by the-Leitz** [comment]
:( is there any command to change the toggle in to a pushbutton ? (The
relay)

Op 23 apr. 2017 17:55 schreef "David Lang" <notifications@github.com>:

**Comment by davidelang** [comment]
you don't change the relay, you change the switch settings. This is what 
switchmode (and buttonmode for buttons) do.

but you have to have a switch defined before you can set it's mode.

have you defined a switch on the gpio yet?

**Comment by the-Leitz** [comment]
Shouldn't i configure a button ? And which gpio should i choose ?

**Comment by davidelang** [comment]
well, if you want to have it control relay1 (the built-in relay), you would need 
to configure button1, but since button1 is already defined (the button on the 
module) and you can't define two gpios to have the same function, you can't 
define button1. So you need to define switch1

As to which gpio you configure it on, that depends on which gpio you have wired 
it to. you need to configure the switch in software to match where you have 
attched the switch on the hardware.

**Comment by the-Leitz** [comment]
No i do not want control the relay with an external switch, i want to user the webinterface . When i Press the toggle button, i want the relay to turn on and directly off again. So It works like a pushbutton . I understand now that the button options in the firmware are all about, external buttons you can connect to the module. So thats not the way to go. Do you have any idea How i can achieve this ?

**Comment by davidelang** [comment]
so you aren't actually wiring up a physical switch?

you are just talking about changing the web interface?

There is no option to change the web interface, you would have to edit the 
webserver.ino source to add this functionality.
k

**Comment by the-Leitz** [comment]
Yes i think i Will have to do some scripting, I don't know if this is possible

**Comment by davidelang** [comment]
This is not scripting, it is modifying the C code in webserver.ino to add 
additional buttons to the html, and then to respond when those buttons are 
pressed.

**Comment by the-Leitz** [comment]
No no, no extra buttons, just the behaviour, like ' if on then off ' I don't think it is possible in tasmota, thx for the help

**Comment by davidelang** [comment]
that's what toggle is.

and no, tasmota does not give you any ability to redefine what the web interface 
does.

**Comment by the-Leitz** [comment]
i just want to say that i resolved it, i used the PulseTime Command and a single puls and it works :D

**Comment by djdom111** [comment]
The Leitz, can you tell me how you used the pulse time command on the console. I need to do the same with sonoff as you wanted and did it. But for me doesn't work.

**Comment by the-Leitz** [comment]
i'm sorry i can not remember the commands, but i used the pulstime command to give 1 pulse of 1 second that worked for me

**Comment by tomasroud** [comment]
cmnd/YOURDEVICE/pulsetime 10
will do when you send cmnd/YOURDEVICE/POWER ON ... it stays on 1 second and then OFF relay and set state to POWER OFF
