### ISSUE TITLE
Toggle not working on IE

### ISSUE THREAD

**Issue by Meinsda** [arendst/Sonoff-Tasmota#3753]
after some time the toggle button on the web interface don't work on Internet Explorer. Use different tasmota Devices. The command "power toggle" works

**Comment by arendst** [comment]
Let's say we do not support IE. Select one of many new alternatives like Edge, Chrome, Firefox, Safari ...

**Comment by Meinsda** [comment]
;) this is not a bug this is a feature? ;) I think there is only a Caching Problem. It is a very simple page

**Comment by arendst** [comment]
The page looks simple because javascript is doing the action

**Comment by ascillato2** [comment]
Hi,

Duplicated issue: #3557
