### ISSUE TITLE
Using sht3X sensor in hom assistant?

### ISSUE THREAD

**Issue by jascdk** [arendst/Sonoff-Tasmota#3758]
Hi - Home assistant won’t let me use the sensor - it is saying error . I think it is because it’s name is sht30x-something .

My bme280 is fine 

Can the name of the sht30x just be that?

**Comment by ascillato** [comment]
Please, complete the troubleshooting template in order to properly help you.

**Comment by ascillato** [comment]
### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato2** [comment]
Hi,

When you have time, please provide all the information requested and your HA configuration
