### ISSUE TITLE
Wemos d1 Mini freezing on power cycle when switch pulled down.

### ISSUE THREAD

**Issue by petrfaitl** [arendst/Sonoff-Tasmota#377]
Not sure if firmware or hardware is at fault, but using a Switch<x> on GPIO0 or GPIO2 on Wemos d1 mini leads to a freeze on PowerOn. This occurs when the switch is pulled down.

In my example, I'm using a reed switch, on garage door that's pulled down, when the garage is closed. If I recycle power on the Wemos it will not come back. Of course using the two pins above was intentional due to having an internal pull-up resistor on both. I had to resolve this by using another pin. Other than the two GPIOs above, all seem to behave.

**Comment by arendst** [comment]
As designed by hardware. By pulling GPIO0 down during power up you are placing the esp8266 in firmware upload mode. Do not pull down GPIO0 during power up if you want to run the software.
