### ISSUE TITLE
Alexa hue emulation works but 'isnt responding please check network connection and power supply'

### ISSUE THREAD

**Issue by bjhutchins** [arendst/Sonoff-Tasmota#3776]
alexa is finding devices but i just seem to control them!?
Seen people have previously had similar trouble but Whats going on?!

<img width="1312" alt="screen shot 2018-09-12 at 13 26 16" src="https://user-images.githubusercontent.com/43088329/45424811-856ea680-b68f-11e8-8a27-8ce70927f184.png">

**Comment by ascillato** [comment]
Hi,

There is a lot of information missing in order to help you properly. Please, complete the troubleshooting template.

Also, inform us if you are using a precompiled version or compiled by yourself. Which version, which esplib version, which hardware, which compiler, etc etc.

**Comment by ascillato2** [comment]
Hi,

Sorry, stills all the information requested is missing.

Please, when you have time, complete the information requested in order to properly help you.

Thanks

**Comment by bjhutchins** [comment]
i dont understand what else you need to know? sorry
