### ISSUE TITLE
"PROJECT- '_%06X'" not working?

### ISSUE THREAD

**Issue by prankousky** [arendst/Sonoff-Tasmota#3786]
Hi everybody,

I am trying to configure `user_config.h` before building and uploading `firmware.bin` to my sonoff devices. It works (compiles, can be uploaded, webGUI working, etc.), but I feel like setting `"PROJECT  '_%06X'"` does not work correctly.

I'd like my sonoff devices (a) `hostname`, (b) `MQTT Client & Fallback Topic`, (c) `MQTT Topic` all to be named something like `sonoff-5148`, 5148 in this case being an automatically generated value.

Here are the relevant parts of my code
```
// -- Project -------------------------------------
#define PROJECT                "sonoff- '_%06X'" 

// %topic% token options (also ButtonTopic and SwitchTopic)
#define MQTT_TOPIC             PROJECT           // [Topic] (unique) MQTT device topic, set to 'PROJECT "_%06X"' for unique topic including device MAC address
#define MQTT_GRPTOPIC          "sonoff- '_%06X'"         // [GroupTopic] MQTT Group topic
#define MQTT_BUTTON_TOPIC      "0"               // [ButtonTopic] MQTT button topic, "0" = same as MQTT_TOPIC, set to 'PROJECT "_BTN_%06X"' for unique topic including device MAC address
#define MQTT_SWITCH_TOPIC      "0"               // [SwitchTopic] MQTT button topic, "0" = same as MQTT_TOPIC, set to 'PROJECT "_SW_%06X"' for unique topic including device MAC address
#define MQTT_CLIENT_ID         "sonoff- '_%06X'"       // [MqttClient] Also fall back topic using Chip Id = last 6 characters of MAC address

// -- HTTP ----------------------------------------
#define WEB_SERVER             2                 // [WebServer] Web server (0 = Off, 1 = Start as User, 2 = Start as Admin)
#define WEB_PASSWORD           "verySecret"                // [WebPassword] Web server Admin mode Password for WEB_USERNAME (empty string = Disable)
#define FRIENDLY_NAME          "sonoff- '_%06X'"          // [FriendlyName] Friendlyname up to 32 characters used by webpages and Alexa
#define EMULATION              EMUL_NONE         // [Emulation] Select Belkin WeMo (single relay/light) or Hue Bridge emulation (multi relay/light) (EMUL_NONE, EMUL_WEMO or EMUL_HUE)
```
Here is a [screenshot](https://i.imgur.com/QZXbSCO.png) from my webGUI info page.

Now, `Hostname | sonoff- '_24D41C-5148` is **almost** correct, except the single quote, underscore, and the 24D41C part. Could you please tell me what I need to set all those variables to in order to get the desired `sonoff-<automatically-generated-4-digit-number` name for all of them?

As you can see, in webGUI, the device is even named `sonoff-'_%o6X'`, while it should be named `sonoff-5148`.

This is just a naming pattern I manually set anyway and can easily remember and use in, for example, node-red... example: instead of switching mqtt topic `cmnd/sonoff-5148/POWER` to `on`, I will link the output from mqtt topic `room/bedroom/nightstand/cmnd/POWER` **to** the sonoff-5148 mqtt topic. In this case, if I ever switch an outlet (from kitchen to bedroom), I do not edit anything on the sonoff device itself, but rather just in node-red (in this case, just switch 5148 to whatever the new ID would be and still keep all my mqtt controlls). Don't know if this is good practise, but it works for me :)

Thank you in advance for your help 👍

**Comment by ascillato2** [comment]
Hi,

Your idea is good. A Label to this issue has been added for future reference to be taken into account.

Thanks for share your ideas.

**Comment by ViniciusDS** [comment]
I have the same problem
