### ISSUE TITLE
Wiki incorrectly notes Pin 5 of the Sonoff Basic header is GPIO4 instead of GPIO14

### ISSUE THREAD

**Issue by joecotton** [arendst/Sonoff-Tasmota#379]
The [Expanding-Sonoffs page of the wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs), Examples section, notes in multiple places that pin 5 of the 5-pin programming header is GPIO4 (four), rather than the correct value of GPIO14 (fourteen).

(The GPIO Locations page with the pictures is accurate)

**Comment by davidelang** [comment]
it is a wiki,so you could fix it yourself :-)

I fixed it (I think, let me know if I missed anything)
