### ISSUE TITLE
security issu if own wlan down

### ISSUE THREAD

**Issue by TasmotaFan** [arendst/Sonoff-Tasmota#3791]
dear all,
when my normal wlan breaks down, the sonoff devices open their fallback Wlan sonoff-xxxx at 192.168.4.1 and are ready for unfriendly takeover by someone.

**Comment by ascillato** [comment]
Hi,

You have 2 options there to change that behaviour:

in Tasmota console type:

`wificonfig 5` in order to stop your WIFI_MANAGER to pop up

OR

If you want to have that WIFI_MANAGER option, just add an ADMIN Password from the configuration menu.
