### ISSUE TITLE
trigger for dimmer?

### ISSUE THREAD

**Issue by Newz20** [arendst/Sonoff-Tasmota#3793]
https://github.com/arendst/Sonoff-Tasmota/wiki/Rules
Tell me, please, what kind of trigger you can use for a dimmer to create rules.

**Comment by ascillato** [comment]
Please, explain exactly what you want to achieve

**Comment by ascillato** [comment]
It is already there. When you change dimmer value, Tasmota sends a mqtt message

**Comment by Newz20** [comment]
But I need to redirect to another topic

**Comment by ascillato** [comment]
From where you are sending the dimmer command?

**Comment by ascillato** [comment]
https://discord.gg/Ks2Kzd4

For a more dynamic conversation, please join us at the Discord Chat

**Comment by devanl** [comment]
It would be nice if you could trigger rules on the dimmer, I do not believe this is possible with current message?

**Comment by ascillato** [comment]
Yes, it is possible and it is implemented. Please, read the wiki at rules. Thanks

**Comment by devanl** [comment]
Got it, not sure how I missed that with how many times I read this. Thanks again!
