### ISSUE TITLE
Integrating RF 433 on wemos with Tasmota

### ISSUE THREAD

**Issue by peopledrivemecrazy** [arendst/Sonoff-Tasmota#3797]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Hardware used : Wemos D1 Mini

Adding RF 433 on a wemos, 
https://github.com/arendst/Sonoff-Tasmota/issues/1990#issuecomment-388509026 doesn't talk about wiring, I am looking for the connections, Any help will be greatly appreciated :smile:

**Comment by ascillato** [comment]
Hi,

Tasmota don't support integrating a 433mhz RF to a WEMOS by now.

Please check the open Pull Request #3797.

Thanks.
