### ISSUE TITLE
DomoticzUpdateTimer for Sensor

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#38]
Hello Theo,

thanks for your great work here... Today I updated my Sonoffs from the old version to the new Tasmota. This version makes everything so easy :-). And now it is possible to add Sensors Idx for Domoticz... Nice.

I have one little question:
My Temperature in Domoticz is only up to date when my Sonoff reboots. Is it possible to set an Updatetimer for the Sensor?

Greetings
Fabian

**Comment by arendst** [comment]
What device are you using?
Did you configure teleperiod for 300 seconds?

**Comment by 0n3-70uch** [comment]
Its an TH16... and you are richt its working :-). Good to know that the sensor update intervall is set by the teleperiod. Thx for help.
