### ISSUE TITLE
Support for EXS RELAY V5.0

### ISSUE THREAD

**Issue by cheise** [arendst/Sonoff-Tasmota#3810]
Your Firmware Support the EXS RELAY V3.1, i use this Device configuration for the EXS Relay V5.0, but i can use only first Relay on the V5.0 Relay, LED1 not working, too. Can you support the second Relay and LED1 in your next Releases, please ? 

The V5.0 Relay have this Pinouts:

 GPIO_USER,        // GPIO00 Module Pin 4
 GPIO_USER,        // GPIO01 Module Pin 3
 0,                        // GPIO02
 0,                        // GPIO03
 GPIO_USER,        // GPIO04 Module Pin 2
 GPIO_USER,        // GPIO05 Module Pin 1
 0, 0, 0, 0, 0, 0,     // Flash connection
 GPIO_REL1,        // GPIO12 Relay1 ( 1 = Off)
 GPIO_REL2,        // GPIO13 Relay1 ( 1 = On)
 GPIO_REL3,        // GPIO14 Relay2 ( 1 = Off)
 GPIO_LED1,       // GPIO15 LED1
 GPIO_REL4,       // GPIO16 Relay2 ( 1 = On)
 0
![img_3804_pin](https://user-images.githubusercontent.com/43306023/45931836-e2156f80-bf73-11e8-9595-f99018e69045.jpg)

![wifiv5](https://user-images.githubusercontent.com/43306023/46250630-1c34b480-c43f-11e8-9af9-9718ee243fe1.PNG)

**Comment by cheise** [comment]
The V5.0 Relay have this Pinouts:

     GPIO_USER,        // GPIO00 Module Pin 4
     GPIO_USER,        // GPIO01 Module Pin 3
     0,                        // GPIO02
     0,                        // GPIO03
     GPIO_USER,        // GPIO04 Module Pin 2
     GPIO_USER,        // GPIO05 Module Pin 1
     0, 0, 0, 0, 0, 0,     // Flash connection
     GPIO_REL1,        // GPIO12 Relay1 ( 1 = Off)
     GPIO_REL2,        // GPIO13 Relay1 ( 1 = On)
     GPIO_REL3,        // GPIO14 Relay2 ( 2 = Off)
     GPIO_LED1,       // GPIO15 LED1
     GPIO_REL4,       // GPIO16 Relay2 ( 2 = On)
     0

**Comment by Frogmore42** [comment]
You can copy the template for the v3.1 and add the extras for v5, by using the generic module type.  It looks like the v3.1 uses relay 1 and relay 2 for the single relay, so you will need to use relay 3 and 4 for the second one.  You will have to update both relays in Tasmota to get the real relay to turn on.  Perhaps there is a rule that can make it easier, so you only have to turn on one and the rule will take care of the other.

**Comment by cheise** [comment]
I have do that bevor over the generic profil. I can‘t toggle the second relay. Than i look in the sonoff.ino and determine only the first relay is hardcoded by the Firmware for „latching relay“ use ( void setlatchingrelay) when you take the EXS Relay profil. My expertise to patch this issue are very bad. :(

**Comment by Frogmore42** [comment]
Try set option 14
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands
That might work.

**Comment by cheise** [comment]
With "SetOption14=%20On" i can use both Relays with interlock Mode. I have 4 virtual Buttons. For interacting with the Relays i must use the Buttons pairwise (1-2  = Relay 1 and 3-4 = Relay 2), thats not what i need. With the "ESX Relay Profil" i can use the Relay 1 with 1 Button in Toggle Mode. Thats what i need for Relay 2, too, 1 Button for Relay 2 in Toggle Mode. You have any ideas?

**Comment by Frogmore42** [comment]
You are correct that there is code that special cases the ESX.  If you use VS Code with PlatformIO it has a search capability which you could use to search the code to find it and duplicate it for the second relay.  Or, you could probably write a rule that would do something similar.

**Comment by cheise** [comment]
Ok, i can wait, maybe, i hope the device becomes support with the next release. My expertise to patch the Firmware is very bad, thanks for your support.

**Comment by cheise** [comment]
Here is picture from the Board with Pinouts:
![img_3804_pin](https://user-images.githubusercontent.com/43306023/45931826-9cf13d80-bf73-11e8-9088-68d6f5bb68f4.jpg)

**Comment by arendst** [comment]
BTW do you have a link to this device? I cannot find it on ex-store.de

**Comment by cheise** [comment]
Here is the link:

https://ex-store.de/2-Kanal-WiFi-WLan-Relay-V5-Blackline-fuer-Unterputzmontage

Von meinem iPhone gesendet

**Comment by arendst** [comment]
In order to use EXS Relay V5.0 select the EXS Relay(s) module and add the two additional relays as used by the EXS Relay V5.0:


![image](https://user-images.githubusercontent.com/11044339/46258913-f6a4bb00-c4d1-11e8-980a-07269c3427aa.png)

**Comment by arendst** [comment]
Pls let me know if this works.

**Comment by cheise** [comment]
Everything is functional now, but two things are wrong. The output pins are reversed on the PCB. That's my mistake. You must change relay 1 into relay 2 and and the other way with relay 2, too. Second thing is, the state from relay is inverted. I must use 31=Relay3i and 32=Relay4i, see the picture below.....

![wifiv5 0](https://user-images.githubusercontent.com/43306023/46262614-dd1c6700-c503-11e8-8fe7-6edd9726cbc6.PNG)

**Comment by arendst** [comment]
If relay1 and 2 need to be reversed than the v3.1 version won't work anymore.

Is anyone still using v3.1 as it doesn't appear on the sellers website anymore?

**Comment by cheise** [comment]
> Is anyone still using v3.1 as it doesn't appear on the sellers website anymore?

You can leave it like that. Only the outputs on the PCB are reversed. No problem. For Relay 2 ( Relays 3+4 latching state) is the "i" option the right thing ;). The V3.1 are disappear, i think they sell only the v5.0 now.

**Comment by arendst** [comment]
@cheise would you be so kind to add this info to the wiki to make sure users know how to add the second relay.

**Comment by cheise** [comment]
@arendst 
I have add a Info in the wiki under "other devices" ;)
