### ISSUE TITLE
SI7021 temperature in rules directly after start

### ISSUE THREAD

**Issue by simonCor** [arendst/Sonoff-Tasmota#3811]
When a rule like "on si7021#Temperature<5 do Power1 1 endon" is used, the action is always executed after start although the temperature is around 20°C.

I assume that the sensor has a default value (0?) which is used at the first run before a valid value is read.

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [X] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : Sonoff TH16
- [X] _Provide the output of command_``status 0`` :
```
08:12:08 RSL: STATUS = {"Status":{"Module":4,"FriendlyName":["HeizungKeller"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"SaveData":1,"SaveState":0,"ButtonRetain":0,"PowerRetain":0}}
08:12:08 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","RestartReason":"Software/System restart","Uptime":"0T16:12:28","StartupUTC":"2018-09-15T14:59:40","Sleep":0,"BootCount":21,"SaveCount":129,"SaveAddress":"FA000"}}
08:12:08 RSL: STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-09-09T16:50:26","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
08:12:08 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["bwfue","lan"],"TelePeriod":15,"SetOption":["00000000","55818000","00000001"]}}
08:12:08 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":471,"Free":532,"Heap":15,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","000003A0","23B617CE","00000000"]}}
08:12:08 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff-5624","IPAddress":"192.168.178.130","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"5C:CF:7F:42:95:F8","Webserver":2,"WifiConfig":2}}
08:12:08 RSL: STATUS7 = {"StatusTIM":{"UTC":"Sun Sep 16 07:12:08 2018","Local":"Sun Sep 16 08:12:08 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"06:28","Sunset":"19:01"}}
08:12:08 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-09-16T08:12:08","SI7021":{"Temperature":19.8,"Humidity":51.8},"TempUnit":"C"}}
08:12:08 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-09-16T08:12:08","Uptime":"0T16:12:28","Vcc":3.245,"POWER":"OFF","Wifi":{"AP":1,"SSId":"bwfue","RSSI":88,"APMac":"CC:CE:1E:1B:ED:3D"}}}
08:12:22 RSL: STATE = {"Time":"2018-09-16T08:12:22","Uptime":"0T16:12:42","Vcc":3.246,"POWER":"OFF","Wifi":{"AP":1,"SSId":"bwfue","RSSI":92,"APMac":"CC:CE:1E:1B:ED:3D"}}
```

**To Reproduce**
- Do in environment with temp > 10 °C
- Attach sensor SI7021 to TH16
- Insert command "Rule1 on si7021#Temperature<5 do Power1 1 endon"
- Remove power and reattach power to TH16
- Result: The device will switch on on start

**Expected behavior**
The device should not switch on.

**Additional context**
I assume, that the sensor has a default value (0 maybe?) set before the first communication with the sensor is established.

**Comment by ascillato2** [comment]
Hi,

I could not reproduce it.

Please, can you share your output of your Tasmota console at startup? May be, your power on cames from another thing and not your rule.

**Comment by ascillato2** [comment]
Hi,

Please, when you have time, share the requested information. Thanks.

**Comment by simonCor** [comment]
Sorry that this took this long. The week was very busy.

Here is the requested output:
`00:00:00 Project sonoff HeizungKeller (Topic sonoff, Fallback DVES_4295F8, GroupTopic sonoffs) Version 6.2.1-2_3_0
00:00:00 WIF: Connecting to AP2 lan in mode 11N as sonoff-5624...
00:00:00 RUL: SI7021#TEMPERATURE<5 performs "Power1 1"
00:00:00 RSL: RESULT = {"POWER":"ON"}
00:00:00 RSL: POWER = ON
00:00:06 RSL: INFO1 = {"Module":"Sonoff TH","Version":"6.2.1","FallbackTopic":"DVES_4295F8","GroupTopic":"sonoffs"}
00:00:06 RSL: INFO2 = {"WebServerMode":"Admin","Hostname":"sonoff-5624","IPAddress":"192.168.28.193"}
00:00:06 RSL: INFO3 = {"RestartReason":"Software/System restart"}
00:00:06 RSL: RESULT = {"POWER":"ON"}
00:00:06 RSL: POWER = ON
00:00:07 WIF: Connected
00:00:07 DNS: Initialized
00:00:07 HTP: Web server active on sonoff-5624.local with IP address 192.168.28.193
20:16:40 RSL: STATE = {"Time":"2018-09-25T20:16:40","Uptime":"0T00:00:15","Vcc":3.245,"POWER":"ON","Wifi":{"AP":2,"SSId":"lan","RSSI":100,"APMac":"08:96:D7:0E:99:02"}}
20:16:40 RSL: SENSOR = {"Time":"2018-09-25T20:16:40","SI7021":{"Temperature":21.8,"Humidity":46.7},"TempUnit":"C"}`

**Comment by arendst** [comment]
@ascillato could you try to test if this solves the problem.

Replace line 428 in file xdrv_10_rules.ino from
```
  if (Settings.rule_enabled) {            // Any rule enabled
```
in to 
```
  if (Settings.rule_enabled && (uptime > 4)) {  // Any rule enabled
```

This will stall rule sensor processing during restart for the first 5 seconds.

**Comment by ascillato2** [comment]
Tested.

Now works perfect.

Thanks :+1:
