### ISSUE TITLE
6.2 smarthings

### ISSUE THREAD

**Issue by xHirscHx** [arendst/Sonoff-Tasmota#3820]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Hardware used : 
- [x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by xHirscHx** [comment]
Im running smarthings hubs and about 20 Sonoffs with 6.1 Hue Bridge all working great thought i would try to upgrade to 6.2 . Now the 2 i upgraded arent  taking to the smart things hub, still works with alexa but my automatons wont( motion turning on the sonoff t1)or (t3 mimicking other lights) work. st new app and old. any ideas. I killed the bathroom and kitchen (wife not happy)
Help
thx

**Comment by Frogmore42** [comment]
Start with filling out the information from the template, otherwise everyone will have to guess exactly what is wrong.

**Comment by ascillato2** [comment]
Hi,

A lot of information is missing. Please, when you have time, complete all information requested in order to properly help you, Thanks.

**Comment by xHirscHx** [comment]
Sorry first post 

Sent from Yahoo Mail on Android 
 
  On Sun, Sep 16, 2018 at 10:02 PM, Frogmore42<notifications@github.com> wrote:   
Start with filling out the information from the template, otherwise everyone will have to guess exactly what is wrong.
