### ISSUE TITLE
PowerOnState

### ISSUE THREAD

**Issue by mrmin24** [arendst/Sonoff-Tasmota#383]
On some devices like the Wemos the power on telemetry is {"Started":"External System"}. 

The powerOnState however checks for (ESP.getResetReason() == "Power on") before using the settings for the command. 

Thus the powerOnState does not work on all devices correctly. Works on SV for instance, but not Wemos

**Comment by davidelang** [comment]
I'm curious as to why there is a need to do different things depending on the reason for the restart?

**Comment by mrmin24** [comment]
Not sure, but maybe on soft reset the relays should not switch

**Comment by arendst** [comment]
Will test for "External System" too when powered on in next version.

**Comment by CommodoreWhite** [comment]
I have to say that my workaround was to change the code so that, no matter what the reason for the restart, the poweronstate setting was always honoured. This mean that in the event that a catastrophic power failure that took out my Mqtt services, the lights would always go on day or night.

**Comment by CommodoreWhite** [comment]
Btw. TASMOTA v5.0.1 works a treat on my dragons. Thanks.

**Comment by mrmin24** [comment]
Might be worth having this as a User Definable option?

**Comment by mrmin24** [comment]
I will close this issue as it is duplicate for #380. I think we opened it very close together

I made a comment that I do not think it is working 100% yet in #380

thanks
