### ISSUE TITLE
Switch 1 behavior

### ISSUE THREAD

**Issue by michau83** [arendst/Sonoff-Tasmota#3832]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**Describe the bug**
_A clear and concise description of what the bug is._
1. I flashed tasmota 2.4.2 into nodeMCUv1 with platformIO.
2. I chose 18 Generic
3. setup D1 as swith1 and D2 as relay1.
4. wen to ip off nodeMCU, toggle the switch in D1, the state show OFF, I toggle to ON at the button toggle in the web.
5. toggle switch again, I did not change to state to OFF. 
I tried with switch1 in other GPIO with the same respond issue. they have no problem with other swith2-3-4-5-6-7... they have no issue with OFF to ON. only problem when OFF by switch, then ON by web then toggle with switch1 and nothing happen.

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x ] _Searched the problem in issues and in the wiki_
- [x ] _Hardware used_ : nodemcuV1.0
- [x ] _Development/Compiler/Upload tools used_ : platformIO
- [ ] _Provide the output of command_``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**To Reproduce**
_Steps to reproduce the behavior:_
1. toggle switch1 with define on GPIO pin connect to switch and make sure it show OFF in web
2. toggle on WEB to ON
3. toggle swith1 again. we expect it should be turn to OFF but nothing happen until we toggle 1 more time.

**Expected behavior**
_A clear and concise description of what you expected to happen._
WEB show ON, toggle with switch have to be go to OFF

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._
only have problem with switch1 and (ON by web and then toggle switch)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
@michau83 

That is not the output from a STATUS 0 command. Open the Console and type 'STATUS 0'. The results is what is requested in the template.
