### ISSUE TITLE
Again: Blitzwolf SHP2 somtimes reports wrong zero values for factor and power via MQTT (#3827)

### ISSUE THREAD

**Issue by helmutGitHub** [arendst/Sonoff-Tasmota#3835]
**Describe the bug**

Issue #3827 was my first contact with the bug report function. Sorry for the misconception with that:
_With the SHP2 i control my fridge. Sometimes it reports current > 0 (2018-09-16 23:25:33) but the factor and power is reported = 0._

This is my first Blitzwolf powermeter. My experience with several Sonoff Pow, also R2 are good. I used before a Sonoff Pow, at last a Sonoff Pow R2 at the same fridge, also with version 6.2.1 and never saw such characteristics. I read the discussion  about powerdelta and i never changed the default value = 80. It seems to be a problem just with the Blitzwolf.

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [X] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : Blitzwolf SHP2
- [X] _Development/Compiler/Upload tools used_ : Arduino IDE, esptool.py
- [X] _Provide the output of command_``status 0``
STATUS 0 OUTPUT HERE
09:32:33 MQT: stat/bw_shp2_01/STATUS = {"Status":{"Module":45,"FriendlyName":["bw_shp2_01"],"Topic":"bw_shp2_01","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"SaveData":0,"SaveState":0,"ButtonRetain":0,"PowerRetain":0}}
09:32:33 MQT: stat/bw_shp2_01/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://xxxx:80/api/arduino/sonoff.bin","RestartReason":"Power on","Uptime":"1T15:52:52","StartupUTC":"2018-09-16T15:39:41","Sleep":0,"BootCount":8,"SaveCount":10,"SaveAddress":"FA000"}}
09:32:33 MQT: stat/bw_shp2_01/STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-09-10T15:27:49","Boot":4,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
09:32:33 MQT: stat/bw_shp2_01/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":3,"SysLog":0,"LogHost":"rpw2","LogPort":514,"SSId":["xxxxxxxxxxxx","xxxxxxxxxxxx"],"TelePeriod":300,"SetOption":["00208008","55958000","00000000"]}}
09:32:33 MQT: stat/bw_shp2_01/STATUS4 = {"StatusMEM":{"ProgramSize":409,"Free":592,"Heap":22,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","00008480","00000000","00100096","00000000"]}}
09:32:33 MQT: stat/bw_shp2_01/STATUS5 = {"StatusNET":{"Hostname":"bw_shp2_01-3242","IPAddress":"192.168.xx.xxx","Gateway":"192.168.xx.x","Subnetmask":"255.255.255.0","DNSServer":"192.168.xx.x","Mac":"DC:4F:22:xx:xx:xx","Webserver":2,"WifiConfig":5}}
09:32:33 MQT: stat/bw_shp2_01/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.xx.xx","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_2ACCAA","MqttUser":"admin","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
09:32:33 MQT: stat/bw_shp2_01/STATUS7 = {"StatusTIM":{"UTC":"Tue Sep 18 07:32:33 2018","Local":"Tue Sep 18 09:32:33 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":99}}
09:32:33 MQT: stat/bw_shp2_01/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
09:32:33 MQT: stat/bw_shp2_01/STATUS10 = {"StatusSNS":{"Time":"2018-09-18T09:32:33","ENERGY":{"Total":1.283,"Yesterday":0.760,"Today":0.304,"Power":129.30,"Factor":0.58,"Voltage":232.60,"Current":0.958}}}
09:32:33 MQT: stat/bw_shp2_01/STATUS11 = {"StatusSTS":{"Time":"2018-09-18T09:32:33","Uptime":"1T15:52:52","Vcc":3.519,"POWER":"OFF","Wifi":{"AP":1,"SSId":"bath45-fritz","RSSI":30,"APMac":"9C:C7:A6:9F:43:D1"}}}
09:34:56 MQT: tele/bw_shp2_01/STATE = {"Time":"2018-09-18T09:34:56","Uptime":"1T15:55:15","Vcc":3.519,"POWER":"OFF","Wifi":{"AP":1,"SSId":"xxxxxxxxxxxx","RSSI":30,"APMac":"9C:C7:A6:9F:43:D1"}} (retained)
09:34:56 MQT: tele/bw_shp2_01/SENSOR = {"Time":"2018-09-18T09:34:56","ENERGY":{"Total":1.288,"Yesterday":0.760,"Today":0.309,"Period":10.81,"Power":125.60,"Factor":0.57,"Voltage":232.30,"Current":0.948}}

**To Reproduce**
_Steps to reproduce the behavior:_

Compare to a similar configured Sonoff powermeter.

**Expected behavior**
_A clear and concise description of what you expected to happen._

Avoiding of wrong zero values.

**Screenshots**
_If applicable, add screenshots to help explain your problem.

The blue power line without breaks (Sonoff)
![sonoff-pow-r2](https://user-images.githubusercontent.com/26544542/45673970-5f805080-bb2c-11e8-9a1b-313359acb3b8.png)

and the Blitzwolf with breaks to zero.
![blitzwolf-shp2](https://user-images.githubusercontent.com/26544542/45673984-6a3ae580-bb2c-11e8-88cf-a70aaa5dde60.png)

**Additional context**
_Add any other context about the problem here._

The data from issue #3827

| 2018-09-16 23:24:52 | ENERGY_Current | 0 |
| 2018-09-16 23:24:56 | ENERGY_Current | 1.03 |
| 2018-09-16 23:25:33 | ENERGY_Current | 0.982 |
| 2018-09-16 23:25:34 | ENERGY_Current | 0.983 |
| 2018-09-16 23:29:56 | ENERGY_Current | 1.004 |
| 2018-09-16 23:34:56 | ENERGY_Current | 0.967 |
| 2018-09-16 23:39:56 | ENERGY_Current | 0.946 |
| 2018-09-16 23:44:44 | ENERGY_Current | 0.929 |
| 2018-09-16 23:44:54 | ENERGY_Current | 0 |

| 2018-09-16 23:24:52 | ENERGY_Factor | 0 |
| 2018-09-16 23:24:56 | ENERGY_Factor | 0.62 |
| 2018-09-16 23:25:33 | ENERGY_Factor | 0 |
| 2018-09-16 23:25:34 | ENERGY_Factor | 0.59 |
| 2018-09-16 23:29:56 | ENERGY_Factor | 0.61 |
| 2018-09-16 23:34:56 | ENERGY_Factor | 0.58 |
| 2018-09-16 23:39:56 | ENERGY_Factor | 0.56 |
| 2018-09-16 23:44:44 | ENERGY_Factor | 0.16 |
| 2018-09-16 23:44:54 | ENERGY_Factor | 0 |

| 2018-09-16 23:19:56 | ENERGY_Power | 0 |
| 2018-09-16 23:24:51 | ENERGY_Power | 602.1 |
| 2018-09-16 23:24:52 | ENERGY_Power | 245.7 |
| 2018-09-16 23:24:56 | ENERGY_Power | 148.7 |
| 2018-09-16 23:25:33 | ENERGY_Power | 0 |
| 2018-09-16 23:25:34 | ENERGY_Power | 136 |
| 2018-09-16 23:29:56 | ENERGY_Power | 143.9 |
| 2018-09-16 23:34:56 | ENERGY_Power | 131.3 |
| 2018-09-16 23:39:56 | ENERGY_Power | 124 |
| 2018-09-16 23:44:44 | ENERGY_Power | 34.1 |
| 2018-09-16 23:44:54 | ENERGY_Power | 0 |

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Yes, Blitzwolf device is different. Please try to set PowerDelta to 0. Standard Setup 80 is tested for/with POW
Report if you get results now as expected

**Comment by helmutGitHub** [comment]
I'll try it with PowerDelta = 0 and report the result as soon as i come to new conclusions. Thank you.

**Comment by helmutGitHub** [comment]
Hello Jason2866,
after more then 24 h in service it's all clean. Thank you for your assistance.

**Comment by lug-gh** [comment]
How to do so? When I write PowerDelta = 0 into the Console, I get the output of the value 80 ?!

```
15:41:55 CMD: PowerDelta = 0
15:41:55 MQT: stat/sonoff/RESULT = {"PowerDelta":80}
15:42:02 CMD: PowerDelta = 0
15:42:02 MQT: stat/sonoff/RESULT = {"PowerDelta":80}
```

**Comment by arendst** [comment]
Syntax.

``Powerdelta 0``

**Comment by lug-gh** [comment]
wow thanks :)

**Comment by lug-gh** [comment]
Okay, PowerDelta 0 is working contraproductive.. Theres only one value posted every 5 minutes, and sometimes it's 0 even if power draw is like 500W. So I changed PowerDelta to 10, now the values are refreshed like every 1-10 seconds
