### ISSUE TITLE
TLS fingerprint 

### ISSUE THREAD

**Issue by carbonarius** [arendst/Sonoff-Tasmota#3846]
Hi all,

just made one of my Sonoff Basics inaccessible. Short history:
- had to change broker tls cert/keys
- Miss-typed at "MqttFingerprint" "fingerprint" command
- device is inaccessible
(just if you wanted to ask, same process worked for three other devices)

Right after that, I've found out about "MqttFingerprint2" in recent firmware versions **damn**

Ok, has anyone an idea how to access the misconfigured device without unmounting it and access it via serial console?

BTW: checking what was going wrong, it seems, I've sent `cat ./new_fingerprint` as new fingerprint (literally, forgot the backtick in the command...) so `cat ./new_fingerprint` it was accepted as fingerprint.

In the meantime, I had a short look into `xdrv_01_mqtt.ino` and hopefully found the place, where the new fingerprint is stored (lines 588 ff) and the only check I can see, is if the string is >0 and <60 (length of char fingerprint[60]). 

Would it make sense to add a check, if the entered string has a valid format? 
If regular expressions would be available something like:
`^(([0-9a-zA-Z]{2}\s*)){20}$` ?

- [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [X] Development/Compiler/Upload tools used : Arduino but not related
- [X] Hardware used : Sonoff Basic
- [X] Provide the output of command ``status 0`` : not possible at the moment

**Comment by ascillato** [comment]
> Ok, has anyone an idea how to access the misconfigured device without unmounting it and access it via serial console?

If you have changed the user_config.h file you need to re flash. If you did not change that do a reset 1 command of press gpio0 for 40 secs.
