### ISSUE TITLE
RF_Bridge delay

### ISSUE THREAD

**Issue by rbravenboer** [arendst/Sonoff-Tasmota#3850]
Hi,
When RF_Bridge receives a RF command it takes roughly 1 second before the MQTT message is send.
Where does this delay come from?

Best regards,
Robin

**Comment by ascillato2** [comment]
Hi,

From the decode in the RF chip and the comms to the ESP8266.

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
