### ISSUE TITLE
WS2812 Red and Green Swapped

### ISSUE THREAD

**Issue by guidoffm** [arendst/Sonoff-Tasmota#3863]
Board is Wemos D1 mini. Tasmota is 6.2.1.
Two WS2812 type leds connected in chain to GPIO4. All commands work but colors green and red are swapped? Is this a hardware related problem? Can I fix this by using a command rather than compiling a new software?

**Comment by ascillato** [comment]
Hi

duplicated issue: https://github.com/arendst/Sonoff-Tasmota/issues/3741
