### ISSUE TITLE
Add a Configuration Option to Address the Red Green Leds Swapped Problem

### ISSUE THREAD

**Issue by guidoffm** [arendst/Sonoff-Tasmota#3865]
Please add a configuration option to address the issue described in https://github.com/arendst/Sonoff-Tasmota/issues/3741 to avoid the need of compiling the software.

**Comment by ascillato** [comment]
Hi,

Please read Theo's [comment](https://github.com/arendst/Sonoff-Tasmota/issues/3741#issuecomment-419695906).
