### ISSUE TITLE
Sonoff Basic - Blink Lights

### ISSUE THREAD

**Issue by Areyes85** [arendst/Sonoff-Tasmota#3867]
Hi
I installed Sonoff Basic to my house lights and it paired correctly with Ewelink, but the lights blink constantly, what can I do? 
Thanks

**Comment by ascillato** [comment]
Hi,

This site is not iTead. Sorry. 

If you are using Ewelink means that you are using iTead software. 

This site is Tasmota. An alternative firmware for sonoff devices that you need to flash inside a sonoff using a FTDI adapter.
