### ISSUE TITLE
Incorrect wiring information

### ISSUE THREAD

**Issue by pmknowles** [arendst/Sonoff-Tasmota#3868]
The information on this page is incorrect
https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs
**Connect jack**
Instead of connecting a switch, you could connect a 4-pin 2.5mm jack, with the pins wired:
tip pin5 (GPIO14)
r1 no connection
r2 pin1 (3.3v)
r3 pin4 (ground)
You can then plug a sensor into the jack like you would to a Sonoff TH10/TH16 and define what sensor you have connected to GPIO14
According to https://github.com/arendst/Sonoff-Tasmota/wiki/GPIO-Locations
Ring 3 is 3.3V
And
Ring 2 is Ground

**Comment by Frogmore42** [comment]
You know you can edit the page to fix it?
Just tap/click the edit button in the upper right.

**Comment by pmknowles** [comment]
Yes, but always worry if the other person's data was correct at one point and that gets lost.

**Comment by arendst** [comment]
Before making a change verify the actual situation. Copying without verification is useless.

In this case find out what is the correct connection and then update pls.

**Comment by Frogmore42** [comment]
The TH10/16 does indeed have 3v3 on the sleeve, and gnd on the ring next to it.  I smoked (literally) a SHT15 sensor because I didn't double check this and thought who would NOT put gnd on the sleeve.

**Comment by Frogmore42** [comment]
The jack is a TRRS one.  Tip, Ring, Ring, Sleeve.  2.5mm.
I prefer the 3.5mm size as it is much easier to get decent quality parts.  All of the 2.5mm ones are of very poor quality.

**Comment by pmknowles** [comment]
Have amended the page
