### ISSUE TITLE
H801 controls

### ISSUE THREAD

**Issue by cobra85ec** [arendst/Sonoff-Tasmota#387]
how do i control

**Comment by Staars** [comment]
Just set the PWM-value via MQTT (0-1023). You can mix RGB that way. I used Homebridge an Node-Red and have a fully working RGB-Strip. It's not that hard.

**Comment by cobra85ec** [comment]
can u give me a eg plz...

**Comment by cobra85ec** [comment]
OK ...never mind..... i got it

**Comment by Staars** [comment]
Well, I can only try to explain my config. 
I use: Homebridge, Homebridge-mqtt, Node-Red ... and of course some iOS-devices at home to control it. 
If you don't use iOS/HomeKit, then I can give only some rough information to you.

**Comment by cobra85ec** [comment]
One more question.... what do u use in node-red to pick the color u want.... i got it working with slide.. but qould love to use the color picker

**Comment by Staars** [comment]
I get the color from any HomeKit-App.
I goes that way:
Homekit->Homebridge->Homebridge-mqtt->my Node-Red-Flow.
Im my Node-Red-flow:
I subscribe to Homebridge-mqtt and get the HSV-value. Then I convert HSV to RGB and RGB to PWM (that is only multiplying with 4). The PWM-values get published to the H801 via MQTT.

It sounds much more complicated than it is. 
Will you use the color picker from node-red?

**Comment by cobra85ec** [comment]
here is my swetup...
RASPBERRY PI3
Mosquitto
NODE_RED
-- I DONT USE HOMEKIT
JUST NODE-RED UI DASHBOARD
i was useing node red to sen pwm with value for each color,,,...
i wasnted to used a simple color picker that would just change the color i pick...

**Comment by Staars** [comment]
Okay, I understand.
I will try it out for myself inside Node-Red (without Homekit), but I can’t do it before tomorrow.
When I get it to work, I will report here.

**Comment by davidelang** [comment]
If you are asking about the configuration of node-red to have a color picker, 
that's a question you would have to ask the node-red developers.

Tasmota has a minimal GUI, but it's really designed to be managed via mqtt, so 
you can set it via commands (see the commands page for all the details), and 
tasmota is pretty software agnostic as far as things like node-red, homekit, 
openhab, etc go. The wiki has some 'getting started' info, but really, 
configuration of the management software is going to be best dealt with by 
talking to the people who wrote it..

**Comment by cobra85ec** [comment]
ok thank u Staars

**Comment by Staars** [comment]
Okay, it's even easier with the Node-Red color picker, which gives us already R,G and B.
Do the following:
Take a color-picker and wire it to an function node. Use this code snippet:
`msg1 = {payload: msg.payload.b*4};
msg2 = {payload: msg.payload.g*4};
msg3 = {payload: msg.payload.r*4};

return [msg1,msg2,msg3];`

Use 3 outputs in the function node.

Connect every output to a corresponding mqtt-publish-node, which should publish to "cmnd/YOURH801/PWMx", where x is 3,4 or 5 or whatever PWM-pin you use.

This is a short and hacky approach, but you can extend it as you like.

**Comment by cobra85ec** [comment]
trying nothing working... can u export ur flow plz

**Comment by cobra85ec** [comment]
i got the mqtt for each color pwm3,4,5 but the funtion dont work

**Comment by cobra85ec** [comment]
ok i got it... Thank You very much

**Comment by davidelang** [comment]
It sounds as if you have solved this. If not, please re-open the issue.
