### ISSUE TITLE
Issue @Compiling 6.2.1.5

### ISSUE THREAD

**Issue by Florian1307** [arendst/Sonoff-Tasmota#3874]
Hi,
i am at the beginning with flashing tasmota. This issue i tryed to solve but i can't.
need help please :-)

What is wrong?

In file included from lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/../Serialization/../Serialization/FloatParts.hpp:12:0,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/../Serialization/JsonWriter.hpp:14,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/../Serialization/JsonSerializer.hpp:10,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/../Serialization/JsonPrintable.hpp:15,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/../JsonVariantBase.hpp:13,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/../JsonVariant.hpp:16,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/../JsonBuffer.hpp:15,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/JsonParser.hpp:10,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/JsonBufferBase.hpp:10,
from lib\ArduinoJson-5.11.2\src/ArduinoJson/DynamicJsonBuffer.hpp:10,
from lib\ArduinoJson-5.11.2\src/ArduinoJson.hpp:10,
from lib\ArduinoJson-5.11.2\src/ArduinoJson.h:10,
from C:/Users/xxxx/Downloads/Sonoff-Tasmota-415ed97dab55c02fd1a6b4536bfa40befdaa47c4/Sonoff-Tasmota-415ed97dab55c02fd1a6b4536bfa40bef
daa47c4/sonoff/sonoff.ino:53:
lib\ArduinoJson-5.11.2\src/ArduinoJson/Deserialization/../Serialization/../Serialization/../TypeTraits/FloatTraits.hpp:12:32: fatal er
ror: ../Configuration.hpp: No such file or directory
#include "../Configuration.hpp"
^
compilation terminated.
*** [.pioenvs\sonoff-DE\src\sonoff.ino.cpp.o] Error 1

cheers Flo

**Comment by ascillato** [comment]
Hi,

That is a problem with mixing versions and libraries. 

Please, delete all and download all Tasmota again. You did not specify which compiler are you using. Very handy would be if you use the template for issues.

Please, follow the steps specified in the wiki for compiling. 

If you are not modifying anything in Tasmota, it is better to use the precompiled bins and flash them with esptool.py 

All the information is on the wiki

If you need more help, please find us in Discord Chat. 

Thanks
