### ISSUE TITLE
Shelly2: No calibration possible (Version 6.2.1.5)

### ISSUE THREAD

**Issue by h-tro** [arendst/Sonoff-Tasmota#3878]
I've just flashed my Shelly2 with Tasmota 6.2.1.5 and connected a 60 W bulb with an external power meter for calibration.

I have run the VoltageSet, CurrentSet, and PowerSet commands with the values of the external power meter. But the values displayed by Tasmota do not change. No calibration possible. Can anybody confirm this? 
A bug?

**Comment by arendst** [comment]
Enable more logging with weblog 4. Execute command ``VoltageSet xxx`` and report the output pls.

**Comment by h-tro** [comment]
Output in the file
(MQTT is disabled)

[Shelly2Log1.txt](https://github.com/arendst/Sonoff-Tasmota/files/2408641/Shelly2Log1.txt)

**Comment by arendst** [comment]
Looks fine. Response changes indeed from 08FA (=229.8V) to 090A (=231.4V)

**Comment by h-tro** [comment]
Now it's working.
Is the problem serial log level?

**Comment by arendst** [comment]
If seriallog is >0 it interferes with energy monitoring. I'll disable it for shelly2 in next update.
