### ISSUE TITLE
I can not use the user_config.h settings

### ISSUE THREAD

**Issue by chenfengfeng** [arendst/Sonoff-Tasmota#388]
user_config.h
```
#define CFG_HOLDER             0x20161209
#define SAVE_DATA              1
#define SAVE_STATE             1
// -- Wifi ----------------------------------------
#define WIFI_IP_ADDRESS        "192.168.1.199"
#define WIFI_GATEWAY           "192.168.1.1"
#define WIFI_SUBNETMASK        "255.255.255.0"
#define WIFI_DNS               "114.114.114.114"
```
but my ip is 192.168.1.115
---
I can not clear the original data, long press 4 seconds to restore the settings did not work

**Comment by davidelang** [comment]
did you restart after doing the 4-second pause?

\

**Comment by chenfengfeng** [comment]
@davidelang sorry,i forgot to modify CFG_HOLDER

**Comment by davidelang** [comment]
you should not need to modify CFG_HOLDER if you explicitly tell the device to 
reload the settings (the 4 second button hold, etc)

**Comment by chenfengfeng** [comment]
@davidelang can you help me the question #389
