### ISSUE TITLE
after flashing sonoff SV I get weird text

### ISSUE THREAD

**Issue by kaliboe** [arendst/Sonoff-Tasmota#3880]
I follow this guy tutorial https://www.youtube.com/watch?v=UDnNI5wkNNY&t=1s&list=PLUkzur2i1tew9aDvV79Mo_3PM5drMh514&index=19
first time I was lucky, it was working, I was able to connect to the Tasmato software on my sonoffSV, but for some strange reason I don't see it anymore, seems the wifi is gone.
I flash it the second time, flashing was succeful but when I connect with Termite I get this green text all the time, [00][00][00][00][00][00][00], I am not able to place my ssid1, I am stuck on this
I try my second sonofSV ... same result
How can I solved this? can it be solved?

**Comment by Jason2866** [comment]
Before flashing erase the complete flash with Esptool.
Fragments left in flash causes strange errors.
Usage of Esptool and flashing device is described in wiki
Use for beginning the provided precompiled firmware from here
