### ISSUE TITLE
No WiFi connect with espressif8266@1.8.0

### ISSUE THREAD

**Issue by PjotrekSE** [arendst/Sonoff-Tasmota#3889]
**Describe the bug**
Compiled with '_platform =espressif8266@1.8.0_', the Sonoff Basic does never connect to WiFi. Compiled with '_platform = https://github.com/platformio/platform-espressif8266.git_', it finds WIFi within seconds.
Just reporting, reflashed by wire with working binary, now everything OK again. Sorry, no time to test other builds, as going on vacation.

- [X ] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : Sonoff Basic
- [X] _Development/Compiler/Upload tools used_ : Platformio, OTA, 6.2.1
- [ ] _Provide the output of command_``status 0`` :

**To Reproduce**
_Steps to reproduce the behavior:_
Compile with 'platform =espressif8266@1.8.0', _user_config_override.h_ undefining just about everything except relay. Enclosed.

**Expected behavior**
WiFi connect

[user_config_override.h.txt](https://github.com/arendst/Sonoff-Tasmota/files/2410402/user_config_override.h.txt)

**Comment by ascillato** [comment]
Hi,

I use 1.8.0 without any problem. So, there is nothing wrong in the actual Tasmota code.

Please, reinstall 1.8.0.

Thanks 

If you need further assistant, please contact us in Discord Chat
