### ISSUE TITLE
Feature request: NeoPixel Fire Effect

### ISSUE THREAD

**Issue by rocklobster42195** [arendst/Sonoff-Tasmota#39]
How about implementing a NeoPixel Fire Effect, e.g. [http://www.walltech.cc/neopixel-fire-effect/](http://www.walltech.cc/neopixel-fire-effect/)?

**Comment by arendst** [comment]
How about ``scheme 9`` ?

**Comment by hoekbrwr** [comment]
Why not replace it. It is an astonishing good simulation of fire, scheme 9 is very dull!

**Comment by arendst** [comment]
As soon as I see a delay in a piece of code I get weary...

**Comment by hoekbrwr** [comment]
So use setTimeout and put the for loop in a at random time(50-150ms) called function? That will work?

**Comment by davidelang** [comment]
@hoekbrwr it can't be anything that requires a loop for just this functionality, it needs to be something that can run in the main loop along with everything else that's happening

**Comment by don-willingham** [comment]
Yes. When the software is delaying, it's not doing anything else. A module could be added to the main loop, and set a time when it will run time. If on it's next iteration not enough time has elapsed, it will simply return.  I just started digging into the sensor code, as I submitted [PR658](https://github.com/arendst/Sonoff-Tasmota/pull/658), the library I pulled from has a delay(500), ugly!

**Comment by ascillato2** [comment]
Duplicated issue. Closing. Leaving #1952 open.
