### ISSUE TITLE
Maintain case sensitive status of values passed in a rule

### ISSUE THREAD

**Issue by TLCary** [arendst/Sonoff-Tasmota#3900]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
do event PubState=false endon
on event#PubState do publish stat/sonoff/LockStae %value% endon
the value is sometimes "FALSE" and sometimes "false"
**Describe the solution you'd like**
Maintain the origin case of the string.  MQTT is case sensitive. 

**Describe alternatives you've considered**
I made everything caps and reworked the backend.  For a Garage Door the default for Closed was C and Closing was c...   This can be worked around.  If I make them all caps and unique the seem to stay all caps.

**Additional context**
Fantastic work on the rules and they are completely functional.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

Sorry, duplicated issue (#3875)

This question has been addressed before and the answer was that we can't do that due to backward compatibility. If we make MQTT to be case sensitive, we will have a lot of new issues.
