### ISSUE TITLE
Two Reed Switches connected to ONE sonoff BASIC

### ISSUE THREAD

**Issue by fals3illusion** [arendst/Sonoff-Tasmota#3902]
Hello,

I am trying to fine tune my garage door opener/door position sensor with two reed switches. One mounted in where open position is and one mounted where closed position is. ( which allows me to view Open, Opening, Closed, Closing, and Obstruction status)

Currently I am using Two Sonoff Basics on GPIO14 on each with a reed switch and it works flawlessly.  
Is it possible to use one of the GPIO1 (Rx) or GPIO3 (Tx) points to connect another reed switch to?

Wondering if it was possible to only use one for this project.

Thanks for any help!

**Comment by ascillato** [comment]
Yes, you can but take into account the wiring restrictions

https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs
