### ISSUE TITLE
Transmitting command by mqtt.fx not succesfull

### ISSUE THREAD

**Issue by JoergZ2** [arendst/Sonoff-Tasmota#3912]
I'm trying to send ON and OFF commands directly by using mqtt.fx but without success. For example:
Publishing of the statement "cmnd/S20neu/power" shows the result stat/S20neu/POWER = OFF at the S20neu console. But there is no way to give the command for ON. Everytime I tried to transmit one more character than the simple status query is quitted by {Command:Unknown}. Even a blank brings this messages. What is wrong with the publishing statement like cmnd/S20neu/power = "ON"?

**Comment by roguestreak** [comment]
Don't know about mqtt.fx, but mqtt is typically published as 
cmnd/S20neu/POWER on
you might need to research mqtt.fx to find out how to publish a topic (cmnd/S20neu/POWER) and a payload for that topic (on)

**Comment by curzon01** [comment]
Often make mistake when beginner using mqtt.fx:

The payload must be entered in the extra window below the topic and NOT as postfix of the topic.

This is correct:
![2018-09-27 14-53-17](https://user-images.githubusercontent.com/6636844/46147325-85f96680-c265-11e8-8a21-c366a7cc2ea5.png)

**Comment by JoergZ2** [comment]
@curzon01
Thanks!
