### ISSUE TITLE
DS18B20 connectoed to Sonoff DUAL R2

### ISSUE THREAD

**Issue by jiripaskov** [arendst/Sonoff-Tasmota#3913]
Hello could I use Tasmota if I would like to connect DS18B20 to sonoff dual R2? I know it runs with TH version but not sure if it will be possible with DUAL.

 Thank you.

**Comment by ascillato** [comment]
Yes, it is possible.

**Comment by jiripaskov** [comment]
OK :) And how please? Tasmota is ready for this? Which pin to use for connecting the sensor?

**Comment by ascillato** [comment]
All the information is on the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki):

* Connecting sensors: https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs
* Available pins in Sonoff Dual: https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Dual-and-Dual-R2
* Support at Tasmota Discord Chat: https://discord.gg/Ks2Kzd4
