### ISSUE TITLE
Don't work DEBUG_THEO

### ISSUE THREAD

**Issue by labastov** [arendst/Sonoff-Tasmota#3917]
- [x ] _Searched the problem in issues and in the wiki_
- [ x] _Hardware used_ : wemos d1 mini
- [x ] _Development/Compiler/Upload tools used_ : VSC + palformio
- [ x] _Provide the output of command_``status 0`` : don't need. compiling broken

**To Reproduce**
You must definited in sonoff_post.h
#define DEBUG_THEO 

**Expected behavior**

.../sonoff/settings.ino: In function 'void RtcSettingsSave()':
../sonoff/settings.ino:181:21: error: 'RtcSettingsDump' was not declared in this scope

**Additional context**

I can not found function RtcSettingsDump() in any files of project.

**Comment by ascillato2** [comment]
Fixed
