### ISSUE TITLE
Sonoff Bridge - Timer function can not be used

### ISSUE THREAD

**Issue by vocaris9** [arendst/Sonoff-Tasmota#3919]
Hello,
 i hope i can explain the problem in english.

After i flashed my Sonoff Bridge with a Tasmota FW, you are not able to use the timer function.
In the web interface you can see, that there is von combobox shown with the the value OUTPUT.
So you are not able config. wich REFKEY should be react.

Also of you use the console to set the timer, you are even not able to set the value OUTPUT. And action can only be saved as 3.

I think the dev has forgotten to enter the right timercode in the firmware for the Sonoff Bridge.

I am looking foward for a new version.. Thank you

**Comment by ascillato** [comment]
Hi,

In a sonoff bridge, as there isn't set by default any output (relays) the only output available for timers are rules.

I suppose that you want to send a rfkey when a timer is triggered right? 

If that is the case, you can set a rule to be triggered by a timer and then the rule can send the rfkey you want.

**Comment by ascillato** [comment]
As an example:

_Send the stored RFKEY 1 at a determinated time._

* Go to Timers Configuration Menu
* Set the time you want your timer 1 to trigger
* Then go to the Tasmota console and type:

```
rule1 1
rule1 on Rules#Timer=1 do rfkey1 1 endon
```

**Comment by ascillato2** [comment]
Rules Explanation and Examples: https://github.com/arendst/Sonoff-Tasmota/wiki/Rules
Tasmota Commands: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

If you have further questions, please find us in the Tasmota Discord Chat.

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by vocaris9** [comment]
OK. Thank you. But i think this is very difficult...
But your syntax is not the solution for my task.
When i set the timer1 to e.g. {"Timer1":{"Arm":1,"Mode":0,"Time":"15:55","Window":0,"Days":"0000010","Repeat":1,"Action":3}

and i want to send the RFkey1 at this time, i may have to use the 
rule1 on Clock#Timer=1 do rfkey1 endon

One more Question:
I have da PRT sender.
1) I wanted to learn the PRT sender at the Bridge. 
2) when the PRT sends a signal, the Bridge should send the RFKEY(X) (Lamp goes on). After 3 minutes the Bridge should send the RFKEY(X) so the light goes out.

**Comment by vocaris9** [comment]
Yes. I have learned the PRT Code on RFKEY 2 for example.
Then i have defined this:
Rule3 on RfReceived#RfKey=2 do rfkey1 endon

OK. Now every time the PRT sends a signal the RFKEY 1 will be send.
The Receiver of the RFKEY1 Signal is a wireless socket with a lamp.

But the problem is. Ervey time the PRT sends his signal, the RFKEY1 will be send. So the lamp will go on and off and on and off.

I wanted that when the Bridge receives the PRT signal, the RFKEY1 Signal will be send. Then the Bridge waits for 3 Minutes and then the bridge sends the RFKEY1 Signal again.

Meeanwhile this 3 Minutes the Bridge does not react even when a PRT signal was received.
I hope i have explained it correctly.

**Comment by ascillato** [comment]
> I wanted that when the Bridge receives the PRT signal, the RFKEY1 Signal will be send. Then the Bridge waits for 3 Minutes and then the bridge sends the RFKEY1 Signal again.
> Meeanwhile this 3 Minutes the Bridge does not react even when a PRT signal was received.

So, that is totally different of what you were asking at the begining. So, all this, is not a problem, nor a bug. It is only what you want the Sonoff Bridge to do. And Clock Timers are not being used for this. So as to WAIT is not a Clock Timer, is a ruletimer. What you are asking is a complex behaviour, so expect to use a complex rule.

So. The tasks you want the Sonoff Bridge to perform are:
* When RFKEY2 is received:
  * stop listening to RFKEY2, 
  * send RFKEY1
  * wait for 3 minutes
  * send RFKEY1
  * start to listening again to RFKEY2

So, the rules for that (as example, adapt it to your needs) :

Go to the console and type:

```
rule1 1
rule1
on system#boot do var1 0 endon
on RfReceived#RfKey=2 do event mytasks=%var1% endon
on event#mytasks=0 do backlog var1 1; rfkey1; ruletimer1 180 endon
on rules#timer=1 do backlog var1 0; rfkey1 endon
```

**Comment by vocaris9** [comment]
Sorry. Yes this are two different questions. Sorry.
I have testet your rule:
rule1 on system#boot do var1 0 endon on RfReceived#RfKey=2 do event mytasks=%var1% endon on event#mytasks=0 do backlog var1 1; rfkey1; ruletimer1 180 endon on rules#timer=1 do backlog var1 0; rfkey1 endon

But it doesn't work. Even the Bridge receives the PIR Code but the bridge does not send the RFKEY1.
Here is the resukt:
17:18:13 RSL: RESULT = {"RfReceived":{"Sync":12510,"Low":420,"High":1220,"Data":"E15CEE","RfKey":2}}
17:18:13 RUL: RFRECEIVED#RFKEY=2 performs "backlog event mytasks="
17:18:13 RSL: RESULT = {"Event":"Done"}

**Comment by ascillato** [comment]
> Oh Sorry. I think i must reboot the Bridge beforè?

Yes, or just set `VAR1 0`

**Comment by vocaris9** [comment]
Is ist possible to send more RFKEYs`in this Command line? So that e.g. 3 wireless sockets will receive a signal?

**Comment by ascillato** [comment]
yes, just add it.

**Comment by vocaris9** [comment]
e.g.:
rule1 on system#boot do var1 0 endon on RfReceived#RfKey=2 do event mytasks=%var1% endon on event#mytasks=0 do backlog var1 1; rfkey1; rfkey3; rfkey4; ruletimer1 180 endon on rules#timer=1 do backlog var1 0; rfkey1;rfkey3; rfkey4 endon

??

**Comment by ascillato** [comment]
yes, just try it.

**Comment by ascillato** [comment]
If that multi send doesn't work, put a delay between rfkeys like:

```
rule1 1
rule1 on system#boot do var1 0 endon on RfReceived#RfKey=2 do event mytasks=%var1% endon on event#mytasks=0 do backlog var1 1; rfkey1; delay 10; rfkey3; delay 10; rfkey4; ruletimer1 180 endon on rules#timer=1 do backlog var1 0; rfkey1; delay 10; rfkey3; delay 10; rfkey4; endon
```
