### ISSUE TITLE
Support push buttons for Shelly 1/2

### ISSUE THREAD

**Issue by TheEggi** [arendst/Sonoff-Tasmota#3939]
It seems that currently only switches are supported for the Shelly1/2 and the user is not able to configure this. Also the default option for the Shelly should imho be a push button as you cannot use the up/down paddle information of a switch anymore (it does not reflect the real state).

**Comment by arendst** [comment]
Shelly supports pushbuttons out-of-the-box in the latest development releases

Have look at command switchmode and issue #3896

Maybe try ``switchmode 4``.

**Comment by TheEggi** [comment]
I commented in the other issue - will close this one.

**Comment by ascillato2** [comment]
Hi,

Closing. Issue continued at #3896

**Comment by TheEggi** [comment]
Could you please reopen the other issue as the solution seems to cause issues.
