### ISSUE TITLE
Sonoff Dont Receive MQTT messages

### ISSUE THREAD

**Issue by fpereiracostaa** [arendst/Sonoff-Tasmota#394]
I'm trying to switch the relay state publishing to the topic "stat/sonoff1/POWER" with payload "ON" and "OFF" and nothing happens. im using the same topic and payload i receive when i press the toggle button on the browser or when i click the sonoff switch.

Can anybody please help?

**Comment by davidelang** [comment]
stat/ messages are messages from the sonoff to the home automation software. To 
send commands to the sonoff to tell it to do something, you need to use the 
cmnd/ messages

**Comment by cobra85ec** [comment]
use it like this  cmnd/sonoff1/POWER ON

**Comment by fpereiracostaa** [comment]
Thank you a lot. I'm feeling like a donkey. I've seen that topic before. Thank you very much.
