### ISSUE TITLE
config backup/restore with no web server

### ISSUE THREAD

**Issue by or78rXxZ** [arendst/Sonoff-Tasmota#3941]
**Have you look for this feature in other issues and in the wiki?**
yes
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
perform backup and restore of config with no web server running on sonoff

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by curzon01** [comment]
Duplicate - see #2800
