### ISSUE TITLE
Momentary switch function for WeMo

### ISSUE THREAD

**Issue by orso7** [arendst/Sonoff-Tasmota#3946]
Is it possible to use a WeMo emulated switch (controlled by amazon alexa or google home) as momentary swtich? (Running on a NodeMcu)

**Comment by ascillato2** [comment]
yes, using pulsetime, or rules

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
