### ISSUE TITLE
No eagle.flash.1m0.ld file in this package

### ISSUE THREAD

**Issue by mrohner** [arendst/Sonoff-Tasmota#396]
Should I rename the provided esp8266.flash.1m0.ld file?

Regarding your IDE prereq description: replace board.txt with what exactly??

Installing updated linker file for version 5.0.0 and up

To gain as much code space as possible from the available 1M flash memory I provide a linker file without SPIFFS area. Follow the steps below to install and use it in your IDE:

Copy file eagle.flash.1m0.ld to directory portable\packages\esp8266\hardware\esp8266\2.3.0\tools\sdk\ld
Replace file boards.txt in directory portable\packages\esp8266\hardware\esp8266\2.3.0
Restart you IDE
This will provide an additional option Tools - Flash Size: "1M (no SPIFFS)".

**Comment by arendst** [comment]
Look in the https://github.com/arendst/Sonoff-Tasmota/tree/master/arduino/version%202.3.0 folder.
