### ISSUE TITLE
Support Digitalloggers PLC

### ISSUE THREAD

**Issue by nitinuae** [arendst/Sonoff-Tasmota#3976]
Hello
Long time back, I bought a digitalloggers PLC (https://dlidirect.com/products/diy-programmable-controller), thinking that its a nice PLC which can be programmed. This came out to useless as digitalloggers dont provide any info other than schematics and their github page has botched up programming.

Basically, its an ESP8266, which is hardwired to Arduino mega, with Relay shields (6 relay 8Analogue in, 8 Digital out).

The relay shield can be controlled (by ESP) by sending out preset serial command(and status be read by serial)

The command can be seen in https://github.com/digitalloggers/PLDuino/blob/master/ESP8266/server.lua

Can this be done in Tasmota?

**Comment by ascillato** [comment]
Yes,

Select module as Generic and set the GPIO as in your device.
