### ISSUE TITLE
Sonoff Touch LED

### ISSUE THREAD

**Issue by LexPrima** [arendst/Sonoff-Tasmota#398]
The Itead website adverts this with "Its LED backlight lets you easily find and turn on the switch at night." However tasmota seems do interchange these states. The LEDs are off when the switch is off.

I tried playing around with ledpower and ledstate but these only control the wifi indicator. And also either completely on or off when switch is off.

**Comment by lxz81** [comment]
I have seen a possible solution on [another website](https://www.bountysource.com/issues/43123915-sonoff-touch-how-to-change-the-led-behaviour) by changing GPIO_LED1_INV to GPIO_LED1 in the sonoff/sonoff_template.h file. Haven't tried this though..

**Comment by khcnz** [comment]
That website is just a front for github anyway - thats this ticket https://github.com/arendst/Sonoff-Tasmota/issues/214

**Comment by arendst** [comment]
The touch has two leds. One connected to the same control line as the relay (in the middle) so that when the relay is on the led is also on. Unable to control it seperately from the relay.

The second led is the wifi indicator which my software controls with both commands ``ledstate`` and ``ledpower``.

Those are all leds available on my touch so other than the wifi led I see no possibility for a "LED backlight".

**Comment by LexPrima** [comment]
Thanks for clearing things up

**Comment by TRIROG** [comment]
Quick question:
@LexPrima make sure to set the  `Module type` to `Sonoff Touch` and not `Sonoff Basic` in `Module configuration` menu. Then the WiFi led is on when the switch is off (to help you find the switch in the dark :)) and vice versa

However i would prefer for the WiFi led to somehow reflect the status of the switch i.e.  to turn on once the swtich has established WiFi or MQTT connection and reported Online to LWT topic, and turn off when offline? Maybe blink while attempting to connect?

**Comment by madradrakie** [comment]
@glsf91 can you make a picture or explain what you mean with "connect to GND?". Do you mean hardwire the track to GND? Can you show us how this looks like?

**Comment by glsf91** [comment]
@madradrakie 
Yes, I mean hardwire the track to GND.

**Comment by madradrakie** [comment]
@glsf91 , can you maybe share a picture how you hardwired the lower part to GND. I would like to know were and how you attached to wire.

**Comment by glsf91** [comment]
> @glsf91 , can you maybe share a picture how you hardwired the lower part to GND. I would like to know were and how you attached to wire.

You can see it at the red arrow, the big soldering you see.

**Comment by madradrakie** [comment]
@gls91, it worked! Thanks. Do you also know how to tweak the sonoff touch T2? In that version the buttons are at the right and left.

**Comment by glsf91** [comment]
@madradrakie, I don't have a T2 so I don't know.

**Comment by madradrakie** [comment]
@glsf91 thanks for your help anyway. 4 of my Touch T1 are now modified and glowing in the dark! :-)

I think the T2 works at the same way as the T3, the only problem is that the connection for the left LED is underneath the touch button which i can not reach.
