### ISSUE TITLE
[Sonoff-Tasmota 6.2.1] - Sonoff 4ch 

### ISSUE THREAD

**Issue by danielraq** [arendst/Sonoff-Tasmota#3981]
Hi,
I'm trying to add additional sensor to my sonoff 4ch on grio3 (regular pin is already occupied) , i've disabled serial loggin by `SerialLog off`, unfortunately it didn't help. Could you help me and tell me if it's possible, if yes what i'm doing wrong.

**Comment by Jason2866** [comment]
A little more Info would be helpful :-)
What sensor? Is it correct wired? Is in firmware sensor enabled on GPIO3?

**Comment by andrethomas** [comment]
I would aim for D1 (GPIO4) - It is also broken out nicely on the the board

![image](https://user-images.githubusercontent.com/470015/46535884-009d3400-c8ad-11e8-9fa4-a4fb796a8497.png)

**Comment by Jason2866** [comment]
@andrethomas 
if it is a 4CHpro yes. On a 4CH GPIO 2 is easy reachable

**Comment by andrethomas** [comment]
@Jason2866 Aaah, even easier.. so why is there this issue then?

**Comment by danielraq** [comment]
@Jason2866 

> What sensor? 
Ir reciver - TSOP4838 

> Is it correct wired? 
Yes, it works with GPIO2.

> Is in firmware sensor enabled?  Configured on GPIO3?
I'm not sure if I understood the question so correct me if I'm wrong. It is enabled in tasmota `51 IRrecv`

@andrethomas
I'm using regular 4CH sonoff.

To be precise GPIO2 is already in use by DHT11 sensor, This is why i decided to use GPIO3

**Comment by andrethomas** [comment]
@danielraq 

I do not see that GPIO3 is broken out on the module so not sure where you connected it to.

![image](https://user-images.githubusercontent.com/470015/46537533-d13cf600-c8b1-11e8-9d28-4d005682d079.png)

**Comment by Jason2866** [comment]
Finally you can solder on Module GPIO16
https://www.itead.cc/wiki/images/thumb/e/e6/PSF-A85_pinmap.jpg/500px-PSF-A85_pinmap.jpg

**Comment by danielraq** [comment]
@Jason2866
it worked. i switched cables and it's working :) thanks
