### ISSUE TITLE
Can you disable prefix without reflash?

### ISSUE THREAD

**Issue by poldim** [arendst/Sonoff-Tasmota#3984]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [X] Development/Compiler/Upload tools used : Arduino IDE
- [x] Hardware used : MagicHome

- Initially, my device running with the command_topic as `cmnd/homeassistant/light/living-room-rgb/POWER` with MQTT Full Topic set to `%prefix%/%topic%/`.
- Currently, I have my device running with the command_topic as `homeassistant/light/living-room-rgb/cmnd/POWER` after setting MQTT Full Topic to `homeassistant/light/living-room-rgb`.  _It's automatically appending Prefix1 as a suffix to the Full Topic even though it's not configured as such._
- I've tried to disable Prefix1, but changing it to 0 just makes the prefix 0 so that the new topic is `homeassistant/light/living-room-rgb/0/POWER`.

Is there a way to remove the use of prefixes entirely without recompiling and flashing a new firmware?  Deisred state is `homeassistant/light/living-room-rgb/POWER`.

If anyone has any links to anything that describes the benefits of keep the standard `%prefix%/%topic%/` setup, I'd love to read more about it.  And does keeping the prefix up front break HomeAssistant discovery?

**Comment by ascillato** [comment]
Hi,

> Is there a way to remove the use of prefixes entirely without recompiling and flashing a new firmware? 

there is no way of changing that without modifying the code and reflashing

> And does keeping the prefix up front break HomeAssistant discovery?

No, It works fine
