### ISSUE TITLE
Wifi Setup doesn't work 

### ISSUE THREAD

**Issue by ConmantheOnlyone** [arendst/Sonoff-Tasmota#3998]
**Describe the bug**
Not able to configure the sonoff S20 Wifi with any method, nor toggling the on or off the device having flashed with Sonoff.classic v6.2.1

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x ] _Searched the problem in issues and in the wiki_
- [x ] _Hardware used_ : Sonoff S20 EU v1.3 2017 02 16
- [x ] _Development/Compiler/Upload tools used_ : ESPTool
- [x ] _Provide the output of command_``status 0`` : not sure if I understand what you mean, I copied the out of the flashing...
```
STATUS 0 OUTPUT HERE
esptool-2.5.0> esptool.py --port COM7 write_flash -fs 1MB -fm dout 0x0 sonoff-classic.bin
esptool.py v2.5.0
Serial port COM7
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
MAC: dc:4f:22:2d:82:dc
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Compressed 486816 bytes to 335865...
Wrote 486816 bytes (335865 compressed) at 0x00000000 in 33.0 seconds (effective 117.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**To Reproduce**
After first flashing device with latest release 6.2.1; I was not able to configure the Wifi via WPS or SmartConfig or Wifi Manager method by pushing the buttons. The device was flashing with green LED 3 times in a row repeatedly having the last blink a little longer starting over again. The device didn't toggle the relay when pushing the button one time.

**Expected behavior**
Being able to configure the Wifi


**Screenshots**
_If applicable, add screenshots to help explain your problem._


**Additional context**
I installed previous v6.1.2 being able to setup using WPS without a problem. Upgrading the FW afterwards after initial Wifi configuration did work though.

**Comment by Frogmore42** [comment]
Since the WiFi is not working for you, you will need to learn how to use the serial port monitor.  There are many ways to listen and to talk to the esp8266 via its serial port.  There are terminal emulators like putty and TeraTerm that will allow you to see what is happening to the esp8266.

Status 0 is a command you can send to the device to find out lots of information about the device, the configuration and the software.

**Comment by ConmantheOnlyone** [comment]
Well I got around it by installing 6.1.1, configuring Wi-Fi and installing
6.2.1 OTA. Of cause Wi-Fi configuration is still failing but I am ok.  What
I would be interested in is how are you getting log information over the
serial port, where can I find information on this?

Frogmore42 <notifications@github.com> schrieb am So., 7. Okt. 2018, 08:09:

**Comment by Jason2866** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#troubleshooting-tools
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#wifi

**Comment by ascillato2** [comment]
If you need further assistant, please find us in the Tasmota Discord Chat at https://discord.gg/Ks2Kzd4
