### ISSUE TITLE
SerialMonitor from Sonoff pow is: NULNUL

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#3999]
I did reflash with atom and its was all ok flashing.
after that the device isn't connecting to my Wi-Fi and when I try to get information with Atom's Serial Monitor I got: 'NULNULNULNULNULNULNUL'
Photo: 
![image](https://user-images.githubusercontent.com/4135420/46576616-f4ad9100-c9d6-11e8-896e-ea2d59f1e164.png)
What Can I do? 
Is there "hard flash" or something similar?
Thanks !

**Comment by Jason2866** [comment]
Disconnect it. Reasemble, connect it to mains. It will probably work
POW uses serial for measurement. You cant use serial...
See https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Pow-and-Pow-R2

**Comment by ascillato** [comment]
Serial log is used by the power measurement chip. Can not be used for monitoring.

Please, close this issue. Thanks

**Comment by shayshtern** [comment]
At the end I flash it with this tool: https://github.com/marcelstoer/nodemcu-pyflasher/releases
Than open a serial monitor from Atom and set the WiFi and password with sending commands! 
Thank anyway!
