### ISSUE TITLE
How to control APA104 (WS2812)?

### ISSUE THREAD

**Issue by kruebsam** [arendst/Sonoff-Tasmota#400]
Sorry for asking in here, but I could not find any details at all on how to make use of the WS2812-part of your TASMOTA 5.01 (preferably using MQTT). Could you give me some hint, please

**Comment by arendst** [comment]
See wiki > Sensor Configuration

**Comment by kruebsam** [comment]
See https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#ws2812-led-string for the details
