### ISSUE TITLE
Switchtopic2 2- Cant seem to adjust this setting

### ISSUE THREAD

**Issue by chris8837** [arendst/Sonoff-Tasmota#4004]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used : ATOM
- [ ] Hardware used : 
-Qunqi 3.3V 5.5V FT232RL FTDI USB to TTL Serial Adapter Module for Arduino Mini Port
-Sonoff SV
- [ ] Provide the output of command ``status 0`` :
```
13:21:25 CMD: status 0
13:21:25 MQT: stat/sonoffsv01/STATUS = {"Status":{"Module":3,"FriendlyName":["Sonoff","Sonoff2"],"Topic":"sonoffsv01","ButtonTopic":"sonoffsv01","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":1}}
13:21:25 MQT: stat/sonoffsv01/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:04:41","StartupUTC":"2018-10-07T20:16:44","Sleep":0,"BootCount":6,"SaveCount":15,"SaveAddress":"F5000"}}
13:21:25 MQT: stat/sonoffsv01/STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-10-05T15:31:42","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
13:21:25 MQT: stat/sonoffsv01/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["sable88",""],"TelePeriod":300,"SetOption":["000080A9","55818000","00000000"]}}
13:21:25 MQT: stat/sonoffsv01/STATUS4 = {"StatusMEM":{"ProgramSize":472,"Free":528,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","24000000","23B617CE","00000000"]}}
13:21:25 MQT: stat/sonoffsv01/STATUS5 = {"StatusNET":{"Hostname":"sonoffsv01-0217","IPAddress":"192.168.1.45","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"DC:4F:22:4B:80:D9","Webserver":2,"WifiConfig":5}}
13:21:25 MQT: stat/sonoffsv01/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.20","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4B80D9","MqttUser":"chris8837","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
13:21:25 MQT: stat/sonoffsv01/STATUS7 = {"StatusTIM":{"UTC":"Sun Oct 07 20:21:25 2018","Local":"Sun Oct 07 13:21:25 2018","StartDST":"Sun Mar 11 02:00:00 2018","EndDST":"Sun Nov 04 02:00:00 2018","Timezone":99,"Sunrise":"06:40","Sunset":"18:16"}}
13:21:25 MQT: stat/sonoffsv01/STATUS10 = {"StatusSNS":{"Time":"2018-10-07T13:21:25","Switch2":"ON"}}
13:21:25 MQT: stat/sonoffsv01/STATUS11 = {"StatusSTS":{"Time":"2018-10-07T13:21:25","Uptime":"0T00:04:41","Vcc":3.160,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"sable88","RSSI":100,"APMac":"EC:08:6B:EE:D6:89"}}}
```

**(Please, remember to close the issue when the problem has been addressed)**

I enter switchtopic2 2 in the console and it won't change it.  I'm on 6.2.1

I'm using this for a garage sensor with reed switch to trigger the garage.  Sonoff SV unit.

Before I was having issues and I learned on the Dr. ZZs tutorial that I needed to change the Module to GPIO4 to Relay 2.  So I plugged it back in to test.

Now the reed switch doesn't trigger the garage anymore, but I cant seem to adjust this setting to 2 for the Home Assistant software to read the status.

Everytime that I do it it just stays on 0

Here

13:24:29 CMD: switchtopic2 2
13:24:29 MQT: stat/sonoffsv01/RESULT = {"SwitchTopic":"0"}

**Comment by ascillato** [comment]
Hi,

switchtopic is not the same as switchmode

please read the commands at https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by ascillato2** [comment]
### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
