### ISSUE TITLE
Where to set the HOSTNAME?

### ISSUE THREAD

**Issue by aaamitsingh** [arendst/Sonoff-Tasmota#4005]
Remembering mac_id of very tough for every module so I want to set different Hostname for the different sonoff module so that I can easily identify the which module is up and down from the IP scan tools. But don't know where to change. Please help..

**Comment by andrethomas** [comment]
From web ui, Configuration|Configure Wifi

![image](https://user-images.githubusercontent.com/470015/46594703-01b0aa00-cad5-11e8-83da-4c8921506e75.png)

**Comment by ramanraja** [comment]
I tried to remove the %4d at the end of the host name since I don't want it. Also tried to give the hostname %s command from the console. But every time the 4 digit appendage was reappearing. How to get rid of that ?

**Comment by sfromis** [comment]
Those usages of `%` are for the default naming scheme, not for you to adapt on. Preferable to set your own full host name without getting confusion around how those `%` tags are not straightforward.

(In general, questions should be asked in the "Discussions" tab, not in "Issues")

**Comment by ramanraja** [comment]
Thank you @sfromis.
For the sake of closure and to help late comers: I discovered that the same issue has been discussed from 2017 to 2022 in different threads. The most comprehensive answer is found in https://github.com/arendst/Tasmota/issues/142
