### ISSUE TITLE
PowerOnState cannot be disabled

### ISSUE THREAD

**Issue by skop1986** [arendst/Sonoff-Tasmota#4011]
It is not possible to disable PowerOnState4, nothing helps. Tried cmnd/sonoff/PowerOnState 0, cmnd/sonoff/Reset 1, cmnd/sonoff / Reset 2. Re-flash and restore the configuration also heard different reviews.esptool.py --port /dev/cu.wchusbserial143320 erase_flash -it doesn't help.Please help. Need any way to disable this option

**Comment by Frogmore42** [comment]
Your device is not connected to you MQTT server.

**Comment by Frogmore42** [comment]
You can send commands using the web console.

**Comment by skop1986** [comment]
16:33:31 MQT: stat/sonoff/RESULT = {"PowerOnState":4}
16:33:33 CMD: cmnd/sonoff/PowerOnState 0
16:33:33 MQT: stat/sonoff/RESULT = {"PowerOnState":0}
16:33:36 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
16:33:36 MQT: stat/sonoff/POWER = ON
16:33:36 MQT: stat/sonoff/RESULT = {"PowerOnState":4}
16:33:41 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
16:33:41 MQT: stat/sonoff/POWER = ON
16:33:41 MQT: stat/sonoff/RESULT = {"PowerOnState":4}
16:33:46 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
16:33:46 MQT: stat/sonoff/POWER = ON
16:33:46 MQT: stat/sonoff/RESULT = {"PowerO

**Comment by skop1986** [comment]
http://10.0.1.11/cm?cmnd=PowerOnState%200

**Comment by andrethomas** [comment]
Works fine for me

```
16:47:22 CMD: poweronstate
16:47:23 MQT: stat/lounge1/RESULT = {"PowerOnState":3}
16:47:32 CMD: poweronstate 0
16:47:32 MQT: stat/lounge1/RESULT = {"PowerOnState":0}
16:47:35 CMD: poweronstate
16:47:35 MQT: stat/lounge1/RESULT = {"PowerOnState":0}
16:47:45 CMD: poweronstate 3
16:47:45 MQT: stat/lounge1/RESULT = {"PowerOnState":3}
```

**Comment by andrethomas** [comment]
You could also force the state of power at boot time using a rule if nothing else works.

`rule on System#Boot do power off endon`

**Comment by ascillato** [comment]
Hi, I could not reproduce your issue. Seems to be a faulty firmware. Please, do as Jason told you in the Tasmota Chat and erase all flash and flash the firmware again. Please, use the precompiled bins from http://thehackbox.org/tasmota/

**Comment by andrethomas** [comment]
Repost of https://github.com/arendst/Sonoff-Tasmota/issues/4008 and repost after discussed on Discord Chat.
