### ISSUE TITLE
"&" replacement %26 doesnt work

### ISSUE THREAD

**Issue by boklubre** [arendst/Sonoff-Tasmota#4014]
Hi,

I used WebCommands to control the Sonoff Bridge like this:

http://192.168.1.60/cm?&user=xxxxx&password=xxxxxx&cmnd=RfCode%20331796

My Sender hast problems with the "&" in the string. I have replace it with "%26" but it dosn´t work. The Replacement of the Space works fine with "%20".

Is that a problem with Tasmota Firmware?

Cheers

Boris

**Comment by ascillato2** [comment]
Hi,

Sorry. The %26 as a replacement of & is not supported. Those codes for webserver are managed by the esp8266 libraries outside Tasmota.

May be, the best should be to use MQTT as it is the main feature of Tasmota.
