### ISSUE TITLE
Feature request: display Running Hours for Pow

### ISSUE THREAD

**Issue by i3laze** [arendst/Sonoff-Tasmota#4019]
**Have you look for this feature in other issues and in the wiki?**
Yeap

**Is your feature request related to a problem? Please describe.**
Energy Total for POW doesn't give a clue about total running time.

**Describe the solution you'd like**
I've got a heater with variable power consumption, triggered by some scripts or manually.
I'd love to see Runtime Today, Runtime Yesterday and Runtime Total alongside with Energy outputs on Sonoff's main web-page. Sending such telemetry via MQTT is welcome too.
Solution might utilize current timer and ruleset feature but better be hardcoded.

**Describe alternatives you've considered**
Currently, I'm tinkering with aggregating such counters on Domoticz.. but out of the box solution is preferable.

**Comment by ascillato** [comment]
Hi, duplicated. See #3971

**Comment by i3laze** [comment]
Sorry, thanks.  The other issue description was kinda messy. :(

**Comment by ascillato** [comment]
hehehe, no problem. Please, just add there your ideas.

**Comment by i3laze** [comment]
#3971 solved only it’s own demand for a total start time..

Personally, I'd love to see:

Runtime Today,
Runtime Yesterday
Runtime Total

Unlike a fridge, i've got a heater triggered by Sonoff directly.
For a 24x7 fridge a Runtime value might be calculated for power consumption bigger than some threshold.
