### ISSUE TITLE
Wemos D1 mini Powerlevel?

### ISSUE THREAD

**Issue by timtimsson** [arendst/Sonoff-Tasmota#402]
Hi,
all my Wemos D1 mini have got  a Powerlevel between Vcc 2,72-2,78. 
Is this correct or a little bit to low?
Thanks

**Comment by davidelang** [comment]
that seems quite low to me.

**Comment by arendst** [comment]
Mine are low too. It looks to be normal for Wemos D1 mini.

**Comment by timtimsson** [comment]
... only for my understanding, 
if i have a level on tele from 2,7V on the sonoffLEDPanel, then breakdown the sonoff device?!)
If i measurement between the wemos pin:
GND-3.3=> 3.02V
GND-5=> 4.47V
where can i find the 2.7V?
Thanks

**Comment by timtimsson** [comment]
ups, my ElectroDragon Module shows: 0.224V ?

**Comment by arendst** [comment]
Dive into the wonderfull world of esp8266 ADC and enjoy it's dynamic functionality...

On the Sonoff Led it provides a great means of comparing within it's family with functional (> 2.7V) and disfunctional. On the wemos I've never see any problems with ADC voltages of 2.7V

**Comment by arendst** [comment]
The ADC input on Sonoff is not connected.

The ADC input of the Wemos is connected with a 100k resistor to Gnd which will lower the ADC value considerably resulting in your findings.

The Electrodragon is worse by connecting the ADC with a 1k resistor to Gnd resulting in even lower values.
