### ISSUE TITLE
Adding support for RGB/WW/CW Controller with music and timer mode

### ISSUE THREAD

**Issue by Damontir** [arendst/Sonoff-Tasmota#4027]
Hey!

Just bought a 
"DC12V 24V Wifi LED Controller RGB/RGBW/RGBWW 16 Million Colors Music and Timer Mode Wifi " 
because i have some meters RGBWW leds laying around here .

I found out that its driven by a ESP8285

Maybe worth a look to get this little baby running?

https://www.aliexpress.com/item/DC12V-24V-Wifi-LED-Controller-RGB-RGBW-RGBWW-16-Million-Colors-Music-and-Timer-Mode-Wifi/32674135296.html

![utb8eit6in_ixkjksaluq6ybzvxa2](https://user-images.githubusercontent.com/2669454/46752825-785ccb80-ccbe-11e8-927e-d7f6597ab2d3.jpg)
![utb82pb1idnjxkjksaiyq6ahwxxae](https://user-images.githubusercontent.com/2669454/46752830-7abf2580-ccbe-11e8-9d3b-46b5edf8f570.jpg)

**Comment by ascillato** [comment]
Hi

You will need to find which gpios are being used and then set the module type as generic.

**Comment by ascillato2** [comment]
If you can find the GPIOs that are being used, please, share it and we can add that information to the wiki.

Thanks.
