### ISSUE TITLE
Shelly1 on/off every 4-10 seconds

### ISSUE THREAD

**Issue by JDunnio** [arendst/Sonoff-Tasmota#4028]
Hi,

I'm trying to get my two Shelly1's working.

I've succesfully flashed them with Arduino IDE and the instruction video's below:
https://www.youtube.com/watch?v=J20hxfUTP9I
https://www.youtube.com/watch?v=sIVjeYZeLNU

I've two problems:
problem 1: the light bulb is turning on and off every 4-10 seconds. I've replaced the ikea LED bulb with a regular E27 light saver bulb but with no luck.
I hear the relay clicking so i looks like it's getting instructions from somewhere? I'm pretty sure the wiring is correct. With the original Shelly Cloud firmware this wasn't an issue.
I don't have MQTT enabled. This is my first tasmota device and first want the physical button and the Tasmoto webpage to work before configuring this.

Problem 2:
How to use the momentary switch with the shelly1 and the use of 2x press/3x press/HOLD? When switching on it turns off immediatly but i see no options on the device to change this? Work in progess?

Help is greatly appriciated!

15:59:27 RSL: STATE = {"Time":"2018-10-10T15:59:27","Uptime":"0T01:20:13","Vcc":3.568,"POWER":"ON","Wifi":{"AP":1,"SSId":"SECRET","RSSI":62,"APMac":"F0:9F:C2:31:C5:DB"}}
15:59:27 RSL: SENSOR = {"Time":"2018-10-10T15:59:27","Switch1":"OFF"}
16:00:13 RSL: RESULT = {"POWER":"OFF"}
16:00:13 RSL: POWER = OFF
16:01:08 RSL: RESULT = {"POWER":"ON"}
16:01:08 RSL: POWER = ON
16:01:19 RSL: RESULT = {"POWER":"OFF"}
16:01:19 RSL: POWER = OFF
16:01:53 RSL: RESULT = {"POWER":"ON"}
16:01:53 RSL: POWER = ON
16:02:00 RSL: UPTIME = {"Time":"2018-10-10T16:02:00","Uptime":"0T01:22:46"}
16:02:37 RSL: RESULT = {"POWER":"OFF"}
16:02:37 RSL: POWER = OFF

15:25:29 RSL: STATUS = {"Status":{"Module":46,"FriendlyName":["Shelly1-Test2"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
15:25:29 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Power on","Uptime":"0T00:46:15","StartupUTC":"2018-10-10T13:39:14","Sleep":0,"BootCount":11,"SaveCount":142,"SaveAddress":"F6000"}}
15:25:29 RSL: STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-10-10T15:11:35","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
15:25:29 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["KIEVID",""],"TelePeriod":300,"SetOption":["00008001","55818000","00000000"]}}
15:25:29 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":506,"Free":496,"Heap":20,"ProgramFlashSize":1024,"FlashSize":2048,"FlashMode":3,"Features":["00000809","0FDAE794","00000000","23B617CE","00000000"]}}
15:25:29 RSL: STATUS5 = {"StatusNET":{"Hostname":"shelly-test2","IPAddress":"10.0.0.41","Gateway":"10.0.0.1","Subnetmask":"255.255.255.0","DNSServer":"1.1.1.1","Mac":"BC:DD:C2:8B:18:92","Webserver":2,"WifiConfig":5}}
15:25:29 RSL: STATUS7 = {"StatusTIM":{"UTC":"Wed Oct 10 14:25:29 2018","Local":"Wed Oct 10 15:25:29 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"07:03","Sunset":"18:11"}}
15:25:29 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-10-10T15:25:29","Switch1":"OFF"}}
15:25:29 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-10-10T15:25:29","Uptime":"0T00:46:15","Vcc":3.559,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SECRET","RSSI":58,"APMac":"F0:9F:C2:31:C5:DB"}}}

**Comment by ascillato** [comment]
Hi

Duplicated issue 

Please read #4023

Thanks
