### ISSUE TITLE
Sonoff Dual Problem

### ISSUE THREAD

**Issue by jiafengwang** [arendst/Sonoff-Tasmota#403]
Hello
I have a Sonoff Basic and a Sonoff Dual.When I flashing the Tasmota to Sonoff Dual, aduino says it flashed successfully and then connect to (AC) power, it just blinks the blue led about some 30 times and then a long blue led, then turns off the led, and after a couple of seconds repeates.
But the same firmware is working well with my Sonoff Basic.
Can anybody know about this?
Thanks a lot.

**Comment by gajotnt** [comment]
Make sure you have your wifi settings right, had that problem once and i was making a mistake in the SSID of the wifi.

**Comment by jiafengwang** [comment]
Yes, I am sue. The ssid and password is correct because the Sonoff Basic is working normally.
Only Sonoff Dual can not work.
Even can not access AP Mode (WIFI Manager) to set wifi configration by 4 short presses.

**Comment by gajotnt** [comment]
:-/ i also had some troubles configuring a Dual, try another usb cable and turn off serial loggin.
After some tryes and using another usb cable i got it to finally work

**Comment by jiafengwang** [comment]
![seriseinfo](https://cloud.githubusercontent.com/assets/2180882/25621680/a2c13f4c-2f84-11e7-8be5-551452abffb4.png)

**Comment by gajotnt** [comment]
It seams it cannot connect to the Wifi, do you have wifi signal were you're installing it?
And again, double check in the user_config if the AP settings are right.

**Comment by jiafengwang** [comment]
I am sure the SSID and Password is correct. The router  also works well. 
I even tried to compare these two behavior : one is modifying wifi setting by typing my own ssid and password, the other is keeping default setting.
Both can flash successfully, and show the same logs above.  The ssid both are same named"indebuurt1"  even if I typed my own SSID.

**Comment by davidelang** [comment]
if you power the device from your serial cable does it come up and connect to 
the wifi?

you would be far from the first to have a module that has trouble connecting to 
wifi while on mains power.

**Comment by jiafengwang** [comment]
Both serial and AC power are showing the same erro.

**Comment by davidelang** [comment]
If you can't connect to your wifi, even when powered by the serial port, then 
unless there is a signal strength issue, it's either a config error or there is 
something odd about your wifi.

if you do the 'scan for networks' option, does your network show up and what 
signal strength did it show?

**Comment by jiafengwang** [comment]
My Sonoff Basic is working well at the same time with the same router. Only Sonoff Dual can not work. Even can not access AP Mode (WIFI Manager) to set wifi configration by 4 short presses.

**Comment by jiafengwang** [comment]
![_20170503080959](https://cloud.githubusercontent.com/assets/2180882/25644342/ee67be00-2fd7-11e7-85b5-f8958feeaddd.jpg)

**Comment by jiafengwang** [comment]
I found the version of this Sonoff Dual is "ver 2.0"
Is there something different from the old?

**Comment by davidelang** [comment]
the wifi is a feature of the esp8266 chip, other than antenna design, it 
shouldn't be affected by anything else.

**Comment by jiafengwang** [comment]
I have tried flash another new Sonoff Dual just now, OMG,  exactly the same problem.
![c q 23 gc tv njtz h14](https://cloud.githubusercontent.com/assets/2180882/25645111/d0b9b402-2fdd-11e7-8838-4f8c3d1926e8.png)

**Comment by davidelang** [comment]
set logging level to 4 (more debugging) and see if there is any more info from the logging when it attempts to connect.

what does the 'scan for networks' show?

**Comment by jiafengwang** [comment]
I solved this problem finally by using "esptool.py --port COM4 erase_flash" command to erase the flash.
Thank you all.
WOW~WOW~WOW~

**Comment by davidelang** [comment]
If that solved your problem, then you didn't have the config set the way you 
thought you did. See the troubleshooting page about why user_config.h changes 
may not be active.
