### ISSUE TITLE
Time string does not include a timezone for SonoffPow

### ISSUE THREAD

**Issue by borpin** [arendst/Sonoff-Tasmota#4030]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**Describe the bug**
The Time/Date string output from Tasmota on the SonoffPow does not include the timezone offset.  It seems there is an option in some cases to add it.  This should be available for all devices with a time capability.

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [X] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : SonoffPow R1
- [X] _Development/Compiler/Upload tools used_ : Nil flashed Bin
- [ ] _Provide the output of command_``status 0`` :
```
19:52:19 MQT: stat/SonoffPow1/STATUS = {"Status":{"Module":6,"FriendlyName":"SonoffPow1","Topic":"SonoffPow1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
19:52:19 MQT: stat/SonoffPow1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","Uptime":0,"Sleep":0,"BootCount":31076,"SaveCount":88774,"SaveAddress":"F6000"}}
19:52:19 MQT: stat/SonoffPow1/STATUS2 = {"StatusFWR":{"Version":"5.10.0g","BuildDateTime":"2017-12-30T13:52:18","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
19:52:19 MQT: stat/SonoffPow1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"home123","SSId2":"","TelePeriod":30,"SetOption":"00000009"}}
19:52:19 MQT: stat/SonoffPow1/STATUS4 = {"StatusMEM":{"ProgramSize":484,"Free":516,"Heap":23,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3}}
19:52:19 MQT: stat/SonoffPow1/STATUS5 = {"StatusNET":{"Hostname":"SonoffPow1","IPAddress":"192.168.X.X","Gateway":"192.168.X.X","Subnetmask":"255.255.255.0","DNSServer":"192.168.X.X","Mac":"XXXXXXXX","Webserver":2,"WifiConfig":1}}
19:52:19 MQT: stat/SonoffPow1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.7.50","MqttPort":1883,"MqttClientMask":"SonoffPow1","MqttClient":"SonoffPow1","MqttUser":"posting","MAX_PACKET_SIZE":512,"KEEPALIVE":15}}
19:52:19 MQT: stat/SonoffPow1/STATUS7 = {"StatusTIM":{"UTC":"Wed Oct 10 19:52:19 2018","Local":"Wed Oct 10 19:52:19 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":0}}
19:52:19 MQT: stat/SonoffPow1/STATUS9 = {"StatusPTH":{"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
19:52:19 MQT: stat/SonoffPow1/STATUS10 = {"StatusSNS":{"Time":"2018-10-10T19:52:19","ENERGY":{"Total":712.717,"Yesterday":0.002,"Today":0.002,"Power":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
19:52:19 MQT: stat/SonoffPow1/STATUS11 = {"StatusSTS":{"Time":"2018-10-10T19:52:19","Uptime":0,"Vcc":3.180,"POWER":"OFF","Wifi":{"AP":1,"SSId":"XXXXXX","RSSI":100,"APMac":"XXXXXXX"}}}
```

**To Reproduce**
View time output `Time: "2018-10-10T19:55:33"`

**Expected behavior**
output should be of format `Time: "2018-10-10T19:55:33+00"` as per ISO 8601

**Screenshots**
NA

**Additional context**
When parsing a date/time string, without any offset, parsers will often assume it is UTC unless specific instruction is given.

For backward compatibility it is suggested this is offered as an option.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

Duplicated issue: see #3629 and #3711

Thanks.
