### ISSUE TITLE
Get H801 Led Controller to work with home assistant

### ISSUE THREAD

**Issue by jascdk** [arendst/Sonoff-Tasmota#4038]
Hi:)

I am a bit confused - which config from the wiki should I use to insert the H801 led controller into Home Assistant?

It looks like the 801 in the wiki is missing:)

Hope you can help:)

**Comment by ascillato** [comment]
Hi,

The configuration for Home Assistant not depends in the Hardware you are using. It depends on how you have configured your hardware. You don't need to look for H801 in the wiki. You need to configure as you have set your device outputs.

The HA Configs in the wiki are examples. You need to use the same topic as you configured in your device, and set relays, as you have configured in your device, etc.
