### ISSUE TITLE
Client Certificate compile guide

### ISSUE THREAD

**Issue by kesor** [arendst/Sonoff-Tasmota#4040]
Would love to see a guide created that explains how to compile a client certificate into a Tasmota image.

For example, AWS IoT generates these certificates for you upon device registration and downloads a zip file with the private+public certificates in PEM format.

I understand that Tasmota has no space to add file handling code - but a guide on the wiki that shows how these certificates can be compiled updated using OTA, and used with AWS IoT would be really great.

Related to https://github.com/arendst/Sonoff-Tasmota/issues/1395

**Comment by ascillato** [comment]
Hi,

As explained in your referred issue, I don't think is possible what you are requesting. Sorry.
