### ISSUE TITLE
Configurable Delay for RF like Sonoff Bridge

### ISSUE THREAD

**Issue by joke24** [arendst/Sonoff-Tasmota#4042]
Hi,
it would be great to have a configurable delay setting for sending RF commands with the Sonoff Bridge to the switches and sockets.

Issue: Using a Sonoff Bridge with Tasmota and two intertechno itl-3500 3 channel switch.
When using the group on/off function of openhab, all mqtt commands get sent very fast to the sonoff bridge, that sends this also to fast via rf to the switch. So often only half of the lights turn on / off.

You could do this manually with scripting in the home automation system, but it's often a pain and a lot of work to do with every switch. scripting-hell.

Would be great to have a delay to set in ms e.g. 100ms when sending a command, maybe at the end of sending one command, so the other has to wait some time befor get sent out from the bridge.

Thank you, keep up your great work! <3

**Comment by benzino77** [comment]
Maybe this will do the trick for you? 
On RF Bridge define this rule:
```
rule1 on event#allswitchesON do 
backlog rfraw <code_to_on_switch1>;delay 2;rfcode <code_to_on_switch2>;delay 2; rfcode <code_to_on_switch3>
endon 
on event#allswitchesOFF do 
backlog rfraw <code_to_off_switch1>;delay 2;rfcode <code_to_off_switch2>;delay 2; rfcode <code_to_off_switch3>
endon 
```
do not forget to eneble rule by typing `rule1 1`

Then from openhab publish: `cmnd/rf_bridge_topic/event allswitchesON` to send rfcodes to three switches to turn them on (with 200ms delay between each code) and `cmnd/rf_bridge_topic/event allswitchesOFF` to turn them off.


Backlog, delay and rfcode commands described [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands)
