### ISSUE TITLE
Timer setup, how to setup repetition?

### ISSUE THREAD

**Issue by Vendo232** [arendst/Sonoff-Tasmota#4043]
Hello

I`m not an expert but I have few Basic Sonoffs around the house hooked on Home Assistant.
I wanted to use simple timer on few of those instead of creating complicated automation.

I have set the right time zone in Console, I have selected ARM when I create ON and OFF setup in Tasmota.

The timer worked ONCE, the next day it did not execute. Would you know where I`m doing mistake?

**Comment by ascillato** [comment]
Have you set all the days on? (the list of days of the week is at the bottom of the timers configuration menu)

**Comment by Vendo232** [comment]
Yes Sir, I did that. After ONE cycle is done the selection on ARM dissapeers. Not sure what ARM means. but Im having trouble to setup the timer to go ON and OFF the same time. 
![screenshot_20181012-154406_chrome](https://user-images.githubusercontent.com/44098230/46895581-4e2e1980-ce36-11e8-8de2-c3701f09352a.jpg)

**Comment by ascillato** [comment]
Hi, you also need to tick the repeat checkbox in order to be repeated.

ARM means ARMED, that it is that the timer will trigger
