### ISSUE TITLE
Setting module from serial port corrupts baudrate

### ISSUE THREAD

**Issue by ftkalcevic** [arendst/Sonoff-Tasmota#4045]
If I use the serial port interface to set the module, eg "Module 43", the device reboots with a new baudrate which termite (and other terminal ports can't access)  It claims 4800baud, but that didn't work.

[x ] _Searched the problem in issues and in the wiki_
[x ] _Hardware used_ :  sonoff pow r2
[x ] _Development/Compiler/Upload tools used_ :  Uploaded using ESPEasy_mega-20180930, version Sonoff-Tasmota-6.2.1
[x ] _Provide the output of command_``status 0`` :

This is the output from the serial terminal session
```
Module 43
00:00:01 CMD: Module 43
00:00:01 RSL: stat/sonoff3/RESULT = {"Module":"43 (Sonoff Pow R2)"}
00:00:03 APP: Restarting

 ets Jan  8 2013,rst cause:1, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v60000608
~ld

00:00:00 APP: Set Baudrate to 4800
[00][00][00][00][00][00][00][00]
[00][00][00][00][00][00][00][00][00][00][00][00][00][00][00][00]
[00][00][00][00][00][00][00][00][00][00][00][00][00][00][00][00]
....
[00][00][00]


```

**To Reproduce**
Enter "module 43" on a serial port terminal.  Happens every time.  Doesn't happen through the web interface.

**Expected behavior**
The module should change.  Reboot.  The baudrate shouldn't change.

**Screenshots**
Log shown above.

**Additional context**
Can work around by using the web ui to set the module.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi

The behaviour you found is expected. Sonoff Pow R2 uses the serial port at 4800 baud to communicate to the power measurement chip.
