### ISSUE TITLE
Is there a way to reset yesterday's (and/or today's) energy usage on the Sonoff Pow?

### ISSUE THREAD

**Issue by mihalski** [arendst/Sonoff-Tasmota#406]
As the topic states, is there a way to reset yesterday's (and/or today's) energy usage on the Sonoff Pow?

Or is the only way to just wait it out?

**Comment by arendst** [comment]
Will be available in next release.

**Comment by mihalski** [comment]
That's great! Thank you.

**Comment by mihalski** [comment]
Thank you kindly.
