### ISSUE TITLE
Control ifan02 on the basis of a humidity sensor

### ISSUE THREAD

**Issue by danielpondruff** [arendst/Sonoff-Tasmota#4069]
Hi,

I have the following question for you.

I want to use the ifan02 to control my fan in the bathroom. Is it possible to run some kind of script with Tasmota?

I want to control the fan level 1-2-3 according to the current humidity.

 Is this possible with Tasmota, or do I have to use EasyESP for this?

Greetings
 Daniel

**Comment by wongnam** [comment]
Use Rule to do so. refer to Wiki.

**Comment by andrethomas2** [comment]
As indicated by @wongnam please read the Wiki on Rules here https://github.com/arendst/Sonoff-Tasmota/wiki/Rules

Closing this issue as it has been answered.

If you have further questions please do not hesitate to follow one of the provided support entry points listed below.

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by danielpondruff** [comment]
Perfect. Thank you 👍
