### ISSUE TITLE
user_config.h WEB_SERVER configutation

### ISSUE THREAD

**Issue by xbow42** [arendst/Sonoff-Tasmota#4070]
hello,

I use ArduininoIDE for flashing SonoffS20 
my first flash with follow parameters in user_config.h
#define WEB_SERVER 1
#define WEB_PASSWORD "mysecret"
#define WEB_USERNAME "admin"
after login on the webpage show only the Togglebutton, so far so good!
now i will change thies setup. my second firewareupload with
#define WEB_SERVER 2 // ...[100%] uploaded no errors
has no results. 
Reload (with browsercache delete) an new login. I have no access  to the configuration-buttons :-(

how can i do?

**Comment by andrethomas** [comment]
**For the love of Tasmota, can you please complete the template?**

Settings are persistent - if you want the new firmware you use the new user_config content you need to perform a reset 1 from serial console after flashing.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

If you have further questions please do not hesitate to follow one of the provided support entry points listed below.

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
