### ISSUE TITLE
Why show Module type (Sonoff Basic) when type is different?

### ISSUE THREAD

**Issue by svh1985** [arendst/Sonoff-Tasmota#4073]
Hey,

Just wondering.. why does Tasmota show **Module type (Sonoff Basic)** when the type is set to (for example) **18 Generic**? 

Only when you change the **MODULE** (which is not advised), it will show the correct module label.
`#define MODULE                 SONOFF_BASIC `

Would it not make sense to just remove the "(Sonoff Basic)" label?

![tasmota_-_configure_module](https://user-images.githubusercontent.com/5213210/46976599-3969b400-d0ca-11e8-877e-52633d6f4860.jpg)

**Comment by ascillato** [comment]
That is an example and the default value. See also mqtt config. There is shown only what will be the default after a reset 1 command or pushing button1 for more than 40 seconds, as explained in the wiki.
