### ISSUE TITLE
Management via MQTT

### ISSUE THREAD

**Issue by carpenike** [arendst/Sonoff-Tasmota#4074]
Is there a tool that will manage multiple Tasmotas via MQTT? I have the web interface disabled to support MQTTS

**Comment by ascillato** [comment]
Yes,

All the Home Automation Softwares have MQTT brokers. Use any and you can manage and control your Tasmotas.

**Comment by carpenike** [comment]
So that would work for controlling the devices attached to the Tasmotas, but what about configuring the devices themselves? Initiating firmware downloads, configuring sensors attached to GPIO pins, etc.

**Comment by ascillato** [comment]
Please, read the wiki at commands: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

All that can be configured by MQTT as explained in the refered entry of the wiki. Thanks

**Comment by ascillato** [comment]
Setting rules in your Home Automation Software.

**Comment by ascillato** [comment]
Home Assistant has as an addon TasmoAdmin for that.

**Comment by carpenike** [comment]
Yes, I've used TasmoAdmin before, but it requires the web interface in order to operate. In order to have MQTTS, you have to disable the web interface, therefore it won't work.
