### ISSUE TITLE
Is it possible to operate relays with physical switches without WAN connection?

### ISSUE THREAD

**Issue by yuuya45** [arendst/Sonoff-Tasmota#4078]
I plan to use SONOFF T1 US 2 or 3 gang.
I want to turn on / off by touching without WAN connection.
However, in the official shop there was description as follows.
"LAN Control (1 Gang Only) - Turn on / off the device even when WiFi has no Internet access"

Can I solve this problem by using Tasmota?
Is it a hardware limitation?

**Comment by ascillato** [comment]
Yes, it will work.

**Comment by ascillato2** [comment]
### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
