### ISSUE TITLE
Can't manage to sniff my Dooya remote

### ISSUE THREAD

**Issue by ThierryDB** [arendst/Sonoff-Tasmota#4082]
Hi, I have a Sonoff RF Bridge 433 flashed with Tasmota 6.xxx and I flashed the RF-Bridge-EFM8BB1 with the RF-Bridge-EFM8BB1.hex. In the console if I entre "rfraw 166" it shows:

RSL: stat/sonoff_blinds/RESULT = {"RfRaw":"ON"} 
11:34:43 MQT: Attempting connection...
11:34:49 MQT: Connect failed to 192.168.4.55:1883, rc -2. Retry in 10 sec

If I go to 192.168.4.55:1883 I see nothing. what am I doing wrong? I'm new to this. Thanks

**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used :
- [ ] Hardware used : 
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Please use latest dev build from today. http://thehackbox.org/tasmota/
The Bug you describe is fixed just now. Portisch did an update of his firmware too.
Please use latest from here if you use RfRaw: https://github.com/Portisch/RF-Bridge-EFM8BB1
