### ISSUE TITLE
Sonoff SC reporting sensors

### ISSUE THREAD

**Issue by mrmin24** [arendst/Sonoff-Tasmota#409]
SC does not seem to report Sensor status anymore on new release. Only Tele/xx/STATE

**Comment by arendst** [comment]
Works fine with me.

19:50:09 MQTT: tele/sc/STATE = {"Time":"2017-05-03T19:50:09", "Uptime":1, "Vcc":3.196, "Wifi":{"AP":2, "SSID":"indebuurt2", "RSSI":100, "APMac":"00:22:6B:FE:8E:20"}}
19:50:09 MQTT: tele/sc/SENSOR = {"Time":"2017-05-03T19:50:09", "Temperature":27.0, "Humidity":14.0, "Light":10, "Noise":20, "AirQuality":100, "TempUnit":"C"}

Suggestion power cycle your sc to restart atmel328

**Comment by mrmin24** [comment]
yup, power cycle worked
