### ISSUE TITLE
Use rule on analog0 to dimm 37 PWM1

### ISSUE THREAD

**Issue by Wifiunterputzdose** [arendst/Sonoff-Tasmota#4097]
Sry for the new Issue but my problem was not solved. 
[https://github.com/arendst/Sonoff-Tasmota/issues/4090](url)
Dont know why my thread was closed...

As I said before the ADC was enabled. Status 10 gives me the actual value of the adc input.

But the rule don't work >> rule on analog#a0div10 do dimmer %value% endon

I get the following response:

18:27:54 CMD: rule on analog#a0div10 do dimmer %value% endon
18:27:54 RSL: stat/WiFiUnterPutzdose/RESULT = {"Command":"Unknown"}

I also defined use_rules in userconfig.h

My target is to dimm the PWM1 output on D5 GPIO14 as a function of the adc input voltage
Pls help.

**Comment by ascillato** [comment]
Duplicated issue. Answered in #4090
