### ISSUE TITLE
RFC - Add Wi-Fi signal strength to status 5

### ISSUE THREAD

**Issue by timstanley1985** [arendst/Sonoff-Tasmota#4102]
I have recently had wi-fi connection issues with one of my sonoff basics and as part of my debugging the issue I wanted to check that low WiFi signal wasnt the root cause of the issue. The only way I can see currently to ascertain wi-fi signal strength is via the front end. 

Can the current signal strength be added to status 5 so I can monitor signal strength more effectively over time please.

Thanks

**Comment by edelstahlratte** [comment]
tele/.../STATE shows RSSI...

**Comment by arendst** [comment]
How about command ``status 11``...

**Comment by timstanley1985** [comment]
Thanks, learnt something new today! Not come across the term RSSI before
