### ISSUE TITLE
Sonoff T1 R2 v1.1

### ISSUE THREAD

**Issue by ahmaddxb** [arendst/Sonoff-Tasmota#4104]
Holding Button 1 and 4 don't work to get into programming mode. You need to power up the device while grounding R19 to enter programming mode.

![2018-10-19 13 10 53](https://user-images.githubusercontent.com/43728586/47209633-d9ad2a80-d3a1-11e8-8670-6c5b89465d21.jpg)

**Comment by ascillato** [comment]
Great. Please add to the wiki and close this issue. Thanks

**Comment by tyjtyj** [comment]
does double press on reset works ? I got this V1.1 and trying to avoid soldering
