### ISSUE TITLE
Sonoff Pow Yesterday

### ISSUE THREAD

**Issue by Satellietje** [arendst/Sonoff-Tasmota#411]
I have a strange thing with the Sonoff Pow's I have 4 and everyone has the same problem.

I have run on the Pow's 4.1.2. The communication by the Pow to Domoticz is ok, ut Domoticz shows yesterdays usage also today
.
![2017-05-03_19-51-30](https://cloud.githubusercontent.com/assets/26080895/25674378/e2d591d0-303a-11e7-9b52-2b241798abeb.jpg)
Image is from the washing machine Pow:
Washing machine Used on sunday
Monday not, should be about 0.017
Tuesday used
Wednesday not, should be about 0.017

If I look at the Pow self, it is correct.
![2017-05-03_19-50-49](https://cloud.githubusercontent.com/assets/26080895/25674385/ea06bf38-303a-11e7-915a-0c1a2ee08014.jpg)

All other flow meters work well, only the Sonoff Pow does not work ok with today.
I've updated domoticz to the latest version, but it does not fix the problem.

If I use more energy than yesterday, he just adds the difference to today and counts well further.
It seems that the pow told to late to Domoticz that it's a day later or something. The clock is exactly right in Domoticz and in the Pow.

**Comment by arendst** [comment]
I'm afraid that your findings are the result of my daily resetting of the energy value. Domoticz probably wants to receive an incrementing value (as provided by my smart meter) and calculates the daily values from it.

That would need some additional code providing a total energy use counter. I sleep on it...

**Comment by Satellietje** [comment]
I'll keep waiting until you wake up again :-)

**Comment by mihalski** [comment]
Can Domoticz maybe accumulate the usage using the period value?

**Comment by arendst** [comment]
I've already implemented a total energy counter which I believe will solve the Domoticz problem and also provides a nice addition to the counter count ;-).

To be released soon.

**Comment by arendst** [comment]
@Satellietje what Sensor Type did you select for the Pow Energy usage in Domoticz? ``Usage (Electric)`` or ``Electric (Instant+Counter)``?

**Comment by mihalski** [comment]
How long will the counter accumulate before it resets?

**Comment by arendst** [comment]
Good question. You caught me just in time. Have to rewrite this counter...

**Comment by mihalski** [comment]
I have my moments. My immediate thought was that if it accumulates forever it will overrun or similar.

**Comment by arendst** [comment]
Roll-over at about 40MWh so that should take a while...

**Comment by mihalski** [comment]
If my calculations are correct, that would be $9,844 of electricity here :P Plus fees and surcharges.

**Comment by Satellietje** [comment]
I use (Instant + Counter)

@Satellietje what Sensor Type did you select for the Pow Energy usage in Domoticz? Usage (Electric) or 
Electric (Instant+Counter)?

**Comment by Satellietje** [comment]
@arendst, That was a quick update, I installed him on one Pow.
Tomorrow I know if it works.

**Comment by mlamie** [comment]
I have installed 5.0.4 and see the below in the Sonoff console. My question is why does it take several minutes to update the power usage?

`22:33:29 MQTT: domoticz/in = {"idx":160,"nvalue":1,"svalue":""}
22:33:29 MQTT: stat/sonoff/RESULT = {"POWER":"ON"}
22:33:29 MQTT: stat/sonoff/POWER = ON
22:34:40 MQTT: domoticz/in = {"idx":162,"nvalue":0,"svalue":"109;12.7"}
22:34:40 MQTT: tele/sonoff/ENERGY = {"Time":"2017-05-06T22:34:40", "Total":0.013, "Yesterday":0.000, "Today":0.013, "Period":7, "Power":109, "Factor":1.00, "Voltage":226, "Current":0.464}
22:36:58 MQTT: domoticz/in = {"idx":160,"nvalue":0,"svalue":""}
22:36:58 MQTT: stat/sonoff/RESULT = {"POWER":"OFF"}
22:36:58 MQTT: stat/sonoff/POWER = OFF
22:39:58 MQTT: domoticz/in = {"idx":162,"nvalue":0,"svalue":"0;16.9"}`

p.s. I have created 2x a dummy
- Switch | IDX 160
-  Usage (Electirc) | IDX 162

**Comment by mihalski** [comment]
How would you imagine it to work? Send updated power usage every second? The web interface updates much more frequently.

The default for MQTT is 300 seconds which amount to 5 minutes. This can be changed in the source in user_config.h under:
```
// -- MQTT - Telemetry ----------------------------
#define TELE_PERIOD            300               // [TelePeriod] Telemetry (0 = disable, 10 - 3600 seconds)
```

**Comment by Satellietje** [comment]
Yes, it works! :)
![afbeelding](https://cloud.githubusercontent.com/assets/26080895/25778062/64496dd0-32f3-11e7-8386-8997d761a5b2.png)

**Comment by arendst** [comment]
@mihalski  and @mlamie try focussing on online commands instead of changing user_config.h and recompile. Most parameters can be changed online. In this case use teleperiod.

@Satellietje glad it works. 

I'll close this issue soon.

**Comment by mihalski** [comment]
True enough. The only user_config.h change that I would recommend is the wifi network and password.
