### ISSUE TITLE
Setting up an offset for the "built-in" sensors of the Sonoff SC

### ISSUE THREAD

**Issue by 7h30n3** [arendst/Sonoff-Tasmota#4114]
Hello,

According to the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#8b-adjust-the-value-of-a-sensor-and-send-it-by-mqtt) adding an offset to a sensor value is done like this:

```
rule
on tele-SI7021#temperature do backlog var1 %value%; add1 2; event sendtemp endon
on event#sendtemp do publish stat/sonoff/temp %var1% endon
```

However, how to adress the bulit-in sensors of the Sonoff SC?

Because the sent MQTT message on my topic `tele/parlor_sonoff_sc/SENSOR` looks like this:

```
{"Time":"2018-10-20T00:12:21","SonoffSC":{"Temperature":26.0,"Humidity":49.0,"Light":10,"Noise":20,"AirQuality":100},"TempUnit":"C"}
```

the second line of the rule above doesn't seem applicable, not to mention the "name" of the sensor in my case.

**Comment by ascillato** [comment]
Corrections are meant to be done inside your automation software.

If you want to do it inside Tasmota, you can modify that rule to match your JSON message to:

```
rule
on tele-SonoffSC#temperature do backlog var1 %value%; add1 2; event sendtemp endon
on event#sendtemp do publish stat/sonoff/temp %var1% endon
```

Please for support go to the Tasmota Chat (https://discord.gg/Ks2Kzd4). Thanks
