### ISSUE TITLE
Configure GPIO14 for Door Contact Sensor Sonoff 4H Pro R2

### ISSUE THREAD

**Issue by dastrix80** [arendst/Sonoff-Tasmota#4115]
Hi All

Ive read a few articles but im highly confused.

I have my contact sensor connected to the unit on GND & SDA pin.

I cannot see references to GPIO14 in my web UI.

Can anyone assist? Essentially I want to report if the gate is open or closed using this device, with the other channels used to pulse the gate for fully open, or partially open.

Thank you!
Kris

**Comment by ascillato** [comment]
Hi, please for support go to the Tasmota Chat (https://discord.gg/Ks2Kzd4). Thanks
