### ISSUE TITLE
GY-49 MAX44009 Ambient Light Sensor Module

### ISSUE THREAD

**Issue by Sergio-tix** [arendst/Sonoff-Tasmota#4116]
Hi!
Is it possible to add support the industrial MAX44009 ambient light sensor?

**Comment by ascillato** [comment]
If you need further assistant please find us in the Tasmota Chat. Thanks

**Comment by Sergio-tix** [comment]
APDS9960 has a completely different purpose.  ̷B̷H̷1̷7̷7̷0̷  BH1750 has significantly worse specifications. 
But if not, then do not. Find another way out.
