### ISSUE TITLE
Restart causes trigger on 6.2 Tasmota

### ISSUE THREAD

**Issue by dastrix80** [arendst/Sonoff-Tasmota#4120]
Hi All

This is occurring again. I have a brand new 4CH Pro R2 unit and its doing the example same thing. Im using Tasmota 6.2.0

Ive already configured SetOption0 0, wificonfig 5 and PowerOnState 0.

If I restart the unit via the WebUI it triggers a relay. This is a HUGE issue for me because I have dogs that can escape the yard through the back gate.

see status0:

01:24:36 CMD: Status 0
01:24:36 MQT: stat/gate/STATUS = {"Status":{"Module":23,"FriendlyName":["GateControl","GateControl2","GateControl3","GateControl4"],"Topic":"gate","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"SaveData":1,"SaveState":0,"ButtonRetain":0,"PowerRetain":0}}
01:24:36 MQT: stat/gate/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/GarageController.ino.bin","RestartReason":"Software/System restart","Uptime":"0T00:01:59","StartupUTC":"2018-10-21T00:22:37","Sleep":0,"BootCount":28,"SaveCount":51,"SaveAddress":"F9000"}}
01:24:36 MQT: stat/gate/STATUS2 = {"StatusFWR":{"Version":"6.2.0","BuildDateTime":"2018-08-31T15:15:32","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
01:24:36 MQT: stat/gate/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["Tard","indebuurt2"],"TelePeriod":200,"SetOption":["00000008","55818000","00000001"]}}
01:24:36 MQT: stat/gate/STATUS4 = {"StatusMEM":{"ProgramSize":472,"Free":528,"Heap":19,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","24000000","23B617CE","00000000"]}}
01:24:36 MQT: stat/gate/STATUS5 = {"StatusNET":{"Hostname":"gate-3636","IPAddress":"192.168.0.239","Gateway":"192.168.0.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.254","Mac":"84:0D:8E:46:2E:34","Webserver":2,"WifiConfig":5}}
01:24:36 MQT: stat/gate/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.3","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_462E34","MqttUser":"mosquitto","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
01:24:36 MQT: stat/gate/STATUS7 = {"StatusTIM":{"UTC":"Sun Oct 21 00:24:36 2018","Local":"Sun Oct 21 01:24:36 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"07:19","Sunset":"17:49"}}
01:24:36 MQT: stat/gate/STATUS10 = {"StatusSNS":{"Time":"2018-10-21T01:24:36"}}
01:24:36 MQT: stat/gate/STATUS11 = {"StatusSTS":{"Time":"2018-10-21T01:24:36","Uptime":"0T00:01:59","Vcc":2.936,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"Tard","RSSI":100,"APMac":"FC:EC:DA:D1:6D:D7"}}}

**Comment by ascillato** [comment]
Hi,

Sorry, duplicated issue. Just reopen your old issue.
