### ISSUE TITLE
Shelly 1 Switchmodes

### ISSUE THREAD

**Issue by HorstRado** [arendst/Sonoff-Tasmota#4123]
Hello,

I need help for Shelly1 with Tasmota. I have installed Tasmota 6.2.1.x
I want to replace an eltaco with the Shelly. Therefor I connect the pushbutton to the
SW pin of the Shelly. I thought switchmode 0 would work like a pushbutton on a sonoff:
Pressing once: relay is on, press again: relay is off. But in my case the relay goes on when 
I press the pushbutton and go off when the button is released. Same with switchmode 1. All other
switchmodes do not work at all. Any idea?

Regards
Horst

**Comment by arendst** [comment]
Switchmode 0,1 and 2 work like a normal switch: relay off when open, relay on when closed (or inverted)

To use a bushbutton you need to select switchmode 3 or 4.

See #3989 too

**Comment by ascillato2** [comment]
Hi

You said version 6.2.1.x but which one. Several issues are solved using last version. Please, update to last version and test again please.

**Comment by HorstRado** [comment]
Thanks. The Problem is solved with latest development version 6.2.1.18
