### ISSUE TITLE
Sonoff Pow loses Energy Total values

### ISSUE THREAD

**Issue by FabianHM** [arendst/Sonoff-Tasmota#4125]
Hello,
Why does the Sonoff Pow lose its Total value already after a day without mains voltage? I'm sure that was not the case in the older version.

Thanks for your Ideas,
Greetings Fabian

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Development/Compiler/Upload tools used : Sonoff-Tasmota 6.2.0 
- [x] Hardware used : Sonoff Pow (V1)

**Comment by ascillato** [comment]
Please, update to the last version from http://thehackbox.org/tasmota/

**Comment by Frogmore42** [comment]
The pow and pow r2 share a lot of code, so it is not surprising they would have the same issue, that is likely fixed.

**Comment by ascillato2** [comment]
When you have time, please told us if it works for you.

**Comment by anwar3000** [comment]
> Hello,
> Why does the Sonoff Pow lose its Total value already after a day without mains voltage? I'm sure that was not the case in the older version.
> 
> Thanks for your Ideas,
> Greetings Fabian
> 
> * [x]  Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
> * [x]  Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
> * [x]  Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
> * [x]  Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
> * [x]  Development/Compiler/Upload tools used : Sonoff-Tasmota 6.2.0
> * [x]  Hardware used : Sonoff Pow (V1)

SAME PROBLEM WITH ME 
8.3.1(sensors)

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
