### ISSUE TITLE
Shelly is supported only in the development version (now it is 6.2.1.6)

### ISSUE THREAD

**Issue by bean007007007** [arendst/Sonoff-Tasmota#4128]
download it from http://thehackbox.org/tasmota/

_Originally posted by @ascillato in https://github.com/arendst/Sonoff-Tasmota/issues/2789#issuecomment-424138011_

the firmware from thehackbox works great on my shelly 1 but.. MQTT is missing Domoticz tab to configure the IDX numbers of the switch :\ can someone update the firmware from thehackbox with the Domoticz tab enabled ?

**Comment by ascillato** [comment]
Remember that you can compile it by yourself. All the instructions are in the wiki.

**Comment by bean007007007** [comment]
thank you very much ascillato :)
