### ISSUE TITLE
Serial Port with AC wire connected

### ISSUE THREAD

**Issue by j105** [arendst/Sonoff-Tasmota#413]
Hi There,

Just wondered that if I am able to access serial when ac wire connected?

Cheers
Jimmy

**Comment by arendst** [comment]
If it's a Sonoff Pow you'll need optocouplers as documented in the wiki as there is AC power on the serial lines.

Anything else can have serial connected as long as you DO NOT CONNECT 3V3 to your serial converter.

**Comment by j105** [comment]
Thanks and Can I tap 3.3v from that pin for external pic?

**Comment by arendst** [comment]
If it doesn't drain power too much it should work.

**Comment by j105** [comment]
Sounds great.

Thanks for clarification.
