### ISSUE TITLE
it looks esp device have bug if mqtt server down for long time,

### ISSUE THREAD

**Issue by hamwong** [arendst/Sonoff-Tasmota#4132]
it may have a bug on 6.2.1.15, today my mqtt server were down for around 3 hours, after mqtt server recover, I found there is 4 switch (sonoff device, 2 Pow, 1 Dual, 1 basic, total around 30) no response to mqtt command, it keep tel post by set time, but it's not getting command, mqtt server also see command from openhab but no reponse from device, switch is normal, I login to web and found everything is running fine just no response on mqtt, console also don't see income msg.

There is another issue with MQTT since long time ago, is there anyway can make relay won't flash when mqtt is not reachable, like if it's on with light, light keep flash every x-1xsec, I have set wificonfig 5 so it won't reboot, but while it keep connecting, relay still flash and relay also slow response (eg, press on button will slow reponse), can mqtt be manual set retry time and let unit run more smooth, and my family get annoy due to light keep flashing,

P.S. I use original MQTT_PUBSUBCLIENT on 3.x-5.x firmware, and change to MQTT_TASMOTAMQTT on 6.1.15, today 4 switch stop response is all run on 6.1.15 with MQTT_TASMOTAMQT, (issue happen today never happen before, on 3.x 4.x 5.x firmware, mqtt down few hours only make relay flash and no response, but all back to network when mqtt back online)

**Comment by ascillato** [comment]
Hi, try to use last version. The last version is using a new pubsubclient mqtt library. Thanks.
