### ISSUE TITLE
Chirp! moisture sensor

### ISSUE THREAD

**Issue by madmicio** [arendst/Sonoff-Tasmota#4137]
I looked for the iusse but I did not find the answer I'm looking for. is it possible to use this humidity sensor with tasmota?
https://www.tindie.com/products/miceuz/i2c-soil-moisture-sensor/

Which capacitive humidity sensors are supported?

Which rain sensors are supported?

**Comment by andrethomas** [comment]
None from what I know.

Soil moisture sensors are tricky because the cheap chinese ones generally last a few days and then you start not getting useful data due to oxidation or corrosion on the probes.

I think adding I2C support for that device is the least of the problem but perhaps someone like @mike2nl will entertain it.

Just my 2c ;)

**Comment by mike2nl** [comment]
@madmicio 
there are more then one sensor to messaure humidity and temperature.
There is a DHT11, DHT22, AM2302 and some others.
Depending on the quality you need and what you will messaure.

Right now there is no RAIN sensor supported. Mostly used in combination with weather station.
But we have now the TX20 wind direction and speed.

So possible you can give us some more information what you precisely will do.

**Comment by madmicio** [comment]
my project is to insert the humidity sensor into the ground and activate irrigation only when the humidity falls below a certain value. I bought the sensor in the link because it is difficult to corrode.

with the rain sensor instead I would like to change the time of my alarm in case of rain

**Comment by ascillato** [comment]
Hi,

There is already an open request for this sensor at #2065

Let's continue the thread there.

Thanks

**Comment by madmicio** [comment]
Why did you close? Beyond the CHIRP, I asked if there are rain sensors and other soil moisture sensors supported.

**Comment by andrethomas** [comment]
Your question was answered, so no need for it to remain open.
