### ISSUE TITLE
Access Web environment after a few days

### ISSUE THREAD

**Issue by lscosta90br** [arendst/Sonoff-Tasmota#4138]
After a few days I can not access my web environment by ip

```
14:17:56 CMD: status 0
14:17:56 MQT: stat/garagem-controle-wireless/STATUS = {"Status":{"Module":18,"FriendlyName":["Garagem Controle Wireless"],"Topic":"garagem-controle-wireless","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":0,"ButtonRetain":0,"PowerRetain":0}}
14:17:56 MQT: stat/garagem-controle-wireless/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.2.xx:9541/data/firmwares/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:53","StartupUTC":"2018-10-22T17:17:03","Sleep":0,"BootCount":115,"SaveCount":227,"SaveAddress":"F4000"}}
14:17:56 MQT: stat/garagem-controle-wireless/STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-09-09T16:50:26","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
14:17:56 MQT: stat/garagem-controle-wireless/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["magneto_v3_bgn",""],"TelePeriod":300,"SetOption":["00008008","55818000","00000001"]}}
14:17:56 MQT: stat/garagem-controle-wireless/STATUS4 = {"StatusMEM":{"ProgramSize":471,"Free":532,"Heap":15,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3,"Features":["00000809","0FDAE794","000003A0","23B617CE","00000000"]}}
14:17:56 MQT: stat/garagem-controle-wireless/STATUS5 = {"StatusNET":{"Hostname":"garagem-controle-wireless-4944","IPAddress":"192.168.2.xx","Gateway":"192.168.2.100","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1x","Mac":"60:01:94:xx:xx:xx","Webserver":2,"WifiConfig":2}}
14:17:56 MQT: stat/garagem-controle-wireless/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.25","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_2BB350","MqttUser":"ha","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
14:17:56 MQT: stat/garagem-controle-wireless/STATUS7 = {"StatusTIM":{"UTC":"Mon Oct 22 17:17:56 2018","Local":"Mon Oct 22 14:17:56 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":-3,"Sunrise":"03:21","Sunset":"13:47"}}
14:17:57 MQT: stat/garagem-controle-wireless/STATUS10 = {"StatusSNS":{"Time":"2018-10-22T14:17:56","Switch1":"ON"}}
14:17:57 MQT: stat/garagem-controle-wireless/STATUS11 = {"StatusSTS":{"Time":"2018-10-22T14:17:57","Uptime":"0T00:00:54","Vcc":2.710,"POWER":"OFF","Wifi":{"AP":1,"SSId":"magneto_v3_bgn","RSSI":100,"APMac":"EC:08:6B:xx:xx:xx"}}}
```

Is there any command to take the web environment out of power save?

**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**Describe the bug**
_A clear and concise description of what the bug is._

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [ ] _Searched the problem in issues and in the wiki_
- [ ] _Hardware used_ : 
- [ ] _Development/Compiler/Upload tools used_ :
- [ ] _Provide the output of command_``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**To Reproduce**
_Steps to reproduce the behavior:_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi, there is not in Tasmota such thing as web page power save.

Seems that your device just hungs or you are having wifi issues with your router setup.

**Comment by andrethomas** [comment]
Also try using `wificonfig 5` so that your device does not restart when losing wifi connectivity

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered. 

If you have further questions please do not hesitate to follow one of the provided support entry points listed below.

### Support Information

See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by lscosta90br** [comment]
How do I schedule a reboot every day at 11 o'clock?

**Comment by ascillato** [comment]
go to timers. set your time in timer1 and put rule1 as output

go to console:

```
rule1 1
rule1 on Clock#Timer=1 do restart 1 endon
```

For more information, please visit the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki)
