### ISSUE TITLE
Avoid UART and directly flash EEPROM?

### ISSUE THREAD

**Issue by thatso** [arendst/Sonoff-Tasmota#4139]
Regarding the different and sometimes rather difficult to connect pinouts of some (Sonoff) devices, I wonder if it would be feasible not to connect the usual UART pins but write directly to the EEPROM?
The chip could be easily connected via a test clip for programming.
Could this be done with a bin file compiled the regular way, has the file to be prepared in some sort or is this idea simply not possible?

**Comment by ascillato** [comment]
Sorry. There are several sonoff that uses esp8285 that don't have the eeprom outside. So, that will leave a lot of Sonoff devices outside.
