### ISSUE TITLE
Sonoff Dual Module GPIO1+GPIO3

### ISSUE THREAD

**Issue by zibous** [arendst/Sonoff-Tasmota#4142]
I am using a Sonoff Dual and would like to connect a DTH22 sensor. If I use Sonoff Dual R2 modules, then I can see the sensor's data but not switch the relay.

Is it possible to activate the "Serial IN / OUT" on the Sonoff Dual?

![img_20181023_124831](https://user-images.githubusercontent.com/30198737/47356223-ba750c80-d6c3-11e8-9a79-a89eef2721ba.jpg)

![bildschirmfoto 2018-10-23 um 12 51 32](https://user-images.githubusercontent.com/30198737/47356247-c791fb80-d6c3-11e8-82f4-7f680925f062.png)

![bildschirmfoto 2018-10-23 um 12 54 57](https://user-images.githubusercontent.com/30198737/47356255-c9f45580-d6c3-11e8-946a-d1589f879ffb.png)

**Comment by arendst** [comment]
The Sonoff Dual uses the serial interface to switch the relays so you cannot use TX/RX for connecting a sensor.

Sonoff Dual R2 uses direct connected relays and the RX/TX can be used for sensors.

Your device as shown on the picture is a Sonoff Dual and NOT a Sonoff Dual R2.

**Comment by ascillato** [comment]
Hi,

In a sonoff dual, the relays are being controlled by another MCU and the esp8266 control that MCU using the serial interfase. So, it is not possible to use the serial interfase in a sonoff dual.

**Comment by zibous** [comment]
@theo:
Thanks, i understand, therefore I should use the GIPO14 for my Sonoff Dual, only I find only directly at the esp8266 control

**Comment by arendst** [comment]
Yes. correct. By request of some users these GPIO's were made configurable as they seemed to be very handy in connecting wires to the chip. ;-)
