### ISSUE TITLE
Rule mqtt#connected is fired even when MQTT server is disabled

### ISSUE THREAD

**Issue by KPK75** [arendst/Sonoff-Tasmota#4149]
**Describe the bug**
Rule mqtt#connected is fired even when MQTT server is disabled.

**To Reproduce**
`setoption3 0`
`rule1 on mqtt#connected do var1 1 endon`
`rule2 1`
`restart 1`

`00:00:06 RUL: MQTT#CONNECTED performs "var1 1"`
`00:00:06 RSL: RESULT = {"Var1":"1"}`

**Expected behavior**
No mqtt#connected event.

**Comment by ascillato** [comment]
I could reproduce the issue. Thanks for reporting :+1:

**Comment by ascillato2** [comment]
Closing as it is fixed. Thanks
