### ISSUE TITLE
Time set to 1970

### ISSUE THREAD

**Issue by chris8837** [arendst/Sonoff-Tasmota#4152]
Any reason why my new flashes are being set to 1970?

Just happened all of a sudden.

**Comment by ascillato** [comment]
That means that you don't have connection to internet. Tasmota uses NTP to Sync the Time

**Comment by ascillato** [comment]
type in the console `NtpServer`

and you will see if it is ok.

to reset to default use:
NtpServer1 1
NtpServer2 1
NtpServer3 1

Have you tried to power cycle the device ?

**Comment by ascillato** [comment]
If you stills find that issue erase all flash with esptool.py and flash again using the precompiled bins from http://thehackbox.org/tasmota/

**Comment by ascillato** [comment]
Also remember that you can find us also in the Tasmota Chat
