### ISSUE TITLE
2x TH16 w/ SI7021 not showing any sensor data

### ISSUE THREAD

**Issue by NOTORIOUSVR** [arendst/Sonoff-Tasmota#4157]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [X ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ X] Development/Compiler/Upload tools used : Arduino 1.8.5
- [ X] Hardware used :  TH16 + SI7021
- [X ] Provide the output of command ``status 0`` :
```
02:17:19 CMD: status 0
02:17:19 RSL: STATUS = {"Status":{"Module":4,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
02:17:19 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:03:10","StartupUTC":"2018-10-25T01:14:09","Sleep":0,"BootCount":4,"SaveCount":10,"SaveAddress":"FA000"}}
02:17:19 RSL: STATUS2 = {"StatusFWR":{"Version":"6.0.0a","BuildDateTime":"2018-07-02T17:46:07","Boot":6,"Core":"2_4_1","SDK":"2.2.1(cfd48f3)"}}
02:17:19 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["BATCAVE",""],"TelePeriod":300,"SetOption":["00008001","55818000"]}}
02:17:19 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":545,"Free":456,"Heap":15,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","00000000","17B6179A","00000000"]}}
02:17:19 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff-1683","IPAddress":"10.10.10.125","Gateway":"10.10.10.254","Subnetmask":"255.255.240.0","DNSServer":"10.10.10.10","Mac":"EC:FA:BC:87:26:93","Webserver":2,"WifiConfig":3}}
02:17:19 RSL: STATUS7 = {"StatusTIM":{"UTC":"Thu Oct 25 01:17:19 2018","Local":"Thu Oct 25 02:17:19 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"07:26","Sunset":"17:42"}}
02:17:19 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-10-25T02:17:19"}}
02:17:19 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-10-25T02:17:19","Uptime":"0T00:03:10","Vcc":3.471,"POWER":"OFF","Wifi":{"AP":1,"SSId":"BATCAVE","RSSI":100,"APMac":"80:2A:A8:81:E9:3F"}}}
```

I have two TH16 units with SI7021 sensors (both units purchased directly from Sonoff web store), neither will show any sensor data (I believe it should show under STATUS10 in the console.

Module configured for TH (04) and Sensor GPIO set for SI7021 (03)

Not sure what else to do at this point?

Thanks

**Comment by ascillato** [comment]
Please, go to the console and type `weblog 4` and restart.
Then show us if there is some error message in the console when the device starts.

**Comment by ascillato** [comment]
Another thing you can try is to update. Your version is old. The last precompiled bins from the development branch are at http://thehackbox.org/tasmota/

**Comment by NOTORIOUSVR** [comment]
console output from weblog 4:

``
00:00:00 CFG: Loaded from flash at FB, Count 89
00:00:00 APP: Boot Count 73
00:00:00 SRC: Restart
00:00:00 Project sonoff SERVER-PWR (Topic sonoff-serverpwr, Fallback DVES_0DC031, GroupTopic sonoffs) Version 6.0.0a-2_4_1
00:00:00 CFG: Saved to flash at FA, Count 90, Bytes 3584
00:00:00 WIF: Checking connection...
00:00:00 WIF: Attempting connection...
00:00:00 WIF: Connecting to AP1 BATCAVE in mode 11N as SERVER-PWR...
00:00:01 WIF: Checking connection...
00:00:01 WIF: Attempting connection...
00:00:02 WIF: Checking connection...
00:00:02 WIF: Attempting connection...
00:00:04 WIF: Checking connection...
00:00:04 WIF: Attempting connection...
00:00:05 WIF: Checking connection...
00:00:05 WIF: Attempting connection...
00:00:06 WIF: Checking connection...
00:00:06 WIF: Connected
00:00:06 DNS: Initialized
00:00:06 HTP: Web server active on SERVER-PWR.local with IP address 10.10.10.119
00:00:06 HTP: Main Menu
00:00:06 MQT: Attempting connection...
00:00:06 MQT: Connected
00:00:06 MQT: tele/sonoff-serverpwr/LWT = Online (retained)
00:00:06 MQT: cmnd/sonoff-serverpwr/POWER = 
00:00:06 MQT: Subscribe to cmnd/sonoff-serverpwr/#
00:00:06 MQT: Subscribe to cmnd/sonoffs/#
00:00:06 MQT: Subscribe to cmnd/DVES_0DC031/#
00:00:06 MQT: tele/sonoff-serverpwr/INFO1 = {"Module":"Sonoff TH","Version":"6.0.0a","FallbackTopic":"DVES_0DC031","GroupTopic":"sonoffs"}
00:00:06 MQT: tele/sonoff-serverpwr/INFO2 = {"WebServerMode":"Admin","Hostname":"SERVER-PWR","IPAddress":"10.10.10.119"}
00:00:06 MQT: tele/sonoff-serverpwr/INFO3 = {"RestartReason":"Software/System restart"}
00:00:06 DHT: Timeout waiting for start signal high pulse
00:00:06 APP: (UTC) Thu Oct 25 01:47:38 2018, (DST) Sun Mar 25 02:00:00 2018, (STD) Sun Oct 28 03:00:00 2018
02:47:39 HTP: Console
02:47:39 MQT: stat/sonoff-serverpwr/RESULT = {"POWER":"ON"}
02:47:39 MQT: stat/sonoff-serverpwr/POWER = ON
02:47:46 MQT: tele/sonoff-serverpwr/STATE = {"Time":"2018-10-25T02:47:46","Uptime":"0T00:00:14","Vcc":3.519,"POWER":"ON","Wifi":{"AP":1,"SSId":"BATCAVE","RSSI":100,"APMac":"80:2A:A8:81:E9:3F"}}
02:47:46 DHT: Timeout waiting for start signal high pulse
02:47:58 WIF: Checking connection...
02:47:58 WIF: Connected
``

Re. updating... just download sonoff.bin and then use the FW update menu item?

**Comment by NOTORIOUSVR** [comment]
Never mind, the update did the trick on both devices with the sensor status showing up right at the top of the main web page instantly on one, and the other the plug needed to be pushed in just a tiny bit more after seeing NaN displayed.

Thank you very much!
