### ISSUE TITLE
No difference in MQTT msg generated by different switches

### ISSUE THREAD

**Issue by kkx4r** [arendst/Sonoff-Tasmota#4159]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**Describe the bug**
_A clear and concise description of what the bug is._
No difference in MQTT msg for individual switches connected to  various GPIOs
No difference in MQTT msg for input configured as Switch1 or as Switch1n

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x] _Searched the problem in issues and in the wiki_
- [x] _Hardware used_ : Wemos D1 Mini
- [x] _Development/Compiler/Upload tools used_ : VSCode/PlatformIO Tasmota V6.2
- [x] _Provide the output of command_``status 0`` :

I need to connect a series of external switches to Home assistant and react to their states. For a test I took a Wemos D1 Mini with Tasmota connected to 7 switches. There is no relay connected to the Wemos D1, but adding a single relay in the configuration of the module solved the first problem. Without the relay, each of the positions produced the same msg:
Topic/cmnd/POWER
No indication which particular switch was activated and what its state was.
Adding a single relay made that msg change into
Topic/cmnd/POWERx = OFF
Now I get the switch id and the state for each individual IO. So the problem is easily resolved.

Each of the used Wemos D1 Mini IO points is pulled up to 3.3VDC by a 4k7 resistor. The switch switches the point to GND, so from logical ON to OFF. That produces the ../POWERx OFF msg. By configuring the inputs as Switch1..7n I expected the inverse value, so ON for a closed switch. But nothing changed, the same OFF msg was produced. The following STATUS 0 output is obtained with seven switches set to the n version and an added unused dummy relay.

STATUS 0 OUTPUT HERE
```
00:40:29 CMD: Status 0
00:40:29 MQT: Meterkast_OTZ/stat/STATUS = {"Status":{"Module":18,"FriendlyName":["Sonoff"],"Topic":"Meterkast_OTZ","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"Techniek_OTZ","SwitchMode":[1,1,1,1,1,1,1,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:40:29","StartupUTC":"","Sleep":0,"BootCount":27,"SaveCount":70,"SaveAddress":"F8000"}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS2 = {"StatusFWR":{"Version":"6.2.1.18","BuildDateTime":"2018-10-24T10:58:42","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["domotica",""],"TelePeriod":300,"SetOption":["00008009","55818000","00000001"]}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS4 = {"StatusMEM":{"ProgramSize":488,"Free":512,"Heap":18,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3,"Features":["00000413","0FDAE794","240083A1","23B617CE","00003BC0"]}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS5 = {"StatusNET":{"Hostname":"Meterkast_OTZ-3593","IPAddress":"192.168.1.26","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.27","Mac":"DC:4F:22:1C:8E:09","Webserver":2,"WifiConfig":3}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.3","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_1C8E09","MqttUser":"Swift","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 00:40:29 1970","Local":"Thu Jan 01 00:40:29 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":1,"Sunrise":"07:44","Sunset":"15:32"}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:40:29","Switch1":"ON","Switch2":"ON","Switch3":"ON","Switch4":"ON","Switch5":"ON","Switch6":"ON","Switch7":"ON"}}
00:40:29 MQT: Meterkast_OTZ/stat/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:40:29","Uptime":"0T00:40:29","Vcc":2.766,"POWER":"OFF","Wifi":{"AP":1,"SSId":"domotica","BSSId":"B0:4E:26:29:9F:94","Channel":1,"RSSI":100}}}```
```

**To Reproduce**
_Steps to reproduce the behavior:_
1. Connect a few switches to a Wemos D1 Mini and configure it with no relay
2. Add a dummy relay to the configuration and test once with Switch1 assigned to a GPIO point and next with Switch1n assigned to the same position. 

**Expected behavior**
_A clear and concise description of what you expected to happen._
When there is no relay in the physical setup I do not expect the requirement to add one in order to obtain the number and the state of each switch indicated in the MQTT msg.
When I change the GPIO configuration from Switch1..7 to Switch1..7n I expect the reverse state reported.

**Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/25265912/47492220-cd671880-d84c-11e8-8f07-c0d448410116.png)

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

By design, if you set several switches with just one relay defined, that will be the standard case of a STAIR LIGHT. So, Tasmota interprets as that.

What you want to do is not the standard, so you need to tell Tasmota what behaviour you want. So, you need to use rules and set what you need.

For example:

go to console and type:

```
rule1 1
rule1 on switch2#state do publish cmnd/mysonofftopic/switch2 %value% endon on switch3#state do publish cmnd/mysonofftopic/switch3 %value% endon
```

You can set the mqtt message you want and add all rules for the switches as you want.

For more information about commands and rules, please check the wiki.

If you need more help, remember that you can find us in the Tasmota Chat.

Thanks
