### ISSUE TITLE
Sonoff Bridge EFM8 firmware update

### ISSUE THREAD

**Issue by catroc** [arendst/Sonoff-Tasmota#4165]
Hi,

I'm using the Sonoff Bridge V2 and trying to update the rf chip with the portisch firmware.
But I can't do the upload because tasmota tells me that there is not enough free space.

I'm using tasmota 6.2.1 and it doesn't matter if I use the minimal or some other image.

What's wrong here?

Regards Michael

**Comment by ascillato** [comment]
First you need to update Tasmota to last version from http://thehackbox.org/tasmota/

**Comment by ascillato** [comment]
Then you need to follow the wiki instructions for flashing the RF CHIP.

https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF-Bridge-433#rf-chip-firmware-upgrade

**Comment by ascillato** [comment]
If you need further assistance, remember that you can find us in the Tasmota Chat https://discord.gg/Ks2Kzd4

**Comment by ascillato2** [comment]
Please, also remember to search in the issues. This was addressed before several times.
