### ISSUE TITLE
MagicHome RGB LED - IR remote not working

### ISSUE THREAD

**Issue by hawaiianer** [arendst/Sonoff-Tasmota#4167]
I am trying to get my magic home board to work with the included ir remote:
![20181026_112745](https://user-images.githubusercontent.com/11526907/47558149-c1de2500-d912-11e8-9fb2-c0d76c4e2f7b.jpg)
![20181026_112800](https://user-images.githubusercontent.com/11526907/47558150-c1de2500-d912-11e8-8e4e-5f5d67e63f75.jpg)

I have tried tasmota version 6.2.1 with the included board gpio settings - no luck.
Also I have tried this data (modified the sonoff_template.h (using plattform.io) - no luck.

The problem might be that the board/gpio layout is a different one in my case. Tried to check with a multimeter where the pin from the ir reciever will end up on the ESP8266 chip but I could not locate it....

Best regards,
hawaiianer

**Comment by ascillato2** [comment]
Hi,

Sorry, that board is not the standard magichome. Is a clone, so you will need to find which gpio are being used and modify a template or use generic module.

**Comment by hawaiianer** [comment]
thanks for the replies. 
My main problem is the IR remote which does not work. The LEDs do light on to blue when the device is switched on via the web interface.
I will try to figure out where the differences on the board are or I just buy the H801 for my RGB light.
