### ISSUE TITLE
esp8266 2.5.0 and tls

### ISSUE THREAD

**Issue by or78rXxZ** [arendst/Sonoff-Tasmota#4168]
@ascillato, i have tried your build from http://thehackbox.org/stage/ and have had no issues
if you have spare minute could you make a bin file for a basic r2 with tls enabled, no web server and no sensors

thank you

**Comment by ascillato** [comment]
As TLS uses a lot of memory, you will need to disable lot of features to make it work. So, the best is that you build by yourself and try which features works in your device.

**Comment by ascillato2** [comment]
If you need further assistant in compiling, remember that you can find us also in the Tasmota Chat
