### ISSUE TITLE
Publish LWT on TOPIC change

### ISSUE THREAD

**Issue by mrmin24** [arendst/Sonoff-Tasmota#417]
Would it be possible to send an Offline message to the old topic when TOPIC is changed, before or just after changing TOPIC?

The reason being that when TOPIC is changed, the old topic is never set to Offline before the new TOPIC comes back online. So it looks like 2 devices are online, but only one is.

**Comment by arendst** [comment]
Sending an empty message with previous topic will be implemented in next release (unless there is a majority voting for just sending an offline message...)

**Comment by mrmin24** [comment]
Maybe a offline message and then a empty one?

**Comment by arendst** [comment]
I make it configurable by the user; either select Offline OR empty message ;-)

**Comment by mrmin24** [comment]
Haha, OK. Sorry for trouble.

I think you should add a donate button on your wiki😊

**Comment by mrmin24** [comment]
Tested v5.0.7

Thanks
