### ISSUE TITLE
How to flash Sonoff with FOCA board?

### ISSUE THREAD

**Issue by sommersohn** [arendst/Sonoff-Tasmota#4181]
Hi all, 

I bought 4 new Sonoff-basic devices recently. Tried the OTA update but it seems not to work with my newer device. So I asked my self if I could use my existing [FOCA](https://www.itead.cc/wiki/Foca) board. Can anyone tell me how this can work and how to wire it up?

**Comment by ascillato** [comment]
Your board provides 5v. The esp8266 uses 3.3

You will need to have an extra 3.3v to power your sonoff and then just connect tx, rx and gnd as explained in the wiki

**Comment by ascillato2** [comment]
If you need further assistant, remember that you can find us also in the Tasmota Chat. Thanks
