### ISSUE TITLE
RfRaw as default on restart

### ISSUE THREAD

**Issue by deliantwo** [arendst/Sonoff-Tasmota#4182]
**Have you look for this feature in other issues and in the wiki?**
Yes.

**Is your feature request related to a problem? Please describe.**
I cannot set the rf bridge to start with Portisch firmware support. Since I need it with some socket that are not supported by the iTead firmware and the codes are different by design I'd like the rf bridge to be in the RfRaw mode ( if not I have to duplicate the sensors in homeassistant one listening to default iTead codes and the other to the RfRaw ones)

**Describe the solution you'd like**
a field to specify if the bridge should start with RfRaw 0 or RfRaw 1

**Describe alternatives you've considered**
Use homeassistant to intercept rf bridge LWT online and send the RfRaw 1 to it

**Comment by arendst** [comment]
Workaround: Use a local bridge rule to be executed at restart

**Comment by ascillato2** [comment]
Closing issue as has been addressed.

**Comment by deliantwo** [comment]
Thank you  @arendst for the hint!
Sorry to reopen but I would like to share the command I've used, for anyone looking for a solution to the same problem:

```Rule1 on system#boot do RfRaw 1 endon```

Thank you again!

**Comment by Jason2866** [comment]
For sending RfRaw commands the bridge can be in modus Rfraw 0.
If you send a Rfraw command it will do it and will stay in Rfraw 1

**Comment by fabito** [comment]
I tried the @deliantwo rule but something seems to be setting `RfRaw 0` after the rule executes. Check my init log:

```
00:00:04 DNS: Initialized
00:00:04 HTP: Web server active on /home/office/rf-bridge-3518.local with IP address 192.168.0.106
00:00:04 MQT: Attempting connection...
00:00:06 MQT: Connected
00:00:06 MQT: tele/home/office/rf-bridge/LWT = Online (retained)
00:00:06 MQT: cmnd/home/office/rf-bridge/POWER = 
00:00:06 MQT: tele/home/office/rf-bridge/INFO1 = {"Module":"Sonoff Bridge","Version":"6.3.0","FallbackTopic":"DVES_B2ADBE","GroupTopic":"sonoffs"}
13:34:04 MQT: tele/home/office/rf-bridge/INFO2 = {"WebServerMode":"Admin","Hostname":"/home/office/rf-bridge-3518","IPAddress":"192.168.0.106"}
13:34:04 MQT: tele/home/office/rf-bridge/INFO3 = {"RestartReason":"Software/System restart"}
13:34:04 RUL: SYSTEM#BOOT performs "RfRaw 1"
13:34:04 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"ON"}
13:34:04 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"ON"}
13:34:04 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"ON"}
13:34:04 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"ON"}
13:34:04 MQT: tele/home/office/rf-bridge/RESULT = {"RfRaw":{"Data":"AAA055"}}
13:34:04 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"OFF"}
```

Any idea on what could be happening ?

**Comment by ascillato** [comment]
Please, try the command weblog 4 in order to have more debug information. Then, restart your device. You will see now some new log lines with SRC: something, that points out where the command is comming from. Seems to me that before rfraw 0 you will hace SRC: MQTT, meaning that you have retained messages in your broker and your broker is sending that command to your Tasmota. Please, try that. In the case that is retained message, change your config in your home automation software for retain to false and you will have to delete the broker database. Fastest way is to uninstall and install mosquitto again.

**Comment by fabito** [comment]
Hi @ascillato ,

Here is the detailed init log:

```
15:38:33 MQT: tele/home/office/rf-bridge/INFO3 = {"RestartReason":"Software/System restart"}
15:38:33 HTP: Main Menu
15:38:33 RUL: SYSTEM#BOOT performs "RfRaw 1"
15:38:33 SRC: Rule
15:38:33 RSL: Received Topic /RfRaw, Data Size 1, Data 1
15:38:33 RSL: Group 0, Index 1, Command RFRAW, Data 1
15:38:33 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"ON"}
15:38:33 SRC: MQTT
15:38:33 RSL: Received Topic cmnd/home/office/rf-bridge/RfRaw, Data Size 170, Data AA B0 4C 04 08 136A 0276 010E 1360 38192A192A1A1A19292A1A19292929292A19292A1929292A1A1A1A192A1A1929292A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A192A19292A192A1A19292A1929 55
15:38:33 RSL: Group 0, Index 1, Command RFRAW, Data AA B0 4C 04 08 136A 0276 010E 1360 38192A192A1A1A19292A1A19292929292A19292A1929292A1A1A1A192A1A1929292A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A192A19292A192A1A19292A1929 55
15:38:33 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"ON"}
15:38:33 SRC: MQTT
15:38:33 RSL: Received Topic cmnd/home/office/rf-bridge/Backlog, Data Size 189, Data RfRaw 1; RfRaw AA B0 4A 03 14 026C 010E 137E F00110011010100101101001010101011001011001011001101001101010010101101010101010100110101010101010101001101010100101011001101010010102 55; RfRaw 0
15:38:33 RSL: Group 0, Index 1, Command BACKLOG, Data RfRaw 1; RfRaw AA B0 4A 03 14 026C 010E 137E F00110011010100101101001010101011001011001011001101001101010010101101010101010100110101010101010101001101010100101011001101010010102 55; RfRaw 0
15:38:33 SRC: Backlog
15:38:33 RSL: Received Topic /RfRaw, Data Size 1, Data 1
15:38:33 RSL: Group 0, Index 1, Command RFRAW, Data 1
15:38:33 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"ON"}
15:38:33 SRC: Backlog
15:38:33 RSL: Received Topic /RfRaw, Data Size 165, Data AA B0 4A 03 14 026C 010E 137E F00110011010100101101001010101011001011001011001101001101010010101101010101010100110101010101010101001101010100101011001101010010102 55
15:38:33 RSL: Group 0, Index 1, Command RFRAW, Data AA B0 4A 03 14 026C 010E 137E F00110011010100101101001010101011001011001011001101001101010010101101010101010100110101010101010101001101010100101011001101010010102 55
15:38:33 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"ON"}
15:38:33 MQT: tele/home/office/rf-bridge/RESULT = {"RfRaw":{"Data":"AAA055"}}
15:38:34 SRC: Backlog
15:38:34 RSL: Received Topic /RfRaw, Data Size 1, Data 0
15:38:34 RSL: Group 0, Index 1, Command RFRAW, Data 0
15:38:34 MQT: stat/home/office/rf-bridge/RESULT = {"RfRaw":"OFF"}
15:38:34 SER: Received A0 55
15:38:34 HTP: Console
```
`SRC` is Backlog not MQTT.
Seems like messages are being retained. 
I've disabled it. Trying to wipe out mosquitto now.

**Comment by fabito** [comment]
Thanks @ascillato , clearing the topics solved the problem!

**Comment by ascillato** [comment]
The backlog is a consecuence of the previous SRC: MQTT that have the backlog command. So, it is indeed a retained message.

If you use home assistant, please use the config as explained in the Tasmota wiki (retain: false)
Retain to true is meant for other type of automations
