### ISSUE TITLE
Sonoff RF remote options?

### ISSUE THREAD

**Issue by mihalski** [arendst/Sonoff-Tasmota#419]
Sorry to treat this like a forum, but AFAIK this is the biggest community of Sonoff users on the internet.

It is unclear to me if the Sonoff RF can only be controlled by the remote provided by Itead or if there are other, programmable ways to control it. Does anyone here have any experience with this?

**Comment by ecsfang** [comment]
Hi @mihalski!
Just a humble nudge - have you seen https://groups.google.com/forum/#!forum/sonoffusers?
This is a forum for Sonoff-users and should be used to discuss ideas etc :)
Cheers,
Thomas

**Comment by mihalski** [comment]
Thank you! That's great. Will check it out.
