### ISSUE TITLE
Sonoff RF starts blinking after button press

### ISSUE THREAD

**Issue by MGKQB** [arendst/Sonoff-Tasmota#4194]
I just flashed my first Sonoff RF. Everything works fine when I remote control the Sonoff RF.

but when I press the button (I thought pressing the button ONCE will trigger the switch on and off) the Sonoff RF goes crazy and starts turning on and off all the time. I am not really in the mood for a light show on my desk lamp though...

i soldered a bridge to be able to flash like described in the wiki and left it in, could that be the reason?

**Comment by ascillato** [comment]
Which button? from the rf control or the one in the board.

Besides that we really need you to complete the troubleshooting template to have information to properly help you and not guessing.

**Comment by MGKQB** [comment]
the button on the Sonoff - I think the Sonoff RF has only one button? 
I don't have a remote (yet).

i was just collecting all the information (will post asap), was just wondering if that is a known issue.

**Comment by ascillato** [comment]
Not a known issue.

Seems to be a misconfiguration or a broken pullup. 

Provide also the output of the console and please use weblog 4 in order to have more debug information

**Comment by MGKQB** [comment]
Make sure these boxes are checked [x] before submitting your issue - Thank you!

x Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
x Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
x Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
x Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
 Hardware used : Sonoff RF (no remote, just the switch)
 Provide the output of command status 0 in steady state:
`18:43:31 CMD: state 
18:43:31 RSL: RESULT = {"Time":"2018-10-28T18:43:31","Uptime":"0T00:33:14","Vcc":3.116,"POWER":"ON","Wifi":{"AP":1,"SSId":"MnM-Haus","RSSI":100,"APMac":"F0:7F:06:81:43:64"}}
18:43:33 CMD: status 0
18:43:33 RSL: STATUS = {"Status":{"Module":2,"FriendlyName":["Sonoff-RF-1"],"Topic":"sonoff","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
18:43:33 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.1.3/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:33:16","StartupUTC":"2018-10-28T17:10:17","Sleep":0,"BootCount":16,"SaveCount":101,"SaveAddress":"F7000"}}
18:43:33 RSL: STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-10-28T17:08:20","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
18:43:33 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MnM-Haus",""],"TelePeriod":300,"SetOption":["00008001","55818000","00000000"]}}
18:43:33 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":440,"Free":560,"Heap":17,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","1F002590","24000010","00000096","00000000"]}}
18:43:33 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff-7919","IPAddress":"192.168.21.21","Gateway":"192.168.21.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.21.1","Mac":"DC:4F:22:2D:9E:EF","Webserver":2,"WifiConfig":1}}
18:43:33 RSL: STATUS7 = {"StatusTIM":{"UTC":"Sun Oct 28 17:43:33 2018","Local":"Sun Oct 28 18:43:33 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"07:11","Sunset":"16:54"}}
18:43:33 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-10-28T18:43:33"}}
18:43:33 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-10-28T18:43:33","Uptime":"0T00:33:16","Vcc":3.116,"POWER":"ON","Wifi":{"AP":1,"SSId":"MnM-Haus","RSSI":100,"APMac":"F0:7F:06:81:43:64"}}}`

**Comment by ascillato** [comment]
Provide also the output of the console and please use weblog 4 in order to have more debug information

**Comment by MGKQB** [comment]
18:45:22 CMD: weblog 4
18:45:22 RSL: RESULT = {"WebLog":4}
18:45:22 CFG: Saved to flash at F6, Count 102, Bytes 3584
18:45:27 APP: Button1 multi-press 1
18:45:28 SRC: Button
18:45:28 RSL: RESULT = {"POWER":"OFF"}
18:45:28 RSL: POWER = OFF
18:45:28 APP: Button1 multi-press 1
18:45:28 CFG: Saved to flash at F5, Count 103, Bytes 3584
18:45:29 SRC: Button
18:45:29 RSL: RESULT = {"POWER":"ON"}
18:45:29 RSL: POWER = ON
18:45:29 APP: Button1 multi-press 1
18:45:29 CFG: Saved to flash at F4, Count 104, Bytes 3584
18:45:30 SRC: Button
18:45:30 RSL: RESULT = {"POWER":"OFF"}
18:45:30 RSL: POWER = OFF
18:45:30 APP: Button1 multi-press 1
18:45:30 CFG: Saved to flash at FB, Count 105, Bytes 3584
18:45:30 SRC: Button
18:45:30 RSL: RESULT = {"POWER":"ON"}
18:45:30 RSL: POWER = ON
18:45:31 APP: Button1 multi-press 1
18:45:31 SRC: Button
18:45:31 RSL: RESULT = {"POWER":"OFF"}
18:45:31 RSL: POWER = OFF
18:45:31 APP: Button1 multi-press 1
18:45:32 SRC: Button
18:45:32 RSL: RESULT = {"POWER":"ON"}
18:45:32 RSL: POWER = ON
18:45:32 APP: Button1 multi-press 1
18:45:32 CFG: Saved to flash at FA, Count 106, Bytes 3584
18:45:33 SRC: Button
18:45:33 RSL: RESULT = {"POWER":"OFF"}
18:45:33 RSL: POWER = OFF
18:45:33 APP: Button1 multi-press 1
18:45:33 CFG: Saved to flash at F9, Count 107, Bytes 3584
18:45:33 SRC: Button
18:45:33 RSL: RESULT = {"POWER":"ON"}
18:45:33 RSL: POWER = ON
18:45:34 WIF: Checking connection...
18:45:34 WIF: Connected
18:45:35 RSL: POWER = ON
18:45:35 APP: Button1 multi-press 1
18:45:35 CFG: Saved to flash at F8, Count 108, Bytes 3584
18:45:36 SRC: Button
18:45:36 RSL: RESULT = {"POWER":"OFF"}
18:45:36 RSL: POWER = OFF
18:45:36 APP: Button1 multi-press 1
18:45:36 CFG: Saved to flash at F7, Count 109, Bytes 3584
18:45:37 SRC: Button
18:45:37 RSL: RESULT = {"POWER":"ON"}
18:45:37 RSL: POWER = ON
18:45:37 APP: Button1 multi-press 1
18:45:37 SRC: Button
18:45:37 RSL: RESULT = {"POWER":"OFF"}
18:45:37 RSL: POWER = OFF
18:45:38 APP: Button1 multi-press 1
18:45:38 SRC: Button
18:45:38 RSL: RESULT = {"POWER":"ON"}
18:45:38 RSL: POWER = ON
18:45:38 CFG: Saved to flash at F6, Count 110, Bytes 3584
18:45:38 APP: Button1 multi-press 1
18:45:39 SRC: Button
18:45:39 RSL: RESULT = {"POWER":"OFF"}
18:45:39 RSL: POWER = OFF
18:45:39 APP: Button1 multi-press 1
18:45:39 CFG: Saved to flash at F5, Count 111, Bytes 3584
18:45:40 SRC: Button
18:45:40 RSL: RESULT = {"POWER":"ON"}
18:45:40 RSL: POWER = ON
18:45:40 APP: Button1 multi-press 1
18:45:40 CFG: Saved to flash at F4, Count 112, Bytes 3584
18:45:40 SRC: Button
18:45:40 RSL: RESULT = {"POWER":"OFF"}
18:45:40 RSL: POWER = OFF
18:45:41 APP: Button1 multi-press 1
18:45:41 RSL: STATE = {"Time":"2018-10-28T18:45:41","Uptime":"0T00:35:24","Vcc":3.116,"POWER":"OFF","Wifi":{"AP":1,"SSId":"MnM-Haus","RSSI":94,"APMac":"F0:7F:06:81:43:64"}}
18:45:41 SRC: Button
18:45:41 RSL: RESULT = {"POWER":"ON"}
18:45:41 RSL: POWER = ON
18:45:41 APP: Button1 multi-press 1
18:45:42 SRC: Button
18:45:42 RSL: RESULT = {"POWER":"OFF"}
18:45:42 RSL: POWER = OFF
18:45:42 APP: Button1 multi-press 1
18:45:42 CFG: Saved to flash at FB, Count 113, Bytes 3584
18:45:43 SRC: Button
18:45:43 RSL: RESULT = {"POWER":"ON"}
18:45:43 RSL: POWER = ON
18:45:43 APP: Button1 multi-press 1
18:45:43 CFG: Saved to flash at FA, Count 114, Bytes 3584
18:45:43 SRC: Button
18:45:43 RSL: RESULT = {"POWER":"OFF"}
18:45:43 RSL: POWER = OFF
18:45:44 APP: Button1 multi-press 1
18:45:44 CMD: Status 0
18:45:44 SRC: WebConsole from 192.168.1.226
18:45:44 RSL: Received Topic /Status, Data Size 1, Data 0
18:45:44 RSL: Group 0, Index 1, Command STATUS, Data 0
18:45:44 RSL: STATUS = {"Status":{"Module":2,"FriendlyName":["Sonoff-RF-1"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
18:45:44 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.1.3/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:35:27","StartupUTC":"2018-10-28T17:10:17","Sleep":0,"BootCount":16,"SaveCount":114,"SaveAddress":"FA000"}}
18:45:44 RSL: STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-10-28T17:08:20","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
18:45:44 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MnM-Haus",""],"TelePeriod":300,"SetOption":["00008001","55818000","00000000"]}}
18:45:44 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":440,"Free":560,"Heap":17,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","1F002590","24000010","00000096","00000000"]}}
18:45:44 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff-7919","IPAddress":"192.168.21.21","Gateway":"192.168.21.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.21.1","Mac":"DC:4F:22:2D:9E:EF","Webserver":2,"WifiConfig":1}}
18:45:44 RSL: STATUS7 = {"StatusTIM":{"UTC":"Sun Oct 28 17:45:44 2018","Local":"Sun Oct 28 18:45:44 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"07:11","Sunset":"16:54"}}
18:45:44 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-10-28T18:45:44"}}
18:45:44 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-10-28T18:45:44","Uptime":"0T00:35:27","Vcc":3.118,"POWER":"OFF","Wifi":{"AP":1,"SSId":"MnM-Haus","RSSI":100,"APMac":"F0:7F:06:81:43:64"}}}
18:45:44 APP: Button1 multi-press 2
18:45:45 CFG: Saved to flash at F9, Count 115, Bytes 3584
18:45:45 SRC: Button
18:45:45 RSL: RESULT = {"POWER":"ON"}
18:45:45 RSL: POWER = ON
18:45:45 APP: Button1 multi-press 1
18:45:46 CFG: Saved to flash at F8, Count 116, Bytes 3584
18:45:46 SRC: Button
18:45:46 RSL: RESULT = {"POWER":"OFF"}
18:45:46 RSL: POWER = OFF
18:45:46 APP: Button1 multi-press 1
18:45:47 SRC: Button
18:45:47 RSL: RESULT = {"POWER":"ON"}
18:45:47 RSL: POWER = ON
18:45:47 APP: Button1 multi-press 1
18:45:47 SRC: Button
18:45:47 RSL: RESULT = {"POWER":"OFF"}
18:45:47 RSL: POWER = OFF
18:45:48 APP: Button1 multi-press 1
18:45:48 CFG: Saved to flash at F7, Count 117, Bytes 3584
18:45:48 SRC: Button
18:45:48 RSL: RESULT = {"POWER":"ON"}
18:45:48 RSL: POWER = ON
18:45:48 APP: Button1 multi-press 1
18:45:49 CFG: Saved to flash at F6, Count 118, Bytes 3584
18:45:49 SRC: Button
18:45:49 RSL: RESULT = {"POWER":"OFF"}
18:45:49 RSL: POWER = OFF
18:45:49 CMD: Status 0
18:45:49 SRC: WebConsole from 192.168.1.226
18:45:49 RSL: Received Topic /Status, Data Size 1, Data 0
18:45:49 RSL: Group 0, Index 1, Command STATUS, Data 0
18:45:49 RSL: STATUS = {"Status":{"Module":2,"FriendlyName":["Sonoff-RF-1"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
18:45:49 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.1.3/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:35:32","StartupUTC":"2018-10-28T17:10:17","Sleep":0,"BootCount":16,"SaveCount":118,"SaveAddress":"F6000"}}
18:45:49 RSL: STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-10-28T17:08:20","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
18:45:49 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MnM-Haus",""],"TelePeriod":300,"SetOption":["00008001","55818000","00000000"]}}
18:45:49 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":440,"Free":560,"Heap":17,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","1F002590","24000010","00000096","00000000"]}}
18:45:49 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff-7919","IPAddress":"192.168.21.21","Gateway":"192.168.21.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.21.1","Mac":"DC:4F:22:2D:9E:EF","Webserver":2,"WifiConfig":1}}
18:45:49 RSL: STATUS7 = {"StatusTIM":{"UTC":"Sun Oct 28 17:45:49 2018","Local":"Sun Oct 28 18:45:49 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"07:11","Sunset":"16:54"}}
18:45:49 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-10-28T18:45:49"}}
18:45:49 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-10-28T18:45:49","Uptime":"0T00:35:32","Vcc":3.116,"POWER":"OFF","Wifi":{"AP":1,"SSId":"MnM-Haus","RSSI":100,"APMac":"F0:7F:06:81:43:64"}}}

**Comment by MGKQB** [comment]
the blinking even survives a restart. I had to unplug it for it to stop blinking.

i have a second unit here, starting to solder the headers now.

Is it ok to keep the solder bridge in?

**Comment by ascillato** [comment]
If you have solder just connectors or wires, will not affect your sonoff.

But in your device seems to be a hardware problem. Did you take out the pullup resistor? 

Try to add another 10k pullup resistor between gpio0 and 3.3v

**Comment by MGKQB** [comment]
ok, removing the solder bridge solved the issue. This might be useful information for the wiki, I added it to the Sonoff RF page.

Thanks, the comment about the pullup made me think about the additional connection - lots of internet pages state the additional GPIO0 connection can stay and does not matter, that is obviously incorrect.
I also tested my second RF unit, same behavior.
