### ISSUE TITLE
Request - Non-Addressable RGB LED Strip support

### ISSUE THREAD

**Issue by bl8rnr** [arendst/Sonoff-Tasmota#42]
First off I would like to say; great work on this.

I was wondering if it would be possible to add support for non-addressable LED strips with the Sonoff LED module. 

Maybe MQTT JSON compatible as:

https://github.com/corbanmailloux/esp-mqtt-rgb-led

Thanks again for the great work.

**Comment by ascillato2** [comment]
Old issue. Already Implemented. Closing
