### ISSUE TITLE
can you help me with a rule/Commands ?

### ISSUE THREAD

**Issue by mahdy89** [arendst/Sonoff-Tasmota#4200]
please i need to help i really cannot understand the tutorial
i want my sonoff basic when turn on to turn off after 2 seconds and then turn on  and then turn of for 2 second
can you help me with setting up this rules/Commands?
can you help me with writing the exact rules i should put? thank you a lot

**Comment by ascillato** [comment]
Go to the Tasmota console and type:

`pulsetime1 20`

If you need further assistance, please find us in the Tasmota Chat at https://discord.gg/Ks2Kzd4

**Comment by wongnam** [comment]
no need rule, just use BlinkCount, BlinkTime and send command to sonoff is BLINK instead of ON or OFF.

https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by ascillato2** [comment]
Closing issue as has been answered.

Thanks !
