### ISSUE TITLE
Sonoff Basic with PIR, Wall Switch, ANd Door Contact?

### ISSUE THREAD

**Issue by CazMan** [arendst/Sonoff-Tasmota#4201]
Hi,
I am new to Tasmota (Great firmware by the way - flashing all my ESP devices with Tasmota now) and was trying to configure a Sonoff Basic to use 
1) Wall switch (Ground, GPIO14)
     -This should turn the relay on/off (Relay post MQTT message)
2) Door contact (Serial IN) 
    -This should post a MQTT topic 
3) PIR (Serial OUT)
    -This should post a MQTT topic

I found that setting GPIO4 as Relay2 gives me 3 topics (POWER1,POWER2,POWER3), and controls the the light relay as expected...

But as soon as the MQTT server is offline the PIR (Switch3) toggles Relay1 - I suspect this is because there is no relay 3 for it to control)

Is there a better way of doing this? From what I read, possibly setting the switchtopic 1, and then a rule to turn on relay 1 with switch 1?

**Comment by ascillato** [comment]
Hi,

duplicated issue.

https://github.com/arendst/Sonoff-Tasmota/issues/4187
