### ISSUE TITLE
DHT11 in home assistant

### ISSUE THREAD

**Issue by Bashface** [arendst/Sonoff-Tasmota#4202]
here is my tasmota log: 

`07:14:22 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:14:22","Uptime":"0T00:06:24","Vcc":3.146,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:14:22 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:14:22","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:14:32 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:14:32","Uptime":"0T00:06:34","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:14:32 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:14:32","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:14:42 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:14:42","Uptime":"0T00:06:44","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:14:42 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:14:42","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:14:52 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:14:52","Uptime":"0T00:06:54","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:14:52 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:14:52","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:15:02 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:15:02","Uptime":"0T00:07:04","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:15:02 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:15:02","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:15:12 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:15:12","Uptime":"0T00:07:14","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:15:12 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:15:12","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:15:22 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:15:22","Uptime":"0T00:07:24","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:15:22 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:15:22","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:15:32 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:15:32","Uptime":"0T00:07:34","Vcc":3.146,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:15:32 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:15:32","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:15:42 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:15:42","Uptime":"0T00:07:44","Vcc":3.145,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:15:42 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:15:42","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:15:52 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:15:52","Uptime":"0T00:07:54","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:15:52 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:15:52","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:16:02 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:16:02","Uptime":"0T00:08:04","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:16:02 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:16:02","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:16:12 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:16:12","Uptime":"0T00:08:14","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:16:12 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:16:12","DHT11":{"Temperature":24.0,"Humidity":42.0},"TempUnit":"C"}
07:16:22 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:16:22","Uptime":"0T00:08:24","Vcc":3.145,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:16:22 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:16:22","DHT11":{"Temperature":24.0,"Humidity":41.0},"TempUnit":"C"}
07:16:32 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:16:32","Uptime":"0T00:08:34","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:16:32 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:16:32","DHT11":{"Temperature":24.1,"Humidity":42.0},"TempUnit":"C"}
07:16:42 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:16:42","Uptime":"0T00:08:44","Vcc":3.145,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:16:42 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:16:42","DHT11":{"Temperature":24.0,"Humidity":41.0},"TempUnit":"C"}
07:16:52 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:16:52","Uptime":"0T00:08:54","Vcc":3.143,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:16:52 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:16:52","DHT11":{"Temperature":24.0,"Humidity":41.0},"TempUnit":"C"}
07:17:02 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:17:02","Uptime":"0T00:09:04","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:17:02 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:17:02","DHT11":{"Temperature":24.0,"Humidity":41.0},"TempUnit":"C"}
07:17:12 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:17:12","Uptime":"0T00:09:14","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:17:12 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:17:12","DHT11":{"Temperature":24.0,"Humidity":41.0},"TempUnit":"C"}
07:17:22 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:17:22","Uptime":"0T00:09:24","Vcc":3.146,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:17:22 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:17:22","DHT11":{"Temperature":24.0,"Humidity":41.0},"TempUnit":"C"}
07:17:32 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:17:32","Uptime":"0T00:09:34","Vcc":3.143,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:17:32 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:17:32","DHT11":{"Temperature":24.0,"Humidity":41.0},"TempUnit":"C"}
07:17:42 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:17:42","Uptime":"0T00:09:44","Vcc":3.145,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:17:42 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:17:42","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:17:52 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:17:52","Uptime":"0T00:09:54","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:17:52 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:17:52","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:17:58 APP: Serial logging disabled
07:18:02 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:18:02","Uptime":"0T00:10:04","Vcc":3.144,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:18:02 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:18:02","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:18:12 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:18:12","Uptime":"0T00:10:14","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:18:12 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:18:12","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:18:22 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:18:22","Uptime":"0T00:10:24","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:18:22 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:18:22","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:18:32 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:18:32","Uptime":"0T00:10:34","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:18:32 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:18:32","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:18:42 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:18:42","Uptime":"0T00:10:44","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:18:42 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:18:42","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:18:52 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:18:52","Uptime":"0T00:10:54","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:18:52 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:18:52","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:19:02 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:19:02","Uptime":"0T00:11:04","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:19:02 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:19:02","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:19:12 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:19:12","Uptime":"0T00:11:14","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:19:12 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:19:12","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:19:22 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:19:22","Uptime":"0T00:11:24","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":96,"APMac":"FC:EC:DA:38:8F:04"}}
07:19:22 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:19:22","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:19:32 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:19:32","Uptime":"0T00:11:34","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:19:32 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:19:32","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:19:42 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:19:42","Uptime":"0T00:11:44","Vcc":3.146,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:19:42 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:19:42","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:19:52 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:19:52","Uptime":"0T00:11:54","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:19:52 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:19:52","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:20:02 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:20:02","Uptime":"0T00:12:04","Vcc":3.146,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:20:02 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:20:02","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:20:12 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:20:12","Uptime":"0T00:12:14","Vcc":3.146,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:20:12 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:20:12","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:20:22 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:20:22","Uptime":"0T00:12:24","Vcc":3.145,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":96,"APMac":"FC:EC:DA:38:8F:04"}}
07:20:22 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:20:22","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:20:32 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:20:32","Uptime":"0T00:12:34","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:20:32 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:20:32","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:20:42 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:20:42","Uptime":"0T00:12:44","Vcc":3.147,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:20:42 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:20:42","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:20:52 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:20:52","Uptime":"0T00:12:54","Vcc":3.145,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":98,"APMac":"FC:EC:DA:38:8F:04"}}
07:20:52 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:20:52","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:21:02 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:21:02","Uptime":"0T00:13:04","Vcc":3.144,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:21:02 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:21:02","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:21:12 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:21:12","Uptime":"0T00:13:14","Vcc":3.148,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:21:12 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:21:12","DHT11":{"Temperature":24.1,"Humidity":41.0},"TempUnit":"C"}
07:21:22 MQT: kidsbedmain/STATE = {"Time":"2018-10-29T07:21:22","Uptime":"0T00:13:24","Vcc":3.146,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TazSpace","RSSI":100,"APMac":"FC:EC:DA:38:8F:04"}}
07:21:22 MQT: kidsbedmain/SENSOR = {"Time":"2018-10-29T07:21:22","DHT11":{"Temperature":24.2,"Humidity":41.0},"TempUnit":"C"}`

My home assistant config:

   platform: mqtt
    state_topic: 'tele/kidsbedmain/SENSOR'
    name: 'Kids Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.DHT11.Temperature }}'
  - platform: mqtt
    state_topic: 'tele/kidsbedmain/SENSOR'
    name: 'Kids Bedroom Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.DHT11.Humidity }}'

**Comment by ascillato** [comment]
Please, follow the troubleshooting template and explain what is your issue.

Please, also use the information provided in the wiki.

Sorry, Closing as incomplete issue.
