### ISSUE TITLE
HTTP request for Sonoff Dual - Seperate Power on/off

### ISSUE THREAD

**Issue by FabianHM** [arendst/Sonoff-Tasmota#421]
I need help to set my two Channels of the Sonoff Dual by HTTP Requets.
For the other Components I use: 
http://sonoff/cm?cmnd=Power%20On

But the Dual has two seperate relais. How can I set them seperate?
Thanks for help
Fabian

**Comment by davidelang** [comment]
power1 on
power2 on
k

**Comment by FabianHM** [comment]
Thanks, perfekt and so simple.
