### ISSUE TITLE
Add MQTT GROUP NAME as part of configuration screen

### ISSUE THREAD

**Issue by mosaid88** [arendst/Sonoff-Tasmota#4210]
Add MQTT GROUP NAME as part of configuration screen. 
To allow easier grouping for multiple devices, without having to re-flash the devices.

**Comment by lalo-uy** [comment]
You can set the group name via MQTT

mosquito_pub  -t   myhouse/living/GroupTopic  -m "east_area"

**Comment by ascillato** [comment]
And as @lalo-uy has said, you can also set using commands from the Tasmota console:
`GroupTopic  east_area`

See wiki at commands for more information :https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#mqtt-specific
