### ISSUE TITLE
No such file or directory esp-knx-ip.h or sonoff_post.h

### ISSUE THREAD

**Issue by PETEIOT** [arendst/Sonoff-Tasmota#4212]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**Describe the bug**

In file included from C:\Users\Chris\Documents\Arduino\Sonoff-Tasmota-development\sonoff\sonoff.ino:36:0:

sketch\sonoff_post.h:41:24: fatal error: esp-knx-ip.h: No such file or directory
![esppic](https://user-images.githubusercontent.com/35778227/47680586-d7f71a00-db8c-11e8-86df-c10bec9b750b.JPG)

 #include <esp-knx-ip.h>
                        ^
compilation terminated.

exit status 1
Error compiling for board Generic ESP8266 Module.

I 

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [ x] _Searched the problem in issues and in the wiki_
- [ x] _Hardware used_ : 
- [ ] _Development/Compiler/Upload tools used_ :
- [ x] _Provide the output of command_``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**To Reproduce**
_Steps to reproduce the behavior:_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
That means that you have missing files and missing libraries.

Please, download all again and install as explained in the wiki 

Tasmota is compiling fine.
