### ISSUE TITLE
HX711 web ui & xdrv_17_rcswitch.ino

### ISSUE THREAD

**Issue by mike2nl** [arendst/Sonoff-Tasmota#4213]
**Describe the bug**
_A clear and concise description of what the bug is._

- 1:
I don't know is that a bug (it's a big word more a wrong text) or not.
Is that right or see i something were i'm wrong?
Please see Figure 1 about the web ui text for the HX711 at the TX20.

Figure 1 is taken here (bottom on that site):
https://github.com/arendst/Sonoff-Tasmota/tree/development/sonoff

Figure 1:
![hx711](https://user-images.githubusercontent.com/5562918/47699062-f9e6b000-dc11-11e8-8c24-b88a08f67c4f.PNG)

- 2:
The version date in the xdrv_17_rcswitch.ino file looks old ;-).
-- Copyright (C) 2017  Theo Arends

I saw it because i updated the Tasmota_Supported_Sensors xlsx sheet to version 1.0.0.6.
Name new: Tasmota_Supported_Sensors_v1.0.0.6.xlsx

**Comment by andrethomas** [comment]
The comment you see is just the comment which was used when the git commit was done, so if other files were changed during the same commit the same message will be listed on all the files which were changed.

> Copyright (C) 2017 Theo Arends

Theo has been known to do a little time travel every now and then...

**Comment by ascillato2** [comment]
@mike2nl 

Please, do the PR for Theo to review it. Thanks

**Comment by arendst** [comment]
@mike2nl I'm back in da house and will push an update soon.

Thx so far ;-)

**Comment by andrethomas** [comment]
@mike2nl 

Seeeeeee: ?
![image](https://user-images.githubusercontent.com/470015/47721997-10185e80-dc5a-11e8-936d-9866d8f4fbcd.png)

TIME TRAVELER!!
