### ISSUE TITLE
Show current time and date in the status web page

### ISSUE THREAD

**Issue by mellado** [arendst/Sonoff-Tasmota#4225]
I would love to check easily the correct date and time of my devices by just entering in the main status web page.

Thanks for this great software.

**Comment by ascillato** [comment]
You have that information in the console and in the information menu

**Comment by reloxx13** [comment]
you could do it with tasmoadmin

looks like that:

![grafik](https://user-images.githubusercontent.com/14855001/47817443-f52b1480-dd55-11e8-8b0c-edfaebdb9d8e.png)

**Comment by ascillato** [comment]
:+1:

**Comment by mellado** [comment]
The current time is not in the Information page.

**Comment by ascillato** [comment]
You are right. It is in the console.
