### ISSUE TITLE
Analog0 written in the GUI?

### ISSUE THREAD

**Issue by jascdk** [arendst/Sonoff-Tasmota#4227]
Hi.

After updating to the latest release, I am seeing this "Analaog0" in the top of my GUI buttons. What is it for?

**Comment by ascillato** [comment]
If you use sonoff_sensors.bin you will have enabled the Analog A0 pin.

If you use sonoff.bin you will have internal VCC measurements instead.

Please, for general questions, are better and faster addresed in the Tasmota Chat.

**Comment by fragolinux** [comment]
is there a way to rename that "analog0" to "LDR", for example? Thanks

**Comment by ascillato** [comment]
Sorry, there isn't. That is a job for your home automation software.
