### ISSUE TITLE
Energy Meter Device with S0 input

### ISSUE THREAD

**Issue by Tommy-LSA** [arendst/Sonoff-Tasmota#4230]
Because my last Request was closed without understanding the question - 2nd try. I don't asked for transmitting Number of pulses over MQTT!

I ask for:

Input: S0 Pulse

SENSOR Output:
{
	"Time": "2018-10-31T14:38:39",
	"ENERGY": {
		"TotalStartTime": "2018-10-31T07:57:44",
		"Total": 0.594,
		"Yesterday": 0.031,
		"Today": 0.530,
		"Period": 0,
		"Power": 4,
		"ApparentPower": 11,
		"ReactivePower": 10,
		"Factor": 0.36,
		"Voltage": 220,
		"Current": 0.048
	}
}

**Comment by ascillato2** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/4228
