### ISSUE TITLE
Setting up MQTT client, How to extract JSON data?

### ISSUE THREAD

**Issue by ilya89vet** [arendst/Sonoff-Tasmota#4231]
Please help to configure MQTT client.
I want to fully control and manage my device via MQTT! I was able to get the relay on / off, but I do not understand what you need to register in The JSON Patch to obtain data from the sensors. Please someone give examples of settings MQTT client, it is desirable to attach the screenshots.
Is it possible to manage timers via MQTT?

**Comment by andrethomas** [comment]
To use the json data you will need HA software - So either home assistant,  or node-red, or something else you like.

See https://github.com/arendst/Sonoff-Tasmota/wiki/Tutorials

Also, on the right-hand side, there is an entire section dedicated to home assistant software.

![image](https://user-images.githubusercontent.com/470015/47800688-79b96b00-dd35-11e8-812b-76fe830d5d18.png)

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered. Next time only open an issue if there is a bug or problem with the Tasmota firmware. Issues are not intended for generic questions such as the one you made.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
