### ISSUE TITLE
SONOFF 4 CH WIFI WIRELESS SWITCH INCHING/SELF-LOCKING/INTER-LOCKING MODE support?

### ISSUE THREAD

**Issue by octa22** [arendst/Sonoff-Tasmota#425]
It would be nice if 4 CH WiFi Wireless Switch Inching/Self-Locking/Inter-Locking Mode is supported too.
https://www.itead.cc/4-channel-wifi-wireless-switch.html

It is discontinued product but Itead does not offer similar product right now if you want to control appliances with different voltage (e.g. 25V AC for sprinklers)

**Comment by arendst** [comment]
Try module 4 Channel.
