### ISSUE TITLE
Command FrequencySet malfunction

### ISSUE THREAD

**Issue by hamwong** [arendst/Sonoff-Tasmota#4256]
I tried on firmware 6.2.1.18 & 6.3.0.2 on Huafan SS and Sonoff Pow with command "FrequencySet " all result as "Command":"Unknown",  PowerSet, CurrentSet, VoltageSet work as expected

18:28:58 CMD: FrequencySet
18:28:58 MQT: stat/Pow_BedR_Plug1/RESULT = {"Command":"Unknown"}
18:33:57 CMD: PowerSet
18:33:58 MQT: stat/Pow_BedR_Plug1/RESULT = {"PowerSetCal":4650}
18:34:04 CMD: CurrentSet
18:34:04 MQT: stat/Pow_BedR_Plug1/RESULT = {"CurrentSetCal":3500}
18:35:00 CMD: VoltageSet
18:35:00 MQT: stat/Pow_BedR_Plug1/RESULT = {"VoltageSetCal":1522}

**Comment by andrethomas** [comment]
@hamwong 

The FrequencySet command should only work if a parameter is passed.

So for 50hz, you would need to issue the command
`FrequencySet 50`

**Comment by andrethomas** [comment]
Also, the POW/POW2 does not support frequency - I think it's only the Shelly 2 which will support this command.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
