### ISSUE TITLE
Automatic wifi router power control

### ISSUE THREAD

**Issue by treepleks** [arendst/Sonoff-Tasmota#4262]
If a Tasmota relay controls the power of my wifi router, I can imagine the following power saving mechanism:

1) my NAS periodically scan the LAN for the MAC adresses of the phones of the family. If no phone is there, it sends an MQTT message to cut power to the router.

2) the Tasmota device turns the router OFF  and detects that wifi is  disconnected. A rule triggers a specific AP mode where the Tasmota device switches it's wifi in AP mode with the same SSID/password it was using to connect to the router. It will remain like this until one of the phones connects to this AP (MAC address recognized). Then it powers the router, shit to wifi client mode and connects to the wifi that the router now provides. Back to normal.

I have scanned Tasmota doc and I do not see how this could be achieved. The only missing thing I think is a command that would turn Tasmota to AP mode and wait until one of the MAC adresses is detected.

Woul this be feasible? My router (4g router + unified LR AP) eats 30 watts.This would be a great transparent power saver for many users around the world I would assume.

T. Reepleks

**Comment by andrethomas** [comment]
I do not think this is feasible to implement within Tasmota firmware but it may be possible to do this with a second wemos/nodemcu board running custom firmware to pull one of the pins on the Tasmota driven device that powers your wifi gear.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
