### ISSUE TITLE
will parameters

### ISSUE THREAD

**Issue by or78rXxZ** [arendst/Sonoff-Tasmota#4275]
how do you set the mqtt will parameters
will topic
will message
will qos
will retain
thanks

**Comment by arendst** [comment]
You can't. 

It's all done automatically by Tasmota as ``tele/sonoff/LWT = Offline`` retained with qos 1 where ``tele/sonoff`` depends on your fulltopic definition.

**Comment by or78rXxZ** [comment]
i'll have to think on that a bit
thanks

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
