### ISSUE TITLE
WS2811

### ISSUE THREAD

**Issue by skatun** [arendst/Sonoff-Tasmota#4282]
WS2811 together with ws2812 is one of the most common ledstrip on the market. WS2811 runs on 12V and hence can normally be longer then the WS2812 which runs on 5V(due to power supply)

They both uses the neopixel library, however for some odd reason the ws2811 has the colors in grb order vs rgb for the ws2812.

For now I have done it on the Openhab side of the software to avoid problems when using TasmoAdmin and upgrading devises, because `USE_WS2812_CTYPE    NEO_GRB`  will be reset when upgrading the software.

I also use WS2812 strips so it would be nice to be able to seperate them in the server of  the device, i.e be able to select both WS2811 and WS2812 in the software.

**Comment by arendst** [comment]
Old issue. See #857 why.
