### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by marrobHD** [arendst/Sonoff-Tasmota#4285]
How can I get the counter value via mqtt? Exists any setting to reset the counter after e.g. 2 seconds?
Thanks for help

**Comment by ascillato** [comment]
Yes, please see commands in the wiki

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by marrobHD** [comment]
I cant find this in the wiki

**Comment by ascillato2** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#sensor

**Comment by ascillato2** [comment]
For general questions, please use the support chat. Github issues are for bug reporting and using the provided template. Thanks.

**Comment by marrobHD** [comment]
there is not declared mqtt and autoreset
