### ISSUE TITLE
Hardware Serial Bridge loses part of the response message

### ISSUE THREAD

**Issue by kockockockoc** [arendst/Sonoff-Tasmota#4300]
**~1 of 40 times I get broken message via hw serial bridge**

- [x] _Searched the problem in issues and in the wiki_: yes
- [x] _Hardware used_ :  Wemos D1 Mini <= Hardware Serial Bridge  9600 => Arduino
- [x] _Development/Compiler/Upload tools used_ : Upload FW via "Upgrade by file upload"
- [x] _If a pre-compiled release or development binary was used, which one?_ : pre-compiled release sonoff-sensors.bin (Sonoff-Tasmota v6.3.0)
- [x] _You have tried latest release or development binaries?_ : latest release
- [x] _Provide the output of command_``status 0`` : 

```
{"Status" {"Module":18,"FriendlyName" ["arduino_433"],"Topic":"arduino_433","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
{"StatusPRM":{"Baudrate":9600,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-sensors.bin","RestartReason":"External System","Uptime":"0T00:38:13","StartupUTC":"2018-11-06T21:11:53","Sleep":0,"BootCount":17,"SaveCount":45,"SaveAddress":"F7000"}}
{"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018-10-30T17:35:53","Boot":4,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
{"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["xxx",""],"TelePeriod":300,"SetOption":["00408009","55818000","00000000"]}}
{"StatusMEM":{"ProgramSize":516,"Free":484,"Heap":13,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3,"Features":["00000809","0FDEE794","0001A3A4","B7FFBFCC","00003BC0"]}}
```

My setup:
**Wemos D1 Mini <= (hw serial bridge) => Arduino (Serial0) <= (usb) => Arduino IDE Serial Monitor**

Wemos Module parameters:
TX GPIO1 Serial Out => 72 SerBr Rx  (the wire to Arduino Mega (Tx0))
RX GPIO3 Serial In => 71 SerBr Tx  (the wire to Arduino Mega (Rx0)

Arduino sketch very simple (concept):
```
void setup()
{
  Serial.begin(9600);
}
void loop()
{
  Serial.println("{\"s\": \"a\", \"d\": {\"conc_pm1_0_cf1\": 15, \"conc_pm2_5_cf1\": 21, \"conc_pm10_0_cf1\": 21, \"conc_pm1_0_amb\": 15, \"conc_pm2_5_amb\": 21, \"conc_pm10_0_amb\": 21, \"pm_ver\": 147, \"err_code\": 0}}");
  delay(3000);
}
```
**Expected behavior**
I see this printline in two places at the same time: Tasmota WebConsole (via hw serial bridge) and Arduino IDE Serial Monitor (via Serial-USB at arduino board)

I use SerialSend (text serial response messages) and ~1 of 40 times I get broken message via hw serial bridge:
```
Arduino IDE Serial Monitor (OK):
{"s": "a", "d": {"conc_pm1_0_cf1": 7, "conc_pm2_5_cf1": 15, "conc_pm10_0_cf1": 19, "conc_pm1_0_amb": 7, "conc_pm2_5_amb": 15, "conc_pm10_0_amb": 19, "pm_ver": 147, "err_code": 0}}

Tasmota WebConsole (Not OK):
01:49:08 MQT: tele/arduino_433/RESULT = {"SerialReceived":"
{"s": "a", "d": {"conc_pm1_0_cf1": 7, "conc_pm2_5_cf1": 15, "conc_pm10_0_cf1": 19, "conc_pm1_0_amb": 7, "conc_pm2_5_amb": 15, "conc_pm10_"}
```

It also happens like this:
```
at the end of the message in a different place:
01:47:53 MQT: tele/arduino_433/RESULT = {"SerialReceived":"
{"s": "a", "d": {"conc_pm1_0_cf1": 8, "conc_pm2_5_cf1": 14, "conc_pm10_0_cf1": 16, "conc_pm1_0_amb": 8, "conc_pm2_5_amb": 14, "conc_pm10_0_amb": 16, "pm_ver": 14"}

or in the middle of the message:
01:44:52 MQT: tele/arduino_433/RESULT = {"SerialReceived":"
{"s": "a", "d": {"conc_pm1_0_cf1": 7, "conc_pm2_5_cf1": 11, "conc_pm10_0_cf1": 14, "conc_pm1_0_amb": 7, "conc_pm2_5_amb": 11, "cver": 147, "err_code": 0}}"}
```
All this time there are no issue via Arduino IDE Serial Monitor.

The issue also persists when switching to "serial response messages is encoded as hex strings" (SerialSend4).
```
00:17:55 MQT: tele/arduino_433/RESULT = {"SerialReceived":
"7b2273223a202261222c202264223a207b22636f6e635f706d315f305f636631223a2031352c2022636f6e635f706d325f355f636631223a2032312c2022636f6e635f706d31305f305f636631223a2032312c2022636f6e635f706d315f305f616d62223a2031352c2022636f6e635f706d325f355f616d62223a2032312c206465223a20307d7d0d0a"}

(decoded):
{"s": "a", "d": {"conc_pm1_0_cf1": 15, "conc_pm2_5_cf1": 21, "conc_pm10_0_cf1": 21, "conc_pm1_0_amb": 15, "conc_pm2_5_amb": 21, de": 0}}
```

**Comment by ascillato** [comment]
Please, can you test again but using last Tasmota version from the development branch? Thanks.

**Comment by chaosmaster** [comment]
> TX GPIO1 Serial Out => 72 SerBr Rx (the wire to Arduino Mega (Tx0))
RX GPIO3 Serial In => 71 SerBr Tx (the wire to Arduino Mega (Rx0)

Why do you use TX as RX and vice versa?

@ascillato @arendst 
It seems serial_bridge doesn't use hardware-serial fallback:
https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/xdrv_08_serial_bridge.ino#L78

Could this possibly be related?

**Comment by kockockockoc** [comment]
@ascillato Yes, development branch (61985ca16bb98c58aa224006242a070084bc7a73) fixes the issue. Thanks.
```
{"Version":"6.3.0.5(sonoff)","BuildDateTime":"2018-11-07T23:32:33","Boot":4,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
```
With the same hw and wires setup (TX GPIO1=>72 SerBr Rx  and RX GPIO3=>71 SerBr Tx). And now if I don't touch the wires but change (TX GPIO1=>71 SerBr Tx and RX GPIO3=>72 SerBr Rx) everything still works.


@chaosmaster Hmm... I can rollback to 6.3.0 and check it out. If it matters.


...after a few minutes of work, Wemos rebooted and lost the config. Not lost wifi and name cfg but module type switch to Sonoff Basic. It seems beyond the scopes of this issue.
```
00:55:00 MQT: tele/arduino_433/INFO3 = {"RestartReason":"Fatal exception:0 flag:2 (EXCEPTION) epc1:0x4025ab3f epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000"}
```

**Comment by chaosmaster** [comment]
I think what you want is removing "72 SerBr Rx" and "71 SerBr Tx" from configuration alltogether and connect GPIO1 to Rx0 and GPIO3 to Tx0.
See here: https://github.com/arendst/Sonoff-Tasmota/issues/2376#issuecomment-379218886

**Comment by kockockockoc** [comment]
@chaosmaster nope, issue still exist on pre-compiled release sonoff-sensors.bin (Sonoff-Tasmota v6.3.0)
TX GPIO1=> None 
RX GPIO3=> None

**Comment by chaosmaster** [comment]
Use that configuration with development

**Comment by kockockockoc** [comment]
development branch fixes the issue. regardless of this configuration

**Comment by chaosmaster** [comment]
It looked like it was crashing according to your previous comment:

> 00:55:00 MQT: tele/arduino_433/INFO3 = {"RestartReason":"Fatal exception:0 flag:2 (EXCEPTION) epc1:0x4025ab3f epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000"}

Anyway you don't want to use software-serial with GPIO1 and GPIO3 you want to use hardware-serial.

**Comment by kockockockoc** [comment]
khmmm... It looks like I found what it is.
pre-compiled release "Core":"2_3_0"
my development tests "Core":"2_4_2"
I just rebuilt  6.3.0 with "2_4_2" 
```
{"Version":"6.3.0","BuildDateTime":"2018-11-08T03:33:09","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
```
and issue is gone

**Comment by ascillato2** [comment]
Closing this issue as @kockockockoc said it is solved.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
