### ISSUE TITLE
New hardware revision v2.3 BlitzWolf® BW-SHP2

### ISSUE THREAD

**Issue by aritmeester** [arendst/Sonoff-Tasmota#4303]
My new BW-SHP2 just arrived and it seems I have gotten a new hardware revision. I managed to flash Tasmota on it but it does not work with the default BW-SPH2 module type.
I switched to generic board and was able to use the relay on GPIO14. I didn't get the other functions working (power monitoring, button, led).

Any help to get it working completely is appreciated!

![image](https://user-images.githubusercontent.com/644662/48126808-71f04e00-e282-11e8-89d4-603c9ffb8e26.png)

![image](https://user-images.githubusercontent.com/644662/48126826-7d437980-e282-11e8-81cd-17ba7e439a8a.png)

![image](https://user-images.githubusercontent.com/644662/48126861-8df3ef80-e282-11e8-8a09-7365a07da7b4.png)

![image](https://user-images.githubusercontent.com/644662/48127131-4326a780-e283-11e8-93ef-acc7b94650d2.png)

![image](https://user-images.githubusercontent.com/644662/48127125-3c983000-e283-11e8-8008-aa1c18974413.png)

**Comment by ascillato** [comment]
Please,

Find which gpios are connected to buttons, leds, power monitoring and also which power monitoring chip it uses.

Then modify the sonoff_template.h with your findings to test your device. 

Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by AugustH** [comment]
see -- Goland SP1 V2.3 seems to be a clone
https://github.com/arendst/Sonoff-Tasmota/issues/4297

**Comment by AugustH** [comment]
Why is this closed? needs change/additional entry in sonoff_template.h -- see #4297

**Comment by aritmeester** [comment]
I can confirm this unit working perfectly on the _Teckin_ module type

**Comment by Roxxor91** [comment]
I just flashed it with the standard tasmota firmware. First I was able to get the hotspot functionality. (Nor sure if this was default, or I entered it successfully with 4 button presses.) Now it doesnt connect, maybe I entered something wrongly. I now want to reconfigure, but Im not able to enter hotspot mode via 4 button presses. Does this eman the button doesnt work and I have to reflash? I already removed all wires -_-

**Comment by R-Guhr** [comment]
Hardware button is not working! Tasmota v6.3.0, BlitzWolf BW-SHP2 v2.3

**Comment by Soulguard** [comment]
Same here at Gosund SP1 v2.3. All works, except the hardware button and the LED is constantly slow flashing in red regardless the plug is switched on or off.

**Comment by AugustH** [comment]
which version did you flash? just checked the nightly (Sonoff-Tasmota 6.3.0.14) from
 http://thehackbox.org/tasmota/ 
with Konfiguration: 55 Gosund SP1 v23

**Comment by Soulguard** [comment]
thank you very much AugustH, i had flashed 6.3.0. now with 6.3.0.14 the device works as expected. Hardware Button works, LED is blue now (properly configuring MQTT stops slowly flashing LED) Great work!

**Comment by kbhuinfo** [comment]
Teckin working for me as well.
![img_20181130_183649](https://user-images.githubusercontent.com/24209193/49339059-1b312680-f62c-11e8-9eec-87c76dc54a21.jpg)
![img_20181130_183707](https://user-images.githubusercontent.com/24209193/49339060-1b312680-f62c-11e8-96d4-7cdf4427d819.jpg)

**Comment by Silencer80** [comment]
I´ve just flashed tasmota to 4 Gosund SP1 v24. This one has Screws to and is not glued together like the Teckin. Pins/Layout seems equal to v23. I´ll test the newest nightly this afternoon and will post here, if everything works as expected.

**Comment by naeramarth7** [comment]
Running latest tasmota firmware (v6.4.1), the button works for me using the "Gosund SP1 v23 (55)" config.

**Comment by vb0** [comment]
I have a V2.4 that looks just like the pictures here, with a date from 201811. Works fine with "Gosund SP1 v23 (55)" /6.4.1 too.

**Comment by SimoneBnc** [comment]
I got 2 v2.4 SHP2 and it works like the v2.3.  Has anyone measured how accurate is the voltage reading? Mine is 10v below what I measured with a true rms multimeter.

**Comment by agsochi** [comment]
Hi. I have a V2.4. Button works with "Gosund SP1 v23 (55)" /6.4.1, blue LED is flashing 1sec period.
When i push button - relay is on, but no RED led is on. How to fix RED led?

**Comment by riston** [comment]
I received also newer version BlitzWolf v2.4 and when using Gosound SP1 module type it's working great after calibration voltage is off by +-2V(mostly 1).

**Comment by paucoma** [comment]
Hi All, 
I recieved mine (v2.4) opened it up and traced the board to create this schematic. Not Tested yet! but I'm pretty sure its right. 
In summary ESP pinout is the following : 
-IO1 | sink LED1 blue [out] | U0TXD
-IO3 | active low K1 (pushbutton) [in] | U0RXD
-IO4 | CF (BL0937) [in] | GPIO4
-IO5 | CF1 (BL0937) [in] | GPIO5
-IO12 | SEL (BL0937) [out] | MTDI
-IO13 | sink LED1 red [out] | MTCK
-IO14 | source RL2 relay [out] | MTMS
-RST | not connected | EXT_RSTB?
-AD | not connected | TOUT

Cheers,
Pau
[sch_BW-SHP2_(SP1-C_V2.4).pdf](https://github.com/arendst/Sonoff-Tasmota/files/3038647/sch_BW-SHP2_.SP1-C_V2.4.pdf)

**Comment by scasic** [comment]
What are modes of button LED? When it should blink and with which color?
Mine:
MQTT enabled, power is OFF - blinking BLUE
MQTT enabled, power is ON - blinking RED/BLUE
MQTT disabled, power is OFF - no light
MQTT disabled, power in ON - solid red

Is it correct behavior?

**Comment by mariantr** [comment]
I successfully flashed a BW-SPH2 with latest Tasmota, but after that the led slowly blinks red and the device does not connect to wifi (pre-configured SSID and password in config before flashing) and the button is not working
Anyone has any idea how to fix this?

**Comment by SimoneBnc** [comment]
Start by reading the serial debug and look for what's going on

**Comment by mszel42** [comment]
Since SHP2 is one of those Tuya based devices this OTA Tasmota installation method worked just fine:
https://github.com/ct-Open-Source/tuya-convert
The tuya-convert has a built in Tasmota v6.5.0 basic(but you can define any firmware during the install), remember, that basic version doesn't come with homeassistant auto discovery support, but Tasmota OTA works as expected.

**Comment by shady2k** [comment]
> I received also newer version BlitzWolf v2.4 and when using Gosound SP1 module type it's working great after calibration voltage is off by +-2V(mostly 1).

@riston , How do you calibrate it? Are you convert data on server side?

**Comment by sorianonet** [comment]
hi,
i've broken the IO0. is there another way to find it and enter in programmer mode?

**Comment by Notrial** [comment]
> What are modes of button LED? When it should blink and with which color?
> Mine:
> MQTT enabled, power is OFF - blinking BLUE
> MQTT enabled, power is ON - blinking RED/BLUE
> MQTT disabled, power is OFF - no light
> MQTT disabled, power in ON - solid red
> 
> Is it correct behavior?

Did you by any chance figure out how to modify this? I have same led patterns.
Can we disable the leds altogether?

**Comment by AugustH** [comment]
you could create a template without the leds

**Comment by atico45** [comment]
Good afternoon, I have been able to flash this device through OTA but I do not know how to link it to the homeassistant I have done it through Mqtt, there is another hole.
Thanks and sorry for not knowing English, this is from the google translate

**Comment by SimoneBnc** [comment]
It's written in the home assistant documentation, just enable the autodiscover in tasmota

**Comment by atico45** [comment]
Ok, gracias
