### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by TomekMar** [arendst/Sonoff-Tasmota#4305]
Hi

Recently one of my Sonoff Basic was reset, by mistake I pressed button >40s.
Now i cannot start it. Few flashing by TTL, or platformio without results.
I have log that serwerer 192.168.4.1 is started but not visible in SSID on computer or phone
 Any idea how to solve it? Led is blinking every second.
After 4 times pressing button i have:

00:00:08 RSL: stat/sonoff/RESULT = {"POWER":"ON"}
00:00:08 RSL: stat/sonoff/POWER = ON
00:00:14 WIF: Connect failed as AP cannot be reached
00:00:14 WIF: WifiManager active for 3 minutes
00:00:14 HTP: Web server active on sonoff-1329 with IP address 192.168.4.1
00:02:00 RSL: tele/sonoff/UPTIME = {"Time":"1970-01-01T00:02:00","Uptime":"0T00:02:01"}
00:03:16 APP: Restarting

 ets Jan  8 2013,rst cause:1, boot mode:(3,7)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v3fff3670
~ld

00:00:00 Project sonoff Sonoff (Topic sonoff, Fallback DVES_0F0531, GroupTopic sonoffs) Version 6.2.1.11-2_3_0

**Comment by ascillato2** [comment]
Please, erase before flash and flash the precompiled bin called sonoff_basic.bin from the development branch. Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
