### ISSUE TITLE
Enable Timer not working

### ISSUE THREAD

**Issue by ChGalle** [arendst/Sonoff-Tasmota#4306]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

**Describe the bug**
_When working with IOS or OS X Safari, its not possible to save after checking Timer enable in the Webinterface. In Chrome it works without any problem._

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x ] _Searched the problem in issues and in the wiki_
- [x ] _Hardware used_ :  Sonoff S20
- [ x] _If a pre-compiled release or development binary was used, which one?_ : release 6.3.0
- [x ] _You have tried latest release or development binaries?_ :
- [x ] _Provide the output of command_``status 0`` :
```
19:46:13 CMD: status 0
19:46:13 RSL: STATUS = {"Status":{"Module":1,"FriendlyName":["Aussen"],"Topic":"sonoff","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:46:13 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff-DE.bin","RestartReason":"Software/System restart","Uptime":"2T01:22:52","StartupUTC":"2018-11-05T17:23:21","Sleep":0,"BootCount":9,"SaveCount":193,"SaveAddress":"FA000"}}
19:46:13 RSL: STATUS2 = {"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018.10.30 17:39:28","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
19:46:13 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Galle",""],"TelePeriod":300,"SetOption":["00008001","55C18000","00000001"]}}
19:46:13 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":490,"Free":512,"Heap":13,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000407","0FDAE794","000183A0","23B617CE","00003BC0"]}}
19:46:13 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff-3960","IPAddress":"192.168.1.100","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"5C:CF:7F:3B:8F:78","Webserver":2,"WifiConfig":5}}
19:46:13 RSL: STATUS7 = {"StatusTIM":{"UTC":"Wed Nov 07 18:46:13 2018","Local":"Wed Nov 07 19:46:13 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":99,"Sunrise":"07:37","Sunset":"16:58"}}
19:46:13 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-11-07T19:46:13"}}
19:46:13 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-11-07T19:46:13","Uptime":"2T01:22:52","Vcc":3.222,"POWER":"ON","Wifi":{"AP":1,"SSId":"Galle","BSSId":"80:2A:A8:5A:59:81","Channel":6,"RSSI":84}}}
```

**To Reproduce**
_Steps to reproduce the behavior:_
Use Safari Browser

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by reloxx13** [comment]
duplicate, next time use search function.

https://github.com/arendst/Sonoff-Tasmota/issues/4250
