### ISSUE TITLE
Wifi won't connect after replacing a new router

### ISSUE THREAD

**Issue by kevinshane** [arendst/Sonoff-Tasmota#4308]
version: 5.14 and 5.12 mixing together with 10+ sonoff t1 3gang
Hi all, I have 10+ sonoff T1 running well on an old router, but after I replace a new router(with same ssid and pwd, same ip range, same netmask 192.168.0.1/24), some of them is missing and won't connect to the new one anymore(and I wait the whole night but still missing some of them).. the new router only can find 4~5 of them.
I also disable the wifi broadcast via `WifiConfig 5` and `SetOption13 1` when I original flashed all devices. Now they are all staying in wall few months. The problem is when I replace the old router and they are all come alive again. It just not working with the new router(openwrt OS). What would you suggest in this situation?
- Removing them one by one in wall and try to re-flash them?(which is a huge job). 
- Changing new router's broadcasting channel?(didn't try that yet.) 
- Make some of them start to broadcast its own ssid?(which I have no idea how to do that, I try short click the first gang 4 times but it just turn on/off)
- turn off the main ac? which I did but no luck.

Plase help, thanks!!

**Comment by Jason2866** [comment]
Update to latest release 6.3.0. Many issues solved...

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
