### ISSUE TITLE
DS18B20's start showing 0.0C randomly. Power cycling fixes the issue.

### ISSUE THREAD

**Issue by thucar** [arendst/Sonoff-Tasmota#4310]
Still happening with 6.3.0 Not as often though. Today was the first time in 6 days.

_Originally posted by @thucar in https://github.com/arendst/Sonoff-Tasmota/issues/4237

**Comment by ascillato2** [comment]
No need to open a new issue for a comment of another issue.

**Comment by thucar** [comment]
The other issue is closed though. Would it be possible to re-open it please?
