### ISSUE TITLE
SSID deleting minus sign (-)

### ISSUE THREAD

**Issue by anduz** [arendst/Sonoff-Tasmota#4312]
Hello,

compiled and uploaded using Atom, setting my SSID in STA_SSID1.
I set it to "my-wifi", but it tried to connect to "mywifi" instead.
Is this a bug?
I have other ESP8266 devices with other firmwares working fine with this SSID.

Best regards

**Comment by ascillato2** [comment]
Hi,

Sorry, I have just tested "my-wifi" as ssid name and works fine.

Please, review your configuration.
