### ISSUE TITLE
change topic name "POWER1" with a custom name 

### ISSUE THREAD

**Issue by khriss75** [arendst/Sonoff-Tasmota#4317]
I checked on wiki but not found.
Is possible to change telemetry, topic etc, but is possible to change the "POWER1" or "POWER2" with a custom name?
I'm using T1 2CH and my full topic is:
"sonoff_T1_bedroom/stat/POWER1" payload ON/OFF
"sonoff_T1_bedroom/stat/POWER2" payload ON/OFF
I'd like to change in:
"sonoff_T1_bedroom/stat/**blue_light**" payload ON/OFF  (blue_light = POWER1)
"sonoff_T1_bedroom/stat/**red_light**" payload ON/OFF  (red_light = POWER2)

Is it possible?

**Comment by ascillato** [comment]
Not supported, but you can use rules as workaround to publish the way you want.

go to the console and type:

```
rule1 1
rule1 on power1#state=1 do publish sonoff_T1_bedroom/stat/blue_light ON endon on power1#state=0 do publish sonoff_T1_bedroom/stat/blue_light OFF endon on power1#state=2 do publish sonoff_T1_bedroom/stat/blue_light TOGGLE endon
rule2 1
rule2 on power2#state=1 do publish sonoff_T1_bedroom/stat/red_light ON endon on power2#state=0 do publish sonoff_T1_bedroom/stat/red_light OFF endon on power2#state=2 do publish sonoff_T1_bedroom/stat/red_light TOGGLE endon
```

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
