### ISSUE TITLE
Bug bei 3.5.0.6 mit Gosund SP1 (alte Version)

### ISSUE THREAD

**Issue by ihavenonick** [arendst/Sonoff-Tasmota#4319]
![grafik](https://user-images.githubusercontent.com/36501310/48303066-e4bd2b80-e505-11e8-80ec-8aaeb45521f2.png)
Man kann zwar "BlitzWolf SHP2 Modul" auswählen, aber nach dem Neustart steht es wieder auf "Generic".
Die Funktion wird dadurch allerdings nicht beeinträchtigt.

**Comment by arendst** [comment]
Verified. It does select the new module but displays Generic.

Investigating.

**Comment by arendst** [comment]
Should be fixed now. Just let me know.

**Comment by ihavenonick** [comment]
yes it is OK now
