### ISSUE TITLE
Sonoff S20 works with 3.3V but not when plugged in AC

### ISSUE THREAD

**Issue by cirolaferrara** [arendst/Sonoff-Tasmota#4322]
Sonoff S20 flashed with tasmota 6.1.1.
It connects to WIFI and works well with 3.3V but when i plug in into AC, no LED powers ON. Why?

**Comment by ascillato** [comment]
Seems that it is defective.

**Comment by ascillato2** [comment]
Please, search in issues for solutions with the addition of capacitor of changing the Vregulator
