### ISSUE TITLE
LED dimmers

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#4338]
Regarding support for the several LED dimmers. 

I have looked around but I cannot seem to find what the module type should be set for once Tasmota is installed.

Sorry, but this does seem like a very basic question.

**Comment by ascillato** [comment]
I think I'm not understanding your question. If you go to module configuration you can see which module you have configured.

It is better and more dynamic to ask general question in the Tasmota Chat.

**Comment by Lawrencezarb** [comment]
Thanks...
