### ISSUE TITLE
Feature request - Shelly 2LED

### ISSUE THREAD

**Issue by trommegutten** [arendst/Sonoff-Tasmota#4340]
I have successfully been able to flash this device with Tasmota. I tried to choose the Tasmota “generic” device but I couldn’t figure out how to configure it. Anyone?

**Comment by ascillato** [comment]
Shelly 2 is already supported. See release notes. Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by trommegutten** [comment]
Both Shelly1 and Shelly2 are supported, but this post was regarding the Shelly 2LED. A led dimmer.

https://shelly.cloud/shelly-2-led/

![9bc0d1b9-f823-4230-8530-33422519819e](https://user-images.githubusercontent.com/12217243/48370336-54bfe300-e6b9-11e8-829c-38933b597b60.jpeg)
![f5694305-e968-41d2-b39c-f62947ddf8c9](https://user-images.githubusercontent.com/12217243/48370390-7caf4680-e6b9-11e8-82a1-2e910a17f4be.jpeg)
![a6b4deba-e995-44ef-b222-accda3949b38](https://user-images.githubusercontent.com/12217243/48370391-7caf4680-e6b9-11e8-9f4c-a2e6f1dca436.jpeg)
