### ISSUE TITLE
Timer web configuration fails when using webkit based browser.

### ISSUE THREAD

**Issue by Geitde** [arendst/Sonoff-Tasmota#4343]
I am using latest 6.3.0 and noticed that timer setup via web interface does not work anymore.

All changes are simply ignored. The entire timer setup page is useless.

It works fine with Mozilla-Firefox, but fails e.g. when using ipad or desktop browsers using webkit engine.

**Comment by ascillato** [comment]
Hi @geitde

That issue was already solved. (https://github.com/arendst/Sonoff-Tasmota/issues/4250) Please, upgrade to last version.
Please, next time search in issues as the template asks.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
