### ISSUE TITLE
Shelly 1 flash delete complete?

### ISSUE THREAD

**Issue by daendaen** [arendst/Sonoff-Tasmota#4344]
Hi!

Tasmota ist on my shelly 1. Now i will flash tasmota new on the shelly, but i have problem with my settings. Everytime when i flash tasmota in shelly 1 again, my settings are all there. How can i delete entire memory ?

Thanks for help

Greetings

**Comment by ascillato** [comment]
Hi,

In the wiki is all the information you need.

You can use the `reset 1` command (https://github.com/arendst/Sonoff-Tasmota/wiki/Commands)

Or you can erase all flash using esptool.py (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#esptool-usage)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
