### ISSUE TITLE
LC04 with rgbww 4in1

### ISSUE THREAD

**Issue by timtimsson** [arendst/Sonoff-Tasmota#4360]
Hello,
i use this [LC04](https://github.com/arendst/Sonoff-Tasmota/wiki/Arilux-LC04) module.
How can i control my rgbww strip 4in1? 
With LC11 i can use ct+dimmer -  with LC04 only dimmer...
Is the color-temperature changeable?
who can help me?
![homematic-rgbw-bausatz-18](https://user-images.githubusercontent.com/17343162/48580640-0b250180-e920-11e8-913b-dbfcccaf10e8.jpg)

**Comment by ascillato** [comment]
Have you tried the commands?

Please, read the wiki. Thanks

**Comment by ascillato2** [comment]
Have you asked for support at the Tasmota chat? 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato** [comment]
LC11 has 5 pwm channels

LC04 has 4 pwm channels

So the color temperature can not be changed using your LC04 and your led strip.
