### ISSUE TITLE
wemos d1 mini pro bme680 mqtt output

### ISSUE THREAD

**Issue by lucafolin** [arendst/Sonoff-Tasmota#4362]
Hi I have wemos d1 mini pro and bme680 sensor and It's working fine.
I need to change mqtt output message now I have something like:

22:03:21 MQT: tele/sonoff/SENSOR = {"Time":"2018-11-15T22:03:21","BME680":{"Temperature":23.2,"Humidity":53.7,"Pressure":1018.1,"Gas":39.10},"TempUnit":"C"}

but I need something like:

22:03:21 MQT: tele/sonoff/SENSOR = {23.2,53.7,1018.1,39.10} 

only output values separated by coma.
How can I acive it ? how can I change xsns_09_bmp.ino file so to have this output ?

**Comment by ascillato** [comment]
Sorry, not supported. Tasmota uses JSON format

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
