### ISSUE TITLE
S20 won't turn on, but will re-flash sucessfully

### ISSUE THREAD

**Issue by glennmurley15** [arendst/Sonoff-Tasmota#4370]
I have a sonoff s20, flashed with tasmota (sonoff.bin) as normal, flashing was successful, but then device is completely unresponsive.
No LEDs lit, no wifi AP, not even with 4 presses of button.

Looks as if fried,
However, tried to flash again, using the development precompiled version, abd flashing was successful so the board can't be fried.
Also tried the minimal version of precompiled release and development.

**Comment by ascillato** [comment]
After you flash, can you send commands using the serial interfase?

**Comment by glennmurley15** [comment]
I am not sure, I use an FTDI USB adapter, and the ESPtool to flash the devices - I found that tool to be very simple to use, as it is preprogrammed for ESP chip with 1M flash etc

Could you please provide an example of how I would send additional commands?

**Comment by ascillato** [comment]
After you flash, using your FTDI you can send command by serial using any serial terminal software like termite, hiperterminal, the serial monitor of arduino ide etc.

You can configure your device by commands like your wifi. For the list of commands, please read the wiki at commands. 

You can start with status 0 to know if was flashed correctly.

If status 0 don't respond your flashing was not correct. 

The best procedure is erase and then flash using esptool.py as explained in the wiki.

**Comment by ascillato2** [comment]
When you have time, let us know if you could use the serial interfase. If not, find us in the support Tasmota chat. Thanks

**Comment by glennmurley15** [comment]
OK update time.
Thank you very much for explaining to wipe the flash first, this worked, and now the unit is functioning perfectly.

I did have a search around at first, but couldn't find anything linked to a "dead" device after flashing.
