### ISSUE TITLE
DisplayText issues

### ISSUE THREAD

**Issue by j-broyles** [arendst/Sonoff-Tasmota#4375]
This is the functionality I've been waiting for Tasmota to have before I settled on which ESP8226 firmware to settle on. So I was wringing it out and came across the following issues and questions...

0.96 oled SSD1306 128x64 Display connected to NodeMCU I2C on GPIO 12(SCL)/13(SDA) at address 0x3c

Program Version		6.3.0
Build Date & Time	2018-10-30T17:36:38
Core/SDK Version	2_3_0/1.5.3(aec24ac9)

https://github.com/arendst/Sonoff-Tasmota/wiki/DisplayText-Command

DisplayText command wiki error:
Text is printed at the last provided position, either l or y for the vertical position, and either x (should b "c") or x for the horizontal position. Neither x nor y are advanced/updated after printing text.
Works mostly

command Display returns:
stat/KMTA_F1_L00/RESULT = {"Display":{"Model":2,"Mode":0,"Dimmer":1,"Size":1,"Font":0,"Rotate":0,"Refresh":2,"Cols":[16,8],"Rows":2}}

What do the values "Cols" and "Rows" designate, and can they be changed, and what command/escape code changes them?

Escape Code Issues:
[lp] - has no effect on printing text location eg: [zl5]test still prints at px0:0
[cp] - has no effect on printing text location eg: [zc10]test still prints at px0:0
[t] - output truncated after 4 characters
[T] - unknown escape
[sp] - only works for values 1-3. p=0,4,5,8,9 uses size 1; p=6 uses size 2; p=7 uses size 3; p=10 or higher gives unknown escape

In the Hardware connections section
DisplayModel: recomend adding this list to Wiki 
[DisplayModel 1] Enable Lcd display (I2C addresses 0x27 and 0x3F) (+6k code)
[DisplayModel 2] Enable SSD1306 Oled 128x64 display (I2C addresses 0x3C and 0x3D) (+16k code)
[DisplayModel 3] Enable 8x8 Matrix display (I2C adresseses see below) (+11k code)
[DisplayModel 4] Enable ILI9341 Tft 480x320 display (+19k code)
[DisplayModel 5] Enable e-paper display (+19k code)

DisplayDimmer: no definition for this command as to function or values

Do the values used set an automatic dimming time (either by the values used or the displayed result of the command)? I noticed the Main Menu power indication was ON at some point after DisplayDimmer 6 command had been issued, then at some later point the menu indication was OFF.

Values:
12:45:10 CMD: DisplayDimmer 98
12:45:10 MQT: stat/KMTA_F1_L00/RESULT = {"DisplayDimmer":14}
12:45:15 CMD: DisplayDimmer 99
12:45:15 MQT: stat/KMTA_F1_L00/RESULT = {"DisplayDimmer":15}
12:47:10 CMD: displaydimmer 0
12:47:10 MQT: stat/KMTA_F1_L00/RESULT = {"POWER3":"OFF"}
12:47:10 MQT: stat/KMTA_F1_L00/POWER3 = OFF
12:47:10 MQT: stat/KMTA_F1_L00/RESULT = {"DisplayDimmer":0}

DisplayDimmer 
low	high	Result	display
0	5	0	power off
6	12	1	power on
13	18	2	power on
19	26	3	power on
27	32	4	power on
33	38	5	power on
39	45	6	power on
46	52	7	power on
53	58	8	power on
59	65	9	power on
66	72	10	power on
73	78	11	power on
79	85	12	power on
86	92	13	power on
93	98	14	power on
99	and up	15	power on

Thanks!  --jb

**Comment by ascillato2** [comment]
Hi

You are right but in gemu's fork it all does work. Theo (@arendst) is working on adapting PR (https://github.com/arendst/Sonoff-Tasmota/pull/3748) to be integrated into Tasmota with the smallest footprint. That is why the wiki states "upcoming features".

Thanks a lot for testing. You can try gemu's fork or PR 3748, or wait until it is totally integrated.
