### ISSUE TITLE
some of commands not working on 5.0.6

### ISSUE THREAD

**Issue by hamwong** [arendst/Sonoff-Tasmota#439]
I just upgraded to 5.0.6, and found some of the command is not working

```
Program version	5.0.6
Build Date & Time	2017-05-11T21:01:30
Core/SDK version	2_3_0/1.5.3(aec24ac9)

```
most of the new command and MQTT command not working

```
21:19:39 CMND: SetOption8
21:19:39 RSLT: RESULT = {"Command":"Unknown"}
21:22:07 CMND: ButtonRetain
21:22:07 RSLT: RESULT = {"Command":"Unknown"}
```

old command works
```
21:21:35 CMND: sleep
21:21:35 RSLT: RESULT = {"Sleep":"1 (1)"}
```

anyone know why?

also, when upgrade from 4.1.1 to 5.0.x, I got no issue, but after power cut and restart, it fail to start,
in serial console, I found lot of characters turns to unicode "square", and wifi fail to connect
reflash by arudino doesn't work until I change CFG_HOLDER to another value.

**Comment by arendst** [comment]
Your ``ButtonRetain`` doesn't work because you disabled mqtt.
All ``SetOption<x>`` will be released in next version.

Regarding migrating from < 5.0 to 5.0 see wiki > Upgrade - Migration Path step 4

**Comment by hamwong** [comment]
Thanks for response @arendst, I didn't disable mqtt as it's the only reason why I use tasmota but I do disabled **USE_DOMOTICZ**, will it be the reason? as I only use openhab, **DOMOTICZ** feature is useless for me.

I checked the wiki, I did stored config, issue is not happened right after upgrade, it upgraded successfully  to 5.0.x and info also shows corrected version, issue happened after power cut, after power restore, ESP fail to start and serial shows  lot of characters turns to unicode "square", wifi connection keep fail.

I don't know is this a unique case, I will try on other ESP tomorrow see will it happen again.

**Comment by hamwong** [comment]
I don't know is this a bug or not,
I found if I use stored setting, MQTT was disabled in info, (config menu dont have MQTT option)
after I do reset setting, MQTT back to default setting in rom, config menu have MQTT again
I don't know what's going on
