### ISSUE TITLE
openhab json send error

### ISSUE THREAD

**Issue by hwarang098tkd** [arendst/Sonoff-Tasmota#4390]
openhab2 in rasp
wemo with tasmota software (Sonoff-Tasmota 6.3.0 by Theo Arends)

i have this rule and i want to send command with timer to my device... but....

    rule "heater time adjust Mode 2"
    when
    Item progr received command
    then
    var jsonstring= '{Timer1:{\"Arm\":\"0\",\"Mode\":\"0\",\"Time\":\"13:34\",\"Window\":\"0\",\"Days\":\"1111111\",\"Repeat\":\"0\",\"Output\":\"1\",\"Action\":\"1\"}}'
    logInfo("heater",jsonstring.toString)
    heater_command.sendCommand(jsonstring)
    end

mqtt spy result on topic -->

> {Timer1:{"Arm":"0","Mode":"0","Time":"13:34","Window":"0","Days":"1111111","Repeat":"0","Output":"1","Action":"1"}}

log file openhab result --->

> 2018-11-20 01:11:54.498 [INFO ] [clipse.smarthome.model.script.heater] - {Timer1:{"Arm":"0","Mode":"0","Time":"13:34","Window":"0","Days":"1111111","Repeat":"0","Output":"1","Action":"1"}}

on device my arsend software the result on consol is -->

> 01:19:54 MQT: stat/relay_heater/RESULT = {"Timer1":{"Arm":1,"Mode":0,"Time":"02:23","Window":0,"Days":"0011001","Repeat":1,"Output":1,"Action":1}}

What goes wrong? whatever I put to my string ,timer1 or timer2,arm 0 or 1 etc I always take the same result for timer1

**Comment by ascillato** [comment]
Seems that your json is incorrect. Seems that Tasmota is not understanding what you are sending

The first part of your command is {"timer1": but Tasmota syntax is timer1 {

**Comment by ascillato2** [comment]
When you have time, please report back if that works.
Remember that you can also find us in the Tasmota chat for support.
Thanks

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by hwarang098tkd** [comment]
> Seems that your json is incorrect. Seems that Tasmota is not understanding what you are sending
> 
> The first part of your command is
> 
> {"timer1":
> 
> but Tasmota syntax is
> 
> timer1 {
> 
> Please, see wiki for more details.



> Seems that your json is incorrect. Seems that Tasmota is not understanding what you are sending
> 
> The first part of your command is
> 
> {"timer1":
> 
> but Tasmota syntax is
> 
> timer1 {
> 
> Please, see wiki for more details.

if i send this
`var String jsonstring= "Timer3 {\"Arm\":0,\"Mode\":0,\"Time\":\"13:34\",\"Window\":0,\"Days\":\"1111111\",\"Repeat\":0,\"Output\":1,\"Action\":1}"`
the result is 

> 23:45:28 MQT: stat/relay_heater/RESULT = {"Timer1":"Invalid JSON"}

**Comment by ascillato** [comment]
If I do exactly that, works fine:

![image](https://user-images.githubusercontent.com/35405447/48947126-e4159380-ef0e-11e8-8f6a-fdba334c6f3d.png)

Console Output - Command from MQTT (previously I had another Timer config to test that It changes):
```
10:58:28 SRC: MQTT
10:58:28 RSL: Topic Recibido cmnd/living/timer1, Tamaño de Datos 94, Datos {"Arm":0,"Mode":0,"Time":"13:34","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":1}
10:58:28 RSL: Grupo 0, Índice 1, Comando TIMER, Datos {"Arm":0,"Mode":0,"Time":"13:34","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":1}
10:58:28 MQT: stat/living/RESULT = {"Timer1":{"Arm":0,"Mode":0,"Time":"13:34","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":1}}
10:58:28 CFG: Grabado a la flash en 3F5, Conteo 79, Bytes 3584
```

Console Output - Command from Console (previously I had another Timer config to test that It changes):
```
10:28:10 CMD: Timer1 {"Arm":0,"Mode":0,"Time":"13:34","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":1}
10:28:10 SRC: WebConsole from 192.168.1.131
10:28:10 RSL: Topic Recibido /Timer1, Tamaño de Datos 94, Datos {"Arm":0,"Mode":0,"Time":"13:34","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":1}
10:28:10 RSL: Grupo 0, Índice 1, Comando TIMER, Datos {"Arm":0,"Mode":0,"Time":"13:34","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":1}
10:28:10 MQT: stat/living/RESULT = {"Timer1":{"Arm":0,"Mode":0,"Time":"13:34","Window":0,"Days":"1111111","Repeat":0,"Output":1,"Action":1}}
```

![image](https://user-images.githubusercontent.com/35405447/48947164-060f1600-ef0f-11e8-8421-48a349ccb623.png)


So, there is something wrong in your OpenHab side. Sorry, not Tasmota side.

**Comment by hwarang098tkd** [comment]
I appreciate your help. I will search it 
. Thnx

**Comment by hwarang098tkd** [comment]
the solution was very simple 
i had wrong topic ..../timer instead of ..../time1
so 
`var String jsonstring= "{\"Arm\":0,\"Time\":\"13:35\",\"Window\":0,\"Days\":\"11TW11S\",\"Repeat\":0,\"Output\":1,\"Action\":1}"`
it works now.
