### ISSUE TITLE
Can't connect to Wifi

### ISSUE THREAD

**Issue by jaime1988** [arendst/Sonoff-Tasmota#44]
Since I updated to the newer version, it doesn't connect to any wifi. With the default configuration the serial output is:
0:00:00 Wifi: Connecting to AP256 � in mode 11N as enchufe5...
00:00:07 Wifi: Connect failed as AP cannot be reached

Can you please help me?

Thanks

**Comment by jaime1988** [comment]
Solved erasing flash, not sure what was happening.

**Comment by csaleman** [comment]
had the same issue, had to erase flash in order to connect.
