### ISSUE TITLE
Backup & Restore to original firmware on Sonoff Pow R2 is not working

### ISSUE THREAD

**Issue by HobbytronicsPK** [arendst/Sonoff-Tasmota#4402]
Hello,
I have backed up the firmware according to instructions given under your [wiki article](https://github.com/arendst/Sonoff-Tasmota/wiki/Esptool) and another article [Backup & Restore Official Firmware of Sonoff WiFi Smart Switches](https://hobbytronics.pk/sonoff-original-firmware-backup-restore/) on my Sonoff Pow and Sonoff Pow R2 using the command as given below.

`esptool.py --port COM5 read_flash 0x00000 0x100000 image1M.bin`

Restored worked on Sonoff Pow but it does not work on Sonoff Pow R2. It gets restored successfully but there is no LED blinks observed after restore. Here is command used for restore purpose.

`esptool.py --port COM5 write_flash -fs 1MB -fm dout 0x0 image1M.bin`

I also erased the flash prior restoration. 

`esptool.py --port COM5 erase_flash`

If I re-install your pre-built [Tasmota binary](https://github.com/arendst/Sonoff-Tasmota/releases/download/v6.3.0/sonoff.bin), it starts working again. Only the restore of original firmware does not work. I have tried it on different Sonoff Pow R2 devices without any success. But on Sonoff Pow (which is Version 2, not R2) it always works as expected.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by HobbytronicsPK** [comment]
I have tried to backup the stock firmware numerous times using different Sonoff  Pow R2. I think either Itead has changed something in their firmware or `esptool.py --port COM5 erase_flash` is not erasing the flash completely. Anyone more experienced may put light on it?

**Comment by HobbytronicsPK** [comment]
I am using latest esptool version 2.5.1

**Comment by arendst** [comment]
Both pow and pow r2 have a 4M flash. You're backing up only 1M flash.

**Comment by HobbytronicsPK** [comment]
@arendst Can you adapt these commands for 4M?
`esptool.py --port COM5 read_flash 0x00000 0x100000 image1M.bin`
`esptool.py --port COM5 write_flash -fs 1MB -fm dout 0x0 image1M.bin`

**Comment by arendst** [comment]
Be a bit adventuourous and chane all 1's to 4's

**Comment by HobbytronicsPK** [comment]
Updated the blog post [Backup & Restore Official Firmware of Sonoff WiFi Smart Switches](https://hobbytronics.pk/sonoff-original-firmware-backup-restore/) with resolution of the problem of restoring Sonoff devices to origin firmware by determining the Flash Size.

**Comment by evlo** [comment]
I have tried again to restore original firmware to different r2 and it did not work, i grabbed image myself from 2 different original r2s and both images are different, ie. serial number is stored in binary.

Device just does not power up with restored original firmware

**Comment by meingraham** [comment]
Sonoff binaries are specific to the device. You can upload a binary from another device of the same model, but it will not operate. You have to back up the binary and but back that same file on the device in order for it to work.

**Comment by evlo** [comment]
that is what i found out - there is currently no known working way that would work for restoring original firmware (if you don't have backup for each device), right?

**Comment by meingraham** [comment]
Correct

**Comment by cent0** [comment]
> I have tried again to restore original firmware to different r2 and it did not work, i grabbed image myself from 2 different original r2s and both images are different, ie. serial number is stored in binary.
> 
> Device just does not power up with restored original firmware

hello you have found solution ?
i have same problem to pow r1
blue led fix on button not work and wifi not start.
with espurna all work fine
