### ISSUE TITLE
cannot access webpage sonoff pow R2 after flashing

### ISSUE THREAD

**Issue by bramschats** [arendst/Sonoff-Tasmota#4406]
Flashed latest tasmota firmware on my Sonoff pow R2. Devices get's IP from DHCP and I can ping the device but am not able to view the webbrowser.

I have had more flashed sonoff devices and never had this issue.

Hope someone can help solving this problem.

Regards.

**Comment by ascillato** [comment]
Hi,

Seems that something went wrong on your flashing process.

Please, erase all flash with esptool.py and flash it again using the precompiled bins from development: http://thehackbox.org/tasmota/

If that don't work, please, use the troubleshooting template or use the Tasmota support Chat. Thanks.

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
