### ISSUE TITLE
Sonoff 4CH Pro R2 buttons not work

### ISSUE THREAD

**Issue by fnatalucci** [arendst/Sonoff-Tasmota#4408]
Hello,
I flash Sonoff 4CH Pro R2 with use of Easpeasy tool selecting sonoff.bin (latest) firmware as default. The flashing goes good, but when I try to push button hardware to change state of 1 of 4 button it don't respond. The lights are off for all buttons, the state on webinterface not change...

I Think that could be DOUT settings?

What's I wrong?

**Comment by wongnam** [comment]
You did not provide enough info for us to know what configuration of your device is.
Go to Console menu type Status 0 and provide that info here. Thk

**Comment by ascillato2** [comment]
@fnatalucci 

As @wongnam told you, please, provide the Troubleshooting Template completed in order to have enough information for properly help you. Also, please provide the output of the console when you press the buttons. Please, use command `weblog 4` in order to have more debug information.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato2** [comment]
Hi,

Please, when you have time, provide the requested information so as to help you properly. Remember that you can also use the Tasmota Chat for support. Thanks

**Comment by fnatalucci** [comment]
Hi @ascillato2, 

I have already read the wiki 2 times and read all the troubleshooting on wiki. I send you my status 0 
```

22:45:59 MQT: stat/sonoff-01/STATUS = {"Status":{"Module":23,"FriendlyName":["Sonoff","Sonoff2","Sonoff3","Sonoff4"],"Topic":"sonoff-4ch-sal-01","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
22:45:59 MQT: stat/sonoff-01/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-IT.bin","RestartReason":"Power on","Uptime":"0T00:23:14","StartupUTC":"2018-11-22T21:22:45","Sleep":0,"BootCount":15,"SaveCount":89,"SaveAddress":"FB000"}}
22:45:59 MQT: stat/sonoff-01/STATUS2 = {"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018-10-30T17:43:43","Boot":7,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
22:45:59 MQT: stat/sonoff-01/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ALFA-X",""],"TelePeriod":300,"SetOption":["00008009","55818000","00000000"]}}
22:45:59 MQT: stat/sonoff-01/STATUS4 = {"StatusMEM":{"ProgramSize":490,"Free":512,"Heap":15,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000410","0FDAE794","000183A0","23B617CE","00003BC0"]}}
22:45:59 MQT: stat/sonoff-01/STATUS5 = {"StatusNET":{"Hostname":"sonoff-01","IPAddress":"192.168.100.11","Gateway":"192.168.100.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.13","Mac":"xxxxxxx","Webserver":2,"WifiConfig":5}}
22:45:59 MQT: stat/sonoff-01/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.100.1","MqttPort":1883,"MqttClientMask":"sonoff-01","MqttClient":"sonoff-01","MqttUser":"domouser","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
22:45:59 MQT: stat/sonoff-01/STATUS7 = {"StatusTIM":{"UTC":"Thu Nov 22 21:45:59 2018","Local":"Thu Nov 22 22:45:59 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"08:09","Sunset":"17:02"}}
22:45:59 MQT: stat/sonoff-01/STATUS10 = {"StatusSNS":{"Time":"2018-11-22T22:45:59"}}
22:45:59 MQT: stat/sonoff-01/STATUS11 = {"StatusSTS":{"Time":"2018-11-22T22:45:59","Uptime":"0T00:23:14","Vcc":3.125,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"ALFA-X","BSSId":"XXXXX","Channel":11,"RSSI":100}}}
```
When push button on hardware nothing happen on Log Console. I do this test with USB 3.3v. If I click on ON/OFF button on sonoff web page it works...

**Comment by fnatalucci** [comment]
The problem was the power! USE DC power supply! and works great!
