### ISSUE TITLE
Switch1#state - doesn't work - 6.3.0 - Sonoff Basic

### ISSUE THREAD

**Issue by mvincm** [arendst/Sonoff-Tasmota#4414]
- [X ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [X ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [X ] Development/Compiler/Upload tools used : esptool
- [X ] Hardware used : Sonoff Basic R2 V1.0
- [X ] If a pre-compiled release or development binary was used, which one? : sonoff.bin 6.3.0
- [X ] You have tried latest release or development binaries? : NO
- [X ] Provide the output of command status 0 :

```
18:41:25 CMD: status 0
18:41:25 RSL: STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[3,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
18:41:25 RSL: STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T01:05:19","StartupUTC":"2018-11-22T16:36:06","Sleep":0,"BootCount":21,"SaveCount":108,"SaveAddress":"F8000"}}
18:41:25 RSL: STATUS2 = {"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018-10-30T17:33:53","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
18:41:25 RSL: STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["KoroFlat",""],"TelePeriod":60,"SetOption":["04008000","55818000","00000000"]}}
18:41:25 RSL: STATUS4 = {"StatusMEM":{"ProgramSize":489,"Free":512,"Heap":13,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","000183A0","23B617CE","00003BC0"]}}
18:41:25 RSL: STATUS5 = {"StatusNET":{"Hostname":"sonoff_mm","IPAddress":"192.168.22.162","Gateway":"192.168.22.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.22.1","Mac":"84:F3:EB:48:6D:51","Webserver":2,"WifiConfig":5}}
18:41:25 RSL: STATUS7 = {"StatusTIM":{"UTC":"Thu Nov 22 17:41:25 2018","Local":"Thu Nov 22 18:41:25 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"08:09","Sunset":"17:02"}}
18:41:25 RSL: STATUS10 = {"StatusSNS":{"Time":"2018-11-22T18:41:25","DS18B20":{"Temperature":22.0},"TempUnit":"C"}}
18:41:25 RSL: STATUS11 = {"StatusSTS":{"Time":"2018-11-22T18:41:25","Uptime":"0T01:05:19","Vcc":2.982,"POWER1":"OFF","Wifi":{"AP":1,"SSId":"KoroFlat","BSSId":"34:CE:00:63:20:41","Channel":1,"RSSI":82}}}
```

Hello.

I'm trying to implement simple thermostat based on: https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#9-simple-thermostat-example

And it almost working but... Switch#state do nothing. I must manually (e.g. by console) turn on thermostat mem1=1. Pushing button do not generate any trigger. I'm know that SwitchTopic must be 0 but there is another problem. If I type SwitchTopic=0 I get "RESULT = {"Command":"Unknown"}".

BTW...

18:43:18 CMD: SwitchTopic 0
18:43:18 RSL: RESULT = {"Command":"Unknown"}

Any ideas what is wrong? Thanks in advanced!

Best regards,
MvincM

**Comment by ascillato** [comment]
Hi

`SwitchTopic=0` is not a command in Tasmota, the correct syntax is `SwitchTopic 0`

```
14:58:18 CMD: switchtopic 0
14:58:18 SRC: WebConsole from 192.168.1.131
14:58:18 RSL: Topic Recibido /switchtopic, Tamaño de Datos 1, Datos 0
14:58:18 RSL: Grupo 0, Índice 1, Comando SWITCHTOPIC, Datos 0
14:58:18 RSL: stat/living/RESULT = {"SwitchTopic":""}
```

`Switch#state` is not a valid trigger. The correct syntax is `Switch1#state`

Also you need to have defined your GPIOs as Switches to work, and also you need to set the correct SWITCHMODE for that.

See commands in the wiki and the examples in the wiki. You can copy and paste directly from the example. Thanks

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
