### ISSUE TITLE
ability to use variables within add/sub/mult commands

### ISSUE THREAD

**Issue by th-s-op** [arendst/Sonoff-Tasmota#4419]
Using version 6.3.0.5 on a Sonoff S20.

My feature request would be to be able to use variables like %var1% or %mem3% within the mathematic commands like ADD, SUB.

Example:
```
var1 2
var2 3
add1 %var2%
```
The result would be adding the value 3 to the value 2 in var1 with the result 5 in var1.

A situation where this would be a great feature: every time I use a rule to collect sensor values, it could add the sensor value to a variable (that works fine) and increase a counter in another variable (also works fine). In the end, I want to send out the AVERAGE measured value, which would be
"sum of all measurements" divided by "cound of measurements".

My hope is that a function which replaces every %var...% and %mem...% with its values already exists (used in rules) and that it could be quite a small change.

PLUS, would't it be even more useful to allow use of %var...% and %mem...% placeholders in ALL commands, anytime?

**Comment by ascillato** [comment]
Hi,

The use case of replacing variables for all commands is inside a rule like your comment:

> A situation where this would be a great feature: every time I use a rule to collect sensor values, it could add the sensor value to a variable

If you use that inside a rule, it works fine! Already implemented for ALL commands (see example: https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#8b-adjust-the-value-of-a-sensor-and-send-it-by-mqtt)

Using your example but in a rule:
```
rule
  on event#setvar do backlog var1 2;var2 3 endon
  on event#test do add1 %var2% endon
```

Console Output.
```
17:40:46 CMD: rule on event#setvar do backlog var1 2;var2 3 endon on event#test do add1 %var2% endon
17:40:46 SRC: WebConsole from 192.168.1.131
17:40:46 RSL: Topic Recibido /rule, Tamaño de Datos 81, Datos on event#setvar do backlog var1 2;var2 3 endon on event#test do add1 %var2% endon
17:40:46 RSL: Grupo 0, Índice 1, Comando RULE, Datos on event#setvar do backlog var1 2;var2 3 endon on event#test do add1 %var2% endon
17:40:46 MQT: stat/living/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":430,"Rules":"on event#setvar do backlog var1 2;var2 3 endon on event#test do add1 %var2% endon"}
17:40:47 CFG: Grabado a la flash en 3F5, Conteo 87, Bytes 3584
17:40:52 CMD: event setvar
17:40:52 SRC: WebConsole from 192.168.1.131
17:40:52 RSL: Topic Recibido /event, Tamaño de Datos 6, Datos setvar
17:40:52 RSL: Grupo 0, Índice 1, Comando EVENT, Datos setvar
17:40:52 MQT: stat/living/RESULT = {"Event":"Done"}
17:40:52 RUL: EVENT#SETVAR performs "backlog var1 2;var2 3"
17:40:52 SRC: Rule
17:40:52 RSL: Topic Recibido /backlog, Tamaño de Datos 13, Datos var1 2;var2 3
17:40:52 RSL: Grupo 0, Índice 1, Comando BACKLOG, Datos var1 2;var2 3
17:40:52 SRC: Backlog
17:40:52 RSL: Topic Recibido /var1, Tamaño de Datos 1, Datos 2
17:40:52 RSL: Grupo 0, Índice 1, Comando VAR, Datos 2
17:40:52 MQT: stat/living/RESULT = {"Var1":"2"}
17:40:53 SRC: Backlog
17:40:53 RSL: Topic Recibido /var2, Tamaño de Datos 1, Datos 3
17:40:53 RSL: Grupo 0, Índice 2, Comando VAR, Datos 3
17:40:53 MQT: stat/living/RESULT = {"Var2":"3"}
17:40:58 CMD: event test
17:40:58 SRC: WebConsole from 192.168.1.131
17:40:58 RSL: Topic Recibido /event, Tamaño de Datos 4, Datos test
17:40:58 RSL: Grupo 0, Índice 1, Comando EVENT, Datos test
17:40:58 MQT: stat/living/RESULT = {"Event":"Done"}
17:40:58 RUL: EVENT#TEST performs "add1 3"
17:40:58 SRC: Rule
17:40:58 RSL: Topic Recibido /add1, Tamaño de Datos 1, Datos 3
17:40:58 RSL: Grupo 0, Índice 1, Comando ADD, Datos 3
17:40:58 MQT: stat/living/RESULT = {"Add1":"5.00"}
```
