### ISSUE TITLE
How to Update from 5.10 FW

### ISSUE THREAD

**Issue by freaktech** [arendst/Sonoff-Tasmota#4421]
How can i update a already installed Touch switch to the latest firmware without to loose the settings (wifi ,impulse time...)

if i press OTA Update

nothing will start
thx
tom

**Comment by Jason2866** [comment]
Wiki:
https://github.com/arendst/Sonoff-Tasmota/wiki/Upgrade

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by freaktech** [comment]
thank you for the link

ok i found the lates bin in german

but i dont understand what next

just select the file and update?

what means 
Initiate the upgrade via the serial/MQTT/web command 
?!?! i dont understand this  commands


and after the update will my settings be in the device?
wlan,—

thank you

tom

**Comment by freaktech** [comment]
worls easier as o thought

wit this video

https://www.youtube.com/watch?v=lSq19iolFas


thx
tom
