### ISSUE TITLE
BW-SHP2 dead after flashed

### ISSUE THREAD

**Issue by vpomax** [arendst/Sonoff-Tasmota#4435]
![20181122_194604](https://user-images.githubusercontent.com/33105151/48973192-17a10c80-f03a-11e8-9994-702916f26d09.jpg)
![20181122_194505](https://user-images.githubusercontent.com/33105151/48973195-31425400-f03a-11e8-8a6a-6b19da7ecc1f.jpg)

I flashed a Blitzwolf SHP2 (not a v. 2.3) using Wndows 10 with Arduino IDE 1.8.7. and a USB to TTL programmer with last version of Tasmota firmware 6.3.0 just downloaded.
Flashing ended succesfully without errors... but after the SHP2 do not seem alive.
If I plug it to power plug its led flashs for less then a second and then it turn off.
If I pull down its button anything happens.
I tried to reflash it but with the same result
What's happened?

**Comment by andrethomas** [comment]
Please try the latest codebase and revert back to us.

You may compile, but I would recommend using a pre-compiled binary from http://thehackbox.org/tasmota/

The sonoff.bin one should work fine - We are now on version 6.3.0.12 in the open development codebase.

**Comment by Jason2866** [comment]
@andrethomas 
I have this device too. It does work with 6.3.0

**Comment by vpomax** [comment]
What version of tasmota I should use for it?

**Comment by andrethomas** [comment]
sonoff.bin will work fine.

**Comment by vpomax** [comment]
I have windows 100 and I have installed python 3.6... how can I use esptool.py?

**Comment by ascillato** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#esptool-usage

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
