### ISSUE TITLE
DHT11 more than 3 pcs on ESP8266 not working

### ISSUE THREAD

**Issue by byt3w4rri0r** [arendst/Sonoff-Tasmota#4437]
**Describe the bug**
DHT11 more than 3 pcs on ESP8266 not working

- [X] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : NodeMCU Dev Board
- [X] _Development/Compiler/Upload tools used_ : sonoff.ino, Arduino IDE
- [X] _If a pre-compiled release or development binary was used, which one?_ : not used
- [X] _You have tried latest release or development binaries?_ : Installed latest Stable
- [X] _Provide the output of command_``status 0`` :
```
00:11:29 MQT: stat/TempNode/STATUS = {"Status":{"Module":18,"FriendlyName":["TempNode"],"Topic":"TempNode","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:11:29 MQT: stat/TempNode/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:04:27","StartupUTC":"2018-11-24T23:07:02","Sleep":0,"BootCount":10,"SaveCount":18,"SaveAddress":"3FA000"}}
00:11:29 MQT: stat/TempNode/STATUS2 = {"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018-11-24T22:46:56","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
00:11:29 MQT: stat/TempNode/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["WIFINAME",""],"TelePeriod":300,"SetOption":["00008009","55818000","00000000"]}}
00:11:29 MQT: stat/TempNode/STATUS4 = {"StatusMEM":{"ProgramSize":522,"Free":2548,"Heap":19,"ProgramFlashSize":4096,"FlashSize":4096,"FlashMode":2,"Features":["00000809","0FDAE794","000183A0","23B617CC","00003BC0"]}}
00:11:29 MQT: stat/TempNode/STATUS5 = {"StatusNET":{"Hostname":"TempNode-7055","IPAddress":"XX.XX.XX.XX","Gateway":"XX.XX.XX.XX","Subnetmask":"XX.XX.XX.XX","DNSServer":"XX.XX.XX.XX","Mac":"XX.XX.XX.XX","Webserver":2,"WifiConfig":5}}
00:11:29 MQT: stat/TempNode/STATUS6 = {"StatusMQT":{"MqttHost":"XX.XX.XX.XX","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_B97B8F","MqttUser":"MQTT-SERVERNAME","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:11:29 MQT: stat/TempNode/STATUS7 = {"StatusTIM":{"UTC":"Sat Nov 24 23:11:29 2018","Local":"Sun Nov 25 00:11:29 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"08:14","Sunset":"17:00"}}
00:11:29 MQT: stat/TempNode/STATUS10 = {"StatusSNS":{"Time":"2018-11-25T00:11:29","ANALOG":{"A0":2},"DHT11-04":{"Temperature":24.1,"Humidity":39.0},"DHT11-05":{"Temperature":22.9,"Humidity":43.0},"DHT11-14":{"Temperature":23.8,"Humidity":35.0},"TempUnit":"C"}}
00:11:29 MQT: stat/TempNode/STATUS11 = {"StatusSTS":{"Time":"2018-11-25T00:11:29","Uptime":"0T00:04:27","Wifi":{"AP":1,"SSId":"WIFINAME","BSSId":"MACADRESSE","Channel":1,"RSSI":100}}}
```

**To Reproduce**
Choose more than 3 DHT11 on Generic Board, the 4th one will not be shown in the WebUI nether it will get sent via MQTT.

**Expected behaviour**
I expected to see all 4 DHT11 in the WebUI and to get the Data of all 4 DHT11 via MQTT.

{"Time":"2018-11-25T00:20:49","ANALOG":{"A0":1},"DHT11-04":{"Temperature":23.6,"Humidity":38},"DHT11-05":{"Temperature":23.3,"Humidity":42},"DHT11-12":{"Temperature":24.4,"Humidity":39},"TempUnit":"C"}

the 4th one is missing…

**Screenshots**
<img width="349" alt="screenshot 2018-11-25 at 00 20 15" src="https://user-images.githubusercontent.com/42189234/48973791-1bd42680-f048-11e8-9e6f-a2d0cf258933.png">

<img width="395" alt="screenshot 2018-11-25 at 00 28 53" src="https://user-images.githubusercontent.com/42189234/48973833-2216d280-f049-11e8-9c8b-a0c7d5d766b9.png">

wbr Leo

**Comment by ascillato2** [comment]
Hi,

You are right. The limit by design is 3 DHT sensors. It is not a bug. See the code at:

https://github.com/arendst/Sonoff-Tasmota/blob/bd8bd514ed21c78100756d143eae5f5c23f35a9b/sonoff/xsns_06_dht.ino#L31

Thanks
