### ISSUE TITLE
Question: Combine WS2812 and relays

### ISSUE THREAD

**Issue by martin072** [arendst/Sonoff-Tasmota#4439]
Question, Is it possible to combine, 3 Relays and 1 WS2812 in the same unit and also use their respective toggle buttons?

**Comment by Jason2866** [comment]
Which device? In general yes that is possible, but it depends on device....

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by martin072** [comment]
Thanks. Device would be a Wemos D1 Mini
