### ISSUE TITLE
4ch pro double press and hold buttons

### ISSUE THREAD

**Issue by fsmoreno** [arendst/Sonoff-Tasmota#4442]
Hello,
I have a sonoff 4ch pro with tasmota
I want to setup a multifunction buttons 
I want to setup a double press and a hold buttons on every relay but not work.

**Comment by Jason2866** [comment]
see here:
https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#13-toggle-a-relay-only-when-holding-the-button-for-2-seconds
and here
https://github.com/arendst/Sonoff-Tasmota/wiki/Understanding-SwitchMode-and-SwitchTopic

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
