### ISSUE TITLE
Tasmota keeps crashing

### ISSUE THREAD

**Issue by Vrnreg** [arendst/Sonoff-Tasmota#4445]
Hello there,

> - [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
> - [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
> - [X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
> - [X] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
> - [X] Development/Compiler/Upload tools used : ESPEASY,  ATOM, Tasmota 6.2.1
> - [X] Hardware used : Sonoff 4CH PRO R2
> - [ ] If a pre-compiled release or development binary was used, which one? : No
> - [X] You have tried latest release or development binaries? : Not yet. Used 6.2.1
> - [X] Provide the output of command ``status 0`` :

`00:07:23 CMD: status 0
00:07:23 MQT: stat/pro9/STATUS = {"Status":{"Module":8,"FriendlyName":["Sonoff","Sonoff2","Sonoff3","Sonoff4"],"Topic":"pro9","ButtonTopic":"pro9","Power":6,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":1}}
00:07:23 MQT: stat/pro9/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Power on","Uptime":"0T00:07:24","StartupUTC":"","Sleep":0,"BootCount":1197,"SaveCount":3166,"SaveAddress":"F6000"}}
00:07:23 MQT: stat/pro9/STATUS2 = {"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-10-21T14:31:25","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
00:07:23 MQT: stat/pro9/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Hub 2.4","Hub 2.4"],"TelePeriod":300,"SetOption":["00008029","55818000","00000000"]}}
00:07:24 MQT: stat/pro9/STATUS4 = {"StatusMEM":{"ProgramSize":472,"Free":528,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","24000000","23B617CE","00000000"]}}
00:07:24 MQT: stat/pro9/STATUS5 = {"StatusNET":{"Hostname":"pro9-5572","IPAddress":"192.168.0.128","Gateway":"192.168.43.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.43.1","Mac":"60:01:94:A3:55:C4","Webserver":2,"WifiConfig":2}}
00:07:24 MQT: stat/pro9/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.120","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_A355C4","MqttUser":"jaguar","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:07:24 MQT: stat/pro9/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 00:07:24 1970","Local":"Thu Jan 01 00:07:24 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":1,"Sunrise":"07:43","Sunset":"16:03"}}
00:07:24 MQT: stat/pro9/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:07:24","Switch1":"ON","Switch2":"OFF","Switch3":"OFF","Switch4":"ON"}}
00:07:24 MQT: stat/pro9/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:07:24","Uptime":"0T00:07:24","Vcc":3.113,"POWER1":"OFF","POWER2":"ON","POWER3":"ON","POWER4":"OFF","Wifi":{"AP":1,"SSId":"Hub 2.4","RSSI":68,"APMac":"50:C7:BF:FB:63:F7"}}}`

I’m using few tasmotized Sonoff 4CH pro R2’s for my home and I’m using the below settings.

SwitchMode1 7
SwitchMode2 7
SwitchMode3 7
SwitchMode4 7

Switchretain OFF
Buttonretain OFF
POWERONSTATE 3
POWERRETAIN ON

I have soldered the ends of the push buttons to make it work with physical rocker switches. However after sometime the relays won’t work even if I change them using the soft-buttons on Tasmota Web UI or the rocker switches. It’s like the tasmota is stuck. Restarting the device also doesn’t help. Finally, I have to remove the Phase or Neutral that powers the sonoff and restart it to make it work. Did anyone face this issue? Any help will be highly appreciated.

I’m using Tasmota version 6.2.1 .

Regards,
Toms

**Comment by ascillato2** [comment]
Duplicated issue
