### ISSUE TITLE
dht22 not show hum / temp

### ISSUE THREAD

**Issue by lpt2007** [arendst/Sonoff-Tasmota#4452]
I flashed version 6.3.0.12 on sonoff basic. Now no temp & hum. I have dht22 on gpio14 and I selected 3 SI7021. any idea?

**Comment by ascillato** [comment]
Please, provide the troubleshooting template completed in order to have information for properly help you. Thanks.

**Comment by ascillato2** [comment]
Troubleshooting template missing. Please complete it in order to have information for properly help you. Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
