### ISSUE TITLE
Sonoff POW Day/Night consumption

### ISSUE THREAD

**Issue by mr-const** [arendst/Sonoff-Tasmota#446]
Is there any way to differentiate power consumption during day/night time? I have two-zone tariff at home, so since 23 until 07 my energy price has 50% cut. It would be great to see how energy is distributed between this times.

**Comment by davidelang** [comment]
no, you would need to do this in your home automation software that the data is 
reported to.

**Comment by mihalski** [comment]
I calculate cost in my home automation software and this could easily take into account tariffs.. Our tariffs are so mysterious that nobody knows how they work so I just assume maximum cost all the time.
