### ISSUE TITLE
Can Amazon branded Smart Plug be Tasmotized

### ISSUE THREAD

**Issue by badabing2005** [arendst/Sonoff-Tasmota#4464]
I searched but didn't find any relevant topics.
Can Amazon branded Smart plugs be Tasmotized?
Link to the product: https://www.amazon.ca/gp/product/B077Y7TBHQ/

Sorry if I missed a discussion about it.

Thanks
BB

**Comment by ascillato** [comment]
Hi,

If it has an ESP8266 chip, answer is yes. If it has not an ESP8266 chip, the answer is no.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by mkormendy** [comment]
What about if it can be tuya-converted?

**Comment by meingraham** [comment]
I doubt it has a Tuya Wi-Fi module in it. On a Tuya ESP based module with Tuya firmware is compatible with Tuya-Convert. And then only if Tuya hasn't changed it's encryption to make the Tuya-Convert back obsolete.

**Comment by mkormendy** [comment]
@meingraham I guess I'm asking if this device can be controlled with the smart life app? If it can, then it's possible that it can be tuya-converted, barring all of your warnings.

**Comment by meingraham** [comment]
If the device can be controlled with the SmartLife app, then the device has a Tuya module inside it. You cannot make the Tuya app control a device that is not Tuya internally. Amazon's devices cannot be paired to the Tuya app.

But, it would cost you nothing but some of your time to attempt it. You can order a plug. Try to Tuya-Convert it. If Tuya_Convert "sees" the Amazon plug and flashes it, you're golden. If not, just return the plugs.
