### ISSUE TITLE
HomeAssistant discovery topic reversed

### ISSUE THREAD

**Issue by lanefu** [arendst/Sonoff-Tasmota#4468]
despite all my other mqtt settings being `%prefix%/%topic%` HomeAssistant discovery is publishing the command topic as `%topic%/%prefix%`

I think the logic from here needs to be inverted or removed.

https://github.com/arendst/Sonoff-Tasmota/blame/development/sonoff/xdrv_12_home_assistant.ino#L431

I tried testing a build with that code commented out then homeassistant autodiscovery worked as expected.  I didn't want to submit a PR because I didn't understand the intent of that code block.  

@emontnemery any thoughts?

**Comment by emontnemery** [comment]
It's intentional that Hass autodiscovery overrides the preset topic with `%prefix%/%topic%` However, I forgot to save settings and resubcribe when topic was changed.

I'll try to submit a fix in a couple of days.

**Comment by emontnemery** [comment]
@lanefu #4471 should solve your issue.
