### ISSUE TITLE
Somebody use kinetic doorbell to RF Bridge (modded radio FW)?

### ISSUE THREAD

**Issue by vampywiz17** [arendst/Sonoff-Tasmota#4469]
Hello there!

Somebody use Kinetic doorbell (like this https://goo.gl/fg1jXd) If yes, what is the type that working well?

Now i use  a delight 55339 Kinetic doorbell, but the RF bridge not see this. I would like to buy a new one, but not want to buy a unsupported one again.

**Comment by vampywiz17** [comment]
@gappleby  waht do you think, it is working? 

https://goo.gl/MXnNAC
 
https://ae01.alicdn.com/kf/HTB1HDUwa4WYBuNjy1zkq6xGGpXaE/KERUI-EU-US-UK-Plug-32-Songs-Optional-Waterproof-Touch-Button-Smart-Home-Welcome-Doorbell-Alarm.jpg_640x640.jpg

**Comment by vampywiz17** [comment]
Ok i order 1 button (battery) and a kinetic set (1x kinetic button + 1x  indoor base station)

If kinetic button not working, i will use the battery one. (I hope that is possible to pair the battery button to base station. If i see correctly, they use fully same)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
