### ISSUE TITLE
Feature request - On/off times with random variation

### ISSUE THREAD

**Issue by bigcookie** [arendst/Sonoff-Tasmota#4479]
Hello, I am looking for a solution to replace the typical on/off scenarios which are tightly programmed to turn a light e.g. in the evening on/off to simulate people living in a house while you are away.
It would be great, if one can define a time window and the device picks a on/off time within the tie window, not repeating the same switching time as the day before. To make things simpler, it is sufficient to vary in 5 or 10 minute steps...
I can help specifying more (for example how the handling works in case an on and off time is set in an overlapping time window etc). Just wanted to get some feedback first.

Thanks for the great development/project!!!

**Comment by ascillato** [comment]
Hi, it is already implemented.

Please, using the Tasmota webmenu, go to configuration, then go to timers and there it is a random +/- to choose.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
