### ISSUE TITLE
SONOFF TH10 with tasmota 6.3.0 not shownig temp or humidity on its web interface

### ISSUE THREAD

**Issue by mmatesic01** [arendst/Sonoff-Tasmota#4483]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used : EASEASY mega
- [x ] Hardware used : SONOFF TH10
- [ ] If a pre-compiled release or development binary was used, which one? :  
- [ x] You have tried latest release or development binaries? : release 6.3.0
- [x ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
17:01:56 CMD: status 0
17:01:56 MQT: stat/TH10_01/STATUS = {"Status":{"Module":4,"FriendlyName":["Sonoff"],"Topic":"TH10_01","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
17:01:56 MQT: stat/TH10_01/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-basic.bin","RestartReason":"Software/System restart","Uptime":"0T00:08:25","StartupUTC":"2018-11-29T15:53:31","Sleep":0,"BootCount":88,"SaveCount":110,"SaveAddress":"F6000"}}
17:01:56 MQT: stat/TH10_01/STATUS2 = {"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018-10-30T17:34:51","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
17:01:56 MQT: stat/TH10_01/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ASUS_SW",""],"TelePeriod":300,"SetOption":["00008009","55818000","00000000"]}}
17:01:56 MQT: stat/TH10_01/STATUS4 = {"StatusMEM":{"ProgramSize":424,"Free":576,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0F082780","000083A0","21021706","000001C0"]}}
17:01:56 MQT: stat/TH10_01/STATUS5 = {"StatusNET":{"Hostname":"TH10_01-0526","IPAddress":"192.168.2.25","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"DC:4F:22:43:A2:0E","Webserver":2,"WifiConfig":5}}
17:01:56 MQT: stat/TH10_01/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.20","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_43A20E","MqttUser":"mmatesic","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
17:01:56 MQT: stat/TH10_01/STATUS7 = {"StatusTIM":{"UTC":"Thu Nov 29 16:01:56 2018","Local":"Thu Nov 29 17:01:56 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1,"Sunrise":"08:19","Sunset":"16:57"}}
17:01:56 MQT: stat/TH10_01/STATUS10 = {"StatusSNS":{"Time":"2018-11-29T17:01:56"}}
17:01:56 MQT: stat/TH10_01/STATUS11 = {"StatusSTS":{"Time":"2018-11-29T17:01:56","Uptime":"0T00:08:25","Vcc":3.196,"POWER":"OFF","Wifi":{"AP":1,"SSId":"ASUS_SW","BSSId":"74:D0:2B:87:2F:70","Channel":1,"RSSI":100}}}
17:02:00 MQT: tele/TH10_01/UPTIME = {"Time":"2018-11-29T17:02:00","Uptime":"0T00:08:29"}


Have set everything I have to Module: SONOFF TH and GPIO14 Sensor on 02 AM2301. All others GPIO are set to none.
Did several saves and restarts no output shown on screen.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
In web config frontend ?
![image](https://user-images.githubusercontent.com/24528715/49235846-3bc66a00-f3fb-11e8-9c94-39471090bc19.png)
How looks your main screen?
![image](https://user-images.githubusercontent.com/24528715/49235901-5ef11980-f3fb-11e8-89c2-bb28105b5105.png)

**Comment by mmatesic01** [comment]
I am having trouble attaching images  (I am a noob) so I'l to to illustrate to you.
Instead "generic module"  as you have, I have "sonoff TH module" under it "Sonoff" and under it no values just big OFF, the status of switch.
In configuration module I have selected and saved GPIO14 Sensor on 02 AM2301
Sensor plug is all the way in (with a click). I'll try to measure voltage as you suggested.

**Comment by mmatesic01** [comment]
I measured voltage on sensor while pluged in and TH powered on.
voltage between Vcc and GND ii 3.3V
voltage between OUT and GND also 3.3V.  Should I be worred about this value?
Wiring on sensor is OK and it is not in contact between wires. Could itbe that the TH10 plug is faulty?

**Comment by Jason2866** [comment]
Disconnect from AC mains. Open sonoff. Measure if the signal from out goes to GPIO 14
Just to be sure it s not the firmware. Upgrade via OTA to http://thehackbox.org/tasmota/sonoff.bin

**Comment by mmatesic01** [comment]
I have check all 4 contacts between sensor and plug 4 soldered contacts. Connections are good, no line is in direct contact with another. I'll try OTA.

**Comment by mmatesic01** [comment]
Thank you. Upgrade through OTA did the trick. 
Now I see temp and humidity.  Cheers.

**Comment by karpaz** [comment]
Sorry for write to dead issue. I will try to help others with my experience... The seller says that I ordered AM2301, but when i opened case, then I saw SI7021, when changed on Tasmota config, started working ! :))
