### ISSUE TITLE
Syslog buffer

### ISSUE THREAD

**Issue by timstanley1985** [arendst/Sonoff-Tasmota#4485]
Hi,

I am trying to use the tasmota syslog feature to export log messages to an external rsyslog daemon to try and debug an intermittent WiFi issue.  The syslog feature is working great but the log messages relevant to the issue I am suffering are being dropped because there is a no WiFi connection for a few seconds.  Would it be possible for tasmota to buffer log messages if there is no active WiFi connection and then send these to the syslog server once a Wi-Fi connection has been re-established?

**Comment by ascillato2** [comment]
Hi,

Your idea is very good, but there is not enough memory for a large log. Sorry.

May be you can use the serial log.
