### ISSUE TITLE
DIGOO DG-SP202 3720W Dual Outlet Smart Socket @ tasmota?

### ISSUE THREAD

**Issue by on-off-on** [arendst/Sonoff-Tasmota#4487]
hi, has someone checked if tasmota run´s on this well designed EU dual outlet socket? 

DIGOO DG-SP202 / DIGOO NX-SP202  

3720W Dual Outlet Smart Socket ( banggood id /item no:  1375323 )

According to details on the website -both sockets can be ontrolled separately(!)

**Comment by ascillato** [comment]
If that device has an esp8266 may be Tasmota works, but if it has another controller, Tasmota will not work.

You will need to buy one to test. ;)

**Comment by blakadder** [comment]
Its still on preorder so I guess noone has access to it yet. 
I think the chances are high it can be supported.

**Comment by ascillato2** [comment]
Thanks for sharing your ideas. When someone have access to this device, we can retake this to see if it can be supported

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by Jason2866** [comment]
It is on sale now for 14,39€

**Comment by DocZoid** [comment]
Did anyone manage to flash Tasmota on that device?

**Comment by sciipiio** [comment]
also curious about this. nice outlet...

**Comment by markus1540** [comment]
https://github.com/arendst/Sonoff-Tasmota/pull/4891
