### ISSUE TITLE
Request: dynamic relays and keys

### ISSUE THREAD

**Issue by aferraz** [arendst/Sonoff-Tasmota#45]
Hi,
 this is a great firmware, my congratulations.
I wanted to ask: why not also make the relays and keys configurable from the web page ?

Best Regards
 Alessandro

**Comment by arendst** [comment]
Too much variables I have to check to keep it functional.

**Comment by aferraz** [comment]
@arendst thanks you for the response, I understand your point.
Instead the possibility to read an analog sensor ?
I'm using your firmware on nodemcu and it works perfectly, it might be convenient to be able to connect other types of sensors or, for example, a tft display. 
Maybe it is already possible but I do not know how to do.

Best Regards
 Alessandro

**Comment by mihalski** [comment]
A TFT display isn't a sensor.. It's an output device.

I expect that for the time being this sort of thing is probably outside the scope of this firmware. Especially with its intent to target Sonoff devices which have very limited storage and memory unlike more generic ESP8266 modules which greatly vary in those aspects.
