### ISSUE TITLE
Request: PowerOnState 5 - Retrieving info from Domoticz

### ISSUE THREAD

**Issue by mrohner** [arendst/Sonoff-Tasmota#450]
Problem description:
The Sonoff was down due to a power failure. In the meantime Domoticz had issued a POWER on command (from a set timer). When the Sonoff powers on again the relais is either off or on based on current PowerOnState settings .

Request: 
Implement a PowerOnState 5 - Turn relay(s) on or off based on current state in Domoticz.
After boot up the Sonoff Device would have to issue a GET request to the Domoticz server to obtain the information through /json.htm?type=devices&rid=IDX.

**Comment by arendst** [comment]
Nice idea but... I only communicate with Domoticz via MQTT so the http /json.htm method is not available (I do not want to know the IP address of the Home Automation software).

Suggestion: After Sonoff powers on it will send it's status to domoticz via MQTT. Try to capture it in Domoticz and send the correct state back to Sonoff.
