### ISSUE TITLE
Sonoff 4ch Pro r2 inching mode. unexpected turn on after reboot

### ISSUE THREAD

**Issue by netmaster01** [arendst/Sonoff-Tasmota#4504]
I have ramdon turns on in channel 2 and 4 when the network is down or is a power down, or sonoff restart. they are configured in inching mode. channel 1 and 3 does not show this problem, they are configured in normal operation 

here the last logs that i managed to capture after restart

00:00:00 CFG: Saved to flash at F6, Count 2262, Bytes 2560
00:00:00 WIF: Checking connection...
00:00:00 WIF: Attempting connection...
00:00:00 WIF: Connecting to AP1 NetXtreme in mode 11N as sonoffgg1-6488...
00:00:01 WIF: Checking connection...
00:00:01 WIF: Attempting connection...
00:00:02 WIF: Checking connection...
00:00:02 WIF: Attempting connection...
00:00:04 WIF: Checking connection...
00:00:04 WIF: Attempting connection...
00:00:04 APP: Button2 level 1-0
00:00:04 RSL: stat/sonoffgg1/RESULT = {"POWER2":"ON"}
00:00:04 RSL: stat/sonoffgg1/POWER2 = ON
00:00:04 APP: Button4 level 1-0
00:00:04 RSL: stat/sonoffgg1/RESULT = {"POWER4":"ON"}
00:00:04 RSL: stat/sonoffgg1/POWER4 = ON
00:00:04 APP: (UTC) Sun Dec 02 04:14:59 2018, (DST) Sun Mar 25 02:00:00 2018, (STD) Sun Oct 28 03:00:00 2018
05:15:00 WIF: Checking connection...
05:15:00 WIF: Connected
05:15:00 DNS: Initialized
05:15:00 HTP: Web server active on sonoffgg1-6488.local with IP address 10.0.1.29
05:15:00 APP: Button2 level 0-1
05:15:00 RSL: stat/sonoffgg1/RESULT = {"POWER2":"OFF"}
05:15:00 RSL: stat/sonoffgg1/POWER2 = OFF
05:15:00 APP: Button4 level 0-1
05:15:00 RSL: stat/sonoffgg1/RESULT = {"POWER4":"OFF"}
05:15:00 RSL: stat/sonoffgg1/POWER4 = OFF
05:15:01 MQT: Attempting connection...
05:15:06 MQT: Connect failed to 10.0.1.10:1883, rc -2. Retry in 10 sec
05:15:17 MQT: Attempting connection...
05:15:17 MQT: Connected
05:15:17 MQT: tele/sonoffgg1/LWT = Online (retained)
05:15:17 MQT: cmnd/sonoffgg1/POWER = 
05:15:17 MQT: Subscribe to cmnd/sonoffgg1/#
05:15:17 MQT: Subscribe to cmnd/sonoffs/#
05:15:17 MQT: Subscribe to cmnd/DVES_A35958/#
05:15:17 MQT: tele/sonoffgg1/INFO1 = {"Module":"Sonoff 4CH Pro","Version":"5.13.1b","FallbackTopic":"DVES_A35958","GroupTopic":"sonoffs"}
05:15:17 MQT: tele/sonoffgg1/INFO2 = {"WebServerMode":"Admin","Hostname":"sonoffgg1-6488","IPAddress":"10.0.1.29"}
05:15:17 MQT: tele/sonoffgg1/INFO3 = {"RestartReason":"Fatal exception:3 flag:2 (EXCEPTION) epc1:0x40246923 epc2:0x00000000 epc3:0x00000000 excvaddr:0x40000002 depc:0x00000000"}
05:15:18 MQT: stat/sonoffgg1/RESULT = {"POWER1":"OFF"}
05:15:18 MQT: stat/sonoffgg1/POWER1 = OFF
05:15:18 MQT: stat/sonoffgg1/RESULT = {"POWER2":"OFF"}
05:15:18 MQT: stat/sonoffgg1/POWER2 = OFF
05:15:18 MQT: stat/sonoffgg1/RESULT = {"POWER3":"OFF"}
05:15:18 MQT: stat/sonoffgg1/POWER3 = OFF
05:15:18 MQT: stat/sonoffgg1/RESULT = {"POWER4":"OFF"}
05:15:18 MQT: stat/sonoffgg1/POWER4 = OFF
05:15:25 WIF: Checking connection...
05:15:25 WIF: Connected
05:15:25 MQT: tele/sonoffgg1/STATE = {"Time":"2018-12-02T05:15:25","Uptime":"0T00:00:30","Vcc":3.486,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","Wifi":{"AP":1,"SSId":"NetXtreme","RSSI":100,"APMac":"14:CC:20:8E:C9:E6"}}
05:15:42 APP: Button1 level 1-0
05:15:42 MQT: stat/sonoffgg1/RESULT = {"POWER1":"ON"}
05:15:42 MQT: stat/sonoffgg1/POWER1 = ON
05:15:43 APP: Button1 level 0-1
05:15:45 WIF: Checking connection...
05:15:45 WIF: Connected
05:15:46 APP: Button4 level 1-0
05:15:46 MQT: stat/sonoffgg1/RESULT = {"POWER4":"ON"}
05:15:46 MQT: stat/sonoffgg1/POWER4 = ON
05:15:46 APP: Button4 level 0-1
05:15:47 APP: Button4 level 1-0
05:15:47 MQT: stat/sonoffgg1/RESULT = {"POWER4":"OFF"}
05:15:47 MQT: stat/sonoffgg1/POWER4 = OFF
05:15:48 APP: Button1 level 1-0
05:15:48 MQT: stat/sonoffgg1/RESULT = {"POWER1":"OFF"}
05:15:48 MQT: stat/sonoffgg1/POWER1 = OFF
05:15:48 APP: Button1 level 0-1
05:16:05 WIF: Checking connection...
05:16:05 WIF: Connected
05:16:25 WIF: Checking connection...
05:16:25 WIF: Connected
05:16:45 WIF: Checking connection...
05:16:45 WIF: Connected
05:17:05 WIF: Checking connection...
05:17:05 WIF: Connected
05:17:25 WIF: Checking connection...
05:17:25 WIF: Connected
05:17:45 WIF: Checking connection...
05:17:45 WIF: Connected
05:17:45 HTP: Console
05:17:58 HTP: Main Menu
05:17:59 HTP: Console

_Originally posted by @netmaster01 in https://github.com/arendst/Sonoff-Tasmota/issue_comments#issuecomment-443480659_

**Comment by ascillato2** [comment]
When you have time, please complete the troubleshooting template. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
