### ISSUE TITLE
PWM not clear to me

### ISSUE THREAD

**Issue by mrbgfromv** [arendst/Sonoff-Tasmota#4511]
I'm on an WemosD1 mini and compiled Tasmota (Version 6.3.0-2_4_2) under the Arduino IDE - it works nicely.
Is it possible to configure 3 GPIOs as PWM and assign values to them so that if the device is turned on, certain voltages appear on these GPIOs? And finally these GPIOs should be turned on/off by a timer.
I don't get the concept of PWM with Tasmota here. I used the web console to understand/debug:
"Pwm" returns unkown command
"SetOption15" returns ON
"Gpio" returns
"GPIO0":"0 (None)","GPIO1":"0 (None)","GPIO2":"0 (None)","GPIO3":"0 (None)","GPIO4":"37 (PWM 1)","GPIO5":"39 (PWM 3)","GPIO12":"0 (None)","GPIO13":"0 (None)","GPIO14":"0 (None)","GPIO15":"41 (PWM 5)","GPIO16":"0 (None)"
If I assign more than 2 PWM x in the device configuration (3 in my case), the number of sliders of the pwm controls on the main device web site reduce from 2 to 1 but I expected 3 sliders...
I'm not really sure what I'm doing here, so any help would be appreciated.

Thanks!

**Comment by ascillato** [comment]
Hi

Please address this questions to the Tasmota Support Chat, There we can do a Q&A more dynamic to help you (https://discord.gg/Ks2Kzd4)

Github issues are meant for Tasmota BUG reports and tracking. Thanks.

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
