### ISSUE TITLE
Feature: fade WS2812 sequentially

### ISSUE THREAD

**Issue by dimalo** [arendst/Sonoff-Tasmota#4512]
**Have you look for this feature in other issues and in the wiki?**
Yes and didn't find something.

**Is your feature request related to a problem? Please describe.**
I am enjoying Tasmota quite a while now with a lot of Sonoffs - THANK YOU.
I have some Sonoff SVs controlling WS2812-like LED strips.
I would like to have a fading effect when turning it on. 

**Describe the solution you'd like**
Instead of fading all LEDs at once, it would look very nice if at first just one lid up, then 2 then 3... Depending on the fading speed the whole strip would come to life from left to right. Or from right to left. Or even giving it a starting point and then it shall fade to the left and right from the starting point.

In other words: The fading effect should not be accomplished by controlling the brightness of all LEDs, but the number of lid LEDs. 
This can also be enhanced with the number and the brightness of each LED.

I imagine three new options:
1. SeqFade: boolean to activate the fading method
2. SeqFadeMode: 0=left to right, 1=right to left, 2=both directions, 3=both directions inverted
3. SeqFadeStart (Only for SeqFadeMode=2): Number, which is < Pixel count, defining LED to start the fade from - if Pixel count % 2 == 0 then first animation frame lights up SeqFadeStart and SeqFadeStart + 1 (see example below)

**Describe alternatives you've considered**
The alternative would be to send the strip a lot of PIXELS commands, which doesn't give a nice animation and doesn't give the option of fading direction.

**Additional context**
Here is an example showing the state of a 10 LED strip in each animation frame:
```
x -> ON
- -> OFF

Left to Right:
----------
x---------
xx--------
xxx-------
xxxx------
xxxxx-----
xxxxxx----
xxxxxxx---
xxxxxxxx--
xxxxxxxxx-
xxxxxxxxxx

Right to Left:
----------
---------x
--------xx
-------xxx
------xxxx
-----xxxxx
----xxxxxx
---xxxxxxx
--xxxxxxxx
-xxxxxxxxx
xxxxxxxxxx

Both Directions with SeqFadeStart == 5:
----xx----
---xxxx---
--xxxxxx--
-xxxxxxxx-
xxxxxxxxxx


Both Directions inverted with SeqFadeStart == 5:
x--------x
xx------xx
xxx----xxx
xxxx--xxxx
xxxxxxxxxx
```
SeqFadeMode 2 and 3 should be executed either with half speed or with fading in brightness of each LED in 2 steps (0 -> 50% -> 100%)

I WOULD LOVE THAT FEATURE!

**Comment by ascillato2** [comment]
Nice idea. Added your request to the list of requested effects in the already open issue #3480

Thanks for sharing your ideas.
