### ISSUE TITLE
Toggle relay after long button press

### ISSUE THREAD

**Issue by calcipher49** [arendst/Sonoff-Tasmota#4522]
I am a little lost with various options for buttons (SetOption1, SetOption13 and SetOption32).
I wish this behaviour for relay linked with button:
- Toggle relay immediatly when button pressed (SetOption13 1, but not disable it with Setoption32)
- If button released promptly (before SetOption32 value), do not toggle relay at release
- If button kept pressed during long time (more than SetOption32 value), toggle relay at release

Not sure if possible.
If yes, thanks if someone can explain, if no, thanks to consider this feature.

**Comment by ascillato** [comment]
Yes, it is possible but as that is not the standard behaviour of Tasmota you need to tell Tasmota what you want to do. So for that you need to use the feature called Rules. Please check the example:

https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#16-using-an-external-button-with-single-press---double-press-and-hold

If you need further assistance, please find us in the Tasmota Support Chat.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
