### ISSUE TITLE
Standalone Feature (no wifi router needed)

### ISSUE THREAD

**Issue by xcom67** [arendst/Sonoff-Tasmota#4534]
Currently, I need to control a device, a gate. Using Internet is not recommended as one might accidentally opened the gate half way around the world not knowing that the gate opened.

Therefore, the one must be within visible distance of the gate, a few feet away using a mobile phone to open/close gate.

SonOff cannot do it, but Shelly stock can; unfortunately, Shelly is not available in my area (and would take 6 weeks to get due to the holidays), I am looking into a solution using SonOff + Tasmota.

However, upon installing Tasmota, there is no support for it. I need to have a wifi router for tasmota and mobile devices to connect. It is not an elegant / clean solution unfortunately.

Therefore I ask to have a Standalone mode wherein Tasmota would create its own permanent Password protected SSID accepting mobile devices to connect to it.

Thanks!

**Comment by ascillato** [comment]
Hi,

Sorry, not supported.

Duplicated issue: https://github.com/arendst/Sonoff-Tasmota/issues/3536

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
