### ISSUE TITLE
Trigger State of Sensor

### ISSUE THREAD

**Issue by danst0** [arendst/Sonoff-Tasmota#4537]
Hi,
I am using Tasmota on a Wemos D1 with a HC SR04 sensor. It is working fine, both in the Web interface and MQTT.
However I am still looking for a way to trigger a measurement via MQTT. Every now and then I get an update from the WEMOS via a tele-message, however, I seem to be unable to trigger a measurement myself.

Daniel

**Comment by ascillato2** [comment]
Hi,

Please, read the wiki, specially at rules where there are examples of that (https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#examples)

Also search in issues for more examples.

For support use the Tasmota Support Chat at https://discord.gg/Ks2Kzd4

Github issues are for bug reporting and also it is required to use the templates. Thanks.
