### ISSUE TITLE
Function request Status LED and wlan Turn off and better user interface for the timer

### ISSUE THREAD

**Issue by rothlive** [arendst/Sonoff-Tasmota#4539]
Hello

I've got some ideas for the Tasmota:
first of all :
LED Switchable or settings when the LEDs should light how.
I think the sonoff s20 has pretty bright and annoying flashing LEDs.
Would be good if you could turn them off or set when they light up.

Next:
Wlan can be switched off temporarily.
I use the sonoff as a timer. A night switch-off of the Wlan would be good. Or other options similar to a Fritzbox. https://service.avm.de/support/media/de/265.png
And as emergency switch for the Wlan could be a key code on the push button.

And the Last idea:
A better user interface for the timer.
At the moment you can only set 16 actions. Whereby you can always only set on or off.
Why not set one switch-on time per action and the switch-off time directly.

Or the same as https://service.avm.de/support/media/de/265.png 
With the clickable bars.

**Comment by ascillato** [comment]
Hi,

Thanks for sharing your ideas but are already implemented or not in the Tasmota scope. 

Leds: already implemented. See wiki at commands. Use ledstate command

Wifi: turning off is not the Tasmota scope that is home automation. See readme. 

Automatically turn off relays: already implemented. See wiki at commands. Use pulsetime command.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
