### ISSUE TITLE
sonofff SC Resolution

### ISSUE THREAD

**Issue by mrmin24** [arendst/Sonoff-Tasmota#454]
It seems that the SC always reports a round number even with a decimal. e.g. 25.0 degrees or 79.0% humidity. 
Is this a HW limitation or possibly the Atmel firmware?

**Comment by arendst** [comment]
Different items are in play here.
- The DHT11 sensor in the Sonoff SC is the most unpleasant sensor someone would ever want! Read up it's specs and you understand why it's humidity is more like a lottery and it's temperature should have been documented as Cold, Warm or Hot. In short it's temperature resolution is but 1 centigrade and it's humidity is also but 1 hPa.
- The Atmel software does no job in providing better resolution as there just is no better resolution for such a sensor.

If you want results without resolution just change them with command ``tempres 0`` and humres 0``

**Comment by mrmin24** [comment]
thanks
