### ISSUE TITLE
Tuya Dimmer in Home Assistant

### ISSUE THREAD

**Issue by h4nc** [arendst/Sonoff-Tasmota#4544]
Could someone provide a ready to use code of the tuya dimmer for home assistant?

Thanks!

**Comment by ascillato** [comment]
Hi,

You have several examples provided in the wiki at https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant

Please, check them and adapt it to your configuration. Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by h4nc** [comment]
Thanks!

**Comment by h4nc** [comment]
So I used this example and changed it to my configuration and it says "not available", but I can receive the mqtt data on MQTTBox.

<img width="830" alt="bildschirmfoto 2018-12-06 um 16 16 23" src="https://user-images.githubusercontent.com/25117255/49592785-50ae7a80-f972-11e8-8b53-a06ba23dfc8b.png">


```
  - platform: mqtt
    name: "Dimmer"
    command_topic: "cmnd/sonoff_dimmer/POWER"
    state_topic: "stat/sonoff_dimmer/RESULT"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/sonoff_dimmer/LWT"
    brightness_command_topic: "cmnd/sonoff_dimmer/Dimmer"
    brightness_state_topic: "stat/sonoff_dimmer/RESULT"
    brightness_scale: 100
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false
```

**Comment by h4nc** [comment]
Commenting the availability_topic out lets me control the device from ha. However it shows "unavailable" in the history. So something is wrong.
