### ISSUE TITLE
Need more than 4 FriendlyNames 

### ISSUE THREAD

**Issue by swampyclark** [arendst/Sonoff-Tasmota#4545]
Now that other boards are supported with greater GPIOs, need to be able to set more than 4 names.  IE 8 relays

**Comment by ascillato** [comment]
Hi,

Sorry, this is a duplicated issue:

Please read https://github.com/arendst/Sonoff-Tasmota/issues/3098 and https://github.com/arendst/Sonoff-Tasmota/issues/3273

Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
