### ISSUE TITLE
IO Expander MCP23S17 - near identical MCP23017

### ISSUE THREAD

**Issue by daninfuchs** [arendst/Sonoff-Tasmota#4550]
First and foremost, I love your firmware and I'm using it in many devices, including many "unsupported" ones out-of-the-box using Generic. Anyways!

I'll try to keep this short, as I tend to be overly verbose frequently. We'll start with the outline;

I'd like to see support for MCP23S17/etc added alongside MCP23017/etc in the supported sensor line, and due to their similarity the workload on you should be pretty minimal(?)...

Some background;

My next project has been forced on me. I'm rebuilding a hot tub control system (its thermal sensor ADC is cooked and replacement isn't viable) and Tasmota + Wemos D1 Mini wins. Rules + MQTT means I can do LOTS of automation, and lots of safety. I like this. The problem;

I've got a strip of unused MCP23S17 IO expanders. They're part-identical to MCP23017 EXCEPT that they use SPI instead of I2C for their communication bus. They're electrically and physically identical, near identical pin layout - except the I2C and SPI pins of course - control registers, communications protocol are both identical, except that it supports SPI up to 10mhz instead of I2C at 400khz/1.7mhz etc etc. Also, SPI is easier to co-exist than I2C.

I understand that you don't want to add lots of generic things for lots of generic targets that'll never be used, but I'm kinda hoping due to the massively parallel path this chip takes compared to the one you already support, you might find time for me. My hot tub is down until I can find a solution, but I'm certainly not putting that responsibility on your shoulders.

Again, thanks for the amazing work!

**Comment by daninfuchs** [comment]
I figured at the time of implementation it was that way. I also noticed that SPI was added, and some sensors and such use it, thus it might be a consideration. No worries, though. I figured it might not make it mainline.

Also, I know the bus speed isn't an issue. It's not as if we're clocking flight time of a projectile or trying to PID thrust-balance a drone. Yes, we're talking about 0.05% instead of 0.08% or some other nonsensically small number and uselessly small gain to reflect the decrease in overhead, it was more of a general 'it exists and is different' thing. I mentioned how identical they were in my own message. And that I tend to be overly verbose.

Though just for conversation's sake - I prefer SMD, it's easier for the pick and place after fabricating a board, and I don't have to change out tool heads for vias or pins if it's all surface-mounted. I'm not concerned with the cost of the chip, it's more that I have a ton of them on hand (just like I have a few Wemos D1 Minis) and figured it might be as easy as copying a code block, changing some defines, and adding an enum entry for it in a few places. I'll look into it myself, that's all it took to add supported devices after all. Have a good one, and keep up the great work.

**Comment by daninfuchs** [comment]
I would love to, and actually that's a fair moment now that I have your attention (Is there a better place for this conversation now? I don't want to mis-use resources or attention) - my IDE immediately re-formats the entire source base's indentation upon importing/opening to use spaces instead of a mix between tabs and spaces, which results in a ridiculous and frankly unneccesary changeset right off the bat.

I don't really want to change its tendencies there since I'm (insanely) OCD with code indent comformity, but when I tried a PR last time I was unable to push JUST the devices/etc as a change. I'm new to git (old-school local-only coder here, hah) so I frankly have no idea and a brief search was less than helpful. My Google-Fu was weak, it would seem.

**Comment by andrethomas** [comment]
@daninfuchs 

I think it would be better to do it in a new file anyway because the current one is conditional to #define USE_I2C which is not the case for yours... or the SPI would have to check if USE_SPI is defined.

So take ideas from the I2C one if you need them and use the same configuration dataset in Settings but the rest is going to need some re-writing for sure.

I still need to clean up the I2C one because there are a few things in there which I am not 100% happy about from an optimization perspective but I do not have a formatting OCD... have some other ones not related to formatting of text.

**Comment by andrethomas2** [comment]
> I'm new to git (old-school local-only coder here, hah) so I frankly have no idea and a brief search was less than helpful. My Google-Fu was weak, it would seem.

We have a Discord Chat channel where someone can take you through this and any other questions. There is a link to the invite code in the signature below.

I recommend installing the Discord Desktop app as it makes it easier to drag and drop files during discussions.

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
