### ISSUE TITLE
Establish link-local IP address when DHCP is not available

### ISSUE THREAD

**Issue by amontefusco** [arendst/Sonoff-Tasmota#4552]
As per title, it would be useful, in case devices are deployed in isolated networks, where no infrastructural services are available, that a link-local IP is automatically self-assigned.
Now, it seems that the feature depends on the Arduino code.
So I asked there (https://github.com/esp8266/Arduino/issues/5437), and such feature will be enabled on the following milestones:

https://github.com/esp8266/Arduino/milestone/10
https://github.com/esp8266/Arduino/milestone/8

**Comment by andrethomas2** [comment]
Those are future cores you are referring to, so unless its already included in 2.5.0 you are not going to get this to happen - if it is enabled already on the stage you can self-compile using the 2.5.0 esp8266 arduino core using platform IO.

**Comment by andrethomas** [comment]
Those are future cores you are referring to, so unless its already included in 2.5.0 you are not going to get this to happen - if it is enabled already on the stage you can self-compile using the 2.5.0 esp8266 arduino core using platform IO.

**Comment by Jason2866** [comment]
This feature is still not in any core. PR is ready but still needs merge...

**Comment by ascillato2** [comment]
Nice idea, but as it is not in any released core, there is nothing we can do from Tasmota side. Thanks for share.

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
