### ISSUE TITLE
Bricked S26 after OTA Update?

### ISSUE THREAD

**Issue by CommanderWayan** [arendst/Sonoff-Tasmota#4557]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used : esptool
- [ ] Hardware used : Raspberry Pi
- [ ] If a pre-compiled release or development binary was used, which one? : 6.2.1 -> 6.3.0
- [ ] You have tried latest release or development binaries? : yes
- [ ] Provide the output of command ``status 0`` : not possible
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

Hello and greetings :)

I think i ran into a problem i cannot resolve. At first, thanks for providing that great way to use Sonoffs

A few weeks ago i flashed a Sonoff S26 with tasmota-basic and it still works like a charm.
2 days ago I received 2 new S26 and tried to flash them via a raspberry pi and esptool.

It worked flawlessly (i thought), plugged them into a socket, waited and went to configuring them
I remembered that i used version 6.2.1, so i looked for an update via OTA (Version 6.3.0)- one ran through (It has a problem now, that it looses my WiFi every 5 seconds and opens its own Sonoff-XXXX, but i will try to reflash it)

My main problem is the other S26, i don't know if it ran well through the update, butt all it does is that i lights up the read LED, and thats it.
It reacts to nothing.
If i connect it to the raspberry, the red LED lights up, and nothing more.
I can't enter flash mode, as soon as 3.3V is connected it lights up red, no mater if the button is presses or not.
I even tried shorting gpio0 to gnd for entering flash mode, nothing.
Esptool cannot connect (timeout) and miniterm shows absolutely nothing, and doesn't accept commands. 

So... literally nothing i tried works...

Anybody have anothoer idea?

thanks in advance and have a nice weekend everybody :)

**Comment by ascillato** [comment]
Hi,

Please, try the latest Tasmota 6.3.0.16 from http://thehackbox.org/tasmota/

Please, erase before flash and flash again with esptool.py

If you need further assistant, please find us in the Tasmota Support Chat. Thanks.
