### ISSUE TITLE
Emulated Hue

### ISSUE THREAD

**Issue by chris8837** [arendst/Sonoff-Tasmota#4560]
Describe the bug
When I woke up this morning my echo couldn’t see any devices. I checked my tasmota devices and rebooted. I looks like they updated something on Amazon’s side. App and firmware. Broke the bridge. 

To Reproduce
Look at the Alexa app and it shows all tasmota devices as unresponsive. All non tasmota devices still working. 

Expected behavior
I should not have the device as unresponsive. 

Screenshots
None

**Comment by Jason2866** [comment]
Please fill out issue template. Without we know nothing about your setup and cant help

**Comment by chris8837** [comment]
Done!!

**Comment by ascillato** [comment]
Can you post the console output of status 0 command also?

**Comment by ascillato** [comment]
Which amazon echo device are you using?

**Comment by chris8837** [comment]
Sorry. My fault. One of my echo devices was offline for some reason.
