### ISSUE TITLE
WS2812 wrong Color

### ISSUE THREAD

**Issue by danst0** [arendst/Sonoff-Tasmota#4565]
Hi,

Something seems to be wrong with my WS2812 strip on my Tasmota with Wemos D1 mini.
I send a HSB Color of 120,100,70 via MQTT (or console) gives me red LEDs (instead of green). I think the color channels seem to be mixed up...
Is there a way to change the assignment?

Daniel

**Comment by Jason2866** [comment]
You have to compile your own version and change in my_user_config.h
`  #define USE_WS2812_CTYPE     NEO_GRB           // WS2812 Color type (NEO_RGB, NEO_GRB, NEO_BRG, NEO_RBG, NEO_RGBW, NEO_GRBW)`

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by jeroenst** [comment]
It's also possible to SetOption37 to 24 nowadays.

**Comment by sfromis** [comment]
Since this ancient thread was resurrected, I can add that the ESP32-only command `PixelType` now is there to "Set the number of channels per led in the strip, and the color order"

**Comment by jeroenst** [comment]
Thank you, yes an old thread which I used before for info about this. At least it's now up to date again.
