### ISSUE TITLE
Somfy RTS Sender Replacement

### ISSUE THREAD

**Issue by nosaj66au** [arendst/Sonoff-Tasmota#4584]
**Have you look for this feature in other issues and in the wiki?**

**Is your feature request related to a problem? no

**Describe the solution you'd like**
Can we please take a look at supporting Somfy RF protocol it has be requested in the past it has been 
report at requiring hardware however I believe this is not the case looking at code examples and some testing I have done.  

**Describe alternatives you've considered**
This is a pretty well defined protocol used by may blind companies and there is not other options I can find.

**Additional context**
refer Somfy RTS Sender Replacement #3108

Jason

**Comment by ascillato** [comment]
Hi, the RF protocol support are done by portish. Please, open an issue there. He can help you with that.
When he updates the RF firmware, then, that firmware can be added to the RF chips.

Thanks
