### ISSUE TITLE
4ch pro - control all 4 dry relays simultaneously

### ISSUE THREAD

**Issue by uga5** [arendst/Sonoff-Tasmota#4585]
Electrician but complete noob to tasmota, so plz forgive ignorance.

Want to use a 4Ch pro to replace a mechanical relay.  In legacy setup, single wall switch opens/closes 4ch mechanical relay where each circuit is on dependent breaker from the panel.  Single switch turns lights on/off in 4 different rooms at same time.  Those old mechanical relays are loud as hell and overkill in post LED conversion.  Each channel now draws 2-4 amps compared to 12 amps or more prior to LED conversion.

Ideally, would replace wall switch with wifi or 433mhz switch to toggle all 4 relays on the 4ch pro at the same time. Default firmware won't get me there.  Don't like mains able to provide more juice than relay rating, so would replace 20A breakers w 10A or smaller or include in-line fuses.   

Reasonably confident I can follow directions to flash Tasmota, but a non-starter unless Tasmota can be configured for this use case.

Any ideas much appreciated...

**Comment by ascillato2** [comment]
Hi,

How to flash is explained in the wiki. https://github.com/arendst/Sonoff-Tasmota/wiki There you have step by step instructions and also links to video tutorials.

If you need further support, please visit the chat channel for this type of support at: https://discord.gg/Ks2Kzd4

Thanks.
