### ISSUE TITLE
Not able to use Ground Trigger (low) Relay on my MiniWemo

### ISSUE THREAD

**Issue by mrteausa** [arendst/Sonoff-Tasmota#4588]
**Have you look for this feature in other issues and in the wiki?**

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by mrteausa** [comment]
I have lots of Low (ground) Trigger 2-4-6 Relays strips.  These does not work with your Tasmota firmware installed on MiniWemo DI or NodeMCU board because I need High trigger Relays.  Any future changes so I can use these low trigger relays strip would be great..

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
