### ISSUE TITLE
second switch not working

### ISSUE THREAD

**Issue by DaPeace** [arendst/Sonoff-Tasmota#4594]
Im trying to add a second switch to my th16. Ive connected it to rx and when i add it as switch2 i can trigger the relay by this switch or by the button at the pcb.
But i want that switch send its state to mqtt AND i want the switch at the pcb do the relay-work.
Ive read around and i should add switchtopic2 limitswitch to set the topic to limitswitch for the second switch. But that is not working. My new topic for both switches ist limitswitch/POWER1 + POWER2 and the relay is not moving anymore. When i revert that changes and set switchtopic2 0 both switches are moving the relay again. Any hint why that happens?
In the Wiki "Understanding SwitchMode and SwitchTopic" you describe that i simply have the change the topic for the second switch...

**Comment by ascillato** [comment]
There are several items to check in order to properly help you due to the troubleshoting template has been ignored. Will be faster to address this in the Tasmota support chat https://discord.gg/Ks2Kzd4

Github issues are meant for bug reports.

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
