### ISSUE TITLE
Rule example to output sensor data via single W2812 led ( low Co2 Blue to high Co2 level Red)

### ISSUE THREAD

**Issue by postaanerik** [arendst/Sonoff-Tasmota#4597]
**Have you look for this feature in other issues and in the wiki?**

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

Which Tasmota version?

Which sensor?

Have you tried the examples in the wiki?

For example, if you are using MHZ19B a rule could be (adapt to your needs):

```
rule1 1
rule1 on MHZ19B#CO2>100 do color 1 endon on MHZ19B#CO2<100 do color 3 endon
```

For further support please find us in the Tasmota Support Chat at https://discord.gg/Ks2Kzd4
_(Github issues are meant for bug report)_

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
