### ISSUE TITLE
Would be great if for multiple DS18B20s a user could set the MQTT names

### ISSUE THREAD

**Issue by bramco** [arendst/Sonoff-Tasmota#4605]
Just installed a Sonoff Basic with 7 temperature sensors to replace a home brew esp8266 system.

The sensor data is reported to an emoncms server running locally which was direct with the home brew system but now with the Sonoff and Tasmota running has to go via MQTT and Node Red.

The name given to the sensors by Tasmota are a bit of a pain. DS18B20-1 etc.  The '-' in the name makes it hard in Node Red to get the data - I'm probably not good enough at Javascript but I had to resort to a 'change' node to change DS18B20- to get rid of the dash and then I could process the sensor data and send on to emoncms.

So my thought is that it would be great if there could be a simple interface to allow users to rename the standard identifiers so that these are a) more understandable, i.e. HeatBankTop and also less of a pain in Node Red which is where I guess most people would deal with the data.

If not, can someone document how to easily access the sensor data when the object name has a dash in it or could the standard names be changed to DS18B20a, ...b, ....c etc.  ?

Simon

**Comment by ascillato** [comment]
Hi,

Nice idea, but as you now, the flash and memory of the esp8266 is limited, so some make up improvements are not done in favor of leaving more free ram and flash for other features.

Anyway, besides you can rename your sensors displayed in you home automation software, there is a workaround from Tasmota side to acomplish also your request.

You can use rules and on every tele message, you can catch the sensors values and send them with the topic, name and format you want like:

```
Rule1 1 
Rule1 on DS18B20-1#temperature do publish stat/yoursonofftopic/HouseRoofNorthTemp %value% endon on DS18B20-2#temperature do publish stat/yoursonofftopic/HouseRoofTankTemp %value% endon
```

Please, let us know if this workaround satisfy your request. Thanks

**Comment by ascillato** [comment]
The rules feature was added by Theo to modify the standard behaviours of Tasmota.

Please, try the example provided. That should solve your request and the good thing is that it is already implemented and working.

**Comment by bramco** [comment]
Hi,

As I said, I've already done a workaround in Node Red using a change node - which frankly is a lot easier than using a rule.

Simon
