### ISSUE TITLE
state Topic wrong

### ISSUE THREAD

**Issue by wolf40home** [arendst/Sonoff-Tasmota#4606]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

**Describe the bug**
I have set the fulltopic to %topic%/%prefix%/ as follows. 
that works out the way it's supposed to.
Example:
ltreppeoben/tele/SENSOR
ltreppeoben/tele/STATE
only if you issue the command for on or for off it is ignored
15:21:07 MQT: stat/ltreppeoben/RESULT = {"POWER1":"ON"}
15:21:07 MQT: stat/ltreppeoben/POWER1 = ON
the problem occurred after activating Domiticz in version 6.3.0.16

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [ X] _Searched the problem in issues and in the wiki_
- [X ] _Hardware used_ : Sonoff POW, Basic, S20
- [ ] _Development/Compiler/Upload tools used_ : Visual Studio Code
- [ ] _If a pre-compiled release or development binary was used, which one?_ :
- [X ] _You have tried latest release or development binaries?_ :
- [ ] _Provide the output of command_``status 0`` :
```
15:25:07 CMD: status 0
15:25:07 MQT: ltreppeoben/stat/STATUS = {"Status":{"Module":1,"FriendlyName":["ltreppeoben","Sonoff2"],"Topic":"ltreppeoben","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
15:25:07 MQT: ltreppeoben/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://10.10.0.4/api/arduino/firmware.bin","RestartReason":"Software/System restart","Uptime":"1T14:33:20","StartupUTC":"2018-12-10T22:51:47","Sleep":50,"BootCount":14,"SaveCount":32,"SaveAddress":"F9000"}}
15:25:07 MQT: ltreppeoben/stat/STATUS2 = {"StatusFWR":{"Version":"6.3.0.16(sonoff)","BuildDateTime":"2018.12.10 13:57:19","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
15:25:07 MQT: ltreppeoben/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":2,"LogHost":"10.10.0.4","LogPort":514,"SSId":["Steiner-Fritz","Steiner-Asus"],"TelePeriod":30,"SetOption":["00008008","558180C0","00000000"]}}
15:25:07 MQT: ltreppeoben/stat/STATUS4 = {"StatusMEM":{"ProgramSize":450,"Free":552,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000407","0630079C","24038121","00000696","00003AC0"]}}
15:25:07 MQT: ltreppeoben/stat/STATUS5 = {"StatusNET":{"Hostname":"ltreppeoben","IPAddress":"10.10.0.26","Gateway":"10.10.0.1","Subnetmask":"255.255.255.0","DNSServer":"10.10.0.1","Mac":"68:C6:3A:A3:A1:7E","Webserver":2,"WifiConfig":4}}
15:25:07 MQT: ltreppeoben/stat/STATUS6 = {"StatusMQT":{"MqttHost":"10.10.0.4","MqttPort":1883,"MqttClientMask":"ltreppeoben","MqttClient":"ltreppeoben","MqttUser":"mqttuser","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
15:25:07 MQT: ltreppeoben/stat/STATUS7 = {"StatusTIM":{"UTC":"Wed Dec 12 13:25:07 2018","Local":"Wed Dec 12 15:25:07 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":"+02:00"}}
15:25:07 MQT: ltreppeoben/stat/STATUS10 = {"StatusSNS":{"Time":"2018-12-12T15:25:07","Switch2":"OFF","HTU21":{"Temperature":25.8,"Humidity":23.6},"TempUnit":"C"}}
15:25:07 MQT: ltreppeoben/stat/STATUS11 = {"StatusSTS":{"Time":"2018-12-12T15:25:07","Uptime":"1T14:33:20","Vcc":3.130,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":40,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"Steiner-Fritz","BSSId":"CC:CE:1E:B4:AD:E2","Channel":10,"RSSI":92}}}
```

**To Reproduce**
_Steps to reproduce the behavior:_
turn the switch on or off

**Expected behavior**
_A clear and concise description of what you expected to happen._
15:21:07 MQT: ltreppeoben/stat/POWER1 = ON

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

Yes. It is designed like that for backward compatibility. Hope that is not a big inconvinience for you to adapt your configuration in your home automation software. Thanks

**Comment by wolf40home** [comment]
is there a setoption to change that?

**Comment by ascillato** [comment]
No, there is not. Sorry.

**Comment by ascillato2** [comment]
After analysing you request, was decided to leave as it is in favor of backward compatibility. There are too many users using Tasmota and we don't want to brake their setups. Sorry if the outcome was not the one you wanted. 

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
