### ISSUE TITLE
RFbridge not recieving any signals anymore

### ISSUE THREAD

**Issue by woudenbe** [arendst/Sonoff-Tasmota#4608]
i updated the rf chip firmware with the latest file (20181127) and now the bridge is not able to see any rf signals anymore.
is there any way to get the original RF chip firmware back ?

thanks Hans

**Comment by meingraham** [comment]
I believe that the ITEAD firmware is available here - https://github.com/arendst/Sonoff-Tasmota/tree/development/tools/fw_efm8bb1

**Comment by ascillato2** [comment]
@woudenbe You can go back to the stock firmware using the link provided by @meingraham 

But anyway, The firmware from Portish works really good. If you want, you can try flash it again.

If you need further assistance with that, please find us in the Tasmota Support Chat.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
