### ISSUE TITLE
Help restore 'Home-Assistant' wiki page

### ISSUE THREAD

**Issue by emontnemery** [arendst/Sonoff-Tasmota#4613]
Somehow I accidentally deleted the 'Home-Assistant' wiki page while creating a new wiki page.
I put the content is back, but the history is gone.

I think it can be fixed by resetting back to commit 44e2b93a02c6d11a08fe7bf78895da3f5d3ea41e, and then cherry pick commits not related to my changes.
(Currently this is only commit 1bdf1ddda8691962d681b7722ee084bca3f8b471)

(If it's not crucial to have the edit history, just close this issue)

**Comment by curzon01** [comment]
Isn't that the history?
https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant/_history

**Comment by emontnemery** [comment]
It indeed is, thanks @curzon01!
