### ISSUE TITLE
I followed Tasmota configuration on SHT30 shield on MiniWemo and it getting the reading on webserver just fine.  But when I put this line value_template: '{{ value_json["SHT30-0x45"].Temperature }}', on the configuration.yaml for HomeAssistant, the return value is unknown.  I use DT22 module just fine but not this SHT30 module.  What do I need to change to get the reading on HA?

### ISSUE THREAD

**Issue by mrteausa** [arendst/Sonoff-Tasmota#4615]
_Originally posted by @mrteausa in https://github.com/arendst/Sonoff-Tasmota/issues/4591#issuecomment-446241222_

**Comment by ascillato** [comment]
Please, address this question in the support chat. It will be more dynamic because there are lot of information missing in order to help you properly. Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by mrteausa** [comment]
Got it to works.  Need to use  value_template: '{{ value_json["SHT3X-0x45"].Temperature }}' and I got the reading on the Home Assistant webserver.  Thanks.
