### ISSUE TITLE
Feature Request : Pulsing LED (Breathable LED effect) for status lights etc.

### ISSUE THREAD

**Issue by jascdk** [arendst/Sonoff-Tasmota#4622]
Hi.

Would it be possible to integrate a "Breathable LED effect" in the LED light options.

Mainly for use in projects to indicate that MQTT / wifi etc. is not connected.

I used this code in another project linked below:

https://arduining.com/2015/08/20/nodemcu-breathing-led-with-arduino-ide/

It gives a nice effect - a bit more cool than just standard blinking :)

**Comment by Jason2866** [comment]
It is not the goal of Tasmota to have cool LED blinking effects which needs rare resources.
LED indication for status is already implemented
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#main

**Comment by ascillato2** [comment]
Nice idea. Added your request to the list of requested effects in the already open issue #3480

Thanks for sharing your ideas.
