### ISSUE TITLE
Fast toggle blocking time

### ISSUE THREAD

**Issue by MichMoos** [arendst/Sonoff-Tasmota#4626]
Hi,

would it be possible to add a timer which blocks fast toggle of the relay? A 2 second blocking time could help prevent damage to the connected device or the relay itself.

**Comment by ascillato2** [comment]
If you want a more advanced example that will have the relay toggling as soon as the mqtt message is received and just waits 2 seconds for being able to toggle again, you can use the following:

```
rule1
on system#boot do var1 0 endon
on event#TOGGLE do event checktoggle=%var1% endon
on event checktoggle=0 do power1 2 endon
on power1#state do backlog var1 1; ruletimer1 2 endon
on Rules#Timer=1 do var1 0 endon
```

So, all rules together for copying and pasting in the console:

```
rule1 1
rule1 on system#boot do var1 0 endon on event#TOGGLE do event checktoggle=%var1% endon on event checktoggle=0 do power1 2 endon on power1#state do backlog var1 1; ruletimer1 2 endon on Rules#Timer=1 do var1 0 endon
```

If you need further assistance please find us in the Tasmota Chat. Thanks.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
