### ISSUE TITLE
webserver:213:18: error: expected ',' or ';' before 'D_LOG_LEVEL'

### ISSUE THREAD

**Issue by Gisy** [arendst/Sonoff-Tasmota#4633]
"const char HTTP_FORM_LOG2[] PROGMEM =
<br/><b>{b0}" D_LOG_LEVEL "</b> ({b1})<br/><select id='{b2}' name='{b2}'>.............................

I installed Arduino IDE from scratch. Every time i try to compile the code, i got the error above.
It looks good for me.... don´t know what to do.

**Comment by andrethomas** [comment]
Current codebase compiles fine for me using Arduino.

Sorry I cannot reproduce this error.

**Comment by ascillato2** [comment]
If you need further assistance solving your issue, please find us in the Tasmota Chat. Will be easier to chat for helping you with your building issue.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
