### ISSUE TITLE
Add new template smart plug 

### ISSUE THREAD

**Issue by riddik14** [arendst/Sonoff-Tasmota#4641]
{ "Smart Plug",   //http://playinstinct.ru/sp1-eu-16a-smart-life-wifi-socket-remote-control-timer-switch-socket-support-alexa-voice-control-google-home-eu-smart-plug/
//https://s.click.aliexpress.com/e/sV54z1P

                  
     GPIO_LED1_INV,    // GPIO00 Red Led (1 = On, 0 = Off)
     GPIO_USER,        // GPIO01 Serial RXD and Optional sensor
     GPIO_USER,        // GPIO02 Blue Led (1 = On, 0 = Off)
     GPIO_USER,        // GPIO03 Serial TXD and Optional sensor
     GPIO_USER,
     GPIO_HJL_CF,      // GPIO05 BL0937 or HJL-01 CF power
     0, 0, 0, 0, 0, 0, // Flash connection
     GPIO_REL1,        // GPIO12 rele 16A
     GPIO_KEY1,        // GPIO13 Button
     GPIO_NRG_CF1,     // GPIO14 BL0937 or HJL-01 CF1 current / voltage
     GPIO_NRG_SEL_INV,        // GPIO15 
     0, 0
  },

**Comment by riddik14** [comment]
I  have to try blitzwolf shp conf, it work with monitoring but rele go to blink. And key not work.
The plug have 2 led, 1 red and 1 blue. The blue is connect to serial the red to gpo0. I have burn flash tasmota and work with conf posted, but no monitoring

**Comment by riddik14** [comment]
I have compiled fw with ide. Plug work with monitoring but Ampere are show high. Example 8w 16.6 A, why?

**Comment by riddik14** [comment]
I have start calibration https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Pow-and-Pow-R2

Powerset
Currentset
VoltageSet 
Now work good

**Comment by andrethomas2** [comment]
@riddik14 Thanks for your information - happy to hear it is working. We will need to add this to the Wiki

Thank you for your contribution!
