### ISSUE TITLE
When using WS2812, onboard LED follows "virtual" relay instead of primary relay

### ISSUE THREAD

**Issue by joecotton** [arendst/Sonoff-Tasmota#465]
From version 5.1.1, the WS2812 option adds a "virtual" relay so that power for the WS2812 string can be independent from the main relay.

However, now the onboard led follows this virtual relay instead of the physical relay.

**Comment by arendst** [comment]
The led follows all relays and in this case the ws2812 too. As designed as on dual or 4ch you would not use this led as you do in sonoff basic.
