### ISSUE TITLE
Tasmota LWT status - Upper/Lower case letters - 'Online' in 6.4.0 - 'online' versions before

### ISSUE THREAD

**Issue by h4nc** [arendst/Sonoff-Tasmota#4652]
It looks like in the newest Version of tasmota 6.4.0 the LWT status is reported as `'Online'` and `'Offline' `instead of `'online'` and `'offline'`.
I don't really know if its a tasmota or a home assistant issue. But I think I should try it here first.

It causes problems with entities in home assistant.
Things like the `availability_topic` of mqtt-lights will be unavailable and there is no option for that to change it to` 'Online'` in HA. 
[](https://www.home-assistant.io/components/light.mqtt/)
It seems like for now there is no way but to uncomment this line to make the light work again (of course coudl also go back to 6.3.0).

**Comment by digiblur** [comment]
I checked a couple of my previous configs in and I've always had them as 'Online' and 'Offline'

**Comment by h4nc** [comment]
Thanks for checking your configs.

That's weird. Maybe I also always had 'Online'. The strange thing is that my LWT automations stopped working and I had to change them to 'Online'. They worked before the Sonoff-Upgrades.

**Comment by h4nc** [comment]
Ok so I downgraded one of my sonoffs to 6.3.0 (both 6.3.0 and 6.4.0 from github, I didn't change something) 
In my screenshots you can see that there is indeed a upper/lower case letter difference for both versions. And because availability-topic only listens to online and offline (lower case) this will fail.

<img width="415" alt="6 3 0" src="https://user-images.githubusercontent.com/25117255/50094635-ec15da00-0213-11e9-91c2-349ceb408a65.png">
<img width="418" alt="6 4 0" src="https://user-images.githubusercontent.com/25117255/50094637-ecae7080-0213-11e9-8674-c3a694a5281f.png">

**Comment by arendst** [comment]
Let me guess, Germany?

https://github.com/arendst/Sonoff-Tasmota/pull/4392

**Comment by h4nc** [comment]
Yes, it's the german file, thanks.

**Comment by arendst** [comment]
But this is the main reason why it has to stay as it is: https://github.com/arendst/Sonoff-Tasmota/issues/4388

**Comment by h4nc** [comment]
Ok, I get that all languages should use 'Online' consistant. It's fine to change it.

So it seems like now it gets a home assistant issue? But if it was always Online for all the other languages, how did you use the 'availability_topic' in ha? As I said before it seems like it only listens to lower case online's ;-)

From here: https://www.home-assistant.io/components/light.mqtt/

> availability_topic
> (string)(Optional)The MQTT topic subscribed to receive availability (online/offline) updates.

I think sonoff devices are one of the most used mqtt devices in home assistant, so it wouldn't make sense to have those differences.

**Comment by arendst** [comment]
I don't think Germany is the only country using HASS. The others never complaint so I guess there must be a simple HASS solution...

**Comment by h4nc** [comment]
Yes, I also think so. I will take this to the ha community. Let's see what they say. Could also be possible that most guys don't use the availability_topic, as this isn't mandatory.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by h4nc** [comment]
Ok, so the hint from @digiblur was the problem solver. 

Had to add those lines:

```
    payload_available: "Online"
    payload_not_available: "Offline"
```
The default values are lower case.
