### ISSUE TITLE
Compile core 2.4.2 Release binaries 6.4.0

### ISSUE THREAD

**Issue by turin400** [arendst/Sonoff-Tasmota#4654]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used :
- [ ] Hardware used : 
- [ ] If a pre-compiled release or development binary was used, which one? :
- [ ] You have tried latest release or development binaries? :
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```
I have seen that the latest stable versions are compiled with the core 2.4.2, is this already solved the problem of wifi sleep with this core?
Thank you.

**Comment by Jason2866** [comment]
The issue in core is still there. The core is the same and stil has the bug.
Tasmota has now its own sleep routine and doesnt need anymore the function from the core.
This is the greatest change from v.6.3.0 to 6.4.0.
The Tasmota sleep doesnt lag the device as it was with core sleep!
Sleep is now enabled by default with a value of 50. How to change is in wiki section commands
Please close this issue.

**Comment by turin400** [comment]
Thank you.
