### ISSUE TITLE
Battery suggestion

### ISSUE THREAD

**Issue by helmar74** [arendst/Sonoff-Tasmota#4671]
Hi,

I'm planning to run the Tasmota fork from stefan bode on a Wemos D Mini, connected with a HC-SR04.
([https://github.com/stefanbode/Sonoff-Tasmota])
The Device should be battery powered.
As a HC-SR04 is connected, I need a 5V battery or battery pack. The battery should have round about 10000mAh
I tried several usb power packs, but unfourtnately all powerpacks I tried had a "auto power down" mode. So it was powering down, when the wemos mini entered deepsleep mode...

Has anyone an suggestion which battery, usb powerpack or battery pack would meet my requirements?

Thanks a lot

Helmar

**Comment by Jason2866** [comment]
Not a easy answered question. Please visit Discord for this

**Comment by ascillato2** [comment]
Closing this issue as it is not a Tasmota software issue. 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
