### ISSUE TITLE
Problem with WiFi channel on first configuration on D1 mini and other

### ISSUE THREAD

**Issue by mumin50** [arendst/Sonoff-Tasmota#4673]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used : Arduino
- [ x] Hardware used : D1mini 
- [ ] If a pre-compiled release or development binary was used, which one? :
- [x ] You have tried latest release or development binaries? yes
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

Hi All 
My D1mini on first install starts AP on wifi channel1, and by some reason this channel is not working well for me, at least i tried to connect to it with my laptop, phone, and few other devices... (Europe region devices).
I had that issue before with my other arduino project based also on esp8266, so i think it is global problem. Always changing channel to 6 was fixing it...

Question : is there a way to set it up on default channel 6 or other 3-10 range for AP?
I searched but can't find where to change it... Any help
Marcin

**Comment by Jason2866** [comment]
Mhh, strange issue you have. Channel 1 should work with evey device in every region in the world.
Maybe @arendst change it for you :-)

**Comment by andrethomas** [comment]
@mumin50 

Assuming you're not self-compiling yet you can test the binaries from here as a temporary solution which should start up on channel 6 according to the recommended code change from @arendst 

http://thehackbox.org/tasmota/mumin50/

Please advise when complete so that the folder may be removed.

Thanks

**Comment by ascillato2** [comment]
Hi

Have you managed to solve your issue?

**Comment by ascillato2** [comment]
Closing this issue as there is no feedback. When you have time please tell us if it worked. Thanks.

**Comment by mumin50** [comment]
Sorry was traveling for Christmas...
Tested .bin. Works perfectly without any issue.
Starts on channel 6.
 
I hope this change could be send to main code for future improvement.
Thank You

**Comment by mumin50** [comment]
@andrethomas great thanks folder can be removed

**Comment by arendst** [comment]
Will make it my_user_configurable by define.
