### ISSUE TITLE
How to use Sonoff-Tasmota with Sloeber 4.3 plugin in Eclipse

### ISSUE THREAD

**Issue by MAWMN** [arendst/Sonoff-Tasmota#4674]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x ] Development/Compiler/Upload tools used : Sloeber 4.3 with eclipse
- [x ] Hardware used : Wemos d1 mini
- [x ] If a pre-compiled release or development binary was used, which one? :
- [x ] You have tried latest release or development binaries? : Sonoff-Tasmota-6.4.0
- [x ] Provide the output of command ``status 0`` : 
```
STATUS 0 OUTPUT HERE
not available

**(Please, remember to close the issue when the problem has been addressed)**

QUESTION :🤔

Hello, 
  I am using Sloeber 4.3 for programming and flashing my Arduino and Wemos boards.
Is there any description, video or short notes of how to import/use the Sonoff-Tasmota application in(to) the sloeber environment ?
I am using Sloeber plugin 4.3 and the Sonoff Tasmota release 6.4.0

Help will be greatly appreciated.

Thanks in advance..

**Comment by ascillato** [comment]
Hi

Sorry, but we don't support Sloeber plugin.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
