### ISSUE TITLE
Tasmota Sonoff TH MQTT tele status cannot retrive

### ISSUE THREAD

**Issue by eadin79** [arendst/Sonoff-Tasmota#4679]
Hello,
I'm using Node-red and Mosquitto for Sonoff TH and SI7021 sensor.
Power ON/OFF and temprature humidity I can get by MQTT commands, but I cannot retrive tele/sonoff1/STATUS ... what is wrong in my request to mqtt broker? or why tasmota sonoff is not aswering?
I tried cmnd/sonoff1/STATUS 0.... still nothing.

PS: I'm newbie ,but I learn.

**Comment by eadin79** [comment]
![image](https://user-images.githubusercontent.com/45868350/50188199-70a64c80-0329-11e9-8a4a-68070c760ab0.png)
wih first 2 stat and tele works someting more, but wth tele/sonoff1/uptime or anything else not except wildcard #

**Comment by ascillato2** [comment]
Hi,

Seems that your config is not correct. 
As we need a lot more information to properly help you, please address this to the Tasmota Support Chat. Github issues are for bug reporting with the provided tenplates. Thanks

**Comment by eadin79** [comment]
a link to Tasmota Support chat please ...

**Comment by ascillato** [comment]
In the readme (main webpage of Sonoff-Tasmota) are the links to the chat, wiki and forum.

Chat: https://discord.gg/Ks2Kzd4

**Comment by garymcleanuk** [comment]
> ![image](https://user-images.githubusercontent.com/45868350/50188199-70a64c80-0329-11e9-8a4a-68070c760ab0.png)
> wih first 2 stat and tele works someting more, but wth tele/sonoff1/uptime or anything else not except wildcard #
> even with timestamp sending 0 to cmnd/sonoff1/status I got nothing back :-)
> 
> what I did wrong?
> ![image](https://user-images.githubusercontent.com/45868350/50188408-3be6c500-032a-11e9-9f5b-68731ebb1a67.png)

your Command is incorrect when trying to grab the status. You need to PUBLISH thatn subscrive to start with and you need to send payload Zero or 4 if you want status 4 Try this:

mosquitto_pub -h 192.168.1.7 -p 1883 -u admin -P test -t cmnd/sonoff1/status -m "0"
