### ISSUE TITLE
Reset RF Bridge

### ISSUE THREAD

**Issue by Trippersgarage** [arendst/Sonoff-Tasmota#4682]
How can I reset the Rf bridge using the button? According to the wiki, one can use the button to start wifi manager, reset etc via a sequence of presses. A reset is holding the button for over 40secs. But does this apply for the rf bridge as well? I've tried following the instructions with zero results.

Thank you.

**Comment by Jason2866** [comment]
Yes, it does work this way. May you have changed options you dont remember?
If you still have access to device try `Reset 5` it does reset to initial config and erases flash.
Just wifi settings survive. If this doesnt help a serial flash is neccessary.

**Comment by andrethomas** [comment]
I think it may work if connected to 3.3V power and not via USB - I have not been able to do it whilst powered from USB.

Alternative is reset 2 (which will erase data flash and restore to default settings), OR, reset 5 (which will erase data flash and restore to default settings whilst retaining ONLY the wifi configuration)

If that fails, it is erase and flash by serial according to https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF-Bridge-433

**Comment by Trippersgarage** [comment]
@andrethomas Didn't work connected to 3.3. Looks like a reflash is in order.

**Comment by andrethomas** [comment]
Yeah tried it on my spare sonoff rf bridge v2 also - the same thing, looks like the only way to get it out of trouble (not that mine was in trouble) is a wire flash.

**Comment by ascillato2** [comment]
Please, let us know if reflash solve your issue. Thanks.

**Comment by Trippersgarage** [comment]
Now my reflash keeps failing. Sigh.

**Comment by Trippersgarage** [comment]
So whats happens when I try to reflash, I'm using Atom on OSX. I am following the tutorial from "Quickpi". Initially I could not even access the unit via wire, kept getting a unable to open error during the platform upload stage. Checked settings and it seems I had platofromIO-ide installed? Strange. Disabled that and platformio seems to be able to upload, I see "success", but then it restarts the whole sequence again and uploads again. And again. and again. Its seems to be enjoying uploading and is uploading in an infinite loop. Anyways, I try accessing the serial monitor and I'm told by ATOM to use the serial monitor, I need to install or enable platformio-ide. Well fine then, I try that.. and I get the following error message;

`Mac-Pro:Sonoff-Tasmota-master macpro$ pio device monitor --port /dev/cu.usbserial-A5XK3RJT --baud 115200
--- Miniterm on /dev/cu.usbserial-A5XK3RJT  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---


--- exit ---
Exception in thread rx:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/macpro/.platformio/penv/lib/python2.7/site-packages/serial/tools/miniterm.py", line 445, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/Users/macpro/.platformio/penv/lib/python2.7/site-packages/serial/serialposix.py", line 501, in read
    'device reports readiness to read but returned no data '
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

I am out of my depth at this point. Shouldn't have tried to update the Sonoff in the first place...

**Comment by Trippersgarage** [comment]
@ascillato2 @andrethomas Any ideas?

**Comment by ByteJunk** [comment]
Bringing this up because I also couldn't reset the bridge using button presses after misconfiguring the WiFi connection.

I solved it by changing the value of CFG_HOLDER, rebuilding the image and flashing it (see https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting for info on CFG_HOLDER, took me a while to figure that one).

Cheers!

**Comment by Jason2866** [comment]
@ByteJunk  Do you have the Bridge V2 (the one with screws to open)?

**Comment by ByteJunk** [comment]
@jason2866 Yes, it has r2 printed on the board, and screws to open.

**Comment by andrethomas** [comment]
I'll check mine when I am home this evening to see what version my development one is... since it is already open.

**Comment by wongnam** [comment]
* I have tried to reset it by pressed the button 40s without success. Module is selected Sonoff Bridge (25).
* I still haven't tested it when it's in module Sonoff Basic, i will test it tonight.

**Comment by nosaj66au** [comment]
I had a hell of a time with my new Sonoff Bridge last night. After the first flashing it the first time it worked ok. I then change some config re compiled and flashed again via Web and the device didn't come back. In the end Identified it was in fact running without connecting with the correct IP settings, I don't even know where the settings it was using came from. It was a new unit from Itead. End up Flashing with an "erase flash program" via a local connection and 3.3 power. Then flashing my tasmota image back again. From there opened monitor from the Arduino IDE and found the serial console was functioning. Made all the changes to correct IP Subnet gateway all good. Never did get to full reset but I have now done 100's of Tasmota flashes but this one was just weird.

**Comment by Jason2866** [comment]
Tried to reset via button. Doesnt work when selected module "RF Bridge"
You have to change to module "Basic". Now you can reset device.

**Comment by wongnam** [comment]
> Tried to reset via button. Doesnt work when selected module "RF Bridge"
> You have to change to module "Basic". Now you can reset device.
Thanks @Jason2866 Yes, I was mentioned on above, but no one confirm that it can be replicated the issue.

**Comment by Jason2866** [comment]
@arendst  Is it possible to change the button behaviour for the bridge to act like a sonoff basic for reseting?

**Comment by arendst** [comment]
Give it a try.

**Comment by Jason2866** [comment]
Does work :-)

**Comment by ascillato2** [comment]
Closing this issue as it has been fixed. Thanks.

**Comment by yadenisenko** [comment]
Hello,
After flashing Sonoff rf, I cannot delete my RF remotes from memory, please help.
I read #4682 and enjoyed advice:

I held the button for 40 seconds and changed the Module type for different types
I have flashed through the platformio many times with CFG_HOLDER change.

It did not help.
Can you advice on how to delete the rf remotes from memory?
