### ISSUE TITLE
LEDSTATE and LEDPOWER for multiGang wall_switches

### ISSUE THREAD

**Issue by sshrage** [arendst/Sonoff-Tasmota#4684]
Hello. And thank you!

**Comment by sshrage** [comment]
Hello. 

I'm facing difficulties using sonoff_tasmota firmware with several WiFi wall switches. 
Here is an example. This is a 3Gang wall switch. It's name is - YK3_WIFI_SV2 FR4 94V0 (20170922). Attachment:
![20181219_122919](https://user-images.githubusercontent.com/45992878/50212095-3a011e00-038b-11e9-9ab6-85293dfa2e20.jpg)

Its wiring completely differs from SONOFFs. So Im forced to use Generik. Attachment:
![generic](https://user-images.githubusercontent.com/45992878/50212069-2e155c00-038b-11e9-9517-19553b4ebe58.JPG)

WallSwitch works perfectly with this cpnfiguration. The only problem is that ony Led1 reacting on button press of any gang. It doesn matter if I press 1Button or 3Button - Led1 is the only who blinks, or changing state. Led2, Led3 - are unusable. They are not capble of changing state.

Please help. How can I configure that part. 
Thank you for your software. It is more than usable!

I've used Arduino to compile my own .bin. I had to change LedState 0 and LedPower 0 commands to disable those functions. Because otherwise I see only Led1 Turnig ON or OFF no matter If press Button 2 , or Button3, or Button 1.

**Comment by KPK75** [comment]
LED1 is working as designed. LED2 and so on are not implemented (yet).
So set leds to RELAY4, 5 and 6 and use rules to turn them on/off.

**Comment by sshrage** [comment]
Thank you very MUCH!!! It works! 
![image](https://user-images.githubusercontent.com/45992878/50222042-0e406100-03a8-11e9-9a01-274afcdeee08.png)

Now i cant turn LEDs ON and OFF.
I made a rule
rule1 on power1#state do power4 on endon
so, when I turn the power ON the LED is turning ON too.
But what do I have to do to turn it OFF. 
Please advise the rule. I don't understand how to make a rule that will turn POWER 4 ON/OFF according to state change of POWER1.

**Comment by sshrage** [comment]
Dont answer. I figured it out myself. 
Here is the rule
rule1 on power1#state do power4 toggle endon
And it is working fine. 
Thank you VERY MUCH!!! 

Another question. Is there any way to make more percise  rule like 
rule1 on power1#on do power4 on endon power1#off do power4 off endon
So there is true dependency of ON and OFF parameter.
???

Again! Thanks!

**Comment by ascillato2** [comment]
> Another question. Is there any way to make more percise rule like
> rule1 on power1#on do power4 on endon power1#off do power4 off endon
> So there is true dependency of ON and OFF parameter.
> ???

Yes

`Rule1 On power1#state=1 do power4 1 endon On power1#state=0 do power4 0 endon`

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by Hurleyking** [comment]
Sshrage can you please say how you flash this?

**Comment by sshrage** [comment]
Here is the picture of pinout.
![white_wiring](https://user-images.githubusercontent.com/45992878/52768337-51cce980-303e-11e9-841e-b79e318e52f5.JPG)

 You've got to to use additional wire number 5. Connect it to "Ground" and to GPI0 on the chip while powering ON and beginning of the FLASH procedure.

**Comment by Hurleyking** [comment]
Thanks a lot. Works. 👍

**Comment by Tobias007** [comment]
Hi, here the template file:
{"NAME":"YK3_WIFI_SV2","GPIO":[27,0,24,18,22,17,0,0,19,21,25,23,26],"FLAG":0,"BASE":18}

**Comment by Tobias007** [comment]
Here another one:

![image](https://user-images.githubusercontent.com/37033298/67141146-40a23f80-f293-11e9-8dcb-aeac87a34753.png)

available here:
https://www.aliexpress.com/item/32916836771.html?spm=a2g0s.9042311.0.0.27424c4dPMuY1i

{"NAME":"eWelink Touch ","GPIO":[17,0,0,0,23,22,18,19,21,24,0,0,0],"FLAG":0,"BASE":0}

![image](https://user-images.githubusercontent.com/37033298/67141330-5cf2ac00-f294-11e9-97a8-bfba9bf5cacb.png)

Similar to Sonoff T 3CH
