### ISSUE TITLE
MagicHome Controller GRB setup

### ISSUE THREAD

**Issue by kingphil123** [arendst/Sonoff-Tasmota#4689]
Hello, I have successfully flashed my MagicHome controller with Tasmota 6.2.1 & configured as per this link [https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-with-ESP8285](url).

However my MagicHome is setup in GRB not RGB. Any idea how I swap the Red & Green?

**Comment by ascillato2** [comment]
Hi,

Duplicated issue. Please, search in issues for the recommended solution.

**Comment by ascillato** [comment]
https://github.com/arendst/Sonoff-Tasmota/issues/3741
