### ISSUE TITLE
Multiple devices no connect to wifi in sametime 

### ISSUE THREAD

**Issue by khriss75** [arendst/Sonoff-Tasmota#4690]
Using abount 25 sonoff devices (T1, DUAL R2, BASIC, TH10...) in my home with Tasmota firmware latest version: 6.3
As reported in #2089 ( [https://github.com/arendst/Sonoff-Tasmota/issues/2089](url) ) I'm having the same issue: several wifi connection to router in the same time cause problems.
Seems to be fixed `https://github.com/arendst/Sonoff-Tasmota/commit/ad40a851613e69ccfca7e39fd305c712c16a53bf` but I'm not able to fix the problem, how can I set a different delay wifi connection in my devices? 
I can't find the `#define WIFI_RETRY_SEC  `  , or is possible to use a command like "MQTTRETRY xx"?

- [X ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [X ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used :
Arduino IDE and OTA
- [ ] Hardware used :  Sonoff T1, Sonoff BASCI, Sonoff DUAL R2, Sonoff 4CH PRO
- [ ] If a pre-compiled release or development binary was used, which one? : 
sonoff.bin ver 6.4
- [ ] You have tried latest release or development binaries? :
Tried latest release
- [ ] Provide the output of command ``status 0`` 👍 

```
STATUS 0 OUTPUT HERE
9:05:20 MQT: sonoff_DUAL_R2/stat/STATUS = {"Status":{"Module":39,"FriendlyName":["Sonoff","Sonoff2"],"Topic":"sonoff_DUAL_R2","ButtonTopic":"0","Power":0,"PowerOnState":0,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Power on","Uptime":"2T22:52:18","StartupUTC":"2018-12-16T19:13:02","Sleep":50,"BootCount":8,"SaveCount":94,"SaveAddress":"F6000"}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS2 = {"StatusFWR":{"Version":"6.3.0.12(sonoff)","BuildDateTime":"2018-12-07T11:32:40","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["TISCALI_2340",""],"TelePeriod":1800,"SetOption":["00008009","55818000","00000000"]}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS4 = {"StatusMEM":{"ProgramSize":570,"Free":432,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000410","1FDAE7B4","000383A0","23B617CE","00003BC0"]}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS5 = {"StatusNET":{"Hostname":"sonoff_DUAL_R2-5140","IPAddress":"192.168.178.29","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"DC:4F:22:86:B4:14","Webserver":2,"WifiConfig":1}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.178.20","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_86B414","MqttUser":"mqttcris","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS7 = {"StatusTIM":{"UTC":"Wed Dec 19 18:05:20 2018","Local":"Wed Dec 19 19:05:20 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":"+01:00","Sunrise":"08:39","Sunset":"16:54"}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS10 = {"StatusSNS":{"Time":"2018-12-19T19:05:20"}}
19:05:20 MQT: sonoff_DUAL_R2/stat/STATUS11 = {"StatusSTS":{"Time":"2018-12-19T19:05:20","Uptime":"2T22:52:18","Vcc":3.464,"LoadAvg":2000,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"TISCALI_2340","BSSId":"5C:E2:8C:A5:23:41","Channel":4,"RSSI":48}}}
```

**Comment by ascillato** [comment]
Please, as asked in the other issue. update to latest and try again. A lot of things has change since then. Thanks. Also, please provide the troubleshoting template completed when opening a new issue. Thanks

**Comment by khriss75** [comment]
Now I'm on latest Tamsota (6.4). I can't find "wifi_retry_sec" as reported to solution!
I'm asking some help! (Or missed the "wifi_retry_sec" with new release?

**Comment by ascillato** [comment]
please provide the troubleshoting template completed

**Comment by khriss75** [comment]
> please provide the troubleshoting template completed

Done, edited first post.
The problem is related only if all my 20+ devices try to connect in the same time to wifi.

**Comment by khriss75** [comment]
Adrian, thank you so much for your replay and support!
Now I'm on 6.3 (self compiled) but tried 6.4 (compiled bin) with same problem.
I was searching in "support.ino" tab, not "support_wifi.ino" my error. I'll retry.
Powering on only 2 or 3 devices and other 2 or 3 devices after some second, and again other 2 -3 devices after some seconds, no problem.
Powering up all more 20 devices in the same time only about 10 devices are connected to wifi.
I use only one router, TP-LINK.

**Comment by ascillato** [comment]
The connection at the same time is not real. Sorry. Tasmota uses the CHIP ID to connect at different time. I have never had that issue and I have a lot of devices in my network.

`wifi_retry_init = WIFI_RETRY_OFFSET_SEC + ((ESP.getChipId() & 0xF) * 2);`

You are having another issue with your router.

**Comment by khriss75** [comment]
I can't test now with an other router, no wifi interference (I can se only one other wifi network but on channel 4, I'm moved to ch 9) with wifi analyzer.
For now I close the issue, I'll tray with other router.
