### ISSUE TITLE
how to set MQTT QoS >=1

### ISSUE THREAD

**Issue by lucafolin** [arendst/Sonoff-Tasmota#4693]
I have installed tasmota 6.3 on my client hardware but I'm not able to set mqtt = 1.
How and where can I modify Tasmota code to gain this feature ?
I use emqx brocker that send data to my sql database only if it receive an mqtt message with qos > 0.

**Comment by ascillato** [comment]
Sorry, not supported by the mqtt library: pubsubclient. From the readme of the library:

```
# Limitations

 - It can only publish QoS 0 messages. It can subscribe at QoS 0 or QoS 1.
```

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
