### ISSUE TITLE
HASS Discovery doesn't respect MQTT topic

### ISSUE THREAD

**Issue by Gaff** [arendst/Sonoff-Tasmota#4700]
I'm using tasmota 6.4.0

I've set my MQTT Topic to "sonoff-pow1234" and my Full topic to `%prefix%/%topic%/`

However the HASS relay discovery messsage has things like:

    "command_topic":"sonoff-pow1234/cmnd/POWER"

It should be:

    "command_topic":"/cmnd/sonoff-pow1234/POWER"

**Comment by mhuca** [comment]
@Gaff 

There has been significant updates to the home assistant integration. One of the changes was enforcing %topic%/%prefix%
If you don't us the home assistant auto discovery you can disable this with
SetOption19 0
SetOption55 0
SetOption59 0
restart 1
more information can be found in the wiki:
https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant

**Comment by Gaff** [comment]
Ok - I see that `%prefix%/%topic%/` is not compatible with the abbreviations / base topic (option55).

However if I've set MQTT to use `%prefix%/%topic%/` then there's no point in sending `%topic%/%prefix%/` to HASS - it just leaves the users very confused 😢 


Perhaps we could enforce `%topic%/%prefix%/` for anyone who enables option19? Or make it default? Or make option19 fail if it's not set thusly? Anything is better than where it is now!

**Comment by ascillato2** [comment]
@Gaff

Let's gather all your problems with Hass Autodiscovery in only one issue https://github.com/arendst/Sonoff-Tasmota/issues/4699
