### ISSUE TITLE
Tasmota IR Receive how?

### ISSUE THREAD

**Issue by ceaswaran** [arendst/Sonoff-Tasmota#4701]
I was able to flash this esp8266 based Tuya universal IR (Send/receive) controller with Tasmota. TASMOTA booting successfully with a generic module. I see GPIO 05 marked in PCB for IR receiver LED (Black LED)
I have set GPIO 4 as IR send in my Tasmota console. 
I also see Green LED on device blink when I send a MQTT IRSEND sample code from Tasmota wiki page. 

Question : 
1. How do I know this device really works from the hardware side?
2. How do I receive/learn an IR code from my TV remote to this device (Tasmota console). 
Note: I already have Broadlink RM Pro for IR devices in my living room, But those IR codes don't work in Tasmota console. Broadlinks code looks totally different from the decimal /hex code mentioned in Tasmota wiki page. 

Please help.
![screenshot_2018-12-21-08-32-03-550_com android chrome](https://user-images.githubusercontent.com/40624146/50323049-e7943e80-04fd-11e9-882b-e3d5bf5e68fb.png)
![img_20181220_223316](https://user-images.githubusercontent.com/40624146/50323050-e7943e80-04fd-11e9-9eeb-9eca2b926f07.jpg)
![img_20181220_224955](https://user-images.githubusercontent.com/40624146/50323051-e7943e80-04fd-11e9-9b7e-50e18f564e70.jpg)
![img_20181220_225013](https://user-images.githubusercontent.com/40624146/50323052-e82cd500-04fd-11e9-9946-8d3219fe69b2.jpg)

**Comment by ceaswaran** [comment]
Tasmota support Chat link plz

**Comment by ascillato** [comment]
https://discord.gg/Ks2Kzd4
