### ISSUE TITLE
No SENSOR topic, but there

### ISSUE THREAD

**Issue by vadimbz** [arendst/Sonoff-Tasmota#471]
```
03:04:29 MQTT: tele/sonoff2/TELEMETRY = {"Time":"2017-05-22T03:04:29", "Uptime":6, "POWER":"ON", "Wifi":{"AP":1, "SSID":"Glimmer", "RSSI":100}}
03:04:29 MQTT: tele/sonoff2/TELEMETRY = {"Time":"2017-05-22T03:04:29", "DHT":{"Temperature":"31.7", "Humidity":"73.5"}}
```
I can get data for sensors from it, but every other message causes error, flooding the log. Is there a way around it? Sonoff RF with DHT22

**Comment by davidelang** [comment]
it's not clear what you are asking.

are you saying that you hooked up a sensor, configured it in the module config, 
and are not getting sensor data sent out in the tele/ messages?

we would need more details to know where to start.

**Comment by vadimbz** [comment]
moment, fatfinger hit the enter button

**Comment by vadimbz** [comment]
...and Home Assistant, and Mosquitto
`- platform: mqtt
  name: "Temperature"
  state_topic: "tele/sonoff2/TELEMETRY"
  value_template: "{{ value_json['DHT'].Temperature }}"
  unit_of_measurement: "°C"
- platform: mqtt
  name: "Humidity"
  state_topic: "tele/sonoff2/TELEMETRY"
  value_template: "{{ value_json['DHT'].Humidity }}"
  unit_of_measurement: "%"`
