### ISSUE TITLE
Increase the limit for "Window" from 15 to several hours

### ISSUE THREAD

**Issue by qorron** [arendst/Sonoff-Tasmota#4713]
**Have you look for this feature in other issues and in the wiki?**
yes

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

simulating presence with lights when not at home needs more entropy than +/-15min

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

exchange the drop down for a text input that takes numbers from 0 to 300 (or even higher)
 - or - 
if for some reason the drop down is mandatory and having a drop down with 301 entries s not something one desires, allow higher values being set via mqtt.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

control the switch externally via mqtt: possible but seems far more complex than increasing the limit.

**Comment by arendst** [comment]
There is currently a limit on the amount of bits to use for entropy (4 bits = 0 - 15). For the short term there is no change anticipated.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
