### ISSUE TITLE
Please add REST base report for SonOff POW measurements

### ISSUE THREAD

**Issue by halacs** [arendst/Sonoff-Tasmota#4714]
**Have you look for this feature in other issues and in the wiki?**
yes

**Is your feature request related to a problem? Please describe.**
I already have a PHP script what collects measurements from other sources via REST. It would be nice to integrate my boiler controlled by a SonOff POW. I don't want to add a new component to my system just because of this (MQTT). REST report would ensure that an attacker cannot modify my Sonoff from the Internet.

**Describe the solution you'd like**
POW would periodically send its measurements as it does in case of MQTT but via REST. Web UI would have a configurable URL to define where to POST the measurements in json format.

**Describe alternatives you've considered**
Using MQTT as transport protocol then use mqttwarn to forward the received information into the database what the REST use. This solution would need extra effort in the operation.

Thanks!

**Comment by Jason2866** [comment]
Tasmota is designed for use as a mqtt device. Web frontend isnt the core goal. Just a nice to have
Do to the fact of the limited resources of the device your wish will probably not implemented from Theo.

**Comment by arendst** [comment]
Just pull the info using HTTP. See wiki commands how to.

**Comment by halacs** [comment]
Then would it be acceptable to add a "freeze" MQTT command somehow? The goal of this would be to make impossible to control the device via MQTT. Device would be able to send telemetry data but receive any command.

**Comment by ascillato** [comment]
You can use rules, events and websend command. Search in issues. This was already addressed. Thanks

**Comment by arendst** [comment]
You can turn off MQTT on the fly. See wiki commands.
