### ISSUE TITLE
rules timer not executing

### ISSUE THREAD

**Issue by shanekuz** [arendst/Sonoff-Tasmota#4717]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used :
- [x] Hardware used : 
- [ ] If a pre-compiled release or development binary was used, which one? :
- [ ] You have tried latest release or development binaries? :
- [x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
You hve to check. `"ARM"`
![image](https://user-images.githubusercontent.com/24528715/50382971-f8ce7e00-06aa-11e9-9f23-b70477b373d0.png)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by manikdutta** [comment]
Rules on timer not working..
![untitled](https://user-images.githubusercontent.com/17022949/52624144-0eef0280-2ed4-11e9-982a-f18615a307d9.png)

**Comment by ascillato** [comment]
Hi,

Please, stop spamming issues. You have an answer in the issue you have opened.

**Comment by shanekuz** [comment]
I don’t know what you mean I have not spammed anything I raised an issue and have not done anything since

**Comment by ascillato** [comment]
@shanekuz

Sorry, that was not meant for you.

Was for @manikdutta that he/she is posting his/her issue repeteadly in several issues.
