### ISSUE TITLE
Variables %time%, %uptime%, %sunrise% or %sunset% wrong result

### ISSUE THREAD

**Issue by clientgithub** [arendst/Sonoff-Tasmota#4722]
Rule:
Rule on RfReceived#RfKey=1 do publish tele/sonoff_rf/ALARM %time% endon
Result:
tele/sonoff_rf/ALARM 1279

Rule:
Rule on RfReceived#RfKey=2 do publish tele/sonoff_rf/SUNSET %sunset% endon
Result:
tele/sonoff_rf/SUNSET 961

Tasmota 6.4.0
Hardware used: Sonoff RF Bridge 433

**Comment by clientgithub** [comment]
Sorry, i not see this post:

%time% : actual elapsed time since midnight in minutes
%sunrise% : sunrise in minutes
%sunset% : sunset in minutes
%uptime% : actual uptime in minutes

But how send to topic current date and time?

**Comment by ascillato** [comment]
Every tele message has date and time.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
