### ISSUE TITLE
wifi problem with 6.4 on wemos d1 mini

### ISSUE THREAD

**Issue by mpuff** [arendst/Sonoff-Tasmota#4725]
Hello,

i have wifi problems with v6.4 and wemos d1 mini.
the most time the devices are disconnected from wlan, so i went back to 6.3, now it is running without disconnections again.

**Comment by ascillato2** [comment]
Hi,

Seems that you have a bad flashing problem.

You should erase all flash with esptool.py as explained in the wiki and flash again with the precompiled bins from release.

Please, check the wiki at https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#wifi-issues-arduino-core-versions-and-expressif-sdk for explanations
Also check issue: #4697
