### ISSUE TITLE
Can not connect with Wifi (PlatformIO and 6.4.0 and Wemos-d1) with Arduino IDE it is working.

### ISSUE THREAD

**Issue by MAWMN** [arendst/Sonoff-Tasmota#4726]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x ] Development/Compiler/Upload tools used :
- [x ] Hardware used : Wemos D1
- [x ] If a pre-compiled release or development binary was used, which one? : 
- [x ] You have tried latest release or development binaries? :
- [x ] Provide the output of command ``status 0`` : not possible won't start
```
STATUS 0 OUTPUT HERE
00:00:51 CMD: status0
00:00:51 RSL: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"
PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"Switch
Retain":0,"SensorRetain":0,"PowerRetain":0}}

**(Please, remember to close the issue when the problem has been addressed)**

My compilation with PlatformIO won't connect to my WiFi, the same source(and settings) compiled with Arduino IDE is working OKE ??

PART of the PlatformIO serial LOG : 
00:04:42 WIF: Verbinden met AP1 mna_AP in stand 11N als sonoff-3173...
00:04:54 WIF: Verbinding mislukt door fout wachtwoord
00:04:55 WIF: Verbinding mislukt door fout wachtwoord
00:04:55 WIF: Verbinden met AP1 mna_AP in stand 11N als sonoff-3173...
00:04:59 RSL: tele/sonoff/STATE = {"Time":"1970-01-01T00:04:59","Uptime":"0T00:04:59","Vcc":3.739,"SleepMode":"Dynamic","Sleep":5
0,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"mna_AP","BSSId":"FF:FF:FF:FF:FF:FF","Channel":11,"RSSI":100}}
00:05:07 WIF: Verbinding mislukt door fout wachtwoord
00:05:08 WIF: Verbinding mislukt door fout wachtwoord

**Comment by ascillato2** [comment]
Hi,

Seems that you have a bad flashing problem.

You should erase all flash with esptool.py as explained in the wiki and flash again with the precompiled bins from release.

Please, check the wiki at https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#wifi-issues-arduino-core-versions-and-expressif-sdk for explanations
Also check issue: #4697
