### ISSUE TITLE
Core 2.4.2 as default?

### ISSUE THREAD

**Issue by ihavenonick** [arendst/Sonoff-Tasmota#4729]
Ab 6.4.0.3 ist der Core 2.4.2 wieder default und alle damit verbundenen Probleme.
HUE Emulation funktioniert nicht
Websend läuft nur sporadisch wenn man damit ein anderes Tasmota Gerät schalten möchte.
Ein Beispiel:
`Rule1 on Power1#State=1 do websend [192.168.100.60:80,admin:joker] POWER1 ON endon on Power1#State=0 do websend [192.168.100.60:80,admin:joker] POWER1 OFF endon`

**Comment by ascillato** [comment]
Hi, sorry I can't understand your post. Please, write in English with the template completed. Thanks

**Comment by ihavenonick** [comment]
From Tasmota version 6.4.0.3 the Core 2.4.2 is default again and all related problems.
Websend runs only sporadically if you want to switch it with another Tasmota device.
An example:
`Rule1 on Power1#State=1 do websend [192.168.100.60:80,admin:joker] POWER1 ON endon on Power1#State=0 do websend [192.168.100.60:80,admin:joker] POWER1 OFF endon`

**Comment by ascillato** [comment]
Please, see the wiki at:

https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#wifi-issues-arduino-core-versions-and-expressif-sdk

There you have the links for other cores also. Thanks

**Comment by ihavenonick** [comment]
OK, thanks for the link. Is it correct that in the Core 2.5.0 patch no longer the parsing.cpp is necessary?

**Comment by ascillato** [comment]
Correct. Core 2.5.0 has Alexa bug fixed and also light_modem_sleep bug fixed.

**Comment by ascillato** [comment]
Great! Thanks for sharing your tests. Very appreciated.
