### ISSUE TITLE
Sonoff DUAL

### ISSUE THREAD

**Issue by Kurvi** [arendst/Sonoff-Tasmota#473]
Hi everybody,
whant to use the Sonoff DUAL for controlling my windows shutters to open and close it. 
But it it very importent that never bouth relais will be switched on at same time.

Is there any possibility in the configuration files to set this option?

Thank you for your help.

**Comment by davidelang** [comment]
no, there is nothing in the software preventing both relays from being on at the 
same time. search other issues for 'shutters' and you will find many discussions 
on options.

**Comment by Kurvi** [comment]
Problem solved. 👍 
Please follow tread #309 Support for Shutter motors?
