### ISSUE TITLE
4CH Pro R2 switch behaviour

### ISSUE THREAD

**Issue by Jackosme** [arendst/Sonoff-Tasmota#4736]
Hi, this is probably a configuration issue rather than a tasmota issue but hopefully you can help.

I've flashed a Sonoff 4CH Pro R2 (v1.0) with Tasmota v6.4.1.  While i can switch the relays via MQTT the physical buttons on the board do no work.  I was getting the following showing in the console;

cmnd/sonoff/sonoff/POWER1 = TOGGLE
cmnd/sonoff/sonoff/POWER2 = TOGGLE
cmnd/sonoff/sonoff/POWER3 = TOGGLE
cmnd/sonoff/sonoff/POWER4 = TOGGLE

While toggle shows in the console the relay does not toggle or make any noise and the LED does not blink.  How can i get the push buttons to work the relays?

I have have also changed some config and POWER1 = TOGGLE  is not showing in the console as if i have disabled that button via a command (not sure what command though)

I have the board set to SELF-LOCKING and all DIP switches are set to SELF-LOCKING as well.

**Comment by ascillato** [comment]
Set the dip switches as explained in the wiki at https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-4CH-and-4CH-Pro#4ch-pro-dipswitch-configuration

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by Jackosme** [comment]
I have done so, as mentioned above.  

Work Mode Switch S6 = 1
Work Mode Switch K5, CH1 = 1, CH2 =1, CH3 = 1, CH4 =1.

**Comment by ascillato** [comment]
K6 to 0?

Have you solder or unsolder anything?

Have you set any rule?

**Comment by Jackosme** [comment]
> K6 to 0?
> 
> Have you solder or unsolder anything?
> 
> Have you set any rule?

K6 all to 0, yes.  I only soldered 4 pin header for flashing, but nothing else.

I have a standard backlog command for general setup which includes SSID, PW, MQTT IP + User + PW as well as switchretain off, powerretain off and poweronstate 3.

I have been playing around with and included switchmode 3 (which i believe is default?) 

I have two CH4 Pro R2s, both were flashed with Sonoff-Tasmota 5.13.1 and both having the same issue.  I have since flashed Sonoff-Tasmota 6.4.1 over the top of one of them.  Still the issue is the same.

It might be easier to start from scratch, but it must be a simple configuration issue i think.  Both are working fine via MQTT and the webpage for all 4 relays on both devices.

**Comment by Jackosme** [comment]
Both are set as '23 SONOFF 4CH PRO'

**Comment by ascillato** [comment]
Try to use reset 5 command in the console. This will erase all your config except wifi credentials. After reboot just select your module and try the physical buttons.

**Comment by Jackosme** [comment]
I did this in the end and the physical buttons are working again.  Incidentally, the device with v5.13.1, 3 of the 4 physical buttons worked after reset 5 but since flashing with 6.4.1 the 4th button is working now.  Not sure what the issue was, but thank you for your quick replies.

Both devices working as expected in HA and also with physical button press. :)
