### ISSUE TITLE
Make variable/mem comparison a trigger for rules. (more clearer to understand)

### ISSUE THREAD

**Issue by AalianKhan** [arendst/Sonoff-Tasmota#4737]
Hello,
I want to compare two variables to see if they are equal or not. but as @ascillato said "Tasmota must know 'when' to trigger the comparison". So to work around this issue you can add the rule like this 
```on Time#Minute var1=var2 do ruletimer1 300```
This way Tasmota knows when to trigger the rule. 
You can also do this `Events` but they can get really big and confusing really fast.

Thank you.
Note I made this issue before but it was really open ended and I didn't tell the problem in detail so I hope this is better to understand.

**Comment by ascillato2** [comment]
Let's try not to duplicate issue in order to not confuse people searching for solutions. Comment copied to the original issue: https://github.com/arendst/Sonoff-Tasmota/issues/4730
