### ISSUE TITLE
Linker Script not Needed anymore 

### ISSUE THREAD

**Issue by hallard** [arendst/Sonoff-Tasmota#474]
Hi guys,

Not really an issue, just to let you know that the latest Arduino ESP8266 V2.4.0rc1 just released one day ago and include the correct linker script for :

- 1M (NoSPIFFS) Option see this [commit](https://github.com/esp8266/Arduino/commit/0b47911b69bf349af06047da1a93b9f2944f9dd5#diff-fce09ad94aad2ba67472cd9142f00146)

See here for doc and how to install new [release](https://github.com/esp8266/Arduino/releases/tag/2.4.0-rc1)

May be worth updating the Wiki [documentation](https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite) by removing all modification to boards.txt not needed anymore ;-)

**Comment by ulab** [comment]
Thanks, this helped a lot after not getting it to work manually on my Mac for some reason.  

Easiest way to install V2.4.0rc1 is to use the board manager as usual using this URL: https://github.com/esp8266/Arduino/releases/download/2.4.0-rc1/package_esp8266com_index.json
