### ISSUE TITLE
IFAN02 MQTT RESULT JSON should include both FandSpeed and Power1 Values

### ISSUE THREAD

**Issue by gbrogna** [arendst/Sonoff-Tasmota#4740]
Since the MQTT command stat/Device/RESULT is returned on every change of the device wether it is the light or fan speed it should always return in JSON and include all fields.  It makes it difficult getting the status of the device.

**Comment by arendst** [comment]
You might want to read the wiki regarding command ``SetOption4 1``

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by gbrogna** [comment]
Thank you! Worked like a charm
