### ISSUE TITLE
Shelly 1 not working with switch

### ISSUE THREAD

**Issue by cschwarz007** [arendst/Sonoff-Tasmota#4742]
Dear all,

appreciate your support upfront. I have the following scenario: I want to use a Shelly 1 any use the switch functionality (by connecting a switch to the SW input of the device). I compiled Tasmota (both 6.4.0 and 6.4.1) with standard settings (using sonoff-knx presets), but neither works with the switch. Power gets attached to the "SW" input, but the Shelly ignores it and does not switch the output to voltage.

Can anyone help me solve this issue?

Many thanks in advance!
Christian

**Comment by ascillato** [comment]
Please complete the troubleshooting template in order to have more information so as to properly help you

**Comment by ascillato2** [comment]
Please, when you have time, provide more information so as to help you. Thanks.
