### ISSUE TITLE
Old phone rotary dial support as sensor

### ISSUE THREAD

**Issue by donatmarko** [arendst/Sonoff-Tasmota#4743]
I would love to see a sensor that supports rotary dial (the round thing on old landline phones) as sensor input.

It acts more or less a counter, but the dialed digit should only be posted/sent when the dial has stabilized (no further pulses received after a specified amount of time).

I am currently using the Counter input, but as said it sometimes sends the value when the dial is still spinning, therefore returns a completely different value than the dialed one.

Please look into this feature request, these kind of old thingies have a good fun factor, e.g. to control smart home appliances with them 🙂

**Comment by ascillato2** [comment]
Thanks for sharing your ideas.

Added label for future reference.
