### ISSUE TITLE
Upgrade from 6.3.0 to 6.4.x 

### ISSUE THREAD

**Issue by sindudas** [arendst/Sonoff-Tasmota#4748]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

**Describe the bug**
_A clear and concise description of what the bug is._
When upgrading from 6.3.0 flashed with Arduino, and with Wifi settings already configured and working, then upgrading to 6.4.0 o 6.4.1 with sonoff.bin from github. Results in device in WifiManager Mode, without IP and SSID, and unable to connect it as AP or connected to the Wifi configured before.
Seen that on 2 Wemos D1 mini.
Flashing again with 6.3.0 with Arduino IDE, works like before upgraded, SSID yet configured and connects to that SSID.
Configuring throw the Serial the SSID and Password on 6.4.1, it connects to the Wfii. But flashing with Arduino and 6.3.0, and then sonoff.bin with 6.4.1, still the same issue.
Finally tested with same results version 6.4.1.1(6f55964-sonoff)-2_5_0_BETA2

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [X] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : Wemos D1 Mini
- [X] _Development/Compiler/Upload tools used_ : Arduino 1.8.5 / ESP8266 2.4.2 
- [ ] _If a pre-compiled release or development binary was used, which one?_ :
- [ ] _You have tried latest release or development binaries?_ :
- [ ] _Provide the output of command_``status 0`` :
```
STATUS 0 OUTPUT HERE - DO NOT DELETE THE MARKERS ABOVE AND BELOW THIS LINE
00:00:00 Project sonoff Sonoff Version 6.4.1.1(6f55964-sonoff)-2_5_0_BETA2
00:00:00 WIF: WifiManager active for 3 minutes
00:00:00 HTP: Web server active on sonoff-7997 with IP address (IP unset)
00:00:06 CMD: status 0
00:00:06 RSL: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:00:06 RSL: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:06","StartupUTC":"","Sleep":50,"BootCount":8,"SaveCount":11,"SaveAddress":"F6000"}}
00:00:06 RSL: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.4.1.1(6f55964-sonoff)","BuildDateTime":"2018-12-26T23:12:02","Boot":16,"Core":"2_5_0_BETA2","SDK":"3.0.0-dev(c0f7b44)"}}
00:00:06 RSL: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["",""],"TelePeriod":300,"SetOption":["00008009","558180C0","00000000"]}}
00:00:06 RSL: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":546,"Free":456,"Heap":25,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640E0","FlashMode":3,"Features":["00000809","0FDAE794","000383A0","23B617CE","00003BC0"]}}
00:00:06 RSL: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-7997","IPAddress":"(IP unset)","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"A0:20:A6:19:7F:3D","Webserver":2,"WifiConfig":4}}
00:00:06 RSL: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_197F3D3D","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:00:06 RSL: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 00:00:06 1970","Local":"Thu Jan 01 00:00:06 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":"+00:00","Sunrise":"07:43","Sunset":"16:03"}}
00:00:06 RSL: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:00:06"}}
00:00:06 RSL: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:00:06","Uptime":"0T00:00:06","Vcc":3.003,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"","BSSId":"00:00:00:00:00:00","Channel":1,"RSSI":100}}}
```

**To Reproduce**
_Steps to reproduce the behavior:_
Download 6.3.0 from github, open with Arduino, and flash Wemos D1 Mini. Then from the Web, upgrade to 6.4.1/6.4.0 with downloaded sonoff.bin

**Expected behavior**
_A clear and concise description of what you expected to happen._
Upgrade without issues.

**Screenshots**
_If applicable, add screenshots to help explain your problem._
00:00:00 CFG: Use defaults
00:00:00 Project sonoff Sonoff Version 6.4.1(sonoff)-2_4_2
00:00:00 WIF: WifiManager active for 3 minutes
00:00:00 HTP: Web server active on sonoff-7997 with IP address 0.0.0.0

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

I could not reproduce your issue. Sorry.

Seems that you have a bad flashing issue.

Please check the wiki for more explanations and solutions at: https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#wifi-issues-arduino-core-versions-and-expressif-sdk
