### ISSUE TITLE
Sonoff Touch don't work

### ISSUE THREAD

**Issue by adaha82** [arendst/Sonoff-Tasmota#475]
Hello
After uploading the firmware my SONOFF TOUCH does not work. What could be the reason?
Upload firmware to SONOFF DUAL and SONOFF BASIC and everything works.
Why does not SONOFF TOUCH work? May I connect badly?

Please help
Adam

**Comment by TRIROG** [comment]
Most likely a bad ESP8285 chip.
I had the same thing happen to me. Flash went through without problems, but it would not boot afterwards.
Try opening a serial port after flashing to verify the tasmota firmware starts successfully.
If you get only garbage output at 115200 baud it is very likely a bad chip.
You can then confirm this by switching baud to 76800 (i think) and then reset the chip to see what the boot output is.

Upon flashing in serial at 115200 baud i got
```
Fatal exception (0): 
epc1=0x40217e08, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
```
at 74880 baud i get
```
 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0xef
csum 0xef
csum err
ets_main.c
```

I replaced the chip and now it works.
