### ISSUE TITLE
Tasmota with NeoCoolcam WiFi PIR sensors

### ISSUE THREAD

**Issue by TSparkas** [arendst/Sonoff-Tasmota#4753]
I have few of these Neo Coolcam WiFi PIR sensors: https://www.banggood.com/NEO-COOLCAM-NAS-PD02W-WiFi-PIR-Motion-Sensor-Detector-Home-Alarm-System-Motion-with-Magnet-Bracket-p-1285340.html?rmmds=myorder&cur_warehouse=CN

They are controlled via Tuya app and are running on ESP8266, so it should possible to flash them with Tasmota. 

Has anybody tried this? Will it be possible to configure deep sleep mode to save battery life?

I have found some efforts here: https://community.home-assistant.io/t/coolcam-wifi-motion-sensor-pir/54783/16

**Comment by Jason2866** [comment]
You are the first...
Tasmota is not designed to work with deep sleep and will not support this.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
