### ISSUE TITLE
Cant flash sonoff

### ISSUE THREAD

**Issue by NicoSoftware** [arendst/Sonoff-Tasmota#4757]
I'm a complete noob with flashing firmware to devices and actually never really used arduino before.
I'm using this FTDI Board:
https://www.ebay.de/itm/FTDI-Adapter-FT232RL-USB-zu-TTL-Serial-3-3V-und-5V-f%C3%BCr-Arduino-PRO-Mini/272300614420?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649
Which gets detected as serial PORT5 (connected with the old micro usb stadard to a USB 2.0 Port)
With Sonoff Basics
These are my Arduino settings:
![image](https://user-images.githubusercontent.com/35654361/50538269-fa95b700-0b6c-11e9-8457-9a423cde618f.png)
With ESP8266 2.4.2:
![image](https://user-images.githubusercontent.com/35654361/50538274-1600c200-0b6d-11e9-9d68-38ee31c23354.png)
Flash procedure:
- Connecting Pins:
Sonoff GND to FTDI GND
Sonoff 3.3v to FTDI VCC
Sonoff RX to FTDI TX
Sonoff TX to FTDI RX
- pressing down the Button
- compile with arduino

But I'm always getting:
```
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed
```
Errors, what am I missing?

**Comment by Jason2866** [comment]
You have to press and hold the button before you connect the FTDI to PC!
Everything else looks correct

**Comment by ascillato2** [comment]
For better and more dynamic troubleshooting help, please address this in the Tasmota Chat. Github issues are for bug reporting. Thanks
