### ISSUE TITLE
H801 with 2 LED strips independent (2 x CW  or RGB+CW)

### ISSUE THREAD

**Issue by EricG77** [arendst/Sonoff-Tasmota#4766]
Hello,
I connected 2 CW LED Strips to H801 (first at W1 and W2, the second at G an R).
They should be controlled seperatly.
I am newbe in development.
Where the best way to start in the code? (Adding new light-type in xdrv04_light ?)

Or is there a planning for this feature?

Eric

H801  has 5 PWM channels. The idea is to control 2 LED strips. 1 CW strip (2 channels) and 1 CW (2 channels) or 1 RGB strip (3 channels).
The light driver supports one strip only.

**Comment by arendst** [comment]
No plan for this feature as it interferes with the current single light policy. Implementation would mean a major change in code.
