### ISSUE TITLE
Wemos d1 mini DHT shield V3.0.0

### ISSUE THREAD

**Issue by igazka** [arendst/Sonoff-Tasmota#4768]
**Have you look for this feature in other issues and in the wiki?**
DHT shield version v1.0.0 support [found]([https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-DHT11-Shield-Humidity-&-Temperature]), v3.0.0 not.
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/31811932/50549592-c7802000-0c5f-11e9-8f38-8c22422301a6.png)
![image](https://user-images.githubusercontent.com/31811932/50549594-d5ce3c00-0c5f-11e9-9a2d-5469a3df6563.png)
This is with a Dht shield v3.0.0.
**Describe the solution you'd like**
Support for the DHT shield v3.0.0

**Comment by Jason2866** [comment]
You found a solution via Module Generic. Not every device can be added because of the limited
hardware resources from the ESP chip. Feel free to add your finding to the wiki!

**Comment by igazka** [comment]
> The DHT device is not a I2C device so do not expect any useful info when connecting a DHT using the SDA/SCL GPIO config.
> 
> See the wikki how to configure/connect a DHT.

I did read the wiki, and did not found that the shield i am refering to.
I am talking about this shield:
https://wiki.wemos.cc/products:d1_mini_shields:dht_shield

**Comment by Jason2866** [comment]
This is not a sensor it is a random generator connected via I2C.

**Comment by andrethomas** [comment]
Some DH12 sensors are around that are I2C variants of sensors other than the DHT ones but they are encased the same.

You getting a false detect for a BH1750 which is on I2C address 0x23 or 0x5C - If you perform an i2cscan command from the console and find which of the two addresses are found you may be able to determine what the sensor is based on that, but its definitely not a traditional single wire sensor based on the schematic in the wiki.

**Comment by igazka** [comment]
> Some DH12 sensors are around that are I2C variants of sensors other than the DHT ones but they are encased the same.
> 
> You getting a false detect for a BH1750 which is on I2C address 0x23 or 0x5C - If you perform an i2cscan command from the console and find which of the two addresses are found you may be able to determine what the sensor is based on that, but its definitely not a traditional single wire sensor based on the schematic in the wiki.

I found 0x5c with the "i2cscan" command. This is the newest dht12 shield(v3.0.0) for the wemos d1 mini as i linked above. It is communicating via D1(SCL) and D2(SDA).

**Comment by Jason2866** [comment]
Let me explain my comment. Since DHT 11 (DHT12 is a variant of this) is a very bad and outdated sensor
there will be no support for this sensor. There are extreme better sensors which are already supported
(for I2C as example the BME280)

**Comment by andrethomas** [comment]
I2C Address find on 0x5C is most likely a repurposed AM2315 or equivalent. There is no driver for this in Tasmota so it will not work at this time.

As recommended by @Jason2866 rather obtain a BME280 as it will yield better results than a DHT11/12/22 would anyway.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by vinibali** [comment]
> Let me explain my comment. Since DHT 11 (DHT12 is a variant of this) is a very bad and outdated sensor there will be no support for this sensor. There are extreme better sensors which are already supported (for I2C as example the BME280)

It's not that bad actually:
https://www.bvinarz.org/20230827/compare-bosch-bmp280-and-dht12-temperature-sensor-accuracy/

**Comment by barbudor** [comment]
1° is bad
Now comparing BMP280 to DHT12 without a proper reference such a a high accuracy thermometer is pointless. You know there is a difference but you still don't know who is good or who is bad. 

Hdc1080 is even better than BME280 if you don't need the pressure

There are already enough T/HR sensors supported  by Tasmota. There's no will to make Tasmota support all sensors available in the world but focus on a few of good sensors that people are OK to maintain.

**Comment by vinibali** [comment]
> 1° is bad Now comparing BMP280 to DHT12 without a proper reference such a a high accuracy thermometer is pointless. You know there is a difference but you still don't know who is good or who is bad.
> 
> Hdc1080 is even better than BME280 if you don't need the pressure
> 
> There are already enough T/HR sensors supported by Tasmota. There's no will to make Tasmota support all sensors available in the world but focus on a few of good sensors that people are OK to maintain.

there is a stable diff of 1°C, which you can easily get rid off by using some offset. that measurement was done to prove that DTH12 is not a random number generator.
both sensors are supported by Tasmota, my goal was not about the prove: "okay, we need to support this".
I hope it's better to understand now.
BR
