### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by stefanoMancon** [arendst/Sonoff-Tasmota#4769]
invalid conversion from 'char*' to 'const uint8_t* {aka const unsigned char*}' [-fpermissive]

**Comment by Jason2866** [comment]
Your setup has to be faulty.
Latest dev version compiles without any error.
Since you ignored the needed issue template no help can be provided

**Comment by andrethomas2** [comment]
Please note that GitHub Issues are for reporting bugs and requesting additional features.

Please search the Wiki for the information you require or visit Discord Chat where general questions and answers are handled.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
