### ISSUE TITLE
Update Wiki to reflect flash size setting 1M (no SPIFFS) for version 5.0.0 and up

### ISSUE THREAD

**Issue by TRIROG** [arendst/Sonoff-Tasmota#477]
If i understand correctly, for flashing version 5.0.0 and up Flash size should be set to 1M (no SPIFFS).
Wiki should reflect that.

**Comment by gajotnt** [comment]
It does...
https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite

**Comment by TRIROG** [comment]
I was refering to the section [https://github.com/arendst/Sonoff-Tasmota/wiki/Hardware-Preparation](url)
Where for example for the Touch it is stated that certain changes should be made, which could be misunderstood.
```
Sonoff Touch
As the Sonoff Touch is based on the ESP8285 using Flash Mode DOUT you will have to make some changes to the proposed Arduino IDE settings as follows:

    Tools Board Generic ESP8285 Module
    **Flash Size: 1M (64K SPIFFS)**
```

**Comment by gajotnt** [comment]
There it should be updated :)

**Comment by filzek** [comment]
There is a problem on Arduino IDE where it doesnt allow 1M (no SPIFFS), so how to set it?
![image](https://user-images.githubusercontent.com/29267027/26911966-6cc987bc-4be7-11e7-8482-95ccfdb01ab4.png),

Is there any idea?
