### ISSUE TITLE
Datetime of last event sent in status mqtt

### ISSUE THREAD

**Issue by smartandsafe** [arendst/Sonoff-Tasmota#4770]
Hi:
is there a way to get the last time of event (ex: switch change) in mqtt status or tele?
or is there a way to save the datetime of event (ex: switch change) as var1 using rules?

Does someone can give me an approach to get it?

thankyou

**Comment by wongnam** [comment]
Use "rule" to check switch#state and do publish stat/topic/time

Read wiki.

**Comment by smartandsafe** [comment]
Thanks for your answer
i tried and i get {"Time":"%timestamp%"}  message in mqtt, i don´'t get the time in message.

(i tried with and without quotes)

it seems  %timestamp%  is not being saved as variable.


thank you
