### ISSUE TITLE
Retrieve Heat Index from DHT22 (AM2301(2)) Sensor

### ISSUE THREAD

**Issue by gbrogna** [arendst/Sonoff-Tasmota#4771]
I reviewed the WIKI and searched considerably and I found no reference to retrieving the Heat Index from a DHT22 sensor.  I am wondering if there is an away or can it be added?

I retrieve the heat index using a regular Arduino sketch

    float t = dht.readTemperature(true);
    dtostrf(t, 4, 2, msg);
    client.publish("Thermostat/Master/Temperature", msg);
    Serial.print("Temperature: ");
    Serial.println(msg);
    
    float h = dht.readHumidity();
    dtostrf(h, 4, 2, msg);
    client.publish("Thermostat/Master/Humidity", msg);
    Serial.print("Humidity: ");
    Serial.println(msg);
  
    float hif = dht.computeHeatIndex(t, h);
    dtostrf(hif, 4, 2, msg);
    client.publish("Thermostat/Master/HeatIndex", msg);
    Serial.print("Heat Index: ");
    Serial.println(msg);

Thank you in advance and I hope I did not miss anything

**Comment by Jason2866** [comment]
What is Heat Index?

**Comment by gbrogna** [comment]
Thank you.

**Comment by boozeman** [comment]
Hi,

Seems like heat Index do not include any information of the unit of measurement, so It works nicely in Tasmota screen, but Home Assistant do not know what measurement type is so the history looks like this:
![image](https://github.com/arendst/Tasmota/assets/40159019/27290b9f-1138-4e95-9197-439e2dd803ea)

Seems like it does not know the TempUnit: "C/F" on mqtt message json?

**Comment by barbudor** [comment]
This is by design, only units that can be changed are explit
Other units are assumed

**Comment by sfromis** [comment]
In general, it is up to HA to "know" what unit applies to each value, but when there is a sensor with "Temperature", the default temperature unit of Tasmota, C/F, should already be included in the sensor payload. In HA, this is not linked to HeatIndex, as [hatasmota](https://github.com/emontnemery/hatasmota/) has a table of what sensor names are which unit, and possibly `HeatIndex` should be processed the same way as `DewPoint`.

One question may be if the heat index calculation above is in C or F, or works for both. The many "magic numbers" suggests that the formula may be for Fahrenheit. If this speculation is correct, it would be needed to make sure that Tasmota can calculate HeatIndex for both types of temperature units, before it would work well to have hatasmota "know" that the `TempUnit` field in the JSON applies.

**Comment by arendst** [comment]
Don't worry. HeatIndex, just like Dewpoint adjusts to Fahrenheit AND celsius as other temperature results.

**Comment by jeroenst** [comment]
Thank you for implementing this feature!

**Comment by sfromis** [comment]
Then, next step could be to fix hatasmota to include this.

Or maybe open the old can of worms about Tasmota being able to report units with the various sensor values, instead of the subscriber needing to know all those units by itself.

**Comment by boozeman** [comment]
One more pic for the situation here:
![image](https://github.com/arendst/Tasmota/assets/40159019/14421ef4-af57-4025-a77f-8193f04ca220)

When I looked at the matter more closely and with rested eyes, I noticed that the decimal separator is a dot and not a comma as we here in northern Europe tend to use. There is probably a reason to make some changes to the code so that users don't have to make manual MQTT sensors that take into account the unit of measure and the decimal separator?

And Thanks for the brilliant work!

**Comment by sfromis** [comment]
Here's what I'm seeing in Tasmota: 
![image](https://github.com/arendst/Tasmota/assets/47082390/b33e37b6-5e5a-4e9e-b971-c00d1f7dd58e)
Unit is included, and a space in the name instead of the key. Did you make sure to use a fresh source download for building?

Or is your screenshot not from Tasmota? In that case, next step is not up to what happens in Tasmota, but maybe hatasmota which I already hinted at a couple of times.

**Comment by sfromis** [comment]
I was surprised to not see the heat index for BME280, with it appearing for other sensors. 
![image](https://github.com/arendst/Tasmota/assets/47082390/3048ef14-fa0d-47bf-9fee-df9baf33df37)

**Comment by sfromis** [comment]
Also see https://github.com/arendst/Tasmota/discussions/19666 for more generalized support for including units in the payloads, instead of the subscriber having to "know" this implicitly.

**Comment by arendst** [comment]
Ha. I noticed yesterday the BMP/E code indeed doesn't use the generic TempHum functions. I guess because not all BMP's support humidity but looking briefly at the code I couldn't understand how the humidity was handled.

Will investigate today (again).

**Comment by arendst** [comment]
Fixed

![image](https://github.com/arendst/Tasmota/assets/11044339/48f782f7-b3cc-4c72-b97b-e592d61f5f8e)

**Comment by boozeman** [comment]
> Here's what I'm seeing in Tasmota: 

Yeah, It is on HA > Devices > Tasmota > Greenhouse1.  
![image](https://github.com/arendst/Tasmota/assets/40159019/ac3a5cab-c5f7-4b29-b638-d85e3bb13400)
Readings are allright on Tasmota web gui.

I don't see any weird stuff on mqtt json either. Tasmota Discovey is active

 {
  "Time": "2024-02-19T20:42:05",
  "Switch1": "ON",
  "Switch2": "ON",
  "BME280": {
    "Temperature": 11.7,
    "Humidity": 38.7,
    "DewPoint": -1.9,
    "Pressure": 1006.5,
    "SeaPressure": 1018.3
  },
  "SHT3X": {
    "Temperature": 9.7,
    "Humidity": 45.9,
    "DewPoint": -1.4,
    "HeatIndex": 8
  },
  "HX711": {
    "Weight": 0.5,
    "WeightRaw": 3276,
    "AbsRaw": 58975
  },
  "PressureUnit": "hPa",
  "TempUnit": "C"
}

**Comment by sfromis** [comment]
Again, it is because [hatasmota](https://github.com/emontnemery/hatasmota/) (the Tasmota Integration feature of HA) has a table to to select which JSON field names (like Humidity) has what unit of measurement, as those are nowhere in the JSON. Hence it does not "know" what `HeatIndex` is about.

**Comment by sfromis** [comment]
Sensor name SI7021 also includes Temperature and Humidity, but no HeatIndex. Devices are at least Sonoff THR316D and Sonoff TH16. 
![image](https://github.com/arendst/Tasmota/assets/47082390/6941b066-ed4c-4b52-9bef-416dbbc1547a)

`{"Time":"2024-02-21T21:16:55.911+01:00","SI7021":{"Temperature":20.40,"Humidity":54.90,"DewPoint":11.01},"TempUnit":"C"}`

**Comment by Noschvie** [comment]
Shall the HeatIndex be added for the SCD40 / 41 sensor too?

````
{
   "Time":"2024-02-22T07:08:49",
   "SCD40":{
      "CarbonDioxide":409,
      "eCO2":409,
      "Temperature":25.1,
      "Humidity":42.3,
      "DewPoint":11.4
   },
   "TempUnit":"C"
}

**Comment by arendst** [comment]
It should have been there. If not I’ll fix it asap. It should be everywhere where dewpoint is too.

**Comment by Noschvie** [comment]
Ok. This compile option wasn't noted in this issue so far.
