### ISSUE TITLE
6.4.1 crash/corrupted flash?

### ISSUE THREAD

**Issue by GianCann** [arendst/Sonoff-Tasmota#4773]
Yesterday i have update (OTA) my ESP8266 D1 Mini from 6.3 to 6.4.1.
All works fine, but few minute ago the device stop responding from web interface (i'm away of my home) and after some another minute it's back "live" with corrupted html GUI.
I have configured the module as generic with four LED and four button.

What'a appened?

[
![img_20181231_131417](https://user-images.githubusercontent.com/45897944/50560161-49268b00-0cfe-11e9-9a09-694c37fec0fb.jpg)

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
