### ISSUE TITLE
Using var in payload for status

### ISSUE THREAD

**Issue by smartandsafe** [arendst/Sonoff-Tasmota#4774]
Hi:

please, someone tell me which is the way to use the "memX" variables in payload for status?

i added ",\"" D_CMND_POWERHIGH "\":%mem1%}"  to payload for status 11

AND I GET ,       "PowerHigh":mem1"

thanks

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
