### ISSUE TITLE
Problem with Sonoff TH16

### ISSUE THREAD

**Issue by 1Topf** [arendst/Sonoff-Tasmota#4775]
Hello everybody :o),
I have a new TH16 (with DS18B20-sensor) and flashed it with Tasmota 6.2.1. But I can`t see the temperature. When I choose "AM2301", I see "nan°C". Any ideas?
Many greetings and a Guten Rutsch ins neue Jahr :-D,
Andi

![sonoff_th16_2](https://user-images.githubusercontent.com/44591717/50563263-9d8c3380-0d1b-11e9-8c42-2d28e39595f9.jpg)

![dsc_1204_kleiner](https://user-images.githubusercontent.com/44591717/50563227-41c1aa80-0d1b-11e9-8cf9-4d8f023ca298.jpg)

![sonoff_th16](https://user-images.githubusercontent.com/44591717/50563144-acbeb180-0d1a-11e9-83e8-28f99ff58026.jpg)

**Comment by wongnam** [comment]
Chose module DS18x20 (04).
Should use the latest FW for stable and more functionality. 

Happy New Year!!!

**Comment by 1Topf** [comment]
Happy new year. :-)
Update done without success.

With sensor DS18x20 (04):

![sonoff_th16_3](https://user-images.githubusercontent.com/44591717/50573019-0d59f700-0dcc-11e9-8c1f-43aba65b1036.jpg)

With sensor AM2301 (02):

![sonoff_th16_4](https://user-images.githubusercontent.com/44591717/50573021-177bf580-0dcc-11e9-87e7-d193dd96e241.jpg)

my_user_config.h:

![sonoff_th16_5](https://user-images.githubusercontent.com/44591717/50573023-206cc700-0dcc-11e9-8e22-e339c73d5c95.jpg)


Perhaps sensor defective?

**Comment by Jason2866** [comment]
Plug isnt correct in socket!
Try it with a little more force

**Comment by wongnam** [comment]
a TH10/16 that had this problem that the jack was very loose, need force press the 2.5mm male jack to get better contact.
#2168

**Comment by ascillato2** [comment]
Hi,

Please, try the solution proposed and report back if it is working for you. Thanks
