### ISSUE TITLE
Issue when build: low free memory, OTA options?

### ISSUE THREAD

**Issue by puppetmaster886** [arendst/Sonoff-Tasmota#4776]
Hi, I make a mistake when building the firmware and now I found that all my devices had very low remaining memory, and I need to update it by ota because the devices are **inside the wall**.

The devices have the 6.2.1, this memory:
Flash Chip Id	1327198
Flash Size	1024kB
Program Flash Size	1024kB
Program Size	447kB
**Free Program Space	44kB
Free Memory	15kB**

I am a developer with relative experience on IOT, do you think there is any possibility that I could modify the minimal version (or any other code out there) to enable ota functionality on the small free memory that my devices have?

**Comment by andrethomas** [comment]
Try command
`reset 5`
It will erase all your settings and the unused flash portion but will keep your wifi settings.

After complete, connect again and see if space has free'd up.

**Comment by arendst** [comment]
Your initial memory model is wrong. You did not use 1M0 linker but probably 512M0 as your total program memory is only about 512k.

Solution: reflash via serial using the correct memory model (linker 1M0)

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
