### ISSUE TITLE
pacefair power calculation error

### ISSUE THREAD

**Issue by lisergio** [arendst/Sonoff-Tasmota#4782]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

In this article,
https://github.com/arendst/Sonoff-Tasmota/issues/3694
 we explain how to adapt the Pacefair meter to use it with tasmota, and it works correctly, but when updating it has stopped doing it

in the 6.4.0.1 and newest
the calculation of the power consumed is wrong ...

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x] _Searched the problem in issues and in the wiki_
- [x] _Hardware used_ : 
- [x] _Development/Compiler/Upload tools used_ :
- [ ] _If a pre-compiled release or development binary was used, which one?_ :
- [ ] _You have tried latest release or development binaries?_ :
- [ ] _Provide the output of command_``status 0`` :
```
STATUS 0 OUTPUT HERE - DO NOT DELETE THE MARKERS ABOVE AND BELOW THIS LINE
```

**To Reproduce**
update at 6.4.0.1 version or newest

**Expected behavior**
power meter error 

**Screenshots**
<img width="406" alt="captura de pantalla 2019-01-01 a las 20 33 12" src="https://user-images.githubusercontent.com/289037/50575760-7fe6c900-0e04-11e9-8959-05b62fd0a0a9.png">

![img_1857](https://user-images.githubusercontent.com/289037/50575744-4ada7680-0e04-11e9-93a1-3a2b099778b1.JPG)

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Duplicate
See https://github.com/arendst/Sonoff-Tasmota/issues/4662
