### ISSUE TITLE
Pin Configuration for Generic Module In Code Behind

### ISSUE THREAD

**Issue by manikdutta** [arendst/Sonoff-Tasmota#4784]
Hi sir,
I want pin configuration for the generic module (NodeMcuESP8266) in code behind i.e., in the Tasmota firmware not from the browser. If someone guides me on how to achieve this from code will be very helpful. The pin configuration is shown in the picture below(Using Tasmota v6.1.1).
![genericmodulepin](https://user-images.githubusercontent.com/17022949/50584268-93da0b80-0e94-11e9-84cb-6671288ec198.png)

**Comment by arendst** [comment]
Learn to use commands ``gpio`` and ``gpios`` to be used by serial, http, webconsole and MQTT. See wiki > commands.

**Comment by manikdutta** [comment]
Through commands, the goal will be achieved but I want this through the code

**Comment by arendst** [comment]
Find function GpioInit and feed your userconfig file defines.

**Comment by ascillato2** [comment]
@manikdutta 

Hi, 

Sorry, but It is not supported "by default" so you need to modify the code to achieve what you want. Search for the function gpioinit in Tasmota code. Thanks.
