### ISSUE TITLE
Bluetooth Beacon

### ISSUE THREAD

**Issue by PapaSpik3** [arendst/Sonoff-Tasmota#4790]
Hey all,
thanks for this project!

Is it possible to receive BT beacons with Tasmota? I didn't find a solution.
Would be nice to have an option if a BT beacon will be received to send MQTT msg or turn on the sonoff.

I want to use it e. g. as "coming home feature" to turn on the light of my garage.

Maybe [this](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/ble_ibeacon) could help?

Thanks for all and best regards!

**Comment by ascillato** [comment]
The esp8266 don't have BT. Only wifi.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
