### ISSUE TITLE
print out configuration

### ISSUE THREAD

**Issue by egs2003** [arendst/Sonoff-Tasmota#4799]
I want a command to see all configuration made

**Comment by ascillato** [comment]
Hi,

Duplicated issue. 

There is already a an option to download all the config to a file and a script to decode it. 

Please, search in issues for more information. Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by curzon01** [comment]
see [decode-config](https://github.com/arendst/Sonoff-Tasmota/blob/development/tools/decode-config.md) - it is not neccessary to previously save a config file, the tool is also able to decode the config directly from the device.

**Comment by egs2003** [comment]
Danke, das hat mir geholfen!
