### ISSUE TITLE
Sonoff POW

### ISSUE THREAD

**Issue by agsochi** [arendst/Sonoff-Tasmota#480]
Hi. @arendst  thank you for great firmware.
I use Sonoff POW to detect my washing machine on/off.
After washing cycle it go to standby mode and in this mode it consumes very low power.
When washing machine is in standby mode - i look at SonoffPOW main page and i see `Power` changing every 10-20sec from 0w to 3w to 0w to 6w and so on.

Feature request:
`Teleperiod` takes into account only last measurement, and if it was 0 - `Teleperiod` shows 0,
but 20 sec before power was 3w.
Can you please add `TeleperiodAverage` (or something like that) parameter, which count all `Power` measurements for `Teleperiod` period (120s) and shows average value for this period?
Result will looks like  `TeleperiodAverage=1.234W` for  `Teleperiod` period (120s) where measurements was from 0w to 6w.
This helps to detect low power consumers.

**Comment by davidelang** [comment]
it would be better to do this in your home automation software, or extend the 
tele period to cover the timeframe you want info for.

I'm not arendst, but remember that we are tight on space and so every feature 
added needs to be balanced against it's cost. In this case the calculation is 
trivial, but the infrastructure needed to support it (command handling, config 
space, etc) are as expensive as any other option.

**Comment by agsochi** [comment]
But extending `Teleperiod` not help in this case because of `Teleperiod` takes into account only last measurement. And if it (measurement)  was 0-3-0-6-0-0-0-0-3-0-0 - `Teleperiod` shows always `0`

**Comment by mihalski** [comment]
To do this in home automation software you would pretty much have to set tele period to 1 which is impractical. This does indeed look like something that would need to happen on the device.

**Comment by agsochi** [comment]
> EDIT: Perhaps alternatively you could compare the energy used between the last update and the current one? I would expect that to be cumulative.

Thanks @mihalski, don't think about that.

**Comment by davidelang** [comment]
Are you sure? I would expect the 'last measurement' to cover the entire last 
teleperiod.

> But extending `Teleperiod` not help in this case because of `Teleperiod` takes into account only last measurement. And if it (measurement)  was 0-3-0-6-0-0-0-0-3-0-0 - `Teleperiod` shows always `0`

**Comment by mihalski** [comment]
That's what I though too.. But I'm not certain.. Lots of 0's here too.. Maybe he'd be better off monitoring power? Perhaps Watt hours just tend to very low numbers (below 1) for short periods?

Here's my fridges an example:
![screen shot 2017-05-26 08 25 31 pm](https://cloud.githubusercontent.com/assets/3755059/26491130/a1f2aa12-4251-11e7-9cc2-0934cf0170f2.png)
![screen shot 2017-05-26 08 26 11 pm](https://cloud.githubusercontent.com/assets/3755059/26491133/a5eb2e8c-4251-11e7-9e83-6ddb63ab6272.png)

**Comment by agsochi** [comment]
Here is my Washing machine in standby:
![default](https://cloud.githubusercontent.com/assets/2944079/26491738/7781190e-4219-11e7-8395-83d967b2986c.png)

**Comment by davidelang** [comment]
I assume this is with a 1m log interval, what is you set it longer?

**Comment by agsochi** [comment]
2 minutes

**Comment by mihalski** [comment]
![screen shot 2017-05-26 10 15 59 pm](https://cloud.githubusercontent.com/assets/3755059/26494184/f6bfe8c0-4260-11e7-963a-ebcc074de29e.png)

**Comment by davidelang** [comment]
if you have more than 2 points in a 10 min period, it is not set to a 5 min reporting interval. try power cycling the device to make sure it is using your new settings

**Comment by agsochi** [comment]
I zoom my graph - yes it shows 2min and 20sec periods. But 5min looks same.

**Comment by davidelang** [comment]
If the device is only reporting one value every 5 min, then any graph that shows 
details every minute or every two minutes cannot possibly be correct.

So if you are getting per-minute (or per two minute) data, then you have the 
tele period set for 60 or 120 seconds, not 300 seconds.

The POW only computes the power usage when it's sending a tele/ report, it 
doesn't generate it every X seconds and send the last one, it keeps a running 
total of power used and computes the number it reports when it generates a tele/ 
report.

**Comment by agsochi** [comment]
Maybe you wrong, POW shows usage at main page with period every 2-3 sec.

**Comment by goprojojo** [comment]
I'm looking for the same solution to receive a notification when the washing cycle is ready. Anyone success on this? If yes how should the config look like?

**Comment by agsochi** [comment]
I got result - look at `Total` graph. I took `Total` value with `Teleperiod=60s` and compare it with previous value. Measurement is very accurate with resolution below 1W (compare with `Power W` from teleperiod stats). Here is grafana setting for `Total` measurement.
![5](https://cloud.githubusercontent.com/assets/2944079/26757047/08f974da-48b9-11e7-8912-dc19de9f399b.png)
