### ISSUE TITLE
When selecting DS18B20 in new basic, the temp is missing

### ISSUE THREAD

**Issue by seritos** [arendst/Sonoff-Tasmota#4805]
I have the new board of Sonoff basic. I have solder a DS18B20, however, when selecting it in GPIO2, the temperature is not displayed in the main page: 

<img width="587" alt="image" src="https://user-images.githubusercontent.com/45351579/50657349-81e09180-0f96-11e9-972d-7738ea1d51b2.png">

<img width="493" alt="image" src="https://user-images.githubusercontent.com/45351579/50657361-8e64ea00-0f96-11e9-9aca-c71769956a31.png">

Even is the sensor wouldn't be soldered, the temperature line should appear. isn't it?

Thanx

**Comment by andrethomas** [comment]
> Even is the sensor wouldn't be soldered, the temperature line should appear. isn't it?

No

**Comment by seritos** [comment]
I have removed the Ds18b20, added a DHT11 and it works fine. 

The temperature line does appear even though the sensor is not connected. Try it.

**Comment by andrethomas** [comment]
> The temperature line does appear even though the sensor is not connected. Try it.

Once detected yes it will. But if not connected on power-up it will not.

**Comment by Neil-M0NFI** [comment]
It works for me on GPIO2 with the new version of Sonoff Basic. Have you connected the 4K7 resistor between 3.3v and GPIO2 that the DS18B20 needs?

**Comment by seritos** [comment]
No I haven't! 

Didn't know this was needed! Is this only with the Ds18b20?

**Comment by seritos** [comment]
It works! Thanx much for your supoort! 

Just a couple of questions...

Is it posible to read the temperature in Homekit with 0,1 degrees definition instead of 0,5? 

Is there any possibility with tasmota to create, trough an app or similar, a graph with the historial temperature?  

Thanx!

**Comment by andrethomas** [comment]
> Is it posible to read the temperature in Homekit with 0,1 degrees definition instead of 0,5?

If you use the correct sensor it can provide finer than 0.5deg resolution - LM75AD, for example, can provide up to 0.125 deg C resolution - Some users use the BMP/BME 180,280 and 680 sensors which are more reliable and consistent in that order.

> Is there any possibility with tasmota to create, trough an app or similar, a graph with the historical temperature?

All data can be transmitted via mqtt to a home automation system which can do this recording for you. There are many options available... OpenHab, HomeAssistant, Node-red etc

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
