### ISSUE TITLE
MQTT Serial log level?

### ISSUE THREAD

**Issue by CazMan** [arendst/Sonoff-Tasmota#4808]
**Have you look for this feature in other issues and in the wiki?**
Yes, SerialSend/SerialReceived is implemented - but it seems to disable commands via serial (Hardware serial) - all responses from my connected device is published to MQTT  so commands are not executed.. 

**Describe the solution you'd like**
I would like a serial logging option that sends the MQTT topic and payload received for the device (or possibly all MQTT topics|payloads) to the serial port - delimited with maybe a | (No other info). All commands sent via serial must still execute...

Although I got the SerialSend and SerialReceived to function properly - I would like to be able to still issue commands via serial. (Allowing my connected device to interpret the MQTT topic|payload, and issue commands to publish to a MQTT topic, or send any other serial command as needed...)

**Comment by ascillato2** [comment]
Hi

Mqtt is for commands, not for logging. You have 3 log options available SERIAL, SYSLOG, WEBLOG

So, the best for you would be to use the serial as standard to issue commands and use a syslog for logging outside Tasmota. 

Thanks
