### ISSUE TITLE
Color control via Alexa (HUE Emu) for Magic Home Controller

### ISSUE THREAD

**Issue by ihavenonick** [arendst/Sonoff-Tasmota#4809]
Is this control possible, or is the HUE emulation limited to brightness? Is not it feasible, or not wanted?

**Comment by altelch** [comment]
Hi,

the echo/alexa built in routines only support on/off/brightness.

Greetings,

       Altelch.

Am 04.01.2019 um 10:19 schrieb ihavenonick:

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
