### ISSUE TITLE
Hard Thermostat

### ISSUE THREAD

**Issue by off14** [arendst/Sonoff-Tasmota#481]
Is it possible to include functionality of HARD thermostat - where no MQTT(or similar) server is available or there are no commands received.
Of course this mode will require temp sensor connected.
You need to include logic to support COOL or HEAT modes,  Hystersis setup  (0.1 - 5) together with TargetTemperature

This will make sonoff working as a thermostat with web interface, even without any server. Very useful when sonoff is installed on remote location and there are big chances that internet is not stable there

WDYT?

**Comment by citrusfizz** [comment]
i like this idea.   i recently built a thermostat with a raspberry pi, some relays and Node-Red and mqtt all built in.   Trusting the PI for 24/7 operation is a bit sketchy. and if it reboots it takes a while to boot up and get all its gears turning.   Working well so far,  if you have a PI i can share my node red flows with you.

**Comment by off14** [comment]
Thanks, i have mine also in node-red and in openhab rules
the main idea is to have **independent** thermostat, which not requires any server (mqtt or whatever)

**Comment by CommodoreWhite** [comment]
Why not for any sensor that returns an analogue value (that is, not binary). So, for instance, a set point for humidity to control the bathroom extractor fan, a light sensor could turn security lights on and off, a proximity detector could control stair well lights. Hmm, the last one is a bad example but you get the picture. 

The underlying logic is generic, if a sensor value is exceeds some thresholds, switch a relay and or send a message.

The implementation might not be as responsive as you like because, if memory serves, sensors are polled rather than continuously monitored and why having a proximity sensor manage stair lights could have undesirable consequences.

So it's a +1 from me.

Peter

**Comment by CommodoreWhite** [comment]
Oh! I forgot. It would be nice if the feature could be enabled or disabled depending on the presence or absence of an Mqtt connection. So, if the Mqtt service dies, lights still turn off and on. If Mqtt is working the control reverts to a higher authority.

**Comment by AlexTransit** [comment]
I made a simple thermostat at my place. (On fast)
He has no settings

I wanted to make PID and settings.
Do not do it. :)

sonoff.ino
void every_second()
{
  char log[LOGSZ], stopic[TOPSZ], svalue[MESSZ], stime[21];
  float ctemp;

#ifdef TEMPERATURE_CONTROL_DS18x20
if (ds18x20_read(0, TEMP_CONVERSION, ctemp, true)) 
{
  if ((ctemp == 85.0) || (ctemp >= sysCfg.temp_target)){
      if (power != 0) {
      do_cmnd_power(1, 0);}
      //setRelay(0);
  } else {
      if (power != 1) {do_cmnd_power(1, 1);}
      //setRelay(1);
  }
} else { //sensor error. disable power
  if (power != 0) {do_cmnd_power(1, 0);}
}
#endif // TEMPERATURE_CONTROL_DS18x20

**Comment by davidelang** [comment]
This question has come up several times.

It is currently not supported, although it would be possible to add it.

One problem is "what sensor should it look at" given that multiple sensors can 
be attached at the same time.

Another is how many such configs should it allow at once? (on a dual, should it 
be able to control both a heater and an AC with different settings?

There is similar functionality in the POW to respond locally to power 
consumption, so it's not out of the question. but someone would have to think 
through the details and code it in a way that does not require a lot of extra 
flash or ram.

**Comment by AlexTransit** [comment]
All right.
I did not have a source on my boiler.
I specifically use the library 18x20
And the temperature adjustment is done taking into account the sensor address.
Also incorrect data can come from the sensor. Then the temperature will be 85.0 degrees.

If you make a thermostat, then there may be several controls.
Just a relay or SSR
Or two relays, add a cold, and add hot.
Still the sensor 18 is quite slow. (Sample 700ms)

**Comment by off14** [comment]
i think it should be independent from type of sensor you are using. if you have **any sensor supplying temperature** then the "thermostat" option should be available, with dropdown list for sensors found.

of course, could be many variations, like 2 relays, pow-models etc - but i guess it will make the development complicated and even not compatible with sonoff chip (memory size)

my suggestion is to go with simplest possible setup
MODE: HEAT/COOL
HYSTERSIS: 0.1-5.0
MQTT_MSG: thermo { "mode": <mode>, "hyst": <hystersis>, "currentstate" : <state>, "enabled" : <boolean> };

**Comment by pprotschka** [comment]
has anybody been able to implement this? Tasmota is great but Wifi routers and Networks fail...and i dont want my walk in freezer to be left ON forever.

i know that easyesp has "rules" that make this possible but unfortunately easyesp is a lot more tricky to  configure.

**Comment by davidelang** [comment]
This has been a repeated request.

**Comment by mo8Zomo0** [comment]
+1

I was wondering about the same functionality and before opening a new request I searched and found this one.

It would really be a handy feature to control heating, cooling, de-/humidifiers, or use input from other sensors like light, moisture, ...

**Comment by nambuco** [comment]
+1 that would love this functionality.

To make implementation simple, should focus on Sonoff TH10/TH16 hardware (one sensor / one relay).

**Comment by apathyuk** [comment]
Sounds interesting. Has anyone have a solution for controlling radiator TVRs?

**Comment by PeggyFree** [comment]
It would be not far from the existing power threshold triggering, no?

**Comment by vstonkus** [comment]
I building electric floors heating in bathroom. There is a simple 220v wire (https://www.infrafloor.com/images/HomeBoxes/big/InfraFloorMat-FloorHeating.jpg). I think that Sonoff TH10/16 with water proof temp sensor inside floor concrete below tiles would be a solution here.
I would like to get it connected to home assistant, and Homekit. Would be great configure it to raise tiles temperature in the morning and in the evening for a little.
In bathroom there is other unit to control - coil heater, but it should be on after shower, so it can be connected on Sonoff TH with temperature and humidity sensor. Home assistant for example could notice increased humidity and turn on coil heater or mirror heating for example. Mirror does not need hard thermostat, but coil heater and mostly floors heating does.

I agree with @nambuco. Would be great to have this feature.

**Comment by nambuco** [comment]
I will try to implement a temp control for Sonoff TH, in case it works I will share it here. I may need help from someone who knows the sw structure. I will use AlexTransit code as a starting point, add PID and setpoint adjustment using MQTT (that's the complex part...).  Let's see...

**Comment by AlexTransit** [comment]
I connected Sonof BASIC to the thermopot. as a relay I use SSR.
there is a small problem.
if you turn on the web. and disable the WIFI point then
the procedure "every_second" does not work until you go to the web page.
the firmware version is very old. (3.2.13)
I do not have enough programming knowledge and experience to implement a normal PID controller
but I'll find out. :) I do not know when.
still there is a problem with the OTA update when the size is more than 50%
this set back my further elaboration of PID.
the size of the firmware is great. and update the cable is not possible.

**Comment by spacefolder** [comment]
Hi guys! Any news on this request? I have my sonoffs running my own (buggy, sloppy and slow) firmware, but having a TASMOTA Thermostat would be great, reaaly great! 

+1

**Comment by nambuco** [comment]
Hello Guys, I finally got my USB/TTL converter and flashed my first Sonoff TH for testing. I forked this repository and will start coding a "hard thermostat".

Every tip / information will be welcome.

I will implement an on-off controller because my application (refrigerator) does not require a PID control. 

I noticed that temp measures are done on every telemetry cycle defined by TelePeriod parameter. My idea is to run the thermostat function at same frequency.

I want to use some of the free setting bytes for a **SetPointTemp**, **Histeresys** and **ThermostatMode**  - On (or Auto) and Off .

I will post here the evolution of this change.

Nambuco

**Comment by davidelang** [comment]
look at how the power limit functions are done, they are probably a good model

**Comment by mo8Zomo0** [comment]
It would be good if the TH1x temperature sensors would be supported and even cooler of also a remote temperature sensor could be supported.

@nambuco Btw, regards flashing, check out: https://github.com/mirko/SonOTA

**Comment by nambuco** [comment]
@davidelang, thanks for the tip, it helped me to implement the first beta version available on https://github.com/nambuco/Sonoff-Tasmota for testing.

 @mo8Zomo0, I am using the OTA in the WebServer interface, works fine here. I implemented for DS18B20, I do not have the TH1x sensor to test, but should be easy to adapt (replace Ds18b20ReadTemperature() by ShtReadTempHum() in the thermostat.ino file).

**Comment by sgttrs** [comment]
@nambuco Can you make in the firmware a simple logic for switching the relay?
Example:
if Temperature<30 - Relay OFF
if Temperature>30 - Relay ON

**Comment by nambuco** [comment]
Hi @sgttrs ,

If you change the constant on thermostat.ino file

#define OFF_DELAY 90  // minimal off time in seconds
#define HYSTERESIS 2  // Hysteresys in 0.1 Degrees

both to zero, you have the effect you want. I just warn you that turning off and on before 60 seconds can damage a compressor (if this is your application).

Important point, set tele_period to 10 to allow a fast response

**Comment by sgttrs** [comment]
@nambuco Thanks for the answer. I want to use Sonoff in the heating system to start the circulation pump. Is it suitable for this application?

**Comment by nambuco** [comment]
Hi @sgttrs , if the logic is like you describe (temp above setpoint turns on the relay) it will work as it is. Please be aware that I did not test in all possible conditions, You have to download and help me test in your setup.

I am planning to add a second mode where the relay will turn on if temp is below setpoint.

**Comment by sgttrs** [comment]
Hi @nambuco, I'm testing the firmware with the settings you suggested. When I activate the thermostat and enter SETPOINT 30, the thermostat turns on the relay at any temperature, even if it is less than 30 ° C. I also noticed that when I connect Sonof to AC, it turns on and off the relay several times. Is there any way to avoid this?

**Comment by nambuco** [comment]
Hi  @sgttrs, the SetPoint is defined in 0,1 steps, this means, to get 30C you have to input 300 in SetPoint.
Concerning the on / off during boot, that odd, I never faced it, but I will test in different conditions.

**Comment by pixidixi88** [comment]
Hi
I would like to use SONOFF TH16 to floor heating control. I have a AM2301 sensors. I need such rules:
If temperature is > wished temp - relay ON
If temperature is < wished temp - relay OFF
It seems like "cooling" because it will close valves when temperature is higher then wished.

Is it possible to put wished temperature via MQTT? I would like to add this as "thermostat device" to my Homebridge.

I am beginner  so please explain me as clear as possible. :)

**Comment by sgttrs** [comment]
Hi @nambuco. I just tried to change the temperature with the `setpoint` command via mqtt and via console. The result of processing the command:
```
15:41:25 CMD: setpoint 500
15:41:25 MQT: stat/sonoff/RESULT = {"SetPoint":300}
```
Rebooting the module does not help.

Hi @pixidixi88. The firmware is still under development. Various errors in work are possible. If you are ready for this, [here](https://github.com/arendst/Sonoff-Tasmota/wiki) is the instruction on how to install the firmware on the module. Also read the posts of **nambuco** in this thread.
I use Home Assistant to control my devices. To set the temperature value through mqtt, send the topic: `cmnd/sonoff/setpoint`. In the content of the topic, set the desired temperature value, multiplied by 10.

**Comment by nambuco** [comment]
Hi @sgttrs, the setpoint is limited to -500 to +499. It is easy to change that and I will put it in a constant next release. Please check if it works for 499.

Hi @pixidixi88, I implemented this feature only for DS18b20 sensors, I have to check how AM2301 is implemented to see if it is easy to add it to thermostat function. If someone has any tip on AM2301 it will be helpful.

**Comment by pixidixi88** [comment]
Hi @sgttrs 
I have installed Tasmota software and I am very glad of use this, but what I really need is thermostat function. I am not afraid about errors because I understand that it is more less "homemade" solution.
Hi @nambuco 
I have tried adjust code from DS18B20 to AM2301 by myself but I failed :( so I really need your help. If you need any data, please let me know.

**Comment by sgttrs** [comment]
Hi @nambuco. Yes. At values up to 499, everything works fine. Thanks.
Is it possible to configure the firmware to work in this mode? Example:
Setpoint 400. Hysteresis 50.
T > 450 - Relay ON
T < 350 - Relay OFF
T 350:450 - Saving the previous state of the relay

**Comment by jtamasi** [comment]
Hi @nambuco
First of all, I'd like to thank you for the work you put into this mod.
I think I'm not alone when I'm saying that AM2301 compatibility is very important because that is the most obvious choice for a thermostat with Sonoff TH. Could you waste some time and try to add it to the supported sensors
Cheers

**Comment by skorc99** [comment]
Hello,

this works for cooling.

How to change for heating?

T<20 relay ON
T>20 relay OFF
ON/OFF delay x seconds

This should keep setpoint temperature.
U

**Comment by Stevehans** [comment]
Any chance of a pull request for this code, would be great to see this in mainstream?

**Comment by Stevehans** [comment]
Would also be good to extend the timer functionality to have on/off/auto (min,max)

**Comment by IceStuff** [comment]
Hello All,

I extended on the Hard Thermostat with webpage controls, heating and cooling modes and supports all temperature sensors.

Check it out and provide feedback would be great.  Humidity control is coming.

https://github.com/IceStuff/Sonoff-Tasmota/releases/tag/v5.12.1

Thanks,
IceStuff

**Comment by Highcooley** [comment]
Hi IceStuff

I did the German translation and gave it a try with a TH10. However, somehow I cannot find the Thermostat webpage controls, no matter what language I flash the module with. Do I have to select another module type (I already tried standard and dual next to TH)? Also with the MQTT request STAUTUS:10, I don't get a temperature in return anymore. 

Cheers,
Andy

**Comment by wasi54** [comment]
Hi IceStuff
I loaded [5.12.1_beta.bin](https://github.com/IceStuff/Sonoff-Tasmota/releases/download/v5.12.1/sonoff-GB-thermostat-5.12.1_beta.bin) to one of my TH10 via sonoff-minimal and OTA. It is working verry well.
Next step was compiling from source with PlattformIO (PlatformIO 3.5.3a9 and all updates are installed). Compiling was successfull without any issues.
Unfortunately the TH10 was not visible on the WiFi any more after OTA upgrade. Button 4 short presses will show the WiFi Manager and i was able to set the SID and password. But no WiFi access after reboot and not pingable. Toggle the Button will toggle the Relais and the LED's. Furthermore the generated firmware.bin is 2k smaller than the beta binarie.
Any idea or help is highly appreciated.
Thanks

**Comment by wasi54** [comment]
@Highcooley
I guess MQTT_HOST set to "" and the library #define MQTT_LIBRARY_TYPE MQTT_PUBSUBCLIENT will cause the webserver to hang ...
The solution for me was:
#define MQTT_LIBRARY_TYPE MQTT_TASMOTAMQTT

**Comment by wasi54** [comment]
Thermstat module setting:
![thermostat-config](https://user-images.githubusercontent.com/6075168/38834090-b2e3cc68-41c7-11e8-9094-394a60e691d6.png)

**Comment by Highcooley** [comment]
@wasi54 got it, setting MQTT_HOST helped and the sonoff didn't hang. My other issue (no thermostat menue) *facepalm*, reflashing removed the sensor setting which switches off this menue. 
Now everything is working splendid. 
@IceStuff the German translation works a treat as well. Do you have your 
My next step is to implement TM1637 (4 digit LED Display) support including two buttons to set the thermostat temperature at GPIO 2 and 4 or 5.

**Comment by IceStuff** [comment]
Sorry about that in my last post.  I mentioned that as soon as Sonoff TH was selected the thermostat settings menu would appear.  I forgot that you also need to have a proper temperature sensor on GPIO 14.

I removed the MQTT_HOST during testing because it was flooding the console with errors not being able to find the default MQTT host and it was causing my debug messages to roll off screen too quickly.  I noticed that the first time I flashed it with the MQTT host blank that it hung but once I rebooted it came back online.  I chalked it up to my mistake.

@Highcooley do you have the German translation you can send to me so I can implement it?

You may have noticed some of the default includes in the config file were disabled in my code.  This was to keep it under 500k so I could upload the changes via the webpage.

I am not sure why the code would be 2k smaller when you compiled it unless there was an update.  My Platform IO is Home 0.9.5·Core 3.5.3a9 with Visual Studio Code Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Are you using VS Code or Atom?

Glad to hear you have this working.  I was thinking to implement the display and rotary encoder via the RS232 programming header since they also have power on the header.

IceStuff

**Comment by AlexTransit** [comment]
good solution (use pid)
https://github.com/arendst/Sonoff-Tasmota/issues/2425

**Comment by wasi54** [comment]
@IceStuff Atom 1.25.1x64 on Linux with PlatformIO 3.5.3a9 is currently the newest version available.

**Comment by IceStuff** [comment]
@Highcooley thanks for the translation.  I merged it with my repository.  I also created a pull request back to the main code, hoping they will implement along with their main code.

@AlexTransit I was debating using PID.  I figured it would be too much on and off when using relay control.  If we were using PWM or analog output then it would definitely make sense.

**Comment by AlexTransit** [comment]
@IceStuff  I figured it would be too much on and off when using relay control. 
all is correct. if the PID time is short, frequent operation will quickly break relay.
can make SSR in GIPO settings?

there is a defect in the current branch. because of it I have not yet checked the firmware on my boiler.
I'll try to fix it.
If there is no data from the sensor, or data with an error, it is necessary to disconnect the load.
I assembled the test version.
At low temperature, the load is switched on. I physically disconnect the sensor and everything continues to work. It is not safe.

**Comment by arendst** [comment]
My two cents:

How about a rule like:
```
{"Rule":"ON","Once":"ON","Rules":"on ds18b20#temperature>24 do power off endon on ds18b20#temperature<23 do power on endon"}
```
With variations in warming/cooling or other sensor type. Once the rule is configured the unit will perform like a thermostat standalone.

**Comment by aenertia** [comment]
Without going the ssr route why not set a timeout since last change of state. Something like a tunable and if the state changed X seconds ago then don't trigger the relay again until the timeout. This combined with a range +/- sensor threshold would solve frequent flipping of the relay problem.

**Comment by dweston** [comment]
@IceStuff I've been using your v5.120k binary for the past 4-5 days and the whole thing has run impeccably. For a non-programmer the UI was straight forward and very effective. I'm running it on Sonoff TH16 controlling a fan in a cavity behind a wine fridge. Wasn't sure what parameters best suited the situation. Didn't even know what temp settings to work with. Set up a nodered UI chart and then kept tweaking your settings on the device UI directly - and within 48 hrs adjusting temp & hysteresis had the whole situation controlled as well as I believe will ever be. Fantastic.

**Comment by IceStuff** [comment]
@AlexTransit I fixed the output staying on if temperature sensor fails.  Please check out the latest release and provide feedback: https://github.com/IceStuff/Sonoff-Tasmota/releases/tag/v5.12.2
It will have to wait until the sensor read times out then will shut off relay.  It will also go through the regular cycle to make sure the minimum off time is met.

@dweston I really appreciate your comments.  I am glad that you found the hard thermostat helpful.  I recommend upgrading to the latest release to implement the fix in case the temperature sensor fails.
https://github.com/IceStuff/Sonoff-Tasmota/releases/tag/v5.12.2

IceStuff

**Comment by IceStuff** [comment]
@arendst Sorry I missed your comment above.  Can you give me a link that would explain the rule you posted?  Why would you include the sensor type?  The current firmware will work with any of the sensors.

Thanks,
IceStuff

**Comment by arendst** [comment]
See Wiki - Rules.

The rule allows any sensor, current and future as you just have to enter your local sensor name as seen in the JSON teleperiod message.

The main advantage of a rule is that here is no coding needed from my side; it's all in the hands of the user allowing me to continue to the next level...

**Comment by spacefolder** [comment]
Hi!

I have a Sonoff TH16. Was working flawlessly with tasmota 5.10.0.
Decided to try the ThermoWeb. Flashed it ok OTA.

Now I can't see the sonoff in my network.
Serial Monitor shows that the device boots up just fine, 
but it's manually self assigning the IP to 192.168.1.1 (which is my routers IP).

If I unplug my router, I can access the web interface (I have a dedicated AP for home automation), but it's asking to login in, with user & pass, which I don't know.

![image](https://user-images.githubusercontent.com/27922111/40286762-78c516f4-5c7f-11e8-9799-7d0c4331d431.png)

![image](https://user-images.githubusercontent.com/27922111/40286769-8c30bf7c-5c7f-11e8-8c59-4e438906405e.png)

Any ideas?
Cheers!

**Comment by dweston** [comment]
@IceStuff I have been running with v5.12.2 now for 20 days and it has worked flawlessly.

**Comment by ascillato** [comment]
Hi,

In the wiki, now is available an example of a Simple Thermostat using RULE feature (https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#7-simple-thermostat-example)

Please, check it to see if that helps you.

**Comment by spacefolder** [comment]
@dweston , did you go from "regular" tasmota  to ThermoWeb, uploading **sonoff-GB-thermostat-5.12.2_beta.bin** OTA through the web interface, or did you flash the .bin using the serial port?

**Comment by dweston** [comment]
@spacefolder I downloaded the .bin file off Github and flashed it OTA within my local network.

**Comment by dweston** [comment]
@ascillato I would not say that is simple, but I can certainly see the powerful flexibility built into the 'rule' system. When I can set aside the time I will give it a go using this example. In the meantime for my present purposes v5.12.2 is working perfectly well for me and is considerably easier to work with.

**Comment by spacefolder** [comment]
@dweston @IceStuff 

I gave it another shot. Reinstalled Tasmota. Everything working fine. My DHCP assigns the IP correctly, and the Sonoff reads temp and humidity values correctly (itead Si7021 sensor).

Tried upgrading via web interface (downloaded a "fresh" thermoweb" .bin)

![image](https://user-images.githubusercontent.com/27922111/40336310-46d9697c-5d3f-11e8-986d-f5bab828bb03.png)

Still the same issues. It self asigns 192.168.1.1 (clashing with my routers' IP)
If I unplug my router, I can ping and connect to the Sonoff, but it keeps asking me user & pass.
(admin and "blank" dont work)

Any clues?
Thanks. Cheers!

**Comment by dweston** [comment]
@spacefolder I'd suggest you do a complete memory erase via serial [https://github.com/arendst/Sonoff-Tasmota/wiki/Esptool#optional-erase-firmware](url) and then reinstall [https://github.com/arendst/Sonoff-Tasmota/wiki/Esptool#upload-firmware](url) using Esptool. Remember the OTA does not overwrite some persistent areas of Flash so if a bug is in the persistent part it will keep on being an issue.

**Comment by pbutterworth** [comment]
Hi folks,
There's also another open source project (hasn't been touched in a while) that implements a thermostat on a ESP8266 board (not sonoff). It's a bit cobbled together, but does have some really nice functionality.
https://guide.openenergymonitor.org/integrations/mqtt-relay/
https://github.com/openenergymonitor/ESP8266_Relay_Board/tree/master/1ch_relay

What is particularly interesting is the local scheduler and web interface feature, making it possible to manage and use the thermostat completely independently.

![image](https://user-images.githubusercontent.com/3683210/40693465-9cf297e8-640b-11e8-9248-12d6bd36f41f.png)

The scheduler comes from here:
https://github.com/emoncms/development/tree/master/experimental/control/open_thermostat_scheduler

Would be super-nice to get this in to this project for TH modules.

**Comment by dweston** [comment]
@IceStuff I have just encountered my first hic-up with the v5.12.2 firmware.

I had reason to update my MqttHost address in all my Sonoffs, only one of which at the moment is running v5.12.2. All the rest are running v5.13.0.The pre-existing MqttHost name was an IP address.

After issuing a group topic command updating the MqttHost name, which in my case is now 'vistacontrol.local', all the devices changed over flawlessly except for the TH16 running v5.12.2. This refused to connect giving the following error:
`00:00:00 Project wineFan Wine Fan (Topic wineFan, Fallback DVES_A010DE, GroupTopic sonoffs) Version 5.12.2-2_4_1`
`00:00:00 WIF: Connecting to AP1 xxxxxx in mode 11N as winefan...`
`00:00:06 WIF: Connected`
`00:00:06 DNS: Initialized`
`00:00:06 HTP: Web server active on winefan.local with IP address xx.xx.xx.xx`
`00:00:07 MQT: Attempting connection...`
`16:28:29 MQT: Connect failed to vistacontrol.local:1883, rc -2. Retry in 10 sec`
`16:28:33 RSL: stat/wineFan/RESULT = {"POWER":"OFF"}`
`16:28:33 RSL: stat/wineFan/POWER = OFF`

Changing the MqttHost in this device back into an IP address format for the new broker and the device connects no problem:
`00:00:00 Project wineFan Wine Fan (Topic wineFan, Fallback DVES_A010DE, GroupTopic sonoffs) Version 5.12.2-2_4_1`
`00:00:00 WIF: Connecting to AP1 xxxxxxx in mode 11N as winefan...`
`00:00:05 WIF: Connected`
`00:00:05 DNS: Initialized`
`00:00:05 HTP: Web server active on winefan.local with IP address xx.xx.xx.xx`
`00:00:06 MQT: Attempting connection...`
`00:00:06 MQT: Connected`
`00:00:06 MQT: tele/wineFan/LWT = Online (retained)`
`00:00:06 MQT: cmnd/wineFan/POWER = `
`00:00:06 MQT: tele/wineFan/INFO1 = {"Module":"Sonoff TH","Version":"5.12.2","FallbackTopic":"DVES_A010DE","GroupTopic":"sonoffs"}`
`00:00:06 MQT: tele/wineFan/INFO2 = {"WebServerMode":"Admin","Hostname":"winefan","IPAddress":"xx.xx.xx.xx"}`
`00:00:06 MQT: tele/wineFan/INFO3 = {"RestartReason":"Software/System restart"}`
`00:00:07 MQT: stat/wineFan/RESULT = {"POWER":"OFF"}`
`00:00:07 MQT: stat/wineFan/POWER = OFF`
`16:33:50 MQT: stat/wineFan/RESULT = {"POWER":"OFF"}`
`16:33:50 MQT: stat/wineFan/POWER = OFF`

I presume this is a quirk resulting from v5.12.2 being a branch off the main repository.

**Comment by BladeRunner68** [comment]
is @IceStuff  still around?  I have just tried this excellent addition to control my freezer.  However the web UI does not accept float numbers such as if I want to set the setpoint to -2.5C - same in the hysteresis input too.  Is there a workaround?

Also this firmware works with sonoff basic with ds18b20 added to gpio14 and TH model set.

**Comment by ascillato** [comment]
Referencing other similiar issues to keep the Thermostat thread here.
https://github.com/arendst/Sonoff-Tasmota/pull/2486 https://github.com/arendst/Sonoff-Tasmota/issues/2425 https://github.com/arendst/Sonoff-Tasmota/issues/818

**Comment by IceStuff** [comment]
Hi @BladeRunner68, yes I am still here.  I haven't received notification for any of these updates and just checked in to see how think are going.

Thanks,
Paul

**Comment by dweston** [comment]
@IceStuff are you intending to develop this branch further? I'm still using v5.12.2 which is quite stable, though the issue with MqttHost name referred to above, is still unresolved. I note the request above for float numbers, and the humidity ToDo mentioned at the bottom of your Wiki [https://github.com/IceStuff/Sonoff-Tasmota/wiki](url) would be very useful to me.

**Comment by ascillato2** [comment]
Hi,

Closing this issue as it has been without activity for a while and it is not going to be developed soon for Tasmota. Anyway, it has been added the label **Feature Request (hold over)** for future reference because here were exposed very interesting ideas. May be this feature can be added as a new extra driver in the near future. Thanks everyone for sharing their ideas. 

As a workaround for this feature there is in the wiki, an example of a Thermostat using RULES feature (https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#7-simple-thermostat-example)

Please, check it to see if that helps you.

**Comment by ascillato** [comment]
Added #8212

**Comment by dexterbot80** [comment]
> Hi,
> 
> In the wiki, now is available an example of a Simple Thermostat using RULE feature (https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#7-simple-thermostat-example)
> 
> Please, check it to see if that helps you.

Hello, Can you send the correct link here? Thank you
