### ISSUE TITLE
documentation needed for IRremote

### ISSUE THREAD

**Issue by aihysp** [arendst/Sonoff-Tasmota#4812]
there are no Docs related on how to send IR MQTT request 
if someone can please add a way to use this

Wiki refers us to [this](https://github.com/altelch/SonoffIR)
its great on how to build and connect to the sonoff , but i am not getting how to use it

**Comment by curzon01** [comment]
Use [IRSend command](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#irremote) as described.

How to use commands in general see [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by aihysp** [comment]
Many thanks, I will try!
