### ISSUE TITLE
teleperiod 300, to many mqtt messages

### ISSUE THREAD

**Issue by 1igeza** [arendst/Sonoff-Tasmota#4813]
HI, 
I have got a problem with my one sonoff pow. Teleperiod is set to 300, and in log i have:
`12:34:01 LOG: SerialLog 2, WebLog 2, SysLog 0, LogHost , LogPort 514, TelePeriod 300
12:34:16 MQT: rafal_pow/tele/SENSOR = {"Time":"2019-01-04T12:34:16","ENERGY":{"TotalStartTime":"2018-11-26T06:36:25","Total":0.153,"Yesterday":0.298,"Today":0.153,"Power":7,"ApparentPower":38,"ReactivePower":38,"Factor":0.18,"Voltage":247,"Current":0.155}}
12:34:20 MQT: rafal_pow/tele/SENSOR = {"Time":"2019-01-04T12:34:20","ENERGY":{"TotalStartTime":"2018-11-26T06:36:25","Total":0.153,"Yesterday":0.298,"Today":0.153,"Power":3,"ApparentPower":33,"ReactivePower":33,"Factor":0.09,"Voltage":245,"Current":0.135}}
12:36:49 MQT: rafal_pow/tele/SENSOR = {"Time":"2019-01-04T12:36:49","ENERGY":{"TotalStartTime":"2018-11-26T06:36:25","Total":0.153,"Yesterday":0.298,"Today":0.153,"Power":7,"ApparentPower":37,"ReactivePower":36,"Factor":0.18,"Voltage":247,"Current":0.149}}
12:36:54 MQT: rafal_pow/tele/SENSOR = {"Time":"2019-01-04T12:36:54","ENERGY":{"TotalStartTime":"2018-11-26T06:36:25","Total":0.153,"Yesterday":0.298,"Today":0.153,"Power":2,"ApparentPower":50,"ReactivePower":50,"Factor":0.04,"Voltage":247,"Current":0.203}}
12:36:56 MQT: rafal_pow/tele/SENSOR = {"Time":"2019-01-04T12:36:56","ENERGY":{"TotalStartTime":"2018-11-26T06:36:25","Total":0.153,"Yesterday":0.298,"Today":0.153,"Power":7,"ApparentPower":36,"ReactivePower":35,"Factor":0.19,"Voltage":247,"Current":0.144}}
12:37:02 MQT: rafal_pow/tele/SENSOR = {"Time":"2019-01-04T12:37:02","ENERGY":{"TotalStartTime":"2018-11-26T06:36:25","Total":0.153,"Yesterday":0.298,"Today":0.153,"Power":2,"ApparentPower":32,"ReactivePower":32,"Factor":0.07,"Voltage":244,"Current":0.132}}
12:37:20 MQT: rafal_pow/tele/SENSOR = {"Time":"2019-01-04T12:37:20","ENERGY":{"TotalStartTime":"2018-11-26T06:36:25","Total":0.153,"Yesterday":0.298,"Today":0.153,"Power":6,"ApparentPower":33,"ReactivePower":32,"Factor":0.18,"Voltage":247,"Current":0.132}}`

Also setopion19 is set to 0, but home assistant discover all date from this sonoff pow. I have 4 pcs of this, and all have tasmota 6.4.1.3, but problem is with only one, and I can find what could be a problem.

`12:54:54 CMD: status 0
12:54:54 MQT: rafal_pow/stat/STATUS = {"Status":{"Module":6,"FriendlyName":["Rybki"],"Topic":"rafal_pow","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
12:54:54 MQT: rafal_pow/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.5.7/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:42:44","StartupUTC":"2019-01-04T11:12:10","Sleep":50,"BootCount":9,"SaveCount":28,"SaveAddress":"F4000"}}
12:54:54 MQT: rafal_pow/stat/STATUS2 = {"StatusFWR":{"Version":"6.4.1.3(sonoff)","BuildDateTime":"2019-01-01T12:25:30","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
12:54:54 MQT: rafal_pow/stat/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Rafal",""],"TelePeriod":300,"SetOption":["00028009","558180C0","00000200"]}}
12:54:54 MQT: rafal_pow/stat/STATUS4 = {"StatusMEM":{"ProgramSize":522,"Free":480,"Heap":21,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":3,"Features":["00000415","0FDAE794","240383A0","23B617CE","00003BC0"]}}
12:54:54 MQT: rafal_pow/stat/STATUS5 = {"StatusNET":{"Hostname":"rafal_pow-1242","IPAddress":"192.168.5.47","Gateway":"192.168.5.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.5.1","Mac":"xxxxxxxxxxxx","Webserver":2,"WifiConfig":2}}
12:54:54 MQT: rafal_pow/stat/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.5.7","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_9584DA","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
12:54:54 MQT: rafal_pow/stat/STATUS7 = {"StatusTIM":{"UTC":"Fri Jan 04 11:54:54 2019","Local":"Fri Jan 04 12:54:54 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:43","Sunset":"17:06"}}
12:54:54 MQT: rafal_pow/stat/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
12:54:54 MQT: rafal_pow/stat/STATUS10 = {"StatusSNS":{"Time":"2019-01-04T12:54:54","ENERGY":{"TotalStartTime":"2018-11-26T06:36:25","Total":0.154,"Yesterday":0.298,"Today":0.154,"Power":4,"ApparentPower":22,"ReactivePower":22,"Factor":0.16,"Voltage":238,"Current":0.094}}}
12:54:54 MQT: rafal_pow/stat/STATUS11 = {"StatusSTS":{"Time":"2019-01-04T12:54:54","Uptime":"0T00:42:44","Vcc":3.448,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":1,"SSId":"Rafal","BSSId":"xxxxxxxxxxxx","Channel":6,"RSSI":76}}}`

**Comment by mike2nl** [comment]
@1igeza 
please fill in the requested information. You have seen it when you made these new issue.

**Comment by ascillato** [comment]
You have set powerdelta. That is why you have all those reports. Please, search in issues and also in the wiki due this issue is duplicated and was addressed before

**Comment by ascillato2** [comment]
Closing this issue as it is duplicated 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
