### ISSUE TITLE
Sonoff 4CH Pro: Interlock

### ISSUE THREAD

**Issue by wewa00** [arendst/Sonoff-Tasmota#4814]
Hello,

I have a Sonoff 4Ch Pro flashed with Tasmota and also configured it as a "Sonoff 4 CH Pro" module. My problem is, that I only can turn one relay on. If I turn another relay on, the other relay is turned off.
Interlock ("SetOption14") is off.
How can I turn several relays on at the same time?

Best regards,
wewa00

**Comment by Einstein67** [comment]
Set the hw-switches, as described in the wiki:

S6: 1
K5: all 1
K6: all 0

**Comment by ascillato** [comment]
Please, read the wiki at sonoff ch4 pro and set your dip switches as explained there. Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been duplicated. 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
