### ISSUE TITLE
New Sonoff RF R2 power need to add gpio 2

### ISSUE THREAD

**Issue by desskyblue** [arendst/Sonoff-Tasmota#4820]
**Have you look for this feature in other issues and in the wiki?**

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Ok, Thanks.

**Comment by ascillato** [comment]
PR https://github.com/arendst/Sonoff-Tasmota/pull/4821

**Comment by ascillato** [comment]
Can you please post a picture of the board? Thanks.

**Comment by desskyblue** [comment]
![sonoff_rf1](https://user-images.githubusercontent.com/46384571/50709142-1e726480-1067-11e9-966c-491aacd785b7.jpg)
![sonoff_rf_r2a](https://user-images.githubusercontent.com/46384571/50709143-1e726480-1067-11e9-9a1f-0be4486f5566.jpg)
![sonoff_rf_r2](https://user-images.githubusercontent.com/46384571/50709144-1e726480-1067-11e9-99c4-e657c73953a0.jpg)
![sonoff_rf2](https://user-images.githubusercontent.com/46384571/50709145-1e726480-1067-11e9-95c5-210545b76fb9.jpg)

**Comment by ascillato** [comment]
In an hour you will be able to download the new Tasmota version with this change from http://thehackbox.org/tasmota/

Thanks.

**Comment by desskyblue** [comment]
Which version should I choose? I do not see gpio2 with sonoff rf.
http://thehackbox.org/tasmota/sonoff.bin

**Comment by desskyblue** [comment]
Thanks for the fast action, it works very well.
