### ISSUE TITLE
Power state on web always OFF 

### ISSUE THREAD

**Issue by FFNemmenich** [arendst/Sonoff-Tasmota#4822]
I flashed one of the newer boards "Sonoff RF R2 POWER" with the firmware 6.4.1 which went great too.
If I now connect to the Sonoff via http there is "OFF" because he has not switched. If I switch it with the button, the OFF will switch to "**OFF**", the light will also turn on, but it will not show an **ON** but an **OFF**.

**Comment by ascillato2** [comment]
Please, address this to the Tasmota Support Chat. Thanks. Github issues are for bug reporting.

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
