### ISSUE TITLE
favicon in Tasmota

### ISSUE THREAD

**Issue by peiperakos** [arendst/Sonoff-Tasmota#4830]
Hello, i am new to esp8266 and tasmota !!
i have a question can i add favicon in html of tasmota ?

**Comment by peiperakos** [comment]
I will agree with you but because I only use it as a web server I would love one favicon.. 
i compile with arduino ide can i add some where ?

**Comment by ascillato2** [comment]
Closing as it is not a bug reporting

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by RichyT** [comment]
I would like to be able to do this too. If you have multiple tabs open, it would be handy to identify

**Comment by pgorod** [comment]
Totally agree with @RichyT.

Favicons are not "without purpose". They serve a very clear usability purpose in the context of, well, all the other things you are doing in other browser tabs :-)

**Comment by barbudor** [comment]
Considering that the tasmota favicon (used with docs) weight 15KB, I believe it is a no go to use that quantitty of precious flash to embedded the icon in the flash.
Alternatively, favicon is a link, so it couldbe a link to the favicon of the doc site which would work only when using a browser that is on network that has access to the Internet, case for most users.

**Comment by s-hadinger** [comment]
This should be not too hard with Berry scripting on Esp32 - need to test it.

For Esp8266, the file would need to be stored on Flash. Maybe it's not so big of a change.

**Comment by barbudor** [comment]
Not sure why you want to involve Berry
It's just a link to add in the generic page header
```
<head>
      <link rel="icon" href="https://tasmota.github.io/docs/_media/favicon.ico">
</head>
```
We don't need to store the file in the flash.

**Comment by arendst** [comment]
Berry seems to be the ultimate ointment good for everything.

**Comment by RichyT** [comment]
While I have no issue with using an icon on the web, it does have certain "phone home" and privacy implications that people might object to. I see no reason why an icon has to be 15k, however.

**Comment by s-hadinger** [comment]
Oh right, I was thinking of registering a callback to `favicon.ico` and serving the image from Flash.

**Comment by barbudor** [comment]
It's coming up ...
![image](https://user-images.githubusercontent.com/2996042/148619988-4f8888ac-3352-41af-ade9-db4b677b7865.png)
