### ISSUE TITLE
OTA 

### ISSUE THREAD

**Issue by NiekN** [arendst/Sonoff-Tasmota#4833]
The OTA does not work for my sonoff device, is my URL to the Upgrade by web server wrong?
My sonoff S20 runs : Sonoff-Tasmota 6.3.0 by Theo Arends

http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
