### ISSUE TITLE
IRsend Technics 

### ISSUE THREAD

**Issue by danielraq** [arendst/Sonoff-Tasmota#4834]
Hi 
I have a problem with Tasmota IRsend to long storry short when i send data to my Technics SA-EH580 nothing happen :( 
This what i get from remote 

`RESULT = {"IrReceived":{"Protocol":"PANASONIC","Bits":48,"Data":"0x538BC81"}}`

and this is what i send:
`21:15:03 CMD: IRsend {"Protocol":"PANASONIC","Bits":48,"Data":"0x538BC81"}
21:15:03 SRC: WebConsole from 192.168.1.243
21:15:03 RSL: Group 0, Index 1, Command IRSEND, Data {"Protocol":"PANASONIC","Bits":48,"Data":"0x538BC81"}
21:15:03 IRS: protocol_text PANASONIC, protocol PANASONIC, bits 48, data 87604353 (0x538BC81), protocol_code 5
21:15:03 MQT: stat/daniel_sypialnia/RESULT = {"IRSend":"Done"}
21:15:03 IRR: RawLen 100, Bits 48, Value 7FF11200, Decode 87604353
21:15:03 MQT: tele/daniel_sypialnia/RESULT = {"IrReceived":{"Protocol":"PANASONIC","Bits":48,"Data":87604353}}`
Unfortunattely my hifi don't see it :(

any suggestions what i can do next?

**Comment by ascillato** [comment]
Hi,

Please, for support you can use the Tasmota Support Chat.

Github issues are for Bug reporting. Thanks.

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
