### ISSUE TITLE
Wiki error PZEM004T inverted configuration

### ISSUE THREAD

**Issue by namadori** [arendst/Sonoff-Tasmota#4837]
Hi, I tried connecting the PZEM-004T energy monitor and it seems that on page https://github.com/arendst/Sonoff-Tasmota/wiki/PZEM004T-Energy-Monitor the configuration for TX and RX is inverted.

Attached you can find the screenshot of the configuration currently working for me.

Thanks for your great work!!!

![pzem004_config](https://user-images.githubusercontent.com/10942270/50730409-5653d780-114d-11e9-9ce0-05074c4d08b7.png)

**Comment by ascillato** [comment]
Yes, you are right. Please, could you be so kind to add update it? You have access to edit the wiki. Thanks
