### ISSUE TITLE
Alexa 'Device is unresponsive' workaround

### ISSUE THREAD

**Issue by alexdobo** [arendst/Sonoff-Tasmota#4838]
I've been experiencing an issue where randomly Alexa will say that my device is unresponsive. I tried various troubleshooting steps with no luck, so I made a workaround that I would like to share with anyone else that may be experiencing the same issue.

Note: This workaround isn't very good, but it's better than nothing

Setup an IFTTT trigger with Alexa (e.g. 'Alexa, trigger the lights').
Have this write the current date/time a google sheet
Run the following Python 2.7 code (inspired by [Tim Leland](https://timleland.com/use-google-home-to-control-wireless-power-outlets/)) on a RPi (or anything really):

    #!/usr/bin/env python
    import urllib, json, subprocess, time
    
    
    lastCommandDate = None
    url = 'https://spreadsheets.google.com/feeds/list/YOUR_SPREADSHEET_ID_HERE/1/public/values?alt=json'
    
    while True:
            time.sleep(.5)
    
            response = urllib.urlopen(url)
            data = json.loads(response.read())
        
            lastIndex = len(data['feed']['entry']) - 1
            currentCommandDate = data['feed']['entry'][lastIndex]['updated']['$t']
            
            if lastCommandDate != currentCommandDate:
                lastCommandDate = currentCommandDate
                urllib.urlopen("http://Your_Devices's_IP_Here/cm?cmnd=Power%20TOGGLE")

Essentially, this checks to see if the spreadsheet has been modified, and if it has, then it toggles the lights.
There are a few other ways to do this, if you set up port forwarding, you could get IFTTT to toggle the lights directly
    
As I said, it's not good, but it works.
You can add a bit more to make sure it doesn't repeat commands using the gspread module

It might even be possible to run this code (or something similar on the device itself?

**Comment by Jason2866** [comment]
Which version do you run? There where a modification for release 6.4.x for Alexa that should fix this.
Please fill out issue template. Thx!
There will be no modification to use Alexa with the need to use a third party provider

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
