### ISSUE TITLE
Increase HX711 resolution

### ISSUE THREAD

**Issue by nicolasbisi** [arendst/Sonoff-Tasmota#4839]
**Have you look for this feature in other issues and in the wiki?**
Yes

**Is your feature request related to a problem? Please describe.**
Maybe, not sure. I'm only getting integer values.

**Describe the solution you'd like**
Maybe having a Sensor34 7 that switches between Kg and g. Or just add Kg with more resolution (x,xx instead of integer only)

Cheers

**Comment by arendst** [comment]
Look in wiki for command weightres

**Comment by nicolasbisi** [comment]
Ah. Nice. Thanks, @arendst.

**Comment by pico563** [comment]
@arendst 
thank you for all your great work
I spent a hole day trying to find how to change the resolution but unfortunately there is no Wiki for HX711.
I changed in the sketch to get it work as gram (i removed the / 1000)
finally I found this command **"weightres"**
I still don't understand **Item weight (kg)** is used for.
please add a wiki for HX711
thanks

**Comment by meingraham** [comment]
@pico563 Arggh! WeightRes was missing from the wiki. That was the missing piece I was hoping for. I added the WeightRes command to the wiki.

The whole topic of how to best document supported sensors is being discussed. When this portion of the wiki is restructured, we will look at all the supported sensors, out of date sensors, future sensors, etc.

Thanks for being persistent.

Mike

**Comment by pico563** [comment]
hi @meingraham 
I found it after our last night discussion (zee)
thanks

**Comment by pico563** [comment]
@meingraham @ascillato2 
I still don't understand **_Item weight (kg)_** is used for.

**Comment by pico563** [comment]
[https://dl3.pushbulletusercontent.com/rbr2oUH5jrydRe3uIiQXtwak1a9fxeyZ/Screenshot_20190511-150149.png](url)

**Comment by pico563** [comment]
@meingraham
@ascillato2

about sensor34  6
it shows item weight in gram and not in decigram.
pls. check
```
`6`  = show single item weight in decigram
|`6 <value>`  = set single item weight in decigrams. Once the item weight is set, when items are added to the scale, the telemetry message will report the number of items.
```
```
23:00:01 CMD: Sensor34  6
23:00:01 RSL: RESULT = {"Sensor34":{"WeightRef":250,"WeightCal":261,"WeightMax":10000,"WeightItem":250.0}}

23:00:03 RSL: SENSOR = {"Time":"2019-05-16T23:00:03","HX711":{"Weight":1.534,"Count":6}}
```

**Comment by meingraham** [comment]
It appears that you set the weight per item to be 250. Is the reported `Weight` in grams or Kilograms? If it's Kilograms, then I agree, the item weight setting is grams. Please confirm that the weight on your scale was 1.5 Kg.

**Comment by pico563** [comment]
confirmed .

**Comment by meingraham** [comment]
Wiki updated.

**Comment by dexterbot80** [comment]
> Look in wiki for command weightres

Hello @arendst, hello @meingraham Where is located that wiki page?
I want to learn how to display the weight in grams.
Thank you

**Comment by sfromis** [comment]
The unit is always kilograms, but using the command [WeightRes](https://tasmota.github.io/docs/Commands/#weightres), you can set a precision of 3 decimals for grams.

**Comment by dexterbot80** [comment]
> The unit is always kilograms, but using the command [WeightRes](https://tasmota.github.io/docs/Commands/#weightres), you can set a precision of 3 decimals for grams.

Thank you @sfromis

**Comment by sfromis** [comment]
In general, you can expect things working with Tasmota for ESP8266 to also work with ESP32, but with Mr. Murphy not being "very predictable", I'm nok making absolute claims :wink:

**Comment by dexterbot80** [comment]
> In general, you can expect things working with Tasmota for ESP8266 to also work with ESP32, but with Mr. Murphy not being "very predictable", I'm nok making absolute claims 😉

Hello, It works with ESP32 but i have one Chinese weighing machine that have bluetooth connection with the screen.
They use an Chinese IC chip that have I2C connection to - 3.3V SDA SCL GND pins available on the board.
It will be great if we manage to connect TASMOTA to this and make-it MQTT compatible :)

**Comment by sfromis** [comment]
You already have [another thread](https://github.com/arendst/Tasmota/discussions/22053) about that **unrelated** question.

**Comment by dexterbot80** [comment]
> You already have [another thread](https://github.com/arendst/Tasmota/discussions/22053) about that **unrelated** question.

Yeah, Maybe we make-it .....:)
I connected the 400KG weight cell to the HX711 and encountered a rather interesting problem.
When I try to calibrate with a known weight, it displays a much higher weight.
At a weight of 291 grams it displays 311 - 312 after calibration and at my weight of 76200 grams after calibration it displays 78800-78900 grams.
I used two types of boards with HX711 powered by both 5V and 3.3V and they behave the same.
I use the latest version of tasmota sensors [from here](https://tasmota.github.io/install/) and the pins for DT and SCK are D4 and D5 at ESP32.
Has anyone encountered this problem?

**Comment by dexterbot80** [comment]
Hello, @arendst, @meingraham 
Can someone tell me where I can find the full calibration process for the HX711? I kept trying but I can't calibrate the scale.

I designed this for Arduino and the calibration works, but I would like to be able to use Tasmota - programmers much more skilled than me worked here :)

`#include <Ethernet.h>
#include <PubSubClient.h>
#include <HX711.h>
#include <EEPROM.h>

// Ethernet settings
byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
IPAddress ip(192, 168, 1, 21);  // IP address of Arduino
IPAddress server(192, 168, 1, 200);  // MQTT Server IP

// MQTT settings
const char* mqttUser = "openhabian";
const char* mqttPassword = "openhabian";
const char* mqttTopicWeight = "home/loadcell/weight";
const char* mqttTopicCalibration = "home/loadcell/calibration";

// Define Client ID
#define CLIENT_ID "Client_001"  // Modifică acest ID pentru fiecare dispozitiv

// HX711 load cell settings
#define DOUT  6
#define CLK  7
HX711 scale;

float calibration_factor = 1.0;  // Default calibration factor
float known_weight = 2000.0;     // Known weight placed on the load cell in grams

// EEPROM Addresses
#define EEPROM_CALIBRATION_FACTOR_ADDR 0

// Ethernet client
EthernetClient ethClient;

// MQTT client
PubSubClient client(ethClient);

// Define RESET_EEPROM macro
#define RESET_EEPROM 1  // Change this to 1 to reset EEPROM

// Function to write a float value to EEPROM
void EEPROM_writeFloat(int address, float value) {
  byte* data = (byte*)(void*)&value;
  for (int i = 0; i < sizeof(float); i++) {
    EEPROM.write(address + i, data[i]);
  }
}

// Function to read a float value from EEPROM
float EEPROM_readFloat(int address) {
  float value = 0.0;
  byte* data = (byte*)(void*)&value;
  for (int i = 0; i < sizeof(float); i++) {
    data[i] = EEPROM.read(address + i);
  }
  return value;
}

// Function to reset EEPROM
void resetEEPROM() {
  for (int i = 0; i < EEPROM.length(); i++) {
    EEPROM.write(i, 0xFF);  // Write 0xFF to every address in EEPROM
  }
  Serial.println("EEPROM reset completed.");
}

// Function to reconnect to the MQTT server
void reconnect() {
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    if (client.connect(CLIENT_ID, mqttUser, mqttPassword)) {
      Serial.println("connected");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      delay(5000);
    }
  }
}

void setup() {
  Serial.begin(115200);
  Serial.println("Load Cell Calibration");

  // Check if EEPROM should be reset based on the macro
  if (RESET_EEPROM == 1) {
    resetEEPROM();  // Reset EEPROM
    calibration_factor = 1.0;  // Set default calibration factor
    EEPROM_writeFloat(EEPROM_CALIBRATION_FACTOR_ADDR, calibration_factor);
    Serial.println("Calibration factor reset to default.");
  }

  // Initialize Ethernet
  Ethernet.begin(mac, ip);
  delay(1000);
  Serial.println("Ethernet initialized");

  // Initialize MQTT
  client.setServer(server, 1883);

  // Initialize the HX711 scale
  scale.begin(DOUT, CLK);
  scale.set_gain(128);  // Set gain to 128

  // Load EEPROM values
  calibration_factor = EEPROM_readFloat(EEPROM_CALIBRATION_FACTOR_ADDR);

  // If calibration factor is 'nan', reset to default
  if (isnan(calibration_factor) || calibration_factor <= 0) {
    calibration_factor = 1.0;
    Serial.println("Calibration factor not valid. Using default value.");
  }

  Serial.print("Loaded calibration factor: ");
  Serial.println(calibration_factor);

  // Calibration process using new method
  if (calibration_factor == 1.0) {
    Serial.println("Empty the scale and press any key to continue");
    unsigned long startMillis = millis();
    bool inputReceived = false;
    while (millis() - startMillis < 30000) {  // Timeout after 30 seconds
      if (Serial.available()) {
        Serial.read();  // Consume any available input
        inputReceived = true;
        break;
      }
      delay(100);  // Small delay to avoid rapid polling
    }
    if (!inputReceived) {
      Serial.println("No input received. Exiting calibration.");
      return;
    }

    Serial.println("Taring scale...");
    scale.tare();  // Double tare for better accuracy

    Serial.println("Put 2000 grams on the scale, then press any key to continue");
    startMillis = millis();
    inputReceived = false;
    while (millis() - startMillis < 30000) {  // Timeout after 30 seconds
      if (Serial.available()) {
        Serial.read();  // Consume any available input
        inputReceived = true;
        break;
      }
      delay(100);  // Small delay to avoid rapid polling
    }
    if (!inputReceived) {
      Serial.println("No input received. Exiting calibration.");
      return;
    }

    Serial.println("Waiting for stabilization...");
    delay(30000);  // Wait for 30 seconds to stabilize

    // Measure weight multiple times and calculate average
    float total = 0;
    int num_samples = 20;  // Increase number of samples for better accuracy
    for (int i = 0; i < num_samples; i++) {
      total += scale.get_units();
      delay(500);  // Delay between measurements
    }
    float average_weight = total / num_samples;

    // Calibrate using known weight
    scale.calibrate_scale(known_weight, average_weight);  // Calibrate with 2000 grams
    calibration_factor = scale.get_scale();  // Get the calculated scale factor

    // Save the calibration factor to EEPROM
    EEPROM_writeFloat(EEPROM_CALIBRATION_FACTOR_ADDR, calibration_factor);

    // Publish calibration message
    char calibrationMessage[50];
    snprintf(calibrationMessage, sizeof(calibrationMessage), "Calibration complete with factor: %.4f", calibration_factor);
    client.publish(mqttTopicCalibration, calibrationMessage);

    Serial.print("Calibration factor: ");
    Serial.println(calibration_factor);

    Serial.println("Calibration completed. Remove the weight.");
    delay(5000);  // Wait for the weight to be removed

    scale.tare(); // Reset the scale to zero again
    Serial.println("Scale is ready.");
  } else {
    scale.set_scale(calibration_factor); // Use the saved calibration factor
    scale.tare(); // Reset the scale to zero
  }
}

void loop() {
  if (!client.connected()) {
    reconnect();
  }
  client.loop();

  // Measure the weight with higher precision
  float weight = 0;
  int num_samples = 20;  // Number of samples to take for averaging
  for (int i = 0; i < num_samples; i++) {
    weight += scale.get_units();
    delay(100);  // Delay between measurements
  }
  weight /= num_samples;  // Average the weight readings

  // Check if weight is less than 10 grams and reset scale if true
  if (weight < 10) {
    weight = 0; // Set weight to 0 grams
    scale.tare(); // Reset scale to zero
    Serial.println("Weight is less than 10 grams. Scale reset to zero.");
  }

  // Print the weight to Serial
  Serial.print("Weight: ");
  Serial.print(weight);
  Serial.println(" grams");

  // Convert the weight to string and publish it
  char weightString[8];
  if (weight < 10) {
    snprintf(weightString, sizeof(weightString), "0"); // Publish 0 grams if weight is less than 10 grams
  } else {
    dtostrf(weight, 1, 2, weightString);
  }
  client.publish(mqttTopicWeight, weightString);

  // Delay before next reading
  delay(2000);  // 2-second delay between readings
}
`

**Comment by dexterbot80** [comment]
> Look in wiki for command weightres

Hello @arendst 
You kill me with this phrase :)
Where is the wiki for HX711 located?
I searched [here](https://tasmota.github.io/docs/Supported-Peripherals/) but the HX711 does not have a dedicated page

Thank you

**Comment by barbudor** [comment]
All commands are on the Commands page
https://tasmota.github.io/docs/Commands/

**Comment by dexterbot80** [comment]
> All commands are on the Commands page https://tasmota.github.io/docs/Commands/

Thank you @barbudor 
Now I found for Sensor34
I hope I can calibrate :)
Thank again 1000 times :)

**Comment by dexterbot80** [comment]
For small weights it seems to work with autocalibration.
But if I later put large weights on the scale, the error is very large, several kilograms...
For example, if I calibrate with a weight of 2000 grams, after calibration I measure 2070 - 2073 grams.
And then if I get on the scale with 75200 grams, the scale displays 79680 - 79683 and it annoys me because I'm not even like a bear :)
Calibrated scale value can only be an integer?
I tried to enter 11.4 or 11.4, but the saved value remains fixed at 11...
Can someone give me an idea how to properly calibrate the scale for a weight up to a maximum of 100KG?

Thank you
