### ISSUE TITLE
FeatureRequest: Show Name/Place of the Module on WebGui?

### ISSUE THREAD

**Issue by ozett** [arendst/Sonoff-Tasmota#4840]
after some while i update my devices OverTheAir,
but i dont know exactly where i placed them around the house.
so i can not find them quick, if anything goes wrong.

i would be very helpful to store a hint on the devices,
like a name,or place. it would also be more informational,
to see this info on the landing-webpage, as the somehow redundant modulename "sonoff" or the already configured type itself.

![image](https://user-images.githubusercontent.com/5937811/50736499-9d2de580-11be-11e9-9422-36b25637117e.png)

what do you think?

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
