### ISSUE TITLE
shelly 2 SW1 not working when module shelly2 selected, disable internal pullup for SW1

### ISSUE THREAD

**Issue by fhloston** [arendst/Sonoff-Tasmota#4841]
**Describe the bug**
_When the module is set to shelly2 the momentary switch connected to SW1 has no effect when it is pressed. When the module is set to generic and "GPIO4":"21 (Relay1)","GPIO5":"22 (Relay2)","GPIO12":"82 (Switch1n)","GPIO14":"83 (Switch2n)" both SW1 and SW2 work as expected.

When seting "GPIO4":"21 (Relay1)","GPIO5":"22 (Relay2)","GPIO12":"82 (Switch1)","GPIO14":"83 (Switch2)" the result is the same as with module shelly2, only SW2 works.

The toggle buttons in webfrontend do work properly in both cases. Same goes for mqtt cmnds. _

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [X] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : shelly2, gira momentary switch, warema shades 
- [X] _Development/Compiler/Upload tools used_ : tasmota 6.4, tasmota 6.4.1.6 with core2.5/commit 4135100
- [X] _If a pre-compiled release or development binary was used, which one?_ :
6.4.1.6(4135100-sonoff)
2_5_0_BETA2/3.0.0-dev(c0f7b44)
- [X] _You have tried latest release or development binaries?_ : yes
- [X] _Provide the output of command_``status 0`` :
```
15:11:00 CMD: status 0
15:11:00 MQT: stat/bedroom/shades/STATUS = {"Status":{"Module":47,"FriendlyName":["tasmota","tasmota2"],"Topic":"bedroom/shades","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[4,4,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1}}
15:11:00 MQT: stat/bedroom/shades/STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"sonoffs","OtaUrl":"http://xxx/tasmota/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:00:17","StartupUTC":"2019-01-06T14:10:43","Sleep":50,"BootCount":30,"SaveCount":439,"SaveAddress":"FA000"}}
15:11:00 MQT: stat/bedroom/shades/STATUS2 = {"StatusFWR":{"Version":"6.4.1.6(4135100-sonoff)","BuildDateTime":"2019-01-05T17:12:16","Boot":31,"Core":"2_5_0_BETA2","SDK":"3.0.0-dev(c0f7b44)"}}
15:11:00 MQT: stat/bedroom/shades/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":2,"LogHost":"xxx","LogPort":514,"SSId":["SSID1","SSID2"],"TelePeriod":300,"SetOption":["0000C029","558180C0","00000008"]}}
15:11:00 MQT: stat/bedroom/shades/STATUS4 = {"StatusMEM":{"ProgramSize":547,"Free":456,"Heap":18,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540EF","FlashMode":3,"Features":["00000809","0FDAE794","000383A0","23B617CE","00003BC0"]}}
15:11:00 MQT: stat/bedroom/shades/STATUS5 = {"StatusNET":{"Hostname":"bedroom/shades-5049","IPAddress":"10.100.4.12","Gateway":"10.100.4.1","Subnetmask":"255.255.255.0","DNSServer":"10.100.4.1","Mac":"xx:xx:xx:xx:xx:xx","Webserver":2,"WifiConfig":4}}
15:11:00 MQT: stat/bedroom/shades/STATUS6 = {"StatusMQT":{"MqttHost":"yyy","MqttPort":1883,"MqttClientMask":"tasmota-5049","MqttClient":"tasmota-5049","MqttUser":"tasmota-5049","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
15:11:00 MQT: stat/bedroom/shades/STATUS7 = {"StatusTIM":{"UTC":"Sun Jan 06 14:11:00 2019","Local":"Sun Jan 06 15:11:00 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":99,"Sunrise":"08:22","Sunset":"16:38"}}
15:11:00 MQT: stat/bedroom/shades/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
15:11:00 MQT: stat/bedroom/shades/STATUS10 = {"StatusSNS":{"Time":"2019-01-06T15:11:00","Switch1":"OFF","Switch2":"OFF","ENERGY":{"TotalStartTime":"2018-12-22T17:52:35","Total":0.025,"Yesterday":0.000,"Today":0.025,"Power":115,"ApparentPower":117,"ReactivePower":26,"Factor":0.98,"Frequency":50,"Voltage":225,"Current":0.521}}}
15:11:01 MQT: stat/bedroom/shades/STATUS11 = {"StatusSTS":{"Time":"2019-01-06T15:11:00","Uptime":"0T00:00:17","Vcc":3.512,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"ON","POWER2":"OFF","Wifi":{"AP":1,"SSId":"SSID1","BSSId":"yy:yy:yy:yy:yy:yy","Channel":6,"RSSI":70}}}
```

**To Reproduce**
_Steps to reproduce the behavior:_
Set shelly2 to module shelly2, connect momentary switches to SW1 and SW2, press SW2 connected switch, shades move up, press SW1 connected switch -> nothing happens
Set shelly2 to module generic, configure GPIO ports: "GPIO4":"21 (Relay1)","GPIO5":"22 (Relay2)","GPIO12":"82 (Switch1n)","GPIO14":"83 (Switch2n)", press SW1 -> shades move down 

**Expected behavior**
_A clear and concise description of what you expected to happen._
Presses on a SW1 connected switch should have an effect when module shelly2 is selected.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
As you are using momentary switches did you change the switchmode1 and switchmode2 from 0 to 3?

**Comment by ascillato2** [comment]
@arendst What about having 2 templates for Shelly 2, like **Shelly 2-P** and **Shelly 2-NP**, and let the user choose the one that works for their hardware ?

**Comment by arendst** [comment]
Add no pull-up control to Shelly 2 module (default is pull-up, change GPIO2 to Switch3n for no pull-up).

Give it a try.

Using pull-up (default):

![image](https://user-images.githubusercontent.com/11044339/50739705-2f94b000-11e4-11e9-9a57-d802b9202b64.png)

Not using pull-up:

![image](https://user-images.githubusercontent.com/11044339/50739709-41765300-11e4-11e9-8a1d-209e30c6f116.png)

**Comment by fhloston** [comment]
Weird, my wires are also very short, the shelly2 is conencted directly to the gira switches [1] in the same "unterputzdose". So not more than 10cm.

Will give the new version a go! 

[1] https://www.amazon.de/Gira-015700-SchalterTaster-Jalousie-2-polig/dp/B000ONRHXG

**Comment by fhloston** [comment]
Yup, module=shelly2, GPIO2=Switch3n -> works.

Thanks a lot for the quick fix!

GPIO2 Switch3n is not very intuitive though...

**Comment by ascillato2** [comment]
Closing this issue as it has been added a new option.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
