### ISSUE TITLE
RF B1 signal conversion to B0

### ISSUE THREAD

**Issue by mewild** [arendst/Sonoff-Tasmota#4847]
Describe the bug
I have a RF hub running Tasmota 6.4.1.6 flashed with Portisch.

I have successfully sniffed the following codes from rfraw 166 (Representing up, stop and down)

18:24:08 MQT: tasmota/tele/sonoff-rfbridge/RESULT = {"RfRaw":{"Data":"AAA60601FFFF4273F555"}}
18:24:14 MQT: tasmota/tele/sonoff-rfbridge/RESULT = {"RfRaw":{"Data":"AAA60601FFFF4273F155"}}
18:24:15 MQT: tasmota/tele/sonoff-rfbridge/RESULT = {"RfRaw":{"Data":"AAA60601FFFF4273F955"}}

rfraw 177 only produces the following:

00:06:54 MQT: tasmota/stat/sonoff-rfbridge/RESULT = {"RfRaw":"ON"}
00:06:54 MQT: tasmota/tele/sonoff-rfbridge/RESULT = {"RfRaw":{"Data":"AAA055"}}

I cant find any documentation on how to decode these signals to resend. Could anyone help?

I have tried the following codes as a result of reading another issue thread:

AAA80601FFFF4273F955

but to no avail.

Searched the problem in issues and in the wiki [x]
Hardware used : RF Bridge 2, Abis Screen Projector Remote
If a pre-compiled release or development binary was used, which one? Tasmota 6.4.1.6
To Reproduce
Cannot as need remote to reproduce codes.

Expected behavior
Projector Screen reacts to rf codes as expected (Up, Down, Stop).

Screenshots

Additional context

(Please, remember to close the issue when the problem has been addressed)

**Comment by ascillato2** [comment]
Are you using latest Tasmota 6.4.1.7? Can you please update to latest and also **complete the troubleshooting template**? Thanks

**Comment by Jason2866** [comment]
Please start reading here https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF-Bridge-433#interactive-b1-to-b0-tool

**Comment by Jason2866** [comment]
The custom firmware for the EFM chip is from Portisch.
For further support visit his github side https://github.com/Portisch/RF-Bridge-EFM8BB1
