### ISSUE TITLE
Minus "-" character is an unfortunate choice for index separation

### ISSUE THREAD

**Issue by katodev** [arendst/Sonoff-Tasmota#4857]
I connect two sensors (DS18S20) from the same type and I get these two names:
 DS18S20-1
 DS18S20-2

MQTT use a JSON string for names and values.  When I try to extract the values in JavaScript with a JSON function I get an error.

A part of my script:
```
var idJSON = 'mqtt.0.tele.test.SENSOR';
var obj = JSON.parse(json);
Temp1 = obj.DS18S20-1.Temperature; 
Temp2 = obj.DS18S20-2.Temperature;
```

Minus sign "-" is an arithmetic operation and the index separation of the name. The same issue is with the command-line JSON processor "jq"

I thing an underscore "_" for the index separation should be better.

My software is openSUSE leap 15.0 , ioBroker 3.5.10 , tasmota 5.14.0

**Comment by Jason2866** [comment]
Duplicate... Search in issues
"-" is allowed in Json string

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
