### ISSUE TITLE
Wiki: Split up Hardware Preparation

### ISSUE THREAD

**Issue by ThomDietrich** [arendst/Sonoff-Tasmota#486]
Hey @arendst,
seems like the [Hardware Preparation](https://github.com/arendst/Sonoff-Tasmota/wiki/Hardware-Preparation) page is growing out of it's size while the device specific articles (currently titled "Tips") do only contain little content. If you agree I'd move all device specific preparation content into the specific articles under a title "Devices".

**Comment by arendst** [comment]
Yes please do.

**Comment by ThomDietrich** [comment]
Sonoff Dual done. https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Dual (you might want to copy the second image over to your media folder)

**Comment by ThomDietrich** [comment]
Sonoff Pow done. I've also tuned the first part of the Hardware Preparation article.

Whoever is reading this, feel free to follow along with any of the other modules.

**Comment by ThomDietrich** [comment]
Sonoff Touch done.

**Comment by ThomDietrich** [comment]
Sonoff 4CH done.

Next up Sonoff (basic) probably the most important.

**Comment by ThomDietrich** [comment]
@arendst regarding: https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Pow

Sorry I removed this warning you've readded. However I'm not sure why it is needed. The warning is no different for all other modules and I've added it to the general Hardware Preparations article long ago. All module specific articles are referencing this article and hence are already linked to this warning.

**Comment by arendst** [comment]
The problem with a pow is that ANY connection, even gnd only could blow your PC as AC mignt blow it's power supply. That's why only opto coupling is safe.

For all other sonoffs serial connection is safe as long the Vcc is not connected to your PC.
