### ISSUE TITLE
Sonoff POW v 2.0 has 4MB Flash

### ISSUE THREAD

**Issue by danilogd** [arendst/Sonoff-Tasmota#487]
I bought a bunch of Sonoff POW a week ago and all have a 32Mbit Flash chip instead of the usual 8Mbit.
What changes are needed to adapt to this new flash capacity?

Here are two photos of the new chips:

![img_0869](https://cloud.githubusercontent.com/assets/29076242/26607736/fb28d018-4565-11e7-9711-9bb44b41efd1.JPG)
![img_0870](https://cloud.githubusercontent.com/assets/29076242/26607741/0039d228-4566-11e7-97af-3b561a2a13b8.JPG)

Thank you in advance.

**Comment by davidelang** [comment]
If the only difference is the flash size, the existing builds should work just 
fine. Some of the other devices have 4MB flash and normally we just ignore the 
extra capacity.

**Comment by khcnz** [comment]
This is the standard sonoff pow build - but since the desire is to run the same build on all sonoffs the normal advice is just to use the 1mb mode for all devices - some more info here https://github.com/arendst/Sonoff-Tasmota/issues/437

**Comment by dimitrisA** [comment]
Hello. Could you please share where you bought these 4 Mb Sonoff POWs ? Thanks! :)
