### ISSUE TITLE
Xiaomi Desk Lamp support

### ISSUE THREAD

**Issue by dh-harald** [arendst/Sonoff-Tasmota#4870]
Hi,

I've a Xiaomi/Yeelight Smart Desk lamp (https://www.mi.com/global/smartlamp/). It would be nice, if Tasmota could support it.

It has 2 opensource firmware already:
https://github.com/fvollmer/xiomi-desk-lamp-open-firmware
https://github.com/Torxgewinde/Desk-Lamp-Alternative-Firmware

**Comment by arendst** [comment]
Nice complete product.

But does it provide enough light? 600lm is not much for a desk lamp...

**Comment by ascillato2** [comment]
Please, try Tasmota with the generic module configuration and set the gpios according to this hardware to test. You will need to find out which gpios of the esp8266 are connected and to what. Thanks for share.

**Comment by dh-harald** [comment]
Hi,

Based on the existing firmwares, I've set the following:
D4 GPIO2 -> Button1 (17)
D2 GPIO4 -> PWM1 (37)
D1 GPIO5 -> PWM2 (38)

With this settings, I could turn on and off the lamp via pressing the button, and I could set the brightness and the color temperature on the web frontend... (toggle button worked as well)

Unfortunately (I think), the rotary switch needs extra work from your side...

**Comment by arendst** [comment]
Yes, the rotary switch functionality is not available  in Tasmota.

**Comment by ascillato** [comment]
>Unfortunately (I think), the rotary switch needs extra work from your side...

And also the hardware. You can send one of those lamps to Theo.

**Comment by dh-harald** [comment]
> Yes, the rotary switch functionality is not available in Tasmota.

In this case, I'll try to implement it. Fingers crossed :)

**Comment by ascillato2** [comment]
PR from @dh-harald https://github.com/arendst/Sonoff-Tasmota/pull/4887
