### ISSUE TITLE
Shelly HT support

### ISSUE THREAD

**Issue by mientki** [arendst/Sonoff-Tasmota#4874]
Is it possible to add support for Shelly HT in Tasmota?

https://shelly.cloud/shelly-humidity-and-temperature/

**Comment by curzon01** [comment]
That's a battery driven device; I don't believe it works long enough with Tasmota

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
