### ISSUE TITLE
Switchdebounce

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#4876]
Is it possible to modify the Arduino sketch to increase the maximun switch debounce option from 1 second to 2 seconds?

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by benzino77** [comment]
@ascillato2 the maximum debounce possible is 1s (that is based on the wiki, I don't know how and if it is checked in the code) but the @Lawrencezarb needs 2s.
@Lawrencezarb try this rule (switchtopic has to be 0):
```java
on switch1#state do
RuleTimer1 2
endon
on rules#timer=1 do
//do your stuff
endon
```
It will work that way:
when switch state will be changing over 2 seconds, the timer will be restarted every change. When the state of the switch will be "stable" for 2s, the timer will fire and do what you want.

ps.
Haven't tested that ;)

**Comment by Jason2866** [comment]
Switch debounce >1sec why?  What switch is this?
For providing a propper solution it would be better to describe your complete problem / use case.
For doing this visit us at our Chat.

**Comment by benzino77** [comment]
@Jason2866 it has not to be a switch that you can think of. Just give up the idea of using Tasmota with those two:
![switch](https://user-images.githubusercontent.com/15658235/51017340-10937680-1574-11e9-9783-fe56a052491e.jpg)
![bulb](https://user-images.githubusercontent.com/15658235/51017343-12f5d080-1574-11e9-9ed6-e0d6c7616778.jpg)
and you will see how deep is a rabbit burrow (and what Tasmota is capable of) ;)
For example, in one place I've seen using Tasmota with this little puppies:
![floating](https://user-images.githubusercontent.com/15658235/51017612-ec846500-1574-11e9-95cd-4bdd0a8120bd.jpg)
When the water surface is moving up and down... well you can imagine what happens.

... and please don't take this too serious ;)

**Comment by Jason2866** [comment]
Not thinking just in switches and bulbs with Tasmota was the reason asking for the use case...
If switchdebounce with 1 second isnt enough there is probably a other solution needed.

**Comment by benzino77** [comment]
Tasmota gives you ability to get to the destination (the behavior/state you expect/need) in many different ways. Start thinking of switch as a **_sensor_**. One second debounce for the switch from the picture above is a nightmare (even if it is possible and doable by Tasmota). If you start thinking of switch as a actuator/sensor one or more seconds is not a big deal.
