### ISSUE TITLE
How to connect multiple DS18B20 to Sonoff TH16

### ISSUE THREAD

**Issue by rikray02** [arendst/Sonoff-Tasmota#4880]
Hello,

I read in closed issue that it's possible to connect multiple DS18B20 to Sonoff TH10/16.  So, i don't know how.  Does it's possible to explain how can i do that?  Can i connect many DS18B20 to the same GPIO14 (external connector) or i need to use other one (GPIO4)?

Thank a lot for your help.
Richard

**Comment by edelstahlratte** [comment]
They share one single-wire bus... See [https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-Configuration#single-wire-sensor](url) and [https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs](url) to get an idea... It's simple...

Nico.

**Comment by Jason2866** [comment]
You have to connect like this
https://www.microcontroller-project.com/uploads/2/2/1/5/22159166/nodemcu-esp8266-with-multiple-ds18b20-sensors_orig.png

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
