### ISSUE TITLE
/in values (especially mac or software version as json

### ISSUE THREAD

**Issue by mo8Zomo0** [arendst/Sonoff-Tasmota#4889]
**Have you look for this feature in other issues and in the wiki?**
yes could not find it
Especially parameters like the software version and the macadress I did not find in
the sourcecode or documentaion on how to request it as json.

**Is your feature request related to a problem? Please describe.**
My problem is that I would like to see the info from the /in as a json list.

**Describe the solution you'd like**
Implement in the source code to have more status / information about the device as json

**Describe alternatives you've considered**
tried to analyse the page returned by /in but that does not seem to be very friendly to grab

**Additional context**
-

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
