### ISSUE TITLE
Enhancement request: press and hold a switch for different action

### ISSUE THREAD

**Issue by lotekjunky** [arendst/Sonoff-Tasmota#489]
If at all possible, it would be very useful to have a "press and hold" feature. Right now I have a switch that sends a toggle command to my automation server. If I press the switch (SWITCH_MODE = PUSHBUTTON) for > X seconds, it would then send a different message, perhaps "hold" instead of "toggle" (possible MQTT_CMND_HOLD or just StateText4?)

**Comment by arendst** [comment]
SwitchMode 5 (PUSHBUTTONHOLD) and 6 (PUSHBUTTONHOLD_INV) will be introduced in next release.
