### ISSUE TITLE
Lot of Outages

### ISSUE THREAD

**Issue by MaxBec** [arendst/Sonoff-Tasmota#4890]
Hey guys,

since i updated to 6.4.1 i have a lot of unreachable Sonoff devices.
I compiled with 2.3.0 and TasmotaMQTT.

![grafana_-_maintenance](https://user-images.githubusercontent.com/8254514/51018777-19d31200-1579-11e9-93ad-e737abfc3a67.jpg)

Do you have any idea on how to reduce those outages? I already tried 2.4.2 and 2.5.0... they were even worse.

Thanks.

**Comment by Jason2866** [comment]
First fill out issue template. No template - No help (possible)
Read:
https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting
https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#wifi-issues-arduino-core-versions-and-expressif-sdk

**Comment by MaxBec** [comment]
I will try the 2.5.0 again.
But are there any recommendations for which MQTT version to use?
Tasmota, PubSub, etc.?

**Comment by Jason2866** [comment]
`#define MQTT_LIBRARY_TYPE      MQTT_PUBSUBCLIENT   // Use PubSubClient library`

**Comment by ascillato** [comment]
Please, use the precompiled bins to solve your issue as explained in the wiki at 

https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#wifi-issues-arduino-core-versions-and-expressif-sdk

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
