### ISSUE TITLE
Where to go for help?

### ISSUE THREAD

**Issue by ripvega** [arendst/Sonoff-Tasmota#4892]
I appreciate that this is are for raising tasmota issues but I don't have an issue to raise, I'm just looking for some help.

Where is the best place to ask for tasmota assistance?

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
