### ISSUE TITLE
Sonoff T1 3ch - is possible to interlock only 2 gang??

### ISSUE THREAD

**Issue by Pako75** [arendst/Sonoff-Tasmota#4893]
Hi, I've just flashed Tasmota on my T1 US 3ch and I'm wondering if it's possible to interlock only 2 of the 3 relays....

Thank you

**Comment by ascillato** [comment]
Sorry, not supported

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
