### ISSUE TITLE
Wemos D1 with PIR and WS2812

### ISSUE THREAD

**Issue by danst0** [arendst/Sonoff-Tasmota#4895]
Hi,

I have a WEMOS D1 with a SR501 _and_ a WS2812 connected.
My workflow is as follows:
* Motion is detected properly.
* MQTT message is received by openHAB
* openHAB sends MQTT to switch on WS2812 (openHAB does not switch off the light)

However the light goes off as soon as the motion trigger from the PIR is released.
On the MQTT bus and the console I see an stat/pir1/POWER OFF message.

Isn't is somehow possible to separate the sensor from the lights completely?

Daniel

**Comment by ascillato** [comment]
Hi,

Yes, it is possible. Please, search in issues for PIR. This was addressed several times with the solution provided. Also in the wiki are the examples of PIR. 

Thanks

**Comment by ascillato2** [comment]
Closing this issue as it is duplicated. 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
