### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by scargill** [arendst/Sonoff-Tasmota#4897]
Hi

Im using the latest binary for Sonoff Basic and just getting to grips with it. I noted when sending MQTT messages from Node Red that the cmnds are not case sensitive but it seems that status of POWER is case sensitive. Seems odd for one way to be case sensitive and not the other...

**Comment by Jason2866** [comment]
Just do all case sensitive and you are fine :-)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
