### ISSUE TITLE
Enhancement request - relay on/off to accept boolean true/false

### ISSUE THREAD

**Issue by smadds** [arendst/Sonoff-Tasmota#49]
Could the alternative options for switching the relay(s) on and off include true/false so it will work with a Boolean input?

(I am looking to use a ramp thermostat - http://flows.nodered.org/node/node-red-contrib-ramp-thermostat and it would save having to add converters)

**Comment by arendst** [comment]
You mean 0 for false and 1 for true? If so than that's already implemented. Power 0 is off, Power 1 is on, Power 2 is toggle.

**Comment by smadds** [comment]
In Node Red a Boolean output is sent as string "true" or string "false", so
could those be aliases for 1 and 0?

ᐧ

**Comment by arendst** [comment]
Ah, can't you put a function node behind the node putting out true/false and convert it to 1/0?

**Comment by smadds** [comment]
Yes, of course. Just thought that it would increase the flexibility of the
Tasmota code and make the node-red flows easier to follow.

**Comment by arendst** [comment]
Fixed in version 3.9.14 just released

**Comment by smadds** [comment]
Brilliant. Thanks Theo
