### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by rlust** [arendst/Sonoff-Tasmota#490]
Sorry, but I do not understand where the binary files are located,

**Comment by cobra85ec** [comment]
https://github.com/arendst/Sonoff-Tasmota/releases

**Comment by TRIROG** [comment]
Can the OTA filename now be just
 #define OTA_URL                "serverIP" PROJECT ".bin"  // [OtaUrl]
or does it still need to be 
 #define OTA_URL                "serverIP" PROJECT ".ino.bin"  // [OtaUrl]

**Comment by davidelang** [comment]
It needs to match whatever the files are named on the server. The Arduino IDE 
likes to name them .ino.bin, but if you have them named just .bin on the server, 
use that in the config.
