### ISSUE TITLE
PWM for 3 channels via MQTT at same time

### ISSUE THREAD

**Issue by egs2003** [arendst/Sonoff-Tasmota#4901]
I need to submit pwm values via mqtt at the same time. If I use the backlog topic, there is a delay between each command.

**Comment by egs2003** [comment]
But I can see it. I use PWM1 to 3 for the colors RGB. If I use the backlog I can see each setting of the color. For example the LED stripe is off. So I send via backlog all three PWM RGB values (1023). The LED stripe will show first red then yellow and then white. I dont'T want to use the color comand cause of the rounding failure.

**Comment by ascillato2** [comment]
Ok, sorry. That is not supported.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by egs2003** [comment]
this was an feature request!
