### ISSUE TITLE
Dimmer options for a lamp

### ISSUE THREAD

**Issue by speedyrazor** [arendst/Sonoff-Tasmota#4911]
Hi, I have a few Sonoff Basics wired for my main lights, but I also have a room lamp with a Tungsten Halogen Floodlight bulb, which currently has a standard analogue turning dimmer, so is a working dimmer. I would like to automate this with a in-line controller (something like a Sonoff Basic or simular), what are my options, open to suggestions.
Regards.

**Comment by ascillato2** [comment]
Hi, 

Please, address this to the Tasmota Support Chat. Github issues are for bug reporting. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
