### ISSUE TITLE
sonoff pow uses.

### ISSUE THREAD

**Issue by terryrow** [arendst/Sonoff-Tasmota#492]
Can the sonoff pow switch a remote sonoff th 16 using the "max power" variable?
This is not available using current Itead firmware/app.
My aim is to charge my electric car via a socket, switched on by sonoff 16, when the solar panel power exceeds a threshold Kw level then off when Kw drops to a lower level with some sort of hysteresis delay to avoid too frequent switching.

**Comment by davidelang** [comment]
no, the max power type of stuff only works on the local device. You can 
implement this sort of logic using your home automation software.
k

**Comment by terryrow** [comment]
Thanks, these micro processors are a totally new area for me. The code I saw seemed to have the watts , amps, max power as variables in an If statement so I assumed it would be possible to send a wireless "switch on" to a relay if watts>123.. 
I originally looked to use a current loop, transistor amp and solid state relay but the cost of parts made it a none starter compared to sonoff items. The current loop option is still preferred to breaking into the solar cable, especially as the sonoff connectors are so miserable.
Do you have any detailed suggestions as to how I can achieve monitoring the power and wirelessly switching on a relay? Please bear in mind I have no knowledge of these systems.
Thanks againTerry Rowland. 

    On Saturday, June 3, 2017 6:19 PM, David Lang <notifications@github.com> wrote:
 

 no, the max power type of stuff only works on the local device. You can 
implement this sort of logic using your home automation software.
k

**Comment by davidelang** [comment]
http://docs.openhab.org/tutorials/beginner/rules.html
http://www.homeautomationforgeeks.com/openhab_rules.shtml

the second shows sending an e-mail when it gets hot, you can just as easily send 
any command and test the power rather than temp.

**Comment by terryrow** [comment]
Thanks David, I will go through those soon.
Cheers Terry Rowland. 

    On Saturday, June 3, 2017 10:45 PM, David Lang <notifications@github.com> wrote:
 

 http://docs.openhab.org/tutorials/beginner/rules.html
http://www.homeautomationforgeeks.com/openhab_rules.shtml

the second shows sending an e-mail when it gets hot, you can just as easily send 
any command and test the power rather than temp.
