### ISSUE TITLE
SerialSend4 & SerialSend5

### ISSUE THREAD

**Issue by GianCann** [arendst/Sonoff-Tasmota#4920]
I've a question.
Why SerialSend4 and SerialSend5 are not present in the Software Serial Bridge?

How can i send, via Serial Bridge, a string like this?:

txtStatus.txt="Some text" 

with 3 bytes **0xFF** at the end?

**Comment by GianCann** [comment]
I have the same necessity described here:
https://github.com/arendst/Sonoff-Tasmota/issues/3560

**Comment by ascillato2** [comment]
Issue #3560 reopened as you requested.
