### ISSUE TITLE
MQTT full topic change not saved

### ISSUE THREAD

**Issue by hvullu** [arendst/Sonoff-Tasmota#4922]
Hi there,

trying to change via webinterface the MQTT fulltopic. Any change is NOT saved and lost in the current release, in older releases works as expected.

Tried with a Goddess Mini RGB (as generic with PWMx assigned to the correct GPIO).

not working with:
Core-/SDK-Version | 2_4_2/2.2.1(cfd48f3) (self compiled)
(and the precompiled downloadable release file).

working with:
Core-/SDK-Version | 2_3_0/1.5.3(aec24ac9)

Thx.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

If you need further assistance please find us in the Tasmota Support Chat. Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
