### ISSUE TITLE
Sleep 255 or 250 docs say 2 things

### ISSUE THREAD

**Issue by ezraholm50** [arendst/Sonoff-Tasmota#4930]
Hello,

Playing around with the new dynamic sleep settings. Now i see this wiki page show the max of 255ms
`
To allow for power usage flexibility this value may also be increased to a value of up to 255 milliseconds which is very useful to reduce power and processing demand on non-time critical devices such as switches (which is what most of Sonoff-Tasmota is used for.)
`
https://github.com/arendst/Sonoff-Tasmota/wiki/Dynamic%20Sleep

And this one not mentioning 255 but 250. Also i cant set anything higher then 250 via console. 

https://github.com/arendst/Sonoff-Tasmota/wiki/Energy-Saving

I guess it should be updated? Just a small typo, but it cost me about 10 minutes of debugging why i couldn't set 255 ^^

Edit:

Also the old energy saving docs state that some readings of the Sonoff POW could be off using sleep.
How does the new dynamic sleep handle this? I couldn't make this up out of the docs.

`If your Sonoff needs to do something continuously, this will be affected. E.g. Sonoff LED will flicker and Sonoff POW will not be able to correctly total the energy consumption. Spot readings of power, voltage, etc. will however remain correct.`

This because of the logs showing LoadAVG: 999 when having `sleep 0 ` and `setoption60 1` 
Now i guess i have to turn it on, but i'd like correct totals.

`21:18:46 MQT: stat/fridge/STATUS11 = {"StatusSTS":{"Time":"2019-01-14T21:18:46","Uptime":"0T00:02:22","Vcc":3.203,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":999,"POWER":"ON","Wifi":{"AP":1,"SSId":"WaaromZoMoeilijk2","BSSId":"B0:4E:26:12:37:B4","Channel":1,"RSSI":84}}}`

**Comment by ascillato2** [comment]
It is 250ms.

Wiki Fixed. Thanks.

About the rest of sensors and devices with sleep:

If you use fixed sleep. You will see that goes to 0 automatically when using some devices like LED STRIP WS2812B. And also you will notice some lag on response if sleep if high.

If you use dynamic sleep you don't need to worry. It will be taken care automatically.

**Comment by ezraholm50** [comment]
Great, i'm using dynamic on all my 30+ devices with sleep 250. Should make a difference!
Thanks!

**Comment by ascillato** [comment]
Sleep 250 is very high. Remember that you can experience lag in response. The recommended is dynamic sleep to 50 (default).

With just sleep to 1 the energy consumption goes very low. Then going up from that value, it isn't too much the difference. Remember that the lower consumption is using core 2.3.0 or 2.5.0 (2.4.2 has a CPU sleep but it doesn't have WIFI sleep - The radio stays ON all the time)

**Comment by ezraholm50** [comment]
Great, will try 50, its laggy indeed. And im on 2.3, thanks for the tip.
