### ISSUE TITLE
Home Assistent displays devices after reboot as "off" when they are "on"

### ISSUE THREAD

**Issue by TheZoker** [arendst/Sonoff-Tasmota#4931]
**Describe the bug**
When I start Home Assistant, the status of the sonoff devices get's not updated (not even after 5 minutes). I used this automation to trigger the update:
```
- alias: Tasmota - Powerstate
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/state"
        payload: "" 
```

- [x] _Searched the problem in issues and in the wiki_
- [x] _Hardware used_ :  Sonoff S20
- [x] _Development/Compiler/Upload tools used_ : arduino
- [x] _If a pre-compiled release or development binary was used, which one?_ : sonoff.bin
- [x] _You have tried latest release or development binaries?_ : latest
- [x] _Provide the output of command_``status 0`` :
```
01:18:29 CMD: status 0
01:18:29 MQT: stat/ecklampe/STATUS = {"Status":{"Module":8,"FriendlyName":["Ecklampe Sonoff"],"Topic":"ecklampe","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":0,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
01:18:29 MQT: stat/ecklampe/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"2T22:52:02","StartupUTC":"2019-01-12T01:26:27","Sleep":50,"BootCount":30,"SaveCount":445,"SaveAddress":"F8000"}}
01:18:29 MQT: stat/ecklampe/STATUS2 = {"StatusFWR":{"Version":"6.4.1(sonoff)","BuildDateTime":"2018-12-24T14:41:00","Boot":6,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
01:18:29 MQT: stat/ecklampe/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Sparta-IoT",""],"TelePeriod":300,"SetOption":["00008009","558180C0","00000000"]}}
01:18:29 MQT: stat/ecklampe/STATUS4 = {"StatusMEM":{"ProgramSize":521,"Free":480,"Heap":17,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000809","0FDAE794","000383A0","23B617CE","00003BC0"]}}
01:18:29 MQT: stat/ecklampe/STATUS5 = {"StatusNET":{"Hostname":"ecklampe-1399","IPAddress":"192.168.180.33","Gateway":"192.168.180.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.180.1","Mac":"5C:CF:7F:79:A5:77","Webserver":2,"WifiConfig":5}}
01:18:29 MQT: stat/ecklampe/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.180.31","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_79A577","MqttUser":"florian","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
01:18:29 MQT: stat/ecklampe/STATUS7 = {"StatusTIM":{"UTC":"Tue Jan 15 00:18:29 2019","Local":"Tue Jan 15 01:18:29 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:38","Sunset":"17:20"}}
01:18:29 MQT: stat/ecklampe/STATUS10 = {"StatusSNS":{"Time":"2019-01-15T01:18:29"}}
01:18:29 MQT: stat/ecklampe/STATUS11 = {"StatusSTS":{"Time":"2019-01-15T01:18:29","Uptime":"2T22:52:02","Vcc":3.442,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":1,"SSId":"Flos-IoT","BSSId":"44:4E:6D:4C:70:CC","Channel":1,"RSSI":100}}}
```

**To Reproduce**

- Add tasmota device to HA via:
```
switch:
  - platform: mqtt
    name: "Ecklampe"
    state_topic: "stat/ecklampe/POWER"
    command_topic: "cmnd/ecklampe/POWER"
    availability_topic: "tele/ecklampe/LWT"
    state_value_template: "{{value_json.POWER}}"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
```
- Reboot HA
- Device is displayed as "off" even when it's "on"

**Expected behavior**
Display device as on if it's on

**Screenshots**
Device is on:
![screenshot_2019 01 15_01h22m49s_005_](https://user-images.githubusercontent.com/1368405/51149834-19ca5f00-1864-11e9-8763-8d1eeecb7e5c.png)
But displayed as off:
![screenshot_2019 01 15_01h22m32s_004_](https://user-images.githubusercontent.com/1368405/51149833-19ca5f00-1864-11e9-9e35-2169c4119f65.png)

BTW: The commands are different [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant-%E2%80%90-Manual-Config#tip-sync-power-state) and [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant#tip-sync-power-state)

`topic: "cmnd/sonoffs/state"` vs `topic: "sonoffs/cmnd/state"`

**Comment by ascillato** [comment]
You are right. You need that automation and that automation is explained in the wiki.

Also the difference you saw in the wiki is correct. The fulltopic is different if you config HA manually or by automatic discovery.

Sorry, there is no issue. In the wiki is explained all this.

**Comment by TheZoker** [comment]
@ascillato Thanks for the fast feedback. So I added my devices via the manual configuration and added the automation described above. Why does it not work then?

**Comment by ascillato2** [comment]
You can not use both, manual and automatic config. You need to choose one. The fulltopic is different. So, if you choose manual, check that your fulltopic is the same.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by TheZoker** [comment]
I don't want to use both. I just want to use manual configuration

**Comment by ascillato2** [comment]
check that your fulltopic is the same.

**Comment by TheZoker** [comment]
Since I use the manual configuration, I need to use `"cmnd/sonoffs/state"` and that is exactly what I use in my automation:
![screenshot_2019 01 15_02h12m53s_006_](https://user-images.githubusercontent.com/1368405/51151415-1686a180-186b-11e9-9ff5-4a23d7242f16.png)

This should be correct, right?

**Comment by ascillato2** [comment]
In the Tasmota webmenu go to mqtt config and check what is your fulltopic

**Comment by TheZoker** [comment]
Currently it's `%prefix%/%topic%/` (see screenshot above). Do I need to change that?

Sorry if these questions are obvious, but I'm completely new to tasmota and MQTT. Really appreciate the help!

**Comment by ascillato2** [comment]
Write the command grouptopic in the console to check that your grouptopic is sonoffs

**Comment by TheZoker** [comment]
Output: 
```
02:21:55 CMD: grouptopic
02:21:55 MQT: stat/ecklampe/RESULT = {"GroupTopic":"sonoffs"}
```

**Comment by ascillato2** [comment]
```yaml
- alias: Tasmota - Powerstate
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/state"
        payload: ""
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER2
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/POWER3  
```

**Comment by ascillato2** [comment]
You were right. We rearrange the wiki and that was taken out. Will correct the wiki. Thanks for reporting :+1:

**Comment by TheZoker** [comment]
Seems to work :) Thank you very much for the quick help!

**Comment by ascillato** [comment]
Great! Thanks for your testings and patience.
