### ISSUE TITLE
Inclusion of Dooya RF raw Protocol

### ISSUE THREAD

**Issue by nosaj66au** [arendst/Sonoff-Tasmota#4934]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._
No a new product
**Describe the solution you'd like**
I would like to have a driver included for Dooya Curtians/Blinds/ Sun Shade and window winders.

**Describe alternatives you've considered**
Yes nothing else really fits.

**Additional context**
This is a very simple and common blind controller around the world in fact I have found several other blind vendors using the mechs. http://www.dooya.com/index_en.php
My example is https://www.venetablinds.com.au/. There are also DIY mechs for people wanting to retrofitting.
 I have already written and tested the code for ESP8266 and just need it add in Tasmota, it requires no extra libraries and only uses ArduinoJSON. I will to do any the testing as required and will pass rights to the Tasmota team. The only hardware required is a 443 RF Tx connect to a single pin. It will enable programming of up to 15 blinds within a group and several thousand groups addresses are available. All with individual or group control of blinds. Command include up, down, stop and program.  Currently I use a JSON string to issues commands and does not have any feedback.

----------------------------------------------------------------------------------------------------
#include <ArduinoJson.h>
       
//Example input string
//device - Phyical name only
//group - any 24 bit number for blind groups 
//blind - 0 will control all blinds in the group / 1-15 single blind control
//action - 1 - 4 for commands

//{"device":"Blind","group":"0xA03407","blind":1,"action":1}

//Global Variables
int outPin = 4;   // pushbutton connected to digital pin 7
int last_delay =0;
String inputString = "";         // a String to hold incoming data

//Routine declarations
void activate(int64_t data);
void init_msg();
void send_bit(int state);

void setup() {
  pinMode(outPin, OUTPUT);  
  Serial.begin(9600);  // initialize serial:
  Serial.println("Ready");
  inputString.reserve(200); // reserve 200 bytes for the inputString:
}

void loop() {
  // print the string when a newline arrives:
   while (Serial.available()) {
    // get the new byte:
    char inChar = (char)Serial.read();
    // add it to the inputString:
    inputString += inChar;
    // if the incoming character is a newline, set a flag so the main loop can
    // do something about it:
    if (inChar == '\n') {
      StaticJsonBuffer<200> jb;
      JsonObject& root = jb.parseObject(inputString);
        
       if(root.success()){  
          String device = root["device"];
          String group = root["group"];
          int blind = root["blind"];
          int action = root["action"];

          //Serial.print("device - ");Serial.println(device); 
          //Serial.print("group - ");Serial.println(group);
          //Serial.print("blind - ");Serial.println(blind);
          //Serial.print("action - ");Serial.println(action);
          
          unsigned long group_num = strtol(group.c_str(), NULL, 16);
          int64_t msg = group_num;
          msg = msg << 16;         
          msg += 45056; //0xB
          blind = blind << 8;
          msg += blind; 
          
          //Serial.print("group dec - ");
          //char buffer[100];
          //sprintf(buffer, "%0ld", msg/1000000L);Serial.print(buffer);  
          //sprintf(buffer, "%0ld", msg%1000000L);Serial.println(buffer);
          
          switch(action){
            //DOWN
            case 1:{ 
              activate(msg + 51);
              break;
            }
            //STOP
            case 2:{ 
              activate(msg + 85);
              break;
            }
            
            //UP
            case 3:{ 
              activate(msg + 17);
              break;
            } 
            //P2
            case 4:{
              activate(msg + 204);
              break;
            }
          }
       inputString = "";
       }
    }
  }
}

void activate(int64_t data){
  //Send the Msessage 3 or more times to insure it not corupted by other 433 devices
  for(int m=0;m<3;m++){   
    init_msg(); //initilsation sequence
    //loop through all 40 bits of the protocol packet
    for(int b=40;b>0;b--){send_bit(bitRead(data,b-1));}
  }
}

void init_msg(){
  
  int prep_l = 8550; //8550
  int start_h = 4725; //4725
  int start_l = 1525; //1525

  digitalWrite(outPin, LOW);
  delayMicroseconds(prep_l - last_delay); 
  digitalWrite(outPin, HIGH);
  delayMicroseconds(start_h);
  digitalWrite(outPin, LOW);
  delayMicroseconds(start_l);
}

void send_bit(int state){
  int high_time, low_time;
  int short_b = 335; //335 
  int long_b = 715; //715
  
  if(state){ //True State
    high_time = long_b;
    low_time=short_b;
  }else{ //False State
    high_time = short_b;
    low_time=long_b;
  }
  //output to the transmiter 
  digitalWrite(outPin, HIGH);
  delayMicroseconds(high_time);
  digitalWrite(outPin, LOW);
  delayMicroseconds(low_time);
  last_delay = low_time;
} 
--------------------------------------------------------------------------------------------------------

**Comment by Jason2866** [comment]
It is a Open Source project. Feel free to do and make a PR.
We do like PRs :-)

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
