### ISSUE TITLE
Question: Irremoteesp8266 HVAC Tasmota Supported protocols

### ISSUE THREAD

**Issue by martinmatias** [arendst/Sonoff-Tasmota#4944]
- [X ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used :
- [ X] Hardware used : Wemos D1 Mini 
- [ ] If a pre-compiled release or development binary was used, which one? :
- [X ] You have tried latest release or development binaries? :
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE
```

Hi all. Into last Tasmota version (6.4.1), file IRremoteESP8266.h is modified from it original. Most of HVAC IR protocols are disabled. 
It is planned to enabled them all? Then, would be great if you let the user choose witch one to disable (to save memory). 
I'm not using yet since none of my 3 different HVAC are in the list IRremoteesp8266 library and I'm trying to add them, but need to know once I can make IRremoteesp8266 work with my HVAC.

Regards
Martin

**Comment by ascillato** [comment]
Sorry. It is not planned to be added.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
