### ISSUE TITLE
ability to use data elements of STATUS messages as data items to publish to Domoticz ie. RSSI

### ISSUE THREAD

**Issue by K1WIZ** [arendst/Sonoff-Tasmota#4945]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
Unable to write a rule to publish Wifi RSSI to domoticz/in

**Describe the solution you'd like**
It would be useful to use data elements in the STATUS message to publish select data items .ie RSSI, Battery, etc as values to a Domoticz IDX to domoticz/in over MQTT.   For example, I can send the value of A0 to an IDX over MQTT to domoticz/in and that works beautifully:

> on tele-analog#a0 do publish domoticz/in {"idx":421,"nvalue":0,"svalue":"%value%"} endon

**Describe alternatives you've considered**
ESPEasy is able to send RSSI as a sendable value to a custom domoticz object.  Would rather use Tasmota.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

Why you need this? RSSI is already sent to domoticz on every mqtt message.

**Comment by K1WIZ** [comment]
But it's not.   I'm sending the analog value of pin A0 by rule (IDX 421).   This is a water tank level sensor.   The unit is located near the fringe of the wifi network so I setup a second dummy custom sensor (IDX422) to display just the wifi signal over time.   (domoticz has awesome history graphs useful in troubleshooting and analysis).    Wifi is not sent to idx 421, so therefore I need a way to get the rssi data everytime telemetry fires.

My current rule:

> 02:37:49 MQT: tele/sonoff/INFO1 = {"Module":"Generic","Version":"6.4.1.8(sonoff)","FallbackTopic":"cmnd/DVES_01CD81_fb/","GroupTopic":"sonoffs"}
02:37:49 MQT: tele/sonoff/INFO2 = {"WebServerMode":"Admin","Hostname":"tank","IPAddress":"10.50.50.85"}
02:37:49 MQT: tele/sonoff/INFO3 = {"RestartReason":"Software/System restart"}
02:37:57 MQT: tele/sonoff/STATE = {"Time":"2019-01-16T02:37:57","Uptime":"0T00:00:14","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"Wifi":{"AP":1,"SSId":"MIND CONTROL BG","BSSId":"0E:EC:DA:38:D5:8A","Channel":1,"RSSI":98}}
02:37:57 MQT: tele/sonoff/SENSOR = {"Time":"2019-01-16T02:37:57","ANALOG":{"A0":1024}}
02:37:57 RUL: TELE-ANALOG#A0 performs "publish domoticz/in {"idx":421,"nvalue":0,"svalue":"1024"}"
02:37:57 MQT: domoticz/in = {"idx":421,"nvalue":0,"svalue":"1024"}

thanks.

**Comment by ascillato** [comment]
The rssi is sent with every idx like power on and the rest of the standards of domoticz Tasmota menu. Please, check domoticz driver code in Tasmota. It is sent along with batery level and other data.

**Comment by ascillato** [comment]
So, if you use a rule, it is no need to send those data that are being sent in the others idx.

**Comment by K1WIZ** [comment]
im sorry but I see no evidence that the rssi is being sent along with the primary sensor value (in this case analog pin A0).   I have other tasmota driven esp8266 located around the site and no rssi data is visible from them on domoticz either.   they are all talking to Domoticz via my broker and here's what I see on the broker for topic domoticz/in:

> {"idx":193,"nvalue":0,"svalue":"10.2","Battery":38,"RSSI":3}
{"idx":404,"nvalue":0,"svalue":"14.1;32.4;2","Battery":46,"RSSI":5}
{"idx":377,"nvalue":0,"svalue":"20.9"}
{"idx":403,"nvalue":0,"svalue":"24.3;19.0;2","Battery":46,"RSSI":7}
{"idx":405,"nvalue":0,"svalue":"","Battery":38,"RSSI":7}
{"idx":380,"nvalue":1,"svalue":"","Battery":85,"RSSI":7}
{"idx":420,"nvalue":0,"svalue":"-2.4;66.7;1","Battery":45,"RSSI":6}
{"idx":372,"nvalue":0,"svalue":"22.6","Battery":40,"RSSI":4}
{"idx":382,"nvalue":0,"svalue":"0;5811.1","Battery":85,"RSSI":7}
{"idx":384,"nvalue":1,"svalue":"","Battery":88,"RSSI":5}
{"idx":421,"nvalue":0,"svalue":"1024"}

In the last line (this one being the tank sensor) the rssi is not sent because I had to use a rule to convince the esp8266 to send the raw value of the analog pin (A0).

**Comment by ascillato** [comment]
Yes, exactly, in a rule is not there, but in the rest of idx it is there as your log states:

{"idx":193,"nvalue":0,"svalue":"10.2","Battery":38,"RSSI":3}

So, there you have RSSI

That is why, there is no need to duplicate the information adding more information in a rule. It is already sent to Domoticz with the standards idx.

**Comment by ascillato2** [comment]
Could you use RSSI in domoticz from the standard messages?

**Comment by ascillato2** [comment]
Closing this issue as there is no feedback. When you have time, please tell us if you could configure your Domoticz to see the rssi from the standard idx messages. Thanks
