### ISSUE TITLE
too many decimal points in number

### ISSUE THREAD

**Issue by hmook** [arendst/Sonoff-Tasmota#4948]
Hi. 

I'am trying to update my Sonoff Basic but I am running in to an issue. When I hit update in Arduino IDE (on Mac) it looks like it's preparing and after a minute or so it gives me the following error:

`Arduino: 1.8.8 (Mac OS X), Board:"Generic ESP8266 Module, 80 MHz, Flash, Disabled, nodemcu, 26 MHz, 40MHz, DOUT, 1M (no SPIFFS), 2, v2 Higher Bandwidth (no features), Disabled, None, Only Sketch, 115200"

sonoff:29:10: error: too many decimal points in number
 Arduino: 1.8.8 (Mac OS X), Board: "Arduino/Genuino Uno"
          ^
sonoff:29:1: error: 'Arduino' does not name a type
 Arduino: 1.8.8 (Mac OS X), Board: "Arduino/Genuino Uno"
 ^
In file included from /Users/hmook/Downloads/Sonoff-Tasmota-6.4.1/sonoff/sonoff.ino:79:0:
settings.h:220:3: error: 'power_t' does not name a type
   power_t       power;                     // 2E8
   ^
settings.h:355:3: error: 'power_t' does not name a type
   power_t       power;                     // 2AC
   ^
sonoff:315:23: error: variable or field 'SetLatchingRelay' declared void
 void SetLatchingRelay(power_t lpower, uint8_t state)
                       ^
sonoff:315:23: error: 'power_t' was not declared in this scope
sonoff:315:47: error: expected primary-expression before 'state'
 void SetLatchingRelay(power_t lpower, uint8_t state)
                                               ^
sonoff:335:21: error: variable or field 'SetDevicePower' declared void
 void SetDevicePower(power_t rpower, int source)
                     ^
sonoff:335:21: error: 'power_t' was not declared in this scope
sonoff:335:37: error: expected primary-expression before 'int'
 void SetDevicePower(power_t rpower, int source)
                                     ^
sonoff:124:1: error: 'power_t' does not name a type
 power_t power = 0;                          // Current copy of Settings.power
 ^
sonoff:125:1: error: 'power_t' does not name a type
 power_t blink_power;                        // Blink power state
 ^
sonoff:126:1: error: 'power_t' does not name a type
 power_t blink_mask = 0;                     // Blink relay active mask
 ^
sonoff:127:1: error: 'power_t' does not name a type
 power_t blink_powersave;                    // Blink start power save state
 ^
sonoff:128:1: error: 'power_t' does not name a type
 power_t latching_power = 0;                 // Power state at latching start
 ^
sonoff:129:1: error: 'power_t' does not name a type
 power_t rel_inverted = 0;                   // Relay inverted flag (1 = (0 = On, 1 = Off))
 ^
sonoff:315:23: error: variable or field 'SetLatchingRelay' declared void
 void SetLatchingRelay(power_t lpower, uint8_t state)
                       ^
sonoff:315:23: error: 'power_t' was not declared in this scope
sonoff:315:47: error: expected primary-expression before 'state'
 void SetLatchingRelay(power_t lpower, uint8_t state)
                                               ^
In file included from /Users/hmook/Documents/Arduino/libraries/NeoPixelBus-2.2.9/src/NeoPixelBus.h:60:0,
                 from /Users/hmook/Downloads/Sonoff-Tasmota-6.4.1/sonoff/xplg_ws2812.ino:25:
/Users/hmook/Documents/Arduino/libraries/NeoPixelBus-2.2.9/src/internal/NeoBitmapFile.h:30:22: error: expected declaration before end of line
 #pragma pack(push, 2)
                      ^
exit status 1
too many decimal points in number

Dit rapport zou meer informatie bevatten met
"Uitgebreide uitvoer weergeven tijden compilatie"
optie aan in Bestand -> Voorkeuren.
`

Love to hear what is going wrong.

BR, Hanno

**Comment by ascillato2** [comment]
Please, for support use the Tasmota Support Chat. Github issues are for bug reporting. Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
