### ISSUE TITLE
Help on Rule for MQTT message on sensor new value

### ISSUE THREAD

**Issue by makejoint** [arendst/Sonoff-Tasmota#4958]
Dear all, I'm quite new on rules. I need a bit of help. I'm trying to publish a MQTT message  as soon as my I2C sensor has an updated temperature value (different from the last measured). I'm using this rule, but it triggers a MQTT message every second... 

`Rule1 on var1 do publish stat/sonoff-WZ-fan/TEMPERATURE %value% endon on SHT1X#Temperature do var1 %value% endon`

So the first part would publish the value of `var1`in case of a update of its value, while the second `on` pushes the actual value of the I2C sensor to `var1`. 

The output is then 
```
01:05:53 MQT: stat/sonoff-WZ-fan/RESULT = {"Var1":"23.0"}
01:05:55 RUL: SHT1X#TEMPERATURE performs "var1  23.0"
01:05:55 MQT: stat/sonoff-WZ-fan/RESULT = {"Var1":"23.0"}
01:05:57 RUL: SHT1X#TEMPERATURE performs "var1  23.0"
01:05:57 MQT: stat/sonoff-WZ-fan/RESULT = {"Var1":"23.0"}
01:05:59 RUL: SHT1X#TEMPERATURE performs "var1  23.0"
01:05:59 MQT: stat/sonoff-WZ-fan/RESULT = {"Var1":"23.0"}
```

What am I missing? Do I need to use two variables?

---------------------------------------
P.S. a cool thing would also be to have openhab/homeassistant's rules for sonoffs automatically translated into tasmota as decentralized control. If home automation server crashes, then a minimal set of sensors/rules/actuators shall continue working autonomously, without having to translate each rule into Tasmota and viceversa. This is just an idea, which require much more specs and use cases behind...

**Comment by Jason2866** [comment]
Take a look at this example
https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#8a-sending-the-value-of-a-sensor-to-mqtt-only-when-a-delta-is-reached

**Comment by safadi63** [comment]
I am using the following rule, and it is working for me.

**Rule1 on tele-DS18B20#Temperature do var1 %value% endon on DS18B20#Temperature>%var1% do backlog var1 %value%; publish stat/NodeMCU/temp %value%; var2 %value%; endon on DS18B20#Temperature<%var2% do backlog var2 %value%; publish  stat/NodeMCU/temp %value%; var1 %value%; endon**

Note:
Replace the _**TOPIC**_ and **_SENSOR_** type to match what you have.

To reduce the number of **MQTT** messeges, you can set the Maximum number of decimals (0 - 3) showing sensor Temperature.

**tempres 0**

Hope this will help you.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by makejoint** [comment]
thank you all 👍
