### ISSUE TITLE
Rule for one shot that does not retrigger for some time interval

### ISSUE THREAD

**Issue by mcsSolutions** [arendst/Sonoff-Tasmota#4959]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)  Tried chat also, but no response.
- [x ] Development/Compiler/Upload tools used : Platform IO / Atom
- [ x] Hardware used : Sonoff S31
- [ X] If a pre-compiled release or development binary was used, which one? : 6.4.1.5
- [ x] You have tried latest release or development binaries? : recently downloaded release version
- [x ] Provide the output of command ``status 0`` :
```
17:48:48 CMD: status 0
17:48:48 MQT: DenHeater/STATUS = {"Status":{"Module":41,"FriendlyName":["Den Heater"],"Topic":"DenHeater","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
17:48:48 MQT: DenHeater/STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"6T00:19:59","StartupUTC":"2019-01-11T00:28:49","Sleep":50,"BootCount":12,"SaveCount":55,"SaveAddress":"F5000"}}
17:48:48 MQT: DenHeater/STATUS2 = {"StatusFWR":{"Version":"6.4.1.5(sonoff)","BuildDateTime":"2019-01-03T16:11:14","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
17:48:48 MQT: DenHeater/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["U","U"],"TelePeriod":300,"SetOption":["00008109","55A180C0","00000000"]}}
17:48:48 MQT: DenHeater/STATUS4 = {"StatusMEM":{"ProgramSize":452,"Free":548,"Heap":24,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":3,"Features":["00000809","0F802790","24000000","000000A6","000000C0"]}}
17:48:48 MQT: DenHeater/STATUS5 = {"StatusNET":{"Hostname":"DenHeater","IPAddress":"192.168.0.104","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"DC:4F:22:0A:F2:F9","Webserver":2,"WifiConfig":4}}
17:48:48 MQT: DenHeater/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.30","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0AF2F9","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
17:48:48 MQT: DenHeater/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 17 00:48:48 2019","Local":"Wed Jan 16 17:48:48 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"-07:00","Sunrise":"07:32","Sunset":"17:42"}}
17:48:48 MQT: DenHeater/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
17:48:48 MQT: DenHeater/STATUS10 = {"StatusSNS":{"Time":"2019-01-16T17:48:48","ENERGY":{"TotalStartTime":"2019-01-03T16:50:56","Total":16.330,"Yesterday":1.589,"Today":4.865,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":119,"Current":0.000}}}
17:48:48 MQT: DenHeater/STATUS11 = {"StatusSTS":{"Time":"2019-01-16T17:48:48","Uptime":"6T00:19:59","Vcc":3.438,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":2,"SSId":"U","BSSId":"78:8A:20:84:48:1D","Channel":11,"RSSI":92}}}
```

**(Please, remember to close the issue when the problem has been addressed)**

I am trying to wrap my head around some of the Tasmota rules concepts.  My initial need is with Sonoff S31 where I want to cycle the plug power 45 minutes after the plug senses power above 100.  I recognize  Rule 5 so this only occurs upon initial detection of the power level above threshold.  

It is possible that the power dips below 100 in the 45 minute interval so I need something to latch the occurrence of the initial measurement above 100 and use this latch state to set the ruletimer1 to 2700.  As timer counts down I can trigger the power off and then the power on as well as resetting the latch condition so ready for the next  45 minute rule execution.  

My initial try is with "rule1 on ENERGY#POWER>100 do var1 1 endon on var1=1 do ruletimer1 60 endon on rules#timer=5 do POWER1 OFF endon on rules#timer=1 do backlog POWER1 ON; var1 0 endon", but  never get past var1 being set to 1 in the console feedback.  

In a more general vane I do not understand why one would use the event command vs. just using a var as I have done in the above.  Is the event only evaluated once while the var=x always evaluated?  

With Rule 5 it seems the first trigger of the rule will obey the one shot  operation.  Since this rule has multiple triggers I do want them all to obey the one shot criteria, especially the var=1 trigger because I want the ruletimer only initialized once.

The wiki contains the following example for Set a variable:
  rule needed: on event#setvar1 do var1 %value% endon
  command: event setvar1=1
Why is the event needed to set a var to 1?  Other examples show a simple "var1 1" expression.

In the staircase timer example the following rule is used.  Is %value% always the trigger evaluation?
rule1 on button1#state do backlog power1 %value%; ruletimer1 600 endon on rules#timer=1 do power1 off endon

This help request is specific for a rule that serves my need for pulsing power after 45 minutes has elapsed since detecting power flowing through plug.  It also has components about rules that I do not yet understand.

**Comment by ascillato** [comment]
Hi,

Thanks for sharing your ideas. I don't think this is going to be added due to it can be solved this request with ruletimer command. 

The rules you post have syntax errors. Please check the wiki. 

As I understood what you want to achieve is that when the power reaches 100w to turn off the relay for 45 minutes and then turn on again. Right? Well the rules for that could be:

```
Rule1 1 
Rule1 4
rule1 on ENERGY#POWER>100 do backlog power1 0; ruletimer1 2700 endon on rules#timer=1 do POWER1 1 endon
```

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

If you need further assistant please find us in the Tasmota Chat. Github issues are for bug reporting. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato** [comment]
Ok, so, what you want is:

* If load>100 then wait 45min and then turn off for 1 second

After that, it can start all that again.

Is that correct?

**Comment by mcsSolutions** [comment]
Yes that is the correct scenario.  I am able to achieve this with three rules, but what I want to learn is how to achieve it with events and/or var.  I used three rules because I did not know how to use a second timer (ruletimer2) and detect the trigger which is rules#timer for the first timer.  What is the event for when the second timer counts down to 1?


rule1 on ENERGY#POWER>100 do backlog ruletimer1 2700; rule1 0; rule2 1; rule3 0 endon 
rule2 on rules#timer=1 do backlog POWER1 0; ruletimer1 5 endon on rules#timer=1 do backlog POWER1 1; rule1 0; rule2 0; rule3 1 endon
rule3 on rules#timer=1 do backlog POWER1 1; rule1 1 rule2 1; rule3 0 endon

**Comment by ascillato** [comment]
Ok. So for the requested behaviour:

>If load>100 W, wait 45min and then turn it off for 5 seconds and then turn it on again. 

One solution with rules could be:

```
Rule1 1
Rule1 On system#boot do var1 0 endon On Energy#Power>100 do event countdown=%var1% endon On event#countdown=0 do backlog var1 1; ruletimer1 2700 endon On rules#timer=1 do backlog power1 0; ruletimer2 5 endon On rules#timer=2 do backlog power1 1; var1 0 endon 
```

Hope this helps.

**Comment by mcsSolutions** [comment]
Good example.  I was able to see how the event is advantageous and how the rulestimer expression is not the timer count, but the timer number.

This issue can be closed.
