### ISSUE TITLE
BME680 compensation functions

### ISSUE THREAD

**Issue by brunofosi** [arendst/Sonoff-Tasmota#4964]
Is it possible to include in the command line the compensation functions that the [https://github.com/BoschSensortec/BME680_driver](url) uses?

> Regarding compensation functions for temperature, pressure, humidity and gas we have two implementations.
> 
> - Integer version
> - floating point version

**Comment by ascillato** [comment]
Hi,

Have you checked the BME680 library included in Tasmota? Seems that it is already there, isn't it?

**Comment by brunofosi** [comment]
well yes, the [](https://github.com/BoschSensortec/BME680_driver) library used, gots the compensation functions! but i think we need to compile the tasmota firmware whenever we need to compensate the sensor. maybe i got it wrong? I propose a way to compensate the sensor using the CLI or a GUI setting!

**Comment by ascillato2** [comment]
Great, thanks for sharing your ideas :+1: 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
