### ISSUE TITLE
Support for ACK over serial

### ISSUE THREAD

**Issue by fluppie** [arendst/Sonoff-Tasmota#4965]
**Have you look for this feature in other issues and in the wiki?**

Yes, here: https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#serial-bridge

**Is your feature request related to a problem? Please describe.**
The device I'm communicating with has 0x02 as startbit and 0x03 as stopbit. Implementing the stopbit is easy via SerialDelimiter 3. So that part is done. When you send a command, the device keeps sending (5 to 7 times) the answer. When you answer 0x06 after receiving, it will stop. So to save time/battery from the other device, an ACK function would be helpful.

**Describe the solution you'd like**
Like we have the SerialDelimiter function to cut off after for example, receiving 0x03, I want a ACK message back to the sender for example 0x06 so he stops sending the same message 5 to 7 times.

**Describe alternatives you've considered**
Ofcourse I could SerialSend 0x06 with Node-Red on receiving a new message. But I think it would be better to handle this within Tasmota.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi, 

Nice idea. This could be achieved with rules when the request https://github.com/arendst/Sonoff-Tasmota/issues/4942 be implemented.

Please, wait for that. Thanks.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by fluppie** [comment]
OK cool, so SerialReceived#data=0x03 do command SerialSend5 0x06 endon ?

**Comment by ascillato** [comment]
Yes, something like:

```
Rule on SerialReceived#data=0x03 do SerialSend5 0x06 endon
```

Just wait for that to be implemented ;)
