### ISSUE TITLE
Switch turns off after losing wifi connection.

### ISSUE THREAD

**Issue by sjev** [arendst/Sonoff-Tasmota#4968]
I have an issue with a switch turning off after a wifi reconnection. It was not possible for me to do fix it with changing powerretain parameter. 
I've removed the sonoff from Home Assistant, to make sure that the problem is located on the switch itself.
Configuration: Sonoff basic with Sonoff-Tasmota 6.4.1.8 

I'd appreciate some pointers on how to fix or work-around this issue.

```
08:58:54 MQT: stat/laders/RESULT = {"POWER":"ON"}
08:58:54 MQT: stat/laders/POWER = ON (retained)
09:01:20 MQT: tele/laders/STATE = {"Time":"2019-01-18T09:01:20","Uptime":"0T02:30:16","SleepMode":"Dynamic","Sleep":150,"LoadAvg":5,"POWER":"ON","Wifi":{"AP":1,"SSId":"fry","BSSId":"CC:5D:4E:91:1A:3C","Channel":4,"RSSI":52}}
09:02:00 MQT: tele/laders/UPTIME = {"Time":"2019-01-18T09:02:00","Uptime":"0T02:30:56"}
09:06:20 MQT: tele/laders/STATE = {"Time":"2019-01-18T09:06:20","Uptime":"0T02:35:16","SleepMode":"Dynamic","Sleep":150,"LoadAvg":5,"POWER":"ON","Wifi":{"AP":1,"SSId":"fry","BSSId":"CC:5D:4E:91:1A:3C","Channel":4,"RSSI":48}}
09:07:29 MQT: Attempting connection...
09:07:29 MQT: Connected
09:07:29 MQT: tele/laders/LWT = Online (retained)
09:07:29 MQT: cmnd/laders/POWER = 
09:07:29 MQT: stat/laders/RESULT = {"POWER":"OFF"}
09:07:29 MQT: stat/laders/POWER = OFF (retained)
09:10:27 MQT: Attempting connection...
09:10:27 MQT: Connected
09:10:27 MQT: tele/laders/LWT = Online (retained)
09:10:27 MQT: cmnd/laders/POWER = 
09:10:27 MQT: stat/laders/RESULT = {"POWER":"OFF"}
```

**Comment by Jason2866** [comment]
Please fill out the issue template.  `status 0` is needed !

**Comment by Yali0n** [comment]
Hi!

You can try
"wificonfig 5"

With this setup your sonoff wont restart at wifi-loss.

It also looks like you have some retained parameters set.

There is a great YouTube video how to fix this
    https://www.youtube.com/watch?v=31IyfM1gygo

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

If you need further assistant please find us in the Tasmota Chat. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by mr-varga** [comment]
I have the same problem, with some device, after wifi reconection the device turn off. Here is the log:
`01:01:52 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:01:52","Uptime":"0T00:10:12","UptimeSec":612,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":22,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"1E:E8:29:9D:7D:09","Channel":6,"RSSI":70,"Signal":-65,"LinkCount":1,"Downtime":"0T00:00:07"}}
01:01:52 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:01:52","Switch1":"ON"}
01:06:52 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:06:52","Uptime":"0T00:15:12","UptimeSec":912,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":24,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"1E:E8:29:9D:7D:09","Channel":6,"RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:07"}}
01:06:52 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:06:52","Switch1":"ON"}
01:11:52 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:11:52","Uptime":"0T00:20:12","UptimeSec":1212,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"1E:E8:29:9D:7D:09","Channel":6,"RSSI":70,"Signal":-65,"LinkCount":1,"Downtime":"0T00:00:07"}}
01:11:52 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:11:52","Switch1":"ON"}
01:16:52 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:16:52","Uptime":"0T00:25:12","UptimeSec":1512,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":45,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"1E:E8:29:9D:7D:09","Channel":6,"RSSI":70,"Signal":-65,"LinkCount":1,"Downtime":"0T00:00:07"}}
01:16:52 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:16:52","Switch1":"ON"}
01:21:52 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:21:52","Uptime":"0T00:30:12","UptimeSec":1812,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"1E:E8:29:9D:7D:09","Channel":6,"RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:07"}}
01:21:52 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:21:52","Switch1":"ON"}
01:26:52 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:26:52","Uptime":"0T00:35:12","UptimeSec":2112,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"1E:E8:29:9D:7D:09","Channel":6,"RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:07"}}
01:26:52 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:26:52","Switch1":"ON"}
01:31:52 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:31:52","Uptime":"0T00:40:12","UptimeSec":2412,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"1E:E8:29:9D:7D:09","Channel":6,"RSSI":68,"Signal":-66,"LinkCount":1,"Downtime":"0T00:00:07"}}
01:31:52 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:31:52","Switch1":"ON"}
01:35:43 WIF: Connecting to AP1 Mr-Varga_Admin Channel 13 BSSId 7E:8A:20:B7:F9:97 in mode 11n as lusala2...
01:35:45 MQT: Attempting connection...
01:35:45 MQT: Connected
01:35:45 MQT: tele/lusala2/LWT = Online (retained)
01:35:45 MQT: cmnd/lusala2/POWER = 
01:35:46 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:35:46","Uptime":"0T00:44:06","UptimeSec":2646,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":35,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"7E:8A:20:B7:F9:97","Channel":13,"RSSI":100,"Signal":-47,"LinkCount":2,"Downtime":"0T00:00:09"}}
01:35:46 MQT: stat/lusala2/RESULT = {"POWER":"OFF"}
01:35:46 MQT: stat/lusala2/POWER = OFF (retained)
01:35:46 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:35:46","Uptime":"0T00:44:06","UptimeSec":2646,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":29,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"7E:8A:20:B7:F9:97","Channel":13,"RSSI":96,"Signal":-52,"LinkCount":2,"Downtime":"0T00:00:09"}}
01:35:46 MQT: stat/lusala2/RESULT = {"Time":"2022-12-02T01:35:46","Uptime":"0T00:44:06","UptimeSec":2646,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":29,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"7E:8A:20:B7:F9:97","Channel":13,"RSSI":96,"Signal":-52,"LinkCount":2,"Downtime":"0T00:00:09"}}
01:35:46 MQT: stat/lusala2/STATUS11 = {"StatusSTS":{"Time":"2022-12-02T01:35:46","Uptime":"0T00:44:06","UptimeSec":2646,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":29,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"7E:8A:20:B7:F9:97","Channel":13,"RSSI":100,"Signal":-49,"LinkCount":2,"Downtime":"0T00:00:09"}}}
01:35:47 MQT: stat/lusala2/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:44:07","StartupUTC":"2022-12-01T23:51:40","Sleep":50,"CfgHolder":4617,"BootCount":50,"BCResetTime":"2020-04-05T18:07:11","SaveCount":1741,"SaveAddress":"F8000"}}
01:36:51 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:36:51","Uptime":"0T00:45:11","UptimeSec":2711,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"7E:8A:20:B7:F9:97","Channel":13,"RSSI":100,"Signal":-48,"LinkCount":2,"Downtime":"0T00:00:09"}}
01:36:51 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:36:51","Switch1":"ON"}
01:41:51 MQT: tele/lusala2/STATE = {"Time":"2022-12-02T01:41:51","Uptime":"0T00:50:11","UptimeSec":3011,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":31,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"7E:8A:20:B7:F9:97","Channel":13,"RSSI":100,"Signal":-49,"LinkCount":2,"Downtime":"0T00:00:09"}}
01:41:51 MQT: tele/lusala2/SENSOR = {"Time":"2022-12-02T01:41:51","Switch1":"ON"}`

And this is status0:
`01:46:25.201 CMD: status0
01:46:25.231 MQT: stat/lusala1/STATUS0 = {"Status":{"Module":1,"DeviceName":"lusala1","FriendlyName":["lusala1"],"Topic":"lusala1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"lusala1","SwitchMode":[5,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1,"InfoRetain":0,"StateRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T01:55:27","StartupUTC":"2022-12-01T22:50:58","Sleep":50,"CfgHolder":4617,"BootCount":60,"BCResetTime":"2021-08-02T10:51:52","SaveCount":2094,"SaveAddress":"F8000"},"StatusFWR":{"Version":"12.1.1(tasmota)","BuildDateTime":"2022-08-25T11:33:55","Boot":31,"Core":"2_7_4_9","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"401/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Mr-Varga_Admin","P9_Zsolt"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["40028029","0505C80001000600003C5A0A002800000000","00002280","00006000","00004000","00000000"]},"StatusMEM":{"ProgramSize":624,"Free":376,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashFrequency":40,"FlashMode":3,"Features":["00000809","8F9AC787","04368001","000000CF","010013C0","C000F981","00004004","00001000","54000020","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37,45,62","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"lusala1","IPAddress":"192.168.2.31","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer1":"192.168.2.1","DNSServer2":"0.0.0.0","Mac":"84:F3:EB:93:56:0B","Webserver":2,"HTTP_API":1,"WifiConfig":5,"WifiPower":17.0},"StatusMQT":{"MqttHost":"mrvarga.duckdns.org","MqttPort":1883,"MqttClientMask":"lusala1","MqttClient":"lusala1","MqttUser":"pi","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4},"StatusTIM":{"UTC":"2022-12-02T00:46:25","Local":"2022-12-02T01:46:25","StartDST":"2022-03-27T02:00:00","EndDST":"2022-10-30T03:00:00","Timezone":99,"Sunrise":"08:23","Sunset":"16:55"},"StatusSNS":{"Time":"2022-12-02T01:46:25","Switch1":"ON"},"StatusSTS":{"Time":"2022-12-02T01:46:25","Uptime":"0T01:55:27","UptimeSec":6927,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Mr-Varga_Admin","BSSId":"7E:8A:20:B7:F9:97","Channel":13,"Mode":"11n","RSSI":86,"Signal":-57,"LinkCount":1,"Downtime":"0T00:00:03"}}}`

The device in a Sonoff basic coneccted to Unifi access-point.
