### ISSUE TITLE
How to retrive whole Rule definition?

### ISSUE THREAD

**Issue by mkh595** [arendst/Sonoff-Tasmota#4969]
Rule can be up to 511 characters long but only 422 characters are displayed. Same result in console or http comand.
![rule](https://user-images.githubusercontent.com/30566575/51383621-3b547080-1b1a-11e9-97fc-4cebe5194a6c.PNG)
Is there way how to retrive whole definition? I need modify rule but don't want to lose part which is not displayed.

**Comment by arendst** [comment]
Use MQTT

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by mkh595** [comment]
It works.
Personaly I would prefere 5x 300ch rules instead of 3x 511.

Thank you.

**Comment by bod-bod** [comment]
Hi. Is this a valid solution yet (8.3.1)? The mqtt RESULT message is not complete too.
