### ISSUE TITLE
"Fake" Sonoff Touch, esp8285 solder pins

### ISSUE THREAD

**Issue by fh-cy** [arendst/Sonoff-Tasmota#4970]
Hi,

i bought a "Sonoff" touch on ebay and got a fake one, is it possible to flash tasmato on it?

Thanks for any help!

![img_20190117_230156](https://user-images.githubusercontent.com/44025374/51384539-ebc37400-1b1c-11e9-94d8-88a8bcde8014.jpg)

**Comment by ascillato2** [comment]
As it has esp8285 you can flash Tasmota to it. 

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
