### ISSUE TITLE
No Sonoff SSID broadcast annymore

### ISSUE THREAD

**Issue by Rockel83** [arendst/Sonoff-Tasmota#4975]
I'm not sure if it's allowed to ask for support this way. But did some google searches and did not find anny sollutions that fit my problem. So this platform seemed the best way looking for a solution (at least I hope).

to start with, I'm quite new to programming and Python etc. I'm trying to understand and figuring out some things, but a lot of things are still abracadabra for me :P

I've flashed a couple of Blitzwolf powerplugs (SHP2 & SHP6) folowing these instructions:
https://github.com/arendst/Sonoff-Tasmota/wiki/Hardware-Preparation
https://github.com/arendst/Sonoff-Tasmota/wiki/BlitzWolf-SHP2
https://github.com/arendst/Sonoff-Tasmota/wiki/BlitzWolf-SHP6

I used PL-2303HX chip to flash the newest Tasmota firmware a.t.m. (v6.4.1) using the "FlashESP8266" flashtool in Windows. Because Python looks still quite difficult for me at the moment.
Flashing went well for a couple of SHP2 and SHP6 powerplugs, and configured them via mqtt into Hass.io, and it's working pretty well!

This week I've recieved a new SHP6, and flashed it immediately with Tasmota. Flashing went well, but and I was able to connect it to the Sonoff SSID and configure it for my home network. But something seemed to be faulty (relays clicked 2-3 times verry quickly when switching it on the Sonoff web page). Couldn't figure out if it was a hardware or a software problem, so I deceided to flash it again.

Only this time, I forgot to disconnect the GPIO0 pin from ground when start flashing. But it was looking like it still transfered the firmware. But after reasembeling and power it up, I couldn't find the Sonoff SSID broadcast between the WIFI connections around here. Thought the device was really faulty.

I had another SHP6 laying around (with a broken housing) which I already had flashed with Tasmoto, and it was working. So I deceided to replace the housings, and switched the prints with the "faulty"one.
I played around a lot with it's settings already, so I thought it would be ok to flash it again.

And again, I made the mistake of removing the GPIO0 pin from the ground while flashing (yes, I felt quite stupid at that moment). But also couldn't find anny Sonof SSID broadcast annymore then. So I tried to reset it by holding the buton for 40 seconds, which seemed to work. But the Sonoff enveironment was quite diffrent then the one I was used to. Can't remeber exactly what I did or happend after that. But it's not responding annymore. I cant't find a broadcasting Sonoff SSID annymore, it's not connecting to my own network (çan't find it between the connected devices on my router) and it doesn't seem te reset annymore (holding buton over more then 40sec).

Is there anny way to solve this problem? Or did I just fried something because of forgetting to remove the GPIO0 pin when flashing?

Thanks in advance!

**Comment by ascillato** [comment]
Removing GPIO0 while flashing do nothing to the process. GPIO0 to GND is required before powering it up to ENTER in programming mode. After that, you can release GPIO0. By Flashing you can not brake the device (if you use 3.3v of course)

You need to follow the wiki in order to solve your issue.

You need to erase all flash with esptool.py (as explained in the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#esptool-usage)) and flash it again using the latest precompiled bins from development branch (http://thehackbox.org/tasmota/)

If you need further support, please find us in the Tasmota support Chat (https://discord.gg/Ks2Kzd4) Github issues are for bug reporting. Thanks.

**Comment by Rockel83** [comment]
Thanks a lot for pointing me in the correct direction with that info!"
I was missing some basic fundamental information about using Python and ESPtool.py in Windows and was therfore  confused about how to use these commands.

But I got it working with your with erasing the memory, so thanks again!
