### ISSUE TITLE
adding tasmota to ifttt 

### ISSUE THREAD

**Issue by georgia088** [arendst/Sonoff-Tasmota#4977]
I am sure this is a really stupid question but how to I add a tasmota controlled device to ifttt?  I have flashed a sonoff basic with tasmota.  I can control it with via web interface and alexa/alexa app.  However, I would like to be able to create easy accessible push buttons on my phone to control multiple tasmota switches (using ifttt).  Please help.
THanks!

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by francwalter** [comment]
Possible to realise email commands to Tasmota as it is possible with IFTTT?

At the moment I use eWeLink over IFTTT with simple email commands to switch on or off my sonoff basic devices (costs only around 5.- euro) but since June 20 IFTTT is not anymore working for the free eWeLink services.

I use Google home too, but would best need some email commands for my use case.

Thanks for hints.
Frank

**Comment by Jason2866** [comment]
You can send emails with scripter. Read the documentation how it works

**Comment by ascillato** [comment]
You can send emails also using rules, but to enable emails, you need to uncomment the define in my_user_config.h and self compile.

If you need further assistant on that, please address this to the Tasmota support chat. Thanks

**Comment by juulg** [comment]
I don't know if this will help anyone but I have been trying for some time to have IFTTT toggle a Tasmota Flashed light bulb.  Every combination I could think of - then installed Wireshark and figured out the sequence from there. Attached is a screen Shot from IFTTT  - The IP address is my WAN address which is port forwarded to the IP address of the Tasmota flashed light bulb !! Works great !
![IFTTT and Tasmota](https://user-images.githubusercontent.com/43410557/110247333-c2067a80-7f39-11eb-96c9-79ef5831d9c7.png)
