### ISSUE TITLE
Xingg Model: W-DE004S

### ISSUE THREAD

**Issue by Arkadije** [arendst/Sonoff-Tasmota#4985]
HI all, 
I have Xingg WiFi Smar Socket Model: W-DE004S
I am wondering is it possible to flash Tasmota on it.
Product:
https://www.aliexpress.com/item/EU-European-Smart-Wi-Fi-Power-Plug-Socket-Outlet-Adapter-For-Amazon-Alexa-Echo-Google-Assistant/32850566772.html?spm=2114.13010708.0.0.3a994c4dZvZUk5

![img_20190120_134221](https://user-images.githubusercontent.com/4341856/51439456-9e7d0900-1cba-11e9-9f79-2bf0155d52d3.jpg)
![img_20190120_134421](https://user-images.githubusercontent.com/4341856/51439457-9e7d0900-1cba-11e9-80a5-636ee8949be1.jpg)
![img_20190120_134458](https://user-images.githubusercontent.com/4341856/51439454-94f3a100-1cba-11e9-9e5e-b6ba912e50c2.jpg)

**Comment by ascillato** [comment]
If it has an esp8266 may be it is possible. You should try. Remember to backup the original firmware.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato** [comment]
If you need further assistant please find us in the Tasmota Chat

**Comment by Arkadije** [comment]
Thanks for the fast reply.
I am new in all of this, trying to wrap my head around it. 
Flashed couple of Sonoff basic but that is about it.

Maybe it is nube question, but where I can find Chat?
