### ISSUE TITLE
Bug with MH-Z19B and Home Assistant

### ISSUE THREAD

**Issue by muuuh** [arendst/Sonoff-Tasmota#4992]
Hi,

there is a bug with MQTT, Home Assistant, Home Assistant MQTT Discovery and the MH-Z19B ([link](https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-MH-Z19B-CO2-Sensor#mh-z19b-co2-sensor-serial)).

It can be seen at the log files:

```
18:58:45 MQT: homeassistant/sensor/aaa_MHZ19_CarbonDioxide/config = {"name":"mhz MHZ19 CarbonDioxide","stat_t":"~SENSOR","avty_t":"~LWT","pl_avail":"Online","pl_not_avail":"Offline","unit_of_meas":" ","val_tpl":"{{value_json['MHZ19'].CarbonDioxide}}","uniq_id":"aaa_MHZ19_CarbonDioxide","device":{"identifiers":["aaa"],"name":"mhz","model":"Generic","sw_version":"6.4.1.8(sonoff)","manufacturer":"Tasmota"}, "~":"mhz/tele/"} (retained)

18:58:53 MQT: mhz/tele/SENSOR = {"Time":"2019-01-20T18:58:53","MHZ19B":{"CarbonDioxide":1619,"Temperature":25.0},"TempUnit":"C"}
```

The name of the json parameter is MHZ19, but the device name is MHZ19**B** (ending with B!). This results to Home Assistant not finding the correct json element which was announced and to 0 values.

Best regards,

**Comment by arendst** [comment]
Nice find.

The MHZ19 sensor can either be a MHZ19 or a MHZ19B. At restart init time the sensor is being forced as MHZ19 as it cannot be detected at that time as either MHZ19 or MHZ19B.

Once some reading has been taking from the device the correct version can be detected and the name might change to MHZ19B.

The problem with Hass detection is that it runs before the correct MHZ19 hardware version could be detected and you get the issue you noticed here. 

Delaying HASS discovery is not really a solution as one never knows when the correct MHZ19 is detected so if someone comes up with a solution the Hass community would be happy.

**Comment by arendst** [comment]
That's why I love this issue list.

**Comment by andrethomas** [comment]
> That's why I love this issue list.

I'm in a room that has < 410ppm :)

**Comment by arendst** [comment]
Problem is if I change the name to MHZ19 sec it will probably rain issues of people who had a MHZ19B configured in Node-Red, OpenHab,...

I think the easiest solution is to name all MHZ19 types just MHZ19B. MHZ19 is an "older" model and I hope not many people are using this...

**Comment by arendst** [comment]
Right. So I make it best of both worlds. I'll add the type field too and keep the name fixed at MHZ19B

**Comment by andrethomas2** [comment]
Closing this issue as commit https://github.com/arendst/Sonoff-Tasmota/commit/dcabb9c6dc1668209a6a770446253b79efbe1cc5 which was merged to development should solve this issue.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by muuuh** [comment]
Thank you! Works for me
