### ISSUE TITLE
Rules continuation of Issue 4959

### ISSUE THREAD

**Issue by mcsSolutions** [arendst/Sonoff-Tasmota#4994]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ x] Development/Compiler/Upload tools used : Atom/PlatformIO
- [ x] Hardware used :  S31
- [x ] If a pre-compiled release or development binary was used, which one? : 6.4.1.5
- [x ] You have tried latest release or development binaries? : yes
- [ ] Provide the output of command ``status 0`` :
```
17:56:13 CMD: status 0
17:56:13 MQT: DenHeater/STATUS = {"Status":{"Module":41,"FriendlyName":["Den Heater"],"Topic":"DenHeater","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
17:56:13 MQT: DenHeater/STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"10T00:27:24","StartupUTC":"2019-01-11T00:28:49","Sleep":50,"BootCount":12,"SaveCount":62,"SaveAddress":"F6000"}}
17:56:13 MQT: DenHeater/STATUS2 = {"StatusFWR":{"Version":"6.4.1.5(sonoff)","BuildDateTime":"2019-01-03T16:11:14","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
17:56:13 MQT: DenHeater/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["U","U"],"TelePeriod":300,"SetOption":["00008109","55A180C0","00000000"]}}
17:56:13 MQT: DenHeater/STATUS4 = {"StatusMEM":{"ProgramSize":452,"Free":548,"Heap":24,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":3,"Features":["00000809","0F802790","24000000","000000A6","000000C0"]}}
17:56:13 MQT: DenHeater/STATUS5 = {"StatusNET":{"Hostname":"DenHeater","IPAddress":"192.168.0.104","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"DC:4F:22:0A:F2:F9","Webserver":2,"WifiConfig":4}}
17:56:13 MQT: DenHeater/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.30","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0AF2F9","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
17:56:13 MQT: DenHeater/STATUS7 = {"StatusTIM":{"UTC":"Mon Jan 21 00:56:13 2019","Local":"Sun Jan 20 17:56:13 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"-07:00","Sunrise":"07:31","Sunset":"17:46"}}
17:56:13 MQT: DenHeater/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
17:56:13 MQT: DenHeater/STATUS10 = {"StatusSNS":{"Time":"2019-01-20T17:56:13","ENERGY":{"TotalStartTime":"2019-01-03T16:50:56","Total":21.510,"Yesterday":0.000,"Today":0.148,"Power":1812,"ApparentPower":1820,"ReactivePower":161,"Factor":1.00,"Voltage":113,"Current":16.079}}}
17:56:13 MQT: DenHeater/STATUS11 = {"StatusSTS":{"Time":"2019-01-20T17:56:13","Uptime":"10T00:27:24","Vcc":3.438,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":2,"SSId":"U","BSSId":"78:8A:20:84:48:1D","Channel":11,"RSSI":92}}}
17:56:15 MQT: DenHeater/STATE = {"Time":"2019-01-20T17:56:15","Uptime":"10T00:27:26","Vcc":3.438,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"ON","Wifi":{"AP":2,"SSId":"U","BSSId":"78:8A:20:84:48:1D","Channel":11,"RSSI":88}}
17:56:15 MQT: DenHeater/SENSOR = {"Time":"2019-01-20T17:56:15","ENERGY":{"TotalStartTime":"2019-01-03T16:50:56","Total":21.511,"Yesterday":0.000,"Today":0.148,"Period":109,"Power":1796,"ApparentPower":1825,"ReactivePower":324,"Factor":0.98,"Voltage":113,"Current":16.128}}
```

Issue 4949 was closed early due to misunderstanding of the question being asked.  The response was based upon the following use case:

As I understood what you want to achieve is that when the power reaches 100w to turn off the relay for 45 minutes and then turn on again. Right? Well the rules for that could be:

Rule1 1 
Rule1 4
rule1 on ENERGY#POWER>100 do backlog power1 0; ruletimer1 2700 endon on rules#timer=1 do POWER1 1 endon

The use case I am trying to achieve is to allow power to remain on for 45 minutes after it has been initially sensed that the load was drawing more than 100 watts.  After 45 minutes then provide a short pulse on the power.  The rule should then be reactivated looking for then next 100 watt utilization. During that 45 minute interval the sensed power will vary depending upon what is happening with the load.  Sometimes over 100 watts.  Sometimes under 100 watts.  Note that for this use case the activation of a load is done remotely and through mechanism independent of the power state of S31.  The S31 needs to have power on when the remote activation occurs.  The pulse at the end of 45 minutes is used to reset the device that is powered through the S31

If I use Rule 1 then ruletimer1 is set to 2700 many times and never gets the chance to count down to mark the 45 minutes period.

If I use Rule 5 (one shot) then ruletimer1 again gets set to 2700 often as the wattage dips below and then above 100 watts (i.e. one shot is retriggered).

It seemed to me that a var would need to be used to inhibit the retriggering of the one shot during the 45 minute ruletimer countdown.  It may need implementing the event command, but as much as I tried I could not understand how event works vs. just setting a var to a value.  While I have a specific use case I want to solve, I also want to get a better understanding of the approach to solving it so I can be better able to do similar rules in the future.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
There is no need to duplicate issue, let's continue your issue in the original https://github.com/arendst/Sonoff-Tasmota/issues/4959
