### ISSUE TITLE
Recurrent Hardware Watchdog Restarts

### ISSUE THREAD

**Issue by meingraham** [arendst/Sonoff-Tasmota#4995]
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- Development/Compiler/Upload tools used: TASMOTA OTA
- Hardware used: HW-655 w/ PZEM-004T
- If a pre-compiled release or development binary was used, which one?:
```
Program Version: 6.3.0.16(a516b25-sonoff)
Build Date & Time: 2018-12-09T18:24:40
Core/SDK Version: 2_4_2/2.2.1(cfd48f3)
```
- [ ] You have tried latest release or development binaries? Not yet. Trying to not introduce variables to my troubleshooting.
```
STATUS = {"Status":{"Module":18,"FriendlyName":["Power Monitor HW-655 PZEM"],"Topic":"PZEM_PowerMonitor","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":0,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/sonoff-sensors.bin","RestartReason":"Hardware Watchdog","Uptime":"1T02:16:52","StartupUTC":"2019-01-20T17:00:27","Sleep":25,"BootCount":53,"SaveCount":184,"SaveAddress":"FB000"}}
STATUS2 = {"StatusFWR":{"Version":"6.3.0.16(a516b25-sonoff)","BuildDateTime":"2018-12-09T18:24:40","Boot":6,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":2,"LogHost":"myHost","LogPort":514,"SSId":["mySSID",""],"TelePeriod":300,"SetOption":["00208108","559580C0","000000C0"]}}
STATUS4 = {"StatusMEM":{"ProgramSize":520,"Free":480,"Heap":16,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashMode":3,"Features":["00000809","0FDAE794","000383A0","23B617CE","00003BC0"]}}
STATUS5 = {"StatusNET":{"Hostname":"PZEM_PowerMonitor-8082","IPAddress":"192.168.1.nnn","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"myMAC","Webserver":2,"WifiConfig":4}}
STATUS6 = {"StatusMQT":{"MqttHost":"myHost","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_myMAC","MqttUser":"myUserID","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
STATUS7 = {"StatusTIM":{"UTC":"Mon Jan 21 19:17:19 2019","Local":"Mon Jan 21 14:17:19 2019","StartDST":"Sun Mar 10 02:00:00 2019","EndDST":"Sun Nov 03 02:00:00 2019","Timezone":99,"Sunrise":"07:32","Sunset":"17:43"}}
STATUS9 = {"StatusPTH":{"PowerDelta":0,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
STATUS10 = {"StatusSNS":{"Time":"2019-01-21T14:17:19","ENERGY":{"TotalStartTime":"2018-12-10T17:32:10","Total":23.483,"Yesterday":1.175,"Today":2.619,"Power":0.00,"ApparentPower":0.00,"ReactivePower":0.00,"Factor":0.00,"Voltage":121.70,"Current":0.000}}}
STATUS11 = {"StatusSTS":{"Time":"2019-01-21T14:17:19","Uptime":"1T02:16:52","Vcc":3.438,"SleepMode":"Dynamic","Sleep":25,"LoadAvg":39,"Wifi":{"AP":1,"SSId":"mySSID","BSSId":"myBSSIdMAC","Channel":1,"RSSI":52}}}
```

```
Jan  9 00:11:12: tele/PZEM_PowerMonitor/INFO3 = {"RestartReason":"Hardware Watchdog"}
Jan 14 21:05:17: tele/PZEM_PowerMonitor/INFO3 = {"RestartReason":"Hardware Watchdog"}
Jan 15 03:38:30: tele/PZEM_PowerMonitor/INFO3 = {"RestartReason":"Hardware Watchdog"}
Jan 15 22:52:44: tele/PZEM_PowerMonitor/INFO3 = {"RestartReason":"Hardware Watchdog"}
Jan 18 00:17:55: tele/PZEM_PowerMonitor/INFO3 = {"RestartReason":"Hardware Watchdog"}
Jan 20 12:00:35: tele/PZEM_PowerMonitor/INFO3 = {"RestartReason":"Hardware Watchdog"}
```

I don't see a pattern as to what might be causing this. I have looked at the logs to see if there was something logged that was similar each time and I can't spot a pattern. I have the SysLog level 2 log files (compressed) for these days if you would like for me to PM them to you to see if you can spot something relevant.

Thanks.

Mike

**Comment by arendst** [comment]
Check if you use software serial (at power up) and if so change to hardware serial by selecting the correct GPIOs. See Whats New for correct GPIO selection

**Comment by meingraham** [comment]
@arendst Theo,

This is what I have - [connection diagram](https://user-images.githubusercontent.com/34340210/51444410-2536e380-1cc5-11e9-8989-b181c2851863.png) and [Generic Module configuration](https://user-images.githubusercontent.com/34340210/51444596-6af4ab80-1cc7-11e9-82ca-8c34791e5f03.PNG) screenshots

Full write-up - https://github.com/arendst/Sonoff-Tasmota/wiki/US-240V-Clothes-Dryer-PZEM004T-Energy-Monitor

> if you use software serial (at power up)

At power up? I'm not sure I understand the question.

The device operates for long periods of time. I saw the restart reason when I was performing a `STATUS 0` a few days ago. That's when I implemented my syslog server to capture more information because the Hardware Watchdog restart doesn't happen that often.

Mike

**Comment by ascillato** [comment]
Hi, 

There isn't a clear bug. Could be a bad flashing, a defective device, a power source regulator issue. 

>You have tried latest release or development binaries? Not yet. Trying to not introduce variables to my troubleshooting.

As there isn't a clear bug, you should try latest version to see if your issue repeats. Also you should try another device also to avoid a defective hardware.

**Comment by arendst** [comment]
Right.

At power up I meant that there will be a message telling you if either Software or Hardware Serial is detected.

From your config it seems you are using software serial. Just swap both config GPIOS (do not swap cables) and it should start using hardware serial.

**Comment by meingraham** [comment]
@arendst @ascillato 

1. I'll give Theo's suggestion a try first for a few days to see if that resolves the issue. Theo - please confirm this is what you mean by "swap both config GPIOS".
![image](https://user-images.githubusercontent.com/34340210/51497531-672d5b80-1d91-11e9-92cb-4129ad70745d.png)
I will not swap the physical cables.
Current configuration
![image](https://user-images.githubusercontent.com/34340210/51497608-a065cb80-1d91-11e9-9c30-e8919603b01d.png)
I do not see any message on the web Console (weblog 4) at startup indicating that it has detected what type of serial connection (hardware or software) is present.

2. I will update the firmware on the ESP-01 (onboard module of the HW-655) to the latest development release. Depending on whether I have hardware or software serial will determine whether I use the 2.3.0 or 2.4.2 Core (I have better luck with 2.3.0 although this unit with 2.4.2 seems to keep a pretty good Wi-Fi connection).

3. I will take out the ESP-01 and erase the flash memory and flash the latest firmware.

4. I don't have any additional ESP-01 so I don't have the option to swap hardware. I'd have to order one.  As that's the module that is "Watchdog" restarting, I'm assuming that the HW-655 and the PZEM would not be the ones causing the issue. But I won't cross this bridge before I try a new ESP-01... which is a bridge way down the road for now.

Mike

**Comment by arendst** [comment]
Bullet 1 is hardware serial indeed.

If you restart with weblog set to 2 you could see:
```
00:00:00 Project sonoff Pzem (Topic pzem, Fallback DVES_0CA8BA, GroupTopic sonoffs) Version 6.4.0.1(sonoff)-2_4_2
00:00:00 SNS: Hardware Serial
00:00:00 WIF: Connecting to AP2 indebuurt2 in mode 11N as pzem...
00:00:04 WIF: Connected
00:00:04 HTP: Web server active on pzem with IP address 192.168.2.157
00:00:05 MQT: Attempting connection...
00:00:05 MQT: Connected
00:00:05 MQT: tele/pzem/LWT = Online (retained)
00:00:05 MQT: cmnd/pzem/POWER = 
00:00:06 MQT: tele/pzem/INFO1 = {"Module":"Sonoff Basic","Version":"6.4.0.1(sonoff)","FallbackTopic":"DVES_0CA8BA","GroupTopic":"sonoffs"}
00:00:06 MQT: tele/pzem/INFO2 = {"WebServerMode":"Admin","Hostname":"pzem","IPAddress":"192.168.2.157"}
00:00:06 MQT: tele/pzem/INFO3 = {"RestartReason":"Software/System restart"}
00:00:06 MQT: stat/pzem/RESULT = {"POWER":"ON"}
00:00:06 MQT: stat/pzem/POWER = ON
00:00:07 MQT: domoticz/in = {"idx":118,"nvalue":1,"svalue":"","Battery":88,"RSSI":7}
00:00:14 MQT: tele/pzem/STATE = {"Time":"1970-01-01T00:00:14","Uptime":"0T00:00:14","Vcc":3.490,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":29,"POWER":"ON","Wifi":{"AP":2,"SSId":"indebuurt2","BSSId":"00:22:6B:FE:8E:20","Channel":6,"RSSI":72}}
00:00:14 MQT: domoticz/in = {"idx":213,"nvalue":0,"svalue":"0;8964.0","Battery":88,"RSSI":7}
00:00:14 MQT: domoticz/in = {"idx":214,"nvalue":0,"svalue":"230.0","Battery":88,"RSSI":7}
00:00:14 MQT: domoticz/in = {"idx":215,"nvalue":0,"svalue":"0.000","Battery":88,"RSSI":7}
00:00:14 MQT: tele/pzem/SENSOR = {"Time":"1970-01-01T00:00:14","ENERGY":{"TotalStartTime":"2018-10-30T17:07:01","Total":8.964,"Yesterday":0.166,"Today":0.113,"Period":0.00,"Power":0.00,"ApparentPower":0.00,"ReactivePower":0.00,"Factor":0.00,"Voltage":230.0,"Current":0.000}}
```
Line 2 tells you it's using Hardware Serial.

**Comment by andrethomas** [comment]
@meingraham 

The first image is hardware serial - The MHZ19 Co2 sensor has similar issues with software serial insofar that it loses connectivity or sync and stops giving data to Tasmota (or Tasmota stops receiving it)

Configuring as per your first image is hardware serial, but yes - you need to swap the wires around also to correct the direction of communication to the PZEM module.

**Comment by meingraham** [comment]
@arendst - I just restarted it and went straight to look at the web log. No SNS message.
```
00:00:00 Project sonoff Power Monitor HW-655 PZEM (Topic PZEM_PowerMonitor, Fallback DVES_231F92, GroupTopic sonoffs) Version 6.3.0.16(a516b25-sonoff)-2_4_2
00:00:04 WIF: Connecting to AP1 mySSID in mode 11N as PZEM_PowerMonitor-myDVES...
00:00:08 WIF: Connected
00:00:08 DNS: Initialized
00:00:08 HTP: Web server active on PZEM_PowerMonitor-myDVES.local with IP address 192.168.1.nnn
15:50:37 MQT: Attempting connection...
15:50:37 MQT: Connected
15:50:37 MQT: tele/PZEM_PowerMonitor/LWT = Online (retained)
15:50:37 MQT: cmnd/PZEM_PowerMonitor/POWER = 
15:50:37 MQT: tele/PZEM_PowerMonitor/INFO1 = {"Module":"Generic","Version":"6.3.0.16(a516b25-sonoff)","FallbackTopic":"DVES_231F92","GroupTopic":"sonoffs"}
15:50:37 MQT: tele/PZEM_PowerMonitor/INFO2 = {"WebServerMode":"Admin","Hostname":"PZEM_PowerMonitor-8082","IPAddress":"192.168.1.nnn"}
15:50:37 MQT: tele/PZEM_PowerMonitor/INFO3 = {"RestartReason":"Software/System restart"}
15:50:45 MQT: tele/PZEM_PowerMonitor/STATE = {"Time":"2019-01-21T15:50:45","Uptime":"0T00:00:18","Vcc":3.438,"SleepMode":"Dynamic","Sleep":25,"LoadAvg":39,"Wifi":{"AP":1,"SSId":"mySSID","BSSId":"myBSSId","Channel":1,"RSSI":54}}
15:50:45 MQT: tele/PZEM_PowerMonitor/SENSOR = {"Time":"2019-01-21T15:50:45","ENERGY":{"TotalStartTime":"2018-12-10T17:32:10","Total":23.483,"Yesterday":1.175,"Today":2.619,"Period":0.00,"Power":0.00,"ApparentPower":0.00,"ReactivePower":0.00,"Factor":0.00,"Voltage":122.00,"Current":0.000}}
```

@andrethomas OK - the first image is the update Theo is suggesting... but he recommended **_NOT_** swapping the cables.

**Comment by meingraham** [comment]
Swapped the configuration. Did not swap the cables. I got the SNS message.

`00:00:00 SNS: Hardware Serial`

Don't seem to be getting any data... which says I likely DO need to swap Rx/Tx. Unfortunately, this is going to require some surgery as I've hot glued stuff inside the circuit box to keep it all from coming loose. I think I'll go back to software serial for now and live with the Watchdog restart... until I get some time to open that box up.

I'll close this issue for now and re-open when I make some progress on the hardware change.

Mike

**Comment by andrethomas** [comment]
> Theo is suggesting... but he recommended NOT swapping the cables

Could be I got that part wrong... it seemed logical that you would need to swap them but I did not study the code to confirm.

**Comment by meingraham** [comment]
> it seemed logical that you would need to swap them but I did not study the code to confirm.

Did to me too. And my tests seems to confirm it.

**Comment by arendst** [comment]
Mike did the correct assumption (as I did) that cable swap was not needed. But this seems only the case for versions before 6.3.0.3. Sorry.

As Mike does not receive any data he will have to swap the cables indeed.

**Comment by andrethomas** [comment]
@meingraham 6.3.0.3 puts you here https://github.com/arendst/Sonoff-Tasmota/tree/7418bb9b3d3bc5b614e274fc75aeaaae109a4eea if you want to download the zip and self compile - just ensure that you set a sleep value of at least 50 - 6.3.0.3 pre-dates dynamic sleep so it may run a little hot.

**Comment by andrethomas** [comment]
The last commit prior to 6.3.0.3 is here https://github.com/arendst/Sonoff-Tasmota/tree/9babeed46f3f3f442c8eb3f8d258a3b30c59e3b1

**Comment by meingraham** [comment]
Thanks all.

My options:
1. Avoid having to swap Rx/Tx by installing a version prior to 6.3.0.3
I'm not entirely clear on the software/hardware serial, 2.3.0/2.4.2 topic. If I choose to go the route of 6.3.0.3 (or earlier), and indeed end up with a hardware serial hookup, can I choose 2.3.0?
I've got a Sofie's choice to make. SetOption56/57 (6.3.0.10) really stabilized my connectivity issues.

2. Retain (or upgrade) current firmware and perform a surgical procedure on my device :grimacing: This gives me the option of future firmware upgrades when the next killer feature is released :grin:

I'm leaning toward option no. 2 but it'll be a while before I do it.

Mike

**Comment by es3nric** [comment]
Hi 
I have the same problem. Continous reboots (every 5 minutes) using Sonoff Basic + PZEM004  with Hardware Watchdog reason code.
`
Program Version | 6.4.1(sensors)
-- | --
2018-12-24T14:45:55
2_4_2/2.2.1(cfd48f3)
`
I erased and reflashed using serial. 
I would appreciate any help. As this is my very first message for support I apologize if I have not followed usage indications.

BR

**Comment by meingraham** [comment]
Try reversing the Tx/Rx GPIO assignments in the module configuration.

**Comment by es3nric** [comment]
Hi @meingraham 
I did and then sonoff does not read any value.

**Comment by meingraham** [comment]
To confirm, it has stopped boot looping; yes?

Also, be sure that serial logging is disabled (`SerialLog 0`).

It appears that the Sonoff Basic is receiving data from the PZEM (`SER: Received ...`). What kind of load to you have on the device?

**Comment by meingraham** [comment]
Perhaps try the latest development branch binary. Since you did erase and flash, you've followed the proper procedure to get it flashed. You should be able to get it to update using OTA since it remains booted for a few minutes. Here is the link to the latest development binary compiled with the 2.4.2 ESP Core.

http://thehackbox.org/tasmota/sonoff-sensors.bin

As for data readings, you'll need to put a decent electrical load on your circuit to determine whether the PZEM is functioning as it should.

Mike

**Comment by es3nric** [comment]
That works! I flashed over OTA the last compilation and I didn't have any reboot since yesterdat night.

Thank you very much!

**Comment by orimate** [comment]
Hi, I use several serial sensors on a wemos d1 mini (pms5003, sdm120, mhz19b).
mhz19b => hardware serial,
sdm120 and pms5003 => software serial.
I have to use software serial but after a few hours I get reset with reason: hardware watchdog.
Without error, the sofware serail will not work properly?
Thx

6.5.0 master Core: 2_5_2, SDK: 2.2.1

**Comment by andrethomas** [comment]
@orimate Most likely caused by one of the software serial devices. Try using one of the serial devices at a time to see which one is causing the reset.

**Comment by orimate** [comment]
@andrethomas 
I tried without sdm120 so mhz19b => hardware serial,
pms0005 => software serial. 
After a few hours rebooted with reason hardware watchdog. If I take hardware serial for pms0005, of course it is stable, but then for mhz19 I have to choose software serial. I'm doing a test today.

**Comment by andrethomas** [comment]
@orimate It has previously been determined that the mhz19 will not run for extended periods on software serial. It works initially but eventually stops reporting to Tasmota or Tasmota fails to receive the data correctly.

The same behaviour was experienced when the PN532 serial driver was developed.

I believe it has something to do with the way in which the sdk/core is handling the receive interrupts for software serial so it could be a number of reasons and perhaps something as simple as the serial buffer size being insufficient and causing a buffer overrun, or the sdk/core not disabling interrupts until the serial interrupt has been serviced... maybe an experiment would be to increase the polling frequency of the driver but that would result in a non standard implementation and not likely to be introduced here to mitigate a bug which possibly eminates from the sdk/core.

To explore it further you'd need to write a simple sketch that reproduces the problem and then ask the guys of the ESP8266 Arduino Core on github to look into it.

For my own sanity, I did not explore it further as it was a very intermittent bug making it so much more difficult to debug and it is much easier to just chuck in another wemos D1 mini to get a second hardware serial interface which I know will be reliable... when I say reliable I mean my Mhz19 installations run perfectly fine and I only restart the devices when firmware upgrades are applied.
