### ISSUE TITLE
Touch switch double tap

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#4996]
I have a sonoff basic with a touch switch configured as switch1.

Reading through the wiki it seems I cannot configure it as a button, so I can obtain the double tap feature.

What is the reason for this, or is it possible the config a switch to have the double tap feature?

**Comment by ascillato** [comment]
Hi, 

Why you can't configure your touch switch as a button?

**Comment by Lawrencezarb** [comment]
According to: https://github.com/arendst/Sonoff-Tasmota/wiki/Buttons-and-Switches

I can configure it as a button but must setoption13 to 1 = Enable button single press only for immediate response, when I need setoption13 to 0 = Enable button single, multi-press and hold

**Comment by ascillato** [comment]
Have you tried setoption13 to 0 (the default)?

You can try also setoption1

Seems that should work without any issue.

**Comment by ascillato2** [comment]
@Lawrencezarb 

Hi, any news on this?
I saw you were posting this issue all over internet.
Could you solve your issue?

**Comment by ascillato2** [comment]
Closing issue as there is no feedback.

**Comment by Lawrencezarb** [comment]
Sorry for the late reply. The solution was in fact to set the touch switch as a button. But the wiki indicated that I could not do this...
