### ISSUE TITLE
Tasmota 6.4.1. Rules and two DS18B20 sensors

### ISSUE THREAD

**Issue by avggolden** [arendst/Sonoff-Tasmota#4999]
Hi.
I have 2 DS18B20 sensors on wemos D1 mini, and want send info to mqtt when one or both of those sensors are disconnected. For understanding how rules works, i create simple rule like 
"rule1 on tele-DS18B20-1#Temperature do publish tele/pol/in {"idx":54,"svalue":"%value%"} endon"
and cannot get it working with "USE_DS18x20_LEGACY".
at config page i see two sensors named "DS18B20-1" and "DS18B20-2"

When i uncomment "USE_DS18x20" in my_user_config.h, i can get work only one sensor (when both connected i see no one), but rule "rule1 on tele-DS18B20#Temperature do publish tele/pol/in {"idx":54,"svalue":"%value%"} endon" starts work.

So, for me, this looks like i use wrong sensor name. Help me, plz.

**Comment by avggolden** [comment]
Ok. Got it working with "USE_DS18x20" (both sensors detected) on 6.4.0. firmware, so looks like there a bug in 6.4.1

**Comment by ascillato** [comment]
Hi,

This is a duplicated issue. https://github.com/arendst/Sonoff-Tasmota/issues/4906

Solution: use latest Tasmota version 6.4.1.9 (sonoff-sensor.bin)

Thanks

**Comment by ascillato2** [comment]
Please, let us know if you could make it work with latest version 6.4.1.9

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by avggolden** [comment]
Hi.
It works on 6.4.1.10 with USE_DS18x20, compiled for wemos d1 mini, but only when W1_PARASITE_POWER commented.
