### ISSUE TITLE
nodemcu active a check on gpio when reboot

### ISSUE THREAD

**Issue by misterita** [arendst/Sonoff-Tasmota#5002]
I use a nodemcu to control the relays and when it restart for any reason , for a few seconds it turns the relays on and off, I'd like to know  is it a nodemcu hardware check or something wrong in my configuration?
Tks

**Comment by Jason2866** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs#the-esp8266---hardware-more-info
The ESP cycles most GPIO pins at startup. It is not under control from Tasmota.
You can try GPIO 4 or 5. On these GPIO it should not happen.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by misterita** [comment]
tks
