### ISSUE TITLE
Sonoff nodemcu and Dynamic DNS 

### ISSUE THREAD

**Issue by misterita** [arendst/Sonoff-Tasmota#5008]
Does anyone know if there is a way to configure a dynamic DNS service directly from nodemcu-tasmota (duckdns,...)

**Comment by ascillato** [comment]
No, that task is for your router that knows the external IP

**Comment by ascillato2** [comment]
Please, for general questions you have the Tasmota Support Chat. Github issues are for bug reporting. Thanks 

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by misterita** [comment]
ah ok sorry
