### ISSUE TITLE
How compile the last version ?

### ISSUE THREAD

**Issue by aferraz** [arendst/Sonoff-Tasmota#501]
Hi @arendst,
 I can't compile the last version, I think the problem is the last esp8266 2.4.0-rc1 version.
How can I compile on Arduino ide ?

Thank you
 Alessandro

**Comment by arendst** [comment]
As you did with all previous versions. No need to switch to 2.4.0-rc1 yet.

**Comment by aferraz** [comment]
Hi @arendst,
 it true. I try yesterday night and I got a compile error.
Retry now and all go on.

Thanks
 Alessandro
