### ISSUE TITLE
Can't connect to Wifi with special characters in the password

### ISSUE THREAD

**Issue by andreas-bulling** [arendst/Sonoff-Tasmota#5010]
Hi,

I'm using the latest version of the firmware on a D1 mini but there seems to be a problem with special characters in the Wifi password.

Is this a bug or what is the recommended way of using passwords with characters like
=,:,\,+
?

**Comment by ascillato2** [comment]
Sorry, not supported by the Arduino core.

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by spock64** [comment]
No, the Arduino Core does support the use of "*" - if the password is set via a serial connection, it works. The bug is in how the web UI handles the password - and this is a recent issue as Tasmota was always happy with "*" before.
