### ISSUE TITLE
Sonoff Dual R2 - Problem with Relay #2

### ISSUE THREAD

**Issue by lm699** [arendst/Sonoff-Tasmota#5012]
Hello,
Thank in advance to your job.

I'm using Sonoff Dual R2 (version 1.4, 2018-06-27), and other dates in same versions.
I have flashed the Sonoff with Plateformio finely. But I have a problem when I would like start Relay 2. Relay 1 works.

Have you ever rencontred this problem ? Thank you

**Comment by ascillato** [comment]
Hi,

It is very difficult to know what is happening in your case as the troubleshooting template has not been completed.

Please, for support use the Tasmota Support Chat. Github issues are for bug reporting. Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
