### ISSUE TITLE
sonoff 4 ch pro switch automatically

### ISSUE THREAD

**Issue by Sonimeta** [arendst/Sonoff-Tasmota#5016]
hello to all, I have a sonch 4ch pro r2, after the update to tasmota 6.4.1 the relays are activated automatically without me doing anything, I do not use mqtt only wifi connection.
can you help me plese

**Comment by ascillato** [comment]
Please, for support, address this to the Tasmota Support Chat. Github issues are for bug reporting and with the template completed. Thanks.

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
