### ISSUE TITLE
Socket switches off at MQTT connection

### ISSUE THREAD

**Issue by WaJoWi** [arendst/Sonoff-Tasmota#5019]
I have the following problem with Tasmota 6.4.1.9 and 'gosund' SP1 sockets (v2.4):

With some sockets that are switched on and the MQTT is rebuilt for some reason, the socket is switched off.

The Tasmota log only contains the following information:
```
09:14:21 MQT: Connection attempt...
09:14:21 MQT: connected
09:14:21 MQT: tele/Socket_Aquarium/LWT = Online (maintained)
09:14:22 MQT: cmnd/socket_Aquarium/POWER = 
09:14:22 MQT: stat/Socket_Aquarium/RESULT = {"POWER": "OFF"}
09:14:22 MQT: stat/Socket_Aquarium/POWER = OFF
```

What could be the reason? Mistakes in the 'gosund' socket? Error in Tasmota?

**Comment by andrethomas2** [comment]
Closing this issue as it cannot be answered without the template being completed.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
