### ISSUE TITLE
add  the option to set/unset the retain flag for the LWT topic

### ISSUE THREAD

**Issue by iomax** [arendst/Sonoff-Tasmota#5021]
**Have you look for this feature in other issues and in the wiki?**
Yes.

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._
There seems to be no option to set the retain flag to the LWT topic 

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
add the option to define retain flag to the LWT topic like PowerRetain, ButtonRetain, SwitchRetain and/or SensorRetain.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**
 
Please evaluate the option to add the option to configure the retain flag  to the LWT topic or, be patient Tasmota newbie here, please address me to the right option to set it to false.

Thanks

**Comment by ascillato** [comment]
Hi,

By definition the LWT is a retained message to work. 

What is the use case of a non-retained LWT ? Why you need that?

**Comment by iomax** [comment]
LWT messages are keep into mqtt server db forever and, play around several cards / config / firmware, many "temporary", or in any case not more valid, "devices" will still give their state (  "offline" of course )  to every new clients that will subscribe someway the LWT topic ( e.g. subscribing to the "general" # topic ).
Not a special uses cases now but I'd like to think to it as a configurable option to better match the needs case by case.

**Comment by iomax** [comment]
You are right. The "problem" came when the devices will be definitively removed and not more connected due to whatever reason.
In this case, you still get "offline" info about it every time you will subscribing "#" topic.

**Comment by ascillato** [comment]
Ok. I understand. If you have a device that will not longer be part of your network, you have the old LWT.

So, the solution for that is to delete that retained message sending nothing to that topic and the broker will delete it. 

A LWT without retain is not doing its purpose. I think that adding that option will confuse people as it can't be used for normal use. Sorry.

Anyway, thanks for sharing your ideas :+1:
