### ISSUE TITLE
Interfacing the STM8S003 on a ESP-14 Module

### ISSUE THREAD

**Issue by wolfgangr** [arendst/Sonoff-Tasmota#5023]
The ESP-14 has a 8-bit STM8S003 processor built into the module.
https://www.esp8266.com/wiki/doku.php?id=esp8266-module-family#esp-14

The original design idea was to offer ESP8266-AT-command-WiFi support to the STM8 application.
So, the STM8 - despite much lower performance figures - was considered as master, the ESP as slave.

Why would we like an independent super-cheap-processor as a "master" which "abuses" tasmota as its interface?

- several analog inputs
- no inference with wifi timing and overcrowded arduino loop()
- independent access to timers, interrupts, GPIO...
- no inference with tasmota when writing application software
- it's the same that itead does on its RF bridge and many other manufacturers of serially controlled devices 
- it opens a new level of creativity for users without nuisancing tasmota maintainers with change requests in their build :-)

Itead labels the module as "expired", 
https://www.itead.cc/esp-14.html
but I hope that will not hinder clone manufacturers to supply it in the future.

The ESP-14 module goes for < EUR 3 at chinese sellers.
It has the same form factor than the ESP12, ESP07, ... and fits on common breakout adapters (so I hope)

The STM8 is reported to be in wide use on cheap consumer and DIY gadgets - cmp:
https://hackaday.io/project/16097-eforth-for-cheap-stm8s-gadgets
So the interface could as well be used to connect such a STM8 device to a "bare" module like the ESP-12.

Here 
https://hackaday.com/2017/02/13/hacking-on-the-weirdest-esp-module/
is a description for implementing forth on the STM8S003 of an ESP-14

This was the google-catcher how I found this, since I consider to run forth on an ESP8266. 
But sharing real estate (ram, timing, confguration, management) between tasmota and a language like forth that pretends to replace an operating system is .... close to a nightmare https://github.com/VerboteneZone/WESPOTA/issues/15

There are basically two level of support that tasmota as wifi gateway could supply to the STM8S003:
- interface of deployed application
- development interface

For a running application, I think the serial bridge functionality available in tasmota might suffice.
https://github.com/arendst/Sonoff-Tasmota/blob/e7e378f463bf9a3232506d671d1b85be5aad69bd/sonoff/xdrv_08_serial_bridge.ino
Maybe we'd like a remote reset, but I hope that can be implemented by just a GPIO pulled low.
I'll post the results as soon as I have tested it.

Of course it would ease the development in place if we were able to flash the STM8 over the air from the tasmota. 
The mechanism might basically be the same as implemented to flash the  EFM8BB1 chip on the Sonoff RF Bridge, as can be found here
https://github.com/arendst/Sonoff-Tasmota/blob/2e101839a457ead0bd6d4ede0856902000d3b65c/sonoff/xdrv_01_webserver.ino#L41
and here
https://github.com/arendst/Sonoff-Tasmota/blob/447ec6256eb6e277a350ea94a387e5c7755f5693/sonoff/xdrv_06_snfbridge.ino#L43
So I would favour a code reuse, which might, however, require some generalisation of the code alredy at hand.

I haven't found any pointers in the Wiki nor in others issues nor in the source - beyond the quoted RF bridge flasher.

Alternatively, I think it might be possible to flash the STM8 just over the serial connection, which remains to be checked.

**Comment by ascillato** [comment]
Sorry,

I don't understand your point. What do you want to achieve with the retired esp-14 module? There is no sonoff device with this chip.

**Comment by wolfgangr** [comment]
> it opens a new level of creativity for users without nuisancing tasmota maintainers

Let me drop some of my creative junk pile in front of you.

You know all those tiny arduino sensor examples?
Of course yo do:
https://github.com/arendst/Sonoff-Tasmota/tree/development/lib

I want to run some of them on my farm with two locations, several km apart.
Some of them maybe located out in the field, some maybe on mobile machinery.
My irrigator, e.g. requires control checks in 2...3 hrs intervals, 24/7 over 4 weeks - travel 7 km each time. That' real work

I had tried some of those arduino examples on my desk, with the arduino attached to the usb cable. 
Quick, handson and simple. But limited to the USB cable.
So the intranet/internet should replace the cable, and tasmota the USB-serial chip.
I thnik they call this idea IoT, don' they?

I had the network connection in place 4 yrs ago (well, had some pause due to an accident then...)
I even have own internet root server since that time.
I have an moquito runnnig and want to deply FHEM and zoneminder.
(have been lifted several times now)
Tasmota fits perfectly into that environment
 
With out of the box sonof devices I could cover half of my needs, with cheap multi-relay cards another quarter. But then it gets hard.
One challenge is a double.setpoint_control https://en.wikipedia.org/wiki/Double-setpoint_control
But this might be done with tasmota rules, I think

Next challenge is to position valves. 1.5" size in the heatings, 3" ... 4" in the irrigator.
I have motors, controlled by `arduino monster shield` DC driver, that could drive them.
Envisioning an arduino sketch for that job is easy. 
Throwing a mqtt-tls-syslog-http-capable interface upon them is hard work
This task I think begs for sth like the esp14

There are some control tasks that don't demand such short response times.
I copuld implement them in my favourite perl on the server.
But they should be self contained and continue working if the server/network is not available.
In search for an alternative, I found back to FORTH, the pet of my youth.
In the hackaday link posted, they have a FORTH running on the STM8 within a ESP14.

Remote control of the crop dryer.
Need a bunch of temp/homidity sensors, sense and switch some dozens of 220 V lines and relays.
Maybe a couple of cameras.
The PCF8574 multi-IO prototype is on my desk. The 8-channel 220V-sensing PCB is close to production. 
If it requests a little bit more programming than what is provided in tasmota, I could easily shift it to an independent processor.

> There is no sonoff device with this chip.

Got it. Shall I close the issue or will you do it?

**Comment by wolfgangr** [comment]
Sorry for my long answer to
> What do you want to achieve 

I think that should not be the primary question here.
The question here is whether there are enough **other people** who want to have such a thing, too.

**Comment by wolfgangr** [comment]
OTA flash of the STM8

**Comment by ascillato** [comment]
Ok. I don't know if that is possible. For that other pins should be also connected from the esp8266 to the stm for programming.
