### ISSUE TITLE
Sonoff Pow R2 v2.0 2018-06-11 wont flash

### ISSUE THREAD

**Issue by sash2k** [arendst/Sonoff-Tasmota#5033]
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used :
- [x] Hardware used : 
- [ ] If a pre-compiled release or development binary was used, which one? :
- [Y] You have tried latest release or development binaries? :
- [ ] Provide the output of command ``status 0`` :

Hi, i use an Arduino Uno CH240 with IDE to flash my sonoff devices (I flash 3xBasic 1xS20 without problems). But the Sonoff Pow R2 v2.0 2018-06-11 wont.

The Device is in Flash Mode (no blinking LED)
Test some Wire
Test 100 Ohm, 200 Ohm and 500 Ohm resistor VDD RX
Change RX/TX
Change 3,3 GND
Use Powersupply for Arduino

Serch on the Internet, but nothing usefull. I'm desperately

My Output from Arduino IDE:
trying to connect
flush start
setting serial port timeouts to 1 ms
setting serial port timeouts to 1000 ms
flush complete
espcomm_send_command: sending command header
espcomm_send_command: sending command payload
read 0, requested 1
trying to connect
flush start
setting serial port timeouts to 1 ms
setting serial port timeouts to 1000 ms
flush complete
espcomm_send_command: sending command header
espcomm_send_command: sending command payload
read 0, requested 1
trying to connect
flush start
setting serial port timeouts to 1 ms
setting serial port timeouts to 1000 ms
flush complete
espcomm_send_command: sending command header
espcomm_send_command: sending command payload
read 0, requested 1
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi

For support it is faster and better to address your flashing issue in the Tasmota Support Chat. 

Github issues are for bug reporting. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
