### ISSUE TITLE
Any help about “Fatal exception:0 flag:2"

### ISSUE THREAD

**Issue by jocas61** [arendst/Sonoff-Tasmota#5038]
00:29:37 MQT: tele/corredor1/INFO1 = {“Module”:“Sonoff Basic”,“Version”:“6.4.1(sonoff)”,“FallbackTopic”:“cmnd/DVES_321F0B_fb/”,“GroupTopic”:“sonoffs”}
00:29:37 MQT: tele/corredor1/INFO2 = {“WebServerMode”:“Admin”,“Hostname”:“LuzCorredor1”,“IPAddress”:“192.168.1.133”}
00:29:37 MQT: tele/corredor1/INFO3 = {“RestartReason”:“Fatal exception:0 flag:2 (EXCEPTION) epc1:0x40204513 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000”}
00:29:37 MQT: stat/corredor1/RESULT = {“POWER”:“OFF”}
00:29:37 MQT: stat/corredor1/POWER = OFF (retained)
00:29:45 MQT: tele/corredor1/STATE = {“Time”:“2019-01-25T00:29:45”,“Uptime”:“0T00:00:18”,“Vcc”:3.523,“SleepMode”:“Dynamic”,“Sleep”:50,“LoadAvg”:19,“POWER”:“OFF”,“Wifi”:{“AP”:1,“SSId”:“wirelessjc2”,“BSSId”:“E0:91:F5:A6:2F:FB”,“Channel”:6,“RSSI”:78}}
00:31:55 DNS: Initialized
00:31:55 MQT: Attempting connection…
00:31:56 MQT: Connected
00:31:56 MQT: tele/corredor1/LWT = Online (retained)
00:31:56 MQT: cmnd/corredor1/POWER =
00:32:58 MQT: Attempting connection…
00:32:58 MQT: Connect failed to 192.168.1.135:1883, rc -2. Retry in 10 sec
00:33:07 DNS: Initialized
00:33:18 MQT: Attempting connection…
00:33:18 MQT: Connected
00:33:18 MQT: tele/corredor1/LWT = Online (retained)
00:33:18 MQT: cmnd/corredor1/POWER =

**Comment by ascillato2** [comment]
Hi,

Please, for support find us in the Tasmota support chat. Github issues are for bug reporting. Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
