### ISSUE TITLE
Uploading last precompiled "sonoff.bin" on S.Touch from 5.11.1 to 6.4.1 Failed with message "Upload Failed Upload buffer miscompare"

### ISSUE THREAD

**Issue by ornolio** [arendst/Sonoff-Tasmota#5046]
Fail to Upgrade a Sonoff Touch running 5.11.1  with message:

_QUOTE_:
**Upload Failed 
Upload buffer miscompare**
_UNQUOTE_

using the precompiled Sonoff-Tasmota v6.4.1 released  on 24 Dec 2018 by the downloaded Github file "sonoff.bin"  

**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

**Describe the bug**
_A clear and concise description of what the bug is._

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [X ] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ :  Windows 7 PC + CHROME BROWSER  
- [X ] _Development/Compiler/Upload tools used_ : uploaded the Tasmota binary file using the option "Firmware Upgrade" on the Tasmota Web Interface 
- [ ] _If a pre-compiled release or development binary was used, which one?_ :latest 6.4.1 released this on 24 Dec 2018
- [ ] _You have tried latest release or development binaries?_ :yes latest 6.4.1 released  on 24 Dec 2018
- [ ] _Provide the output of command_``status 0`` :
```
STATUS 0 OUTPUT HERE - DO NOT DELETE THE MARKERS ABOVE AND BELOW THIS LINE
status 0
19:32:48 MQT: stat/riserva/STATUS = {"Status":{"Module":10,"FriendlyName":"Sonoff","Topic":"riserva","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":60,"SaveState":1,"ButtonRetain":0,"PowerRetain":1}}
19:32:48 MQT: stat/riserva/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","Uptime":0,"Sleep":50,"BootCount":11,"SaveCount":26,"SaveAddress":"FB000"}}
19:32:48 MQT: stat/riserva/STATUS2 = {"StatusFWR":{"Version":"5.11.1","BuildDateTime":"2019-01-27T19:07:43","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
19:32:48 MQT: stat/riserva/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"TIM-24084959","SSId2":"BTIM-24084959","TelePeriod":300,"SetOption":"00000029"}}
19:32:48 MQT: stat/riserva/STATUS4 = {"StatusMEM":{"ProgramSize":485,"Free":516,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3}}
19:32:48 MQT: stat/riserva/STATUS5 = {"StatusNET":{"Hostname":"riserva-6242","IPAddress":"192.168.1.224","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"60:01:94:85:38:62","Webserver":2,"WifiConfig":5}}
19:32:48 MQT: stat/riserva/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.77","MqttPort":1883,"MqttClientMask":"DVES_?X","MqttClient":"DVES_853862","MqttUser":"ornolio","MAX_PACKET_SIZE":512,"KEEPALIVE":15}}
19:32:48 MQT: stat/riserva/STATUS7 = {"StatusTIM":{"UTC":"Sun Jan 27 18:32:48 2019","Local":"Sun Jan 27 19:32:48 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":1}}
19:32:48 MQT: stat/riserva/STATUS10 = {"StatusSNS":{"Time":"2019-01-27T19:32:48","DS18B20":{"Temperature":23.3},"TempUnit":"C"}}
19:32:48 MQT: stat/riserva/STATUS11 = {"StatusSTS":{"Time":"2019-01-27T19:32:48","Uptime":0,"Vcc":3.221,"POWER":"OFF","Wifi":{"AP":1,"SSId":"TIM-24084959","RSSI":92,"APMac":"10:13:31:70:95:F3"}}}
```

**To Reproduce**
_Steps to reproduce the behavior:_
1)start with a S.Touch flashed with v. 5.11 
2)download the binary of latest version 6.4.1 on the windows PC
3)run the Tasmota web interface on the browser Chrome
4)apply option "Firmware Upgrade" of the main menu of Tasmota web interface
5)Select option "Upgrade by file upload" and select the binary file dowload at 2)
6)apply "Start Upgrade"

**Expected behavior**
_A clear and concise description of what you expected to happen._
to get at process end the notification: "UPGRADE COMPLETE" together with the "Sonoff-Tasmota 6.4.1 by Theo Arends" at footpage .

**Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/3440063/51805307-2ab79f00-226c-11e9-87a7-a1f7f39f0174.png)

**Additional context**
_Add any other context about the problem here._
5.11 Release has been installed using Arduino 1.6.14 on W.7 &  FT232RL FTDI USB To TTL Serial Converter Adapter Module For Arduino (which I used to flash several S.Touch to upgrade during 2017 & 2018. These S.Touch have been all upgraded to 6.14 by previous described procedure).
This S.Touch and 2 more have a working DS18B20 Temp. Sensor on GPIO1 port.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Thanks for completing the Template.

Anyway, github issues are for bug reporting. For support is way better to use the Tasmota Support Chat. There are bunch of great people there for helping you. Support is faster there. Thanks

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
