### ISSUE TITLE
OTA firmware not working after arduino IDE Flash

### ISSUE THREAD

**Issue by postaanerik** [arendst/Sonoff-Tasmota#5048]
Hi,

I'm having difficulties upgrading sonoff devices if they are initially flashed via the Arduino IDE
( flash size, flash mode, iWip are set correct )
The initial flash is successful (all functions working properly), but after a firmware upgrade the sonoff device is unresponsive, no LED, no serial out.

( when I flash using the ESPEasy tool with a Bin file there is no issue with OTA)

My new sonoff basic devices are delivered with esp8285 so I have to use the Arduino IDE

Any help is welcome.

Thanks,

Erik

**Comment by jziolkowski** [comment]
No, you don't have to use Arduino IDE to flash ESP8285. Esptool works fine. Follow these instructions:
https://github.com/arendst/Sonoff-Tasmota/wiki/Esptool

**Comment by ascillato** [comment]
May be you have flashed with a different memory map, so ota will not work. Please, follow the wiki.

If you need further assistant please find us in the Tasmota Support Chat. Github issues are for bug reporting. Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
