### ISSUE TITLE
sonoff_template.h:  RXD / TXD interchanged in comments?

### ISSUE THREAD

**Issue by indeed1** [arendst/Sonoff-Tasmota#5049]
Looks like RXD and TXD are mixed up in some comments of the module settings. (Only comments, so no real bug and no functional consequences.)

Very often I see comments like:

> // GPIO01 Serial RXD and Optional sensor
> // GPIO03 Serial TXD and Optional sensor

...and am confused. Shouldn't GPIO01 be TX and GPIO03 RX (from ESP's perspective), or where is my fallacy?

**Comment by andrethomas** [comment]
One way around it will be used as Software Serial and the other way around it will be used as Hardware Serial. So what you see is intentional.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
