### ISSUE TITLE
RF Bridge Send MQTT when Button is pressed

### ISSUE THREAD

**Issue by nmrds** [arendst/Sonoff-Tasmota#5060]
Probably this has a simple answer, but I didn't found the solution yet.

How can I set the RF Bridge to send the MQTT message when I press the button in the remote control and not only when I release the button?

Thanks

**Comment by ascillato** [comment]
That depends only on your rf remote control. If it sends a rf code after you release the button, is just how that remote control works. Nothing can be done from the receiver side if your transmitter do that. Sorry.

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
