### ISSUE TITLE
Anoopsyche JH-G01B1 modify S31 config

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#5066]
I have the same issue as per #5056. Following the instruction on that thread I tried to modify the S31 config in sonoff_template.h, but it had no effect.

I assume I am doing something wrong with the config.

Can someone point me in the right direction in what I need to change in sonoff_template.h.

The smart plug requires:

REL1 = GPIO14
Button1 = GPIO12
LED_INV - GPIO13

**Comment by Lawrencezarb** [comment]
Yes, but the Sonoff basic does not include energy monitoring, which the S31 does, and that part works out of the box.

**Comment by andrethomas** [comment]
Ah ok, then make the same changes on the S31.
```
  { "Sonoff S31",      // Sonoff S31 (ESP8266 - CSE7766)
     GPIO_KEY1,        // GPIO00 Button
     0,                // GPIO01 Serial RXD 4800 baud 8E1 CSE7766 energy sensor
     0,
     0,                // GPIO03 Serial TXD
     0, 0,
                       // GPIO06 (SD_CLK   Flash)
                       // GPIO07 (SD_DATA0 Flash QIO/DIO/DOUT)
                       // GPIO08 (SD_DATA1 Flash QIO/DIO/DOUT)
     0,                // GPIO09 (SD_DATA2 Flash QIO or ESP8285)
     0,                // GPIO10 (SD_DATA3 Flash QIO or ESP8285)
                       // GPIO11 (SD_CMD   Flash)
     GPIO_KEY1,        // GPIO12 Red Led and Relay (0 = Off, 1 = On)
     GPIO_LED1_INV,    // GPIO13 Green Led (0 = On, 1 = Off) - Link and Power status
     GPIO_REL1,        // GPIO14
     0, 0, 0
  },
```

**Comment by andrethomas** [comment]
Awesome, well done.

**Comment by andrethomas2** [comment]
Closing this issue as it will not be merged as a new template but a workaround is possible as an interim solution.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by loglux** [comment]
Is it possible to get a firmware release or code that would be working on ANOOPSYCHE JH-G01B1?

**Comment by loglux** [comment]
Many thanks for the config customisation code. I have managed to compile and flash it.

**Comment by blakadder** [comment]
It is now added as a [template](https://blakadder.github.io/templates/anoopsyche_JH-G01B1.html)

**Comment by loglux** [comment]
Great news! Thanks

**Comment by stevel23** [comment]
Apologies if I have made a mistake here but the template does not seem to work. When I apply it, the relay and led work correctly but the main menu on the device web page does not display any energy monitoring information as it does with the S31 - is this correct and how can I access the energy info. Thanks

**Comment by blakadder** [comment]
Which binary are you using?

**Comment by stevel23** [comment]
6.5.0(release-basic)

**Comment by meingraham** [comment]
You have flashed sonoff-basic.bin it appears. Flash sonoff.bin

**Comment by stevel23** [comment]
HI - Same issue I'm afraid - took latest sonoff.bin from https://github.com/arendst/Sonoff-Tasmota/releases. Information page now shows 6.5.0(release-sonoff). If I select S31 I get poower information but no working relay. If I apply and activate the JH-G01B1  template from https://blakadder.github.io/templates/anoopsyche_JH-G01B1.html  I get working relay but no power information.

**Comment by stevel23** [comment]
Hi - Did some playing around and I think I have fixed the issue it seems that in the template GPIO1 and GPIO3 are the wrong way round - to be specific if I change GPIO1 to CSE7766 TX (145) and GPIO3 to CSE7766 RX  (146) all seems to work OK. Thanks for your help

**Comment by blakadder** [comment]
I changed the template. Thanks for the research

**Comment by cflocke** [comment]
Hi - thanks a lot. These settings also worked for me for the JH-G01E Model!
