### ISSUE TITLE
Support of WiFi Electrical Blinds Switch Touch 

### ISSUE THREAD

**Issue by Wortex8** [arendst/Sonoff-Tasmota#5084]
Hello, is this item "[WiFi Electrical Blinds Switch Touch APP Voice Control Curtain Switch Glass Panel](https://www.ebay.com/itm/WiFi-Electrical-Blinds-Switch-Touch-APP-Voice-Control-Curtain-Switch-Glass-Panel/401651284329?ssPageName=STRK%3AMEBIDX%3AIT&var=671396285878&_trksid=p2057872.m2749.l2649)"  directly supported by Sonoff Tasmota?

I did not find any info, only 2 or 3 channel switch, but not directly this.

Thanks

**Comment by ascillato** [comment]
Hi,

Currently not supported. Sorry

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
