### ISSUE TITLE
busch jaeger free@home

### ISSUE THREAD

**Issue by martin072** [arendst/Sonoff-Tasmota#5085]
This is a question about Busch & Jaeger Free@Home. 

I noticed that the KNX protocol was implemented a while ago. Not really familiar with this, but my newly build home will come with a  Busch & Jaeger Free@Home system. I was told this is a branch of their industrial KNX system. It uses both a Bus system or wifi (can be combined). I cannot find any information about technical spec's / protocols for Free@home, so I was wondering if this might be compatible with KNX or if there is a way to implement this within tasmota?

**Comment by ascillato** [comment]
Tasmota supports KNX IP multicast protocol. So, as long as your devices also uses the same protocol, all should work fine.

**Comment by martin072** [comment]
Understood, but as mentioned I cannot really find any information if KNX devices are compatible with Free@home (I am not able to test this as the house is still being built)

**Comment by ascillato2** [comment]
As far as I could find using google, those are KNX devices.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
