### ISSUE TITLE
Is this variant of MagicHome "Led SPI Controller" flashable ?

### ISSUE THREAD

**Issue by fabito** [arendst/Sonoff-Tasmota#5087]
- [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [X] Hardware used : Magic Home Led SPI Controller

Hi, 

I just bought a MagicHome LED controller that seems different from the documented ones. It is very similar to [this one (reported in the espurna project)](https://github.com/xoseperez/espurna/issues/1437).
Check the pictures below:

![img_20190201_124521901](https://user-images.githubusercontent.com/308613/52131869-133e3480-2625-11e9-8567-8083d0b63941.jpg)
![img_20190201_124451780](https://user-images.githubusercontent.com/308613/52131878-189b7f00-2625-11e9-9e9a-cd168dee818f.jpg)

I tried flasshing following the ["variant without rx/tx pads"](https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-LED-strip-controller#variant-without-rxtx-pads) instructions without success.
Apparently I can't boot in flash mode.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by RomeyRome206** [comment]
> If you solder all needed cables on ESP Module it will work!
> https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-LED-strip-controller#variant-without-rxtx-pads
> Connect Power Supply AFTER you have made already the connection GND to GPIO0

FWIW, that method doe mot work on this variant. TX/RX are linked to the ARM chip on the backside. I could only flash it by removing the ESP module from the board completely, then soldering it back on.

**Comment by Chaot1** [comment]
> 
> 
> > If you solder all needed cables on ESP Module it will work!
> > https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-LED-strip-controller#variant-without-rxtx-pads
> > Connect Power Supply AFTER you have made already the connection GND to GPIO0
> 
> FWIW, that method doe not work on this variant. TX/RX are linked to the ARM chip on the backside. I could only flash it by removing the ESP module from the board completely, then soldering it back on.

I was able to flash tasmota on the item. But i can't find which GPIOs are assigned to the output.
Did you find it?

**Comment by LordDuplo** [comment]
Hi,

i have the same controller.
I have flashed Tasmota on it with success.
But i cant find the right config to run the strip.

Maybe we need to solder a wire from DAT Pin to ESP?

**Comment by golddragon007** [comment]
Hello,

I'm afraid that you can't run this without hardware modification because there's an ARM processor which fed by the ESP module. (https://github.com/Aircoookie/WLED/issues/398#issuecomment-597865330)

**Comment by RomeyRome206** [comment]
![0926456A-0F02-4BFB-A174-E46FC5FF927A](https://user-images.githubusercontent.com/7463136/83953488-b133a780-a7f5-11ea-8808-e36aa1159eb4.jpeg)

Remove these 2 resistors, or cut their leads & you’ll be able to flash it. Then run a jump wire directly to the led strip from whatever pin you use for data.

**Comment by golddragon007** [comment]
@RomeyRome206 hah, so I need to remove those two. Maybe I can do it. And then I connect directly the green wire with one of the ESP pins, right?
But the other guy why cut the first two pins leads of the ARM?

**Comment by RomeyRome206** [comment]
> But the other guy why cut the first two pins leads of the ARM?

It effectively does the same thing - Disables ARM communication.  ESP and ARM rx/tx are linked together with resistors probably doing pull up/down duties. I’m guessing when you try to flash the ESP, the commands probably go to the ARM and one, or both reply and fail. You don’t even have to Remove the resistors. Just run a razor across their leads going to the arm.

**Comment by golddragon007** [comment]
Removing the resistors did the trick, I was able to flash the boards after that.
