### ISSUE TITLE
Re-flashing Sonoff Dual, no user_config change

### ISSUE THREAD

**Issue by paco-ita** [arendst/Sonoff-Tasmota#509]
Hi everybody.
Since I had to change my Wi-Fi SSID, I decided to reflash my Sonoff Dual in order to push a new user_config.h with updated Network settings. Compiling and flashing with PlatformIO seem to work, but after rebooting Sonoff Dual still tries to connect to my old network.

Any advice?
Thanks

**Comment by davidelang** [comment]
see the troublehooting page on the wiki.
kkk

**Comment by paco-ita** [comment]
damn, that was easy! Sorry for wasting your time

Thanks!!
