### ISSUE TITLE
Inverting ON/OFF Leds on Sonoff Touch solution

### ISSUE THREAD

**Issue by Domo5785** [arendst/Sonoff-Tasmota#5092]
Soldering the switch LED where the Wifi LED is and than you can control the LED.
When you use the command Ledpower ON.
The Switch LED ist on all the time, even when the switch is off
So you can easy see and find the switch in the dark

![unbenannt](https://user-images.githubusercontent.com/47263019/52157768-158aa800-2692-11e9-8266-6775fec80c11.jpg)

hope that helps

**Comment by ascillato** [comment]
Great! Thanks for sharing. Please, could you be so kind to add this to the wiki.

Thanks a lot :+1:

**Comment by ascillato2** [comment]
This has been asked several times. Thanks for sharing this solution
