### ISSUE TITLE
TM1638 Json string output 

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#5095]
**Describe the bug**
Output for TM 1638 with Sensor and Status 8 is:
```
16:57:18 MQT: tele/sonoff/SENSOR = {"Time":"2019-02-02T16:57:18","Switch1":"ON","Switch2":"ON","Switch3":"ON","Switch4":"ON","Switch5":"ON","Switch6":"ON","Switch7":"ON","Switch8":"ON"}

```
```
16:51:49 CMD: status 8
16:51:49 MQT: stat/sonoff/STATUS8 = {"StatusSNS":{"Time":"2019-02-02T16:51:49","Switch1":"ON","Switch2":"ON","Switch3":"ON","Switch4":"ON","Switch5":"ON","Switch6":"ON","Switch7":"ON","Switch8":"ON"}}
```
Should be (to be like the others):
```

`{"StatusSNS":{"Time":"2019-02-02T16:51:49","TM1638":{"Switch1":"ON","Switch2":"ON","Switch3":"ON","Switch4":"ON","Switch5":"ON","Switch6":"ON","Switch7":"ON","Switch8":"ON"}}}
`
```

**Comment by arendst** [comment]
Will change

**Comment by Jason2866** [comment]
Ahh!

**Comment by jziolkowski** [comment]
But then, why does MPR121A return them nested? I get the switch/button difference, but shouldn't it be consistent?

 "MPR121A":{"Button0":0,"Button1":0,"Button2":0,"Button3":0,"Button4":0,"Button5":0,"Button6":0,"Button7":0,"Button8":0,"Button9":0,"Button10":0,"Button11":0,"Button12":0},"TempUnit":"C"}}

**Comment by arendst** [comment]
@jziolkowski those buttons have no relation with the default buttons.

The switches of tm1638 do have a direct relation to the default buttons. The switch json is legacy style.
