### ISSUE TITLE
Tuya devices

### ISSUE THREAD

**Issue by loglux** [arendst/Sonoff-Tasmota#5099]
The possibility to OTA Flash Tuya devices is a paydirt.
It would be very appreciated to give more possibility for support Tuya.
Along with Tuya-bases smart plug there is a plenty of choice for Smart Power Strips like [this](https://www.aliexpress.com/item/WIFI-smart-power-strip-UK-standard-with-4-wifi-plug-and-4-USB-port-Alexa-and/32970874011.html?spm=2114.search0104.3.319.359935ebJaOS1a&ws_ab_test=searchweb0_0,searchweb201602_2_10065_10130_10068_10547_319_317_10548_10545_10696_10192_453_10084_454_10083_10618_10307_10301_10821_537_536_10902_10059_10884_10887_321_322_10103,searchweb201603_6,ppcSwitch_0&algo_expid=85993e05-a11f-4298-b127-47b0f05982f1-46&algo_pvid=85993e05-a11f-4298-b127-47b0f05982f1)  or [here](https://www.amazon.co.uk/dp/B07N6268WS/?coliid=I2GM19X8NRIZ4X&colid=2LR78KS0N73LM&psc=0&ref_=lv_ov_lig_dp_it)  and [smart wall sockets](https://www.amazon.co.uk/dp/B07GBQJSHK/?coliid=ILF862BGFSYFB&colid=2LR78KS0N73LM&psc=1&ref_=lv_ov_lig_dp_it)

**Comment by andrethomas** [comment]
Your post reminds me of [The XY Problem](http://xyproblem.info/)

**Comment by andrethomas2** [comment]
Closing this issue as it does not contain any specific question, bug report, or feature request.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
