### ISSUE TITLE
How to use Hue emulation?

### ISSUE THREAD

**Issue by spants** [arendst/Sonoff-Tasmota#510]
I have a number of Hue lights, Alexa, Node Red, MQTT etc etc

I see that Tasmota supports Hue emulation. Does this mean that my H801 devices (with RGBW led strips) can behave as a Hub and attached coloured light?
Does it support RGB and separate white?
Does is support the 5050 led strips or is it the ws2812 type?....

Many thanks
Tony

**Comment by altelch** [comment]
Hi,

yes the ESP emulates a Hue bridge but only the minimal subset required 
to work with Alexa/Echo-Devices. I only developed  and tested with an 
WS2812 RGB type LED strip. Never tried 5050 or RGBW as I have none to 
play with.

Greetings,

     Heiko.


Am 07.06.2017 um 21:15 schrieb Tony Neal:

**Comment by spants** [comment]
Many thanks!. I would like to convert my H801 with Hue emulation using PWM for RGBW. I will take a look.

**Comment by zomars** [comment]
Are there any instructions in the wiki?
