### ISSUE TITLE
TM 1990A iButton reader

### ISSUE THREAD

**Issue by UweSeifert** [arendst/Sonoff-Tasmota#5102]
**Have you look for this feature in other issues and in the wiki?**
Yes.
I found nothing about the iButton reader.

**Is your feature request related to a problem? Please describe.**
It's an enhancement for using the tasmota software as a cheap door/access control entry based on low cost Tag ID.
Important: This reader is an 1-wire device which submits a unique id.

**Describe the solution you'd like**
select this reader in the web-ui and get an status message whenever an iButton was detected.

**Comment by Jason2866** [comment]
Device is not supported.
You can write a driver and make a PR

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
