### ISSUE TITLE
Sonoff bridge question. 

### ISSUE THREAD

**Issue by PMBonne** [arendst/Sonoff-Tasmota#5104]
I try to figure out how the bridge works. If I program the bridge to send a code like 584267, then I receive a code that are 08EA4B.. anyone that know what kind of code that are? Or how I can decide my own specific code?

**Comment by ascillato2** [comment]
Yes, you can receive and send simple codes in 433 mhz. 

If you need further information, please check the wiki at sonoff bridge. 
If you need further assistant please find us in the Tasmota Support Chat. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by Jason2866** [comment]
08EA4B (hex) = 584267 (dec)
