### ISSUE TITLE
Web password lost

### ISSUE THREAD

**Issue by SzilagyiR** [arendst/Sonoff-Tasmota#511]
How can I reset my Sonoff Touch, if I lost my password?

Thanks!

**Comment by arendst** [comment]
Enter command webpassword and enter a new password. 

Command can be entered serial or via mqtt server

**Comment by SzilagyiR** [comment]
I tried only HTTP command, thank I will try!

**Comment by davidelang** [comment]
hold down the button for 4 seconds will reset all configs to what was compiled 
in to user_config.h

if that doesn't work, and you can't connect via mqtt to reset the password, you 
will have to reflash the device.
k

**Comment by SzilagyiR** [comment]
How can I send the command via MQTT server?
I ran Mosquito on Raspberry Pi.

**Comment by SzilagyiR** [comment]
I make the reset procedure but after it not connet to the wifi. Now I reflash it but nothing happen, the led blinking and not connect to the wifi.
The AP settings correct in the  user_config.h.

**Comment by davidelang** [comment]
see the troubleshooting page to make sure that the settings from user_config.h 
get applied.
k

**Comment by SzilagyiR** [comment]
It says to change the value of CFG_HOLDER in user_config.h.
The default is 0x20161209, can I change it to anything?

**Comment by SzilagyiR** [comment]
I chang the last number to 6, reflash it and it's work fine!

Thanks for your help!

**Comment by davidelang** [comment]
yes, the only thing that matters is if it matches the prior value or not.

**Comment by cgatnet** [comment]
Helpful thread. -->Seems there was a typo in my password, so i failed to log into after securing the webfrontend. This thread lead me to the fix.
just pushed the button for 40s and the sonoff switched on/off, after that all my flashed settings were back. 
thanks for the great wiki and the helpful threads (and this great project, off course) 👍
