### ISSUE TITLE
admin privileges

### ISSUE THREAD

**Issue by baha00** [arendst/Sonoff-Tasmota#5110]
Hi there, I flashed tuya device OTA with Mocktuya cloud.
I added own module, modified sonoff s31, GPIO settings to work properly. BUT in my user config i setup weblogin as user not admin, so when I login with credentials only thing is monitoring or  wifi AP selection if I change network. Is there anything I can do or I need open and reflash device?
It is not responding to button commands.

**Comment by Jason2866** [comment]
If you cant configure anything (you disabled admin) the only way is a serial reflash.

**Comment by baha00** [comment]
@Jason2866
Thanks, I was assuming this will be an answer.

**Comment by baha00** [comment]
@Jason2866
Thanks, I was assuming this will be an answer.
