### ISSUE TITLE
rules not firing

### ISSUE THREAD

**Issue by jpadie** [arendst/Sonoff-Tasmota#5111]
I'm not seeing any rule output when running the following rule

rule1 on Switch3#state=0 do POWER1 on break on Switch2#state=1 do POWER1 off endon
GPIO14 is configured as switch3, TX as switch2
switchtopic2 and switchtopic3 are both set to 2

when I short GPIO14 to ground no rules are triggered.  ditto shorting/opening the TX pin (seriallog is disabled).

however on both events I can see that the sonoff is recognising the change in state and firing an mqtt command.

I know I could mimic the rules via a broker, but it is important that the system functions whether or not connected to the network.  so the rules need to be managed locally.

any help for pointers as to where I am going wrong would be useful.

thanks
Justin
 

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x ] Development/Compiler/Upload tools used : esptool
- [x ] Hardware used :  sonoff basic
- [x ] If a pre-compiled release or development binary was used, which one? : 6.4.1 sonoff-basic
- [x ] You have tried latest release or development binaries? :no
- [ ] Provide the output of command ``status 0`` :
```
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS = {"Status":{"Module":1,"FriendlyName":["RainWaterPump_Sensor"],"Topic":"rainWaterPump_Sensor","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"rainWaterPump_Sensor","SwitchMode":[1,3,3,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:52:34","StartupUTC":"2019-02-04T14:00:57","Sleep":50,"BootCount":278,"SaveCount":468,"SaveAddress":"F8000"}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS2 = {"StatusFWR":{"Version":"6.4.1(basic)","BuildDateTime":"2018-12-24T14:43:30","Boot":6,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["***********-UK","***********"],"TelePeriod":10,"SetOption":["00008009","558180C0","00000000"]}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS4 = {"StatusMEM":{"ProgramSize":445,"Free":556,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000809","0F082780","000083A0","21021706","000001C0"]}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS5 = {"StatusNET":{"Hostname":"rainWaterPump_Sensor-1040","IPAddress":"192.168.8.169","Gateway":"192.168.8.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.8.1","Mac":"DC:4F:22:0E:44:10","Webserver":2,"WifiConfig":2}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt.no3.co.uk","MqttPort":8883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_0E4410","MqttUser":"***2","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS7 = {"StatusTIM":{"UTC":"Mon Feb 04 14:53:31 2019","Local":"Mon Feb 04 15:53:31 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 01:00:00 2019","Timezone":99,"Sunrise":"08:06","Sunset":"18:06"}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS10 = {"StatusSNS":{"Time":"2019-02-04T15:53:31","Switch2":"ON","Switch3":"ON"}}
15:53:31 MQT: ***/rainWaterPump_Sensor/stat/STATUS11 = {"StatusSTS":{"Time":"2019-02-04T15:53:31","Uptime":"0T00:52:34","Vcc":3.307,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"***********-UK","BSSId":"E4:95:6E:45:CA:62","Channel":1,"RSSI":66}}}

```

**Comment by ascillato** [comment]
Switchtopic needs to be 0 to use rules.
Switchmode need to be 1 to use follow mode.
