### ISSUE TITLE
New Sonoff Basics not working

### ISSUE THREAD

**Issue by scargill** [arendst/Sonoff-Tasmota#5117]
I'm sure something similar has been discussed elsewhere but not using the programming tool I use.
I just got a batch of Sonoff BASICs , the ones with heavy wires instead of thick tracks.

I just flashed two on a PC and got no-where with sonoff-basic.rom (no more than a weeek after downloading)  - so I checked. I'm using NodeMCU Flasher on Windows 10 and I'd mistakenly left the advanced settings at 4MB - so I changed that to 1MB (230400 baud as usual for me, 40Mz flash speed as usual and DIO mode).

I've reflashed both boards but still no lights after flsahing and they ar not showing up as access points on my Android phone which they normally do.

Ideas?

**Comment by ascillato** [comment]
Try erase all flash with esptool.py as explained in the wiki and then please follow the wiki steps for flashing the precompiled bins from release.

**Comment by ascillato2** [comment]
Remember that for support it is available the Tasmota Support Chat.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by scargill** [comment]
#4515 didn't help and I use the NODEMCU Windows flasher. Am I right in saying these are 1MB?  I tried flashing a 1MB blank file then the sonoff-basic.rom file again, no better off.  I don;t know where in the WIKI it refers to reflashing the Sonoff BASIC , not marked as R2 but definitely genuine and ith 2 heavy wires instead of tracks... do I need to do any more than use a 1 meg blank file to wipe/resurrect them?

**Comment by ascillato** [comment]
I don't know if your flasher software delete all the flash content. There are some parts that contains the SDK info and wifi info. If you flashed 4M to a 1M it will be corrupt information.

A bullet proof method is: https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#esptool-usage

**Comment by scargill** [comment]
That fixed it, ascillato - I just messed up the file using 4MB setting. I used esptool.exe rather than .py but otherwise the same. I'd forgotten all about esptool.exe

For others in this situation, I had memory size wrong in NodeMC U Flasher AND the programming mode set to DIO (my normal).

These boards need DOUT. I'm now using NODEMCU Flasher successfully having first fixed my original 2 boards with:

esptool.exe --port COM15 erase_flash
then
esptool.exe --port COM15 write_flash -fs 8m -fm dout 0x0 sonoff-basic.bin

**Comment by scargill** [comment]
/looks like I spoke too soon. The sonoffs light up ok after flashing - I can connect the phone to them and set up SSID and passwords (pimarfy and secondary  SSIDs and passwords) and then save and reboot - but they're not appearing on my network - but I've done 10s of the previous sonoff basic boards without this problem. Is the sonoff-basic.rom file ok with the new boards?

**Comment by ascillato2** [comment]
Yes, it is ok. No issue at all. Are you using spaces, dashes or special characters in the ssid or password? Those are not supported.

**Comment by scargill** [comment]
Looks like I should have stuck with sonoff-basic.bin as sonoff.bin works a treat but OTA presents a message up complaining about minimal firmware. I have one of the boards on sonof-basic operating fully now and OTA is working thanks.

**Comment by scargill** [comment]
I use a period in the password incidentally.

**Comment by ascillato2** [comment]
Great!

Closing issue as it is solved. Thanks
