### ISSUE TITLE
Sonoff T1 R2 Boot Looping After flashing firmware

### ISSUE THREAD

**Issue by Bloodyagent** [arendst/Sonoff-Tasmota#5124]
Hi All
I am new to Sonoff and Tasmota.
I have been struggling to get my Sonoff T1 R2 US with Esp8285 flashed and connected to Wifi.
I have had no issues flashing a sonoff basic or a NodeMCU and connecting it to wireless.
My initial issue was the unit was not connecting to my wifi network. I have been through thread after thread trying to resolve and have tried the following with no luck.
Different firmware as far back as 5.14. Different core binaries including 2.3.0, 2.40, 2.4.2.
I have done a full flash erase using esptool and even tried to program using a bin file.
Using putty I can see the unit refused to connect to wireless, even with no specials characters in SSID and password.

My issue now is:

After multiple reflash after reflash I now cannot get the unit working at all, its in a boot loop, and no matter what firmware I load, fully erasing flash, i get the exact same error. I'm also changing the CFG_HOLDER value each time.
My Ardunio IDE settings are:

Board: ESP8285
1M no spiffs
v2 Higher Bandwidth
Erase Flash only sketch

Error is below, it just repeats continuously. Would appreciate some assistance. Thanks in advance.

ets Jan  8 2013,rst cause:1, boot mode:(3,7)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
vbb28d4a3
~ld

Exception (0):
epc1=0x402684c0 epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000000c depc=0x00000000

ctx: sys
sp: 3fffe780 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffe920:  00000000 00000000 00000000 00000031
3fffe930:  00000005 00000002 3fff0116 402684b8
3fffe940:  00000006 3fff00da 3fff00c8 3fff00d8
3fffe950:  0000001f 3fffe998 00000000 00000000
3fffe960:  00000040 0000002f ffffffff 0000004b
3fffe970:  000000d2 00000138 00000006 ffffffa6
3fffe980:  00000138 00000000 00000002 40006784
3fffe990:  00000001 3fff00c8 3d43474b 40263539
3fffe9a0:  00000000 4026898c 00000000 3fff00c8
3fffe9b0:  00000006 00000001 00000004 06190619
3fffe9c0:  00000000 00000000 00000000 00000000
3fffe9d0:  30003b4f 40266405 3fff00f8 4026a06c
3fffe9e0:  00000000 4026a081 3fff00c8 00000000
3fffe9f0:  3fff021a 3fff00d8 00000001 00000002
3fffea00:  3fff00c8 60000600 60000200 00000000
3fffea10:  40265d77 00000000 00000000 3fff021a
3fffea20:  40105d8e 60000e00 ffffffff ffffffff
3fffea30:  4026ad88 ffffffff ffffffff ffffffff
3fffea40:  00000001 b200db8e b7dc4f22 ffffffff
3fffea50:  00000000 000084c4 3fff4f3c 4026060b
3fffea60:  3ffefc2e 60000e00 3ffefc0c 3ffefc2e
3fffea70:  00000001 00000001 00000000 ffffffff
3fffea80:  40260ee3 3fff4f3c ffffffff 40260e8b
3fffea90:  3fff4f1c 00001000 401048fe 000000fd
3fffeaa0:  000000ed 00000020 3fffff10 00000001
3fffeab0:  3fff4fbc 00000001 00000003 00000000
3fffeac0:  ffffffff ffffffff ffff0002 00000000
3fffead0:  00000000 00000000 00000000 00000000
3fffeae0:  00000000 00000000 00000000 00000000
3fffeaf0:  ffffffff 00ffffff 00000000 00000000
3fffeb00:  00000000 00000000 00000000 00000000
3fffeb10:  00000000 00000000 00000000 00000000
3fffeb20:  00000000 00000000 00000000 00000000
3fffeb30:  00000000 ff000000 ffffffff ffffffff
3fffeb40:  ffffffff ffffffff ffffffff ffffffff
3fffeb50:  ffffffff ffffffff ffffffff ffffffff
3fffeb60:  ffffffff ffffffff ffff00ff ffffffff
3fffeb70:  0000000a 5f505345 45384244 00003742
3fffeb80:  00000000 00000000 00000000 00000000
3fffeb90:  00000000 00000000 00000000 00000000
3fffeba0:  00000000 00000000 00000000 00000000
3fffebb0:  00000000 00000000 00000000 00000000
3fffebc0:  00000000 00000000 00000000 00000000
3fffebd0:  00000000 ffffffff ffffffff ffffffff
3fffebe0:  ffffffff ffffffff ffffffff ffffffff
3fffebf0:  ffffffff 000001ff ffffff04 ffffff01
3fffec00:  ffffffff ffffffff ffffffff ffffffff
3fffec10:  ffffffff ffffffff ffffffff ffffffff
3fffec20:  ffffffff ffffffff ffffffff ffffffff
3fffec30:  ffffffff ffffffff ffffffff ffffffff
3fffec40:  ffffffff ffffffff ffffffff ffffffff
3fffec50:  ffffffff ffffffff ffffffff ffffffff
3fffec60:  ffffffff ffffffff ffffffff ffffffff
3fffec70:  ffffffff ffffffff ffffffff ffffffff
3fffec80:  ffffffff ffffffff ffffffff ffffffff
3fffec90:  ffffffff ffffffff ffffffff ffffffff
3fffeca0:  ffffffff ffffffff ffffffff ffffffff
3fffecb0:  ffffffff ffffffff ffffffff ffffffff
3fffecc0:  ffffffff ffffffff ffffffff ffffffff
3fffecd0:  ffffffff ffffffff ffffffff ffffffff
3fffece0:  ffffffff ffffffff ffffffff ffffffff
3fffecf0:  ffffffff ffffffff ffffffff ffffffff
3fffed00:  ffffffff ffffffff ffffffff ffffffff
3fffed10:  ffffffff ffffffff ffffffff ffffffff
3fffed20:  ffffffff ffffffff ffffffff ffffffff
3fffed30:  ffffffff ffffffff ffffffff ffffffff
3fffed40:  ffffffff ffffffff ffffffff ffffffff
3fffed50:  ffffffff ffffffff ffffffff ffffffff
3fffed60:  ffffffff ffffffff ffffffff ffffffff
3fffed70:  ffffffff ffffffff ffffffff ffffffff
3fffed80:  ffffffff ffffffff ffffffff ffffffff
3fffed90:  ffffffff ffffffff ffffffff ffffffff
3fffeda0:  ffffffff ffffffff ffffffff ffffffff
3fffedb0:  ffffffff ffffffff ffffffff ffffffff
3fffedc0:  ffffffff ffffffff ffffffff ffffffff
3fffedd0:  ffffffff ffffffff ffffffff ffffffff
3fffede0:  ffffffff ffffffff ffffffff ffffffff
3fffedf0:  ffffffff ffffffff ffffffff ffffffff
3fffee00:  ffffffff 00000003 ffffffff ffffffff
3fffee10:  ffffffff ffffffff ffffffff ffffffff
3fffee20:  ffffffff ffffffff ffffffff ffff0064
3fffee30:  00000000 00000000 ffffffff ffffffff
3fffee40:  ffffffff ffffffff ffffffff ffffffff
3fffee50:  ffffffff ffffffff ffffffff ffffffff
3fffee60:  ffffffff ffffffff ffffffff ffffffff
3fffee70:  ffffffff ffffffff ffffffff ffffffff
3fffee80:  ffffffff ffffffff ffffffff ffffffff
3fffee90:  ffffffff ffffffff ffffffff ffffffff
3fffeea0:  ffffffff ffffffff ffffffff ffffffff
3fffeeb0:  ffffffff ffffffff ffffffff ffffffff
3fffeec0:  ffffffff ffffffff ffffffff ffffffff
3fffeed0:  ffffffff ffffffff ffffffff ffffffff
3fffeee0:  ffffffff ffffffff ffffffff ffffffff
3fffeef0:  ffffffff ffffffff ffffffff ffffffff
3fffef00:  ffffffff ffffffff ffffffff ffffffff
3fffef10:  ffffffff ffffffff ffffffff ffffffff
3fffef20:  ffffffff ffffffff ffffffff ffffffff
3fffef30:  ffffffff ffffffff ffffffff ffffffff
3fffef40:  ffffffff ffffffff ffffffff ffffffff
3fffef50:  4fdcffff b78edb22 ffff0081 9dab190c
3fffef60:  200301e9 b0d8a1c6 ffffff01 55aa55aa
3fffef70:  00000002 00000020 00000020 000000ef
3fffef80:  000000ed aa55aa55 000000ed 40104424
3fffef90:  40001878 00000001 0000000d 9d2a780c
3fffefa0:  4010000d 5201f6b7 e8773cbf 60a0d33e
3fffefb0:  e3395b2a 108bfce8 1ebb6ad3 d367627f
3fffefc0:  3e6724ad d2c021fa d23b6e7a 440eaae2
3fffefd0:  0671d2bc 99f3e267 8e7221c9 15819978
3fffefe0:  20f91ee3 01c05cef 0beb3cd8 107b8f0e
3fffeff0:  f1fe8fb4 24db5f93 8f392d49 83d334f2
3ffff000:  8180536f be88ef5a 3a132a11 ae29dc01
3ffff010:  a1030990 84327630 fa9f5582 c0f21f0c
3ffff020:  22ae8da5 dbc21d47 f162b2cd aa7ec2cd
3ffff030:  8bfa272e bcfaddf7 76cacb65 cef2abaa
3ffff040:  46ce88fd 4f23d855 6091c26f 68b5e6af
3ffff050:  4c342ce7 88593e3d a2e71241 d6aab3f4
3ffff060:  79e46bd1 0c7eec85 e2b65256 c43f6395
3ffff070:  9be6c0c1 a9e87a0f 89047e14 c4b35585
3ffff080:  7890a485 0022e3b3 3e216956 905b8b0e
3ffff090:  d44381f0 61257dcb 893452f2 f1668add
3ffff0a0:  4671b419 d6f6b9b2 de226b46 86494fd7
3ffff0b0:  be76d5b4 6a3e595f e7c69766 452ede87
3ffff0c0:  5d58f0c9 120063e2 d9386b60 d43f8697
3ffff0d0:  843b4c83 8e236311 dfe7f676 c614cbea
3ffff0e0:  3d1fc2b1 93216d9f d0a4e340 f8a1e143
3ffff0f0:  b406d091 7a3d9f93 bb0e11ac a9136f80
3ffff100:  b5bd1488 77415f9a 077405e2 a6e278cf
3ffff110:  1ed6a57c 5075a7c8 f123471e 554b9cdf
3ffff120:  01e80a92 b3d53dec bfc93bc6 df241c85
3ffff130:  bb3da1d7 0545919c 885e49c0 eaddaada
3ffff140:  789a9511 3a0d8934 8210167b 06a2413c
3ffff150:  d9918d0a 58e1d48a d73c8438 20ea9b84
3ffff160:  ffcedf45 9afbcb2e 30a67963 31847adc
3ffff170:  cfc85a16 6b9440fd b5d5fd30 69d911cb
3ffff180:  7472c0ec d16fc474 c4e3acd0 8219fde0
3ffff190:  f3751204 a3fdfcb8 8c7b9330 01a9c9d3
3ffff1a0:  d57e5e16 76ff9a74 fb6a2052 50e15e54
3ffff1b0:  d2935da3 3e5883f3 d7f959a1 3b016d6c
3ffff1c0:  8dbb7a67 c2753caa 892b2149 7d15f1da
3ffff1d0:  345384fe 1c5fddf7 64548018 b9c0f6a1
3ffff1e0:  352ce0b7 aaa9f37e bd9f311a ffd84991
3ffff1f0:  eb032bdf 5d99e94d 6ad08f18 dfecba39
3ffff200:  b8350a5c aa82e273 e0128c82 72bc5bcb
3ffff210:  70d451e3 91882f9c 460ae49d 18d3d822
3ffff220:  123c90c9 df109dad 96906fe5 d218de82
3ffff230:  a9ff2fd2 b9b9f751 72e243bf 7fc7682a
3ffff240:  64671447 28035070 6f650f51 0633e279
3ffff250:  480f60ac fb8d3ae8 82f464d0 1637a305
3ffff260:  f389a2b0 5d35dcb8 7bd75770 dedefe4e
3ffff270:  756924fd cbad76f1 23b7f969 b7aee16c
3ffff280:  3a6c0853 09dd8418 4e0323b6 c41b2c00
3ffff290:  f1efdf15 0cba6f9a f75606cb 069f8440
3ffff2a0:  6ed16d00 0e772dd3 828d1ce9 27f21f1c
3ffff2b0:  75181f4a dcc55d9d d56ac067 8accd5eb
3ffff2c0:  aa9e3d08 266b8cdf 167ff85a 33aa343f
3ffff2d0:  30af4347 c8cdbb84 1534a5db eca1cb94
3ffff2e0:  e32d1ab9 3de7f02c c6dad4f0 4fb73261
3ffff2f0:  abf83263 48f496e4 e4d04711 d23e4ae7
3ffff300:  87f020c1 f92086dc 4acde598 ee964eb8
3ffff310:  9df03f8e 592d7e84 ecf6d493 673ffc0c
3ffff320:  056bbcf5 28d22750 acf79e8f 3a900b17
3ffff330:  2771322a 9264a27a d4527dd3 0404ee07
3ffff340:  d2bf436f 57ca0ed5 56fed0e7 0cfd8d29
3ffff350:  1146599c 44f662a4 abd01737 228244fb
3ffff360:  f267815d a1669e7f 735e1978 5411fd24
3ffff370:  ab5f43ae 022f75ab d69702c4 69b1636b
3ffff380:  32815763 781d0256 8f9c851e 67854d92
3ffff390:  5b3167f3 ff6adcc9 0952d274 8f2204c9
3ffff3a0:  1f668b32 f3c4c8dd 7f7e8e1c 30fa6d64
3ffff3b0:  88315d45 2ae83e6b a3a97959 d343f6b1
3ffff3c0:  ac545787 a281b59b b5becb66 a2556dd5
3ffff3d0:  a57067c2 504146a9 8a982cf6 f23a351a
3ffff3e0:  b29673e9 0ed869a6 7cfca4db c853df39
3ffff3f0:  0b95b45b 586ef7fe fcf6e4a6 4c14bdf2
3ffff400:  3d76732b 1ce88606 3d5c2745 9a911119
3ffff410:  c07c72ee 7c1bba34 65d0bc79 81a6b61e
3ffff420:  7948c037 6147c772 7dfb3201 c7416707
3ffff430:  a77ba5a4 4893faad c8d9498f 0e9da0ee
3ffff440:  1cb52b81 69264571 95820411 60bb09f1
3ffff450:  ffe7541d 950594d2 c2724936 ce37bef2
3ffff460:  cbf733ff 5d6455ac dab2aad0 16e31f86
3ffff470:  def208bd c27005de 24e656a9 80e59de0
3ffff480:  8be7b395 09af29e9 2236ddc2 b6c7a12b
3ffff490:  1ec81409 dc73c47f 857ed3c7 e1678eb2
3ffff4a0:  7a13b8f6 0d20699b 8ea9ba5d c295adc5
3ffff4b0:  3a71addb a67a7537 bd2d031d e04f9158
3ffff4c0:  602b9375 e7a3ce42 9a78457f 3049d75c
3ffff4d0:  db92d2d5 6aaa2d1a 799f4898 316a164f
3ffff4e0:  d985da7a a514cfa6 bc2a2e5a 31f8c6a6
3ffff4f0:  5fef4629 cb2d4cf4 747743bd 54575f55
3ffff500:  3956ed0b 4cb7f752 bf7b0321 7071d6fa
3ffff510:  2fae1588 84470dfa e9f62d26 4a370942
3ffff520:  9d34ac7c 33106fcb 71fca5cc 4a73d79d
3ffff530:  7d7c2abd a4b6344d 8ae62758 4f61e2ea
3ffff540:  ad59c5fa db09c52d 89ee81f2 8a5964a3
3ffff550:  151cdb88 95a5bc3a 6a26a246 acdef27d
3ffff560:  b7690c97 55d1c450 ff4b47c5 090be568
3ffff570:  2ddcdba1 842faa7f 3135597f 4e567db2
3ffff580:  c008150f b10dc62d db4cb240 4506f51e
3ffff590:  7055468f cd62d64e 750f3da8 b22c94a3
3ffff5a0:  3d709671 94dd3830 d3c5a44c 4ace8b57
3ffff5b0:  e35e15eb f7d94f00 9b9d2829 0ff9ee40
3ffff5c0:  410a0cc5 2eb8823b 8fe7f938 3c6e8619
3ffff5d0:  3bbb82af ab903d59 1883685e 5cfefff7
3ffff5e0:  1da75aa1 5c0d9f1f 72291498 3a05677c
3ffff5f0:  b9c69fa8 8e044574 9d0c1d28 2a472adb
3ffff600:  6f2cf560 23b3c656 06ef11d9 dc80fd7c
3ffff610:  c27ee63b ed455b48 60a7765d 3655c877
3ffff620:  98ae0ee8 840ffcbd cf27962d 30effa4c
3ffff630:  f73703ee 660d3316 630a265d 471c2337
3ffff640:  06f12660 55d86db9 d1dcc26c 4c7dffd9
3ffff650:  1da6c8d1 4403f202 b9b9e000 02c499c1
3ffff660:  6b9e4964 4dbe5aae bb720cdb 5ec86aad
3ffff670:  bec4fe52 b3453add 3527d671 e5e9a4fd
3ffff680:  6e2eac7d 43570035 bc4604a3 43e35f15
3ffff690:  3099d1fb 13ab67d8 4120d867 942855ae
3ffff6a0:  7c3ec272 c73c1402 a72525dd 6445e6b3
3ffff6b0:  cf3a64c0 8d44e179 6feb2f5b 29f363fb
3ffff6c0:  f126083b 23a91694 233491ac 0a80ec01
3ffff6d0:  25f1ef02 91a5c8e4 5e414ff7 4de9f1a5
3ffff6e0:  7d7649f7 5069cdc7 75b5281c 19e113a0
3ffff6f0:  41e04fa2 0ceef3b9 e9066b05 373bf5fc
3ffff700:  95d7ec6c 16176055 ecffff46 5c3dc924
3ffff710:  c76e4956 cbd6e7c6 99b18c14 ba57bef3
3ffff720:  a7ed8049 9a5f70e3 b9b5e91e d3f01320
3ffff730:  e5733bd8 77eedbba 5df1352d 8d64bbe6
3ffff740:  7e9943bd 815eda3b 19fe09ae 1caf0997
3ffff750:  cc414973 4fa8e5b9 2b3601bb f18456ea
3ffff760:  e4dd8f1b 98dce967 9b4949a8 2dcd9594
3ffff770:  fd7810e2 074be40d ecb65615 621b457f
3ffff780:  36b33f19 590609a1 3db340d7 60629a5e
3ffff790:  e77892d7 1fbfaa1b e858b380 75b8d3f4
3ffff7a0:  cdb8120b 6a551abe 9ff75f02 9424385f
3ffff7b0:  b8bbfa64 41a4c8fc fb6c0d89 60ed9789
3ffff7c0:  dd8c1693 fa6de100 611c2640 883dbaff
3ffff7d0:  67562c60 31f4542a ffae9f4b 0e4137c0
3ffff7e0:  4fec76db f56872d5 be906c7f 8529bb6d
3ffff7f0:  e8d774ca c17ea4d0 1a21e0b8 079863f2
3ffff800:  2d41b6c4 54e5db18 88a43405 cbb1e4aa
3ffff810:  70c8d708 ca0414e7 352a1c3f 29400939
3ffff820:  edf7f323 0bcc7b3c 51f30dfb 4b1d72f8
3ffff830:  9fad6ef2 1e596d9b e1c93f36 6bcbe29e
3ffff840:  876114ed a243d80b 7c8d193f 2d39d5ef
3ffff850:  9915321e b75b6c37 723a626a 5263441f
3ffff860:  b540a42d 5e1f5598 4f56b8a9 1c9b8777
3ffff870:  d1d1fa48 af44f5ed 5acc3bab a434fe73
3ffff880:  b124f133 8fea76b6 57844385 163f64ed
3ffff890:  6944cabf e1730717 0a8a34c2 4d0b6fc6
3ffff8a0:  ab59aaed 54f98bb3 ebb1482a eba0ea43
3ffff8b0:  f2507cb6 34b0e174 c8d12d85 166d7d36
3ffff8c0:  de33c47c 87804f8a 651de803 453ed9fd
3ffff8d0:  cd54c542 e28af03f edc8c0de 4724f245
3ffff8e0:  65fb70d7 63da98c5 779bdbe2 722ddfef
3ffff8f0:  03782db4 7c8a07b5 6e92e259 a020e0c7
3ffff900:  d48b96c0 893ae687 25bb9d04 49246946
3ffff910:  7bf3cc40 2843c0df 28dab244 25590ecd
3ffff920:  88b24610 0b41585c 5099a741 a63a659e
3ffff930:  d0d4fd26 0934e9ea df9cb2b5 8e2581d3
3ffff940:  72a30618 a87b7b16 743998f2 70496585
3ffff950:  127d07a6 281ffff3 0c1d60fc fd2e7d3e
3ffff960:  679b34d1 426812fd c193bb12 3505c8a5
3ffff970:  df91114a a7c2a9e7 eb5ecd4d 8c31d4ee
3ffff980:  d1c20f46 3e22537c 422dcfe6 9c00fdd9
3ffff990:  e90c1c4f 0c7d6e62 939e91f0 90d7fc9c
3ffff9a0:  ee104959 4121518f 12f9e7cb 0a6c2774
3ffff9b0:  de2e5bbb f78d5b9a bf4c74c6 026575a8
3ffff9c0:  f9341460 45902b63 c3fc06fb a8e8a79d
3ffff9d0:  14edc58e 8494f78a 175134ee 38682bd5
3ffff9e0:  ad080356 ce3d0579 9f3a43ee 1dd9efa2
3ffff9f0:  da607198 c00ee562 82ba35f5 3b19e95f
3ffffa00:  a8e40446 469c34a4 816e3a39 7536b528
3ffffa10:  6c4e1085 d552a64f 6d1a28f7 ab72fe66
3ffffa20:  801752bb 106ddc86 bcc1fe0f d4bd249d
3ffffa30:  7639da7f 685bfaa7 5e7cdc32 56bc5d13
3ffffa40:  dd5151f1 0341c7dd 126676e7 84abbfe0
3ffffa50:  3c292440 86b5b3b6 cf5008d5 ecbd37e3
3ffffa60:  7ed19c23 26fabdbd cd443608 1490623a
3ffffa70:  84d2bb7e 98fa519c adb59084 0e6a7393
3ffffa80:  3848f62a 4aa70d5b 05921e38 19a656fe
3ffffa90:  8a302238 09f8a7ff dfc9b4a5 6630a640
3ffffaa0:  d210f012 4ae07fc4 ff7c7691 9199de46
3ffffab0:  c8b525ee 519d732a db2fdf48 b4f77e97
3ffffac0:  98da649f 2eedcfad 5dba232b 49e68d80
3ffffad0:  1826a90e 9107bb69 6c9e9c26 7eb5ae1d
3ffffae0:  f7a5eeb4 0a7dfe4d 49f9a04b 8b1c2e50
3ffffaf0:  2cc38fb3 2e4a2882 4f393496 1e1e8dd3
3ffffb00:  73e72e1b 281bd39e 7cbdd52a 0e3e5c3d
3ffffb10:  91d86c6d 92434c5c 3e3a249f 019cb98b
3ffffb20:  dec60976 7fefff57 38cf19a2 3898be75
3ffffb30:  adcfc503 118ed848 2bef7524 0fd5d5fb
3ffffb40:  e66939a2 cca29fcf be8fe1d9 8265b9af
3ffffb50:  65e7b508 a01a7aec 568ccf9f 2cbecdc4
3ffffb60:  1f2c6108 dbb1fdf7 b87ef516 296d452d
3ffffb70:  7d547f8d b0aa5e15 83ee8874 30987f5a
3ffffb80:  3eaab212 9e6314ae 5e3c4ed7 494add24
3ffffb90:  d8651271 04605e21 67d428c3 30c1bb7a
3ffffba0:  6cfe070a c572cd7a dfce91b3 289d7b70
3ffffbb0:  7f1f1ecf be078b93 cfd70005 2ee12450
3ffffbc0:  dac73715 c5f3bbdd 7aecd04d 69d5bf9e
3ffffbd0:  5e5412fc 84c0189a 48941069 cd79face
3ffffbe0:  1ee3a68d 8a919337 9307cce1 4a563aaf
3ffffbf0:  94cfa6aa 8eb01efb 762d466f 235f4ddd
3ffffc00:  782de097 4578021c f062d647 d563dcc4
3ffffc10:  09a9bf91 219dc116 07cf730f d81f94b5
3ffffc20:  7a796f82 dca9158f 1e80ce32 4a2e50af
3ffffc30:  67cee07b c4ab6b26 5d148a1f 71d3f7ba
3ffffc40:  b410831d 18105c2b 7dd4c45d 3fb11ab1
3ffffc50:  95f06bbf 7c87bb2c 6536a32a c85a78a9
3ffffc60:  c82af10b 80fbecfc fd9c1cd6 628d6463
3ffffc70:  e0b86b04 81c9a12c 21cbb1bc 498c75d9
3ffffc80:  0acf71d6 0ee5a529 55651842 e3467578
3ffffc90:  7fb8e40f 6e5af30f cbf8642d e090ef7a
3ffffca0:  cabc4b1c 7020c271 35b89d75 1e6edd79
3ffffcb0:  e2ff94a5 10351e0b 87700d0d 3bbcee8b
3ffffcc0:  cd06608e 5b7cf6a3 7838966d 76e02727
3ffffcd0:  6b35466d 839b3958 2ef84d1b ef2756e1
3ffffce0:  ff605a07 a0be619d bf713efa 4cade65b
3ffffcf0:  087fb3c0 12d2d487 fdcb350a 7dc4dddf
3ffffd00:  3532d40c 0c1d2aad 7a65a481 f74a1a06
3ffffd10:  0000000b 00000000 00000010 00000000
3ffffd20:  0000000b 00000000 00000010 00000000
3ffffd30:  dfb5e989 05cad19f c1bfd320 85067cad
3ffffd40:  00000000 80000000 00000000 0000001b
3ffffd50:  00005800 c08de641 00005800 00008000
3ffffd60:  ddbfcafd 00000000 00005800 c94b89f3
3ffffd70:  00008000 c0bfef52 ddb009fc 8846c4d1
3ffffd80:  00000002 00000000 40001e65 3ffffdd8
3ffffd90:  3ffffe50 0000000b 00000010 40001e4b
3ffffda0:  3ffffdd7 00000000 00000000 00000000
3ffffdb0:  00000000 80000000 00000000 0000001b
3ffffdc0:  00001000 007bc342 00001000 00008000
3ffffdd0:  64346133 62623238 00001000 21967922
3ffffde0:  00008000 00000000 0000000a 00000000
3ffffdf0:  00000007 00000000 40001e65 3ffffe42
3ffffe00:  3ffffec0 00000002 19de92a2 40001e4b
3ffffe10:  3ffffe41 00000000 00000000 00000000
3ffffe20:  3fffd848 40002364 00000001 00000000
3ffffe30:  40001db4 00000078 00000000 00000010
3ffffe40:  40001f46 00000009 da6a9d0c 47295bb1
3ffffe50:  38326262 33613464 40001e00 3ffffea1
3ffffe60:  3fffff20 00000007 f7320f35 40001e4b
3ffffe70:  3ffffea0 00000000 00000000 00000000
3ffffe80:  be90188f d4a5e1f3 d2d8105f d607d2aa
3ffffe90:  00000000 3fffff00 3fffff00 3fffff2e
3ffffea0:  40002514 3fffdd3c 00000001 0000000d
3ffffeb0:  3fffff20 00000008 00000008 00000001
3ffffec0:  00000000 bb28d4a3 00000000 3ffffe58
3ffffed0:  00000000 519ef601 95f0a200 0e3c9f57
3ffffee0:  00000002 400042db ffffffff 4010f098
3ffffef0:  40004b31 40001878 00000001 0000000d
3fffff00:  4010f15c bb28d4a3 00000000 20000000
3fffff10:  00086b20 00000004 3fffff01 3ffe8790
3fffff20:  200304e9 40106c48 3ffe8790 00001fe0
3fffff30:  00000000 0000002d 00000000 3ffffec2
3fffff40:  4010f355 aeac1af7 3fffff50 4010f35a <
3fffff50:  00000009 3ef7c243 ffffffff 00000000
3fffff60:  d2fc7f7a db28b832 32291c9c 890e4d7c
3fffff70:  96dd2ffa 71e4b402 2a366fb8 97d1604d
3fffff80:  94989e03 c4ff6dbe d0123e2b bf8fe100
3fffff90:  97b4bb76 592a34ab a190103f fc34c031
3fffffa0:  d8c987ec 9bbc3310 f4a4bc50 d46c8846
<<<stack<<<

Exception (4):
epc1=0x400005cb epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000000c depc=0x00000000

**Comment by Bloodyagent** [comment]
Thanks I will try again, my issue though now is fixing the boot loop. 

So if I erase flash and flash latest bin with the esptool and it doesnt work it means the unit is bust?

**Comment by Jason2866** [comment]
Yes, if powered with AC mains after a successful flash and it doesnt open an AP it has a hardware defect

**Comment by Bloodyagent** [comment]
OK, so I downloaded sonoff.bin from the link you provided, and ran the following commands successfully:

esptool.py erase_flash
esptool.py --port COM4 write_flash -fs 1MB -fm dout 0x0 sonoff.bin

I'm assuming the flash command is the same for both esp8266 and esp8285?

The above has made no difference. The unit is still spewing out the above message and resetting every second and looping.

**Comment by Bloodyagent** [comment]
OK, so it was a power issue!!! Board is for the first time broadcasting an SSID!! So I went into the webserver and entered my SSID and password and its sadly not connecting :), will reflash and do it again, maybe i entered incorrectly. Thanks anyway for the help to get it this far!! Will get back to you now.

**Comment by Bloodyagent** [comment]
I cant believe it!! Thanks so much for your help, I have been struggling for 2 days with the Arduino IDE and here I did it in 2 mins using esptool and your help. Connected to wifi and all seems fine now. 

Thanks again

**Comment by Jason2866** [comment]
Glad it works
