### ISSUE TITLE
Shelly 1 switches up to 10 seconds after wall switch is pressed

### ISSUE THREAD

**Issue by scheilch** [arendst/Sonoff-Tasmota#5127]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

**Describe the bug**
_A clear and concise description of what the bug is._

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x] _Searched the problem in issues and in the wiki_
- [x] _Hardware used_ : Shelly 1 V 1.3 labelled
- [x] _Development/Compiler/Upload tools used_ : platform.io with atom editor
- [ ] _If a pre-compiled release or development binary was used, which one?_ :
- [x] _You have tried latest release or development binaries?_ : v6.4.1
- [x] _Provide the output of command_``status 0`` : will do later - im not at home now
```
STATUS 0 OUTPUT HERE - DO NOT DELETE THE MARKERS ABOVE AND BELOW THIS LINE
```

**To Reproduce**
The Shelly behaves like the product describes for 3 weeks and then the issue came up. The wiring is as described on the shelly website. Now the Shelly 1 reacts 5-10 seconds after the wall switch is pressed. Once the relay has switched and the Shelly is "awoken" - it switches the relay as expected. But if you wait for several minutes it's the same behaviour and it switches the relay long time after the wall switch. That's annoying. I tried to flash a new (probably the same) tasmota 6.4.1 firmware but the issue isn't gone.

**Expected behavior**
Expected is that the Shelly switches the relay right in that time i press the wall switch - at any time.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
@scheilch 
Sorry that your device is faulty. Remember that the warranty from the manufacturer ends when you change the firmware. You should flash the original firmware back and test it. Thanks
