### ISSUE TITLE
Sensor DHT22 not working with Sonoff RF R2 Power V1.0 (new Sonoff Basic)

### ISSUE THREAD

**Issue by jacoscar** [arendst/Sonoff-Tasmota#5130]
Hello,

I'm using one of the new Sonoff Basic with the wires instead of the thick solder tracks, recognisable by the words "Sonoff RF R2 Power V1.0" printed on the board.

I've bought a DHT22 and connected the first pin to 3V3, second pin to Rx (GPIO3) and fourth pin to GND; In settings I've set "GPIO3 Serial In" to "SI7021", restarted the Sonoff but temperature and humidity are not displayed. I've also tried selecting "AM2301", and also using Tx (GPIO1) by connecting the sensor there.

The sensor works fine when connected directly to the Raspberry with both 5V or 3V inputs

**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Development/Compiler/Upload tools used : USB to TTL serial
- [x] Hardware used : Sonoff RF R2 Power V1.0 (new Sonoff Basic)
- [x] If a pre-compiled release or development binary was used, which one? : NA
- [x] You have tried latest release or development binaries? : YES
- [x] Provide the output of command ``status 0`` : YES
```
STATUS 0 OUTPUT HERE

11:23:41 CMD: Status 0
11:23:41 MQT: stat/sonoffR2/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoffR2","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
11:23:41 MQT: stat/sonoffR2/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-basic.bin","RestartReason":"Software/System restart","Uptime":"0T02:23:06","StartupUTC":"2019-02-06T08:00:35","Sleep":50,"BootCount":29,"SaveCount":77,"SaveAddress":"F7000"}}
11:23:41 MQT: stat/sonoffR2/STATUS2 = {"StatusFWR":{"Version":"6.4.1(basic)","BuildDateTime":"2018-12-24T14:43:30","Boot":7,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
11:23:41 MQT: stat/sonoffR2/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MYUSERSSID",""],"TelePeriod":300,"SetOption":["00008009","558180C0","00000000"]}}
11:23:41 MQT: stat/sonoffR2/STATUS4 = {"StatusMEM":{"ProgramSize":445,"Free":556,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0F082780","000083A0","21021706","000001C0"]}}
11:23:41 MQT: stat/sonoffR2/STATUS5 = {"StatusNET":{"Hostname":"sonoffR2-5756","IPAddress":"192.168.1.11","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"DC:4F:22:DF:36:7C","Webserver":2,"WifiConfig":4}}
11:23:41 MQT: stat/sonoffR2/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.15","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_DF367C","MqttUser":"MYUSER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
11:23:41 MQT: stat/sonoffR2/STATUS7 = {"StatusTIM":{"UTC":"Wed Feb 06 10:23:41 2019","Local":"Wed Feb 06 11:23:41 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:13","Sunset":"17:55"}}
11:23:41 MQT: stat/sonoffR2/STATUS10 = {"StatusSNS":{"Time":"2019-02-06T11:23:41"}}
11:23:41 MQT: stat/sonoffR2/STATUS11 = {"StatusSTS":{"Time":"2019-02-06T11:23:41","Uptime":"0T02:23:06","Vcc":3.552,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"MYUSERSSID","BSSId":"7C:11:CB:F2:CA:37","Channel":11,"RSSI":88}}}

```

**Comment by Jason2866** [comment]
Have you disabled serial logging? If not you cant use rx tx

**Comment by jacoscar** [comment]
Yes, It's off

```
08:31:36 CMD: SerialLog
08:31:36 RSL: stat/sonoff/RESULT = {"SerialLog":"0 (Active 0)"}
```

**Comment by ascillato** [comment]
Hi,

Please, could you be so kind on completing the troubleshooting template? The information required there is necessary in order to provide help. Thanks

**Comment by jacoscar** [comment]
> Hi,
> 
> Please, could you be so kind on completing the troubleshooting template? The information required there is necessary in order to provide help. Thanks

I have updated the first post

**Comment by ascillato2** [comment]
It is needed a resistor for DHT22. Did you connect it?

**Comment by jacoscar** [comment]
I read most people don’t use it, but I’ve tried with a 10k Ohm resistor and it didn’t do anything 
I also tried to connect it to a Sonoff S26, still using serial Rx with no luck

**Comment by Jason2866** [comment]
Do you know that the sensor is working?

**Comment by jacoscar** [comment]
> Do you know that the sensor is working?

It works if directly connected to the raspberry; it shows up in Home Assistant

**Comment by ascillato2** [comment]
Please, try the latest full version from the development branch: http://thehackbox.org/tasmota/020500/sonoff.bin

**Comment by jacoscar** [comment]
I did the OTA update, isn't it the same?

**Comment by ascillato** [comment]
You have:

"Version":"6.4.1(basic)" 

I'm asking you to please try latest from development branch (http://thehackbox.org/tasmota/020500/sonoff.bin):

"Version":"6.4.1.14(sonoff)"

**Comment by jacoscar** [comment]
Wow, it works now!

**Comment by ascillato2** [comment]
Closing this issue as it has been solved. Thanks

**Comment by jacoscar** [comment]
I would like to understand, was I supposed to use a development version instead of the released one from the beginning?

**Comment by ascillato** [comment]
You were using the **sonoff-basic.bin** that does not have sensors support. Now you are using the full version **sonoff.bin**
