### ISSUE TITLE
Tasmota 6.4.1 SerialBridge invalid json via MQTT

### ISSUE THREAD

**Issue by neographikal** [arendst/Sonoff-Tasmota#5131]
Followed https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-P1-Energy-Meter

Data is coming through correctly on the device itself:

![image](https://user-images.githubusercontent.com/2643715/52308411-90f39e80-299d-11e9-9465-3550cc053bc6.png)

However via MQTT I receive the following:

![image](https://user-images.githubusercontent.com/2643715/52308464-ad8fd680-299d-11e9-91d7-ef7f2404924a.png)

Note the } at the start and the lack of a closing }

```
23:28:43 CMD: status 0
23:28:43 MQT: stat/nodemcu-p1/STATUS = {"Status":{"Module":18,"FriendlyName":["Sonoff"],"Topic":"nodemcu-p1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
23:28:43 MQT: stat/nodemcu-p1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:15:27","StartupUTC":"2019-02-05T22:13:16","Sleep":10,"BootCount":6,"SaveCount":18,"SaveAddress":"FA000"}}
23:28:43 MQT: stat/nodemcu-p1/STATUS2 = {"StatusFWR":{"Version":"6.4.1(sonoff)","BuildDateTime":"2019-02-05T22:20:26","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
23:28:43 MQT: stat/nodemcu-p1/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["neofoto.nl",""],"TelePeriod":300,"SetOption":["00408009","558180C0","00000000"]}}
23:28:43 MQT: stat/nodemcu-p1/STATUS4 = {"StatusMEM":{"ProgramSize":477,"Free":524,"Heap":19,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640E0","FlashMode":3,"Features":["00000809","0FD02794","240003A0","210217C6","000000C0"]}}
23:28:43 MQT: stat/nodemcu-p1/STATUS5 = {"StatusNET":{"Hostname":"nodemcu-p1","IPAddress":"192.168.2.239","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"A0:20:A6:17:B7:07","Webserver":2,"WifiConfig":4}}
23:28:43 MQT: stat/nodemcu-p1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.35","MqttPort":1883,"MqttClientMask":"nodemcu-p1","MqttClient":"nodemcu-p1","MqttUser":"","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
23:28:43 MQT: stat/nodemcu-p1/STATUS7 = {"StatusTIM":{"UTC":"Tue Feb 05 22:28:43 2019","Local":"Tue Feb 05 23:28:43 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:14","Sunset":"17:53"}}
23:28:43 MQT: stat/nodemcu-p1/STATUS10 = {"StatusSNS":{"Time":"2019-02-05T23:28:43"}}
23:28:43 MQT: stat/nodemcu-p1/STATUS11 = {"StatusSTS":{"Time":"2019-02-05T23:28:43","Uptime":"0T00:15:27","Vcc":3.032,"SleepMode":"Dynamic","Sleep":10,"LoadAvg":99,"Wifi":{"AP":1,"SSId":"neofoto.nl","BSSId":"70:4F:57:83:BC:AE","Channel":1,"RSSI":100}}}
23:28:44 MQT: tele/nodemcu-p1/RESULT = {"SerialReceived":"/XMX5LGBBFFB231077730
"}
```

**To Reproduce**
See above

**Expected behavior**
Correct json output to mqtt

**Comment by arendst** [comment]
Nice one!

The issue here is that your data contains a carriage return at the ends of it's data. This results in a new line just before the closing bracket and makes the JSON invalid.

I'll need to re-write non-text reception like the hardware serial bridge does.

So in the meantime try the not-software serial bridge solution (lookaround the wiki commands how to) as I need some time time to easily solve this one.

**Comment by neographikal** [comment]
Ah cool. I forgot, I am using the hardware rx pin to receive the data :)

**Comment by arendst** [comment]
When using hardware serial did you configure the correct SerialDelimiter as noted in the wiki?

You should have executed command ``SerialDelimiter 10`` the fix your newline issue.

**Comment by neographikal** [comment]
![image](https://user-images.githubusercontent.com/2643715/52502487-2f247600-2be3-11e9-84c7-7f0e8b5d512a.png)

Yep I did :)

**Comment by arendst** [comment]
Change it to 13 and see what happens.

**Comment by neographikal** [comment]
![image](https://user-images.githubusercontent.com/2643715/52507993-71ee4a00-2bf3-11e9-9afe-cfcd3b356cb1.png)
 
Hmm that looks better. I'll try parsing it with Node Red :)

**Comment by arendst** [comment]
Try to change setoption22 0

**Comment by neographikal** [comment]
23:11:17 CMD: setoption22 0
23:11:17 MQT: stat/nodemcu-p1/RESULT = {"Command":"Error"}

Setoption22 off or "Off" does not work either. Documentation says it's a reserved option.

**Comment by arendst** [comment]
See my updated comment.

**Comment by neographikal** [comment]
that results in unknown commands for each received serial line. 

![image](https://user-images.githubusercontent.com/2643715/52509877-1ffcf280-2bfa-11e9-8011-905798277fc9.png)

Enabled serialsend again to get data to mqtt.

**Comment by arendst** [comment]
Right. I will introduce another option for receiving standard text without control characters soon.

**Comment by arendst** [comment]
Pls try the latest dev release and enable the feature to only allow reception of characters between ASCII 32 and 127 using command ``SerialDelimiter 128`` and report back your result.

**Comment by ascillato2** [comment]
@neographikal

Hi, any news on this?

**Comment by neographikal** [comment]
Haven't been home much sorry. Hope I'm home tomorrow night.

**Comment by dusan06** [comment]
I use sonoff TH 16 with DS18B20 and tasmota v6.4.1 and I alsol have error in my flow

[{"id":"e3370fef.9a1ef","type":"debug","z":"39150ecd.3759d2","name":"","active":true,"tosidebar":false,"console":false,"tostatus":false,"complete":"true","x":630,"y":60,"wires":[]},{"id":"4710d33b.1e6d8c","type":"inject","z":"39150ecd.3759d2","name":"Test","topic":"cmnd/sonoff/status 8","payload":"","payloadType":"str","repeat":"30","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":60,"wires":[["56e3543.8e08eac"]]},{"id":"56e3543.8e08eac","type":"json","z":"39150ecd.3759d2","name":"","property":"payload","action":"obj","pretty":false,"x":250,"y":60,"wires":[["3e79d4f8.cfad9c"]]},{"id":"3e79d4f8.cfad9c","type":"function","z":"39150ecd.3759d2","name":"Get Temp","func":"var temp=msg.payload.DS18B20.Temperature;\n\nvar msg = {\n\npayload:temp\n\n};\n\nreturn msg;","outputs":1,"noerr":0,"x":440,"y":60,"wires":[["e3370fef.9a1ef"]]}]

Error Unexpected end of JSON input
I can not read temperature.

Please help Dule

**Comment by ascillato** [comment]
@dusan06

You are using 6.4.1
The fix is in latest version 6.4.1.15

Please update

**Comment by dusan06** [comment]
Thanks ascillato!
One more question, where to find the latest version? If it can link.
Best regards, Dule

**Comment by ascillato** [comment]
http://thehackbox.org/tasmota/

**Comment by dusan06** [comment]
Thank you ascillato, it was very useful

**Comment by neographikal** [comment]
Okay, I tried. It kind of works:

![image](https://user-images.githubusercontent.com/2643715/52673318-ac702380-2f20-11e9-9af4-8761210400b7.png)

Only now not every line becomes an mqtt message, but at the end it is split. Kind of weird. Just thinking out loud: it would be nice to parse P1 output directly in tasmota and provide all the values as telemetry? :)

**Comment by Jason2866** [comment]
You could try GEMU fork. https://github.com/gemu2015/Sonoff-Tasmota -> Branch Univeral2
He is supporting SML devices

**Comment by arendst** [comment]
As the original issue has been solved I close this one.
