### ISSUE TITLE
How to use IRRecv and IRSend?

### ISSUE THREAD

**Issue by botak13** [arendst/Sonoff-Tasmota#5136]
I have now managed to flash a Wifi infrared remote control with Tasmota.
Unfortunately, I do not understand how I can now teach and send infrared commands from Tasmota.

The Device Name is Auvisio NX-4519.

Can someone explain to me how I have to set up the device in Tasmota and how to send and receive infrared commands?

Thanks in advance.

**Comment by Jason2866** [comment]
For questions and help you can visit us at Tasmota Discord Chat https://discord.gg/Ks2Kzd4

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
