### ISSUE TITLE
Extend wifi receiption range??

### ISSUE THREAD

**Issue by leo389** [arendst/Sonoff-Tasmota#5137]
Hello All,

This is just a general question to see if anyone has been able to extend the WiFi reception range by means of connecting an external antenna (I have one from an old router). Perhaps removing/ de-soldering the connecting cap to the onboard antenna. 

I see some stuff on sites claiming increased range but like to hear if it's real or not??

Thanks,

Leo

**Comment by Jason2866** [comment]
This is github issues for Tasmota. Not a forum.
For questions and help / support visit us at Tasmota Discord Chat https://discord.gg/Ks2Kzd4

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
