### ISSUE TITLE
MQTT features: display specific telemetry values on OLED display.

### ISSUE THREAD

**Issue by jedisha** [arendst/Sonoff-Tasmota#5140]
Hi there,

I just read on the MQTT features page that:

...Telemetry data will be sent by prefix tele like tele/sonoff/SENSOR {"Time":"2017-02-16T10:13:52", "DS18B20":{"Temperature":20.6}}

I'm trying to just get my temperature to display on an OLED display. Currently i can only display the entire telemetry output (by subscribing to the mqtt topic). Could anyone point me in the direction of what i need to do with my code to pull out just the temp integer?

Many thanks!
P

**Comment by Jason2866** [comment]
You find nice rule examples in this doc https://github.com/arendst/Sonoff-Tasmota/files/2365181/DisplayText.docx

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
