### ISSUE TITLE
GPIO 12 and GPOI 14 Sonoff RF Link 433

### ISSUE THREAD

**Issue by underwoodblog** [arendst/Sonoff-Tasmota#5142]
Both versions of the Sonoff RF Bridge 433 have solder points for GPIO12 and GPIO14 that are directly connected to the ESP8265 chip. Please make them available in the webinterface as options for IOs.

https://github.com/arendst/Sonoff-Tasmota/pull/5143

**Comment by ascillato2** [comment]
Closing this issue as the PR has been done. Thanks for sharing your ideas. 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
