### ISSUE TITLE
Devices return {"Command":"Unknown"} in reply to cmnd/sonoffs/topic, but return proper topic when issued via cmnd/<topic>/topic

### ISSUE THREAD

**Issue by jziolkowski** [arendst/Sonoff-Tasmota#5145]
Same problem across versions 6.3, 6.4.1 and 6.4 dev bins.

Other commands work, like fulltopic, restart, statuses etc. Didn't try all of them, of course, so maybe other commands don't work as well.

**Comment by jziolkowski** [comment]
oh, tested it with another user, same result.

**Comment by ascillato2** [comment]
Hi, I can also confirm this behaviour.

**Comment by arendst** [comment]
As designed. It's a feature!

Background:
The group command (sonoffs in this case) does not allow commands like hostname to execute as it would mean that several devices would receive the same hostname which will probably make your network a bit unstable.

The same is true for some other commands although this 'group ban' has been lifted from most command over the last year.

To find out which commands are currently under control of this feature search the source code for ``grpflg``

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by jziolkowski** [comment]
Ok, I get it. Could this "ban" mean they're just read-only in some future revision?

**Comment by arendst** [comment]
Nice idea.
