### ISSUE TITLE
Flash with Arduino ide

### ISSUE THREAD

**Issue by Steppdroid** [arendst/Sonoff-Tasmota#5147]
Hi, i flash my sonoff base v2 (esp8285) with setting Erase Flash on All flash Contents.. now sonoff not working... i tried to reflash tasmota but nothing.. any help? Thank!!

**Comment by ascillato2** [comment]
Hi

For support there is available the Tasmota Support Chat. Github issues are for bug reporting with the provided templates completed. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
