### ISSUE TITLE
WebThing API support

### ISSUE THREAD

**Issue by blackfyre** [arendst/Sonoff-Tasmota#5149]
Mozilla is hard at work on implementing an IOT standard which is the WebThing API.
It would be great if one of (if not) the biggest open source firmware alternative could support this!
The documentation for what the sonoffs and shellys provide as services is mature enough for implementation.

I've also made a sample implementation for a Sonoff Basic: https://github.com/blackfyre/sonoff-basic-webthing

API: https://iot.mozilla.org/wot/
GateWay: https://iot.mozilla.org/gateway/

The GateWay can be set up for testing through docker.

**Comment by Jason2866** [comment]
Keep in mind the resources of the ESP devices. 
The "core" of Tasmota is mqtt. It is not the goal to do Home Automation via other protocols.
Since it is Open Source feel free to fork and do it.

**Comment by ascillato2** [comment]
Hi,

Thanks for sharing your ideas. 

Adding the label hold over for future reference.
