### ISSUE TITLE
Sonoff Basic RF R2 POWER V1.0 gpio14

### ISSUE THREAD

**Issue by Jimmyneu** [arendst/Sonoff-Tasmota#5160]
Any way i can solder straight to ESP8285 to connect to gpio14? is it safe? where is it located? it looks to be located on the bottom left. 
![image](https://user-images.githubusercontent.com/47344589/52445931-256f1580-2af2-11e9-995b-1cd85212f6e2.png)

https://www.espressif.com/sites/default/files/0a-esp8285_datasheet_en_v1.0_20160422.pdf
Page 6

**Comment by ascillato2** [comment]
Yes, exactly.

If you need further assistant please find us in the Tasmota Support Chat. Github issues are for bug reporting with the template completed. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
