### ISSUE TITLE
HA won't auto detect Sonoff with Tasmota

### ISSUE THREAD

**Issue by kxkayser** [arendst/Sonoff-Tasmota#5164]
Running Tasmota 6.4.1(sonoff) and HA 0.86.4 on latest Rasbien release.  New to HA and Tasmota.  Have Sonoff mqtt working through node-red.  Have issues the SetOption19 1 command and can see the retained mqtt message:
 {"name":"Sonoff","cmd_t":"~cmnd/POWER","stat_t":"~tele/STATE","val_tpl":"{{value_json.POWER}}","pl_off":"OFF","pl_on":"ON","avty_t":"~tele/LWT","pl_avail":"Online","pl_not_avail":"Offline","uniq_id":"91C0F1_RL_1","device":{"identifiers":["91C0F1"],"name":"Sonoff","model":"Sonoff Basic","sw_version":"6.4.1(sonoff)","manufacturer":"Tasmota"}, "~":"sonoff-light/"}

via mosquitto

HA doesn't seem to be detecting the sonoff.  It does not appear in the Overview or Configuration>integrations>Configured.  Don't know where to go next.  Thanks.

**Comment by ascillato** [comment]
Hi, please address this issue in the Tasmota Support Chat. Github issues are for bug reporting. Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
