### ISSUE TITLE
Oled - not displaying SR04 sensor but other Sonoff sensors shows . 

### ISSUE THREAD

**Issue by Paulf007** [arendst/Sonoff-Tasmota#5166]
I installed an OLED to the Wemos D1 Mini. It displays info on ;
DisplayMode 1 - Date and Time
DisplayMode 2 - Only shows the "system info" - Ip hostname mac ectr.
DisplayMode 4 - Shows all the MQTT info from all my other Sonoff devices. I am assuming that it is getting it from the group topic as I didnot change it, 

How can I get it to display a SR04 sensor that is connected to the Wemos? The Sensor is working and the data is showing on the MQTT topic as well as the webpage, just not on the OLED Display.

**Comment by Jason2866** [comment]
You have to compile a version with included Display and SR04 support.
Precompiled Display version has no sensor support

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
