### ISSUE TITLE
WiFi Smart Socket with RGB LED Indicator Energy Monitoring

### ISSUE THREAD

**Issue by Sergio-tix** [arendst/Sonoff-Tasmota#5171]
Hi!!
I have such a socket, Can you add it to the firmware?:
![0000002](https://user-images.githubusercontent.com/18720428/52511473-36fb0f00-2c11-11e9-9026-430c96abba34.PNG)
![0000001](https://user-images.githubusercontent.com/18720428/52511481-3cf0f000-2c11-11e9-801a-5f25860e635a.PNG)

![0000004](https://user-images.githubusercontent.com/18720428/52511492-4417fe00-2c11-11e9-81c5-c95164155396.PNG)

What I managed to find out:
![avatto](https://user-images.githubusercontent.com/18720428/52511535-7f1a3180-2c11-11e9-8218-4268855227ae.PNG)
This chip (HJL-01 1834CYH D79829IL) is very similar to HLW8012, Perhaps this is his complete equivalent.
![powermonitor](https://user-images.githubusercontent.com/18720428/52511548-84777c00-2c11-11e9-98a7-94b4d722ec9a.PNG)

Module ESP:
![esp](https://user-images.githubusercontent.com/18720428/52511756-8aba2800-2c12-11e9-9316-cae96833f0af.PNG)
ESP8266EX, FM25F08. 
P.S. The device is extremely difficult to disassemble. Disassemble without damaging the case is impossible.

**Comment by ascillato** [comment]
Great, thanks for the detailed description. It should be possible to use Tasmota on that device.

Please, save the original firmware with esptool.py as explained in the wiki and then erase all flash and finally flash it with the latest version of the precompiled bins. 

After the initial wifi config, you can set the module as generic and set the gpios as your description. 

Please, tell us how it goes. If you need further assistant, remember that it is available the Tasmota Support Chat.

If after that it works, we can add these pictures to the Tasmota wiki. 

Thanks

**Comment by Jason2866** [comment]
Hi, in latest dev all needed GPIO pins can be selected in module generic.
Please be so kind and add -if you found it- the working config to wiki.
Thx!

**Comment by arendst** [comment]
You might want to try the below configuration.

![image](https://user-images.githubusercontent.com/11044339/52522755-ccd28080-2c89-11e9-9629-6842e6ff8f25.png)

The power monitoring chip is compatible with BL0937 (not HLW8012).

You might need to experiment with GPIO12 being HLWBL SELi (inverted)

The leds might also be selected as just plain LED1 and LED2 (LED3 is not supported).

The relay might also be inverted so in that case select Relay1i

**Comment by blakadder** [comment]
I added #5175 for the device since I own it myself and setting power monitoring in generic wasn't working quite as expected even after calibration. 
For flashing tuya-convert works fine and if you don't need the RGB light the Blitzwolf SHP module is good enough. button, power monitoring and relay work

**Comment by Sergio-tix** [comment]
> Возможно, вы захотите попробовать приведенную ниже конфигурацию.
> 
> ![образ](https://user-images.githubusercontent.com/11044339/52522755-ccd28080-2c89-11e9-9629-6842e6ff8f25.png)
> 
> Микросхема контроля мощности совместима с BL0937 (не HLW8012).
> 
> Возможно, вам придется поэкспериментировать с GPIO12, являющимся HLWBL SELi (инвертированным)
> 
> Светодиоды также могут быть выбраны как просто LED1 и LED2 (LED3 не поддерживается).
> 
> Реле также может быть инвертировано, поэтому в этом случае выберите Relay1i.

How did you install in GPIO BL0937 and HLWBL? I don't have this in the drop down menu.
P.S. Where can I get the version 6.4.1.**15** ? Is that all there?

**Comment by blakadder** [comment]
[http://thehackbox.org/tasmota/](url)

**Comment by marcobarriosfi** [comment]
> I added #5175 for the device since I own it myself and setting power monitoring in generic wasn't working quite as expected even after calibration.
> For flashing tuya-convert works fine and if you don't need the RGB light the Blitzwolf SHP module is good enough. button, power monitoring and relay work

Hello, I believe I have the same device, but I cannot get the power monitoring to work. On Aliexpress it was called "TOP-MAX Smart Plug WiFi Socket 10A 2300W EU Outlet Remote Control Smart Timing Switch Works For Amazon Alexa/Google Assistant". Any help would be highly appreciated.

**Comment by swiacek** [comment]
Configuration for plug without rgb leds

![Screenshot_20191209-213132_Chrome](https://user-images.githubusercontent.com/39152967/70470785-1f5c1380-1acc-11ea-9635-0aa5f60ebabd.jpg)

**Comment by PabloCastellano** [comment]
> You might want to try the below configuration.
> 
> ![image](https://user-images.githubusercontent.com/11044339/52522755-ccd28080-2c89-11e9-9629-6842e6ff8f25.png)
> 
> The power monitoring chip is compatible with BL0937 (not HLW8012).
> 
> You might need to experiment with GPIO12 being HLWBL SELi (inverted)
> 
> The leds might also be selected as just plain LED1 and LED2 (LED3 is not supported).
> 
> The relay might also be inverted so in that case select Relay1i

I had to switch PWM2 and PWM3 otherwise the RGB colors were not correct

**Comment by gerasimone** [comment]
Any chance to flash this smart plug without destroy the plug itself? Wireless flash works?
thanks

**Comment by Jason2866** [comment]
@gerasimone  if the plug uses the TUYA Smartlife App you can try Tuya Convert.
If the Wifi MCU is still a ESP82XX it probably works.
You can look in template repo too https://templates.blakadder.com/

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and the [Support](https://github.com/arendst/Tasmota#support-information).

Thanks.

### Support Information
See [Documentation](http://tasmota.com/) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by stosoorok** [comment]
Here is wrong template for this smart socket: https://templates.blakadder.com/avatto_OT08.html 
Save some time and use this AVATTO OT08 RGB smart socket template:
`{"NAME":"Avatto OT08","GPIO":[37,0,39,0,38,134,0,0,131,17,132,21,0],"FLAG":0,"BASE":45}`

Got it from here: https://tasmota.github.io/docs/devices/RGB-Smart-Plug-16A/
And don't forget to calibrate: https://tasmota.github.io/docs/Power-Monitoring-Calibration/

Hope it helps someone. :)
