### ISSUE TITLE
SetOption21 1 doesn't show correct V when device not under load

### ISSUE THREAD

**Issue by blakadder** [arendst/Sonoff-Tasmota#5176]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

**Describe the bug**
When setting up a power monitoring device under `Module 18` and calibrating the Voltage isn't showing the correct numbers when the device is not under load. It showed values from 0V to 8V. When I created a custom template for the device and used that everything works as expected-

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x] _Searched the problem in issues and in the wiki_
- [x] _Hardware used_ : Generic Tuya plug referenced in #5171 
- [x] _Development/Compiler/Upload tools used_ : ArduinoIDE
- [ ] _If a pre-compiled release or development binary was used, which one?_ : 
- [x] _You have tried latest release or development binaries?_ :
- [x] _Provide the output of command_``status 0`` :

**To Reproduce**
Configure `Module 18` with power monitoring and enable `SetOption21`

**Expected behavior**
Voltage shown as a number near 220V

**Comment by arendst** [comment]
Just tried on my SHP6 configured as

![image](https://user-images.githubusercontent.com/11044339/52523176-cb578700-2c8e-11e9-8469-19cd28020896.png)

which provides Voltage when powered off as expected

![image](https://user-images.githubusercontent.com/11044339/52523185-e629fb80-2c8e-11e9-9812-decbc7a4bd75.png)

So cannot replicate your situation.

**Comment by ascillato2** [comment]
Hi,

Sorry, I can't reproduce your issue. Can you do a full erase with esptool.py as explained in the wiki and flash again with the precompiled bins from development branch. Then remember to calibrate it.

**Comment by blakadder** [comment]
After configuring the device with a custom template `RGB Smart Plug` based on BlitzWolf SHP template everything works as expected.
