### ISSUE TITLE
Accessory details in Homekit help request

### ISSUE THREAD

**Issue by Bedzaa** [arendst/Sonoff-Tasmota#5186]
Hello, I am rather a amateur, but doing my home automation based on this HUB. All works great.
Detail I am looking to resolve: I am using the accessory.js file (example attached) and in Homekit details I see Default-Manufacturer, Default-SerialNumber and Default-Model. Is there any way to edit that and set proper values? See attached picture. Thank You for help.

![img_0394](https://user-images.githubusercontent.com/45871405/52533066-96027600-2d2e-11e9-9045-3e8977708f69.jpg)

[accessory_example.zip](https://github.com/arendst/Sonoff-Tasmota/files/2848795/accessory_example.zip)

**Comment by Jason2866** [comment]
Sorry we cant help. This is github issues for Tasmota. Not a forum for anything
Please ask Homekit community for help.
Thx!

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
