### ISSUE TITLE
Blitzwolf SHP6/Gosund SP111: Where can I find binary for development firmware >=6.4.1.7

### ISSUE THREAD

**Issue by heikoh81** [arendst/Sonoff-Tasmota#5187]
Hi,

I want to flash Gosund SP111 that is identical to Blitzwolf SHP6.
Wiki states:
> Attention: Please use development firmware >=6.4.1.7

Where can I find binaries of the development firmware.
I tried the development branch on Github, but on clicking the releases-link, I'm back t master branch.

Can't compile it myself, any help appreciated.

Greetings,
Heiko

**Comment by Jason2866** [comment]
Reading main page of Tasmota Github would answer ;-)
https://github.com/arendst/Sonoff-Tasmota
![image](https://user-images.githubusercontent.com/24528715/52533609-8a1ab200-2d36-11e9-9801-2068fd03eeaf.png)
http://thehackbox.org/tasmota/

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by heikoh81** [comment]
@Jason2866 
Thanks. I had visited that page before, but was irritated as there are no version numbers.
I was looking for version 6.4.17.

**Comment by Jason2866** [comment]
Thats why `>`
