### ISSUE TITLE
%06X gives 8 characters, not 6

### ISSUE THREAD

**Issue by msebald** [arendst/Sonoff-Tasmota#5189]
I am using Tasmota 6.4.1 (sonoff) on a Sonoff Basic module and noticed that the %06X variable gives 8 characters, not 6. The last 4 are twice see screenshot. In the MQTT broker I saw that it is not a display bug, the device really shows itself like the information screen also shows.

Also I noticed that in the information screen on the web admin interface I see the %06X varaible for "MQTT Topic" instead of what the firmware made out of it like for all other settings.

MQTT Settings screen:
![sonoff-mqtt-config](https://user-images.githubusercontent.com/249907/52535471-06b98a80-2d4f-11e9-8a42-2aa92ee4dc73.png)

Information screen:
![sonoff-bug](https://user-images.githubusercontent.com/249907/52535458-cb1ec080-2d4e-11e9-9cb7-d09b1ab95773.png)

**Comment by ascillato** [comment]
Hi,

>noticed that the %06X variable gives 8 characters, not 6

The %06X is a code not the amount of characters.

>I see the %06X varaible for "MQTT Topic" instead of what the firmware made out

Yes, you are right. That is as designed. Not a bug.

If you need more information, please, do not hesitate on asking here or in the Tasmota Discord Chat.

Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
