### ISSUE TITLE
Sonoff Dual R2 as a fan speed switch by using rules

### ISSUE THREAD

**Issue by pathia** [arendst/Sonoff-Tasmota#5191]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ x] Development/Compiler/Upload tools used : esptool.exe
- [x ] Hardware used : Sonof dual R2
- [ x] If a pre-compiled release or development binary was used, which one? : sonoff.bin
- [x ] You have tried latest release or development binaries? :6.4.1
- [ x] Provide the output of command ``status 0`` :
```
00:28:19 MQT: stat/sonoff-afzuiging/STATUS = {"Status":{"Module":39,"FriendlyName":["Sonoff afzuiging","Sonoff2"],"Topic":"sonoff-afzuiging","ButtonTopic":"0","Power":2,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:23:51","StartupUTC":"2019-02-10T23:04:28","Sleep":50,"BootCount":20,"SaveCount":350,"SaveAddress":"F6000"}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS2 = {"StatusFWR":{"Version":"6.4.1(sonoff)","BuildDateTime":"2018-12-24T14:41:00","Boot":7,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["myssid",""],"TelePeriod":300,"SetOption":["00008009","558180C0","00000000"]}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS4 = {"StatusMEM":{"ProgramSize":521,"Free":480,"Heap":17,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0FDAE794","000383A0","23B617CE","00003BC0"]}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS5 = {"StatusNET":{"Hostname":"Sonoff_dual_afzuiging","IPAddress":"192.168.5.15","Gateway":"192.168.5.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.5.254","Mac":"theMac","Webserver":2,"WifiConfig":1}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.3.231","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D883B0","MqttUser":"sonoff","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS7 = {"StatusTIM":{"UTC":"Sun Feb 10 23:28:19 2019","Local":"Mon Feb 11 00:28:19 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:05","Sunset":"18:03"}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS10 = {"StatusSNS":{"Time":"2019-02-11T00:28:19"}}
00:28:19 MQT: stat/sonoff-afzuiging/STATUS11 = {"StatusSTS":{"Time":"2019-02-11T00:28:19","Uptime":"0T00:23:51","Vcc":3.488,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"OFF","POWER2":"ON","Wifi":{"AP":1,"SSId":"myssid","BSSId":"mybssid","Channel":11,"RSSI":100}}}
```
Is there a way to reliably build a fan speed control using a Sonoff dual R2 ?
My intention is to wire power1 to the low speed and power2 to the high speed connection on the fan.
Assuming my fan will overheat if I wire both connections at the same time I don't want both of the connections on at the same time.
And for compatibility with Home Assistant it should have a speed and state topic for HA to subscribe to.
I already fixed myself a speed topic which the sonoff sends out its current speed using 2 rather long rules.
But I think I'm not on the right track.
Any ideas how to solve this in a clever way?

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

Yes, it is possible. You don't need rules. Use interlock feature. See wiki at commands for more information. 

If you need further assistant please find us in the Tasmota Support Chat. Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
