### ISSUE TITLE
Add support for NRF24L01 and LT8900

### ISSUE THREAD

**Issue by qingz2004** [arendst/Sonoff-Tasmota#5194]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
Need a bridge to support 2.4G RF communication used by MiLight and other product.

**Describe the solution you'd like**
Add SPI for NRF24L01 or LT8900.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
https://github.com/sidoh/esp8266_milight_hub

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Why?
You can use the esp8266_milight_hub to communicate to Milight.
Since the esp8266_milight_hub uses mqtt too, no hassle to use all in a Home Automation system.

**Comment by qingz2004** [comment]
I'm currently using that project, but I'd like to use the spare IOs from the same NodeMCU for something else. And I prefer to use the same Tasmota firmware for all of my esp8266 devices.
I'm looking for the same solution as Sonoff 433M RF bridge.

**Comment by blakadder** [comment]
look at openmqttgateway then

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
