### ISSUE TITLE
MqttFingerprint1 cannot be unset to disable TLS

### ISSUE THREAD

**Issue by andreas-bulling** [arendst/Sonoff-Tasmota#5198]
Hi,

if a node is configured for MQTT TLS by setting `MqttFingerprint1` and the right `port` (8883) it cannot be reset to normal mode (i.e. TLS cannot be disabled): While the port can be set to 1883, `MqttFingerprint1` cannot be unset.

**Comment by arendst** [comment]
Once compiled with TLS there is no possibility to connect without TLS as it uses TLS specific wifi libraries.

So it's either a TLS binary or a non-TLS binary.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
