### ISSUE TITLE
reaction time switch

### ISSUE THREAD

**Issue by johannesbonn** [arendst/Sonoff-Tasmota#5205]
Hello,

I am using a wemo d1 mini with tasmota 6.4.1.15. I have 4 switches wired and related to relays for different topic.
My question:
The reaction time of the switches seems to be very slow. The console only show a trigger every 2-3 seconds. Can I reduce the reaction time. Thought about SetOption13 but that makes no difference.

Thank you for your help.

**Comment by ascillato** [comment]
Use setoption1

**Comment by ascillato** [comment]
Use sleep 0

**Comment by andrethomas** [comment]
> The console only show a trigger every 2-3 seconds

The console only updates in 2-second intervals iirc.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
