### ISSUE TITLE
Sonoff S31 restarts every 2 minutes aprox

### ISSUE THREAD

**Issue by rjd2783** [arendst/Sonoff-Tasmota#5209]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x ] Development/Compiler/Upload tools used :arduino ide, platformio
- [x ] Hardware used : S31
- [ ] If a pre-compiled release or development binary was used, which one? :
- [x ] You have tried latest release or development binaries? :

- [x
[Sonoff S31 continuous restarts.txt](https://github.com/arendst/Sonoff-Tasmota/files/2858043/Sonoff.S31.continuous.restarts.txt)

 ] Provide the output of command ``status 0`` :what is status 0
```
STATUS 0 OUTPUT HERE
```
[Sonoff S31 continuous restarts.txt](https://github.com/arendst/Sonoff-Tasmota/files/2858051/Sonoff.S31.continuous.restarts.txt)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

If you have no wifi configured it is a normal behaviour. Please, follow the config steps of the wiki or find us for live Support in the Tasmota Support Chat. Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
