### ISSUE TITLE
Option for DisplayMode 2 to hidden Topic name for local Sensor value.

### ISSUE THREAD

**Issue by wongnam** [arendst/Sonoff-Tasmota#5212]
May i know if any Option for DisplayMode 2 to hidden topic name for local sensor value ?
it's no need to have topic name for local sensor information to save display space to show the important value.

![image](https://user-images.githubusercontent.com/36041520/52706882-fc022e00-2fb8-11e9-8475-c83ffbc10ed7.png)

**Comment by arendst** [comment]
There is none but this is a good idea.

Will follow up (someday).

**Comment by andrethomas2** [comment]
Closing this issue as it the necessary changes made for this request has been merged into development.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
