### ISSUE TITLE
Custom Template and WebUI GPIO display

### ISSUE THREAD

**Issue by blakadder** [arendst/Sonoff-Tasmota#5222]
It might be the lack of time spent but afaik when I activate a custom template the WebUI module configuration page shows all the defined GPIO pins with a dropdown menu although none of the pins is set to 255. 
That might cause user confusion and raised issues. 

I propose to either hide the templated gpios showing only 255 user defined one as in the all other supported modules. 
While at the topic is it possible to have the webui not show the recommended pin assignments when module 0 is selected to also reduce user confusion (just like module 18 adds D# pin information, remove any information apart from GPIO#)

**Comment by arendst** [comment]
Showing template GPIOs was a design decision I made. I will re-consider.

Removing the recommended pin assignments is an option to consider too but as the user template is just another template I think it makes sense to have the same info as the inbuilt templates.

**Comment by arendst** [comment]
Ah, just did some tests and I now know why I did it that way. 

As the template is updated with user defined GPIOs the next time the module page is pulled up it will not allow to make a changes to a now defined GPIO.

I will have to dig deeper. WIll roll back the latest change.

**Comment by Jason2866** [comment]
Mhh, i liked the way before this change to create Templates via WebConfig
It was possible to config in Module generic (0) all the GPIOs you want need.
After that just typing in WebConsole `Template 0` and i got the Template config.
Now this isnt possible anymore i always get 255...

**Comment by arendst** [comment]
Then when you re-visit the module web page the template was changed with the latest module changes. I agreed with @blakadder that it might confuse users.

That's why I started to come up with a new menu:

![image](https://user-images.githubusercontent.com/11044339/52804194-e279e880-3083-11e9-9d6f-314ad4c81600.png)

Work in progress but this allows to change the template online without the user getting confused about a dynamic template.

So pls hold on, I'm working on it but I need time to cram it all in no code space.

**Comment by Jason2866** [comment]
Ahh, thx
Had the fear to loose the nice possibility to do template config via webfrontend.
**No rush** if this feature will be there again :-)

**Comment by blakadder** [comment]
Yep, that looks more usable and very straightforward for a majority of users

**Comment by arendst** [comment]
Initial released today. Working on tuning.

**Comment by Jason2866** [comment]
If i define a template and use it afterwards the defined GPIOS are not visible.
Is it the way you want, or what you are going to tune?
![image](https://user-images.githubusercontent.com/24528715/52911982-682bad00-32ab-11e9-8cd4-2022b438de2d.png)

![image](https://user-images.githubusercontent.com/24528715/52911993-98734b80-32ab-11e9-843b-2e825caeffe2.png)

**Comment by arendst** [comment]
This is the way I want it to be.

As in embedded templates, defined GPIOs are not visible in the module menu and cannot be changed by the user.

**Comment by Jason2866** [comment]
Thx, for explaining

**Comment by blakadder** [comment]
![image](https://user-images.githubusercontent.com/5904370/52912996-69fc6d00-32b9-11e9-9b62-1aab825bd37b.png)

Device doesn't restart after clicking save template

**Comment by blakadder** [comment]
![image](https://user-images.githubusercontent.com/5904370/52913001-89939580-32b9-11e9-956d-2486b023d2e9.png)
Device doesn't restart after clicking save in Configure Template

**Comment by wongnam** [comment]
> Device doesn't restart after clicking save in Configure Template
Confirm, I also encounter this issue. It will be happen when i change the name.

![image](https://user-images.githubusercontent.com/36041520/52916942-0ce3d400-3318-11e9-8c47-1ed4a4e54b36.png)

**Comment by lz2ddl** [comment]
I can not add new bulbs (for example, 4 or 5) to Hue Bridge. What to do?

**Comment by arendst** [comment]
Only one WS2812 strip is supported.

**Comment by lz2ddl** [comment]
A normal RGB strip with PCA9685?

**Comment by ascillato** [comment]
@lz2ddl

Sorry, you are offtopic of the current thread. Please, address your questions to the Tasmota Support Chat. Will be better and more dynamic. Thanks. 

See readme for the link to the chat.

**Comment by arendst** [comment]
In that case open a new issue dedicated to your problem as this is another issue.
