### ISSUE TITLE
Teckin E27 RGB successfully flashed but ..... ?

### ISSUE THREAD

**Issue by malcomxcia** [arendst/Sonoff-Tasmota#5224]
Hello !

I have an Teckin E27 RGB (Tuya Device) successfully flashed. 

The MagicHome Module works but not all, I can't set the Blue Color ..... Where i can find out what the Problem is ?

Great Work on Tasmota an have a nice Day ;)
Malcom

**Comment by ascillato** [comment]
Hi, please complete the troubleshooting template. Thanks

**Comment by ascillato2** [comment]
Hi, please for support use the Tasmota Support Chat. Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
