### ISSUE TITLE
Sonoff Ghost Switching Correct Retain Settings

### ISSUE THREAD

**Issue by yasas100** [arendst/Sonoff-Tasmota#5228]
My Sonoff randomly switches on when it disconnects from the wifi. I believe my setting are correct in HA. It is connected to a switch and I am even using a low pass filter to avoid hardware ghosting. I have posted screenshots from my console below. Thanks in advance

MQT: Attempting connection...

20:05:53 MQT: Connected

20:05:53 MQT: tele/sonoff1/LWT = Online (retained)

20:05:53 MQT: cmnd/sonoff1/POWER =

20:05:53 MQT: stat/sonoff1/RESULT = {"POWER":"ON"}

20:05:53 MQT: stat/sonoff1/POWER = ON (retained)

![image](https://user-images.githubusercontent.com/39997689/52811968-a890ee00-3053-11e9-92f5-dddb9268fe7b.png)

![image](https://user-images.githubusercontent.com/39997689/52811983-acbd0b80-3053-11e9-8ede-d96207a8418d.png)

![image](https://user-images.githubusercontent.com/39997689/52811991-b0e92900-3053-11e9-913f-2b883da5c110.png)

**Comment by ascillato2** [comment]
Hi,

You have retained messages in your broker. You need to delete the broker database so as to solve your issue. 

If you need further assistant with that, please find us in the Tasmota Support Chat. Thanks. 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by HobbytronicsPK** [comment]
Have a look on to [Ghost / Random Switching on Sonoff Devices (MQTT Retained)](https://blog.hobbytronics.pk/sonoff-tasmota-tips-tricks/#Ghost-Random-Switching)
