### ISSUE TITLE
S20 Socket: Stuck button causes eeprom reset

### ISSUE THREAD

**Issue by faljse** [arendst/Sonoff-Tasmota#523]
On my S20 units the button can get stuck easily in pressed state, causing tasmota to reset the eeprom settings.

Not sure how this could be solved - Maybe the reset function could be enabled during     
 powerup only (for plug-able units)

**Comment by arendst** [comment]
When in production mode you could use command ``SetOption1 1`` to disable setup features. In that case the eeprom won't be reset if the button is stuck but it might send a mqtt message depending on how you configured button hold feature.
