### ISSUE TITLE
RF Bridge cannot be reset using button

### ISSUE THREAD

**Issue by ByteJunk** [arendst/Sonoff-Tasmota#5230]
**Describe the bug**
Flashed 433 RF Bridge cannot be reset using button, not even long (40s) press works.

This was reported previously as  #4682 but closed without a proper solution, IMHO.

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x] _Searched the problem in issues and in the wiki_
- [x] _Hardware used_ : Sonoff RF Bridge 433 r2
- [x] _Development/Compiler/Upload tools used_ : VSCode+PlatformIO
- [x] _If a pre-compiled release or development binary was used, which one?_ : selfcompiled env_default = sonoff
- [x] _You have tried latest release or development binaries?_ : 6.4.1 release
- [ ] _Provide the output of command_``status 0`` :
```
STATUS 0 OUTPUT HERE - DO NOT DELETE THE MARKERS ABOVE AND BELOW THIS LINE
```

**To Reproduce**
_Steps to reproduce the behavior:_
Flash bridge, attempt to reset it by pressing button.

**Expected behavior**
Behaviour described @ https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage

**Comment by ascillato2** [comment]
Hi

Please, let's try not to duplicate issues so it is easier to follow the thread for anyone searching this. 

Reopening older issue as requested.
