### ISSUE TITLE
Working device - eMylo SS-8839-02

### ISSUE THREAD

**Issue by sqerk** [arendst/Sonoff-Tasmota#5232]
I would just like to add that these devices work.
Used https://github.com/arendst/Sonoff-Tasmota/wiki/CE-Smart-Home---LA-WF3-Wifi-Plug-(TYWE2S) for the soldering guide.
But no need to change settings flashed the same firmware and work the same as Sonoff S31

**Comment by blakadder** [comment]
you're free to add the information in the wiki, preferably with an entry in **Other devices** which links to the page you posted which you can expand with the name and link to the device

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by andylebedev** [comment]
not working at all with s31 template, for me it works with this template https://blakadder.github.io/templates/emylo_XL9251WI.html
