### ISSUE TITLE
RF Bridge 433 mqtt commands

### ISSUE THREAD

**Issue by IamStadam** [arendst/Sonoff-Tasmota#5235]
Gentlemen, help set up.

There is an “extremely simple” system.
Synology-Docker-homebridge-mosquitto-mqttthing- Sonoff RF Bridge 433 Tasmota (and several different sonoff relays working through the homebridge-ewelink-max plugin)
The problem is that homebridge-ewelink-max and the like do not see Sonoff RF Bridge 433. I had to change it to Tasmota in order to manage it by mqtt.
The mosquitto log has a connection to RF Bridge 433.

The task is extremely simple - just send two signals from RF Bridge 433, RfKey1 to open, RfKey2 to close. The keys were trained by the command RfKey <x> 2.

What needs to be done in config.json? For me, this has become a problem. I`m fully noob. Please, help.

P.S. Tried something like this ...
`
"accessory": "mqttthing",
"type": "switch",
"name": "BRIDGE",
"url": "192.168.88.39:1883",
"topics": {
"getOn": "cmnd/sonoff_bridge/RfKey1"
"setOn": "cmnd/sonoff_bridge/RfKey1"
`

**Comment by ascillato2** [comment]
Hi,

Please, for support use the Tasmota Support Chat. Github issues are for bug reporting. Thanks. 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
