### ISSUE TITLE
How ZMPT101B AC Voltage Sensor module works on Tasmota (?)

### ISSUE THREAD

**Issue by adharyanto** [arendst/Sonoff-Tasmota#5236]
**Have you look for this feature in other issues and in the wiki?**

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Not supported

**Comment by adharyanto** [comment]
Will it be supported (planned to be) in the next release of Tasmota?

**Comment by adharyanto** [comment]
Will it be supported (planned to be) in the next release of Tasmota?

**Comment by andrethomas** [comment]
> Will it be supported (planned to be) in the next release of Tasmota?

Most likely one of the developers active on this project will at some point in the future add support for it but for now most people are just using the PZEM modules.

Don't hold your breath though... serious risk of suffocation.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by Zodiark99BR** [comment]
anything aboout this case ?

**Comment by barbudor** [comment]
This is an analog sensor
It can be directly supported using an ADC gpio in ADC Range mode with proper Adcparams

If you want help, open a discussion.
Issues are not for that
