### ISSUE TITLE
CounterDebounce command without function

### ISSUE THREAD

**Issue by Stalkk** [arendst/Sonoff-Tasmota#524]
Hi,

The CounterDebounce command ignores parameter. eg. 
http://sonoff/cm?cmnd=CounterDebounce%20200 returns 
RESULT = {"CounterDebounce":0}, where 0 - the last set value. 

To set CounterDebounce i have to use CounterDebounce3 command.
http://sonoff/cm?cmnd=CounterDebounce3%20300 returns 
RESULT = {"CounterDebounce":300}

If i try to send CounterDebounce1 or CounterDebounce2 it have no impact- Probably because i have only Counter3 assigned to GPIO in settings. 

This behavior is the same for mqtt and http commands.

**Comment by arendst** [comment]
You gave already the correct answer by suggesting the 3 suffix.

I will remove the test for active GPIO in the next release so making command CounterDebounce work as expected.
