### ISSUE TITLE
MQTT not connecting

### ISSUE THREAD

**Issue by cschwarz007** [arendst/Sonoff-Tasmota#5240]
Dear community,

My Shelly 1 does no longer connect to my MQTT broker. Connecting to the MQTT broker from other clients works fine. It is mosquitto on RPi.

This is the error I am getting constantly:
`
21:00:02 MQT: Attempting connection...
21:00:02 MQT: Connect failed to mqtt.janettundchristian.de:1883, rc 4. Retry in 10 sec
`
Don't worry - the domain resolves in my internal nework locally only and is not reachable from outside...

And this is the output of status 0
`20:59:38 RSL: stat/sonoff-2288/STATUS = {"Status":{"Module":46,"FriendlyName":["sonoff-2288"],"Topic":"sonoff-2288","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
20:59:38 RSL: stat/sonoff-2288/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:10:09","StartupUTC":"2019-02-15T19:49:29","Sleep":50,"BootCount":13,"SaveCount":160,"SaveAddress":"F4000"}}
20:59:38 RSL: stat/sonoff-2288/STATUS2 = {"StatusFWR":{"Version":"6.4.0(knx)","BuildDateTime":"2018-12-27T11:08:17","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
20:59:38 RSL: stat/sonoff-2288/STATUS3 = {"StatusLOG":{"SerialLog":3,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["FritzHOME_DE",""],"TelePeriod":300,"SetOption":["00008009","558180C0","00000000"]}}
20:59:38 RSL: stat/sonoff-2288/STATUS4 = {"StatusMEM":{"ProgramSize":541,"Free":460,"Heap":18,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540EF","FlashMode":3,"Features":["00000809","1FDAE594","240383B0","23B617CE","00003BC0"]}}
20:59:38 RSL: stat/sonoff-2288/STATUS5 = {"StatusNET":{"Hostname":"sonoff-2288-2249","IPAddress":"192.168.101.78","Gateway":"192.168.101.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.101.1","Mac":"80:7D:3A:5B:A8:C9","Webserver":2,"WifiConfig":4}}
20:59:38 RSL: stat/sonoff-2288/STATUS6 = {"StatusMQT":{"MqttHost":"mqtt.janettundchristian.de","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_5BA8C9","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
20:59:38 RSL: stat/sonoff-2288/STATUS7 = {"StatusTIM":{"UTC":"Fri Feb 15 19:59:38 2019","Local":"Fri Feb 15 20:59:38 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:58","Sunset":"18:10"}}
20:59:38 RSL: stat/sonoff-2288/STATUS10 = {"StatusSNS":{"Time":"2019-02-15T20:59:38","Switch1":"OFF"}}
20:59:38 RSL: stat/sonoff-2288/STATUS11 = {"StatusSTS":{"Time":"2019-02-15T20:59:38","Uptime":"0T00:10:09","Vcc":3.540,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"FritzHOME_DE","BSSId":"08:96:D7:1F:76:B8","Channel":1,"RSSI":66}}}
`
Can anyone help me find the error?

Many thanks!

**Comment by ascillato** [comment]
Hi,

You can try to erase all settings using command reset 5 and config again.

For support there is available the Tasmota Support Chat. Github issues are for bug reporting. Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
