### ISSUE TITLE
OTA support for Xiaomi Philips LED Bulb (feature request)

### ISSUE THREAD

**Issue by pcmester** [arendst/Sonoff-Tasmota#5249]
The Xiaomi-Philips LED bulb is great for it's price, and it can be used with Tasmota. The problem is, that unfortunately, the bulb can't be opened without destroying it. 

There is a python library that allows to control the bulb, and this is also allows updates. I can't figure out how can I update it, but if someone also interested in, there is the GitHub repository: [https://github.com/rytilahti/python-miio]()

**Comment by TimelessNL** [comment]
Is this ever going to work?
[It seems that](https://github.com/arendst/Sonoff-Tasmota/issues/3055?_pjax=%23js-repo-pjax-container#issuecomment-465968986) Xiaomi uses the RTOS_SDK from espressif which is different than NONOS_SDK that Tasmota uses.
