### ISSUE TITLE
MaxPowerRetry configurable via MQTT or serial

### ISSUE THREAD

**Issue by ionciubotaru** [arendst/Sonoff-Tasmota#525]
`#define MAX_POWER_RETRY        5            // Retry count allowing agreed power limit overflow (Pow)`

This parameter can be changed only in `sonoff.ino` 
Please allow configuration via MQTT or serial like `MaxPowerHold` or `MaxPowerWindow`

**Comment by arendst** [comment]
Will be implemented in next release as command ``SetOption33 1..250``

**Comment by tobi320** [comment]
How can I ensure that it is not switched on again after it has been switched off? Unfortunately, setoption33 0 does not exist
