### ISSUE TITLE
MQTT Socket Errors

### ISSUE THREAD

**Issue by JacoFourie** [arendst/Sonoff-Tasmota#5263]
**Describe the bug**
MQTT socket errors result in reconnects on Mosquitto. I have 4 sonoffs and they all do this. I also have some other ESP8266 and ESP32 devices that I wrote the code for myself and they stay connected all the time without the socket errors from Mosquitto.

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [ ] _Searched the problem in issues and in the wiki_
- [X] _Hardware used_ : Sonoff-Basic and Touch
- [ ] _Development/Compiler/Upload tools used_ : OTA
- [ ] _If a pre-compiled release or development binary was used, which one?_ :
- [ ] _You have tried latest release or development binaries?_ :
- [ ] _Provide the output of command_``status 0`` :
```
21:58:36 DNS: Initialized
21:58:37 MQT: Attempting connection...
21:58:37 MQT: Connected
21:58:37 MQT: tele/LoungeLightStand/LWT = Online (retained)
21:58:37 MQT: cmnd/LoungeLightStand/POWER = 
22:01:12 MQT: tele/LoungeLightStand/STATE = {"Time":"2019-02-17T22:01:12","Uptime":"4T07:44:59","Vcc":3.450,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"ON","Wifi":{"AP":1,"SSId":"Pandora-LR","BSSId":"82:2A:A8:BB:06:FE","Channel":1,"RSSI":78}}
22:02:00 MQT: tele/LoungeLightStand/UPTIME = {"Time":"2019-02-17T22:02:00","Uptime":"4T07:45:47"}
22:03:13 MQT: Attempting connection...
22:03:13 MQT: Connect failed to 10.64.9.34:1883, rc -2. Retry in 10 sec
22:03:16 DNS: Initialized
22:03:27 MQT: Attempting connection...
22:03:27 MQT: Connected
22:03:27 MQT: tele/LoungeLightStand/LWT = Online (retained)
22:03:27 MQT: cmnd/LoungeLightStand/POWER = 
22:05:23 DNS: Initialized
22:05:24 MQT: Attempting connection...
22:05:24 MQT: Connected
22:05:24 MQT: tele/LoungeLightStand/LWT = Online (retained)
22:05:24 MQT: cmnd/LoungeLightStand/POWER = 
22:06:12 MQT: tele/LoungeLightStand/STATE = {"Time":"2019-02-17T22:06:12","Uptime":"4T07:49:59","Vcc":3.451,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"ON","Wifi":{"AP":1,"SSId":"Pandora-LR","BSSId":"82:2A:A8:BB:06:FE","Channel":1,"RSSI":78}}
22:09:32 DNS: Initialized
22:09:33 MQT: Attempting connection...
22:09:33 MQT: Connected
22:09:33 MQT: tele/LoungeLightStand/LWT = Online (retained)
22:09:33 MQT: cmnd/LoungeLightStand/POWER = 
22:11:12 MQT: tele/LoungeLightStand/STATE = {"Time":"2019-02-17T22:11:12","Uptime":"4T07:54:59","Vcc":3.450,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"ON","Wifi":{"AP":1,"SSId":"Pandora-LR","BSSId":"82:2A:A8:BB:06:FE","Channel":1,"RSSI":78}}
22:13:24 MQT: Attempting connection...
22:13:24 MQT: Connect failed to 10.64.9.34:1883, rc -2. Retry in 10 sec
22:13:25 WIF: Connecting to AP1 Pandora-LR in mode 11N as LoungeLightStand-6082...
22:13:29 WIF: Connected
22:13:29 DNS: Initialized
22:13:40 MQT: Attempting connection...
22:13:40 MQT: Connected
22:13:40 MQT: tele/LoungeLightStand/LWT = Online (retained)
22:13:40 MQT: cmnd/LoungeLightStand/POWER = 
22:15:44 DNS: Initialized
22:15:45 MQT: Attempting connection...
22:15:45 MQT: Connected
22:15:45 MQT: tele/LoungeLightStand/LWT = Online (retained)
22:15:45 MQT: cmnd/LoungeLightStand/POWER = 
22:16:12 MQT: tele/LoungeLightStand/STATE = {"Time":"2019-02-17T22:16:12","Uptime":"4T07:59:59","Vcc":3.466,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"ON","Wifi":{"AP":1,"SSId":"Pandora-LR","BSSId":"82:2A:A8:BB:06:FE","Channel":1,"RSSI":72}}
22:21:12 MQT: tele/LoungeLightStand/STATE = {"Time":"2019-02-17T22:21:12","Uptime":"4T08:04:59","Vcc":3.466,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"ON","Wifi":{"AP":1,"SSId":"Pandora-LR","BSSId":"82:2A:A8:BB:06:FE","Channel":1,"RSSI":76}}
22:26:09 WIF: Connecting to AP1 Pandora-LR in mode 11N as LoungeLightStand-6082...
22:26:12 RSL: tele/LoungeLightStand/STATE = {"Time":"2019-02-17T22:26:12","Uptime":"4T08:09:59","Vcc":3.451,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"ON","Wifi":{"AP":1,"SSId":"Pandora-LR","BSSId":"82:2A:A8:BB:06:FE","Channel":13,"RSSI":100}}
22:26:13 WIF: Connected
22:26:13 DNS: Initialized
22:26:14 MQT: Attempting connection...
22:26:14 MQT: Connected
22:26:14 MQT: tele/LoungeLightStand/LWT = Online (retained)
22:26:14 MQT: cmnd/LoungeLightStand/POWER = 
22:27:13 DNS: Initialized
22:27:13 MQT: Attempting connection...
22:27:13 MQT: Connected
22:27:13 MQT: tele/LoungeLightStand/LWT = Online (retained)
22:27:13 MQT: cmnd/LoungeLightStand/POWER = 
22:28:17 MQT: Attempting connection...
22:28:17 MQT: Connect failed to 10.64.9.34:1883, rc -2. Retry in 10 sec
22:28:20 DNS: Initialized
22:28:30 MQT: Attempting connection...
22:28:30 MQT: Connected
22:28:30 MQT: tele/LoungeLightStand/LWT = Online (retained)
22:28:30 MQT: cmnd/LoungeLightStand/POWER = 
```

**To Reproduce**

**Expected behavior**
The sonoff should stay connected as the WiFi signal is above 80%. Why does it loose MQTT connection ?

**Screenshots**

![image](https://user-images.githubusercontent.com/17771641/52919444-334f4280-330b-11e9-925b-706057a39bbc.png)

**Additional context**

**Comment by ascillato** [comment]
Hi, please share the status 0 output

**Comment by ascillato** [comment]
The issue is a known problem from core 2.4.2 and 2.5.0 with some brands of routers.

If you use core 2.3.0 you won't have that issue.

Anyway, which core and which mqtt library do you use in your own firmwares?

**Comment by ascillato** [comment]
Tasmota precompiled bins on core 2.3.0:

http://thehackbox.org/tasmota/020300/

**Comment by JacoFourie** [comment]
Hi. I am running 6.4.1. Should I replace 6.4.1 with 2.3.0 ?

**Comment by ascillato** [comment]
Please, use latest Tasmota with core 2.3.0: http://thehackbox.org/tasmota/020300/

Which arduino core do you use in your own firmwares that don't disconnects.

**Comment by JacoFourie** [comment]
I am using the ESP32 core v 1 not 1.0.1

https://github.com/espressif/arduino-esp32

**Comment by ascillato** [comment]
Ok, but ESP32 is another chip and core not related to Tasmota nor Arduino esp8266 core. 

The issue is just with any firmware compiled with Arduino core 2.4.2 or 2.5.0 and just with about the 3% of the brands of routers.

You should test the latest Tasmota precompiled with Arduino core 2.3.0

The issue is outside Tasmota software. Is in the Arduino core. Specifically in the SDK libraries for the esp8266 chip

**Comment by JacoFourie** [comment]
How do I know if the basic or touch is 4 or 1 M. What should I use ?

**Comment by ascillato** [comment]
Use all the time 1M and you will be ok.

**Comment by ascillato** [comment]
Remember to erase all flash with esptool.py as explained in the wiki and flash again with the precompiled bins from development so as to avoid any issue of corrupt data left in the flash.

**Comment by JacoFourie** [comment]
So can I not do it over the air ? The devices are in the roof

**Comment by JacoFourie** [comment]
Can I use reset 5 after I flash with over the air ?

**Comment by ascillato** [comment]
Yes, you can. Erasing all flash is a recommendation to avoid further issues. 

If you can't do the serial flashing, you can do the OTA. But, if after you experiment some weird issues, just do the reset 5. If that don't solve your issue, do a full erase and flash.

**Comment by JacoFourie** [comment]
OK and I will give it a go. Thanks. I will close the issue once I tested it.

**Comment by ascillato** [comment]
In your first post you said that you have your own firmware in an esp8266 that doesn't disconnects from mqtt. That firmware you have compiled using core 2.3.0? And which mqtt library did you use?

**Comment by JacoFourie** [comment]
The one that you configure in the Arduino IDE. 2.3.0 is the one I used I think when I complied the code.
I am not using any new 8266. I am now using ESP32. So I have not updated the code running on the older 8266 chips.

**Comment by ascillato** [comment]
Ok. That explain why it worked in your case.
Core 2.3.0 have no issues with mqtt sockets.
Which brand is your wifi router?

**Comment by JacoFourie** [comment]
I have 3 different AP in my house. I have Microtik , Ubiquiti and Tenda.
How do I know what core is running on the Sonoff. I can see the version of Tasmota but how do I know the core that was used ?

**Comment by ascillato** [comment]
Go to information menu. There it is.

Also you can go to the Tasmota console and type `status 0`

That will give you all the config of Tasmota.

**Comment by JacoFourie** [comment]
Aaa OK cool. Must say this software rocks. The amount of stuff you have put into such a small chip is amazing. Well done to all involved !!!

**Comment by ascillato** [comment]
Microtik has proven to have zero issues with Tasmota. Ubiquiti has some issues with core 2.4.2. I don't know if with latest core 2.5.0 it has issues. May be not.

But anyway with core 2.3.0 you will be fine.

**Comment by JacoFourie** [comment]
OK I flashed 3 of them with the 2.3.0 core. Will let it run. Thanks so much for the help !!

**Comment by mmatesic01** [comment]
If I use 2.3.0 version 6.4.1 from http://thehackbox.org/tasmota/release/020300/, then I have no such problems as described in the beginning of this thread.
But if I use 2.3.0 version 6.4.17 from http://thehackbox.org/tasmota/020300/, then I have the exact problems.

All the sonoff devices which were upgraded to 6.4.17 started having such problems. The rest which stayed on 6.4.1, were stable.

**Comment by JacoFourie** [comment]
Is 6.4.1 not the latest? Where did you get 6.4.17 from ?

**Comment by ascillato** [comment]
@JacoFourie

6.4.1 is the latest master release
6.4.1.17 is the latest development that will become the next master release.

The differences are new features and bug fixing that are being tested before making a new master release. The changelog is available. See readme for the link.

**Comment by ascillato** [comment]
@mmatesic01

There are no wifi changes between 6.4.1 core 2.3.0 and 6.4.1.17 core 2.3.0

So, if you are having wifi issues may be it is related to corrupt data in your flash. Try reset 5 and if that don't solve your issue do a full erase with esptool.py as explained in the wiki and flash again with the precompiled bins from development branch. Thanks

**Comment by JacoFourie** [comment]
OK. All seems fine with my 3 units after the 2.3.0 version.
