### ISSUE TITLE
How to use ir remote?

### ISSUE THREAD

**Issue by lijinqiu1** [arendst/Sonoff-Tasmota#5270]
Sorry, I have just begin to study how to use the project!
I want to use the IR remote function, But I can not find the "IRsend" and "IR recv" in the Configure.
I use the last "sonoff.bin"!!

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Hi,

For support it is better and more dynamic to use the Tasmota Support Chat. 

Github issues are for bug reporting. Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
