### ISSUE TITLE
Switch button unpredictable behaviour when MQTT is not connected

### ISSUE THREAD

**Issue by doppiaemme** [arendst/Sonoff-Tasmota#528]
Hi

when the MQTT broker is not connected the behaviour of the hardware switch button is very unpredictable. Sometimes it works sometimes it doesn't. 
In those situations where the broker is not available (f.i. server offline) it would be important to have a reliable HW switch. Any well known way to make it more reliable and why it does this?

Massimo

**Comment by arendst** [comment]
Search these issues where it has been discussed many times.

Main reason is while trying to connect to the lost MQTT server TCP communication could take up to three seconds before returning to Tasmota leading to your observation.

See command ``MqttRetry`` and get a solid MQTT service.
