### ISSUE TITLE
Digoo DG-HOSA Smart 433MHz Wireless Household Carbon Monoxide Sensor to Sonoff RF Bridge

### ISSUE THREAD

**Issue by spider7611** [arendst/Sonoff-Tasmota#5280]
Hi,

I have a CO sensor and on Sonoff RF Bridge with RfRaw AAA655 receive a codes when I push the test button:
`12:25:07 CMD: Rfraw AAA655 12:25:07 MQT: stat/sonoff_rf/RESULT = {"RfRaw":"ON"} 12:25:07 MQT: tele/sonoff_rf/RESULT = {"RfRaw":{"Data":"AAA055"}} 12:25:21 MQT: tele/sonoff_rf/RESULT = {"RfRaw":{"Data":"AAA604090F350355"}} 12:25:26 MQT: tele/sonoff_rf/RESULT = {"RfRaw":{"Data":"AAA604090F350355"}} 12:25:32 MQT: tele/sonoff_rf/RESULT = {"RfRaw":{"Data":"AAA604090F350355"}} 12:25:32 MQT: tele/sonoff_rf/RESULT = {"RfRaw":{"Data":"AAA604090F350355"}} 12:25:33 MQT: tele/sonoff_rf/RESULT = {"RfRaw":{"Data":"AAA604090F350355"}} 12:25:34 MQT: tele/sonoff_rf/RESULT = {"RfRaw":{"Data":"AAA604090F350355"}}`

In normal mode about 5x or more push after received only one code like this:
`14:50:19 MQT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":13490,"Low":530,"High":1580,"Data":"0F3503","RfKey":"None"}}` 

Is it possible to edit tasmota firmware to working good with this CO sensor? And after every test button push receive the code?

**Comment by Jason2866** [comment]
No, since we dont have the device.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
