### ISSUE TITLE
sonoff dualr2

### ISSUE THREAD

**Issue by junrt** [arendst/Sonoff-Tasmota#5282]
After the dual r2 restarts after wifi sleep toggle 2 turns on, for no reason.
21:33:41 MQT: stat/sonoff/RESULT = {"POWER2":"ON"}
21:33:41 MQT: stat/sonoff/POWER2 = ON

is this a default setting or am I doing something wrong ?
Running on:

Program Version | 6.4.1(sonoff)
Build Date & Time 2018-12-24T14:41:00
Core/SDK Version 2_4_2/2.2.1(cfd48f3)

**Comment by ascillato** [comment]
Hi, please, complete the troubleshooting template. Thanks

**Comment by ascillato2** [comment]
Closing this issue as there is no feedback. When you have time, please complete the troubleshooting template. Thanks
