### ISSUE TITLE
Tuya dimmer - Trying to set dimming level without turning on light

### ISSUE THREAD

**Issue by ericdes** [arendst/Sonoff-Tasmota#5284]
Hi, first I'd like to thank you for this excellent work that has improved a lot over time!

I understand there is a memory feature in the Tuya dimmer since the light turns backs on at its previous brightness level.

My experience so far was to emit an MQTT brightness command to a light being off, **which results in turning it on** at the specified brightness level. 

I just would like to change the value of the brightness memory in the Tuya dimmer while not changing the power state -- i.e. keep the light off.

**Comment by Jason2866** [comment]
Tried?
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#SetOption20

**Comment by ericdes** [comment]
Indeed setting option 20 did the trick for me.

Thank you!

**Comment by ascillato2** [comment]
Closing issue as it has been solved.
