### ISSUE TITLE
Cant enter via Phone with hostname to UI

### ISSUE THREAD

**Issue by hwarang098tkd** [arendst/Sonoff-Tasmota#5285]
So i have alot of switches sonoff Touch
I CANT enter via my phone with hostname but only with IP adr
From my desktop i can.

```
11:30:19 CMD: hostname
11:30:19 MQT: stat/sonoff_t_9/RESULT = {"Hostname":"livingroom_relay"}
11:35:39 CMD: status 5
11:35:39 MQT: stat/sonoff_t_9/STATUS5 = {"StatusNET":{"Hostname":"livingroom_relay","IPAddress":"192.168.1.2","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.254","Mac":"60:01:94:84:CE:82","Webserver":2,"WifiConfig":5}}
```

In my phones wifi settings

![52598965_2172237056422788_4184181621076787200_n](https://user-images.githubusercontent.com/28574054/53077612-06618200-34fb-11e9-906e-05162de42d1d.png)
 
i tried http://livingroom_relay and http://livingroom_relay.local

What i have to do?
thnx in advance

**Comment by netpok** [comment]
To use it via local DNS resolution, you have to use your router as DNS server, based on your status message it is `192.168.1.254`:
`...255.0","DNSServer":"192.168.1.254","Mac":"60:0...`

To use it via mDNS resolution, you have to enable mDNS on the device by executing `SetOption55 1` in the console as documented on the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#Setoption55).

**Comment by hwarang098tkd** [comment]
it is enabled.still cant by my phone.
![relay](https://user-images.githubusercontent.com/28574054/53080438-580d0b00-3501-11e9-8d43-f2eb0c8c18ea.png)

**Comment by netpok** [comment]
You should try a device restart first, and use the .local address.

**Comment by curzon01** [comment]
Your Phone is using the internet public Google DNS 8.8.8.8 and this public DNS does not know anything about the names of your local network. Use 192.168.1.254 as DNS also for your Phone.

**Comment by netpok** [comment]
Yes, but mDNS should work for him with those settings, as it has nothing to do with the DNS server.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by hwarang098tkd** [comment]
> Wireless Client Isolation is _not_ enabled on your router.

cant find it to mu router Technicolor TG589vn v3




> If it's not working you can try to run `avahi-browse --all` on your computer or it's windows/mac counterpart to check if it shows up or not

with Bonjour Browser i can see the hostnames "_http._tcp.      livingroom_relay, IP Addresses 192.168.1.3:80"



> Use 192.168.1.254 as DNS also for your Phone.

did it and still nothing and also with .local

**Comment by netpok** [comment]
Really weird, I don't have any more tips.

On the other hand you should really disable WPS, because it's a [big security hole](https://www.howtogeek.com/176124/wi-fi-protected-setup-wps-is-insecure-heres-why-you-should-disable-it/).

**Comment by hwarang098tkd** [comment]
From laptop with wifi i can access, i tried another phone and the problem is the same. Iphone and android. So i cant via phone with wifi

**Comment by netpok** [comment]
You can try to check it with a bonjour browser on the phone like [this](https://play.google.com/store/apps/details?id=com.druk.servicebrowser&hl=en_US) (never used it myself), but probably the best way to manage your devices is via OpenHAB or Home Assistant, those have nice mobile apps too.

**Comment by hwarang098tkd** [comment]
OK with this app i can see all this devices with their hostnames and Ips on my phone. It is  something
I have openhab 2 years now and everything runs from there. But sometimes i want to configure details via ui (tasmota). So i wanted it to have access with hostname from phone in my house not only desktop

**Comment by netpok** [comment]
If you see them then the problem lies somewhere else, my last guess: Is there a chance that you are using adblocker on the devices like AdGuard? Those are blocking the requests.
