### ISSUE TITLE
SP23 Flashed as per Aterfax

### ISSUE THREAD

**Issue by thecivvie** [arendst/Sonoff-Tasmota#5289]
I flashed 2 SP23 as per Aterfax Wiki page and sucess on both

**Comment by netpok** [comment]
I'm happy for your success, but the issues section are for issues, if you have anything to add to the wiki, please do.

Please close this issue as it is not connected to the development of the firmware, of course we are happy to listen for success stories on [chat](https://discord.gg/Ks2Kzd4).

**Comment by thecivvie** [comment]
Sorry, new to this and wasnt sure, Closed and will make a comment in the chat
