### ISSUE TITLE
Error connecting MQTT to mqtt.thingspeak.com

### ISSUE THREAD

**Issue by KillSwitchSIG** [arendst/Sonoff-Tasmota#529]
**In Tasmota's console:**
00:11:21 MQTT: Connect FAILED to mqtt.thingspeak.com:1883, **rc 5**. Retry in 10 seconds

**According to ThingSpeak's website on MQTT errors:**
[](https://www.mathworks.com/help/thingspeak/mqtt-error-messages.html)
_If you set the CleanSession flag to 0 on your MQTT client, any connection request to the ThingSpeak MQTT broker is rejected with a CONNACK status of "0x05 Connection Refused, not authorized"._

_If you set the Will flag to non-zero values on your MQTT client, any connection request to the ThingSpeak MQTT broker is rejected with a CONNACK status of "0x05 Connection Refused, not authorized"._

I think we need to implement configuration of CleanSession and Will flags...

**Comment by arendst** [comment]
I'm using PubSubClient as MQTT client and it does not support CleanSessions (https://github.com/knolleary/pubsubclient/issues/281).

So you might want to select another mqtt service provider or even start your own using mosquitto...
