### ISSUE TITLE
SONOFF T2 EU boot mode

### ISSUE THREAD

**Issue by VaL080** [arendst/Sonoff-Tasmota#5294]
Hello All,

I've got a problem to enter my SONOFF T2 EU in boot mode.
When I press BTN 1, press reset , release reset and release BTN1 => Nothing appends.

Below, this is what i have when i turn on the SONOFF T1 EU. 
Have you any idea about how i can go in boot mode?

![sans titre](https://user-images.githubusercontent.com/47858543/53174894-18bae900-35eb-11e9-8180-d027ef86cfe8.png)

Thanks for your help!

**Comment by ascillato** [comment]
Hi,

Sorry, the output is not from Tasmota firmware. 

If you need assistant on how to flash a device, please find us in the Tasmota Support Chat. Github issues are for Tasmota software bug reporting. 

Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by xury77** [comment]
Hi.
Does Tasmota work on versions T2 and T3?
Nowhere is it officially written.

**Comment by ascillato** [comment]
Yes
