### ISSUE TITLE
Power state returns blank

### ISSUE THREAD

**Issue by initrd** [arendst/Sonoff-Tasmota#530]
Power status returns a blank string:

> 19:41:22 CMND: stat/sonoff1/POWER
> 19:41:22 MQTT: stat/sonoff1/RESULT = {"POWER":""}
> 19:41:22 MQTT: stat/sonoff1/POWER =  (retained)

When I power on using the web UI, result shows "POWER": "POWER"

> 19:44:40 CMND: stat/sonoff1/power
> 19:44:40 MQTT: stat/sonoff1/RESULT = {"POWER":"POWER"}
> 19:44:40 MQTT: stat/sonoff1/POWER = POWER (retained)

Relevant config:

> sonoff/user_config.h:#define MQTT_STATUS_OFF        "OFF"
> sonoff/user_config.h:#define MQTT_STATUS_ON         "ON"

> sonoff/user_config_override.h:#ifdef MQTT_POWER_RETAIN
> sonoff/user_config_override.h:#undef MQTT_POWER_RETAIN
> sonoff/user_config_override.h:#endif
> sonoff/user_config_override.h:#define MQTT_POWER_RETAIN    1

Observed after upgrading from 4.x to 5.x. Currently on 5.1.6. Is there some setting that's missing?

**Comment by arendst** [comment]
Try a reset 1 to re-initialize settings.

**Comment by initrd** [comment]
That worked perfect, thanks!
