### ISSUE TITLE
websend has stopped working since 6.4.1.17

### ISSUE THREAD

**Issue by ihavenonick** [arendst/Sonoff-Tasmota#5304]
14:51:35 CMD: power1 on
14:51:35 MQT: stat/sonoff/RESULT = {"POWER":"ON"}
14:51:35 MQT: stat/sonoff/POWER = ON
14:51:35 RUL: POWER1#STATE=1 performs "websend [192.168.100.19:80,admin:joker] POWER1 ON"
**14:51:35 MQT: stat/sonoff/RESULT = {"WebSend":"Connect failed"}**

**Comment by arendst** [comment]
As a workaround try:
```
websend [192.168.100.19,admin:joker] POWER1 ON
```
so without port number 80

**Comment by ihavenonick** [comment]
Oh very quickly fix for this Problem
