### ISSUE TITLE
Add retain: true to home assistant config

### ISSUE THREAD

**Issue by timstanley1985** [arendst/Sonoff-Tasmota#5312]
Hi, I have until now been manually configuring my tasmota switches in home assistant but have been experimenting with home assistant discovery this weekend.

It works great and I love the fact that you also get a sensor for each switch that include RSSI and version etc.! But I configure my switches to use a retain flag on the command topic.  This means if home assistant issues a command while the switch is either out of WiFi range of offline for any reason it picks up the command change as a retauned message when it comes back on line.  Can you considering adding this as an option please?

You would just need to add "Ret":'true" to the config payload.

**Comment by Jason2866** [comment]
HA is misconfigured for Tasmota if you use Retain ON.
See Wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant---Manual-Config
There will be no change in Tasmota....

**Comment by curzon01** [comment]
If link above can not be opened (result is "Create new page") on browser, use
https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant-%E2%80%90-Manual-Config

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato2** [comment]
Please, to avoid other problem, don't use retained messages. Use instead the automations explained in the wiki at home assistant chapter. Thanks.
