### ISSUE TITLE
Wemos D1 doesn't operate in Generic mode

### ISSUE THREAD

**Issue by MaiMariarti** [arendst/Sonoff-Tasmota#5317]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

Make sure these boxes are checked [x] before submitting your issue - Thank you!

- [ x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
None found
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
None found
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
None found
- [ x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
None found
- [ x] Development/Compiler/Upload tools used :
flash_download_tools_v3.6.5 for windows 
- [x ] Hardware used : 
Wemos R1 mini
- [ x] If a pre-compiled release or development binary was used, which one? :
tasmota v6.4.1 (sonoff.bin)
- [ x] You have tried latest release or development binaries? :
YES
- [ ] Provide the output of command ``status 0`` :
```
Not using an MQTT
Tasmota Defaults to Sonoff basic(01) with only 5 I/Os exposed.
Wemos has many more. I want to use them without MQTT. 
```

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Duplicated issue.

Please, for support use the Tasmota Support Chat. Thanks
