### ISSUE TITLE
Sonoff R2 as low voltage switch

### ISSUE THREAD

**Issue by MightyMilster** [arendst/Sonoff-Tasmota#5318]
Hi All. 
I'm quite interested in these 2 lines:

> You can removed the thick wires to use the screw connection for low voltage.
> 
> And add a screw terminal next to the relay. This make all high voltage on 1 side of the board

I would like to use the new R2 as a low voltage switch but can't see how it can be done without a major CUT of the L input, between the resistor and the relay leg.

Is there an easier way to do this? Or an expansion on the above quoted lines?

Thanks very much!!!

**Comment by ascillato2** [comment]
Sorry, we don't support mods that can be dangerous without knowledge on AC mains.

It is recommended to use a wemos or nodemcu board for a safer solution. 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by MightyMilster** [comment]
Thanks
