### ISSUE TITLE
Visual Studio Code:PlatformIO: IntelliSence Index Rebuild run FOREVER

### ISSUE THREAD

**Issue by hwarang098tkd** [arendst/Sonoff-Tasmota#5325]
I tried with my laptop and my desktop and i have the same problem. PlatformIO: IntelliSence Index Rebuild run FOREVER and i cant do nothing.
Ideas?

**Comment by Jason2866** [comment]
Not Tasmota related.... Anyway close VSC delete folder  `c:\Users\YourUserName\.platformio` 
Start VSC. Wait... VSC will rebuild Platformio. After that it should work

**Comment by hwarang098tkd** [comment]
thnx. it worked by itself after 2 hours.
