### ISSUE TITLE
Inverting ON/OFF logic

### ISSUE THREAD

**Issue by petrfaitl** [arendst/Sonoff-Tasmota#533]
This pains me even to write, but I have just sourced a 4 relay board that uses LOW as ON and HIGH as OFF. And whilst I could just set PowerOnState to 1, so I don't flood my garden on reset, I think it would be great to have a setting in the user_config.h that deals with this situation.

I have found this in user_config `MQTT_STATUS_OFF        "OFF"` , but I don't really see anything different in the console, when I swap the values around.

Is it doable? Thanks.

**Comment by arendst** [comment]
As it's not a Sonoff I suggest you select a wemos device and populate the relays yourself using the configuration webpage. By selecting option Relayx instead of RelayxI you should be able to control a straigth relay.

**Comment by petrfaitl** [comment]
Thank you. Wasn't aware of that option.
