### ISSUE TITLE
Please correct my submitted template

### ISSUE THREAD

**Issue by SirRedZ** [arendst/Sonoff-Tasmota#5347]
I just used google form to submit a template for Tuya BSD15 Smart plug. Please correct the template as below: I made an error in LED1 (should be LED1i). Option 52 was specified in error. It should be option 56.

{"NAME":"TuyaPlugBSD15","GPIO":[255,255,255,255,255,255,255,255,21,17,56,255,255],"FLAG":1,"BASE":18}

**Comment by blakadder** [comment]
Are you sure you submitted it, I don't see it in the google form data

**Comment by SirRedZ** [comment]
Yes! I see it posted "Generic" - with the mistake

https://blakadder.github.io/templates/us.html

Thank you.

**Comment by blakadder** [comment]
Updated the entry!
