### ISSUE TITLE
Sonoff Touch - no respose after flashing

### ISSUE THREAD

**Issue by SebastianSienicki** [arendst/Sonoff-Tasmota#535]
I'v just sucessfully flash sonoff touch with 5.1.7 version.
![image](https://user-images.githubusercontent.com/8268707/27405032-5b31d416-56d0-11e7-9e74-99035dc80d9b.png)

![image](https://user-images.githubusercontent.com/8268707/27404687-4954eb30-56cf-11e7-8a56-fe7449ee70d8.png)
After reconnect there is no response on serial monitor.
I'v try to reflash it but i have no respose at all.
Any ideas?

**Comment by SebastianSienicki** [comment]
I'v got it.
It was hardware problem - i had to re solder esp.

**Comment by Jantokil** [comment]
I just flashed 3 Sonoffs (basic) in a row with succes but now I'm having the same issues. No response at all when connected to mains. How did you fix it exactly? I'm fairly new to this

**Comment by SebastianSienicki** [comment]
First of all check if your soldering is fine, then check if you upladed correct Environment (for eg. basic is sonoff for TC is sonoff-touch-4ch and so on), then check if you listen on correct serial port with boud rate 115200. there is almost no possibility that 4 modules are broken one.
In one of my TC esp module had poor soldering i had to resolder it, then it start to work properly.

**Comment by David-Aunta** [comment]
Hola SebastianSienicki ,,,podria tener un paso a paso de esto, no me esta dejando flashear
