### ISSUE TITLE
Sonoff dual R1 button sopped working after upgrading to 6.4.1

### ISSUE THREAD

**Issue by BugsonPL** [arendst/Sonoff-Tasmota#5355]
Sonoff dual R1 button sopped working for Relay2 with double press after upgrading to 6.4.1.

Be for update it was working fine.

Unfortunately I dno't remember the previous build.

 I can make some additional tests if needed.

**Comment by ascillato** [comment]
Please, complete the troubleshooting template in order to have more information so as to properly help you. Thanks

**Comment by ascillato** [comment]
And add also the output of the console when doing that. Remember to put weblog to 4

**Comment by ascillato2** [comment]
Please, also try the latest version from the development branch at thehackbox.org/tasmota

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato2** [comment]
Closing this issue as there is no feedback. Please, when you have time, complete the troubleshooting template. Thanks

**Comment by gerardovf** [comment]
I can confirm that version 6.4.1 is working in several (more than 4) Sonoff dual R1 I am using. Any other newer version doesn't allow to use the external button to switch both relays.

**Comment by gerardovf** [comment]
It's finally solved. Checked on version 8.4.0.2. Thanks Theo!
