### ISSUE TITLE
How to full flash Sonoff?  

### ISSUE THREAD

**Issue by shayshtern** [arendst/Sonoff-Tasmota#5357]
When I flash the Sonoff it's still remember the WiFi settings. So how do I fully flash it? 🙏🏼

**Comment by localhost61** [comment]
I  suggest you first make a backup of your current setting
`http://MyDeviceIP/dl` where you have to replace MyDeviceIP with the one you assigned to your device.
Then `http://MyDeviceIP/cm?cmnd=reset%201` will do the trick.

A more classic way is by using the console to enter the [command](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands) :
`Reset 1` and it should restart with the default settings of your firmware.

**Comment by shayshtern** [comment]
@localhost61 I mean flash with PC.
with FTDI to USB.

**Comment by localhost61** [comment]
`esptool.py --port COM3 erase_flash`
If you never used it before, look for [esptool](https://github.com/arendst/Sonoff-Tasmota/wiki/Esptool) in the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki)

**Comment by shayshtern** [comment]
![image](https://user-images.githubusercontent.com/4135420/53484315-3c1ee180-3a8c-11e9-9d9d-cff78a84b7b2.png)
Can I do it with ESPEasy?

**Comment by localhost61** [comment]
I don't know, I never used it. On your screen I see no option for that.

**Comment by shayshtern** [comment]
In the Firmware (.bin) I choose blank_1MB.bin and click Flash ESP Easy FW.
Then reconnect to flash mode with PC and flash with sonoff.bin.
CLOSE.

**Comment by localhost61** [comment]
Close this issue if you're done. Thks

**Comment by localhost61** [comment]
I don't know were you get blank_1MB.bin, it seems to me you're mixing Tasmota and EspEasy projects.
EspEasy flasher is a loader for EspEasy firmware, it's not intended to be used with Tasmota firmware.
Of course, you can try but then you should understand what you do... and learn from your own experiments.
