### ISSUE TITLE
What ESP board is this LED controller based on?

### ISSUE THREAD

**Issue by maxtheking** [arendst/Sonoff-Tasmota#5363]
So a while back i bought a few generic Wi-Fi LED controllers on eBay, i posted images below. They currently use the Tuya cloud, but i want to convert them using tuya-convert so i can control them locally with Home Assistant instead of them reaching out to some chinese Tuya server everytime i turn them on for example. Does anyone know what ESP board they're based on? Can't find any info about them on the internet. 
![img_1112](https://user-images.githubusercontent.com/43993269/53514239-95583680-3ac7-11e9-81b3-4d42d474334a.JPG)
![img_1113](https://user-images.githubusercontent.com/43993269/53514240-95583680-3ac7-11e9-9060-05517983739a.JPG)

**Comment by Jason2866** [comment]
No, and no one can. Because even with the same case there can be different.
Only way is opening the device

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

Please, if you need further assistant please, do not hesitate on asking in the Tasmota Support Chat. Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
