### ISSUE TITLE
upgrade SONOFF TH16 to get sensor reading

### ISSUE THREAD

**Issue by muscaiu** [arendst/Sonoff-Tasmota#5365]
- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Development/Compiler/Upload tools used :
- [x ] Hardware used : SONOFF TH16
- [ ] If a pre-compiled release or development binary was used, which one? :
- [x ] You have tried latest release or development binaries? :
- [x ] Provide the output of command ``status 0`` :
```
21:14:55 CMD: status 0
21:14:55 RSL: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
21:14:55 RSL: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Power on","Uptime":"0T00:00:30","StartupUTC":"2019-02-27T20:14:25","Sleep":50,"BootCount":32,"SaveCount":68,"SaveAddress":"FA000"}}
21:14:55 RSL: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.4.1(sensors)","BuildDateTime":"2018-12-24T14:45:55","Boot":7,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"}}
21:14:55 RSL: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["casussa",""],"TelePeriod":300,"SetOption":["00008009","558180C0","00000001"]}}
21:14:55 RSL: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":550,"Free":452,"Heap":19,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1420C2","FlashMode":3,"Features":["00000809","0FDEE794","0003A3A4","B7FFBFCC","0002BBC0"]}}
21:14:55 RSL: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-5696","IPAddress":"192.168.1.102","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"CC:50:E3:54:56:40","Webserver":2,"WifiConfig":3}}
21:14:55 RSL: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_545640","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
21:14:55 RSL: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Wed Feb 27 20:14:55 2019","Local":"Wed Feb 27 21:14:55 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:36","Sunset":"18:29"}}
21:14:55 RSL: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2019-02-27T21:14:55"}}
21:14:55 RSL: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2019-02-27T21:14:55","Uptime":"0T00:00:30","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"casussa","BSSId":"30:0C:23:A4:70:A4","Channel":6,"RSSI":100}}}
21:15:00 MQT: Attempting connection...
21:15:01 DNS: Query done. MQTT services found 0
21:15:02 CMD:    $@
21:15:02 RSL: stat/sonoff/RESULT = {"Command":"Unknown"}
21:15:06 CMD:  
21:15:06 RSL: stat/sonoff/RESULT = {"Command":"Unknown"}
21:15:08 CMD: @@   @@ 
21:15:08 RSL: stat/sonoff/RESULT = {"Command":"Unknown"}
```

**(Please, remember to close the issue when the problem has been addressed)**

I'm trying to upgrade my SONOFF TH16 to have sensor reading.
This is my current version
![basic module](https://user-images.githubusercontent.com/11426309/53518236-42877a80-3ad9-11e9-8811-75543951d650.png)

Managed to upgrade it to 6.4.1, and using the file downloaded from https://github.com/arendst/Sonoff-Tasmota/releases/download/v6.4.1/sonoff-sensors.bin to update, but it's always failed.

![sonoff_th16_upgrade_failed](https://user-images.githubusercontent.com/11426309/53518006-b9704380-3ad8-11e9-97a8-09760f9b4a6d.png)

What am i doing wrong?

PS: Also for some reason i can't set a static ip to it, but that's another issue, still maybe it helps.
![termite](https://user-images.githubusercontent.com/11426309/53518822-86c74a80-3ada-11e9-9f4a-31208b284bb7.png)

**Comment by ascillato** [comment]
You have 2 things. First, you need to go to configuration and choose sonoff TH. Now you have selected sonoff basic.

Then, if you want to update (you don't need that for sonoff TH) you need to use minimal firmware first to free flash memory to then flash the full version.

If this solves your issue, please close it. 

Remember that for support, it is available the Tasmota Support Chat. Github issues are for bug reporting. Thanks

**Comment by ascillato** [comment]
The commands issue is because your console is not sending the proper newline characters. Please, use the Tasmota console instead (the one that is inside Tasmota, in the web menu). Thanks

**Comment by ascillato** [comment]
Have you tried to choose sonoff TH in the configuration menu?

**Comment by muscaiu** [comment]
@ascillato thanks for the quick reply!

I configured another TH10 few weeks ago and that worked pretty easy to get sensor reading.

Tried your advice  to use minimal firmare and then used the sonoff-sensors.bin to upgrade and upgrade worked, but **still the Temp readings are not showing up on the main menu** for this TH16, there is no info on the top.
Any more ideas why that is?

PS: I didn't know that the Tasmota console works same as Termite, used it and setting static ip worked, thanks!

**Comment by muscaiu** [comment]
> 
> 
> Have you tried to choose sonoff TH in the configuration menu?

Yes, and now it's showing Sonoff TH Module instead of Basic, but still no temp readings.
![th_module](https://user-images.githubusercontent.com/11426309/53521461-d7da3d00-3ae0-11e9-8245-ddeb1589ba47.png)

**Comment by muscaiu** [comment]
On the previos TH10 i used a SI7021(03) sensor and that showed up even if the sensor was not plugged into the SONOFF.

But this time i'm using a DS18B20  sensor and it looks like the temp is only showing if the sensor it's actually plugged into the SONOFF >< Didn't know that, but i thought hey maybe i try it :)

All good! Thanks again for the tips! Closing

![th16](https://user-images.githubusercontent.com/11426309/53521974-21775780-3ae2-11e9-9b10-546064b5a45a.png)
