### ISSUE TITLE
Smart Wifi RGB led controller Spider Z with nuvoton chip

### ISSUE THREAD

**Issue by arcidodo** [arendst/Sonoff-Tasmota#5370]
I order an sonoff led strip flashed with Tasmota. 

link:
https://www.aliexpress.com/item/SONOFF-L1-Smart-LED-Light-Strip-Dimmable-Waterproof-WiFi-Flexible-RGB-Strip-Lights-Work-with-Alexa/32960596437.html?channel=twinner

if i select the module PS-16-DZ the on/off works with only the red color also dimming is working correctly. 

how can i get the RGB function to work? :-)

![unadjustednonraw_thumb_67bb](https://user-images.githubusercontent.com/678514/53598802-eb9ba700-3ba5-11e9-9979-fdeb56d5a278.jpg)
![unadjustednonraw_thumb_67b9](https://user-images.githubusercontent.com/678514/53598803-ec343d80-3ba5-11e9-8bd4-923602a98a2e.jpg)
![unadjustednonraw_thumb_67ba](https://user-images.githubusercontent.com/678514/53598804-ec343d80-3ba5-11e9-8532-6ca05d2a78fd.jpg)

**Comment by ascillato** [comment]
Hi,

You need to find out where the gpios are connected and then select generic module and set what you have found.

Then, when you have it working you can make a new template for that device. (information on this can be found in the wiki) 

If you want to share your template, you can send it as explained in the wiki.

If you need further assistant please find us in the Tasmota Support Chat. Thanks

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by ascillato2** [comment]
Please, when you have time, please tell us if you could make it work. Thanks

**Comment by jakass202** [comment]
Can’t find the GPIO0 to put it in flash mode

**Comment by eford321** [comment]
Flashed by holing GPIO0 low at the chip.  Still not able to find working GPIOs for the controller.

**Comment by arcidodo** [comment]
@eford321 same  here!

**Comment by eford321** [comment]
Really strange.  I am unable to get the controller to respond to any GPIO settings.  I decided to test for the IR GPIO and found the remote still functions as if the original software is still running.  All remote functions work and the Sonoff-Tasmota console does not show any activity other than booting.

**Comment by eford321** [comment]
Found out why.  There is a Nuvoton N76E003AT20 processor on the board.  The ESP8285 must be communicating via i2c or serial to the Nuvoton, which controls the PWM for LEDs.

**Comment by reef-actor** [comment]
This seems to be a rebranded Sonoff L1, discussion in [issue 4935](https://github.com/arendst/Sonoff-Tasmota/issues/4935)

**Comment by Wriman** [comment]
Hi! Can you send me the homeasisstant config?

**Comment by reef-actor** [comment]
@Wriman see https://github.com/arendst/Tasmota/issues/4935#issuecomment-539700171
