### ISSUE TITLE
rule trigger POWER1#STATE 

### ISSUE THREAD

**Issue by baha00** [arendst/Sonoff-Tasmota#5372]
**IMPORTANT NOTICE**
If you do not complete the template below it is likely that your issue will not be addressed. When providing information about your issue please be as extensive as possible so that it can be solved by as little as possible responses.

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

**Describe the bug**
Not sure if is a bug or I am not using it right,but I added simple rule to send Status 8 (power voltage etc) whenever power is changed and I am getting status that it was before power is changed. So if it was on, when I switch off Ill get values Voltage = 230 and if I switch relay on Ill get value 0

_Also, make sure these boxes are checked [x] before submitting your issue - Thank you!_
- [x ] _Searched the problem in issues and in the wiki_
- [ ] _Hardware used_ : SONOFF S31* Appuche chinese but works wit 
- [ ] _Development/Compiler/Upload tools used_ :
- [ ] _If a pre-compiled release or development binary was used, which one?_ :
- [ ] _You have tried latest release or development binaries?_ :
- [ ] _Provide the output of command_``status 0`` :
```
STATUS 8 OUTPUT HERE - 
MQT: _00BF902B/stat/POWER = ON
22:23:02 RUL: POWER1#STATE performs "status 8"
22:23:02 MQT: _00BF902B/stat/STATUS8 = {"StatusSNS":{"Time":"2019-02-28T22:23:02","ENERGY":{"TotalStartTime":"2019-02-28T21:23:15","Total":0.293,"Yesterday":0.000,"Today":0.293,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
```

**To Reproduce**
_Steps to reproduce the behavior:_

**Expected behavior**
This is how I setup the rule
![image](https://user-images.githubusercontent.com/17033913/53603349-26eba500-3ba9-11e9-8add-e989a6f4c014.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/17033913/53603276-e3913680-3ba8-11e9-8582-57cc9b8dcd9d.png)

![image](https://user-images.githubusercontent.com/17033913/53603309-fefc4180-3ba8-11e9-8b66-647bcd76044a.png)

**Comment by ascillato** [comment]
That is because the rule is triggered as soon as the event occurs and before all the sensors values are updated. 

Please add a delay. 

```
Rule1 1 
Rule1 on Power1#state do backlog delay 1; status 8 endon
```

**Comment by baha00** [comment]
This sorted out!! thanks, another question, is it possible to implement that rule in Firmware? so no need to setting it up to be in by default?

**Comment by ascillato** [comment]
It is very specific to this case. Is like adding in the code that "If a power state has changed, update all values before executing other commands". That would add a delay on the answer for all use cases.

May be Theo (@arendst) has an idea for that.

**Comment by baha00** [comment]
@ascillato no, my bad expression, I didnt mean to add it on default, but is there option before building firmware to add rules ? Like wifi ap etc

**Comment by ascillato** [comment]
Ah, ok.

No, there isn't yet.

**Comment by markross42** [comment]
Hi @ascillato, 
This 

Rule1 on Power1#state do backlog delay 20; status 8 endon
sorted out my problem - a bit, :) Still, this does not trigger telematic data send by power state change.


THX
