### ISSUE TITLE
RF Bridge - Send RFKEYS to KNX

### ISSUE THREAD

**Issue by atomi23** [arendst/Sonoff-Tasmota#5376]
Would be nice to Send all RFKEYS 1-16 direct to the KNX BUS with the RF Bridge

**Comment by ascillato2** [comment]
Hi,

It is already supported. You need to use rules to define the behaviour you want:

In the KNX WEB Menu, set the group address you want to send the command in the KNX slot 1 (KNX TX 1) and then in the console type:

```
rule1 1
rule1 on RfReceived#RfKey=1 do KnxTx_Cmnd1 1 endon
```

For more information, please check the wiki at commands, rules and KNX.

If you need further assistance, please, find us in the Tasmota Support Chat. Thanks.

Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
