### ISSUE TITLE
Xiaomi Mi Desk Lamp button dimming and color chamging to slow

### ISSUE THREAD

**Issue by computerkoenig** [arendst/Sonoff-Tasmota#5378]
At the Xiaomi Mi Desk Lamp there is a wheel to change the brightness and light color.
If you turn that wheel you see in the logs that there is is always changing the value by 1. for that reason you have to turn the wheel really often to change it. This shoud be set to 5 or 10 to have less steps.

**Comment by joba-1** [comment]
sounds useful.

Most of my lights would need a quadratic or logarithmic increment though
(small steps while dark and big steps when bright).

Never looked at rules, but maybe what you want can be achieved already with
them? Like „if value between 1 and 5 then value = 10“ and so on and similar
for stepping down.
-- 
iphone so i typo

**Comment by ascillato2** [comment]
Hi,

Please, can you complete the troubleshooting template, or at least share the output of the STATUS 0 command and the output of the console when you see that? Thanks

**Comment by ascillato** [comment]
@computerkoenig

Hi,

Any feedback?

**Comment by ascillato2** [comment]
@computerkoenig

Hi, 

We want to help you but we need more information in order to do so. Please, when you have time, share the information requested. Thanks
