### ISSUE TITLE
FallbackTopic

### ISSUE THREAD

**Issue by ionciubotaru** [arendst/Sonoff-Tasmota#538]
FallbackTopic is affected by fullTopic configuration. Ex: for FullTopic `tasmota/%topic%/%prefix%/` the FallbackTopic  is `tasmota/cmnd/<FallbackTopic>/<command>  <parameter>`

I suggest, because FallbackTopic is mainly used for debugging reasons, to preserve standard configuration `cmnd/<FallbackTopic>/<command>  <parameter>` to avoid FullTopic misconfigure issues

**Comment by arendst** [comment]
Sounds Ok with me.

I would like to suggest to make ``cmnd`` also mandatory as it could have been misconfigured by command ``Prefix1``.

So the total FallBackTopic string would then be ``cmnd/<FallbackTopic>/<command> <parameter>`` (Without ``tasmota``).

If no comments I will try to implement after a week from now.
