### ISSUE TITLE
Need help integrating in Home Assistant

### ISSUE THREAD

**Issue by wpeterw** [arendst/Sonoff-Tasmota#54]
I have a Sonoff POW.  When I do:

`pi@HomeAssistant:~$ mosquitto_sub -h 192.168.178.123 -p 8883 -t 'cmnd/sonoff_droger/status 8' -v -u ha -P ha`

I get:

`pi@HomeAssistant:/var/www/html$ mosquitto_sub -h 192.168.178.123 -p 8883 -t stat/sonoff_droger/RESULT -v -u ha -P ha
stat/sonoff_droger/RESULT PWR: Voltage 228 V, Current 0.000 A, Power 0 W, Today 0.005 kWh, Factor 0.00`'

But how to do this in Homeassistant ?

**Comment by arendst** [comment]
Perhaps the information in the wiki can give you some clue how to proceed with Home Assistant.

BTW: I see you are using an old version. I'll recommend upgrading to Sonoff-Tasmota version 3.9.14
