### ISSUE TITLE
A way to add WiFi SSID and KEY directly on the binary, without build

### ISSUE THREAD

**Issue by nagyrobi** [arendst/Sonoff-Tasmota#5413]
It would be nice to be able to change the default SSID and KEY in the binary itself, straight after download, and then flash to the device. Some sort of HEX editing the binary. If the SSID and KEY would be stored in the binary at the same HEX address always, one could write a simple tool to "edit" the binary with his/her own wifi settings.

**Comment by Jason2866** [comment]
Not possible. If you want hard coded settings you need to compile your own.
There is a way. Flash version. Setup wifi. Connect it again. Read whole flash back with esptool.
Flash this version to your devices. All the settings are stored and will be used.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
