### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by elzershark** [arendst/Sonoff-Tasmota#5415]
of https://github.com/arendst/Sonoff-Tasmota/wiki/User-created-templates.. there is a link to https://blakadder.github.io/templates/...

I'm not sure .. I have z.b. taken .. 
https://blakadder.github.io/templates/lyasi_pt-bw09.html
https://amzn.to/2C9FVBb
because such an absolutely identical, as I have already spoken here before ... I copied and pasted the code. and wondered why the lamp then answers nothing at all. Since I noticed that there is a button in the code. And other settings that I do not know. have all the devices been tested? I do not think so.

So the lamp does not respond from the website. she is in the router .. in the wlan ..but not to reach over the web page.
this is my lamp.. https://amzn.to/2Tou1hB this is the same picture..
the right code = 
`{"NAME":"Luminea ZX2832","GPIO":[255,0,255,0,140,37,0,0,255,142,141,0,255],"FLAG":1,"BASE":18}`

and on the link code.. he kills the lamp..
That can never be an attitude for a lamp ...

`{"NAME":"Lyasi PT-BW09","GPIO":[17,255,255,255,143,144,0,0,0,0,0,0,0],"FLAG":0,"BASE":27}`

**Comment by ascillato** [comment]
Hi,

Sorry. I don't understand your issue. 

Please, could you be so kind on completing the troubleshooting template in order to have more information so as to properly help you? 

Thanks.

**Comment by blakadder** [comment]
This issue has nothing to do with the sonoff tasmota code and should be opened in the appropriate repository
