### ISSUE TITLE
Which hardware for a led strip power supply

### ISSUE THREAD

**Issue by blademckain** [arendst/Sonoff-Tasmota#5416]
Hi all,
i have this power supply
[https://www.alphaelettronica.com/kl284-04.html](https://www.alphaelettronica.com/kl284-04.html)
[https://www.alphaelettronica.com/media/catalog/product/cache/1/image/700x700/427b491f10f4712ade17208687ea36db/5/6/56341_001.jpg](https://www.alphaelettronica.com/media/catalog/product/cache/1/image/700x700/427b491f10f4712ade17208687ea36db/5/6/56341_001.jpg)

there is any hardware that allows me to dimmer a 1-10v?

**Comment by Jason2866** [comment]
Please read https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md

**Comment by ascillato2** [comment]
Hi,

Please, check the wiki for the full list of supported devices by Tasmota Software.

If you need further assistant, please, find us in the Tasmota support chat. Github issues are for Tasmota Software Bug reporting. 

Thanks.

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
