### ISSUE TITLE
Teckin SP27 hardware

### ISSUE THREAD

**Issue by arvydas** [arendst/Sonoff-Tasmota#5422]
**Is your feature request related to a problem? Please describe.**

Need to enable powere metering on Teckin SP27 (UK version)

**Describe the solution you'd like**

Power metering function visible.

**Additional context**

I have successfuly flashed Sonoff.bin and it's working. 

Generic module maping:

* GPIO0 -> Led1i (56)
* GPIO13 -> Button1 (17)
* GPIO15 -> Relay1 (21)

Just missing the power metering feature. None of Blitzwolf and Teckin predefined module types work.

I think power metering chip is the one right in the middle marked as:

HP-01
AJ61GC.1
H19

I can't find any info on the internet or within source code about this type of chip.

Photos below

![20190308_175224](https://user-images.githubusercontent.com/72420/54050293-be1eb100-41d6-11e9-9567-55ebac58d065.jpg)

![20190308_190213](https://user-images.githubusercontent.com/72420/54050312-c4149200-41d6-11e9-804e-648d35e7c4e2.jpg)

![20190308_190236](https://user-images.githubusercontent.com/72420/54050319-ca0a7300-41d6-11e9-8856-e65035cc3979.jpg)

![20190308_190301](https://user-images.githubusercontent.com/72420/54050330-cecf2700-41d6-11e9-8351-97e4bb036f12.jpg)

**Comment by kobuki** [comment]
Are you sure it has power metering built in? If that's the single chip on the board besides the WiFi panel, I don't think it has. That chip must be the unisolated power supply controller. I can't see the shunt resistor for metering, either (usually 1 mOhm).

**Comment by arvydas** [comment]
You are probably right. Just checked user comments on Amazon webpage and they complain that this socket does not have energy monitoring on official app. Bugger. Case closed.

**Comment by gyurobenjamin** [comment]
BTW these are Tuya devices. You can upload custom bins via OTA without open the housing.

**Comment by realcountjocular** [comment]
The Teckin SP23 has power monitoring, it's done on the EPS8266 board. 
As the SP23 seems discontinued, if you still want power monitoring look for Aoycocr U3S, is has exactly the same internals as SP23.
![20220916_215523_2](https://user-images.githubusercontent.com/59534035/190747689-68a015b4-c3b7-45dc-b0ff-17db65e26f6c.JPG)
![20220916_215452_2](https://user-images.githubusercontent.com/59534035/190747880-5d3698d1-efae-4430-adfc-087f24ca54c8.JPG)
![20220916_215440_2](https://user-images.githubusercontent.com/59534035/190748037-04fc84ba-6917-4cb7-9be5-0660db427bbb.JPG)
