### ISSUE TITLE
sonoff B1 R2 where in gpio02 ?

### ISSUE THREAD

**Issue by hwarang098tkd** [arendst/Sonoff-Tasmota#5435]
can anyone show me where is the gpio02 on sonoff bulb b1 r2 v1.0?

**Comment by Jason2866** [comment]
If you upload hires pictures of the device, there is a chance we can help...

**Comment by hwarang098tkd** [comment]
![51180848-dacef480-18c9-11e9-9390-ed294dfc77b5](https://user-images.githubusercontent.com/28574054/54083518-2384b600-432d-11e9-9654-fce5feec2470.jpg)

**Comment by Jason2866** [comment]
The solder pin near GPIO 0 is SDA (=GPIO 4). Pin GPIO 2 is not available as solder point.
You have to solder for this GPIO direct on the ESP chip. https://github.com/arendst/Sonoff-Tasmota/issues/3347#issuecomment-408480719

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
