### ISSUE TITLE
MJ-S01

### ISSUE THREAD

**Issue by atwillman** [arendst/Sonoff-Tasmota#5439]

**Comment by atwillman** [comment]
I am having an issue finding the appropriate module after flashing this switch with Tasmota. I am new to this Tasmota thing thanks for your help.

**Comment by ascillato2** [comment]
Hi,

For support it is available the **Tasmota Support Chat** in which we can help you step by step and solve your questions. Github issues are for Tasmota Bug Reporting with the Template completed. Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
