### ISSUE TITLE
Tuya QS-WIFI-S03 / Shelly clone

### ISSUE THREAD

**Issue by tifrei** [arendst/Sonoff-Tasmota#5444]
Hello,

bought this shelly clone for testing. Already got tasmota uploaded but im not sure on how to set this up so that it works properly ?

Any ideas from you Tasmota God's?

i know my soldering skills are bad but at least tasmota is on it already.... :D 

https://imgur.com/mr8HiSv

https://imgur.com/BwFbq4w

https://imgur.com/s13yEXT

**Comment by netpok** [comment]
You have to trace the switch contact and relay driver transistor back to a gpio and set them up as switch/relay in module settings.

**Comment by blakadder** [comment]
Please try and ask for help in [Discord chat](https://discord.gg/Ks2Kzd4), issues are meant for bugs in the code not individual help
