### ISSUE TITLE
Sonoff Basic SwitchMode Not working.. on Sonoff Basic RF2 Version

### ISSUE THREAD

**Issue by asking23** [arendst/Sonoff-Tasmota#5446]
Hi,
I have flashed my Sonoff basic with Tasmota 6.4.1 successfully and its working.
I want to Add Switch to GPIO14 (Soldered wire to KEY Point on PCB) .

I have tried all the SwitchMode0....4 all commands accepted in webui console but not effective.

When i short GPIO14 and GND it toggles only. No SwitchMode is effective. what can i do ?

**Comment by Frogmore42** [comment]
Issues are for real issues with the software, not for help on how to use the software.  The template provides several resources to check to get help with how to use and configure things.

**Comment by ascillato2** [comment]
Closing issue as it does not follow the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md)
