### ISSUE TITLE
GPIO15 for Sensor on Sonoff 4CH PRO R2

### ISSUE THREAD

**Issue by dastrix80** [arendst/Sonoff-Tasmota#5447]
Hi All

Im already using GPIO14 on this device as a contact sensor/reed sensor but id like to add another. Relay4 is not being used, but I cannot locate where to connect my sensor.

GPIO15 i believe is tied to relay4

May someone assist?

Thank you

**Comment by blakadder** [comment]
You can try asking in [Discord chat](https://discord.gg/Ks2Kzd4) for help, issues is only for code bugs and issues not a how to on supported devices
