### ISSUE TITLE
SonOff CH4 R2 whit BME680

### ISSUE THREAD

**Issue by Valerio1975** [arendst/Sonoff-Tasmota#5450]
I have a problem, I set everything for BME680 but I don't see the parameters. do i need to enable anything. I use Arduino IDE.
TX=GPIO1-> SDA
RX=GPIO3-> SCL

![1](https://user-images.githubusercontent.com/46631445/54234288-1aebd580-450f-11e9-9661-6ccf066517f0.png)

![2](https://user-images.githubusercontent.com/46631445/54234308-2212e380-450f-11e9-83fe-89600554c5ef.png)

![3](https://user-images.githubusercontent.com/46631445/54234383-4cfd3780-450f-11e9-9b2a-fdc1d2a08491.png)

**Comment by joba-1** [comment]
you use serial lines for i2c. Have you deactivated serial output?
The bme should be discovered and values displayed automatically.

**Comment by ascillato** [comment]
Hi, please update to latest Tasmota version and try again. Thanks

**Comment by Valerio1975** [comment]
How can I disable the serial port? I have the latest version.

⁣Inviato da TypeApp ​

Il giorno 12 mar 2019, 21:56, alle ore 21:56, joba-1 <notifications@github.com> ha scritto:

**Comment by ascillato** [comment]
With that you have the serial log disabled. Anyway, 6.4.1.9 is not the latest. Please update. Several fixes related to your issue has been applied after that.

After you update, please complete the troubleshooting template sharing also the output of status 0 command and the output of the console. Thanks

**Comment by Valerio1975** [comment]
Sorry you could send me the complete link to update the latest version, because I did the update but this is the latest version. I also put the normal one in English (thinking that it changed from the Italian one) but nothing changes always remains the same. I put the minimal first and then sonoff.bin

**Comment by ascillato2** [comment]
http://thehackbox.org/tasmota/sonoff.bin

Please, complete the troubleshooting template

**Comment by Valerio1975** [comment]
Thanks, too bad the update doesn't work. Ne upload of minimal ne sonoff.bin.
I will try to make an erase of the flash and program directly with the file you sent me the link.
Unfortunately, as in the old post you finally told me to use the chat, the update will not work either via internet or by hand. Once in the chat he offered one who told me he gave me a hand and then he disappeared, others tell me all about putting the minimal first and then the file I want. But when I say that it doesn't work, nobody answers anymore. Thanks a lot anyway.

**Comment by Valerio1975** [comment]
I reprogrammed everything, now it works but putting sonoff-sensor.bin.
However, updating via OTP or manual still does not work.

![5](https://user-images.githubusercontent.com/46631445/54309429-64502980-45d0-11e9-82d7-859d737a22c0.png)
