### ISSUE TITLE
How to add manual switching with only Switched Live and Neutral available as input

### ISSUE THREAD

**Issue by Svyatk0** [arendst/Sonoff-Tasmota#5453]
Hey guys. I am trying to add sonoff basic to the ceiling rose to be used both as manual switch and the sonoff controlled. 
The issue I have is that i can only see 2 wires in the rose. I have Switched Live and Neutral. I have no access to Live or the switch wires 😔 as they appear to be tucked away in the unreachable junction box. 

Tried basic inline wiring, but that only works partially. 
If sonoff state is remotely set to OFF, my switch cant turn it back on. with only 2 wires available  i have nothing to attach to RX and GRND pins to trigger the manual on/off. 

Any suggestions would be appreciated.

Thanks.

**Comment by ascillato2** [comment]
Hi,

For support, please use the Tasmota support chat. Github issues are for Tasmota Software Bug reporting with the template completed. For more information on this, please see contributing guidelines at CONTRIBUTING.md

Thanks 

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
