### ISSUE TITLE
WifiManager, wifi settings error

### ISSUE THREAD

**Issue by au190** [arendst/Sonoff-Tasmota#5456]
### BUG DESCRIPTION
When you set up the wifi usenrame and password and you miss it (enter wrong password) After that you are never able to connect to the WifiManager.
The AP mode never comes up again, until you set up by serial.
Please find the logs below.

CONSOLE OUTPUT HERE:
00:00:09 RSL: stat/s_51/RESULT = {"Command":"Unknown"}
00:00:25 WIF: Connect failed with AP timeout
00:00:50 WIF: Connect failed with AP timeout
00:00:51 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:01:06 WIF: Connect failed with AP incorrect password
00:01:31 WIF: Connect failed with AP timeout
00:01:32 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:01:49 WIF: Connect failed with AP incorrect password
00:01:50 WIF: Connect failed with AP incorrect password
00:01:51 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:02:00 RSL: tele/s_51/UPTIME = {"Time":"1970-01-01T00:02:00","Uptime":"0T00:02:00"}
00:02:06 WIF: Connect failed with AP incorrect password
00:02:31 WIF: Connect failed with AP timeout
00:02:32 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:02:57 WIF: Connect failed with AP timeout
00:03:22 WIF: Connect failed with AP timeout
00:03:23 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:03:34 WIF: Connect failed as AP cannot be reached
00:03:34 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:03:59 WIF: Connect failed with AP timeout
00:04:24 WIF: Connect failed with AP timeout
00:04:25 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:04:50 WIF: Connect failed with AP timeout
00:04:59 RSL: tele/s_51/STATE = {"Time":"1970-01-01T00:04:59","Uptime":"0T00:04:59","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","POWER6":"OFF","POWER7":"OFF","Wifi":{"AP":1,"SSId":"Roby","BSSId":"FF:FF:FF:FF:FF:FF","Channel":11,"RSSI":44}}
00:04:59 RSL: tele/s_51/SENSOR = {"Time":"1970-01-01T00:04:59","ANALOG":{"A0":81}}
00:05:15 WIF: Connect failed with AP timeout
00:05:16 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:05:41 WIF: Connect failed with AP timeout
00:06:06 WIF: Connect failed with AP timeout
00:06:07 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...
00:06:24 WIF: Connect failed with AP incorrect password
00:06:49 WIF: Connect failed with AP timeout
00:06:50 WIF: Connecting to AP1 Roby in mode 11N as s_51-3039...

```

### TO REPRODUCE
 enter wrong wifi password, Wifi manager do not comes up. The device not gos in AP mode


### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

After few connection to wifi error go into AP mode

**Comment by Jason2866** [comment]
As designed. Look in wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#Wi-Fi
Command `WifiConfig`

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
