### ISSUE TITLE
Tasmota on Tuya Smart Wireless WiFi Water Gas Shut-Off Valve

### ISSUE THREAD

**Issue by antibill51** [arendst/Sonoff-Tasmota#5457]
Hi.
Has anyone ever tried to install tasmota on a device like this one?
[https://www.alibaba.com/product-detail/Tuya-Smart-Wireless-WiFi-Water-Gas_60750642284.html](url)
Thanks.

**Comment by Jason2866** [comment]
This is Github Issue. See https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md
Visit Tasmota Discord Chat for questions around Tasmota

**Comment by ascillato2** [comment]
### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.

**Comment by amitubale** [comment]
https://blakadder.github.io/templates/jinvoo_SM-PW713.html

**Comment by prankousky** [comment]
I am waiting for this product to be delivered. Can you please explain how to flash tasmota onto it (or rather, where to solder rx,tx,3.3v and gnd? )?

**Comment by Dylantje** [comment]
Hi some has this valve working?

**Comment by NorthernMan54** [comment]
@Dylantje It appears that someone has this working after flashing with Tasmota.  And they note that they used to tuya-convert

https://templates.blakadder.com/owfeel_EN71.html

**Comment by mrmaximas** [comment]
@NorthernMan54 may be you have backup of original tuya fw from this valve?? i want to revert it, but lost my backup ;(

**Comment by NorthernMan54** [comment]
@mrmaximas Sorry, no backup

**Comment by prankousky** [comment]
Me neither, sorry @NorthernMan54
