### ISSUE TITLE
The Hebrew Release not in Hebrew.

### ISSUE THREAD

**Issue by rt400** [arendst/Sonoff-Tasmota#5465]
Hi ,

The Hebrew bin file does not contain in hebrew. show only in english .

please fix it. thanks .

**Comment by ascillato** [comment]
Hi,

The language file for hebrew is not completed translated.

If you are able to edit it and translate it, you will be helping us a lot.

**Comment by ascillato** [comment]
If you want to help us, one way of editing the language file is browsing the code by the webpage of github, go to the folder language and open he-HE.h
Then click on the pencil (edit), make the modifications you think are appropiated and then you can save it. After that, github will save the changes on your own fork (your own version of Tasmota) and right after that will pop up a message to make a pull request to main Tasmota repository for verification.

**Comment by ascillato2** [comment]
If you need further assistant, please ask here or in the Tasmota support chat. Thanks.

**Comment by rt400** [comment]
@ascillato it was translate by me. once..
This is not intentionally completed because there are no Hebrew words for English words so there are still English words in this file. Most of the things that can be translated logically made the rest do not need to be translated.
