### ISSUE TITLE
TimeZone < -1 issue

### ISSUE THREAD

**Issue by dariosm** [arendst/Sonoff-Tasmota#547]
It seems like setting timezone to a value lower than -1 is always -1.
```
17:27:14 CMND: timezone 1
17:27:14 MQTT: stat/sonoff5/RESULT = {"Timezone":1}
19:27:21 CMND: timezone -1
19:27:21 MQTT: stat/sonoff5/RESULT = {"Timezone":-1}
17:27:23 CMND: timezone -3
17:27:23 MQTT: stat/sonoff5/RESULT = {"Timezone":-1}
```

By looking at the code, I've found it correct:
```
    else if (!strcmp_P(type,PSTR("TIMEZONE"))) {
      if ((data_len > 0) && (((payload >= -12) && (payload <= 12)) || (99 == payload))) {
        sysCfg.timezone = payload;
      }
      snprintf_P(svalue, sizeof(svalue), PSTR("{\"Timezone\":%d}"), sysCfg.timezone);
```

I've temporally added this debug line: 
`printf("<payload: %d><svalue: %d>\n",payload,svalue);`
... to check the value of `payload` and is always `-1` for every value lower than `0`. I'm wondering, could be `payload` negative?

**Comment by arendst** [comment]
It's a regression caused by setting a wrong default value for payload. Change line 919 into:
```
    int16_t payload = -99;               // No payload
```
which should solve the situation.

**Comment by dariosm** [comment]
Working
