### ISSUE TITLE
candlelight effect for normal PWM LED

### ISSUE THREAD

**Issue by computerkoenig** [arendst/Sonoff-Tasmota#5470]
It would be really nice to have a candlelight effect for normal RGB LEDs.
For example now I have a esp8266 RGB Strip controller and only a "white" LED connected.
It would be really nice to have a candlelight for this white led. Like a little bit flickering.

Do you need more informations?

**Comment by ascillato** [comment]
Yes, please, add more information but to the already open request for more effects at https://github.com/arendst/Sonoff-Tasmota/issues/3480

Thanks

**Comment by ascillato2** [comment]
Issue moved to #3480 

Thanks for sharing your ideas :+1:
