### ISSUE TITLE
Feature Request: End of support for TasmotaMQTT

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#5474]
**Is your feature request related to a problem? Please describe.**

TasmotaMQTT is not needed since PUBSUBCLIENT has all needed features and uses lower resources.

**Describe the solution you'd like**
Delete library and remove entry in my_user_config.h

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Allright with me. 

Same for MQTT_ARDUINOMQTT?

**Comment by Jason2866** [comment]
Yes, there where no people asking for ARDUINOMQTT in Discord too...
