### ISSUE TITLE
Streamline Template GUI in a single page

### ISSUE THREAD

**Issue by blakadder** [arendst/Sonoff-Tasmota#5481]
Would it make sense to have all the template options in the **Configure Template** menu page instead of one part being in Configure Template and the other in Configure Other.

Here's a mockup of an idea, not a perfect solution since the page has to be scrolled on certain resolutions but atleast its all in one place

![image](https://user-images.githubusercontent.com/5904370/54472928-3980f380-47d1-11e9-93c3-e6c5853b9422.png)

You can save on space if you remove the header **Import Template** and instead write it in the submit button. Not sure it makes that option as straightforward:

![image](https://user-images.githubusercontent.com/5904370/54472979-db084500-47d1-11e9-94fe-0dfa86478d4d.png)

**Comment by arendst** [comment]
The issue is with the logic needed to upgrade the changes made to either the selects when an import is done or the template text when a select is changed; they tend to deviate this way.

**Comment by blakadder** [comment]
Not worth the trouble and time then.
If the documentation is good it shouldn't be an issue having them separate as it is now
