### ISSUE TITLE
remove user selectable gpio assignments from shelly

### ISSUE THREAD

**Issue by blakadder** [arendst/Sonoff-Tasmota#5487]
Some people tend to be dumb and we had a too many (imho) inquiries about attaching peripherals to Shelly1 exposed gpios even after being strongly advised against that and pointing them to the wiki warning. 

**Describe the solution you'd like**
Completely remove user configurable gpio's for shelly products. If someone really knows what they're doing they'll figure it out with templates instead of having one dumbass electrocuting himself or someone else.

**Comment by underwoodblog** [comment]
Didn't agree. Because two things are eternal: The universe and human stupidity. So a "dumbass" finds a soluten to electrocute himself anyway. 

**Describe the solution you'd like**
Let Darwin sort them all out.
https://teespring.com/shop/let-darwin-sort-them-all-out#pid=212&cid=5822&sid=front

**Comment by meingraham** [comment]
Yes, remove configurable GPIOs from the built-in modules.

But still leave a warning that if they decide to configure a Shelly via a template (e.g., using Shelly as the BASE), they need to beware. Maybe amp up the warning to say modifications of Shelly devices are **highly NOT recommended** unless they **absolutely know what they are doing** and that any modifications they perform, like any device, is completely their responsibility, etc., etc., etc.

The alternative is that they see that the device has exposed GPIOs and they make modifications and have not been given a warning. They go forward with what looks similar to other devices and end up harming themselves! Better that they are provided with information and warnings than to hope inexperienced users don't delve into making modifications.

**Comment by ascillato** [comment]
Totally agree with @Blakadder
That is a safer path.
The proof that this is needed are the insistent questions for adding sensors to a non isolated device in the Tasmota support chat.

**Comment by ascillato2** [comment]
PR https://github.com/arendst/Sonoff-Tasmota/pull/5489
