### ISSUE TITLE
PN532 HSU not working ELECHOUSE card and WEMOS D1

### ISSUE THREAD

**Issue by olix74** [arendst/Sonoff-Tasmota#5497]
Hi,
first of all thank you for all your efforts!
I would like to connect PN532.
I'm using latest tasmota 6.5.0 release on WEMOS d1 and NFC MODULE V3 from ELECHOUSE.
I'm building sonoff-sensors with enabled #define USE_PN532_HSU with PlatformIO and Visual Studio Code successfully.
I do connect as follows:
wemos d1-->PN532
GND-->GND
3V3-->VCC
D1-->SCL/RXD
D2-->SDA/TXD
I also configued PINs and config as described on the wiki page for PN532.

Initialy communication did not seem to work at all. I debugged a lot and added some retries to the code and by that I could get communication up and running "sporadicaly" and was able to read NFC cards, but never managed to get it running stable. I also noticed some timing issues with the retries, since removing debug output changed communication behavior.
I also tried NODEMCU instead of WEMOS and tried 3 different PN532 from totaly different suppliers, different cables etc - problem always seems to be the same.

Has anyone ever observed similar issues. Any idea on what I may be doing wrong?
Currently I assume serial communication is highly unstable, but I don't know why or how to fix.

One more question: I tried to compile with #define USE_PN532_HSU on sonoff-classic, the resulting image was running fine but would not allow me to configure PN_532_RX or TX on the device config - any hint here?
 Thank you all,
Oliver

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry. Please, check in the already open issue (https://github.com/arendst/Sonoff-Tasmota/issues/4941). Thanks

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
