### ISSUE TITLE
Enable analog(A0) on Air

### ISSUE THREAD

**Issue by hwarang098tkd** [arendst/Sonoff-Tasmota#5498]
I have wemo d1 mini and i updated via ota. after this update to 6.5 firm analog pin disappear, Is it possible to enable it without flash it vi ausb again?
thnx in advance

**Comment by ascillato** [comment]
If you want the analog pin, you need to use the sonoff-sensors.bin version. The rest of the binaries are compiled with the internal VCC instead.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
