### ISSUE TITLE
Feature request: Option for default DisplayMode in my_user_config.h

### ISSUE THREAD

**Issue by wongnam** [arendst/Sonoff-Tasmota#5508]
(As i understand display feature did not have technical supported officially.)

Currently the default DisplayMode is always 1(date/time) after device reset to default.

I want to self-compile the fw dedicate use for my energy monitor(Wemos+PZEM004T+LCD1602 display). i usually have to type DisplayMode 2 in console to use for local sensor info, or displaymode 0 to use with my MQTT sent info. 

Please let us have an option to chose a default displaymode. or any workaround is ok. Thanks.
(edit: just a workaround is ok for me as i understand that add more option will lead to more byte of code.)

BTW, DisplayRows, DisplayCols, DisplayModel. Thanks.

**Comment by curzon01** [comment]
workaround using [rules](https://github.com/arendst/Sonoff-Tasmota/wiki/Rules):

```
Rule1 on System#Boot do DisplayMode 2 endon
Rule1 1
Rule1 4
```

**Comment by wongnam** [comment]
Thanks @curzon01 . if this will be deleted after reset configuration by pressing button 40s?
I want to burn it in to ROM so that it will not be deleted after reset configuration.

**Comment by curzon01** [comment]
Rules will not outlast reset device settings.

An alternative would be patch the function SettingsDefaultSet_5_10_1() in settings.ino line 840...

**Comment by wongnam** [comment]
@curzon01 It was great, to me it was satisfying what I expected. Thanks so much for the solution.

**Comment by ArjitJangid** [comment]
currently i have designed a display pattern of data in arduino how can i display similar data in tasmota like reading status of gpio and current time with ip to login
