### ISSUE TITLE
How to read value HIGH and LOW from switch and apply to rules ?

### ISSUE THREAD

**Issue by tinamore** [arendst/Sonoff-Tasmota#5515]
Hi, i use version Sonoff-Tasmota v6.5.0 and Core 2.4.2.

When i set: GPIO3 Serial In as Switch1 (9). and GPIO1 Serial Out as Switch2 (10)

and set rules
```
rule1 on Switch1#state=1 do POWER1 1 endon
rule2 on Switch2#state=1 do POWER1 0 endon
```

I want create two separate on and off buttons and input to GPIO3 and GPIO1.

But it seems the switch automatically controls the relay before run rules.

How to read HIGH and LOW values from switch and apply to rules ?

**Comment by ascillato** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#16-using-an-external-button-with-single-press---double-press-and-hold

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md)).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
