### ISSUE TITLE
BH1750: Tasmota Sensors needed?

### ISSUE THREAD

**Issue by heikoh81** [arendst/Sonoff-Tasmota#5518]
Hi,

can I use standard Tasmota with BH1750, or do I need Tasmota sensors.
Wiki does not state this.

For TSL2561, Wiki says Tasmota sensors is needed:
https://github.com/arendst/Sonoff-Tasmota/wiki/Wemos-D1-Mini-and-TSL2561-Luminosity-Sensor#tsl2561-luminosity-sensor-i2c

Both sensors seem to be I2C, so I'm wondering what version to use.

Greetings,
Heiko

**Comment by arendst** [comment]
How about release notes https://github.com/arendst/Sonoff-Tasmota/releases

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by heikoh81** [comment]
Thanks.
