### ISSUE TITLE
MTU issue

### ISSUE THREAD

**Issue by revk** [arendst/Sonoff-Tasmota#5530]
Web server not working via limited MTU remote link (i.e. my VPN).

This may be a library issue, or maybe it is something the tasmota s/w can set if we have a config option, but it seems that the MTU in the initial SYN from the client is ignored. I have tried prepping for 1460 and 1500 and MTU with no luck.

I have a dump showing TCP MSS in initial SYN of 1360 but first full packet from device is 1460 Tcp segment length, and oddly shows a TCP checksum error too.

Version 6.5.0 on a Sonoff basic.

Is there any way the Tasmota can have an MTU/MSS config?

**Comment by Jason2866** [comment]
Have you tried to compile a version by yourself with a different lwip setting?
Try lwip setting higher bandwidth. Which core do you use?
Without `Status 0` it is hard....

**Comment by revk** [comment]
Bandwidth is not the issue, but can you clarify where lwip settings are, thanks.
It looks like a faulty TCP stack, but trying to see if any workaround.

**Comment by Jason2866** [comment]
If you use Arduino IDE you find the infos here https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE
When using platformio as IDE you have to change in platformio.ini Infos are here
https://github.com/arendst/Sonoff-Tasmota/wiki/PlatformIO

**Comment by Jason2866** [comment]
See https://github.com/esp8266/Arduino/issues/5902

**Comment by revk** [comment]
Thanks
