### ISSUE TITLE
Constant URL for reboot

### ISSUE THREAD

**Issue by einarmiger0815** [arendst/Sonoff-Tasmota#5531]
Hello, is it possible not to change the URL for the reboot page with every release?

I've created a script in the Iobroker, which reads out all Tasmota devices at a certain time by reading out the properties in the Sonoff adapter.
But if with every release this url changes (from "/?rstrt" to "/?rst" etc.) such a script is impossible.

Not always you want to update all devices to the latest firmware - why even if they work ...

**Comment by Jason2866** [comment]
I didnt change over a long time....

**Comment by einarmiger0815** [comment]
For sure. Please test for yourself:

In Version 5.X it was http://ipadress/rb?"

In version 6.4.x it was "http://ipadress/?rstrt=", now in 6.5.x it is "http://ipadress/?rst=". Unfortunately

**Comment by curzon01** [comment]
Use [official commands](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands) like [Reset 1](https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#management) by http request:

`http://sonoff/cm?cmnd=Reset%201` or
`http://sonoff/cm?cmnd=Reset%2099`

This has never changed as long as ca can remmeber

**Comment by einarmiger0815** [comment]
Okay, will look for the simple reboot-command and try...

**Comment by Jason2866** [comment]
5.x is that oooooold

**Comment by jziolkowski** [comment]
5.x was used by Noah on the Ark...

**Comment by einarmiger0815** [comment]
I know, it was an example ...

**Comment by Jason2866** [comment]
Please read and respect next time ;-) https://github.com/arendst/Sonoff-Tasmota/blob/master/CONTRIBUTING.md

**Comment by einarmiger0815** [comment]
For sure. Nevertheless, the question is not unjustified, since the repeated change of the link is a fact.

But now I know what I can use. Thank you, that fits.
