### ISSUE TITLE
Sonoff 4Ch Pro R2 - flashing issues

### ISSUE THREAD

**Issue by zzzZZZzzz9** [arendst/Sonoff-Tasmota#5542]
Hi all, 

I flashed my Sonoff 4Ch Pro R2 a few weeks back, worked like a charm. Yesterday, I tried upgrading the firmware using the web interface. After the restart, I wasn't able to access it anymore.

Then I connected it to the computer in flash mode and flashed it again using PlatformIO which looks successful. But it doesn't connect to my WiFi i.e. no new IP pops up in my network.

When connected to electricity, the WiFi led is slowly flashing blue. I can control all 4 channels using the buttons but the button funtions described [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage) do not work.

Any idea what the issue might be?

This is the Build Panel Output during flashing:

`Processing sonoff-DE (framework: arduino; platform: espressif8266@1.8.0; board: esp01_1m)
 
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz 80KB RAM (1MB Flash)

Converting sonoff.ino
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 54 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <PubSubClient> 2.6
|-- <Adafruit SGP30 Sensor> 1.0.2
|   |-- <Wire> 1.0
|-- <I2Cdevlib-ADS1115>
|   |-- <I2Cdevlib-Core>
|   |   |-- <Wire> 1.0
|-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |-- <SPI> 1.0
|-- <ESP8266WiFi> 1.0
|-- <Mutichannel_Gas_Sensor> 0.0.1
|   |-- <Wire> 1.0
|-- <SPI> 1.0
|-- <Adafruit ILI9341> 1.2.0
|   |-- <Adafruit GFX Library> 1.2.9

|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <ESP8266HTTPClient> 1.1
|   |-- <ESP8266WiFi> 1.0
|-- <TasmotaSerial> 2.3.0
|-- <C2Programmer> 1.0.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <LiquidCrystal_I2C>
|   |-- <Wire> 1.0
|-- <NeoPixelBus> 2.2.9
|   |-- <SPI> 1.0
|-- <OneWire> 2.3.2
|-- <BME680_driver-bme680_v3.5.9>
|-- <MQTT> 2.4.0
|-- <LinkedList>
|-- <Wire> 1.0
|-- <NewPing> 1.9.1
|-- <TasmotaMqtt> 1.0.0
|-- <DNSServer> 1.1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoJson> 5.13.4

|-- <Ticker> 1.0
|-- <IRremoteESP8266> 2.5.2
|-- <rc-switch> 2.6.2
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <Adafruit SSD1306> 1.1.2
|   |-- <Adafruit GFX Library> 1.2.9
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|   |-- <SPI> 1.0
|-- <Joba_Tsl2561> 2.0.7
|   |-- <Wire> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
|-- <I2Cdevlib-MPU6050>
|   |-- <I2Cdevlib-Core>
|   |   |-- <Wire> 1.0
|-- <Adafruit LED Backpack Library> 1.1.6
|   |-- <Adafruit GFX Library> 1.2.9
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <ESP8266httpUpdate> 1.2
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266HTTPClient> 1.1
|   |   |-- <ESP8266WiFi> 1.0
|-- <TasmotaModbus> 1.1.0
|   |-- <TasmotaSerial> 2.3.0
|-- <Adafruit CCS811 Library> 1.0.0
|   |-- <Wire> 1.0
|-- <Adafruit GFX Library> 1.2.9
|   |-- <SPI> 1.0
|-- <I2Cdevlib-Core>
|   |-- <Wire> 1.0
|-- <ESP KNX IP Library> 0.5.1
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <EEPROM> 1.0
Compiling .pioenvs\sonoff-DE\src\Parsing.cpp.o
Compiling .pioenvs\sonoff-DE\src\core_esp8266_timer.c.o
Compiling .pioenvs\sonoff-DE\src\core_esp8266_wiring_digital.c.o

Compiling .pioenvs\sonoff-DE\src\core_esp8266_wiring_pwm.c.o
sonoff\Parsing.cpp:25:2: warning: #warning **** Tasmota is using v2.4.2 patched Parsing.cpp as planned **** [-Wcpp]
#warning **** Tasmota is using v2.4.2 patched Parsing.cpp as planned ****
^
sonoff\core_esp8266_timer.c:25:2: warning: #warning **** Tasmota is using v2.4.0 timer.c as planned **** [-Wcpp]
#warning **** Tasmota is using v2.4.0 timer.c as planned ****
^
sonoff\core_esp8266_wiring_pwm.c:25:2: warning: #warning **** Tasmota is using v2.4.0 wiring_pwm.c as planned **** [-Wcpp]
#warning **** Tasmota is using v2.4.0 wiring_pwm.c as planned ****
^
sonoff\core_esp8266_wiring_digital.c:25:2: warning: #warning **** Tasmota is using v2.4.0 wiring_digital.c as planned **** [-Wcpp]
#warning **** Tasmota is using v2.4.0 wiring_digital.c as planned ****
^
Compiling .pioenvs\sonoff-DE\src\sonoff.ino.cpp.o
Generating LD script .pioenvs\sonoff-DE\ld\eagle.app.v6.common.ld
Compiling .pioenvs\sonoff-DE\libf66\PubSubClient-EspEasy-2.6.09\PubSubClient.cpp.o
Compiling .pioenvs\sonoff-DE\lib294\Wire\Wire.cpp.o
Compiling .pioenvs\sonoff-DE\libe47\Adafruit_SGP30-1.0.0.13\Adafruit_SGP30.cpp.o
Archiving .pioenvs\sonoff-DE\lib294\libWire.a
Compiling .pioenvs\sonoff-DE\lib355\I2Cdevlib-Core\I2Cdev.cpp.o
Archiving .pioenvs\sonoff-DE\libf66\libPubSubClient-EspEasy-2.6.09.a
Compiling .pioenvs\sonoff-DE\lib080\I2Cdevlib-ADS1115\ADS1115.cpp.o
Archiving .pioenvs\sonoff-DE\libe47\libAdafruit_SGP30-1.0.0.13.a
Compiling .pioenvs\sonoff-DE\lib8e0\SPI\SPI.cpp.o

[... more compiling and archiving...]

Compiling .pioenvs\sonoff-DE\FrameworkArduino\uart.c.o
Compiling .pioenvs\sonoff-DE\FrameworkArduino\umm_malloc\umm_malloc.c.o
Archiving .pioenvs\sonoff-DE\libFrameworkArduino.a

Linking .pioenvs\sonoff-DE\firmware.elf
Retrieving maximum program size .pioenvs\sonoff-DE\firmware.elf
Building .pioenvs\sonoff-DE\firmware.bin
Checking size .pioenvs\sonoff-DE\firmware.elf
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [======    ]  60.2% (used 49328 bytes from 81920 bytes)
PROGRAM: [=====     ]  52.5% (used 537172 bytes from 1023984 bytes)
Configuring upload protocol...
Looking for upload port...
Use manually specified: COM5
Uploading .pioenvs\sonoff-DE\firmware.bin
Uploading 541312 bytes from .pioenvs\sonoff-DE\firmware.bin to flash at 0x00000000
................................................................................ [ 15% ]
................................................................................ [ 30% ]
................................................................................ [ 45% ]
................................................................................ [ 60% ]
................................................................................ [ 75% ]
................................................................................ [ 90% ]
.................................................                                [ 100% ]
 [SUCCESS] Took 178.58 seconds
 

 [SUMMARY]
Environment sonoff              [SKIP]
Environment sonoff-minimal      [SKIP]
Environment sonoff-basic        [SKIP]
Environment sonoff-classic      [SKIP]
Environment sonoff-knx          [SKIP]
Environment sonoff-sensors      [SKIP]
Environment sonoff-display      [SKIP]
Environment sonoff-BG           [SKIP]
Environment sonoff-BR           [SKIP]
Environment sonoff-CN           [SKIP]
Environment sonoff-CZ           [SKIP]
Environment sonoff-DE           [SUCCESS]
Environment sonoff-ES           [SKIP]
Environment sonoff-FR           [SKIP]
Environment sonoff-GR           [SKIP]
Environment sonoff-HE           [SKIP]
Environment sonoff-HU           [SKIP]
Environment sonoff-IT           [SKIP]
Environment sonoff-KO           [SKIP]
Environment sonoff-NL           [SKIP]
Environment sonoff-PL           [SKIP]
Environment sonoff-PT           [SKIP]
Environment sonoff-RU           [SKIP]
Environment sonoff-SE           [SKIP]
Environment sonoff-SK           [SKIP]
Environment sonoff-TR           [SKIP]
Environment sonoff-TW           [SKIP]
Environment sonoff-UK           [SKIP]
 [SUCCESS] Took 178.59 seconds`

**Comment by Jason2866** [comment]
Erase flash with esptool https://github.com/arendst/Sonoff-Tasmota/wiki/Esptool#erase-firmware
Upload with esptool a precompiled Tasmota version to be sure using a working build
http://thehackbox.org/tasmota/release/sonoff-DE.bin

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md)).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
