### ISSUE TITLE
Is there Any timer to calculate relay Uptime ?

### ISSUE THREAD

**Issue by hwarang098tkd** [arendst/Sonoff-Tasmota#5546]
I was wondering if there is inner timer for relays(power). I want to sen to my openhab the min that a relay is on or off!!! I know that i can do it with code in openhab but is safer to do this work the client.

**Comment by Jason2866** [comment]
No, maybe it can be done via rules.

**Comment by hwarang098tkd** [comment]
Any suggestion?

**Comment by Jason2866** [comment]
No, not really. Never thought about this...
You find examples for rules here https://github.com/arendst/Sonoff-Tasmota/wiki/Rules

**Comment by ascillato2** [comment]
Hi,

Sorry, there is not an easy way to do that without modifying the code. 

Anyway, that uptime is meant to be managed in your home automation software. 

Adding label feature request (hold over) for future reference. 

Thanks for sharing your ideas.
