### ISSUE TITLE
sonoff 4ch pro toggles all 4 relays - only 1 relay at the same time is on

### ISSUE THREAD

**Issue by marcelkussin** [arendst/Sonoff-Tasmota#5548]
The Problem is:
I switch POWER1 to ON
Then POWER2 to ON, then the Sonoff/Tasmota switches POWER1 OFF
This happens with all 4 relays.

__Switchmode__ is 0
__Interlock__ is 0

__Version__: 6.5.0.1
__Language__: German

## STATUS
6:03:23 CMD: status 0
16:03:23 SRC: WebConsole from 192.168.178.74
16:03:23 RSL: empfangenes topic /status, Datengröße 1, Daten 0
16:03:23 RSL: Gruppe 0, Index 1, Befehl STATUS, Daten 0
16:03:23 MQT: stat/sonoff4chPro/STATUS = {"Status":{"Module":23,"FriendlyName":["Sonoff4ch","Sonoff4ch2","Sonoff4ch3","Sonoff4ch4"],"Topic":"sonoff4chPro","ButtonTopic":"0","Power":4,"PowerOnState":0,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
16:03:23 MQT: stat/sonoff4chPro/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Power on","Uptime":"0T00:19:30","StartupUTC":"2019-03-29T14:43:53","Sleep":50,"CfgHolder":5656,"BootCount":5,"SaveCount":66,"SaveAddress":"FA000"}}
16:03:23 MQT: stat/sonoff4chPro/STATUS2 = {"StatusFWR":{"Version":"6.5.0.1(sonoff)","BuildDateTime":"2019.03.29 15:32:54","Boot":6,"Core":"2_5_0","SDK":"3.0.0-dev(c0f7b44)"}}
16:03:23 MQT: stat/sonoff4chPro/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["KoMa",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
16:03:23 MQT: stat/sonoff4chPro/STATUS4 = {"StatusMEM":{"ProgramSize":571,"Free":432,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000407","0FDAE394","000783A0","23B617CE","00003BC0"]}}
16:03:23 MQT: stat/sonoff4chPro/STATUS5 = {"StatusNET":{"Hostname":"sonoff4chPro-1941","IPAddress":"192.168.178.80","Gateway":"192.168.178.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.178.1","Mac":"84:0D:8E:46:27:95","Webserver":2,"WifiConfig":4}}
16:03:23 MQT: stat/sonoff4chPro/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.178.64","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_462795","MqttUser":"","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
16:03:23 MQT: stat/sonoff4chPro/STATUS7 = {"StatusTIM":{"UTC":"Fri Mar 29 15:03:23 2019","Local":"Fri Mar 29 16:03:23 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"06:34","Sunset":"19:15"}}
16:03:23 MQT: stat/sonoff4chPro/STATUS10 = {"StatusSNS":{"Time":"2019-03-29T16:03:23"}}
16:03:23 MQT: stat/sonoff4chPro/STATUS11 = {"StatusSTS":{"Time":"2019-03-29T16:03:23","Uptime":"0T00:19:30","Vcc":3.475,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":23,"POWER1":"OFF","POWER2":"OFF","POWER3":"ON","POWER4":"OFF","Wifi":{"AP":1,"SSId":"KoMa","BSSId":"32:56:27:EB:D8:49","Channel":11,"RSSI":58,"LinkCount":1,"Downtime":"0T00:00:04"}}}

## CONSOLE:
16:02:30 CMD: weblog 4
16:02:30 MQT: stat/sonoff4chPro/RESULT = {"WebLog":4}
16:02:31 CFG: in Flash gespeichert am F4, zählen 64, Bytes 3584
16:02:32 HTP: Hauptmenü
16:02:35 SRC: WebGui from 192.168.178.74
16:02:35 MQT: stat/sonoff4chPro/RESULT = {"POWER1":"ON"}
16:02:35 MQT: stat/sonoff4chPro/POWER1 = ON
16:02:35 APP: Knopf2 level 1-0
16:02:35 SRC: Button
16:02:35 MQT: stat/sonoff4chPro/RESULT = {"POWER2":"OFF"}
16:02:35 MQT: stat/sonoff4chPro/POWER2 = OFF
16:02:36 CFG: in Flash gespeichert am FB, zählen 65, Bytes 3584
16:02:39 WIF: Prüfe Verbindung...
16:02:39 WIF: verbunden
16:02:56 SRC: WebGui from 192.168.178.74
16:02:56 MQT: stat/sonoff4chPro/RESULT = {"POWER3":"ON"}
16:02:56 MQT: stat/sonoff4chPro/POWER3 = ON
16:02:57 APP: Knopf1 level 0-1
16:02:57 SRC: Button
16:02:57 MQT: stat/sonoff4chPro/RESULT = {"POWER1":"OFF"}
16:02:57 MQT: stat/sonoff4chPro/POWER1 = OFF
16:02:57 CFG: in Flash gespeichert am FA, zählen 66, Bytes 3584
16:02:59 WIF: Prüfe Verbindung...

**Comment by meingraham** [comment]
Check the settings on the hardware itself. The 4Ch PCB has dip switches to set interlock/self-lock mode.

**Comment by marcelkussin** [comment]
thank you, i just discovered this little dip switches. closed
