### ISSUE TITLE
Sonoff RF R2 power, difference between GPIO2 and IO3(Rx)?

### ISSUE THREAD

**Issue by dwengticorp** [arendst/Sonoff-Tasmota#5550]
I have sonoff with new design, 8265 chip and printed Sonoff RF R2.

It doesn't have GPIO14, but has a GPIO2 with pin hole filled.

I tried to connect a DHT11 sensor, it didn't work with GPIO2, I ended up connect it to the  GPIO3(RX) pin, then it worked fine.

No with another Sonoff, I tried to connect RF receiver to the GPIO3(RX), it didn't work, but when I connected it to GPIO2, it worked.

So I wonder anyone can tell me why it behaviors like that, what is the different between the GPIO2 and GPIO3?

**Comment by blakadder** [comment]
This is not a forum for various inquiries, you can ask your question in our discord channel
