### ISSUE TITLE
Multiple bridge installations

### ISSUE THREAD

**Issue by jwoodard80** [arendst/Sonoff-Tasmota#5553]
**Have you look for this feature in other issues and in the wiki?**
Yes, I didn't see something exactly related

**Is your feature request related to a problem? Please describe.**
I have 433mhz sensors spread out all over my home and I have 3 sonoff RF bridges spaced out to try to improve the overall reach and stability. Works good, howeve, if one of the bridges happens to get a signal as well, the multiple mqtt publishes are made. This usually doesn't cause issues but sometimes it does. 

**Describe the solution you'd like**
it seems this is implemented in this project, however, I enjoy tasmota too much to change so I'm hoping it could be incorporated into a future release. 
https://github.com/1technophile/OpenMQTTGateway/wiki/Multiple-gateway-installation

If someone has an alternative I'm happy to try. I just thought the above sounded promising and I do not want to change my firmware. :-)

**Comment by Jason2866** [comment]
Dont understand what could make a issue. You get in worst case some mqtt messages with the info from you RF433 device. I use this setup too. No problem, just check in my Home Automation system the messages i get and consolidate the infos....

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
