### ISSUE TITLE
sonoff discovery using raspberry pi and nmap

### ISSUE THREAD

**Issue by sbeland2** [arendst/Sonoff-Tasmota#5556]
my device: wifi smart plug from costco CE smart home by charging essentials.
my raspberry: pi zero wifi using AP (192.168.44.1) + STA (192.168.0.135)

my device is connected to my raspberry pi AP, i have an ssh session on my pi using the pi AP address with putty from windows.  I also have another ssh session with my pi STA.

i did my test from the pi logged with AP and STA, the same problem occured.

i have written a script (below) using nmap and sometimes nmap works, sometimes not, it can be fast response and sometimes very slow (1 min to 2 min) to get a reply from the smartplug.

if i connect my smartplug on the house's router at 192.168.0.1, everything works perfect and very fast (less than 1 sec).

only when the smartplug is connected to my pi AP show problems.

the real problem is not my script itself which i explain further below, it is more a problem with nmap as shown here:

 sudo nmap -sn 192.168.44.*

Starting Nmap 7.40 ( https://nmap.org ) at 2019-03-30 14:10 EDT
Nmap scan report for DESKTOP-DELL (192.168.44.51)
Host is up (0.0055s latency).
MAC Address: ********* (Intel Corporate)
Nmap scan report for 192.168.44.1
Host is up.
Nmap done: 256 IP addresses (2 hosts up) scanned in 1.94 seconds
pi@RpiOffice:~ $ sudo nmap -sn 192.168.44.*

Starting Nmap 7.40 ( https://nmap.org ) at 2019-03-30 14:10 EDT
Nmap scan report for DESKTOP-DELL (192.168.44.51)
Host is up (0.0049s latency).
MAC Address:********** (Intel Corporate)
Nmap scan report for 192.168.44.1
Host is up.
Nmap done: 256 IP addresses (2 hosts up) scanned in 1.98 seconds
pi@RpiOffice:~ $ sudo nmap -sn 192.168.44.*

Starting Nmap 7.40 ( https://nmap.org ) at 2019-03-30 14:10 EDT
Nmap scan report for DESKTOP-DELL (192.168.44.51)
Host is up (0.0072s latency).
MAC Address: *********** (Intel Corporate)
Nmap scan report for 192.168.44.1
Host is up.
Nmap done: 256 IP addresses (2 hosts up) scanned in 1.95 seconds
pi@RpiOffice:~ $ sudo nmap -sn 192.168.44.*

Starting Nmap 7.40 ( https://nmap.org ) at 2019-03-30 14:10 EDT
Nmap scan report for DESKTOP-DELL (192.168.44.51)
Host is up (0.0023s latency).
MAC Address: *********** (Intel Corporate)
Nmap scan report for sonoff-7135 (192.168.44.60)
Host is up (0.13s latency).
MAC Address: ********** (Unknown)
Nmap scan report for 192.168.44.1
Host is up.
Nmap done: 256 IP addresses (3 hosts up) scanned in 4.56 seconds

here, i finally get my device sonoff-7135 on the fourth try with nmap, what's wrong with that???

calling my script like this: ./findsonoff 192.168.44.1 -v

here's my script:

#!/bin/bash

if [ "$1" == "" ]; then
  echo "provide a ip address to scan, the last digit will be removed"
  exit
fi

verbose=0
if [ "$2" == "-v" ]; then
  verbose=1
fi

count=0
i=`echo "$1" | sed 's/.$//'`
i2="$i*"

for j in [1..3] 
do
  echo "scanning on $i2"
  p=`sudo nmap -sn "$i2"`
  p2=`echo "$p" | grep "sonoff"`
  if [ "$p2" != "" ]; then
    break
  fi
  echo "got $p2, retry"
  sleep 1
done

p2=`echo "$p" | grep "sonoff" | awk '{print $6}' | sed 's/[()]//g'`
if [ $verbose -eq 1 ]; then
  echo "result: $p"
  echo "filter: $p2"
fi

IFS=$'\n'

for line in "$p2"
do
  if [ "$line" == "" ]; then
     continue
  fi
  
  if [ $verbose -eq 1 ]; then
    echo "trying: $line"
  fi
  c=`curl http://"$line"/cm?cmnd=power`
  r=`echo "$c" | grep "{\"POWER\":" | sed s/{\"POWER\"://g | sed s/[\"}]//g`
  if [ "$r" != "" ]; then
     h=`curl http://"$line"/cm?cmnd=friendlyname`
     hn=`echo $h | sed s/"{\"FriendlyName1\":\""//g | sed s/[\"}]//g`     
     echo "name:'$hn' state:'$r' ip:'$line'"
     
  fi
done

output:
scanning on 192.168.44.*
result:
Starting Nmap 7.40 ( https://nmap.org ) at 2019-03-30 13:32 EDT
Nmap scan report for DESKTOP-DELL (192.168.44.51)
Host is up (0.042s latency).
MAC Address: **************** (Intel Corporate)
Nmap scan report for sonoff-7135 (192.168.44.60)
Host is up (0.61s latency).
MAC Address: *************** (Unknown)
Nmap scan report for 192.168.44.1
Host is up.
Nmap done: 256 IP addresses (3 hosts up) scanned in 4.07 seconds
filter: 192.168.44.60
trying: 192.168.44.60
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15    0    15    0     0      4      0 --:--:--  0:00:03 --:--:--     4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:12 --:--:--     0curl: (7) Failed to connect to 192.168.44.60 port 80: Connection timed out
name:'' state:'OFF' ip:'192.168.44.60'

but sometimes, output is this:
 ./findsonoff 192.168.44.1 -v
scanning on 192.168.44.*
got , retry
result:
Starting Nmap 7.40 ( https://nmap.org ) at 2019-03-30 13:23 EDT
Nmap scan report for DESKTOP-DELL (192.168.44.51)
Host is up (0.0039s latency).
MAC Address: ************ (Intel Corporate)
Nmap scan report for 192.168.44.1
Host is up.
Nmap done: 256 IP addresses (2 hosts up) scanned in 5.56 seconds
filter:

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md)).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
