### ISSUE TITLE
Kingart Q4

### ISSUE THREAD

**Issue by mclaudiopt** [arendst/Sonoff-Tasmota#5572]
Hello
can  Kingart Q4 be the same as this one ?
if yes, can it be flashed and used the same way for courtain?

the kingart q4 is this one
https://github.com/arendst/Sonoff-Tasmota/issues/5059

**Comment by Jason2866** [comment]
Please read https://github.com/arendst/Sonoff-Tasmota/blob/master/CONTRIBUTING.md

For questions visit Tasmota Support Chat in [Discord](https://discord.gg/Ks2Kzd4)

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md)).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
