### ISSUE TITLE
Sonoff SC MQTT Message after 5 Minutes

### ISSUE THREAD

**Issue by BrutalBirdie** [arendst/Sonoff-Tasmota#558]
This more a Question because I have an Issue with the Sonoff SC 😀 

I noticed that the Sonoff SC only sends his State every 5 Minutes and I sadly did find any command to control it https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

Is there some way to increase the MQTT message frequency ?

**Comment by SwiftNick** [comment]
There a setting called the Telemetric period on the Configure Logging page web page.
Tray changing that.

**Comment by BrutalBirdie** [comment]
Could you also tell me how to calibrate the temperature sensor etc. ?

**Comment by arendst** [comment]
You cannot calibrate the temperature sensor.

**Comment by davidelang** [comment]
look for loginterval (default 300)
k
