### ISSUE TITLE
Black web server UI instead of white

### ISSUE THREAD

**Issue by Markkyboy** [arendst/Sonoff-Tasmota#5586]
**Have you look for this feature in other issues and in the wiki?**
Yes, I only found one question asking where/how to make UI changes.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To change the current UI to black from white, easier on the eyes for night time usage

**Describe alternatives you've considered**
Using a plugin to 'invert' colours, but no plugin exists for my device.
Or, perhaps just a button within the UI to 'invert' page colours, making the general background either white or black - I am a big fan of black backgrounds! ;)

**Additional context**
Only 3 lines needed editing to make the changes I desired. All are inside xdrv_webserver.ino;

Line 242 - add 'background-color:black' to fieldset
Line 248 - add 'background-color:black' to completely fill page background with black 
Line 265 - add 'background-color:black; color:white;' to invert original white text to black

![Screenshot_20190405_001](https://user-images.githubusercontent.com/6370412/55625510-52b20a00-57a9-11e9-8b40-ba35c5e6036e.png)

![Screenshot_20190405_002](https://user-images.githubusercontent.com/6370412/55625512-52b20a00-57a9-11e9-8c98-5075e6b6e189.png)

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Implemented as options in my_user_config.h

Give it a try!

**Comment by Markkyboy** [comment]
Hi Theo,

That's wonderful news, thank you!, when I get 5 minutes, I will most certainly check it out.

Regards,

Mark


  ----- Original Message -----

**Comment by Markkyboy** [comment]
Hi, not sure if this is the right place to post this, but while compiling this version in Atom, I noticed red text fly by, scrolling back, I took a screenshot as I could not successfully swipe the right bit of text.

![HU compile error](https://user-images.githubusercontent.com/6370412/55675441-e7f4f180-58c2-11e9-9cd8-535988cdd062.JPG)

**Comment by Markkyboy** [comment]
Request fulfilled.
