### ISSUE TITLE
Zemismart boiler switch configuration

### ISSUE THREAD

**Issue by rhayun** [arendst/Sonoff-Tasmota#5587]
Hi all

i purchase the Zemismart Boiler switch and flash it with tuya-convert and tasmota
now i am trying to set the GPIO to make it work and its bit hard

did someone have template for that or can help?

![56119378_10157446672021122_6607128004537614336_o](https://user-images.githubusercontent.com/769417/55628138-94967c80-57b8-11e9-9aaf-fd0915a8b34b.jpg)
![56158099_10157446675996122_503762027022385152_o](https://user-images.githubusercontent.com/769417/55628139-952f1300-57b8-11e9-8568-ee033c0083e7.jpg)
![56178632_10157446563631122_2665928944141729792_n](https://user-images.githubusercontent.com/769417/55628140-952f1300-57b8-11e9-8e93-cad505018e2f.jpg)
![56280027_10157446676161122_802786841399918592_o](https://user-images.githubusercontent.com/769417/55628142-952f1300-57b8-11e9-9c83-65fe4372371e.jpg)
![56551774_10157446563261122_5091479125755953152_n](https://user-images.githubusercontent.com/769417/55628143-952f1300-57b8-11e9-8192-e791f8b3a991.jpg)
![56790921_10157446563406122_2695655168711589888_n](https://user-images.githubusercontent.com/769417/55628144-95c7a980-57b8-11e9-89e2-1f7637d18771.jpg)

**Comment by ascillato** [comment]
From your photos, seems that your device has another mcu. It can't be seen clearly, but if it has another processors you will need the original firmware to see the communication between the esp8266 and that other microcontroller and make also the driver or rules for that.

If you have backed up the original firmware, you can have some support on that reverse engineering in the Tasmota support chat

**Comment by rhayun** [comment]
i did it myself and its seems to be working like this:

![image](https://user-images.githubusercontent.com/769417/55630636-cdd1eb00-57be-11e9-9dfd-82cb700d30e0.png)

but i am not sure if the tempeture sensor is working

**Comment by blakadder** [comment]
Can you submit the device to the [templates database ](https://blakadder.github.io/templates/)

As far as temperature sensor, you can find it with the continuity setting on your multimeter since all the chip gpio's are nicely labelled and easily reached although I didn't spot it in the board images. Maybe its a simple thermistor?

**Comment by ascillato2** [comment]
@rhayun

Hi,

Have you managed to find the right temperature sensor and to submit the complete template?

**Comment by rhayun** [comment]
{"NAME":"Zemismart WH","GPIO":[53,255,255,17,21,255,255,255,255,255,52,255,255],"FLAG":1,"BASE":18}

**Comment by blakadder** [comment]
That is correct. Issue closed.
