### ISSUE TITLE
The problem of The HC-SR501 PIR Motion Detection in sonoff

### ISSUE THREAD

**Issue by vaguecupid** [arendst/Sonoff-Tasmota#559]
I want add HC-SR501 PIR Motion Detection to the sonoff, so I set GPIO14  to 09switch1, set GPIO1 to 10switch2, set SwitchMode to 0, set SwitchTopic to 1. I add the switch to GPIO14, and PIR to GPIO1.

the result is switch can work perfectly, the PIR can work,but console and MQTT always show（no “OFF”）:

> cmnd/sonoff/POWER2 = ON
stat/sonoff/RESULT = {"Command":"Unknown"}
cmnd/sonoff/POWER2 = ON
stat/sonoff/RESULT = {"Command":"Unknown"}

**Comment by davidelang** [comment]
cmnd/ switches relays, not switches.
you would need to have two relays defined before power2 does anything

**Comment by vaguecupid** [comment]
I test use the relay,but PIR(relay 2) can not work.

**Comment by jhlweb** [comment]
set `Switchmode2 1` this lets switch2 follow the state and publishes it

**Comment by EdelHert** [comment]
Thanks jhlweb, thats works for me. The only problem I am having still is that the switch does not stay on. It turns on for 36 seconds (PIR-delay), then turns off, even with motion, and turns on after 6 seconds again.. Any idea how I can make it to stay on until no motion is detected
