### ISSUE TITLE
BlitzwWolf SHP2 LED is orange after updating to 6.5

### ISSUE THREAD

**Issue by Merwenus** [arendst/Sonoff-Tasmota#5590]
Updated my blitzwolf smart connectors to v6.5.0 from v6.4.1 and the blue led became orange. I couldn't find option for it in the webui and google didnt really help.

How can I revert back the LED color to the original blue from orange? Orange looks like something is wrong with the device.

**Comment by Merwenus** [comment]
Got answer on discord. Template should be this:

{"NAME":"BlitzWolf SHP","GPIO":[56,255,57,255,0,134,0,0,131,17,132,21,0],"FLAG":0,"BASE":45}

**Comment by ascillato2** [comment]
Thanks for sharing that. Very appreciated.
