### ISSUE TITLE
RELEASE.md for module 52 (Teckin SP20) incorrect

### ISSUE THREAD

**Issue by ptmoy2** [arendst/Sonoff-Tasmota#5591]
I'm running Tasmota v6.5.0 (pre-compiled sonoff.bin" downloaded from the release site) on a Teckin SP20 smart plug with energy monitoring.  When I set module type to "Teckin 52" as recommended in the release notes,  the toggle doesn't work, and no monitored values are displayed on the Tasmota device web page.  However, everything seems to work as expected when I set module type to "Techkin US - 59."

Is this a mistake in the Release Notes, or a problem with the "Teckin -52" settings?

**Comment by blakadder** [comment]
Do you have this plug https://www.amazon.de/gp/product/B07D5V139R

**Comment by ptmoy2** [comment]
No, I have this one:

https://www.amazon.com/gp/product/B079Q5W22B/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1 

Bottom of the plug says Model: SP20

**Comment by Jason2866** [comment]
Manufactures do change there products and sell it with same or different names...
If you found a working setting everything is fine. 
That means template isnt false, device "just" changed.
You can add a note to the SP20 template that maybe template Teckin-52 is the right choice for a variant of the SP 20

**Comment by blakadder** [comment]
Ah ok. I understand the problem now. 

@ascillato @arendst RELEASE.md incorrectly states that module `Teckin (52)` applies to [Teckin SP20 ](https://www.teckinhome.com/copy-of-sp-22-2 )which is in fact module `Teckin US (59)`. 
Judging by the link in sonoff_template.h module `52` should be [Teckin SP22](https://www.teckinhome.com/copy-of-sp-23).
Furthermore module 45 also names Teckin SP22 
![image](https://user-images.githubusercontent.com/5904370/55706547-c0487b00-59e1-11e9-9673-6a363a9170a7.png)
but the pinouts for `45` and `52` are different.
Reading #3950 does not clarify much.
Is module 52 meant for older board revisions of Teckin SP22? 
If it is obsoleted by a new version compatible with module 45 it might be prudent to remove the module or change the name to avoid user confusion.

**Comment by Jason2866** [comment]
@blakadder  Yes there are different Teckin SP22 versions (different GPIO layout)

**Comment by blakadder** [comment]
Ok, but still RELEASENOTES.md state its SP20 when it is in fact not, Teckin SP20 is Teckin US module

**Comment by ascillato2** [comment]
Closing this issue as the PR #5606 has been made to fix this. Thanks for your contributions.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
