### ISSUE TITLE
How to determine Smart Bulb Module Parameters

### ISSUE THREAD

**Issue by garnern2** [arendst/Sonoff-Tasmota#5601]
I have successfully flashed a non-upgraded Teckin Smart Bulb (https://www.amazon.com/Dimmable-Multicolor-Compatible-TECKIN-Equivalent/dp/B07GT2Q5RW). I can access the bulb's settings in the Tasmota web interface, but I cannot for the life of be set the parameters so that the bulb works as expected. I've attempted to use the color commands and can only get green, white, and occasionally red--albeit in the wrong order. I know this is because my parameter settings are incorrect, but is there a way that I can determine what they should be? I'm willing to go the trial and error route, but I've been doing that four 5 hours and have still had no luck.

If this is a dumb question, I sincerely apologize--but I have indeed attempted to find the answer myself and I'm now at an impasse.

**Comment by Jason2866** [comment]
Take a look at https://github.com/arendst/Sonoff-Tasmota/issues/4883
You have enter manualy in the web console the command
Color 1 should be light red
Color 2 should be light green
Color 3 should be light blue
Read the Wiki -> Commands
If you read https://github.com/arendst/Sonoff-Tasmota/issues/1867 you get a idea how it works...

**Comment by Jason2866** [comment]
You can try ready made templates too. Maybe one fits to your bulb
https://blakadder.github.io/templates/light.html

**Comment by blakadder** [comment]
Here you go https://blakadder.github.io/templates/teckin-sb50.html

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
