### ISSUE TITLE
Simple EVSE-WB / EVSE-DIN with Modbus RS485

### ISSUE THREAD

**Issue by roesl** [arendst/Sonoff-Tasmota#5609]
Hi,
I want to control my EVSE-DIN which has Modbus protocol with Sonoff Tasmota ( MQTT) to set charging current or read the status of the device, so I could also use several Inputs or outputs of the tasmota device too.
Because there are also modules for IP-Symcon and other Smarthome applications available it would be easy to charge vehicles with solar power.

**Comment by Jason2866** [comment]
What is your question?

**Comment by roesl** [comment]
I want to control the evse-din with modbus rs485 so I need a device for tasmota to do this

**Comment by Jason2866** [comment]
Modbus Protocol isnt supported from Tasmota. 
You can connect Modbus hardware as described here
https://github.com/arendst/Sonoff-Tasmota/issues/3694#issuecomment-424743666

**Comment by roesl** [comment]
there is the SDM630 Energy meter ( this has Modbus protocol)  as device in tasmota so I think it would be also possible to add the device EVSE-DIN

**Comment by Jason2866** [comment]
There is a specific driver made for this device. This would be needed for the device you want too.
There is no general solution...

**Comment by roesl** [comment]
is anybody able to make a driver for the EVSE - I think there are many people interested because they  will drive Electric vehicles in the future

**Comment by ascillato2** [comment]
@roesl 

Thanks for sharing your ideas. It is indeed very interesting. I personally like it a lot, but would be very difficult to develop a driver for it without having the actual hardware and obviously without the car for testing.

I'm adding the label feature request (hold over) for future reference and work.

Also, I'm posting here some links with extra information about this.

EVSE-WB =  Electric Vehicle Supply Equipment for Wallbox
EVSE-DIN = Electric Vehicle Supply Equipment for DIN

EVSE is for European Standard

Compatibility:
• Tesla Model S
• Nissan Leaf
• Mitsubishi iMiev (Peugeon iOn, Citroen cZero)
• Opel Ampera
• eGolf
• Mitsubishi Outlander PHEV
• Citroen Berlingo Electrique
• and others

Board explanation: http://openwb.de/manuals/evse-wb-din_20180611.pdf
Protocol: https://www.openevse.com/
To Buy: https://www.off-grid-systems.de/Simple-EVSE-WB-Wallbox-Bausatz

**Comment by ascillato2** [comment]
For now you can use as a workaround the serial-mqtt bridge feature of Tasmota as @Jason2866 has explained.

Thanks
