### ISSUE TITLE
T1 led flashing

### ISSUE THREAD

**Issue by lammy666** [arendst/Sonoff-Tasmota#5625]
I have a T1 which I have flashed with v 6.5.0.  (one of several)  However the LED continues to flash.  The device has been configured and re-flashed but I still get the same result.  

The trouble shooting suggests and issue with the flashing "This indicates that the ESP-8266 did not get flashed properly" but other than the LED the device works as expected.  I couldnt find any other relevant info on this issue.  Below is a short video.

Any ideas?  I am sorry if I have missed something I am relatively new to Tasmota.

https://photos.app.goo.gl/Sn6saKkbFchveFbs5

  
Status 0 OUTPUT:

22:45:20 CMD: status 0
22:45:20 RSL: stat/sonoff/STATUS = {"Status":{"Module":29,"FriendlyName":["Kitchen Main","Kitchen Main 2"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":0,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
22:45:20 RSL: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Power on","Uptime":"0T00:00:21","StartupUTC":"2019-04-11T21:44:59","Sleep":50,"CfgHolder":4617,"BootCount":10,"SaveCount":58,"SaveAddress":"F4000"}}
22:45:20 RSL: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.5.0(release-sonoff)","BuildDateTime":"2019-03-19T12:24:10","Boot":7,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
22:45:20 RSL: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Router-t2sw",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
22:45:20 RSL: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":507,"Free":496,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0FDAE394","000783A0","23B617CE","00003BC0"]}}
22:45:20 RSL: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"S_kitchen_main","IPAddress":"192.168.1.72","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.254","Mac":"84:0D:8E:51:98:B0","Webserver":2,"WifiConfig":4}}
22:45:20 RSL: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_5198B0","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
22:45:20 RSL: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Thu Apr 11 21:45:20 2019","Local":"Thu Apr 11 22:45:20 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"06:07","Sunset":"19:35"}}
22:45:20 RSL: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2019-04-11T22:45:20"}}
22:45:20 RSL: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2019-04-11T22:45:20","Uptime":"0T00:00:21","Vcc":3.152,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"Router-t2sw","BSSId":"C2:4A:00:5B:4E:C0","Channel":13,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:06"}}}

**Comment by ascillato2** [comment]
Led blinking means wifi not configured or mqtt not configured. 

Please, if you need more help address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md)).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
