### ISSUE TITLE
Problem: switch off after losing Wifi

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#563]
Hi,

My last comment was about the version 3... Now I'm back with :-).

I notice a problem with my sonoffs connected to a MQTT server and switched via Domoticz. If the sonoff lose the connection to the MQTT server then the sonoff power off.
For example: if I reboot the MQTT server then the sonoff switch go to off. Same happend with a sonoff outside... there are two access points, the sonoff switch between both WiFi points and all the time this item goes off.

I also notice another thing. Some of my sonoff toggle for a while or reboot 3-5 times after an update. Tested with version 5.2.2.

Thanks for your help
Fabian

**Comment by 0n3-70uch** [comment]
Found another interesting thing:
Normally if I'm upgrading the Sonoffs then the devices go off for a second or less. But with the new firmware the devices go off and not on again. And the Domiticz status is also incorrect. Some switches are off but Domoticz show me an on.

**Comment by arendst** [comment]
Sounds like you are using one of the many MQTT message retain options. Turn them off and try again.

**Comment by 0n3-70uch** [comment]
Hi Theo,

no the retain options are off. I test it with the original firmware with only these changes:
`
#ifdef WIFI_GATEWAY
#undef WIFI_GATEWAY
#endif
#define WIFI_GATEWAY    "192.168.2.1"

#ifdef WIFI_DNS
#undef WIFI_DNS
#endif
#define WIFI_DNS    "192.168.2.1"

#ifdef STA_SSID1
#undef STA_SSID1
#endif
#define STA_SSID1   "name1"

#ifdef STA_PASS1
#undef STA_PASS1
#endif
#define STA_PASS1   "password"

#ifdef STA_SSID2
#undef STA_SSID2
#endif
#define STA_SSID2   "name1"

#ifdef STA_PASS2
#undef STA_PASS2
#endif
#define STA_PASS2   "password"

#ifdef SYS_LOG_HOST
#undef SYS_LOG_HOST
#endif
#define SYS_LOG_HOST    "192.168.2.11"

#ifdef OTA_URL
#undef OTA_URL
#endif
#define OTA_URL     "http://192.168.2.11:8080/Updates/" PROJECT ".ino.generic.bin"

#ifdef MQTT_HOST
#undef MQTT_HOST
#endif
#define MQTT_HOST   "192.168.2.11"

#ifdef MQTT_USER
#undef MQTT_USER
#endif
#define MQTT_USER   "mosquitto"

#ifdef MQTT_PASS
#undef MQTT_PASS
#endif
#define MQTT_PASS   "password"

#ifdef MQTT_CLIENT_ID
#undef MQTT_CLIENT_ID
#endif
#define MQTT_CLIENT_ID    "Sonoff_%06X"

#ifdef MQTT_GRPTOPIC
#undef MQTT_GRPTOPIC
#endif
#define MQTT_GRPTOPIC   "Sonoffs"

#ifdef WEB_SERVER
#undef WEB_SERVER
#endif
#define WEB_SERVER    0

#ifdef WEB_PASSWORD
#undef WEB_PASSWORD
#endif
#define WEB_PASSWORD    "password"

#ifdef USE_IR_REMOTE
#undef USE_IR_REMOTE
#endif`

**Comment by 0n3-70uch** [comment]
Hi,

the restart of the Sonoff is back... But now I got a message:
> Software Watchdog

Seems thats something is wrong. Its an standard Sonoff with attached AM2301 at GPIO14. MQTT and Domoticz is active nothing else...

**Comment by 0n3-70uch** [comment]
Hi Im closing this issue now... seems that the wifi strenght is too low (8%). I will make some test in the future...
