### ISSUE TITLE
Factory Reset after a few minutes

### ISSUE THREAD

**Issue by 42Rhino** [arendst/Sonoff-Tasmota#5637]
I have some Problems with my Shelly1. I have just flash it with Tasmota and selected the Shelly1 profile. Because i need Button functionality i changed the switch to a button. A few minutes everything works, but then Tosmota got a factory reset. 
I have tried it with DE and Basic version. All the same.

`{"NAME":"Shelly1 - Butt","GPIO":[0,0,0,0,21,90,0,0,0,0,0,0,0],"FLAG":0,"BASE":46}`

**Comment by Jason2866** [comment]
Issue template is missing. Since we are no clairvoyants no help can be provided.

**Comment by blakadder** [comment]
have you properly configured the button
you might be activating factory reset after 40 seconds since buttons have extra functionality https://github.com/arendst/Sonoff-Tasmota/wiki/Button-usage

**Comment by Jason2866** [comment]
@blakadder  Good finding! This is the issue. You cant change the switch to a button on a Shelly1.

**Comment by 42Rhino** [comment]
Thanks for the help. Now i changed the SwitchMode to 3 and it works. Sorry, but i don't know anything about the commands bevore.
