### ISSUE TITLE
Timer has only Rules#Timer=1 trigger?

### ISSUE THREAD

**Issue by MikeVRT** [arendst/Sonoff-Tasmota#5643]
If I need some special behavior **while** timer "countdowning" how to detect it?
And may be something extra like if [Rules#Timer#value > 60] todo something?

**Comment by ascillato** [comment]
Hi,

Sorry. That is not supported.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
