### ISSUE TITLE
problem GPIO sonoff Basic R2 cutted track

### ISSUE THREAD

**Issue by pilot1981** [arendst/Sonoff-Tasmota#5649]
Hi,
I have a SONOFF BASIC R2 (new layout): using 220v, I notice I don't receive signal of dry contact connected to GND and RX PIN...I try to open and close dry contact but SONOFF don't log any changes....

Using 3,3v, it work fine! Logging output say all works fine, GPIO contact communicate open/close signal...

I already tried to erase and flash again, I tried to do again soldering points...but problem remain!!!

**Comment by blakadder** [comment]
You have physically modified the device beyond the factory specifications so we cannot offer support

**Comment by pilot1981** [comment]
you give support only original HW? I can find any support on chat?

**Comment by blakadder** [comment]
You can always ask in chat, issues on github is for code issues first of all.
