### ISSUE TITLE
Question about the Shelly 2.5 GPIO connector

### ISSUE THREAD

**Issue by greensouth** [arendst/Sonoff-Tasmota#5652]
Hi!!

Does anybody know what is the name of the wires, or the connector type used for Shelly 2.5 programming? They are smaller than the ones used by -e.g.- the Raspberry GPIO port. They just don't fit and I don't know the name so I can order one.

Thanks in advance!
;)

**Comment by ascillato2** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Shelly-1-and-2#serial-connection-1

**Comment by kroon040** [comment]
Hi,

Here is not the answer, the shelly 1 and shelly 2 uses the normal dupont cables, but what cable is used for flashing the shelly 2.5? It is a debug header cable, but what size of pins on de shelly2.5 side?

regards Richard

**Comment by greensouth** [comment]
> Hi,
> 
> Here is not the answer, the shelly 1 and shelly 2 uses the normal dupont cables, but what cable is used for flashing the shelly 2.5? It is a debug header cable, but what size of pins on de shelly2.5 side?
> 
> regards Richard

it's like the connectors used when linking two LED stripes. I soldered that tiny wire which is used for closing bread bags, to dupont connectors :) and worked like a charm

**Comment by jasase** [comment]
I have the same problem. @greensouth do you have some pictures or a little bit more details?

**Comment by greensouth** [comment]
Take some soldering iron, a thin wire and solder it to the metallic tip of the Dupont connector. Then you can insert easily in the Shelly.

**Comment by thxthx0** [comment]
or buy some **1.27 mm Pin Headers** :)

e.g. https://www.aliexpress.com/item/1-27mm-1-27-Pin-Header-Single-Row-Male-Breakaway-PCB-Board-Connector-Pinheader-1-2/32914658645.html?spm=a2g0s.9042311.0.0.5c1f4c4dvITIsn

**Comment by Frigorio** [comment]
I did my own using a 5 rigid wire intercom cable, some hot glue and a momentary switch... works like a charm 😉

**Comment by cinemarene** [comment]
For me LED pin connectors are a real help.

![IMG_20190607_224856](https://user-images.githubusercontent.com/9309569/59134413-5f0a3d00-897b-11e9-99c9-36523629e312.jpg)
![IMG_20190607_224940](https://user-images.githubusercontent.com/9309569/59134414-5fa2d380-897b-11e9-929d-4cf98639f23c.jpg)
![IMG_20190607_224923](https://user-images.githubusercontent.com/9309569/59134415-5fa2d380-897b-11e9-83e1-c94c63965d91.jpg)
![IMG_20190607_224946](https://user-images.githubusercontent.com/9309569/59134416-5fa2d380-897b-11e9-8fc5-4b25b9e47389.jpg)

**Comment by cinemarene** [comment]
For me LED pin connectors are a real help.

![IMG_20190607_224856](https://user-images.githubusercontent.com/9309569/59134935-5ca8e280-897d-11e9-96dd-1318ace4744e.jpg)
![IMG_20190607_224923](https://user-images.githubusercontent.com/9309569/59134936-5ca8e280-897d-11e9-8142-61549cb9bd64.jpg)
![IMG_20190607_224940](https://user-images.githubusercontent.com/9309569/59134937-5d417900-897d-11e9-8db9-9292a4be9d4b.jpg)
![IMG_20190607_224946](https://user-images.githubusercontent.com/9309569/59134938-5d417900-897d-11e9-9ad0-dede051b3151.jpg)

**Comment by joba-1** [comment]
Clever to ask.
Whatever you use, insert it very gently. 
I broke off the sockets including pcb routes trying to insert small dupont pins :( 
At least I broke no connections. The device still works fine with the original fw.

**Comment by supermaninja** [comment]
I broked the connector on the shelly 2.5, are on the shelly other point where I can find rx tx.....ecc?

**Comment by Frigorio** [comment]
> Whatever you use, insert it very gently.

![IMG_20190518_125723](https://user-images.githubusercontent.com/43074128/65411938-6fd9a400-ddee-11e9-8bc7-8aee2261a894.jpg)
![IMG_20190518_131037](https://user-images.githubusercontent.com/43074128/65411959-7b2ccf80-ddee-11e9-81da-a0287ca8cf56.jpg)
![IMG_20190518_220811](https://user-images.githubusercontent.com/43074128/65411991-90a1f980-ddee-11e9-92be-a88f688c2e7a.jpg)
![IMG_20190518_220742](https://user-images.githubusercontent.com/43074128/65412034-b0d1b880-ddee-11e9-9657-16e4abe0dd2b.jpg)

**Comment by hallard** [comment]
Something like that also
![image](https://user-images.githubusercontent.com/2471931/142023643-019a7fe3-fead-4c44-856d-687165f3670f.png)
https://www.digikey.com/en/products/detail/chip-quik-inc/F127T254P06/5978243

Need to build my own with push button :-)
