### ISSUE TITLE
Can't select WS2812 in GPIO

### ISSUE THREAD

**Issue by lacsap88** [arendst/Sonoff-Tasmota#5654]
Hi,

I can't select WS2812 in the Settings with Version 6.5.0. Is ws2812 support still available or not? What am I doing wrong?

<img width="489" alt="Bildschirmfoto 2019-04-15 um 17 19 18" src="https://user-images.githubusercontent.com/4109200/56144532-d686a600-5fa2-11e9-8781-d5e654912af1.png">

**Comment by ascillato** [comment]
Please, update your device using sonoff.bin instead of sonoff-basic.bin

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
