### ISSUE TITLE
Sonoff Pow R2 not publishing power info to MQTT

### ISSUE THREAD

**Issue by nickjedl** [arendst/Sonoff-Tasmota#5657]
Hi there

My Sonoff Pow R2 is not publishing power info to MQTT all of a sudden, 10 minutes ago it was working perfectly fine...
It publishes sensor data with the default telemetry period, but it should also report the usage about every second.

Tasmota version: 6.5.0

Thanks in advance!

**Comment by nickjedl** [comment]
Just did "Status 0" which I saw somewhere on a forum, which did in fact publish the values to the correct topics, but only once: https://i.imgur.com/pCNRUSV.png

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
