### ISSUE TITLE
Possible using "Simple thermostat" from Wiki in A/C mode?

### ISSUE THREAD

**Issue by vel2000** [arendst/Sonoff-Tasmota#5661]
I'm trying to use this [thermostat example from the wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Rules#9-simple-thermostat-example), in A/C mode, but can't get it to work by only changing the "mem2-3" values.
Initial config:
`backlog SwitchMode1 3; Rule 1; Rule 4; TelePeriod 60; SetOption26 1; SetOption0 0; poweronstate 0; mem1 0; mem2 24; mem3 23; var1 0`
Rule:
`Rule on system#boot do RuleTimer1 70 endon on Switch1#State do event toggling1=%mem1% endon on event#toggling1=0 do mem 1 endon on event#toggling1=1 do mem 0 endon on Rules#Timer=1 do backlog var1 0; RuleTimer1 70; power1 0; endon on tele-SI7021#temperature do backlog var1 1; RuleTimer1 70; event ctrl_ready=1; event temp_demand=%value%; endon on event#ctrl_ready>%mem1% do var1 0 endon on event#temp_demand>%mem2% do power1 0 endon on event#temp_demand<%mem3% do power1 %var1% endon`

Since the thermostat-rules are too complicated, (at least for me...), can somebody help me out with a working rule-code like "power on =/>25° | power off =24°"?
thanks in advance.

**Comment by blakadder** [comment]
**<Please DO NOT OPEN AN ISSUE:>
  <If you have general questions or you need help on Tasmota usage, go to the Tasmota support chat>**

https://discord.gg/Ks2Kzd4
