### ISSUE TITLE
List with IR Codes

### ISSUE THREAD

**Issue by helmar74** [arendst/Sonoff-Tasmota#5662]
Hi everbody,

as  the [YTF IR Bridge](https://github.com/arendst/Sonoff-Tasmota/wiki/YTF-IR-Bridge) is supported since version 6.4.1.8, 
I ordered one and i started to collect  IR Remote Codes:
[IR Code List](https://github.com/arendst/Sonoff-Tasmota/wiki/Codes-for-IR-Remotes-(for-YTF-IR-Bridge))

Please be aware that you should use Tasmota > 6.5.0.3 as there's a bug for IR Codes > 32Bit: #5523

Everbody is invited to also collect IR Codes to get a shared information for everyone.

Regards

Helmar

**Comment by helmar74** [comment]
Closing issue

**Comment by ascillato2** [comment]
@helmar74 

Hi, 

Please, could you add this to the wiki? 

Thanks

**Comment by helmar74** [comment]
It' s in there already.....
Look at the device site

**Comment by ascillato** [comment]
Great!

Thank you very much :+1:
