### ISSUE TITLE
Hvac panasonic ac

### ISSUE THREAD

**Issue by riddik14** [arendst/Sonoff-Tasmota#5668]
I noticed that tasmota does not support hvac ir command, can you implement something about it? I tried to sniff the ir code but with the ir send command it doesn't work, does anyone use irsend / irhvac to control panasonic air conditioners?

**Comment by Jason2866** [comment]
Panasonic AC isnt supported in the used library IRremoteESP8266
Controlling AC with IR isnt just a simple sended command it uses a Protocol.
So somebody has to decode the protocol and expand the library with.
IR basic work and protocol implementation isnt the focus of Tasmota.
Maybe somebody does it someday...

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by hpirila** [comment]
Panasonic AC is now supported in latest version IRremoteESP8266 2.6. It would be nice to get that into upcoming tasmota release.
