### ISSUE TITLE
Alexa Hue Bridge On Off works but if dimming she says it appears malfunctioning

### ISSUE THREAD

**Issue by supermario1111** [arendst/Sonoff-Tasmota#5675]
Hi! I try to use a basic ESP8266 module with Tasmota firmware V6.5.
I want to control my own roller shutter system with it. The idea is to connect a simple module (ESP-07S) to my existing electronics with UART, and from the messages I can read out, what the shutter should to do. If i turn off the 5 minutes debug message counter (stop decreasing the counter), it will work constantly. It's OK, I tried it.
I can connect it to Alexa, but with HueEmulation works only the simple ON/OFF command. If i set the dimmer from the application (Alexa), then it goes back to the last dimming value, writes Device malfunction, and a second later it goes to the right, new dimming value. If I ask Alexa, the same thing happens. I can see on uart the debug messages, and it get the new dimming value, but after a while alexa says it is not responding. Now I am trying it as AiLight, but I have tried everything. 
So the ON/OFF works, but the dimming is not working as well. I have attached a picture from terminal.
![alexa_dim_problem](https://user-images.githubusercontent.com/49785417/56424798-03440180-62b2-11e9-9710-d8e03e39dd3b.png)

**Comment by s-hadinger** [comment]
This is solved by PR #5667, still under validation.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
