### ISSUE TITLE
sonoff basic unable to connect from home assistant

### ISSUE THREAD

**Issue by zinghs** [arendst/Sonoff-Tasmota#5676]
hi all,
I have several sonoff devices flashed with tasmota 6.5.0, however I am unable to get one of my sonoff basics connected to home assistant.
I have checked previous similar posts but unfortunately none can solve my issue.

<img width="347" alt="sonoff_basic" src="https://user-images.githubusercontent.com/38904999/56424964-dfe67a00-62e4-11e9-8fdd-05c3ed445b3f.PNG">

configuration.yaml
switch:
  - platform: mqtt
    name: "Kitchen Light"
    command_topic: "cmnd/sonoffKL/POWER"
    state_topic: "stat/sonoffKL/POWER"
    availability_topic: "tele/sonoffKL/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

Appreciate for any help and thanks in advance

Regards,
Ferry

**Comment by Jason2866** [comment]
Please read wiki https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant
Tasmota Release V.6.5.0 does work well with HA

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
