### ISSUE TITLE
#define D_START_UPGRADE is unnecessary

### ISSUE THREAD

**Issue by ngalfas** [arendst/Sonoff-Tasmota#5677]
This is more like memory improvement...

I really think that #define D_START_UPGRADE is unnecessary string.
I am currently reviewing the greek translation and i made a change on this define.

I noticed this..
![tasmota1](https://user-images.githubusercontent.com/22976096/56427973-79eafa00-62c6-11e9-92f9-148f8338f2c7.png)

I didn't go to check the code but i bet this is the strings used on this page.  I really do not see any reason to have different labels on these two buttons.

**Comment by arendst** [comment]
Nice one.

If you searched the code you would find a reason for it. 

The string D_START_UPGRADE could be replaced by D_START + D_UPGRADE.

The code using D_START + D_UPGRADE is also being used by D_START + D_RESTORE.

So it might be an option to keep D_START_UPGRADE and add D_START_RESTORE. The code would be larger to handle this. Codespace was/is an issue.

For now we keep it this way.

**Comment by ngalfas** [comment]
I see.  It's a code housekeeping issue then :)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
