### ISSUE TITLE
AM2301 - adjust readings

### ISSUE THREAD

**Issue by agoralive** [arendst/Sonoff-Tasmota#5686]
This has been asked before.... I KNOW but always the answer is:

It's writting in the Wiki, under rules BUT:

Where do I type these rules? In "Console"?

What do I do exactly if I wan't the temperature reading down by 3.4 degrees?

This is the reading which I have:
```
15:58:26 RSL: STATE = {"Time":"2019-04-22T15:58:26","Uptime":"0T00:06:59","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"Wifi":{"AP":1,"SSId":"KK-NET2.4","BSSId":"70:3A:CB:F6:92:27","Channel":6,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:10"}}
15:58:26 RSL: SENSOR = {"Time":"2019-04-22T15:58:26","ANALOG":{"A0":0},"AM2301":{"Temperature":25.3,"Humidity":27.3},"TempUnit":"C"}
```

**Comment by Staars** [comment]
I guess you search for this topic under RULES in the wiki:
8.b. Adjust the value of a sensor and send it by MQTT

You can use the web console.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
