### ISSUE TITLE
Add use of Varx to DisplayText

### ISSUE THREAD

**Issue by gpearston** [arendst/Sonoff-Tasmota#5687]
It would be helpful and a powerful extension if adding the ability to display the contents of the variables Var1, Var2, Var3, Var4 and Var5 using DisplayText.  

Being able to use the variables in a manner similiar to:

Rule on Var1#State do DisplayText [s1l1c1]%Var1% endon
so the contents of Var1 are displayed at the location described.

**Comment by ascillato2** [comment]
Hi,

That is already implemented. 

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
