### ISSUE TITLE
Gosund SP111/Blitzwolf SHP6 Fatal Exceptions

### ISSUE THREAD

**Issue by pyro2k8** [arendst/Sonoff-Tasmota#5688]
I experience different Fatal exceptions when installing the plugs at location with less 60% Wifi signal strengh. Example: 
`{"RestartReason":"Fatal exception:0 flag:2 (EXCEPTION) epc1:0x4025d01f epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000001 depc:0x00000000"}`
The number of the exception differs from time to time.

The plug then restarts many times - you can hear the relay sound...

I also use 2 SP111 1m near the Wifi Ap, that works fine...

Firmware is Tasmota 6.5.0 with Arduino Core 2.3.0.

**Comment by Jason2866** [comment]
Have you erased the whole flash before flashing Tasmota?
This issues are most of the time from fragments left in flash.
You can try `reset 5` This erase all settings and deletes flash. Only wifi credentials kept

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
