### ISSUE TITLE
Fatal exception (10k per day!) Wemos D1 with PZEM016

### ISSUE THREAD

**Issue by xCapeITA** [arendst/Sonoff-Tasmota#5690]
I have bound a Wemos D1 mini to a PZEM016 and configured the tasmota as in the guide, but D1 keeps restarting like every minute , with 10.000 reboots per day.
Reason for reboot is a fatal exception.
I tried more than one D1 and more than one PZEM with no luck. Without GPIO configuration D1 has no issue
Thanks

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [X] Device used (i.e. Sonoff Basic) : Wemos D1mini
- [X] Tasmota binary firmware version number used : 6.50 precompiled
- [X] Provide the output of command ``status 0`` :

00:00:00 Project sonoff Sonoff Version 6.5.0(release-sensors)-2_3_0
00:00:00 WIF: Connecting to AP1 FASTWEB_DGX in mode 11N as pzem016-7967...
00:00:03 RSL: tele/pzem016/SENSOR = {"Time":"1970-01-01T00:00:03","ENERGY":{"TotalStartTime":"2019-04-20T15:02:23","Total":5313.981,"Yesterday":0.029,"Today":5313.952,"Power":605,"ApparentPower":666,"ReactivePower":278,"Factor":0.91,"Frequency":50,"Voltage":234,"Current":2.841}}
00:00:07 WIF: Connected
00:00:07 HTP: Web server active on pzem016-7967 with IP address 192.168.1.138
08:43:42 MQT: Attempting connection...
08:43:44 MQT: Connected
08:43:44 MQT: tele/pzem016/LWT = Online (retained)
08:43:44 MQT: cmnd/pzem016/POWER = 
08:43:44 MQT: tele/pzem016/INFO1 = {"Module":"Generic","Version":"6.5.0(release-sensors)","FallbackTopic":"cmnd/DVES_32DF1F_fb/","GroupTopic":"sonoffs"}
08:43:44 MQT: tele/pzem016/INFO2 = {"WebServerMode":"Admin","Hostname":"pzem016-7967","IPAddress":"192.168.1.138"}
08:43:44 MQT: tele/pzem016/INFO3 = {"RestartReason":"Fatal exception:0 flag:2 (EXCEPTION) epc1:0x40238690 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000"}
08:43:52 MQT: tele/pzem016/STATE = {"Time":"2019-04-23T08:43:52","Uptime":"0T00:00:18","SleepMode":"Dynamic","Sleep":50,"LoadAvg":22,"Wifi":{"AP":1,"SSId":"FASTWEB_DGX","BSSId":"A0:64:8F:DF:88:E9","Channel":1,"RSSI":68,"LinkCount":1,"Downtime":"0T00:00:07"}}
08:43:52 MQT: tele/pzem016/SENSOR = {"Time":"2019-04-23T08:43:52","ANALOG":{"A0":11},"ENERGY":{"TotalStartTime":"2019-04-20T15:02:23","Total":5313.984,"Yesterday":0.029,"Today":5313.955,"Period":3,"Power":572,"ApparentPower":636,"ReactivePower":277,"Factor":0.90,"Frequency":50,"Voltage":235,"Current":2.707}}
08:44:06 CMD: STATUS 0
08:44:06 MQT: stat/pzem016/STATUS = {"Status":{"Module":18,"FriendlyName":["Sonoff"],"Topic":"pzem016","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
08:44:06 MQT: stat/pzem016/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-sensors.bin","RestartReason":"Exception","Uptime":"0T00:00:32","StartupUTC":"2019-04-23T07:43:34","Sleep":50,"CfgHolder":4617,"BootCount":10377,"SaveCount":10411,"SaveAddress":"FB000"}}
08:44:06 MQT: stat/pzem016/STATUS2 = {"StatusFWR":{"Version":"6.5.0(release-sensors)","BuildDateTime":"2019-03-19T12:26:22","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
08:44:06 MQT: stat/pzem016/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["FASTWEB_DGX",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
08:44:06 MQT: stat/pzem016/STATUS4 = {"StatusMEM":{"ProgramSize":544,"Free":456,"Heap":12,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"16400E","FlashMode":3,"Features":["00000809","0FDEE394","0007A3A4","B7FFBFCC","005ABBC0"]}}
08:44:06 MQT: stat/pzem016/STATUS5 = {"StatusNET":{"Hostname":"pzem016-7967","IPAddress":"192.168.1.138","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.254","Mac":"3C:71:BF:32:DF:1F","Webserver":2,"WifiConfig":4}}
08:44:06 MQT: stat/pzem016/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.119","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_32DF1F","MqttUser":"brokers","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
08:44:06 MQT: stat/pzem016/STATUS7 = {"StatusTIM":{"UTC":"Tue Apr 23 07:44:06 2019","Local":"Tue Apr 23 08:44:06 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"05:44","Sunset":"19:53"}}
08:44:06 MQT: stat/pzem016/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
08:44:06 MQT: stat/pzem016/STATUS10 = {"StatusSNS":{"Time":"2019-04-23T08:44:06","ANALOG":{"A0":12},"ENERGY":{"TotalStartTime":"2019-04-20T15:02:23","Total":5313.986,"Yesterday":0.029,"Today":5313.957,"Power":572,"ApparentPower":634,"ReactivePower":275,"Factor":0.90,"Frequency":50,"Voltage":235,"Current":2.703}}}
08:44:06 MQT: stat/pzem016/STATUS11 = {"StatusSTS":{"Time":"2019-04-23T08:44:06","Uptime":"0T00:00:32","SleepMode":"Dynamic","Sleep":50,"LoadAvg":29,"Wifi":{"AP":1,"SSId":"FASTWEB_DGX","BSSId":"A0:64:8F:DF:88:E9","Channel":1,"RSSI":72,"LinkCount":1,"Downtime":"0T00:00:07"}}}

- [ ] Provide the output of console when you experience your issue if apply :

00:00:00 CFG: Loaded from flash at F4, Count 10490
00:00:00 SRC: Restart
00:00:00 Project sonoff Sonoff Version 6.5.0(release-sensors)-2_3_0
00:00:00 WIF: Checking connection...
00:00:00 WIF: Attempting connection...
00:00:00 WIF: Patch issue 2186
00:00:00 WIF: Connecting to AP1 FASTWEB_DGX in mode 11N as pzem016-7967...
00:00:01 WIF: Checking connection...
00:00:01 WIF: Attempting connection...
00:00:02 DMP: 01 04 14 09 1D 06 32 00 00 0A AB 00 00 2B B8 00 00 01 F4 00 4A 00 00 D5 EB
00:00:02 WIF: Checking connection...
00:00:02 WIF: Attempting connection...
00:00:03 RSL: tele/pzem016/SENSOR = {"Time":"1970-01-01T00:00:03","ENERGY":{"TotalStartTime":"2019-04-20T15:02:23","Total":5314.131,"Yesterday":0.029,"Today":5314.102,"Power":273,"ApparentPower":370,"ReactivePower":250,"Factor":0.74,"Frequency":50,"Voltage":233,"Current":1.586}}
00:00:03 DMP: 01 04 14 09 1D 06 32 00 00 0A A9 00 00 2B B8 00 00 01 F3 00 4A 00 00 67 69
00:00:03 WIF: Checking connection...
00:00:03 WIF: Attempting connection...
00:00:04 DMP: 01 04 14 09 1E 06 33 00 00 0A AD 00 00 2B B8 00 00 01 F3 00 4A 00 00 7C 39
00:00:04 WIF: Checking connection...
00:00:04 WIF: Attempting connection...
00:00:05 DMP: 01 04 14 09 1E 06 32 00 00 0A AB 00 00 2B B8 00 00 01 F4 00 4A 00 00 91 AF
00:00:05 WIF: Checking connection...
00:00:05 WIF: Attempting connection...
00:00:06 DMP: 01 04 14 09 1D 06 34 00 00 0A AD 00 00 2B B8 00 00 01 F3 00 4A 00 00 8A 4C
00:00:06 WIF: Checking connection...
00:00:06 WIF: Attempting connection...
00:00:07 DMP: 01 04 14 09 20 06 34 00 00 0A B0 00 00 2B B9 00 00 01 F4 00 4A 00 00 7E 68
00:00:07 WIF: Checking connection...
00:00:07 WIF: Connected
00:00:07 HTP: Web server active on pzem016-7967 with IP address 192.168.1.138
00:00:07 APP: (UTC) Tue Apr 23 08:16:58 2019, (DST) Sun Mar 31 02:00:00 2019, (STD) Sun Oct 27 03:00:00 2019
09:16:59 DMP: 01 04 14 09 1F 06 35 00 00 0A AF 00 00 2B B9 00 00 01 F4 00 4A 00 00 1D 76
09:16:59 MQT: Attempting connection...
09:17:00 DMP: 01 04 14 09 1F 06 35 00 00 0A AF 00 00 2B B9 00 00 01 F3 00 4A 00 00 A8 B6
09:17:01 DMP: 01 04 14 09 22 06 30 00 00 0A AE 00 00 2B B9 00 00 01 F4 00 4A 00 00 6D 0F
09:17:01 MQT: Connected
09:17:01 MQT: tele/pzem016/LWT = Online (retained)
09:17:01 MQT: cmnd/pzem016/POWER = 
09:17:01 MQT: Subscribe to cmnd/pzem016/#
09:17:01 MQT: Subscribe to cmnd/sonoffs/#
09:17:01 MQT: Subscribe to cmnd/DVES_32DF1F_fb/#
09:17:01 MQT: tele/pzem016/INFO1 = {"Module":"Generic","Version":"6.5.0(release-sensors)","FallbackTopic":"cmnd/DVES_32DF1F_fb/","GroupTopic":"sonoffs"}
09:17:01 MQT: tele/pzem016/INFO2 = {"WebServerMode":"Admin","Hostname":"pzem016-7967","IPAddress":"192.168.1.138"}
09:17:01 MQT: tele/pzem016/INFO3 = {"RestartReason":"Fatal exception:0 flag:2 (EXCEPTION) epc1:0x40238690 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000"}
09:17:02 DMP: 01 04 14 09 26 06 30 00 00 0A B2 00 00 2B B9 00 00 01 F3 00 4A 00 00 06 A3
09:17:02 APP: Boot Count 10456
09:17:03 CFG: Saved to flash at FB, Count 10491, Bytes 3584
09:17:03 DMP: 01 04 14 09 27 06 34 00 00 0A B8 00 00 2B B9 00 00 01 F3 00 4A 00 00 61 94
09:17:04 DMP: 01 04 14 09 2B 06 33 00 00 0A BB 00 00 2B B9 00 00 01 F4 00 4A 00 00 70 F7
09:17:05 DMP: 01 04 14 09 2A 06 33 00 00 0A BB 00 00 2B B9 00 00 01 F4 00 4A 00 00 70 F7
09:17:05 DBG: PzemAc response error 9
09:17:06 DMP: 01 04 14 09 33 06 2D 00 00 0A B3 00 00 2B B9 00 00 01 F4 00 4A 00 00 20 BB
09:17:07 DMP: 01 04 14 09 33 06 2A 00 00 0A AD 00 00 2B B9 00 00 01 F4 00 4A 00 00 BA 94
09:17:08 DMP: 01 04 14 09 32 06 2B 00 00 0A AD 00 00 2B B9 00 00 01 F4 00 4A 00 00 D6 F8
09:17:09 DMP: 01 04 14 09 32 06 2B 00 00 0A AD 00 00 2B B9 00 00 01 F4 00 4A 00 00 D6 F8
09:17:09 MQT: tele/pzem016/STATE = {"Time":"2019-04-23T09:17:09","Uptime":"0T00:00:18","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"Wifi":{"AP":1,"SSId":"FASTWEB_DGX","BSSId":"A0:64:8F:DF:88:E9","Channel":1,"RSSI":72,"LinkCount":1,"Downtime":"0T00:00:07"}}
09:17:09 MQT: tele/pzem016/SENSOR = {"Time":"2019-04-23T09:17:09","ANALOG":{"A0":11},"ENERGY":{"TotalStartTime":"2019-04-20T15:02:23","Total":5314.132,"Yesterday":0.029,"Today":5314.103,"Period":1,"Power":273,"ApparentPower":372,"ReactivePower":252,"Factor":0.74,"Frequency":50,"Voltage":235,"Current":1.579}}
09:17:10 DMP: 01 04 14 09 33 06 3A 00 00 0A C6 00 00 2B B9 00 00 01 F4 00 49 00 00 DC 7A
09:17:11 DMP: 01 04 14 08 32 06 35 00 00 0A C1 00 00 2B BA 00 00 00 F4 00 4A 00 00 06 3E
09:17:11 DBG: PzemAc response error 9
09:17:12 DMP: 01 04 14 09 31 06 2E 00 00 0A B1 00 00 2B BA 00 00 01 F4 00 4A 00 00 BA 41
09:17:13 DMP: 01 04 14 09 30 06 2C 00 00 0A AE 00 00 2B BA 00 00 01 F4 00 4A 00 00 0C 42
09:17:14 DMP: 01 04 14 09 30 06 2C 00 00 0A AE 00 00 2B BA 00 00 01 F4 00 4A 00 00 0C 42
09:17:15 DMP: 01 04 14 09 30 06 2C 00 00 0A AE 00 00 2B BA 00 00 01 F4 00 4A 00 00 0C 42
09:17:16 DMP: 01 04 14 09 30 06 2B 00 00 0A AE 00 00 2B BA 00 00 01 F4 00 4A 00 00 BE 73
09:17:17 DMP: 01 04 14 08 2E 06 2C 00 00 0A B2 00 00 2B BA 00 00 01 F4 00 4A 00 00 B0 C8
09:17:17 DBG: PzemAc response error 9
09:17:18 DMP: 01 04 14 09 2F 06 2C 00 00 0A B2 00 00 2B BA 00 00 01 F4 00 4A 00 00 B0 C8
09:17:19 DMP: 01 04 14 09 31 06 2C 00 00 0A B4 00 00 2B BA 00 00 01 F3 00 4A 00 00 A2 E4
09:17:20 WIF: Checking connection...
09:17:20 WIF: Connected
09:17:20 DMP: 01 04 14 09 32 06 2B 00 00 0A B0 00 00 2B BA 00 00 01 F4 00 4A 00 00 EF D5
09:17:21 DMP: 01 04 14 08 33 06 34 00 00 0A BC 00 00 2B BA 00 00 01 F4 00 49 00 00 0B D3
09:17:21 DBG: PzemAc response error 9
09:17:22 DMP: 01 04 14 09 33 06 34 00 00 0A BC 00 00 2B BA 00 00 01 F3 00 49 00 00 BE 13
09:17:23 DMP: 01 04 14 09 34 06 30 00 00 0A B9 00 00 2B BA 00 00 01 F4 00 4A 00 00 00 63
09:17:24 DMP: 01 04 14 09 34 06 35 00 00 0A C1 00 00 2B BA 00 00 01 F4 00 4A 00 00 B3 4A
09:17:25 DMP: 01 04 14 08 33 06 30 00 00 0A B5 00 00 2B BB 00 00 01 F4 00 49 00 00 59 4B
09:17:25 DBG: PzemAc response error 9
09:17:26 DMP: 01 04 14 09 33 06 2B 00 00 0A AC 00 00 2B BB 00 00 01 F4 00 49 00 00 00 E5
09:17:27 DMP: 01 04 14 09 33 06 2A 00 00 0A AC 00 00 2B BB 00 00 01 F3 00 4A 00 00 14 B5
09:17:28 DMP: 01 04 14 09 33 06 2A 00 00 0A AC 00 00 2B BB 00 00 01 F3 00 4A 00 00 14 B5
09:17:29 DMP: 01 04 14 09 33 06 30 00 00 0A B7 00 00 2B BB 00 00 01 F4 00 4A 00 00 AE 09
09:17:30 DMP: 01 04 14 09 32 06 2E 00 00 0A B2 00 00 2B BB 00 00 01 F4 00 4A 00 00 F6 56
09:17:31 DMP: 01 04 14 09 30 06 2D 00 00 0A B1 00 00 2B BB 00 00 01 F4 00 4A 00 00 47 21
09:17:31 DBG: PzemAc response error 9
09:17:32 DMP: 01 04 14 09 31 06 2D 00 00 0A B1 00 00 2B BB 00 00 01 F4 00 4A 00 00 47 21
09:17:33 DMP: 01 04 14 09 2E 06 2C 00 00 0A AF 00 00 2B BB 00 00 01 F4 00 4A 00 00 AD 79
09:17:34 DMP: 01 04 14 08 2E 06 2B 00 00 0A AA 00 00 2B BA 00 00 00 F4 00 4A 00 00 10 CC
09:17:34 DBG: PzemAc response error 9
09:17:35 DMP: 01 04 14 09 2D 06 2E 00 00 0A AC 00 00 2B BB 00 00 01 F4 00 4A 00 00 4D 9E
09:17:36 DMP: 01 04 14 09 2E 06 30 00 00 0A AF 00 00 2B BB 00 00 01 F4 00 49 00 00 95 BF
09:17:37 DMP: 01 04 14 08 2E 06 30 00 00 0A AF 00 00 2A BC 00 00 01 F4 00 48 00 00 B2 8F
09:17:37 DBG: PzemAc response error 9
09:17:38 DMP: 01 04 14 09 2F 06 2E 00 00 0A AD 00 00 2B BC 00 00 01 F3 00 49 00 00 55 57
09:17:39 DMP: 01 04 14 09 32 06 2F 00 00 0A AF 00 00 2B BC 00 00 01 F3 00 49 00 00 E9 EB
09:17:40 WIF: Checking connection...
09:17:40 WIF: Connected
09:17:40 DMP: 01 04 14 09 31 06 36 00 00 0A B7 00 00 2B BC 00 00 01 F3 00 49 00 00 57 E0
09:17:41 DMP: 01 04 14 08 31 06 36 00 00 0A B7 00 00 2B BC 00 00 01 F3 00 49 00 00 57 E0
09:17:41 DBG: PzemAc response error 9
09:17:42 DMP: 01 04 14 09 31 06 6D 00 00 0B 57 00 00 2B BC 00 00 01 F3 00 4B 00 00 C3 A3
09:17:43 DMP: 01 04 14 08 31 06 86 00 00 0B A8 00 00 2B BC 00 00 01 F3 00 4C 00 00 18 58
09:17:43 DBG: PzemAc response error 9
09:17:44 DMP: 01 04 14 09 31 06 88 00 00 0B AB 00 00 2B BC 00 00 01 F4 00 4C 00 00 CC 38
09:17:45 DMP: 01 04 14 09 30 06 86 00 00 0B AB 00 00 2B BC 00 00 01 F4 00 4C 00 00 95 A7
09:17:46 DMP: 01 04 14 09 30 06 86 00 00 0B AB 00 00 2B BC 00 00 01 F3 00 4C 00 00 20 67
09:17:47 DMP: 01 04 14 09 31 06 83 00 00 0B A7 00 00 2B BC 00 00 01 F3 00 4C 00 00 1F 06

**Comment by Jason2866** [comment]
Fatal Exception 0 is most of the time a power issue. WemosMini often do have bad Vregs...

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

https://github.com/arendst/Sonoff-Tasmota/issues/5673
https://github.com/arendst/Sonoff-Tasmota/issues/5554
https://github.com/arendst/Sonoff-Tasmota/issues/4995
And others


Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
