### ISSUE TITLE
Wifi Kit 8 Display not working

### ISSUE THREAD

**Issue by stompmann** [arendst/Sonoff-Tasmota#5691]
### BUG DESCRIPTION
I'm using a WifiKit 8 (Version 1) and tried to get the display (SSD1306) working. Pinout diagram can be found here: https://download.bastelgarage.ch/Datasheet/WIFI_Kit_8_Diagram_new.pdf

Display is found via I2C scan but it shuts down after 1-2 seconds and don't turn on again until I power off the board. In this state it can't be found with I2C scan. After experimenting with Adafruit and U8g2 it seems that use of OLED_RST (GPIO16) is necessary.

So I changed following 2 lines of code in xdsp_02_ssd1306.ino:
```
oled = new Adafruit_SSD1306();
oled->begin(SSD1306_SWITCHCAPVCC, Settings.display_address[0]);
```
to
```
oled = new Adafruit_SSD1306(16);
oled->begin(SSD1306_SWITCHCAPVCC, Settings.display_address[0], 1);
```
Now the display works perfectly and shows text in mode 0 or time/date in mode 1. Is there any other way to configure OLED_RST? It would be great if it could be selected in web frontend like I2C pins.

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (i.e. Sonoff Basic) : WifiKit 8, Version 1
- [x] Tasmota binary firmware version number used : 6.5.0 / self-compiled
- [x] Development IDE - Compiler / Upload tools used : Arduino
- [x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE:
10:25:49 CMD: status 0
10:25:49 RSL: stat/sonoff/STATUS = {"Status":{"Module":0,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
10:25:49 RSL: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"External System","Uptime":"0T02:23:11","StartupUTC":"2019-04-23T06:02:38","Sleep":50,"CfgHolder":4617,"BootCount":8,"SaveCount":21,"SaveAddress":"3F7000"}}
10:25:49 RSL: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.5.0(sonoff)","BuildDateTime":"2019.04.17 10:55:37","Boot":31,"Core":"2_5_0","SDK":"3.0.0-dev(c0f7b44)"}}
10:25:49 RSL: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["GUEST",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
10:25:49 RSL: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":591,"Free":3484,"Heap":21,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":2,"Features":["00000407","0FFAE394","00078120","23B617CE","00003BC0"]}}
10:25:49 RSL: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-1904","IPAddress":"10.0.15.13","Gateway":"10.0.15.254","Subnetmask":"255.255.255.0","DNSServer":"8.8.8.8","Mac":"2C:3A:E8:29:27:70","Webserver":2,"WifiConfig":4}}
10:25:49 RSL: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_292770","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
10:25:49 RSL: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Tue Apr 23 08:25:49 2019","Local":"Tue Apr 23 10:25:49 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":99,"Sunrise":"06:44","Sunset":"20:53"}}
10:25:49 RSL: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2019-04-23T10:25:49"}}
10:25:49 RSL: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2019-04-23T10:25:49","Uptime":"0T02:23:11","Vcc":2.965,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":20,"POWER":"ON","Wifi":{"AP":1,"SSId":"GUEST","BSSId":"02:A0:57:1C:0D:95","Channel":13,"RSSI":68,"LinkCount":29,"Downtime":"0T00:02:14"}}}
```
### EXPECTED BEHAVIOUR
OLED_RST configurable

**Comment by Jason2866** [comment]
Sorry not every display is compatible

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
