### ISSUE TITLE
MAX31865 and termoresistance

### ISSUE THREAD

**Issue by posh1982** [arendst/Sonoff-Tasmota#5693]
Hello,
it's possible to add to support max31865? I read the max31855 it's support.
many thanks

**Comment by Jason2866** [comment]
Tasmota is a Open Source project everyone can contribute.
There is NO paid programmer, so a driver will only be written if someone needs it and has to skill to write the driver.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
