### ISSUE TITLE
HC-SR501 On/Off constantly

### ISSUE THREAD

**Issue by chris8837** [arendst/Sonoff-Tasmota#5694]
<GUIDE>

<This BUG issue template is meant to REPORT Tasmota software BUGS ONLY>
  
<Please DO NOT OPEN AN ISSUE:>
  <If your Tasmota version is not the latest, please update before posting. Your issue might be already solved. Latest precompiled bins of Tasmota can be downloaded from http://thehackbox.org/tasmota/>
  <If your issue is a flashing issue, please address that to the Tasmota Support Chat>
  <If your issue is compilation problem, please address that to the Tasmota Support Chat>
  <If your issue has been addresed before (duplicated issue), please ask in the original issue>
  <If your issue is wifi problem or mqtt problem, please try first the steps provided in troubleshooting of the wiki>

### BUG DESCRIPTION
_A clear and concise description of what the bug is._

HC-SR501 PIR Sensor
on/off with the sensor every 10 seconds or so.  This seemed to be working fine before.  I upgraded to 6.5 and the issue started.

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Device used (i.e. Sonoff Basic) : _____
- [ ] Tasmota binary firmware version number used : ____ / (pre-compiled or self-compiled ?)
- [ ] Development IDE - Compiler / Upload tools used : ____ / ____
- [ ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE:


```
- [ ] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:
00:00:00 Project sonoff Sonoff Version 6.4.1(sonoff)-2_4_2
00:00:00 WIF: Connecting to AP1 sable88 in mode 11N as d1mini03-5530...
00:00:00 RSL: stat/d1mini03/RESULT = {"POWER":"ON"}
00:00:00 RSL: stat/d1mini03/POWER = ON
00:00:03 RSL: stat/d1mini03/RESULT = {"POWER":"OFF"}
00:00:03 RSL: stat/d1mini03/POWER = OFF
00:00:04 WIF: Connected
00:00:04 DNS: Initialized
00:00:04 HTP: Web server active on d1mini03-5530.local with IP address 192.168.1.64
17:03:32 MQT: Attempting connection...
17:03:32 MQT: Connected
17:03:32 MQT: tele/d1mini03/LWT = Online (retained)
17:03:32 MQT: cmnd/d1mini03/POWER = 
17:03:32 MQT: tele/d1mini03/INFO1 = {"Module":"Generic","Version":"6.4.1(sonoff)","FallbackTopic":"cmnd/DVES_28559A_fb/","GroupTopic":"sonoffs"}
17:03:32 MQT: tele/d1mini03/INFO2 = {"WebServerMode":"Admin","Hostname":"d1mini03-5530","IPAddress":"192.168.1.64"}
17:03:32 MQT: tele/d1mini03/INFO3 = {"RestartReason":"Software/System restart"}
17:03:32 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:03:32 MQT: stat/d1mini03/POWER = OFF (retained)
17:03:32 MQT: stat/d1mini03/RESULT = {"Command":"Unknown"}
17:03:40 MQT: tele/d1mini03/STATE = {"Time":"2019-04-23T17:03:40","Uptime":"0T00:00:14","Vcc":3.061,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"sable88","BSSId":"EC:08:6B:EE:D6:89","Channel":11,"RSSI":100}}
17:03:40 MQT: tele/d1mini03/SENSOR = {"Time":"2019-04-23T17:03:40","Switch2":"OFF"}
17:04:12 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:04:12 MQT: stat/d1mini03/POWER = ON (retained)
17:04:15 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:04:15 MQT: stat/d1mini03/POWER = OFF (retained)
17:05:28 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:05:28 MQT: stat/d1mini03/POWER = ON (retained)
17:05:31 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:05:31 MQT: stat/d1mini03/POWER = OFF (retained)
17:05:39 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:05:39 MQT: stat/d1mini03/POWER = ON (retained)
17:05:42 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:05:42 MQT: stat/d1mini03/POWER = OFF (retained)
17:05:59 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:05:59 MQT: stat/d1mini03/POWER = ON (retained)
17:06:02 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:06:02 MQT: stat/d1mini03/POWER = OFF (retained)
17:07:08 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:07:08 MQT: stat/d1mini03/POWER = ON (retained)
17:07:11 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:07:11 MQT: stat/d1mini03/POWER = OFF (retained)
17:07:22 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:07:22 MQT: stat/d1mini03/POWER = ON (retained)
17:07:24 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:07:24 MQT: stat/d1mini03/POWER = OFF (retained)
17:07:39 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:07:39 MQT: stat/d1mini03/POWER = ON (retained)
17:07:42 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:07:42 MQT: stat/d1mini03/POWER = OFF (retained)
17:08:11 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:08:11 MQT: stat/d1mini03/POWER = ON (retained)
17:08:14 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:08:14 MQT: stat/d1mini03/POWER = OFF (retained)
17:08:40 MQT: tele/d1mini03/STATE = {"Time":"2019-04-23T17:08:40","Uptime":"0T00:05:14","Vcc":3.069,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"sable88","BSSId":"EC:08:6B:EE:D6:89","Channel":11,"RSSI":100}}
17:08:40 MQT: tele/d1mini03/SENSOR = {"Time":"2019-04-23T17:08:40","Switch2":"OFF"}
17:08:42 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:08:42 MQT: stat/d1mini03/POWER = ON (retained)
17:08:45 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:08:45 MQT: stat/d1mini03/POWER = OFF (retained)
17:08:57 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:08:57 MQT: stat/d1mini03/POWER = ON (retained)
17:09:00 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:09:00 MQT: stat/d1mini03/POWER = OFF (retained)
17:09:13 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:09:13 MQT: stat/d1mini03/POWER = ON (retained)
17:09:16 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:09:16 MQT: stat/d1mini03/POWER = OFF (retained)
17:09:30 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:09:30 MQT: stat/d1mini03/POWER = ON (retained)
17:09:32 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:09:32 MQT: stat/d1mini03/POWER = OFF (retained)
17:09:39 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:09:39 MQT: stat/d1mini03/POWER = ON (retained)
17:09:41 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:09:41 MQT: stat/d1mini03/POWER = OFF (retained)
17:10:01 MQT: stat/d1mini03/RESULT = {"POWER":"ON"}
17:10:01 MQT: stat/d1mini03/POWER = ON (retained)
17:10:04 MQT: stat/d1mini03/RESULT = {"POWER":"OFF"}
17:10:04 MQT: stat/d1mini03/POWER = OFF (retained)

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
Just hookup the PIR and it does it.

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

Only when my body passes should it trigger.  Constant on/off

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._
I'm using D6 as Relay1
I'm using D5 as Switch1

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by chris8837** [comment]
THis is a Wemod D1 Mini.  Could this be the problem?  I saw on a post that it may be.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
