### ISSUE TITLE
RF Bridge and a PT2662 Remote with DipSwitches

### ISSUE THREAD

**Issue by macavelly** [arendst/Sonoff-Tasmota#5695]
Hi, thanks in advance to anyone for any help offered. I appreciate your time.

So to begin, I have the Sonoff RF bridge flashed with the latest version of tasmota "Sonoff-Tasmota 6.5.0 by Theo Arends"

I upgraded the RF Firmware according to this guide "https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF-Bridge-433" with the latest firmware found here "https://github.com/arendst/Sonoff-Tasmota/tree/master/tools/fw_efm8bb1" (RF-Bridge-EFM8BB1-20181127.hex"

The remote I'm trying to copy is this remote (it has a PT2262 chip as well as dip switches)
![20190407_122018](https://user-images.githubusercontent.com/17036758/56629693-37098900-661c-11e9-84bd-703b014ba041.jpg)
![20190419_154612](https://user-images.githubusercontent.com/17036758/56629783-aaab9600-661c-11e9-9e49-62543e850083.jpg)

When I push any of the button I don't get any response from the console.

> 00:00:00 CFG: Loaded from flash at F6, Count 38
> 00:00:00 APP: Set Baudrate to 19200
> 00:00:00 SRC: Restart
> 00:00:00 Project sonoff Sonoff Version 6.5.0(release-sonoff)-2_3_0
> 00:00:00 WIF: Checking connection...
> 00:00:00 WIF: Attempting connection...
> 00:00:00 WIF: Patch issue 2186
> 00:00:00 WIF: Connecting to AP1 MacUP24 in mode 11N as rfbridge-1397...
> 00:00:00 DMP: A0 55
> 00:00:01 WIF: Checking connection...
> 00:00:01 WIF: Attempting connection...
> 00:00:02 WIF: Checking connection...
> 00:00:02 WIF: Attempting connection...
> 00:00:03 WIF: Checking connection...
> 00:00:03 WIF: Attempting connection...
> 00:00:04 WIF: Checking connection...
> 00:00:04 WIF: Connected
> 00:00:04 HTP: Web server active on rfbridge-1397 with IP address 192.168.1.5
> 00:00:05 MQT: Attempting connection...
> 00:00:06 APP: (UTC) Wed Apr 24 03:09:03 2019, (DST) Sun Mar 31 02:00:00 2019, (STD) Sun Oct 27 03:00:00 2019
> 04:09:06 MQT: Connected
> 04:09:06 MQT: tele/rfbridge/LWT = Online (retained)
> 04:09:06 MQT: cmnd/rfbridge/POWER = 
> 04:09:06 MQT: Subscribe to cmnd/rfbridge/#
> 04:09:06 MQT: Subscribe to cmnd/sonoffs/#
> 04:09:06 MQT: Subscribe to cmnd/DVES_8F6575_fb/#
> 04:09:06 MQT: tele/rfbridge/INFO1 = {"Module":"Sonoff Bridge","Version":"6.5.0(release-sonoff)","FallbackTopic":"cmnd/DVES_8F6575_fb/","GroupTopic":"sonoffs"}
> 04:09:06 MQT: tele/rfbridge/INFO2 = {"WebServerMode":"Admin","Hostname":"rfbridge-1397","IPAddress":"192.168.1.5"}
> 04:09:06 MQT: tele/rfbridge/INFO3 = {"RestartReason":"Software/System restart"}
> 04:09:06 HTP: Main Menu
> 04:09:11 APP: Boot Count 26
> 04:09:11 CFG: Saved to flash at F5, Count 39, Bytes 3584
> 04:09:15 MQT: tele/rfbridge/STATE = {"Time":"2019-04-24T04:09:15","Uptime":"0T00:00:17","Vcc":3.126,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"Wifi":{"AP":1,"SSId":"MacUP24","BSSId":"00:03:7F:BE:EF:EC","Channel":11,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:04"}}
> 04:09:17 HTP: Console
> 04:09:26 WIF: Checking connection...
> 04:09:26 WIF: Connected
> 04:09:46 WIF: Checking connection...
> 04:09:46 WIF: Connected
> 04:10:06 WIF: Checking connection...
> 04:10:06 WIF: Connected
> 04:10:26 WIF: Checking connection...
> 

If I do rfraw 177 and then, press any of the buttons I do get a response from the bridge. The following is the down button. 

> 04:12:53 CMD: rfraw 177
> 04:12:53 SRC: WebConsole from 192.168.1.196
> 04:12:53 RSL: Received Topic /rfraw, Data Size 3, Data 177
> 04:12:53 RSL: Group 0, Index 1, Command RFRAW, Data 177
> 04:12:53 MQT: stat/rfbridge/RESULT = {"RfRaw":"ON"}
> 04:12:54 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AAA055"}}
> 04:13:00 WIF: Checking connection...
> 04:13:00 WIF: Connected
> 04:13:00 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0398 00C8 1FD6 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:02 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 037A 010E 1FCC 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:02 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 037A 00FA 2012 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:06 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0366 00FA 006E 1FEA 01010101101010101010010101011001101010100101101013 55"}}
> 04:13:07 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0366 010E 1FEA 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:09 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0370 0104 2026 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:10 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 037A 010E 1FE0 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:14 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 037A 0104 1FEA 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:15 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 037A 00FA 1FC2 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:18 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 04 03A2 00D2 0172 1FE0 01010101201010101010010101011001101020100101101013 55"}}
> 04:13:20 WIF: Checking connection...
> 04:13:20 WIF: Connected
> 04:13:21 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 037A 0104 1FFE 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:23 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0384 00F0 1FF4 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:24 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0370 00F0 1FEA 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:25 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0398 00DC 0172 1FE0 01010101101020101010010101011001101010100101102013 55"}}
> 04:13:28 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 04 0398 00C8 0140 1FF4 01010101101010202020010101011001101010100101101013 55"}}
> 04:13:30 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0366 010E 1FE0 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:36 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 037A 010E 1FC2 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:42 WIF: Checking connection...
> 04:13:42 WIF: Connected
> 04:13:46 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 033E 0104 1FD6 01010101101010101010010101011001101010100101101012 55"}}
> 04:13:50 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 04 03C0 00AA 0140 1FCC 01010101202020202020010101021001202020200102202023 55"}}
> 04:13:51 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 04 03B6 00B4 015E 1FEA 01010101201020202020010201012001202020100101202023 55"}}
> 04:14:00 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 038E 00F0 1FE0 01010101101010101010010101011001101010100101101012 55"}}
> 04:14:02 WIF: Checking connection...
> 04:14:02 WIF: Connected
> 04:14:04 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0384 00DC 1FF4 01010101101010101010010101011001101010100101101012 55"}}
> 04:14:11 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AA B1 03 0384 00F0 1FFE 01010101101010101010011001011001101010100101101012 55"}}

I then use the python scrip found here "https://github.com/henfri/bitbuckedconverter/blob/master/BitBucketConverter" to convert the B1 codes to B0.

> Filtered 0xB1 data: AAB103039800C81FD60101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 0398 00C8 1FD6 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103037A010E1FCC0101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 037A 010E 1FCC 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103037A00FA20120101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 037A 00FA 2012 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB104036600FA006E1FEA0101010110101010101001010101100110101010010110101355
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 23 04 04 0366 00FA 006E 1FEA 13010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB1030366010E1FEA0101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 0366 010E 1FEA 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB1030370010420260101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 0370 0104 2026 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103037A010E1FE00101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 037A 010E 1FE0 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103037A01041FEA0101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 037A 0104 1FEA 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103037A00FA1FC20101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 037A 00FA 1FC2 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB10403A200D201721FE00101010120101010101001010101100110102010010110101355
> Failed to decode buckets...
> Resulting 0xB0 data: AA B0 23 04 04 03A2 00D2 0172 1FE0 13010101012010101010100101010110011010201001011010 55
> 
> Filtered 0xB1 data: AAB103037A01041FFE0101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 037A 0104 1FFE 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103038400F01FF40101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 0384 00F0 1FF4 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103037000F01FEA0101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 0370 00F0 1FEA 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB104039800DC01721FE00101010110102010101001010101100110101010010110201355
> Failed to decode buckets...
> Resulting 0xB0 data: AA B0 23 04 04 0398 00DC 0172 1FE0 13010101011010201010100101010110011010101001011020 55
> 
> Filtered 0xB1 data: AAB104039800C801401FF40101010110101020202001010101100110101010010110101355
> Failed to decode buckets...
> Resulting 0xB0 data: AA B0 23 04 04 0398 00C8 0140 1FF4 13010101011010102020200101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB1030366010E1FE00101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 0366 010E 1FE0 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103037A010E1FC20101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 037A 010E 1FC2 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103033E01041FD60101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 033E 0104 1FD6 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB10403C000AA01401FCC0101010120202020202001010102100120202020010220202355
> Failed to decode buckets...
> Resulting 0xB0 data: AA B0 23 04 04 03C0 00AA 0140 1FCC 23010101012020202020200101010210012020202001022020 55
> 
> Filtered 0xB1 data: AAB10403B600B4015E1FEA0101010120102020202001020101200120202010010120202355
> Failed to decode buckets...
> Resulting 0xB0 data: AA B0 23 04 04 03B6 00B4 015E 1FEA 23010101012010202020200102010120012020201001012020 55
> 
> Filtered 0xB1 data: AAB103038E00F01FE00101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 038E 00F0 1FE0 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103038400DC1FF40101010110101010101001010101100110101010010110101255
> Decoded value: 0xF03D0C
> Resulting 0xB0 data: AA B0 21 03 04 0384 00DC 1FF4 12010101011010101010100101010110011010101001011010 55
> 
> Filtered 0xB1 data: AAB103038400F01FFE0101010110101010101001100101100110101010010110101255
> Decoded value: 0xF02D0C
> Resulting 0xB0 data: AA B0 21 03 04 0384 00F0 1FFE 12010101011010101010100110010110011010101001011010 55

I entered every B0 code into the tasmota console for example like this for the first B0 code.
"RfRaw AAB0210304039800C81FD61201010101101010101010010101011001101010100101101055"

Unfortunately no response from the gate to close from any of the codes.

> 04:28:35 RSL: Received Topic /RfRaw, Data Size 74, Data AAB0210304039800C81FD61201010101101010101010010101011001101010100101101055
> 04:28:35 RSL: Group 0, Index 1, Command RFRAW, Data AAB0210304039800C81FD61201010101101010101010010101011001101010100101101055
> 04:28:35 MQT: stat/rfbridge/RESULT = {"RfRaw":"ON"}
> 04:28:36 MQT: tele/rfbridge/RESULT = {"RfRaw":{"Data":"AAA055"}}
> 

Do the dip switches affect what the B0 code should be? What could I be missing here?

Thanks again for any insight anyone can provide.

**Comment by Jason2866** [comment]
It should not be neccessary to use Rfraw for PT2262 code. With this version of Portisch firmware
the code is supported (it does work for my PT2262 power sockets).
For questions to portisch firmware please visit Portisch Github site.
You can find always the latest version there too.
https://github.com/Portisch/RF-Bridge-EFM8BB1

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
