### ISSUE TITLE
Support for etekcity Voltson WiFi power monitoring - ESW01 

### ISSUE THREAD

**Issue by tj31moll** [arendst/Sonoff-Tasmota#5708]
**Is your feature request related to a problem? Please describe.**

Yes. Currently the outlet is not officially supported but it is able to run Tasmota as confirmed by :

https://community.smartthings.com/t/etekcity-voltson-esw01-usa/114744/8

https://github.com/arendst/Sonoff-Tasmota/issues/1679

https://www.reddit.com/r/homeassistant/comments/bemcca

However, power monitoring is still an issue. The exact pins are not clear and we do not have something open.

**Describe the solution you'd like**
If we can all try and research these as they are affordable and could be great.

**Comment by blakadder** [comment]
You can use [Templates](https://github.com/arendst/Sonoff-Tasmota/wiki/Templates) to add your device to Tasmota. As far as GPIO assignments only the ones with the device can find whats connected where.

Try your luck and try all the [power monitoring templates](https://github.com/arendst/Sonoff-Tasmota/wiki/Templates) or [search for the gpio's](https://github.com/arendst/Sonoff-Tasmota/wiki/Configuration-Procedure-for-New-Devices) one by one

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
