### ISSUE TITLE
DS18B20 Temperature affected by switch status

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#5710]
I am currently running Tasmota version 6.5.0.4
I have two DS18B20's connected to a D1 Mini configured with 7 relays.
One DS18B20 is a waterproof unit measuring Aquarium temperature, and the other measures the room temperature and is located about 1 metre from the Aquarium and D1 mini.

The issue I have is that when all relays are off the room temerature reading is correct, but as soon as I engergize at least one relay the room temperature reading immediately increases by at least 0.5C.

The Aquarium reading remains constant and unaffected.

**Comment by blakadder** [comment]
Not really a Tasmota issue. Try using an i2c sensor instead

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
