### ISSUE TITLE
Switch - how to ignore one signal (in my case OFF)

### ISSUE THREAD

**Issue by witek1308** [arendst/Sonoff-Tasmota#5721]
Hi
I have the following setup: sonoff basic with Tasmota 6.5.0 and PIR (I don't know the model) connected as Switch1 to GPIO1 and controlling the LED light. Triggering works fine but I would like to be able to ignore OFF signal from the PIR. 
It seems PIR have some intelligence which I didn't expect from it and after sending ON signal when move detected, it sends OFF signal after 5s. I don't like this behaviour as light goes off too early. 
I tried to use pulseTime but it doesn't give expected result, actually some dodgy behaviour (or maybe it should go toghether with some other setting?) but this is kind of logical if PIR sends the OFF signal.
So expected behaviour would be:
- receive ON
- ignore any further OFF from switch
- send OFF from non-switch (MQTT or Toggle via HTTP)
Is it possible at all? I browsed the net but couldn't find similar issue, on the other hand it looks like a very common case so most likely my search query was not good enough

**Comment by MadDoct** [comment]
Look at switchmode!... There's your solution! ;)

**Comment by witek1308** [comment]
I have looked before asking but can't conclude which would this be. It looked to me like none will fit. Which one do you have in mind, 4?

**Comment by MadDoct** [comment]
Exactly...

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
