### ISSUE TITLE
Move SWA1 Smartplug from optional to module list

### ISSUE THREAD

**Issue by fred9176** [arendst/Sonoff-Tasmota#5725]
Hi,

I managed to install Sonoff-Tasmota to an SWA1 Smartplug but I can't find it in the list in the configuration interface.

Looking in source code (sonoff-template.sh) I saw that SWA1 was in optional modules.
Would it be possible to add it to the list displayed in the module selection ? 

I managed to add a new template taking the same parameters as in sonoff-template.sh and it works great.

Regards,

Fred

**Comment by meingraham** [comment]
A template for this device is available in the template repository - https://blakadder.github.io/templates/swa1.html

Unless there are unique features for a particular device not available through another existing BASE device, all new devices will be supported via the Tasmota Template facility.
