### ISSUE TITLE
Sonoff Basic R2

### ISSUE THREAD

**Issue by c3reeman** [arendst/Sonoff-Tasmota#5726]
Can anyone help me regarding the new versions of sonoff basic R2 unfortunately GPIO14 is no longer available. This pin has been crucial to my setup (sonoff basics hidden in the ceiling and gpio14 pin going down to a light switch giving me hardwired options and phone alexa support etc)

Ive read about using GPIO2 and I've tested it working fine however as stated in the wiki if its pulled down to gnd on startup it causes problems... this is a night mare for me with the wife expectance factor in the event of a power cut or something.

Is there any other options available to me ? to reproduce exactly what I had with the old sonoff basics ?

**Comment by meingraham** [comment]
GPIO3?

https://www.youtube.com/watch?v=yavDqDzRdUk

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
