### ISSUE TITLE
Wemos D1 mini DHT11 v2.0 shield

### ISSUE THREAD

**Issue by emics** [arendst/Sonoff-Tasmota#5731]
Hi
The new shield DHT11 v2.0 is connected to Wemos with I2C throw GPIO 4 e 5 but if i connect with this settings the module recognizes a BH1750 Illuminance sensor. 

Is possible to change the I2C id?

**Comment by blakadder** [comment]
All I2C addresses need to be changed in code. Not sure DHT11 will work that way since I don't have experience with the old or the new version

**Comment by Jason2866** [comment]
Will not be supported for two reasons:
- DHT11 is a old bad sensor, there are MUCH better supported sensors available (for example BMP280)
- Module is [retired ](https://wiki.wemos.cc/products:retired:dht_shield_v2.0.0)

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
