### ISSUE TITLE
A User end toggle option in Web GUI

### ISSUE THREAD

**Issue by ghpk** [arendst/Sonoff-Tasmota#5738]
**Have you look for this feature in other issues and in the wiki?**
no such feature as of now.
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._
enhancement request.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
I've deployed this to 3 rooms, and love it, each board control 3 devices and one
DHT 11, but problem is,if I need to share the web gui with kids or other family members, they might accidentally get into config, so what I am suggesting is, by default Gui should only allow you to toggle the switch, and once you click Admin link, it should ask for login credentials, this will also help many people who want to deploy this to their customers, they would not be flooded with calls every time a client changes the config accidentally or deliberately as a experiment.

I know running two Gui on the nodemcu could be heavy so having basic options available to all and only when admin access is required then password prompt should appear.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
None 
**Additional context**
_Add any other context or screenshots about the feature request here._
new feature request, Initial thoughts, Not tried though.
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry. See #5719

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
