### ISSUE TITLE
I suggest in kind of plugin support

### ISSUE THREAD

**Issue by OstertagM** [arendst/Sonoff-Tasmota#5739]
I want to use many I2C and different other sensor (analogue) on one tasmota device.
So how can I easy integrate new sensors with different lib?
Sensor are: ML8511; MPL3115; HDC1080 and so on...
Tasmota has a good ui and function around that I want to use!

**Comment by blakadder** [comment]
This is documented here https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-API

Supported sensors are listed https://github.com/arendst/Sonoff-Tasmota/wiki/Sensors-Supported-by-Tasmota

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
