### ISSUE TITLE
Support TX20 Wind Sensor in Domoticz settings

### ISSUE THREAD

**Issue by javier6d2** [arendst/Sonoff-Tasmota#5740]
I would like to operate the following wind sensor on a Tasmota device connected to Raspberry PI and Domoticz:

https://www.amazon.de/Technoline-TX-20/dp/B01HXZ3KLA

The sensor has support on Tasmota but I would like to have the possibility to manage the Domoticz parameters for it.

At this moment I think is possible to write code to make it work with a script. This option would be a great addition to Tasmota. Unfortunately I can't (bad software developer) implement that by myself. I own the hardware and I would like to support an implementation with tests.

Thanks a lot!
Javalin

**Comment by ascillato2** [comment]
Hi, 

This can be done using rules feature of Tasmota. You can check in other issues for examples and also in the wiki. 

If you need further assistant, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by javier6d2** [comment]
Please, may you say me how I can get data from my sonoff device?
