### ISSUE TITLE
software serial missing RX bytes

### ISSUE THREAD

**Issue by boaschti** [arendst/Sonoff-Tasmota#5745]
### BUG DESCRIPTION
I started to implement a Fingerprint Sensor which communicates via uart 57600baud. In Tasmota I selected SW serial on pin 4,5.
The Adafruit Fingerprint lib sends a ccommand to the sensor, the sensor answers and in Tasmota I get only the last byte. See screenshot last byte 0x1D and the print in Tasmota console below.

![ersten bytes verschwinden](https://user-images.githubusercontent.com/16265092/57191339-b8b6bc00-6f24-11e9-9c68-75360f1e9872.JPG)

Thats the current code:
https://github.com/boaschti/Sonoff-Tasmota/tree/Add_AS608_Fingerprint/sonoff

The uart buffer is read in Adafruit_Fingerprint.cpp Line 309-377 per byte = mySerial->read();
I print the RX data in XSNS_43_AS608.ino with:
`    if (finger.verifyPassword()){
      snprintf_P(log_data, sizeof(log_data), PSTR(D_LOG_LOG " AS608x found"));
    }else{
      snprintf_P(log_data, sizeof(log_data), PSTR(D_LOG_LOG " AS608x not found %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X %02X"), finger.mydata[0], finger.mydata[1], finger.mydata[2], finger.mydata[3], finger.mydata[4], finger.mydata[5], finger.mydata[6], finger.mydata[7], finger.mydata[8], finger.mydata[9], finger.mydata[10], finger.mydata[11]);
    }
    AddLog(LOG_LEVEL_INFO);`

Has anybody a idea what happens here? Is it a timing problem (sensor response too fast)?

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ x] Device used (i.e. Sonoff Basic) : wemos d1 mini
- [x ] Tasmota binary firmware version number used : 6.5.0 / (self-compiled)
- [x ] Development IDE - Compiler / Upload tools used : atom / ____
- [ x] Provide the output of command ``status 0`` :

> 
platformio run --target upload
Processing sonoff (framework: arduino; platform: espressif8266@1.5.0; board: esp01_1m)
 

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz 80KB RAM (1MB Flash)
Converting sonoff.ino
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 51 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <I2Cdevlib-ADS1115>
|   |-- <I2Cdevlib-Core>
|   |   |-- <Wire> 1.0
|-- <ESP8266httpUpdate> 1.1
|   |-- <ESP8266HTTPClient> 1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <BME680_driver-bme680_v3.5.9>
|-- <Adafruit GFX Library> 1.2.9
|   |-- <SPI> 1.0
|-- <Adafruit LED Backpack Library> 1.1.6
|   |-- <Adafruit GFX Library> 1.2.9
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <rc-switch> 2.6.2
|-- <ESP8266HTTPClient> 1.1
|   |-- <ESP8266WiFi> 1.0
|-- <Adafruit CCS811 Library> 1.0.0
|   |-- <Wire> 1.0

|-- <FrogmoreScd30>
|   |-- <Wire> 1.0
|-- <Adafruit Fingerprint Sensor Library> 1.1.2
|   |-- <TasmotaSerial> 2.3.0
|-- <NeoPixelBus> 2.2.9
|   |-- <SPI> 1.0
|-- <C2Programmer> 1.0.0
|-- <Wire> 1.0
|-- <LiquidCrystal_I2C>
|   |-- <Wire> 1.0
|-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |-- <SPI> 1.0
|-- <TasmotaModbus> 1.1.0
|   |-- <TasmotaSerial> 2.3.0
|-- <I2Cdevlib-MPU6050>
|   |-- <I2Cdevlib-Core>
|   |   |-- <Wire> 1.0
|-- <SPI> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> 1.0
|-- <OneWire> 2.3.2
|-- <Joba_Tsl2561> 2.0.7
|   |-- <Wire> 1.0
|-- <ArduinoJson> 5.13.4

|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP KNX IP Library> 0.5.1
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <EEPROM> 1.0
|-- <TasmotaSerial> 2.3.0
|-- <Adafruit ILI9341> 1.2.0
|   |-- <SPI> 1.0
|   |-- <Adafruit GFX Library> 1.2.9
|   |   |-- <SPI> 1.0
|-- <Adafruit SGP30 Sensor> 1.0.2
|   |-- <Wire> 1.0
|-- <DNSServer> 1.1.0
|   |-- <ESP8266WiFi> 1.0
|-- <Mutichannel_Gas_Sensor> 0.0.1
|   |-- <Wire> 1.0
|-- <Adafruit SSD1306> 1.1.2
|   |-- <SPI> 1.0
|   |-- <Adafruit GFX Library> 1.2.9
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <LinkedList>
|-- <Ticker> 1.0
|-- <IRremoteESP8266> 2.5.2
|-- <PubSubClient> 2.6
|-- <I2Cdevlib-Core>

|   |-- <Wire> 1.0
|-- <NewPing> 1.9.1
Compiling .pioenvs\sonoff\src\sonoff.ino.cpp.o
Compiling .pioenvs\sonoff\lib5fe\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp.o
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp: In member function 'uint8_t Adafruit_Fingerprint::setPassword(uint32_t)':
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:269:54: warning: narrowing conversion of '(password >> 24)' from 'uint32_t {aka unsigned int}' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
SEND_CMD_PACKET(FINGERPRINT_SETPASSWORD, (password >> 24), (password >> 16), (password >> 8), password);
^
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:31:21: note: in definition of macro 'GET_CMD_PACKET'
uint8_t data[] = {__VA_ARGS__}; \
^
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:269:3: note: in expansion of macro 'SEND_CMD_PACKET'
SEND_CMD_PACKET(FINGERPRINT_SETPASSWORD, (password >> 24), (password >> 16), (password >> 8), password);
^
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:269:72: warning: narrowing conversion of '(password >> 16)' from 'uint32_t {aka unsigned int}' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
SEND_CMD_PACKET(FINGERPRINT_SETPASSWORD, (password >> 24), (password >> 16), (password >> 8), password);
^
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:31:21: note: in definition of macro 'GET_CMD_PACKET'
uint8_t data[] = {__VA_ARGS__}; \
^
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:269:3: note: in expansion of macro 'SEND_CMD_PACKET'
SEND_CMD_PACKET(FINGERPRINT_SETPASSWORD, (password >> 24), (password >> 16), (password >> 8), password);
^
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:269:90: warning: narrowing conversion of '(password >> 8)' from 'uint32_t {aka unsigned int}' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
SEND_CMD_PACKET(FINGERPRINT_SETPASSWORD, (password >> 24), (password >> 16), (password >> 8), password);
^
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:31:21: note: in definition of macro 'GET_CMD_PACKET'
uint8_t data[] = {__VA_ARGS__}; \
^
lib\Adafruit_Fingerprint_Sensor_Library\Adafruit_Fingerprint.cpp:269:3: note: in expansion of macro 'SEND_CMD_PACKET'

SEND_CMD_PACKET(FINGERPRINT_SETPASSWORD, (password >> 24), (password >> 16), (password >> 8), password);
^
Archiving .pioenvs\sonoff\lib5fe\libAdafruit_Fingerprint_Sensor_Library.a
Linking .pioenvs\sonoff\firmware.elf
Checking size .pioenvs\sonoff\firmware.elf
Building .pioenvs\sonoff\firmware.bin
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [=======   ]  67.7% (used 55420 bytes from 81920 bytes)
PROGRAM: [=====     ]  49.5% (used 518807 bytes from 1048576 bytes)
Configuring upload protocol...
Looking for upload port...
Use manually specified: COM2
Uploading .pioenvs\sonoff\firmware.bin
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x01 0x00, expected 0x01 0x08
Uploading 522960 bytes from .pioenvs\sonoff\firmware.bin to flash at 0x00000000
................................................................................ [ 15% ]
................................................................................ [ 31% ]
................................................................................ [ 46% ]
................................................................................ [ 62% ]
................................................................................ [ 78% ]
................................................................................ [ 93% ]
...............................                                                  [ 100% ]
 [SUCCESS] Took 48.46 seconds
 
 [SUMMARY]
Environment sonoff              [SUCCESS]
Environment sonoff-minimal      [SKIP]
Linter
Severity 	Provider 	Description	Line 
PIO Buildsonoff\xsns_43_as608.ino2111038:1(6, 523)
CRLFUTF-8C++
Add_AS608_FingerprintFetchGitHubGit (3)10 updates

**Comment by Jason2866** [comment]
Please provide Status 0 output

**Comment by boaschti** [comment]
Correct output?

**Comment by Jason2866** [comment]
No, you have to open webfrontend and from there click Button "Console" now type in Console Command `Status 0` Post the output generated in conesole from this here. Please us function "Insert code" this can be reachec via the symbol "<>"

**Comment by Jason2866** [comment]
Just take a look at your branch. You use are very old and outdated version. 
Please update to latest dev branch there are MANY issues fixed since that time.
Anyway if you use Core 2.3.0 you will have problems with software serial. See https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#arduino-core-differences
Switch to core 2.4.2 or latest core 2.5.x feature/stage

**Comment by Jason2866** [comment]
You can take a look in driver https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/xsns_40_pn532.ino how software serial can be implemented in a custom driver. This driver works very reliable

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by boaschti** [comment]
Newest dev branch works great! Much Thanks.
