### ISSUE TITLE
Opening BlitzWolf SHP2 with XIAOMI Mijia Wiha TRI2.3 not working

### ISSUE THREAD

**Issue by JBS5** [arendst/Sonoff-Tasmota#5752]
Not really a software related question, but quite importent to start the project.

I am trying to open the BlitzWolf SHP2 with the TRI2.3 from the XIAOMI Mijia Wiha set, but the TRI2.3 will not fit enough to open the screws. Shoud work...? Any suggestions? I don't have a Torx T6 unfortunately.

**Comment by blakadder** [comment]
Go to [these](https://github.com/arendst/Sonoff-Tasmota/wiki#community) for unrelated support

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
