### ISSUE TITLE
Support for Blitzwolf BW-SHP5 3680W EU

### ISSUE THREAD

**Issue by Cybolord** [arendst/Sonoff-Tasmota#5756]
Is the new Blitzwolf BW-SHP5 supported (ESP8285)?
please see [LINK](https://www.blitzwolf.com/BlitzWolf-BW-SHP5-3680W-EU-Wifi-Socket-Smart-Charger-with-Dual-USB-Ports-Compatible-with-French-Standard,-Works-with-Alexa,-Scheduled-Control,-Remote-Control,-Monitor-Power-Use-p-326.html)

Cant find any Info about this

...successfully flashed v6.5.0 but Button not working:
so tried to build a new template for device (based on generic device "18") but failed so far...

**Comment by blakadder** [comment]
It is not on the supported modules list and henceforth not supported. If you cannot map the gpio's yourself you'll have to wait for someone else with the device to do it. Keep an eye on the [template repo](http://blakadder.github.io/templates)

**Comment by Cybolord** [comment]
so I would like to offer my help and not only waiting for "someone else" indeed but need a few hints ;)

![BW-BHP5](https://user-images.githubusercontent.com/23726446/57221049-ea4f8600-6ffd-11e9-8e0f-6238499c7246.jpg)

**Comment by blakadder** [comment]
It is appreciated but you have failed to read the message when opening an issue. This is not the place to configure your new device. Read the wiki on Templates and new device configuration or seek help in [discussion channels ](https://github.com/arendst/Sonoff-Tasmota/wiki#community)

**Comment by meingraham** [comment]
@Cybolord - Hints available [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Templates) and [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Configuration-Procedure-for-New-Devices).

**Comment by Cybolord** [comment]
> 
> 
> @Cybolord - Hints available [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Templates) and [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Configuration-Procedure-for-New-Devices).

...great, thanks a lot meingraham!

**Comment by zewelor** [comment]
@Cybolord How did you flashed tasmota ? Using tuya-convert or flasher via pins ?

**Comment by GoNzCiD** [comment]
> 
> 
> @Cybolord How did you flashed tasmota ? Using tuya-convert or flasher via pins ?

I can't by tuya-convert. I have flashed it via pins

**Comment by GoNzCiD** [comment]
@Cybolord, can you made it work? I have just flashed one SHP5 with tasmota 6.5.0

**Comment by zewelor** [comment]
@GoNzCiD DO you have photo which pins and how did you connect flasher ?

**Comment by GoNzCiD** [comment]
![1](https://user-images.githubusercontent.com/12912439/57575216-c39eae80-7446-11e9-9d25-74900dd8c833.jpg)
IOD => IO0 short to gnd on boot to enter in flash mode. @zewelor 
And flashed with NodeMCU-PyFlasher-4.0

**Comment by zewelor** [comment]
@GoNzCiD Thanks for info. Just to be sure, 5V is correct, not 3.3V ?

**Comment by GoNzCiD** [comment]
> 
> 
> @GoNzCiD Thanks for info. Just to be sure, 5V is correct, not 3.3V ?

Yes, look at the pcb on the other side:
![2](https://user-images.githubusercontent.com/12912439/57605113-2f2b6d80-7566-11e9-861e-44967a3908f3.jpg)

**Comment by zewelor** [comment]
Right thanks !

**Comment by waiet** [comment]
I adding more photos
![received_299680470962523](https://user-images.githubusercontent.com/6156355/57676926-e89d4800-7625-11e9-8d84-e97d543062a0.jpeg)
![received_463231024431186](https://user-images.githubusercontent.com/6156355/57676930-ec30cf00-7625-11e9-87b0-8926f92ced93.jpeg)

**Comment by thomasklingbeil** [comment]
![SHP5](https://user-images.githubusercontent.com/190958/57842223-600cdc00-77cc-11e9-8329-abd3c44f1e8d.png)

Energy monitoring is done with an HLW8032 (https://datasheet.lcsc.com/szlcsc/Hiliwei-Tech-HLW8032_C128023.pdf)
I guess one of the outputs (probably PF) is sent through an photocoupler (EL357N) to one of the IO pins of the ESP8285.

**Comment by thomasklingbeil** [comment]
Apart from the power monitoring, the device already seems to work: https://github.com/blakadder/templates/blob/master/_templates/blitzwolf_SHP5

To update my guess from earlier today: It seems as if PF is the only pin of the HLW8032 that is NOT connected. Thus, it seems more likely, that the serial connection is used. It should be UART with 4800bps, Start/Stop Bit and even parity. Every 50ms there should be 24 byte of data.

**Comment by arendst** [comment]
Just ordered one to write a new nrg driver for serial HLW8032 support.

**Comment by arendst** [comment]
While comparing the datasheets from HLW8032 (chinees) with CSE7766 (english) the resemblance is striking.

For those owning this device you might want to try the CSE7766 RX/TX config option in Tasmota to check if any energy measuring is shown.

**Comment by kamkilt** [comment]
> Apart from the power monitoring, the device already seems to work: https://github.com/blakadder/templates/blob/master/_templates/blitzwolf_SHP5
> 

This module have also control of USB port on GPIO5.
My config is following: 
template: '{"NAME":"BlitzWolf SHP5","GPIO":[56,255,57,255,255,22,255,255,255,255,21,255,17],"FLAG":0,"BASE":18}'  - button contorling 230 V relay
 or 
template: '{"NAME":"BlitzWolf SHP5","GPIO":[56,255,57,255,255,22,255,255,255,255,21,255,18],"FLAG":0,"BASE":18}' - button contorling 5 V USB

Energy measuring using CSE7766 RX/TX on GPIO1 and GPIO3 is not working.

**Comment by arendst** [comment]
Thx for testing CSE7766. When mine arrives I'll try to implement HLW8032

**Comment by thomasklingbeil** [comment]
Does the regular Serial output of Sonoff Tasmota need to be disabled first?

**Comment by arendst** [comment]
No, that's been handled by the CSE7766 driver. Did you try to swap RX/TX too?

**Comment by thomasklingbeil** [comment]
I’ll give it a try soon. Unfortunately it seems that my first SHP5 has stopped working...

Side note: The ESP and the power monitor

**Comment by kamkilt** [comment]
> No, that's been handled by the CSE7766 driver. Did you try to swap RX/TX too?
> 
> This works for CSE7766:
> 
> ![image](https://user-images.githubusercontent.com/11044339/58010911-8f378c00-7af1-11e9-8f1f-401a21725908.png)

It started working, i have changed SerialLog to 0, Baudrate to 4800, but also trying to set CSE7766 on different GPIOs, so i'dont what finaly heleped, but it works on GPIOs that You send.

On start voltage was about 129 V, i calibrated it to my volteage 240 V.

I will check if it showing right values in the evening.

![Capture](https://user-images.githubusercontent.com/44520713/58011690-1afde800-7af3-11e9-927e-178a67a1c5ac.PNG)

**Comment by kamkilt** [comment]
So my final template are:
{"NAME":"SHP5","GPIO":[56,145,57,146,255,22,0,0,255,255,21,255,18],"FLAG":0,"BASE":18}

**Comment by arendst** [comment]
Only the shown GPIO's are supported for CSE7766 serial connection so all others will fail.

Glad it works!

**Comment by miquelbotanch** [comment]
Anyone has been able to flash it ?

I did it many times without issues with BW-SHP6 but with this the RX light of the programmer never turns on. (tried on 2 different SHP5)

Maybe I should use an external power supply? My programmer has 5<->3,3 power switch but doesnt work.

**Comment by arendst** [comment]
Just did a serial upload as tuya-convert doesn't work anymore due to unsupported https.

![IMG_20190603_171048](https://user-images.githubusercontent.com/11044339/58817450-0b6ebb00-862c-11e9-9952-3b80c73093a7.jpg)

Flashing went fine.

Make sure that once you activate the SHP5 template serial comms changes to 4800 bps even parity. That worked for me.

**Comment by Jason2866** [comment]
Fancy soldering & wiring 😊

**Comment by kamkilt** [comment]
I calibrated BW-SHP5 using 60 W bulb, with load energy measure is correct, but without anything connected it always shows about 3 W, it's not an USB output, because is not changing when something is connected to USB output, is there some way to calibrate energy measure to show 0 W when nothing is connected?

I have two modules and both shows same values.

![Screenshot 2019-06-03 at 21 34 30](https://user-images.githubusercontent.com/44520713/58829188-8beee500-8647-11e9-959d-aa2594203fcd.png)

**Comment by arendst** [comment]
Probably not as I suspect the sensor is connected before the SHP5 logic so it will always measure the load of the SHP5.

**Comment by arendst** [comment]
The final SHP5 template should be this:
```
{"NAME":"SHP5","GPIO":[57,145,56,146,0,22,0,0,0,0,21,0,18],"FLAG":0,"BASE":18}
```
where the blue led represents the link info and the red led follows any power setting. As other GPIO's cannot be used they need to be set to 0.

**Comment by arendst** [comment]
Updated wiki and closing

**Comment by arendst** [comment]
@kamkilt if you do not want to measure loads below 5W you might want to set define CSE_MAX_INVALID_POWER in file xnrg_02_cse7766.ino from 128 to 1.

This will disable showing invalid power measurments usually below 5W.

**Comment by arendst** [comment]
Use SetOption39 to control handling of invalid power measurments.

The HLW8032 reports invalid power often if values below 5W are found. During this situation it sometimes reports avalid load. By setting SetOption39 to 128 (default) it must read at least 128 invalid power readinfs before deciding there is no load. 

So to discard all loads below 6W simply set SetOption39 to 1 (0 will reset to default on next restart) so it will report no load below 6W.

**Comment by chkbln** [comment]
Hello
How can I open the case? There is a screw on the bottom. I could solve that.
But how is it going now?
Can someone give me a hint.

Thank you

**Comment by waiet** [comment]
> Hello
> How can I open the case? There is a screw on the bottom. I could solve that.
> But how is it going now?
> Can someone give me a hint.
> 
> Thank you

There are 1 screw and on the corners are clips. After screwing out the screw I opened case with old club card
![IMG_20190512_161556__01](https://user-images.githubusercontent.com/6156355/59129370-ed2af700-896c-11e9-8aa6-410acd7e43e2.jpg)
![sph5](https://user-images.githubusercontent.com/6156355/59129371-ed2af700-896c-11e9-8f6d-0e7c53335c93.jpg)

**Comment by waiet** [comment]
> I calibrated BW-SHP5 using 60 W bulb, with load energy measure is correct, but without anything connected it always shows about 3 W, it's not an USB output, because is not changing when something is connected to USB output, is there some way to calibrate energy measure to show 0 W when nothing is connected?
> 
> I have two modules and both shows same values.
> 
> ![Screenshot 2019-06-03 at 21 34 30](https://user-images.githubusercontent.com/44520713/58829188-8beee500-8647-11e9-959d-aa2594203fcd.png)

I measured the energy consumption without a load with original fw. Power consumption  still was circa 4w on blitzwolf app and too on power meter after shp5. See image
![image](https://user-images.githubusercontent.com/6156355/59131207-01252780-8972-11e9-87df-cfc717d17ec0.png)

**Comment by meingraham** [comment]
Does it draw power with the relays off?

**Comment by waiet** [comment]
On this img relays were  power on, but with power off is result the same

**Comment by meingraham** [comment]
Turn on weblog 4 and see if you are getting any checksum errors.

What is Relay2 controlling?

**Comment by kamkilt** [comment]
> What is Relay2 controlling?

USB Output.

**Comment by arendst** [comment]
If you do not want to see measurements below 5W use the latest dev release and execute command ``setoption39 1`` as documents earlier in this thread.

**Comment by kamkilt** [comment]
> If you do not want to see measurements below 5W use the latest dev release and execute command `setoption39 1` as documents earlier in this thread.

I did and it's working well. thanks.

**Comment by waiet** [comment]
But shp 5 compared to the shp 6 has relatively high consumption without any load.
That's probably not a software issue. Tasmota is working perfectly.

**Comment by kamkilt** [comment]
> But shp 5 compared to the shp 6 has relatively high consumption without any load.
> That's probably not a software issue. Tasmota is working perfectly.

I measured mine using Sonoff pow R2 and SHP5 gets around ~ 1 - 1.2 W, while SHP6 takes around 0.8 - 1 W, relays on both turned on.

Connecting SHP5 to SHP6, and reading measures from SHP6 gives similar results, so I don't see that high difference in consumption.

**Comment by maschere** [comment]
It seems the Gosund SP112 (https://www.amazon.de/dp/B07PMW88L7) is the same as the SHP5, at least the template for the SHP5 works flawlessly for the Gosund as well. SO thanks a lot for that!

However I'm also getting strange power readings of the power consumption of the switch itsels. Without any load connected and both relays set to OFF, my power meter says 9 Watts (the same with both relays on). When I measure one SP112 with the other SP112 (after calibration) it says about 1 Watts. Can anyone with a previse power meter measure the SHP5 (or SP112) without any load?

**Comment by hemy81** [comment]
Hey guys, thanks for this nice discussion so far. I have been trying to flash the SP112 without any success so far. I have the following items:
- Gosund SP112
- esptool (executable) for Mac
- USB adapter CP2102 (/dev/tty.SLAB_USBtoUART)

I think it cannot enter the flash mode. I shortened the IO0 and Gnd, upon plugin in the UART, but I only hear the relay "clicking" but the blue LED is still blinking. The only difference I hear is the relay that clicks once I remove the IO0 and Gnd cable. 

Any help is very welcome.

**Comment by chkbln** [comment]
Hi
I connect GPO0 and GND together and then I plug the UART into the USB port.
The LED lights up red. Then I flash.
greeting

**Comment by hemy81** [comment]
Hmm, that‘s what I did. I connected IO0 with GND and put the UART into USB port. The LED is not blinking red, but blue. I waited even for 10s with both GND and IO0 connected.

**Comment by chkbln** [comment]
- GOSUND SP112 is broken?
- GPO0 is not at GND potential? Test the connection for correct contact.
I flashed 4 sockets on Tasmota without any problems

**Comment by wvsbsp** [comment]
I just received my GOSUND SP112's and managed to open them without breaking any tabs. ;-)

Just one Idea: Has anybody thought about routing the unused GPIOs 4, 12 and 13 to the unused USB-datalines? This would be perfect for adding sensors via 1-wire, GPIO or I2C. 5V power supply included for free...
One Pin of the ESP-module is not clear to me. The pin between Vdd and GPIO14 - is it TOUT (ADC0) or IO15?

And some additions to the circuit itself: U3 (device-marking 2634 A833 - which is the date-code?) is a dual USB protection IC (such as TI TPS2513A or ST USBLC6-4) which protects plugged USB devices - good, but the pins have no other connection.
In the picture in article https://github.com/arendst/Sonoff-Tasmota/issues/5756#issuecomment-492991170
there are two ICs marked K0443I ans K0268I. This might be the production code. The ICs are one On-Bright OB2502TCPB and one OB2005VCPK. Both should be PWM regulators for the separated power-supplies. Unfortunately, i couldn't find the datasheets.

**Comment by ascillato** [comment]
@wvsbsp

Please, NEVER CONNECT SENSORS TO A POWER MEASUREMENT DEVICE. 

YOU CAN BE ELECTROCUTED. 

the gnd pin is directly connected to Mains AC. 

For sensors please use a nodemcu instead. 

Devices with power measurement MUST BE USED AS IT COMES FROM FACTORY. 

DO NOT PUT YOU, YOUR FAMILY AND YOUR HOUSE IN DANGER 

Please, read the wiki! This warning is everywhere.

**Comment by wvsbsp** [comment]
For shure it is not the case with th SP112. I plan to stick the sensors into the two external USB charging ports which are certainly isolated from mains.... 
Look at the device, the power measurement uses its own power-supply and the communication to the esp runs over an optocoupler.

**Comment by Jason2866** [comment]
@ascillato2  please lock this thread
@wvsbsp  We do NOT want discussions with dangerous mods here.
