### ISSUE TITLE
Request for Barometer device for Domoticz

### ISSUE THREAD

**Issue by SargonofAssyria** [arendst/Sonoff-Tasmota#5757]
I have an BME280 connected on an NodeMCU 8266.
Domoticz MQTT has a Temp, Temp/Hum and a Temp/Hum/Baro devices.
The last one is a problem. Its creates 2 devices in Domoticz with the same name/caption.
1 device is placed in the Temperature Tab and the other in the Weather Tab with the same name.
Thats confusing.
Request is for a seperate Barometer device in the settings with only the air pressure from the BME280 with the prediction/forecast.

**Comment by ascillato2** [comment]
Not supported. Sorry.

Adding the label requested feature for future reference. Thanks
