### ISSUE TITLE
Help with H801 and RGBW via MQTT

### ISSUE THREAD

**Issue by Blue407** [arendst/Sonoff-Tasmota#576]
New to all this, so please be gentle :)

I have successfuly configured my H801 and reflashed it with Sonoff-Tasmota.

I have tested commands like:-
mosquitto_pub -r -t cmnd/H801-1/PWM4 -m "1000"

Which work fine.

Is there a way to set multiple colour values at the same time in one line?
Or do I have to issue 4 separate colour commands every time?

I plan on using this with Openhab, so any advice specific to that would be appreciated :) :)
I hope to have a colour picker as well as some pre-defined colours like Green, Purple, White etc.

**Comment by arendst** [comment]
Currently there is only single pwm control.

**Comment by Blue407** [comment]
Is there any chance of multiple PWM control at a later date?

Any advice on how best to use it to pick colours based on its current limitation?

**Comment by cobra85ec** [comment]
are u using node-red..?

**Comment by Blue407** [comment]
No, OpenHAB.

**Comment by kruebsam** [comment]
Would also be interested in the above with exactly same config
