### ISSUE TITLE
Serialsend3 doesnt replace ESC codes correct with values

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#5760]
<GUIDE>

<This BUG issue template is meant to REPORT Tasmota software BUGS ONLY>
  
<Please DO NOT OPEN AN ISSUE:>
  <If your Tasmota version is not the latest, please update before posting. Your issue might be already solved. Latest precompiled bins of Tasmota can be downloaded from http://thehackbox.org/tasmota/>
  <If your issue is a flashing issue, please address that to the Tasmota Support Chat>
  <If your issue is compilation problem, please address that to the Tasmota Support Chat>
  <If your issue has been addresed before (duplicated issue), please ask in the original issue>
  <If your issue is wifi problem or mqtt problem, please try first the steps provided in troubleshooting of the wiki>

### BUG DESCRIPTION
Serialsend3 should replace ESC codes with values

### REQUESTED INFORMATION

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (i.e. Sonoff Basic) : WemosMini
- [x] Tasmota binary firmware version number used : latest dev 6.5.0.9 self compiled
- [x] Development IDE - Compiler / Upload tools used : VSC with esptool
- [x] Provide the output of command ``status 0`` :
```
18:32:45 CMD: Status 0
18:32:45 MQT: stat/sonoff/STATUS = {"Status":{"Module":18,"FriendlyName":["149"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
18:32:45 MQT: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.2.20/data/firmwares/sonoff.bin","RestartReason":"External System","Uptime":"0T00:06:44","StartupUTC":"2019-05-07T16:26:01","Sleep":50,"CfgHolder":4617,"BootCount":26,"SaveCount":171,"SaveAddress":"F8000"}}
18:32:45 MQT: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.5.0.9(sonoff)","BuildDateTime":"2019-05-07T16:58:22","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(2a5f9d5)"}}
18:32:45 MQT: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Jason_Home_WLAN",""],"TelePeriod":300,"Resolution":"55C180C0","SetOption":["00408009","280500000100000000000000000000000000","00000000"]}}
18:32:45 MQT: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":497,"Free":504,"Heap":26,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1625C2","FlashMode":3,"Features":["00000809","0F8AA384","040003A1","00041496","000000C0"]}}
18:32:45 MQT: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-1459","IPAddress":"192.168.2.149","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"B4:E6:2D:15:85:B3","Webserver":2,"WifiConfig":5}}
18:32:45 MQT: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.2.114","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_1585B3","MqttUser":"openhabian","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
18:32:45 MQT: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Tue May 07 16:32:45 2019","Local":"Tue May 07 18:32:45 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":99,"Sunrise":"05:43","Sunset":"20:35"}}
18:32:45 MQT: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2019-05-07T18:32:45"}}
18:32:45 MQT: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2019-05-07T18:32:45","Uptime":"0T00:06:44","Vcc":3.041,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Jason_Home_WLAN","BSSId":"00:A0:57:2A:BD:19","Channel":9,"RSSI":90,"LinkCount":1,"Downtime":"0T00:00:05"}}}


```

### TO REPRODUCE
```
18:34:07 CMD: Serialsend3 TheQuickBrownFoxJumpsOverTheLazyDog\xFF\xFF\xFF\n
18:34:07 MQT: stat/sonoff/RESULT = {"SerialSend":"Done"}
```
received
![image](https://user-images.githubusercontent.com/24528715/57316747-ce7bdb00-70f6-11e9-894d-de0f97c970bb.png)

### EXPECTED BEHAVIOUR
Replacing the Esc codes (\xFF) with values

**Comment by andreapede** [comment]
I had a different result Sending
Serialsend3 TheQuickBrownFox\xFF\xFF\xFF\n
TheQuickBrownFoxÿÿÿ<LF>\xff\xff\n

What I think is that tera term doesn't visualize the escaped code and it visualize only the echoed string (that in any case shouldn't be transmitted).

What it seems to me is that both the escaped code + escape code are transmitted.

Mayeb a possible issue in the Unescape function (support.ino)?
