### ISSUE TITLE
Wrong Values For SHT11 Sensor with Wemos D1 Mini Release 3.0.0

### ISSUE THREAD

**Issue by guidoffm** [arendst/Sonoff-Tasmota#5768]
One SHT11 sensor ist connected to the wemos D1 mini board.

Tasmota (6.5.0) ist configured as type generic (18).

Pins are configured this way:
I2C SCL(5) for pin TX
I2C SDA (6) for pin RX 

With an older type of the Wemos D1 mini board everything works correctly. Sensor type recognized is ok and temperature and humidity values are correct.

With Wemos D1 mini R3.0.0 board sensor type is recognized ok. Temperature and humidity values are not correct. Temperature reads 288 degrees Celsius.

I checked this with two boards of the same type.

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
