### ISSUE TITLE
Configuration for TYWE3S module on Wlansmart RM Mini IR Hub

### ISSUE THREAD

**Issue by jjmuriel** [arendst/Sonoff-Tasmota#5771]
Hi.

Please, someone can tell me where should I solder the pins  for this device to connect via serial-usb?  This IR Hub has the same chip as the IR YTF. Or is it possible to load the firmware via OTA? Thanks.

https://www.amazon.com/gp/product/B07LG7WK2T/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

![IMG_20190508_174548_1](https://user-images.githubusercontent.com/17131600/57452178-d176e880-7228-11e9-86f1-4c3e595b3f39.jpg)
![IMG_20190508_175048](https://user-images.githubusercontent.com/17131600/57452191-d63b9c80-7228-11e9-8e16-769d301adde3.jpg)
![IMG_20190508_175127](https://user-images.githubusercontent.com/17131600/57452201-da67ba00-7228-11e9-8411-b3c696c47e38.jpg)

**Comment by meingraham** [comment]
Have you tried [Tuya-Convert](https://github.com/ct-Open-Source/tuya-convert)?

Please, address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4) and close this issue on GitHub. The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota software feature requests and bug reporting. Troubleshooting is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by jjmuriel** [comment]
Ok @meingraham , thank you for your quick response.

**Comment by jjmuriel** [comment]
Only for reference: 
![tywe3s](https://user-images.githubusercontent.com/17131600/57455124-0d617c00-7230-11e9-9355-cfef1daffca8.jpg)
