### ISSUE TITLE
PZEM-004T V3 wrong readings

### ISSUE THREAD

**Issue by SeByDocKy** [arendst/Sonoff-Tasmota#5775]
Hi,

I just received a PZEM-004T V3 now with Modbus. 
I am using last tasmota all-sensor build , 

TX GPIO1 Serial Out => (62)
RX GPIO3 Serial In => (68)

For me power, current readigs are wrong for example with a 17,5W lamp, 240V, 0,125A, I am reading

Analog0 | 1
-- | --
241 V
0.037 A
1 W
9 VA
9 VAr
0.06
50 Hz
0.000 kWh
0.000 kWh
0.000 kWh

**Comment by curzon01** [comment]
[Template](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#opening-new-issues) is missing and as [noted](https://github.com/arendst/Sonoff-Tasmota/issues/5765#issuecomment-491081812) by @meingraham (which is true) the values are from the sensor and calibrate is not supported. .

Please address this to [Support's Community](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md#supports-community).

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
