### ISSUE TITLE
Hass Discover do not detect button state

### ISSUE THREAD

**Issue by Fires04** [arendst/Sonoff-Tasmota#5778]
Hi, I got two sonooff touch .. All same firmware 6.5 and same settings(different name of course). But Hass detect button state on just one . Any advice ?  BTN is just on the left. 
![Screenshot - 10 05 2019 , 13_43_36](https://user-images.githubusercontent.com/699214/57525570-619d5680-732b-11e9-9b5c-6c335bdd852b.png)

**Comment by Jason2866** [comment]
Probably old settings stored. Do command `reset 5` This resets all settings to defaults and ersases flash.
Only wifi credentials will survive. After reconfiguring device try again. 

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
