### ISSUE TITLE
Visual Studio Code Settings for Shelly

### ISSUE THREAD

**Issue by lobocobra** [arendst/Sonoff-Tasmota#5781]
Hi all

I am moving to Visual Studio code from Arduino and followed the wiki page to complie the arendst firmware. 

My issue:
Shelly has 2mb (which I can easily switch to in Arduino), but for Visual-Studio-Code I need to change the config in platform.ini.
=> I assume that I have to switch this value: 
`[common]
framework                 = arduino
board                     = esp01_1m
board_build.flash_mode    = dout`

But to what I do neet to switch esp01_1m? 

Many thanks for a short hint. I found nothing in google and wiki.

**Comment by Jason2866** [comment]
Leave everything unchanged in platformio.ini  Shelly works fine with the standard settings

**Comment by SargonofAssyria** [comment]
I have a OBI IP44 with a esp-wroom-2M also 2mb.
It would be nice to have a compile setting for 1.5 mb Sketch and 512kb spiff, so OTA would be easy.
Is that possible?

**Comment by ascillato2** [comment]
For backwards compatibility with Tasmota users, the precompiled bins will continue be with the standard memory map.
If you have a different memory map in your devices, you need to full erase with esptool.py as explained in the wiki and flash it again. 

If you need further assistant, please, address this to the Tasmota support chat. Thanks

**Comment by SargonofAssyria** [comment]
Found my solution: https://groups.google.com/forum/#!topic/sonoffusers/wCquqDdfAnA
