### ISSUE TITLE
Toggle is not working

### ISSUE THREAD

**Issue by zesa0000** [arendst/Sonoff-Tasmota#5785]
Hey Guys,
after hours I could flash a Sonoff 4CH Pro R2.
BUT: No Toggle Button on the webserver works.
I tried Chrome, Safari, iOS Safari, iOS Chrome.
S6 on 1 and 0, both didnt chance anything.

Under console, I can see the comands:
```
00:14:25 RSL: stat/sonoff4chpro/RESULT = {"POWER1":"OFF"}
00:14:25 RSL: stat/sonoff4chpro/POWER1 = OFF
00:14:26 RSL: stat/sonoff4chpro/RESULT = {"POWER1":"ON"}
00:14:26 RSL: stat/sonoff4chpro/POWER1 = ON
00:14:28 RSL: stat/sonoff4chpro/RESULT = {"POWER1":"OFF"}
00:14:28 RSL: stat/sonoff4chpro/POWER1 = OFF
00:14:28 RSL: stat/sonoff4chpro/RESULT = {"POWER1":"ON"}
00:14:28 RSL: stat/sonoff4chpro/POWER1 = ON
```

But thats all. The sonoff doesnt react of any commands.

What could be wrong? :(

btw:
The module type is Sonoff CH4 Pro (23). Should be the right one.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
