### ISSUE TITLE
Sonoff tasmota MQTT duplicate entries in home assistant for POW R2

### ISSUE THREAD

**Issue by evlo** [arendst/Sonoff-Tasmota#5788]
I have quite a few POW R2s that all have duplicate entries for the switch (or maybe online state of the sonoff box itself) that I have in history and would like to get rid off.
I use hassio, so I use the integrated mosquitto and it's autodiscovery and I would like not to have to configure each switch and sensor manually.

This is my config https://i.imgur.com/vSJjr2i.png and what i'm writing about. Switches that show unavailable are the ones that were newly flashed with 6.5, the one that shows off are the ones that are upgraded from older versions for year or so.

What I would like is to have only one entry for each Pow r2 switch - unavailable when it is is offline/on when it is on and off when it is off.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
