### ISSUE TITLE
Time not correct when using "APP_TIMEZONE 99"

### ISSUE THREAD

**Issue by AffeP** [arendst/Sonoff-Tasmota#579]
Compiled with the following code:
#define TIME_DST               Last, Sun, Mar, 2, +120  // Last sunday in march at 02:00 +120 minutes
#define TIME_STD               Last, Sun, Oct, 3, +60   // Last sunday in october 02:00 +60 minutes
#define APP_TIMEZONE           99                // [Timezone] +1 hour (Amsterdam) (-12 .. 12 = hours from UTC, 99 = use TIME_DST/TIME_STD)

But it does not work, gives me TIME_STD even when it should be TIME_DST?

Great work by the way!!
:-)

**Comment by arendst** [comment]
What's your current timezo e value (command timezone)

**Comment by AffeP** [comment]
{"Timezone":1}

**Comment by arendst** [comment]
Change it to 99 and you're on time. No need to fool around with user_config.h. It's so 2016...

**Comment by AffeP** [comment]
Worked fine!!

**Comment by AffeP** [comment]
Should it not have worked the other way to?
It is ok now when I know the backdoor way.
