### ISSUE TITLE
Toggle switch on gpio3/gnd stopped working

### ISSUE THREAD

**Issue by mrlong67** [arendst/Sonoff-Tasmota#5790]
Hi,
I have set up quite a few sonoff basics v2 in switchmode1 with standard toggle light switch using gpio3 and gnd.
All physical toggle switches worked but a few started to randomly flicker even when off eventually leading to the physical toggle switch (wall switch) not working. They can be turned on or off via any other method. (home assistant/google assistant/alexa/tasmota gui)

1. Can a gpio pin fail?
2. Will the resistor/capacitor addition to the wiring resolve this issue? Watching the videos online they all say that the lights flicker, none say the physical switch stops working.

Some help will be greatly appreciated,

Thanks

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
