### ISSUE TITLE
Tasmota more than one LED Strip

### ISSUE THREAD

**Issue by jflkjjlkdsajlkdsajlkjlkjdsaljdsa** [arendst/Sonoff-Tasmota#5798]
Hello, 

is it possible to control two white LED strips independently from each other and to also be able to dimm them? If I choose PWM1 and PWM2 for example it thinks I'm using a RGB LED strip instead of two white ones. 
I'm using a Wemos D1 btw in generic mode. 

Thanks
Kind regards
Chris

**Comment by Jason2866** [comment]
See PWM commands in wiki commands section.
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
