### ISSUE TITLE
Tip: How to setup timers in firmware default

### ISSUE THREAD

**Issue by th-s-op** [arendst/Sonoff-Tasmota#5820]
Nothing spectacular... but if you like me want to create a firmware binary with one or more timers already set up by default, just add the following code to the end of the "void SettingsDefaultSet2(void)" function in "settings.ino":

  Settings.flag3.timers_enable = 1;   // 0:disable timers  1:enable timers

  // example for Output 1, Action Off, Arm, Repeat, Time 02:00 +/- 00, Sun...Sat
  Settings.timer[0].time = 120;  // minutes in a day
  Settings.timer[0].window = 0;  // minutes random window 0..15
  Settings.timer[0].repeat = 1;  // 1:repeat  0:no repeat
  Settings.timer[0].days = 127;  // bit mask for days  0..127
  Settings.timer[0].device = 0;  // Output 0..15 (0:Output 1, ..., 15:Output 16)
  Settings.timer[0].power = 0;   // 0:off 1:on  2:toggle  3:rule
  Settings.timer[0].mode = 0;    // timer modes - 0 = Scheduler, 1 = Sunrise, 2 = Sunset
  Settings.timer[0].arm = 1;     // 1:arm  0:not armed`

The 16 timers are referenced by timer[0] to timer[15].

**Comment by ascillato2** [comment]
Thanks for the tip :+1:
