### ISSUE TITLE
Single button to cycle motor up>stop>down>stop etc...

### ISSUE THREAD

**Issue by rbswift** [arendst/Sonoff-Tasmota#5821]
I am using a sonoff dual R2 to control a roller shutter motor with the Interlock and PulseTime commands.

I think it would be very useful to control the motor with a single momentary press button (either the onboard button or one remotely wired to a GPIO) and to cycle through:

Up (Relay1 On),
Stop (Relay 1 Off),
Down (Relay 2 On),
Stop (Relay 2 Off)
etc...

Forgive me if I've missed something but I don't see any way to do this currently.

Thanks

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
