### ISSUE TITLE
Problem with Core 2.3.0 and device with 2MB Flash

### ISSUE THREAD

**Issue by ihavenonick** [arendst/Sonoff-Tasmota#5825]
with Core 2.3.0 not OK
![grafik](https://user-images.githubusercontent.com/36501310/57983774-e5ef8800-7a55-11e9-86fa-bb2d980ef22b.png)

with Core 2.5.1 OK
![grafik](https://user-images.githubusercontent.com/36501310/57983791-12a39f80-7a56-11e9-93d3-b05f16a87ddc.png)

Master Version 6.5.0 with Core 2.3.0 OK
![grafik](https://user-images.githubusercontent.com/36501310/57983920-fbb17d00-7a56-11e9-9e17-1c4bc30cc0c2.png)

**Comment by Jason2866** [comment]
Issue template is missing. Anyway 2MB flash is NOT supported from Tasmota.
Tasmota uses always 1M flash no SPIFFS for all devices. This is needed and done for OTA upgrade possibility for all devices with Tasmota.

**Comment by ihavenonick** [comment]
It worked the whole time and works with the master version as well. Thus, this statement is not correct

**Comment by Jason2866** [comment]
You are wrong take a look https://github.com/esp8266/Arduino/tree/09826c6d87e54c15422da90f060377c9ef188947/tools/sdk/ld

**Comment by ihavenonick** [comment]
Look at the pictures, as you can see that it works who the 2.5.1 Core at the dev. Version takes, or the master version 6.5.0

**Comment by ihavenonick** [comment]
![grafik](https://user-images.githubusercontent.com/36501310/57984146-fa814f80-7a58-11e9-8647-fb303d3cf1cc.png)

**Comment by Jason2866** [comment]
Yes because 2.5.1 is a DIFFERENT NEWER core and it does support.
Core 2.3.0 does not.

**Comment by ihavenonick** [comment]
and why does the Screnshot say something else?

**Comment by Jason2866** [comment]
Because you have used a manually builded linker script. I did not say it isnt possible.
It isnt official supported.

**Comment by Jason2866** [comment]
Please close this. It isnt a issue. It is as wanted and designed.

**Comment by ihavenonick** [comment]
OK, I think it's wanted to use the 2.5.1 core. Too bad that the current dev. Versions that do not contain anymore.

**Comment by Jason2866** [comment]
You can still use the NEVER official 2M0 linker script that you have used for building the version
you have made before. It is a setup of your build environment. It is in NO way a Tasmota sofware thing.
The 2M0 linker script was never included in Tasmota.

**Comment by ihavenonick** [comment]
Yes, it just does not work anymore.
I will just use the 2.5.1 core, so it works as it had previously worked with the 2.3.0.
