### ISSUE TITLE
Missing commands in wiki

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#5827]
I notice there are missing SETOPTIONS in the command section of the the  Wiki..

Specifically Setoption14, and the new Setoption64...

**Comment by blakadder** [comment]
Thanks for bringing this to our attention!

![image](https://user-images.githubusercontent.com/5904370/58006647-d40af500-7ae8-11e9-8f94-8b5bea2a14e4.png)

SetOption64 will be added to the wiki promptly
