### ISSUE TITLE
bmp280 and bh1750 + Node MCU

### ISSUE THREAD

**Issue by echo4019** [arendst/Sonoff-Tasmota#5829]
Hi, I'm trying to build a weather sensor using bmp280, bh1750 + Node MCU. 

I'm using Tasmota 6.5 and setting the module type to 18 generic.

I have the BMP280 connected to 3v3, GND, D1 & D2. The BH1750 is connected to VIN, GND, D3 & D4. 

The problem i am having is that I am only receiving values from one sensor. I relise these are both I2C so is there something i need to do differently?

![Capture](https://user-images.githubusercontent.com/34657978/58039132-be69ef80-7b29-11e9-90aa-9fba3981303f.PNG)

**Comment by joba-1** [comment]
I2C is a bus. All I2C devices connect to it. Physically attach SDA and SCL
of both sensors to the same 2 pins, e.g. D1 and D2.
-- 
iphone so i typo

**Comment by echo4019** [comment]
Ah that makes sense. 

Thanks for the help!

**Comment by Jason2866** [comment]
Please close. Thx

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)h
