### ISSUE TITLE
Fixed: NO 1M (no Spiffs) available

### ISSUE THREAD

**Issue by noxx2015** [arendst/Sonoff-Tasmota#583]
hello

i want flash my Sonoff S20 and see that the point NO 1M (no Spiffs)
isnt available.
i flashed with 512M (no Spiffs), works. But why i have no  1M (no Spiffs) ?

![1](https://user-images.githubusercontent.com/12627059/27877919-cd1dd9b6-61bc-11e7-9411-07489d84a296.PNG)

**Comment by arendst** [comment]
See wiki - prerequisites

**Comment by Courty40** [comment]
you have to add 1M (no Spiffs) to the config yourself, its not a default option. instructions in the setups / wiki
