### ISSUE TITLE
Flash Slampher without Soldering?

### ISSUE THREAD

**Issue by sonuyos** [arendst/Sonoff-Tasmota#5832]
Hello,

I wanted to flash Tasmota on my Slampher, any way to do it?

I havnt ordered it till now, but looking forward to do it and flash it.

**Comment by curzon01** [comment]
use a search engine of your choice (startpage.com, duckduckgo.com, google) and search for `flash slampher`:
* https://www.youtube.com/watch?v=KEdQEv9vLYM
* https://tinkerman.cat/post/new-firmware-for-the-slampher
...
