### ISSUE TITLE
ESP Chip id in MQTT message

### ISSUE THREAD

**Issue by SargonofAssyria** [arendst/Sonoff-Tasmota#5833]
Could 'ESP Chip id" also be present is MQTT STATUS4?

**Comment by curzon01** [comment]
except STATUS4 shows memory info and IMHO might be the wrong place for it:
use [last three bytes of MAC](https://github.com/esp8266/Arduino/issues/921l)

--
Please address this to [Support's Community](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md#supports-community).
The community channels are a better and more dynamic for helping you.
Github issues are mainly used for Tasmota software feature requests and bug reporting. 

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Jason2866** [comment]
For what is this info needed? Please describe the use case needed for.
There is only a chance to be considered for implementation with a good reason.
