### ISSUE TITLE
Custom mqtt payload

### ISSUE THREAD

**Issue by solucionesmipc** [arendst/Sonoff-Tasmota#584]
hi:

which file should i modify to custom mqttt payload?

thanks 

luis

**Comment by davidelang** [comment]
that depends what you are wanting to do. A lot of the files create parts of the 
mqtt payload.

explain a bit what you are trying to do.

**Comment by solucionesmipc** [comment]
Hi

I need extra data in published messages.

Ex: {"POWER":"ON", "TOPIC":"54555531"}

I need topic published in payload for stat and tele messages

Thanks a lot

**Comment by davidelang** [comment]
that sort of modification would be in sonoff.ino

**Comment by solucionesmipc** [comment]
Thanks for your answer

i got extra data in mqtt messages, but i still dont get the "topic" variable.

ex:

snprintf_P(svalue, ssvalue, PSTR("%s, \"AP\":%d, \"SSID\":\"%s\", \"RSSI\":%d, \"APMac\":\"%s\", \"Topic\":\"%s\"}"),
    svalue, sysCfg.sta_active +1, sysCfg.sta_ssid[sysCfg.sta_active], WIFI_getRSSIasQuality(WiFi.RSSI()), WiFi.BSSIDstr().c_str(), "what variable should i use here");


thanks again

**Comment by davidelang** [comment]
look at the code that sends the stat and tele messages, see the variables that 
are used there to form the message header.
kk

**Comment by solucionesmipc** [comment]
i got it.
sysCfg.mqtt_topic
thanks a lot

solved.
