### ISSUE TITLE
SGP30 Abs Humidity not working

### ISSUE THREAD

**Issue by TONGXD** [arendst/Sonoff-Tasmota#5841]
SGP30 Abs Humidity always shows 0.0000g/m³,no change!
Sonoff-Tasmota 6.5.0.12

**Comment by Jason2866** [comment]
Issue template?

**Comment by gemu2015** [comment]
you need a valid temperature AND relative humidity sensor to get absolute humidity from the sgp30.

**Comment by blakadder** [comment]
Maybe a short write up on the SGP30 use in tasmota on the wiki would help in the future?

**Comment by gemu2015** [comment]
yes this would help. 
the problem however is that there is only one variable named global_update not showing if both needed variables are present and updated. better would be an indication of each global variable separately  then the sgp30 would only show a value when both needed globals were set.

**Comment by arendst** [comment]
@gemu2015 you're right but for the moment just test for a non-zero number as global humidity as zero humidity is highly unlikely.

**Comment by ascillato2** [comment]
Closing this issue as it is solved. Thanks
