### ISSUE TITLE
Pow2 - energy reset does not work

### ISSUE THREAD

**Issue by TungstenE2** [arendst/Sonoff-Tasmota#5846]
Sonoff-Tasmota 6.5.0 on POW2

reset commands according to wiki does not work.

https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

15:36:00 CMD: /SmartHome/Steckdosen/Sonoff-POW-01/EnergyReset
15:36:00 MQT: /SmartHome/Steckdosen/Sonoff-POW-01/stat/RESULT = {"EnergyReset":{"Total":15.975,"Yesterday":0.196,"Today":0.001}}
15:38:51 APP: Serial logging disabled
15:38:54 CMD: /SmartHome/Steckdosen/Sonoff-POW-01/EnergyReset1
15:38:54 MQT: /SmartHome/Steckdosen/Sonoff-POW-01/stat/RESULT = {"EnergyReset":{"Total":15.976,"Yesterday":0.196,"Today":0.001}}
15:39:03 CMD: /SmartHome/Steckdosen/Sonoff-POW-01/EnergyReset2
15:39:04 MQT: /SmartHome/Steckdosen/Sonoff-POW-01/stat/RESULT = {"EnergyReset":{"Total":15.976,"Yesterday":0.196,"Today":0.001}}
15:39:08 MQT: /SmartHome/Steckdosen/Sonoff-POW-01/tele/STATE = {"Time":"2019-05-22T15:39:08","Uptime":"0T00:10:21","Vcc":3.178,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":22,"POWER":"ON","Wifi":{"AP":1,"SSId":"Hustentee","BSSId":"CC:CE:1E:0E:3C:E3","Channel":1,"RSSI":66,"LinkCount":1,"Downtime":"0T00:00:07"}}
15:39:08 MQT: /SmartHome/Steckdosen/Sonoff-POW-01/tele/SENSOR = {"Time":"2019-05-22T15:39:08","ENERGY":{"TotalStartTime":"2019-03-25T19:28:44","Total":15.976,"Yesterday":0.196,"Today":0.001,"Period":1,"Power":8,"ApparentPower":18,"ReactivePower":16,"Factor":0.43,"Voltage":231,"Current":0.078}}
15:39:11 CMD: /SmartHome/Steckdosen/Sonoff-POW-01/EnergyReset3
15:39:11 MQT: /SmartHome/Steckdosen/Sonoff-POW-01/stat/RESULT = {"EnergyReset":{"Total":15.976,"Yesterday":0.196,"Today":0.001}}

**Comment by curzon01** [comment]
Needs an argument, use e.g. EnergyReset<x> 0

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
