### ISSUE TITLE
RF-Bridge does not detect signal from the remote control

### ISSUE THREAD

**Issue by Lampi85** [arendst/Sonoff-Tasmota#5855]
Hello everybody,

I flashed my sonoff rf-bridge with tasmota and the rf-chip with the portish firmware. Unfortunately, the Sonoff does not recognize my remote control.
I had already read the remote control with an Arduino and the RC-Switch library and also the sending worked flawlessly.
Since I always had problems with the signal strength, I would now like to switch to an RF bridge.

Unfortunately, the sniffing of RAW code does not work either, I get a lot of ghost signals and can not identify which ones come from my remote control.

The code I ship with the Arduino is the following:
mySwitch.send (10652032, 24);
mySwitch.send (10652047, 24);

I think this is a Decimal Code have already tried to convert this to HEX but so far has been unsuccessful. I am also not sure if RFSync, RFlow and RfHigh are correct:
`{ mqtt=">[mosquitto:cmnd/sonoff-rfbridge/Backlog:command:ON:RfSync 11320; RfLow 360; RfHigh 1090; RfCode #A28980],
>[mosquitto:cmnd/sonoff-rfbridge/Backlog:command:OFF:RfSync 11320; RfLow 360; RfHigh 1090; RfCode #A2898F]" }`

Can someone please help me to convert this code for the RF-Bridge?

Thanks in advance
Best regards
Lampi

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
