### ISSUE TITLE
Support for ex-store wifi dimmer v4

### ISSUE THREAD

**Issue by martijnr17** [arendst/Sonoff-Tasmota#5856]
I've bought a 2 Kanal RS232 WiFi WLan Dimmer Modul V4 with ESP8266.
It is not on the supported list, I thought because it supports mqtt it works out of the box with domoticz but not.
I have no idea of programming but think it should be pretty easy for the pro's.
The module is well documented how to control over serial.
https://blog.ex-store.de/content/wifidimmer-v4

**Comment by Jason2866** [comment]
Sorry we dont have the device and we cant buy everything...
No it isnt that easy. The described functions are for the included firmware.
How and what have to be done (if possible) to get it working needs completely (re)engeenired

**Comment by martijnr17** [comment]
Sorry my mistake. More work than I thought. To bad.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
