### ISSUE TITLE
MCP230XX switch configuration

### ISSUE THREAD

**Issue by baacktothefuture** [arendst/Sonoff-Tasmota#5857]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Hi,
it would be nice if MCP230XX (configured as input) could have a configuration template such as the main one for the GPIOs, in order to make each channel configured as Switch1, Switch2 etc...
**Describe alternatives you've considered**
I know that achieving a similar result is already possible via rules, but is non straightforward

**Additional context**
-

Thank you
Marco

**Comment by Jason2866** [comment]
It is not the way MCP230xx is designed to work with Tasmota.
Template function is only available for GPIOs from ESP chip.
Changing this to work with the MCP230xx is a mandantory change in Tasmota and in the MCP230xx driver
which will need more of the rare flash space.
You can integrate this behaviour with rules or the new script engine.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
