### ISSUE TITLE
Support for Tuya in-wall dimmer

### ISSUE THREAD

**Issue by MortenVinding** [arendst/Sonoff-Tasmota#5859]
Sorry if this is not the right place to post this.

I bought a in-wall-dimmer on Aliexpress:
[https://www.aliexpress.com/item/Smart-life-Wifi-Smart-dimmer-240V-150W-LED-light-triac-module-Timer-Switch-Controller-Voice-Control/32975062679.html](url)

Thought since it is using the Tuya app it would be possible to flash Tasmota on it.
I tried with Tuya convert, but with no success.

Then I did the manly thing and took it apart:
![IMG_1102](https://user-images.githubusercontent.com/1188091/58360161-7c251300-7e87-11e9-9f0a-522d14c90b8f.jpeg)
![IMG_1096](https://user-images.githubusercontent.com/1188091/58360177-96f78780-7e87-11e9-8f49-0af5f612dcbf.jpeg)
![IMG_1098](https://user-images.githubusercontent.com/1188091/58360259-23a24580-7e88-11e9-92d9-224aa9992f0e.jpeg)
![IMG_1103](https://user-images.githubusercontent.com/1188091/58360288-45033180-7e88-11e9-8d7f-051f41824eb4.jpeg)

But I have been unable to find any info on the used wifi module, and since can't identify TX,RX and GPIO0.

Do any of you guys know this module and is able to point me at some info about it's pinout?

It seems to be working pretty well, but I really want to have Tasmota running on it.

**Comment by Jason2866** [comment]
No this dimmer isnt supported see duplicate #5737 

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
