### ISSUE TITLE
RFBridge variable signal values

### ISSUE THREAD

**Issue by waldorffsmama** [arendst/Sonoff-Tasmota#5866]
With the Sonoff Tasmota RF bridge I get different values for remote signals sent. Rfkey1 2 will not trigger the receiver. Also, a wide array of possible commands sent will not work.

Hardware: RFbridge with Tasmota 6.5.0 and Portisch; receiver Intertechno CMR500 - Homecode 3 and address 3; remote control EZcontrol XS1

STATUS 0 OUTPUT HERE:
cnx/rfbridge/STATUS = {"Status":{"Module":25,"FriendlyName":["Sonoff RF Bridge"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
06:57:43 MQT: cnx/rfbridge/STATUS1 = {"StatusPRM":{"Baudrate":19200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T08:41:49","StartupUTC":"2019-05-27T15:15:54","Sleep":50,"CfgHolder":4617,"BootCount":23,"SaveCount":889,"SaveAddress":"F8000"}}
06:57:43 MQT: cnx/rfbridge/STATUS2 = {"StatusFWR":{"Version":"6.5.0(release-sonoff)","BuildDateTime":"2019-03-19T12:24:10","Boot":7,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
06:57:43 MQT: cnx/rfbridge/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":3,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["connecting...","home"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
06:57:43 MQT: cnx/rfbridge/STATUS4 = {"StatusMEM":{"ProgramSize":507,"Free":496,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0FDAE394","000783A0","23B617CE","00003BC0"]}}
06:57:43 MQT: cnx/rfbridge/STATUS5 = {"StatusNET":{"Hostname":"Sonoff Bridge","IPAddress":"192.168.1.240","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"60:01:94:BE:81:8E","Webserver":2,"WifiConfig":4}}
06:57:43 MQT: cnx/rfbridge/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.14","MqttPort":1883,"MqttClientMask":"rfbridge","MqttClient":"rfbridge","MqttUser":"kai","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
06:57:43 MQT: cnx/rfbridge/STATUS7 = {"StatusTIM":{"UTC":"Mon May 27 23:57:43 2019","Local":"Tue May 28 06:57:43 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+07:00","Sunrise":"10:54","Sunset":"02:40"}}
06:57:43 MQT: cnx/rfbridge/STATUS10 = {"StatusSNS":{"Time":"2019-05-28T06:57:43"}}
06:57:43 MQT: cnx/rfbridge/STATUS11 = {"StatusSTS":{"Time":"2019-05-28T06:57:43","Uptime":"0T08:41:49","Vcc":3.142,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"Wifi":{"AP":1,"SSId":"connecting...","BSSId":"28:28:5D:44:4B:B0","Channel":11,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:03"}}}

CONSOLE OUTPUT pressing remote 10 times:

07:06:47 DMP: A4 2A 58 01 54 04 2E 10 10 14 55
07:06:48 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10840,"Low":340,"High":1070,"Data":"101014","RfKey":1}}
07:06:48 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"1052692","Battery":54,"RSSI":10}
07:06:49 DMP: A4 2A 58 01 54 04 38 50 01 15 55
07:06:49 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10840,"Low":340,"High":1080,"Data":"500115","RfKey":"None"}}
07:06:49 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"5243157","Battery":54,"RSSI":10}
07:06:49 DMP: A4 2A 58 01 54 04 2E 50 01 15 55
07:06:51 DMP: A4 2A 58 01 54 04 38 50 11 15 55
07:06:51 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10840,"Low":340,"High":1080,"Data":"501115","RfKey":"None"}}
07:06:51 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"5247253","Battery":54,"RSSI":10}
07:06:52 DMP: A4 2A 4E 01 54 04 38 50 41 14 55
07:06:52 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10830,"Low":340,"High":1080,"Data":"504114","RfKey":"None"}}
07:06:52 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"5259540","Battery":54,"RSSI":10}
07:06:52 DMP: A4 2A 58 01 54 04 2E 50 41 14 55
07:06:54 DMP: A4 2A 4E 01 54 04 2E 10 10 14 55
07:06:54 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10830,"Low":340,"High":1070,"Data":"101014","RfKey":1}}
07:06:54 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"1052692","Battery":54,"RSSI":10}
07:06:55 DMP: A4 2A 44 01 5E 04 2E 10 10 14 55
07:06:57 DMP: A4 2A 4E 01 54 04 2E 10 10 14 55
07:06:57 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10830,"Low":340,"High":1070,"Data":"101014","RfKey":1}}
07:06:57 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"1052692","Battery":54,"RSSI":10}
07:06:57 DMP: A4 2A 4E 01 54 04 2E 10 10 14 55
07:06:59 DMP: A4 2A 44 01 54 04 2E 10 10 14 55
07:06:59 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10820,"Low":340,"High":1070,"Data":"101014","RfKey":1}}
07:06:59 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"1052692","Battery":54,"RSSI":10}
07:07:01 DMP: A4 2A 58 01 54 04 2E 10 10 14 55
07:07:02 DMP: A4 2A 4E 01 54 04 2E 10 10 14 55
07:07:02 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10830,"Low":340,"High":1070,"Data":"101014","RfKey":1}}
07:07:02 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"1052692","Battery":54,"RSSI":10}
07:07:04 DMP: A4 2A 4E 01 54 04 2E 10 10 14 55
07:07:04 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10830,"Low":340,"High":1070,"Data":"101014","RfKey":1}}
07:07:04 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"1052692","Battery":54,"RSSI":10}
07:07:06 DMP: A4 2A 4E 01 54 04 2E 10 10 14 55
07:07:08 DMP: A4 2A 4E 01 54 04 2E 10 10 14 55
07:07:08 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10830,"Low":340,"High":1070,"Data":"101014","RfKey":1}}
07:07:08 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"1052692","Battery":54,"RSSI":10}
07:07:09 DMP: A4 2A 4E 01 54 04 2E 10 10 14 55

Constant here is "data", "low"; "Sync" varies between 10820 and 10840, while "High" varies between 1070 and 1080. 
I have tried all of the following commands:

backlog rfsync 10820; rflow 340; rfhigh 1070; rfcode #101014
backlog rfsync 10830; rflow 340; rfhigh 1070; rfcode #101014
backlog rfsync 10840; rflow 340; rfhigh 1070; rfcode #101014
backlog rfsync 10850; rflow 340; rfhigh 1070; rfcode #101014
backlog rfsync 10820; rflow 340; rfhigh 1080; rfcode #101014
backlog rfsync 10830; rflow 340; rfhigh 1080; rfcode #101014
backlog rfsync 10840; rflow 340; rfhigh 1080; rfcode #101014
backlog rfsync 10850; rflow 340; rfhigh 1080; rfcode #101014

None of them works. So I press the remote control again (once) and get this output:
07:36:07 MQT: cnx/rfbridge/RESULT = {"RfReceived":{"Sync":10840,"Low":1080,"High":330,"Data":"101014","RfKey":1}}
07:36:07 MQT: domoticz/in = {"idx":2,"nvalue":0,"svalue":"1052692","Battery":54,"RSSI":10}

To make it all more confusing: here "Low" and "High" seem to be reversed. But that does not happen always.

Any ideas what could be wrong here?

**Comment by Jason2866** [comment]
For controlling intertechno devices you need custom EFM firmware (portisch)
I have the best experience with EFM version https://github.com/arendst/Sonoff-Tasmota/blob/development/tools/fw_efm8bb1/RF-Bridge-EFM8BB1-20181127.hex
for switching Intertechno devices. How it is flashed is in wiki described

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
