### ISSUE TITLE
Switch relay instantly when switch is pressed/touched (esp. sonoff touch)

### ISSUE THREAD

**Issue by qorron** [arendst/Sonoff-Tasmota#587]
I understand that there are different actions when the switch is pressed several times.
but esp. with the sonoff touch it is rather annoying if the relay does not respond instantly because there is absolutely no feedback if the touch has been recognized or not.
perhaps other actions could be initiated with an initial long press?

while other devices like the sonoff basic are designed to almost never being operated directly rather than being triggered via the network the sonoff touch was designed to be manually switched on a regular basis.

**Comment by arendst** [comment]
Instant relay power on/off is default behaviour. Anything else is caused by parameters you may have changed.

**Comment by davidelang** [comment]
not quite true, if you hit button0, it waits for a half second to see if you 
hit it again (multipress detection). What they are asking for is an option that 
would disable multipress

**Comment by qorron** [comment]
yep.. exactly.. disable multipress completely or perhaps conditionally, e.g. only if wifi is connected i.e. the module can be reached and reconfigured via the network hence no need to do anything else but switch lights on/off. it should also switch the relay the instant the switch is pressed/touched and not wait once it is released. every legacy light switch gives instant tactile feedback once the required user interaction to flip the switch is completed. e.g. I feel/hear a 'click', I no longer have to increase the pressure of my fingers on the switch an I can remove my hand from the switch now. imho a smart switch should not provide less comfort.

**Comment by ChrSch84** [comment]
Hello all,

iam New at SonOff and so very new at Tasmota. But i run into this Problem as the rest of us. Is it Possible to Disable Multipress over the Console?! Maybe i am blind or i could not find the right command in the Wiki.

Thanks.

**Comment by arendst** [comment]
There will be an option to make a single press instantaneous.

This is mutually excluding any other option like multi-press AND hold as there is no nice way to detecting this AFTER the first press has been acted upon.

**Comment by qorron** [comment]
thanks a lot! that will make the sonoff touch modules much more convenient to use. I understand that having such a mode would hide the means to do some debugging oder recovery if something is not working. but there are ways to remedy this:
only use this mode when the wifi is connected.
- or - 
use a long-press to exit this mode. (the relay would engage the instant the button is pressed but one can always remove the light bulb if darkness is preferred)

these are just my small ideas :-)

**Comment by arendst** [comment]
Was just about to finish the code when @qorron came along with an opt out request ...

The single press only feature can be enabled by ``SetOption13 1``.
I've opted for the long hold press (three times as long as configured by SetOption32) which will return to the default behaviour by exectuting ``SetOption13 0``.

**Comment by qorron** [comment]
oh boy, @arendst, I didn't mean to burden you with extra work. I was just thinking those functions are there for a reason: saving us from prying the modules out of the wall in case something went wrong.

**Comment by ChrSch84** [comment]
@arendst Thank you for the Update the Sonoff Touch is now perfekt :)

**Comment by qorron** [comment]
works like charm for my test rig too.

I encountered some problems with the OTA though, the modules didn't accept the update unless I incremented the CFG_HOLDER.
(I did change the default config to include my wifi and some changes to the full topic)
I guess this is normal?
