### ISSUE TITLE
Sonoff Dual R2 and rolling shutter and SetOption14

### ISSUE THREAD

**Issue by steph5555** [arendst/Sonoff-Tasmota#5871]
Hi there,

I would like to command my shutter with my Sonoff dual R2.

I seen old topic and you speak about SetOption14, but since version 6.5 (the last one) this option dosen't exist yet. So how can i do to don't active 2 relays together ? because it was the fonction of SetOption14.

thank you for your help and sorry for my english.
Stephane

**Comment by meingraham** [comment]
Interlock

**Comment by steph5555** [comment]
Yes thank you soo much
i read this option but didn't understand

i tried, it works

Have a nice day
