### ISSUE TITLE
how to get a switch rule to work with switch_topic="" and NOT control the relay?

### ISSUE THREAD

**Issue by mikep1998** [arendst/Sonoff-Tasmota#5873]
Hello, I have been working on a switch rule not working for days. Finally found the issue switch_topic was set to "my switch topic" so that the relay1 is not controlled by switch1. 

But if I set switch_topic to "" then the switch controls the relay. Not the behavior I want. 

What is the correct way to get a rule to execute for switch1 and not have relay1 change?

thanks

**Comment by blakadder** [comment]
Everything is easily findable in the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Buttons-and-Switches
You have not read the provided message when opening the issue. This is not the place to discuss issues like this.

---
Read the support [Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).
Please consult the [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information or seek help in [Discord Chat](https://discord.gg/Ks2Kzd4).).

**Comment by meingraham** [comment]
@mikep1998 Are you mikep_1998 on Discord? If so, please check you private messages there. Thanks.
