### ISSUE TITLE
BlitzWolf SHP6 -not start..

### ISSUE THREAD

**Issue by itProfi** [arendst/Sonoff-Tasmota#5880]
All do, like in this description- https://github.com/arendst/Sonoff-Tasmota/wiki/BlitzWolf-SHP6
and see:
````
00:00:00 WIF: WPSConfig failed to start
00:00:04 APP: Restarting
 ets Jan  8 2013,rst cause:1, boot mode:(3,7)
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vbb28d4a3
~ld
````
Try version 6.5 and 6.4 sonoff-classic.bin ...
When i flash original sowfware - it WORk WONDERFULL!
What i do wrong?

**Comment by meingraham** [comment]
Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by itProfi** [comment]
For me it work ONLY, if i define in my_user_config.h
````
// If not selected the default will be SONOFF_BASIC
#define MODULE                 BLITZWOLF_BWSHP      // [Module] Select default model from sonoff_template.h

#define SAVE_DATA              1                 // [SaveData] Save changed parameters to Flash (0 = disable, 1 - 3600 seconds)
#define SAVE_STATE             1                 // [SetOption0] Save changed power state to Flash (0 = disable, 1 = enable)
#define BOOT_LOOP_OFFSET       1                 // [SetOption36] Number of boot loops before starting restoring defaults (0 = disable, 1..200 = boot loops offset)
````
Only with this it work!
