### ISSUE TITLE
pzem004 shutdown does not reset readings

### ISSUE THREAD

**Issue by servim** [arendst/Sonoff-Tasmota#5881]
Hi!
When disconnecting pzem004  from electricity, the latest data from pzem004 continue to be published on the Tasmota web page, which is misleading. Is this a limitation of the protocol or can it be fixed so that when the pzem004 is disconnected, the readings are cleared?
PS It is not necessary that the device is permanently connected to electricity, it can have a plug to connect and when it is disconnected from electricity, the automation system to which the Tasmota transmits data will think that the device is still on the network and consumes energy, it is, IMHO wrong.
Thanks :)

**Comment by curzon01** [comment]
Similarly to your SDM230 issue but slightly different code change - I can do a PR to change the behaviour but I'm off next days so you have to wait...

**Comment by servim** [comment]
Thank you for your responsiveness! I'll wait :)

**Comment by arendst** [comment]
@curzon01 Norbert, I'll do it.

**Comment by ascillato2** [comment]
Closing this issue as it is fixed.

Thanks everyone for working on this :+1:
