### ISSUE TITLE
MQTT cmnd/NodeXX/POWER/ ON command no longer working

### ISSUE THREAD

**Issue by Courty40** [arendst/Sonoff-Tasmota#589]
upgraded from 4.2.0 to 5.1.4 and this command returns 'command not recognised' in the console
revert to 4.2.0 and MQTT is working again

**Comment by arendst** [comment]
Did you ever consider the command ``cmnd/NodeXX/POWER ON``?

**Comment by Courty40** [comment]
Just tried with 4.2.0 and 5.1.4 on a couple of Sonoff Basics and this does indeed interpret differently.
`cmnd/NodeXX/POWER/ ON` only works on the version 4.2.0 and below producing an error on 5.1.2, where as `cmnd/NodeXX/POWER ON ` (noting the removal of the backslash after POWER) works on either.

Have updated my Node-Red flows accordingly

Many Thanks..
