### ISSUE TITLE
Tasmota on Sonoff Bridge but port 80 not open

### ISSUE THREAD

**Issue by bkenobi** [arendst/Sonoff-Tasmota#5891]
### ISSUE DESCRIPTION - TROUBLESHOOTING
I flashed following the Tasmota guide:
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF-Bridge-433

Prior to flashing firmware update, I set up the hub to work on my network.  It was somewhat stable but would go offline periodically.  I did not do anything with it for some time (weeks) before getting to flashing Portisch.  That flash was successful but I can't connect to the board reliably now.  Using the 40 second reset does not seem to help though the board does show up on my network I can't connect to port 80.  Network scan shows no available ports on the hub.

### REQUESTED INFORMATION
Sonoff bridge R2 V1.0
Arduino 1.8.5
Tasmota 6.5.0 20190319
Portisch firmware

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
