### ISSUE TITLE
Problem with  daylight saving time / time zone

### ISSUE THREAD

**Issue by Vujagig** [arendst/Sonoff-Tasmota#5893]
<GUIDE>

<This BUG issue template is meant to REPORT Tasmota software BUGS ONLY>
  
<Please DO NOT OPEN AN ISSUE:>
  <If your Tasmota version is not the latest, please update before posting. Your issue might be already solved. Latest precompiled bins of Tasmota can be downloaded from http://thehackbox.org/tasmota/>
  <If your issue is a flashing issue, please address that to the Tasmota Support Chat>
  <If your issue is compilation problem, please address that to the Tasmota Support Chat>
  <If your issue has been addresed before (duplicated issue), please ask in the original issue>
  <If your issue is wifi problem or mqtt problem, please try first the steps provided in troubleshooting of the wiki>

### BUG DESCRIPTION
Can it be that there is a problem with the calculation of the daylight saving time / time zone?
In the default settings of my_user_config, the time zone 1 (standart, Amsterdam, Berlin) and the daylight saving time (UTC + 120 min) show a time that is too low by 1 hour.
Changes in the offset of daylight saving time have no effects on the time.
Why does the daylight saving time offset refer to UTC and not to the set time zone? This makes setting the time zone unnecessary.

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (i.e. Sonoff Basic) : WeMos
- [x] Tasmota binary firmware version number used : 6.5.0.13 / self-compiled
- [x] Development IDE - Compiler / Upload tools used : Arduino IDE / OTA
- [x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE:
09:06:30 CMD: status 0
09:06:30 SRC: WebConsole from 192.168.10.101
09:06:30 RSL: Received Topic /status, Data Size 1, Data 0
09:06:30 RSL: Group 0, Index 1, Command STATUS, Data 0
09:06:30 RSL: stat/sonoff/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
09:06:30 RSL: stat/sonoff/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"External System","Uptime":"0T00:00:13","StartupUTC":"2019-05-31T08:06:17","Sleep":50,"CfgHolder":4617,"BootCount":4,"SaveCount":8,"SaveAddress":"3F4000"}}
09:06:30 RSL: stat/sonoff/STATUS2 = {"StatusFWR":{"Version":"6.5.0.13(sonoff)","BuildDateTime":"2019-05-31T09:49:05","Boot":31,"Core":"2_5_1","SDK":"2.2.1(cfd48f3)"}}
09:06:30 RSL: stat/sonoff/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SAW-AP",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100060000000000000000000000","00000000"]}}
09:06:30 RSL: stat/sonoff/STATUS4 = {"StatusMEM":{"ProgramSize":602,"Free":3472,"Heap":24,"ProgramFlashSize":4096,"FlashSize":16384,"FlashChipId":"1840EF","FlashMode":3,"Features":["00000809","0FFAE394","001783A0","23BE37CC","01003BC0"]}}
09:06:30 RSL: stat/sonoff/STATUS5 = {"StatusNET":{"Hostname":"sonoff-3973","IPAddress":"192.168.10.99","Gateway":"192.168.10.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.10.1","Mac":"2C:3A:E8:1F:6F:85","Webserver":2,"WifiConfig":4}}
09:06:30 RSL: stat/sonoff/STATUS6 = {"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_1F6F85","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
09:06:30 RSL: stat/sonoff/STATUS7 = {"StatusTIM":{"UTC":"Fri May 31 08:06:30 2019","Local":"Fri May 31 09:06:30 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"04:12","Sunset":"20:33"}}
09:06:30 RSL: stat/sonoff/STATUS10 = {"StatusSNS":{"Time":"2019-05-31T09:06:30"}}
09:06:30 RSL: stat/sonoff/STATUS11 = {"StatusSTS":{"Time":"2019-05-31T09:06:30","Uptime":"0T00:00:13","SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SAW-AP","BSSId":"44:4E:6D:39:96:E6","Channel":11,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:04"}}}
09:06:41 WIF: Checking connection...

```
- [x] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:
00:00:00 CFG: Loaded from flash at 3F4, Count 8
00:00:00 SRC: Restart
00:00:00 Project sonoff Sonoff Version 6.5.0.13(sonoff)-2_5_1
00:00:00 WIF: Checking connection...
00:00:00 WIF: Attempting connection...
00:00:00 WIF: Connecting to AP1 SAW-AP in mode 11N as sonoff-3973...
00:00:01 WIF: Checking connection...
00:00:01 WIF: Attempting connection...
00:00:02 WIF: Checking connection...
00:00:02 WIF: Attempting connection...
00:00:03 WIF: Checking connection...
00:00:03 WIF: Attempting connection...
00:00:04 WIF: Checking connection...
00:00:04 WIF: Connected
00:00:04 HTP: Web server active on sonoff-3973 with IP address 192.168.10.99
00:00:04 APP: (UTC) Fri May 31 08:07:37 2019, (DST) Sun Mar 31 02:00:00 2019, (STD) Sun Oct 27 03:00:00 2019
09:07:43 APP: Boot Count 5
09:07:43 CFG: Saved to flash at 3FB, Count 9, Bytes 3584
09:07:57 WIF: Checking connection...
09:07:57 WIF: Connected
09:08:06 CMD: timezone
09:08:06 SRC: WebConsole from 192.168.10.101
09:08:06 RSL: Received Topic /timezone, Data Size 0, Data 
09:08:06 RSL: Group 0, Index 1, Command TIMEZONE, Data 
09:08:06 RSL: stat/sonoff/RESULT = {"Timezone":"+01:00"}
09:08:17 WIF: Checking connection...
09:08:17 WIF: Connected

The real local time is 10:08


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
To specify offsets, you must set time one to 99.

Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
