### ISSUE TITLE
Unable to put Slamper in Programming mode after flash

### ISSUE THREAD

**Issue by sonuyos** [arendst/Sonoff-Tasmota#5900]
I got 4 slamphers, out of them for i tested 2 and both showing same issue.

1 - I flash using latest sonoff.bin and ESP, and it works for something but then wifi connection drops very often

2 - Doesn't show up in HA and gives socket error.

3 - I read that i can compile my own as well, so i tried to do it.

4 - Tried to boot slampher in programming mode, and it just doesnt go, previously in 1-2 try it just booted, i flashed 2-3 times and then it suddenly just stopped, just doesnt let me boot into programming mode.

5 - Now i have 2 dead slampher, which are not connecting to internet/wifi, and gives almost 97% request time out and do not go into programming mode too.

I am not sure what to do.

Is this common?

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
