### ISSUE TITLE
How to output Tvoc_base & Co2_base values to Domoticz?

### ISSUE THREAD

**Issue by TONGXD** [arendst/Sonoff-Tasmota#5902]
SGP30
How to output Tvoc_base & Co2_base values to Domoticz?

https://github.com/rumluft-project/rumluft-indoor-firmware

https://forums.adafruit.com/viewtopic.php?f=19&t=133097&p=677614&hilit=SGP30+baseline#p677614

**Comment by ascillato2** [comment]
Hi,

You can use the Tasmota's feature called rules to publish those values by mqtt. You can search in issues for examples related to domoticz and rules, and also in the wiki. 
If you need further assistant on that, please address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you.

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
