### ISSUE TITLE
Add openenergymonitor.org generic serial energy sensor

### ISSUE THREAD

**Issue by 1danielsan** [arendst/Sonoff-Tasmota#5913]
Hello, is it possible to provide serial support for custom energy meter built with emontx (from openenergymonitor.org).
this should be the original firmware  serial output pattern:
https://github.com/openenergymonitor/emonhub/tree/emon-pi/conf/interfacer_examples/directserial
Seems to be:
idnode ct1 ct2 ct3 ct4 vrms (separated by space)

In my configuration I have 4CT connected to emontx-->arduino nano-->esp8266, that send instant watt, voltage, amps and power factor but NOT ENERGY!  (kwh) using mqtt protocol to my domotic server. 

If you could add this sensor device for a generic esp8266 tasmota to allow importing watt (4channel datas) and voltage from serial input and CALCULATE/showing ENERGY (kwh) informations like for sonoffPOW or pzem004 will be amazing!!

I also see in documentation that there is:
USE_ENERGY_SENSOR
but it is not documented... maybe it already do what I am asking for? (In my configuration I can format serial data output in easy way)

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
