### ISSUE TITLE
Support for Sonoff TX Series

### ISSUE THREAD

**Issue by stevengohss** [arendst/Sonoff-Tasmota#5918]
iTead had recently launched a new touch switch ([Sonoff TX Series](https://www.itead.cc/sonoff-tx-series-wifi-smart-wall-switches.html))

Not sure if Tasmota supports this (using existing Sonoff T1 XCH) or a new module type needs to be created.

Will there be any advise?

**Comment by Jason2866** [comment]
We dont have this device. It needs someone who does the research.
If you do, your findings are highly welcome.

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by arendst** [comment]
I have some in the mail but it is verrrrry slow.

Once received I'll check if it can be implemented.

**Comment by stevengohss** [comment]
Thanks so much and appreciate if you could post once checked so I can place my order too! The TX series looks great.

**Comment by dandowftm** [comment]
Hi, just received a number of TX UK models to add to my home when i get it rewired.
Struggled on for a bit, but found some help from a UK automation forum on Facebook.
Anyway, I've managed to flash tasmota to 1 and 2 channel devices and i suspect the 3 channel will be the same, just havent got round to it yet.
The board is different to any I've found when searching for information so I found a pin out and located the GPIO0 pin on the chip. I bridged this with ground whilst plugging in the FTDI module and got it into boot mode. From here I was able to flash using Atom.
![T1UK Touch](https://user-images.githubusercontent.com/51716783/59292627-56fd1680-8c75-11e9-86db-d59dfb3e349b.jpg)
![GPIO0](https://user-images.githubusercontent.com/51716783/59292633-5bc1ca80-8c75-11e9-977d-d41accb4cddd.PNG)

**Comment by alex-sever-h** [comment]
Hi,
I just got sonoff TX devices for all my apartment, so I'm interested in making them work reliably.
Thanks @dandowftm for finding GPIO0. In the meanwhile, I've found an easier location (R19) to get to it on the PCB. Just measured it, because I don't have too much time right now to test it out.
![easy-sonoff-tx](https://user-images.githubusercontent.com/1508457/59547745-6b2e6580-8f4c-11e9-875d-27b89ef64e22.png)

**Comment by stevengohss** [comment]
Thanks @alex-server-h and @dandowftm for the great work and help on the new TX series. Can I ask if the flashing process is the same as the T1 after bridging GPIO0 or R19 to ground?

**Comment by dandowftm** [comment]
Yes flashes the same way as any other sonoff device. Personally I always use Atom

**Comment by stevengohss** [comment]
Thanks @dandowftm, shall order mine and try

**Comment by shafzhr** [comment]
Is it possible to be done without soldering or it's too tiny?

**Comment by timbru31** [comment]
An interesting new feature seems the controllable LED light - could this be Tasmota controllable in the future? (IMHO the LED is way to bright in the night)

**Comment by meingraham** [comment]
@timbru31 A combination of a "fake" LedLink to be able to have direct control of the LED GPIO and configure them as PWM? That's as far as I'm going to take it since I don't have one of these to test with. But now I've assigned the science experiment ;-)

**Comment by arendst** [comment]
Received my Tx Eu 3 gang and flashed it with Tasmota. Selected T1 3CH and off I went. No issues what so ever. It perfoms exactly like the T1 EU's I had so I think we can say Tasmota supports TX too.

Regarding flashing I used the testpoint (TP2 GPIO0) on the back of the touch board (That's what testpoints are for) and soldered a small wire to it. Flashing is done with the board disconnected from the base anyway.

![IMG_20190715_155814](https://user-images.githubusercontent.com/11044339/61221775-775b3d80-a719-11e9-9135-26f4245c2353.jpg)

**Comment by ascillato2** [comment]
Closing this issue as support for this device has been added to Tasmota by Theo. Thanks

**Comment by zomfg** [comment]
quick question: are your TXs as quick as T1? mine has like half second delay after button press, and since I flashed right away I'm not sure if it's the same with stock firmware :( my T1s are almost instant though

**Comment by shafzhr** [comment]
@zomfg Mine response instantly.

**Comment by ascillato** [comment]
@zomfg 

See commands: Setoption1 and setoption13 for inmediate response.

**Comment by zomfg** [comment]
SetOption13 was it, thank you very much.

**Comment by dannygohks** [comment]
> Received my Tx Eu 3 gang and flashed it with Tasmota. Selected T1 3CH and off I went. No issues what so ever. It perfoms exactly like the T1 EU's I had so I think we can say Tasmota supports TX too.
> 
> Regarding flashing I used the testpoint (TP2 GPIO0) on the back of the touch board (That's what testpoints are for) and soldered a small wire to it. Flashing is done with the board disconnected from the base anyway.
> 
> ![IMG_20190715_155814](https://user-images.githubusercontent.com/11044339/61221775-775b3d80-a719-11e9-9135-26f4245c2353.jpg)

can you show the wiring using TP2 to flash the device?

**Comment by mithoog** [comment]
@dannygohks Connect TP2 with Ground on boot to enter into Flash mood.

**Comment by dannygohks** [comment]
My T2UK3C TP2 dont have GPIO0 in the board. How can i boot into flash mode?

![IMG_20190824_113316](https://user-images.githubusercontent.com/48622859/63632118-38e36780-c663-11e9-9fbf-4cf6f9734639.jpg)
![IMG_20190824_113307](https://user-images.githubusercontent.com/48622859/63632119-38e36780-c663-11e9-9cd6-4a24468d2044.jpg)

**Comment by meingraham** [comment]
The Sonoff 4Ch Pro R1 has a similar issue. The trick is to have a lead connected to ground with a very small pin (e.g., a needle) on the other end. You then hold the pin onto GPIO0 of the ESP chip itself and then apply power to the board. Or you could ohm out the traces to see if GPIO0 is broken out to somewhere on the PCB (e.g., to a pull-up resistor).

**Comment by GaseGasovic** [comment]
Guys, what do u use for flashing, source code or .bin file, because, I cannot flash it with .bin file dunno why.... And another question, does TX 2 channels uses ESP8266 or ESP8265? Thanks in advance

**Comment by Berkinka** [comment]
Hello, I bought Sonoff TX T2 EU (2 gang and 3 gang) version. Yesterday they came and i just tried flashing by using this link https://github.com/arendst/Tasmota/wiki/Sonoff-TX-Series but i saw that the person who did this did not connected ground to serial connector. He just bridged ground and GPIO0 pins. When i did that, did not get any response from device. (I'm using CH340G) Then I tried by connecting ground to serial connector, and then using the other ground on the PCB and bridge it with GPIO0. This time I got 3 blue lights always on. I installed drivers and Tasmotizer able to see my device but when i try to flash unfortunately it can't connect ESP and throw an error. 

I tried on Windows and Mac, same results. Then i accidentally connected TX to TX and RX to RX. This time, Tasmotizer able to connect ESP, erase and write flash successfully. Program said power cycle and did. But when i gave power, all 3 blue lights was just blinking and hardware plugged in/plugged out tone was repeating itself. 

So I cant able to flash this thing. I don't know what i did wrong. How can i solve this? Thanks

**Comment by ascillato** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://tasmota.github.io/docs/#/) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
