### ISSUE TITLE
Support sonoff mini

### ISSUE THREAD

**Issue by leschNUX** [arendst/Sonoff-Tasmota#5925]
Hi,

Itead new sonoff mini.

https://www.itead.cc/sonoff-mini.html

**Comment by Jason2866** [comment]
Since the device is not available yet it cant be supported at the moment.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Derkades** [comment]
It is available now: https://www.itead.cc/smart-home/sonoff-mini.html

**Comment by arendst** [comment]
See #6022

**Comment by meingraham** [comment]
@leschNUX @Derkades 

See also - https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-DIY
