### ISSUE TITLE
Enhanced web experience by moving to a CDN

### ISSUE THREAD

**Issue by EYScudeler** [arendst/Sonoff-Tasmota#5926]
**Have you look for this feature in other issues and in the wiki?**
yes

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Moving most part of the web admin code to a CDN, allowing a better web experience (SPAs like angular, reacts, etc...)

**Describe alternatives you've considered**
Moving most part of web code to a free CDN like Cloudfare.
Make the web server to respond only to REST API calls.

**Comment by Jason2866** [comment]
Tasmota is designed for use with mqtt in a local (W)LAN. 
A enhancement that needs a internet services will not be included i  Tasmota
Feel free to fork and enhance as you like.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
