### ISSUE TITLE
stat/%topic%/STATUSx - period

### ISSUE THREAD

**Issue by cubilon** [arendst/Sonoff-Tasmota#5927]
Hi there,
anyone can explain me **stat/%topic%/STATUSx** list, appearing on the console every 10-20 seconds?
I don't mean the meaning of the data (that's clear to me); what I don't understand is the timing. Why a full list of data every 10-20 seconds? How to adjust this timing? Not with TelePeriod so, what else?

Thanks a lot
KC

**Comment by Jason2866** [comment]
Do you use TasmoAdmin?

**Comment by cubilon** [comment]
WTF

**Comment by cubilon** [comment]
confirmed: it was him. thanks a lot.
