### ISSUE TITLE
Pair Sonoff Rf with programmable 433Mhz remote

### ISSUE THREAD

**Issue by kessack** [arendst/Sonoff-Tasmota#5937]
I have 4 Sonoff RF's which arrive here in Scotland from China on 21/9/2017.

They have all just been re-flashed with the latest Tasmota sonoff.bin & been configured for WiFi & MQTT. 

Weblink and MQTT are switching these units very reliably over WiFi.

When I ordered these sonoff's I did not order the RF remotes with them, as I already had 4 identical looking remotes here that were surplus.

I imagined pairing the remote with the Sonoff would be easy. I don't think it is, but I may be missing something.

I have followed the pairing instructions at 
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-RF 
and elsewhere including on the Sonoff web pages, 
and have had no luck with pairing any of the remotes with any of the Sonof RF switches I have.

Questions:

1. Does the Sonoff expect a signal from the remote that follows a specific pattern / specific number of transmitted bits / timing pattern etc. If so does anyone know what the specific format is?
If I know what the 433MHz signal format it is expecting should look like then I can broadcast it from an Arduino and suck it up onto the remote and the Sonoff RF.

2. Can I get the Sonoff RF to transmit the code it already holds, if I have not deleted it which I think I likely have, so that my remote can learn this code / 433MHz sequence.
The remotes I have are very adaptable and seem to be able to learn all sorts of formats of transmitted 433MHz codes.

3. What is the purpose of the small white push button on the RF board inside the Sonoff RF?
 
Having remotes in your home, as well as your phone in your pocket, is very useful becasue remotes can be stuck onto walls at room entrances which is very very handy.

**Comment by Jason2866** [comment]
1) Should be EV1527 code
2) no, it is only a receiver
3) ?
You have to delete the stored code to get the possibility to learn a new code!

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
