### ISSUE TITLE
Pow R2 not loading Webinterface

### ISSUE THREAD

**Issue by Wibias** [arendst/Sonoff-Tasmota#5938]
Soo today my POW-R-2 started becoming really unresponsive and almost can never be reached. I found out that it just becomes unresponsive when I set the module as `Sonoff Pow R2`, but when I set it as `Sonoff Pow` it works just fine. Can anyone help me with that?

**Comment by Jason2866** [comment]
This is just a coincidence. If it worked before it seems it is hardware defective.
Do you have changed something in your wifi (hardware) setup?

**Comment by Wibias** [comment]
Well. It works fine now. When it's set to Sonoff Pow or to Sonoff Basic. When I change it to Sonoff Pow R2 it doesnt work anymore. On Both Sonoff Pow-R-2. One of them was bought just 3 months ago. So not thinking about hardware there. Not changed anything on wifi side.

**Comment by Jason2866** [comment]
What device is it? It wont work correct if you dont choose the right module.

**Comment by Wibias** [comment]
It is a Sonoff Pow-R2 as I've already said. But when i select the right module: `Sonoff Pow R2` the webpage cant be reached anymore and loads for ever. It can be reached every now and then but with like 2 minutes loading time. When I select other modules the webpage loads just fine and I can atleast use the power toggle.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
