### ISSUE TITLE
Sonoff RF WiFi Station Mode

### ISSUE THREAD

**Issue by HobbytronicsPK** [arendst/Sonoff-Tasmota#5949]
Hi there,
I am using Sonoff Tasmota (Pre-build Binaries) for sometime which is working as expected.

Now I want to install one of my sonoff device in area where there is no WiFi connectivity. I want to boot my Sonoff device in WiFi station mode instead of WiFi client mode. So that it broadcast it's own access point always instead of looking for a WiFi network and gets restarted etc. etc.

May someone please put a light on it whether is it possible or can you consider it as a feature request?

**Comment by Jason2866** [comment]
Sorry not possible.
Will not be implemented because Tasmota is designed to have a mqtt (wifi) connection nearly all time.

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
