### ISSUE TITLE
No Switchs Displayed On Tasmota Main Menu

### ISSUE THREAD

**Issue by Hobit99** [arendst/Sonoff-Tasmota#5956]
I'm using Tasmota 6.5.0 and compiled it using Arduino IDE. After downloading to the Wemos D1 Mini, I attempt to add a switch for my AM312. I changed the module type to Genera, added an Am2301 (DHT22), and tried to add a switch for the AM312. The Temp & Huid was displayed but there was nothing for the switch. I tried all different types of switched on all different ports, nothing.  What am I doing wrong ??????
Mike

**Comment by meingraham** [comment]
Many questions to ask to try to figure this out. Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Hobit99** [comment]
Thanks
