### ISSUE TITLE
Device failed to switch

### ISSUE THREAD

**Issue by kenmercer** [arendst/Sonoff-Tasmota#5957]
My fishtank light is controlled by domoticz using a “every day at 6.30am” timer and the sonoff (Tasmota 6.4.1.17) failed to switch on this morning. It’s only happened once before but I do want a system configured so it is  100% reliable as I have other, more important, switches.

The domoticz log shows it switched on at 6:30:01
The sonoff consol log shows:
06:29:35 MQT: Attempting connection...
06:29:36 MQT: Connected
06:29:36 MQT: tele/MTSC/LWT = Online (retained)
06:29:36 MQT: cmnd/MTSC/POWER = 
06:29:58 MQT: domoticz/in = {"idx":45,"nvalue":0,"svalue":"","Battery":97,"RSSI":6}
06:30:04 MQT: Attempting connection...
06:30:06 MQT: Connected
06:30:06 MQT: tele/MTSC/LWT = Online (retained)
06:30:06 MQT: cmnd/MTSC/POWER = 
06:31:07 MQT: tele/MTSC/STATE = {"Time":"2019-06-15T06:31:07","Uptime":"3T12:32:57","Vcc":3.591,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"mySSId","BSSId":"9C:C1:72:0D:C6:69","Channel":1,"RSSI":66}}
06:31:07 MQT: domoticz/in = {"idx":46,"nvalue":0,"svalue":"24.6","Battery":97,"RSSI":6}

No one was up at 06.30 so what caused the normally reliable connection to break? If a connection does break is there anything I can do to ensure a switch command isn’t lost? Should I run a script to switch all my devices on/off every minute?
Thanks in advance.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
