### ISSUE TITLE
Blocked on minimal-firmware

### ISSUE THREAD

**Issue by cirolaferrara** [arendst/Sonoff-Tasmota#5960]
Hi, I'm blocked on Tasmota 6.5.0 **minimal** on Sonoff Pow. When I try to upload any sonoff firmware (also minimal again) I have timeout error.
Tried:

- _Reset 2_ command and flash again - same result
- _OtaURL http://thehackbox.org/tasmota/sonoff.bin_ and _Update 1_ commands - same result

I'd like to don't flash via serial, any ideas?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
