### ISSUE TITLE
DFRobot Digital Pot

### ISSUE THREAD

**Issue by mobywan1985** [arendst/Sonoff-Tasmota#5962]
**Have you look for this feature in other issues and in the wiki?**

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
The ability to control a digital pot from a MQTT command. From 0-100%
https://wiki.dfrobot.com/Dual_Digital_Pot__100K__SKU__DFR0520

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
Tried PWM or DAC solutions but this seems to be the best.

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by edit21** [comment]
I would be very interested if this can be controlled from Tasmota, I'll grab one of  the pots but not sure how to integrate with Tasmota, happy to test code though, would open up a powerful scope to the  current  arsenal of features. Looks to be 3 wire SPI.
