### ISSUE TITLE
Detect light flashing

### ISSUE THREAD

**Issue by PitySOFT** [arendst/Sonoff-Tasmota#5963]
Hi,

I have a Nice Gate Automation and the control unit has an output for flashing a light. If the door is opened the light start flashing. I can detect the flashing using an optocoupler because of high voltage (~24V).

The bottom line is that I want to send an MQTT message when the flashes begin and then send another MQTT message when the flashing is stopped.

Any idea how to set up one pin on the ESP to achieve this?

Thanks.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
