### ISSUE TITLE
MCP23017 Option 6

### ISSUE THREAD

**Issue by Sansibari** [arendst/Sonoff-Tasmota#5965]
I'm glad about the implentation of MCP23017!

In the table after the text "The behavior of all pins on the MCP23008 / MCP23017 ....."
(https://github.com/arendst/Sonoff-Tasmota/wiki/MCP23008-MCP23017)

the option 6 is missing (please complete).

At "sensor29 reset6"
All outputs should be initialized "high" (and not low as they are now), otherwise relays will be turned on at reset6 with a relay board connected to the MCP 23017.

I would be happy if the inputs / outputs of the MCP23017 behave the same way as the outputs / inputs from Sonoff (Power, Power1, Power2 ... Power15) and would also issue the same MQTT messages.
Integration into projects like ioBroker would be much easier.

Thanks

**Comment by andrethomas** [comment]
> All outputs should be initialized "high" (and not low as they are now), otherwise relays will be turned on at reset6 with a relay board connected to the MCP 23017.

This change request is probably logical but could be mitigated by accepting that this will happen during initial configuration and setting the default power-on state with something like this as documented in the wiki.

``
sensor29 0,6,1  // Configure pin 0 as INVERTED OUTPUT and default to OFF on reset/power-up
``

> I would be happy if the inputs / outputs of the MCP23017 behave the same way as the outputs / inputs from Sonoff (Power, Power1, Power2 ... Power15) and would also issue the same MQTT messages.
> Integration into projects like ioBroker would be much easier.
> 

This will not be possible as the PowerX commands are limited to controlling relays or lights directly connected to a specific pin on the ESP82xx.

The MCP230xx implementation is a sensor like extension so it cannot be integrated unconditionally in the main firmware as it is an elective add-on controlled via the driver interface.

It's neither viable nor likely to use the additional IO pins provided by expander chips like the MCP230xx and PCF8574/5 type port expanders as there is no direct interface to facilitate this conditionally from within the ESP82xx core.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
