### ISSUE TITLE
Tasmota & MCP23017: HTML and MQTT command

### ISSUE THREAD

**Issue by Sansibari** [arendst/Sonoff-Tasmota#5966]
How I can switch on/off the  MCP23017 pins D0...D15 via HTML and MQTT?

**Comment by blakadder** [comment]
You have not read the provided message when opening the issue. This is not the place to discuss issues like this.

Read the support [Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).
Please consult the [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information or seek help in [Discord Chat](https://discord.gg/Ks2Kzd4).
