### ISSUE TITLE
Webserver off, MQTT on ?! (5.2.3 & 5.2.4)

### ISSUE THREAD

**Issue by chriskmn** [arendst/Sonoff-Tasmota#597]
Hello,

after updating to 5.2.3 and 5.2.4 I have then problem that the devices are not any more adressable via http/webserver, but still work via MQTT. After power off and on the device it works again as usual.

Is this known ? I have the effect on all 11 devices at my home.

Thanks, Chris

**Comment by ionciubotaru** [comment]
Your wifi signal is low. MQTT works even at 5% signal, while WEB need at least 40%

**Comment by chriskmn** [comment]
Thank you Ion. Did not know about that difference. But even devices close to the router ( less than one meter) are affected. And I haven't had the issues with 5.1.x....
