### ISSUE TITLE
Reboot continuously after set   3 reles ,  i2c and 1 button by TEMPLATE

### ISSUE THREAD

**Issue by ArielBaravalle** [arendst/Sonoff-Tasmota#5972]
### BUG DESCRIPTION
Hello
After  set this tamplate in a ESP12E  nodemcu ,  the firmware stop an reset continuosly by the "wdt reset".

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x ] Device used (i.e. Sonoff Basic) : ESP201  and  ESP12E ( nodemcu)
- [ ] Tasmota binary firmware version number used : 6.5.0(release-sensors)  / (pre-compiled )
- [ ] Development IDE - Compiler / Upload tools used : ____ / ____
- [ ] Provide the output of command ``status 0`` :  I can't
```
STATUS 0 OUTPUT HERE:
i can't get the status 0  ,  the module are restartes continuosly.

```
- [ ] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:
```

00:00:00 Project sonoff Sonoff Version 6.5.0(release-sensors)-2_3_0
00:00:00 WIF: Connecting to AP1 MOVISTAR_A58A in mode 11N as sonoff-0951...
00:00:07 WIF: Connected
00:00:07 HTP: Web server active on sonoff-0951 with IP address 192.168.1.41
18:50:19 OTH: MQTT enable ON, Emulation 0, FriendlyName Esp12E, Sonoff2, Sonoff3  , Sonoff4
18:50:19 RSL: stat/sonoff/RESULT = {"NAME":"ESP201","GPIO":[17,21,255,22,6,5,23,  24,255,255,255,255,255],"FLAG":1,"BASE":18}
18:50:19 RSL: stat/sonoff/RESULT = {"Module":"0 (ESP201)"}
18:50:21 APP: Restarting

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v60000608
~ld

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v60000608
~ld

### TO REPRODUCE
set this template :
{"NAME":"ESP201","GPIO":[17,21,255,22,6,5,23,24,255,255,255,255,255],"FLAG":1,"BASE":18}
in "configure ohter " button

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by arendst** [comment]
Bad template. You cannot use GPIO9 and GPIO10 on your hardware as they are used to access the ESP flash. There is a reason why they are in RED.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
