### ISSUE TITLE
knx coupler

### ISSUE THREAD

**Issue by dcec** [arendst/Sonoff-Tasmota#5974]
Is possible to use a knx coupler instead of knx ip?
With wired bus is possible to integrate on existing wired knx.
I find this project:
http://www.intranet-of-things.com/smarthome/infrastructure/knx/arduino/

**Comment by ascillato** [comment]
Hi,

Sorry, but Tasmota only supports KNX IP MULTICAST by using the wifi capabilities of the esp8266 chip.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
