### ISSUE TITLE
Tuya Smart Life WiFi Boiler Water Heater Switch 4400W

### ISSUE THREAD

**Issue by thepuncake** [arendst/Sonoff-Tasmota#5976]
Hi there, this isn't really an issue, was unsure where to post it, please let me know if this is not the place. Anybody familiar with these? From what I understand they are relatively new. I emailed the seller who confirmed this is ESP8266. I have ordered one, we'll see when it arrives I guess :)

This is the product link:
https://www.aliexpress.com/item/33032606776.html?spm=a2g0s.9042311.0.0.3aa74c4dQXMsZs

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
