### ISSUE TITLE
Tasmota on NodeMCU switch only mqtt commands

### ISSUE THREAD

**Issue by moita420** [arendst/Sonoff-Tasmota#5977]
Hello, i have flashed my nodemcu with tasmota, and i want to connect just pushbuttons to the nodemcu, so i choosed generic on the board selection and assigned some gpios to the switch input, but when i pull it to ground i dont get any command even with "buttontopic 1" 
What am i doing wrong? 
Maybe im not posting on the best place Sorry! But i've searched online and found no solution.
Thanks and keep the great work!

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
