### ISSUE TITLE
Upload Failed  Not enough space...ver 6.5.0.13

### ISSUE THREAD

**Issue by itProfi** [arendst/Sonoff-Tasmota#5978]
Hello, friends! I have a trouble - BlitzWolf SHP Module BW-SHP6 - 
Program Version | 6.5.0.13(classic)

````2019-06-21T18:00:44
2_5_2/2.2.2-dev(c0eb301)
0T00:25:26
11 at 0xFB000

ESP Chip Id	2331020
Flash Chip Id	0x144068
Flash Size	1024kB
Program Flash Size	2048kB
Program Size	493kB
Free Program Space	508kB
Free Memory	29kB
````
When i compile  minimal version - only 386 kb - i have same error - 

Upload Failed
Not enough space ::(

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
