### ISSUE TITLE
Sonoff TH16 + SI7021 null sensor reading

### ISSUE THREAD

**Issue by superq1** [arendst/Sonoff-Tasmota#5985]
Running Tasmota 6.5.0 on Sonoff TH16 configured GPIO14 with SI7021 temp & humidity sensor 
However I continuously get "null" sensor readings on both temperature and humidity.
However if I plug in DS18B20 sensor and configure, I get reading straight away.
I have 3 x SI7021 sensors all doing the same thing ...
Not sure its the connection jack - seems to work just fine with DS18B20
... so what gives?

The below log entry persists:

`MQT: tele/heater_kayla/SENSOR = {"Time":"2019-06-26T17:24:29","SI7021":{"Temperature":null,"Humidity":null},"TempUnit":"C"}`

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by superq1** [comment]
Thank you Jason - wasnt sure if it was a bug or a general support issue
Will take it up in the forum and see if I can get some help there ...
