### ISSUE TITLE
Help With Flashing

### ISSUE THREAD

**Issue by filoor** [arendst/Sonoff-Tasmota#5987]
Hi All.

I would like to have some help to Flash a switch.
I have tried tuya convert OTA but it wont work for this switch
How Must i connect it on which pins.
![IMG_20190627_145436](https://user-images.githubusercontent.com/3647638/60268130-febc4a80-98eb-11e9-9f40-701d828da861.jpg)
![IMG_20190627_145431](https://user-images.githubusercontent.com/3647638/60268131-ff54e100-98eb-11e9-8d0a-9c93ff0aa3c4.jpg)
![IMG_20190627_145425](https://user-images.githubusercontent.com/3647638/60268132-ff54e100-98eb-11e9-9555-fdb2e3f8d5d7.jpg)
![IMG_20190627_145701](https://user-images.githubusercontent.com/3647638/60268133-ff54e100-98eb-11e9-84f2-44ca6669ffd4.jpg)

Thanks a Lot

**Comment by tobox** [comment]
You should at least specify the exact name and model of the device you are trying to flash.

**Comment by tobox** [comment]
Here you see all necessary connectors on the ESP8266 board; you may trace some of them to the 5 point header. Then solder wires to the remaining pins and follow the standard flash instructions.

https://user-images.githubusercontent.com/14855001/34749157-2fc38d00-f5a0-11e7-89c0-3cd91e443803.jpg

**Comment by meingraham** [comment]
Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Jason2866** [comment]
Google is your friend 🙄
[Module TYWE3S](https://docs.tuya.com/en/hardware/WiFi-module/wifi-e3s-module.html)

**Comment by filoor** [comment]
Thanks all
