### ISSUE TITLE
Default value in AP1 Password Field

### ISSUE THREAD

**Issue by seanr2109** [arendst/Sonoff-Tasmota#5994]
does anybody know what the default value that is in the AP1 Password field?

I just went to setup a device for the first time and thought lastpass had populated the AP1 password field, however the device never connected to the wifi.

when i do to 192.168.4.1 the AP1 and AP2 fields already have something in them (but obviously they are just showing 4 dots and not the actual value of the field.)

I am hoping if there is a known default value for these fields i can just change my wifi password temporarily to this password let the device connect and go in and set the correct password then reset my wifi password.

before anybody suggests putting the device into a different mode by pressing a button 4/5 times this unfortunately isn't an option as its a smart plug and the button is not on gpio 0 or configured. so the only way i can see is an option is to try and get the device to connect with its current password.

**Comment by ascillato2** [comment]
Hi,

There is no password defined by default.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
