### ISSUE TITLE
Password protection for web interface?

### ISSUE THREAD

**Issue by smadds** [arendst/Sonoff-Tasmota#60]
I would like to discuss the feasibility and appetite for adding password protection to the web interface.
It seems to me that at the moment the Sonoffs are vulnerable to anyone logged into the same wifi network. Clearly one option is to create a hidden SSID wifi access point for Sonoff use, but if that is not an option, how can we secure the devices?

Would an admin password setting option on the 192.168.4.1 initial setup page work? If the password was forgotten a full system reset could start from scratch. Also, setting/resetting the admin pw from MQTT could be possible as access to the MQTT server can be secured.

Thoughts?

**Comment by arendst** [comment]
Quick solution: disable webserver with option 0.

**Comment by smadds** [comment]
If there was a "like" button I would press it!
ᐧ

**Comment by hoekbrwr** [comment]
:closed_lock_with_key:
