### ISSUE TITLE
ESP8266 with 8 Relay Board Problem

### ISSUE THREAD

**Issue by Dreamdancer100** [arendst/Sonoff-Tasmota#6007]
Have more ESP8266 in use but one that control an 8 Relay Board completely turns! ESP8266 is flashed with the current Tasmota. Configured as 
User (255): GPIO0 = DS18x20 (internally box)
User (255): GPIO15 = Relay1 
User (255): GPIO14 = Relay2
User (255): GPIO13 = Relay3
User (255): GPIO12 = Relay4
User (255): GPIO5 = Relay5
User (255): GPIO4 = Relay6
User (255): GPIO2 = Relay7
User (255): GPIO0 = Relay8
I have installed a 24 volt 3 amp power supply with a step down to 12 volts to get relay board with power and another stepdown to 5 volts what the ESPs supplied with power. The 240 Volt sockets have a direct connection to the relay board over normally closed.
On the other ESP8266 run two DS18B20 water sensors in series and two DHT11 sensors.
The ESP is running perfectly.
This constellation was perfectly connected for 3 months via MQTT. Iobroker was everything. Had the ESP and the relay card already exchanged for new devices but no success. I run a seawater aquarium with the ESPs and I have to rely on a smooth function. Furthermore, I will try to swap the ESP8266 for an ESP32 what then also gets the Tasmota software missed.
I am grateful for any help! If more information is needed, just let me know then share it.
Looking Movie with issue
[http://gordonx.de/issue.mov](url) 
Many Thanks

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Dreamdancer100** [comment]
thanks
