### ISSUE TITLE
WeMos Button

### ISSUE THREAD

**Issue by Courty40** [arendst/Sonoff-Tasmota#601]
Tried load of combinations of Switch / Button settings and SWITCH_MODE settings but I can't seem to get the unit to play nicely.

I'm trying to have the push button send a message over MQTT Without operating the relay.
I have the button on GPIO 4 and the relay on GPIO 5, both work fine other than I cant separate them.

Im sure its me, have I missed something basic here ? can someone point me at a config that works ?

Thanks in advance

**Comment by davidelang** [comment]
look at buttontopic
k
