### ISSUE TITLE
Translation error on Russian language

### ISSUE THREAD

**Issue by ilya89vet** [arendst/Sonoff-Tasmota#6026]
In version 6.5.0 Fw sonoff-RU a part of the text is cut off
![6 5 0](https://user-images.githubusercontent.com/30374417/60752937-9c8ed400-9fd4-11e9-94ba-ff5e601789b8.jpg)

Here an example of correct translation in version 6.4.1
![6 4 1](https://user-images.githubusercontent.com/30374417/60753018-aebd4200-9fd5-11e9-8b78-526a2d935ce6.jpg)

**Comment by arendst** [comment]
As Russian (and others) use UTF-16 character set they need the double amount of char byte size. For next release it was raised to 64 but I notice that it is even too small. So I will raise it to 100.

**Comment by arendst** [comment]
This looks better:

![image](https://user-images.githubusercontent.com/11044339/60755251-6f9aeb00-9fed-11e9-80bb-3dd54b37962a.png)

**Comment by ascillato2** [comment]
Closing this issue as it has been solved. Thanks for reporting :+1: 

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
