### ISSUE TITLE
IR Receiver On Tx or Rx pin

### ISSUE THREAD

**Issue by Adityakush** [arendst/Sonoff-Tasmota#6027]
I tried using IR receiver on the Rx pin and also on the tx pin which did not work even after disabling serial log. 
However these pins can be used as IR receiver as I can confirm using ESPHOME (just to confirm that its not something about the hardware itself). 
Maybe someone can point me in the right direction if I am wrong somewhere. 
Thanks

**Comment by Jason2866** [comment]
Yes, IR Receive does not work on GPIO1 and GPIO3 in Tasmota.

**Comment by Adityakush** [comment]
So that means its not gonna be added in the future also?

**Comment by arendst** [comment]
Correct

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Adityakush** [comment]
Sorry for asking again but why cant these be used?
