### ISSUE TITLE
Domoticz Battery 200% for all devices

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#6033]
### BUG DESCRIPTION
Hello, all domoticz battery levels are at 200%. 

### REQUESTED INFORMATION
- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [X] Device used (i.e. Sonoff Basic) : Sonoff Basic
- [X] Tasmota binary firmware version number used : 6.6.0 / self-compiled
- [X] Development IDE - Compiler / Upload tools used : core 2.5.2 / platformio 2.2.2_dev
- [X] Provide the output of command ``status 0`` :
```
{"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"sonoff_E7C407","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"sonoff_SW_%06X","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
{"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"192.168.2.11/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:24:08","StartupUTC":"2019-07-07T09:59:54","Sleep":50,"CfgHolder":1111,"BootCount":3,"SaveCount":6,"SaveAddress":"F6000"}}
{"StatusFWR":{"Version":"6.6.0(sonoff)","BuildDateTime":"2019-07-07T11:10:09","Boot":31,"Core":"2_5_2","SDK":"2.2.2-dev(c0eb301)"}}
{"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"192.168.2.11","LogPort":514,"SSId":["Name","Sonoff"],"TelePeriod":0,"Resolution":"558180C0","SetOption":["00008009","280500000100060000000000000000000000","00000000"]}}
{"StatusMEM":{"ProgramSize":413,"Free":588,"Heap":33,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440E0","FlashMode":3,"Features":["00000809","0698E106","040783A1","22B617CC","01003BC0"]}}
{"StatusNET":{"Hostname":"sonoff_E7C407-1031","IPAddress":"192.168.2.111","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.1","Mac":"AA:BB:CC:DD:EE:FF","Webserver":0,"WifiConfig":4}}
{"StatusMQT":{"MqttHost":"192.168.2.11","MqttPort":1883,"MqttClientMask":"sonoff_%06X","MqttClient":"sonoff_E7C407","MqttUser":"mosquitto","MqttCount":2,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
{"StatusTIM":{"UTC":"Sun Jul 07 10:24:02 2019","Local":"Sun Jul 07 11:24:02 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00"}}
{"StatusSNS":{"Time":"2019-07-07T11:24:02"}}
{"StatusSTS":{"Time":"2019-07-07T11:24:02","Uptime":"0T00:24:08","Heap":33,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Name","BSSId":"AA:BB:CC:DD:EE:FF","Channel":6,"RSSI":54,"LinkCount":2,"Downtime":"0T00:00:10"}}}
```
- [ ] Provide the output of console when you experience your issue if apply :

### TO REPRODUCE
```
#undef DOMOTICZ_UPDATE_TIMER
#define DOMOTICZ_UPDATE_TIMER    300
```

### EXPECTED BEHAVIOUR
Correct battery level (0-100%).

### SCREENSHOTS
![battery](https://user-images.githubusercontent.com/6533600/60767024-c7028f00-a0b1-11e9-807b-fd3664fdd896.png)

### ADDITIONAL CONTEXT
Seems that something is wrong in https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/xdrv_07_domoticz.ino
```
int DomoticzBatteryQuality(void)
{
  // Battery 0%: ESP 2.6V (minimum operating voltage is 2.5)
  // Battery 100%: ESP 3.6V (maximum operating voltage is 3.6)
  // Battery 101% to 200%: ESP over 3.6V (means over maximum operating voltage)

  int quality = 0;	// Voltage range from 2,6V > 0%  to 3,6V > 100%

  uint16_t voltage = ESP.getVcc();
  if (voltage <= 2600) {
    quality = 0;
  } else if (voltage >= 4600) {
    quality = 200;
  } else {
    quality = (voltage - 2600) / 10;
  }
  return quality;
}
```

**Comment by ascillato** [comment]
If you want to use the internal voltage as your domoticz battery, you need to enable in my_user_config.h the key use_adc_vcc.

#define USE_ADC_VCC

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by 0n3-70uch** [comment]
Thanks
