### ISSUE TITLE
ENERGY_OVERTEMP as SetOption

### ISSUE THREAD

**Issue by cinemarene** [arendst/Sonoff-Tasmota#6036]
**Have you look for this feature in other issues and in the wiki?**
Yes, it seems as if some people need this function as well.
https://github.com/arendst/Sonoff-Tasmota/issues/5968#issuecomment-506975001

**Is your feature request related to a problem? Please describe.**
My Shelly1PM for my washing machine already switches off at 73 degrees. But there is a statement from Shelly that says that the first one switches off at 95 degrees.
https://m.facebook.com/groups/1686781668087857?view=permalink&id=2054834997949187

**Describe the solution you'd like**
ENERGY_OVERTEMP in xdrv_03_energy as SetOption

**Comment by arendst** [comment]
Default changed from 73C to 90C and add command SetOption42 to change it.

**Comment by cinemarene** [comment]
Thank you for the quick implementation.
