### ISSUE TITLE
Simple push-button for Sonoff SV?

### ISSUE THREAD

**Issue by jstorgaard** [arendst/Sonoff-Tasmota#604]
I want to install a Sonoff SV for opening my garageport. I got 24V output for the SV and the garageport motor got input for connecting a simple push-button for triggering open and close of the port.
How should I configure the SV for emulating push of a button?

**Comment by ionciubotaru** [comment]
use GPIO 0 - is configured by default to toggle the relay, or better read https://github.com/arendst/Sonoff-Tasmota/wiki/Understanding-SwitchMode-and-SwitchTopic

**Comment by GhsHun** [comment]
Use PulseTime Command. (for example PulseTime 3 = 0.3 sec impulse) See it: [https://github.com/arendst/Sonoff-Tasmota/wiki/Commands](url) After that you send a Power On command, the switch will be On state and Off state immediately and send an impulse to the motor. This impuilse will open or close the door. That's how I solved the thing.

**Comment by jstorgaard** [comment]
Thank you for your replies. 
I will have a go with the PulseTime command.
For the output - will I use the regular outputs or some other outputs on the SV board for the GPIO?
