### ISSUE TITLE
gbridge.io + new version FW 6.6 with TLS support

### ISSUE THREAD

**Issue by ilya89vet** [arendst/Sonoff-Tasmota#6042]
In version 6.6 support of TLS appeared and I want to be connected directly to gbridge.io for control of the devices by means of [Google Assistant](https://doc.gbridge.io/integration/tasmota.html)

I compiled new version 6.6 with having uncommented both options 
#define USE_MQTT_TLS and #define USE_MQTT_TLS_CA_CERT
After I tried to be connected to mqtt gbridge.io, BUT the device gives an error message "MQT: TLS connection error: 0" 
What do I not so do?
![Screenshot_1](https://user-images.githubusercontent.com/30374417/60800279-9b4cdb00-a17d-11e9-908c-d845b24c8752.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/30374417/60799816-95a2c580-a17c-11e9-8fc0-a3a4bd276a67.jpg)

And still, if I at assembly of the binary file activated TLS I cannot use usual unprotected mqtt connection any more?

**Comment by s-hadinger** [comment]
When using Letsencrypt, the cipher BR_TLS_RSA_WITH_AES_128_GCM_SHA256 is rejected by the server because considered not secure enough.

You can check with the following command:

`openssl s_client -showcerts -connect mqtt.gbridge.io:8883 -tls1_2 -cipher DHE-RSA-AES128-GCM-SHA256`

What you need is an hybrid between the current version and the AWS IoT version that uses BR_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256. It should work as shown with the following command:

`openssl s_client -showcerts -connect mqtt.gbridge.io:8883 -tls1_2 -cipher ECDHE-RSA-AES128-GCM-SHA256`

I'll add it as an option, but I'm lacking time right now.

**Comment by ilya89vet** [comment]
Problem as to me seems that I incorrectly collect Binary file! Except a raskomentirovaniye of two lines in my_user_config it is necessary to do something still?

**Comment by ilya89vet** [comment]
> openssl s_client -showcerts -connect mqtt.gbridge.io:8883 -tls1_2 -cipher ECDHE-RSA-AES128-GCM-SHA256
I did not understand where I need to write this command?

**Comment by s-hadinger** [comment]
You can run this command on any machine to check the server certificates. But you don't need to.

Can you try to compile from this commit ? https://github.com/s-hadinger/Sonoff-Tasmota/commit/edc898f3a360d3bfc72044c3843976955d08ab8e

**Comment by ilya89vet** [comment]
> Можете ли вы попытаться скомпилировать из этой фиксации ? [s-hadinger@edc898f](https://github.com/s-hadinger/Sonoff-Tasmota/commit/edc898f3a360d3bfc72044c3843976955d08ab8e)
> 
> И раскомментировать:`#define USE_MQTT_TLS_FORCE_EC_CIPHER`

I already made it, But there is no positive result!

**Comment by ilya89vet** [comment]
I work in Windows 10 and VSCode PlatformIO
I entered team in a command line
`openssl s_client - showcerts - connect mqtt.gbridge.io: 8883-ls1_2 - cipher DHE-RSA-AES128-GCM-SHA256` 
and it says that openssl is not found...
I need to establish OpenSSL still?

**Comment by ilya89vet** [comment]
Perhaps a problem only at me? Maybe who else will check connection with **gbridge.io**

**Comment by s-hadinger** [comment]
I doubled check, and I was mistaken. It is not a TLS problem. Actually the TLS connection completes normally. It is when MQTT connection is started that there is an issue. Maybe a user/password issue or Retained messages unsupported.

`TLS connection error: 0` means no error at the TLS layer.

Just forget everything I said above, and check your MQTT parameters.

**Comment by ilya89vet** [comment]
Most likely the problem is in my gbridge.io account

вт, 9 июл. 2019 г., 1:38 s-hadinger <notifications@github.com>:

**Comment by ilya89vet** [comment]
The problem as to me seems in the certificate
Here a screenshot from my account gbridge
![Screenshot_5](https://user-images.githubusercontent.com/30374417/60862777-5aa99c00-a227-11e9-9127-d205d015dd80.jpg)

On android the client (Virtuino MQTT) I managed successfully it was connected to gbridge.io only to a psla of the indication of the file of certificates downloaded at this **[link](https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt)**

**Comment by timbru31** [comment]
I've had to enable the private key support, too: https://github.com/arendst/Sonoff-Tasmota/compare/development...s-hadinger:tls_force_ec#diff-abb73cfd1f384bb284b47c0788a61e8eR857 @ilya89vet. For me it connects to my mqtt broker successfully.

**Comment by s-hadinger** [comment]
I tried again, and in both cases I saw the TLS connection working: with or without forcing EC (Elliptic Curve). @ilya89vet your problem is in the MQTT layer, not the TLS layer.

@timbru31 what mqtt broker are you using? Is it useful to merge "Force EC" into development? I'm still not sure this option is any useful.

**Comment by timbru31** [comment]
@s-hadinger I'm using mosquitto on my Raspberry Pi. Since it's in my local network only I'm also my own CA. For me it's useful :) - and with 6.6 it was the only way to connect, with fingerprint and no CA verification I had a lot of crashes (like https://github.com/esp8266/Arduino/issues/6232)

**Comment by s-hadinger** [comment]
@timbru31 You don't have crash anymore with this version? s-hadinger@edc898f

I've had devices connecting to AWS IoT (TLC EC with Private Key) and did not observe a single crash in days.

**Comment by timbru31** [comment]
Correct. (I've made the changes locally myself with the addition of the EC Private Key enabled, too, as stated above. But I'm not 100% if this was needed). My test device is running >2 days now with no restart/crash.
