### ISSUE TITLE
Example of using RC Switch with Tasmota

### ISSUE THREAD

**Issue by vks007** [arendst/Sonoff-Tasmota#6043]
I have a requirement where I want to use an ESP8266 with Tasmota to transmit and receive some data over RF (using 433 MHz modules). I see there is support for RC Switch on Tasmota that was recently added but I could not find any example on how to use that. Can anybody please point me to the right resources. Details of what I am trying to do below:
I am creating a water level controller using SR04 sensor. The transmitter which is a Tasmotized ESP has this configured and is able to publish messages on MQTT but my requirement is also to transmit SR04 data over RF. On the receiving side I will have another Tasmotized ESP which will receive this over RF and be able to take action. It will also update its actions on MQTT. I am not sure if its possible to do this receiver on using Tasmota but for now, I am concentrating only on the transmitter. 
The reason I am introducing RF in the mix here is because I dont want this system to have dependence on HA & MQTT.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
