### ISSUE TITLE
Zoozee plug bricked after factory reset

### ISSUE THREAD

**Issue by ozgunawesome** [arendst/Sonoff-Tasmota#6049]
### ISSUE DESCRIPTION - TROUBLESHOOTING
* I loaded Tasmota 6.6.0 OTA using Tuya convert onto this device: https://blakadder.github.io/templates/zoozee.html
* After a factory reset from GUI I can no longer access the device.
* I can see it joining my access point on the router but not the MQTT broker.
* Web interface either times out or returns unreachable.
* Tried various button combinations found on the wiki to no avail 

### REQUESTED INFORMATION
* Is there anything left to try, except taking it apart and doing a wired flash?

Thanks

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
