### ISSUE TITLE
Inverting ON/OFF Leds on Sonoff Touch

### ISSUE THREAD

**Issue by PeggyFree** [arendst/Sonoff-Tasmota#605]
**Currently :** 
Relay OFF : button LED is OFF, wifi LED is ON
Relay ON :  button LED is ON, wifi LED is OFF

All my family and guests get trapped : whend the living room is dark, they try to push the wifi button which is enlightened, then they get confused because nothing happens.

**Expected:**
Relay **OFF** : button LED is **ON**, wifi LED is OFF
Relay **ON** :  button LED is **OFF**, wifi LED is OFF (or ON, whatever)

Like this the Touch would be more user friendly and behave like my other touch switches : livolo, neo coolcam. IMHO the wifi LED should just blink when a command is sent, but I don't care as long as the main button LED is inverted with the relay state.

**Comment by zizebra** [comment]
I have noted this behavior on my new esp8285 one channel. It does not happen all the time. It does happen after a while. However I am not sure if this is related to the issue which you are experiencing

**Comment by lxz81** [comment]
I've seen this in another issue: https://github.com/arendst/Sonoff-Tasmota/issues/398#issuecomment-298324476

Seems what you expect is not possible

**Comment by davidelang** [comment]
according to the command page, the led state is inverted for the touch, what 
version of the firmware are you running?

see ledstate

https://github.com/arendst/Sonoff-Tasmota/wiki/Commands
k

**Comment by PeggyFree** [comment]
I'm using the 5.1.5. As far as I know the ledstate is mapped on the wifi signal and the push button led is inverted with this. 

The answer to my question is given by arendst in the #398 : The touch has two leds. One connected to the same control line as the relay (in the middle) so that when the relay is on the led is also on. Unable to control it seperately from the relay.

Looks like nobody can change this behaviour, unfortunately. This is a bad design from ITEAD, IMHO.

**Comment by glsf91** [comment]
@PeggyFree 
See my solution in #398 .
Now it is always on.
