### ISSUE TITLE
Adax Electric Heater flash

### ISSUE THREAD

**Issue by DenielTorres** [arendst/Sonoff-Tasmota#6051]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
I have several Adax Neo Wifi branded electric heaters around the house with a digital thermometer. After opening up one of them I can confirm that it runs on ESP 8266.

**Describe the solution you'd like**
Would it be possible to add it to the supported items, or have some information on whether it can be flashed and used with a template?

**Additional context**
I couldn't find any related info/articles on this one so far, and it would be great if we could entertain the idea for a second. Thanks in advance!

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
