### ISSUE TITLE
Help with status of GPIO on boot 

### ISSUE THREAD

**Issue by Giaitzoglou** [arendst/Sonoff-Tasmota#6052]
Hi I have a esp controlling an 4 channel relay and I want on boot to have specific status of the controlling GPIO like say GPIO 4 1 GPIO 5 0 etc . How is that possible ?
Also is it possible have specific GPIO act as a momentary switch when the command comes from MQTT say 1 for GPIO 4 activate GPIO 4 for 1 sec and the 0 again without sending the 0 command via MQTT ? 
Thanks for you help in advance 
Chris

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
