### ISSUE TITLE
Sharp  GP2Y1010AU0F (Sonoff SC sensor) with esp8266+tasmota

### ISSUE THREAD

**Issue by FullLoading** [arendst/Sonoff-Tasmota#6057]
I have a Wemos D1 mini running with tasmota. (version 6.6.0)
At this time, I have an aperture sensor (CP321), temperature and humidity sensor (BME280), light sensor (BH1750), presence sensor (PIR HC-SR501) and wanted to lastly add the sonoffSC dust sensor , the sharp gp2y1010au0f.
What happens is that I do not know how to connect to Wemos D1.
Can someone help me to finalize my project?
Thank you

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
