### ISSUE TITLE
DS1818x20 sensor not working after update to 660

### ISSUE THREAD

**Issue by mvveelen** [arendst/Sonoff-Tasmota#6064]
Been using a Sonoff TH16 with a DS18x20 temperature sensor for a few years now and after updating Tasmota from 650 to 660 I don't get any readings. After downgrading to 650 it's working again. I don't see anything that might be wrong with the configuration and didn't change anything too.

Couldn't find anything about having to change something or other users with the same issue.

GPIO14 sensor: DS18x20(4)

**Comment by Jason2866** [comment]
Please fill out complete issue template. Provide `status 0` output

**Comment by ascillato** [comment]
Have you updated to Sonoff-sensors.bin?

**Comment by mvveelen** [comment]
(Trying to get the output)

No, I updated to sonoff-minimal (OTA) and after that to sonoff.bin (OTA) like I always do.

**Comment by ascillato2** [comment]
Please, update to sonoff-sensors.bin

**Comment by mvveelen** [comment]
Shoot me. After getting the output from 650 and updating to sonoff-minimal.bin and sonoff.bin (660) to get the output from that version, the sensor suddenly works....?

Case closed and I'm feeling ashamed.....

**Comment by ascillato2** [comment]
Great to know that now it is working for you :+1:

Please, next time use the troubleshooting template. It gaves us a lot of information so as to properly help you.

Also remember that you can find us also in the Tasmota Support Chat.
