### ISSUE TITLE
Tuya Dimmer Dimmer Value not equal to Rx Dim State

### ISSUE THREAD

**Issue by Hollako** [arendst/Sonoff-Tasmota#6066]
<GUIDE>

<This BUG issue template is meant to REPORT Tasmota software BUGS ONLY>
  
<Please DO NOT OPEN AN ISSUE:>
  <If your Tasmota version is not the latest, please update before posting. Your issue might be already solved. Latest precompiled bins of Tasmota can be downloaded from http://thehackbox.org/tasmota/>
  <If your issue is a flashing issue, please address that to the Tasmota Support Chat>
  <If your issue is compilation problem, please address that to the Tasmota Support Chat>
  <If your issue has been addresed before (duplicated issue), please ask in the original issue>
  <If your issue is wifi problem or mqtt problem, please try first the steps provided in troubleshooting of the wiki>

### BUG DESCRIPTION
I recently bought and Tuya dimmer US type and flash Tasmota Firmware. Everything goes smoothly and i started to test it then i noticed that the commands sent from the WEB or MQTT are not "accepted" but the dimmer MCU of the Tuya switch. 
After some troubleshoots i did the Dim UP and Dim Down commands from the keypad to see what are the commands received from the ESP i noticed that the RX Dim State is correct and the Dimmer Value in the stat/Result is wrong and not synchronized. And when i send the commands to the MCU, it will reply by another value or it doesn't respond at all.

Noting that the ON/OFF commands are working properly. And i am using the 6.6.0 Version.

HERE IS BELOW THE CONSOLE OUTPUT HERE:

Garden_Dim1/stat/RESULT = {"POWER1":"ON","Dimmer":_**28**_}
22:33:40 TYA: RX Packet: "55aa03070008020200040000004861"
22:33:40 TYA: RX Dim State=**_72_**
MQT: Garden_Dim1/stat/RESULT = {"POWER1":"ON","Dimmer":**_20_**}
22:44:38 TYA: RX Packet: "55aa0307000802020004000000334c"
22:44:38 TYA: RX Dim State=**_51_**

### EXPECTED BEHAVIOUR
RX Dim State = Dimmer value

Thank you in advance, and i am ready for any further troubleshoot when advised.

Regards,

**Comment by thirug010** [comment]
@Hollako, 
I will check and update you on this

**Comment by thirug010** [comment]
PR submitted for this issue

**Comment by Hollako** [comment]
Hello thirug010,

Firs of all, thank you for the support.

And is there something to do or test from my side? 

regards,

**Comment by thirug010** [comment]
@Hollako,

Please take the code from the cloned branch : https://github.com/thirug010/Sonoff-Tasmota
[default setoption66-->0 will use dimmer range 1 - 100, setOption66--> 1 will use dimmer range 1- 255] 

Thanks
Thiru

**Comment by Hollako** [comment]
The link is down !!

**Comment by ascillato** [comment]
@Hollako 

It has been fixed in Tasmota. Please, try latest version from dev branch.

**Comment by Hollako** [comment]
Tested and Done !!

Thank you.
