### ISSUE TITLE
Magic Home- Arilux LC02 - ESP8285 -  ZJ-WFMN-A V1.1

### ISSUE THREAD

**Issue by vsterian** [arendst/Sonoff-Tasmota#6070]
Hello Guys,

I have an Magic Home LED controller with revision ZJ-WFMN-A V1.1 .
I've managed to flash it with a tasmota 6.1.1 firmware just like described in 👍 
https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-with-ESP8285

My problem is that after i flash the new firmware, i disconnect the power, and connect it back again, but no SSID is broadcasted.
I tried also with another custom firmware made specially for this type of controller, but still the same issue.

I've used nodemcu with DOUT option for flashing the ESP8285 controller.

Regardless of this problem I have three other questions:
1.The GPIO pin must be shorted with GND only on boot-up?
2.Can you tell me please what firmware should i use (maybe an older version) in order to successfully use the Controller?
3.Is there any way of "reseting" the controller, or just the wi-fi module (like on H801 with on/off for 4/5 times)?

**Comment by Jason2866** [comment]
You use a very very old version. Try latest.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
