### ISSUE TITLE
IrRemote Repeat & Delay

### ISSUE THREAD

**Issue by marcelkordek** [arendst/Sonoff-Tasmota#6074]
Hi,

is it possible to repeat IR commands?
Some of my IR devices require the code to be sent longer than others.

Maybe something like that (xdrv_05_irremote.ino)?

```
int pulse = root[UpperCase_P(parm_uc, PSTR(D_JSON_IR_PULSE))];
int repeat = root[UpperCase_P(parm_uc, PSTR(D_JSON_IR_REPEAT))];
int rdelay = root[UpperCase_P(parm_uc, PSTR(D_JSON_IR_RDELAY))];
int pdelay = root[UpperCase_P(parm_uc, PSTR(D_JSON_IR_PDELAY))];

if (pulse <= 0)
    pulse = 1; // Make sure pulse isn't 0
if (repeat <= 0)
    repeat = 1; // Make sure repeat isn't 0
if (pdelay <= 0)
    pdelay = 100; // Default pdelay
if (rdelay <= 0)
    rdelay = 1000; // Default rdelay

if (protocol && bits) {
    char protocol_text[20];
    int protocol_code = GetCommandCode(protocol_text, sizeof(protocol_text), protocol, kIrRemoteProtocols);

    snprintf_P(log_data, sizeof(log_data), PSTR("IRS: protocol_text %s, protocol %s, bits %d, data %u (0x%lX), protocol_code %d"), protocol_text, protocol, bits, data, data, protocol_code);
    AddLog(LOG_LEVEL_DEBUG);

    // Repeat Loop
    for (int r = 0; r < repeat; r++) {
        // Pulse Loop
        for (int p = 0; p < pulse; p++) {
            switch (protocol_code) {
                case NEC:
                    irsend - > sendNEC(data, (bits > NEC_BITS) ? NEC_BITS : bits);
                    break;
                case SONY:
                    irsend - > sendSony(data, (bits > SONY_20_BITS) ? SONY_20_BITS : bits, 2);
                    break;
                case RC5:
                    irsend - > sendRC5(data, bits);
                    break;
                case RC6:
                    irsend - > sendRC6(data, bits);
                    break;
                case DISH:
                    irsend - > sendDISH(data, (bits > DISH_BITS) ? DISH_BITS : bits);
                    break;
                case JVC:
                    irsend - > sendJVC(data, (bits > JVC_BITS) ? JVC_BITS : bits, 1);
                    break;
                case SAMSUNG:
                    irsend - > sendSAMSUNG(data, (bits > SAMSUNG_BITS) ? SAMSUNG_BITS : bits);
                    break;
                case PANASONIC:
                    irsend - > sendPanasonic(bits, data);
                    break;
                default:
                    snprintf_P(mqtt_data, sizeof(mqtt_data), S_JSON_COMMAND_SVALUE, command, D_JSON_PROTOCOL_NOT_SUPPORTED);
            }
            if (p + 1 < pulse)
                delay(pdelay);
        }
        if (r + 1 < repeat)
            delay(rdelay);
    }
} else {
    error = true;
}
```
Thanks.

Regards,
Marcel

**Comment by marcelkordek** [comment]
And for MQTT Commands:

```
IRsend {"Protocol":"NEC","Bits":32,"Data":2170978686,"Pulse":1,"Repeat":1,"RDelay":100,"PDelay":1000}
```
Regards,
Marcel

**Comment by Jason2866** [comment]
Sending it twice via command backlog and delay?

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by kobuki** [comment]
Would it be possible to add the same functionality for raw codes? My AC for example requires raw commands to be used, but about 1 in 10 remote command doesn't get through. It would be more robust if it was possible to add repeat/long press parameters similarly to the solution in the [PR](https://github.com/arendst/Sonoff-Tasmota/pull/6096) above. I can open a new issue if needed.

**Comment by s-hadinger** [comment]
Makes sense. Will take a look.

**Comment by s-hadinger** [comment]
@kobuki I have submitted PR #6176

**Comment by kobuki** [comment]
@s-hadinger thanks, I was notified of the PR. How is it possible to set the inter-message delay? Some devices have a specific requirement regarding that.

**Comment by s-hadinger** [comment]
Are you using IRsend with timing pulses or IRSend Raw with binary bitstream? If the later, I need to add a parameter for inter-message.

**Comment by kobuki** [comment]
I'm using the latter - binary codes. Just a hint though, wouldn't it have been simpler to change not the command name, but the raw keyword that accepts additional parameterst? Something like:

`IRSend raw2,<repeat>,<repeatdelay>,0,8951,4543,593,542,1654,110000010110000000000001010000010000000000000000`

I admit I'm not very familiar with the internals of the code, adding an index-like number to the IRSend param (IRSend<X>) like how you implemented now, might be simpler.

**Comment by arendst** [comment]
The chosen solution has the advantage of backward compatibility while allowing to have repeat for both ``IrSend <raw>`` and ``IrSend <freq>``.

**Comment by kobuki** [comment]
I understand, though `IRSend raw2, ...` or similar change would't break that compatibility with `IRSend raw, ...`.

**Comment by arendst** [comment]
Correct, but it wouldn't add repeat to ``IrSend <freq>...`` where you might want it too.

**Comment by s-hadinger** [comment]
Actually `IRSend<x>` comes for free in Tasmota, `<x>` is already in `XdrvMailbox.index`

I'm reluctant to add a parameter to `IRSend raw...` because of backwards compatibility. Instead I propose to insert a computed inter-message pause of `3 * (header_mark + header_space)`. Comparing to existing protocols, il looks like a safe value.

**Comment by kobuki** [comment]
Would something like passing a negative value after the frequency value work? Or some value that's too big to be a mark/space length, like 100000+pause_length from which the actual pause could be computed. I'd be fine with the latest proposed solution, it's simple and if easy to implement, all the better.

**Comment by s-hadinger** [comment]
In your case, I'm not sure the inter-message gap has any importance. You're just covering the fact that the first message was not well received. It's not even equivalent to a long press.

In your case, it would compute to 40.5ms inter-message gap. Is this value suitable?

**Comment by s-hadinger** [comment]
Before you ask, the current code uses `uint16_t` for values, so no negatives nor >65535 values.

**Comment by kobuki** [comment]
I can only test it by converting to raw timing values. I'll attempt that later if you need me to, but I think 40.5 ms would be adequate. It's the same as used by the NEC protocol IIRC. Actually the custom AC IR proto is very similar with similar timings but with 48 bits of data so I can't send them as NEC (Tasmota cuts off the extra bits).

**Comment by s-hadinger** [comment]
Ah, ok. It definitely looked like NEC encoding.

@arendst I'm pushing a complement to the PR.
