### ISSUE TITLE
Sonoff T1 2CH touch buttons unresponsive

### ISSUE THREAD

**Issue by vladanm** [arendst/Sonoff-Tasmota#6079]
Hi, after flashing Sonoff T1 2CH EU by official guide without problems, device over MQTT works ok, it switch lights remotely without problem, but pressing touch buttons is not working ok, i need to press very hard and keep my finger for couple of seconds to work, device worked ok before flashing, any ideas?
Thank You

**Comment by Jason2866** [comment]
See https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#setoption-overview

Setoption13 1
