### ISSUE TITLE
Plugins separation

### ISSUE THREAD

**Issue by Adminius** [arendst/Sonoff-Tasmota#609]
Hi, 
first of all: realy nice job!
but i have some feedback:
i needed about 2h to understand how it woks, which settings has to be to changed and so on...
The other thing: i need only HUE emulation, nothing else... no MQTT, no Webserver, no log...
Is it possible to make it a little bit easier to turn the "plugins" on/off?

My suggestion:
**_user_settings.h:** (should be the first file/tab in Ardiuno IDE)
```
#define LOG
#define WEB_SERVER
#define ...

#ifdef LOG
#include "log.h"
#endif
#ifdef WEB_SERVER
#include "web_server.h"
#endif

```
in this case each plugin is in a separate file and will not be included if it is not necessary.

also all **addLog(..)** functions should be included in `#ifdef LOG ... #endif`

also, please use only one .ino File = main project file, all others (i.e. plugins, settings should be *.h). so it is easier to manage a file order on a compilation.

it aslo possible to put all "not user relevant" files to a separate "tools" or "plugins" folder to make a project structure clearlier

**Comment by arendst** [comment]
You do not have to change any setting in user_config.h Just use the default image and execute commands to configure your device.

Your suggestions are so 2016 and have been leading to this one size fits all firmware.
