### ISSUE TITLE
Sonoff POW - Connection Problems

### ISSUE THREAD

**Issue by riotm0de** [arendst/Sonoff-Tasmota#6090]
Hi Guys,

i already checked the [Troubleshootings](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting#wifi-issues-arduino-core-versions-and-expressif-sdk) and erased my flash. But i still have connection issues as long as i use it via 230v.

When the sonoff is powered by COM Port its working like it should. But when using it with 230V, i cant reach the IP (WebServer). the button on the device still controls the relais. Sometimes i can reach the device via IP and after 2x on/off its gone and not responsive any longer.... 

Please help - Thank you!

PS: I've tried it with sonoff.bin / sonoff-DE.bin / minimal.bin / 6.5.0 version.bin + ESPTool

**Comment by Jason2866** [comment]
Your device has a hardware issue with the power supply.
It is not Tasmota related.

**Comment by riotm0de** [comment]
> Your device has a hardware issue with the power supply.
> It is not Tasmota related.

so the device is broken ?   i mean just L/N cables + EU Plug on it for testing...

**Comment by ascillato2** [comment]
Closing this issue as it is a hardware problem. You should use the warranty and ask for another device. Sorry. 

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
