### ISSUE TITLE
Feature Request: make Ifan driver optional at compile time

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#6093]
**Have you look for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
Decrease firmware size by making the ifan driver selectable when self compiling 

**Describe the solution you'd like**
`# define... `in my_user_config.h for ifan to enable/disable at compile time

**Describe alternatives you've considered**
None

**Comment by arendst** [comment]
Will consider but as it intertwines a lot with the code it ends up with many ifdefs...

**Comment by arendst** [comment]
Well that saves only 2k...

**Comment by Jason2866** [comment]
Thx, every byte counts ;-)
