### ISSUE TITLE
WebSend [IP] FanSpeed + does not work

### ISSUE THREAD

**Issue by qingz2004** [arendst/Sonoff-Tasmota#6094]
"WebSend [IP] FanSpeed +" does not work from any Tasmota console to increase fan speed of iFan02.
"WebSend [IP] FanSpeed -" and "WebSend [IP] FanSpeed [0-3]" work fine.

Lastest Tasmota (6.6.0.2 core 2.3.0).

**Comment by arendst** [comment]
Have a look at #6080

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
