### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#61]
Hello Theo,

I want to compile the new version 3.9.16. But this error appears:

> /home/fabian/Entwicklung/Arduino/Sonoff/Sonoff.ino:158:27: fatal error: ArduinoJson.h: No such file or directory
   #include <ArduinoJson.h>
                           ^
compilation terminated.
exit status 1
Fehler beim Kompilieren für das Board Generic ESP8266 Module. (Error while compiling the code for the Board (...)).

Greetings
Fabi

**Comment by altelch** [comment]
You need to install ArduinoJson library from library manager.

Greetings,
Heiko.

**Comment by 0n3-70uch** [comment]
Hello Heiko,

yeah now I notice that there are some more libaries are required. The next step is the IRremoteESP8266.h.
I was a little bit to fast... the wiki is not up to date because the code is to new :-).

Greetings
Fabi

**Comment by 0n3-70uch** [comment]
I updated the wiki page:
https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite
