### ISSUE TITLE
Update GroupTopic <XYZ Room> is resulted <XYZ_Room>

### ISSUE THREAD

**Issue by Sunrise17** [arendst/Sonoff-Tasmota#610]
Dear @arendst ,
Thanks for the useful update (5.3.0), Backlog works so well. I have one issue after update. Before 5.3.0, i was using v.5.1.3 and my group topic could accept space between words. However, with 5.3.0, its adding "_" to spaces between words. I have checked same thing in FriendlyName, there is no such problem in that.

![28251044-c8e31a90-6a7d-11e7-90ef-57091693e9c3](https://user-images.githubusercontent.com/26038249/28260208-a10a0f14-6ae2-11e7-8e5e-b90c854b17bc.png)

Greetings
Koray

**Comment by arendst** [comment]
Good point. I changed it thinking that mqtt would not allow spaces in topics. Apperently mqtt does allow spaces in topics.

I have to check what the consequences are for my code if i reallow spaces ...

**Comment by Sunrise17** [comment]
It will be so perfect, if you can reallow unless it will be any problem for your code.
Thanks for your support,

**Comment by Sunrise17** [comment]
Dear @arendst,
I am closing this issue, there is no need to use spaces between words in topic in Mqtt. I have solved the issue. Thanks for your attention,
