### ISSUE TITLE
Today energy set to wrong value after power outage and power restored

### ISSUE THREAD

**Issue by ninhvanthang** [arendst/Sonoff-Tasmota#6104]
<GUIDE>

<This troubleshooting issue template is meant to help Tasmota users with difficult problems. It is aimed to be opened if using the wiki and the support chat could not solve the issue. The Github Issue tracker is NOT a general discussion forum>
  
<Please DO NOT OPEN AN ISSUE:>
  <If you have general questions or you need help on Tasmota usage, go to the Tasmota support chat>
  <If your Tasmota version is not the latest, please update before posting. Your issue might be already solved. Latest precompiled bins of Tasmota can be downloaded from http://thehackbox.org/tasmota/>
  <If your issue is a new device, please use the Tasmota Template Feature. See wiki for that>
  <If your issue is a flashing issue, please address that to the Tasmota Support Chat>
  <If your issue is compilation problem, please address that to the Tasmota Support Chat>
  <If your issue has been addresed before (duplicated issue), please ask in the original issue>
  <If your issue is wifi problem or mqtt problem, please try first the steps provided in troubleshooting of the wiki>

### ISSUE DESCRIPTION - TROUBLESHOOTING
_A clear description of what the issue is and be as extensive as possible_
  

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x ] Device used (i.e. Sonoff Basic) : Sonoff Basic
- [x ] Tasmota binary firmware version number used : 6.6 / self-compiled
- [x ] Development IDE - Compiler / Upload tools used : VS Code / ____
- [x ] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE:

13:20:47 CMD: status 0
13:20:47 SRC: WebConsole from 192.168.1.121
13:20:47 RSL: Received Topic /status, Data Size 1, Data 0
13:20:47 RSL: Group 0, Index 1, Command STATUS, Data 0
13:20:47 MQT: stat/powermeter/STATUS = {"Status":{"Module":1,"FriendlyName":["Sonoff"],"Topic":"powermeter","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
13:20:47 MQT: stat/powermeter/STATUS1 = {"StatusPRM":{"Baudrate":9600,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Power on","Uptime":"0T00:13:35","StartupUTC":"2019-07-17T06:07:12","Sleep":50,"CfgHolder":4617,"BootCount":34,"SaveCount":113,"SaveAddress":"F5000"}}
13:20:47 MQT: stat/powermeter/STATUS2 = {"StatusFWR":{"Version":"6.6.0.1(sonoff)","BuildDateTime":"2019-07-12T20:30:24","Boot":31,"Core":"2_5_2","SDK":"2.2.2-dev(c0eb301)"}}
13:20:47 MQT: stat/powermeter/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":4,"SysLog":2,"LogHost":"","LogPort":514,"SSId":["THANGA",""],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","280500000100060000005A00000000000000","00000000"]}}
13:20:47 MQT: stat/powermeter/STATUS4 = {"StatusMEM":{"ProgramSize":416,"Free":584,"Heap":28,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440E0","FlashMode":3,"Features":["00000809","00802182","04000000","0000001C","000002C0"]}}
13:20:47 MQT: stat/powermeter/STATUS5 = {"StatusNET":{"Hostname":"powermeter-7470","IPAddress":"192.168.1.129","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"5C:CF:7F:AF:5D:2E","Webserver":2,"WifiConfig":4}}
13:20:47 MQT: stat/powermeter/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.138","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_AF5D2E","MqttUser":"hassio","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
13:20:47 MQT: stat/powermeter/STATUS7 = {"StatusTIM":{"UTC":"Wed Jul 17 06:20:47 2019","Local":"Wed Jul 17 13:20:47 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+07:00"}}
13:20:47 MQT: stat/powermeter/STATUS9 = {"StatusPTH":{"PowerDelta":0,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
13:20:47 MQT: stat/powermeter/STATUS10 = {"StatusSNS":{"Time":"2019-07-17T13:20:47","ENERGY":{"TotalStartTime":"2019-07-08T23:56:49","Total":113.138,"Yesterday":11.587,"Today":9.267,"Power":479,"ApparentPower":485,"ReactivePower":76,"Factor":0.99,"Frequency":50,"Voltage":218,"Current":2.219}}}
13:20:47 MQT: stat/powermeter/STATUS11 = {"StatusSTS":{"Time":"2019-07-17T13:20:47","Uptime":"0T00:13:35","Heap":30,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"THANGA","BSSId":"C4:71:54:D2:37:46","Channel":1,"RSSI":60,"LinkCount":1,"Downtime":"0T00:01:07"}}}

```
- [x] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:

00:01:07 WIF: Checking connection...
00:01:07 WIF: Connected
00:01:07 HTP: Web server active on powermeter-7470 with IP address 192.168.1.129
00:01:07 DMP: 01 04 14 08 2C 07 49 00 00 0E F5 00 00 4A E6 00 03 01 F4 00 62 00 00 1B DD
00:01:08 DMP: 01 04 14 08 2E 07 37 00 00 0E CE 00 00 4A E6 00 03 01 F4 00 62 00 00 78 A6
00:01:09 MQT: Attempting connection...
00:01:09 DMP: 01 04 14 08 2E 07 37 00 00 0E CA 00 00 4A E6 00 03 01 F3 00 62 00 00 C3 E2
00:01:10 DMP: 01 04 14 08 2B 07 38 00 00 0E CA 00 00 4A E6 00 03 01 F4 00 62 00 00 8F 1D
00:01:11 MQT: Connected
00:01:11 MQT: tele/powermeter/LWT = Online (retained)
00:01:11 MQT: cmnd/powermeter/POWER = 
00:01:11 MQT: Subscribe to cmnd/powermeter/#
00:01:11 MQT: Subscribe to cmnd/sonoffs/#
00:01:11 MQT: Subscribe to cmnd/DVES_AF5D2E_fb/#
00:01:11 MQT: tele/powermeter/INFO1 = {"Module":"Sonoff Basic","Version":"6.6.0.1(sonoff)","FallbackTopic":"cmnd/DVES_AF5D2E_fb/","GroupTopic":"sonoffs"}
00:01:11 MQT: tele/powermeter/INFO2 = {"WebServerMode":"Admin","Hostname":"powermeter-7470","IPAddress":"192.168.1.129"}
00:01:11 MQT: tele/powermeter/INFO3 = {"RestartReason":"Power on"}
00:01:11 MQT: stat/powermeter/RESULT = {"POWER":"OFF"}
00:01:11 MQT: stat/powermeter/POWER = OFF
00:01:11 DMP: 01 04 14 08 2A 07 3E 00 00 0E D5 00 00 4A E6 00 03 01 F3 00 62 00 00 CE 1F
---
00:01:18 DMP: 01 04 14 08 2C 07 2F 00 00 0E B7 00 00 4A E7 00 03 01 F3 00 62 00 00 91 B0
00:01:19 MQT: tele/powermeter/STATE = {"Time":"1970-01-01T00:01:19","Uptime":"0T00:01:17","Heap":31,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":34,"POWER":"OFF","Wifi":{"AP":1,"SSId":"THANGA","BSSId":"C4:71:54:D2:37:46","Channel":1,"RSSI":58,"LinkCount":1,"Downtime":"0T00:01:07"}}
00:01:19 MQT: tele/powermeter/SENSOR = {"Time":"1970-01-01T00:01:19","ENERGY":{"TotalStartTime":"2019-07-08T23:56:49","Total":113.049,"Yesterday":11.587,"Today":9.178,"Period":2,"Power":377,"ApparentPower":385,"ReactivePower":78,"Factor":0.98,"Frequency":50,"Voltage":209,"Current":1.839}}
00:01:19 DMP: 01 04 14 08 2C 07 2F 00 00 0E B7 00 00 4A E7 00 03 01 F3 00 62 00 00 91 B0
---
00:01:45 DMP: 01 04 14 08 3B 07 36 00 00 0E DF 00 00 4A E9 00 03 01 F4 00 62 00 00 5C D8
13:08:56 NTP: Drift 0, (UTC) Wed Jul 17 06:08:56 2019, (DST) Sun Mar 31 02:00:00 2019, (STD) Sun Oct 27 03:00:00 2019
13:08:56 DMP: 01 04 14 08 3B 07 36 00 00 0E DF 00 00 4A EA 00 03 01 F4 00 62 00 00 48 28
---
13:09:19 DMP: 01 04 14 08 4B 07 3E 00 00 0F 0E 00 00 4A EC 00 03 01 F4 00 62 00 00 83 50
13:09:20 WIF: Checking connection...
13:09:20 WIF: Connected
13:09:20 DMP: 01 04 14 08 4D 07 33 00 00 0E F7 00 00 4A EC 00 03 01 F4 00 62 00 00 C2 B2
----
13:09:28 DMP: 01 04 14 08 4E 07 38 00 00 0F 06 00 00 4A ED 00 03 01 F4 00 62 00 00 BE E5
13:09:29 MQT: tele/powermeter/STATE = {"Time":"2019-07-17T13:09:29","Uptime":"0T00:02:17","Heap":31,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"THANGA","BSSId":"C4:71:54:D2:37:46","Channel":1,"RSSI":62,"LinkCount":1,"Downtime":"0T00:01:07"}}
13:09:29 MQT: tele/powermeter/SENSOR = {"Time":"2019-07-17T13:09:29","ENERGY":{"TotalStartTime":"2019-07-08T23:56:49","Total":113.055,"Yesterday":11.587,"Today":9.184,"Period":6,"Power":385,"ApparentPower":393,"ReactivePower":80,"Factor":0.98,"Frequency":50,"Voltage":213,"Current":1.848}}

```

### TO REPRODUCE
_Steps to reproduce the behavior:_
after power outage then power restored, today energy gone wrong value,
today energy value alway set to "Today":9.178 after power restored,

After power restored, my rounter need about 2 minutes to connect to internet,
i think it's because wrong date/time after sonoff reset

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

![today energy](https://i.imgur.com/1A5k2TH.jpg)

i added red arrow to point to value after power restored

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Behaviour is as expected. Power Monitoring values are only stored one per day in flash (around midnight)
This needs to be done to reduce flash writes. If flash write would be done more often device would fail with
defect flash. If the values are mandantory for you save it in a database, all Home Automation systems are capable of this.

**Comment by ninhvanthang** [comment]
> Behaviour is as expected. Power Monitoring values are only stored once per day in flash (around midnight)
> This needs to be done to reduce flash writes. If flash write would be done more often device would fail with
> defect flash. If the values are mandantory for you save it in a database, all Home Automation systems are capable of this.

Do you mean that total value is stored in RAM, and it's written to flash one time per day ?

**Comment by Jason2866** [comment]
yes, all power values are stored in RAM and written one time per day to flash.

**Comment by ninhvanthang** [comment]
ok, Thanks for your info

**Comment by al13nus** [comment]
So writting to flash one time per day does make sense but how to I manualy set the total energy consumsion then?

**Comment by sfromis** [comment]
See commands here: https://tasmota.github.io/docs/Commands/#power-monitoring
(including to set total energy consumption)

**Comment by al13nus** [comment]
> 

Yeah, saving before would have been great, nevermind:

`13:11:57.934 CMD: set EnergyTotal 1033
13:11:57.941 MQT: stat/tasmota_D537DC/RESULT = {"Command":"Unknown"}`

what I'm doing wrong?

**Comment by brjhaverkamp** [comment]
I got hit by this issue as well. I understand the background and only writing to flash once a day.
 I had a couple of (unplanned) outages on parts of my home the past weeks and my graphs look like this now:
![graph of 2 tasmota shelly pm power meters](https://user-images.githubusercontent.com/3051118/210579882-70048384-c1cb-4f7f-b652-58ca56b28960.png)
But it could be made more intelligent, as the updated value total can never be smaller than the old value, right.
So you could do something like this, in pseudo-code:
```
If new_total > old_total
    write new total to flash
if  new_total <old_total
   write old_total+daily usage to flash
```

This way you only use the amount between the previous write and the power outage, which is the best you can get in this case.

**Comment by arendst** [comment]
Try latest dev release. 

It was recently amended with a feature setting the registers after power on like it was midnight the day before.

Might solve your issue.

**Comment by brjhaverkamp** [comment]
Nice, as always you are way ahead of me:-)
