### ISSUE TITLE
Support for Shelly Plug S

### ISSUE THREAD

**Issue by m0rph2k** [arendst/Sonoff-Tasmota#6108]
Hi

can tasmota get support for Shelly Plug S ?

**Comment by Jason2866** [comment]
Have you tried templates from similar looking devices?
For example https://blakadder.github.io/templates/blitzwolf_SHP6.html

**Comment by m0rph2k** [comment]
No, I will try it

**Comment by m0rph2k** [comment]
mhh i open the Shelly-Plug-S but no RX,TX GND label

**Comment by Jason2866** [comment]
Do upload High Res pictures here, maybe we can help

**Comment by m0rph2k** [comment]
I found this.I will test it
https://faulty.cloud/blog/shelly-plug-s-pinout

**Comment by Jason2866** [comment]
Take a look in this template too, if there is a temp sensor in the Shelly S you can adapt from to try to get it working https://blakadder.github.io/templates/shelly_25.html

**Comment by ascillato2** [comment]
>Ok, Shelly S works with Tasmota 6.6.0 and the "BlitzWolf SHP" Template.

Great. Closing this issue as it is solved. Thanks

**Comment by xppx99** [comment]
Hi there! I've managed to flash Shelly Plug S following this guide, and aplying the "blitzWolf SHP" almost everything works. 
One sugestion though is that for someone to update the wiki with this device, please.

**Comment by meingraham** [comment]
@xppx99 

You can submit a new entry in the [template repository](https://blakadder.github.io/templates/). Just name the entry for this device and provide the template you used (similar or same as SHP).
