### ISSUE TITLE
Options as array in STATUS

### ISSUE THREAD

**Issue by tomasroud** [arendst/Sonoff-Tasmota#6110]
**Is your feature request related to a problem? Please describe.**
I can not clearly decode setoption in STATUS (0|3) response.

**Describe the solution you'd like**
Let json response of STATUS includes SetOption bits and integers as numeric array and not 64bit numbers.

**Additional context**
There are changes in options every version and it costs a lot of time to reverse engeneer how options are stored.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by jziolkowski** [comment]
Note that the option changes are only in the 2nd register. See the code around https://github.com/arendst/Sonoff-Tasmota/blob/development/tools/decode-status.py#L199 for explanation.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
