### ISSUE TITLE
Sonoff Dual Flip Switches

### ISSUE THREAD

**Issue by Joeyhza** [arendst/Sonoff-Tasmota#6116]
I have 2 of my duals installed behind wall light switches each controlling 2 lights on Tasmota latest release.

The only problem with the wall switch is I have to flip it up and then down to turn the light on and off. So 2 flips to turn on and then 2 flips to turn off for each external flip switch.

Tried every variant of switchmode. 

Any help appreciated - this is driving me up the wall.

Thanks for all the great dev work people!!! Love Tasmota

**Comment by meingraham** [comment]
You're going to have better luck with an interactive chat. Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
