### ISSUE TITLE
ADC0 - Analog (1) Command

### ISSUE THREAD

**Issue by davidatkadpro** [arendst/Sonoff-Tasmota#6118]
I am having trouble getting ADC0 values with commands, `analog#a0` is displaying as `"Command":"Unknown"`, `Analog#A0div10` in rules doesn't seem to work either. 

It's reading the values and transmitting to MQTT/Console fine with the defaults.

Anyone else noticing this behaviour?

**Comment by meingraham** [comment]
You have not completed the information in the requested template. The information we need to begin to help you is not provided so there is no guidance we can provide.

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
