### ISSUE TITLE
Shelly1PM

### ISSUE THREAD

**Issue by mjoelmendes** [arendst/Sonoff-Tasmota#6123]
I bought a Shelly 1PM, I put a firmware of my own, now I would like to know which relay GPIO and SW, I am using the code below, the relay does not dock and the state the input and always 1.

With the multimeter I measured the SW input and it varies when I load 120V to 230V

//========================================

#define SERIAL_BAUDRATE                 115200

// GPIOs
#define RELAY_PIN                       4

void setup() {

    // Init serial port and clean garbage
    Serial.begin(SERIAL_BAUDRATE);
    Serial.println();
    Serial.println();

    // Close the relay to switch on the load
    pinMode(RELAY_PIN, OUTPUT);
    pinMode(5, INPUT_PULLUP);
    digitalWrite(RELAY_PIN, LOW);
}

void loop() {

 if (digitalRead(5) == 1) {
    Serial.println("0");
  
  } else if (digitalRead(5) == 0) {
    Serial.println("1");
    }  
  
    
      digitalWrite(RELAY_PIN, LOW);
      delay(1000);
      digitalWrite(RELAY_PIN, HIGH);
      delay(1000);

    

 

}

**Comment by meingraham** [comment]
As this is not related to Tasmota, please close this issue. For general ESP coding, there are many forums on the Internet.
