### ISSUE TITLE
Wemos D1 mini and shields

### ISSUE THREAD

**Issue by errik97** [arendst/Sonoff-Tasmota#6126]
Hi, i have installed tasmota on my LOLIN D1 mini and i'm using the IR controller shield and the SHT30 shield. They are working fine but i would like to add the PIR shield, the problem is that he use the GPIO0 (D3) that, at the moment, is used for IRSend. If i try to use another GPIO pin the PIR shield just don't work. How can i remap the GPIO of the PIR shield? 
Thanks for your help.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
