### ISSUE TITLE
MQTT Connect FAILED

### ISSUE THREAD

**Issue by EmilySmith0** [arendst/Sonoff-Tasmota#613]
Hi Guys I am getting MQTT connection issue with my Sonoff basic Relay
I want to integrate my sonoff with HomeSeer using MQTT protocol
My homeseer and Mosquitto broker is on same pc with IP 192.168.1.102
Homeseer plugins are able to communicate with Mosquitto broker but sonoff showing following error

00:00:17 MQTT: Attempting connection...
00:00:18 mDNS: Query done with 0 mqtt services found
00:00:24 MQTT: Connect FAILED to 192.168.1.102:1883, rc -2. Retry in 10 seconds
Thanks
Emily
![mqtt](https://user-images.githubusercontent.com/30232790/28266249-44786810-6b0d-11e7-9d08-ee939e251c6f.PNG)

**Comment by khcnz** [comment]
The error codes (-2) is documented here https://pubsubclient.knolleary.net/api.html#state indicates that it can't connect to that ip address.

**Comment by EmilySmith0** [comment]
I don't know what to do to establish connection
Here is MQTT configurations image
![config](https://user-images.githubusercontent.com/30232790/28267097-ddaa4478-6b11-11e7-8bfb-79e87f4c59a6.PNG)

**Comment by EmilySmith0** [comment]
I allowed mosquitto broker in firewall and all is working now
First click add another program in firewall settings and browse for mosquitto and tick mark to allow in home and public networks
