### ISSUE TITLE
PCA9685 fade funktion

### ISSUE THREAD

**Issue by dr-apple** [arendst/Sonoff-Tasmota#6130]
Hi, i need a function, which can fade every single channel and with each change, z.b. from 10% to 50% or 0% to 100% etc ...

Please help me :-)

**Comment by Jason2866** [comment]
Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
