### ISSUE TITLE
PIR Sensor and relay with delayed OFF

### ISSUE THREAD

**Issue by tosiek** [arendst/Sonoff-Tasmota#6133]
Hi.

I need delay the relay off for example for 300 seconds after motion detection from HC-SR501. (it should be on for 300 seconds after motion detection)

I tried PulseTime but relay turned off in random times. Is there any timer? Which type of switchmode is correct for pir sensor?

**Comment by meingraham** [comment]
`turned off in random times` Then you have something else resetting PulseTime or turning off the relay.

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
