### ISSUE TITLE
Connecting PZEM017 on tasmota

### ISSUE THREAD

**Issue by aslu25** [arendst/Sonoff-Tasmota#6135]
Hi,
I'm trying to connect wemos d1 mini with PZEM017 dc on tasmota
I tried to connect A to D2 and B to D3 with TX/RX and vice versa but no luck. I bought MAX485 TTL To RS485 https://robu.in/product/max485-ttl-rs485/?gclid=Cj0KCQjwyerpBRD9ARIsAH-ITn9BcHEiKtGQkAP2qxKRe0oXUK57QDzx0C32Mfcs6WgaZC69iL3-8jwaAj6vEALw_wcB 
I need help to connect Wemos d1 o rs485 and PZEM017. 
I have latest version of PZEM017.

Thanks 
Aslam

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
