### ISSUE TITLE
DS18B20 sensor info not showing up on web-page (Sonoff TH-16)

### ISSUE THREAD

**Issue by lightrow** [arendst/Sonoff-Tasmota#6139]
<GUIDE>

<This BUG issue template is meant to REPORT Tasmota software BUGS ONLY>
  
<Please DO NOT OPEN AN ISSUE:>
  <If your Tasmota version is not the latest, please update before posting. Your issue might be already solved. Latest precompiled bins of Tasmota can be downloaded from http://thehackbox.org/tasmota/>
  <If your issue is a flashing issue, please address that to the Tasmota Support Chat>
  <If your issue is compilation problem, please address that to the Tasmota Support Chat>
  <If your issue has been addresed before (duplicated issue), please ask in the original issue>
  <If your issue is wifi problem or mqtt problem, please try first the steps provided in troubleshooting of the wiki>

### BUG DESCRIPTION
_A clear and concise description of what the bug is._

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ ] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (i.e. Sonoff Basic) : Sonoff TH-16
- [x] Tasmota binary firmware version number used : 6.6.0/ pre-compiled
- [ ] Development IDE - Compiler / Upload tools used : ____ / ____
- [x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE:

10:17:12 CMD: status 0
10:17:12 SRC: WebConsole from 192.168.1.46
10:17:12 RSL: Received Topic /status, Data Size 1, Data 0
10:17:12 RSL: Group 0, Index 1, Command STATUS, Data 0
10:17:12 MQT: switch/sonoff_2/STATUS = {"Status":{"Module":4,"FriendlyName":["Sonoff"],"Topic":"sonoff_2","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
10:17:12 MQT: switch/sonoff_2/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-sensors.bin","RestartReason":"Software/System restart","Uptime":"0T00:26:38","StartupUTC":"2019-07-27T08:50:34","Sleep":50,"CfgHolder":4617,"BootCount":21,"SaveCount":50,"SaveAddress":"FA000"}}
10:17:12 MQT: switch/sonoff_2/STATUS2 = {"StatusFWR":{"Version":"6.6.0(release-sensors)","BuildDateTime":"2019-07-06T13:12:39","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
10:17:12 MQT: switch/sonoff_2/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["groza_keenetic2","groza_keenetic"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100060000000000000000000000","00000000"]}}
10:17:12 MQT: switch/sonoff_2/STATUS4 = {"StatusMEM":{"ProgramSize":545,"Free":456,"Heap":12,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14605E","FlashMode":3,"Features":["00000809","0FDEE396","0017A3A4","B7FFBFCD","01DABBC0"]}}
10:17:12 MQT: switch/sonoff_2/STATUS5 = {"StatusNET":{"Hostname":"sonoff-2","IPAddress":"192.168.1.33","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"CC:50:E3:C8:25:2C","Webserver":2,"WifiConfig":4}}
10:17:12 MQT: switch/sonoff_2/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.45","MqttPort":1883,"MqttClientMask":"groza","MqttClient":"groza","MqttUser":"groza","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
10:17:12 MQT: switch/sonoff_2/STATUS7 = {"StatusTIM":{"UTC":"Sat Jul 27 09:17:12 2019","Local":"Sat Jul 27 10:17:12 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"05:16","Sunset":"20:36"}}
10:17:12 MQT: switch/sonoff_2/STATUS10 = {"StatusSNS":{"Time":"2019-07-27T10:17:12"}}
10:17:12 MQT: switch/sonoff_2/STATUS11 = {"StatusSTS":{"Time":"2019-07-27T10:17:12","Uptime":"0T00:26:38","Heap":12,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":35,"POWER":"OFF","Wifi":{"AP":1,"SSId":"groza_keenetic2","BSSId":"F6:EC:38:A5:70:1A","Channel":6,"RSSI":88,"LinkCount":1,"Downtime":"0T00:00:04"}}}
```

### TO REPRODUCE
Plug in DS18B20 sensor into Sonoff TH-16 flashed with latest sonoff-sensors.bin

### EXPECTED BEHAVIOUR
Temperature and humidity should appear on main page

### ACTUAL BEHAVIOUR
Temperature and humidity doesn't appear, not even "null" readings

### ADDITIONAL CONTEXT
If i select any other sensor in Modules or Templates configuration, i can see the "null" readings on the web-page, but if i select the DS18x20 ( the one i have ) i get no readings at all, no "null", nothing, just the ON-OFF status of the switch and nothing else. Console log doesn't reflect anything as well.

Im using Sonoff TH-16 with sonoff-sensors.bin, and just plug the sensor 2.5mm cable into the jack, which is supposed to be GPIO14. I tried assigning the sensor to GPIO4 but that didn't work either.

**Comment by lightrow** [comment]
never mind, i just didn't plug it all the way in ( there is an audible click at the very end )

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
