### ISSUE TITLE
Help in Using RF arduino Module

### ISSUE THREAD

**Issue by PipeDeveloper** [arendst/Sonoff-Tasmota#6141]
Hello comunity!

I have bought a Sonoff smart switch which it has included an RF 433mhz receiver. I have understand that it only support one button but its ok for its purpose.

1. The problem that im having is that all my home control that we use to open our gate (yes, all they are 433mhz, just one code per button, its not multicode) doesnt pair with the sonoff swich. Please check the image below to see the control that i have.
![image1](https://user-images.githubusercontent.com/35433329/62001413-d5930380-b0bd-11e9-9b61-e31586bcc1fe.jpeg)
![image2](https://user-images.githubusercontent.com/35433329/62001414-d75cc700-b0bd-11e9-9e2d-cfae2c0090fa.jpeg)

2. Anyways the goal of all this is to use the same code of any button to send it via the RF arduino module (check the image below).
![kit-modulo-rf-transmisor-receptor-433mhz-para-arduino](https://user-images.githubusercontent.com/35433329/62001416-db88e480-b0bd-11e9-981e-b27e2e4143c4.jpg)

Theoretically if it pair with any remote control button and I'm able to decode that button, The RF arduino module should simulate that button and should send the same code.

3 .Next step to get all working (because its a software which it will trigger the on/off signal via the RF module) i need a code of 16 digits long in Hexadecimal
XXXXXX-YYYYYY-ZZZZ
6 first digits X means "on signal"
7-12 digits Y means "off signal" on this case it should be the same as one, because we are repeating the same buttom (well that sonoff supports only one button)
last four digits means the "signal timming"

Possible solutions:
Point 1, im having problems to pair it with that control, the question is if it is possible to reset and coppy a code (a working code) or i have to buy the "correct" remote controller to get working with sonoff (wich control, wich brands, reference on aliexpress?)

Point 2, to decode im using the pair module RF receiver and transmiter and a raspberry pi 3. The thing is that i tried to decode my actual remote control using this script from this video. But it didnt worked
https://www.youtube.com/watch?v=Xe5Bj_N4Crw&t=530s
there is a way to decode the signal? im sure that they works because they open my home gate, but the receiver is not taking any signal from some buttons and other just appears different numbers.

point 3. i dont understand what means "signal timming". Its related with "pulselength"? value in miliseconds?

Thank you!

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
