### ISSUE TITLE
My 2 year old pwns my heater with a double-press

### ISSUE THREAD

**Issue by macgeeknz** [arendst/Sonoff-Tasmota#6146]
**Have you look for this feature in other issues and in the wiki?**
Ohh yes, have I what.

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._
I have a Sonoff basic with a space heater connected through the relay and using MQTT to toggle the relay. I have the built-in button decoupled from the relay by setting buttontopic to "=sunlamp" and this separate topic causes a lamp on the wall with a separate Sonoff to toggle.

In normal operation my daughter will press the button on the heater's Sonoff which turns the light on her wall on and off (not the heater). The heater itself is controlled via OpenHAB rules through MQTT, so I am managing to 'kill 2 birds with one stone'.

The problem is that she often presses the heater Sonoff's button twice in quick succession (she is only 2 years old), and this causes the internal relay to toggle, which turns the heater on. Then I come in an hour later and wonder WTF her bedroom is 30 deg C.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
I'd like to have a button multipress mode of operation which let's us send one MQTT topic for a single press and another MQTT topic for a double-press (instead of only having the option of toggling the internal relay). Ie, I'd like for there to be an option somewhere in this table which doesn't include 'toggle relay' under either column (single OR double-press):

https://github.com/arendst/Sonoff-Tasmota/wiki/Control-other-devices

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
The only alternative I've been able to come up with is having a second Sonoff unit just for her button-input and physically disabling access to the button on the first unit.

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
