### ISSUE TITLE
Sonoff seems that it is not receiving the commands, even if it's connected at MQTT

### ISSUE THREAD

**Issue by paulo9999** [arendst/Sonoff-Tasmota#615]
Hello,

I have installed MQTT and I'm monitoring the MQTT messages sent to Sonoff using mosquitto_sub in one terminal:

tasmota/sonoff-abajur/cmnd/POWER (null)
tasmota/sonoff-abajur/tele/LWT Online
tasmota/sonoff-abajur/cmnd/POWER (null)
/cmnd/tasmota/sonoff-abajur/POWER OFF   <-- this last line I've sent using mosquito_pub from other terminal. 

at SONOFF's console it appears the following

03:49:44 MQTT: tasmota/sonoff-abajur/tele/LWT = Online (retained)
03:49:44 MQTT: tasmota/sonoff-abajur/cmnd/POWER = 
03:49:54 MQTT: Attempting connection...
03:49:55 mDNS: Query done with 0 mqtt services found
03:49:55 MQTT: Connected
03:49:55 MQTT: tasmota/sonoff-abajur/tele/LWT = Online (retained)
03:49:55 MQTT: tasmota/sonoff-abajur/cmnd/POWER = 

if I publish a command to turn on of off the light, sometimes it appears the command (sometimes not) but it doesn't execute anyway. 

If I write the exact command at the console, than it will work...
Below there are the configurations at the Sonoff console:

Topic = %topic% (sonoff)
sonoff-abajur

Full Topic (%prefix%/%topic%/)
tasmota/%topic%/%prefix%/

I'd really appreciate any help!!

**Comment by arendst** [comment]
You write: 

/cmnd/tasmota/sonoff-abajur/POWER OFF   <-- this last line I've sent using mosquito_pub from other terminal.

and:

Topic = %topic% (sonoff) = sonoff-abajur
Full Topic (%prefix%/%topic%/) = tasmota/%topic%/%prefix%/

According to your configuration the device should respond to MQTT commands like
``tasmota/sonoff-abajur/cmnd/POWER off``
