### ISSUE TITLE
Send irhvac for Daikin AC

### ISSUE THREAD

**Issue by vlad-323** [arendst/Sonoff-Tasmota#6153]
Hello. I want to control my Daikin AC by irhvac or irsend command, but I can't. As I understand, that problem is in xdrv_05_irremote file. I tried to use this file: https://github.com/arendst/Sonoff-Tasmota/issues/2557#issuecomment-445367638 but firmware not compiled, I saw many errors, maybe something changes in newer versions. Can you add Daikin AC control by default ?

**Comment by ascillato2** [comment]
Hi,

This is a duplicated issue. Sorry.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
