### ISSUE TITLE
{"Command":"Unknown"}

### ISSUE THREAD

**Issue by helste64** [arendst/Sonoff-Tasmota#6158]
It is not possible for me to get running the sonoff Basic01.
Firmware = 6.6.0.1
I use MQTTBox, MQTTfx, Mosquitto on my PC, furthermore  an Raspi as a broker.

Module parameters: 
Module type (Sonoff Basic) -> Sonoff Basic(1)
all GPIOs = None (0) 

sonoff Basic01 MQTT config:

MQTT Host: 192.xxxxxx
MQTT Port: 1883
MQTT Client: sonoff-tasmota-6601
MQTT Topic: sonoff
MQTT Group Topic: sonoffs
MQTT Full Topic: sonoff/loggia/cmnd/
MQTT Fallback Topic: cmnd/sonoff-tasmota-6601_fb/

my topic is :   sonoff/loggia/cmnd/POWER or power or Power
my payload is : on, off, toogle, 0, 1, 2

It does not matter I get always the result:
20:54:03 MQT: sonoff/loggia/stat/RESULT = {"Command":"Unknown"}
and the LED flashes only once

Where cloud be my mistake?

TNX for Help

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
