### ISSUE TITLE
MQTT DS18B20 Multiple don't public payload

### ISSUE THREAD

**Issue by ppnacho** [arendst/Sonoff-Tasmota#6161]
<GUIDE>

<This troubleshooting issue template is meant to help Tasmota users with difficult problems. It is aimed to be opened if using the wiki and the support chat could not solve the issue. The Github Issue tracker is NOT a general discussion forum>
  
<Please DO NOT OPEN AN ISSUE:>
  <If you have general questions or you need help on Tasmota usage, go to the Tasmota support chat>
  <If your Tasmota version is not the latest, please update before posting. Your issue might be already solved. Latest precompiled bins of Tasmota can be downloaded from http://thehackbox.org/tasmota/>
  <If your issue is a new device, please use the Tasmota Template Feature. See wiki for that>
  <If your issue is a flashing issue, please address that to the Tasmota Support Chat>
  <If your issue is compilation problem, please address that to the Tasmota Support Chat>
  <If your issue has been addresed before (duplicated issue), please ask in the original issue>
  <If your issue is wifi problem or mqtt problem, please try first the steps provided in troubleshooting of the wiki>

### ISSUE DESCRIPTION - TROUBLESHOOTING
_A clear description of what the issue is and be as extensive as possible_
 Hi, I have seven DS18B20 in the same GPIO, seems that all it`s OK, but I've check the mqtt publish message in other mqtt client (subscribed to mqtt message) and don't receive anything. If only connect one DS18B20, all works OK, but when connect two or more sensors, the client don't receive the payload of tele/../SENSOR. I've check to publish from another client mqtt the payload and topic that I can view in the console of Tasmota software and works. I've cheked and modify some variables in Tasmota (MESSZ, MQTT_MAX_PACKET_SIZE) but don't work. Please help.
Thanks

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (i.e. Sonoff Basic) : Wemos D1 Mini_
- [x] Tasmota binary firmware version number used : 6.6.0 _ / ( self-compiled )
- [x] Development IDE - Compiler / Upload tools used : __Arduino IDE__ / _Arduino IDE___
- [x] Provide the output of command ``status 0`` :
```
STATUS 0 OUTPUT HERE:
23:04:50 CMD: status 0
23:04:50 RSL: stat/pbaja1/STATUS = {"Status":{"Module":18,"FriendlyName":["SensoresPBaja1"],"Topic":"pbaja1","ButtonTopic":"pbaja1","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
23:04:50 RSL: stat/pbaja1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"External System","Uptime":"0T00:38:15","StartupUTC":"2019-08-01T20:26:35","Sleep":50,"CfgHolder":4617,"BootCount":74,"SaveCount":173,"SaveAddress":"3F7000"}}
23:04:50 RSL: stat/pbaja1/STATUS2 = {"StatusFWR":{"Version":"6.6.0(sonoff)","BuildDateTime":"2019-08-01T22:23:57","Boot":31,"Core":"2_5_2","SDK":"2.2.1(cfd48f3)"}}
23:04:50 RSL: stat/pbaja1/STATUS3 = {"StatusLOG":{"SerialLog":3,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MIFIStation","SALON"],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","280500000100060000000000000000000000","00000000"]}}
23:04:50 RSL: stat/pbaja1/STATUS4 = {"StatusMEM":{"ProgramSize":577,"Free":2492,"Heap":24,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640C8","FlashMode":2,"Features":["00000809","0FDAE396","001783A0","22B617CD","01003BC0"]}}
23:04:50 RSL: stat/pbaja1/STATUS5 = {"StatusNET":{"Hostname":"pbaja1-6049","IPAddress":"192.168.1.40","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"80.58.61.250","Mac":"5C:CF:7F:B1:17:A1","Webserver":2,"WifiConfig":4}}
23:04:50 RSL: stat/pbaja1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.160","MqttPort":1883,"MqttClientMask":"SensoresPB","MqttClient":"SensoresPB","MqttUser":"ppnacho","MqttCount":1,"MAX_PACKET_SIZE":2000,"KEEPALIVE":30}}
23:04:50 RSL: stat/pbaja1/STATUS7 = {"StatusTIM":{"UTC":"Thu Aug 01 21:04:50 2019","Local":"Thu Aug 01 23:04:50 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+02:00","Sunrise":"06:23","Sunset":"21:29"}}
23:04:50 RSL: stat/pbaja1/STATUS10 = {"StatusSNS":{"Time":"2019-08-01T23:04:50","DS18B20-1":{"Id":"00000B0EF34B","Temperature":28.2},"DS18B20-2":{"Id":"00000B0F6CAB","Temperature":28.3},"DS18B20-3":{"Id":"00000B101AA1","Temperature":28.1},"DS18B20-4":{"Id":"00000B10C80F","Temperature":28.1},"TempUnit":"C"}}
23:04:50 RSL: stat/pbaja1/STATUS11 = {"StatusSTS":{"Time":"2019-08-01T23:04:50","Uptime":"0T00:38:15","Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":24,"Wifi":{"AP":2,"SSId":"SALON","BSSId":"A0:64:8F:4B:4A:FF","Channel":6,"RSSI":98,"LinkCount":1,"Downtime":"0T00:00:04"}}}
23:04:51 RSL: tele/pbaja1/STATE = {"Time":"2019-08-01T23:04:51","Uptime":"0T00:38:16","Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":23,"Wifi":{"AP":2,"SSId":"SALON","BSSId":"A0:64:8F:4B:4A:FF","Channel":6,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:04"}}
23:04:51 RSL: tele/pbaja1/SENSOR = {"Time":"2019-08-01T23:04:51","DS18B20-1":{"Id":"00000B0EF34B","Temperature":28.2},"DS18B20-2":{"Id":"00000B0F6CAB","Temperature":28.3},"DS18B20-3":{"Id":"00000B101AA1","Temperature":28.1},"DS18B20-4":{"Id":"00000B10C80F","Temperature":28.1},"TempUnit":"C"}

```
- [x] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:
23:05:19 CMD: weblog 4
23:05:19 MQT: stat/pbaja1/RESULT = {"WebLog":4}
23:05:20 CFG: Saved to flash at 3F6, Count 174, Bytes 3584
23:05:21 WIF: Checking connection...
23:05:21 WIF: Connected

```
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
Our ability to provide assistance is greatly hampered since you did not take a few minutes to complete the template with the requested information. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
