### ISSUE TITLE
Fixed: Support for other SonOff boards?

### ISSUE THREAD

**Issue by Blue407** [arendst/Sonoff-Tasmota#617]
I notice there are quite a few other SonOff boards, such as USB 5v or DC7v-32v 4 channel Jog inching board or 103 Gang Wifi smart wall touch light switches.

Can any of these also be re-programmed with this firmware?

**Comment by davidelang** [comment]
pretty much anything powered by the esp8266 can be supported by this firmware.

Look at the wiki for specific models

**Comment by ionciubotaru** [comment]
you can define your own boards with switches, relays, sensors, buttons
Tasmota is very flexible

**Comment by Blue407** [comment]
I didn't realise that, thanks :) :)
