### ISSUE TITLE
DimmerOnState

### ISSUE THREAD

**Issue by briansmith7** [arendst/Sonoff-Tasmota#6173]
Hello, 

I think it would be helpful to have a DimmerOnState to instruct Tasmota to reset Dimmer variable to a certain default value (e.g. 100%) every time device is powered on (similar to PowerOnState). 
Right now Dimmer is set to last known value every time the device (PS-16-DZ) is powered on. 

Maybe I am missing something, but it seems that this feature is currently missing (based on what I have seen in the Commands wiki page). 

Thank you to all the contributors for this amazing software!

**Comment by ascillato** [comment]
Hi, you can achieve that, using rules

**Comment by briansmith7** [comment]
Awesome, this solved my issue! Thank you @ascillato!

**Comment by ascillato** [comment]
Hi,

If you want, please share the rules you made for other users. Thanks.
