### ISSUE TITLE
Webserver port setting

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#618]
When I initially flashed Tasmoto 5.2.2 I changed the Webserver port in user_config.h to 2525.

After upgrading to 5.3.0 I find that the webserver port has defaulted to 80. Can I change the webserver port from the console or do I have to amend user_config.h and reflash 5.3.0 with the FTDI cable again?

**Comment by zizebra** [comment]
I think you can change the port to your desired number in the code, compile and export a new version. You then upload the new version via web. That should work.

**Comment by arendst** [comment]
Web server port is hardcoded using user_config.h

In your case you will have to recompile with your required web port as @zizebra suggested.

**Comment by Lawrencezarb** [comment]
Thanks, that worked for me
