### ISSUE TITLE
Teckin SB50 serial flashing instructions

### ISSUE THREAD

**Issue by SmartBoi89** [arendst/Sonoff-Tasmota#6187]
Hi,
this is my first post here, i hope I'm doing it right :)
I bought a Teckin SB50 RGBW light bulb and unsuccessfully tried flashing via tuya-convert. Is there a way flashing it with serial flash? I tried disassembling it, but can't find the right pins (or they aren't labeled).

Did anyone flash it via serial and could help? If needed I could provide pictures of the board as far as possible. If there is no way to flash it via serial I'd like to send it back so I don't want to rip out the board if I'm not sure it is flashable.

Thanks in advance

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
