### ISSUE TITLE
SmartReleBR

### ISSUE THREAD

**Issue by caosaquatico** [arendst/Sonoff-Tasmota#6195]
Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

**Have you looked for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is._

Read the signal from a door, I have a project that throws signal 1 for light on and 0 for light off. when I use swith it sends the signal instead of reading.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Read the door instead of throwing the signal.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Read the door instead of throwing the signal.

**Additional context**
_Add any other context or screenshots about the feature request here._

New device

**(Please, remember to close the issue when the problem has been addressed)**

https://www.youtube.com/watch?v=8GFG_AV1e7s&t=8s

**Comment by ascillato2** [comment]
For custom projects, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
