### ISSUE TITLE
Yesterday kWh Value in empty

### ISSUE THREAD

**Issue by m0rph2k** [arendst/Sonoff-Tasmota#6203]
Hello

From one day to the other the yesterday kWh value is empty. A reboot and EnergyReset2 did not help

The Sonoff adapter say 
Cannot parse data "SENSOR": _{"Time":"2019-08-10T12:29:33","ENERGY":{"TotalStartTime":"2018-11-08T21:58:48","Total":1021.36963,"Yesterday":,"Today":1.85860,"Period":0.53,"Power":197.89,"ApparentPower"

![2019_08_10_12_26_38_Sonoff_POW](https://user-images.githubusercontent.com/37833189/62820820-56e0a080-bb6a-11e9-844d-8425c421a5c4.png)

Anyone an idea to fix that ?

STATUS 0 OUTPUT HERE:

12:17:49 CMD: status 0
12:17:49 MQT: stat/Sonoff-POW-ClientXY/STATUS = {"Status":{"Module":43,"FriendlyName":["Sonoff-POW-ClientXY"],"Topic":"Sonoff-POW-ClientXY","ButtonTopic":"0","Power":1,"PowerOnState":4,"LedState":0,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
12:17:49 MQT: stat/Sonoff-POW-ClientXY/STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.ino.bin","RestartReason":"Software/System restart","Uptime":"0T17:19:46","StartupUTC":"2019-08-09T16:58:03","Sleep":0,"BootCount":135,"SaveCount":829,"SaveAddress":"FA000"}}
12:17:49 MQT: stat/Sonoff-POW-ClientXY/STATUS2 = {"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018.10.30 17:39:28","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
12:17:49 MQT: stat/Sonoff-POW-ClientXY/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["1337-2,4-Oben",""],"TelePeriod":10,"SetOption":["00008009","56918000","00000001"]}}
12:17:49 MQT: stat/Sonoff-POW-ClientXY/STATUS4 = {"StatusMEM":{"ProgramSize":490,"Free":512,"Heap":14,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3,"Features":["00000407","0FDAE794","000183A0","23B617CE","00003BC0"]}}
12:17:49 MQT: stat/Sonoff-POW-ClientXY/STATUS5 = {"StatusNET":{"Hostname":"Sonoff-POW-ClientXY","IPAddress":"192.168.0.85","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.21","Mac":"84:F3:EB:B1:D5:47","Webserver":2,"WifiConfig":5}}
12:17:49 MQT: stat/Sonoff-POW-ClientXY/STATUS6 = {"StatusMQT":{"MqttHost":"MQTTHostXY","MqttPort":1883,"MqttClientMask":"Sonoff-POW-ClientXY","MqttClient":"Sonoff-POW-ClientXY","MqttUser":"MQTTUserXY","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
12:17:50 MQT: stat/Sonoff-POW-ClientXY/STATUS7 = {"StatusTIM":{"UTC":"Sat Aug 10 10:17:49 2019","Local":"Sat Aug 10 12:17:49 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":99,"Sunrise":"06:35","Sunset":"21:15"}}
12:17:50 MQT: stat/Sonoff-POW-ClientXY/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
12:17:50 MQT: stat/Sonoff-POW-ClientXY/STATUS10 = {"StatusSNS":{"Time":"2019-08-10T12:17:50","ENERGY":{"TotalStartTime":"2018-11-08T21:58:48","Total":1021.33307,"Yesterday":,"Today":1.82207,"Power":185.75,"ApparentPower":201.23,"ReactivePower":77.40,"Factor":0.92,"Voltage":227,"Current":0.888}}}
12:17:50 MQT: stat/Sonoff-POW-ClientXY/STATUS11 = {"StatusSTS":{"Time":"2019-08-10T12:17:50","Uptime":"0T17:19:47","Vcc":3.151,"POWER":"ON","Wifi":{"AP":1,"SSId":"1337-2,4-Oben","BSSId":"78:8A:20:DA:99:D8","Channel":1,"RSSI":82}}}

Console:

12:33:13 MQT: tele/Sonoff-POW-ClientXY/SENSOR = {"Time":"2019-08-10T12:33:13","ENERGY":{"TotalStartTime":"2018-11-08T21:58:48","Total":1021.38098,"Yesterday":,"Today":1.87002,"Period":0.52,"Power":193.48,"ApparentPower":215.01,"ReactivePower":93.80,"Factor":0.90,"Voltage":228,"Current":0.942}}

**Comment by arendst** [comment]
First update your 6.3.0 version to the latest and then report again.
