### ISSUE TITLE
4CH PRO DIP switches

### ISSUE THREAD

**Issue by jobrads** [arendst/Sonoff-Tasmota#6204]
**Have you looked for this feature in other issues and in the wiki?**
YES
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
The Sonoff 4CH PRO has 2 DIP switches on the PCB, I would like to be able to use them in the Sonoff-Tasmota software (read/use the values as part of the device runtime settings).

**Describe alternatives you've considered**
I have looked in the Templates but I don't see anything related to the DIP switches

**Additional context**
Great job on the Tasmota software, and on the support and help you provide to the community of users.

**Comment by arendst** [comment]
Alas, the switches are under control of the additional microcontroller and unreachable by the esp8266 running Tasmota.

For Tasmota to function properly the switches need to be in a desired default state anyway as documented in the wiki. Features provided by the switches can be enabled within Tasmota.

Search issues and wiki.
