### ISSUE TITLE
Button on Sonoff T1 2ch not working (sonoff.bin)

### ISSUE THREAD

**Issue by GKO1** [arendst/Sonoff-Tasmota#6205]
Hello Everybody,

This is my first post and question on GitHub and I have a question.
The question is identical to the question from Joggs #5197. 

First button on Sonoff T1 2ch touch panel is not working using of sonoff.bin (6.6.0)
the first button works well from the web ui, but not if you push the button on the panel.
When pressing continuously you can hear a peep so the button is nog broken.

I don't know if I'm doing this on the right way.  Further I copied the "Solved" answer from arendst below 

--------------------------------------------------------------------------------------

arendst mentioned in the topic before (#5197
Due to the bug the settings for GPIO9 and GPIO10 ar lost. They are being used for button2 (Touch 2CH and Pros) and button3 (Touch 3CH and Pros).

What is a workaround:

Execute SetOption51 1 (enabling GPIO9 and GPIO10)
Remember current module and change current module to whatever (Rewriting GPIO9 and GPIO10 values)
Change to remembered module (Rewriting GPIO9 and GPIO10 values)
Once the fix is released execute SetOption51 0

--------------------------------------------------------------------------------------
**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X ] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [ X] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [ ] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [ ] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [ ] Device used (i.e. Sonoff Basic) : _____
- [ ] Tasmota binary firmware version number used : ____ / (pre-compiled or self-compiled ?)
- [ ] Development IDE - Compiler / Upload tools used : ____ / ____
- [ ] Provide the output of command ``status 0`` :
```

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
