### ISSUE TITLE
Disable Double Press - Decouple switch entirely from relay

### ISSUE THREAD

**Issue by pprotschka** [arendst/Sonoff-Tasmota#621]
hey there,
how would one decouple the switch from the actual relay so a double press does not actuate the relay at all.

I have defined switchmode (3), buttontopic "blabla" and protected against more than double presses with SetOption1 1.
This works great however the user still can switch the relay with a double tap. This i bad especially for lets say a door opener/door bell.

**Good**: User hits the doorbell once, server gets message and sees if its ok to open door. opens door if so.
**Bad**: impatient person hits doorbell twice fast and door opens right away ...  :/

**Comment by ionciubotaru** [comment]
try `SetOption11 1` or check [table](https://github.com/arendst/Sonoff-Tasmota/issues/200#issuecomment-306617207)
