### ISSUE TITLE
Fixed: Switchmode CMD not as expected 

### ISSUE THREAD

**Issue by pprotschka** [arendst/Sonoff-Tasmota#622]
without defined a switch in "configure module" i can not set switch mode via web console.
if you enter switchmode1 3 in the 4ch sonoff web console you will get an "unkown command" reply.
Once you set a GPIO to a switch in module parameters it works normally.
Is this a bug? or am i missing something? Some users might just want change the build in button without defining new ones...

this is has occured on my sonoff th16 and sonoff  4channel.

**Comment by davidelang** [comment]
On Thu, 20 Jul 2017, Phil Pro wrote:

> without defined a switch in "configure module" i can not set switch mode via web console.
> if you enter switchmode1 3 in the 4ch sonoff web console you will get an "unkown command" reply.
> Once you set a GPIO to a switch in module parameters it works normally.
> Is this a bug? or am i missing something? Some users might just want change the build in button without defining new ones...

No, this is not a bug, until you have a switch defined, you can't set the mode 
on it.

a switch is not a button.
