### ISSUE TITLE
BlitzWolf SHP-6 won't update OTA?

### ISSUE THREAD

**Issue by fribse** [arendst/Sonoff-Tasmota#6232]
BlitzWolf SHP6 flashed with tasmota 6.5.0 without any issues (by mistake, should have been 6.6.0).
The flashing was done by soldering wires to it, and then with serial FTDI, and before doing so, the flash was erased as recommended.

I'm trying to update it to 6.6.0.4, and I've tried both with OTA, and direct upload of the sonoff.bin
The file is uploaded, and the device reboots, and then it is still at 6.5.0

STATUS 0 OUTPUT HERE:
06:15:36 CMD: status 0
06:15:36 MQT: stat/fryserlys/STATUS = {"Status":{"Module":45,"FriendlyName":["fryserlys"],"Topic":"fryserlys","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
06:15:36 MQT: stat/fryserlys/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://http://thehackbox.org/tasmota/release/sonoff.bin:9541/data/firmwares/sonoff.bin","RestartReason":"Blocked Loop","Uptime":"0T00:08:13","StartupUTC":"2019-08-15T05:07:23","Sleep":50,"CfgHolder":4617,"BootCount":16,"SaveCount":64,"SaveAddress":"FA000"}}
06:15:36 MQT: stat/fryserlys/STATUS2 = {"StatusFWR":{"Version":"6.5.0(release-sonoff)","BuildDateTime":"2019-03-19T12:24:10","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
06:15:36 MQT: stat/fryserlys/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SSID",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
06:15:36 MQT: stat/fryserlys/STATUS4 = {"StatusMEM":{"ProgramSize":507,"Free":496,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144068","FlashMode":3,"Features":["00000809","0FDAE394","000783A0","23B617CE","00003BC0"]}}
06:15:36 MQT: stat/fryserlys/STATUS5 = {"StatusNET":{"Hostname":"fryserlys","IPAddress":"10.11.12.57","Gateway":"10.11.12.1","Subnetmask":"255.255.255.0","DNSServer":"10.11.12.28","Mac":"CC:50:E3:D4:5A:94","Webserver":2,"WifiConfig":4}}
06:15:36 MQT: stat/fryserlys/STATUS6 = {"StatusMQT":{"MqttHost":"10.11.12.33","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D45A94","MqttUser":"mqttuser","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
06:15:36 MQT: stat/fryserlys/STATUS7 = {"StatusTIM":{"UTC":"Thu Aug 15 05:15:36 2019","Local":"Thu Aug 15 06:15:36 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"05:42","Sunset":"20:06"}}
06:15:36 MQT: stat/fryserlys/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
06:15:36 MQT: stat/fryserlys/STATUS10 = {"StatusSNS":{"Time":"2019-08-15T06:15:36","ENERGY":{"TotalStartTime":"2019-08-14T17:23:00","Total":0.002,"Yesterday":0.001,"Today":0.001,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
06:15:36 MQT: stat/fryserlys/STATUS11 = {"StatusSTS":{"Time":"2019-08-15T06:15:36","Uptime":"0T00:08:13","Vcc":3.108,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":34,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SSID","BSSId":"E8:DF:70:D2:DE:3C","Channel":1,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:06"}}}
06:15:41 MQT: stat/fryserlys/STATUS = {"Status":{"Module":45,"FriendlyName":["fryserlys"],"Topic":"fryserlys","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
06:15:41 MQT: stat/fryserlys/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://http://thehackbox.org/tasmota/release/sonoff.bin:9541/data/firmwares/sonoff.bin","RestartReason":"Blocked Loop","Uptime":"0T00:08:18","StartupUTC":"2019-08-15T05:07:23","Sleep":50,"CfgHolder":4617,"BootCount":16,"SaveCount":64,"SaveAddress":"FA000"}}
06:15:41 MQT: stat/fryserlys/STATUS2 = {"StatusFWR":{"Version":"6.5.0(release-sonoff)","BuildDateTime":"2019-03-19T12:24:10","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
06:15:41 MQT: stat/fryserlys/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SSID",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
06:15:41 MQT: stat/fryserlys/STATUS4 = {"StatusMEM":{"ProgramSize":507,"Free":496,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144068","FlashMode":3,"Features":["00000809","0FDAE394","000783A0","23B617CE","00003BC0"]}}
06:15:41 MQT: stat/fryserlys/STATUS5 = {"StatusNET":{"Hostname":"fryserlys","IPAddress":"10.11.12.57","Gateway":"10.11.12.1","Subnetmask":"255.255.255.0","DNSServer":"10.11.12.28","Mac":"CC:50:E3:D4:5A:94","Webserver":2,"WifiConfig":4}}
06:15:41 MQT: stat/fryserlys/STATUS6 = {"StatusMQT":{"MqttHost":"10.11.12.33","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D45A94","MqttUser":"mqttuser","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
06:15:41 MQT: stat/fryserlys/STATUS7 = {"StatusTIM":{"UTC":"Thu Aug 15 05:15:41 2019","Local":"Thu Aug 15 06:15:41 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"05:42","Sunset":"20:06"}}
06:15:41 MQT: stat/fryserlys/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
06:15:41 MQT: stat/fryserlys/STATUS10 = {"StatusSNS":{"Time":"2019-08-15T06:15:41","ENERGY":{"TotalStartTime":"2019-08-14T17:23:00","Total":0.002,"Yesterday":0.001,"Today":0.001,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
06:15:41 MQT: stat/fryserlys/STATUS11 = {"StatusSTS":{"Time":"2019-08-15T06:15:41","Uptime":"0T00:08:18","Vcc":3.108,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SSID","BSSId":"E8:DF:70:D2:DE:3C","Channel":1,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:06"}}}
06:15:50 MQT: stat/fryserlys/STATUS = {"Status":{"Module":45,"FriendlyName":["fryserlys"],"Topic":"fryserlys","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
06:15:50 MQT: stat/fryserlys/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://http://thehackbox.org/tasmota/release/sonoff.bin:9541/data/firmwares/sonoff.bin","RestartReason":"Blocked Loop","Uptime":"0T00:08:27","StartupUTC":"2019-08-15T05:07:23","Sleep":50,"CfgHolder":4617,"BootCount":16,"SaveCount":64,"SaveAddress":"FA000"}}
06:15:50 MQT: stat/fryserlys/STATUS2 = {"StatusFWR":{"Version":"6.5.0(release-sonoff)","BuildDateTime":"2019-03-19T12:24:10","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
06:15:50 MQT: stat/fryserlys/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SSID",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
06:15:50 MQT: stat/fryserlys/STATUS4 = {"StatusMEM":{"ProgramSize":507,"Free":496,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144068","FlashMode":3,"Features":["00000809","0FDAE394","000783A0","23B617CE","00003BC0"]}}
06:15:50 MQT: stat/fryserlys/STATUS5 = {"StatusNET":{"Hostname":"fryserlys","IPAddress":"10.11.12.57","Gateway":"10.11.12.1","Subnetmask":"255.255.255.0","DNSServer":"10.11.12.28","Mac":"CC:50:E3:D4:5A:94","Webserver":2,"WifiConfig":4}}
06:15:50 MQT: stat/fryserlys/STATUS6 = {"StatusMQT":{"MqttHost":"10.11.12.33","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D45A94","MqttUser":"mqttuser","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
06:15:50 MQT: stat/fryserlys/STATUS7 = {"StatusTIM":{"UTC":"Thu Aug 15 05:15:50 2019","Local":"Thu Aug 15 06:15:50 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"05:42","Sunset":"20:06"}}
06:15:50 MQT: stat/fryserlys/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
06:15:50 MQT: stat/fryserlys/STATUS10 = {"StatusSNS":{"Time":"2019-08-15T06:15:50","ENERGY":{"TotalStartTime":"2019-08-14T17:23:00","Total":0.002,"Yesterday":0.001,"Today":0.001,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
06:15:50 MQT: stat/fryserlys/STATUS11 = {"StatusSTS":{"Time":"2019-08-15T06:15:50","Uptime":"0T00:08:27","Vcc":3.108,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SSID","BSSId":"E8:DF:70:D2:DE:3C","Channel":1,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:06"}}}
06:15:59 MQT: stat/fryserlys/STATUS = {"Status":{"Module":45,"FriendlyName":["fryserlys"],"Topic":"fryserlys","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
06:15:59 MQT: stat/fryserlys/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://http://thehackbox.org/tasmota/release/sonoff.bin:9541/data/firmwares/sonoff.bin","RestartReason":"Blocked Loop","Uptime":"0T00:08:36","StartupUTC":"2019-08-15T05:07:23","Sleep":50,"CfgHolder":4617,"BootCount":16,"SaveCount":64,"SaveAddress":"FA000"}}
06:15:59 MQT: stat/fryserlys/STATUS2 = {"StatusFWR":{"Version":"6.5.0(release-sonoff)","BuildDateTime":"2019-03-19T12:24:10","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
06:15:59 MQT: stat/fryserlys/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SSID",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100000000000000000000000000","00000000"]}}
06:15:59 MQT: stat/fryserlys/STATUS4 = {"StatusMEM":{"ProgramSize":507,"Free":496,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144068","FlashMode":3,"Features":["00000809","0FDAE394","000783A0","23B617CE","00003BC0"]}}
06:15:59 MQT: stat/fryserlys/STATUS5 = {"StatusNET":{"Hostname":"fryserlys","IPAddress":"10.11.12.57","Gateway":"10.11.12.1","Subnetmask":"255.255.255.0","DNSServer":"10.11.12.28","Mac":"CC:50:E3:D4:5A:94","Webserver":2,"WifiConfig":4}}
06:15:59 MQT: stat/fryserlys/STATUS6 = {"StatusMQT":{"MqttHost":"10.11.12.33","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D45A94","MqttUser":"mqttuser","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
06:15:59 MQT: stat/fryserlys/STATUS7 = {"StatusTIM":{"UTC":"Thu Aug 15 05:15:59 2019","Local":"Thu Aug 15 06:15:59 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"05:42","Sunset":"20:06"}}
06:15:59 MQT: stat/fryserlys/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
06:15:59 MQT: stat/fryserlys/STATUS10 = {"StatusSNS":{"Time":"2019-08-15T06:15:59","ENERGY":{"TotalStartTime":"2019-08-14T17:23:00","Total":0.002,"Yesterday":0.001,"Today":0.001,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
06:15:59 MQT: stat/fryserlys/STATUS11 = {"StatusSTS":{"Time":"2019-08-15T06:15:59","Uptime":"0T00:08:36","Vcc":3.107,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":1,"SSId":"SSID","BSSId":"E8:DF:70:D2:DE:3C","Channel":1,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:06"}}}

```
- [ ] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:

```
**(Please, remember to close the issue when the problem has been addressed)**

**Comment by fribse** [comment]
I have successfully updated with sonoff-basic binary instead of sonoff.bin
I'm not sure if that is the correct thing to do?

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
