### ISSUE TITLE
 Power Calibration after Unlug

### ISSUE THREAD

**Issue by BearTi** [arendst/Sonoff-Tasmota#6233]
Hi,

I it the Power Calibration according to the following instruction:
https://github.com/arendst/Sonoff-Tasmota/wiki/Power-monitoring-calibration

It works perfect. BUT when I unplug the socket (with Tasmota) and plug it in again, the calibration is gone. Means the power is not correct any more. I can´t automate this step, because the consumer has not a constant power consumption.

Is it possible that the calibration will be saved or something?

Thanks!

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
