### ISSUE TITLE
Subtle differences with the Hue API

### ISSUE THREAD

**Issue by suhajda3** [arendst/Sonoff-Tasmota#6238]
Hello,

I have turned on Hue Bridge emulation on my Sonoff-Tasmota 6.6.0. I thought since Alexa works great with this emulation it should work with [homebridge-hue](https://github.com/ebaauw/homebridge-hue) as well. After a lot of tries I couldn't make it work so I reported [this issue](https://github.com/ebaauw/homebridge-hue/issues/512). As it turns out Sonoff-Tasmota has some subtle differences with the Hue API.

> 1. Missing attributes from the /config, notably modelid and apiversion;
> 2. It still exposes pointsymbols in the /lights;
> 3. state is missing from the /groups resources;
> 4. The /sensors resource seems to be missing.

It would be great if Sonoff-Tasmota would be compatible with homebrdige-hue.

Thank you!

**Comment by meingraham** [comment]
@suhajda3 

There has been additional effort for the Hue emulation and lights features since 6.6.0 master was released. Please load the latest stable version of Tasmota (6.6.0.4) from http://thehackbox.org/tasmota and report back whether the issues you outlined still exist.

Thanks.

Mike

**Comment by s-hadinger** [comment]
I will take a look.

**Comment by s-hadinger** [comment]
Troubleshooting happening here: https://github.com/ebaauw/homebridge-hue/issues/512

**Comment by Krocko** [comment]
@s-hadinger is it possible for you to get the `resourcelinks` working?
So we can expose the device as outlet in homebridge-hue?

**Comment by s-hadinger** [comment]
It's already in the latest version v6.6.0.8. Please download the latest binaries.

**Comment by Krocko** [comment]
I am on v6.6.0.8 but i can't create a resourcelink.
Can you tel me, how to create a resourcelink on a Sonoff Dual R2?

**Comment by s-hadinger** [comment]
There are no plans to implement `resourcelinks`. They would require persistent storage and would impact too much the code size. This type of advanced features are better implemented at MQTT gateway level.
