### ISSUE TITLE
Support Albohes PC-1606 Outdoor Plug

### ISSUE THREAD

**Issue by arzaman** [arendst/Sonoff-Tasmota#6239]
Hi

need to control via tasmota a dual plug for **OUTDOOR** usage
my choice was for Albohes PC-1606, very well done, robust waterproof with tactlile switch

![image](https://user-images.githubusercontent.com/6697518/63129430-cb2aa200-bfb7-11e9-918f-cdc261fd4c24.png)

I try to upgrade via Tuya-Convert with no success so I decide to open it and flash the firmware but not sure about the TX/RX/GPIO0 mapping on the ESP8285  (Vcc and GND are marked)

any one can help me in finding the PINout ?

![image](https://user-images.githubusercontent.com/6697518/63129670-76d3f200-bfb8-11e9-94c2-78634bb72d52.png)

![image](https://user-images.githubusercontent.com/6697518/63129692-85220e00-bfb8-11e9-92af-a2019a9b4653.png)

![image](https://user-images.githubusercontent.com/6697518/63129714-93702a00-bfb8-11e9-8e44-210f94a20b15.png)

any alternative dual plug for outdoor (Easy to disassemble or compatible with OTA upgrade)

thanks
Davide

**Comment by thxthx0** [comment]
maybe this will help:
https://blakadder.github.io/templates/albohes-pc-1606.html
https://forum.creationx.de/forum/index.php?thread/1767-albohes-sp-1606/

**Comment by ascillato2** [comment]
Closing this issue as the device requested is already supported by Tasmota. 

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by arzaman** [comment]
I know that the template and support for this outdoor switch is OK but still don't know what are the PIN for flashing ESP8285

does anyone has idea of the TX/RX/GPIO0 poistion for this device ?

thanks
Davide

**Comment by arzaman** [comment]
Anyone has idea where are the PIN for flashing tasmota on this device ?
it's supported as a template so I expect that someone has flashed it

thanks
Davide

**Comment by meingraham** [comment]
@arzaman It may have been flashed with Tuya-Convert. Give that a try first... but that may no longer work.

**Comment by psi-4ward** [comment]
Anyone had success flashing this device? Its flagged supported but I cant get it work with SonOTA or Tuya-Convert

**Comment by ronny130286** [comment]
Hello, i have problem with the same plug, but i cant flash ist via tuya-convert.
I thing its a problem with the orgi firmeware on plug.

The plug create an AP with IP 10.10.7.1 (in pairing mode) so that the tuja convert cant find it.
Is there a soloution for it?

Thx for Help :)
