### ISSUE TITLE
Fixed: Power state not being saved

### ISSUE THREAD

**Issue by maxdamage2122** [arendst/Sonoff-Tasmota#624]
Not sure if this is a setup issue or a bug.
I have a sonoff basic setup with mqtt and using home assistant. If I toggle the sonoff via HA and reboot it through the webserver, it boots back up in the correct previous power state. But if I toggle the sonoff via the webserver or through a wired switch and reboot it then it boots back up with the previous state set by HA.

**Comment by davidelang** [comment]
read the poweron state page of the wiki

https://github.com/arendst/Sonoff-Tasmota/wiki/PowerOnState-Configuration

**Comment by maxdamage2122** [comment]
I had already read that page but I think I found my issue. With switchtopic on, the topic uses POWER1 and in my HA config I was using POWER. Switching my HA config to use POWER1 seems to have fixed the issue.
