### ISSUE TITLE
SONOFF T4EU1C - 1 Gang EU Wi-Fi Smart Single Wire Wall Switch

### ISSUE THREAD

**Issue by FVM00** [arendst/Sonoff-Tasmota#6248]
https://www.itead.cc/sonoff-t4eu1c-wi-fi-smart-single-wire-wall-switch.html

Anybody already seen this device?
Is it ESP8266 based and flasable?
Very exited and curious. Living in an old house with very strange wiring, So have not been able to route an extra wire

![T4EU1C_11](https://user-images.githubusercontent.com/51421883/63208885-5f8d2580-c0da-11e9-959b-e8a008298c34.jpg)

**Comment by ascillato2** [comment]
It is already supported.

If you need further assistant, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by AS137430** [comment]
1. Scanned the development changelog and commits. Nothing on Sonoff T4EU1C.
2. Nothing on templates for this model as well.
3. Nothing in issues as well.

@ascillato2: Why did you say this Sonoff model is supported? This product was released in August only.

**Comment by effinG123** [comment]
I'm interested in this also!  Agreed can't find info on this device as it has only just been released.

**Comment by arendst** [comment]
This device is new indeed.

I expect that module 28 (Sonoff T1 1CH) will do the job just fine. Let me know if it doesn't.

**Comment by effinG123** [comment]
Will do.  Thanks...It's on order now.

**Comment by FVM00** [comment]
Still looking for (extra) GPIO0 spot :-) .


![20190901_191629 1](https://user-images.githubusercontent.com/51421883/64080017-64172800-ccef-11e9-9d95-ef53f070737b.jpg)
![20190901_191653 1](https://user-images.githubusercontent.com/51421883/64080029-7d1fd900-ccef-11e9-9551-3713c2372762.jpg)
![20190901_192850 1](https://user-images.githubusercontent.com/51421883/64080042-a17bb580-ccef-11e9-8e87-1def0160486b.jpg)

**Comment by arendst** [comment]
Looking at the small amount of logic AND the fact that the device doesn't need both power connections it might well be that Tasmota won't work because it uses a lot of cpu resources.

From the pictures it seems the push button is connected to GPIO0 via the additional microcontroller.

Once you're able to flash I suggest you make a backup first.

**Comment by Hellcube** [comment]
So how can i put this into flashing mode?

**Comment by MCrissDev** [comment]
I am interested in this too :)

**Comment by FVM00** [comment]
Tried to find a connection for GPIO0, but did not find anything on the board. 
Gave up hope and tried to connect directly on the chip.
This worked, flashing mode was enabled (WiFi led not blinking)
Flashing Tasmota without a problem.
Operates also exactly the same as T1.

Currently operating with Homey through MQTT 😁😁😁

**Comment by SelcouthGuy** [comment]
@FVM00 thank you very much for this information.
 Please inform us if you find any abnormalities/inconvenience. I'm very interested.

**Comment by Hellcube** [comment]
![pin0](https://user-images.githubusercontent.com/4286625/64677613-314ffb00-d478-11e9-800a-5f86d9d5716c.png)
Is this pin you are referring to?

**Comment by meingraham** [comment]
@Hellcube 

In the diagram, yes. In the photo, no.

Note in the diagram the black dot in the corner of pin 1 & pin 33. The dot is also on the physical chip itself. It tells you were pin 1 is. The GPIO0 pin is actually in the diagonally opposite corner in the photo from what you indicated.

**Comment by arendst** [comment]
@meingraham I think you're wrong. Both picture and diagram are correct. Remember, you turned the picture upside down.

**Comment by meingraham** [comment]
Or likely I'm blind and need glasses :wink:. That looked like a dot in the photo.

Nevertheless, @Hellcube orient using the dot.

**Comment by arendst** [comment]
There's also the dot on the PCA next to the almost invisible dot on the chip :-)

**Comment by FVM00** [comment]
![2019-09-11-20-56-46-541 1](https://user-images.githubusercontent.com/51421883/64726963-085f5280-d4d8-11e9-8735-1d22b9e29b42.jpg)
I made a new, better, photo. Now you can see clearly the marking spot on the chip and on the board :smiley:

**Comment by arendst** [comment]
I think R10 on the flip side is connected to GPIO00 too. So it may be easier to wire it up there.

**Comment by Hellcube** [comment]
R10 works. Sucesfully flashed. I have a problem with the relay, it switches on and off all the time when pluged in main power (not from serial adapter).

**Comment by Snipercaine** [comment]
I'm in on this too.   
I got it flashed with R10 as my GPIO-0 connection.  I'm not getting a relay toggle with the cap-touch button.  I had the relay toggle working via the UI with the Module as Sonoff Basic, but not the cap-touch switch.

**Comment by effelle** [comment]
I had a look to the board, since @Snipercaine jump on our channel to get some info. Looking at the pic I have, seems GPIO0 is the one controlling the touch, but passing trough the MCU (U2).
Is an SOT23-6, Touch I/O Flash MCU model BS83A02A-4.
ON Pin2 (VSS) is connected GPIO0 trough R10 and on Pin5 (PA1/KEY1) there is the touch out.

**Comment by mB-PiBox** [comment]
Is the diagram in the Original Post accurate? It indicates a (N) Neutral Wire, but this switch doesn't require one.

**Comment by jonoxer** [comment]
> It indicates a (N) Neutral Wire, but this switch doesn't require one.

Neutral is still required to the load, it just doesn't need to go to the switch. The diagram is correct.

**Comment by mB-PiBox** [comment]
> > It indicates a (N) Neutral Wire, but this switch doesn't require one.
> 
> Neutral is still required to the load, it just doesn't need to go to the switch. The diagram is correct.

Except in the diagram, it has the "Out" connection of the Switch connected to the (N) Natural Wire.

**Comment by d4vew557** [comment]
The out looks to be connected to the live side of the bulb and then the neutral to the other side of the bulb to me, then the anti flicker module connected across both.

**Comment by mB-PiBox** [comment]
> The out looks to be connected to the live side of the bulb and then the neutral to the other side of the bulb to me, then the anti flicker module connected across both.

Oi, you're right.. dumba$$ me didn't take notice of the circle/X representing the bulb.

**Comment by jonoxer** [comment]
I've done a description of how this board works, and the process that I found to be successful for installing Tasmota. Some of it is documented in the video, some is on the page: https://www.superhouse.tv/34-science-or-sorcery-sonoff-t4eu1c-no-neutral-wifi-touch-switch/

**Comment by nolimitek** [comment]
There must be a problem with tasmota because esphome works fine flashed on the"normal" way

**Comment by effelle** [comment]
And we are aware of it. The problem is being investigated.

**Comment by nolimitek** [comment]
Thats fine. Hope you find the problem. Love tasmota on the sonoff units

**Comment by s-hadinger** [comment]
Quick question for current users. Is this device immune to Ghost switching? Thx

**Comment by effelle** [comment]
@s-hadinger I'm not sure. 
As for now we tested three units, each one showed different behavior:

- One refuses to flash without using `reset` pin to enter in program mode and flashed successfully just using 74880bps .
- A Second one was flashed as any other ESP but didn't sense the touch button until an additional resistor was added on R10.
- A third one was flashed as any other ESP and works just fine. 

As you can imagine is hard to reply until we get more units with Tasmota on board. 
Seems on EspHome this particular model is working just fine out of the box. 
My fear is we are facing a power issue here: @jonoxer told me the stock firmware was draining about 70-80mA and will test the actual draining under Tasmota. Until then can't say what's going on.

**Comment by vampik** [comment]
Successfully flashed without any difficulties. Used R10 as a connection point for GPIO0. Additional GND for easy connection is available at some of J2 pins. Switch works just fine with a couple of fluorescent bulbs and the anti flicker module.

**Comment by effelle** [comment]
@vampik thanks for your feedback. 
What is your Voltage configuration? 110v/220v? 50/60Hz?

**Comment by vampik** [comment]
> What is your Voltage configuration? 110v/220v? 50/60Hz?
220V 50Hz.
> And what `.bin` you flashed?
I flashed sonoff.bin.

**Comment by moccajava** [comment]
Hi guys,

Timely this came out. So my home wiring does not have a N to the switch and I find it next to impossible to run the lines.

So I do have the Sonoff T1 UK switches. Will the anti-flicker module work with this? And can I make my own anti-flicker module? Any help on how to make that will save me the trouble and hassle of snake wiring all my points.

Thanks guys.

**Comment by vzorglub** [comment]
No the T1 will not work without neutral. With on without the anti flicker device. See @jonoxer video above

**Comment by nolimitek** [comment]
Any news for this device ?

**Comment by meingraham** [comment]
Yes. Google it and Tasmota. Several successful outcomes.

**Comment by nolimitek** [comment]
Can you send me a link. I read everywhere that after tasmota is flashed the Hardware button is not working anymore

**Comment by meingraham** [comment]
https://www.youtube.com/watch?v=4f34SPqP4-A
https://www.youtube.com/watch?v=VNYcD7MEp4A
https://www.youtube.com/watch?v=_q96xx9sZ8o

**Comment by nolimitek** [comment]
The first link Hardware Button does not Work
Second link to strong way not doable for me.
Third link if you read the comments the hardware button does not work.

**Comment by meingraham** [comment]
Them's your choices at this time.

**Comment by nolimitek** [comment]
FYI:
Flashed three T4EU1C with an older sonoff.bin from februar 2019 and all works. After flashing it does not work, But after setting up the wifi and set the device to T1 alls is working fine

**Comment by Hellcube** [comment]
Tried new version v6.7.1 does not work. Can You provide me the link to that firmware from february? i will test it...

**Comment by nolimitek** [comment]
What exactly does not work?

**Comment by Hellcube** [comment]
same deal. When pluged

> R10 works. Sucesfully flashed. I have a problem with the relay, it switches on and off all the time when pluged in main power (not from serial adapter).

**Comment by Hellcube** [comment]
> R10 works. Sucesfully flashed. I have a problem with the relay, it switches on and off all the time when pluged in main power (not from serial adapter).

**Comment by nolimitek** [comment]
> > R10 works. Sucesfully flashed. I have a problem with the relay, it switches on and off all the time when pluged in main power (not from serial adapter).

Do you have attached the anti flicker module ?

**Comment by Hellcube** [comment]
> > > R10 works. Sucesfully flashed. I have a problem with the relay, it switches on and off all the time when pluged in main power (not from serial adapter).
> 
> Do you have attached the anti flicker module ?

I did not flicker module fixed it. Thanks.

**Comment by ivohulsman** [comment]
For everyone with a working Tasmota flash but without the actual button working, I replaced R10 with a 1K resistor and everything works fine on my end now.

**Comment by donseelim** [comment]
I made a video on how to flash this for those who need it.  https://www.youtube.com/watch?v=RNQXRko5mPU

**Comment by kreso975** [comment]
@donseelim Thanks a lot!! :) :) Very easy and fast. 
note: tried with DIO (not working) , DOUT works like a charm. Flash it with my code including SPIFFS.

**Comment by donseelim** [comment]
> @donseelim Thanks a lot!! :) :) Very easy and fast.
> note: tried with DIO (not working) , DOUT works like a charm. Flash it with my code including SPIFFS.

You are welcome. Great to know my video helped!

**Comment by askrejans** [comment]
Flashed successfully with 8.1.0 version straight after unpacking through the R10 resistor. All worked right away with no modifications, touch button and everything. T1 config preset works fine. Wifi led was blinking all the time, but that could be disabled through the normal config options. Ordered two more, will check if its the same with those.

**Comment by meingraham** [comment]
@askrejans 

Link LED blinking is either Wi-Fi (probably not your case) or MQTT not connected. If the latter and you don't use MQTT, you can disable it (`SetOption3 0`).

**Comment by vwtune** [comment]
I managed to flash the T4eu with tasmota 8.1.0 but after flashing, the touch is not responding very good, i have to press hard and/ ore multiple times. Over mqtt it is switching instantly. Before flashing it was just fine. What to do?

**Comment by JulesBousema** [comment]
Does anyone know if two of the t4eu1c in a row will work? As in the live out from the first goes to the live in from the second? Im worried about enough power being aviable.

**Comment by pmknowles** [comment]
@JulesBousema I would say almost certainly not. The first one being switched off would restrict the current to the next. I presume this is for a 2 way switch.  If so you could try using the 'spare' wire (in UK it's yellow) from the output of the first switch to the output of the second and then connect the live feed (UK red or brown) to the L of both switches.

**Comment by galsalman** [comment]
Is there a json config available ?

**Comment by pmknowles** [comment]
If you mean a template - have a look on the Template pages. It's a standard module so you should be able just to select it in Module Configuration - there's no need to use a template

**Comment by galsalman** [comment]
Sorry my mistake it’s part of haa flash not Tasmota

**Comment by JulesBousema** [comment]
Does anyone know if theres a spot where I could pull 5v for a sensor id like to connect to the t4eu1c?

**Comment by pmknowles** [comment]
________________________________
I think these are 3.3V only on the 'smart' PCB. On the Tuya devices the relays are 5V so it may be available from the relay board (or near the header on the smart PCB).

Regards

Phil K
