### ISSUE TITLE
Sonoff Basic R3 no SSID after flashing

### ISSUE THREAD

**Issue by Tenere-750** [arendst/Sonoff-Tasmota#6251]
Good afternoon,

I just flashed a Sonoff Basic R3 according to the Wiki article "Sonoff DIY".

After sucessful flashing (I used the sonoff-classic binary) and restarting the device there's no sonoff-xxxx SSID to be found. The Blue LED is blinking and that's all...

Does anyone has any idea what could have happened and how do I reset the device?

Seems I have to flash the device the "hard" way (soldering pins). Or is there any other things I can try?

Regards,

Joerg

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
