### ISSUE TITLE
HUE emulator problem

### ISSUE THREAD

**Issue by ihavenonick** [arendst/Sonoff-Tasmota#6255]
Alexa responds that the device does not respond, but switches the device properly.
The problem occurs with the Sonoff IFAN2. I have no other devices with the HUE EMU.

**Comment by coredump80** [comment]
Hi, 
i have the same problem with Tasmota 6.6.0.5 on a Sonoff T1 and S20. The older version 6.6.0.3 works fine.

**Comment by s-hadinger** [comment]
There has been a change to get rid of the Dimmer for pure switches. You need to remove the device from Alexa and discover it again. It will be then classified as pure switch. 

By the way what Alexa devices do you have?

**Comment by ihavenonick** [comment]
ok it works
