### ISSUE TITLE
trouble with irsend command for GREE AC

### ISSUE THREAD

**Issue by mcsa2003** [arendst/Sonoff-Tasmota#6261]
I try to send ir command to on/off AC.
I have AC cooper&hunter. I use IRrecvDumpV2 to scan code:
`Timestamp : 000272.167
Encoding  : GREE
Code      : 39076050002000C0 (64 bits)
Mesg Desc.: Model: 1 (YAW1F), Power: On, Mode: 1 (COOL), Temp: 23C, Fan: 3 (High), Turbo: Off, IFeel: Off, WiFi: Off, XFan: Off, Light: On, Sleep: Off, Swing Vertical Mode: Manual, Swing Vertical Pos: 0 (Last Pos), Timer: Off
Library   : v2.6.4

Raw Timing[139]:
   +  8968, -  4464,    +   644, -  1644,    +   644, -   552,    +   644, -   554, 
   +   644, -  1642,    +   644, -  1644,    +   644, -  1646,    +   642, -   554, 
   +   642, -   554,    +   644, -  1644,    +   644, -  1644,    +   644, -  1646, 
   +   642, -   554,    +   644, -   552,    +   644, -   552,    +   644, -   552, 
   +   644, -   554,    +   644, -   552,    +   644, -   554,    +   644, -   554, 
   +   644, -   552,    +   644, -   554,    +   642, -  1646,    +   642, -  1644, 
   +   644, -   554,    +   644, -   552,    +   644, -   552,    +   644, -   554, 
   +   644, -   554,    +   644, -  1644,    +   644, -   554,    +   644, -  1644, 
   +   644, -   554,    +   642, -   554,    +   644, -  1644,    +   644, -   552, 
   +   642, - 19904,    +   644, -   554,    +   644, -   554,    +   642, -   554, 
   +   644, -   552,    +   644, -   554,    +   644, -   554,    +   644, -   554, 
   +   644, -   552,    +   644, -   554,    +   644, -   554,    +   644, -   554, 
   +   644, -   554,    +   644, -   552,    +   644, -  1644,    +   644, -   554, 
   +   644, -   552,    +   644, -   552,    +   644, -   554,    +   644, -   554, 
   +   644, -   554,    +   644, -   554,    +   644, -   552,    +   644, -   552, 
   +   644, -   552,    +   644, -   552,    +   644, -   552,    +   646, -   552, 
   +   644, -   552,    +   646, -   552,    +   642, -   554,    +   644, -  1644, 
   +   644, -  1644,    +   644

uint16_t rawData[139] = {8968, 4464,  644, 1644,  644, 552,  644, 554,  644, 1642,  644, 1644,  644, 1646,  642, 554,  642, 554,  644, 1644,  644, 1644,  644, 1646,  642, 554,  644, 552,  644, 552,  644, 552,  644, 554,  644, 552,  644, 554,  644, 554,  644, 552,  644, 554,  642, 1646,  642, 1644,  644, 554,  644, 552,  644, 552,  644, 554,  644, 554,  644, 1644,  644, 554,  644, 1644,  644, 554,  642, 554,  644, 1644,  644, 552,  642, 19904,  644, 554,  644, 554,  642, 554,  644, 552,  644, 554,  644, 554,  644, 554,  644, 552,  644, 554,  644, 554,  644, 554,  644, 554,  644, 552,  644, 1644,  644, 554,  644, 552,  644, 552,  644, 554,  644, 554,  644, 554,  644, 554,  644, 552,  644, 552,  644, 552,  644, 552,  644, 552,  646, 552,  644, 552,  646, 552,  642, 554,  644, 1644,  644, 1644,  644};  // GREE
uint8_t state[8] = {0x39, 0x07, 0x60, 0x50, 0x00, 0x20, 0x00, 0xC0};`

I try to send command
`18:55:42 CMD: irsend "Protocol":"GREE","Bits":64,"Data":"0x39076050002000C0"
18:55:42 RSL: stat/sonoff1/RESULT = {"IRSend":"Invalid RawData"}`

Also I cant sent command in RAW
`irsend 0,8968,4464,644,1644,644,552,644,554,644,1642,644,1644,644,1646,642,554,642,554,644,1644,644,1644,644,1646,642,554,644,552,644,552,644,552,644,554,644,552,644,554,644,554,644,552,644,554,642,1646,642,1644,644,554,644,552,644,552,644,554,644,554,644,1644,644,554,644,1644,644,554,642,554,644,1644,644,552,642,19904,644,554,644,554,642,554,644,552,644,554,644,554,644,554,644,552,644,554,644,554,644,554,644,554,644,552,644,1644,644,554,644,552,644,552,644,554,644,554,644,554,644,554,644,552,644,552,644,552,644,552,644,552,646,552,644,552,646,552,642,554,644,1644,644,1644,644`
After that I dont get any message in console

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
