### ISSUE TITLE
MagicHome MQTT Sometimes not responding

### ISSUE THREAD

**Issue by davidkrammer** [arendst/Sonoff-Tasmota#6263]
### BUG DESCRIPTION
Using several MagicHome LED Controller with the latest Tasmota on it. When i type some Color command in the commandline of the tasmota webinterface everything working fine. But when i am using MQTT, the ledcontroller sometimes never receive the command. Example i have 4 controller with tasmota on the same mqtt topic. And when i power them all (all at once using the one topic) they do not turn all at once. Some turn on some not.. i have to send commands sometimes up to about 100times till everything is on or on a specific color.. using different topics does nlt work too.. "fixed" the turning on using hue emulation.. but color changing would be cool to use too..   I am using openHAB in case this is important.

### REQUESTED INFORMATION
- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (i.e. Sonoff Basic) : ___MagicHome LED Controller__
- [x] Tasmota binary firmware version number used : __6.6.0_pre-compiled_ / (pre-compiled or self-compiled ?)
- [x] Development IDE - Compiler / Upload tools used : __NodeMCU Flasher__ / ____
- [x] Provide the output of command ``status 0`` :
```
00:01:05 RSL: stat/wifiled_1/STATUS = {"Status":{"Module":0,"FriendlyName":["LED Controller"],"Topic":"wifiled_1","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
00:01:05 RSL: stat/wifiled_1/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-DE.bin","RestartReason":"External System","Uptime":"0T00:01:04","StartupUTC":"","Sleep":50,"CfgHolder":4617,"BootCount":64,"SaveCount":378,"SaveAddress":"FA000"}}
00:01:05 RSL: stat/wifiled_1/STATUS2 = {"StatusFWR":{"Version":"6.6.0(release-sonoff)","BuildDateTime":"2019.07.06 13:17:19","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
00:01:05 RSL: stat/wifiled_1/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Krammer 2.4GHz",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100060000000000000000000000","00000000"]}}
00:01:05 RSL: stat/wifiled_1/STATUS4 = {"StatusMEM":{"ProgramSize":504,"Free":496,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000407","0FDAE396","001783A0","22B617CD","01003BC0"]}}
00:01:05 RSL: stat/wifiled_1/STATUS5 = {"StatusNET":{"Hostname":"WifiLED_1","IPAddress":"192.168.1.166","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"C4:4F:33:A3:8B:C4","Webserver":2,"WifiConfig":4}}
00:01:05 RSL: stat/wifiled_1/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.3","MqttPort":1883,"MqttClientMask":"admin","MqttClient":"admin","MqttUser":"admin","MqttCount":59,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
00:01:05 RSL: stat/wifiled_1/STATUS7 = {"StatusTIM":{"UTC":"Thu Jan 01 00:01:05 1970","Local":"Thu Jan 01 00:01:05 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":"+00:00","Sunrise":"07:43","Sunset":"16:03"}}
00:01:05 RSL: stat/wifiled_1/STATUS10 = {"StatusSNS":{"Time":"1970-01-01T00:01:05"}}
00:01:05 RSL: stat/wifiled_1/STATUS11 = {"StatusSTS":{"Time":"1970-01-01T00:01:05","Uptime":"0T00:01:04","Heap":14,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":973,"POWER":"ON","Dimmer":100,"Color":"FF0900","HSBColor":"2,100,100","Channel":[100,4,0],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"Krammer 2.4GHz","BSSId":"0C:9D:92:B0:AD:28","Channel":13,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:04"}}}



```
- [x] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
00:03:05 CMD: weblog 4
00:03:05 SRC: WebConsole from 192.168.1.117
00:03:05 RSL: empfangenes topic /weblog, Datengröße 1, Daten 4
00:03:05 RSL: Gruppe 0, Index 1, Befehl WEBLOG, Daten 4
00:03:05 RSL: stat/wifiled_1/RESULT = {"WebLog":4}
00:03:05 MQT: Verbindungsversuch...
00:03:05 MQT: verbunden
00:03:05 MQT: tele/wifiled_1/LWT = Online (beibehalten)
00:03:05 MQT: cmnd/wifiled_1/POWER = 
00:03:05 MQT: abonniere cmnd/wifiled_1/#
00:03:05 MQT: abonniere cmnd/sonoffs/#
00:03:05 MQT: abonniere cmnd/admin_fb/#
00:03:06 MQT: Verbindungsversuch...
00:03:06 MQT: verbunden


```

### TO REPRODUCE
Use MagicHome and send mqtt commands..

### EXPECTED BEHAVIOUR
Instant Color Changing on all Devices

### SCREENSHOTS
--

### ADDITIONAL CONTEXT
--

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
Every device needs a UNIQUE (different) topic!

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
