### ISSUE TITLE
Magnetschalter an Sonoff RF R2 V1.0 (neue Version)

### ISSUE THREAD

**Issue by FabianJECC** [arendst/Sonoff-Tasmota#6276]
Hallo,
da ja im November 2018 der neue Sonoff mit anderem Platinenlayout auf den Markt kam, haben sich ein paar Sachen bezüglich der GPIO-Pin's getan.

Der PIN Key hat nichts mit GPIO14 zu tun, ist nämlich GPIO0 und liegt auch am Taster.
GPIO2 (ist IO3, findet man neben 3V3) hat die gleichen Funktionen wie GPIO14
WICHTIG: Der GPIO2 darf beim booten nicht auf GND liegen, sonst startet wer nicht! (Also eher für Taster und nicht für Magnetkontakte geeignet)
RX habe ich noch nicht getestet, hier setze ich auf Eure Erfahrungen 🙂 (Seriell-Logg Level auf "0" stellen)
Stelle ich als Gerätetyp "Generic" ein, kann ich alle GPIO's konfigurieren.

Das ist das wichtigste was ich bis jetzt aus mehreren Foren herausgefunden habe. Dort wurde versucht ein Schalter/Taster am Sonoff anzubringen um das Relais zu steuern.

Mein Ziel ist es, einen Magnetschalter am Sonoff anzubringen, der mir NICHT das Relais schaltet, sondern einen Wert im ioBroker zurückgibt. Der Einsatzbereich hier beläuft sich auf eine Garagentorsteuerung. Den Sonoff habe ich bereits umgebaut, dass er als Schalter dient (Gleiches Prinzip, wie wenn man einen Tastschalter an den Garagentormotor hängt).

Meine Frage: Wie und Wo muss/kann ich meinen Magnetkontakt anschließen, sodass der Sonoff auch bootet, wenn der Schalter geschlossen ist. (Garagentor ZU = Magnetkontakt geschlossen)
Wie müsste die Konfiguration im Webinterface vom Sonoff Tasmota der GPIO-Pin's aussehen? (Ja, Tasmota ist drauf)

Vielen dank im Voraus!

**Comment by Jason2866** [comment]
Bitte stelle diese Frage im im [Tasmota Support Chat](https://discord.gg/Ks2Kzd4).
GitHub is für Fehlermeldungen in der Software selbst!
Desweiteren sind Einträge hier ausschließlich in Englisch!
Danke! 

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
