### ISSUE TITLE
Lost wifi connection and turn off sonoff

### ISSUE THREAD

**Issue by silverricardo** [arendst/Sonoff-Tasmota#6278]
Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

**Have you looked for this feature in other issues and in the wiki?**
Yes.

**Is your feature request related to a problem? Please describe.**
I need to know if is possible, when the sonoff lost wifi connection, can be automatically turned off and when the wifi connection come back turn on again.

**Describe the solution you'd like**
I need to know if there is any function to be able to do this control

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
Hi,

This feature is already supported using rules.

Go to the Tasmota console and type:

```
rule1 1
rule1 on Wifi#Disconnected do power1 0 endon on Wifi#Connected do power1 1 endon
```

If you need further assistance, remember that you can use the Tasmota Support Chat.

Thanks.
