### ISSUE TITLE
5 independent PWM channels

### ISSUE THREAD

**Issue by podarok** [arendst/Sonoff-Tasmota#6289]
Hi.
Is there any chance to control 5 pwm channels independently?
I tried to set Generic template but web ui still shows 2 sliders for color/brightness

Thanks in advance

**Comment by meingraham** [comment]
This? https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#Setoption68

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
