### ISSUE TITLE
Is it possible to Assign Command Result to Variable?

### ISSUE THREAD

**Issue by windischb** [arendst/Sonoff-Tasmota#6291]
Hi!
Is it possible to assign the result from a Command to a variable?
I would like to toggle the FanSpeed of in iFan03 on double press.
If FanSpeed is 0 set FanSpeed to 2, if Fanspeed other than 0 set FanSpeed to 0.

Rule1
on button1#state=2 var1 FanSpeed endon
on var1#state=0 FanSpeed 2 endon
on var1#state!=0 FanSpeed 0 endon

**Comment by ascillato** [comment]
Sorry, not supported.

What is the behaviour you want to achieve?

**Comment by windischb** [comment]
As i wrote above, i'll try to toggle the FanSpeed of an iFan03.

If the Fan is on (FanSpeed != 0) turn of the Fan.
If the Fan is off (FanSpeed == 0) turn the Fan on at Speed 2.

But for that i have the check the current value of Fanspeed...

In Javascript i would wrote something like that:
```Javascript
var currentFanSpeed = Fanspeed;
if (currentFanSpeed == 0) {
    FanSpeed 2;
} else {
    FanSpeed 0;
}
```

**Comment by windischb** [comment]
Maybe the only possible solution is to compile with Scripting Feature...?

**Comment by laurentdong** [comment]
@windischb You can try to use MQTT subscribe a topic and catch the value with RULE.

**Comment by richcarnell** [comment]
@windischb 
Did you have any luck with this?
