### ISSUE TITLE
Windows 10 Tasmota Device Manager - config crashed TDM

### ISSUE THREAD

**Issue by scargill** [arendst/Sonoff-Tasmota#6293]
I have what I think is up to date TDM - 0.1.20 - running on Windows 10 64 bit - the Raspberry Pi 3 running Buster and Mosquitto is handling my Tasmota'd Sonoff BASICs (6.6.0) is running fine, 24-7. I can use TDM to turn the devices on and off very reliably, but if I hit either the top CONFIGURE or individual item CONFIGURE options in TDM, ultimately TDM crashes within seconds.

Pete

**Comment by meingraham** [comment]
@scargill Pete,

TDM is a "related" project to Tasmota. Support for TDM can be obtained from @jziolkowski through his GitHub project. A newer version is under development. It is available at https://github.com/jziolkowski/tdm/tree/development. However, it is a work in progress and the Configure capability may not yet be fully fleshed out.

As your post is not a Tasmota bug or feature request, direct your questions to the TDM GitHub and please close this issue.

Mike

**Comment by ascillato2** [comment]
Closing this issue as it is not Tasmota Software issue. Please, address this on TDM repository. Thanks

**Comment by scargill** [comment]
Sorry - wrong forum, thanks for feedback.
