### ISSUE TITLE
Potential memory leak!

### ISSUE THREAD

**Issue by tam481** [arendst/Sonoff-Tasmota#63]
Hi Theo,
Since moving from the old firmware to the new Tasmota, I've noticed that amount of free memory on the Sonoff drops down to 17KB from 28KB. I've tried erasing "Reset 2" and trying again but it still continues to happen. Is this normal behaviour? If not, is anyone else affected?

**Comment by arendst** [comment]
It's normal as long as you have weblog enabled; 60 lines are stored in core and depending on the amount of characters on a line it needs a lot of memory.

Disable weblog, restart and memory should not drop below 20k. It needs a restart as current lines still occupy core.
