### ISSUE TITLE
Is there any 868 MHz radio support (TX)?

### ISSUE THREAD

**Issue by maximevince** [arendst/Sonoff-Tasmota#6321]
**Have you looked for this feature in other issues and in the wiki?**
Yes

**Is your feature request related to a problem? Please describe.**
I'd like to be able to transmit 868 MHz packets, like I can at 433 using the Sonoff RF bridge with Tasmota firmware. 

**Describe the solution you'd like**
If there are any supported devices, where can I find them. If not, I am willing to integrate one, e.g. a CC1101 over SPI. Some pointers to get me started on how to integrate / interface with Tasmota would be appreciated.

**Describe alternatives you've considered**
Not sure. I'd like to integrate it with one of my existing ESP-based Tasmota devices (RF bridge, Sonoff S26, NodeMCU ...)

Many thanks!

**Comment by meingraham** [comment]
@maximevince 

Use this as a coding guide - https://github.com/arendst/Sonoff-Tasmota/wiki/Sensor-API

You can use the other sensor drivers (xsns---.ino) as examples. Just adapt the CC1101 protocols per the module's data sheet.

**Comment by Jason2866** [comment]
@maximevince  Take a look in Gemu Tasmota fork. He has already a driver for cc1101
https://github.com/gemu2015/Sonoff-Tasmota/blob/universal7/sonoff/xsns_97_moritz.ino

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
