### ISSUE TITLE
Sonoff Mini firmware upgrade 

### ISSUE THREAD

**Issue by Gringohekus** [arendst/Sonoff-Tasmota#6333]
I got  Sonoff Mini DIY and upgraded by the tasmota "sonoff-basic" BIN file. It started and I could start to use as any other tasmota device.  After that removed the jumper. I wanted to upgrade the Tasmota firmware using Tasmota OTA service. Upgrade started as usual but the module did not restart.  Sience that no led blinking on the modul. I tried to push the button on the Mini for 5sec or 5x but nothingh happended. I also can see its SSID of the device. Installed back the jumper and tried to reach it again but no change.
What could happened and how can I fix it?

Thanks

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
