### ISSUE TITLE
Sonoff tasmota mqtt connection problem

### ISSUE THREAD

**Issue by vedatorkun** [arendst/Sonoff-Tasmota#6335]
I can't connect to the device's mqtt address. Where am I doing wrong?
The required port on the modem is open.

Sonoff ip :  192.168.0.99
Sonoff mqtt : 192.168.0.98

00:00:03 WIF: Connected
00:00:03 HTP: Web server active on sonoff_1 with IP address 192.168.0.99
00:00:04 MQT: Attempting connection...
02:38:35 MQT: Connect failed to 192.168.0.98:1883, rc -2. Retry in 10 sec
02:38:46 MQT: Attempting connection...
02:38:52 MQT: Connect failed to 192.168.0.98:1883, rc -2. Retry in 10 sec
02:39:03 MQT: Attempting connection...
02:39:09 MQT: Connect failed to 192.168.0.98:1883, rc -2. Retry in 10 sec
02:39:20 MQT: Attempting connection...
02:39:26 MQT: Connect failed to 192.168.0.98:1883, rc -2. Retry in 10 sec
02:39:37 MQT: Attempting connection...
02:39:43 MQT: Connect failed to 192.168.0.98:1883, rc -2. Retry in 10 sec
02:39:54 MQT: Attempting connection...
02:40:01 MQT: Connect failed to 192.168.0.98:1883, rc -2. Retry in 10 sec
02:40:11 MQT: Attempting connection...
02:40:18 MQT: Connect failed to 192.168.0.98:1883, rc -2. Retry in 10 sec

![Screenshot_1](https://user-images.githubusercontent.com/5546009/64085469-99e1fe00-cd3b-11e9-82ec-1709076aa93a.png)

![Screenshot_2](https://user-images.githubusercontent.com/5546009/64085535-0b21b100-cd3c-11e9-89ed-2e7736afe549.png)

**Comment by curzon01** [comment]
not a Tasmota issue

Please address this to [Support's Community](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md#supports-community).
The community channels are a better and more dynamic for helping you.
Github issues are mainly used for Tasmota software feature requests and bug reporting. 

Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). 

Remember to close the issue. Thanks.

<hr>

#### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and links if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
