### ISSUE TITLE
Sonoff POW R2 - wrong "Energy Today" value

### ISSUE THREAD

**Issue by nromensky** [arendst/Sonoff-Tasmota#6336]
I have night circuit which is ON only 00:30 to 07:30. POW on this circuit shows wrong "energy today". device is off at 00:00, is that related? is it fixable?

**Comment by curzon01** [comment]
duplicate issue #6104


Remember to read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). 

Remember to close this issue. Thanks.

<hr>

#### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and links if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
