### ISSUE TITLE
Can't connect to WiFi with SSID with 32 characters

### ISSUE THREAD

**Issue by dalgoist** [arendst/Sonoff-Tasmota#6341]
When I try to connect the Sonoff (flashed with Tasmota) to my WiFi which has a 32 char long SSID via the Interface there is an question mark behind the SSID in the scanning menu. When I enter the correct SSID an password it wont connect to my WiFi. When I try to connect to a WiFi with 31 char SSID it works, when I try to connect to a WiFi with any 32 char SSID (also without spaces, special characters, ...) it can't connect...
I use the precompiled version (sonoff-DE.bin and sonoff.bin - both versions have this problem).

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

32 characters are not supported for ssid. If you want to use that, you need to modify the code. Remember that a change in the memory settings map will make your custom version not compatible with newer versions. 

If you need further assistant on how to modify the code, you can find us in the Tasmota support chat. 

Thanks. 

------

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
