### ISSUE TITLE
Temperatur from DS18B20 with Tasmota on WEMOS D1 mini flapping

### ISSUE THREAD

**Issue by hermann1514** [arendst/Sonoff-Tasmota#6345]
Hi, 

i have a WEMOS D1 mini with the followng Configuration:

Tasmota 6.6
DS18B20 Sensor
4,7K resistance between Data and 3,3V

The Temparature was displayed on the Main Menu from Tasmota. 
But it changes every few seconds. Actual value, then 0.6 degrees less, then again the normal value, etc ...

Anybody an idea?

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
