### ISSUE TITLE
Main Menu Title

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#635]
Hi, Is it possible to remove the Module Type in the Main menu.

For example mine unit says "Sonoff Basic Module"

I would like only the Friendly name to appear

**Comment by ionciubotaru** [comment]
Remove the html code you don'y need from sources and recompile.

**Comment by Lawrencezarb** [comment]
Where is that located?

**Comment by ionciubotaru** [comment]
in `webserver.ino` at line 90  replace `  "<div style='text-align:center;'><h3>{ha} Module</h3><h2>{h}</h2></div>";` with the text you like or delete everything except the semicolon in the end

**Comment by Lawrencezarb** [comment]
thanks I'll give it a try
