### ISSUE TITLE
 aofo power strip

### ISSUE THREAD

**Issue by rieders** [arendst/Sonoff-Tasmota#6350]
Hello
I am new here and wanted to ask if it is possible to control this power striphttps://www.amazon.de/dp/B07SR13SH5/ref=sspa_dk_detail_0?psc=1&pd_rd_i=B07SR13SH5&pd_rd_w=1ipR6&pf_rd_p=ba8dd0a6-f259-424f-a55c-308aa41eb539&pd_rd_wg=Zt68E&pf_rd_r=G30ZJPW95K2BC27EFBDG&pd_rd_r=508249b2-4fc1-4ca6-a3a1-ce432ada8bd9&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyRVRDU1lVUjlBWDBBJmVuY3J5cHRlZElkPUEwMzE3NjkwS0tVVVZVWEs2WFBPJmVuY3J5cHRlZEFkSWQ9QTEwMDI5MTQyUTIzTUo4SlpUTVJSJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ== with tasmota.
I have flashed the ESP and tasmota is also running.
The esp is connected to an IC 8S003F3P6 via RX and TX.
Is there a setup for me to control the 4 sockets and the USB sockets?
Many thanks for the help

**Comment by meingraham** [comment]
Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
