### ISSUE TITLE
Wire.flush() ?

### ISSUE THREAD

**Issue by Koepel** [arendst/Sonoff-Tasmota#6363]
In the file "Sonoff-Tasmota/sonoff/xsns_53_sml.ino", in the function `ADS1115::read_register()` there is a `Wire.flush()` after a `Wire.requestFrom()`.

Can you tell me what you want the `Wire.flush()` to do ?

The flush makes sense for the Serial library.
However, it makes no sense for the Wire library in my opinion.
The Wire library uses packets of data. The buffers are cleared with `Wire.beginTransmission()` and `Wire.requestFrom()`.

There is a implementation of the [Wire.flush()](https://github.com/arduino/ArduinoCore-avr/blob/7a2e1cd815266fef3012a5c9b48f88d78551f838/libraries/Wire/src/Wire.cpp#L271), but that is empty. It says: `// XXX: to be implemented`. In my opinion, there is nothing to implement.

**Comment by gemu2015** [comment]
i simply copied this code over from ADS1115 driver. it is not yet functional however and not used.
i am working on an analog comparator input for optical sensors to feed into the counter section.

so the author of the ADS1115 driver has to answer this question.
