### ISSUE TITLE
RFSend & RFrecv missing ?

### ISSUE THREAD

**Issue by marcelkordek** [arendst/Sonoff-Tasmota#6366]
Hi,

I'm running the latest version 6.6.0.10 20190905 and the RF components under Configuration are missing:

105 | RFSend
106 | RFrecv

Everything is visible and configurable with Version 6.6.0.
Were these two components removed or is it a error?

Thank you.

Greetings,
Marcel

**Comment by meingraham** [comment]
Did you flash `sonoff-sensors.bin` or compile with `RF_SENSOR`?

**Comment by arendst** [comment]
rc-switch is disabled due to lack of iram. See changelog at 6.6.0.1

**Comment by marcelkordek** [comment]
Thanks, with sonoff-sensors it’s working now :)

Greetings 
Marcel
