### ISSUE TITLE
MagicHome WS2812b V5 3-pin variant

### ISSUE THREAD

**Issue by ruudvddries** [arendst/Sonoff-Tasmota#6369]
Hi, I'm kind a new to the whole Tasmota scene and might have started with a too difficult first step. I am trying to flash my Magichome LED SPI controller with Tasmota. I have managed to load the firmware succesfully but now I'm wondering what module to load. I have tried Generic and Magichome and run through all pin options with every time setting a different pin to WS2812 but I'm never able to, in the first place, switch the leds in the strip on or off. The leds in the strip come on the moment I add a power source (5v3a) to the magichome module.

What am I missing here? If somebody could help me out, I am more than greatfull for your help with this!

Kind regards,

Ruud

**Comment by ruudvddries** [comment]
Hi guys,

I solved it by bypassing the magichome circuit between de rap and the ws2812b connectors. I have directly connected GPIO5 to the ws2812b data pin and I can now control it. At least I can turn it on and off. Next steps approaching, which is good.

Kind regards,


Ruud

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
