### ISSUE TITLE
4 dallas sensors - MQTT String corrupt

### ISSUE THREAD

**Issue by Schnittcher** [arendst/Sonoff-Tasmota#637]
Hello,

on the Sonoff Switch, we have 4 dalls sensors.
MQTT sends a corrupted string:

`{"Time":"2017-07-24T12:23:35", "DS18x20":{"DS1":{"Type":"DS18S20", "Address":"10D4B431030800E6", "Temperature":19.0}, "DS2":{"Type":"DS18S20", "Address":"105A7F30030800C2", "Temperature":19.8}, "DS3":{"Type":"DS18S20", "Address":"10BB863003080089", "Temperature":19.2}, "DS4":{"Type":"DS18S20", "Address":"10C72D3203080028", "Temperature":19.8}}, "TempUnit":"`

When we have 2 sensors on the switch, the MQTT string is fine:

`{"Time":"2017-07-24T12:24:52", "DS18x20":{"DS1":{"Type":"DS18S20", "Address":"10D4B431030800E6", "Temperature":19.1}, "DS2":{"Type":"DS18S20", "Address":"10C72D3203080028", "Temperature":19.8}}, "TempUnit":"C"}`

Can anyone help?
Sorry for my bad english.

**Comment by davidelang** [comment]
it looks like you are hitting the max message size limit, increase it.
kkkk

**Comment by Schnittcher** [comment]
Thanks, I will try it.
The max message size is MESSZ, right?
Can I change this with a command? Or I need to flash it, again?

**Comment by davidelang** [comment]
you will need to flash it. You may need to increase the max size in the library 
(the instructions tell you to increase it to 256 IIRC)
k

**Comment by arendst** [comment]
You could also use the pre-compiled binary ``sonoff-ds18x20.bin`` which allows for more sensors.

In the next version I'll update the default buffer length anyway with some 4 bytes as the problem is introduced by adding the TempUnit field to the JSON message.
