### ISSUE TITLE
Touch Buttons without Relay

### ISSUE THREAD

**Issue by nixmeer** [arendst/Sonoff-Tasmota#6371]
Hello,

as many before, I'd like to use the touch areas of my Sonoff T1 EU 2CH independent of the relays. 

First: Answers like [this](https://github.com/arendst/Sonoff-Tasmota/issues/3759#issuecomment-420098349) do not help at all. I've been working through the wiki, the issues and google for 4.5 hours now and I'm frustrated since I don't understand what Tasmota is doing. The wiki might be intuitive for those writing and spending lots of time with it; for me, it's not obvious what certain things mean or even how it's structured. Google revealed many wiki pages to me that I couldn't find on the GitHub page

What I want: A short press, a double press and a long press should publish different things to topicA and topicB, one topic for each button. The relays should react to topicC and topicD. The relays should not be triggered by any touch area.

I found [this](https://github.com/arendst/Sonoff-Tasmota/wiki/Rule-Cookbook#using-an-external-button-with-single-press---double-press-and-hold) but still: either a single or a double press trigger the relay.

I found an issue where arendst said that using rules for buttons stops them from toggling the relay but that's not true in my case. 

Adding a third ON-DO-rule to my rule with other states didn't show any difference. But again: I think I had seen a list of the different button states, but I can't find it again. Neither in GitHub nor using google... 

How does Tasmota work? What does a button press issue? How do I (dis)connect an action to or from an event such as a button press? What commands would create what I wand? 

Thanks for any reply!

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
