### ISSUE TITLE
size of clock on display SSD1306

### ISSUE THREAD

**Issue by nromensky** [arendst/Sonoff-Tasmota#6395]
sorry if this has been discussed already .... how to make clock larger on  SSD1306 display, please see photo

![IMG_20190910_113544](https://user-images.githubusercontent.com/25114540/64608693-26875e80-d3c3-11e9-9b69-351e3d24d69b.jpg)

**Comment by Jason2866** [comment]
All possibilitys are explained in wiki
https://github.com/arendst/Sonoff-Tasmota/wiki/Displays

**Comment by arendst** [comment]
Currently you cannot. 

Making it larger will make it unreadable as most characters will fall of the screen. There is no scaling in between.

![IMG_20190911_165428](https://user-images.githubusercontent.com/11044339/64708810-7e05f700-d4b5-11e9-933d-dc243ddf0597.jpg)

**Comment by arendst** [comment]
Now you can.

**Comment by nromensky** [comment]
thx Theo! unfortunately I do not see significant difference in relation to this topic.

any chance you could make clock in format HH:MM which will fill whole screen, currently we have HH:MM:SS + date, which uses only half the screen
