### ISSUE TITLE
Replace Led with IR transmitter

### ISSUE THREAD

**Issue by Plum67** [arendst/Sonoff-Tasmota#64]
Love idea of adding an IR transmitter that has come with latest release 3.9.16.

Just wondering if it would be possible to just replace the existing LED that is already on the board that currently shows relay state , and swapping out with the IR transmitter, so saving a GPIO?

**Comment by altelch** [comment]
No, not enough current to drive the IR led. The ESP8266 can drive about 38mA. You want 80-100mA for IR.

Greetings, Heiko.
