### ISSUE TITLE
Switching all relay on device

### ISSUE THREAD

**Issue by ahmaddxb** [arendst/Sonoff-Tasmota#6402]
I don't understand why this command documented in the commands list doesn't work.

If i do any command power0 is says {"Command":"Unknown"}

![image](https://user-images.githubusercontent.com/43728586/64688273-0a57f000-d49d-11e9-925f-73144fe71ae9.png)

Any help would be appreciated.

**Comment by Jason2866** [comment]
Are you using latest development version?
Since you didnt fill out issue template we just guessing.

**Comment by ahmaddxb** [comment]
Sorry no release 6.6.0

**Comment by ahmaddxb** [comment]
Is this feature only available in versions higher then 6.6.0?

**Comment by arendst** [comment]
FYI https://github.com/arendst/Sonoff-Tasmota/issues/6368#issuecomment-530324993

**Comment by ahmaddxb** [comment]
Nice so it already in the works. This will be a very helpful.
