### ISSUE TITLE
Same function as PowerDelta for other sensors

### ISSUE THREAD

**Issue by qingz2004** [arendst/Sonoff-Tasmota#6404]
**Have you looked for this feature in other issues and in the wiki?**
Yes
**Is your feature request related to a problem? Please describe.**
I can't find an efficient way to send MQTT immediately if a sensor data changes more than a certain percentage.
The sensor data can be anything like temperature, humidity, ADC.... Not just power.

**Describe the solution you'd like**
Need a command with similar function as PowerDelta.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by meingraham** [comment]
I understand the request, but in the interim, might this help?

https://github.com/arendst/Sonoff-Tasmota/wiki/Rule-Cookbook#Transmit-sensor-value-only-when-a-delta-is-reached

**Comment by qingz2004** [comment]
Thanks!
I know I can do that, but I want a percentage change, not a absolute change. And you have to take both increase and decrease into calculation for percentage which makes the expression complicated. That's why I say I can't find a efficient way to do that.

**Comment by meingraham** [comment]
Understood... just wanted to be sure you were aware.

Something like
sns\<x>Delta.metric
sns\<x>High.metric
sns\<x>Low.metric

[\<x> numbers](https://docs.google.com/spreadsheets/d/e/2PACX-1vRBFqaP5QAFmT8iIYBxrn-EQp7-SrkxL6tb0OjpqtBxDEsmkiWCFei3sFyA_UXoqlbs3CqtEdOfC6Pa/pubhtml?gid=1029939700&single=true)

e.g., sns3Delta.Power == PowerDelta

And can be a requirement in the development of the driver?

And while we're at it #5901 :wink:

**Comment by qingz2004** [comment]
Thanks!
At this time I will try to use the absolute change as you suggested, and see if it fits my case. Will segment the range in separate rules.

**Comment by ascillato2** [comment]
Closing this issue as this feature is not going to be added due to the resorces that it requires. Thanks for sharing your ideas.
