### ISSUE TITLE
Tasmota with ThingSpeak

### ISSUE THREAD

**Issue by asadenton** [arendst/Sonoff-Tasmota#6408]
**Is your feature request related to a problem? Please describe.**
I am trying to get Tasmota to connect directly to https://thingspeak.com/ via MQTT for direct reporting to record IOT data. I see that a few other people have been trying this but without success. The problem is the willTopic is set (see https://au.mathworks.com/help/thingspeak/troubleshoot-MQTT-publish.html Item 7)

**Describe the solution you'd like**
I have managed to get it to connect by setting the willTopic parameter in the connect command to nullptr: https://github.com/arendst/Sonoff-Tasmota/blob/f88e87cfde982bb3bbbfaa27a275777ba0166bf9/sonoff/xdrv_02_mqtt.ino#L609. I think it would be great to have a checkbox that allows you to disable the willTopic via the UI.

**Describe alternatives you've considered**
Alternatives would be a build flag but that means that individuals cannot set this without building the system however, for the small amount of data storage required this would be cumbersome.

Thanks.

**Comment by mcsabi** [comment]
@asadenton, I am on release 6.6.0 and I get the same error "Connect failed to mqtt.thingspeak.com:1883, rc 5. Retry in 10 sec". What are the steps I need to take, console commands, to get it connect to Thingspeak. Thanks

**Comment by mcsabi** [comment]
would you share the rebuilt code? Would be interested to test with ThingSpeak Thanks

**Comment by asadenton** [comment]
Sure: https://drive.google.com/open?id=1rPg_kQUCZ4p4nKGwx4aIbbQf4YIyLums

I will leave it up for a few days. There are no commands that can be issued from the console to make this change, it must be rebuilt. This issue is proposing that we change that.

**Comment by mcsabi** [comment]
Thank you! Perfect got it connected right away!!! Now trying to publish the DHT22 temp and humidity data, but so far it does not get published. Using these two publishing methods:
channels/<channelID>/publish/<Write apikey>
channels/<channelID>/publish/fields/field1/<Write apikey>

**Comment by meingraham** [comment]
@asadenton perhaps you can structure a PR that at the least uses a #define directive to set this parameter? It may not be as easy as the GUI, but it would make it more accessible to those users that want to use ThingSpeak. It would be easier for them to set the #define in their `user_config_override.h` and compile on Gitpod to easily get this capability.

**Comment by asadenton** [comment]
I think my use case is going to need a little more thought. There is not an easy way to map tasmota payloads and topics to thingspeak payloads and topics. I am likely going to need a broker that does the remapping in between the two services. I know mosquito can act as a bridge and remap topics but not payloads. Does anyone have any other suggestions for this?

I am happy to implement the code if it can be done in Tasmota but I don't think it is without significant size increase to the code.

**Comment by mcsabi** [comment]
It would be fantastic if you could implement it in Tasmota. There is 448kB free program space on NodeMCU having the standard Tasmota installed. Would that be enough, you think?

**Comment by effelle** [comment]
@asadenton what exactly have you changed on `xdrv_02_mqtt.ino` ?
Did you do an extensive test to see if mqtt works fine for all the entities you have set under ThingSpeak?

**Comment by Jason2866** [comment]
@mcsabi  There is not 448kb free space. You need about 400k free flash for the possibility to do OTA.
There will be no PR merged which will increase code size (a lot) for a not often used feature.
Tasmota main use is for a local mqtt broker

**Comment by asadenton** [comment]
Given there are a few people who have been interested in this, I will document what I have discovered and why Tasmota is not suitable for ThingSpeak.

Tasmota will not connect to ThingSpeak by default because the MQTT will topic is always set and ThingSpeak does not support that. This is easy to fix in the code and could be added as a UI feature with little trouble. I had Tasmota connecting to ThingSpeak with the one line change above.

The problem comes with the MQTT contract that ThingSpeak requires (topic: channels/<channelID>/publish/fields/field<fieldnumber>/<apikey>, message: <value>). Although the topic can be adjusted through the UI, the value that is sent in the message cannot. Tasmota will send JSON for a DHT22 and there is no way to force it to send a single value or split the data (temp and humidity) into two topics. The changes are too large and Tasmota has not been designed with this in mind - it is just the wrong platform.

This problem may be solvable with ESPhome however, I will be putting something together that will likely have a MQTT bridge along with some level of translation. Thank you all for your time.

**Comment by mcsabi** [comment]
@Jason2866 thank you for the clarification, totally understood!
@asadenton, thanks so much for spending the time and trying to find a solution for the Thingspeak problem. Your one line fix had worked like a charm and I could connect to Thinkgspeak broker straight away. Would be nice to have a UI checkbox for it.
As for the sending multiple values to separate fields to Thinkspeak, I guess would be doable with the full topic of "channels/<channelID>/publish/<apikey>" but it would require a value of "field1=100&field2=50&status=MQTTPUBLISH" and as you mentioned this is not possible with Tasmota. 
I am unfortunately not familiar with ESPhome, but will have a look at it. Thank you for all your efforts, it would be great if you could make it work. Many thanks!!!

**Comment by mcsabi** [comment]
@asadenton, did you have a chance to have a look at ESPhome to see if it would be a solution? BTW what I would like to achieve is to have tasmotized NodeMCUs with sensors (dht22, bme280), not on local network, to publish their data in every 15 min. I would need to see the latest reading + the history graph. Thingspeak is a great solution, but I would be happy with any solution that does not require any local installation such as Domoticz, home assistant, mqtt broker, etc. The client could be a browser or a client that runs on iOS&Android. Any suggestion would be appreciated! Thank you!

**Comment by asadenton** [comment]
I did not try it but I have used ESPhome many times before. I am pretty sure it is easy to do. Just check out this page: https://esphome.io/components/mqtt.html#mqtt-publish-action
