### ISSUE TITLE
Using the `rule(x)` command over MQTT can return invalid JSON if the Rule contains double quotes "

### ISSUE THREAD

**Issue by DeviousPenguin** [arendst/Sonoff-Tasmota#6413]
### BUG DESCRIPTION

Using Rules can produce invalid JSON when the `Rule(x)` command is used over MQTT. Specifically if any rule with double quotes in => `"` as they are not escaped by Tasmota. To resolve this the double quotes should be escaped so the MQTT payload has `\"` instead of `"` within the Rule text. http://www.json.org/ may show this more clearly than my description here!

https://jsonformatter.org/json-escape is also handy for checking payloads

For example, when I run the `Rule1` command from the Tasmota Console on the webinterface I get this output:

` 01:14:25 MQT: garage_lights_9CFF12/stat/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":270,"Rules":"on switch1#state=1 do backlog power5 1; publish garage_lights_9CFF12/tele/SENSOR {"Switch1":"ON"}; RuleTimer1 300 endon on switch1#state=0 do publish garage_lights_9CFF12/tele/SENSOR {"Switch1":"OFF"} endon on Rules#Timer=1 do power5 0 endon"}`

Which is OK from the console. However when I need 
However when I try and decode the MQTT payload in NodeRED, I get:

` "Unexpected token S in JSON at position 150"`

which is the start 'Switch1' of `SENSOR {"Switch1":"ON"}` in the payload. While JSON errors are somewhat OK in NodeRED, when using HomeAssistant invalid JSON totally breaks things. 

I have manually escaped the quotes in my previous rule:

` {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":270,"Rules":"on switch1#state=1 do backlog power5 1; publish garage_lights_9CFF12/tele/SENSOR {\"Switch1\":\"ON\"}; RuleTimer1 300 endon on switch1#state=0 do publish garage_lights_9CFF12/tele/SENSOR {\"Switch1\":\"OFF\"} endon on Rules#Timer=1 do power5 0 endon"} `

If I manually send the above escaped string as a test MQTT message to NodeRED or HomeAssistant it now works.

Would it be possible to add escape chars to MQTT payloads when the Rule(x) command is used using MQTT?

### REQUESTED INFORMATION
_Make sure these boxes are checked before submitting your issue. Thank you_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Searched the problem in the chat (https://discord.gg/Ks2Kzd4)
- [x] Device used (i.e. Sonoff Basic) : Sonoff 4ch
- [x] Tasmota binary firmware version number used : 6.6.0.10(sonoff) self-compiled dev branch
- [x] Development IDE - Compiler / Upload tools used : VSCodium / PlatformIO
- [x] Provide the output of command ``Rule1`` :
```
Rule1 OUTPUT HERE:

01:14:25 MQT: garage_lights_9CFF12/stat/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":270,"Rules":"on switch1#state=1 do backlog power5 1; publish garage_lights_9CFF12/tele/SENSOR {"Switch1":"ON"}; RuleTimer1 300 endon on switch1#state=0 do publish garage_lights_9CFF12/tele/SENSOR {"Switch1":"OFF"} endon on Rules#Timer=1 do power5 0 endon"}

```
- [x] Provide the output of console when you experience your issue if apply :
_(Please use_ ``weblog 4`` _for more debug information)_
```
CONSOLE OUTPUT HERE:

not needed
```

### TO REPRODUCE
_Steps to reproduce the behavior:_

Have a Rule with a double quote `"` in then use the Rule command over MQTT

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

I expected the returned MQTT message to have escaped double quotes.

If the rule contains `SENSOR {"Switch1":"ON"}` then I expected the MQTT payload from the Rule command to be `SENSOR {\"Switch1\":\"ON\"}`

**Comment by curzon01** [comment]
Escapes are handled by your NodeRED and/or HA, not by mqtt nor by console input.
So escaping is only a solution if Tasmota Ruleparameter will handle escapes.

**Comment by DeviousPenguin** [comment]
> Escapes are handled by your NodeRED and/or HA, not by mqtt nor by console input.

Yep I've tested using an MQTT payload in NodeRED, it handles JSON payloads which used escaped double quotes when doing a test MQTT message. The issue is that Tasmota does not Escape special characters such as double quotes when sent over MQTT when using the `Rule1` or `Rule2` command, so produces invalid JSON.

>  So escaping is only a solution if Tasmota Ruleparameter will handle escapes.

I don't want to add in escapes in my Tasmota rules using the console, this will probably break my rules anyway. I only want Tasmota to add the escapes when the Rules are sent over MQTT, so that the JSON is valid.

So for example, if I've set my rule in the console to this, no escapes:

`rule1 on switch1#state=1 do backlog power5 1; publish garage_lights_9CFF12/tele/SENSOR {"Switch1":"ON"}; RuleTimer1 300 endon on switch1#state=0 do publish garage_lights_9CFF12/tele/SENSOR {"Switch1":"OFF"} endon on Rules#Timer=1 do power5 0 endon`

I then need to use the `Rule1` command over MQTT which should produce this MQTT payload, with escapes:

`{"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":270,"Rules":"on switch1#state=1 do backlog power5 1; publish garage_lights_9CFF12/tele/SENSOR {\"Switch1\":\"ON\"}; RuleTimer1 300 endon on switch1#state=0 do publish garage_lights_9CFF12/tele/SENSOR {\"Switch1\":\"OFF\"} endon on Rules#Timer=1 do power5 0 endon"}`

This allows my to have Switches in HA that can turn Tasmota rules on and off for example.

**Comment by meingraham** [comment]
@DeviousPenguin 

Is it not possible to have HA perform all the MQTT sensor publishing and have Tasmota only send HA a "trigger" message with just the data HA requires to then turn around and transmit the information?

This consolidates the "intelligence" in your hub and Tasmota is only tasked with low level actions.

Mike

**Comment by curzon01** [comment]
@DeviousPenguin 
as Michael wrote, Tasmota (command window) and MQTT should used for low level actions.
Neither Tasmota nor mqtt needs escapes for double quotes.

**Comment by Jason2866** [comment]
There will probably no change in Tasmota since it would need to much of the rare resources.
As @curzon01 and @meingraham wrote these level functions are better placed in a "higher level"
You already found a solution with node-red👍

**Comment by andrethomas2** [comment]
Closing this issue as it has been answered.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
