### ISSUE TITLE
driver USE_SDM630_2 i'm tested 

### ISSUE THREAD

**Issue by dr-apple** [arendst/Sonoff-Tasmota#6431]
Hi here my report for the driver USE_SDM630_2:

before:

![Bildschirmfoto 2019-09-16 um 15 48 13](https://user-images.githubusercontent.com/15102858/64963609-d6fcd300-d899-11e9-8e94-9d019703e322.png)

here with the driver USE_SDM630_2:

![Bildschirmfoto 2019-09-16 um 15 15 17](https://user-images.githubusercontent.com/15102858/64963651-e8de7600-d899-11e9-8657-c7caa06f061d.png)

I became only 1 value for volt and the other values....

**Comment by arendst** [comment]
Ah, bugger. Forgot to tell it's three phase. Hold on.

**Comment by dr-apple** [comment]
Thank you very much, it's work fine:

![Bildschirmfoto 2019-09-16 um 16 28 31](https://user-images.githubusercontent.com/15102858/64966450-1aa60b80-d89f-11e9-9635-d40bb024af73.png)
