### ISSUE TITLE
Teckin SP22 with Realtek chips RTL8710BN

### ISSUE THREAD

**Issue by rikthefrog** [arendst/Sonoff-Tasmota#6434]
Currently Tuya is selling Teckin SP22 smart connectors with the Realtek chip RTL8710BN. On these chips is doesn't look Tasmota is working. According to Max Prokhorov these chips can only be flashed with an SDK which is provided to the vendor by Tuya :(

So be careful if you want to buy Teckin SP22 and want to flash it, you can run into a big disappointment.

**Comment by Jason2866** [comment]
This is really bad news :-(

**Comment by hochwasser** [comment]
On the template repository I put a warning about those plugs. Maybe a warning should be put one the wiki here too. I think about buying [ESP-12F](https://www.adafruit.com/product/2491) modules or the original ones from tuya [TYWE2S](https://german.alibaba.com/product-detail/tuya-tywe2s-wifi-module-develop-wireless-networking-module-esp-8285-wifi-module-development-62133775853.html). 
Has somebody done this?

**Comment by Jason2866** [comment]
@hochwasser  You can make changes in wiki ;-)

**Comment by hochwasser** [comment]
I created a page: https://github.com/arendst/Sonoff-Tasmota/wiki/Teckin-SP22

**Comment by znanev** [comment]
@hochwasser Most of the UK plugs that I got come with module **ESP8266-3** (manufactured by _Hysiry_ for _Tuya_). I damanged one of the modules while desoldering it from the main board, but found replacement on AliExpress:

https://www.aliexpress.com/item/32869538851.html

Its form factor is closer to TYWE2S, so you could use that.

**Comment by MaSylvester** [comment]
![Teckin_SP22_V15](https://user-images.githubusercontent.com/55551205/65346320-bbb4ff00-dbdc-11e9-867e-e27bb199cb9b.jpg)
![Teckin_SP22_RTL](https://user-images.githubusercontent.com/55551205/65346324-be175900-dbdc-11e9-9ef9-25f3965d74f4.jpg)
Some Pictures from the new V15 with Realtek-Chip

**Comment by hochwasser** [comment]
@znanev 
The module you suggested has the pins opposite of each other. One the TYWE2S the pins on the back side have an offset. You can see this quite well on this picture:
![IMG_20190920_194802_572](https://user-images.githubusercontent.com/4726652/65357019-23c40f00-dbf6-11e9-8499-fdff8701245a.jpg)

@MaSylvester 
How did you open the case? I made some damage to the border and on one side I cut the over lapping of the border. So the case does not look nice any more.

Does somebody know what the IC U1 make and what type it is?

**Comment by Jason2866** [comment]
You mean U4? This is the power monitoring ic BL0937

**Comment by znanev** [comment]
@hochwasser I thought that you're not looking for a direct replacement, because you mentioned ESP-12F, which has quite different pinout than TYWE2S.

**Comment by hochwasser** [comment]
@Jason2866 
No. That chip could i identify. I mean the chip U1 on the top right side in the picture from @MaSylvester.

@znanev 
Sorry, my failure. The ESP-12F is easier and faster to get here. This is the cause why I want to use it.
I found https://german.alibaba.com/product-detail/tuya-tywe2s-wifi-module-develop-wireless-networking-module-esp-8285-wifi-module-development-62133775853.html but I don't know if the supplier is trustworthy.

**Comment by znanev** [comment]
@hochwasser I would give alibaba.com a go, I've used them in the past. At least the price is not prohibitive.

Did you manage to track the signals going in / out the RTL module, i.e. is it pin compatible to TYWE2S?

**Comment by hochwasser** [comment]
@znanev 
I looked at the datasheet tuya supplied: [TYWE2S](https://docs.tuya.com/docDetail?code=K8uhknau42nof) / [WR2](https://docs.tuya.com/docDetail?code=K8uhkbx75kg7y)
(at the bottom you can change the language to english)

The pinout seems equal enough and the marking on the PCB on the module slot is  TYWE2S.
So I'm pretty sure the TYWE2S would fit.

**Comment by znanev** [comment]
@hochwasser Indeed, just compared the pins of both modules and they look compatible. So you could try replacing the RTL module for the ES8266-based TYWE2S. This will be a nice module transplantation exercise - I even envy you a bit for that opportunity :)

**Comment by MaSylvester** [comment]
@hochwasser : I used the blade from my IFixiIt-Kit and made some turn-around at the case.
I'm also interested in some TYWE2S-Modules if you would buy some from alibaba. 
![Teckin_SP22_Blade](https://user-images.githubusercontent.com/55551205/65371407-a931d880-dc63-11e9-9a4c-a29894de19de.jpg)
![Teckin_SP22_Opening](https://user-images.githubusercontent.com/55551205/65371408-a931d880-dc63-11e9-80b9-5dc5d5773bfb.jpg)

**Comment by MaSylvester** [comment]
@hochwasser , @znanev 
Some more pictures from U1 ans the WLAN-module
![Teckin_SP22_U1](https://user-images.githubusercontent.com/55551205/65371752-3296da00-dc67-11e9-817b-452eb1711a11.jpg)
![Teckin_SP22_WLAN](https://user-images.githubusercontent.com/55551205/65371753-3296da00-dc67-11e9-9c9b-0ed6e1994c53.jpg)

**Comment by Jason2866** [comment]
From whats around the IC U1 it is a switching power supply unit

**Comment by andrethomas2** [comment]
Closing this issue as it relates to an unsupported device on which Sonoff-Tasmota will not run.

At this point only ESP8266/ESP8285 devices are supported in this repository.

**Comment by roberdlv** [comment]
Do you know if there is the same problem with teckin sp21? or sp21 only has chips yours flasheables via wifi? Thank you

**Comment by ToxicF** [comment]
> @znanev
> I looked at the datasheet tuya supplied: [TYWE2S](https://docs.tuya.com/docDetail?code=K8uhknau42nof) / [WR2](https://docs.tuya.com/docDetail?code=K8uhkbx75kg7y)
> (at the bottom you can change the language to english)
> 
> The pinout seems equal enough and the marking on the PCB on the module slot is TYWE2S.
> So I'm pretty sure the TYWE2S would fit.

hey @hochwasser , did you had success with changing the chip? I would be really interested because i got some SP22's too, and unfortunately they also got the new chip.

**Comment by krakkato** [comment]
Hi, I have SP22 with a new chip ... I replaced the chip with esp12f. Relay, blue and red LEDs work fine... but I can't read the consumption measurement.

**Comment by hochwasser** [comment]
@ToxicF sorry for not answering earlier.
I did not work and like @krakkato I could not read the power consumption.
The chip for the power consumptions seems really picky: I did not get any meaningful data or changes on the pins.
I measured with an oscilloscope with not luck ether. 

I cut my losses and bought DELOCK 11826, they already come with tasmota and are easy to update.
A friend of mine told me that there is a new one with power meter, DELOCK 11827. But on the WLAN he get packet losses.
Maybe someone can test this device if his setup is broken or the 11827 has some problems.

**Comment by jaymemaurice** [comment]
I have purchased a pair of Teckin sp20's that appear to have this same chip 👎 
From the outside they are indistinguishable (including FCC ID) from the ESP based ones I had purchased earlier.
The silk-screening on my ESP based version is slightly lighter and crisper... but maybe that's just my imagination.

**Comment by array81** [comment]
Is there a wat to know if a SP22 use or not use a ESP chip without open it?

**Comment by sfromis** [comment]
Yes, find the MAC, and look it up on a site like `macvendors.com`. If it is Espressif, the chip is ESP.

The MAC just might be on a label somewhere (don't count on that), or find it in pairing mode using some Wifi analyzer app.

**Comment by zillion42** [comment]
Hi,

I don't know if I'm right here. Please point me to a general serial flashing hardware discussion if not. 

I have some moderately old Teckin Sp22 which hopefully still can be tasmotized ?

> The [BlitzWolf SHP2](https://tasmota.github.io/docs/devices/BlitzWolf-SHP2/.md), HomeCube SP1, and Teckin SP22 are basically the same device barring the branding.

I tried OTA tuya convert today but unfortunately the firmware is to new.

`could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1056)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.24:49153
ID: 02f90525f2566f56f7a7c37d5f02c07588de99375850ed78f6f429d7643fe62669ed9cac325e8017ca9e35faf4fc88e274`

and

`Attempting to diagnose the issue...
Your device's firmware is too new.
Tuya patched the PSK vulnerability that we use to establish a connection.
You might still be able to flash this device over serial.`

So I would like to flash them over serial... 
I managed to open one of the housings today (they have no screws, and I broke it, but its collateral) and found the following:

https://photos.app.goo.gl/ZBCecqas7YuGs3Xw5

Looking at the pictures, I found this thread.
Mac Address is:
18:69:D8:5E:EA:A8

Can those be flashed ?
Thx in advance.

**Comment by barbudor** [comment]
Not an ESP
Bad luck

**Comment by sfromis** [comment]
MAC lookup should say "Espressif", and this round logo means "Tasmota-compatible" 
![image](https://user-images.githubusercontent.com/47082390/195975985-ef6c3abf-70d0-4914-bb9e-bf92742f6b57.png)

**Comment by flohav** [comment]
Hi, I just flashed ESPHome on a SP22 plug with RTL8710BN using LibreTuya. 
https://github.com/kuba2k2/libretuya
I posted the config on their Discord.

**Comment by Jason2866** [comment]
@flohav Tasmota crew has not planned to support Realtek nor any other chips from other vendors than espressif
