### ISSUE TITLE
Variable SSID/Password combinations

### ISSUE THREAD

**Issue by drannex42** [arendst/Sonoff-Tasmota#6435]
I am not able to hardcode any of the SSID into the system, while I realize that the ep chipset is purely wifi, is there a guide/knowledge base that could direct me to allow for bluetooth setting of the ssid information, or a local network creation? 

Thanks (I realize issues are not where this should be, but only community that I can find for this atm).

**Comment by meingraham** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/iBeacon-driver?

**Comment by drannex42** [comment]
I must have skipped over this good bit of information: https://github.com/arendst/Sonoff-Tasmota/wiki/Initial-Configuration

> 'Connect your device to a power source and grab your smartphone (or tablet or laptop or any other web and Wi-Fi capable device). Search for a Wi-Fi AP named sonoff-xxxx (where x is a number) and connect to it. In this example the Wi-Fi AP is named sonoff-7718. When it connects to the network, you may get a warning that there is no Internet connection and be prompted to connect to a different network. Do not allow the mobile device to select a different network.
> 
>     Wi-Fi manager server is active for only 3 minutes. If you miss the window you might have to disconnect your device from power and reconnect.
> 
> Sign in to Wi-Fi Network After you have connected to the Tasmota Wi-Fi AP, open http://192.168.4.1 in a web browser on the smartphone (or whatever device you used). Some devices might prompt you to sign in to Wi-Fi network which should also open the above address.

**Comment by webtop** [comment]
You missed these also ;0)

[Discord ](https://discord.gg/Ks2Kzd4)
[Telegram ](https://t.me/tasmota)
[Community Forum](https://groups.google.com/d/forum/sonoffusers)

**Comment by andrethomas2** [comment]
Please note that GitHub Issues are for reporting bugs and requesting additional features.

Please search the Wiki for the information you require or visit Discord Chat where general questions and answers are handled.

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
