### ISSUE TITLE
Wrong data using P1 smart meter implementation in  Sonoff Pow R2

### ISSUE THREAD

**Issue by pablozg** [arendst/Sonoff-Tasmota#6444]
Hi, after few days using the new P1 smart meter for domoticz I observed some wrong data using it with a sonoff Pow R2:

Edit: I'm using the last development version on github (6.6.0.12 commit 8483a71) compiled with Visual Studio Code and Platformio

This screenshot is from the new P1 smart meter, as you can see along the day is using both usage (usage1 and usage2): 

![P1 Pow R2](https://user-images.githubusercontent.com/9143666/65135455-4394e080-da06-11e9-9c6b-060f11c0a853.png)

This screenshot is from my custom LUA script in domoticz in the same space time, using the formula I used in my PR.

![P1 POW R2 LUA](https://user-images.githubusercontent.com/9143666/65135555-6fb06180-da06-11e9-9fbd-90ed1ce117d9.jpg)

But the new sensor is working well with the sdm120 as you can see in this screen shot, so only wrong data is sended with the POW R2.

![P1 SDM120](https://user-images.githubusercontent.com/9143666/65135758-c1f18280-da06-11e9-874c-2ae4d7d2aeb5.jpg)

Here the status 0 of POW R2:

```
11:25:12 CMD: status 0
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS = {"Status":{"Module":43,"FriendlyName":["monitorCasa"],"Topic":"Casa/PB/monitorCasa","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"sonoffs","OtaUrl":"http://10.10.0.110:1880/esp8266-ota/update/firmware_6.6.0.12_4mbit","RestartReason":"Software/System restart","Uptime":"0T00:42:36","StartupUTC":"2019-09-18T08:42:36","Sleep":50,"CfgHolder":4617,"BootCount":140,"SaveCount":745,"SaveAddress":"3F8000"}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS2 = {"StatusFWR":{"Version":"6.6.0.12(sonoff)","BuildDateTime":"2019-09-18T10:38:21","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS3 = {"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Isabella_T","Isabella_H"],"TelePeriod":20,"Resolution":"558B88C0","SetOption":["002A8009","28B400000100068000005AFF000000170D00","00000200"]}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS4 = {"StatusMEM":{"ProgramSize":563,"Free":2508,"Heap":26,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":3,"Features":["00000809","8FDAE397","043683A1","22B617CD","41001BC0","00000001"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34,49"}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS5 = {"StatusNET":{"Hostname":"Casa/PB/monitorCasa-6274","IPAddress":"10.10.0.101","Gateway":"10.10.0.254","Subnetmask":"255.255.255.0","DNSServer":"10.10.0.254","Mac":"80:7D:3A:32:B8:82","Webserver":2,"WifiConfig":2}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS6 = {"StatusMQT":{"MqttHost":"10.10.0.110","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_32B882","MqttUser":"htpc","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS7 = {"StatusTIM":{"UTC":"Wed Sep 18 09:25:12 2019","Local":"Wed Sep 18 11:25:12 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":99,"Sunrise":"07:30","Sunset":"19:58"}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS9 = {"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS10 = {"StatusSNS":{"Time":"2019-09-18T11:25:12","ENERGY":{"TotalStartTime":"2019-05-25T00:00:00","Total":[11024.791,146.777,10878.015],"Yesterday":11.305,"Today":4.137,"Power":1317.1,"ApparentPower":1360.6,"ReactivePower":341.2,"Factor":0.97,"Voltage":234.5,"Current":5.802}}}
11:25:12 MQT: Casa/PB/monitorCasa/stat/STATUS11 = {"StatusSTS":{"Time":"2019-09-18T11:25:12","Uptime":"0T00:42:36","UptimeSec":2556,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"Isabella_T","BSSId":"D4:6E:0E:D0:43:EC","Channel":6,"RSSI":38,"LinkCount":1,"Downtime":"0T00:00:04"}}}
```
And the Tariff config:

````
11:27:09 CMD: tariff
11:27:09 MQT: Casa/PB/monitorCasa/stat/RESULT = {"Tariff":{"Off-Peak":[22,23],"Standard":[12,13],"Weekend":"OFF"}}
````

**Comment by gajotnt** [comment]
I'm also having some readings being way off. 
Using the my SDM120 for both the domoticz virtual meter and the P1 smart (updated the sonoff to try out the new feature), for example the normal usage meter is giving me a total Usage of 9 kwh and the P1 is giving me 5.4kwh, almost half. Letting it run a couple more days.

**Comment by pablozg** [comment]
It seems only are affected the off-peak period, during the standard period all data is ok:

![offpeek period](https://user-images.githubusercontent.com/9143666/65231285-a43c2000-dacf-11e9-89b6-3e40053867ef.png)

**Comment by pablozg** [comment]
I have created a PR #6462, with the new code no wrong data is reported to domoticz.

![p1 new code](https://user-images.githubusercontent.com/9143666/65322773-fea8af80-dba7-11e9-8897-6f5c19f55eac.png)

@gajotnt can you compile tasmota with the changes made in my PR and test it?

Thanks.

**Comment by gajotnt** [comment]
Will try this weekend :)

**Comment by pablozg** [comment]
Hi, for me is working well now, I'll wait to @gajotnt test result, before close the issue.

**Comment by gajotnt** [comment]
Having some issues with Arduino ide. Gotta reinstall it again

**Comment by pablozg** [comment]
@gajotnt You can download the lastest compiled binaries from http://thehackbox.org/tasmota/, they have the new changes merged and you only have to flash it.

**Comment by gajotnt** [comment]
On it, gonna upload the bin and maybe later today or tomorrow will report

**Comment by gajotnt** [comment]
Like this right? So far still seeing it register 0watts, but better wait some more hours. Also im not on the lastest beta of domoticz, dont know if it matters.
![CaptureSDM120](https://user-images.githubusercontent.com/25504364/65386897-8b7e7500-dd30-11e9-8754-190fa19a7e50.JPG)

**Comment by pablozg** [comment]
Please, create a new P1 sensor in domoticz, and configure the new index number in tasmota and see if it update properly.

**Comment by gajotnt** [comment]
Ok, deleted it, made a new P1SmartMeter sensor and updated sonoff with new IDX.

**Comment by gajotnt** [comment]
When return is above 0watts shouldnt the usage be 0watts?

![domo](https://user-images.githubusercontent.com/25504364/65390143-0dc86280-dd4c-11e9-9eec-073ab5ebf3c4.JPG)

Otherwise so far not really that off from the normal usage sensor

![usage](https://user-images.githubusercontent.com/25504364/65390265-e8882400-dd4c-11e9-9543-60a4e99ccc29.JPG)

**Comment by pablozg** [comment]
> When return is above 0watts shouldnt the usage be 0watts?

You are right, I have the same issue, but I think is related to the data update speed in domoticz and the formula they use to process the data, I don't know if they use the last reported data in the five minutes or they use a arithmetic average of all data received in the lapse of five minutes and then represent it in the chart.

> Otherwise so far not really that off from the normal usage sensor

I have the same behaviour, but if you see the totals in the two sensors, they are the same.

![p1vspowersdm120](https://user-images.githubusercontent.com/9143666/65391154-29406700-dd66-11e9-9785-7c73bab0817d.png)

![p1vspowersdm120totals](https://user-images.githubusercontent.com/9143666/65391156-2c3b5780-dd66-11e9-8981-8f6b8af605cd.png)

**Comment by arendst** [comment]
Latest fix solves domoticz decimal resolution which would always be zero for a smart meter.

Also fixed partial entries for EnergyReset4 and EnergyRestet5.

Be awar that before implemnting this make a copy of your current usage values; after installation new code you will have to execute EnergeReset4 (and possibly EnergyReset5) to restore the correct values as now they are divided by 100 ;-).

**Comment by gajotnt** [comment]
If i do this will the domoticz normal usage sensor still work like always?

**Comment by arendst** [comment]
Yep

**Comment by gajotnt** [comment]
Ok nice :)

**Comment by gajotnt** [comment]
Now domoticz doesnt even show return 1 and 2. maybe because no return has been detected.

**Comment by gajotnt** [comment]
Still getting some off place minor return values. 
![Screenshot_20190922-232859](https://user-images.githubusercontent.com/25504364/65395981-18591b00-dd91-11e9-970a-d6246276c5a0.jpg)

**Comment by pablozg** [comment]
It's strange, as you can see my return chart is totally flat, maybe something in your installation is injecting energy to the grid or a faulty meter.

![return flat](https://user-images.githubusercontent.com/9143666/65408014-7bc06880-dde4-11e9-9b51-822732c8b2aa.png)

**Comment by gajotnt** [comment]
I have solar panels, but at night there is no sun, thats why I found it wierd, and if the house is consuming 638watts there can't be return. Maybe my sdm120 is faulty, still 11watts is nothing.

**Comment by pablozg** [comment]
I have solar panels too, but as you can see, my sdm120 don't register any activity at night.

**Comment by gajotnt** [comment]
If its working well in your side of the woods, then its something in my install.
12watts readings now and then wont change the readings in the long run, we're talking about 0.001Kwh, thats nothing :)

**Comment by pablozg** [comment]
Ok, So I think we can close this issue and mark it as fixed

**Comment by gajotnt** [comment]
Again some minor errors during the day, with the return, this time the usage should be zero.
Can be sinse domoticz logs in 5min intervals, in those 5 min the SD120 registred return and usage. Can this be the case?
![domo1](https://user-images.githubusercontent.com/25504364/65458882-2749d700-de3e-11e9-9636-ead124dc3b5d.JPG)

**Comment by pablozg** [comment]
I think so, because the counters used by tasmota to send the data to domoticz are acumulative.

So the both counters (usage/export) can be increased in the lapse of five minutes.

**Comment by gajotnt** [comment]
Those spikes right after it going to 0watts are wierd. Cant find a suitable explantion for it.
PS: if the house goes over +/-3500watts the fuses go off.

![spikes](https://user-images.githubusercontent.com/25504364/65603522-59ba1800-df95-11e9-8268-1fd0f73ccc17.PNG)
