### ISSUE TITLE
Automatically switching the supply voltage of a WS2812 LED strip.

### ISSUE THREAD

**Issue by Vujagig** [arendst/Sonoff-Tasmota#6446]
> Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

**Have you looked for this feature in other issues and in the wiki?**  
Yes

**Is your feature request related to a problem? Please describe.**  
No

**Describe the solution you'd like**  
If the LEDs are "soft-off", an LED strip can quite well consume a few watts of standby power.
It would be good if you could use a SetOption command for the fact that a relay output with a short delay is switched.
WS2812 ON: Power on -> short wait -> WS2812 command on
WS2812 OFF: WS2812 command off -> short wait -> LED power off
SetOption xx 1..16 for GPIO-No. or  0..8 for D-No.
SetOption yy 1-250 Delay time in ms
You only need a single command to completely switch off the LED

**Describe alternatives you've considered**  

**Additional context**  
None

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
This is doable via a rule.
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Vujagig** [comment]
Oh thanks, it works :)

**Comment by raddi** [comment]
Did you manage do accomplish this? Could you post your rule? Thank you! :)
