### ISSUE TITLE
Reset but now GPIO14 to DHT22 no longer works

### ISSUE THREAD

**Issue by tam481** [arendst/Sonoff-Tasmota#645]
Hello, I have been having issues since upgrading to 5.4 from 5.2.1 so I decided to reset the device to default. I did that (reset 2) and tried to configure the device GPIO14 to DHT22 (as before) and it rebooted but it no longer displays or logs the temperature and humidity.

Help!

Regards,

**Comment by tam481** [comment]
I also tried using the console "GPIO14 3" to no avail

**Comment by tam481** [comment]
Downgraded to 5.2.1 again (reset 2) and reconfigured the module and I have my temperature and humidity reading again :-)

**Comment by jedrollins** [comment]
I'm having a problem with 5.4 converting to F with the conversion flag set to 1. Only displays degrees in C even when F is displayed.
