### ISSUE TITLE
MCP23017 IO & Hue Emulation

### ISSUE THREAD

**Issue by BBBits** [arendst/Sonoff-Tasmota#6456]
Can the MCP23017 IO be included in Hue Emulation Device Discovery ?

**Comment by Jason2866** [comment]
At the moment no.

**Comment by BBBits** [comment]
Ok, thanks.
I see that the max hue devices is limited to 15.
is this a limitation of the device hue emulation type or just a decision made for some reason ?

**Comment by Jason2866** [comment]
@s-hadinger  Can you answer the question from @BBBits ?

**Comment by s-hadinger** [comment]
This limit of 15 is completely arbitrary. However the max number of Relays+ light is lower. Changing this number requires also to change the Hue ID assignment. Do you see this limit as an issue?

**Comment by BBBits** [comment]
If support was to be added for mcp23017 , that would add up to 16 for each address.

**Comment by s-hadinger** [comment]
It looks doable to extend to 31 devices. Internal settings shows that `power` is coded on 32 bits so it should be able to support 32 Relays. 

You would still need to add mcp23017 support

**Comment by s-hadinger** [comment]
I looked at it, it's easy to increase the number of devices controlled by Hue emulation to 32. Beyond that number it breaks other parts of the code. I will post a small PR in the following days.

**Comment by s-hadinger** [comment]
@BBBits I posted a PR to increase Hue devices to 32.

MCP23017 doc is here: https://github.com/arendst/Sonoff-Tasmota/wiki/MCP23008-MCP23017

However, I think it is still missing the matching between Tasmota Relays and the sensor29 command. I'm not sure you can do this with rules or scripting.

**Comment by BBBits** [comment]
Cool , Thanks .
Dunno If I have all the skills to address the hue integration of the MCP but will certainly see If I can figure it out.

**Comment by Jason2866** [comment]
Isnt a friendly name needed for each relay (output)? So there will be the next restriction...

**Comment by s-hadinger** [comment]
It used to be a limit, but it changed when `SetOption68` was introduced. The first 4 devices take their names from friendlyname[1..4]. The 5th and above are named after <friendlyname4>-0<01..xx>.

But indeed there is a problem when there are more than 14 devices, it will use characters after '9' which may cause issues.

Good catch @Jason2866 ! On my TODO list

**Comment by Jason2866** [comment]
Now it is up to you @BBBits to write rules or do it via scripter engine.

**Comment by BBBits** [comment]
eek .. stumped.
can we create rules that generate hue devices ?

**Comment by Jason2866** [comment]
@thxthx0 can you help? You have scripter experience :-)

**Comment by thxthx0** [comment]
I'm afraid not nearly experienced enough... ;)

I agree with s-hadinger:
> still missing the matching between Tasmota Relays and the sensor29 command...

You could define virtual relays and control the MCP23017 outputs according via script,
so that they'll be discovered by HUE Emu - 
but there will remain the limit of 8 relays in Tasmota.

I think if anyone can help, @gemu2015 is the right address :)

**Comment by gemu2015** [comment]
send sensor29 cmds on change of a power state of a tasmota defined relay

\>D
; relais 1..N power state
p1=0
p2=0
etc

\>E
; get power state
p1=pwr[1]
; if there is a change
; then set appropriate output pin
if chg[p1]>0
then
if p1>0
then
->sensor29 0,ON
else
->sensor29 0,OFF
endif
endif
etc

the fanciest solution would be to have a scripter section >H
where you could define virtual hue devices and assign them to script variables
i looked into it. it is doable but a considerable amount of work.

**Comment by s-hadinger** [comment]
Thanks @gemu2015 

Hue devices follow the `devices_present` variable, which gives the overall controllable devices. This variable is computed in `GpioInit()` in `sonoff.ino`. I'm not sure whether you can change this variable with scripting **before** Hue or lights are initialized.

**Comment by Jason2866** [comment]
Thanks @gemu2015 for implementing!!

See Example https://github.com/arendst/Sonoff-Tasmota/pull/6522#issuecomment-536589939
