### ISSUE TITLE
Single Quote in SSID name will connect but not shown

### ISSUE THREAD

**Issue by roelbroersma** [arendst/Sonoff-Tasmota#6458]
Hi,

Just installed Tasmoto (v6.6.0) on an ESP01 8266 4MB Flash.    It connects via WiFi to an SSID with a single quote in it, like:

Roel's Wifi

Although it will connect,  going to the WiFi page again will only show:   Roel   instead of: Roel's WiFi

I think there is a problem with quotes/escaping ..

**Comment by Jason2866** [comment]
Lucky it works. No special characters allowed in Tasmota.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
