### ISSUE TITLE
Fixed: Sonoff POW bad topics (anyone seen this?)

### ISSUE THREAD

**Issue by tascar01** [arendst/Sonoff-Tasmota#646]
Yesterday I installed two sonoff basic's and a sonoffpow, all serial and at the same time using Arduino IO, set-up each with the browser access.

The two basic's work OK, but the POW (being set to POW) shows data in the browser, but the MQTT topics are as below.

I can see the topics in mqtt-spy, but can't pickup the topics from Node-red or Home Assistant.

![image](https://user-images.githubusercontent.com/29986572/28635440-e7fea38a-723a-11e7-9449-be0a9824dced.png)

Anybody seen this? or has a solution. I used 5.3.0 code

**Comment by arendst** [comment]
Check your prefix1, prefix2, prefix3 and fulltopic settings via the web console.

**Comment by tascar01** [comment]
Sorry not sure where you mean, only topics I could find on the web console (192.168.1.19) is in the Configure MQTT Tab, this is the list from the Information Tab.

 
![image](https://user-images.githubusercontent.com/29986572/28638287-b8b3409a-7244-11e7-8256-bdae500dea4e.png)
or am I looking in the wrong place?

**Comment by arendst** [comment]
- Goto the console webpage
- Type prefix1 and hit return key
- Read respone on console
- Same for prefix2 and prefix3.

If strange results see the wiki comma ds section and fill with cmns, stat and tele.

**Comment by tascar01** [comment]
I did all three and they returned 
![image](https://user-images.githubusercontent.com/29986572/28639857-e9804d1c-7249-11e7-9556-79decf92a43c.png)
but with 2 and 3 for the others, what do I meed to change?

**Comment by arendst** [comment]
What is a console....

One of the sonoff webpages is called Console. Just select the console butten and start entering commands please.

**Comment by tascar01** [comment]
Sorry I didn't understand, the output is
![image](https://user-images.githubusercontent.com/29986572/28640129-09727388-724b-11e7-8ed2-e9789d7adcb8.png)

**Comment by arendst** [comment]
And compare with one of your other sonoffs. Then just enter that info via the console: prefix1 cmnd, prefix2 stat and prefix3 tele.

**Comment by tascar01** [comment]
This is from one of the basic done at the same time and is working OK
![image](https://user-images.githubusercontent.com/29986572/28640357-c0c810a6-724b-11e7-84c8-7859fa58b1b9.png)

**Comment by arendst** [comment]
So what's the next step? Hint read my last entry.

**Comment by tascar01** [comment]
If strange results see the wiki commands section and fill with cmnd, stat and tele.

Will have a good look and let you know if I sort it, or don't.

Many Thanks, will leave this open until a result

**Comment by tascar01** [comment]
Many Thanks, all sorted and working.
