### ISSUE TITLE
Sonoff basic ESP8285 doesn't show config

### ISSUE THREAD

**Issue by Cysign** [arendst/Sonoff-Tasmota#6484]
Just flashed an ESP8285 using the FlashESP8266.exe tool (running on Win10) using the sonoff-basic.bin file.
LED blinks and I'm able to connect my smartphone to it, using fing to see the device's IP: 192.168.244.1 (on a previous try it was 192.168.4.1).
Sometimes device stops to blink. 

But I cannot connect to the config-page using firefox (on Android). Looks like a timeout.
Don't know how to find more information about this...

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
