### ISSUE TITLE
Flashing in DIY mode through terminal on mac: "curl: (52) Empty reply from server"

### ISSUE THREAD

**Issue by dakkerd** [arendst/Sonoff-Tasmota#6485]
To give full context: I'm on a macbook pro, and first followed the guide of Drzzs. It explains how to flash through the DIY tools, on windows. I thusly installed boot camp and Win 10. I got the Sonoff on the list, and was able to change its SSID. On flashing it halts on 0%. Not sure why. 

I therefore tried the mac method, as explained on the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-DIY). All goes well, yet flashing halts. 
I have a webserver (MAMP, locally on my mac) which I can evoke through the IP. I have the bin there, and should flash. I use the line:
`curl http://ip_device:8081/zeroconf/ota_flash -XPOST --data '{"deviceid":"<deviceID>","data":{"downloadUrl": "http://ip-mac-server:8888/sonoff-basic.bin", "sha256sum": "09c1ddf1374e69a8a092b29d17733f775f36dfd0c00ff4fcf34fdee898418619"}}'`

Then I get the error `curl: (52) Empty reply from server`

Any pointers?

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
