### ISSUE TITLE
Sonoff Touch T1 2CH turn on itself

### ISSUE THREAD

**Issue by giacomotontini** [arendst/Sonoff-Tasmota#6487]
I'm using a sonoff touch t1 with mqtt, integrated with Hassio
All retained options are disabled, but sometimes the light turn on itself. 

My router's wifi is disabled turing night, but the problem happens independently from this.
WifiConfig is set to 5.
That's the log capturing the issue

```
21:45:51 MQT: tele/sonoff/STATE = {"Time":"2019-09-24T21:45:51","Uptime":"0T05:41:33","Heap":15,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"FSOCIETY-MAIN","BSSId":"0C:B6:D2_dropped","Channel":6,"RSSI":52,"LinkCount":2,"Downtime":"0T00:00:08"}}
21:50:51 MQT: tele/sonoff/STATE = {"Time":"2019-09-24T21:50:51","Uptime":"0T05:46:33","Heap":15,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"FSOCIETY-MAIN","BSSId":"0C:B6:D2_dropped","Channel":6,"RSSI":48,"LinkCount":2,"Downtime":"0T00:00:08"}}
21:54:17 APP: Button2 immediate
21:54:17 SRC: Button
21:54:17 MQT: stat/sonoff/RESULT = {"POWER2":"ON"}
21:54:17 MQT: stat/sonoff/POWER2 = ON (retained)
21:54:17 CFG: Saved to flash at FA, Count 981, Bytes 3584`

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, search in issues as this has been addressed before. Or ask in the Tasmota support chat. If your issue persist, please open a new issue with the troubleshooting template completed. Thanks 

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
