### ISSUE TITLE
h801 all leds flash on when applying power

### ISSUE THREAD

**Issue by jormus** [arendst/Sonoff-Tasmota#649]
hi,

I take away the voltage of the h801 controller when i'm not using it, but when I apply voltage, the leds flash on for like 50 ms. This looks like somebody is flashing with a camera, because my led strips are RGBWA all in one. Can this be disabled somehow?

thx

**Comment by arendst** [comment]
I guess not as it's the result of initial power up of the esp8266 having set the pwm ports to a default stae before the firmware kicks in.

Same happens on my BN-SZ ceiling led. Just leave the power on and turn the led off.

**Comment by ramafun** [comment]
I have the same issue. I don't think it is due to a HW problem, because when I leave the original firmware and configure with ewelink, it doesn't blink on powering up.

**Comment by andriej** [comment]
Exactly the same issue

**Comment by bernhardhauffen** [comment]
I have the same issue. With the orignial FM the leds are not flashing while powering up.
