### ISSUE TITLE
Cannot connect to Sonoff Basic R2

### ISSUE THREAD

**Issue by Rndix** [arendst/Sonoff-Tasmota#6492]
Hello,
i am not able to flash my Sonoff Basic R2.

Log on ESP EASY Flasher and nearly the same on FlashESP8266.exe:
[Basic_20190925162418.txt](https://github.com/arendst/Sonoff-Tasmota/files/3653026/Basic_20190925162418.txt)
NodeMCU Flasher: it does not connect

here is the guide
https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Basic

I tried it with the ESPEasy Flasher and with the Node MCU Flasher. I have also tried to switch RX and TX but it did not work for me. The weird thing is that it worked for the Sonoff SV and the Magic Home LED Controller (Arilux LC03).

Hopefully someone can help me!
Greetings from Germany

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
