### ISSUE TITLE
YTF IR Bridge flashed but can not configure IR ...

### ISSUE THREAD

**Issue by Eddie-BS** [arendst/Sonoff-Tasmota#6493]
Hi,

I did succesfully flash an YTF IR bridge with tuys convert (ran on RPI)
the YTF comes online as basic sonoff device and I can start configuring it.
I did change the device type to YTF IR Bridge (62) and the device reboots.
After that I do not have the 

GPIO | Component | Description
-- | -- | --
04 | LED1i (52) | Blue LED - Link status
05 | IRrecv (51) | IR Receiver
13 | Button1 (17) | Button
14 | IRsend (8) | IR Transmitter

setting to configure, it shows :

<img width="420" alt="Screen Shot 2019-09-25 at 16 58 25" src="https://user-images.githubusercontent.com/10174704/65613117-bb8a7a00-dfb5-11e9-8ec7-9b6b37c0f31c.png">

Am I missing something ?

regards,
Eddie

**Comment by arendst** [comment]
You're missing nothing. The GPIO's used by the device are invisible.

**Comment by Eddie-BS** [comment]
thanks Theo,
any suggestions in how to configure this further to send and receive signals ?

**Comment by meingraham** [comment]
@Eddie-BS 

Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Eddie-BS** [comment]
@meingraham tnx, I will close the issue and try to find a solution myself.
