### ISSUE TITLE
support.ini Line 128: "first" contain invalud UTF-8 character

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#6509]
Small typo in file prevent compiling. /x81 is unknown

**Comment by arendst** [comment]
???

See https://github.com/stefanbode/Sonoff-Tasmota/issues/192#issuecomment-536280906

**Comment by stefanbode** [comment]
The "fi" in the word "first" in line 128 in support.ino is a vary strange UTF8 character. I cannot compile it. Replacing it with "fi" solves the problem

**Comment by arendst** [comment]
Thx!!!

That's what I get with copy and paste. Will change now.

**Comment by ascillato2** [comment]
Closing this issue as it has been fixed. Thanks.
