### ISSUE TITLE
sonoff-basic.bin on sonoff mini doesnt switch topic with option19

### ISSUE THREAD

**Issue by magiva** [arendst/Sonoff-Tasmota#6513]
### BUG DESCRIPTION
If i flash a sonoff mini DIY with sonoff-basic.bin and setOption19 1, normally this would switch the function/name round for auto discovery, it doesnt

  Configuration output here:
  after setting up mqtt, i see stat/name/power etc
i then set option 19 to on, normally i would see the mqtt change to name/stat/power but this doesnt happen

**Comment by Jason2866** [comment]
Sonoff-Basic doesnt support this feature. Upgrade to sonoff.bin

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
