### ISSUE TITLE
Help, friends on how to set the button set!

### ISSUE THREAD

**Issue by 1043717432** [arendst/Sonoff-Tasmota#652]
Sorry, I re-described! A total of 4 jog switch, I want to achieve switch 1, switch 2, switch 3, any open one, the other two automatically shut down. The While switch 4 is primarily responsible for closing all switches.

**Comment by davidelang** [comment]
please try to re-state what you are trying to do, it's not clear what you are 
asking.

**Comment by 1043717432** [comment]
@davidelang   Hello there!
   Is this, I think the firmware used in the garage door and aisle switch, my switch is self-resetting jog switch, scene 1: when I open the switch 1, and then open the switch 2, this time switch 1 will automatically shut down.
Scenario 2: The switch 1 is turned on and the switch 2 is automatically turned off. If the switch 3 is turned on, the switch 1 and the switch 2 are automatically turned off. Scenario 3: When I turn on the switch 4, switch 1, switch 2, switch 3, if it is in the state, will become off.

**Comment by davidelang** [comment]
the tasmota firmware does not do this sort of thing in the firmware, you would 
do this sort of thing in the home automation software.

The tasmota firmware is focused on providing the ability to control the switch 
to automation software.

**Comment by arendst** [comment]
Using the Sonoff 4ch pro in interlock mode does just that; the microcontroller only allows one relay active or no relay active.

Installing Tasmota on this device allows also mqtt control providing the same interlock mode.

**Comment by 1043717432** [comment]
How to use mqtt to complete this operation?tks

**Comment by 1043717432** [comment]
Hello, the author.
I was esp8266 development board, can the firmware choose Sonoff 4ch pro?

**Comment by davidelang** [comment]
It's not clear what you are asking, but Tasmota can be installed on any esp8266 
and you select the module type that matches the hardware that's attached to the 
esp.

**Comment by 1043717432** [comment]
I would like to ask how to use 8266esp + relay, for example: Sonoff 4ch pro interlock mode is the case, in the firmware web how to choose sonoff 4ch pro firmware?

**Comment by davidelang** [comment]
this project supplies the tasmota firmware (and it's source code), not the 
sonoff 4ch pro firmware, you would have to contact sonoff to get details on 
their firmware.

As I understand it from watching the discussions, there may be additional 
hardware involved with some of those features.

the plain sonoff setting will let you have an esp8266 + relay and will work just 
fine. With only one relay, "interlock mode" is a meaningless term.

If you have multiple relays, Tasmota doesn't have any controls that care about 
the state of one when changing the state of others, that is up to your home 
automation software. Tasmota just provides a way for that automation software to 
communicate with the esp8266 and control the relay(s) that are connected to it.

**Comment by 1043717432** [comment]
Thank you! Is my ability to express well! This diy is not getting it for the time being. @davidelang

**Comment by 1043717432** [comment]
@davidelang  Thank you! Is my ability to express my mistakes! This diy is not getting it for the time being.
