### ISSUE TITLE
Sonoff Rf Bridge and Sonoff Smoke Detector 

### ISSUE THREAD

**Issue by wumpsven** [arendst/Sonoff-Tasmota#6528]
Hello

I have my raspberry running on Homebridge, and all of my sonoff's are controlled via mqttthing.
Now I would just like to embed my RfBridge with Tasmota 6.6.0, the Sonoff smoke detector C50W. Unfortunately, I find nothing online at all. Of course it can be that it does not work fundamentally.
Maybe you can help.

**Comment by ascillato** [comment]
Hi,

The smoke detector C50W is not from itead sonoff but it is 100% compatible with the sonoff bridge

Itead Official: https://www.itead.cc/smart-home.html

Itead Support for this type of devices: https://support.itead.cc/support/discussions/topics/11000019077

Smoke Detector:
https://www.banggood.com/3-in-1-C50W-Smoke-Detector-Sound-Light-Sound-Alarm-Wireless-433-Transmission-p-1387757.html?utm_source=google&utm_medium=cpc_ods&utm_campaign=nancy-content-sdsrm-motor-all-content&utm_content=nancy&ad_id=197162953176&gclid=Cj0KCQjwz8bsBRC6ARIsAEyNnvomMQy5bWyAb8aYFO1NmkuL3VXVRUhEEPqwpxBByIyWZc_TvrLUlJYaAoBuEALw_wcB&cur_warehouse=CN

https://www.gearbest.com/alarm-systems/pp_009974155184.html

So, if you don't receive anything on your sonoff bridge, may be the smoke detector is not working.

If you need further help on how to troubleshoot this, please use the manufacturer page, or the Itead Support, or if using Tasmota on the bridge, please use the Tasmota Support chat. Thanks

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
