### ISSUE TITLE
Can't use all 4 GPIOs simultaneously

### ISSUE THREAD

**Issue by bluebird11** [arendst/Sonoff-Tasmota#653]
I have a Sonoff Basic and it has 4 GPIOs (as shown in the wiki here https://github.com/arendst/Sonoff-Tasmota/wiki/GPIO-Locations). I can successfully address each of them individually, but I can't use more than 3 of them in the same time (there are only options for Relay2...Relay4). I also tried setting a GPIO as a LED, but I couldn't make it go on ("cmnd/ledpower2 on" only changes the state of the main LED, not of the GPIO)...

And another question: When I reboot the module, GPIO 01 (RX PIN) toggles the state several times quickly. Can I prevent it somehow? I read that disabling serial logging should help, but it didn't solve this.

Is this a hardware limitation or am I doing something wrong? Thanks!

**Comment by davidelang** [comment]
On Fri, 28 Jul 2017, bluebird11 wrote:

> I have a Sonoff Basic and it has 4 GPIOs (as shown in the wiki here 
> https://github.com/arendst/Sonoff-Tasmota/wiki/GPIO-Locations). I can 
> successfully address each of them individually, but I can't use more than 3 of 
> them in the same time (there are only options for Relay2...Relay4). I also 
> tried setting a GPIO as a LED, but I couldn't make it go on ("cmnd/ledpower2 
> on" only changes the state of the main LED, not of the GPIO)...

how do you have the module configured? if you have all four relayX outputs 
defined, you should have power1-power4, if you only have relay2-4 defined you 
won't have power1 defined

> Is this a hardware limitation or am I doing something wrong? Thanks!

it's something in your config, show us how you have the module configured.

**Comment by bluebird11** [comment]
Hmmm, I only have relay 2...4 resp. 2l...4l to choose from in the drop-down menu. I do see power 1...4 but power1 is always the main relay. I'll post a screenshot when I get home.

**Comment by davidelang** [comment]
so you you have power1-power4 defined.

What is it you are trying to do that's failing?

**Comment by bluebird11** [comment]
Sorry for not explaining it clearer.

Power1 seems to always be controlling the main relay (gpio12) and that's ok. I want to be able to control it and also gpio 1, 3, 4, 14. I can control them all separately by assigning relay2..4 to them. So I kind of need an option relay5. I hope it's better explained this time and thank you for your help.

**Comment by davidelang** [comment]
Tasmota only supports 4 relays. This is defined in sonoff_templates.ino, but 
there may be assumptions in the code as well about only having 4 of anything.

**Comment by bluebird11** [comment]
Thank you very much for the information and the help!

I skimmed through the code and changed it at a few places and now it does exactly what I want. It was much easier than I thought :) If anyone is interested, I can provide the changes and I hope arendst would consider adding support for 4 relays.

**Comment by davidelang** [comment]
On Sat, 29 Jul 2017, bluebird11 wrote:

> I skimmed through the code and changed it at a few places and now it does 
> exactly what I want. It was much easier than I thought :) If anyone is 
> interested, I can provide the changes and I hope arendst would consider adding 
> support for 4 relays.

it already supports 4 relays, you want it to support 5 or more :-)

you aren't the first person to ask this. The problem is that the current 
firmware has an enumerated list of all possible items, and increasing from 4 to 
8 (a common request) means that you create 4 more relays, 4 more inverted 
relays, 4 more LEDs, 4 more inverted LEDs, 4 more buttons, 4 more switches (and 
I've probably forgotten something). This makes the lists very long.

What needs to happen is to switch from static enumeration to a dynamic list 
where you can 'create' items and add them to the list. That way there can be any 
number of a particular type of items, and more complex items (encoders, 
interconnected outputs for driving motors, etc). But that would be a major 
change in the code and almost requires a fork to do it right.

**Comment by bluebird11** [comment]
Ok, thanks for the clarification. Until there is a proper official solution, I'll have to live with my hack.

What does the led option do by the way? When I set a gpio as led and change its state from the console nothing happens.

**Comment by JoePala** [comment]
Hi Bluebird,

I'm in a situation similar to yours.  I'm using a Wemos D1 mini and I want to use it to control six relays.  Can you share the hack you made with me?  You can either reply here, or take it off the issues page and email me directly to my address in my profile page.

I'm also confused about the use of LED as gpio.  Plese share if you get an answer to that.

Joe

**Comment by bluebird11** [comment]
It's not much, so I'll simply share it here "manually":

In sonoff.ino
below
#define VERSION
add
#define NUM_DEV                5 // number of relays

change
uint8_t rel_inverted[4] = { 0 };      // Relay inverted flag (1 = (0 = On, 1 = Off))
to
uint8_t rel_inverted[NUM_DEV] = { 0 };      // Relay inverted flag (1 = (0 = On, 1 = Off))

change
if ((mpin >= GPIO_REL1_INV) && (mpin <= GPIO_REL4_INV)) {
        rel_inverted[mpin - GPIO_REL1_INV] = 1;
        mpin -= 4;
}
to
if ((mpin >= GPIO_REL1_INV) && (mpin <= GPIO_REL5_INV)) {
        rel_inverted[mpin - GPIO_REL1_INV] = 1;
        mpin -= NUM_DEV;
}

change
for (byte i = 0; i < 4; i++) {
      if (pin[GPIO_REL1 +i] < 99) {
        pinMode(pin[GPIO_REL1 +i], OUTPUT);
        Maxdevice++;
      }
      if (pin[GPIO_KEY1 +i] < 99) {
        pinMode(pin[GPIO_KEY1 +i], INPUT_PULLUP);
      }
}
to
for (byte i = 0; i < NUM_DEV; i++) { // Yassen
      if (pin[GPIO_REL1 +i] < 99) {
        pinMode(pin[GPIO_REL1 +i], OUTPUT);
        Maxdevice++;
      }
      if (pin[GPIO_KEY1 +i] < 99) {
        pinMode(pin[GPIO_KEY1 +i], INPUT_PULLUP);
      }
}

in sonoff_template.h:
below
GPIO_REL4,
add
GPIO_REL5,

below
GPIO_REL4_INV,
add
GPIO_REL5_INV,

below
"Relay4",
add
"Relay5",

below
"Relay4I",
add
"Relay5l",

In webserver.ino:
change
  if (((val >= GPIO_REL1) && (val <= GPIO_REL4)) || ((val >= GPIO_LED1) && (val <= GPIO_LED4))) {
    offset = 4;
  }
  if (((val >= GPIO_REL1_INV) && (val <= GPIO_REL4_INV)) || ((val >= GPIO_LED1_INV) && (val <= GPIO_LED4_INV))) {
    offset = -4;
  }
to
  if (((val >= GPIO_REL1) && (val <= GPIO_REL5)) || ((val >= GPIO_LED1) && (val <= GPIO_LED4))) {
    offset = NUM_DEV;
  }
  if (((val >= GPIO_REL1_INV) && (val <= GPIO_REL5_INV)) || ((val >= GPIO_LED1_INV) && (val <= GPIO_LED4_INV))) {
    offset = -NUM_DEV;
  }

That's it. It might be ugly and not elegant, but it works for me and as far as I can tell it doesn't break anything.

**Comment by stefanbode** [comment]
Yes, up to eight the change is easy. Beyond eight major changes are required and require more memory, because status is stored in a byte variable (8bit) and this must be changed to uint32 at several places. And also some calculation work still with FF as a logic combine. Also, change here required. I supposed to stay at 4 as it is. And maybe extend to 8. Additional code is always expensive, because the EPS8266 is limited, even if it does not look like. Arendt is spending a lot of time to keep it small as possible.
