### ISSUE TITLE
Using a non-polarity bi colour (Red/Blue Diode) with Tasmota

### ISSUE THREAD

**Issue by MaliMrav** [arendst/Sonoff-Tasmota#6532]
Hi there,

I have modified a Orvibo (Bauhn) S20 Wi-Fi switch and replaced the HF-LBP100 CPU with an ESP8266 (ESP-07s) and have loaded Sonoff Tasmota onto it.

everything works ok except the non-polarity bi colour LED.

![Screen Shot 2019-10-01 at 9 13 49 pm](https://user-images.githubusercontent.com/6211939/65957913-71ac0300-e491-11e9-9a45-b6c38670ce72.png) 
![Screen Shot 2019-10-01 at 9 14 41 pm](https://user-images.githubusercontent.com/6211939/65958664-44f8eb00-e493-11e9-8559-23f7eb72c452.png)

In my case I have connected one side of the diode to GPIO13 and the other to GPIO14.

What I'd like to achieve the following:
1. When the device is powering on, I'd like it to blink red
2. When Wi-Fi is connected (and relay off), I'd like it to stay solid red 
3. When the button is pressed (or via command/MQTT/etc), the relay is activate and the LED needs to go solid blue.

To achieve the first 2 was easy, in fact, by default, this is what happens. however for the Blue led to fire up the polarity needs to be reversed. i.e. GPIO13 needs to go low and GPIO14 high

I tried for ages to wok through the LedState, LedPower and LedMask commands but I cannot see any way to turn off the LED PowerState when turning on the LedRelay state. like an XOR.

any suggestions?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
