### ISSUE TITLE
Increase number of timers

### ISSUE THREAD

**Issue by Lawrencezarb** [arendst/Sonoff-Tasmota#6536]
I was running version 6.5.0.9, and increased the number of timers available from 16 to 64 by increasing the MAX_TIMERS value and recompilimg the firmware.

I tried it with the latest version, but when my D1 mini reboots it is stuck in AP mode, and although it accepts my SSID and password, it continue to be in AP mode after the reboot.

**Comment by arendst** [comment]
As you are aware of the consequences of increasing the amount of timers you could conclude yourselves that it will fail with latest versions using the full 4k flash page.

If you need more timers you will need to redesign the 4k setting area.
