### ISSUE TITLE
addtional / different security level for configuration menus

### ISSUE THREAD

**Issue by species5618** [arendst/Sonoff-Tasmota#6543]
Would it be possible to manage security differently for the home page (data display / control) and the configuration / management pages

For my use case, only applying password to management pages, and leaving front page unprotected is an option

I would like to allow anyone in the house hold / network (share space) to access the device, but not be able to change any of the setup.

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, check commands in the wiki. Thanks. If you need further assistant, please find us in the Tasmota support chat. Thanks 

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
