### ISSUE TITLE
Fixed: Sonoff 4CH Rev 2.0 - GPIO Bug ?

### ISSUE THREAD

**Issue by noxx2015** [arendst/Sonoff-Tasmota#655]
hello 

i try 4 versions of Tasmota (also sonoff-ds18x20.bin e.g. Rev 5.4.0) and ESPeasy, on 2 different Sonoffs 4 CH (both Rev 2.0).
Also 4 different DS18b20. But non of them show me values of my temp-sensor :-(

is a hardware bug in rev 2.0 possible?

`

Program version | 5.4.0
-- | --
2017-07-25T16:38:37
2_3_0/1.5.3(aec24ac9)
22 Hours
144 at F7000
58
Software/System restart
Sonoff1
Sonoff2
Sonoff3
Sonoff4
 
FRITZ!Box Fon WLAN 7390 (90%)
sonoff-4707
192.168.1.72
192.168.1.1
255.255.255.0
192.168.1.1
60:01:94:85:72:63
 
192.168.1.9
1883
DVES_857263
iobroker
sonoff
sonoffs
cmnd/sonoff/
 
Hue Bridge
Enabled
Webserver
 
8745571
1327185
1024kB
1024kB
474kB
528kB
24kB

`

![1](https://user-images.githubusercontent.com/12627059/28730058-f42d5e68-73ce-11e7-8206-111283025bcd.PNG)

![2](https://user-images.githubusercontent.com/12627059/28730066-f93aaafa-73ce-11e7-883e-1927c00d9125.PNG)

**Comment by arendst** [comment]
Where do you connect the ds18b20 sensor?

**Comment by noxx2015** [comment]
DS18B20:
Black on GND
Red on VCC33
Yellow on I02

![1](https://user-images.githubusercontent.com/12627059/28732782-8d622f14-73d9-11e7-8201-805a1dce8a76.PNG)

**Comment by arendst** [comment]
I guess you will need a 10k resistor between 3V3 and IO2

**Comment by noxx2015** [comment]
thx, thats was it

![2](https://user-images.githubusercontent.com/12627059/28743086-53f6db2c-7441-11e7-9316-e551ac1b45e6.PNG)
