### ISSUE TITLE
Two way switch with sync status

### ISSUE THREAD

**Issue by AdvaitT17** [arendst/Sonoff-Tasmota#6553]
I have a sonoff 4 ch pro and 4 two-way switches...I want to connect them such that when I will use the regular two-way switch it will get sync within the app as well. Is this possible? Please help...

**Comment by Jason2866** [comment]
From which app do you speak?
4 two way switches how does it work now? Without a exact explanation what you want to achive
no one can help you. A drawing how it is wired now would help...

**Comment by jziolkowski** [comment]
This is not strictly a Tasmota issue; please visit the Discord support server at https://discord.gg/Ks2Kzd4
