### ISSUE TITLE
Tuya 3 Switch Gang - Switch Names

### ISSUE THREAD

**Issue by danmed** [arendst/Sonoff-Tasmota#6566]
I'm running Tasmota 6.6.0 on a 3 gang extension lead.

I've set friendly names for all 3 sockets and when i setoption19 1, they all appear with their friendly names in Home Assistant.. However, only the first socket has a sensible Entity ID of switch.friendly_name.. the others are all switch.sonoff2, switch.sonoff3.

How do i get these switches to have sensible entity ID's? The way i see it, i can only use one of these 3 gangs now as they will be published as the same switch names in HA...

I'm using this template if it matters : https://blakadder.github.io/templates/yagala_SWB3.html

**Comment by meingraham** [comment]
Please close this issue address this question to the Home Assistant Discord server - https://discord.gg/c5DvZ4e
