### ISSUE TITLE
Flashing Sonoff T3EU3C

### ISSUE THREAD

**Issue by Wilhelm1Daniel** [arendst/Sonoff-Tasmota#6569]
Hello Members,

At first sorry for my english...

Last week I've bought a Sonoff T3EU3C.
Now I have the problem to find out the placement of the GPIO 0 to setup the device in FlashMode.

There's a sign on the backside of the platine, but I'm not sure about the exactly position...

Thanks for help

![20191001_170539](https://user-images.githubusercontent.com/47296950/66255894-42dfa680-e789-11e9-9f77-0fab4d2eb26b.jpg)
![20191001_173515](https://user-images.githubusercontent.com/47296950/66255895-42dfa680-e789-11e9-9323-a405a8717a51.jpg)
![20191001_173525](https://user-images.githubusercontent.com/47296950/66255896-42dfa680-e789-11e9-8b5f-180ba1f7c87f.jpg)
![20191001_173629](https://user-images.githubusercontent.com/47296950/66255897-43783d00-e789-11e9-8a40-0b2f8bd59f0d.jpg)
![20191001_173637](https://user-images.githubusercontent.com/47296950/66255898-43783d00-e789-11e9-9167-56f04d123bf5.jpg)

**Comment by meingraham** [comment]
As the template states when you open a new issue, these kinds of questions should be directed to the Discord chat.

Does TP2 not work as the GPIO0 contact?

Please close this issue and address any reamining questions to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
