### ISSUE TITLE
Support/help template for Magichome Arilux SL-LC 10

### ISSUE THREAD

**Issue by ceraz68** [arendst/Sonoff-Tasmota#6588]
I'm fighting to get the IR remote work with this model Magichome aka Arilux SC LC 10 from [here](https://www.banggood.com/ARILUX-AL-LC10-Super-Mini-LED-WIFI-APP-Controller-RF-Remote-Control-For-RGBW-LED-Strip-DC9-28V-p-1085111.html?cur_warehouse=CN) 

It's the RGB version with a small IR remote. Tasmota 6.6.0 installed and working with the generic template for module configuration. I found PWM1 (37) is on GPIO5, PWM3 (39) is on GPIO12 and PWM2 (37) is on GPIO14. But I can't figure out IR control.

I followed the wiki for the LC 11 version[here](https://github.com/arendst/Sonoff-Tasmota/wiki/MagicHome-with-ESP8285) but when I assign the IrRcv (51) to GPIO4 console goes crazy with tele reports:

21:46:43 MQT: tele/sonoffLEDtv/RESULT = {"IrReceived":{"Protocol":"UNKNOWN","Bits":50,"Data":"0x000003F817FAE"}}
21:46:43 MQT: tele/sonoffLEDtv/RESULT = {"IrReceived":{"Protocol":"UNKNOWN","Bits":50,"Data":"0x000006BC4673C"}}
21:46:44 MQT: tele/sonoffLEDtv/RESULT = {"IrReceived":{"Protocol":"UNKNOWN","Bits":50,"Data":"0x00000A9955047"}}

I tried using Arilux Rrcv(149) like in the LC 11 template but nothing is reported in the console. Tried different IO ports based on the generic template but no trace of IR reception in the console.

It's hard to find out which IO port to use and which ir receiver function to use with this model.

Has anybody succeeded with this LED controller variant?

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
