### ISSUE TITLE
Display and Domoticz

### ISSUE THREAD

**Issue by mmaxx74** [arendst/Sonoff-Tasmota#6590]
Hi, can anyone help me?
i tried tasmota compiler, i need to load tasmota with lcd display and to have i domoticz settings. i tried different versions, but it doesn't work together.
I need the DS18b20 sensor to be displayed on the LCD and simultaneously sent the temperature to domoticz.
Can someone help me ? Thank you very much .

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by mmaxx74** [comment]
Hello , where i find tasmota support chat ?
Can you get link . Thanks .

Dne út 8. 10. 2019 14:27 uživatel Adrian Scillato <notifications@github.com>
napsal:

**Comment by ascillato** [comment]
In the previous comment is the link

**Comment by mmaxx74** [comment]
Ok thanks.

Dne út 8. 10. 2019 19:46 uživatel Adrian Scillato <notifications@github.com>
napsal:
