### ISSUE TITLE
Tuya MCU add support for 2 bytes brightness

### ISSUE THREAD

**Issue by Nonsense1112** [arendst/Sonoff-Tasmota#6605]
**Have you looked for this feature in other issues and in the wiki?**  
Yes
**Is your feature request related to a problem? Please describe.**  
_A clear and concise description of what the problem is._

No, it's an enhancement.

**Describe the solution you'd like**  
_A clear and concise description of what you want to happen._

I would like that Tuya MCU module to have support for 2byte brightness values.

Older models of Tuya dimmer uses a range of 1-255 on last byte that is sent to dimming MCU.

Some new models uses now the last 2 bytes as brightness data, with value between 10-1000

**Describe alternatives you've considered**  
_A clear and concise description of any alternative solutions or features you've considered._
Option to select the range for dimming above 255.

**Additional context**  
_Add any other context or screenshots about the feature request here._

I'm using tasmota 6.6.016 with Moes Dimmer DS01C.
The minimum brightness command used by this MCU is:
55 AA 00 06 00 08 02 02 00 04 00 00 00 0A 1F

and for maximum brightness, command is:
55 AA 00 06 00 08 02 02 00 04 00 00 03 E8 00

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by ascillato** [comment]
@Nonsense1112

Your request has been added by @shantur on PR #6606

Please, can you test it? Thanks

**Comment by Nonsense1112** [comment]
Hi,
It works now.
The only problem is with the range below touch slider minimum.
the touch minimum is 55aa0307000802020004000000b4cd

If I want to dim the lights below the touch minimum using the switch, I have to double press the button, but the mcu send a package of 55aa0307000802020004000000b4cd and updates tasmota brightness.
But I don't think there is something that it can be done, because tasmota can't know the difference between the slider minimum and button double press, as the mcu send the same response for both.

Thank you!
