### ISSUE TITLE
merkury ww105 smart wifi plug

### ISSUE THREAD

**Issue by or78rXxZ** [arendst/Sonoff-Tasmota#6613]
i picked up one of these at walmart today for about $8
the package is glued so i had to be a bit destructive to get in to it
i found it had a tywe2s the same as described here
https://github.com/arendst/Sonoff-Tasmota/wiki/CE-Smart-Home---LA-WF3-Wifi-Plug-(TYWE2S)
i searched a bit and found an ota method to update it
http://www.thesmarthomehookup.com/tuya-convert-walk-through-february-2019/
i followed the instructions and tasmota loaded without a hitch

**Comment by ascillato2** [comment]
Great!

Thanks.
