### ISSUE TITLE
Change of LedPower affect LedState?

### ISSUE THREAD

**Issue by mkh595** [arendst/Sonoff-Tasmota#662]
Hello,
on Sonoff POW I set LedState to 7. After change of LedPower to ON shows LedState 8. After change of LedPower to OFF shows LedState 0.

09:52:43 CMND: cmd/home214/LedPower
09:52:44 MQTT: home/stat/home214/RESULT = {"LedPower":"ON"}
09:52:49 CMND: cmd/home214/LedState
09:52:49 MQTT: home/stat/home214/RESULT = {"LedState":8}
09:53:01 CMND: cmd/home214/LedPower off
09:53:01 MQTT: home/stat/home214/RESULT = {"LedPower":"OFF"}
09:53:06 CMND: cmd/home214/LedState
09:53:06 MQTT: home/stat/home214/RESULT = {"LedState":0}
09:53:13 CMND: cmd/home214/LedState 7
09:53:13 MQTT: home/stat/home214/RESULT = {"LedState":7}
09:53:19 CMND: cmd/home214/LedState
09:53:19 MQTT: home/stat/home214/RESULT = {"LedState":7}
09:53:26 CMND: cmd/home214/LedPower on
09:53:26 MQTT: home/stat/home214/RESULT = {"LedPower":"ON"}
09:53:31 CMND: cmd/home214/LedState
09:53:31 MQTT: home/stat/home214/RESULT = {"LedState":8}

**Comment by arendst** [comment]
As LedState and LedPower are mutually exclusive this is as designed.
