### ISSUE TITLE
Sonoff Mini's - Occasional switch not activating

### ISSUE THREAD

**Issue by speedyrazor** [arendst/Sonoff-Tasmota#6627]
Hi, I have a few Sonoff Mini's with Tasmota installed (currently 6.6.0.16), but have had this issue now and then with various versions.
I use them in the ceiling rose to control UK Lights, so use the standard light switch.
The issue I have is, very occasionally, I switch the light switch and nothing happens, nothing appears on the console. I have checked the wiring and thats all good, and I have seen this issue on multiple lights, which use different circuits and switches.
I use the setting, Module 'Sonoff Basic', with GPIO4 set to 'Switch 1 (19)'.
This works 99% of the time, but very occasionally the switch does not activate the light, and like I say, nothing in console to suggest anything. When this happens, if you then switch on and off again, it then works. Very odd, never had this with my recently removed Tasmota flashed Sonoff Basic's.
Any ideas would be greatly appreciated.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
