### ISSUE TITLE
Please add KNX tunneling support

### ISSUE THREAD

**Issue by lassos** [arendst/Sonoff-Tasmota#6631]
Could you please add tunneling support ? I just have a mdt knx ip interface without router function. so there is no way to send udp via multicast to 224.0.23.12:3671

**Comment by ascillato2** [comment]
Hi,

Tunneling support is a great feature but adding that is a huge effort and a massive rewrite for the knx library and for the knx Tasmota's driver.

I'm sorry but I won't be working on that, at least for now.

Anyway, thanks for sharing your ideas.
