### ISSUE TITLE
Help Please ESP-12F

### ISSUE THREAD

**Issue by pedroOliveiraptc** [arendst/Sonoff-Tasmota#664]
Hello friend, have some one flash it and use it with success the ESP-12-F ? i lost hours and hours around it and cannot make it work :/
It works manually but don't work on mqtt.

http://www.ebay.com/itm/WiFi-Control-Panel-Touch-Wall-Switch-1-Way-1-Gang-Compatible-Work-with-Alexa-8A-/232371517466

![img_2299](https://user-images.githubusercontent.com/12796621/28767295-f9a7c8e4-75ca-11e7-9882-4c071b9e8560.JPG)
![img_2298 2](https://user-images.githubusercontent.com/12796621/28767306-01031314-75cb-11e7-922c-b09ae4a9e97a.JPG)

**Comment by davidelang** [comment]
describe what's happening a bit more.

you flash it. Does it then connect to your network? can you reach the web page 
to configure it?

what happens when it tries to connect to your mqtt server?

is there any information in the logs? (have you increased your log detail to 
"more debugging"?)

k

**Comment by stefanbode** [comment]
I assume you do not have enough Flash space and/or your firmware is too big to fit two times into the -F version (1MByte). The serial flash works always. The OTA Flash required at least double size of the firmware as the flash to store the new version until it reboots. The SONOFF and also the early ESP versions are limited by 1MB. This creates trouble in 80% of the cases. Not easy to solve here.

**Comment by jeylites** [comment]
@pedroOliveiraptc 

in case you're wondering why this did work out, check the link below

[Yewelink/Tuya WiFi Touch wall light switch](https://www.letscontrolit.com/forum/viewtopic.php?f=5&t=3244)
