### ISSUE TITLE
Make Sonoff SC optional via define in my_user_config.h

### ISSUE THREAD

**Issue by Jason2866** [arendst/Sonoff-Tasmota#6640]
**Is your feature request related to a problem? Please describe.**  
Since Sonoff SC is not a device which everyone has it would be nice to have the option to disable at compile time. Similar to Sonoff ifan. Saves flash for selfcompiled firmwares

**Describe the solution you'd like**  
Define option in my_user_config.h to enable/disable
Enabled by default, so no change to actual situation

**Describe alternatives you've considered**  
Change code myself. Needs to be done every time :-(

**Comment by arendst** [comment]
Will do.

**Comment by Jason2866** [comment]
Thx!
