### ISSUE TITLE
Add new section to scripts that is run on button change

### ISSUE THREAD

**Issue by BCNelson** [arendst/Sonoff-Tasmota#6643]
**Have you looked for this feature in other issues and in the wiki?**  
Yes

**Is your feature request related to a problem? Please describe.** 
No

**Describe the solution you'd like**  
I would like to add another section to the scripts that is run anytime that FUNC_BUTTON_PRESSED event is fired by XdrvCall()
also I think that two new variables need to be added namely button and button state that are valid only in the button section.

**Describe alternatives you've considered**  
Checking the buttons in the >F section that is executed every 100ms while this is serviceable it is slow and takes more room in the script storage.

**Additional context**  
_Add any other context or screenshots about the feature request here._

**Comment by BCNelson** [comment]
Mostly I'm looking to see if this would be acceptable before I go to the work of making it. As well as discussing the specifics of the addition

**Comment by gemu2015** [comment]
this is already working.
the >E section receives all events like rules does, but in contrast to rules JSON strings are case sensitive.

for buttons use:

>D
b1=0

>E
b1=Button1#State

if upd[b1]>0
then
print button 1 pressed
endif

**Comment by gemu2015** [comment]
ok, added section >b
is executed on any state change of button

#define USE_BUTTON_EVENT

bt[x]   x=1-MAX_KEYS
\>b
print button event =>%bt[1]%

**Comment by gemu2015** [comment]
@BCNelson 

https://github.com/gemu2015/Sonoff-Tasmota/blob/universal7/sonoff/xdrv_10_scripter.ino

will do a pr soon
