### ISSUE TITLE
Sonoff RF reboot loop Exception28

### ISSUE THREAD

**Issue by michi1g** [arendst/Sonoff-Tasmota#6649]
I'm trying to get tasmota on my Sonoff RF but always fail to get it running
I tried using Arduino and NodeMCU PyFlasher. Tried sonoff.bin sonoff-sensors.bin my arduino compiled file but nothing is working.
I always get stuck in a bootloop:

> 12:02:04.791 -> 
12:02:04.791 -> Exception (0):
12:02:04.791 -> epc1=0x4010705d epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
12:02:04.791 -> 
12:02:04.791 -> ctx: cont 
12:02:04.791 -> sp: 3fff51c0 end: 3fff5440 offset: 01a0
12:02:04.791 -> 
12:02:04.813 -> >>>stack>>>
12:02:04.813 -> 3fff5360:  0000001c 00000000 3fff4350 40201084  
12:02:04.813 -> 3fff5370:  00000030 00000001 3fff6c7c 40202d15  
12:02:04.813 -> 3fff5380:  00000000 00000001 000001da 4010020c  
12:02:04.813 -> 3fff5390:  0000001c 00000000 3fff4350 00000000  
12:02:04.813 -> 3fff53a0:  0000001c 00000000 3fff4350 4023656c  
12:02:04.846 -> 3fff53b0:  00000001 3fff2ac8 40237fc4 3fff4420  
12:02:04.846 -> 3fff53c0:  402022d2 00000064 3fff4350 3fff2ac8  
12:02:04.846 -> 3fff53d0:  3fff24f7 3fff4350 00000000 40215ba7  
12:02:04.846 -> 3fff53e0:  3fff24f7 3fff292d 3fff27c8 40215f6c  
12:02:04.846 -> 3fff53f0:  6f6e6f73 fe006666 feefeffe feefeffe  
12:02:04.879 -> 3fff5400:  feefeffe feefeffe feefeffe feefeffe  
12:02:04.879 -> 3fff5410:  feefeffe feefeffe feefeffe 3fff440c  
12:02:04.879 -> 3fff5420:  3fffdad0 00000000 3fff4405 40238008  
12:02:04.879 -> 3fff5430:  feefeffe feefeffe 3fff4420 40100718  
12:02:04.879 -> <<<stack<<<
12:02:04.912 -> 
12:02:04.912 ->  ets Jan  8 2013,rst cause:1, boot mode:(3,0)
12:02:04.912 -> 
12:02:04.912 -> load 0x4010f000, len 1384, room 16 
12:02:04.912 -> tail 8
12:02:04.912 -> chksum 0x2d
12:02:04.912 -> csum 0x2d
12:02:04.912 -> v60000608
12:02:04.912 -> ~ld

any suggestions how to get it running?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Jason2866** [comment]
Please close since it is solved. -> Bad flash...
