### ISSUE TITLE
Sonoff UK Binary is Russian

### ISSUE THREAD

**Issue by somebodywhoisntme** [arendst/Sonoff-Tasmota#6665]
Hello,

I only compiled the UK-Binary but after uploading it it was russian or something like that.

Now I downloaded the UK Version from this site and its also in russian and not english.

Am I to stupid or whats the problem here?

**Comment by arendst** [comment]
Yes you are to stupid as this issue has come along before (grin) ;-)

How about UK is NOT United Kingdom but perhaps Ukrain...

**Comment by arendst** [comment]
I can hear your brains crunching. Where is the United Kingdom version....

Try the default ones. Chances are they are using English.

**Comment by somebodywhoisntme** [comment]
It could be hardly otherwise :D I already flashed the right binary. 

Really thanks for your fast answer and much more for the hard work you put in here.

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
