### ISSUE TITLE
WS2812 Strip has 360 leds firmware caps at 256

### ISSUE THREAD

**Issue by anthonykeane** [arendst/Sonoff-Tasmota#667]
Code around the `sysCfg.ws_pixels ` is` uint8_t` needs to be `uint16_t` otherwise the led strip can only be 255 pixels, I have strips that are 360 pixels

**Comment by arendst** [comment]
Does it work to full content? If so I could extent to 360 leds.

**Comment by arendst** [comment]
Give it a try and let me know.
