### ISSUE TITLE
channel command resets channel4 to 0

### ISSUE THREAD

**Issue by homeseer666** [arendst/Sonoff-Tasmota#6671]
### BUG DESCRIPTION
_A clear and concise description of what the bug is._

Using latest Tasmota version with LEd controller MAgichome ZJ-WFMN-A V1.1
Module type | 18 Generic |
D1 GPIO5 | 38 PWM2 | BLUE
D6 GPIO12 | 37 PWM1 | RED
D7 GPIO13 | 39 PWM3 | GREEN
D8 GPIO15 | 40 PWM4 | WHITE

Using console:
Whenever I use any channel command to change colors, channel 1, 2 and 3 values remain unchanged, however, channel 4 is reset to zero.
if changing channel1 Red from 100 to 50, I don't want the command to affect any existing channel value, including channel4/white

See example below:

06:28:27 CMD: channel2 100
06:28:27 MQT: stat/LEDRGBWA/RESULT = {"POWER":"ON","Dimmer":100,"Color":"255,255,0,0","HSBColor":"60,100,100","Channel":[100,100,0,0]}
06:28:34 CMD: channel2 0
06:28:35 MQT: stat/LEDRGBWA/RESULT = {"POWER":"ON","Dimmer":100,"Color":"255,0,0,0","HSBColor":"0,100,100","Channel":[100,0,0,0]}
06:28:41 CMD: channel4 100
06:28:42 MQT: stat/LEDRGBWA/RESULT = {"POWER":"ON","Dimmer":100,"Color":"255,0,0,255","HSBColor":"0,100,100","Channel":[100,0,0,100]}
06:28:50 CMD: channel1 50
06:28:50 MQT: stat/LEDRGBWA/RESULT = {"POWER":"ON","Dimmer":50,"Color":"128,0,0,0","HSBColor":"0,100,50","Channel":[50,0,0,0]}

- [x ] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x ] Searched the problem in [issues](https://github.com/arendst/Sonoff-Tasmota/issues)
- [x ] Searched the problem in the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x ] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [x ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x ] Device used (e.g., Sonoff Basic): _____above
- [x ] Tasmota binary firmware version number used: _____latest
  - [ ] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [ x] Flashing tools used: _____
- [ ] Provide the output of command: ``Backlog Template; Module; GPIO``:
  ```
  Configuration output here:
  06:41:28 CMD: Backlog Template; Module; GPIO
06:41:29 MQT: stat/LEDRGBWA/RESULT = {"NAME":"LEDRGBWA","GPIO":[255,255,255,255,255,38,255,255,37,39,255,40,255],"FLAG":15,"BASE":18}
06:41:29 MQT: stat/LEDRGBWA/RESULT = {"Module":"0 (LEDRGBWA)"}
06:41:29 MQT: stat/LEDRGBWA/RESULT = {"GPIO0":"0 (None)","GPIO1":"0 (None)","GPIO2":"0 (None)","GPIO3":"0 (None)","GPIO4":"0 (None)","GPIO9":"0 (None)","GPIO10":"0 (None)","GPIO14":"0 (None)","GPIO16":"0 (None)"}
  
  ```
- [ ] If using rules, provide the output of this command: ``Backlog Rule1; Rule2; Rule3``:
  ```
  Rules output here:
  
  
  ```
- [ ] Provide the output of this command: ``Status 0``:
  ```
  STATUS 0 output here:
  06:42:22 CMD: Status 0
06:42:23 MQT: stat/LEDRGBWA/STATUS = {"Status":{"Module":0,"FriendlyName":["LEDRGBWA"],"Topic":"LEDRGBWA","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
06:42:23 MQT: stat/LEDRGBWA/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T01:02:37","StartupUTC":"2019-10-17T04:39:46","Sleep":50,"CfgHolder":4617,"BootCount":6,"SaveCount":94,"SaveAddress":"F6000"}}
06:42:23 MQT: stat/LEDRGBWA/STATUS2 = {"StatusFWR":{"Version":"6.6.0(release-sonoff)","BuildDateTime":"2019-07-06T13:10:20","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
06:42:23 MQT: stat/LEDRGBWA/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["SALON","SOUS-SOL"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00028009","280500000100060000000000000000000000","00000000"]}}
06:42:24 MQT: stat/LEDRGBWA/STATUS4 = {"StatusMEM":{"ProgramSize":503,"Free":500,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0FDAE396","001783A0","22B617CD","01003BC0"]}}
06:42:24 MQT: stat/LEDRGBWA/STATUS5 = {"StatusNET":{"Hostname":"LEDRGBWA-4897","IPAddress":"192.168.0.167","Gateway":"192.168.0.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.0.1","Mac":"C4:4F:33:81:B3:21","Webserver":2,"WifiConfig":4}}
06:42:24 MQT: stat/LEDRGBWA/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.0.117","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_81B321","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
06:42:24 MQT: stat/LEDRGBWA/STATUS7 = {"StatusTIM":{"UTC":"Thu Oct 17 05:42:24 2019","Local":"Thu Oct 17 06:42:24 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:13","Sunset":"17:57"}}
06:42:24 MQT: stat/LEDRGBWA/STATUS10 = {"StatusSNS":{"Time":"2019-10-17T06:42:24"}}
06:42:25 MQT: stat/LEDRGBWA/STATUS11 = {"StatusSTS":{"Time":"2019-10-17T06:42:24","Uptime":"0T01:02:38","Heap":14,"SleepMode":"Dynamic","Sleep":0,"LoadAvg":999,"POWER":"ON","Dimmer":50,"Color":"128,0,0,0","HSBColor":"0,100,50","Channel":[50,0,0,0],"Scheme":0,"Fade":"OFF","Speed":1,"LedTable":"ON","Wifi":{"AP":1,"SSId":"SALON","BSSId":"B4:75:0E:39:C1:4E","Channel":11,"RSSI":74,"LinkCount":1,"Downtime":"0T00:00:04"}}}
  
  ```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ ``weblog 4`` _for more debug information)_
  ```
  Console output here:
  
  
  ```

### TO REPRODUCE
_Steps to reproduce the behavior:_

see above example

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

if changing channel1 Red from 50 to 100, I dont want the command to affect any existing channel value, including channel4/white

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
You use v.6.6.0. Since that version MANY fixes and updates are made.
Please use the actual version http://thehackbox.org/tasmota/sonoff.bin
If the issues is still there, please update the template or close if update has solved.

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
