### ISSUE TITLE
No load firmware Mac

### ISSUE THREAD

**Issue by josep112** [arendst/Sonoff-Tasmota#6675]
Hi,
I am using the manual process to install new firmware with Mac OsX, the first command works perfectly as below
curl http://10.0.0.100:8081/zeroconf/info -XPOST --data '{"deviceid":"10009b9b03","data":{}}'
{"seq":2,"error":0,"data":"{\"switch\":\"off\",\"startup\":\"off\",\"pulse\":\"off\",\"pulseWidth\":500,\"ssid\":\"sonoffDiy\",\"otaUnlock\":false}"}

But I can not unlock ota or send the new firmware, see the errors:
curl http://10.0.0.100:8081/zeroconf/ota_unlock -XPOST --data
'{"deviceid":"10009b9b03","data":{}}'
curl: (52) Empty reply from server

AND

curl http://10.0.0.100:8081/zeroconf/ota_flash -XPOST --data '{"deviceid":"10009b9b03","data":{"downloadUrl": "http://localhost/onoff.ino.bin", "sha256sum": "1e7d098af663d5083e99d02d003db9c6a870486939f431f3cc1777445276b415"} }'
{"seq":2,"error":422}

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
