### ISSUE TITLE
More Relays 

### ISSUE THREAD

**Issue by kinghill44** [arendst/Sonoff-Tasmota#6689]
Hello,

Is it Posible to add more Relays in the Firmware? I need Relay 9i and 10i. 
Can someone tell me how I install this in the firmware?
Which files must be edited?

My Tasmota Version is 6.6.0

THX

**Comment by Jason2866** [comment]
Duplicate see #6334 

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
