### ISSUE TITLE
Teckin SP23s power monitor not working

### ISSUE THREAD

**Issue by scargill** [arendst/Sonoff-Tasmota#6691]
> **GUIDE**
>
> This BUG issue template is meant to REPORT Tasmota software BUGS ONLY>
>  
> Please DO NOT OPEN AN ISSUE:
>  - If your Tasmota version is not the latest from the development branch, please update your device before submitting your issue. Your problem might already be solved. The latest precompiled binaries of Tasmota can be downloaded from http://thehackbox.org/tasmota/  
>  - If your issue is a flashing issue, please address it to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)  
>  - If your issue is compilation problem, please address it to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4)  
>  - If your issue has been addressed before (i.e., duplicated issue), please ask in the original issue  
>  - If your issue is a Wi-Fi problem or MQTT problem, please try the steps provided in the [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) and troubleshooting wiki articles  
>
> Please take a few minutes to complete the requested information below. Our ability to provide assistance is greatly hampered without it. The details requested potentially affect which options to pursue. The small amount of time you spend completing the template will also help the volunteers providing the assistance to you to reduce the time required to help you.

### BUG DESCRIPTION
flashed 2 brand new Teckin SP23 devices tuya convert and updated both to latest 2.6.0 based firmware, 6.6.0.20, no one can do power monitoring... 1 is selected as https://blakadder.github.io/templates/teckin-sp23.html and the other, as suggested, as https://blakadder.github.io/templates/blitzwolf_SHP2.html with same results, button, led and relay work, power monitoring does not

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

**FAILURE TO COMPLETE THE REQUESTED INFORMATION WILL RESULT IN YOUR ISSUE BEING CLOSED**

- [X] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [X] Searched the problem in [issues](https://github.com/arendst/Sonoff-Tasmota/issues)
- [X] Searched the problem in the [wiki](https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [X] Searched the problem in the [forum](https://groups.google.com/d/forum/sonoffusers)
- [X] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [X] Device used (e.g., Sonoff Basic): teckin sp23s
- [X] Tasmota binary firmware version number used: 6.6.0.20
  - [X] Pre-compiled
  - [ ] Self-compiled
    - [ ] IDE / Compiler used: _____
- [X] Flashing tools used: tuya convert, then ota upgrade
- [X] Provide the output of command: ``Backlog Template; Module; GPIO``:
  ```
14:57:59 CMD: Backlog Template; Module; GPIO
14:57:59 MQT: stat/sp23s2/RESULT = {"NAME":"BlitzWolf SHP","GPIO":[57,255,56,255,0,134,0,0,131,17,132,21,0],"FLAG":0,"BASE":45}
14:57:59 MQT: stat/sp23s2/RESULT = {"Module":{"0":"BlitzWolf SHP"}}
14:58:00 MQT: stat/sp23s2/RESULT = {"GPIO1":{"0":"None"},"GPIO3":{"0":"None"}}  
  
  ```
- [ ] If using rules, provide the output of this command: ``Backlog Rule1; Rule2; Rule3``:
  ```
  Rules output here:
  
  
  ```
- [X] Provide the output of this command: ``Status 0``:
  ```
14:58:37 CMD: status 0
14:58:37 MQT: stat/sp23s2/STATUS = {"Status":{"Module":0,"FriendlyName":["sp23s2"],"Topic":"sp23s2","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
14:58:37 MQT: stat/sp23s2/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Exception","Uptime":"0T00:02:14","StartupUTC":"2019-10-19T13:56:23","Sleep":50,"CfgHolder":4617,"BootCount":4,"SaveCount":11,"SaveAddress":"F9000"}}
14:58:37 MQT: stat/sp23s2/STATUS2 = {"StatusFWR":{"Version":"6.6.0.20(6bcfcf1-sonoff)","BuildDateTime":"2019-10-19T15:00:11","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"}}
14:58:37 MQT: stat/sp23s2/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["office",""],"TelePeriod":300,"Resolution":"55A180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000"]}}
14:58:37 MQT: stat/sp23s2/STATUS4 = {"StatusMEM":{"ProgramSize":561,"Free":440,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144068","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007081"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
14:58:37 MQT: stat/sp23s2/STATUS5 = {"StatusNET":{"Hostname":"sp23s2-2013","IPAddress":"192.168.14.130","Gateway":"192.168.14.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.14.1","Mac":"BC:DD:C2:42:47:DD","Webserver":2,"WifiConfig":4}}
14:58:37 MQT: stat/sp23s2/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.14.71","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4247DD","MqttUser":"admin","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
14:58:37 MQT: stat/sp23s2/STATUS7 = {"StatusTIM":{"UTC":"Sat Oct 19 13:58:37 2019","Local":"Sat Oct 19 14:58:37 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:16","Sunset":"17:54"}}
14:58:37 MQT: stat/sp23s2/STATUS9 = {"StatusPTH":{"PowerDelta":0,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0}}
14:58:37 MQT: stat/sp23s2/STATUS10 = {"StatusSNS":{"Time":"2019-10-19T14:58:37","ENERGY":{"TotalStartTime":"2019-10-19T14:51:27","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
14:58:37 MQT: stat/sp23s2/STATUS11 = {"StatusSTS":{"Time":"2019-10-19T14:58:37","Uptime":"0T00:02:14","UptimeSec":134,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"office","BSSId":"00:1B:29:66:D1:B8","Channel":11,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:09"}}}  
  
  ```
- [ ] Provide the output of the Console log output when you experience your issue; if applicable:
  _(Please use_ ``weblog 4`` _for more debug information)_
  ```
  Console output here:
  
  
  ```

### TO REPRODUCE
just plug it and turn relay on, it should AT LEAST report voltage, which stays at 0

### EXPECTED BEHAVIOUR
show power monitoring data

### SCREENSHOTS

![image](https://user-images.githubusercontent.com/1889411/67146243-1b0c3a80-f281-11e9-85ef-0502ee76e8b4.png)

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Jason2866** [comment]
It seems the manufactor has changed the device circuit (how stuff is connected to GPIOs)
You have to find the (changed) correct GPIO settings This is not a Tasmota issue.
How to start to find GPIO settings is described in wiki.  
Your findings for a working config are highly welcome as new Template.

Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
