### ISSUE TITLE
Restart required if wifi connect fails?

### ISSUE THREAD

**Issue by altelch** [arendst/Sonoff-Tasmota#67]
Hi,

is it really required to restart the uC if Wifi-Connect fails? This has one major drawback for me. I use a Sonoff Pow to measure some stuff behind it. If there is no Wifi during startup the uC goes into a boot cycle always toggling the relais. This is a problem if you need the stuff behind the relays to be always on. Isn't it possible to do the Wifi config loop without restarting the ESP?

Greetings,
    Heiko.

**Comment by arendst** [comment]
Select wificonfig 4 and Bob's your uncle.

**Comment by altelch** [comment]
Argl, as always RTFM. Thanks for the quick response.

Heiko.
