### ISSUE TITLE
Show Gosund SP1 monthly usage

### ISSUE THREAD

**Issue by meierchen006** [arendst/Sonoff-Tasmota#6703]
Hi,

I run a Gosund SP1 socket with Tasmota firmware 6.6.0.20. 
This shows me on the overview page many measurement data and consumption data:
e.g.
Energy today
Energy Yesterday
Energy overall.

Here I miss the display energy in the month, so that one could see how much energy was consumed so far in the month.

Could you bring this monthly consumption into one of the next firmware?

Kind regards
meierchen006

**Comment by andrethomas** [comment]
You can reset the energy totals using the commands documented here https://github.com/arendst/Sonoff-Tasmota/wiki/Power-Monitoring-Calibration

Some people will do this weekly, monthly, annually etc so there's no specific way to know all the possible combinations but using the reset function you can schedule this from your home automation software.

**Comment by ascillato** [comment]
Or you can use a home automation software like home assistant or OpenHab

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
