### ISSUE TITLE
nmap resetting/killing tasmotized devices

### ISSUE THREAD

**Issue by p1ranha** [arendst/Sonoff-Tasmota#6709]
### BUG DESCRIPTION
After running Zenmap 7.80 on my network using following command, it kicked out some of the devices from wifi, and changed them to mode where they forgot the wifi and turned the "sonof-xxxx" wifi.
Some of them stopped working at all, not even button toggling power works.

**nmap -sS -sU -T4 -A -v -PE -PP -PS80,443 -PA3389 -PU40125 -PY -g 53 --script "default or (discovery and safe)" 192.168.178.1/24**

This happened on tasmota 6.6.0, 6.6.0.9, 6.6.0.20 with plugs: gosund sp-22, teckin sp20 (as Blizwolf SHP)
Those devices which turned into sonoff-XXXX wifi, I was able to reenter wifi details, and they continued working correctly, others (eg. gosund) are dead. They don't respond to button press, and the led light up for fraction of second just to turn off.
There was no password protection on webgui, so I think nmap is running some scripts that can damage the plugs. I used tuya-convert to upload initial tasmota into devices and everything was working fine for several months until I ran that nmap.

I thought to mention this, so future versions can be better protected against malformed requests coming from scanners like nmap.

**Comment by curzon01** [comment]
The nmap parameter you used causes a lot of http request on all available Tasmota web pages and sometime a "`RESET 1`" command (`RESET 1 = reset device settings to firmware defaults and restart`)

This is a seriallog 5 result of a device scanned with nmap parms above:
```
...
11:52:05 HTP: Main Menu
11:52:08 HTP: Main Menu
11:52:09 HTP: Main Menu
11:52:12 HTP: Main Menu
11:52:12 HTP: Main Menu
11:52:14 HTP: Information
11:52:15 HTP: Main Menu
11:52:15 HTP: Configuration
11:52:15 HTP: Main Menu
11:52:15 HTP: Firmware Upgrade
11:52:16 HTP: Console
11:52:16 HTP: Main Menu
11:52:16 HTP: Configure Other
11:52:17 HTP: Main Menu
11:52:17 HTP: Configure Logging
11:52:17 HTP: Main Menu
11:52:17 HTP: Restore Configuration
11:52:18 HTP: Main Menu
11:52:18 HTP: Configure Timer
11:52:19 HTP: Main Menu
11:52:19 HTP: Configure WiFi
11:52:19 HTP: Main Menu
11:52:19 HTP: Backup Configuration
11:52:20 WIF: Checking connection...
11:52:20 WIF: Connected
11:52:20 HTP: Main Menu
11:52:20 HTP: Configure Template
11:52:20 HTP: Main Menu
11:52:20 HTP: Reset Configuration
11:52:20 SRC: WebGui from 172.18.10.42
11:52:20 CMD: Group 0, Index 1, Command "RESET", Data "1"
11:52:20 MQT: project-home/stat/tasmota/sonoff/RESULT = {"Reset":"Reset and Restarting"}
11:52:20 CFG: Use defaults
11:52:21 CFG: Saved to flash at FB, Count 1, Bytes 4096
11:52:21 CFG: Saved to flash at FA, Count 2, Bytes 4096
11:52:22 CFG: Saved to flash at F9, Count 3, Bytes 4096
11:52:22 APP: Restarting
```
the result is a normal behaviour (result of a `RESET 1` command).

The issue here is you are using nmap against a http device without any http password set. If you enable http minimum protection using WebPassword, issue can not be reproduced

**Comment by ascillato2** [comment]
Closing this issue as it has been answered and that if a reset 1 command is sent to your device (without webpassword defined) by http, this configuration reset is the normal behavior of Tasmota. 

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by joba-1** [comment]
isn't the real issue that tasmota changes persistent state on http get requests while it should use post requests for this? I doubt nmap does post requests exactly to prevent problems like this.
But I have not tested it. Could be wrong...

**Comment by s-hadinger** [comment]
POST or GET is not the issue. There is a complete wiki page on security for Tasmota. 

https://github.com/arendst/Sonoff-Tasmota/wiki/Securing-your-IoT-from-hacking

**Comment by joba-1** [comment]
I tend to disagree. This is not about security. I dont want to use passwords to work around Get/post issues in my isolated iot lan

**Comment by s-hadinger** [comment]
What I mean is moving persistent changes to anonymous POST will not change the security posture by any way. It will still be super easy to change whatever in your Tasmota device once an intruder in on your LAN.

**Comment by joba-1** [comment]
yes, I think we are on the same page.

But tools (with good intentions) know that repeating post requests is not an option while get requests should be fine.

**Comment by foice** [comment]
> What I mean is moving persistent changes to anonymous POST will not change the security posture by any way. It will still be super easy to change whatever in your Tasmota device once an intruder in on your LAN.

I just ran again on this issue on a Tasmota 8.1.0.2 by doing `nmap --script vuln` searching for vulnerabilities in my network. All config of the tasmota is lost. I will put a password, still I am wondering if the webserver in tasmota can be made less susceptible to this type of attacks. (I do get the point that _if_ someone is one my LAN I am already under attack, however you see what happens, you try to scan naively scan your LAN and you end up hacking yourself!)

**Comment by arendst** [comment]
OMG. Why do you respond here after five years using a prehistoric tasmota version. I suggest you update to latest version and if things are still bad open a new issue.

**Comment by sfromis** [comment]
Well, it is known that some older devices may not have the power to sustain concentrated DOS attacks (yes, that's what vulnerability tools do) without failing with boot loops. That's not so much about Tasmota, but about the hardware.

Still, Tasmota does have recovery features for resetting a device failing repeatedly, instead of it being soft-bricked, and those recovery features can be turned off if you do not want Tasmota to recover.
