### ISSUE TITLE
Smaller knx. bin for Sonoff MI I? 

### ISSUE THREAD

**Issue by jensgulow** [arendst/Sonoff-Tasmota#6715]
I'd like to flash a Sonoff Mini with sonoff-knx.bin . But it's about 568k.....Maximum for the Mini is 508k.
Is it possible to get a smaller version of the knx.bin?

**Comment by Jason2866** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by ascillato2** [comment]
The sonoff mini has enough memory for a full version of Tasmota with KNX.

If you are using the DIY mode for flashing, you can start with sonoff_basic.bin (that is a small version) and then you can upgrade via Tasmota OTA to the full version.

If you need assistance on that, please, find us in the Chat. Thanks.

**Comment by AgentFire** [comment]
> The sonoff mini has enough memory for a full version of Tasmota with KNX.
> 
> If you are using the DIY mode for flashing, you can start with sonoff_basic.bin (that is a small version) and then you can upgrade via Tasmota OTA to the full version.
> 
> If you need assistance on that, please, find us in the Chat. Thanks.

Where can i download sonoff_basic.bin?

**Comment by barbudor** [comment]
Now it is called tasmota-lite.bin

**Comment by AgentFire** [comment]
@barbudor and it still bigger than 508k and can't be flashed via DIY tool.

**Comment by ascillato** [comment]
http://ota.tasmota.com/tasmota/tasmota-lite.bin is 502K

**Comment by AgentFire** [comment]
> http://ota.tasmota.com/tasmota/tasmota-lite.bin is 502K

513,264 bytes.
![image](https://user-images.githubusercontent.com/5173466/140612787-dfce4279-2146-4931-ae7c-7513ab8abad0.png)

**Comment by barbudor** [comment]
Pfff. Sonoff DIY is so unreliable. 
Use serial flashing

**Comment by Jason2866** [comment]
The have there own definition of kbyte 😁

**Comment by barbudor** [comment]
V9.3.1 is smaller
http://ota.tasmota.com/tasmota/release-9.1.0/tasmota-lite.bin

**Comment by AgentFire** [comment]
> V9.3.1 is smaller http://ota.tasmota.com/tasmota/release-9.1.0/tasmota-lite.bin

Thanks. Can I hope that you'd put the link on earlier, historic, releases on the MD file?

**Comment by barbudor** [comment]
Where?
You can propose doc updates by clicking the pencil icon on the top right
