### ISSUE TITLE
Support for 2 way smart dimmer

### ISSUE THREAD

**Issue by gonzasmts** [arendst/Sonoff-Tasmota#6719]
Hello, 
is this smart dimmer supported?

https://www.aliexpress.com/item/4000218674472.html?spm=a2g03.12010615.8148356.9.fce3398cbHKfmk

it looks promising, and i want to buy it, but i can't find any information about if it's possible or not to flash it.

thanks

**Comment by meingraham** [comment]
Please close this issue and address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
