### ISSUE TITLE
Hide alexa objects

### ISSUE THREAD

**Issue by prstprst** [arendst/Sonoff-Tasmota#6722]
Hello, 

When using more than one power output in tasmota and choosing the hue emulation (providing also the dimming possibility), alexa detect ALL the "power" existing in the config of tasmota.
I know that it's possible to delete i from the Alexa app, but by making a new search for new devices, uneeded device are coming back in the Alexa app.
The goal should be to have the possibility to make some power  invisible for the alexa detection by adding, for exemple, a simple "$" (has used for hidden share in windows) in front of the frinedly name used in the "hue" config .

Thanks

**Comment by s-hadinger** [comment]
This change would have some impacts in the way Alexa devices are reported and controlled. Also take into consideration that friendly names work only for the first 4 devices. Your use-case seems very specific. It will probably not be implemented in the standard version. But feel free to submit a PR if you like.

**Comment by Jason2866** [comment]
If you do a PR it has a low chance to be merged.
The common wanted use case is to control all connected devices via Alexa.

**Comment by ascillato2** [comment]
Closing this issue as it has been answered.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
