### ISSUE TITLE
Step relay control with feedback

### ISSUE THREAD

**Issue by marcolino7** [arendst/Sonoff-Tasmota#6732]
Hi,
I'm now using another framework based on arduino to perfor this kind of control but i like to have in Tasmota.

In my house I have several step relay with multiple button each one, and I would like to keep it in place, in case a tasmota node fail, i can turn on or off light with physical button.
I use Shelly1 as hardware, because it have one clean contact on its relay, and a input/feedback line.

Actualy I connect the relay of shelly1 in parallel of physical button of a step relay, the input line to line connected to lamp. When I decide to turn on the light from my Home Automation System with actual firmware I have on shelly one, the relay on shelly turn on a couple of second, it press the button and the step relay turn on the light and I got the feedback thrught the input of the shelly. If light is just turned on and I ask to turn not, the relay on shelly do not "press" the button.

Is it possible to achieve this with tasmota, or is it possible to add this functionality?

Marco

**Comment by ascillato2** [comment]
Yes.

Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
