### ISSUE TITLE
Sonoff T2 -Help me find the GPIO0

### ISSUE THREAD

**Issue by macguru341** [arendst/Sonoff-Tasmota#6744]
Just got my T2 buy Sonoff and I want to flash it and I can’t find the GPIO0 on the card.
![28FBD566-24DB-47BF-B25D-DF44F1D4CAF0](https://user-images.githubusercontent.com/22807164/67582119-d33e5500-f751-11e9-9de0-1ecc9f1ae0af.jpeg)
![Uploading 4C1D3B18-C772-461E-958D-97493CEF83FD.jpeg…]()
![Uploading 8FE3E131-F860-4ABC-AACF-2EEE60242967.jpeg…]()
![Uploading C595967E-6F58-4086-88A3-55CC89DE4BEA.jpeg…]()

**Comment by ascillato2** [comment]
Please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by macguru341** [comment]
Ok thanks
