### ISSUE TITLE
Broken POW 

### ISSUE THREAD

**Issue by myozone** [arendst/Sonoff-Tasmota#6754]
Just uploaded the new 6.7.0 to all my Sonoff's and one a POW is broken well the flash didn't work. I uploaded the minimal install then 6.7 but it didn't set my POW as before so I went back to minimal BUT now I get this below and can't re-flash anymore even with the Arduino IDE

Exception (0):
epc1=0x4000e25d epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff5920 end: 3fff5b90 offset: 01a0

>>>stack>>>
3fff5ac0:  3fff75fc 00000100 00000001 40201088  
3fff5ad0:  40202aea 3fff762c 00000001 40202bf0  
3fff5ae0:  00000000 0000001c 00000003 3fff7614  
3fff5af0:  3ffeff30 3fff5be8 3fff4aa0 3ffe8784  
3fff5b00:  3fff30b9 00000001 3fff4aa0 40231688  
3fff5b10:  00000000 0000001c 00000000 40231608  
3fff5b20:  3fff30b9 3fff4aa0 00000000 4021074b  
3fff5b30:  3fff30b9 3fff3354 3fff2f54 40211a77  
3fff5b40:  feefeffe feefeffe feefeffe feefeffe  
3fff5b50:  feefeffe feefeffe feefeffe feefeffe  
3fff5b60:  feefeffe feefeffe feefeffe 3fff4b60  
3fff5b70:  3fffdad0 00000000 3fff4b59 40233124  
3fff5b80:  feefeffe feefeffe 3fff4b70 40100710  
<<<stack<<<

 ets Jan  8 2013,rst cause:1, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v4ceabea9
~ld

00:00:00 APP: Set Baudrate to 0

**Comment by arendst** [comment]
See #6750

**Comment by ascillato2** [comment]
Closing this issue as it is **duplicated**. Sorry.

Please, read the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md). Thanks.

---------------------------

### Support Information ([Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md))
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
