### ISSUE TITLE
Sonoff RE5v1C

### ISSUE THREAD

**Issue by jonferreira** [arendst/Sonoff-Tasmota#6755]
Hi,

I've recently purchased a couple of the new Sonoff RE5V1C tinny modules and I'm wondering if there's any plans for tasmota to support these?

**Comment by ascillato2** [comment]
If the device has an esp8266 and someone wants to donate its time making a new template or driver if needed, it can be supported.

If you want to work on it and need some help for that, please, address this to the [Tasmota Support Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are meant for Tasmota Software Bug Reporting.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

---------------------------

### Support Information 
See [Wiki](https://github.com/arendst/Sonoff-Tasmota/wiki) for more information.
See [FAQ](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ) for common questions/answers and [links](https://github.com/arendst/Sonoff-Tasmota/wiki/FAQ#i-cannot-find-an-answer-here) if none of your question is in the list
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by jonferreira** [comment]
thanks will do!

**Comment by danmandle** [comment]
For those who end up here via searching like I did, there is now a template: https://blakadder.github.io/templates/sonoff_RE5V1C.html

**Comment by dweston** [comment]
Wiring arrangement for flashing Sonoff RE5V1C:
![USB-Sonoff_RE5V1C](https://user-images.githubusercontent.com/631241/71563034-6cd10c80-2add-11ea-835a-da65c8009632.jpg)

**Comment by pauljatho** [comment]
Thanks Danmandle for this, I managed to flash one of these with Tasmota and using your template its working.

I wonder do you know how to change it to work from NO to NC? I would like to use this to control a magnetic door strip.

Thanks agin.

**Comment by danmandle** [comment]
@pauljatho You would likely have to do that with software. The downside is that if it is without power, it would be NO.

**Comment by pauljatho** [comment]
Yup, while thinking it through I realised that the relay doesn't have a NC pin so it would like you say without power be NO which wont work for me since this is controlling an access door.

I'll get one of the Sonoff 1Channel inching devices as this has both NO and NC.

Thanks again for your post above.

**Comment by ttweb** [comment]
Hello everybody,
I also have two of these devices, but I never had such problems soldering the little contacts here compared to other devices. I use standard pb solder.
How did you manage to solder the cable/pins correctly? Any suggestions which flux, temperature and solder to use? Thank you very much.

**Comment by pauljatho** [comment]
> Hello everybody,
> I also have two of these devices, but I never had such problems soldering the little contacts here compared to other devices. I use standard pb solder.
> How did you manage to solder the cable/pins correctly? Any suggestions which flux, temperature and solder to use? Thank you very much.

I soldered directly onto the pads but don't use pins use cable, first put a small amount of solder on each of the pads and make sure the cable has solder, needs a very short time to solder.

Also be careful the pads come off very easily I pulled the one ground pad off, luckily it was the ground pad and not TX or RX so I was able to use another ground on the board.

**Comment by ttweb** [comment]
Thank you very much, I will try this again later. Maybe I just was too impatient...

**Comment by clockworkcrow** [comment]
> > Hello everybody,
> > I also have two of these devices, but I never had such problems soldering the little contacts here compared to other devices. I use standard pb solder.
> > How did you manage to solder the cable/pins correctly? Any suggestions which flux, temperature and solder to use? Thank you very much.
> 
> I soldered directly onto the pads but don't use pins use cable, first put a small amount of solder on each of the pads and make sure the cable has solder, needs a very short time to solder.
> 
> Also be careful the pads come off very easily I pulled the one ground pad off, luckily it was the ground pad and not TX or RX so I was able to use another ground on the board.

I lost the pad on the ground too. Which alternative did yo use?

**Comment by lobmarib** [comment]
> Thanks Danmandle for this, I managed to flash one of these with Tasmota and using your template its working.
> 
> I wonder do you know how to change it to work from NO to NC? I would like to use this to control a magnetic door strip.
> 
> Thanks again.

Which tasmota build did you use? Regular tasmota.bin? 
Thanks

**Comment by gaucho1978** [comment]
With this firmware it is possible to activate sleep mode, is it correct? Which is the consumption of SONOFF Re5v1c during sleep?

**Comment by gaucho1978** [comment]
With this firmware it is possible to activate sleep mode, is it correct? Which is the consumption of SONOFF Re5v1c during sleep?

**Comment by danielbrunt57** [comment]
I just successfully soldered connections to my 2nd unit (botched the first - ERX and ETX pads are gone), flashed with regular tasmota.bin, added template {"NAME":"Sonoff RE5V1C","GPIO":[17,255,255,255,255,255,0,0,21,56,0,0,0],"FLAG":0,"BASE":18}, issued `SwitchMode 13` and `PulseTime 10` in console and inching mode is working!  Woo hoo!  My third Tasmota flash after two Sonoff S31's...
