### ISSUE TITLE
1 Channel with Sensor

### ISSUE THREAD

**Issue by Mohrengemuse** [arendst/Sonoff-Tasmota#678]
Is there a chance to connect a sensor to my 1 channel module?

**Comment by davidelang** [comment]
Yes, you can connect a sensor to any module, it's just a matter of picking what 
GPIO it's easiest to wire a sensor to. Most of the sonoff modules have a 5 pin 
header on them, and the 5th pin is GPIO 14, that's the easiest to wire to.
k

**Comment by Mohrengemuse** [comment]
The 1 Channel module dont have this GPIO 14, thats why I am asking.

**Comment by ionciubotaru** [comment]
Try to connect you sensor to TX or RX pin
Disable serial logging, and attach the sensor to pin.
I attach a DS18B20 to RX pin of Sonoff Touch and works fine. In this way I have a Touch to control lights and a thermometer in every room.
