### ISSUE TITLE
how to configure HC-SR501 for only MQTT messages

### ISSUE THREAD

**Issue by kutteg** [arendst/Sonoff-Tasmota#679]
I have added successfully a HC-SR501 to a sonoff th16 on GPIO 4, but I dont want the sensor to trigger the relay, I want it to only send MQTT message on state change ("Switch1": "ON" "Switch1": "OFF"). How do I have to configure that scenario?

Thanks in advance...

**Comment by kutteg** [comment]
I want only the hardware button to trigger the relay

**Comment by davidelang** [comment]
research switchtopic
k
