### ISSUE TITLE
Use Sonoff as momentary relay

### ISSUE THREAD

**Issue by SecurityAddicted** [arendst/Sonoff-Tasmota#68]
Hi, just a question, can the Sonoff be used as momentary relay with the TASMOTA firmware?
I mean, activate, wait a specific amount of time, then deactivate, sending it a specific command?
Thanks.

**Comment by Nayar** [comment]
I guess you'll have to use a third party software run a timer and send the required commands to activate and deactivate. Try Homeassistant

**Comment by jaysuk** [comment]
Or node red

**Comment by arendst** [comment]
Why not using pulsetime? Set it to a value like 100 and after a power on command it turns off after 10 seconds.

See the wiki for more functional commands...

**Comment by SecurityAddicted** [comment]
Thanks to everyone for the tips :)
Theo, just saw the pulsetime option in the wiki... there is any documentation about the commands around?

**Comment by davidelang** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

I missed it as well
