### ISSUE TITLE
Sonoff POW reset Total

### ISSUE THREAD

**Issue by mkh595** [arendst/Sonoff-Tasmota#685]
According to documentation  command **EnergyReset 1 = 'Reset Energy Today'** but it also reset EnergyTotal

21:04:58 MQTT: home/tele/home214/ENERGY = {"Time":"2017-08-03T21:04:58", "Total":1.944, "Yesterday":1.999, "Today":1.944,
21:05:09 CMND: cmd/home214/EnergyReset 1 
21:05:09 RSLT: Receive topic /EnergyReset, data size 1, data 1 
21:05:09 RSLT: DataCb Group 0, Index 1, Type ENERGYRESET, Data 1 (1)
21:05:09 MQTT: home/stat/home214/RESULT = {"EnergyReset":{"Total":0.000, "Yesterday":1.999, "Today":0.000}} 
21:05:11 Cnfg: Save (1492 bytes) to flash at FA and count 94 
21:05:16 MQTT: home/tele/home214/ENERGY = {"Time":"2017-08-03T21:05:16", "Total":0.000, "Yesterday":1.999, "Today":0.000,

**Comment by arendst** [comment]
EnergyTotal is calculated at midnight as EnergyTotal + EnergyToday. As your EnergyTotal equals EnergyToday and you reset EnergyToday your EnergyTotal becomes 0 too.

Watch what happens if you keep it running for more than one day...
