### ISSUE TITLE
Homebridge Support - Feedback

### ISSUE THREAD

**Issue by jat80** [arendst/Sonoff-Tasmota#694]
Hi there,

Just wondering if anyone has tried with success @MacWyznawca homebridge plugins for sonoff temp and humidity?  Even just the switch as well?

I was unable to get the temp and humidity ones to work properly as explained [here](https://github.com/MacWyznawca/homebridge-mqtt-temperature-tasmota/issues/5) but no response from @MacWyznawca.  

If anyone else has got them to work sweet with homebridge could you let me know. 

Thanks!

**Comment by kutteg** [comment]
Yes, they all work fine...

**Comment by jat80** [comment]
@kutteg how long have you had them working for?  Did you have any problems initially setting them up?
