### ISSUE TITLE
Remove Dangerous FLASHMODE Command

### ISSUE THREAD

**Issue by DeanCording** [arendst/Sonoff-Tasmota#696]
Given the ability to brick ESP8285 devices by setting an unsupported flash mode (#598), it might be wise to remove the (undocumented) Flashmode command that allows the setting of the flash mode.

The whole command could be removed as the current flash mode is also returned by Status 4.

Lines 1285-1292 in sonoff.ino

**Comment by mihalski** [comment]
I think the only way to brick an ESP is to literally hit it with a brick, but if this is no longer necessary or useful then I';m sure it will get removed.

**Comment by arendst** [comment]
Will be removed in next release.

**Comment by arendst** [comment]
Done
