### ISSUE TITLE
Adding additional displaing on web page - ADC, and setup option for ADC

### ISSUE THREAD

**Issue by roblad** [arendst/Sonoff-Tasmota#697]
Hi,

Is it possible to add result of "AnalogInput0":xx to web page ?
Nice to have also some settings for ADC to set USE_ADC_VCC or AnalogInput0 or none.

Additionally I suggest function for LDR that could be easier then use LX measurement through I2C light sensitivity

Thanks,

**Comment by khcnz** [comment]
There is already a compile time option (which is the only possibility) to select between VCC or or A0 for the ADC.

**Comment by roblad** [comment]
Hi,

Is it possible to add that to config page and display it on main web page either VCC or A0 value ?
If there is, haw to switch it on ?

**Comment by roblad** [comment]
Hi,

Any news on it ?

Thanks,
