### ISSUE TITLE
Fixed: HUE App wants to update emulated HUE devices

### ISSUE THREAD

**Issue by chinds185a** [arendst/Sonoff-Tasmota#698]
So I successfully flashed this firmware onto a 4CH sonoff  today. I have turned on the hue emulation. I want to control these devices with Alex and ultimately Apples home kit.

Alex does not discover the devices so I guess I need to add them in the HUE app first? 

Going to the HUE app it find the new bridge and the 4 named devices. However I cannot save the light/add them to a room etc as the HUE app is continuously trying to update the firmware on the new emulated hue bridge and obviously fails.

How can I get each ch discover-able by Alexa? Using wemo emulation works but again only for a single Chanel.

**Comment by arendst** [comment]
Update emulated HUE devices as designed. Don't know how to fix. Probably have to tell the App I have a way to new version....

Alexa should work without any Hue App.

**Comment by Courty40** [comment]
I've just tried the same thing with a 4ch and version 5.5.2 and I'm seeing the same behaviour.
Alexa see ch1 of the 4ch device in Wemo mode but doesn't detect the Sonoff at all in Hue mode. Tried rebooting/power off etc
I had this working a few versions ago on a 2ch Sonoff so I do t believe it's the Alexa

**Comment by Courty40** [comment]
And I can confirm the hue app finds the Sonoff and tries to upgrade it even though the Alexa device search doesn't
Something changed in the Hue discovery protocol maybe ?

**Comment by arendst** [comment]
My Hue code changed between version 5.2.4 and 5.3.0 and might be causing you trouble. I notice the same behaviour on my Hue App regarding the firmware update. I just ignore it.

I do not have Alexa so I can't test. If others have problems with it too please let me know.

**Comment by Courty40** [comment]
Just remoted into one I know works with Hueand that's a BN-SZ LED and its running 5.3.0

**Comment by Courty40** [comment]
More info, Alexa does poll the unit and the unit is responding but Alexa doesn't accept the Sonoff

23:44:31 HTTP: Root
23:44:33 HTTP: Console
23:44:46 Wifi: Checking connection...
23:44:46 Wifi: Connected
23:44:48 UPnP: HUE 3 response packets sent to 192.168.1.16:50000
23:44:48 UPnP: HUE 3 response packets sent to 192.168.1.16:50000

**Comment by chinds185a** [comment]
Still having problems with this. Alexa just doesn’t discover the hue devices. 

Is it worth downgrading the firmware used?

**Comment by altelch** [comment]
Hi,

would be interesting to see what was changed between the last working version and the current version. I still get the emulation working but discovery mostly takes 3 to 4 tries before it works. Maybe also something was changed in Echo firmware during the last versions. Didn't look into this. Hopefully I find some time the next days to check into this issue.

Greetings,

      Heiko.

**Comment by arendst** [comment]
@altelch Heiko as noted above I did some rewrites to the hue code to:

- get Philips hue apps working on my phone (mostly still fails. only the non color app dimmer function seems to work but it doesn't send hue data;  it only send xy color data which we do not support)
- integrate Sonoff Led with hue

As I do not own an echo I can't test Alexa.

**Comment by m3zm3riz3** [comment]
I get the same issue, Alexa is not discovering the Hue emulated devices but i can use the "old" hue app to control them.

**Comment by chinds185a** [comment]
Anymore news on this? kind of makes this device/firmware pointless for what I purchased it for.

**Comment by altelch** [comment]
Hi,

did a merge request to fix this. Hue emulation and detection with 
alexa/echo is working again after this fix. See Pull-Requests.

Greetings,

      Heiko (altelch).

Am 09.09.2017 um 12:41 schrieb Chris Hinds:

**Comment by chinds185a** [comment]
Hi, Thanks, will this work as an OTA update or will I need to re-flash the device?

**Comment by altelch** [comment]
Hi,

I'd guess Theo will release a 5.7.1 soon which should be OTA updateable. 
No need to flash.


Greetings,

      Heiko.


Am 09.09.2017 um 18:05 schrieb Chris Hinds:

**Comment by arendst** [comment]
Working on it . Hold tight.

**Comment by Courty40** [comment]
I've got several Hue emulated and wimo emulated devices controlled via Alexa so will keep an eye for 5.7.1
Will test a couple of them once it's released..

Courty

**Comment by chinds185a** [comment]
Nice. Happy to test this too once’s it’s out. Thanks all.

**Comment by altelch** [comment]
Fixed and testet. 5.7.1 works as expected.

**Comment by Courty40** [comment]
I just uploaded 5.7.1b to a Sonoff BN-SZ LED ceiling Module using the web interface.

I can confirm it works perfectly with Alexa and doesn't cause an error in the HUE app..

Courty

**Comment by arendst** [comment]
Thnx for feedback.

**Comment by nickdos** [comment]
Just tried using Hue app with 5.12.9 and the Hue app wanted me to update the firmware on the Sonoff, as per this thread. Hue app running on iOS with version 2.19.1 (9508). Makes the Hue emulation mode useless and also completely locks up the Hue app, as there is no way to remove the new "bridge" it wants to update. Only work around is to delete the app and reinstall again.

**Comment by austinlg96** [comment]
@nickdos you'll probably want to follow issue #2431
