### ISSUE TITLE
Disable relay option

### ISSUE THREAD

**Issue by pascalsaul** [arendst/Sonoff-Tasmota#699]
In some cases I don't want to use the internal relay because of soft switching.

RelayState | 0 / off | Disable use of relay

**Comment by neographikal** [comment]
This would be really really handy! I use a touch as an activator for my garage door, just to send a mqtt command. The relay doesn't have to switch (it would be nice if that could be done through mqtt separately from the button)

**Comment by arendst** [comment]
Start reading the wiki. Get to know avalable commands. Search the issues and close this one please.

**Comment by davidelang** [comment]
hint buttontopic

**Comment by balk77** [comment]
I was looking for the same functionality; using my POW to measure power consumption of my washing machine which I don't want to switch off via the relay :)

Issue the _PowerOnState_ command with value _4_ and it is solved.

For instance as follows:
http://192.168.0.32/cm?cmnd=PowerOnState%204

See https://github.com/arendst/Sonoff-Tasmota/wiki/Commands

**Comment by pascalsaul** [comment]
When you use HA with Autodiscovery you get a nice and extra device added automatically... With PowerOnState 4 you can't control the relay but it is always on.

![image](https://user-images.githubusercontent.com/659660/43040756-640b5806-8d4c-11e8-8c0c-82e257c52147.png)

I would like to request a PowerOnState | 6 | Turn relay(s) off and disable further relay control

**Comment by Fusseldieb** [comment]
> I would like to request a PowerOnState | 6 | Turn relay(s) off and disable further relay control

Me too. Always on is just energy consuming. I don't know why nobody has thought to put a "off" option there too.

**Comment by blark** [comment]
> > I would like to request a PowerOnState | 6 | Turn relay(s) off and disable further relay control
> 
> Me too. Always on is just energy consuming. I don't know why nobody has thought to put a "off" option there too.

This ^^ Please consider this. It is logical always off functionality if there is already always on.

**Comment by ascillato** [comment]
It is possible to set relays as `relay_i` ( inverted ) and use `poweronstate 4`

**Comment by ascillato** [comment]
Besides that, you can define output_low as gpios instead of relay.

**Comment by blark** [comment]
> It is possible to set relays as `relay_i` ( inverted ) and use `poweronstate 4`

Good idea, thank you @ascillato. I had thought of just removing the relay from the config but wasn't sure what that would do. 

I just set the following config: 

```
PowerOnState 0
SetOption73 1
```

And the button no longer toggles the relay, power always stays off. I guess this is yet another way to achieve this, I didn't think of it earlier.

**Comment by barbudor** [comment]
With this, it is still possible to change the relay by sending a POWER command
If you want to totally disable that, use "OUTPUT_LOW" instead of "RELAY"

**Comment by blark** [comment]
> With this, it is still possible to change the relay by sending a POWER command
> If you want to totally disable that, use "OUTPUT_LOW" instead of "RELAY"

Thanks! In my case I'm only worried about the physical button, so this does the trick.
