### ISSUE TITLE
sonoff auto ON after power off

### ISSUE THREAD

**Issue by h4x00r8** [arendst/Sonoff-Tasmota#70]
hey

there is any configuration to auto on sonoff after power off??

thanks

**Comment by arendst** [comment]
Browse the wiki looking for commands.

**Comment by altelch** [comment]
MQTT Commands: PowerOnState 1

**Comment by h4x00r8** [comment]
thank you altelch
can you explain how i implement it via mqtt switch?
(im using homeassistant)

thank you for your help!

**Comment by h4x00r8** [comment]
thanks you again for your help,
ive managed to get it working
