### ISSUE TITLE
Sonoff S20 - Domoticz/out - Where is my normal Toggle on/off Function?

### ISSUE THREAD

**Issue by FabianHM** [arendst/Sonoff-Tasmota#709]
Why my S20 changed the normaly toggle on/off function to Domoticz, what I didn't need?
![domes](https://user-images.githubusercontent.com/26110738/29087549-9cce773c-7c76-11e7-8a29-41c71da759eb.JPG)

Normaly I see there on/off
![sonoff-off](https://user-images.githubusercontent.com/26110738/29087412-23322ef0-7c76-11e7-8525-0b76b0c64187.JPG)
What happend?

**Comment by arendst** [comment]
Well you could start to mention that you might have installed a new version...

**Comment by FabianHM** [comment]
All my devices have the Program version | 5.3.0... an the others work fine....

**Comment by arendst** [comment]
But did you upgrade this one just a minute ago?

**Comment by arendst** [comment]
Still no answer to my question....

Anyway, try to backup the confuration and then restore the configuration.

**Comment by FabianHM** [comment]
The answear is NO, I didn't update this device. 
Now I have tried to backup an configuration from another device and plan to restore it on this problem device. It doesn't work, I get this message:
![message](https://user-images.githubusercontent.com/26110738/29088809-abc309e8-7c7a-11e7-81e3-870f37645625.JPG)

**Comment by arendst** [comment]
Doesn't work with firefox. 

Try chrome and keep using the same device. So backup config of broken device and restore config just made from broken device.

**Comment by FabianHM** [comment]
It works with this restore way perfekt as before, perfect!

I like your Project very much and your fast support is great, thanks for this great Tool Theo :-)
