### ISSUE TITLE
Readings are stuck on POW webpage

### ISSUE THREAD

**Issue by mr-const** [arendst/Sonoff-Tasmota#711]
My POW which is always ON shows stuck data on the webpage, all readings are the same and don't change for two last days, however console shows correct data and mosquitto gets all actual data as well.
I tried to restart, power-off, but nothing helps...
Is there any way to fix this issue, or have to do hard reset only?
![POW](https://i.imgur.com/dVwgYeJ.png)

**Comment by arendst** [comment]
Clear your browser cache. Change browser.

**Comment by mr-const** [comment]
Hm... Didn't think about browser issues at all. Everything is fine now, thanks.
