### ISSUE TITLE
Is it possible to access the analogue pin on the Wemos D1?

### ISSUE THREAD

**Issue by mihalski** [arendst/Sonoff-Tasmota#714]
I wanted to be able to read the value of a variable resistor which requires the analogue pin but I can't even find the analogue pin bin the device configuration.

Am I looking in the wrong place or is this just not a feature available in Tasmota?

EDIT: I can see this in the source:
```
     GPIO_ADC0         // ADC0   A0 Analog input
```
But I don't see how I would access it.

**Comment by arendst** [comment]
The problem with the analog pin is that changing it's function can only be done at compile time. Tasmota default function is reading power supply voltage.

In your case you will need to disable it in user_config.ino and recompile the code.

The analog value will then pop up as a sensor value.

**Comment by mihalski** [comment]
Thank you.
Maybe a mention on the wiki under connecting sensors could mention this from the user_config.ino

```
#define USE_ADC_VCC   // Display Vcc in Power status. Disable for use as Analog input on selected devices
```
I totally missed it.

**Comment by martinjuhasz** [comment]
Can someone guide me where this A0 pin acutally is on the sonoff basic? would like to add an analog photo resistor.
