### ISSUE TITLE
Backup fails

### ISSUE THREAD

**Issue by SamNitro** [arendst/Sonoff-Tasmota#715]
Hey, on my Mac fails the backup with Network connection lose.
In my VM with Win 7 it works.

Can someone help me? Thanks

**Comment by arendst** [comment]
Try Chrome on your mac

**Comment by SamNitro** [comment]
Firefox and safari don't

Chrome works Thank's

**Comment by arendst** [comment]
Noticed it too. I have no idea why but a HTTP guru might shine some light on it.
