### ISSUE TITLE
28k of extra memory discovered

### ISSUE THREAD

**Issue by ThomDietrich** [arendst/Sonoff-Tasmota#717]
A mystery, a miracle or just a typo? Come and find out!! 😄 

https://github.com/arendst/Sonoff-Tasmota/wiki/Theo's-Tasmota-Tips

Or to say it in other words: The config part of the last diagram is a bit confusing.

**Comment by arendst** [comment]
That's to keep the process as secret as possible...

**Comment by ThomDietrich** [comment]
So mystery? Schrödingers memory? It's there but it isn't? 😸
