### ISSUE TITLE
sonoff does not connect after light off

### ISSUE THREAD

**Issue by moonfarms** [arendst/Sonoff-Tasmota#720]
#I am living in a place in Africa where there is often light off (erratical electricity supply). I have noticed that when power (electricity) is back and everything is back online, due to the delay of the wifi router to reboot the sonoff module will not connect to wifi unless, probably because at sonoff reboot there is no wifi, after wifi router is back online, I have to power off/on the power of the sonoff module for it to reconnect to wifi network
I understand it is not a general issue but related to different environmental? condition.
Thanks in advance

**Comment by arendst** [comment]
What is the value of wificonfig? Try to set it to 4 to retry wifi connection.

**Comment by moonfarms** [comment]
Thank you for your prompt help.
2morrow i will look where to config wificonfig and get back.
have a nice morning/day/evening wherever you are.
