### ISSUE TITLE
don't see parameters domoticz/in  and domoticz/out 

### ISSUE THREAD

**Issue by slamxai** [arendst/Sonoff-Tasmota#729]
Hi everybody,

I'm setting Domoticz config of Sonoff TH10
But I don't see parameters domoticz/in  and domoticz/out like in wiki 
https://github.com/arendst/Sonoff-Tasmota/wiki/Domoticz
Please help.

![01](https://user-images.githubusercontent.com/30963393/29244471-0bf252d0-7fc1-11e7-8dfe-f2527b8b08d9.png)

Petr.

**Comment by arendst** [comment]
These parameters have been removed as they are always the same. Now hardcoded in Tasmota.
