### ISSUE TITLE
Reduce power off after system restart

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#733]
Hello,

I'm searching for solutions to reduce the power offs. First: set `WifiConfig 4` to skip the restart after a wifi reconnect. Is there any solution to skip the power off after a MQTT broker reconnect/restart? For example something with the `retain` state?

Thanks for help.

Greetings
Fabi

**Comment by ionciubotaru** [comment]
When sonoff restarts it sends 3 MQTT messages named INFO1, INFO2 and INFO3
Please publish the content of them.

**Comment by 0n3-70uch** [comment]
Ok I will do it in the evening...

**Comment by ionciubotaru** [comment]
send also the result of `STATUS 0`

**Comment by davidelang** [comment]
read the wiki page on poweronstart, it tells you how to find what is retained in 
your mqtt server and clear it.

**Comment by 0n3-70uch** [comment]
At the moment the devices working fine... I close this issue now. Thanks for the your help.
