### ISSUE TITLE
WS2812 colour via Domoticz

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#734]
Hello,

is it possible to change the WS2812 colour through Domoticz. At the moment I can only change the brightness...

Greetings Fabi

**Comment by 0n3-70uch** [comment]
Hello lovely bot... This question is still up-to-date. :-)

**Comment by 0n3-70uch** [comment]
Stop stale :-)

**Comment by ascillato2** [comment]
Hi, 

Added the label enhancement for the to do list.

_(The bot will not bother you again)_ :wink:

**Comment by 0n3-70uch** [comment]
Haha thank you :-)
