### ISSUE TITLE
Wemos D1 mini 

### ISSUE THREAD

**Issue by Gary202** [arendst/Sonoff-Tasmota#737]
Is it possible to rum Tasmota on a Wemos d1 mini??

**Comment by Gary202** [comment]
Do i flash it like normal but select wemos as the board in arduino? also are the gpios the same?

**Comment by davidelang** [comment]
the wemos module in tasmota allows you to hook up any function to any gpio. I 
don't know how the D1 mini is wired, so I can't tell you what is hooked to each 
gpio

**Comment by Gary202** [comment]
Thank you i will do some research and testing when i get my wemos and report back.!!

**Comment by mkh595** [comment]
yes, wemos is working, here are pins you can use

![wemos2](https://user-images.githubusercontent.com/30566575/29286618-fae7fc92-8132-11e7-8e3a-0d2d55ea868c.PNG)

here is example with 2x DS18B20, 1x DHT22, 1x BME 280 and 3x Relay
![wemos1](https://user-images.githubusercontent.com/30566575/29286704-3e73a696-8133-11e7-98f8-38b9dfe542b8.PNG)
