### ISSUE TITLE
Bug in xdrv_ir_send for Mitsubishi HVAC

### ISSUE THREAD

**Issue by gheesung** [arendst/Sonoff-Tasmota#740]
The Mitsubishi HVAC cannot be switch off using IR and I have modified the code slightly.

At line 264 of xdrv_ir_send.ino, the library is expecting a boolean and not sure why the original code does a binary complement. I have removed the '~' and my AC can be controlled using Tasmota.

Orig
`mitsubir->setPower(~HVAC_Power);`

Change to
`mitsubir->setPower(HVAC_Power);`

If this is a confirmed bug hope that it can be fixed into the master branch.

**Comment by arendst** [comment]
As I do not own a Mitsubishi HVAC I have to rely on your experience.

I'll make the change in next release.
