### ISSUE TITLE
WPA2 Enterprise + MsChapv2 support

### ISSUE THREAD

**Issue by shmrymbd** [arendst/Sonoff-Tasmota#745]
HI, I cant connect tasmota to above WIFI AP. Pls advice

**Comment by shmrymbd** [comment]
https://www.hallgeirholien.no/post/esp8266-eap . could anyone help to explain this

**Comment by i3laze** [comment]
Thinking of WPA2-Enterprise too.. any updates on plaintext login+pass support?
