### ISSUE TITLE
Is the <input> in the SerialConsole gone?

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#747]
From time to time I have used the console e.g. on COM5 to connect to my device and make changes to the access point. I have upgraded my branch from 5.2.4 to the newest version of today. My console window does not accept anymore any stuff. Correct? or a bug? Using still putty without a change.

I type anything into the window, but tasmoto does not react.

**Comment by arendst** [comment]
No change as far as i know. Might be your browsers cache? Still works fine with me.

**Comment by stefanbode** [comment]
messed with putty. Atom has problems with the ports, but Arduino IDE show all is working. Will find it
