### ISSUE TITLE
Upload issues

### ISSUE THREAD

**Issue by efp1** [arendst/Sonoff-Tasmota#756]
I'm having issues uploading the firmware to my sonoff switch. I've tried using both platformio ide and arduino. They both start uploading fine, but get stuck when they reach over 85% uploaded. It doesn't give me an error, it just remains stuck at uploading.

Any ideas? I've tried searching for similar issues but can't find any. 

Thanks!

**Comment by efp1** [comment]
<img width="814" alt="screen shot 2017-08-19 at 16 08 00" src="https://user-images.githubusercontent.com/22729223/29487899-b00262b6-84f8-11e7-98a1-6edd96af97bc.png">

Here's a screenshot as an example. I've tried it several times and it keeps happening.

**Comment by efp1** [comment]
No ideas as to what can be causing it?

**Comment by pierrerigal** [comment]
@efp1 same problem here, did you find any solution ?

**Comment by pierrerigal** [comment]
Solved. Don't forget to "Clean" between 2 uploads.  
Platform.io > Clean

**Comment by ol-v-er** [comment]
I confirm. Cleaning the project before a new upload solve the problem
