### ISSUE TITLE
Pulsed Output

### ISSUE THREAD

**Issue by ht2507** [arendst/Sonoff-Tasmota#757]
Hello,
Thanks for this awesome software!
I could successfully install and test Sonoff software on my Sonoff Wifi device. I would like to use it for opening the garage. For this application I need a pulsed output, means on the http request the output shall be set on for 1..2 seconds only and after this time period go to off.

Kindly ask you to point me to the place in the source code where I have to put the statements for the delay and switch off in. 

Regards
ht

**Comment by ht2507** [comment]
Sorry for the stupid question. I just saw the possible and implemented commands.

Regards
ht

**Comment by arendst** [comment]
Use PulseTime command
