### ISSUE TITLE
The lights are flickering without warning

### ISSUE THREAD

**Issue by albukrek** [arendst/Sonoff-Tasmota#758]
**First of all Thanks, for your wonderful work!**

(All devices have Sonoff-Tasmota-5.5.0)

I have installed  three Sonoff units a few days ago. 
- (2) **Sonoff basic**
     - This unit is  responsible for the 2 night lamps
- (1) **Sonoff 4-channel** 
    - One channel is responsible for the main light in the room
    - The other three channels control the fan.

**All the lamps** are connected on one side to the old switches on the wall, and on the other side to GPIO  14 in the basics,  and the 4-channel lamp switch to GPIO 3.

The old fan switch has been replaced by WEMOS d1 pro so that the Sonoff GPIO is not used for the fan channels.

In general, everything works properly, but when turning on or off one off the lights manually, occasionally without warning the lamp toggles.

We think it happens only in case  the old switch is used, so in order to test this hypothesis yesterday and today we lit the light only through the Home Assistant and the occasionally toggling have  disappeared, except for one case of shutdown and fire back almost immediately.

I'm sure that I have done something wrong, please advise me how to fix this problem.

P.S. Every unit has a unique topic and group. The client id  is generated automatically by default.

Thank's
Arik

**Comment by albukrek** [comment]
I Think that there is a simple solution for my problem:

1. The Sonoff devices  were updated to version5.6.1
2. Change the topic of the mqtt from stat to cmnd (for more detailes see this wiki [topic](https://github.com/arendst/Sonoff-Tasmota/wiki/Understanding-SwitchMode-and-SwitchTopic#switchtopic) ) 
Run commands: 
SwitchTopic 2.
SwitchMode to 1
I'm not sure, but maybe this way it the switch state is retained in the MQTT

**Comment by albukrek** [comment]
The above fix has one drawback, every 50 minutes or so the relay flickers.

Can anyone help please help me?

**Comment by albukrek** [comment]
Found the problems:

1. Topic name in home assistant was written in lower case, while in Sonoff-Tasmota the name is all in upper case.
2. Some retain topic were left on the MQTT server, these topics were deleted.

Thanks!
<img width="1432" alt="screen shot 2017-08-28 at 10 19 18 pm" src="https://user-images.githubusercontent.com/14253503/29789733-b8846a1c-8c3f-11e7-928d-bfd95885524a.png">

**Comment by PeggyFree** [comment]
How do you check such retained messages ? My mosquito mqtt server is
running as a service, I could'nt find any solution to check all the mqtt
trafic and the potential residual subscriptions.

**Comment by davidelang** [comment]
see the wiki page on poweronstate, it tells you how to check for retained 
messages

**Comment by mkh595** [comment]
You can see retained messages e.g. in MQTTfx client. If you subscribe topic, you will receive first all retained messages (if there are any)

![mqttfx](https://user-images.githubusercontent.com/30566575/29820497-f0ef1660-8cc4-11e7-87eb-b34b93316e6a.PNG)

**Comment by albukrek** [comment]
Sorry to report, but the issue have returned...
This time it only happens when the switch is in an open state (circuit is open) from #665 and others 
The solution may be adding a resistor and capacitor

**Comment by albukrek** [comment]
Working fine after adding a pullup resistor and capacitor.

**Comment by aspitznyc** [comment]
Hi @albukrek what size of capacitor did you use? And where did you put it? Between which pins? Thanks!!!

**Comment by davidelang** [comment]
anything in the pF range should be ok.

**Comment by aspitznyc** [comment]
Sorry about my lack of electronics understanding, but could you provide and example? I'm a noob in all this.

Thanks for your help!

**Comment by davidelang** [comment]
see https://github.com/arendst/Sonoff-Tasmota/wiki/Expanding-Sonoffs
