### ISSUE TITLE
cannot compile with errormessage related to IRsend command

### ISSUE THREAD

**Issue by andreasloe** [arendst/Sonoff-Tasmota#764]
I donloaded the latest code (version 5.6.1.c) today but cannot compile it. The problem has to do with the IRsend-command. I am getting the following error message

`drv_ir_send:48: error: 'IRsend' does not name a type`
` IRsend *irsend = NULL;`
` ^`
`/Users/andies/Documents/Arduino/libraries/Sonoff-Tasmota-development/sonoff/xdrv_ir_send.ino: In function 'void ir_send_init()':`
`xdrv_ir_send:52: error: 'irsend' was not declared in this scope`
`   irsend = new IRsend(pin[GPIO_IRSEND]);  // an IR led is at GPIO_IRSEND`
`   ^`
`xdrv_ir_send:52: error: expected type-specifier before 'IRsend'`
`   irsend = new IRsend(pin[GPIO_IRSEND]);  // an IR led is at GPIO_IRSEND`
`                ^xdrv`

I  remember last time that I added 
` #include <IRsend.h>  // Needed if you want to send IR commands.`
` #include <IRrecv.h>  // Needed if you want to receive IR commands.`
at line 27/28 in xdrv_ir_send.ino and that solved my problem. But this time I was not successful, the error message is attached since it is so long.

[error.txt](https://github.com/arendst/Sonoff-Tasmota/files/1237246/error.txt)

**Comment by andreasloe** [comment]
After including the two lines I am getting this message

`/Users/andies/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: /var/folders/l6/myrckv8d12z9_06fl49fm36h0000gn/T/arduino_build_803675/sonoff.ino.elf section `.irom0.text' will not fit in region `irom0_0_seg'
collect2: error: ld returned 1 exit status`

**Comment by davidelang** [comment]
It sounds as if you have not gone through the wiki prereq section, so you are 
missing a library (and probably others)

**Comment by andreasloe** [comment]
I went throught that section but was not able to install it via the library manager, see screenshot below (no version 1.0.2 available). Therefore, I downloaded it by hand and I used the newest version. Is that the problem?
<img width="783" alt="bildschirmfoto 2017-08-20 um 20 19 51" src="https://user-images.githubusercontent.com/10688946/29497252-4e0d918c-85e5-11e7-840e-5e65be89cad2.png">

**Comment by davidelang** [comment]
This error normally means that it didn't find the library, do a more verbose 
compile and I'll bet that it's not finding it.

**Comment by andreasloe** [comment]
But doesn't
`Bibliothek IRremoteESP8266 in Version 2.1.0 im Ordner: /Users/andies/Documents/Arduino/libraries/IRremoteESP8266  wird verwendet`
say that it is using this library? (The error message appears earlier.)

**Comment by andreasloe** [comment]
I remember now what I did and what solved my problem. I added the lines 25 and 26 in the screenshot below.

<img width="760" alt="bildschirmfoto 2017-08-20 um 20 35 37" src="https://user-images.githubusercontent.com/10688946/29497400-413a2180-85e7-11e7-92b6-505ef81ad83f.png">

But who's problem is this? Is my installation corrupt?

**Comment by arendst** [comment]
As the wiki tries to explain in several cases the only supported libraries are provided in the repository and the release Source code download.
