### ISSUE TITLE
Support for GY-2561/TSL-2561

### ISSUE THREAD

**Issue by crispy78** [arendst/Sonoff-Tasmota#765]
Hi there,
I would like to connect a GY-2561/TSL-2561 sensor to my Sonoff S20, but I can't seem to get it to work. It communicates through I2C. Can someone tell me if it is supported (can't find it in the list of devices)? If not how do I get it to work?

Thanks in advance,

Christiaan

**Comment by arendst** [comment]
That tsensor is not supported. The BH1750 is supported.

**Comment by crispy78** [comment]
And what about the GM5528 photo resistor (LDR)? It is included in the Sonoff SC.

**Comment by arendst** [comment]
And connected to an atmel microcontroller which connects to the esp8266.

**Comment by crispy78** [comment]
I've modified a Sonoff S20 with the BH1750 and it's working fine. Thanks
