### ISSUE TITLE
Sonoff G1 GSM GPRS Module

### ISSUE THREAD

**Issue by EmilySmith0** [arendst/Sonoff-Tasmota#769]
@arendst  
Can you please add code for Sonoff G1 GSM/GPRS.
http://sonoff.itead.cc/en/products/sonoff/sonoff-g1
Looking Forward
Thanks 
Emily

**Comment by ps2mdg** [comment]
Yes, please i need code for g1

**Comment by karobyy** [comment]
I live in serbia. In my country have 3 gsm operator, and only work with 1 (VIP telekom)

**Comment by AHBkingman** [comment]
Sonoff G1 will improve M2M IoT a lot. Please if somebody had developed a firmware for G1 please upload it.

**Comment by mrrcomp** [comment]
Hi
Does anyone have info on the G1 to allow it to Transmit Sensor info to mqtt??

**Comment by eazuka** [comment]
@arendst any hope of Sonoff G1 being supported

**Comment by joe63** [comment]
@arendst any hope of Sonoff G1 being supported, it been a wish come true for my use case, now remaining Tasmota support

**Comment by vshaev** [comment]
@arendst any hope of Sonoff G1 being supported, it been a wish come true for my use case, now remaining Tasmota support

**Comment by i3laze** [comment]
Up.

**Comment by obilginer** [comment]
is there any news?

**Comment by AdrielGH** [comment]
Hello all, news?
