### ISSUE TITLE
Reset when use serial port monitor

### ISSUE THREAD

**Issue by Greg2002** [arendst/Sonoff-Tasmota#77]
3.9.17 20170217
1.When I used a serial port monitor - device resetting:
(Config - Sonoff Basic, GPIO4+GPIO14 as I2C), see below  a log
00:04:42 MQTT: stat/sonoff/RESULT = {"Reset":"Reset and Restarting"}
00:04:43 Config: Use default configuration
00:04:57 SYSL: Syslog Host not found so logging disabled for 600 seconds. Consider syslog 0
00:04:58 APP: Restarting....
and so on loop
2. When you Turn On Sonoff -the very first second relay is always On (!), and only after loading - it becomes On or Off as was in last stage. It's dangerous.

**Comment by hoekbrwr** [comment]
You mean Web Console? If you try to use serial monitor with pin 4 using I2c then there is a conflict because pin 4 is normally used for serial communication.

**Comment by Greg2002** [comment]
No, not Web Console. I tried to read information from Arduino IDE serial port. After that Sonoff resetting to default configuration.

**Comment by hoekbrwr** [comment]
All the things you do on the HW serial connection can be done from the Web Console. You cannot use a serial connection when defining pin 4 as I2c. The FW will produce a reset as you experienced. So search for the IP address of your Sonoff on your local network and type <IP-address> in the address line of you favorite browser. Look for commands in the wiki side menu
!

**Comment by Greg2002** [comment]
OK. I know it. It's not necessary read data from Arduino IDE when you have Console and MQTT.
I think that only RX TX pins could conflict with serial port. Thank you
