### ISSUE TITLE
How to get "trailing spaces" removed on Windows

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#770]
Hi arendst, I see that just from code cleaning there are more and more trailing spaces coming into the code more or less by accident I assume. You can easily remove them on Windows using Notepad++.

Hit CTRL-H -> Replace ->Check in the lower part "Extended (\r \n ...)"
-> Search for SPACE + \r   == " \r"
-> Replace with \r == "\r"

Execute as long as you find something with "REPLACE ALL" or "REPLACE ALL in all open documents"

This is straightforward.

**Comment by arendst** [comment]
I am now using VisualStudioCode with platfoemio plugin allowing automagic removal of trailing spaces.
