### ISSUE TITLE
Sonoff SC Individual Data commands

### ISSUE THREAD

**Issue by EmilySmith0** [arendst/Sonoff-Tasmota#780]
Sonoff SC publishes MQTT data as
**MQTT**: tele/sonoffSC/SENSOR = {"Time":"2017-08-24T5:42:45", "Temperature":24.0, "Humidity":53.0, "Light":100, "Noise":10, "AirQuality":100, "TempUnit":"C"}
Is it possible to get individual values after modifying code
i,e stat/sonoffSC/status 20 for temperature
stat/sonoffSC/status 21 for humidity
stat/sonoffSC/status 22 for Light
If yes
Where I should I start. I am not a pro :)

Emily

**Comment by arendst** [comment]
Examine file xdrv_snfsc.ino

**Comment by EmilySmith0** [comment]
I know these variables contains values from sensors
![capture1](https://user-images.githubusercontent.com/30232790/29668262-f5c79470-88f8-11e7-8795-6a3be9f591bc.PNG)

but where I should modify to get get values with commands
like stat/sonoffSC/Status  20
Many Thanks
Emily

**Comment by arendst** [comment]
File sonoff.ino around line 1850

**Comment by EmilySmith0** [comment]
Sonoff SC publishes MQTT data as
MQTT: tele/sonoffSC/SENSOR = {"Time":"2017-08-24T5:42:45", "Temperature":24.0, "Humidity":53.0, "Light":100, "Noise":10, "AirQuality":100, "TempUnit":"C"}
I want to Publish data as 
tele/sonoffSC/**SENSOR1** = {Temperature":24.0}
tele/sonoffSC/**SENSOR1** = {Temperature":24.0}
tele/sonoffSC/**SENSOR1** = {Temperature":24.0}
tele/sonoffSC/**SENSOR1** = {Temperature":24.0}

**Comment by EmilySmith0** [comment]
Changed highlighted line and applied loop for 5 times to get individual values
