### ISSUE TITLE
Is there an internal variable I can use to see uptime?

### ISSUE THREAD

**Issue by stefanbode** [arendst/Sonoff-Tasmota#781]
Many of my devices run on battery, I want to see how long they are online until they go back into deepsleep. Is there a variable I can use for this?
I use the NTP Service that changes my clock. Therefore this value does not work for me.

**Comment by davidelang** [comment]
I don't think tasmota does deepsleep, I think it's always running to stay 
connected to the network and look for commands/buttonpresses.

**Comment by stefanbode** [comment]
No worries about that. This is my own mod/fork. Working well because I have several solar power WEMOS irrigation sensors. Anyhow is there a variable for the uptime?

**Comment by arendst** [comment]
sonoff.ino line 2047

**Comment by stefanbode** [comment]
I had to do some changes and use the rtcMem. This ensure I get the runtime, even, if the device reboots or has a blocking loop. Now everything is fine and I always get the total runtime, even if there is a reboot in between. I do see that on the mqttClient.loop(); sometimes it takes up to 5 seconds until the procedure comes back. Sometimes directly. Even on the reboot procedure, there is no reproducible bahaviour. Not critical, but strange. If you enable the DEBUG_THEO you can see that the loop "hang".
