### ISSUE TITLE
http://cputoasters.com/ameyer/sonoff/ssl/sonota-e2a.zip down

### ISSUE THREAD

**Issue by krtschmr** [arendst/Sonoff-Tasmota#782]
http://cputoasters.com/ameyer/sonoff/ssl/sonota-e2a.zip is used in the OTA update tutorial. not working, 404.

**Comment by lgnd33** [comment]
It seems to be working now.

@Andres Meyer - can you describe if you are hosting full or minimal version
of Sonoff-Tasmota on your servers?
I performed a procedure and got Tasmota up and running, but I suspect it's
minimal version (doesn't want to save any config to flash).

If possible, it would be good to compile and host both minimal and full
image, so we can finish everything in one go from your site.
Of course, you could/should update OTA URL in userconfig ;)
