### ISSUE TITLE
Sonoff T1 2Way Pins for Flashing

### ISSUE THREAD

**Issue by x3r4n0** [arendst/Sonoff-Tasmota#784]
Hello, i Hope anyone can help me to figure out which pin is 3v3, GND and RX,TX to flash the ESP.

Thx in advance

**Comment by cputoaster** [comment]
Its the same as with TH10 / POW. Vcc and GND are marked. I used the same cable.

**Comment by cputoaster** [comment]
seems to be clearly marked: https://github.com/arendst/Sonoff-Tasmota/issues/582 . But it looks like most people just flashed via OTA on that thread. (pls close this thread if thats enough info)
