### ISSUE TITLE
New Slampher is 8285 based

### ISSUE THREAD

**Issue by rajil** [arendst/Sonoff-Tasmota#788]
Hi,
I have a Slampher which doesnt go into programming mode by simply connecting the 4 pins. My board looks the one mentioned in this [thread](http://homeautomation.proboards.com/thread/259/program-slampher-socket-esp8285-esp8266). It seems that this is a new revision of the board. Is this supported? And do i need ground R9 as mentioned?

**Comment by rajil** [comment]
I can confirm that the instructions worked, and I was able to flash the firmware.

**Comment by ElDuderinos** [comment]
I can confirm that connecting GND to the left pad of R9 whilst connecting the FTDI worked.
