### ISSUE TITLE
Flash count goes up every time I switch

### ISSUE THREAD

**Issue by revdaz** [arendst/Sonoff-Tasmota#791]
Hello,

I just see that in the debug view (because some problems with wall switches) of the sonoff website that everytime the flash counter goes up when I switch with a switch on GPIO14. Is this the right behavior?

console:
20:07:11 MQTT: stat/sonoff_rf_esszimmer/POWER = OFF
20:07:12 Cnfg: Save (1648 bytes) to flash at F5 and count 215

Is there no problem with wearing of the flash?

**Comment by arendst** [comment]
If you do not care if the relay will be in the same state after power on of sonoff you can play with commands setoption0 and savedata.

**Comment by revdaz** [comment]
Thank you for the quick answer!
if it's no problem for the sonoff flash, for me it's ok :-)

You really do a great work with this project!
