### ISSUE TITLE
Flashing without soldering and using putty (Knete in german)

### ISSUE THREAD

**Issue by revdaz** [arendst/Sonoff-Tasmota#792]
Hello,

this is no problem, just a tip, but I don't know where to publish....

I figured out, that it's very easy to connect the flasher cables without soldering and using car cleaning putty (Lackreinigerknete in german), this is very strong but I think it should also work with normal putty.
Just fix the connected cables with pin header temporary with the board, after flashing take it away again.
 
I flashed with this method already some sonoff S20, RF and also even sonoff Touch without soldering any cable. Only if you will need the GPIO's you have to solder.

Maybe somebody can put this topic in the right folder or integrate it in the wiki when thinking this will be useful.
![img_8604](https://user-images.githubusercontent.com/31374629/29744488-d545e7fc-8aa5-11e7-9bbe-4d5c7709f34c.JPG)
![img_8607](https://user-images.githubusercontent.com/31374629/29744489-d54762d0-8aa5-11e7-9d0b-82a33f448776.JPG)

**Comment by x3r4n0** [comment]
Kannst du mir vllt verraten wie die PIN Belegung bei dem Sonoff T1 aussieht?

**Comment by revdaz** [comment]
Dei Belegung des 4 PIN Headers ist gleich wie bei allen sonoffs, das orangene Kabel ist bei mir Ground, leider habe ich sonst keine Bilder gemacht und der Schalter ist eingebaut. aber auf: https://forum.fhem.de/index.php?topic=64804.0 sieht man es eigentlich auch ganz gut, für die Bilder dort zu sehen musst du dich aber anmelden. um in den Flashmodus zu kommen musst du noch GPIO brücken bevor du ihn mit strom versorgst, dazu hab ich das einzelne gelbe kabel genommen, dass bei mir auf dem breadbord auf GND liegt und an das ESP Modul gehalten, zweiter Kontakt unten rechts.

**Comment by pascalsaul** [comment]
You can do it even more easier and quicker by just holding the pin header in your hand during flashing :) No clay needed ;)

**Comment by titomontes** [comment]
And you could also publish in english; it´s really rude to to publish in other languages.

**Comment by longbikez** [comment]
Where do I find this header with a 1.5mm pitch, I've looked everywhere I can think of.

**Comment by revdaz** [comment]
Hello,

I think there is a misunderstanding, you will need 2,54 mm headers.... (maybe its 1,5 in inch?) you can order them by ebay or directly by Amazon. e.g. https://www.amazon.de/gp/product/B01LWD5MPB/ref=oh_aui_detailpage_o08_s00?ie=UTF8&psc=1 (but they have longer delivery time.

**Comment by longbikez** [comment]
Yup, I don't know what I was thinking.

**Comment by jetema** [comment]
I don't use soldering, I just use a 4 pin male connector , it works good 
![1](https://user-images.githubusercontent.com/30664452/30228902-07762ff4-94e0-11e7-9579-5f9351bcfdbb.jpg)

**Comment by longbikez** [comment]
Thanks for the pic, it helps. Do you use Blynk boilerplate?

**Comment by jetema** [comment]
No, I'm sorry, I use all my sonoffs through web browser mainly
