### ISSUE TITLE
Improvement `switchMode 5`

### ISSUE THREAD

**Issue by ionciubotaru** [arendst/Sonoff-Tasmota#801]
Is it possible to have `switchMode 5` sending `ON` and `OFF` to `switchTopic` every time the switch status changed ?
Using this information the HA software can decide what to do.
Of course the SENSOR telemetry message do this job, but those messages has at leat 10 s delay.

I like to play the bell1.mp3 when the door is open and the bell2.mp3 when the door is closed

**Comment by nightcat91** [comment]
It sounds like you want to get "On" and "Off" as the commands that you receive over mqtt. 
In that case maybe Switch Mode 1 or 2 would better suit your needs. Give that a try
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#main

**Comment by ionciubotaru** [comment]
Thank you @nightcat91 `switchMode1` is the solution
