### ISSUE TITLE
Hue Emulation not detected by Alexa

### ISSUE THREAD

**Issue by m3zm3riz3** [arendst/Sonoff-Tasmota#803]
I have a Sonoff T1 2Ch, which is set to Hue Emulation but Alexa cannot discover the devices; in the log it showa;

21:27:14 Wifi: Checking connection...
21:27:14 Wifi: Connected
21:27:22 UPnP: HUE 3 response packets sent to 192.168.1.87:50000
21:27:22 UPnP: HUE 3 response packets sent to 192.168.1.87:50000
21:27:23 UPnP: HUE 3 response packets sent to 192.168.1.90:50000
21:27:23 UPnP: HUE 3 response packets sent to 192.168.1.90:50000
21:27:34 Wifi: Checking connection...
21:27:34 Wifi: Connected

But is never discovered, however i can switch emulated bridge is discovered by the hue up and so are the lights.  Any hints on whats wrong, has it been an Alexa update thats screwed the devices discovery of emulated hue devices?

**Comment by Pa-De** [comment]
Hi m3zm3riz3,

same issue with my Sonoff 4ch. WeMo is recognized by my Echo dot, but not the hue bridge. Then I tried to implement it into openHAB (hue binding). It recognizes the Sonoff but there is an error that user is already defined.

**Comment by Courty40** [comment]
#698 has a thread mentioning the same issue, it appears to be an update on Alexa that wont not detect the Sonoff in Hue mode

Courty
