### ISSUE TITLE
Is it possible to reduce the antenna output power?

### ISSUE THREAD

**Issue by fttx** [arendst/Sonoff-Tasmota#807]
Or set the wifi mode to something lower than 802.11n?

**Comment by stefanbode** [comment]
The ESP8266 support IEEE 802.11 b/g/n Wi-Fi. Normally the client should automatically choose the best he can do with the access point. I don't know an option where you can influence it when running the ESP8266 in access point mode. Lowering the antenna output, e.g. save energy is not possible. afaik.

**Comment by davidelang** [comment]
switching out of n mode will only make things worse, never better

**Comment by fttx** [comment]
I'm asking this because i'm getting some false positive with a PIR sensor, and i read in a forum that lowering the wifi power improves the situation.  
I think that the mode can be changed through WiFi.setPhyMode() function, but, is there any option in the user_config_override that allows to do this?

**Comment by davidelang** [comment]
If you have interference from wifi or other sources, add a small capacitor 
between the PIR and ground.

**Comment by fttx** [comment]
Between the PIR out and ground?
I already have a big capacitor between VCC and ground, that is shared from both ESP8266 and PIR.
And i also have a pull down resistor on the PIR out, and a 220nF capacitor across pin12 und pin13 of the BISS0001. And i'm still getting false positives.

**Comment by davidelang** [comment]
yes, between the GPIO that the PIR is connected to and ground. If you haven't 
already done it, a pull-up resistor between that pin and vcc can help as well

**Comment by titomontes** [comment]
You can also create a metallic shield, and place the PIR as far away from the Wifi as possible. I used lead, it works very well.

**Comment by fttx** [comment]
@davidelang Ok, il try with the pull-up resistor. But why put a capacitor between pir out and ground? The problem is that the pir sensor triggers when should not, and when it is already triggered the capacitor can't stop it in any way.

@titomontes lead? isn't it a bit overkill? 😆

**Comment by davidelang** [comment]
On Tue, 29 Aug 2017, filippo wrote:

> But why put a capacitor between pir out and ground? The problem is that the pir sensor triggers when should not, and when it is already triggered the capacitor can't stop it in any way.

if there is some AC signal picked up by the wire (acting as an antenna), the 
capacitor gives it a path to ground while having little effect on the DC signal 
of the switch opening or closing. this makes it far less likely that stray 
signals will trigger a false reading.

**Comment by fttx** [comment]
I think that the problem is before of the output pin, because it stays on for all the duration of the pir module timer, the interference is disturbing the pir circuit, not the output wire...

**Comment by titomontes** [comment]
Off course it´s overkill. It´s also effective and cheap, easy to implement and solderless.

Cheers!

**Comment by jetema** [comment]
fttx you can try covering the sonoff with one or more pieces of aluminium foil, that will decrease strenght os wifi signal ( on both directions ) and check if that trick improves the sensitivity of your PIR  ;-)

**Comment by jhlweb** [comment]
Just use a piece of shielded FTP wire. or wrap the wires in aluminum foil and also wrap the PCB of the PIR in some paper tape first and then with aluminum foil. this should work. And make sure that all foil is connector to the ground of the circuit.
