### ISSUE TITLE
no user-interface.h

### ISSUE THREAD

**Issue by consolacion** [arendst/Sonoff-Tasmota#81]
file 'support.h'  asks for 'user_interface.h'
but there is no such file  should it be ' user_config.h' perhaps?

**Comment by hemantkamalakar** [comment]
same issue.

sketch\support.h:8:28: fatal error: user_interface.h: No such file or directory

 #include "user_interface.h"

**Comment by lucwuyts** [comment]
This file is included in the SDK 2.3.0
Maybe install the Arduino ESP8266 project again?

**Comment by hemantkamalakar** [comment]
Yes. It helped.
Thanks a lot for swift reply.

**Comment by joann235** [comment]
How can this be closed if the error is still occurring?  I flashed a sonoff basic with no problem.  Put another one on immediately after to flash and got this error.  Nothing changed in between.  There must be a more fundamental problem and I have no idea what sdk 2.30 is.
