### ISSUE TITLE
Wemos D1 mini

### ISSUE THREAD

**Issue by Gary202** [arendst/Sonoff-Tasmota#812]
Question (might be the wrong place sorry)

When useing Tasmota on a Wemos D1 mini with the GPIO set for outputs. are they pull up or down for the command? and so do i need to include a pull up or pull down resistor?

Thank you

**Comment by mkh595** [comment]
Pull up/down resistor is used for input to define clear state. If pin is set for output, you don't need it as there will be either 0 or 1.
