### ISSUE TITLE
Invalid json

### ISSUE THREAD

**Issue by ionciubotaru** [arendst/Sonoff-Tasmota#822]
`cmnd/test/mqtthost` returns `{"MqttHost","m1.cloudmqtt.com"}`
This is not a valid json. Other similar commands work fine:
`cmnd/test/ssid1` returns `{"SSid1":"My Home WIFI"}`

**Comment by ionciubotaru** [comment]
I'm sorry I found one more:
`stat/test/RESULT = ["VoltageHigh":"0"}`

**Comment by arendst** [comment]
Was fixed in version 5.6.1i too ;-)
