### ISSUE TITLE
home assistant pwm 

### ISSUE THREAD

**Issue by Ryanmaturi** [arendst/Sonoff-Tasmota#826]
I have been trying to figure out the proper MQTT message fomatting via Home assistant to control a custom Wemos running tasmota 5.6 on which i have logic level switched a mosfet on GPIO5.
this unit has worked perfectly fine via MQTT on and off commands. i have also been able to switch the type to PWM in the tasmota config and issue commands via console commands and get varying levels of brightness via command like  (   /cmnd/pwm2 1023  )   < max bright      (   /cmnd/pwm2 300  )    < somewhere in the middle .
when trying to control light in Home assistant i can turn off and on, but when i try to move the brightness slider it switches from full bright to the dimmed value for only a moment.

I am fairly confident that Tasmota is setup correctly and that i need to change something in my Lights.yaml   here is existing entry for this device.

##Light 8
- platform: mqtt
  name: "Ian TV Light"
  command_topic: "cmnd/windowlight/PWM2"
  state_topic: "stat/windowlight/PWM2"
  brightness_command_topic: "cmnd/windowlight/PWM2"
  brightness_state_topic: "stat/windowlight/PWM2"
  brightness_value_template: "{{ value_json.PWM2 }}"
  brightness_scale: 1023
  qos: 0
  retain: true
  optimistic: true

here is the console output while trying to adjust via HA, seems like the payload is not being understood by tasmota :

16:16:04 MQT: stat/windowlight/RESULT = {"PWM":{"PWM2":690}}
16:16:04 RSL: Received Topic cmnd/windowlight/PWM2, Data Size 2, Data ON
16:16:04 RSL: Group 0, Index 2, Command PWM, Data ON (ON)
16:16:04 MQT: stat/windowlight/RESULT = {"PWM":{"PWM2":1}}
16:16:06 RSL: Received Topic cmnd/windowlight/PWM2, Data Size 2, Data ON
16:16:06 RSL: Group 0, Index 2, Command PWM, Data ON (ON)
16:16:06 MQT: stat/windowlight/RESULT = {"PWM":{"PWM2":1}}
16:16:07 RSL: Received Topic cmnd/windowlight/PWM2, Data Size 3, Data OFF
16:16:07 RSL: Group 0, Index 2, Command PWM, Data OFF (OFF)
16:16:07 MQT: stat/windowlight/RESULT = {"PWM":{"PWM2":0}}
16:16:07 CFG: Saved to flash at 3FB, Count 2000, Bytes 1648
16:16:08 RSL: Received Topic cmnd/windowlight/PWM2, Data Size 2, Data ON
16:16:08 RSL: Group 0, Index 2, Command PWM, Data ON (ON)
16:16:08 MQT: stat/windowlight/RESULT = {"PWM":{"PWM2":1}}
16:16:09 CFG: Saved to flash at 3FA, Count 2001, Bytes 1648
16:16:11 RSL: Received Topic cmnd/windowlight/PWM2, Data Size 2, Data ON
16:16:11 RSL: Group 0, Index 2, Command PWM, Data ON (ON)
16:16:11 MQT: stat/windowlight/RESULT = {"PWM":{"PWM2":1}}

**Comment by mkh595** [comment]
I am afraid that already HA sent wrong payload. You didn't define which value should be sent.

Your state_topic should be **stat/windowlight/RESULT** and not **stat/windowlight/PWM2**
Also value_template should be **value_json.PWM.PWM2** and not **value_json.PWM2**
As you see, HA sent for PWM as payload  **ON** or **OFF** which is interpreted as 1 or 0.

I don't use **Light** so I cannot tell you correct configuration but as example I can give you following.
I define Input slider
```
brightness:
  name: .
  initial: 512
  min: 0
  max: 1023
  step: 100

and update is done via automation

# Update brightness according to slider
- alias: slider_brightness 
  trigger:
    platform: state
    entity_id: input_slider.brightness
  action:
    - service: mqtt.publish
      data_template:
        topic: "home/cmnd/sonoffxxx/Pwm"
        payload: '{{ states.input_slider.brightness.state | int }}

As topic I am using group topic sonofxxx so this automation updates all sonoffs with this group topic

21:52:47 MQT: home/stat/home248/RESULT = {"PWM":{"PWM1":400}}
21:52:50 MQT: home/stat/home248/RESULT = {"PWM":{"PWM1":300}}
21:53:04 MQT: home/stat/home248/RESULT = {"POWER":"OFF"}
21:53:04 MQT: home/stat/home248/POWER = OFF
21:53:08 MQT: home/stat/home248/RESULT = {"POWER":"ON"}
21:53:08 MQT: home/stat/home248/POWER = ON
21:53:22 MQT: home/stat/home248/RESULT = {"PWM":{"PWM1":500}}
