### ISSUE TITLE
Soundoff Touch double tap

### ISSUE THREAD

**Issue by laurentdinclaux** [arendst/Sonoff-Tasmota#833]
Hello,

I use firmware 5.6.1 20170818 on a Sonoff Touch and Home Assistant.

I want double tap to not trigger the relay but send a specific MQTT message, is that possible ?

The use case: the sonoff touch controls a smart bulb. I want it to turn on/off on single tap, and to toggle between two dim light levels on double tap

**Comment by PeggyFree** [comment]
Yes it is possible, I use the double tap for dim light and long press for
the blinds. Search for it in the previous issues, it is explained.

**Comment by laurentdinclaux** [comment]
I did and didn't found, thus why I am asking

**Comment by ionciubotaru** [comment]
look for `setoption11` Button single and double press functionality swapped
and `buttontopic`
