### ISSUE TITLE
Problem with Tasmota installation

### ISSUE THREAD

**Issue by mesab0ogie** [arendst/Sonoff-Tasmota#841]
Followed the installation guide by QuickPi. Used a Sonoff Basic.SSID is 2.4G wifi.

![5xkqbg](https://user-images.githubusercontent.com/10762974/30140527-dd9dc518-93a7-11e7-8fdf-6a950bd032f2.jpg)

Not sure what im doing wrong but i cant get the web address for the device. Any help will be greatly appreciated.

**Comment by ionciubotaru** [comment]
send `status 0` to sonoff via serial

**Comment by mesab0ogie** [comment]
omg. thank you! cant believe i spent 4hrs trying everything but that.
