### ISSUE TITLE
Warning regarding FTDI programmers

### ISSUE THREAD

**Issue by ulab** [arendst/Sonoff-Tasmota#842]
My suggestion is to add a warning to the prerequisites page like:

- 3.3V FTDI USB-to-Serial Converter/Programmer (example)
  - Please note that there are FTDI programmers that can be switched between 3.3 V and 5 V for the data pins, but still provide 5V on the power pin. This might fry your chips.

This is the programmer I am talking about:
![Image of FTDI programmer](https://user-images.githubusercontent.com/504616/30157040-815a91d6-93c1-11e7-91fe-019e1ecdeffa.jpg)

**Comment by Adminius** [comment]
you can modify it to use 3V3 or 5V on 5V Pin:
![grafik](https://user-images.githubusercontent.com/17052262/30368422-5d3b5934-9871-11e7-99ba-42c741d1b6bd.png)

**Comment by qorron** [comment]
thanks for the warning!
apparently I was lucky. I flashed about 40 sonoff devices with 5V Vcc.
according to telemetry more like 4.5V.

will modify my flasher.. or get a true 3.3V model.

**Comment by elbow** [comment]
Yes - this just happened to me. My cable labeled 3V3 actually connects vcc directly to usb power I.e. 5v.  Unhappy smell from Sonoff, don’t know if it works still.

**Comment by webtop** [comment]
I'm not sure about the Sonoff hardware, but the ESP doesn't have a problem with 5v. I flash all my ESPs at 5v, always have done, always will do, and haven't bricked one yet.

Like I said though, the other components on the Sonoff boards may not be 5v tolerant

**Comment by ulab** [comment]
I have updated the Wiki Prerequisite page.

**Comment by stanogustafik** [comment]
I had the same issue with the same converter and here is the solution: if you switch to 3,3, you also have to repin the cable from 5V to one of the yellow pins in the middle ;)
