### ISSUE TITLE
Arduino IDE Preparation Help

### ISSUE THREAD

**Issue by jeylites** [arendst/Sonoff-Tasmota#849]
Are there any youtube video to setup Tasmota in Arduino IDE?

I'm not sure where and what flies needed to be copied.  I've been using PlatformIo and it's been working great but I'm trying to get OTA setup. From what I read, OTA works best on Arduino IDE.

**Comment by ionciubotaru** [comment]
Both Arduino and Platformio compile the sketch to a bin file, so it doesn't matter what compiler you use as long as the result is the same. Then upload the bin file OTA - use a browser for that
