### ISSUE TITLE
DHT22 failure keeps reporting the same values

### ISSUE THREAD

**Issue by mzealey** [arendst/Sonoff-Tasmota#852]
I had a DHT22 fail - it keeps logging `Timeout waiting for start signal low pulse`. The issue is that for a day after it failed the software was just reporting the same temp/humid:

```
ESP-MQTT: domoticz/in = {"idx":16,"nvalue":0,"svalue":"26.3;50.2;1"}
```

After reboot it doesnt report anything. I think sensor values should time out after a while - perhaps 2* send ?

**Comment by ionciubotaru** [comment]
Some suggestions:

- check the pullup resistor
- use short wires between esp and dht
- replace dht with a new one
- check messages on serial or mqtt instead of domoticz

**Comment by mzealey** [comment]
Sure, however this issue is about the DHT22 but with the way the software keeps reporting out of date values when a device has been disconnected.

**Comment by arendst** [comment]
Updated again in v5.9.0
