### ISSUE TITLE
Can't get Tasmota on my Sonoff Dual. Seems to jump out of program mode DURING flashing. 

### ISSUE THREAD

**Issue by EttVenter** [arendst/Sonoff-Tasmota#856]
Every time I try to flash my Dual with Tasmota, I get a result like this:

`[SUMMARY]
Environment sonoff              [SUCCESS]
Environment sonoff-minimal      [ERROR]
Environment sonoff-ds18x20      [ERROR]`

Sometimes, it'll be the first two that succeed and the 3rd fails. I even had one instance where the 1st and 3rd succeed, but the second fails. 

If I go back through through the log, I see that the Sonoff seems to jump out of Program mode, because of this:

`Uploading 488000 bytes from .pioenvs\sonoff-ds18x20\firmware.bin to flash at 0x00000000
...................................warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
warning: espcomm_send_command: didn't receive command response
error: espcomm_upload_mem failed
*** [upload] Error -1`

I've connected GPIO0 and GND properly, so that's not the issue.

Any ideas?

**Comment by EttVenter** [comment]
Anyone?

**Comment by EmilySmith0** [comment]
you didn't mentioned compiler
I assume its arduino
First make BIN file
![capture](https://user-images.githubusercontent.com/30232790/30273241-99f84cf8-9711-11e7-8a20-6b1cd5225952.PNG)

Then find that bin file in project folder
and upload using ESP download Tool
http://espressif.com/en/support/download/other-tools
![image](https://user-images.githubusercontent.com/30232790/30273296-d7d99e46-9711-11e7-85fe-10fb96143333.png)
![capture1](https://user-images.githubusercontent.com/30232790/30273492-a13a64fa-9712-11e7-9260-1480f71e2347.PNG)

I don't know about ATOM(PlatformIO).I think you can create BIN file with ATOM as well

**Comment by EttVenter** [comment]
Thanks @EmilySmith0! I'm compiling with Atom. 

I'll give this a shot!
