### ISSUE TITLE
Big thank you and a minor question regarding precision of Sonoff POW

### ISSUE THREAD

**Issue by andreasloe** [arendst/Sonoff-Tasmota#858]
Before I start with my question I want to say than you Theo for the effort, huge amount of work and passion to put into this project. I think that many of us would not be able or willing to use Sonoff with their native firmware. 

I have a minor question that is possibly not even an issue (and feel free to close it then). I looked  at the variables Sonoff POW measures. I have to look at very small values around 2-3Watt and a variation enabled me to record those values. I always thought that "Total" is the sum of last recorded Total plus recorded Power. Hence, it should not make a difference whether I record "Power" (at any time t) or whether I record "differences in Total" (Total at time t+1 minus Total at time t). 

But from actual data (low values!) that does not seem to be the case! Power is, in particular for low values, much more volatile and inaccurate then differences in Total. It seems to me that differences of Total is the more reliable value. Is that correct?

**Comment by arendst** [comment]
Thnx.

See description on this page https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Pow
