### ISSUE TITLE
LogPort not being shown in STATUS report & can't be updated via MQTT

### ISSUE THREAD

**Issue by wiktorschmidt** [arendst/Sonoff-Tasmota#859]
STATUS3 only reports: `"{"StatusLOG":{"SerialLog":2, "WebLog":2, "SysLog":0, "LogHost":"XXXX", "SSId1":"yyy", "SSId2":"zzz", "TelePeriod":300, "SetOption":"55800009"}}"`

trying to change LogPort fails via MQTT (works via web panel)
`cmnd/sonoffplug/Logport:"52284"`
returns
`stat/sonoffplug/RESULT:"{"LogPort":514}"`

edit: version 5.7.1 but also confirmed on version 5.6.1

**Comment by arendst** [comment]
That's because you wanted to change the port > 32766.

I'll change the code to allow for max port number and add it to Status3 too.

**Comment by wiktorschmidt** [comment]
Ah! Thanks :)
