### ISSUE TITLE
New binaries what do we use to flash it?

### ISSUE THREAD

**Issue by chuxxsss** [arendst/Sonoff-Tasmota#865]
Due to the change in Sonoff stuff because of the chip memory change as I read it. How do I flash the Tasmota.bin files using Dout and 1 Meg (128K SPIFFS)? What tool do I use?

**Comment by davidelang** [comment]
the same tools as before, just with different settings.

**Comment by arendst** [comment]
See wiki > Upload tools

**Comment by chuxxsss** [comment]
I work it out. But no web page. Will it work for Sonoff's RF Bridge?
