### ISSUE TITLE
Request: Sonoff B1 Wakeup w/ Value

### ISSUE THREAD

**Issue by carywin** [arendst/Sonoff-Tasmota#867]
If I send the command "Wakeup" the bulb will start fading back up to the previous Dimmer value, this isn't great when the bulb was turned off while at a very low Dimmer value such as when retiring to bed :)

If the "Wakeup" command also supported a parameter which could become the new Dimmer value and trigger the fade up to the new value, that would be much more useful as a wake up light.

eg. Currently the bulb is Dimmed to 15% and I retire to bed, push the button to turn the lamp off. It retains a Dimmer value of 15%. In the morning when the controller sends "Wakeup", the bulb will only fade up to 15%, not very bright for a wake up light.

Instead if the controller could send "Wakeup 100" and then the bulb fades up to 100% brightness, that will work much better for waking up.

**Comment by arendst** [comment]
Agree, will look in to it.
