### ISSUE TITLE
how do i set my altitude for bme280 ?

### ISSUE THREAD

**Issue by nikki-reprap** [arendst/Sonoff-Tasmota#872]
How do i set my height in meters above sea level for a bme280 ?

Thanks Nikki

**Comment by chkbln** [comment]
Hello
is there already a solution?
The BMP 180 also does not show the correct location-related value. It is not possible to specify the altitude of the site.
Best regards

**Comment by arendst** [comment]
Use Altitude command implemented in release v5.9.0
