### ISSUE TITLE
Subscribe just to the Temperature value

### ISSUE THREAD

**Issue by stubbsjuk** [arendst/Sonoff-Tasmota#873]
I am using MQTT.fx just to try and understand how MQTT works.

I am subscribed to 
                   tele/test/SENSOR
and it returns
                   {"Time":"2017-09-15T15:22:56", "DS18B20":{"Temperature":22.2}, "TempUnit":"C"}

However I would like it to just return the value of 22.2 and not all the rest.
What do I have to add to tele/test/SENSOR to get this.

Best wishes.

**Comment by davidelang** [comment]
you cannot do this without changing the source. you are better off adjusting 
your system that's receiving the data to be able to extract fields out of JSON

**Comment by stubbsjuk** [comment]
Thank you.
