### ISSUE TITLE
cmnd/power not responding to on/off, only to 1/0

### ISSUE THREAD

**Issue by boyd91** [arendst/Sonoff-Tasmota#874]
My Tasmota flashed sonoff touch is not responding to commands with payload `OFF`, `ON`, `BLINK`, `BLINKOFF`. It only works when I use their numeric counterparts `0`, `1`, `3`, `4`. The only string command that works is `TOGGLE`.

The MQTT status messages sent out by Tasmota do have the string payloads as expected (`ON`, `OFF`, ...)

- I know I have to send commands to the cmnd/sonoff/power topic.
- Inside `user_config.h` `MQTT_STATUS_OFF` and `MQTT_STATUS_ON` are set to `OFF` and `ON`
- I'm on version `5.7.1d`

**Comment by arendst** [comment]
What do you use to send commands?

**Comment by boyd91** [comment]
An mqtt client for Mac, home assistant and the console on the Tasmota web interface. They all show the same behavior.

**Comment by arendst** [comment]
Strange. It works fine with me. Pls reflash using the latest version.

**Comment by boyd91** [comment]
It works after reflashing. I used the sonoff environment this time instead of the nl env. So it could have been related to that, not sure though.

**Comment by arendst** [comment]
Ah that's it!

I'll change on/off/toggle check from just plain translations to the ones configured by the user in an updated release.

Blink would still be knipper though.

Nice problem.
