### ISSUE TITLE
Schedule like in original firmware

### ISSUE THREAD

**Issue by Doktor-X** [arendst/Sonoff-Tasmota#883]
Hi, before i flash Pow with this firmware i have question is possible to have Schedule to power on and off devices connected to pow but not with mqtt but like standalone

**Comment by arendst** [comment]
There is no schedule other than pulsetime.

**Comment by Doktor-X** [comment]
pulsetime?

**Comment by ionciubotaru** [comment]
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#main read about pulsetime
