### ISSUE TITLE
I got some issue with switch recently

### ISSUE THREAD

**Issue by hamwong** [arendst/Sonoff-Tasmota#886]
HI, I recently found a strange issue,
I set 2 switch but it resufse to name it with POWER1 / POWER2 for each switch
they all name on POWER but it's not happening on all devices.

```
19:20:28 MQT: tele/ESP-Wemo1-BedRoom/SENSOR = {"Time":"2017-09-19T19:20:28", "Switch1":"OFF", "Switch2":"OFF", "AM2301":{"Temperature":25.2, "Humidity":42.4}, "TempUnit":"C"}
19:20:49 MQT: cmnd/BedRoom-ESP-Motion/POWER = ON
19:20:53 MQT: cmnd/BedRoom-ESP-Motion/POWER = OFF
19:21:13 MQT: cmnd/BedRoom-ESP-Motion/POWER = ON
19:21:15 MQT: cmnd/BedRoom-ESP-Motion/POWER = OFF
```

(above first time were switch1 and second time is switch2)
please advise is there any new command I was missing?

**Comment by hamwong** [comment]
I fallback to firmware 5.0.6 and 4.11, both able have Switch1>POWER1 and Switch2>POWER2

**Comment by arendst** [comment]
If there is just one relay it will perform as you state above.

Check if your device config has one or two relays. Some people seem to loose some devices after an upgrade. I don't know why but it may have something to do with own compilations and using the wrong linker file not being 1M (no SPIFFS).
