### ISSUE TITLE
Connect directly as a AP??

### ISSUE THREAD

**Issue by Neo-NL** [arendst/Sonoff-Tasmota#888]
Hello,

When i try to connect direct to the Sonoff with Tasmota on it. i get stuck at the Wifi network scan.
Thing is, i don't want to set it up in a network but want to use it as a stand alone.

Is that possible? and if yes, how can i arrange that?

**Comment by ionciubotaru** [comment]
Try `WifiConfig 2` https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#wifi

**Comment by Neo-NL** [comment]
Thank you for you comment.
When i Select WifiConfig 2 it starts looking again for a Network like indebuurt1 and 2.
When i go to the 192.168.4.1 screen, it shows me the Networks again.

Do i have to make some changes in the ino files perhaps?

**Comment by arendst** [comment]
It's not meant to stay in AP mode. You'll have to tweak the source yourself and allow access to more configuration pages too.
