### ISSUE TITLE
1 Channel Inching/Self-lockIing Mode WiFi Wireless Switch 5V/12V and Sonoff-Tasmota?

### ISSUE THREAD

**Issue by jannnfe** [arendst/Sonoff-Tasmota#893]
Hallo,
sorry i never posted anything on GitHub but I have a question and can't find a solution at this time. I'm a noob and like to control my Garage Door with Siri and Homebridge. My Garage Door needs a pulse to open/close.
I bought the "1 Channel Inching/Self-lockIing Mode WiFi Wireless Switch 5V/12V" from [itead.cc](https://www.itead.cc/smart-home/inching-self-locking-wifi-wireless-switch.html) and like to use it with the Sonoff-Tasmota Firmware to connect via plugin to Homebridge.

Pictures of the Relay:
![img_6187](https://user-images.githubusercontent.com/30130742/30655805-50903c56-9e32-11e7-8a66-bfd51f319bc8.jpg)
![img_6186](https://user-images.githubusercontent.com/30130742/30655528-739b5448-9e31-11e7-81a1-36344463badf.jpg)

Is it possible to flash the Sonoff-Tasmota Firmware to this relay?
Where do i have to connect my USB adapter or can i just use the build in USB Port?
Where are the RX, TX, GIO Ports on this Relay?

I hope anybody can help me and sorry for my bad english.
Thanks!

**Comment by ionciubotaru** [comment]
You can use Tasmota.
Connect the FTDI to the 4 pin cconector near the relay
One of 2 black buttons must be GPIO0

**Comment by jannnfe** [comment]
Thank you for your reply.
Is this right in the picture?
![30655805-50903c56-9e32-11e7-8a66-bfd51f319bc8](https://user-images.githubusercontent.com/30130742/30688446-77df0148-9ebe-11e7-9556-ad413b839a16.png)

After the flash is the Self-lockIing Mode still working?
Thanks!

**Comment by ionciubotaru** [comment]
From left to right:
GND - TX - RX - 3V3
The square is 3V3

**Comment by jannnfe** [comment]
Thanks!
I wrote with the itead.cc Support and they told me this device can not be flashing.
Is this right?

**Comment by itsecasc** [comment]
any updates ? i have almost the same board, same problem
![image](https://user-images.githubusercontent.com/31914906/30925667-ea814776-a3b2-11e7-894f-c5f77a4a21a8.png)

**Comment by tomasroud** [comment]
Hi, my board does not have connected RX and TX to the chip, so I must used wires with needles and connect directly to the chip. TX and RX is 2nd and 3rd from to left corner. And be aware about changed 3,3 and gnd pin!!!!! First connect 3,3 and gnd and check without button presing if led go on. Fter that start with pressed button. Then press second button, to have both leds light on. Then you can flas with needles, I had so 70 trys, because my hand shaked a lot ;) P.S. I used autoclick with 20s delay to upload firmware ;)

**Comment by tomasroud** [comment]
![21753223_1746353405377883_5072682759846380406_o](https://user-images.githubusercontent.com/9718240/31241500-4c045b12-aa04-11e7-969c-50b5b1b5459b.jpg)
Here is the connect picture. That left to gpio0 is not necessary, button is working good. And for tx, rx use needles. 
![sonoff-self-lock_preview](https://user-images.githubusercontent.com/9718240/31241457-2fae9d24-aa04-11e7-96df-fb28e37ee54a.jpeg)

**Comment by jannnfe** [comment]
Related to @ionciubotaru must the occupancy look like this on my relay? (White):
![pic](https://user-images.githubusercontent.com/30130742/31242897-d8139c4a-aa08-11e7-8b27-320fab094ee4.png)
@tomasroud you say it is possible to flash my relay? Does everything work the way it should or does complications occur?
Is the assignment at the top of the image or do I have to connect 3v3, RX, TX, GND in one of the three red rectangles? If yes, you can tell me which I must use and wich buttons when I must press. Many Thanks!

**Comment by tomasroud** [comment]
Eat the elephant by pieces. First locate 3,3 + GND.
It should be GND and 3v3 as in your picture.
Try to connect if LED light up.
Got it? Next step.
Start flash mode ... must both of two LEDs light up.
Next step.
Locate TX + RX.
Try RX and TX on your picture .... try swap TX + RX. 
Still not working.
Try on rectangle nr 1 second and third from bottom.
And again try to swap second and third as TX + RX.
Tell how successfull you are. And be aware about switch 3,3 and GND. If you connect bad gnd to 3,3 and connect TX or RX, you just demage your USB programmer. As I twice :(

**Comment by jannnfe** [comment]
Now i have tested that what you are explaining.
I found out, that this picture is the right assignment:
![30655805-50903c56-9e32-11e7-8a66-bfd51f319bc8](https://user-images.githubusercontent.com/30130742/30688446-77df0148-9ebe-11e7-9556-ad413b839a16.png)

But i don't know how to come in flash mode. Can you tell me?

**Comment by tomasroud** [comment]
Press one button nr. 1 or 2, try it and then connect to usb. If lights only 1 led, press next button till both of leds light.

Tell me, how it works.

P.S. When you connect 3,3 and GND, it will be too at bottom two pins on block nr. 3

**Comment by jannnfe** [comment]
I use the same arrangement as at the beginning. In the beginning lights still lit. For some reason now lights nothing more when I connect via USB. I do not think this is broken. Can be connected where else GND RX TX and 3v3?

**Comment by tomasroud** [comment]
3,3 and GND are bottom 2 pins in block nr. 3, try it there, if the board will live. Try with ohmmetter that these pins are same as 3,3V and GND.

**Comment by jannnfe** [comment]
@tomasroud No light on the block 3 :(
I think the usb adapter is broken but it is light up on usb connect and it gives out 3,3v.

**Comment by tomasroud** [comment]
USB adapter can be broken on TX or RX, on 3,3 and GND probably not. So it must be OK.
If you connect GND and 3,3 is voltage on block 3, bottom 2 pins?

**Comment by tomasroud** [comment]
![image](https://user-images.githubusercontent.com/9718240/31437695-70e1f8be-ae86-11e7-94f3-d6b4c711a761.png)
Here are TX and RX pins, as I wrote above.

**Comment by jannnfe** [comment]
Idk if this is stupid but i connected 3,3v on board voltage and GND, RX, TX like this picture 
![30655805-50903c56-9e32-11e7-8a66-bfd51f319bc8](https://user-images.githubusercontent.com/30130742/30688446-77df0148-9ebe-11e7-9556-ad413b839a16.png)
and now my mac recognize the board. The two light next to button 1 and 2 are flashing but in Arduino IDE 1.8.4 and 1.8.5 i get the same error like here: https://github.com/arendst/Sonoff-Tasmota/issues/957

**Comment by tomasroud** [comment]
The board lives, that is cool, so, you should connect your USB adaptor to USB in pc in same time as btn. is pressed. Then both LEDs will light ... not flash, light still. OK?

**Comment by jannnfe** [comment]
So I have now tried all sorts of combinations and pins and with nothing I can flash the Tasmota firmware. I have two pictures where you can see the LED light up. No idea what the flash mode is and if he is even in flash mode. Any ideas on how to connect to the tasmota firmware?
![img_6579](https://user-images.githubusercontent.com/30130742/32229695-bc799a7c-be51-11e7-97e6-d42805a6393d.JPG)
![img_6580](https://user-images.githubusercontent.com/30130742/32229696-bc93fb24-be51-11e7-814c-7e9d09a1c53b.JPG)

**Comment by tomasroud** [comment]
You must flash with VCC and GND from USB in PINS only. I see you have connected main voltage, it is not possible to flash the device like that. Unplug micro USB voltage, connect voltage in pins and tell me, if you can set up both these pictures too.

**Comment by jannnfe** [comment]
I'm not able to get in this light mode on picture 2 with VCC and GND connected :(

**Comment by tomasroud** [comment]
Press btn1 when connected to USB and release. Then press btn 2. IT MUST STAY IN 2 LEDs light on.

**Comment by jannnfe** [comment]
No it don't work. I think I have a Version of the Sonoff, that is not flash able :(

**Comment by tomasroud** [comment]
I am wondered, but maybe it is possible. I am sorry, that I can not help you :(

**Comment by ciotlosm** [comment]
This is how flashing mode should look like: https://www.youtube.com/watch?v=E0WBoFCcnYY

**Comment by jannnfe** [comment]
Thank you for the Video. I can access this mode like in the video but im not able to flash the sonoff.
My Module ist the PSA-B01-GL

**Comment by jannnfe** [comment]
Got it finally working!!!
I used Arduino IDE with ESP8285 an Flash Size : 1M (512k SPIFFS) and the latest Sonoff Firmware.
I connect VCC and GND to the pins shown above in the Photo and connect TX and RX to the Pins shown in this picture [https://user-images.githubusercontent.com/9718240/31437695-70e1f8be-ae86-11e7-94f3-d6b4c711a761.png](url). Hold the jumper cable to this pins without soldering it should work. Try swap TX and RX if its not working. After flashing you have to connect the USB to get into webinterface

**Comment by badigit** [comment]
Sucsesfull flashed this with SonOTA

**Comment by benjaminsonnleitner** [comment]
Yesssss also!!! but which device belongs in the configuration set? 
That's not the basic model
[https://www.youtube.com/watch?v=wSjzj-Imj0c](url)


<img width="424" alt="bildschirmfoto 2018-01-12 um 19 15 20" src="https://user-images.githubusercontent.com/35377915/34889073-04b0c0fe-f7cd-11e7-8355-fffaf6a6a787.png">

**Comment by ciotlosm** [comment]
Try to use 1 Channel (option 12)

**Comment by jannnfe** [comment]
Now I have bought a new 1 channel module, which looks different again than what I had before. Since I already gained some experience, I was able to flash this module directly on the chip with RX and TX.

This Module:
![img_0811](https://user-images.githubusercontent.com/30130742/34920702-e61a523a-f976-11e7-84e0-86ecb3d31dfa.JPG)

However, I'm wondering now. Is there any GPIO on this module that you can connect a reed sensor, for example, or do I have to solder directly to the chip?

I found this by @LurchiStromberg in [this Issue](https://github.com/arendst/Sonoff-Tasmota/issues/453) about the PSF-B01 Chip:
![PSF-B01](https://user-images.githubusercontent.com/30866642/29122265-fc2e6cbe-7d11-11e7-89d5-3e6db378b2fc.jpg)

Is there an easy to reach GPIO or RX TX on this module?
Thanks!

**Comment by budisek** [comment]
Hey all,

please can you write any tutorial to flash and upload Tasmota firmware to 5V/12V relay?

I have right this type:

![](https://ae01.alicdn.com/kf/HTB1vxJlcRcHL1JjSZFBq6yiGXXay/3pcs-lot-1-Channel-Inching-Self-Locking-WiFi-Wireless-Switch-dc5V-12V-samrt-Relay-module-for.jpg)

I am using FTDI 3.3v. GND and 3v3 connection is correct but everytime when i try to upload Tasmota i get an error:

> Uploading .pioenvs\sonoff\firmware.bin
> warning: espcomm_sync failed
> error: espcomm_open failed
> error: espcomm_upload_mem failed

I also tried swap TX and RX but it did not help.

Thanks

**Comment by ciotlosm** [comment]
@budisek You need to connect tx and rx to the PSF-B01 correct pins. I have a video that has some details that might help: https://www.youtube.com/watch?v=vzoM4op60jo

**Comment by jannnfe** [comment]
This Module is "hard" to flash.

1. Set Up Arduino IDE: https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE
2. Connect the Jumper Cables to this Sonoff:
![1 channel](https://user-images.githubusercontent.com/30130742/35114678-d5cfd596-fc85-11e7-843f-998b104571be.png)
3. Get into flashing Mode: Connect 3.3V while pressing both buttons and than press the bottom one like in this video: https://www.youtube.com/watch?v=E0WBoFCcnYY
4. Upload Tasmota Firmware with PulseTime enabled

You can just hold the jumper cables at the chip pins seen in this video: https://www.youtube.com/watch?v=vzoM4op60jo

**Comment by budisek** [comment]
Great thats look not so difficult. 

Two questions:
In youtube video is used 5V or 3.3V mode?
And how can i enable pulsetime?

Thanks

**Comment by ciotlosm** [comment]
I used USB 5v not the FTDI 3.3v. I also used only ground from the FTDI and tx/rx

**Comment by ciotlosm** [comment]
@budisek in my video I used USB 5.5V and used FTDI for ground/tx and rx only.

**Comment by benjaminsonnleitner** [comment]
Hallo! 

I doesn‘t Flash the module with FTDI...... I flashed over the Wifi with my MacBook our Windows .... its very easy .... Time what I needed: 2Minutes to Flash. Preparation: 15 minutes

**Comment by budisek** [comment]
I did it. I flashed it by cables and Tasmota is online.

But I need to set the relay to 1 sec ON and then OFF. I changed this in firmware before uploading:

> #define APP_PULSETIME          10       

But it works strange. When I toggle ON, it crashes (led is blinking) and restart is necessary.

What I need to set the relay to ON for 1 sec?

**Comment by jannnfe** [comment]
One time i had the same issue.
Its because Tasmota is not supporting the inching /Self-locking function of the module.
Maybe you are in the wrong mode. Press the Buttons and test different states. 
I also pressed the buttons and at some point it worked.
You can change PulseTime by typing "PulseTime 30" in the Console at the Webinterface.

**Comment by budisek** [comment]
You are right. I switched mode with second button. Then it works like switch (switching between ON and OFF manually) but when i changed pulsetime, now it is ON only for adjusted time. Great.

Last question i hope:

Is it possible to set power on state to OFF always? I see that with every restart it turns ON for short time (less than 1sec) before it toggles to OFF. You know, i dont want to have the garage door opened after every restart :)

**Comment by jannnfe** [comment]
Really thats the restart issue is strange. I don't have this problem.
I changed nothing in the user_config.h except PulseTime, Project Name and Wifi Options and my module is always off even after restart.
Did you configure MQTT? I think I've heard that some functions work better when an MQTT broker is configured.
Maybe someone else knows better about this issue.

**Comment by budisek** [comment]
In fact, i don't have relay connected to garage door yet, so I am only guessing now. 

After every restart red LED (which blinks when I toggle ON) shortly lights and relay clicks twice. Maybe it is some part of restart and it will have no effect to opening. I will let you know.

Thanks for your help.

**Comment by Alpengroove** [comment]
You can do the firmware update OTA without touching the module. 
[https://haus-automatisierung.com/hardware/sonoff/2018/01/04/sonoff-vorstellung-part-11.html](url)
The video is in german, but you can copy the commands.

**Comment by Reikard80** [comment]
Dear All,

Does anywone can tell me where I find the GPIO14 on this board? would be great 

Rik

**Comment by jannnfe** [comment]
> I found this by @LurchiStromberg in [this Issue](https://github.com/arendst/Sonoff-Tasmota/issues/453) about the PSF-B01 Chip:
![PSF-B01](https://user-images.githubusercontent.com/30866642/29122265-fc2e6cbe-7d11-11e7-89d5-3e6db378b2fc.jpg)

**Comment by Reikard80** [comment]
Hi Jannnfe,

Thanks a lot, indeed now I found gpio14 :) thanks for your support on this

Rik

**Comment by salmanslim** [comment]
Wont this 5/12v work without flashing for garage door ?

**Comment by Bull10X** [comment]
It will work but if you can get it flashed it will support an input like a reed switch to determine if your door is open or closed if you are not in line of sight of door.


Doug

**Comment by sumasage** [comment]
How do I flash with pulsetime?  And what is pulsetime?

I do have adruino ide setup and able to flash tasmota to sonoff basic without any problem. 

Thanks

**Comment by tuga49** [comment]
I have it working with tasmota. But how I add a reed switch to it? Thanks

**Comment by rmarkle** [comment]
@tuga49 - Did you get this figured out?  I am trying to do the same thing.

**Comment by salmanslim** [comment]
I am using it wothout flashing as i am using a smartthings sensor for open/close notifications.

**Comment by gadLinux** [comment]
> This Module is "hard" to flash.
> 
>     1. Set Up Arduino IDE: https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE
> 
>     2. Connect the Jumper Cables to this Sonoff:
>        ![1 channel](https://user-images.githubusercontent.com/30130742/35114678-d5cfd596-fc85-11e7-843f-998b104571be.png)
> 
>     3. Get into flashing Mode: Connect 3.3V while pressing both buttons and than press the bottom one like in this video: https://www.youtube.com/watch?v=E0WBoFCcnYY
> 
>     4. Upload Tasmota Firmware with PulseTime enabled
> 
> 
> You can just hold the jumper cables at the chip pins seen in this video: https://www.youtube.com/watch?v=vzoM4op60jo

This board is marked with 7-32 AC/DC. Is it safe to power it up with AC power?

**Comment by Martin-Dolan** [comment]
> > This Module is "hard" to flash.
> > ```
> > 1. Set Up Arduino IDE: https://github.com/arendst/Sonoff-Tasmota/wiki/Arduino-IDE
> > 
> > 2. Connect the Jumper Cables to this Sonoff:
> >    ![1 channel](https://user-images.githubusercontent.com/30130742/35114678-d5cfd596-fc85-11e7-843f-998b104571be.png)
> > 
> > 3. Get into flashing Mode: Connect 3.3V while pressing both buttons and than press the bottom one like in this video: https://www.youtube.com/watch?v=E0WBoFCcnYY
> > 
> > 4. Upload Tasmota Firmware with PulseTime enabled
> > ```
> > You can just hold the jumper cables at the chip pins seen in this video: https://www.youtube.com/watch?v=vzoM4op60jo
> 
> This board is marked with 7-32 AC/DC. Is it safe to power it up with AC power?

Only if the AC is between 7 and 32 volts. I have mine powered by my door intercom transformer which is around 16-18v AC

**Comment by mientki** [comment]
Hello
I ordered a similar WiFi module on Aliexpress. My one has an RF module, besides it seems very similar to Sonoff RF. Of course, it has ewelink software. I would like to reprogram it on tasmote, but I do not know how to enter it in flashing mode. Maybe someone was already trying to flash it? Will you help me?

![obrazek 6](https://user-images.githubusercontent.com/37380727/50560781-69f1df00-0d04-11e9-8ed2-bcae9703bad6.jpeg)
![obrazek 4](https://user-images.githubusercontent.com/37380727/50560790-770ece00-0d04-11e9-86ac-a76d2084a542.jpeg)

**Comment by Martin-Dolan** [comment]
It will be the same as the other modules. Power it on while holding gpi0 to ground for a few seconds

**Comment by udayroy04** [comment]
Hello everyone , i am totally new on git , this board is very useful for me and i want to use this board with my own android application . I would be great full if some can help me find the android sdk for this board .

**Comment by badigit** [comment]
> You are right. I switched mode with second button. Then it works like switch (switching between ON and OFF manually) but when i changed pulsetime, now it is ON only for adjusted time. Great.
> 
> Last question i hope:
> 
> Is it possible to set power on state to OFF always? I see that with every restart it turns ON for short time (less than 1sec) before it toggles to OFF. You know, i dont want to have the garage door opened after every restart :)

Have same problem. After soft-restart in webui, relay switch 1-0.
After hard-restart (via power on\off) - no problems, relay stay off

**Comment by Bacon-Ranch** [comment]
hello,  please can anyone help me, I have tried every possible combination of wires and button holds as I power on, I am using ESP easy, lol. The Sonoff device is a 1 channel inching type, the serial device is a DSD tech FT232 TTL. I have looked for pin outs for the serial device and can not find, I have tried with the jumper on the RTS and CTS pins and without. I have tried 5v and 3.3V jumpers, I do not think I fried anything yet but the serial board did get a bit hot at first. Everything still seems to light up and at least is not completely dead yet, not even sure which button to hold down so I have tried both seperately. Please see the picture showing 2 boards, I get flash failed every time, so it at least attempts to connect. Orange and yellow are TX and RX, Red is +, brown is ground.

![20190406_134555](https://user-images.githubusercontent.com/47070206/55673251-80fc1c00-5873-11e9-8703-44d40eb9fc04.jpg)
![20190406_134535](https://user-images.githubusercontent.com/47070206/55673252-80fc1c00-5873-11e9-8985-bed4127e9afe.jpg)
![20190406_134552](https://user-images.githubusercontent.com/47070206/55673253-80fc1c00-5873-11e9-88ad-c8d1bbc122ce.jpg)

**Comment by Bacon-Ranch** [comment]
> Eat the elephant by pieces. First locate 3,3 + GND.
> It should be GND and 3v3 as in your picture.
> Try to connect if LED light up.
> Got it? Next step.
> Start flash mode ... must both of two LEDs light up.
> Next step.
> Locate TX + RX.
> Try RX and TX on your picture .... try swap TX + RX.
> Still not working.
> Try on rectangle nr 1 second and third from bottom.
> And again try to swap second and third as TX + RX.
> Tell how successfull you are. And be aware about switch 3,3 and GND. If you connect bad gnd to 3,3 and connect TX or RX, you just demage your USB programmer. As I twice :(

was your USB programmer obviously dead? Just wondering if I messed mine up, it is still seen by Windows, powers up, shows a TX light, but is not flashing the Sonoff inching device.

**Comment by scasic** [comment]
> Have same problem. After soft-restart in webui, relay switch 1-0.
> After hard-restart (via power on\off) - no problems, relay stay off

Absolutely the same behavior. Any workaround?

**Comment by ryaske** [comment]
I wanted to reopen this (it can be immediately reclosed) JUST because I know of no other place to post this valuable information, and in my pursuit of the information I found no other place online where it is properly discussed!!

Here is how to flash your PSF-B01. 
NO HARDWARE MODIFICATIONS ARE NECESSARY.
(Note I have the AC/DC 7-32V module and I will be using it as a thermostat override to power on my HVAC fan using sonoff. This should work fine for the other version on this thread too)

Use this pinout; 
<img src="https://user-images.githubusercontent.com/30130742/35114678-d5cfd596-fc85-11e7-843f-998b104571be.png">

<a href="https://www.youtube.com/watch?v=E0WBoFCcnYY">Use this flash boot method</a> (press both buttons while powering it. Both LEDs need to come on.

You can flash Tasmota now.

Once booted, set it to module "1 channel (12)" in the included module list (no external template is needed).

VERY IMPORTANT
SetOption13 1

This will disable the "triple press" functionality that usually reboots ESP8266 into SmartConfig Mode.

After that, you can select via the hardware button if you want inching or locking latch, and you are good to go!

I hope this message saves someone A LOT of time. I took me quite a while to figure out why the module was going haywire.

**Comment by leonraul** [comment]
hi, I have this Relay. Rx and Tx are evident.
 3v3 and Gnd I don't know where they are. Can someone help me? Thanks.

![85A03FA5-FC50-4C7A-A8E9-72B90EF1112B](https://user-images.githubusercontent.com/57762829/68869354-51f73400-06f9-11ea-9cdb-abe14383c3e3.jpeg)

**Comment by ryaske** [comment]
> Can someone help me? Thanks.

LD01-- that is your 3.3 volt regulator. to be absolutely certain I would want to know the labeling on that device so you can verify the pinout, but I am 80% certain that the large metal contact (near label C17) is going to be your 3.3v output.   Grab your multimeter, stick the black lead onto the casing of that USB connector, and probe both that big contact and the little one in the middle of the three. If you get 3.3v , follow that to a convienet place to solder or just connect to the small tab temporarily.

Ground is even easier to find--- again 80% sure that the USB connector casing will be ground across the whole board. However, its better to look at the 4 pin device (near label d6). Again, look at the labeling on it to verify pinout, but that device is going to be your (whatever this board is quoted as handling.... 7-32v DC/AC?) to 5 volt converter/ bridge rectifier). The ground off of there should be the exact same ground that is connected to LD01, once you verify that you can probe the board in continuity mode and find a convenient spot to stick a ground. I would personally just connect to the LD01 appropriate pins since its easy to just tack a wire onto those large pins and remove it after.

Hope this helps!! 

You may also need to get the ESP chip into boot mode, which may require grounding of some of the GPIOs. Try it by just using the GPIO0 button held during boot, first

**Comment by leonraul** [comment]
Thanks! You were really kind. I tried to measure but the multimeter marks zero. The chip is an ESP8285. I'm probably doing something wrong.
![95FB4194-0069-45DE-A919-7D1B6DB05445](https://user-images.githubusercontent.com/57762829/68935198-840ba300-0798-11ea-882e-7aa2df62825e.jpeg)
![Uploading 947073DD-EFB6-4D1A-8755-EC81C9F55416.jpeg…]()

**Comment by ryaske** [comment]
Ok then that may be ground (and I stand corrected!!)  Do you measure any voltage between the usb outer casing and ANY of the three pins? You really have to, or maybe your meter could be broken or not set correctly (or else the board wouldn't power up at all ---- as both the ESP8265 and the LED you see there are powered with 3.3v that originates at that regulator chip--- whether you power the board with USB or with an outside voltage source).

 there MUST be 5v, 3.3v, and ground at those 3 small pins/1 large pin somewhere. Can you make out the labeling on that regulator? If it is AMS1117 its the same chip I use for all my custom made ESP projects..... (and the same one I've seen on sonoffs)

**Comment by ryaske** [comment]
> Thanks! You were really kind. I tried to measure but the multimeter marks zero. The chip is an ESP8285. I'm probably doing something wrong.
> ![95FB4194-0069-45DE-A919-7D1B6DB05445](https://user-images.githubusercontent.com/57762829/68935198-840ba300-0798-11ea-882e-7aa2df62825e.jpeg)

Ok then that may be ground (and I stand corrected!!) Do you measure any voltage between the usb outer casing and ANY of the three pins? You really have to, or maybe your meter could be broken or not set correctly (or else the board wouldn't power up at all ---- as both the ESP8265 and the LED you see there are powered with 3.3v that originates at that regulator chip--- whether you power the board with USB or with an outside voltage source).

there MUST be 5v, 3.3v, and ground at those 3 small pins/1 large pin somewhere. Can you make out the labeling on that regulator? If it is AMS1117 its the same chip I use for all my custom made ESP projects..... (and the same one I've seen on sonoffs)

**Comment by leonraul** [comment]
![circuit](https://user-images.githubusercontent.com/57762829/68979833-f616d300-07fe-11ea-86c8-d9e2da6a954a.jpg)
I confirm! It's an AMS 1117. The GND is pin number 3 of my photo. 
3--->1 =5v
3--->2=3.3v
3--->A=0
3--->B=3.3v
3--->C=0
3--->D=0
3--->E=3.3v
A--->1=5v
A--->2=3.3v
Can I therefore say that A is the GND and B is 3.3v?

**Comment by ryaske** [comment]
Well, 1= 5v, 2= 3.3v and 3= ground. This matches the pinout I posted above (but you are using numbers in reverse, nbd).

With that said, I would be cautious about assuming anything about ABCDE.   Not sure you are certain that one of those is not just "pulled high" by the ESP chip, or if it is actually tied to pin 2. 

What you would do to verify that is either--- break out a bagnifying glass and very carefully follow the traces from the pin #2. Does it go to A B C D or E? 

Yoiu could also flip your multimeter into continuity mode (it either makes a beep or reads 0ohms when both probes are touched together), make sure your board is unpowered, and probe pin 2. Do you get zero ohms to any of the letter pads?    If so, and you can see a trace that goes direct between the two-- only then would I say you are good to use the letter pads. Otherwise, just tack a wire onto pin 2 for your 3.3v+ and pin 3 for your ground. Those we are certain about already!

**Comment by leonraul** [comment]
Ok. I set the multimeter to continuity mode. 
I use the inverted numbering of my photo
A--->3 =Beep  1 and 2 No    
B--->3=Beep 1 and 2 No    
C--->3 =Beep 1 and 2 No    
D--->3=Beep 1 and 2 No    
E--->2 =Beep   1 No   
E--->3=Beep

A= Gnd and E =3,3v?

**Comment by carl689** [comment]
> hi, I have this Relay. Rx and Tx are evident.
> 3v3 and Gnd I don't know where they are. Can someone help me? Thanks.
> 
> ![85A03FA5-FC50-4C7A-A8E9-72B90EF1112B](https://user-images.githubusercontent.com/57762829/68869354-51f73400-06f9-11ea-9cdb-abe14383c3e3.jpeg)

Where you ever able to get this board in flash mode? I for the life of me can't get it to boot in flash mode.

I have tried the button hold down method, and when that didn't work I assumed they aren't connected to GIO0, so I tried grounding what I believe to be the GIO0 pin on the esp itself

**Comment by carl689** [comment]
To the future person googling for this board using the previous mentioned numbering scheme
Ground - A
3.5V     - E
Rx       - TX
Tx       - Rx

Important: To fix flashing being unstable add a capacitor to 2,3

**Comment by istefanpop** [comment]
> To the future person googling for this board using the previous mentioned numbering scheme
> Ground - A
> 3.5V - E
> Rx - TX
> Tx - Rx
> 
> Important: To fix flashing being unstable add a capacitor to 2,3
> 
> Hold down the button closest to the Rx/Tx when you boot up, Tada

Thank you for making me gain valuable time! I installed HAA and currently using one of these as door electric strike relay

**Comment by thienvlkt** [comment]
Thank you for your value information.
Please help me with this board.
I don't know exactly where are Ground, 3v3 and gpio?
![IMG_20191224_170916](https://user-images.githubusercontent.com/12363280/71408730-cebeeb80-2671-11ea-869d-c6542c04cc17.jpg)

**Comment by thienvlkt** [comment]
Hi, can you help me?

**Comment by meingraham** [comment]
@thienvlkt 

Please address this to the [Tasmota Support Discord Chat](https://discord.gg/Ks2Kzd4). The chat is a better and more dynamic channel for helping you. Github issues are best used for Tasmota **_software feature requests and bug reporting_**. Troubleshooting and setup assistance is more effective using an interactive forum.

Please check the [Contributing Guideline and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and the [Support Guide](https://github.com/arendst/Sonoff-Tasmota/blob/development/SUPPORT.md).

Thanks.

### Support Information
See [Wiki](https://tasmota.github.io/docs/#/Home) for more information.
See [Chat](https://discord.gg/Ks2Kzd4) for more user experience.
See [Community](https://groups.google.com/d/forum/sonoffusers) for forum.
See [Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)

**Comment by Denis-tls** [comment]
Indeed, I received the same new version of this Sonoff and was able to flash it with Tasmota, after powering it on while pressing on both buttons. Below the connections:
![Sonoff](https://user-images.githubusercontent.com/59578356/71852387-e1590c00-30d8-11ea-952a-aa3fef892dc9.jpg)

**Comment by tasict** [comment]
> > Last question i hope:
> > Is it possible to set power on state to OFF always? I see that with every restart it turns ON for short time (less than 1sec) before it toggles to OFF. You know, i dont want to have the garage door opened after every restart :)
> 
> Have same problem. After soft-restart in webui, relay switch 1-0.
> After hard-restart (via power on\off) - no problems, relay stay off
Absolutely the same behavior. Any workaround?

**Comment by jeremylee7** [comment]
Anyone figure out the solution to prevent the relay from switching on when performing a soft reset?

I noticed that it also does this behavior when wifi disconnects, this is a big problem

**Comment by blade3609** [comment]
> 
> 
> Indeed, I received the same new version of this Sonoff and was able to flash it with Tasmota, after powering it on while pressing on both buttons. Below the connections:
> ![Sonoff](https://user-images.githubusercontent.com/59578356/71852387-e1590c00-30d8-11ea-952a-aa3fef892dc9.jpg)

Thanks mate! i installed tosmata on my chip also, it looks the same, but the RX and TX were vice versa.

**Comment by foobar26** [comment]
> 
> 
> Indeed, I received the same new version of this Sonoff and was able to flash it with Tasmota, after powering it on while pressing on both buttons. Below the connections:
> ![Sonoff](https://user-images.githubusercontent.com/59578356/71852387-e1590c00-30d8-11ea-952a-aa3fef892dc9.jpg)

Thanks for your info, saved me a lot of time. To make it even easier for others:
- You have to push both buttons during the whole process. I used some clothespins for this.
- Firmware I used was Sonoff basic 6.6. I tried 7.1.2 before but that didn't work and I had to flush again. But maybe I did something wrong.
- Configuration is Sonoff RF.

**Comment by patrikpandolfi** [comment]
Hello guys, i need some help. There's not output tension after relay in my sonoff. I measured with multimeter and nothing chances. Can someone help me? Thanks

**Comment by 2lepus** [comment]
Secondary Pins of the relais don't have any connection. You have to connect any external power to com. This will be switched from NO to NC

**Comment by jhartlep** [comment]
Hi,
I have the same relais as @patrikpandolfi flashed with tasmota.
How can I reset this one without access to the device website?

**Comment by n00bster-za** [comment]
Just want to add some info since I have just flashed my board that is almost the same. My board does not show any LED when in flash mode.  I press 1 button closest to the capacitor and then plug in the usb then let go the button. Unit is in flash mode with now LED on. then I just hold the TX and RX pins to the ESP chip RX TX and then it flashed.

**Comment by napalmz** [comment]
Flashed mine today, powered from USB keeping both button pressed.
A single BLUE led turned on meaning it was in FLASH MODE.
So I just hold TX e RX pin on the flasher and everything went ok!

**Comment by n00bster-za** [comment]
weird mine had no LED going on.  and I know they work because when paring them initially it shows.
