### ISSUE TITLE
Upload Error 255 (espcomm failed)

### ISSUE THREAD

**Issue by chris-008** [arendst/Sonoff-Tasmota#896]
Hi guys,
Pretty new in this scene but with a big eager to learn I started this small homebridge-sonoff tasmota project.
Last step in the whole project is to flash my sonoff devices (material got delivered quite late :-).
I am using an FT232R at 3,3V and the latest Tasmota package V5.7.1. ATOM Platformio to get the softwareflashed on the sonoff device.
After selecting the proper serial monitor, I managed to get the sonoff environment to install with success.
However, the sonoff-NL, -minimal and -ds18x20 are giving Error 255 (espcomm_ failed)
Any idea what I am doing wrong here? Thanks in advance for your kind help!

![schermafbeelding 2017-09-20 om 23 27 10](https://user-images.githubusercontent.com/32146240/30669052-24ec3a3e-9e5d-11e7-8724-dffc77c1ab89.png)

Chris

**Comment by joecotton** [comment]
By default, the PlatformIO settings compile and upload 4 variants on the firmware. See the Wiki for how to select only one:
https://github.com/arendst/Sonoff-Tasmota/wiki/PlatformIO#change-ide-parameters

**Comment by chris-008** [comment]
Hello Joe, thanks a lot for your quick reply... Looking at it now, it makes perfect sense ;-)

**Comment by Kepete** [comment]
I'm experiencing the same error: 

<img width="743" alt="screen shot 2018-01-25 at 15 22 01" src="https://user-images.githubusercontent.com/32489848/35390291-886d7930-01e3-11e8-9d32-6fa5253891ff.png">

I did select only one to upload: 

<img width="671" alt="screen shot 2018-01-25 at 15 23 16" src="https://user-images.githubusercontent.com/32489848/35390334-b3f82460-01e3-11e8-8e8b-be777bb2156c.png">

What am I getting wrong?

**Comment by wizzor** [comment]
I have the same issue, trying to flash the same on Sonoff Touch.

**Comment by robinmanuelthiel** [comment]
Which `upload_speed` are you using? For me, changing it to baud rate 115200 fixed the problem. In `platformio.ini`, I changed line `upload_speed = 512000` to `upload_speed = 115200`.
