### ISSUE TITLE
New user configuration is missing after second flash

### ISSUE THREAD

**Issue by papaiatis** [arendst/Sonoff-Tasmota#899]
I flashed the latest Tasmota firmware to my Sonoff WiFi Relay on Windows 7 with Arduino IDE.
I forgot to update the user_config.h (because it was not mentioned in the Wiki...) so I went back to Arduino IDE and set my SSID and password accordingly then flashed the firmware again.
I connected to the chip with Serial Monitor and I saw that it still tries to connect to the old, default APs: `indebuurt1` and `indebuurt2`. There is no `indebuur` string at all in my entire sketch folder.

What am I doing wrong?

**Comment by papaiatis** [comment]
Figured, I need to change the CFG_HOLDER string in user settings. 
This doesn't seem to be documented as well.

**Comment by davidelang** [comment]
please update the documentation, I don't know how many more places we need to 
put this than where it currently is. If you can add it wherever you looked for 
this, please do.

**Comment by papaiatis** [comment]
It's done. Will update the Wiki wherever I feel the need of it. :)
Thanks.
