### ISSUE TITLE
About Sonoff Control LED Light Belt

### ISSUE THREAD

**Issue by ChienTing** [arendst/Sonoff-Tasmota#900]
I use Sonoff to control the LED light with the control switch  no dimming

There is a slight light when the LED lights are turned off
How to be completely closed
Thank you
![img_3503](https://user-images.githubusercontent.com/26767826/30730323-ad1b56f6-9f98-11e7-9605-d98ba4f30872.JPG)

**Comment by PeggyFree** [comment]
Maybe you switched live and neutral ? Check your cables.

**Comment by ChienTing** [comment]
I changed the phase of the wire after the normal
thank you very much
