### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by NMGAndy** [arendst/Sonoff-Tasmota#901]
Just noticed my 2 sonoff basic devices lost wifi connection to router and created open Access Points. The problem is anybody can connect to the APs and see password of my WIFI network in web page code.
Why it happens?? I know there is a feature to configure WIFI settings this way. I used the feature before by clicking 4 short button clicks. But this time nobody pressed the button.

**Comment by ionciubotaru** [comment]
set `wificonfig 4`

**Comment by NMGAndy** [comment]
I see. Thank you.
A im sure such things should be active by default. It is very surprising that my wifi password shown to everybody.

**Comment by davidelang** [comment]
well, it's shown to everybody who can connect to the device, which either means 
they have physical access to use the serial port, or they are connecting over 
the network, which means that they already have access to your network and the 
wifi password doesn't get them more access.

**Comment by ionciubotaru** [comment]
In production  mode a good practice is to set password to your local mqtt server and to disable web interface.

**Comment by stefanbode** [comment]
Agree. Then serial is the only weak point for outdoor devices. In my mod I disable serial input on seriallog 0. Then it’s getting quite harder to extract information.
