### ISSUE TITLE
Sonoff POW with Tasmota firmware and Domoticz

### ISSUE THREAD

**Issue by Jerby13** [arendst/Sonoff-Tasmota#903]
I have flashed the Sonoff POW with Tasmota V5.6.1k and it's working great with Domoticz, type Electric (Instant + Counter). This way I can measure Energy and Power usage in Domoticz. But how can I measure the Voltage, Current and PowerFactor in Domoticz which are also available on MQTT server? I cannot configure other idx sensors in Tasmota POW.

**Comment by arendst** [comment]
Will consider

**Comment by PeggyFree** [comment]
I am interested by this request too.

**Comment by Jerby13** [comment]
Mr Arendst,
Excellent what a fast service, A and V are working perfect. I'm very impressed about the implementation and options that are build-in to Tasmota and can be configured online. Thanks a lot.

**Comment by PeggyFree** [comment]
Where do you check V and A in domoticz ? I just see power.

**Comment by arendst** [comment]
1 - Domoticz > Setup > Hardware
2 - Virtual Sensors > Create Virtual Sensors
3 - Current: Select Sensor Type Ampere (1 Phase)
4 - Voltage: Select Sensor Type Voltage
