### ISSUE TITLE
Change wifi SSID

### ISSUE THREAD

**Issue by dendrees** [arendst/Sonoff-Tasmota#904]
How can I easily change the SSID of my Sonoff devices?
Is the web part working fine or do I need to use the command line for this?

**Comment by jetema** [comment]
An easy way is via http, from  console, see wifi commands on 
 https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#wifi

**Comment by dendrees** [comment]
Ok I saw that so it will be: SSId / name ssid

**Comment by davidelang** [comment]
you can do this via the web interface or the command line
