### ISSUE TITLE
BN-SZ01 110V

### ISSUE THREAD

**Issue by rajil** [arendst/Sonoff-Tasmota#914]
Hello,

I have tested BN-SZ01 with 220V and it works well with MQTT (flashed used SonOTA). However, i would like to use it with 110V. The LED's do come on when connected to 110V, there is no DHCP request from the Sonoff device. I have seen a [report) [https://captain-slow.dk/2017/04/10/itead-bn-sz01-wifi-round-flush-mount-led-ceiling-light-part-2-hacking-it/#comment-12737] that it should work with 110V. 

Is it possible to make it to work with Tasmota?
Thanks

**Comment by davidelang** [comment]
that sounds as if the chip isn't getting proper power. check the voltage and 
I'll bet that you find that the 3.3v pins are under 3.3v, and as a result the 
esp8266 is not running.

this is not a software issue, it's strictly a hardware problem.
