### ISSUE TITLE
Remove retained messages 

### ISSUE THREAD

**Issue by arun2118** [arendst/Sonoff-Tasmota#916]
How can i remove the retained messages(LWT) from reappearing on my broker (cloudmqtt)? A sonoff im not using is still showing offline.

**Comment by davidelang** [comment]
see the wiki page on poweronstate it includes directions for finding and 
removing such messages

**Comment by arun2118** [comment]
Its saying write "mosquitto_sub -p 1883 -u <username> -P <password> -t cmnd/+/power" to check the messages, but where do i do this? console? its asking for Mqtt host username and pass? If the topic i get back is "tele/sonoff3/LWT" i replace power(in the example) with tele?

**Comment by davidelang** [comment]
On Sun, 24 Sep 2017, arun2118 wrote:

> Its saying write "mosquitto_sub -p 1883 -u <username> -P <password> -t cmnd/+/power" to check the messages, but where do i do this? console?

at the command line ofthe server your mqtt service is running on (or you would 
have to addapara meter to tell it what host to connect to)

> its asking for Mqtt host username and pass?

ifyou have one set, otherwise ship those parameters

> If the topic i get back is "tele/sonoff3/LWT" i replace power(in the example) with tele?

yes

**Comment by arun2118** [comment]
"mosquitto_sub -p 19830 -u ha -P ahat8 -t cmnd/+/tele" returns nothing in cloudmqtt console.  ha being mqtt broker and ahat8 being pass word
