### ISSUE TITLE
Enhancement request: reset command on MQTT

### ISSUE THREAD

**Issue by albukrek** [arendst/Sonoff-Tasmota#924]
From time to time, mainly because of resetting the router the site is not available, but the MQTT is  active. In this case it would be very useful to have an MQTT command to rest the sonoff.

**Comment by ionciubotaru** [comment]
Reset | 1 | Reset sonoff parameters to user_config.h values and restart
Reset | 2 | Erase flash, reset sonoff parameters to user_config.h values and restart
Restart | 1 | Restart sonoff
Restart | 99 | Force restart sonoff without config save

**Comment by albukrek** [comment]
Thanks ionciubotaru,
How can I send a Restart | 1 | command using MQTT?
What is the syntax?
