### ISSUE TITLE
Sonoff LED turn off fade

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#925]
I have enabled fade and it works when turning on, but when turning off it does not work.
Is it by design?

what is the difference of fade and wakeup?

**Comment by arendst** [comment]
Turning off without fading is as designed.

Wakeup allows for light turning on over a longer period like some minutes.

**Comment by ageorgios** [comment]
It would be cool if it had the option for fade to turn off too!
