### ISSUE TITLE
IR Receiver?

### ISSUE THREAD

**Issue by lgnd33** [arendst/Sonoff-Tasmota#939]
Does it make sense to implement an IR Receiver?
 
I have a board that has one soldered and ready at GPIO04 (board is "MagicHome LED strip controller"... has a IR variant that comes with cheap IR remote, but codes are really easy to pick up using already included IRremote library).

I don't need it (at least not for now ;) so I can just ignore it, but I figured someone might have a use-case for picking up IR codes and sending them over MQTT - maybe your LED strip controller is close to the TV and you'd like to pick up that "switch source - CATV" on TV remote to dim the lights or something... 

I wouldn't go as far as to implement IR code interpreter in Sonoff-Tasmota - I'd just pick whatever IR code shows up on the IRreceiver and send it off to MQTT for actual interpretation / processing. 

@arendst - it's a nice exercise for me, but don't want to waste space on code nobody is going to use. What's your take?

**Comment by davidelang** [comment]
I would like to see that, it seems like a very useful feature to complement the 
IR transmitter.

**Comment by arendst** [comment]
@lgnd33 Lazar nice idea and if you manage to keep it's code footprint small it could be integrated with Tasmota. As you stated correctly let the interpretation and processing being done elsewhere.

Give it a try!

**Comment by lgnd33** [comment]
Just to check - new GPIO functionality is added to the end of the upins_t, not to cause backward compatibility issues?

**Comment by arendst** [comment]
Correct.

**Comment by gnkarn** [comment]
im , very interested on this , as i need to sense codes from my alarm system, and the IRreceive code is perfect for this ( even  when the code is not coming from IR) .Would like to know if there was any progress , before starting my own branch , tks
