### ISSUE TITLE
Disable  USE_IR_REMOTE via user_config_override.h

### ISSUE THREAD

**Issue by 0n3-70uch** [arendst/Sonoff-Tasmota#94]
Hello,

Is it possible to disable this option:
`#define USE_IR_REMOTE`

Via the user_config_override.h ? Because I do not need the IR Remote function and so I can skip the installation of the IR library. But at the moment I need to uncomment the option in the user_config.h.

This would be nice:
`#define USE_IR_REMOTE 0`

Greetings
Fabi

**Comment by MacWyznawca** [comment]
You can try:
#ifdef USE_IR_REMOTE
#undef USE_IR_REMOTE
#endif

**Comment by 0n3-70uch** [comment]
Hi, that's easy... Thanks for your help.
