### ISSUE TITLE
PWM pins RGB LED better support

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#941]
Are there any plans for better implementing RGB leds that rely on PWM pins?

It would be really great if the commands matched the Sonoff Led

**Comment by arendst** [comment]
Will be in next (pre)release. 

It will also disable direct PWM control for H801 and MagicHome as it is then under control of commands Color and Dimmer.

**Comment by nosaj66au** [comment]
Hi Arends,
   Would be great if we could name or title the channels and not have them a just RGB,W1,W2. I'm using one H801 per room giving me dimming control of 5 (24vdc) LED downlights. I using a spare GPIO as the switch like a normal sonoff. This either turns the LEDs off / Returns to last dimmer or went held 5 sec brings LEDs to full brightness. I guess there could be a heap of other options.
What do you think?
Jason

**Comment by lgnd33** [comment]
I started working on similar code - are you refactoring xdrv_sfl? 
Can you share the idea, maybe we can split?

//_

**Comment by arendst** [comment]
I think the PWM code is complete as implemented in xdrv_snfled.ino. 

Your IR code could go into xdrv_ir_send.ino. If need be I will transfer to other parts if you have something working.

**Comment by lgnd33** [comment]
I was referring to adding color handling to MagicHome module and
refactoring xdrv_snfled to allow more than 2 direct PWM channels.

Looked at that - seems current code depends on the snf_flg to determine
number of channels and assumes that 1 or 2 channels are direct PWM, while 4
and 5 channels are controller via My92x1.
I was thinking of changing the code to:
- keep 5 component color code independent of the hardware implementation
and use functions like dim, animate (transition) and rgb2hsb on it.
- calculate PWM out of generic color model.
- have a separate per-board configuration for determining controller method
(direct PWM, WS2812, My92x1 or maybe something else if they come up with it)

If you're shooting in a same direction, maybe we can split the work...

**Comment by arendst** [comment]
It's already there in the version released today. Just select MagicHome and you have full color control.

In fact any pwm controlled device can now be controlled that way once you enable this feature with command SetOption15 1

Further action will make the code too big while adding minor progression.

See releasenotes regarding correct pwm gpio selection.

**Comment by lgnd33** [comment]
OK, just pulled latest version and see that you expanded the meaning of the
snf_flg, which solves some issues.
Let me check the rest of the code and see if anything's missing.
