### ISSUE TITLE
HW watchdog reset in 5.8.0b

### ISSUE THREAD

**Issue by WoodsterDK** [arendst/Sonoff-Tasmota#942]
Hi,
I have seen several HW watchdog resets, latest in the 5.8.0b version.
Any ideas?

**Comment by arendst** [comment]
Provide output of command status 0.
On what hardware do you get it.

**Comment by WoodsterDK** [comment]
Its on a Sonoff basic....

**Comment by WoodsterDK** [comment]
Hi there, 
it actually might be a hardware problem - just flashed a new Sonoff Basic - let's see how it performs.
