### ISSUE TITLE
Sonoff RF goes to defaults once RF button is pressed for a long time

### ISSUE THREAD

**Issue by foxel** [arendst/Sonoff-Tasmota#954]
Hi.

My issue is as follows:
My child pressed and held down remote button for about 10 seconds and then module became inaccessible.

I've investigated the issue and it looks like the problem is some firmware reset cycle being driven by long press.
```
00:02:33 MQTT: stat/sonoff/RESULT = {"Reset":"Reset and Restarting"}
00:02:33 Cnfg: Use defaults
00:02:40 SYSL: Syslog Host not found so logging disabled for 600 seconds. Consider syslog 0
```

I think for RF module this cycle should be something different since schematics of RF is pretty funny and pressing RF button seems to be equivalent to pressing body button.

**Comment by arendst** [comment]
Play with commands SetOption1 0/1 and SetOption13 0/1. See Wiki.

**Comment by foxel** [comment]
@arendst thanks!

SetOption1 works like a charm!
