### ISSUE TITLE
PWM level at startup

### ISSUE THREAD

**Issue by emontnemery** [arendst/Sonoff-Tasmota#955]
I'm using the Sonoff BN-SZ configuration.
Values from sysCfg.power and sysCfg.led_dimmer are shown in UI and sent to MQTT, however PWM level itself is not initiated.

Edit:
Some more details.
With sysCfg.poweronstate = 0:
UI matches system state after a cold boot.
UI does not match system state after a restart since resetInfo.reason is neither REASON_DEFAULT_RST nor REASON_EXT_SYS_RST.
Even though GPIOs might be untouched, PWM is probably stopped and should be reinitiated?

With sysCfg.poweronstate = 3, but sysCfg.flag.savestate = 0:
UI does not match system state if there are some saved values in sysCfg.power and sysCfg.led_dimmer

**Comment by arendst** [comment]
As you rightfully suggested setting sl_any to 1 should handle the first situation.

The last situation will be implemented as that all saved power will be set to Off once SaveState (SetOption0) is set to 0 resolving the situation of saved value miscompare. Dimmer will still be saved as it is always the current dimmer value (Although power is Off dimmer value can still be set and will be used as the last dimmer value when powered on).

Both changes will be in next (pre)release.
