### ISSUE TITLE
Did someone tried using Geekcreit modules?

### ISSUE THREAD

**Issue by untitledlt** [arendst/Sonoff-Tasmota#963]
Banggood is selling quite similar modules made by Geekcreit. 
f.e. https://www.banggood.com/Geekcreit-USB-5V-Or-AC-55V-220V-Four-Channel-Jog-Inching-WIFI-Wireless-Smart-Switch-p-1159786.html?rmmds=search

Looks like Sonoff clones and/or somehow related to Sonoff. Did someone tried to flash them with Sonoff-Tasmota firmware? If pinout is the same, it should work i guess. 
Otherwise maybe developers could add support for those modules?

**Comment by rankerson** [comment]
Hy untitledlt,

I tried it already by soldering and OTA without success; see my request/ question concerning this:
https://github.com/arendst/Sonoff-Tasmota/issues/1520

Cheers
Sascha
