### ISSUE TITLE
no MQTT services found?

### ISSUE THREAD

**Issue by chris-008** [arendst/Sonoff-Tasmota#966]
good evening,
Being new in this scene, I have been struggling the last past nights with the final step on how to get the sonoff module to work  on an orange pi zero with MQTT broker.

Unfortunately no MQTT services found...
Typical output on the Sonoff console:
![schermafbeelding 2017-10-05 om 00 11 47](https://user-images.githubusercontent.com/32146240/31202187-f03709e4-a961-11e7-98af-29c7b19093b4.png)

MQTT broker is working though:
![schermafbeelding 2017-10-05 om 00 16 18](https://user-images.githubusercontent.com/32146240/31202332-7ad4be7a-a962-11e7-8f29-cfc21893908f.png)

Accessories are installed, working on homebridge   and properly configured:

![schermafbeelding 2017-10-05 om 00 21 34](https://user-images.githubusercontent.com/32146240/31202553-5e1851b0-a963-11e7-824c-ca4d8d4be787.png)

![schermafbeelding 2017-10-05 om 00 19 32](https://user-images.githubusercontent.com/32146240/31202447-f2cdf4e6-a962-11e7-8054-dfd270450d29.png)
 
the swich is also recognized on the iOS Home app.
but switching doesn't fysically work due to the above MQTT problems.

Anyone who can help me with this one?
Thanks in advance!

**Comment by chris-008** [comment]
Portmapping on my BBox3 router is also done:
![schermafbeelding 2017-10-05 om 00 29 05](https://user-images.githubusercontent.com/32146240/31202777-4ba1a256-a964-11e7-86cf-f914fefe950b.png)

**Comment by chris-008** [comment]
could it be that the MQTT part in the user_config.h file has to be modified and reflashed? cause that part has been left untouched so far...
![schermafbeelding 2017-10-05 om 00 33 59](https://user-images.githubusercontent.com/32146240/31202928-09eea9a2-a965-11e7-8ade-48943ddff00d.png)

**Comment by davidelang** [comment]
connect to the device and see what's configured.

Enable more detailed logging and see what it reports that it's doing.

The problem is probably that the config is not what you think it is (see the 
troubleshooting page)

**Comment by chris-008** [comment]
Hello, thanks for your quick reply.
I went through the troubleshooting but did'nt find an issue which is directly related to mine.

Could you inform me on how to get the detailled logging?
Perhaps the  "troubleshooting tools->logs/ syslogs" part?

Should i leave the MQTT par tin the conf file untouched or does it have to be modified accordingly?
(in the different tutorials I found on youtube, it was not mentioned to modify this section though)

**Comment by jeylites** [comment]
@chris-008 

Check your MQTT Host on Tasmota, it needs to be the same URL as the broker. 
example:
![screen shot 2017-10-05 at 10 08 21 pm](https://user-images.githubusercontent.com/9190080/31231601-ef7c0752-a9ac-11e7-859e-2237486e3a5e.png)


@davidelang 

Little off topic but thought will ask here anyway. 

Is it possible to give a nonstatic IP for  MQTT Host on TASMOTA? Can it still find the broker that way?

The reason I'm asking is I'm unable to give a static IP to my Raspberry Pi running MQTT Broker / homebridge because it fails to reconnect after the internet drops out, with DHCP somehow it connects automatically. Very strange and it seems to be a common problem with these PI. There is a few fix out there but I have yet to look into it.

**Comment by chris-008** [comment]
Thanks for our help.
MQTT host IP is same as the Pi's:
![schermafbeelding 2017-10-05 om 20 55 11](https://user-images.githubusercontent.com/32146240/31247009-8cbd2f66-aa0f-11e7-821f-ed7ad546fbf4.png)

I use a username and PW which is also filled in.

**Comment by davidelang** [comment]
On Thu, 5 Oct 2017, chris-008 wrote:

> I went through the troubleshooting but did'nt find an issue which is directly related to mine.

see the section 'config problems'

**Comment by chris-008** [comment]
Going through the whole Wiki from scratch now...
while trying some more option, i enabled a web password with a known password. When i try to go the sonoff module's IP, I get a verification requirement. Which username should I use here? And is there a way to delete this?

**Comment by chris-008** [comment]
reflashing didn't help...

**Comment by chris-008** [comment]
ok...note to myself...go through the wiki first, ask later ;-)
After weeks of trying I think I wanted a short cut as I was getting clos to giving up.
but appreciated that you showed me the way!
 
For anyone who ran into this issue:
user_config_h has to be filled in including MQTT parameters.
I made the mistake following a youtube tutorial where this part wasn't mentioned.

Regarding the web password issue: holding ground pin for 4 secs did the trick.

Thanks again for your help guys!
