### ISSUE TITLE
Request: SHT11 support

### ISSUE THREAD

**Issue by bluebird11** [arendst/Sonoff-Tasmota#97]
SHT11 is a popular temperature and relative humidity sensor featuring better accuracy than DHT22. Any chance you could add support for it?

There already exist some implementations for ESP8266, e.g. in ESPEasy and in espweather.

**Comment by davidelang** [comment]
it's probably useful to point at an existing implementation (assuming the licenses are compatible)

**Comment by bluebird11** [comment]
The implementation can be found in the aforementioned projects (both GNU license):

https://github.com/MalteP/espweather/blob/master/firmware/user/sht1x.c
https://github.com/letscontrolit/ESPEasy/blob/master/_P031_SHT1X.ino

I would be happy to be a beta tester.

**Comment by arendst** [comment]
I won't support the SHT11. It's using two wires and needs special code to drive it. 

With two wires I support I2C and the excellent HTU21 temp/hum sensor.
