### ISSUE TITLE
sonoff basic Inching /Self-Locking 

### ISSUE THREAD

**Issue by marcgrc** [arendst/Sonoff-Tasmota#978]
Hello to all.
Does anyone know if the sonoff basic with firmware tasmota  can be timed?
for example, is it only active until I press the button or
turns on after two seconds it goes off?
thank you

**Comment by davidelang** [comment]
see the pulsetime command on the wiki commands page

**Comment by marcgrc** [comment]
wher is wiki commands page ??

**Comment by marcgrc** [comment]
Sorry 
Where is wiki commands page??

**Comment by marcgrc** [comment]
ok found
Take an example of what to change to get a 2 second impulse and then unplug it
please
Thank you very mutch

**Comment by davidelang** [comment]
to to the tasmota github repository, and at the top of the page there is a link 
to the wiki (one of the tabs), along the right side of the wiki are links to the 
most significant pages, one of those is the commands that can be understood by 
tasmota.

**Comment by vdhub** [comment]
Hello, I just got an Sonoff SV and I need same as marcgrc said, I need it to act like temporary push button, I start it and after 2 seconds it switches off, ITEAD have this in their app but I want to use it outside the app. 

How can I do that. ?

Thanks

**Comment by ascillato** [comment]
Yes, in Tasmota console use command pulsetime
