### ISSUE TITLE
problem tasmota error

### ISSUE THREAD

**Issue by vchecco84** [arendst/Sonoff-Tasmota#979]
Hello guys. sorry for my english (google translator).
congratulations to all the projects.

I tried to upgrade to "TASMOTA" of a ch4 pro

but I got this error and now it does not work anymore.

what can I do?

I followed your guide on youtube

please help me
![schermata 2017-10-06 alle 18 19 42](https://user-images.githubusercontent.com/32576949/31287848-032e92d0-aac3-11e7-9ddc-86071b7264aa.png)

**Comment by jeylites** [comment]
have you looked into the TX RX connections? & GPIO to ground?
