### ISSUE TITLE
cant flash sonoff 4ch

### ISSUE THREAD

**Issue by rayzor666** [arendst/Sonoff-Tasmota#98]
hi im tryoing to flash a 4ch with no luck.. im getting error "sonoff.ino:144:75: fatal error: ArduinoJson.h: No such file or directory" with ArduinoIDE, with Atom it will flash but the device is useless... can someone pls help with any method of flashing... thanks

**Comment by lucwuyts** [comment]
1. in ArduinoIDE - Sketch - Include Library - Manage Libraries -> add the arduinoJson library.
2. Set the board to "Generic ESP8285 module"
3. Flash size:  1M (64K SPIFFS)
4. And the correct comm port.

This should do it.

PS: During flashing i could not power the board from the serial interface, so i power it now with a 3V battery during flash.

**Comment by rayzor666** [comment]
thanks for that now im getting "xdrv_ir_send.ino:31:29: fatal error: IRremoteESP8266.h: No such file or directory" any idea how to fix this

**Comment by lucwuyts** [comment]
This is explained on this page:
https://github.com/arendst/Sonoff-Tasmota/wiki/Prerequisite

**Comment by rayzor666** [comment]
Thank you very much for your help.... I took a step back, read the wiki properly and started again... All working great
