### ISSUE TITLE
Color API result is different

### ISSUE THREAD

**Issue by ageorgios** [arendst/Sonoff-Tasmota#982]
![screen shot 2017-10-06 at 22 04 46](https://user-images.githubusercontent.com/3126351/31294137-7216856c-aae2-11e7-8411-a874ca12f1f3.png)
![screen shot 2017-10-06 at 22 05 53](https://user-images.githubusercontent.com/3126351/31294165-90509356-aae2-11e7-9db8-45cbb269dbff.png)
Is this normal?

**Comment by arendst** [comment]
Yes.
To be able to use a dimmer range of 0 to 100 I have to re-calculate the colors to 1/100 of their requested value.
That's why you see the dimmer value also changes when a color is provided. The same is true when you provide a dimmer value; color will (and needs) be re-calculated
