### ISSUE TITLE
No answer to MQTT cmnd

### ISSUE THREAD

**Issue by DetlefR** [arendst/Sonoff-Tasmota#986]
Hello,
I use Sonoff-Tasmota in version 5.7.0b. My problem, if I send a command via mqtt (mytouch/cmnd/POWER on) the command is executet but I do not get a "stat" answer. The "stat" mqtt message is send after restart, toggle button on website or as result of a web command.
Any idea.

Thanks for answers.

**Comment by davidelang** [comment]
set logging to 'more debugging' and see what's logged when you send this command

note that you are using non-standard mqtt messages, so that could be part of the 
problem

**Comment by DetlefR** [comment]
Hello,

I have set the full topic again. Now it works. 

Thanks for your answer.
