### ISSUE TITLE
DHT22 on 5.8.0 not working

### ISSUE THREAD

**Issue by mr-const** [arendst/Sonoff-Tasmota#988]
I found out, that on clean installation of a 5.8.0 (and possibly 5.7.1) version, DHT22 sensor doesn't work, or works rarely (perhaps once in 5-10 minutes). Debug log contains `Timeout waiting for start signal low pulse` only.
However after rollback to 5.7.0, `reset 2`, reconfiguration, everything works as expected.

Upgrade from 5.7.0 to 5.8.0 works as expected, DHT22 works.
Tested on Wemos D1 mini and Sonoff Basic.

**Comment by stefanbode** [comment]
I have the same issue right now and try to find out what is happening. with weblog 5 I did not see any message related to what you have reported. For me it did not work currently. reset 2 cause a Blocked Loop from webconsole. Therefore I have to figure out what is wrong.

**Comment by ritschard** [comment]
Same issue. Finally found this issue after few days of thinking I'm going 🔩 😆

**Comment by arendst** [comment]
See #1082

**Comment by arendst** [comment]
Implemented in master release v5.9.0
