### ISSUE TITLE
Virtual relay and real relay - inconsistent status RESULT

### ISSUE THREAD

**Issue by KPK75** [arendst/Sonoff-Tasmota#989]
When you use a module with "color" commands it uses "virtual" relay to control the LED power. And when you add a "real" relay this virtual relay it is always last. But color command gives result:
```
21:37:05 CMD: color ffffff
21:37:05 MQT: stat/sonoff12/RESULT = {"POWER":"ON", "Dimmer":100, "Color":"FFFFFF"}
```
when it should be POWERx when used with additional relays.

**Comment by arendst** [comment]
Implemented in master release v5.9.0
