### ISSUE TITLE
How does sonoff hue emulation exactly work?

### ISSUE THREAD

**Issue by unf0rg0tt3n** [arendst/Sonoff-Tasmota#994]
Hi,

Hoe does the sonoff hue emulation work exactly?
What do I need to setup a light in colors, what is supported?

For example, I have a Ikea Tradfri light with colors.
When I hook this up, can I modify the colors to my need by just using the Hue emulation?

Is there any documentation for this?

Regards,

**Comment by arendst** [comment]
Ikea Tradfri light supports Hue by itself. It does not need Sonoff Tasmota.

You'll need a Ikea or Philips Hue bridge to control the Ikea light.

**Comment by unf0rg0tt3n** [comment]
Hi,

Thanks for your reply. But this is an example. I'd wanted to know how it actually works, this hue emulation.

**Comment by nunoronconcouto** [comment]
Me too...

Thanks
