### ISSUE TITLE
Default behavior at power on

### ISSUE THREAD

**Issue by sken79** [arendst/Sonoff-Tasmota#998]
It would be nice to have an.option to set the default switch status when sonoff is powered. e.g. ON, OFF, previous state(?)

**Comment by lgnd33** [comment]
Have you looked at SetOption0 command?
https://github.com/arendst/Sonoff-Tasmota/wiki/Commands#management

**Comment by davidelang** [comment]
see poweronstate

**Comment by sken79** [comment]
Thank you!
L
